var Localization_favoritesAppDict_tr_TR = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radyo",
    "storeRadioFavorite" : "{frequency} Ekle",
    "moveFavorite" : "Taşı",
    "deleteFavorite" : "Sil",
    "addEditRadioFavorite" : "Favori Radyo Ekle/Düzenle",
    "maxCommFavorites" : "Maksimum favori İletişim sayısına ulaştınız.",
    "maxRadioFavorites" : "Maksimum favori Radyo sayısına ulaştınız.",
    "maxNavFavorites" : "Maksimum favori Navigasyon sayısına ulaştınız.",
    "replaceButtonText" : "Değiştir",
    "replaceExistingFavorite" : "Birini değiştirmek ister misiniz?",
    "selectFavoriteToReplace" : "Değiştirilecek Favoriyi Seçin",
    "dialogBackButton" : "Geri",
    "selectFavoriteToMove" : "Taşınacak Favoriyi Seçin",
    "selectFavoriteToDelete" : "Silinecek Favoriyi Seçin",
    "deleteConfirmation" : "Favori {name} silinmesini istediğinizden emin misiniz?",
    "selectPosition" : "Konum Seçin",
    "selectContactDetailsTitle" : "{name} Bilgilerini seçin",
    "addEditFavoritesCommTitle" : "İletişim",
    "addNewContact" : "Yeni Bağlantı Ekle",
    "addNewContactDetails" : "Yeni Bağlantı Bilgileri Ekle",
    "renameFavorite" : "Yeniden Adlandır",
    "selectContactTitle" : "Bir Bağlantı seçin",
    "selectFavoriteToRename" : "Yeniden Adlandırılacak Favoriyi Seçin",
    "addEditFavoritesNaviTitle" : "Navigasyon",
    "storeCurrentLocation" : "Güncel Konum Ekle",
    "storeCurrentDestination" : "Güncel Hedef Ekle",
    "addFromContact" : "Bağlantıdan Ekle",
    "appTitle" : "Favoriler",
    "renameFavoriteTitle" : "{name} için, yeniden adlandır:",
    "FavoriteAlreadyAvailable" : "Favori Zaten Mevcut",
    "FavoriteAdded" : "Favori Eklendi",
    "addEditCommFavorite" : "Favori İletişim Ekle/Düzenle",
    "addEditNaviFavorite" : "Favori Navigasyon Ekle/Düzenle",
    "replacewithRadioStation" : "{frequency} ile değiştir",
    "replaceWithContact" : "Bağlantı ile değiştir",
    "replaceWithContactDetail" : "Bağlantı Bilgisiyle Değiştir",
    "replaceWithCurrentLocation" : "Mevcut Konumla Değiştir",
    "replaceWithCurrentDestination" : "Mevcut Hedefle Değiştir",
    "replaceWithAddress" : "Bağlantılardaki Adresle Değiştir",
    "phoneNumberCategoryMobile" : "Cep Telefonu:",
    "phoneNumberCategoryHome" : "Ev Telefonu:",
    "phoneNumberCategoryWork" : "İş Telefonu:",
    "phoneNumberCategoryOther" : "Diğer:",
    "phoneNumberCategoryAddress" : "Adres:",
    "selectContactNaviDetailsTitle" : "{name} adresini seçin",
    "GPSlocation" : "Mevcut konum bilinmiyor",
    "PhoneConnectionLost" : "Telefon Bağlantısı Kesildi",
    "Home" : "Ev Telefonu",
    "InvalidAddress" : "Adres geçersiz",
    "FavoriteUpdated" : "Favori Güncellendi",
    "UnsetHome" : "Evi Sil",
    "DeleteHome" : "Ev Konumu temizlendi",
    "EditHome" : "Evi Düzenle",
    "deleteHomeConfirmation" : "Ev konumunu silmek istediğinizden emin misiniz?",
};

framework.registerAppDictLoaded("favorites", "tr_TR");