var Localization_favoritesAppDict_ro_RO = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Adăugare {frequency}",
    "moveFavorite" : "Mutare",
    "deleteFavorite" : "Ştergere",
    "addEditRadioFavorite" : "Adăugare/editare favorit radio",
    "maxCommFavorites" : "Aţi atins numărul maxim de favorite la comunicare.",
    "maxRadioFavorites" : "Aţi atins numărul maxim de favorite la radio.",
    "maxNavFavorites" : "Aţi atins numărul maxim de favorite la navigare.",
    "replaceButtonText" : "Înlocuire",
    "replaceExistingFavorite" : "Doriţi să înlocuiţi unul?",
    "selectFavoriteToReplace" : "Selectaţi un favorit de înlocuit",
    "dialogBackButton" : "Înapoi",
    "selectFavoriteToMove" : "Selectaţi un favorit de mutat",
    "selectFavoriteToDelete" : "Selectaţi un favorit de şters",
    "deleteConfirmation" : "Sigur doriţi să ştergeţi favorita {name}?",
    "selectPosition" : "Selectaţi poziţia",
    "selectContactDetailsTitle" : "Selectaţi detalii {name}",
    "addEditFavoritesCommTitle" : "Comunicare",
    "addNewContact" : "Adăugare contact nou",
    "addNewContactDetails" : "Adăugare date contact nou",
    "renameFavorite" : "Redenumire",
    "selectContactTitle" : "Selectaţi un contact",
    "selectFavoriteToRename" : "Selectaţi un favorit de redenumit",
    "addEditFavoritesNaviTitle" : "Navigaţie",
    "storeCurrentLocation" : "Adăugare locaţie curentă",
    "storeCurrentDestination" : "Adăugare destinaţie curentă",
    "addFromContact" : "Adăugare din contacte",
    "appTitle" : "Favorite",
    "renameFavoriteTitle" : "Redenumire {name} în:",
    "FavoriteAlreadyAvailable" : "Favoritul este deja disponibil",
    "FavoriteAdded" : "Favorit adăugat",
    "addEditCommFavorite" : "Adăugare/editare favorit comunicare",
    "addEditNaviFavorite" : "Adăugare/editare favorit navigaţie",
    "replacewithRadioStation" : "Înlocuire cu {frequency}",
    "replaceWithContact" : "Înlocuire cu Contact",
    "replaceWithContactDetail" : "Înlocuire cu detaliu contact",
    "replaceWithCurrentLocation" : "Înlocuire cu locul curent",
    "replaceWithCurrentDestination" : "Înlocuire cu destinaţia curentă",
    "replaceWithAddress" : "Înlocuire cu adresă din contacte",
    "phoneNumberCategoryMobile" : "Mobil:",
    "phoneNumberCategoryHome" : "Acasă:",
    "phoneNumberCategoryWork" : "Serviciu:",
    "phoneNumberCategoryOther" : "Altul:",
    "phoneNumberCategoryAddress" : "Adresă:",
    "selectContactNaviDetailsTitle" : "Selectaţi adresa {name}",
    "GPSlocation" : "Locaţia actuală este necunoscută",
    "PhoneConnectionLost" : "Conexiune tel. întreruptă",
    "Home" : "Acasă",
    "InvalidAddress" : "Adresa nu este validă.",
    "FavoriteUpdated" : "Favorită actualizată",
    "UnsetHome" : "Ştergeţi Baza",
    "DeleteHome" : "Locaţie Home ştearsă",
    "EditHome" : "Editare Home",
    "deleteHomeConfirmation" : "Sunteţi sigur că doriţi să ştergeţi locaţia Bazei?",
};

framework.registerAppDictLoaded("favorites", "ro_RO");