var Localization_favoritesAppDict_ja_JP = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "FM/AM",
    "storeRadioFavorite" : "{frequency} を登録",
    "moveFavorite" : "移動",
    "deleteFavorite" : "削除",
    "addEditRadioFavorite" : "追加/編集",
    "maxCommFavorites" : "お気に入り登録数が上限に達しました。",
    "maxRadioFavorites" : "お気に入り登録数が上限に達しました。",
    "maxNavFavorites" : "お気に入り登録数が上限に達しました。",
    "replaceButtonText" : "上書き",
    "replaceExistingFavorite" : "上書きしてもよろしいですか?",
    "selectFavoriteToReplace" : "上書きする項目を選択してください。",
    "dialogBackButton" : "戻る",
    "selectFavoriteToMove" : "移動する項目を選択してください。",
    "selectFavoriteToDelete" : "削除する項目選択してください。",
    "deleteConfirmation" : "{name} を削除してもよろしいですか？",
    "selectPosition" : "移動先を選択してください。",
    "selectContactDetailsTitle" : "{name}の詳細を選択してください。",
    "addEditFavoritesCommTitle" : "Communication",
    "addNewContact" : "連絡先を登録",
    "addNewContactDetails" : "電話番号を登録",
    "renameFavorite" : "名前の編集",
    "selectContactTitle" : "連絡先を選択",
    "selectFavoriteToRename" : "編集する項目を選択してください",
    "addEditFavoritesNaviTitle" : "Navigation",
    "storeCurrentLocation" : "現在地を登録",
    "storeCurrentDestination" : "目的地を登録",
    "addFromContact" : "連絡先から登録",
    "appTitle" : "お気に入り",
    "renameFavoriteTitle" : "{name}を編集",
    "FavoriteAlreadyAvailable" : "既に登録されています。",
    "FavoriteAdded" : "登録されました。",
    "addEditCommFavorite" : "追加/編集",
    "addEditNaviFavorite" : "追加/編集",
    "replacewithRadioStation" : "{frequency} を登録",
    "replaceWithContact" : "連絡先を登録",
    "replaceWithContactDetail" : "電話番号を登録",
    "replaceWithCurrentLocation" : "現在地を登録",
    "replaceWithCurrentDestination" : "目的地を登録",
    "replaceWithAddress" : "連絡先から登録",
    "phoneNumberCategoryMobile" : "携帯 : ",
    "phoneNumberCategoryHome" : "自宅 : ",
    "phoneNumberCategoryWork" : "会社 : ",
    "phoneNumberCategoryOther" : "その他 : ",
    "phoneNumberCategoryAddress" : "住所 : ",
    "selectContactNaviDetailsTitle" : "{name}の住所を選択してください。",
    "GPSlocation" : "現在地を特定できません。",
    "PhoneConnectionLost" : "Bluetooth Phone Connection Lost",
    "Home" : "自宅",
    "InvalidAddress" : "住所が見つかりませんでした。",
    "FavoriteUpdated" : "更新完了",
    "UnsetHome" : "削除",
    "DeleteHome" : "登録内容を削除しました",
    "EditHome" : "編集",
    "deleteHomeConfirmation" : "[自宅] の登録情報を削除しますか？",
};

framework.registerAppDictLoaded("favorites", "ja_JP");