var Localization_favoritesAppDict_hr_HR = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Dodaj {frequency}",
    "moveFavorite" : "Premjesti",
    "deleteFavorite" : "Izbriši",
    "addEditRadioFavorite" : "Dodaj/uredi favorit radija",
    "maxCommFavorites" : "Dosegli se maksimalan broj favorita komunikacija.",
    "maxRadioFavorites" : "Dosegli se maksimalan broj favorita radija.",
    "maxNavFavorites" : "Dosegli se maksimalan broj favorita navigacije.",
    "replaceButtonText" : "Zamijeni",
    "replaceExistingFavorite" : "Želite li zamijeniti neki?",
    "selectFavoriteToReplace" : "Odaberi favorit za zamjenu",
    "dialogBackButton" : "Natrag",
    "selectFavoriteToMove" : "Odaberi favorit za premještanje",
    "selectFavoriteToDelete" : "Odaberi favorit za brisanje",
    "deleteConfirmation" : "Jeste li sigurni da želite izbrisati favorit {name}?",
    "selectPosition" : "Odaberi položaj",
    "selectContactDetailsTitle" : "Odaberi pojedinosti osobe {name}",
    "addEditFavoritesCommTitle" : "Komunikacija",
    "addNewContact" : "Dodaj novi kontakt",
    "addNewContactDetails" : "Dodaj nove pojedinosti o kont.",
    "renameFavorite" : "Preimenuj",
    "selectContactTitle" : "Odaberi kontakt",
    "selectFavoriteToRename" : "Odaberi favorit za preimenovanje",
    "addEditFavoritesNaviTitle" : "Navigacija",
    "storeCurrentLocation" : "Dodaj trenutačnu lokaciju",
    "storeCurrentDestination" : "Dodaj trenutačno odredište",
    "addFromContact" : "Dodaj iz kontakta",
    "appTitle" : "Favoriti",
    "renameFavoriteTitle" : "Preimenuj {name} u:",
    "FavoriteAlreadyAvailable" : "Favorit je već dostupan",
    "FavoriteAdded" : "Dodan favorit",
    "addEditCommFavorite" : "Dodaj/uredi favorit komunikacija",
    "addEditNaviFavorite" : "Dodaj/uredi favorit navigacije",
    "replacewithRadioStation" : "Zamijeni s {frequency}",
    "replaceWithContact" : "Zamijeni s kontaktom",
    "replaceWithContactDetail" : "Zamijeni s pojedinosti kontakta",
    "replaceWithCurrentLocation" : "Zamijeni s trenutačnom lokacijom",
    "replaceWithCurrentDestination" : "Zamijeni s trenutačnim odredištem",
    "replaceWithAddress" : "Zamijeni s adresom iz kontakata",
    "phoneNumberCategoryMobile" : "Mobitel:",
    "phoneNumberCategoryHome" : "Kuća:",
    "phoneNumberCategoryWork" : "Posao:",
    "phoneNumberCategoryOther" : "Drugo:",
    "phoneNumberCategoryAddress" : "Adresa:",
    "selectContactNaviDetailsTitle" : "Odaberi adresu osobe {name}",
    "GPSlocation" : "Trenutačna lokacija nije poznata",
    "PhoneConnectionLost" : "Telefonska veza izgubljena",
    "Home" : "Kuća",
    "InvalidAddress" : "Adresa je nevaljana",
    "FavoriteUpdated" : "Favorit ažuriran",
    "UnsetHome" : "Obrišite Kuća",
    "DeleteHome" : "Obrisana poč. lokacija",
    "EditHome" : "Uredi poč.",
    "deleteHomeConfirmation" : "Sigurni ste da želite obrisati lokaciju Kuća?",
};

framework.registerAppDictLoaded("favorites", "hr_HR");