var Localization_favoritesAppDict_it_IT = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Aggiungi {frequency}",
    "moveFavorite" : "Sposta",
    "deleteFavorite" : "Elimina",
    "addEditRadioFavorite" : "Aggiungi/Cambia preferiti radio",
    "maxCommFavorites" : "Si è raggiunto il numero massimo di preferiti per comunicazione.",
    "maxRadioFavorites" : "Si è raggiunto il numero massimo di radio preferite.",
    "maxNavFavorites" : "Si è raggiunto il numero massimo di navigazioni preferite.",
    "replaceButtonText" : "Sostituisci",
    "replaceExistingFavorite" : "Sostiuirne uno?",
    "selectFavoriteToReplace" : "Seleziona preferito da sostituire",
    "dialogBackButton" : "Indietro",
    "selectFavoriteToMove" : "Seleziona un preferito da spostare",
    "selectFavoriteToDelete" : "Seleziona un preferito da eliminare",
    "deleteConfirmation" : "Eliminare preferito {name}?",
    "selectPosition" : "Seleziona posizione",
    "selectContactDetailsTitle" : "Seleziona dettagli {name}",
    "addEditFavoritesCommTitle" : "Comunicazione",
    "addNewContact" : "Aggiungi nuovo contatto",
    "addNewContactDetails" : "Aggiungi dettagli nuovo contatto",
    "renameFavorite" : "Rinomina",
    "selectContactTitle" : "Seleziona un contatto",
    "selectFavoriteToRename" : "Seleziona preferito da rinominare",
    "addEditFavoritesNaviTitle" : "Navigazione",
    "storeCurrentLocation" : "Aggiungi posizione attuale",
    "storeCurrentDestination" : "Aggiungi destinazione attuale",
    "addFromContact" : "Aggiungi da contatto",
    "appTitle" : "Preferiti",
    "renameFavoriteTitle" : "Rinomina {name} con:",
    "FavoriteAlreadyAvailable" : "Preferito già disponibile.",
    "FavoriteAdded" : "Preferito aggiunto.",
    "addEditCommFavorite" : "Aggiungi/Cambia pref comunicazione",
    "addEditNaviFavorite" : "Aggiungi/Cambia preferiti navigazione",
    "replacewithRadioStation" : "Sostituisci con {frequency}",
    "replaceWithContact" : "Sostituire con contatto",
    "replaceWithContactDetail" : "Sostituisci con dettaglio contatto",
    "replaceWithCurrentLocation" : "Sostituisci con località attuale",
    "replaceWithCurrentDestination" : "Sostituisci con destinazione attuale",
    "replaceWithAddress" : "Sostituisci con indirizzo da contatti",
    "phoneNumberCategoryMobile" : "Cellulare",
    "phoneNumberCategoryHome" : "Casa",
    "phoneNumberCategoryWork" : "Lavoro",
    "phoneNumberCategoryOther" : "Altro",
    "phoneNumberCategoryAddress" : "Indirizzo",
    "selectContactNaviDetailsTitle" : "Seleziona indirizzo {name}",
    "GPSlocation" : "La località attuale è sconosciuta.",
    "PhoneConnectionLost" : "Connessione tel.o persa",
    "Home" : "Casa",
    "InvalidAddress" : "Indirizzo non valido.",
    "FavoriteUpdated" : "Preferito aggiornato.",
    "UnsetHome" : "Elimina Casa",
    "DeleteHome" : "Localizzazione Casa annullata",
    "EditHome" : "Modifica Casa",
    "deleteHomeConfirmation" : "Eliminare la posizione di Casa?",
};

framework.registerAppDictLoaded("favorites", "it_IT");