var Localization_favoritesAppDict_pt_PT = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Rádio",
    "storeRadioFavorite" : "Adicionar {frequency}",
    "moveFavorite" : "Mover",
    "deleteFavorite" : "Eliminar",
    "addEditRadioFavorite" : "Adicionar/Editar Favorito de Rádio",
    "maxCommFavorites" : "Atingiu o número máximo de favoritos de Comunicação.",
    "maxRadioFavorites" : "Atingiu o número máximo de favoritos de rádio.",
    "maxNavFavorites" : "Atingiu o número máximo de favoritos de Navegação.",
    "replaceButtonText" : "Substituir",
    "replaceExistingFavorite" : "Pretende substituir um?",
    "selectFavoriteToReplace" : "Seleccionar um Fav. p/ Substituir",
    "dialogBackButton" : "Voltar",
    "selectFavoriteToMove" : "Seleccionar um Favorito p/ Mover",
    "selectFavoriteToDelete" : "Seleccionar Favorito p/ Eliminar",
    "deleteConfirmation" : "Tem a certeza de que pretende eliminar o Favorito {name}?",
    "selectPosition" : "Seleccionar Posição",
    "selectContactDetailsTitle" : "Seleccionar os Detalhes de {name}",
    "addEditFavoritesCommTitle" : "Comunicação",
    "addNewContact" : "Adicionar Novo Contacto",
    "addNewContactDetails" : "Adic. Detal. do Novo Contacto",
    "renameFavorite" : "Mudar o Nome",
    "selectContactTitle" : "Seleccionar um Contacto",
    "selectFavoriteToRename" : "Seleccionar Fav. para Mudar Nome",
    "addEditFavoritesNaviTitle" : "Navegação",
    "storeCurrentLocation" : "Adicionar Localização Actual",
    "storeCurrentDestination" : "Adicionar Destino Actual",
    "addFromContact" : "Adicionar a partir dos Contactos",
    "appTitle" : "Favoritos",
    "renameFavoriteTitle" : "Mudar o Nome de {name} para:",
    "FavoriteAlreadyAvailable" : "O Favorito Já Está Disponível",
    "FavoriteAdded" : "Favorito Adicionado",
    "addEditCommFavorite" : "Adicionar/Editar Favorito de Com.",
    "addEditNaviFavorite" : "Adicionar/Editar Favorito Naveg.",
    "replacewithRadioStation" : "Substituir por {frequency}",
    "replaceWithContact" : "Substituir por Contacto",
    "replaceWithContactDetail" : "Substituir por Detalhe do Contacto",
    "replaceWithCurrentLocation" : "Substituir por Localização Actual",
    "replaceWithCurrentDestination" : "Substituir por Destino Actual",
    "replaceWithAddress" : "Substituir por Endereço de Contactos",
    "phoneNumberCategoryMobile" : "Telemóvel:",
    "phoneNumberCategoryHome" : "Casa:",
    "phoneNumberCategoryWork" : "Emprego:",
    "phoneNumberCategoryOther" : "Outro:",
    "phoneNumberCategoryAddress" : "Morada:",
    "selectContactNaviDetailsTitle" : "Seleccionar o endereço de {name}",
    "GPSlocation" : "A localização actual é desconhecida",
    "PhoneConnectionLost" : "Ligação Perdida",
    "Home" : "Casa",
    "InvalidAddress" : "O endereço é inválido",
    "FavoriteUpdated" : "Favorito Actualizado",
    "UnsetHome" : "Eliminar Casa",
    "DeleteHome" : "Localização de Casa limpa",
    "EditHome" : "Editar Casa",
    "deleteHomeConfirmation" : "Tem a certeza que pretende apagar o Local de Residência?",
};

framework.registerAppDictLoaded("favorites", "pt_PT");