var Localization_favoritesAppDict_lv_LV = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Pievienot {frequency}",
    "moveFavorite" : "Pārvietot",
    "deleteFavorite" : "Dzēst",
    "addEditRadioFavorite" : "Pievienot/rediģēt radio izlasi",
    "maxCommFavorites" : "Esat sasniedzis maksimālo saziņas izlases vienumu skaitu.",
    "maxRadioFavorites" : "Esat sasniedzis maksimālo radio izlases vienumu skaitu.",
    "maxNavFavorites" : "Esat sasniedzis maksimālo navigācijas izlases vienumu skaitu.",
    "replaceButtonText" : "Nomainīt",
    "replaceExistingFavorite" : "Vai aizstāt šo?",
    "selectFavoriteToReplace" : "Atlasīt izlasi, kas jāaizstāj",
    "dialogBackButton" : "Atpakaļ",
    "selectFavoriteToMove" : "Atlasīt izlasi, kas jāpārvieto",
    "selectFavoriteToDelete" : "Atlasīt izlasi, kas jādzēš",
    "deleteConfirmation" : "Vai tiešām vēlaties dzēst izlases vienumu {name}?",
    "selectPosition" : "Atlasīt pozīciju",
    "selectContactDetailsTitle" : "Atlasīt kontakta {name} informāciju",
    "addEditFavoritesCommTitle" : "Saziņa",
    "addNewContact" : "Pievienot jaunu kontaktu",
    "addNewContactDetails" : "Pievienot jaunu kont.inf.",
    "renameFavorite" : "Pārdēvēt",
    "selectContactTitle" : "Atlasīt kontaktu",
    "selectFavoriteToRename" : "Atlasīt izlasi, kas jāpārdēvē",
    "addEditFavoritesNaviTitle" : "Navigācija",
    "storeCurrentLocation" : "Pievienot pašreizējo atrašanās vietu",
    "storeCurrentDestination" : "Pievienot pašreizējo galamērķi",
    "addFromContact" : "Pievienot no kontaktiem",
    "appTitle" : "Izlase",
    "renameFavoriteTitle" : "Pārdēvēt {name} uz:",
    "FavoriteAlreadyAvailable" : "Izlase jau pieejama",
    "FavoriteAdded" : "Izlase pievienota",
    "addEditCommFavorite" : "Pievienot/rediģēt saziņas izlasi",
    "addEditNaviFavorite" : "Pievienot/rediģēt navigācijas izlasi",
    "replacewithRadioStation" : "Aizstāt ar {frequency}",
    "replaceWithContact" : "Aizstāt ar kontaktu",
    "replaceWithContactDetail" : "Nomainīt ar kontaktinformāciju",
    "replaceWithCurrentLocation" : "Nomainīt ar pašreiz.atr. vietu",
    "replaceWithCurrentDestination" : "Nomainīt ar pašreizējo galamērķi",
    "replaceWithAddress" : "Nomainīt ar adresi no kontaktiem",
    "phoneNumberCategoryMobile" : "Mobilais:",
    "phoneNumberCategoryHome" : "Mājās:",
    "phoneNumberCategoryWork" : "Darbā:",
    "phoneNumberCategoryOther" : "Cits:",
    "phoneNumberCategoryAddress" : "Adrese:",
    "selectContactNaviDetailsTitle" : "Atlasīt kontakta {name} adresi",
    "GPSlocation" : "Pašreizējā atrašanās vieta nav zināma",
    "PhoneConnectionLost" : "Zaudēts sav. ar tālruni",
    "Home" : "Mājas",
    "InvalidAddress" : "Adrese nav derīga",
    "FavoriteUpdated" : "Izlase atjaunināta",
    "UnsetHome" : "Dzēst Mājas iestatījumus",
    "DeleteHome" : "Mājas atrašanās vieta noskaidrota",
    "EditHome" : "Rediģēt Mājas iestatījumus",
    "deleteHomeConfirmation" : "Vai tiešām vēlaties izdzēst Mājas atrašanās vietu?",
};

framework.registerAppDictLoaded("favorites", "lv_LV");