var Localization_favoritesAppDict_sk_SK = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Rádio",
    "storeRadioFavorite" : "Pridať {frequency}",
    "moveFavorite" : "Presun",
    "deleteFavorite" : "Vymazať",
    "addEditRadioFavorite" : "Pridať/upraviť obľúbené rádiá",
    "maxCommFavorites" : "Dosiahli ste maximálny počet obľúbených položiek komunikácie.",
    "maxRadioFavorites" : "Dosiahli ste maximálny počet obľúbených položiek rádia.",
    "maxNavFavorites" : "Dosiahli ste maximálny počet obľúbených položiek navigácie.",
    "replaceButtonText" : "Nahradiť",
    "replaceExistingFavorite" : "Chcete nahradiť jeden?",
    "selectFavoriteToReplace" : "Vyberte obľúbenú pol. a nahraďte",
    "dialogBackButton" : "Späť",
    "selectFavoriteToMove" : "Vyberte obľúbenú pol. a presuňte",
    "selectFavoriteToDelete" : "Vyberte obľúbenú pol. a vymažte",
    "deleteConfirmation" : "Naozaj chcete vymazať obľúbenú položku {name}?",
    "selectPosition" : "Vyberte polohu",
    "selectContactDetailsTitle" : "Vyberte detaily kont. {name}",
    "addEditFavoritesCommTitle" : "Komunikácia",
    "addNewContact" : "Pridať nový kontakt",
    "addNewContactDetails" : "Pridať nové detaily kont.",
    "renameFavorite" : "Premenovať",
    "selectContactTitle" : "Vyberte kontakt",
    "selectFavoriteToRename" : "Vyberte polôžku na premenovanie",
    "addEditFavoritesNaviTitle" : "Navigácia",
    "storeCurrentLocation" : "Pridať aktuálnu polohu",
    "storeCurrentDestination" : "Pridať aktuálny cieľ",
    "addFromContact" : "Pridať z kontaktu",
    "appTitle" : "Obľúbené",
    "renameFavoriteTitle" : "{name} premenovať na:",
    "FavoriteAlreadyAvailable" : "Obľúbené už k dispozícii",
    "FavoriteAdded" : "Obľúbená položka pridaná",
    "addEditCommFavorite" : "Pridať/upraviť obľ. položky kom.",
    "addEditNaviFavorite" : "Pridať/upraviť obľúbené polož. Nav.",
    "replacewithRadioStation" : "Nahradiť frekvenciou {frequency}",
    "replaceWithContact" : "Nahradiť kontaktom",
    "replaceWithContactDetail" : "Nahradiť údajom z kontaktu",
    "replaceWithCurrentLocation" : "Nahradiť aktuálnou polohou",
    "replaceWithCurrentDestination" : "Nahradiť aktuálnou destináciou",
    "replaceWithAddress" : "Nahradiť adresou z kontaktov",
    "phoneNumberCategoryMobile" : "Mobil:",
    "phoneNumberCategoryHome" : "Domov:",
    "phoneNumberCategoryWork" : "Práca:",
    "phoneNumberCategoryOther" : "Iné:",
    "phoneNumberCategoryAddress" : "Adresa:",
    "selectContactNaviDetailsTitle" : "Vyberte adresu kontaktu {name}",
    "GPSlocation" : "Aktuálna poloha neznáma",
    "PhoneConnectionLost" : "Strata pripojenia",
    "Home" : "Domov",
    "InvalidAddress" : "Adresa je neplatná",
    "FavoriteUpdated" : "Obľúbené Aktualizované",
    "UnsetHome" : "Zmažte Domov",
    "DeleteHome" : "Vymazaný domov",
    "EditHome" : "Zmeniť domov",
    "deleteHomeConfirmation" : "Ste si istí, že chcete zmazať domov?",
};

framework.registerAppDictLoaded("favorites", "sk_SK");