var Localization_favoritesAppDict_pl_PL = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Dodaj {frequency}",
    "moveFavorite" : "Przenieś",
    "deleteFavorite" : "Usuń",
    "addEditRadioFavorite" : "Dodaj/edytuj radiowe ulubione ",
    "maxCommFavorites" : "Osiągnięto maksymalną liczbę elementów ulubionych komunikacji.",
    "maxRadioFavorites" : "Osiągnięto maksymalną liczbę elementów ulubionych radia.",
    "maxNavFavorites" : "Osiągnięto maksymalną liczbę elementów ulubionych nawigacji.",
    "replaceButtonText" : "Zamień",
    "replaceExistingFavorite" : "Czy zamienić?",
    "selectFavoriteToReplace" : "Ulubiony do wymiany",
    "dialogBackButton" : "Do tyłu",
    "selectFavoriteToMove" : "Ulubiony do przesunięcia",
    "selectFavoriteToDelete" : "Ulubiony do usunięcia",
    "deleteConfirmation" : "Czy na pewno chcesz wymazać Ulubione {name}?",
    "selectPosition" : "Wybierz pozycję",
    "selectContactDetailsTitle" : "Wybierz szczegóły kontaktu {name}",
    "addEditFavoritesCommTitle" : "Komunikacja",
    "addNewContact" : "Dodaj nowy kontakt",
    "addNewContactDetails" : "Dodaj szczeg. nowego kontaktu ",
    "renameFavorite" : "Zmień nazwę",
    "selectContactTitle" : "Wybierz kontakt",
    "selectFavoriteToRename" : "Wybierz ulub. do zmiany nazwy",
    "addEditFavoritesNaviTitle" : "Nawigacja",
    "storeCurrentLocation" : "Dodaj bieżącą lokalizację",
    "storeCurrentDestination" : "Dodaj bieżące miejsce docelowe",
    "addFromContact" : "Dodaj z kontaktu",
    "appTitle" : "Ulubione",
    "renameFavoriteTitle" : "Zmień nazwę {name} na:",
    "FavoriteAlreadyAvailable" : "Element ulubionych jest już dostępny.",
    "FavoriteAdded" : "Element dodany do ulubionych",
    "addEditCommFavorite" : "Dodaj/edytuj ulubiony komun.",
    "addEditNaviFavorite" : "Dodaj/edytuj ulubioną w nawigacji",
    "replacewithRadioStation" : "Zastąpić {frequency}",
    "replaceWithContact" : "Zastąp kontaktem",
    "replaceWithContactDetail" : "Zamień na szczegóły kontaktu",
    "replaceWithCurrentLocation" : "Zamień na bieżącą lokalizację",
    "replaceWithCurrentDestination" : "Zam. na bieżące miejsce docelowe",
    "replaceWithAddress" : "Zamień na adres z kontaktów",
    "phoneNumberCategoryMobile" : "komórka",
    "phoneNumberCategoryHome" : "Dom:",
    "phoneNumberCategoryWork" : "Praca:",
    "phoneNumberCategoryOther" : "Inne:",
    "phoneNumberCategoryAddress" : "Adres:",
    "selectContactNaviDetailsTitle" : "Wybierz adres {name}",
    "GPSlocation" : "Bieżąca lokalizacja jest nieznana.",
    "PhoneConnectionLost" : "Utracone połączenie tel.",
    "Home" : "Dom",
    "InvalidAddress" : "Błędny adres",
    "FavoriteUpdated" : "Uaktualnione Ulubione",
    "UnsetHome" : "Usuń wybór ekranu głównego",
    "DeleteHome" : "Lokalizacja domowa wyczyszczona",
    "EditHome" : "Edytuj ust. lokalizacji domow.",
    "deleteHomeConfirmation" : "Na pewno chcesz usunąć wybór ekranu głównego?",
};

framework.registerAppDictLoaded("favorites", "pl_PL");