var Localization_favoritesAppDict_da_DK = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Tilføj {frequency}",
    "moveFavorite" : "Flyt",
    "deleteFavorite" : "Slet",
    "addEditRadioFavorite" : "Tilføj/Redigér favorit for radio",
    "maxCommFavorites" : "Du har nået det maks. tilladte antal favoritter for kommunikation.",
    "maxRadioFavorites" : "Du har nået det maks. tilladte antal favoritter for radio.",
    "maxNavFavorites" : "Du har nået det maks. tilladte antal favoritter for navigation.",
    "replaceButtonText" : "Erstat",
    "replaceExistingFavorite" : "Ønsker du at erstatte en?",
    "selectFavoriteToReplace" : "Vælg en favorit at erstatte",
    "dialogBackButton" : "Tilbage",
    "selectFavoriteToMove" : "Vælg en favorit at flytte",
    "selectFavoriteToDelete" : "Vælg en favorit for sletning",
    "deleteConfirmation" : "Er du sikker på, at du ønsker at slette favoritnavnet {name}?",
    "selectPosition" : "Vælg position",
    "selectContactDetailsTitle" : "Vælg {name}s oplysninger",
    "addEditFavoritesCommTitle" : "Kommunikation",
    "addNewContact" : "Tilføj ny kontakt",
    "addNewContactDetails" : "Tilføj nye kontaktoplysninger",
    "renameFavorite" : "Omdøb",
    "selectContactTitle" : "Vælg en kontakt",
    "selectFavoriteToRename" : "Vælg en favorit at omdøbe",
    "addEditFavoritesNaviTitle" : "Navigering",
    "storeCurrentLocation" : "Tilføj nuværende placering",
    "storeCurrentDestination" : "Tilføj nuværende destination",
    "addFromContact" : "Tilføj fra kontakt",
    "appTitle" : "Favoritter ",
    "renameFavoriteTitle" : "Omdøb {name} til:",
    "FavoriteAlreadyAvailable" : "Favorit allerede tilføjet",
    "FavoriteAdded" : "Favorit tilføjet",
    "addEditCommFavorite" : "Tilføj/Redigér favorit for komm.",
    "addEditNaviFavorite" : "Tilføj/redigér nav.favorit",
    "replacewithRadioStation" : "Erstat med {frequency}",
    "replaceWithContact" : "Erstat med kontakt",
    "replaceWithContactDetail" : "Erstat med kontaktoplysning",
    "replaceWithCurrentLocation" : "Erstat med nuværende placering",
    "replaceWithCurrentDestination" : "Erstat med nuværende destination",
    "replaceWithAddress" : "Erstat med adresse fra kontakter",
    "phoneNumberCategoryMobile" : "Mobil:",
    "phoneNumberCategoryHome" : "Hjem:",
    "phoneNumberCategoryWork" : "Arbejde:",
    "phoneNumberCategoryOther" : "Andet:",
    "phoneNumberCategoryAddress" : "Adresse:",
    "selectContactNaviDetailsTitle" : "Vælg {name}s adresse",
    "GPSlocation" : "Nuværende placering ukendt",
    "PhoneConnectionLost" : "Forbindelse mistet",
    "Home" : "Hjem",
    "InvalidAddress" : "Adresse er ugyldig",
    "FavoriteUpdated" : "System skal serviceres",
    "UnsetHome" : "Slet hjem",
    "DeleteHome" : "Hjemmeplacering slettet",
    "EditHome" : "Redigér Hjem",
    "deleteHomeConfirmation" : "Slet hjemmeplacering?",
};

framework.registerAppDictLoaded("favorites", "da_DK");