var Localization_favoritesAppDict_ms_MY = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Tambah {frequency}",
    "moveFavorite" : "Gerak",
    "deleteFavorite" : "Padam",
    "addEditRadioFavorite" : "Tambah/Edit Kegemaran Radio",
    "maxCommFavorites" : "Anda telah mencapai bilangan kegemaran Komunikasi maksimum.",
    "maxRadioFavorites" : "Anda telah mencapai bilangan kegemaran radio.",
    "maxNavFavorites" : "Anda telah mencapai bilangan kegemaran Pandu Arah maksimum.",
    "replaceButtonText" : "Ganti",
    "replaceExistingFavorite" : "Adakah anda ingin menggantinya?",
    "selectFavoriteToReplace" : "Pilih Kegemaran untuk Digantikan",
    "dialogBackButton" : "Kembali",
    "selectFavoriteToMove" : "Pilih Kegemaran untuk Dialihkan",
    "selectFavoriteToDelete" : "Pilih Kegemaran untuk Dipadamkan",
    "deleteConfirmation" : "Adakah anda pasti mahu memadamkan Kegemaran {name}? ",
    "selectPosition" : "Pilih Kedudukan",
    "selectContactDetailsTitle" : "Pilih Butiran {name}",
    "addEditFavoritesCommTitle" : "Komunikasi",
    "addNewContact" : "Tambah Kenalan Baharu",
    "addNewContactDetails" : "Tambah Butiran Kenalan Baharu",
    "renameFavorite" : "Namakan semula",
    "selectContactTitle" : "Pilih Kenalan",
    "selectFavoriteToRename" : "Pilih Kesukaan utk Nama Semula",
    "addEditFavoritesNaviTitle" : "Pandu Arah",
    "storeCurrentLocation" : "Tambah Lokasi Semasa",
    "storeCurrentDestination" : "Tambah Destinasi Semasa",
    "addFromContact" : "Tambah dari Kenalan",
    "appTitle" : "Kegemaran",
    "renameFavoriteTitle" : "Namakan semula {name} kepada:",
    "FavoriteAlreadyAvailable" : "Kegemaran Telah Ada",
    "FavoriteAdded" : "Kegemaran Ditambah",
    "addEditCommFavorite" : "Tambah/Edit Kegemaran Komunikasi",
    "addEditNaviFavorite" : "Tambah/Edit Kegemaran Navigasi",
    "replacewithRadioStation" : "Gantikan dengan {frequency}",
    "replaceWithContact" : "Gantikan dengan Kenalan",
    "replaceWithContactDetail" : "Gantikan dengan Butiran Kenalan",
    "replaceWithCurrentLocation" : "Gantikan dengan Lokasi Semasa",
    "replaceWithCurrentDestination" : "Gantikan dengan Destinasi Semasa",
    "replaceWithAddress" : "Gantikan dengan Alamat dari Kenalan",
    "phoneNumberCategoryMobile" : "Mudah Alih:",
    "phoneNumberCategoryHome" : "Rumah:",
    "phoneNumberCategoryWork" : "Tempat Kerja:",
    "phoneNumberCategoryOther" : "Lain-lain:",
    "phoneNumberCategoryAddress" : "Alamat:",
    "selectContactNaviDetailsTitle" : "Pilih alamat {name}",
    "GPSlocation" : "Lokasi semasa tidak diketahui",
    "PhoneConnectionLost" : "Sambungan Tel. Terputus",
    "Home" : "Rumah",
    "InvalidAddress" : "Alamat tidak sah",
    "FavoriteUpdated" : "Kegemaran Dikemas Kini",
    "UnsetHome" : "Padamkan Kediaman",
    "DeleteHome" : "Lokasi Kediaman dikosongkan",
    "EditHome" : "Edit Kediaman",
    "deleteHomeConfirmation" : "Mahu padamkan lokasi Rumah?",
};

framework.registerAppDictLoaded("favorites", "ms_MY");