var Localization_favoritesAppDict_no_NO = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "Legg til {frequency}",
    "moveFavorite" : "Flytt",
    "deleteFavorite" : "Slett",
    "addEditRadioFavorite" : "Legg til/rediger radiofavoritt",
    "maxCommFavorites" : "Du har nådd maksimaltallet for kommunikasjonsfavoritter.",
    "maxRadioFavorites" : "Du har nådd maksimaltallet for radiofavoritter.",
    "maxNavFavorites" : "Du har nådd maksimaltallet for navigeringsfavoritter.",
    "replaceButtonText" : "Skift",
    "replaceExistingFavorite" : "Vil du erstatte en?",
    "selectFavoriteToReplace" : "Velg en favoritt du vil skifte ut",
    "dialogBackButton" : "Tilbake",
    "selectFavoriteToMove" : "Velg en favoritt du vil flytte",
    "selectFavoriteToDelete" : "Velg en favoritt du vil slette",
    "deleteConfirmation" : "Er du sikker på at du vil slette favoritten {name}?",
    "selectPosition" : "Velg posisjon",
    "selectContactDetailsTitle" : "Velg {name}s opplysninger",
    "addEditFavoritesCommTitle" : "Kommunikasjon",
    "addNewContact" : "Legg til ny kontakt",
    "addNewContactDetails" : "Legg til nye kontaktdetaljer",
    "renameFavorite" : "Gi nytt navn",
    "selectContactTitle" : "Velg en kontakt",
    "selectFavoriteToRename" : "Velg favoritt du vil gi nytt navn",
    "addEditFavoritesNaviTitle" : "Navigering",
    "storeCurrentLocation" : "Legg til gjeldende plassering",
    "storeCurrentDestination" : "Legg til gjeldende destinasjon",
    "addFromContact" : "Legg til fra kontakt",
    "appTitle" : "Favoritter",
    "renameFavoriteTitle" : "Gi {name} nytt navn til:",
    "FavoriteAlreadyAvailable" : "Favoritt allerede tilgjengelig",
    "FavoriteAdded" : "Favoritt lagt til",
    "addEditCommFavorite" : "Legg til/rediger komm.favoritt",
    "addEditNaviFavorite" : "Legg til/rediger navigeringsfavoritt",
    "replacewithRadioStation" : "Skift til {frequency}",
    "replaceWithContact" : "Skift med kontakt",
    "replaceWithContactDetail" : "Skift med kontaktopplysninger",
    "replaceWithCurrentLocation" : "Skift med gjeldende plassering",
    "replaceWithCurrentDestination" : "Skift med nåværende destinasjon",
    "replaceWithAddress" : "Skift med adresse fra kontakter",
    "phoneNumberCategoryMobile" : "Mobil:",
    "phoneNumberCategoryHome" : "Hjem:",
    "phoneNumberCategoryWork" : "Arbeid:",
    "phoneNumberCategoryOther" : "Annet:",
    "phoneNumberCategoryAddress" : "Adresse:",
    "selectContactNaviDetailsTitle" : "Velg {name}s adresse",
    "GPSlocation" : "Nåværende plassering er ukjent",
    "PhoneConnectionLost" : "Telefonforbindelsen brutt",
    "Home" : "Hjem",
    "InvalidAddress" : "Adressen er ugyldig",
    "FavoriteUpdated" : "Favoritt oppdatert",
    "UnsetHome" : "Slett Hjem",
    "DeleteHome" : "Hjem-plasseringen slettet",
    "EditHome" : "Rediger Hjem",
    "deleteHomeConfirmation" : "Slette stedet Hjem?",
};

framework.registerAppDictLoaded("favorites", "no_NO");