var Localization_favoritesAppDict_de_DE = {
    //"stringId" : "localString"
    "addEditFavoritesRadioTitle" : "Radio",
    "storeRadioFavorite" : "{frequency} hinzufügen",
    "moveFavorite" : "Verschieben",
    "deleteFavorite" : "Löschen",
    "addEditRadioFavorite" : "Radio-Favoriten hinzufügen/bearb.",
    "maxCommFavorites" : "Sie haben die maximale Anzahl von Kommunikations-Favoriten erreicht.",
    "maxRadioFavorites" : "Sie haben die maximale Anzahl von Radio-Favoriten erreicht.",
    "maxNavFavorites" : "Sie haben die maximale Anzahl von Navigations-Favoriten erreicht.",
    "replaceButtonText" : "Ersetzen",
    "replaceExistingFavorite" : "Möchten Sie einen ersetzen?",
    "selectFavoriteToReplace" : "Favoriten z. Ersetzen wählen",
    "dialogBackButton" : "Zurück",
    "selectFavoriteToMove" : "Favoriten z. Verschieben wählen",
    "selectFavoriteToDelete" : "Wählen Sie 1 Favor. zum Löschen",
    "deleteConfirmation" : "Sind Sie sicher, dass Sie den Favoriten {name} löschen möchten?",
    "selectPosition" : "Position auswählen",
    "selectContactDetailsTitle" : "{name}n Details auswählen",
    "addEditFavoritesCommTitle" : "Kommunikation",
    "addNewContact" : "Neuen Kontakt hinzufügen",
    "addNewContactDetails" : "Neue Kontaktdetails hinzufügen",
    "renameFavorite" : "Umbenennen",
    "selectContactTitle" : "Einen Kontakt auswählen",
    "selectFavoriteToRename" : "Favoriten z. Umbenennen wählen",
    "addEditFavoritesNaviTitle" : "Navigation",
    "storeCurrentLocation" : "Momentanen Standort hinzufügen",
    "storeCurrentDestination" : "Aktuell. Bestimmungsort hinzuf.",
    "addFromContact" : "Aus Kontakten hinzufügen",
    "appTitle" : "Favoriten",
    "renameFavoriteTitle" : "Umbenennen {name} in:",
    "FavoriteAlreadyAvailable" : "Favorit bereits verfügbar",
    "FavoriteAdded" : "Favorit hinzugefügt",
    "addEditCommFavorite" : "Favor.-Kommunik. hinzuf./bearbeit.",
    "addEditNaviFavorite" : "Navigationsfavor. hinzufüg./bearb.",
    "replacewithRadioStation" : "Mit {frequency} ersetzen",
    "replaceWithContact" : "Ersetzen mit Kontakt",
    "replaceWithContactDetail" : "Ersetzen mit Kontaktdetail",
    "replaceWithCurrentLocation" : "Ersetzen mit aktuellem Standort",
    "replaceWithCurrentDestination" : "Ersetzen mit aktuellem Ziel",
    "replaceWithAddress" : "Mit Adresse aus Kontakten ersetzen",
    "phoneNumberCategoryMobile" : "Handy:",
    "phoneNumberCategoryHome" : "Zuhause:",
    "phoneNumberCategoryWork" : "Arbeit:",
    "phoneNumberCategoryOther" : "Andere:",
    "phoneNumberCategoryAddress" : "Adresse:",
    "selectContactNaviDetailsTitle" : "{name}n Adresse auswählen",
    "GPSlocation" : "Aktueller Standort ist unbekannt",
    "PhoneConnectionLost" : "Telefonverbindung verloren",
    "Home" : "Zuhause",
    "InvalidAddress" : "Adresse ist ungültig",
    "FavoriteUpdated" : "Favoriten wurden aktualis.",
    "UnsetHome" : "Zuhause löschen",
    "DeleteHome" : "Zuhause gelöscht",
    "EditHome" : "Zuhause ändern",
    "deleteHomeConfirmation" : "Ihr Zuhause wirklich löschen?",
};

framework.registerAppDictLoaded("favorites", "de_DE");