var Localization_favoritesAppDict_el_GR = {
	//"stringId" : "localString"
	"DeleteHome": "Εκκαθάριση αρχικής θέσης",
	"EditHome": "Επεξεργασία αρχικής θέσης",
	"FavoriteAdded": "Αγαπημένο προστέθηκε",
	"FavoriteAlreadyAvailable": "Αγαπημένο ήδη διαθέσιμο",
	"FavoriteUpdated": "Το αγαπημένο ενημ.",
	"GPSlocation": "Τρέχουσα τοποθεσία είναι άγνωστη",
	"Home": "Αρχική σελίδα",
	"InvalidAddress": "Μη έγκυρη διεύθυνση",
	"NoRadioFavorites": "Δεν υπάρχουν αγαπημένα",
	"PhoneConnectionLost": "Απώλεια τηλεφ. Σύνδ",
	"UnsetHome": "Διαγραφή αρχικής θέσης",
	"addEditCommFavorite": "Προσθ./επεξ. αγαπημ. επικοινωνίας",
	"addEditFavoritesCommTitle": "Επικοινωνία",
	"addEditFavoritesNaviTitle": "Πλοήγηση",
	"addEditFavoritesRadioTitle": "Ραδιόφωνο",
	"addEditNaviFavorite": "Προσθ./επεξ. αγαπημ. πλοήγησης",
	"addEditRadioFavorite": "Προσθ./επεξ. αγαπημ. ραδιοφώνου",
	"addFromContact": "Προσθήκη από επαφή",
	"addNewContact": "Προσθήκη νέας επαφής",
	"addNewContactDetails": "Προσθ. στοιχείων νέας επαφής",
	"appTitle": "Αγαπημένα",
	"deleteConfirmation": "Θέλετε σίγουρα να διαγράψετε το αγαπημένο {name};",
	"deleteFavorite": "Διαγραφή",
	"deleteHomeConfirmation": "Θέλετε σίγουρα να διαγράψετε την αρχική θέση;",
	"dialogBackButton": "Πίσω",
	"maxCommFavorites": "Συμπληρώσατε τον μέγιστο αριθμό αγαπημένων επικοινωνίας.",
	"maxNavFavorites": "Συμπληρώσατε τον μέγιστο αριθμό αγαπημένων πλοήγησης.",
	"maxRadioFavorites": "Συμπληρώσατε τον μέγιστο αριθμό αγαπημένων ραδιοφώνου.",
	"moveFavorite": "Μετακίνηση",
	"phoneNumberCategoryAddress": "Διεύθυνση:",
	"phoneNumberCategoryHome": "Οικίας:",
	"phoneNumberCategoryMobile": "Κινητό:",
	"phoneNumberCategoryOther": "Άλλο:",
	"phoneNumberCategoryWork": "Εργασίας:",
	"renameFavorite": "Μετονομασία",
	"renameFavoriteTitle": "Μετονομασία {name} σε:",
	"replaceButtonText": "Αντικατάσταση",
	"replaceExistingFavorite": "Θέλετε να αντικαταστήσετε ένα;",
	"replaceWithAddress": "Αντικατ. με διεύθυνση από επαφές",
	"replaceWithContact": "Αντικατάσταση με επαφή",
	"replaceWithContactDetail": "Αντικατάσταση με στοιχείο επαφής",
	"replaceWithCurrentDestination": "Αντικατ. με τρέχοντα προορισμό",
	"replaceWithCurrentLocation": "Αντικατ. με τρέχουσα τοποθεσία",
	"replacewithRadioStation": "Αντικατάσταση με {frequency}",
	"selectContactDetailsTitle": "Επιλογή στοιχείων {name}",
	"selectContactNaviDetailsTitle": "Επιλογή διεύθυνσης {name}",
	"selectContactTitle": "Επιλέξτε μια επαφή",
	"selectFavoriteToDelete": "Επιλέξτε αγαπ. για διαγραφή",
	"selectFavoriteToMove": "Επιλέξτε αγαπημένο για μετακ.",
	"selectFavoriteToRename": "Επιλέξτε αγαπημ. για μετον.",
	"selectFavoriteToReplace": "Επιλέξτε αγαπ. για αντικ.",
	"selectPosition": "Επιλογή θέσης",
	"storeCurrentDestination": "Προσθήκη τρέχοντος προορισμού",
	"storeCurrentLocation": "Προσθήκη τρέχουσας τοποθεσίας",
	"storeRadioFavorite": "Προσθήκη {frequency}",
};

framework.registerAppDictLoaded("favorites", "el_GR");