var Localization_favoritesAppDict_sr_RS = {
	//"stringId" : "localString"
	"DeleteHome": "Početni položaj je obrisan",
	"EditHome": "Prikaži početni položaj",
	"FavoriteAdded": "Omiljeni je dodat",
	"FavoriteAlreadyAvailable": "Omiljeni je već dostupan",
	"FavoriteUpdated": "Ažurirani Omiljeni",
	"GPSlocation": "Trenutna lokacija nije poznata",
	"Home": "Kuća",
	"InvalidAddress": "Adresa je nevažeća",
	"NoRadioFavorites": "Nema omiljenih radio stanica",
	"PhoneConnectionLost": "Veza s tel. izgubljena",
	"UnsetHome": "Obrišite Početnu stranicu",
	"addEditCommFavorite": "Dodaj/uredi omiljeno za komunikaciju",
	"addEditFavoritesCommTitle": "Komunikacija",
	"addEditFavoritesNaviTitle": "Navigacija",
	"addEditFavoritesRadioTitle": "Radio",
	"addEditNaviFavorite": "Dodaj/uredi omiljeno za navigaciju",
	"addEditRadioFavorite": "Dodaj/uredi omiljeni radio",
	"addFromContact": "Dodaj iz kontakta",
	"addNewContact": "Dodaj novi kontakt",
	"addNewContactDetails": "Dodaj podatke o novom kontaktu",
	"appTitle": "Omiljeni",
	"deleteConfirmation": "Sigurno želite da izbrišete Omiljene {name}?",
	"deleteFavorite": "Izbriši",
	"deleteHomeConfirmation": "Da li ste sigurni da želite da izbrišete Pošetnu stranicu?",
	"dialogBackButton": "Nazad",
	"maxCommFavorites": "Dostigli ste maksimalni broj omiljenih za komunikaciju.",
	"maxNavFavorites": "Dostigli ste maksimalni broj omiljenih za navigaciju.",
	"maxRadioFavorites": "Dostigli ste maksimalni broj omiljenih za radio.",
	"moveFavorite": "Premesti",
	"phoneNumberCategoryAddress": "Adresa:",
	"phoneNumberCategoryHome": "Kuća:",
	"phoneNumberCategoryMobile": "Mobilni:",
	"phoneNumberCategoryOther": "Ostalo:",
	"phoneNumberCategoryWork": "Posao:",
	"renameFavorite": "Preimenuj",
	"renameFavoriteTitle": "Preimenuj {name} u:",
	"replaceButtonText": "Zameni",
	"replaceExistingFavorite": "Da li želite da ga zamenite?",
	"replaceWithAddress": "Zameni adresom iz kontakata",
	"replaceWithContact": "Zameni sa kontaktom",
	"replaceWithContactDetail": "Zameni detaljima kontakta",
	"replaceWithCurrentDestination": "Zameni trenutnim odredištem",
	"replaceWithCurrentLocation": "Zameni trenutnom lokacijom",
	"replacewithRadioStation": "Zameni sa {frequency}",
	"selectContactDetailsTitle": "Izaberite detalje za {name}",
	"selectContactNaviDetailsTitle": "Izaberite adresu za {name}",
	"selectContactTitle": "Izaberite kontakt",
	"selectFavoriteToDelete": "Izaberite omiljenu stavku za bris.",
	"selectFavoriteToMove": "Izaberite omilj.stavku za premešt.",
	"selectFavoriteToRename": "Izaberite omilj. stavku za preimen.",
	"selectFavoriteToReplace": "Izaberite omilj.stavku za zamenu",
	"selectPosition": "Izaberite položaj",
	"storeCurrentDestination": "Dodaj trenutno odredište",
	"storeCurrentLocation": "Dodaj trenutnu lokaciju",
	"storeRadioFavorite": "Dodaj {frequency}",
};

framework.registerAppDictLoaded("favorites", "sr_RS");