var Localization_favoritesAppDict_nl_NL = {
	//"stringId" : "localString"
	"DeleteHome": "Locatie Home gewist",
	"EditHome": "Home bewerken",
	"FavoriteAdded": "Favoriet toegevoegd",
	"FavoriteAlreadyAvailable": "Favoriet is al beschikbaar",
	"FavoriteUpdated": "Favoriet Bijgewerkt",
	"GPSlocation": "Huidige locatie is onbekend",
	"Home": "Thuis",
	"InvalidAddress": "Adres is ongeldig",
	"NoRadioFavorites": "Geen radiofavorieten",
	"PhoneConnectionLost": "Tel. Verbinding Verloren",
	"UnsetHome": "Thuis verwijderen",
	"addEditCommFavorite": "Fav. communic. toevoegen/bewerken",
	"addEditFavoritesCommTitle": "Communicatie",
	"addEditFavoritesNaviTitle": "Navigatie",
	"addEditFavoritesRadioTitle": "Radio",
	"addEditNaviFavorite": "Fav. navigatie toevoegen/bewerken",
	"addEditRadioFavorite": "Favoriete radio toevoegen/bewerken",
	"addFromContact": "Toevoegen vanuit “Contacten”",
	"addNewContact": "Nieuwe contact toevoegen",
	"addNewContactDetails": "Nieuwe contactgegevs. toevoeg.",
	"appTitle": "Favorieten",
	"deleteConfirmation": "Weet u zeker dat u de Favoriet {name} wilt verwijderen?",
	"deleteFavorite": "Verwijderen",
	"deleteHomeConfirmation": "Weet u zeker dat u de locatie Thuis wilt verwijderen?",
	"dialogBackButton": "Terug",
	"maxCommFavorites": "U hebt het maximale aantal favorieten in “Communicatie” bereikt.",
	"maxNavFavorites": "U hebt het maximale aantal favorieten in “Navigatie” bereikt.",
	"maxRadioFavorites": "U hebt het maximale aantal favorieten in “Radio” bereikt.",
	"moveFavorite": "Verplaatsen",
	"phoneNumberCategoryAddress": "Adres:",
	"phoneNumberCategoryHome": "Thuis:",
	"phoneNumberCategoryMobile": "Mobiel:",
	"phoneNumberCategoryOther": "Andere:",
	"phoneNumberCategoryWork": "Werk:",
	"renameFavorite": "Naam wijzigen",
	"renameFavoriteTitle": "Naam wijzigen {name} in:",
	"replaceButtonText": "Vervangen",
	"replaceExistingFavorite": "Wilt u er een  vervangen?",
	"replaceWithAddress": "Vervangen door contactadres",
	"replaceWithContact": "Vervangen door contact",
	"replaceWithContactDetail": "Vervangen door contactgegevens",
	"replaceWithCurrentDestination": "Vervangen door huidige bestemming",
	"replaceWithCurrentLocation": "Vervangen door huidige locatie",
	"replacewithRadioStation": "Vervangen met {frequency}",
	"selectContactDetailsTitle": "{name} gegevens selecteren",
	"selectContactNaviDetailsTitle": "{name} adres selecteren",
	"selectContactTitle": "Een contact selecteren",
	"selectFavoriteToDelete": "Selecteer een te verwijderen fav.",
	"selectFavoriteToMove": "Selecteer een te verplaatsen fav.",
	"selectFavoriteToRename": "Kies een te hernoemen favor.",
	"selectFavoriteToReplace": "Selecteer een te vervangen favoriet",
	"selectPosition": "Positie selecteren",
	"storeCurrentDestination": "Huidige bestemming toevoegen",
	"storeCurrentLocation": "Huidige locatie toevoegen",
	"storeRadioFavorite": "Toevoegen {frequency}",
};

framework.registerAppDictLoaded("favorites", "nl_NL");