var Localization_favoritesAppDict_es_MX = {
	//"stringId" : "localString"
	"DeleteHome": "Ubicación de Inicio clara",
	"EditHome": "Editar Inicio",
	"FavoriteAdded": "Favorito Añadido",
	"FavoriteAlreadyAvailable": "El favorito ya está disponible",
	"FavoriteUpdated": "Favorito actualizado",
	"GPSlocation": "La ubicación actual es desconocida",
	"Home": "Casa",
	"InvalidAddress": "Dirección Inválida",
	"NoRadioFavorites": "Sin favoritos de radio",
	"PhoneConnectionLost": "Conexión telefóno perdida",
	"UnsetHome": "Eliminar Inicio",
	"addEditCommFavorite": "Añadir/Editar Comunicación Favorita",
	"addEditFavoritesCommTitle": "Comunicación",
	"addEditFavoritesNaviTitle": "Navegación",
	"addEditFavoritesRadioTitle": "Radio ",
	"addEditNaviFavorite": "Añadir/Editar Navegación Favorita",
	"addEditRadioFavorite": "Añadir/Editar Favorito de Radio",
	"addFromContact": "Añadir desde Contacto",
	"addNewContact": "Añadir Nuevo Contacto",
	"addNewContactDetails": "Añadir Detalles Nuevo Contacto",
	"appTitle": "Favoritos ",
	"deleteConfirmation": "¿Está seguro que desea eliminar el favorito {name}?",
	"deleteFavorite": "Eliminar",
	"deleteHomeConfirmation": "¿Está seguro de que quiere eliminar la ubicación inicial?",
	"dialogBackButton": "Atrás  ",
	"maxCommFavorites": "Ha alcanzado el número máximo de favoritos de Comunicación.",
	"maxNavFavorites": "Ha alcanzado el número máximo de favoritos de Navegación.",
	"maxRadioFavorites": "Ha alcanzado el número máximo de favoritos de radio.",
	"moveFavorite": "Mover ",
	"phoneNumberCategoryAddress": "Dirección:",
	"phoneNumberCategoryHome": "Casa:",
	"phoneNumberCategoryMobile": "Móvil:",
	"phoneNumberCategoryOther": "Otro:",
	"phoneNumberCategoryWork": "Trabajo:",
	"renameFavorite": "Renombrar ",
	"renameFavoriteTitle": "Renombrar {name} a:",
	"replaceButtonText": "Sustituir",
	"replaceExistingFavorite": "¿Desea sustituir uno?",
	"replaceWithAddress": "Sustituir con Dirección de Contactos",
	"replaceWithContact": "Sustituir con Contacto",
	"replaceWithContactDetail": "Sustituir con Datos de Contacto",
	"replaceWithCurrentDestination": "Sustituir con Destino Actual",
	"replaceWithCurrentLocation": "Sustituir con Ubicación Actual",
	"replacewithRadioStation": "reemplazar con {frequency}",
	"selectContactDetailsTitle": "Seleccionar Datos de {name}",
	"selectContactNaviDetailsTitle": "Seleccionar dirección de {name}",
	"selectContactTitle": "Seleccionar un Contacto",
	"selectFavoriteToDelete": "Seleccione Favorito a Eliminar",
	"selectFavoriteToMove": "Seleccione un Favorito para Mover",
	"selectFavoriteToRename": "Seleccionar un favorito a renombrar",
	"selectFavoriteToReplace": "Seleccione Favorito a Sustituir",
	"selectPosition": "Seleccionar Posición ",
	"storeCurrentDestination": "Añadir Destino Actual",
	"storeCurrentLocation": "Añadir Ubicación Actual",
	"storeRadioFavorite": "Añadir {frequency}",
};

framework.registerAppDictLoaded("favorites", "es_MX");