var Localization_favoritesAppDict_da_DK = {
	//"stringId" : "localString"
	"DeleteHome": "Hjemmeplacering slettet",
	"EditHome": "Redigér Hjem",
	"FavoriteAdded": "Favorit tilføjet",
	"FavoriteAlreadyAvailable": "Favorit allerede tilføjet",
	"FavoriteUpdated": "System skal serviceres",
	"GPSlocation": "Nuværende placering ukendt",
	"Home": "Hjem",
	"InvalidAddress": "Adresse er ugyldig",
	"NoRadioFavorites": "Ingen radiofavoritter",
	"PhoneConnectionLost": "Forbindelse mistet",
	"UnsetHome": "Slet hjem",
	"addEditCommFavorite": "Tilføj/Redigér favorit for komm.",
	"addEditFavoritesCommTitle": "Kommunikation",
	"addEditFavoritesNaviTitle": "Navigering",
	"addEditFavoritesRadioTitle": "Radio",
	"addEditNaviFavorite": "Tilføj/redigér nav.favorit",
	"addEditRadioFavorite": "Tilføj/Redigér favorit for radio",
	"addFromContact": "Tilføj fra kontakt",
	"addNewContact": "Tilføj ny kontakt",
	"addNewContactDetails": "Tilføj nye kontaktoplysninger",
	"appTitle": "Favoritter ",
	"deleteConfirmation": "Er du sikker på, at du ønsker at slette favoritnavnet {name}?",
	"deleteFavorite": "Slet",
	"deleteHomeConfirmation": "Slet hjemmeplacering?",
	"dialogBackButton": "Tilbage",
	"maxCommFavorites": "Du har nået det maks. tilladte antal favoritter for kommunikation.",
	"maxNavFavorites": "Du har nået det maks. tilladte antal favoritter for navigation.",
	"maxRadioFavorites": "Du har nået det maks. tilladte antal favoritter for radio.",
	"moveFavorite": "Flyt",
	"phoneNumberCategoryAddress": "Adresse:",
	"phoneNumberCategoryHome": "Hjem:",
	"phoneNumberCategoryMobile": "Mobil:",
	"phoneNumberCategoryOther": "Andet:",
	"phoneNumberCategoryWork": "Arbejde:",
	"renameFavorite": "Omdøb",
	"renameFavoriteTitle": "Omdøb {name} til:",
	"replaceButtonText": "Erstat",
	"replaceExistingFavorite": "Ønsker du at erstatte en?",
	"replaceWithAddress": "Erstat med adresse fra kontakter",
	"replaceWithContact": "Erstat med kontakt",
	"replaceWithContactDetail": "Erstat med kontaktoplysning",
	"replaceWithCurrentDestination": "Erstat med nuværende destination",
	"replaceWithCurrentLocation": "Erstat med nuværende placering",
	"replacewithRadioStation": "Erstat med {frequency}",
	"selectContactDetailsTitle": "Vælg {name}s oplysninger",
	"selectContactNaviDetailsTitle": "Vælg {name}s adresse",
	"selectContactTitle": "Vælg en kontakt",
	"selectFavoriteToDelete": "Vælg en favorit for sletning",
	"selectFavoriteToMove": "Vælg en favorit at flytte",
	"selectFavoriteToRename": "Vælg en favorit at omdøbe",
	"selectFavoriteToReplace": "Vælg en favorit at erstatte",
	"selectPosition": "Vælg position",
	"storeCurrentDestination": "Tilføj nuværende destination",
	"storeCurrentLocation": "Tilføj nuværende placering",
	"storeRadioFavorite": "Tilføj {frequency}",
};

framework.registerAppDictLoaded("favorites", "da_DK");