var Localization_favoritesAppDict_fr_CN = {
	//"stringId" : "localString"
	"DeleteHome": "Maison supprimée",
	"EditHome": "Modifier Maison",
	"FavoriteAdded": "Favori ajouté",
	"FavoriteAlreadyAvailable": "Favori déjà disponible",
	"FavoriteUpdated": "Favori mis à jour",
	"GPSlocation": "La position actuelle est inconnue",
	"Home": "Maison",
	"InvalidAddress": "Adresse non valide",
	"NoRadioFavorites": "Aucune radio favorite",
	"PhoneConnectionLost": "Perte connexion téléphone",
	"UnsetHome": "Supprimer Maison",
	"addEditCommFavorite": "Ajouter/Éditer communication fav",
	"addEditFavoritesCommTitle": "Communication",
	"addEditFavoritesNaviTitle": "Navigation",
	"addEditFavoritesRadioTitle": "Radio",
	"addEditNaviFavorite": "Ajouter/Éditer la navigation favorite",
	"addEditRadioFavorite": "Ajouter/Éditer radio favorite",
	"addFromContact": "Ajouter à partir des contacts",
	"addNewContact": "Ajouter un nouveau contact",
	"addNewContactDetails": "Ajouter de nouv. Coordonnées",
	"appTitle": "Favoris",
	"deleteConfirmation": "Êtes-vous sûr de vouloir supprimer ce {name} favori ?",
	"deleteFavorite": "Supprimer",
	"deleteHomeConfirmation": "Voulez-vous supprimer Maison ?",
	"dialogBackButton": "Retour",
	"maxCommFavorites": "Vous avez atteint le nombre maximum de communications favorites.",
	"maxNavFavorites": "Vous avez atteint le nombre maximum de navigations favorites.",
	"maxRadioFavorites": "Vous avez atteint le nombre maximum de radios favorites.",
	"moveFavorite": "Déplacer",
	"phoneNumberCategoryAddress": "Adresse:",
	"phoneNumberCategoryHome": "Maison:",
	"phoneNumberCategoryMobile": "Mobile:",
	"phoneNumberCategoryOther": "Autre:",
	"phoneNumberCategoryWork": "Travail:",
	"renameFavorite": "Renommer",
	"renameFavoriteTitle": "Renommer {name} :",
	"replaceButtonText": "Remplacer",
	"replaceExistingFavorite": "Voulez-vous en rem. un maint. ?",
	"replaceWithAddress": "Remplacer par adresse des contacts",
	"replaceWithContact": "Remplacer par contact",
	"replaceWithContactDetail": "Remplacer par les coordonnées",
	"replaceWithCurrentDestination": "Remplacer par la destination actuelle",
	"replaceWithCurrentLocation": "Remplacer par la position actuelle",
	"replacewithRadioStation": "Remplacer par {frequency}",
	"selectContactDetailsTitle": "Sélectionner coordonnées {name}",
	"selectContactNaviDetailsTitle": "Sélectionner l’adresse de {name}",
	"selectContactTitle": "Sélectionner un contact",
	"selectFavoriteToDelete": "Sélectionner un favori à supprimer",
	"selectFavoriteToMove": "Sélectionner un favori à déplacer",
	"selectFavoriteToRename": "Sélectionner un favori à renommer",
	"selectFavoriteToReplace": "Sélectionner un favori à remplacer",
	"selectPosition": "Sélectionner position",
	"storeCurrentDestination": "Ajouter la destination actuelle",
	"storeCurrentLocation": "Ajouter la position actuelle",
	"storeRadioFavorite": "Ajouter {frequency}",
};

framework.registerAppDictLoaded("favorites", "fr_CN");