var Localization_favoritesAppDict_bg_BG = {
	//"stringId" : "localString"
	"DeleteHome": "Домашният адрес е изчистен",
	"EditHome": "Промяна на домашния",
	"FavoriteAdded": "Добавено в „Предпочитани“",
	"FavoriteAlreadyAvailable": "Вече фигурира в „Предпочитани“",
	"FavoriteUpdated": "Предп. актуализиран",
	"GPSlocation": "Текущото местоположение е неизвестно",
	"Home": "Домашен",
	"InvalidAddress": "Адресът е невалиден",
	"NoRadioFavorites": "Няма любимо радио",
	"PhoneConnectionLost": "Изгубена връзка телеф.",
	"UnsetHome": "Изтриване на домашния",
	"addEditCommFavorite": "Доб./пром. комун. „Предп.“",
	"addEditFavoritesCommTitle": "Комуникация",
	"addEditFavoritesNaviTitle": "Навигация",
	"addEditFavoritesRadioTitle": "Радио",
	"addEditNaviFavorite": "Доб./пром. навиг. „Предп.“",
	"addEditRadioFavorite": "Доб./пром. радио в „Предп.“",
	"addFromContact": "Добавяне от контакт",
	"addNewContact": "Добавяне на нов контакт",
	"addNewContactDetails": "Добавяне нови данни контакт",
	"appTitle": "Предпочитани",
	"deleteConfirmation": "Наистина ли искате да изтриете {name} от „Предпочитани“?",
	"deleteFavorite": "Изтриване",
	"deleteHomeConfirmation": "Сигурни ли сте, че искате да изтриете домашния адрес?",
	"dialogBackButton": "Назад",
	"maxCommFavorites": "Достигнали сте максималния брой „Предпочитани“ за комуникация.",
	"maxNavFavorites": "Достигнали сте максималния брой „Предпочитани“ за навигация.",
	"maxRadioFavorites": "Достигнали сте максималния брой „Предпочитани“ за радио.",
	"moveFavorite": "Преместване",
	"phoneNumberCategoryAddress": "Адрес:",
	"phoneNumberCategoryHome": "Домашен:",
	"phoneNumberCategoryMobile": "Мобилен:",
	"phoneNumberCategoryOther": "Други:",
	"phoneNumberCategoryWork": "Служебен:",
	"renameFavorite": "Преименуване",
	"renameFavoriteTitle": "Преименуване на {name} на:",
	"replaceButtonText": "Замяна",
	"replaceExistingFavorite": "Искате ли да замените един?",
	"replaceWithAddress": "Замяна с адрес от контактите",
	"replaceWithContact": "Замяна с контакт",
	"replaceWithContactDetail": "Замяна с данни на контакт",
	"replaceWithCurrentDestination": "Замяна с текущата крайна цел",
	"replaceWithCurrentLocation": "Замяна с текущото местопол.",
	"replacewithRadioStation": "Заместване с {frequency}",
	"selectContactDetailsTitle": "Изберете данните на {name}",
	"selectContactNaviDetailsTitle": "Изберете адреса на {name}",
	"selectContactTitle": "Изберете контакт",
	"selectFavoriteToDelete": "Изб. изтр. „Предп.“",
	"selectFavoriteToMove": "Изб. премест. „Предп.“",
	"selectFavoriteToRename": "Изб. преим. „Предп.“",
	"selectFavoriteToReplace": "Изб. замяна „Предп.“",
	"selectPosition": "Изберете положение",
	"storeCurrentDestination": "Добавяне на текущата крайна цел",
	"storeCurrentLocation": "Доб. тек. местоп.",
	"storeRadioFavorite": "Добавяне на {frequency}",
};

framework.registerAppDictLoaded("favorites", "bg_BG");