var Localization_favoritesAppDict_ro_RO = {
	//"stringId" : "localString"
	"DeleteHome": "Locaţie Home ştearsă",
	"EditHome": "Editare Home",
	"FavoriteAdded": "Favorit adăugat",
	"FavoriteAlreadyAvailable": "Favoritul este deja disponibil",
	"FavoriteUpdated": "Favorită actualizată",
	"GPSlocation": "Locaţia actuală este necunoscută",
	"Home": "Acasă",
	"InvalidAddress": "Adresa nu este validă.",
	"NoRadioFavorites": "Nici un favorit radio",
	"PhoneConnectionLost": "Conexiune tel. întreruptă",
	"UnsetHome": "Ştergeţi Baza",
	"addEditCommFavorite": "Adăugare/editare favorit comunicare",
	"addEditFavoritesCommTitle": "Comunicare",
	"addEditFavoritesNaviTitle": "Navigaţie",
	"addEditFavoritesRadioTitle": "Radio",
	"addEditNaviFavorite": "Adăugare/editare favorit navigaţie",
	"addEditRadioFavorite": "Adăugare/editare favorit radio",
	"addFromContact": "Adăugare din contacte",
	"addNewContact": "Adăugare contact nou",
	"addNewContactDetails": "Adăugare date contact nou",
	"appTitle": "Favorite",
	"deleteConfirmation": "Sigur doriţi să ştergeţi favorita {name}?",
	"deleteFavorite": "Ştergere",
	"deleteHomeConfirmation": "Sunteţi sigur că doriţi să ştergeţi locaţia Bazei?",
	"dialogBackButton": "Înapoi",
	"maxCommFavorites": "Aţi atins numărul maxim de favorite la comunicare.",
	"maxNavFavorites": "Aţi atins numărul maxim de favorite la navigare.",
	"maxRadioFavorites": "Aţi atins numărul maxim de favorite la radio.",
	"moveFavorite": "Mutare",
	"phoneNumberCategoryAddress": "Adresă:",
	"phoneNumberCategoryHome": "Acasă:",
	"phoneNumberCategoryMobile": "Mobil:",
	"phoneNumberCategoryOther": "Altul:",
	"phoneNumberCategoryWork": "Serviciu:",
	"renameFavorite": "Redenumire",
	"renameFavoriteTitle": "Redenumire {name} în:",
	"replaceButtonText": "Înlocuire",
	"replaceExistingFavorite": "Doriţi să înlocuiţi unul?",
	"replaceWithAddress": "Înlocuire cu adresă din contacte",
	"replaceWithContact": "Înlocuire cu Contact",
	"replaceWithContactDetail": "Înlocuire cu detaliu contact",
	"replaceWithCurrentDestination": "Înlocuire cu destinaţia curentă",
	"replaceWithCurrentLocation": "Înlocuire cu locul curent",
	"replacewithRadioStation": "Înlocuire cu {frequency}",
	"selectContactDetailsTitle": "Selectaţi detalii {name}",
	"selectContactNaviDetailsTitle": "Selectaţi adresa {name}",
	"selectContactTitle": "Selectaţi un contact",
	"selectFavoriteToDelete": "Selectaţi un favorit de şters",
	"selectFavoriteToMove": "Selectaţi un favorit de mutat",
	"selectFavoriteToRename": "Selectaţi un favorit de redenumit",
	"selectFavoriteToReplace": "Selectaţi un favorit de înlocuit",
	"selectPosition": "Selectaţi poziţia",
	"storeCurrentDestination": "Adăugare destinaţie curentă",
	"storeCurrentLocation": "Adăugare locaţie curentă",
	"storeRadioFavorite": "Adăugare {frequency}",
};

framework.registerAppDictLoaded("favorites", "ro_RO");