var Localization_favoritesAppDict_he_IL = {
	//"stringId" : "localString"
	"DeleteHome": "מיקום הבית נוקה",
	"EditHome": "ערוך הגדרת בית",
	"FavoriteAdded": "מועדף התווסף",
	"FavoriteAlreadyAvailable": "מועדף כבר זמין",
	"FavoriteUpdated": "מועדפים מעודכנים",
	"GPSlocation": "מיקום נוכחי בלתי ידוע",
	"Home": "בית",
	"InvalidAddress": "כתובת לא תקפה",
	"NoRadioFavorites": "אין מועדפים לרדיו.",
	"PhoneConnectionLost": "קשר טלפוני אבד",
	"UnsetHome": "מחק בית",
	"addEditCommFavorite": "הוסף/ערוך מועדף בתקשורת",
	"addEditFavoritesCommTitle": "תקשורת",
	"addEditFavoritesNaviTitle": "ניווט",
	"addEditFavoritesRadioTitle": "רדיו",
	"addEditNaviFavorite": "הוסף/ערוך מועדף בניווט",
	"addEditRadioFavorite": "הוסף/ערוך רדיו מועדף",
	"addFromContact": "הוסף מאיש קשר",
	"addNewContact": "הוסף איש קשר חדש",
	"addNewContactDetails": "הוסף פרטי איש קשר חדש",
	"appTitle": "מועדפים",
	"deleteConfirmation": "האם הינך בטוח שברצונך למחוק את המועדף {name}?",
	"deleteFavorite": "מחק",
	"deleteHomeConfirmation": "האם אתה בטוח שברצונך למחוק את מיקום הבית?",
	"dialogBackButton": "חזרה",
	"maxCommFavorites": "הגעת למספר המירבי של  מועדפים בתקשורת.",
	"maxNavFavorites": "הגעת למספר המירבי של מועדפים בניווט .",
	"maxRadioFavorites": "הגעת למספר המירבי של מועדפים ברדיו.",
	"moveFavorite": "עבור",
	"phoneNumberCategoryAddress": "כתובת",
	"phoneNumberCategoryHome": "בית",
	"phoneNumberCategoryMobile": "נייד",
	"phoneNumberCategoryOther": "אחר",
	"phoneNumberCategoryWork": "עבודה",
	"renameFavorite": "תן שם חדש",
	"renameFavoriteTitle": "שנה {name} ל:",
	"replaceButtonText": "החלף",
	"replaceExistingFavorite": "האם ברצונך להחליף אחד?",
	"replaceWithAddress": "החלף עם כתובת מאנשי קשר",
	"replaceWithContact": "החלף באיש קשר",
	"replaceWithContactDetail": "החלף עם פרטי איש קשר",
	"replaceWithCurrentDestination": "החלף עם יעד עכשוי",
	"replaceWithCurrentLocation": "החלף עם מיקום עכשיו",
	"replacewithRadioStation": "החלף עם {frequency}",
	"selectContactDetailsTitle": "בחר פרטים של {name}",
	"selectContactNaviDetailsTitle": "בחר כתובת של {name}",
	"selectContactTitle": "בחר איש קשר",
	"selectFavoriteToDelete": "בחר מועדף למחיקה",
	"selectFavoriteToMove": "בחר מועדף להעברה",
	"selectFavoriteToRename": "בחר מועדף לשינוי השם",
	"selectFavoriteToReplace": "בחר מועדף להחלפה",
	"selectPosition": "בחר מיקום",
	"storeCurrentDestination": "הוסף יעד עכשוי",
	"storeCurrentLocation": "הוסף מיקום עכשוי",
	"storeRadioFavorite": "הוסף {frequency}",
};

framework.registerAppDictLoaded("favorites", "he_IL");