var Localization_aharadioAppDict_et_EE = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Toiming pole saadaval",
	"AhaMaintenance": "Vabandame, praegu toimub aha hooldamine.",
	"AhaNotFound": "aha-d ei leitud",
	"Back": "Tagasi",
	"CheckConnection": "Veenduge, et mobiilseadme andmeühendus toimib korrektselt.",
	"Connect": "Ühenda",
	"ConnectionLost": "Bluetooth-heliühendus on katkenud",
	"Discard": "Loobu",
	"Dislike": "Ei meeldi",
	"DislikeTooltip": "Ei meeldi",
	"EmptyList": "Loend on tühi. Lisage mobiilseadmest.",
	"Episodes_Tooltip": "Episoodid",
	"FunctioningProperly": "Veenduge, et kõik töötab mobiilseadmes korrektselt.",
	"GUI_ShoutPosted_Alert": "Hüüe postitatud",
	"InsufficientConnectivity_Alert": "Ei ole saadaval",
	"LBS": "Läheduses",
	"Like": "Meeldib",
	"LikeTooltip": "Meeldib",
	"MainList_Tooltip": "Põhiloend",
	"MakeSureAhaIsInstalled": "Veenduge, et rakendus aha on mobiilseadmesse installitud.",
	"MobileDeviceError": "Mobiilseadme viga",
	"NoDeviceConnected": "Ühtegi seadet pole ühendatud",
	"NoNetworkAvailable": "Võrguühendus puudub",
	"Nostationsadded": "Jaamu ei lisatud.",
	"Preset": "Eelsalvestatud",
	"RecordingLimit": "Salvestusaja piirang on saavutatud. Kas soovite selle hüüde postitada?",
	"Save": "Salvesta",
	"SetupBluetooth": "Kas häälestan  Bluetooth seadme kohe?",
	"ShoutReady": "Hüüe on valmis",
	"ShoutRecording": "Hüüde salvestamine",
	"VrHelp_LBSDetail_Help_Left1": "Entertainment",
	"VrHelp_LBSDetail_Help_Left2": "Main List",
	"VrHelp_LBSDetail_Help_Left3": "Episodes",
	"VrHelp_LBSDetail_Help_Left4": "Shout",
	"VrHelp_LBSDetail_Help_Left5": "Map",
	"VrHelp_LBSDetail_Help_Right1": "Call",
	"VrHelp_LBSDetail_Help_Right2": "Play / Pause",
	"VrHelp_LBSDetail_Help_Right3": "Previous / Next",
	"VrHelp_LBSDetail_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Main List",
	"VrHelp_NowPlaying_Help_Left3": "Episodes",
	"VrHelp_NowPlaying_Help_Left4": "Shout",
	"VrHelp_NowPlaying_Help_Left5": "Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1": "Back 15 Seconds",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Forward 30 Seconds",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"buffering": "Puhverdamine",
	"entMenu": "Meelelahutuse menüü",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "et_EE");