var Localization_aharadioAppDict_hr_HR = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Radnja nije na raspolaganju.",
	"AhaMaintenance": "Žao nam je. Trenutačno se provodi održavanje apl. aha.",
	"AhaNotFound": "aha nije pronađena",
	"Back": "Natrag",
	"CheckConnection": "Pazite da podatkovna veza na vašem mobilnom uređaju ispravno radi.",
	"Connect": "Poveži",
	"ConnectionLost": "Izgubljena Bluetooth audioveza",
	"Discard": "Odbaci",
	"Dislike": "Nesimpatiziranje",
	"DislikeTooltip": "Nesimpatiziranje",
	"EmptyList": "Popis je prazan. Dodajte iz mobitela.",
	"Episodes_Tooltip": "Epizode",
	"FunctioningProperly": "Provjerite radi li sve ispravno na vašem mobilnom uređaju.",
	"GUI_ShoutPosted_Alert": "\"Shout\" objavljen",
	"InsufficientConnectivity_Alert": "Nedostatno povezivanje.",
	"LBS": "Servisi u blizini",
	"Like": "Simpat.",
	"LikeTooltip": "Simpat.",
	"MainList_Tooltip": "Gl. popis",
	"MakeSureAhaIsInstalled": "Uvjerite se da je aha aplikacija instalirana na mobilnom uređaju.",
	"MobileDeviceError": "Pogreška mobilnog uređaja",
	"NoDeviceConnected": "Nema povezanog uređaja",
	"NoNetworkAvailable": "Nema mrežne veze",
	"Nostationsadded": "Nijedna stanica nije dodana.",
	"Preset": "Unaprijed postavljeno",
	"RecordingLimit": "Dosegnuta je vremenska granica snimanja. Želite li objaviti ovu snimku?",
	"Save": "Spremi",
	"SetupBluetooth": "Sada postaviti Bluetooth uređaj?",
	"ShoutReady": "\"Shout\" spreman",
	"ShoutRecording": "\"Shout\" snimanje",
	"VrHelp_LBSDetail_Help_Left1": "Entertainment",
	"VrHelp_LBSDetail_Help_Left2": "Main List",
	"VrHelp_LBSDetail_Help_Left3": "Episodes",
	"VrHelp_LBSDetail_Help_Left4": "Shout",
	"VrHelp_LBSDetail_Help_Left5": "Map",
	"VrHelp_LBSDetail_Help_Right1": "Call",
	"VrHelp_LBSDetail_Help_Right2": "Play / Pause",
	"VrHelp_LBSDetail_Help_Right3": "Previous / Next",
	"VrHelp_LBSDetail_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Main List",
	"VrHelp_NowPlaying_Help_Left3": "Episodes",
	"VrHelp_NowPlaying_Help_Left4": "Shout",
	"VrHelp_NowPlaying_Help_Left5": "Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1": "Back 15 Seconds",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Forward 30 Seconds",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"buffering": "Predučitavanje",
	"entMenu": "Izbornik Zabava",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "hr_HR");