var Localization_aharadioAppDict_cn_HK = {
	//"stringId" : "localString"
	"ActionNotAvailable": "動作不可用",
	"AhaMaintenance": "對不起，aha 當前正在維修中。",
	"AhaNotFound": "未找到 aha",
	"Back": "後退",
	"CheckConnection": "確保您的行動裝置上的資料連線可用。",
	"Connect": "連線",
	"ConnectionLost": "Bluetooth音訊連線遺失",
	"Discard": "捨棄",
	"Dislike": "不喜好",
	"DislikeTooltip": "不喜好",
	"EmptyList": "清單為空。 從行動裝置新增。",
	"Episodes_Tooltip": "曲集",
	"FunctioningProperly": "確保您的行動裝置一切運行正常。",
	"GUI_ShoutPosted_Alert": "呼喊已發佈",
	"InsufficientConnectivity_Alert": "連線不足",
	"LBS": "附近",
	"Like": "喜好",
	"LikeTooltip": "喜好",
	"MainList_Tooltip": "主清單",
	"MakeSureAhaIsInstalled": "確保 aha 應用程式已經安裝在您的行動裝置上。",
	"MobileDeviceError": "行動裝置錯誤",
	"NoDeviceConnected": "未連接裝置",
	"NoNetworkAvailable": "無網路連線",
	"Nostationsadded": "未新增電臺。",
	"Preset": "預設設定",
	"RecordingLimit": "錄音已達到時限。 是否要發佈此呼喊？",
	"Save": "存儲",
	"SetupBluetooth": "立即設定 Bluetooth 裝置？",
	"ShoutReady": "呼喊準備在",
	"ShoutRecording": "呼喊錄音中",
	"VrHelp_LBSDetail_Help_Left1": "娛樂",
	"VrHelp_LBSDetail_Help_Left2": "主列表",
	"VrHelp_LBSDetail_Help_Left3": "劇集",
	"VrHelp_LBSDetail_Help_Left4": "大聲說",
	"VrHelp_LBSDetail_Help_Left5": "地圖",
	"VrHelp_LBSDetail_Help_Right1": "呼叫",
	"VrHelp_LBSDetail_Help_Right2": "播放 / 暫停",
	"VrHelp_LBSDetail_Help_Right3": "上一個 / 下一個",
	"VrHelp_LBSDetail_Help_Right4": "聲音設置",
	"VrHelp_NowPlaying_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Help_Left2": "主列表",
	"VrHelp_NowPlaying_Help_Left3": "劇集",
	"VrHelp_NowPlaying_Help_Left4": "大聲說",
	"VrHelp_NowPlaying_Help_Left5": "喜歡 / 不喜歡",
	"VrHelp_NowPlaying_Help_Right1": "後退15秒",
	"VrHelp_NowPlaying_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3": "上一個 / 下一個",
	"VrHelp_NowPlaying_Help_Right4": "前進30秒",
	"VrHelp_NowPlaying_Help_Right5": "聲音設置",
	"buffering": "正在緩衝",
	"entMenu": "音訊源",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "cn_HK");