var Localization_aharadioAppDict_sv_SE = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Åtgärd inte tillgänglig",
	"AhaMaintenance": "Tyvärr, det utförs just nu underhåll på aha.",
	"AhaNotFound": "Hittade inte aha.",
	"Back": "Tillbaka",
	"CheckConnection": "Kontrollera att dataanslutningen på din mobila enhet fungerar som den ska.",
	"Connect": "Anslut",
	"ConnectionLost": "Bluetooth-anslutning för ljud bruten",
	"Discard": "Kasta bort",
	"Dislike": "Ogilla",
	"DislikeTooltip": "Ogilla",
	"EmptyList": "Listan tom. Lägg till från mobil enhet.",
	"Episodes_Tooltip": "Avsnitt",
	"FunctioningProperly": "Kontrollera din mobila enhet så att allting fungerar som det ska.",
	"GUI_ShoutPosted_Alert": "Rop publicerat",
	"InsufficientConnectivity_Alert": "Dålig anslutning",
	"LBS": "I närheten",
	"Like": "Gilla",
	"LikeTooltip": "Gilla",
	"MainList_Tooltip": "aha huvudlista",
	"MakeSureAhaIsInstalled": "Se till att aha-programmet finns installerat på din mobila enhet.",
	"MobileDeviceError": "Fel på mobil enhet",
	"NoDeviceConnected": "Ingen enhet ansluten",
	"NoNetworkAvailable": "Ingen nätverksanslutning",
	"Nostationsadded": "Inga stationer tillagda.",
	"Preset": "Förinställningar",
	"RecordingLimit": "Gränsen för inspelningstid har nåtts. Vill du publicera detta rop?",
	"Save": "Spara",
	"SetupBluetooth": "Ställa in Bluetooth-enhet nu?",
	"ShoutReady": "Ropa Klar",
	"ShoutRecording": "Ropa Inspelning",
	"VrHelp_LBSDetail_Help_Left1": "Underhållning",
	"VrHelp_LBSDetail_Help_Left2": "Huvudlista",
	"VrHelp_LBSDetail_Help_Left3": "Episoder",
	"VrHelp_LBSDetail_Help_Left4": "Skrik",
	"VrHelp_LBSDetail_Help_Left5": "Karta",
	"VrHelp_LBSDetail_Help_Right1": "Svara alla",
	"VrHelp_LBSDetail_Help_Right2": "Spela upp / Paus",
	"VrHelp_LBSDetail_Help_Right3": "Föregående / Nästa",
	"VrHelp_LBSDetail_Help_Right4": "Ljudinställningar",
	"VrHelp_NowPlaying_Help_Left1": "Underhållning",
	"VrHelp_NowPlaying_Help_Left2": "Huvudlista",
	"VrHelp_NowPlaying_Help_Left3": "Episoder",
	"VrHelp_NowPlaying_Help_Left4": "Skrik",
	"VrHelp_NowPlaying_Help_Left5": "Gillar / Ogillar",
	"VrHelp_NowPlaying_Help_Right1": "Backa 15 sekunder",
	"VrHelp_NowPlaying_Help_Right2": "Spela upp / Paus",
	"VrHelp_NowPlaying_Help_Right3": "Föregående / Nästa",
	"VrHelp_NowPlaying_Help_Right4": "Framåt 30 sekunder",
	"VrHelp_NowPlaying_Help_Right5": "Ljudinställningar",
	"buffering": "Buffrar",
	"entMenu": "Underhållningsmeny",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "sv_SE");