var Localization_aharadioAppDict_nl_NL = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Actie niet beschikbaar",
	"AhaMaintenance": "Sorry, aha is momenteel in onderhoud.",
	"AhaNotFound": "aha niet gevonden",
	"Back": "Terug",
	"CheckConnection": "Zorg ervoor dat de gegevensverbinding op uw mobiele apparaat naar behoren functioneert.",
	"Connect": "Verbinden",
	"ConnectionLost": "Bluetooth Audio Verbinding Verbroken",
	"Discard": "Verwijderen",
	"Dislike": "Dislike ",
	"DislikeTooltip": "Dislike",
	"EmptyList": "Lijst is leeg. Toevoeg. v.a. mob.app.",
	"Episodes_Tooltip": "Episodes",
	"FunctioningProperly": "Zorg ervoor dat alles goed werkt met uw mobiele apparaat.",
	"GUI_ShoutPosted_Alert": "\"Shout\" geplaatst",
	"InsufficientConnectivity_Alert": "Onvoldoende connectiviteit",
	"LBS": "Vlakbij",
	"Like": "Like",
	"LikeTooltip": "Like",
	"MainList_Tooltip": "Hoofdlijst",
	"MakeSureAhaIsInstalled": "Zorg ervoor dat de aha-app op uw mobiele apparaat geïnstalleerd is.",
	"MobileDeviceError": "Mobiel Apparaat Fout",
	"NoDeviceConnected": "Geen apparaat aangesloten",
	"NoNetworkAvailable": "Geen netwerkverbinding",
	"Nostationsadded": "Geen zenders toegevoegd.",
	"Preset": "Voorinstellingen",
	"RecordingLimit": "Opnametijd limiet bereikt. Wilt u deze \"Shout\" plaatsen?",
	"Save": "Opslaan",
	"SetupBluetooth": "Bluetooth-apparaat nu inrichten?",
	"ShoutReady": "“Shout” klaar",
	"ShoutRecording": "“Shout” opnemen",
	"VrHelp_LBSDetail_Help_Left1": "Entertainment",
	"VrHelp_LBSDetail_Help_Left2": "Hoofdlijst",
	"VrHelp_LBSDetail_Help_Left3": "Episodes",
	"VrHelp_LBSDetail_Help_Left4": "Schreeuwen",
	"VrHelp_LBSDetail_Help_Left5": "Kaart",
	"VrHelp_LBSDetail_Help_Right1": "Bellen ",
	"VrHelp_LBSDetail_Help_Right2": " Afspelen / Pauze",
	"VrHelp_LBSDetail_Help_Right3": "Vorige /  Volgende",
	"VrHelp_LBSDetail_Help_Right4": "Geluidsinstellingen",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Hoofdlijst",
	"VrHelp_NowPlaying_Help_Left3": "Episodes",
	"VrHelp_NowPlaying_Help_Left4": "Schreeuwen",
	"VrHelp_NowPlaying_Help_Left5": " Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1": "15 seconden terug",
	"VrHelp_NowPlaying_Help_Right2": " Afspelen / Pauze",
	"VrHelp_NowPlaying_Help_Right3": "Vorige /  Volgende",
	"VrHelp_NowPlaying_Help_Right4": "30 seconden verder",
	"VrHelp_NowPlaying_Help_Right5": "Geluidsinstellingen",
	"buffering": "Bufferen",
	"entMenu": "Entertainment Menu",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "nl_NL");