var Localization_aharadioAppDict_fi_FI = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Toiminto ei ole käytettävissä",
	"AhaMaintenance": "aha huolletaan tällä hetkellä.",
	"AhaNotFound": "aha ei löytynyt",
	"Back": "Takaisin",
	"CheckConnection": "Tarkista, että mobiililaitteesi datayhteys toimii oikein.",
	"Connect": "Yhdistä",
	"ConnectionLost": "Bluetooth-audioyhteys katkesi",
	"Discard": "Hylkää",
	"Dislike": "En tykkää",
	"DislikeTooltip": "En tykkää",
	"EmptyList": "Luettelo tyhjä. Lisää mobiililaitteesta.",
	"Episodes_Tooltip": "Jaksot",
	"FunctioningProperly": "Varmista, että mobiililaitteeseesi kaikki toiminnot toimivat oikein.",
	"GUI_ShoutPosted_Alert": "Shout-viesti julkaistu",
	"InsufficientConnectivity_Alert": "Riittämätön yhteys",
	"LBS": "Lähellä",
	"Like": "Tykkää",
	"LikeTooltip": "Tykkää",
	"MainList_Tooltip": "Pääluettelo",
	"MakeSureAhaIsInstalled": "Varmista, että aha-sovellus on asennettu mobiililaitteeseen.",
	"MobileDeviceError": "Mobiililaitevirhe",
	"NoDeviceConnected": "Ei kytkettyä laitetta",
	"NoNetworkAvailable": "Ei verkkoyhteyttä",
	"Nostationsadded": "Ei asemia lisätty.",
	"Preset": "Radiokanavat",
	"RecordingLimit": "Äänityksen tallennusraja saavutettu. Haluatko julkaista tämän viestin?",
	"Save": "Tallenna",
	"SetupBluetooth": "Määritetäänkö Bluetooth-laite nyt?",
	"ShoutReady": "Shout-viesti valmiina",
	"ShoutRecording": "Shout-viestiä äänitetään",
	"VrHelp_LBSDetail_Help_Left1": "Viihde",
	"VrHelp_LBSDetail_Help_Left2": "Pääluettelo",
	"VrHelp_LBSDetail_Help_Left3": "Jaksot",
	"VrHelp_LBSDetail_Help_Left4": "Shout-viesti",
	"VrHelp_LBSDetail_Help_Left5": "Kartta",
	"VrHelp_LBSDetail_Help_Right1": "Puhelu",
	"VrHelp_LBSDetail_Help_Right2": "Toista / Tauko",
	"VrHelp_LBSDetail_Help_Right3": "Edellinen/Seuraava",
	"VrHelp_LBSDetail_Help_Right4": "Ääniasetukset",
	"VrHelp_NowPlaying_Help_Left1": "Viihde",
	"VrHelp_NowPlaying_Help_Left2": "Pääluettelo",
	"VrHelp_NowPlaying_Help_Left3": "Jaksot",
	"VrHelp_NowPlaying_Help_Left4": "Shout-viesti",
	"VrHelp_NowPlaying_Help_Left5": "Tykkää / En tykkää",
	"VrHelp_NowPlaying_Help_Right1": "15 sekuntia taaksepäin",
	"VrHelp_NowPlaying_Help_Right2": "Toista / Tauko",
	"VrHelp_NowPlaying_Help_Right3": "Edellinen/Seuraava",
	"VrHelp_NowPlaying_Help_Right4": "30 sekuntia eteenpäin",
	"VrHelp_NowPlaying_Help_Right5": "Ääniasetukset",
	"buffering": "Puskuroidaan",
	"entMenu": "Viihdevalikko",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "fi_FI");