var Localization_aharadioAppDict_tr_TR = {
	//"stringId" : "localString"
	"ActionNotAvailable": "İşlem Mevcut Değil",
	"AhaMaintenance": "Üzgünüz, aha uygulamasına şu anda bakım yapılıyor.",
	"AhaNotFound": "aha Bulunamadı",
	"Back": "Geri",
	"CheckConnection": "Mobil aygıtınızdaki veri bağlantısının sorunsuz çalıştığından emin olun.",
	"Connect": "Bağlan",
	"ConnectionLost": "Bluetooth Ses Bağlantısı Kesildi",
	"Discard": "Sil",
	"Dislike": "Ne sviđa mi se",
	"DislikeTooltip": "Ne sviđa mi se",
	"EmptyList": "Liste boş. Mobil aygıtınızdan ekleyin.",
	"Episodes_Tooltip": "Bölümler",
	"FunctioningProperly": "Mobil aygıtınızda her şeyin sorunsuz çalıştığından emin olun.",
	"GUI_ShoutPosted_Alert": "Yardım Yayınlandı",
	"InsufficientConnectivity_Alert": "Yetersiz Bağlantı",
	"LBS": "Yakında",
	"Like": "Sviđa mi se",
	"LikeTooltip": "Sviđa mi se",
	"MainList_Tooltip": "Glavni spisak",
	"MakeSureAhaIsInstalled": "aha uygulamasının mobil aygıtınıza kurulu olduğundan emin olun.",
	"MobileDeviceError": "Mobil Aygıt Hatası",
	"NoDeviceConnected": "Bağlı Aygıt Yok",
	"NoNetworkAvailable": "Ağ Bağlantısı Yok",
	"Nostationsadded": "Hiçbir istasyon eklenmedi.",
	"Preset": "Ön Ayarlar",
	"RecordingLimit": "Kayıt süresi sınırına ulaşıldı. Bu yardımı yayınlamak ister misiniz?",
	"Save": "Kaydet",
	"SetupBluetooth": "Bluetooth Aygıtı Şimdi Kurulsun Mu?",
	"ShoutReady": "Seslenme Hazır",
	"ShoutRecording": "Seslenme Kaydediliyor",
	"VrHelp_LBSDetail_Help_Left1": "Entertainment",
	"VrHelp_LBSDetail_Help_Left2": "Main List",
	"VrHelp_LBSDetail_Help_Left3": "Episodes",
	"VrHelp_LBSDetail_Help_Left4": "Shout",
	"VrHelp_LBSDetail_Help_Left5": "Map",
	"VrHelp_LBSDetail_Help_Right1": "Call",
	"VrHelp_LBSDetail_Help_Right2": "Play / Pause",
	"VrHelp_LBSDetail_Help_Right3": "Previous / Next",
	"VrHelp_LBSDetail_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Main List",
	"VrHelp_NowPlaying_Help_Left3": "Episodes",
	"VrHelp_NowPlaying_Help_Left4": "Shout",
	"VrHelp_NowPlaying_Help_Left5": "Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1": "Back 15 Seconds",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Forward 30 Seconds",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"buffering": "Ara belleğe alınıyor",
	"entMenu": "Eğlence Menüsü",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "tr_TR");