var Localization_aharadioAppDict_zh_TW = {
	//"stringId" : "localString"
	"ActionNotAvailable": "操作不可用",
	"AhaMaintenance": "抱歉，aha 目前正在維護中。",
	"AhaNotFound": "未找到 aha",
	"Back": "返回",
	"CheckConnection": "確保您的移動裝置上的資料連接工作正常。",
	"Connect": "連接",
	"ConnectionLost": "Bluetooth音頻連接遺失",
	"Discard": "放棄",
	"Dislike": "不喜歡",
	"DislikeTooltip": "不喜歡",
	"EmptyList": "清單為空。請從移動裝置新增。",
	"Episodes_Tooltip": "劇集",
	"FunctioningProperly": "確保您的移動裝置一切工作正常。",
	"GUI_ShoutPosted_Alert": "錄音已發佈",
	"InsufficientConnectivity_Alert": "連接不充分",
	"LBS": "附近",
	"Like": "喜歡",
	"LikeTooltip": "喜歡",
	"MainList_Tooltip": "主清單",
	"MakeSureAhaIsInstalled": "確保您的移動裝置已安裝了 aha 應用程式。",
	"MobileDeviceError": "移動裝置錯誤",
	"NoDeviceConnected": "未連接裝置",
	"NoNetworkAvailable": "無網路連接",
	"Nostationsadded": "無新增電台。",
	"Preset": "預置",
	"RecordingLimit": "達到錄製時間限制。您是否希望發佈此條錄音？",
	"Save": "儲存",
	"SetupBluetooth": "現在設定Bluetooth裝置？",
	"ShoutReady": "錄音準備就緒",
	"ShoutRecording": "正在錄音",
	"VrHelp_LBSDetail_Help_Left1": "娛樂",
	"VrHelp_LBSDetail_Help_Left2": "主列表",
	"VrHelp_LBSDetail_Help_Left3": "劇集",
	"VrHelp_LBSDetail_Help_Left4": "大聲說",
	"VrHelp_LBSDetail_Help_Left5": "地圖",
	"VrHelp_LBSDetail_Help_Right1": "呼叫",
	"VrHelp_LBSDetail_Help_Right2": "播放 / 暫停",
	"VrHelp_LBSDetail_Help_Right3": "上一個 / 下一個",
	"VrHelp_LBSDetail_Help_Right4": "聲音設置",
	"VrHelp_NowPlaying_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Help_Left2": "主列表",
	"VrHelp_NowPlaying_Help_Left3": "劇集",
	"VrHelp_NowPlaying_Help_Left4": "大聲說",
	"VrHelp_NowPlaying_Help_Left5": "喜歡 / 不喜歡",
	"VrHelp_NowPlaying_Help_Right1": "後退15秒",
	"VrHelp_NowPlaying_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3": "上一個 / 下一個",
	"VrHelp_NowPlaying_Help_Right4": "前進30秒",
	"VrHelp_NowPlaying_Help_Right5": "聲音設置",
	"buffering": "正在緩衝",
	"entMenu": "娛樂功能表",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "zh_TW");