var Localization_aharadioAppDict_pt_BR = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Ação não disponível",
	"AhaMaintenance": "Desculpe, o aha encontra-se em manutenção no momento.",
	"AhaNotFound": "aha não encontrado",
	"Back": "Voltar",
	"CheckConnection": "Certifique-se de que a conexão de dados do seu dispositivo móvel está disponível.",
	"Connect": "Conectar",
	"ConnectionLost": "Conexão de áudio Bluetooth perdida",
	"Discard": "Descartar",
	"Dislike": "Descurtir",
	"DislikeTooltip": "Descurtir",
	"EmptyList": "Lista vazia. Adicione do disp.",
	"Episodes_Tooltip": "Episódios",
	"FunctioningProperly": "Certifique-se de que tudo esteja funcionando corretamente em seu dispositivo móvel.",
	"GUI_ShoutPosted_Alert": "Shout publicado",
	"InsufficientConnectivity_Alert": "Conectividade insuficiente",
	"LBS": "Próximo",
	"Like": "Curtir",
	"LikeTooltip": "Curtir",
	"MainList_Tooltip": "Lista principal",
	"MakeSureAhaIsInstalled": "Certifique-se de que o aplicativo aha já esteja instalado em seu dispositivo móvel.",
	"MobileDeviceError": "Erro no dispositivo móvel",
	"NoDeviceConnected": "Nenhum dispositivo conectado",
	"NoNetworkAvailable": "Sem conexão de rede",
	"Nostationsadded": "Nenhuma estação adicionada.",
	"Preset": "Predefinições",
	"RecordingLimit": "Tempo limite de gravação alcançado. Deseja publicar este Shout?",
	"Save": "Salvar",
	"SetupBluetooth": "Configurar dispositivo Bluetooth?",
	"ShoutReady": "Shout pronto",
	"ShoutRecording": "Gravação do Shout",
	"VrHelp_LBSDetail_Help_Left1": "Entretenimento",
	"VrHelp_LBSDetail_Help_Left2": "Lista principal",
	"VrHelp_LBSDetail_Help_Left3": "Episódios",
	"VrHelp_LBSDetail_Help_Left4": "Gritar",
	"VrHelp_LBSDetail_Help_Left5": "Mapa",
	"VrHelp_LBSDetail_Help_Right1": "Telefonar",
	"VrHelp_LBSDetail_Help_Right2": "Reproduzir / Pausar",
	"VrHelp_LBSDetail_Help_Right3": " Anterior / Seguinte ",
	"VrHelp_LBSDetail_Help_Right4": "Definições de som",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Lista principal",
	"VrHelp_NowPlaying_Help_Left3": "Episódios",
	"VrHelp_NowPlaying_Help_Left4": "Gritar",
	"VrHelp_NowPlaying_Help_Left5": "Gostar / Não gostar",
	"VrHelp_NowPlaying_Help_Right1": "Retroceder 15 segundos",
	"VrHelp_NowPlaying_Help_Right2": "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right3": " Anterior / Seguinte ",
	"VrHelp_NowPlaying_Help_Right4": "Avançar 30 segundos",
	"VrHelp_NowPlaying_Help_Right5": "Definições de som",
	"buffering": "Armaz. buffer",
	"entMenu": "Entretenimento",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "pt_BR");