var Localization_aharadioAppDict_it_IT = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Azione non disponibile",
	"AhaMaintenance": "Siamo spiacenti, aha è attualmente in manutenzione.",
	"AhaNotFound": "aha non trovata",
	"Back": "Indietro",
	"CheckConnection": "Assicurarsi che la connessione dati del proprio telefono funzioni correttamente.",
	"Connect": "Connetti",
	"ConnectionLost": "Connessione Bluetooth  persa.",
	"Discard": "Elimina",
	"Dislike": "Non mi piace",
	"DislikeTooltip": "Non mi piace",
	"EmptyList": "Elenco vuoto. Aggiungere da cellulare.",
	"Episodes_Tooltip": "Episodi",
	"FunctioningProperly": "Assicurarsi che il proprio cellulare funzioni correttamente.",
	"GUI_ShoutPosted_Alert": "Post vocale inviato",
	"InsufficientConnectivity_Alert": "Connettività insufficiente",
	"LBS": "Nelle vicinanze",
	"Like": "Mi piace",
	"LikeTooltip": "Mi piace",
	"MainList_Tooltip": "Elenco principale",
	"MakeSureAhaIsInstalled": "Assicurarsi che l'applicazione aha sia già installata sul proprio cellulare.",
	"MobileDeviceError": "Errore cellulare.",
	"NoDeviceConnected": "Nessun dispositivo connesso.",
	"NoNetworkAvailable": "Nessuna connessione di rete.",
	"Nostationsadded": "Nessuna stazione aggiunta.",
	"Preset": "Predefinite",
	"RecordingLimit": "Tempo massimo di registrazione raggiunto. Inviare il post vocale?",
	"Save": "Salva",
	"SetupBluetooth": "Impostare dispositivo Bluetooth ora?",
	"ShoutReady": "Post vocale pronto",
	"ShoutRecording": "Registrazione post vocale ",
	"VrHelp_LBSDetail_Help_Left1": "Intrattenimento",
	"VrHelp_LBSDetail_Help_Left2": "Elenco principale",
	"VrHelp_LBSDetail_Help_Left3": "Episodi",
	"VrHelp_LBSDetail_Help_Left4": "Post vocale",
	"VrHelp_LBSDetail_Help_Left5": "Mappa",
	"VrHelp_LBSDetail_Help_Right1": "Chiama ",
	"VrHelp_LBSDetail_Help_Right2": "Riproduci / Pausa",
	"VrHelp_LBSDetail_Help_Right3": "Precedente / Successivo",
	"VrHelp_LBSDetail_Help_Right4": "Impostazioni audio",
	"VrHelp_NowPlaying_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_Help_Left2": "Elenco principale",
	"VrHelp_NowPlaying_Help_Left3": "Episodi",
	"VrHelp_NowPlaying_Help_Left4": "Post vocale",
	"VrHelp_NowPlaying_Help_Left5": "Mi piace / Non mi piace",
	"VrHelp_NowPlaying_Help_Right1": "Indietro di 15 secondi",
	"VrHelp_NowPlaying_Help_Right2": "Riproduci / Pausa",
	"VrHelp_NowPlaying_Help_Right3": "Precedente / Successivo",
	"VrHelp_NowPlaying_Help_Right4": "Avanti di 30 secondi ",
	"VrHelp_NowPlaying_Help_Right5": "Impostazioni audio",
	"buffering": "Buffering",
	"entMenu": "Menu intrattenimento",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "it_IT");