var Localization_aharadioAppDict_mn_TW = {
	//"stringId" : "localString"
	"ActionNotAvailable": "動作無法使用",
	"AhaMaintenance": "對不起，aha 目前正在維修中。",
	"AhaNotFound": "搜尋不到aha",
	"Back": "回上頁",
	"CheckConnection": "請確認智慧手機的連線功能",
	"Connect": "連接",
	"ConnectionLost": "藍牙連線中斷",
	"Discard": "刪除",
	"Dislike": "不喜歡",
	"DislikeTooltip": "不喜歡",
	"EmptyList": "無選項。請從行動電話新增",
	"Episodes_Tooltip": "劇集",
	"FunctioningProperly": "請確認行動裝置上的一切運作皆正常",
	"GUI_ShoutPosted_Alert": "Shout已傳送",
	"InsufficientConnectivity_Alert": "連線功能不足",
	"LBS": "附近",
	"Like": "喜歡",
	"LikeTooltip": "喜歡",
	"MainList_Tooltip": "主清單",
	"MakeSureAhaIsInstalled": "請確定已將 aha 應用程式安裝在行動裝置上。",
	"MobileDeviceError": "行動裝置錯誤",
	"NoDeviceConnected": "未連接裝置",
	"NoNetworkAvailable": "沒有網路連線",
	"Nostationsadded": "沒有新增電台。",
	"Preset": "預設",
	"RecordingLimit": "已達到錄音時間限制。要傳送此Shout嗎?",
	"Save": "儲存",
	"SetupBluetooth": "要現在設定藍牙裝置嗎?",
	"ShoutReady": "Shout就緒",
	"ShoutRecording": "Shout錄音",
	"VrHelp_LBSDetail_Help_Left1": "娛樂",
	"VrHelp_LBSDetail_Help_Left2": "主列表",
	"VrHelp_LBSDetail_Help_Left3": "劇集",
	"VrHelp_LBSDetail_Help_Left4": "大聲說",
	"VrHelp_LBSDetail_Help_Left5": "地圖",
	"VrHelp_LBSDetail_Help_Right1": "呼叫",
	"VrHelp_LBSDetail_Help_Right2": "播放 / 暫停",
	"VrHelp_LBSDetail_Help_Right3": "上一個 / 下一個",
	"VrHelp_LBSDetail_Help_Right4": "聲音設置",
	"VrHelp_NowPlaying_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Help_Left2": "主列表",
	"VrHelp_NowPlaying_Help_Left3": "劇集",
	"VrHelp_NowPlaying_Help_Left4": "大聲說",
	"VrHelp_NowPlaying_Help_Left5": "喜歡 / 不喜歡",
	"VrHelp_NowPlaying_Help_Right1": "後退15秒",
	"VrHelp_NowPlaying_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3": "上一個 / 下一個",
	"VrHelp_NowPlaying_Help_Right4": "前進30秒",
	"VrHelp_NowPlaying_Help_Right5": "聲音設置",
	"buffering": "緩衝中",
	"entMenu": "娛樂清単",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "mn_TW");