var Localization_aharadioAppDict_ro_RO = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Acţiune nedisponibilă",
	"AhaMaintenance": "Ne pare rău, momentan se efectuează operaţii de întreţinere asupra aha.",
	"AhaNotFound": "aha negăsit",
	"Back": "Înapoi",
	"CheckConnection": "Verificaţi dacă funcţionează corespunzător conexiunea de date a dispozitivului dvs mobil.",
	"Connect": "Conectare",
	"ConnectionLost": "Conexiune Bluetooth audio pierdută",
	"Discard": "Renunţare",
	"Dislike": "Dezaprobare",
	"DislikeTooltip": "Dezaprobare",
	"EmptyList": "Lista goală. Adăug. din disp. mobil.",
	"Episodes_Tooltip": "Episoade",
	"FunctioningProperly": "Verificaţi dacă totul funcţionează adecvat cu dispozitivul dvs mobil.",
	"GUI_ShoutPosted_Alert": "Strigăt inclus",
	"InsufficientConnectivity_Alert": "Conexiune insuficientă",
	"LBS": "În apropiere",
	"Like": "Aprobare",
	"LikeTooltip": "Aprobare",
	"MainList_Tooltip": "Lista principală",
	"MakeSureAhaIsInstalled": "Asiguraţi-vă că aplicaţia aha este deja instalată pe dispozitivul dvs mobil.",
	"MobileDeviceError": "Eroare dispozitiv mobil",
	"NoDeviceConnected": "Niciun dispozitiv conectat",
	"NoNetworkAvailable": "Neconectat la reţea",
	"Nostationsadded": "Nu s-au adăugat posturi.",
	"Preset": "Presetări",
	"RecordingLimit": "Limită durată de înregistrare atinsă. Doriţi să postaţi acest shout?",
	"Save": "Salvare",
	"SetupBluetooth": "Configuraţi dispozitivul Bluetooth acum?",
	"ShoutReady": "Shout pregătit",
	"ShoutRecording": "Înregistrare shout",
	"VrHelp_LBSDetail_Help_Left1": "Entertainment",
	"VrHelp_LBSDetail_Help_Left2": "Main List",
	"VrHelp_LBSDetail_Help_Left3": "Episodes",
	"VrHelp_LBSDetail_Help_Left4": "Shout",
	"VrHelp_LBSDetail_Help_Left5": "Map",
	"VrHelp_LBSDetail_Help_Right1": "Call",
	"VrHelp_LBSDetail_Help_Right2": "Play / Pause",
	"VrHelp_LBSDetail_Help_Right3": "Previous / Next",
	"VrHelp_LBSDetail_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Main List",
	"VrHelp_NowPlaying_Help_Left3": "Episodes",
	"VrHelp_NowPlaying_Help_Left4": "Shout",
	"VrHelp_NowPlaying_Help_Left5": "Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1": "Back 15 Seconds",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Forward 30 Seconds",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"buffering": "Încărcare",
	"entMenu": "Meniu Divertisment",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "ro_RO");