var Localization_aharadioAppDict_pt_PT = {
	//"stringId" : "localString"
	"ActionNotAvailable": "Acção Indisponível",
	"AhaMaintenance": "Lamentamos, de momento o aha está em manutenção.",
	"AhaNotFound": "aha Não Encontrado",
	"Back": "Voltar",
	"CheckConnection": "Certifique-se de que a ligação de dados do dispositivo móvel está a funcionar correctamente.",
	"Connect": "Ligar",
	"ConnectionLost": "Ligação de Áudio Bluetooth Perdida",
	"Discard": "Rejeitar",
	"Dislike": "Não Gostar",
	"DislikeTooltip": "Não Gostar",
	"EmptyList": "Lista vazia. Adic. do dispos. móvel.",
	"Episodes_Tooltip": "Episódios",
	"FunctioningProperly": "Certifique-se de que tudo está a funcionar correctamente com o dispositivo móvel.",
	"GUI_ShoutPosted_Alert": "Grito Publicado",
	"InsufficientConnectivity_Alert": "Conectividade insuficiente",
	"LBS": "Próximo",
	"Like": "Gostar",
	"LikeTooltip": "Gostar",
	"MainList_Tooltip": "Lista Principal",
	"MakeSureAhaIsInstalled": "Certifique-se de que a aplicação aha já está instalada no dispositivo móvel.",
	"MobileDeviceError": "Erro do Dispositivo Móvel",
	"NoDeviceConnected": "Nenhum Dispositivo Ligado",
	"NoNetworkAvailable": "Nenhuma Ligação de Rede",
	"Nostationsadded": "Nenhuma estação adicionada",
	"Preset": "Predefinições",
	"RecordingLimit": "O tempo de gravação foi atingido. Pretende publicar este grito?",
	"Save": "Guardar",
	"SetupBluetooth": "Configurar Dispositivo Bluetooth Agora?",
	"ShoutReady": "Gritar Preparado",
	"ShoutRecording": "Funcionalidade Gritar a Gravar",
	"VrHelp_LBSDetail_Help_Left1": "Entretenimento",
	"VrHelp_LBSDetail_Help_Left2": "Lista Principal",
	"VrHelp_LBSDetail_Help_Left3": "Episódios",
	"VrHelp_LBSDetail_Help_Left4": "Gritar",
	"VrHelp_LBSDetail_Help_Left5": "Mapa",
	"VrHelp_LBSDetail_Help_Right1": "Telefonar",
	"VrHelp_LBSDetail_Help_Right2": "Reproduzir / Pausar",
	"VrHelp_LBSDetail_Help_Right3": " Anterior / Seguinte ",
	"VrHelp_LBSDetail_Help_Right4": "Definições de Som",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Lista Principal",
	"VrHelp_NowPlaying_Help_Left3": "Episódios",
	"VrHelp_NowPlaying_Help_Left4": "Gritar",
	"VrHelp_NowPlaying_Help_Left5": "Gostar / Não Gostar",
	"VrHelp_NowPlaying_Help_Right1": "Retroceder 15 Segundos",
	"VrHelp_NowPlaying_Help_Right2": "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right3": " Anterior / Seguinte ",
	"VrHelp_NowPlaying_Help_Right4": "Avançar 30 Segundos",
	"VrHelp_NowPlaying_Help_Right5": "Definições de Som",
	"buffering": "A Colocar na Memória Intermédia",
	"entMenu": "Menu Entretenimento",
	"sbNameId": "aha",
};

framework.registerAppDictLoaded("aharadio", "pt_PT");