var Localization_btpairingAppDict_nl_NL = {
	//"stringId" : "localString"
	"AddNewDevice": "Nieuw apparaat toevoegen",
	"All": "Weet u zeker dat u alles wilt verwijderen?",
	"AudioConnected": "Audio ingeschakeld",
	"AudioDisconnected": "Audio uitgeschakeld",
	"AudioOnly": "Alleen Audio",
	"BTConnNotAvailableAppleCarPlay": "Er is geen Bluetooth-verbinding beschikbaar voor apparaten die zijn verbonden met Apple CarPlay.",
	"BTPairingDeleteiOS": "Wis \"Mazda\" BT profiel van uw iOS apparaat.",
	"Back": "Terug",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth Verbinding",
	"BluetoothInformation": "Bluetooth Informatie",
	"ChangePaircode": "Koppelcode veranderen",
	"ConfirmDelete": "Weet u zeker dat u {deviceName} wilt verwijderen?",
	"ConnectFailed": "Kan geen verbinding maken met Apparaat",
	"ConnectSuccess": "{deviceName} is nu verbonden",
	"ConnectingDevice": "Verbinden {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth profiel",
	"DeleteComplete": "{deviceName} verwijderd",
	"DeleteDevice": "Apparaatprofiel verwijderen",
	"DeleteFailed": "Loskoppelen {deviceName} mislukt",
	"Disconnect": "Verbinding verbreken",
	"DisconnectFailed": "Uitschakelen mislukt{deviceName}",
	"DisconnectSuccess": "{deviceName}  is losgekoppeld",
	"DisconnectingDevice": "Verbreken {deviceName}",
	"DisconnectingToPair": "Voorbereiding koppeling nieuw apparaat",
	"Discoverable": "Zoeken naar {modelName} op uw Bluetooth apparaat",
	"DiscoverableModel": "Zoek naar {modelName} op uw Bluetooth-apparaat.",
	"DiscoverableTimeout": "Vindbaar voor ({discoverableTimeout}) sec",
	"Enterpaircode": "Voer koppelcode in",
	"InvalidCodeEntry": "Ongeldige code-invoer",
	"InvalidLegacyPIN": "Ongeldige code. Controleer of de code op het mobiele apparaat en het scherm gelijk zijn.",
	"MaxDevices": "Maximale aantal ondersteunde apparaten. Wilt u een apparaat verwijderen?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Mobiele 112 activeren?",
	"NoPairDisconnectFail": "Kan {deviceName} niet uitschakelen voordat er een nieuw apparaat wordt gekoppeld.",
	"NumericConfirmLegacy": "Voer onderstaande PIN in op mobiel apparaat:",
	"NumericConfirmSSP": "Indien het onderstaande nummer overeenkomt met dat op uw mobiele apparaat kunt u koppelen.",
	"PairCancelling": "Koppeling afbreken",
	"PairSuccess": "Koppelen Compleet",
	"PairSuccessConnection": "Verbinding (bezig)",
	"PairingDevice": "Kan Apparaat niet koppelen",
	"PairingInProcess": "Koppelen wordt uitgevoerd",
	"PairingInProcessConnection": "Verbinding (wachten)",
	"PairingSuccess": "Koppeling succesvol",
	"PartialSuccessAudio": "Aangesloten op {partialDeviceName} met audio profiel, maar kon geen verbinding maken met toestel profiel.",
	"PartialSuccessPhone": "Aangesloten op {partialDeviceName} met telefoon profiel, maar kon geen verbinding maken met audio-profiel.",
	"PhoneAndAudio": "Telefoon en audio",
	"PhoneConnected": "Telefoon verbonden",
	"PhoneConnectionLost": "Tel.verbinding verbroken",
	"PhoneDisconnected": "Telefoon uitgeschakeld",
	"PhoneOnly": "Alleen Telefoon",
	"RemoveDevice": "Alle aangekop. apparaten verwijd.",
	"RemovePairDevice": "Gekop. apparaten verwijderen",
	"Retry": "Opnieuw proberen",
	"SelectDeviceToRemove": "Kies te verwijderen apparaat",
	"Setting": "Instellingen",
	"Settings": "Bluetooth Instellingen",
	"TimeLimitExceeded": "Tijdslimiet overschreden",
	"UnableToRemove": "Kan niet alle apparaten verwijderen",
	"UnknownError": "Onbekende fout",
	"Vehiclespeed": "Voertuigsnelheid overschreden",
	"allDevices": "Alle apparaten verwijderd",
};

framework.registerAppDictLoaded("btpairing", "nl_NL");