var Localization_btpairingAppDict_en_UK = {
	//"stringId" : "localString"
	"AddNewDevice": "Add New Device",
	"All": "Are you sure you would like to remove All?",
	"AudioConnected": "Audio Connected",
	"AudioDisconnected": "Audio Disconnected",
	"AudioOnly": "Audio Only",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth connection is not available for devices connected to Apple CarPlay.",
	"BTPairingDeleteiOS": "Delete \"Mazda\" BT profile from your iOS device.",
	"Back": "Back",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth Connection",
	"BluetoothInformation": "Bluetooth Information",
	"ChangePaircode": "Change Paircode",
	"ConfirmDelete": "Are you sure you would like to remove  {deviceName} ?",
	"ConnectFailed": "Unable to Connect Device",
	"ConnectSuccess": "{deviceName} is now connected",
	"ConnectingDevice": "Connecting {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth Profile",
	"DeleteComplete": "{deviceName} Removed",
	"DeleteDevice": "Removing Device Profile",
	"DeleteFailed": "Unable to Remove {deviceName}",
	"Disconnect": "Disconnect",
	"DisconnectFailed": "Unable to disconnect {deviceName}",
	"DisconnectSuccess": "{deviceName} is now disconnected",
	"DisconnectingDevice": "Disconnecting {deviceName}",
	"DisconnectingToPair": "Preparing to pair a new device",
	"Discoverable": "Search for {modelName} in your Bluetooth device.",
	"DiscoverableModel": "Search for {modelName} in your Bluetooth device.",
	"DiscoverableTimeout": "Discoverable for ({discoverableTimeout}) sec",
	"Enterpaircode": "Enter Pair Code",
	"InvalidCodeEntry": "Invalid Code Entry",
	"InvalidLegacyPIN": "Invalid code entry. Check that the code on the mobile device and unit are same.",
	"MaxDevices": "Maximum number of devices supported. Would you like to remove a device?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Enable Mobile 999?",
	"NoPairDisconnectFail": "Unable to disconnect {deviceName} before pairing new device.",
	"NumericConfirmLegacy": "Enter the PIN below on mobile device:",
	"NumericConfirmSSP": "Does the number below match the number on your Mobile Device? If so, you are ready to pair.",
	"PairCancelling": "Pairing Cancelling",
	"PairSuccess": "Pairing Complete",
	"PairSuccessConnection": "Connection (in progress)",
	"PairingDevice": "Unable to Pair Device",
	"PairingInProcess": "Pairing in Progress",
	"PairingInProcessConnection": "Connection (waiting)",
	"PairingSuccess": "Pairing Success",
	"PartialSuccessAudio": "Connected to {partialDeviceName} with Audio Profile but could not connect to Phone Profile",
	"PartialSuccessPhone": "Connected to {partialDeviceName} with Phone Profile but could not connect to Audio Profile",
	"PhoneAndAudio": "Phone And Audio",
	"PhoneConnected": "Phone Connected",
	"PhoneConnectionLost": "Phone Connection Lost",
	"PhoneDisconnected": "Phone Disconnected",
	"PhoneOnly": "Phone Only",
	"RemoveDevice": "Remove All Paired Devices",
	"RemovePairDevice": "Remove Paired Device",
	"Retry": "Retry",
	"SelectDeviceToRemove": "Select Device to Remove",
	"Setting": "Settings",
	"Settings": "Bluetooth Settings",
	"TimeLimitExceeded": "Time Limit Exceeded",
	"UnableToRemove": "Unable to remove all devices",
	"UnknownError": "Unknown error",
	"Vehiclespeed": "Vehicle Speed Exceeded",
	"allDevices": "All Devices Removed",
};

framework.registerAppDictLoaded("btpairing", "en_UK");