var Localization_btpairingAppDict_lv_LV = {
	//"stringId" : "localString"
	"AddNewDevice": "Pievienot jaunu ierīci",
	"All": "Vai esat pārliecināts, ka vēlaties noņemt visu?",
	"AudioConnected": "Audio pievienots",
	"AudioDisconnected": "Audio atvienots",
	"AudioOnly": "Tikai audio",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth savienojums nav pieejams ierīcēm, kas savienotas ar Apple CarPlay.",
	"BTPairingDeleteiOS": "Izdzēsiet \"Mazda\" BT profilu no jūsu iOS iekārtas.",
	"Back": "Atpakaļ",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth savienojums",
	"BluetoothInformation": "Bluetooth informācija",
	"ChangePaircode": "Mainīt sapārošanas kodu",
	"ConfirmDelete": "Vai esat pārliecināts, ka vēlaties noņemt {deviceName}?",
	"ConnectFailed": "Nevar izveidot savienojumu ar ierīci",
	"ConnectSuccess": "Savienojums ar šo ierīci ir izveidots: {deviceName}",
	"ConnectingDevice": "Savieno {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth profils",
	"DeleteComplete": "{deviceName} noņemta",
	"DeleteDevice": "Noņem ierīces profilu",
	"DeleteFailed": "{deviceName} nevar noņemt ",
	"Disconnect": "Atvienot",
	"DisconnectFailed": "Nevar atvienot {deviceName}",
	"DisconnectSuccess": "Savienojums ar šo ierīci ir pārtraukts: {deviceName}",
	"DisconnectingDevice": "Atvieno {deviceName}",
	"DisconnectingToPair": "Sagat. savienošanu pārī ar jaunu ierīci",
	"Discoverable": "Meklējiet {modelName} savā Bluetooth ierīcē.",
	"DiscoverableModel": "Meklēt {modelName} Bluetooth ierīcē.",
	"DiscoverableTimeout": "Ierīce atrodama pēc ({discoverableTimeout}) s",
	"Enterpaircode": "Ievadīt pāra kodu",
	"InvalidCodeEntry": "Nederīga koda ievade",
	"InvalidLegacyPIN": "Ievadīts nederīgs kods. Pārbaudiet, vai mobilajā ierīcē un ierīcē ir ievadīts viens kods.",
	"MaxDevices": "Maksimālais atbalstīto ierīču skaits. Vai noņemt ierīci?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Vai iespējot programmu Zvans 112?",
	"NoPairDisconnectFail": "Nevar atvienot {deviceName} pirms savienošanas pārī ar jaunu ierīci.",
	"NumericConfirmLegacy": "Ievadiet tālāk norādīto PIN mobilajā ierīcē:",
	"NumericConfirmSSP": "Vai tālāk redzamais numurs atbilst numuram mobilajā ierīcē? Ja tā ir, varat veikt savienošanu pārī.",
	"PairCancelling": "Atceļ savienošanu pārī",
	"PairSuccess": "Savienošana pārī pabeigta",
	"PairSuccessConnection": "Savienojums (notiek)",
	"PairingDevice": "Ierīci nevar savienot pārī",
	"PairingInProcess": "Notiek savienošana pārī",
	"PairingInProcessConnection": "Savienojums (gaida)",
	"PairingSuccess": "Savienošana pārī sekmīgi pabeigta",
	"PartialSuccessAudio": "Savienojums ar ierīci {partialDeviceName} ir izveidots, izmantojot audio profilu, taču nevar izveidot savienojumu ar tālruņa profilu.",
	"PartialSuccessPhone": "Savienojums ar ierīci {partialDeviceName} ir izveidots, izmantojot tālruņa profilu, taču nevar izveidot savienojumu ar audio profilu.",
	"PhoneAndAudio": "Tālrunis un audio",
	"PhoneConnected": "Tālrunis pievienots",
	"PhoneConnectionLost": "Zaudēts tālr. savienoj.",
	"PhoneDisconnected": "Tālrunis atvienots",
	"PhoneOnly": "Tikai tālrunis",
	"RemoveDevice": "Noņemt visas sapārotās ierīces",
	"RemovePairDevice": "Noņemt pārī savienoto ierīci",
	"Retry": "Mēģināt vēlreiz",
	"SelectDeviceToRemove": "Atlasīt ierīci, kas jānoņem",
	"Setting": "Iestatījumi",
	"Settings": "Bluetooth iestatījumi",
	"TimeLimitExceeded": "Termiņš pārsniegts",
	"UnableToRemove": "Nevar noņemt visas ierīces",
	"UnknownError": "Nezināma kļūda",
	"Vehiclespeed": "Transportlīdzekļa ātrums pārsniegts",
	"allDevices": "Dzēsts visās ierīcēs",
};

framework.registerAppDictLoaded("btpairing", "lv_LV");