var Localization_btpairingAppDict_bg_BG = {
	//"stringId" : "localString"
	"AddNewDevice": "Добавяне на ново устройство",
	"All": "Сигурни ли сте, че искате да премахнете всички?",
	"AudioConnected": "Звуковото устройство е свързано",
	"AudioDisconnected": "Прек. връз. звук. устр.",
	"AudioOnly": "Само звук",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth връзка не е налична за устройства, свързани към Apple CarPlay.",
	"BTPairingDeleteiOS": "Изтрий профила \"Mazda\" BT от iOS.",
	"Back": "Назад",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Връзка по Bluetooth",
	"BluetoothInformation": "Информация за Bluetooth",
	"ChangePaircode": "Промяна на кода за сдвояване",
	"ConfirmDelete": "Наистина ли искате да изтриете {deviceName}?",
	"ConnectFailed": "Устройството не може да се свърже",
	"ConnectSuccess": "{deviceName} е вече свързано",
	"ConnectingDevice": "Свързване с {deviceName}",
	"ConnectoinTypeTitle": "BT профил на {DeviceName}",
	"DeleteComplete": "{deviceName} е изтрито",
	"DeleteDevice": "Изтриване на профил на устройство",
	"DeleteFailed": "Не може да изтрие {deviceName}",
	"Disconnect": "Прекъсване на връзката",
	"DisconnectFailed": "Връзката с {deviceName} не може да се прекъсне",
	"DisconnectSuccess": "{deviceName} вече не е свързано",
	"DisconnectingDevice": "Прекъсване връзката с {deviceName}",
	"DisconnectingToPair": "Подгот. за сдвоя. с ново устройство",
	"Discoverable": "Търсете {modelName} в Bluetooth устройството.",
	"DiscoverableModel": "Търсене на {modelName} във вашето Bluetooth устройство.",
	"DiscoverableTimeout": "Откриваем за ({discoverableTimeout}) s",
	"Enterpaircode": "Въвеждане на код за",
	"InvalidCodeEntry": "Въведен е невалиден код",
	"InvalidLegacyPIN": "Въведен е невалиден код. Проверете дали кодът на мобилното устройство и системата са едни и същи.",
	"MaxDevices": "Максимален брой поддържани устройства. Искате ли да изтриете устройство?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Разрешаване на Mobile 911?",
	"NoPairDisconnectFail": "Не може да се прекъсне връзката с {deviceName}, преди да се сдвои с друго устройство.",
	"NumericConfirmLegacy": "Въведете следния ПИН код на мобилното устройство:",
	"NumericConfirmSSP": "Следният номер съвпада ли с номера на вашето мобилно устройство? Ако да, значи сте готови за сдвояване.",
	"PairCancelling": "Отказ на сдвояването",
	"PairSuccess": "Сдвояването е извършено",
	"PairSuccessConnection": "Свързване (в ход)",
	"PairingDevice": "Устр-то не може да се сдвои",
	"PairingInProcess": "Извършва се сдвояване",
	"PairingInProcessConnection": "Връзка (изчакване)",
	"PairingSuccess": "Сдвояването е успешно",
	"PartialSuccessAudio": "Има връзка с {partialDeviceName} с аудиопрофил, но не може да се свърже с телефонен профил.",
	"PartialSuccessPhone": "Има връзка с {partialDeviceName} с телефонен профил, но не може да се свърже с аудиопрофил.",
	"PhoneAndAudio": "Телефон и аудио",
	"PhoneConnected": "Телефонът е свързан",
	"PhoneConnectionLost": "Изгуб. връзка с тел.",
	"PhoneDisconnected": "Връз. с телефона е прекъсната",
	"PhoneOnly": "Само телефон",
	"RemoveDevice": "Изтр. всички сдв. устр.",
	"RemovePairDevice": "Изтр. сдв. устр.",
	"Retry": "Повторен опит",
	"SelectDeviceToRemove": "Избор на у-во за изтриване",
	"Setting": "Настройки",
	"Settings": "Настр. Bluetooth",
	"TimeLimitExceeded": "Срокът е изтекъл",
	"UnableToRemove": "Не може да се премахнат всички устройства",
	"UnknownError": "Неизвестна грешка",
	"Vehiclespeed": "Превишена скорост на автомобила",
	"allDevices": "Всички устройства са премахнати",
};

framework.registerAppDictLoaded("btpairing", "bg_BG");