var Localization_btpairingAppDict_zh_TW = {
	//"stringId" : "localString"
	"AddNewDevice": "添加新設備",
	"All": "確定想要刪除所有？",
	"AudioConnected": "音頻已連接",
	"AudioDisconnected": "已斷開音頻的連接",
	"AudioOnly": "僅音頻",
	"BTConnNotAvailableAppleCarPlay": "連接到 Apple CarPlay 的裝置無法使用藍牙連線。",
	"BTPairingDeleteiOS": "從您的iOS設備中移除“Mazda”BT檔案。",
	"Back": "返回",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth連接",
	"BluetoothInformation": "Bluetooth信息",
	"ChangePaircode": "修改配對碼",
	"ConfirmDelete": "您確定要移除 {deviceName} 嗎？",
	"ConnectFailed": "無法連接裝置",
	"ConnectSuccess": "{deviceName} 現已連接",
	"ConnectingDevice": "正在連接 {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth檔案",
	"DeleteComplete": "{deviceName} 已移除",
	"DeleteDevice": "正在移除裝置檔案",
	"DeleteFailed": "無法移除 {deviceName}",
	"Disconnect": "斷開",
	"DisconnectFailed": "無法斷開連接 {deviceName}",
	"DisconnectSuccess": "{deviceName} 現已斷開連接",
	"DisconnectingDevice": "正在斷開連接 {deviceName}",
	"DisconnectingToPair": "正在準備配對新裝置",
	"Discoverable": "在您的Bluetooth裝置中搜尋「{modelName}」。",
	"DiscoverableModel": "在您的Bluetooth裝置中搜尋 {modelName}。",
	"DiscoverableTimeout": "距離超時({discoverableTimeout}) 秒",
	"Enterpaircode": "輸入配對碼",
	"InvalidCodeEntry": "代碼輸入無效",
	"InvalidLegacyPIN": "代碼輸入無效。請檢查移動裝置和系統上的代碼是相同的。",
	"MaxDevices": "支持設備數量已達最大值。 您想移除設備？",
	"Mazda": "Mazda",
	"Mobile911Enable": "啟用移動 911？",
	"NoPairDisconnectFail": "在配對新裝置之前無法斷開 {deviceName}。",
	"NumericConfirmLegacy": "在移動裝置上輸入以下PIN：",
	"NumericConfirmSSP": "下列數字是否和您裝置上的數字一致？如果一致，您已準備好配對。",
	"PairCancelling": "正在取消配對",
	"PairSuccess": "配對完成",
	"PairSuccessConnection": "連接（正在進行）",
	"PairingDevice": "無法配對裝置",
	"PairingInProcess": "正在配對",
	"PairingInProcessConnection": "連接（等待）",
	"PairingSuccess": "配對成功",
	"PartialSuccessAudio": "已連接到帶音頻檔案的 {partialDeviceName}，但無法連接到電話檔案",
	"PartialSuccessPhone": "已連接到帶電話檔案的 {partialDeviceName}，但無法連接到音頻檔案。",
	"PhoneAndAudio": "電話及音訊",
	"PhoneConnected": "電話已連接",
	"PhoneConnectionLost": "電話連接遺失",
	"PhoneDisconnected": "已斷開電話的連接",
	"PhoneOnly": "僅電話",
	"RemoveDevice": "移除所有已配對裝置",
	"RemovePairDevice": "移除已配對裝置",
	"Retry": "重試",
	"SelectDeviceToRemove": "選擇要移除的裝置",
	"Setting": "設置",
	"Settings": "Bluetooth設置",
	"TimeLimitExceeded": "超過時間限制",
	"UnableToRemove": "無法刪除所有設備",
	"UnknownError": "未知錯誤",
	"Vehiclespeed": "超過車速",
	"allDevices": "所有裝置均已移除",
};

framework.registerAppDictLoaded("btpairing", "zh_TW");