var Localization_btpairingAppDict_it_IT = {
	//"stringId" : "localString"
	"AddNewDevice": "Aggiungi nuovo dispositivo",
	"All": "Rimuovere tutti i dispositivi?",
	"AudioConnected": "Audio connesso",
	"AudioDisconnected": "Audio disconnesso",
	"AudioOnly": "Solo audio",
	"BTConnNotAvailableAppleCarPlay": "La connessione Bluetooth non è disponibile per i dispositivi connessi ad Apple CarPlay.",
	"BTPairingDeleteiOS": "Elimina il profilo \"Mazda\" BT dal tuo dispositivo iOS.",
	"Back": "Indietro",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Connessione Bluetooth",
	"BluetoothInformation": "Informazioni Bluetooth",
	"ChangePaircode": "Cambia codice connessione",
	"ConfirmDelete": "Eliminare {deviceName}?",
	"ConnectFailed": "Impossibile connettere il dispositivo.",
	"ConnectSuccess": "{deviceName} è ora connesso.",
	"ConnectingDevice": "Connessione {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Profilo Bluetooth",
	"DeleteComplete": "{deviceName} eliminato.",
	"DeleteDevice": "Eliminazione profilo dispositivo",
	"DeleteFailed": "Impossibile eliminare {deviceName}.",
	"Disconnect": "Disconnetti",
	"DisconnectFailed": "Impossibile da disconnettere {deviceName}.",
	"DisconnectSuccess": "{deviceName} è ora disconnesso.",
	"DisconnectingDevice": "Disconnessione {deviceName}",
	"DisconnectingToPair": "prepar. all'abbinam. di un nuovo disp.",
	"Discoverable": "Ricercare {modelName} nel proprio dispositivo Bluetooth.",
	"DiscoverableModel": "Cerca {modelName} nel tuo dispositivo Bluetooth.",
	"DiscoverableTimeout": "Visualizzabile per ({discoverableTimeout}) sec",
	"Enterpaircode": "Inserisci codice",
	"InvalidCodeEntry": "Codice inserito non valido.",
	"InvalidLegacyPIN": "Codice inserito non valido. Assicurarsi che il codice sul cellulare e sull'unità siano uguali.",
	"MaxDevices": "Numero massimo di dispositivi supportati. Eliminare il dispositivo?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Abilitare chiamate al 118?",
	"NoPairDisconnectFail": "Impossibile disconnettere {deviceName} prima di abbinare un nuovo dispositivo.",
	"NumericConfirmLegacy": "Inserisci il PIN indicato sul cellulare:",
	"NumericConfirmSSP": "Il numero sottostante è uguale a quello sul cellulare? Se sì, il collegamento è pronto.",
	"PairCancelling": "Annullamento associazione",
	"PairSuccess": "Collegamento completato.",
	"PairSuccessConnection": "Connessione (in corso)",
	"PairingDevice": "Impossibile collegare il dispositivo.",
	"PairingInProcess": "Abbinamento in corso…",
	"PairingInProcessConnection": "Connessione (attendere)",
	"PairingSuccess": "Abbinamento riuscito.",
	"PartialSuccessAudio": "Connesso a {partialDeviceName}  con profilo audio, ma impossibile connettersi a profilo telefono.",
	"PartialSuccessPhone": "Connesso a {partialDeviceName}  con profilo telefono, ma impossibile connettersi a profilo audio.",
	"PhoneAndAudio": "Telefono e audio",
	"PhoneConnected": "Telefono connesso",
	"PhoneConnectionLost": "Connessione tel persa.",
	"PhoneDisconnected": "Telefono disconnesso",
	"PhoneOnly": "Solo telefono",
	"RemoveDevice": "Rimuovi tutti i dispositivi associati",
	"RemovePairDevice": "Rimuovi dispositivo collegato",
	"Retry": "Riprova",
	"SelectDeviceToRemove": "Seleziona dispositivo da rimuovere",
	"Setting": "Impostazioni",
	"Settings": "Impostazioni Bluetooth",
	"TimeLimitExceeded": "Limite tempo superato",
	"UnableToRemove": "Impossibile rimuovere tutti i dispositivi.",
	"UnknownError": "Errore sconosciuto.",
	"Vehiclespeed": "Velocità del veicolo eccessiva",
	"allDevices": "Tutti i dispositivi rimossi.",
};

framework.registerAppDictLoaded("btpairing", "it_IT");