var Localization_btpairingAppDict_hr_HR = {
	//"stringId" : "localString"
	"AddNewDevice": "Dodaj novi uređaj",
	"All": "Jeste li sigurni da želite ukloniti sve?",
	"AudioConnected": "Audio povezan",
	"AudioDisconnected": "Audio odvojen",
	"AudioOnly": "Samo audio",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth veza nije dostupna za uređaje koji su povezani s Apple CarPlay.",
	"BTPairingDeleteiOS": "Izbriši \"Mazda\" BT profil s vašeg iOS uređaja.",
	"Back": "Natrag",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth veza",
	"BluetoothInformation": "Bluetooth informacije",
	"ChangePaircode": "Promijeni kod uparivanja",
	"ConfirmDelete": "Jeste li sigurni da želite ukloniti {deviceName} ?",
	"ConnectFailed": "Povezivanje uređaja nije moguće",
	"ConnectSuccess": "{deviceName} je sada povezan",
	"ConnectingDevice": "Povezivanje {deviceName}",
	"ConnectoinTypeTitle": "Bluetooth profil {DeviceName}",
	"DeleteComplete": "{deviceName} uklonjen",
	"DeleteDevice": "Uklanjanje profila uređaja",
	"DeleteFailed": "{deviceName} nije moguće ukloniti",
	"Disconnect": "Prekini vezu",
	"DisconnectFailed": "Nije moguće prekinuti vezu s {deviceName}",
	"DisconnectSuccess": "Veza s uređajem {deviceName}  sada je prekinuta",
	"DisconnectingDevice": "Prekid veze s {deviceName}",
	"DisconnectingToPair": "Priprema za uparivanje novog uređaja",
	"Discoverable": "Tražite {modelName} u svojem Bluetooth uređaju.",
	"DiscoverableModel": "Tražite {modelName} na svojem Bluetooth uređaju.",
	"DiscoverableTimeout": "Otkr. mog. za ({discoverableTimeout}) s",
	"Enterpaircode": "Unesi kod upar.",
	"InvalidCodeEntry": "Unos nevaljanog koda",
	"InvalidLegacyPIN": "Pogrešan unos koda. Provjerite jesu li kod na mobilnom uređaju i na jedinici jednaki.",
	"MaxDevices": "Maksimalan broj podržanih uređaja. Želite li ukloniti neki uređaj?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Omogućiti mobilni 112?",
	"NoPairDisconnectFail": "Prekidanje veze s {deviceName} prije uparivanja novog uređaja nije moguće.",
	"NumericConfirmLegacy": "PIN u nastavku unesite u mobilni uređaj.",
	"NumericConfirmSSP": "Odgovara li broj u nastavku broju na vašem mobilnom uređaju? Ako da, spremni ste za uparivanje.",
	"PairCancelling": "Otkazivanje uparivanja",
	"PairSuccess": "Uparivanje dovršeno",
	"PairSuccessConnection": "Veza (u tijeku)",
	"PairingDevice": "Uparivanje uređaja nije moguće",
	"PairingInProcess": "Uparivanje u tijeku",
	"PairingInProcessConnection": "Veza (čekanje)",
	"PairingSuccess": "Uparivanje uspješno",
	"PartialSuccessAudio": "Povezan na {partialDeviceName} s audio profilom, ali povezivanje s profilom telefona nije moguće.",
	"PartialSuccessPhone": "Povezan na {partialDeviceName} s profilom telefona, ali povezivanje s audio profilom nije moguće.",
	"PhoneAndAudio": "Telefon i audio",
	"PhoneConnected": "Telefon povezan",
	"PhoneConnectionLost": "Izgubljena veza s tel.",
	"PhoneDisconnected": "Telefon odvojen",
	"PhoneOnly": "Samo telefon",
	"RemoveDevice": "Ukloni sve uparene uređaje",
	"RemovePairDevice": "Ukloni upareni uređaj",
	"Retry": "Pokušaj ponovno",
	"SelectDeviceToRemove": "Odaberi uređaj za uklanjanje",
	"Setting": "Postavke",
	"Settings": "Bluetooth postavke",
	"TimeLimitExceeded": "Vremenski limit stekao",
	"UnableToRemove": "Nije moguće ukloniti sve uredaje",
	"UnknownError": "Nepoznata greška",
	"Vehiclespeed": "Prekoračena brzina vozila",
	"allDevices": "Svi uređaji uklonjeni",
};

framework.registerAppDictLoaded("btpairing", "hr_HR");