var Localization_btpairingAppDict_sk_SK = {
	//"stringId" : "localString"
	"AddNewDevice": "Pridať nové zariadenie",
	"All": "Ste si istí, že chcete odstránit všetky?",
	"AudioConnected": "Bluetooth Audio pripojené",
	"AudioDisconnected": "Audio odpojené",
	"AudioOnly": "Iba audio",
	"BTConnNotAvailableAppleCarPlay": "Pripojenie Bluetooth nie je k dispozícii pre zariadenia pripojené k&#160;Apple CarPlay.",
	"BTPairingDeleteiOS": "Odstráňte profil \"Mazda\" BT zo svojho zariadenia iOS.",
	"Back": "Späť",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Pripojenie Bluetooth",
	"BluetoothInformation": "Informácie o pripojení Bluetooth",
	"ChangePaircode": "Zmeniť kód párovania",
	"ConfirmDelete": "Ods.  {deviceName} ?",
	"ConnectFailed": "Nemožno pripojiť zariadenie",
	"ConnectSuccess": "Zariadenie {deviceName} je teraz pripojené",
	"ConnectingDevice": "Pripája sa {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth Profil",
	"DeleteComplete": "{deviceName} odstránené",
	"DeleteDevice": "Odstraňuje sa profil zariadenia",
	"DeleteFailed": "Nedá sa odstrániť {deviceName}",
	"Disconnect": "Odpojiť",
	"DisconnectFailed": "Nedá sa odpojiť {deviceName}",
	"DisconnectSuccess": "Zariadenie {deviceName} je teraz odpojené",
	"DisconnectingDevice": "Odpája sa {deviceName}",
	"DisconnectingToPair": "Pripravuje sa párnovanie nového zar.",
	"Discoverable": "Hľadať {modelName} vo vašom Bluetooth zariadení.",
	"DiscoverableModel": "Vyhľadať {modelName} v Bluetooth zariadenia",
	"DiscoverableTimeout": "Zistiteľné za ({discoverableTimeout}) s",
	"Enterpaircode": "Zadajte párovací kód",
	"InvalidCodeEntry": "Neplatný zadaný kód",
	"InvalidLegacyPIN": "Neplatné zadanie kódu. Skontrolujte, či sú kódy na mobilnom zariadení a jednotke rovnaké.",
	"MaxDevices": "Maximálny počet podporovaných zariadení. Chcete odstrániť zariadenie?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Umožniť tiesňové volanie 911?",
	"NoPairDisconnectFail": "Nedá sa od. {deviceName} pred novým pár.",
	"NumericConfirmLegacy": "Na mobilnom zariadení zadajte nižšie uvedený PIN kód:",
	"NumericConfirmSSP": "Zhoduje sa nižšie uvedené číslo s číslom na vašom mobilnom zariadení? Ak áno, zariadenia sú pripravené na párovanie.",
	"PairCancelling": "Ruší sa párovanie",
	"PairSuccess": "Párovanie dokončené",
	"PairSuccessConnection": "Pripojenie (prebieha)",
	"PairingDevice": "Zariadenie nemožno párovať",
	"PairingInProcess": "Páruje sa",
	"PairingInProcessConnection": "Pripojenie (čaká sa)",
	"PairingSuccess": "Párovanie úspešné",
	"PartialSuccessAudio": "Pripojené k {partialDeviceName} s audio profilom, nemožno ale pripojiť k profilu telefónu.",
	"PartialSuccessPhone": "Pripojené k {partialDeviceName} s profilom telefónu, nemožno ale pripojiť k audio profilu.",
	"PhoneAndAudio": "Telefón a zvuk",
	"PhoneConnected": "Bluetooth Telefón pripojený",
	"PhoneConnectionLost": "Bluetooth Strata pripojenia",
	"PhoneDisconnected": "Telefón odpojený",
	"PhoneOnly": "Iba telefón",
	"RemoveDevice": "Odstrániť všetky spárované zar.",
	"RemovePairDevice": "Odstrániť spárované zar.",
	"Retry": "Skúsiť znova",
	"SelectDeviceToRemove": "Vyberte zar. na odstránenie",
	"Setting": "Nastavenia",
	"Settings": "Nast. Bluetooth",
	"TimeLimitExceeded": "Prekročený časový limit",
	"UnableToRemove": "Nedá Odpojte všetky zariadenia",
	"UnknownError": "Neznáma chyba",
	"Vehiclespeed": "Prekročená rýchlosť vozidla",
	"allDevices": "Všetky zariadenia odstránené",
};

framework.registerAppDictLoaded("btpairing", "sk_SK");