var Localization_btpairingAppDict_pt_BR = {
	//"stringId" : "localString"
	"AddNewDevice": "Adicionar novo dispositivo",
	"All": "Tem certeza que deseja remover tudo?",
	"AudioConnected": "Áudio conectado",
	"AudioDisconnected": "Áudio desconectado",
	"AudioOnly": "Somente áudio",
	"BTConnNotAvailableAppleCarPlay": "Conexão Bluetooth não está disponível para dispositivos conectados ao Apple CarPlay.",
	"BTPairingDeleteiOS": "Excluir perfil \"Mazda\" BT do seu dispositivo iOS.",
	"Back": "Cancelar",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Conexão Bluetooth",
	"BluetoothInformation": "Informações de Bluetooth",
	"ChangePaircode": "Alterar código",
	"ConfirmDelete": "Tem certeza  que deseja remover o {deviceName}?",
	"ConnectFailed": "Não é possível conectar o dispositivo",
	"ConnectSuccess": "O {deviceName} já está conectado",
	"ConnectingDevice": "Conectando {deviceName}",
	"ConnectoinTypeTitle": "Perfil de Bluetooth do {DeviceName}",
	"DeleteComplete": "{deviceName} removido",
	"DeleteDevice": "Desemparelhando dispositivo",
	"DeleteFailed": "Não é possível remover {deviceName}",
	"Disconnect": "Desconectar",
	"DisconnectFailed": "Não é possível desconectar {deviceName}",
	"DisconnectSuccess": "O {deviceName} já está desconectado",
	"DisconnectingDevice": "Desconectando {deviceName}",
	"DisconnectingToPair": "Preparando emp. novo disp.",
	"Discoverable": "Pesquise por {modelName} em seu dispositivo Bluetooth.",
	"DiscoverableModel": "Pesquise por {modelName} em seu dispositivo Bluetooth.",
	"DiscoverableTimeout": "Localizável por ({discoverableTimeout}) segundos",
	"Enterpaircode": "Digite código empar.",
	"InvalidCodeEntry": "Código incorreto",
	"InvalidLegacyPIN": "Código inválido. Verifique se o código do dispositivo móvel é igual ao do sistema.",
	"MaxDevices": "Máximo de dispositivos suportados atingido. Deseja desemparelhar um dispositivo?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Habilitar chamada à assistência emergencial?",
	"NoPairDisconnectFail": "Não é possível desconectar o {deviceName} antes de emparelhar um novo dispositivo.",
	"NumericConfirmLegacy": "Digite o código de emparelhamento abaixo no dispositivo móvel:",
	"NumericConfirmSSP": "O nº corresponde à tela do dispositivo? Se sim, clique em Sim para emparelhar.",
	"PairCancelling": "Cancelamento de emparelhamento",
	"PairSuccess": "Emparelhamento concluído",
	"PairSuccessConnection": "Conectando ao dispositivo",
	"PairingDevice": "Não é possível emparelhar",
	"PairingInProcess": "Emparelhando",
	"PairingInProcessConnection": "Conexão (aguardando)",
	"PairingSuccess": "Emparelhado",
	"PartialSuccessAudio": "Conectado a {partialDeviceName} com perfil de áudio, mas não foi possível conectar ao perfil de telefone.",
	"PartialSuccessPhone": "Conectado a {partialDeviceName} com perfil de telefone, mas não foi possível conectar ao perfil de áudio.",
	"PhoneAndAudio": "Telefone e áudio",
	"PhoneConnected": "Telefone conectado",
	"PhoneConnectionLost": "Conexão Bluetooth perdida",
	"PhoneDisconnected": "Telefone desconectado",
	"PhoneOnly": "Somente telefone",
	"RemoveDevice": "Desemp. dispositivos",
	"RemovePairDevice": "Remover disp. emparelhado ",
	"Retry": "Repetir",
	"SelectDeviceToRemove": "Selec. dispositivo a desemp.",
	"Setting": "Configurações",
	"Settings": "Configurações personalizadas",
	"TimeLimitExceeded": "Limite de tempo excedido",
	"UnableToRemove": "Não é possível remover todos os dispositivos",
	"UnknownError": "Erro desconhecido",
	"Vehiclespeed": "Velocidade do veículo excedida",
	"allDevices": "Todos os dispositivos removidos",
};

framework.registerAppDictLoaded("btpairing", "pt_BR");