var Localization_btpairingAppDict_ro_RO = {
	//"stringId" : "localString"
	"AddNewDevice": "Adăugare dispozitiv nou",
	"All": "Sunteţi sigur ca doriţi să le eliminaţi pe toate",
	"AudioConnected": "Audio conectat",
	"AudioDisconnected": "Audio deconectat",
	"AudioOnly": "Numai audio",
	"BTConnNotAvailableAppleCarPlay": "Conexiunea Bluetooth nu este disponibilă pentru dispozitivele conectate la Apple CarPlay.",
	"BTPairingDeleteiOS": "Ştergeţi profilul \"Mazda\" BT din dispozitivul dvs. iOS.",
	"Back": "Înapoi",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Conexiune Bluetooth",
	"BluetoothInformation": "Informaţii Bluetooth",
	"ChangePaircode": "Modificare cod asociere",
	"ConfirmDelete": "Sunteţi sigur că doriţi să eliminaţi {deviceName} ?",
	"ConnectFailed": "Nu s-a putut conecta dispozitivul",
	"ConnectSuccess": "{deviceName} este acum conectat",
	"ConnectingDevice": "Conectare {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Profil Bluetooth",
	"DeleteComplete": " {deviceName} eliminat",
	"DeleteDevice": "Eliminare profil disp.",
	"DeleteFailed": "Eliminare nereuşită {deviceName}",
	"Disconnect": "Deconectare",
	"DisconnectFailed": "Deconectare nereuşită {deviceName}",
	"DisconnectSuccess": "{deviceName} este acum deconectat",
	"DisconnectingDevice": "Deconectare {deviceName}",
	"DisconnectingToPair": "Pregătit pt. asociere disp.nou.",
	"Discoverable": "Căutaţi {modelName} în dispozitivul dvs Bluetooth.",
	"DiscoverableModel": "Căutare {modelName} în dispozitivul Bluetooth",
	"DiscoverableTimeout": "Descop. timp de ({discoverableTimeout}) sec",
	"Enterpaircode": "Introduceţi codul",
	"InvalidCodeEntry": "Cod incorect",
	"InvalidLegacyPIN": "Cod nevalid introdus. Verificaţi dacă coincid codul de pe dispozitivul mobil şi unitate.",
	"MaxDevices": "Numărul maxim de dispozitive acceptat. Doriţi să eliminaţi un dispozitiv?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Activaţi Mobile 112?",
	"NoPairDisconnectFail": "Nu se poate deconecta {deviceName} înainte de asocierea noului dispozitiv.",
	"NumericConfirmLegacy": "Introduceţi PIN-ul de mai jos pe dispozitivul mobil:",
	"NumericConfirmSSP": "Nr. de mai jos corespunde nr. de pe dispozitivul dvs mobil? Dacă corespunde, sunteţi gata să începeţi asocierea.",
	"PairCancelling": "Anulare asociere",
	"PairSuccess": "Asociere finalizată",
	"PairSuccessConnection": "Conectare (în curs)",
	"PairingDevice": "Nu s-a putut asocia dispozitivul",
	"PairingInProcess": "Asociere în curs",
	"PairingInProcessConnection": "Conectare (aşteptare)",
	"PairingSuccess": "Asociere reuşită",
	"PartialSuccessAudio": "Conectat la {partialDeviceName} cu profil audio, dar nu s-a putut conecta la profilul telefonului.",
	"PartialSuccessPhone": "Conectat la {partialDeviceName} cu profilul telefonului, dar nu s-a putut conecta la profilul audio.",
	"PhoneAndAudio": "Telefon şi audio",
	"PhoneConnected": "Telefon conectat",
	"PhoneConnectionLost": "Leg. telefonică pierdută",
	"PhoneDisconnected": "Telefon deconectat",
	"PhoneOnly": "Numai telefon",
	"RemoveDevice": "Elimină toate dispoz. asociate",
	"RemovePairDevice": "Elimină dispozitivul asociat",
	"Retry": "Reîncercare",
	"SelectDeviceToRemove": "Selectare dispoz. pt. eliminare",
	"Setting": "Setări",
	"Settings": "Setări Bluetooth",
	"TimeLimitExceeded": "Limită de timp depăşită",
	"UnableToRemove": "Este imposibilă eliminarea tuturor dispozitivelor",
	"UnknownError": "Eroare necunoscută",
	"Vehiclespeed": "Viteza vehiculului depăşită",
	"allDevices": "Toate dispozitivele eliminate",
};

framework.registerAppDictLoaded("btpairing", "ro_RO");