var Localization_btpairingAppDict_no_NO = {
	//"stringId" : "localString"
	"AddNewDevice": "Legg til ny enhet",
	"All": "Er du sikker på at du vil fjerne alle?",
	"AudioConnected": "Lyd er tilkoblet",
	"AudioDisconnected": "Lyd er frakoblet",
	"AudioOnly": "Kun lyd",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth-tilkobling er ikke tilgjengelig for enheter tilkoblet med Apple CarPlay.",
	"BTPairingDeleteiOS": "Slett \"Mazda\" BT-profilen fra iOS-enheten.",
	"Back": "Tilbake",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth-tilkobling",
	"BluetoothInformation": "Bluetooth-informasjon",
	"ChangePaircode": "Endre paringskode",
	"ConfirmDelete": "Er du sikker på at du vil fjerne {deviceName} ?",
	"ConnectFailed": "Kan ikke koble til enheten",
	"ConnectSuccess": "{deviceName} er nå tilkoblet",
	"ConnectingDevice": "Tilkobling {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth-profil",
	"DeleteComplete": "{deviceName} fjernet",
	"DeleteDevice": "Fjerner enhetsprofil",
	"DeleteFailed": "Kan ikke fjerne {deviceName}",
	"Disconnect": "Kople fra",
	"DisconnectFailed": "Kan ikke koble fra {deviceName}",
	"DisconnectSuccess": "{deviceName} er nå frakoblet",
	"DisconnectingDevice": "Frakobling {deviceName}",
	"DisconnectingToPair": "Forbereder paring av ny enhet",
	"Discoverable": "Søk etter {modelName} i Bluetooth-enheten.",
	"DiscoverableModel": "Søk etter {modelName} på Bluetooth-enheten.",
	"DiscoverableTimeout": "Synlig i ({discoverableTimeout}) sek",
	"Enterpaircode": "Angi paringskode",
	"InvalidCodeEntry": "Ugyldig kodeoppføring",
	"InvalidLegacyPIN": "Ugyldig kodeoppføring. Sjekk at koden på den mobile enheten og enheten er den samme.",
	"MaxDevices": "Maks antall enheter er nådd. Vil du fjerne en enhet?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Aktiver mobilt nødnummer?",
	"NoPairDisconnectFail": "Kan ikke koble fra {deviceName} før paring av ny enhet.",
	"NumericConfirmLegacy": "Angi PIN-koden nedenfor på den mobile enheten:",
	"NumericConfirmSSP": "Er tallet nedenfor det samme som tallet på den mobile enheten? Hvis ja, er du klar til å pare.",
	"PairCancelling": "Avbryter paring",
	"PairSuccess": "Paring fullført",
	"PairSuccessConnection": "Tilkobling (pågår)",
	"PairingDevice": "Kan ikke pare enheten",
	"PairingInProcess": "Paring pågår",
	"PairingInProcessConnection": "Tilkobling (venter)",
	"PairingSuccess": "Paringen var vellykket",
	"PartialSuccessAudio": "Koblet til {partialDeviceName} med lydprofil men kan ikke koble til telefonprofil.",
	"PartialSuccessPhone": "Koblet til {partialDeviceName} med telefonprofil men kan ikke koble til lydprofil.",
	"PhoneAndAudio": "Telefon og lyd",
	"PhoneConnected": "Telefonen er koblet til",
	"PhoneConnectionLost": "Tel.forb. er brutt",
	"PhoneDisconnected": "Telefonen er koblet fra",
	"PhoneOnly": "Kun telefon",
	"RemoveDevice": "Fjern alle parede enheter",
	"RemovePairDevice": "Fjern paret enhet",
	"Retry": "Prøv på nytt",
	"SelectDeviceToRemove": "Velg enhet som skal fjernes",
	"Setting": "Innstillinger",
	"Settings": "Bluetooth innst.",
	"TimeLimitExceeded": "Tidsgrensen er overskredet",
	"UnableToRemove": "Kan ikke fjerne alle enheter",
	"UnknownError": "Ukjent feil",
	"Vehiclespeed": "Kjøretøyhastigheten er overskredet",
	"allDevices": "Alle enhetene er fjernet",
};

framework.registerAppDictLoaded("btpairing", "no_NO");