var Localization_btpairingAppDict_de_DE = {
	//"stringId" : "localString"
	"AddNewDevice": "Neues Gerät hinzufügen",
	"All": "Sind Sie sicher, Sie möchten alle entfernen?",
	"AudioConnected": "Bluetooth Audio verbunden",
	"AudioDisconnected": "Bluetooth Audio unterbrochen",
	"AudioOnly": "Nur Audio",
	"BTConnNotAvailableAppleCarPlay": "Keine Bluetooth-Verbindung für Geräte verfügbar, die mit Apple CarPlay verbunden sind.",
	"BTPairingDeleteiOS": "Löschen Sie das  \"Mazda\" BT Profil auf Ihrem iOS Gerät",
	"Back": "Zurück",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth-Verbindung",
	"BluetoothInformation": "Bluetooth-Informationen",
	"ChangePaircode": "Kopplungscode ändern",
	"ConfirmDelete": "Sind Sie sicher, dass Sie {deviceName} entfernen möchten?",
	"ConnectFailed": "Es konnte keine Verbindung hergestellt werden",
	"ConnectSuccess": "{deviceName} ist jetzt angeschlossen",
	"ConnectingDevice": "Verbindungaufbau zu {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth-Profil",
	"DeleteComplete": "{deviceName} entfernt",
	"DeleteDevice": "Geräteprofil wird entfernt",
	"DeleteFailed": "Kann {deviceName} nicht entfernen",
	"Disconnect": "Trennen",
	"DisconnectFailed": "Trennung von {deviceName} nicht möglich",
	"DisconnectSuccess": "{deviceName} ist jetzt getrennt",
	"DisconnectingDevice": "Trenne Verbindung zu {deviceName}",
	"DisconnectingToPair": "Verbindungsaufbau zu neuem Gerät",
	"Discoverable": "Suche nach {modelName} in Ihrem Bluetooth-Gerät.",
	"DiscoverableModel": "Suche nach {modelName} in Ihrem Bluetooth-Gerät.",
	"DiscoverableTimeout": "Sichtbar für ({discoverableTimeout}) Sekunden",
	"Enterpaircode": "Code eingeben",
	"InvalidCodeEntry": "Ungültige Code-Eingabe",
	"InvalidLegacyPIN": "Ungültige Codeeingabe. Prüfen Sie, ob der Code auf Mobilgerät und Hauptgerät gleich sind.",
	"MaxDevices": "Maximale Anzahl der zu unterstützten Geräte erreicht. Möchten Sie ein Gerät entfernen?",
	"Mazda": "Mazda",
	"Mobile911Enable": "112-Anruf auf Handy aktivieren?",
	"NoPairDisconnectFail": "Trennung von {deviceName} nicht möglich vor Verbindung mit neuem Gerät.",
	"NumericConfirmLegacy": "U.g. PIN auf dem Mobilgerät eingeben:",
	"NumericConfirmSSP": "Stimmt die u.g. Nr. mit der Nr. auf Ihrem Mobilgerät überein? Wenn ja, sind Sie bereit zum Verbinden.",
	"PairCancelling": "Verbindungsaufbau wird abgebrochen",
	"PairSuccess": "Kopplung abgeschlossen",
	"PairSuccessConnection": "Verbindung (im Aufbau)",
	"PairingDevice": "Gerät kann nicht verbunden werden",
	"PairingInProcess": "Verbindungsaufbau",
	"PairingInProcessConnection": "Verbindung (warte)",
	"PairingSuccess": "Koppelung erfolgreich",
	"PartialSuccessAudio": "Verbunden mit {partialDeviceName} und Audioprofil, konnte aber nicht mit dem Telefonprofil verbinden.",
	"PartialSuccessPhone": "Verbunden mit {partialDeviceName} und Telefonprofil, konnte aber nicht mit dem Audioprofil verbinden.",
	"PhoneAndAudio": "Telefon und Audio",
	"PhoneConnected": "Bluetooth Telefon verbunden",
	"PhoneConnectionLost": "Telefonverb. unterbrochen",
	"PhoneDisconnected": "Bluetooth Telefon unterbrochen",
	"PhoneOnly": "Nur Telefon",
	"RemoveDevice": "Alle gekop. Geräte entfernen",
	"RemovePairDevice": "Gekoppeltes Gerät entfernen",
	"Retry": "Erneut versuchen",
	"SelectDeviceToRemove": "Gerät zum Entfernen auswählen",
	"Setting": "Einstellungen",
	"Settings": "Bluetooth Einstellungen",
	"TimeLimitExceeded": "Zeitlimit überschritten",
	"UnableToRemove": "Entfernen aller Geräte unmöglich",
	"UnknownError": "Unbekannter Fehler",
	"Vehiclespeed": "Fahrzeuggeschwindigkeit überschritten",
	"allDevices": "Alle Geräte entfernt",
};

framework.registerAppDictLoaded("btpairing", "de_DE");