var Localization_btpairingAppDict_ar_SA = {
	//"stringId" : "localString"
	"AddNewDevice": "إضافة جهاز جديد",
	"All": "هل أنت متأكد من رغبتك في إزالة الكل؟",
	"AudioConnected": "وحدة الصوت متصلة",
	"AudioDisconnected": "وحدة الصوت غير متصلة",
	"AudioOnly": "الصوت فقط",
	"BTConnNotAvailableAppleCarPlay": "اتصال Bluetooth غير متوفر للأجهزة المتصلة بـ Apple CarPlay.",
	"BTPairingDeleteiOS": "احذف الملف التعريفي \"Mazda\" BT من الجهاز iOS الخاص بك.",
	"Back": "رجوع",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "اتصال Bluetooth",
	"BluetoothInformation": "بيانات Bluetooth",
	"ChangePaircode": "تغيير Paircode",
	"ConfirmDelete": "هل أنت متأكد من رغبتك في إزالة {deviceName}؟",
	"ConnectFailed": "تعذر توصيل الجهاز",
	"ConnectSuccess": "الآن {deviceName} متصل",
	"ConnectingDevice": "جارٍ اتصال {deviceName}",
	"ConnectoinTypeTitle": "م. تعريفBT {DeviceName}",
	"DeleteComplete": "تمت إزالة {deviceName}",
	"DeleteDevice": "إزالة الملف التعريفي للجهاز",
	"DeleteFailed": "تعذر إزالة {deviceName}",
	"Disconnect": "قطع الاتصال",
	"DisconnectFailed": "تعذر فصل اتصال {deviceName}",
	"DisconnectSuccess": "الآن {deviceName} غير متصل",
	"DisconnectingDevice": "فصل اتصال {deviceName}",
	"DisconnectingToPair": "الإعداد لإقران جهاز جديد جار",
	"Discoverable": "ابحث عن {modelName} في جهاز Bluetooth خاصتك",
	"DiscoverableModel": "ابحث عن {modelName} في جهاز Bluetooth خاصتك",
	"DiscoverableTimeout": "يمكن اكتشافه في ({discoverableTimeout}) ثانية",
	"Enterpaircode": "أدخل كود إقران",
	"InvalidCodeEntry": "إدخال الكود غير سارٍ",
	"InvalidLegacyPIN": "إدخال الكود غير سارٍ. تأكد من أن الكود الموجود على الجوال والوحدة واحد.",
	"MaxDevices": "تم دعم أقصى عدد من الأجهزة. هل ترغب في إزالة جهاز؟",
	"Mazda": "Mazda",
	"Mobile911Enable": "تمكين Mobile 911؟",
	"NoPairDisconnectFail": "لم يتمكن من فصل اتصال {deviceName} قبل إقران جهاز جديد. ",
	"NumericConfirmLegacy": "أدخل كود PIN الوارد أدناه على الهاتف الجوال:",
	"NumericConfirmSSP": "هل يطابق الرقم الوارد أدناه الرقم الموجود في هاتفك الجوال؟ إذا كان كذلك، فإنك مستعد للإقران.",
	"PairCancelling": "إلغاء الإقران جارٍ ",
	"PairSuccess": "اكتمل الاقتران",
	"PairSuccessConnection": "(جارٍ) الاتصال",
	"PairingDevice": "تعذر إقران الجهاز",
	"PairingInProcess": "الإقران جارٍ",
	"PairingInProcessConnection": "الاتصال (قيد الانتظار)",
	"PairingSuccess": "تم الإقران بنجاح",
	"PartialSuccessAudio": "متصل بـ{partialDeviceName} من خلال ملف الصوت التعريفي، لكن لا يمكن الاتصال بملف الهاتف التعريفي.",
	"PartialSuccessPhone": "متصل بـ{partialDeviceName} من خلال ملف الصوت التعريفي، لكن لا يمكن الاتصال بملف الصوت التعريفي.",
	"PhoneAndAudio": "الهاتف والصوت",
	"PhoneConnected": "الهاتف متصل",
	"PhoneConnectionLost": "فُقد الاتصال الهاتفي",
	"PhoneDisconnected": "الهاتف غير متصل",
	"PhoneOnly": "الهاتف فقط",
	"RemoveDevice": "إزالة جميع الأجهزة المقترنة",
	"RemovePairDevice": "إزالة الجهاز المقترن",
	"Retry": "أعد المحاولة",
	"SelectDeviceToRemove": "حدد الجهاز المراد إزالته",
	"Setting": "الإعدادات",
	"Settings": "إعدادات Bluetooth",
	"TimeLimitExceeded": "تم تخطي المهلة",
	"UnableToRemove": "لم يتمكن من إزالة جميع الأجهزة",
	"UnknownError": "خطأ غير معروف",
	"Vehiclespeed": "تم تخطي سرعة المركبة",
	"allDevices": "تمت إزالة جميع الأجهزة",
};

framework.registerAppDictLoaded("btpairing", "ar_SA");