var Localization_btpairingAppDict_cn_HK = {
	//"stringId" : "localString"
	"AddNewDevice": "新增新裝置",
	"All": "是否確定要全部移除？",
	"AudioConnected": "音訊已連線",
	"AudioDisconnected": "音訊已解除連線",
	"AudioOnly": "僅音訊",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth 連線不可用於連線至 Apple CarPlay 的裝置。",
	"BTPairingDeleteiOS": "從您的 iOS 裝置刪除「Mazda」BT 設定檔。",
	"Back": "取消",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth 連線",
	"BluetoothInformation": "Bluetooth 資訊",
	"ChangePaircode": "更改配對代碼",
	"ConfirmDelete": "確定要與 {deviceName}解除配對？",
	"ConnectFailed": "無法連接裝置",
	"ConnectSuccess": "{deviceName} 已連線",
	"ConnectingDevice": "正在連線 {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth 設定檔",
	"DeleteComplete": "{deviceName} 已解除配對",
	"DeleteDevice": "正在與裝置解除配對",
	"DeleteFailed": "無法解除配對 {deviceName}",
	"Disconnect": "解除連線",
	"DisconnectFailed": "無法斷開連線 {deviceName}",
	"DisconnectSuccess": "{deviceName} 已解除連線",
	"DisconnectingDevice": "正在解除 {deviceName} 連線",
	"DisconnectingToPair": "正在準備配對新裝置",
	"Discoverable": "在您的 Bluetooth 裝置中搜尋「{modelName}」。",
	"DiscoverableModel": "在您的行動裝置中搜尋 {modelName}。",
	"DiscoverableTimeout": "可被偵測 ({discoverableTimeout}) 秒",
	"Enterpaircode": "輸入配對碼",
	"InvalidCodeEntry": "輸入代碼無效",
	"InvalidLegacyPIN": "輸入代碼無效。 確保行動裝置與系統中的代碼一致。",
	"MaxDevices": "支援的裝置已達到最大數目。 是否要對裝置解除配對？",
	"Mazda": "Mazda",
	"Mobile911Enable": "啟用緊急救援呼叫？",
	"NoPairDisconnectFail": "在配對新裝置之前無法斷開連線 {deviceName}。",
	"NumericConfirmLegacy": "在行動裝置上輸入下方的配對碼：",
	"NumericConfirmSSP": "下方的數字是否與您行動裝置上的配對代碼相符？如果是，您已準備好配對。",
	"PairCancelling": "正在取消配對",
	"PairSuccess": "配對完畢",
	"PairSuccessConnection": "正在連接裝置",
	"PairingDevice": "無法配對裝置",
	"PairingInProcess": "配對進行中",
	"PairingInProcessConnection": "連線(等待中)",
	"PairingSuccess": "配對成功",
	"PartialSuccessAudio": "連接到帶有音訊設定檔的 {partialDeviceName} 但無法連接到電話設定檔。",
	"PartialSuccessPhone": "連接到帶有電話設定檔的 {partialDeviceName} 但無法連接到音訊設定檔。",
	"PhoneAndAudio": "手機和音訊",
	"PhoneConnected": "電話已連線",
	"PhoneConnectionLost": "失去 Bluetooth 連線",
	"PhoneDisconnected": "電話已解除連線",
	"PhoneOnly": "僅手機",
	"RemoveDevice": "對所有已配對裝置解除配對",
	"RemovePairDevice": "解除此裝置的配對",
	"Retry": "重試",
	"SelectDeviceToRemove": "選取要解除配對的裝置",
	"Setting": "設定",
	"Settings": "Bluetooth 設定",
	"TimeLimitExceeded": "超出时限",
	"UnableToRemove": "無法移除所有裝置",
	"UnknownError": "未知錯誤",
	"Vehiclespeed": "車辆超速",
	"allDevices": "全部裝置已移除",
};

framework.registerAppDictLoaded("btpairing", "cn_HK");