var Localization_btpairingAppDict_sv_SE = {
	//"stringId" : "localString"
	"AddNewDevice": "Lägg till ny enhet",
	"All": "Är du säker på att du vill ta bort allt?",
	"AudioConnected": "Ljud anslutet",
	"AudioDisconnected": "Ljud frånkopplat",
	"AudioOnly": "Enbart audio",
	"BTConnNotAvailableAppleCarPlay": "Anslutning via Bluetooth är inte tillgängligt för enheter som är anslutna till Apple CarPlay.",
	"BTPairingDeleteiOS": "Ta bort \"Mazda\" BT profilen från din iOS enhet.",
	"Back": "Tillbaka",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth-anslutning",
	"BluetoothInformation": "Bluetooth-information",
	"ChangePaircode": "Ändra parkopplingskod",
	"ConfirmDelete": "Vill du verkligen ta bort {deviceName} ?",
	"ConnectFailed": "Kan inte ansluta enhet",
	"ConnectSuccess": "{deviceName} är nu ansluten",
	"ConnectingDevice": "Ansluter {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth-profil",
	"DeleteComplete": "{deviceName} borttagen",
	"DeleteDevice": "Tar bort enhetsprofil",
	"DeleteFailed": "Kan inte ta bort {deviceName}",
	"Disconnect": "Koppla från",
	"DisconnectFailed": "Kan inte koppla från {deviceName}",
	"DisconnectSuccess": "{deviceName} är nu frånkopplad",
	"DisconnectingDevice": "Kopplar från {deviceName}",
	"DisconnectingToPair": "Förbereder parkoppling av ny enhet",
	"Discoverable": "Sök efter {modelName} på Bluetooth-enheter.",
	"DiscoverableModel": "Sök efter {modelName} på Bluetooth-enhet.",
	"DiscoverableTimeout": "Kan upptäckas i ({discoverableTimeout}) sek",
	"Enterpaircode": "Ange parkopplingskod",
	"InvalidCodeEntry": "Ogiltig kod angiven",
	"InvalidLegacyPIN": "Ogiltig kod angiven. Kontrollera att koden på mobila enheten och denna enhet är samma.",
	"MaxDevices": "Max antal enheter stöds redan. Vill du ta bort en enhet?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Aktivera mobil 112?",
	"NoPairDisconnectFail": "Kan inte koppla från {deviceName} innan ny enhet parkopplats.",
	"NumericConfirmLegacy": "Ange nedanstående PIN på mobila enheten:",
	"NumericConfirmSSP": "Stämmer numret nedan med numret på din mobila enhet? I så fall är det klart för parkoppling.",
	"PairCancelling": "Parkoppling avbryts",
	"PairSuccess": "Parkoppling genomförd",
	"PairSuccessConnection": "Anslutning (pågår)",
	"PairingDevice": "Kan inte parkoppla enhet",
	"PairingInProcess": "Parkoppling pågår",
	"PairingInProcessConnection": "Anslutning (väntar)",
	"PairingSuccess": "Parkoppling har genomförts",
	"PartialSuccessAudio": "Ansluten till {partialDeviceName} med audioprofil men kunde inte ansluta till telefonprofil.",
	"PartialSuccessPhone": "Ansluten till {partialDeviceName} med telefonprofil men kunde inte ansluta till audioprofil.",
	"PhoneAndAudio": "Telefon och ljud",
	"PhoneConnected": "Telefon ansluten",
	"PhoneConnectionLost": "Telefonanslutning bruten",
	"PhoneDisconnected": "Telefon frånkopplad",
	"PhoneOnly": "Enbart telefon",
	"RemoveDevice": "Ta bort alla parkopplade enheter",
	"RemovePairDevice": "Ta bort parkopplad enhet",
	"Retry": "Prova igen",
	"SelectDeviceToRemove": "Markera enhet att ta bort",
	"Setting": "Inställningar",
	"Settings": "Bluetooth-inställning",
	"TimeLimitExceeded": "Tidsgräns överskriden",
	"UnableToRemove": "Kan inte avlägsna alla enheter",
	"UnknownError": "Okänt fel",
	"Vehiclespeed": "Fordonshastighet överskriden",
	"allDevices": "Alla enheter borttagna",
};

framework.registerAppDictLoaded("btpairing", "sv_SE");