var Localization_btpairingAppDict_tr_TR = {
	//"stringId" : "localString"
	"AddNewDevice": "Yeni Aygıt Ekle",
	"All": "All kaldirmak istediginizden emin misiniz?",
	"AudioConnected": "Ses Bağlandı",
	"AudioDisconnected": "Ses Bağlantısı Kesildi",
	"AudioOnly": "Yalnızca ses",
	"BTConnNotAvailableAppleCarPlay": "Apple CarPlay'e bağlı cihazlar için Bluetooth bağlantısı mevcut değil.",
	"BTPairingDeleteiOS": "\"Mazda\" BT profilini iOS cihazınızdan silin.",
	"Back": "Geri",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth Bağlantısı",
	"BluetoothInformation": "Bluetooth Bilgisi",
	"ChangePaircode": "Eşleştirme Kodunu Değiştir",
	"ConfirmDelete": "{deviceName} aygıtını kaldırmak istediğinizden emin misiniz?",
	"ConnectFailed": "Aygıt Bağlanamıyor",
	"ConnectSuccess": "{deviceName} Simdi Bağlandı",
	"ConnectingDevice": "{deviceName} bağlanıyor",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth Profili",
	"DeleteComplete": "{deviceName} kaldırıldı",
	"DeleteDevice": "Aygıt Profili Kaldırılıyor",
	"DeleteFailed": "{deviceName} Kaldırılamadı",
	"Disconnect": "Bağlantıyı Kes",
	"DisconnectFailed": "{deviceName} Bağlantısı Kesilemedi",
	"DisconnectSuccess": "{deviceName}  Cihazının Bağlantısı Kesildi",
	"DisconnectingDevice": "{deviceName} bağlantısı kesiliyor",
	"DisconnectingToPair": "Yeni bir aygıt eşleştirilmeye hazırlanılıyor",
	"Discoverable": "Bluetooth aygıtınızda {modelName} kelimesini arayın.",
	"DiscoverableModel": "Bluetooth aygıtınızda {modelName} arayın",
	"DiscoverableTimeout": "({discoverableTimeout}) saniyede bulunabilir",
	"Enterpaircode": "Kodunu Girin",
	"InvalidCodeEntry": "Geçersiz kod girişi",
	"InvalidLegacyPIN": "Geçersiz kod girişi. Mobil aygıtınızdaki ve ünitedeki kodların aynı olduğunu kontrol edin.",
	"MaxDevices": "Desteklenen maksimum aygıt sayısı. Bir aygıtı kaldırmak ister misiniz?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Mobil 112 etkinleştirilsin mi?",
	"NoPairDisconnectFail": "Yeni aygıt eşleştirilmeden {deviceName} aygıtının bağlantısı kesilemiyor.",
	"NumericConfirmLegacy": "PIN'i aşağıya mobil aygıta gir:",
	"NumericConfirmSSP": "Aşağıdaki numara, mobil aygıtınızdaki numarayla uyuyor mu? Uyuyorsa, eşleştirmeye hazırsınız.",
	"PairCancelling": "Eşleştirme İptal Ediliyor",
	"PairSuccess": "Eşleştirme Tamamlandı",
	"PairSuccessConnection": "Bağlantı (devam ediyor)",
	"PairingDevice": "Aygıt Eşleştirilemiyor",
	"PairingInProcess": "Eşleştirme Devam Ediyor",
	"PairingInProcessConnection": "Bağlantı (bekliyor)",
	"PairingSuccess": "Eşleştirme Başarılı",
	"PartialSuccessAudio": "{partialDeviceName} aygıtına ses profiliyle bağlanıldı, ancak telefon profiline bağlanılamıyor.",
	"PartialSuccessPhone": "{partialDeviceName} aygıtına telefon profiliyle bağlanıldı, ancak ses profiline bağlanılamıyor.",
	"PhoneAndAudio": "Telefon Ve Ses",
	"PhoneConnected": "Telefon Bağlı",
	"PhoneConnectionLost": "Telefon Bağlantısı Kesintisi",
	"PhoneDisconnected": "Telefon Kesildi",
	"PhoneOnly": "Yalnızca telefon",
	"RemoveDevice": "Tüm Eşleştirilen Aygıtları Kaldır",
	"RemovePairDevice": "Eşleştirilen Aygıtı Kaldır",
	"Retry": "Yeniden Dene",
	"SelectDeviceToRemove": "Kaldırılacak aygıtı seçin",
	"Setting": "Ayarlar",
	"Settings": "Bluetooth Ayarları",
	"TimeLimitExceeded": "Süre sınırı aşıldı",
	"UnableToRemove": "Tüm aygitlari kaldirin yapilamiyor",
	"UnknownError": "Bilinmeyen hata",
	"Vehiclespeed": "Araç hızı aşıldı",
	"allDevices": "Tüm Aygıtlar Kaldırıldı",
};

framework.registerAppDictLoaded("btpairing", "tr_TR");