var Localization_btpairingAppDict_fi_FI = {
	//"stringId" : "localString"
	"AddNewDevice": "Lisää uusi laite",
	"All": "Oletko varma, että haluat poistaa kaikki?",
	"AudioConnected": "Audiolähde liitetty",
	"AudioDisconnected": "Audiolähde irrotettu",
	"AudioOnly": "Vain audiolähde",
	"BTConnNotAvailableAppleCarPlay": "Bluetooth-yhteys ei ole käytettävissä laitteilla, jotka on yhdistetty Apple CarPlayhin.",
	"BTPairingDeleteiOS": "Poista \"Mazda\" BT-profiili iOS-laitteeltasi.",
	"Back": "Takaisin",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Bluetooth-yhteys",
	"BluetoothInformation": "Bluetooth-tiedot",
	"ChangePaircode": "Vaihda laiteparikoodi",
	"ConfirmDelete": "Haluatko varmasti poistaa laitteen {deviceName}?",
	"ConnectFailed": "Laiteparin muodostaminen ei onnistu",
	"ConnectSuccess": "{deviceName} yhdistetty laitepariksi",
	"ConnectingDevice": "Yhdistetään laitetta {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Bluetooth-profiili",
	"DeleteComplete": "{deviceName} poistettu",
	"DeleteDevice": "Laiteprofiilia poistetaan",
	"DeleteFailed": "Laitteen {deviceName} poistaminen epäonnistui",
	"Disconnect": "Katkaise yhteys",
	"DisconnectFailed": "Laitteen {deviceName} yhteyden katkaiseminen epäonnistui",
	"DisconnectSuccess": "{deviceName} poistettu laiteparista",
	"DisconnectingDevice": "Katkaistaan yhteys: {deviceName}",
	"DisconnectingToPair": "Valm. uuden laitteen liittäm. laitepariksi",
	"Discoverable": "Etsi {modelName} omista Bluetooth-laitteista.",
	"DiscoverableModel": "Etsi laitetta {modelName} omasta Bluetooth-laitteestasi.",
	"DiscoverableTimeout": "Havaittavissa ({discoverableTimeout}) sekunnin ajan",
	"Enterpaircode": "Anna laiteparikoodi",
	"InvalidCodeEntry": "Annettu koodi on virheellinen",
	"InvalidLegacyPIN": "Annettu koodi on virheellinen. Tarkista, että mobiililaitteen ja laitteen koodit täsmäävät.",
	"MaxDevices": "Tuettujen laitteiden enimmäismäärä saavutettu. Haluatko poistaa laitteen?",
	"Mazda": "Mazda",
	"Mobile911Enable": "{deviceName} poistettu",
	"NoPairDisconnectFail": "Laitteeseen {deviceName} ei voi yhdistää ennen kuin uusi laite liitetään laitepariksi.",
	"NumericConfirmLegacy": "Syötä alla oleva PIN-koodi mobiililaitteeseen:",
	"NumericConfirmSSP": "Vastaako alla oleva numero mobiililaitteesi numeroa? Jos se vastaa, voit muodostaa laiteparin.",
	"PairCancelling": "Laiteparin muodostaminen peruutetaan",
	"PairSuccess": "Laitepari muodostettu",
	"PairSuccessConnection": "Yhdistäminen (käynnissä)",
	"PairingDevice": "Laiteparin muodostaminen ei onnistu",
	"PairingInProcess": "Muodostetaan laiteparia",
	"PairingInProcessConnection": "Yhteys (odottaa)",
	"PairingSuccess": "Laiteparin muodostaminen onnistui",
	"PartialSuccessAudio": "Liitetty audioprofiilina laitteeseen {partialDeviceName}, mutta puhelinprofiilia ei voitu liittää.",
	"PartialSuccessPhone": "Liitetty puhelinprofiilina laitteeseen {partialDeviceName}, mutta audioprofiilia ei voitu liittää.",
	"PhoneAndAudio": "Puhelin ja audiolähde",
	"PhoneConnected": "Puhelin kytketty",
	"PhoneConnectionLost": "Yhteys puhelimeen katkesi",
	"PhoneDisconnected": "Puhelin irrotettu",
	"PhoneOnly": "Vain puhelin",
	"RemoveDevice": "Poista kaikki pariksi liitetyt laitt.",
	"RemovePairDevice": "Poista laitepariksi liitetty laite",
	"Retry": "Yritä uudelleen",
	"SelectDeviceToRemove": "Valitse irrotettava laite",
	"Setting": "Asetukset",
	"Settings": "Bluetooth-asetukset",
	"TimeLimitExceeded": "Aikaraja ylittyi",
	"UnableToRemove": "Kaikkien laitteiden poistaminen ei onnistunut",
	"UnknownError": "Tuntematon virhe",
	"Vehiclespeed": "Auton nopeusrajoitus ylittyi",
	"allDevices": "Kaikki laitteet poistettu",
};

framework.registerAppDictLoaded("btpairing", "fi_FI");