var Localization_btpairingAppDict_ms_MY = {
	//"stringId" : "localString"
	"AddNewDevice": "Tambah Peranti Baharu",
	"All": "Adakah anda pasti anda mahu memadam Semua?",
	"AudioConnected": "Audio Disambungkan",
	"AudioDisconnected": "Audio Tidak Disambungkan",
	"AudioOnly": "Audio sahaja",
	"BTConnNotAvailableAppleCarPlay": "Sambungan Bluetooth tidak tersedia untuk peranti yang disambungkan ke Apple CarPlay.",
	"BTPairingDeleteiOS": "Hapus profil \"Mazda\" BT dari peranti iOS anda.",
	"Back": "Kembali",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Sambungan Bluetooth",
	"BluetoothInformation": "Maklumat Bluetooth",
	"ChangePaircode": "Tukar Kod Pasangan",
	"ConfirmDelete": "Adakah anda pasti mahu mengalih keluar {deviceName}",
	"ConnectFailed": "Tidak Dapat Menyambungkan Peranti",
	"ConnectSuccess": "{deviceName} Kini Disambungkan",
	"ConnectingDevice": "Menyambungkan {deviceName}",
	"ConnectoinTypeTitle": "Profil Bluetooth {DeviceName}",
	"DeleteComplete": "{deviceName} dialih keluar",
	"DeleteDevice": "Mengalih Keluar Profil Peranti",
	"DeleteFailed": "Tidak Dapat Mengalih Keluar {deviceName}",
	"Disconnect": "Putuskan Sambungan",
	"DisconnectFailed": "Tidak dapat Memutuskan Sambungan {deviceName}",
	"DisconnectSuccess": "{deviceName} Kini Diputuskan Sambungan",
	"DisconnectingDevice": "Memutuskan sambungan {deviceName}",
	"DisconnectingToPair": "Bersedia utk pasangkan peranti baharu",
	"Discoverable": "Cari {modelName} dalam peranti Bluetooth anda.",
	"DiscoverableModel": "Cari {modelName} dalam peranti Bluetooth anda.",
	"DiscoverableTimeout": "Timeout ({discoverableTimeout}) saat",
	"Enterpaircode": "Masukkan Kod",
	"InvalidCodeEntry": "Masukan kod tidak sah",
	"InvalidLegacyPIN": "Kod yang dimasukkan tidak sah. Semak samada kod pada peranti mudah alih dan unit adalah sama.",
	"MaxDevices": "Jumlah peranti maksimum disokong. Adakah anda ingin mengalih keluar peranti?",
	"Mazda": "Mazda",
	"Mobile911Enable": "Dayakan 911 Mudah Alih?",
	"NoPairDisconnectFail": "Tidak dapat memutuskan hubungan {deviceName} sebelum memasangkan peranti baharu.",
	"NumericConfirmLegacy": "Masukkan PIN di bawah pada peranti mudah alih.",
	"NumericConfirmSSP": "Adakah nombor di bawah padan dgn nombor peranti m/alih anda? Jika ya, anda  bersedia utk memasang.",
	"PairCancelling": "Membatalkan Berpasangan",
	"PairSuccess": "Berpasangan Selesai",
	"PairSuccessConnection": "Sambungan (sedang dijalankan)",
	"PairingDevice": "Tidak Dapat Memasangkan Peranti",
	"PairingInProcess": "Berpasangan sedang Dijalankan",
	"PairingInProcessConnection": "Sambungan (menunggu)",
	"PairingSuccess": "Berpasangan Berjaya",
	"PartialSuccessAudio": "Disambungkan pada {partialDeviceName} dengan profil audio, tetapi tidak dapat bersambung pada profil telefon.",
	"PartialSuccessPhone": "Disambungkan pada {partialDeviceName} dengan profil telefon, tetapi tidak dapat bersambung pada profil audio.",
	"PhoneAndAudio": "Telefon Dan Audio",
	"PhoneConnected": "Telefon Disambungkan",
	"PhoneConnectionLost": "Sambungan Tel. Terputus",
	"PhoneDisconnected": "Telefon Terputus Sambungan",
	"PhoneOnly": "Telefon sahaja",
	"RemoveDevice": "Keluar Semua Pasangan Peranti",
	"RemovePairDevice": "Keluarkan Peranti Dipasangkan",
	"Retry": "Cuba semula",
	"SelectDeviceToRemove": "Pilih peranti untuk dialih keluar",
	"Setting": "Tetapan",
	"Settings": "Tetapan Bluetooth",
	"TimeLimitExceeded": "Melebihi had masa",
	"UnableToRemove": "Tidak dapat buang semua peranti",
	"UnknownError": "Ralat tidak diketahui",
	"Vehiclespeed": "Melebih kelajuan kenderaan",
	"allDevices": "Semua Peranti Dialih Keluar",
};

framework.registerAppDictLoaded("btpairing", "ms_MY");