var Localization_btpairingAppDict_es_ES = {
	//"stringId" : "localString"
	"AddNewDevice": "Añadir nuevo dispositivo",
	"All": "¿Está seguro de que desea eliminar todo?",
	"AudioConnected": "Audio conectado",
	"AudioDisconnected": "Audio desconectado",
	"AudioOnly": "Sólo audio",
	"BTConnNotAvailableAppleCarPlay": "No está disponible la conexión Bluetooth para dispositivos conectados a Apple CarPlay.",
	"BTPairingDeleteiOS": "Borrar el perfil de \"Mazda\" BT de su dispositivo iOS.",
	"Back": "Volver",
	"Bluetooth": "Bluetooth",
	"BluetoothConnection": "Conexión Bluetooth",
	"BluetoothInformation": "Información sobre Bluetooth",
	"ChangePaircode": "Camb. Código emparejamiento",
	"ConfirmDelete": "¿Está seguro de que desea eliminar {deviceName}?",
	"ConnectFailed": "No se puede Conectar el Dispositivo",
	"ConnectSuccess": "{deviceName} está Ahora Conectado",
	"ConnectingDevice": "Conectando {deviceName}",
	"ConnectoinTypeTitle": "{DeviceName} Perfil Bluetooth",
	"DeleteComplete": "{deviceName} eliminado",
	"DeleteDevice": "Eliminando Perfil de Disp.",
	"DeleteFailed": "No se puede Eliminar {deviceName} ",
	"Disconnect": "Desconectar",
	"DisconnectFailed": "No se puede Desconectar {deviceName}",
	"DisconnectSuccess": "{deviceName} está Ahora Desconectado",
	"DisconnectingDevice": "Desconectando {deviceName}",
	"DisconnectingToPair": "Prepar. para emparejar nuevo disp.o",
	"Discoverable": "Buscar {modelName} en su dispositivo Bluetooth.",
	"DiscoverableModel": "Buscar {modelName} en su dispositivo Bluetooth.",
	"DiscoverableTimeout": "Visible por ({discoverableTimeout}) seg",
	"Enterpaircode": "Introduzca el código",
	"InvalidCodeEntry": "Entrada de código inválida",
	"InvalidLegacyPIN": "Entrada de código no válida. Verifique que el código en el dispositivo móvil y la unidad son los mismos.",
	"MaxDevices": "Número máximo de dispositivos admitidos. ¿Desea eliminar un dispositivo?",
	"Mazda": "Mazda",
	"Mobile911Enable": "¿Habilitar 911 Móvil?",
	"NoPairDisconnectFail": "Imposible puede desconectar {deviceName} antes de emparejar el nuevo dispositivo.",
	"NumericConfirmLegacy": "Introduzca el PIN de abajo en el dispositivo móvil",
	"NumericConfirmSSP": "¿El número de abajo coincide con el número en su dispositivo móvil? De ser así, está listo para emparejar.",
	"PairCancelling": "Cancelando Emparejamiento",
	"PairSuccess": "Emparejamiento Completo",
	"PairSuccessConnection": "Conexión (en curso)",
	"PairingDevice": "No se puede emparejar dispositivo",
	"PairingInProcess": "Emparejamiento en proceso",
	"PairingInProcessConnection": "Conectando (esperando)",
	"PairingSuccess": "Emparejamiento con éxito",
	"PartialSuccessAudio": "Conectado a {partialDeviceName} con perfil de audio, pero no se puede conectar al perfil del teléfono.",
	"PartialSuccessPhone": "Conectado a {partialDeviceName} con perfil del teléfono, pero no se puede conectar al perfil de audio.",
	"PhoneAndAudio": "Teléfono y audio",
	"PhoneConnected": "Teléfono conectado",
	"PhoneConnectionLost": "Conexión Tel Perdida",
	"PhoneDisconnected": "Teléfono desconectado",
	"PhoneOnly": "Sólo teléfono",
	"RemoveDevice": "Eliminar Disp emparejados",
	"RemovePairDevice": "Eliminar Disp. Emparejado",
	"Retry": "Reintentar ",
	"SelectDeviceToRemove": "Seleccione dispositivo a eliminar",
	"Setting": "Configuraciones",
	"Settings": "Ajustes Bluetooth",
	"TimeLimitExceeded": "Límite de tiempo excedido",
	"UnableToRemove": "No se pueden quitar todos los dispositivos",
	"UnknownError": "Error desconocido",
	"Vehiclespeed": "Velocidad de vehículo excedida",
	"allDevices": "Todos los dispositivos han sido eliminados.",
};

framework.registerAppDictLoaded("btpairing", "es_ES");