var Localization_usbaudioAppDict_fr_CN = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Désambiguïsation de l’album",
	"Albums": "Albums",
	"AllAlbums": "Tous les albums",
	"AllArtists": "Tous les artistes",
	"AllChapters": "Tous les chapitres",
	"AllEpisodes": "Tous les épisodes",
	"AllSongs": "Tous les morceaux ",
	"Artist": "Artiste",
	"Artists": "Artistes",
	"Audiobook": "Livre audio",
	"Audiobooks": "Livres audio",
	"AuthenticationFailure": "Erreur d'authentification",
	"AuthenticationFailureSBN": "Erreur d'authentification",
	"Folder": "Dossier",
	"Folders": "Dossiers",
	"Genre": "Genre",
	"Genres": "Genres",
	"IncompatibleFirmware": "Micrologiciel incompatible",
	"IncompatibleFirmwareSBN": "Firmware incompatible",
	"NoPlayableFiles": "Aucun fichier lisible",
	"NotSupported": "Dispositif non accepté",
	"NotSupportedSBN": "Dispositif non accepté",
	"Playlist": "Liste de titres",
	"Playlists": "Listes de titres",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Menu racine",
	"Song": "Morceau",
	"Songs": "Morceaux",
	"Tooltip_IcnUmpCurrentList": "Liste des morceaux",
	"USB1Connected": "USB1 : {usbName} Connecté",
	"USB1Disconnected": "USB1 : {usbName} Déconnecté",
	"USB2Connected": "USB2 : {usbName} Connecté",
	"USB2Disconnected": "USB2 : {usbName} Déconnecté",
	"USBDisconnected": "Dispositif USB déconnecté",
	"USBDisconnectedSBN": "USB déconnecté",
	"UnknownType": "Type d’USB inconnu",
	"VrHelp_NowPlaying_Help_Left1": "Divertissements",
	"VrHelp_NowPlaying_Help_Left2": " Menu racine",
	"VrHelp_NowPlaying_Help_Left3": "Liste des morceaux",
	"VrHelp_NowPlaying_Help_Left4": " Lecture en Boucle",
	"VrHelp_NowPlaying_Help_Left5": "Lecture en Boucle Toutes",
	"VrHelp_NowPlaying_Help_Right1": " Lecture aléatoire",
	"VrHelp_NowPlaying_Help_Right2": "Autres similaires",
	"VrHelp_NowPlaying_Help_Right3": "Précédent / Suivant",
	"VrHelp_NowPlaying_Help_Right4": "Lire/Pause",
	"VrHelp_NowPlaying_Help_Right5": "Paramètres audio",
	"VrHelp_USBAudio_Help_Left1": "Liste de titres",
	"VrHelp_USBAudio_Help_Left2": "Artiste",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Morceau",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Dossiers",
	"VrHelp_USBAudio_Help_Right2": "Tout lire",
	"moreLikeThis": "Autres similaires",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "fr_CN");