var Localization_usbaudioAppDict_el_GR = {
	//"stringId" : "localString"
	"Album": "Άλμπουμ",
	"AlbumDisambiguation": "Διασαφήνιση άλμπουμ",
	"Albums": "Άλμπουμ",
	"AllAlbums": "Όλα τα άλμπουμ",
	"AllArtists": "Όλοι οι καλλιτέχνες",
	"AllChapters": "Όλα τα κεφάλαια",
	"AllEpisodes": "Όλα τα επεισόδια",
	"AllSongs": "Όλα τα τραγούδια",
	"Artist": "Καλλιτέχνης",
	"Artists": "Καλλιτέχνες",
	"Audiobook": "Ηχητικό βιβλίο",
	"Audiobooks": "Ηχητικά βιβλία",
	"AuthenticationFailure": "Αποτυχία επικύρωσης",
	"AuthenticationFailureSBN": "Αποτυχία εξακρίβωσης γνησιότητας",
	"Folder": "Φάκελος",
	"Folders": "Φάκελοι",
	"Genre": "Είδος",
	"Genres": "Είδη",
	"IncompatibleFirmware": "Το υλικολογισμικό είναι ασύμβατο",
	"IncompatibleFirmwareSBN": "Το υλικολογισμικό είναι ασύμβατο",
	"NoPlayableFiles": "Κανένα αρχ. δεν μπορεί να αναπ.",
	"NotSupported": "Η συσκευή δεν υποστηρίζεται",
	"NotSupportedSBN": "Η συσκευή δεν υποστηρίζεται",
	"Playlist": "Λίστα αναπαραγωγής",
	"Playlists": "Λίστες αναπαραγωγής",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Κύριο Μενού",
	"Song": "Τραγούδι",
	"Songs": "Τραγούδια",
	"Tooltip_IcnUmpCurrentList": "Λίστα τραγουδιών",
	"USB1Connected": "USB1: {usbName} Συνδεδεμένο",
	"USB1Disconnected": "USB1: {usbName} Αποσυνδεδεμένο",
	"USB2Connected": "USB2: {usbName} Συνδεδεμένο",
	"USB2Disconnected": "USB2: {usbName} Αποσυνδεδεμένο",
	"USBDisconnected": "Συσκευή USB αποσυνδέθηκε",
	"USBDisconnectedSBN": "Συσκευή USB αποσυνδέθηκε",
	"UnknownType": "Άγνωστος τύπος USB ",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "Κι άλλα παρόμοια",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "el_GR");