var Localization_usbaudioAppDict_no_NO = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Forklaring, album",
	"Albums": "Album",
	"AllAlbums": "Alle album",
	"AllArtists": "Alle artister",
	"AllChapters": "Alle kapitler",
	"AllEpisodes": "Alle episoder",
	"AllSongs": "Alle sanger",
	"Artist": "Artist",
	"Artists": "Artister",
	"Audiobook": "Lydbok",
	"Audiobooks": "Lydbøker",
	"AuthenticationFailure": "Autentisering mislyktes",
	"AuthenticationFailureSBN": "Autentisering mislyktes",
	"Folder": "Mappe",
	"Folders": "Mapper",
	"Genre": "Sjanger",
	"Genres": "Sjangere",
	"IncompatibleFirmware": "Fastvaren er uforenlig",
	"IncompatibleFirmwareSBN": "Firmware Incompatible",
	"NoPlayableFiles": "Ingen spillbare filer",
	"NotSupported": "Enheten støttes ikke",
	"NotSupportedSBN": "Enheten støttes ikke",
	"Playlist": "Spilleliste",
	"Playlists": "Spillelister",
	"Podcast": "Podcast",
	"Podcasts": "Podcaster",
	"RootMenu": "Hovedmeny",
	"Song": "Sang",
	"Songs": "Sanger",
	"Tooltip_IcnUmpCurrentList": "Sangliste",
	"USB1Connected": "USB1: {usbName} koblet til",
	"USB1Disconnected": "USB1: {usbName} koblet fra",
	"USB2Connected": "USB2: {usbName} koblet til",
	"USB2Disconnected": "USB2: {usbName} koblet fra",
	"USBDisconnected": "USB-enhet frakoblet",
	"USBDisconnectedSBN": "USB frakoblet",
	"UnknownType": "USB-typen er ukjent",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "Mer som dette",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "no_NO");