var Localization_usbaudioAppDict_th_TH = {
	//"stringId" : "localString"
	"Album": "อัลบั้ม",
	"AlbumDisambiguation": "การจำแนกประเภทอัลบั้ม",
	"Albums": "อัลบั้ม",
	"AllAlbums": "อัลบั้มทั้งหมด",
	"AllArtists": "ศิลปินทั้งหมด",
	"AllChapters": "บททั้งหมด",
	"AllEpisodes": "ตอนทั้งหมด",
	"AllSongs": "เพลงทั้งหมด",
	"Artist": "ศิลปิน",
	"Artists": "ศิลปิน",
	"Audiobook": "หนังสือเสียง",
	"Audiobooks": "หนังสือเสียง",
	"AuthenticationFailure": "ไม่สามารถพิสูจน์ตัวตนได้",
	"AuthenticationFailureSBN": "ไม่สามารถพิสูจน์ตัวตนได้",
	"Folder": "โฟลเดอร์",
	"Folders": "โฟลเดอร์",
	"Genre": "ประเภท",
	"Genres": "ประเภท",
	"IncompatibleFirmware": "เฟิร์มแวร์ไม่สามารถทำงานร่วมกันได้",
	"IncompatibleFirmwareSBN": "เฟิร์มแวร์ไม่สามารถทำงานร่วมกันได้",
	"NoPlayableFiles": "ไม่มีไฟล์ที่เล่นได้",
	"NotSupported": "ไม่รองรับอุปกรณ์",
	"NotSupportedSBN": "ไม่รองรับอุปกรณ์",
	"Playlist": "เพลย์ลิสต์",
	"Playlists": "เพลย์ลิสต์",
	"Podcast": "พอดคาสต์",
	"Podcasts": "พอดคาสต์",
	"RootMenu": "เมนูเริ่มต้น",
	"Song": "เพลง",
	"Songs": "เพลง",
	"Tooltip_IcnUmpCurrentList": "รายชื่อเพลง",
	"USB1Connected": "USB 1: เชื่อมต่อ{usbName} แล้ว",
	"USB1Disconnected": "USB 1: เลิกเชื่อมต่อ{usbName}แล้ว",
	"USB2Connected": "USB 2: เชื่อมต่อ{usbName} แล้ว",
	"USB2Disconnected": "USB 2: เลิกเชื่อมต่อ{usbName} แล้ว",
	"USBDisconnected": "ยกเลิกการเชื่อมต่ออุปกรณ์ USB แล้ว",
	"USBDisconnectedSBN": "ยกเลิกการเชื่อมต่อ USB แล้ว",
	"UnknownType": "ไม่รู้จักประเภทของ USB นี้",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "เพลงประเภทเดียวกัน",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "th_TH");