var Localization_usbaudioAppDict_ms_MY = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Penyahtaksaan Album",
	"Albums": "Album",
	"AllAlbums": "Semua Album",
	"AllArtists": "Semua Artis",
	"AllChapters": "Semua Bab",
	"AllEpisodes": "Semua Episod",
	"AllSongs": "Semua Lagu",
	"Artist": "Artis",
	"Artists": "Artis",
	"Audiobook": "Buku Audio",
	"Audiobooks": "Buku Audio",
	"AuthenticationFailure": "Kegagalan Pengesahan",
	"AuthenticationFailureSBN": "Pengesahan Gagal",
	"Folder": "Folder",
	"Folders": "Folder",
	"Genre": "Genre",
	"Genres": "Genre",
	"IncompatibleFirmware": "Perisian Tegar Tidak Serasi",
	"IncompatibleFirmwareSBN": "Perisian Tegar Tidak Serasi",
	"NoPlayableFiles": "Tiada Fail Boleh Main",
	"NotSupported": "Peranti Tidak Disokong",
	"NotSupportedSBN": "Peranti Tidak Disokong",
	"Playlist": "Senarai Main",
	"Playlists": "Senarai Main",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Menu Punca",
	"Song": "Lagu",
	"Songs": "Lagu",
	"Tooltip_IcnUmpCurrentList": "Senarai Lagu",
	"USB1Connected": "USB1: {usbName} Disambungkan",
	"USB1Disconnected": "USB1: {usbName} Ditanggalkan",
	"USB2Connected": "USB2: {usbName} Disambungkan",
	"USB2Disconnected": "USB2: {usbName} Ditanggalkan",
	"USBDisconnected": "Peranti USB Ditanggalkan",
	"USBDisconnectedSBN": "USB Ditanggalkan",
	"UnknownType": "Jenis USB Tidak Diketahui",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "Lagi Seperti Ini",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "ms_MY");