var Localization_usbaudioAppDict_sk_SK = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Album – odstránenie dvojzmyslov",
	"Albums": "Albumy",
	"AllAlbums": "Všetky albumy",
	"AllArtists": "Všetci interpreti",
	"AllChapters": "Všetky kapitoly",
	"AllEpisodes": "Všetky epizódy",
	"AllSongs": "Všetky skladby ",
	"Artist": "Umelec",
	"Artists": "Interpreti",
	"Audiobook": "Audiokniha",
	"Audiobooks": "Audioknihy",
	"AuthenticationFailure": "Porucha autentifikácie",
	"AuthenticationFailureSBN": "Autentifikácia zlyhala",
	"Folder": "Priečinok",
	"Folders": "Adresáre",
	"Genre": "Žáner",
	"Genres": "Žánre",
	"IncompatibleFirmware": "Firmvér je nekompatibilný",
	"IncompatibleFirmwareSBN": "Nekompatibilný firmvér",
	"NoPlayableFiles": "Žiadne súbory na prehrávanie",
	"NotSupported": "Zariadenie nepodporované",
	"NotSupportedSBN": "Zariadenie nepodporované",
	"Playlist": "Playlist",
	"Playlists": "Zoznamy skladieb",
	"Podcast": "Podcast",
	"Podcasts": "Podcasty",
	"RootMenu": "Základná ponuka",
	"Song": "Skladba",
	"Songs": "Piesne",
	"Tooltip_IcnUmpCurrentList": "Zoznam skladieb",
	"USB1Connected": "USB1: {usbName} pripojené",
	"USB1Disconnected": "USB1: {usbName} odpojené",
	"USB2Connected": "USB2: {usbName} pripojené",
	"USB2Disconnected": "USB2: {usbName} odpojené",
	"USBDisconnected": "USB zariadenie odpojené",
	"USBDisconnectedSBN": "USB odpojené",
	"UnknownType": "Neznámy typ USB",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "Ďalšie podobné",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "sk_SK");