var Localization_usbaudioAppDict_it_IT = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Disambiguazione album",
	"Albums": "Album",
	"AllAlbums": "Tutti gli album",
	"AllArtists": "Tutti gli artisti",
	"AllChapters": "Tutti i capitoli",
	"AllEpisodes": "Tutti gli episodi",
	"AllSongs": "Tutte le canzoni ",
	"Artist": "Artista",
	"Artists": "Artisti",
	"Audiobook": "Audiolibro",
	"Audiobooks": "Audiolibri",
	"AuthenticationFailure": "Autenticazione non riuscita.",
	"AuthenticationFailureSBN": "Autenticazione non riuscita.",
	"Folder": "Cartella",
	"Folders": "Cartelle",
	"Genre": "Genere",
	"Genres": "Generi",
	"IncompatibleFirmware": "Il firmware è incompatibile.",
	"IncompatibleFirmwareSBN": "Firmware incompatibile.",
	"NoPlayableFiles": "Nessun file riproducibile.",
	"NotSupported": "Dispositivo non supportato.",
	"NotSupportedSBN": "Dispositivo non supportato.",
	"Playlist": "Playlist",
	"Playlists": "Playlist",
	"Podcast": "Podcast",
	"Podcasts": "Podcast",
	"RootMenu": "Menù principale",
	"Song": "Canzone",
	"Songs": "Canzoni",
	"Tooltip_IcnUmpCurrentList": "Elenco canzoni",
	"USB1Connected": "USB1: {usbName} Connesso",
	"USB1Disconnected": "USB1: {usbName} disconnesso",
	"USB2Connected": "USB2: {usbName} Connesso",
	"USB2Disconnected": "USB2: {usbName} disconnesso",
	"USBDisconnected": "Dispositivo USB disconnesso.",
	"USBDisconnectedSBN": "USB disconnesso",
	"UnknownType": "Tipologia USB sconosciuta",
	"VrHelp_NowPlaying_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_Help_Left2": "Menu principale",
	"VrHelp_NowPlaying_Help_Left3": "Elenco canzoni",
	"VrHelp_NowPlaying_Help_Left4": "Ripeti",
	"VrHelp_NowPlaying_Help_Left5": "Ripeti tutti",
	"VrHelp_NowPlaying_Help_Right1": "Riproduzione casuale",
	"VrHelp_NowPlaying_Help_Right2": "Riproduzione casuale",
	"VrHelp_NowPlaying_Help_Right3": "Precedente / Successivo",
	"VrHelp_NowPlaying_Help_Right4": "Riproduci / Pausa",
	"VrHelp_NowPlaying_Help_Right5": "Impostazioni audio",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artista",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Canzone",
	"VrHelp_USBAudio_Help_Left5": "Genere",
	"VrHelp_USBAudio_Help_Right1": "Cartelle",
	"VrHelp_USBAudio_Help_Right2": "Riproduci tutti",
	"moreLikeThis": "Altri come questo",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "it_IT");