var Localization_usbaudioAppDict_pl_PL = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Uściślanie albumu",
	"Albums": "Albumy",
	"AllAlbums": "Wszystkie albumy",
	"AllArtists": "Wszyscy wykonawcy",
	"AllChapters": "Wszystkie rozdziały",
	"AllEpisodes": "Wszystkie odcinki",
	"AllSongs": "Wszystkie utwory ",
	"Artist": "Artysta",
	"Artists": "Wykonawcy",
	"Audiobook": "Audiobook",
	"Audiobooks": "Audiobooki",
	"AuthenticationFailure": "Niepowodzenie uwierzytelniania",
	"AuthenticationFailureSBN": "Uwierzytelnianie nie powiodło się.",
	"Folder": "Folder",
	"Folders": "Foldery",
	"Genre": "Gatunek",
	"Genres": "Gatunki",
	"IncompatibleFirmware": "Niezgodne oprogramowanie układ.",
	"IncompatibleFirmwareSBN": "Niezgodne oprogramowanie układowe",
	"NoPlayableFiles": "Brak plików do odtwarzania.",
	"NotSupported": "Nieobsługiwane urządzenie",
	"NotSupportedSBN": "Urządzenie nieobsługiwane",
	"Playlist": "Lista odtwarzania",
	"Playlists": "Listy odtwarzania",
	"Podcast": "Podcast",
	"Podcasts": "Podcasty",
	"RootMenu": "Menu główne",
	"Song": "Piosenka",
	"Songs": "Utwory",
	"Tooltip_IcnUmpCurrentList": "Lista piosenek",
	"USB1Connected": "USB1: {usbName} — podłączone",
	"USB1Disconnected": "USB1: {usbName} — odłączone",
	"USB2Connected": "USB2: {usbName} — podłączone",
	"USB2Disconnected": "USB2: {usbName} — odłączone",
	"USBDisconnected": "Urządzenie USB odłączone",
	"USBDisconnectedSBN": "Urządzenie USB odłączone",
	"UnknownType": "Nieznany typ urządzenia USB",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "Więcej podobnych",
	"usbaudio": "USB{deviceId} — {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "pl_PL");