var Localization_usbaudioAppDict_da_DK = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Album entydighed",
	"Albums": "Album",
	"AllAlbums": "Alle album",
	"AllArtists": "Alle kunstnere",
	"AllChapters": "Alle kapitler",
	"AllEpisodes": "Alle episoder",
	"AllSongs": "Alle sange ",
	"Artist": "Kunstner",
	"Artists": "Kunstnere",
	"Audiobook": "Lydbog",
	"Audiobooks": "Lydbøger",
	"AuthenticationFailure": "Fejl i autentificering",
	"AuthenticationFailureSBN": "Autentificering mislykkedes",
	"Folder": "Mappe",
	"Folders": "Mapper",
	"Genre": "Genre",
	"Genres": "Genrer",
	"IncompatibleFirmware": "Firmware er ikke kompatibel",
	"IncompatibleFirmwareSBN": "Firmware inkompatibel",
	"NoPlayableFiles": "Der findes ingen filer til afspilning",
	"NotSupported": "Enheden understøttes ikke",
	"NotSupportedSBN": "Enhed ikke understøttet",
	"Playlist": "Playliste",
	"Playlists": "Afspilningslister",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Hovedmenu",
	"Song": "Sang",
	"Songs": "Sange",
	"Tooltip_IcnUmpCurrentList": "Sangliste",
	"USB1Connected": "USB1: {usbName} tilsluttet",
	"USB1Disconnected": "USB1: {usbName} frakoblet",
	"USB2Connected": "USB2: {usbName} tilsluttet",
	"USB2Disconnected": "USB2: {usbName} frakoblet",
	"USBDisconnected": "USB-enhed frakoblet",
	"USBDisconnectedSBN": "USB frakoblet",
	"UnknownType": "Ukendt USB-type",
	"VrHelp_NowPlaying_Help_Left1": "Underholdning",
	"VrHelp_NowPlaying_Help_Left2": "Hovedmenu",
	"VrHelp_NowPlaying_Help_Left3": "Sangliste",
	"VrHelp_NowPlaying_Help_Left4": "Gentag",
	"VrHelp_NowPlaying_Help_Left5": "Gentag alle",
	"VrHelp_NowPlaying_Help_Right1": "Bland",
	"VrHelp_NowPlaying_Help_Right2": "Mere som dette",
	"VrHelp_NowPlaying_Help_Right3": "Forrige/Næste",
	"VrHelp_NowPlaying_Help_Right4": "Afspil/Pause",
	"VrHelp_NowPlaying_Help_Right5": "LydIndstillinger",
	"VrHelp_USBAudio_Help_Left1": "Afspilningsliste",
	"VrHelp_USBAudio_Help_Left2": "Kunstner",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Sang",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Mapper",
	"VrHelp_USBAudio_Help_Right2": "Afspil alle",
	"moreLikeThis": "Mere som dette",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "da_DK");