var Localization_usbaudioAppDict_de_DE = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Glossar",
	"Albums": "Alben",
	"AllAlbums": "Alle Alben",
	"AllArtists": "Alle Interpreten",
	"AllChapters": "Alle Kapitel",
	"AllEpisodes": "Alle Episoden",
	"AllSongs": "Alle Lieder",
	"Artist": "Interpreten",
	"Artists": "Interpreten",
	"Audiobook": "Hörbuch",
	"Audiobooks": "Audiobücher",
	"AuthenticationFailure": "Authentifizierung fehlgeschlagen",
	"AuthenticationFailureSBN": "Authentifizierung fehlgeschlagen",
	"Folder": "Ordner",
	"Folders": "Ordner",
	"Genre": "Genre",
	"Genres": "Genres",
	"IncompatibleFirmware": "Firmware ist inkompatibel",
	"IncompatibleFirmwareSBN": "Inkompatible Firmware",
	"NoPlayableFiles": "Keine abspielbaren Dateien",
	"NotSupported": "Gerät wird nicht unterstützt",
	"NotSupportedSBN": "Gerät nicht unterstützt",
	"Playlist": "Wiedergabeliste",
	"Playlists": "Wiedergabelisten",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Stammmenü",
	"Song": "Lied",
	"Songs": "Lieder",
	"Tooltip_IcnUmpCurrentList": "Lied-Liste",
	"USB1Connected": "USB1: {usbName} verbunden",
	"USB1Disconnected": "USB1: {usbName} nicht verbunden",
	"USB2Connected": "USB2: {usbName} verbunden",
	"USB2Disconnected": "USB2: {usbName} nicht verbunden",
	"USBDisconnected": "USB-Gerät nicht verbunden",
	"USBDisconnectedSBN": "USB nicht verbunden",
	"UnknownType": "USB-Typ nicht bekannt",
	"VrHelp_NowPlaying_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlaying_Help_Left2": "Stammmenü",
	"VrHelp_NowPlaying_Help_Left3": "Liederliste",
	"VrHelp_NowPlaying_Help_Left4": "Wiederholen",
	"VrHelp_NowPlaying_Help_Left5": "Alles wiederholen",
	"VrHelp_NowPlaying_Help_Right1": "Mischen",
	"VrHelp_NowPlaying_Help_Right2": "Alles wiederholen",
	"VrHelp_NowPlaying_Help_Right3": "Vorheriger / Nächster",
	"VrHelp_NowPlaying_Help_Right4": "Wiedergabe/Pause",
	"VrHelp_NowPlaying_Help_Right5": "Toneinstellungen.",
	"VrHelp_USBAudio_Help_Left1": "Wiedergabeliste",
	"VrHelp_USBAudio_Help_Left2": "Interpreten",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Lied",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Ordner",
	"VrHelp_USBAudio_Help_Right2": "Alle wiedergeben",
	"moreLikeThis": "Ähnliche Musik",
	"usbaudio": "USB{deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "de_DE");