var Localization_usbaudioAppDict_ar_SA = {
	//"stringId" : "localString"
	"Album": "ألبوم",
	"AlbumDisambiguation": "إزالة غموض الألبوم",
	"Albums": "الألبومات",
	"AllAlbums": "جميع الألبومات",
	"AllArtists": "جميع الفنانين",
	"AllChapters": "جميع الفصول",
	"AllEpisodes": "جميع الحلقات",
	"AllSongs": "جميع الأغاني ",
	"Artist": "فنان",
	"Artists": "الفنانين",
	"Audiobook": "كتاب صوتي",
	"Audiobooks": "الكتب الصوتية",
	"AuthenticationFailure": "فشل المصادقة",
	"AuthenticationFailureSBN": "فشلت المصادقة",
	"Folder": "مجلد",
	"Folders": "المجلدات",
	"Genre": "نوع",
	"Genres": "الأنواع",
	"IncompatibleFirmware": "البرامج الثابتة غير متوافقة",
	"IncompatibleFirmwareSBN": "البرامج الثابتة غير متوافقة",
	"NoPlayableFiles": "لا توجد ملفات قابلة للتشغيل",
	"NotSupported": "الجهاز غير مدعوم",
	"NotSupportedSBN": "الجهاز غير مدعوم",
	"Playlist": "قائمة التشغيل",
	"Playlists": "قوائم التشغيل",
	"Podcast": "بودكاست",
	"Podcasts": "البودكاست",
	"RootMenu": "القائمة الجذر",
	"Song": "أغنية",
	"Songs": "الأغاني",
	"Tooltip_IcnUmpCurrentList": "قائمة الأغاني",
	"USB1Connected": "منفذ USB1: {usbName} متصل",
	"USB1Disconnected": "منفذ USB1: {usbName} غير متصل",
	"USB2Connected": "منفذ USB2: {usbName} متصل",
	"USB2Disconnected": "منفذ USB2: {usbName} غير متصل",
	"USBDisconnected": "تم فصل منفذ USB",
	"USBDisconnectedSBN": "تم فصل منفذ USB",
	"UnknownType": "نوع منفذ USB غير معروف",
	"VrHelp_NowPlaying_Help_Left1": "ترفيه ",
	"VrHelp_NowPlaying_Help_Left2": "وقائمة الجذر",
	"VrHelp_NowPlaying_Help_Left3": "القائمة الأغاني",
	"VrHelp_NowPlaying_Help_Left4": "التكرار",
	"VrHelp_NowPlaying_Help_Left5": "تكرار الكل",
	"VrHelp_NowPlaying_Help_Right1": "التبديل",
	"VrHelp_NowPlaying_Help_Right2": "والمزيد مما يُشبه هذا",
	"VrHelp_NowPlaying_Help_Right3": "والسابق/التالي",
	"VrHelp_NowPlaying_Help_Right4": "وبدء التشغيل/ والتوقف المؤقت",
	"VrHelp_NowPlaying_Help_Right5": "إعدادات الصوت",
	"VrHelp_USBAudio_Help_Left1": "قائمة التشغيل",
	"VrHelp_USBAudio_Help_Left2": "الفنان",
	"VrHelp_USBAudio_Help_Left3": "الألبوم",
	"VrHelp_USBAudio_Help_Left4": "الأغنية",
	"VrHelp_USBAudio_Help_Left5": "النوع",
	"VrHelp_USBAudio_Help_Right1": "المجلدات",
	"VrHelp_USBAudio_Help_Right2": "تشغيل الكل",
	"moreLikeThis": "المزيد مما يشابه ذلك",
	"usbaudio": "{deviceName}-USB{deviceId}",
};

framework.registerAppDictLoaded("usbaudio", "ar_SA");