var Localization_usbaudioAppDict_pt_BR = {
	//"stringId" : "localString"
	"Album": "Álbum",
	"AlbumDisambiguation": "Desambiguação de álbum",
	"Albums": "Álbuns",
	"AllAlbums": "Todos os álbuns",
	"AllArtists": "Todos os artistas",
	"AllChapters": "Todos os capítulos",
	"AllEpisodes": "Todos os episódios",
	"AllSongs": "Todas as músicas",
	"Artist": "Artista",
	"Artists": "Artistas",
	"Audiobook": "Livro de áudio",
	"Audiobooks": "Livros de áudio",
	"AuthenticationFailure": "Falha na autenticação",
	"AuthenticationFailureSBN": "Falha na autenticação",
	"Folder": "Pasta",
	"Folders": "Pastas",
	"Genre": "Gênero",
	"Genres": "Gêneros",
	"IncompatibleFirmware": "Firmware incompatível",
	"IncompatibleFirmwareSBN": "Firmware incompatível",
	"NoPlayableFiles": "Nenhum arq. que possa tocar",
	"NotSupported": "Dispositivo não suportado",
	"NotSupportedSBN": "Dispositivo não suportado",
	"Playlist": "Lista de reprodução",
	"Playlists": "Listas de reprodução",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Manu",
	"Song": "Música",
	"Songs": "Músicas",
	"Tooltip_IcnUmpCurrentList": "Lista de músicas",
	"USB1Connected": "USB1: {usbName} Conectado",
	"USB1Disconnected": "USB1: {usbName} Desconectado",
	"USB2Connected": "USB2: {usbName} Conectado",
	"USB2Disconnected": "USB2: {usbName} Desconectado",
	"USBDisconnected": "Dispositivo USB sesconectado",
	"USBDisconnectedSBN": "USB desconectado",
	"UnknownType": "Tipo de USB desconhecido",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Menu de raiz",
	"VrHelp_NowPlaying_Help_Left3": "Lista de músicas",
	"VrHelp_NowPlaying_Help_Left4": "Repetir",
	"VrHelp_NowPlaying_Help_Left5": "Repetir tudo",
	"VrHelp_NowPlaying_Help_Right1": "Aleatório",
	"VrHelp_NowPlaying_Help_Right2": "Mais deste género",
	"VrHelp_NowPlaying_Help_Right3": "Anterior / Seguinte ",
	"VrHelp_NowPlaying_Help_Right4": "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right5": "Definições de som",
	"VrHelp_USBAudio_Help_Left1": "Lista de reprodução",
	"VrHelp_USBAudio_Help_Left2": "Intérprete",
	"VrHelp_USBAudio_Help_Left3": "Álbum",
	"VrHelp_USBAudio_Help_Left4": "Música",
	"VrHelp_USBAudio_Help_Left5": "Gênero",
	"VrHelp_USBAudio_Help_Right1": "Pastas",
	"VrHelp_USBAudio_Help_Right2": "Reproduzir tudo",
	"moreLikeThis": "Semelhantes",
	"usbaudio": "USB {deviceId} - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "pt_BR");