var Localization_sysupdateAppDict_ms_MY = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Gagal mengesahkan sijil pakej.",
	"AutoRetry": "Sistem kemudiannya akan mencuba semula Kemaskini secara automatik.",
	"AvailablePackages": "Pakej Kemaskini Muzik Tersedia",
	"AvailableSoftwarePackages": "Pakej Kemaskini Perisian Tersedia",
	"BUSY": "Pengendalian diminta dalam keadaan yang tidak sesuai.",
	"ConfirmFailSafeUpdateInstall": "Adakah anda mahu memasang Kemaskini imej pasti selamat {FailsafeImageVersion}?",
	"Continue": "Teruskan",
	"CurrentDatabase": "Versi DB Muzik Semasa ialah {CurrentVersion}.",
	"CurrentOSVersion": "Kemaskini Perisian (Smsa)",
	"CurrentSoftwareVersion": "Sistem {CurrentOsVersion} semasa sedang dijalankan.",
	"CurrentVersion": "Kemaskini Muzik (Semasa)",
	"DEVICE_ERROR": "USB Diputuskan Sambungan",
	"DonotRestart": "Jgn hidup semula kenderaan pd masa ini.",
	"FailSafeImage": "Pakej Pasti Selamat",
	"FailSafeImageUpdateNotify": "Perlukan Kemaskini imej pasti selamat, sila laksanakan Kemaskini imej pasti selamat.",
	"FailSafeNotAvailable": "Fail Safe Version Tak Tersedia",
	"FailSafeSysUpdate": "Memasang kmskini sistem Pasti Selamat {OSVersion}",
	"FailSafeVersion": "Fail Safe Version {CurrentFailSafeVersion}",
	"FailsafeAvailable": "Imej pasti selamat sedia ada tersedia.",
	"FunctionNA": "Kemaskini pangkalan data muzik tidak berjaya.",
	"GracenoteVersion": "Kemaskini Muzik",
	"INCOMPATIBLE_VERSION": "Pakej Kemaskini tidak serasi dengan versi papan semasa.",
	"INVALID": "Kandungan pakej Kemaskini salah atau tidak mencukupi.",
	"InsertUSBDialogText": "Masukkan USB dengan pakej pemasangan semula",
	"Install": "Pasang",
	"InstallDatabase": "Adakah anda ingin memasang Kemaskini Muzik {InstallVersion}?",
	"InstallMusic": "Memasang Kmskini Muzik {MusicVersion}",
	"InstallNotSuccessful": "Pemasangan tidak berjaya {errorType}",
	"InstallSuccessful": "Pemasangan Berjaya",
	"InstallUnsuccessful": "Pemasangan Gagal",
	"InstallingFailsafeSystem": "Memasang kmskini sistem Pasti Selamat",
	"InstallingSysUpdates": "Memasang Kemaskini Sistem {OsVersion}",
	"MusicDBVersion": "Versi DB Muzik ialah {CurrentVersion}",
	"MusicInstallSuccess": "Pemasangan muzik versi {MusicVersion} berjaya.",
	"NOT_FOUND": "Pakej Kemaskini yang diminta tiada.",
	"NOT_SUPPORTED": "Pengendalian tidak dibenarkan kerana modul atau kefungsian tiada.",
	"NeedFailSafeImageUpdate": "Perlukan Kemaskini imej pasti selamat untuk meneruskan, sila hubungi wakil penjual yang terdekat.",
	"NoNewMusicPackages": "Tiada pakej Kemaskini muzik baharu.",
	"NoNewSoftwarePackages": "Tiada pakej Kemaskini baharu.",
	"NoReboot": "But Semula Tidak Diperlukan",
	"NotAvailable": "Versi Pangkalan Data Muzik Tidak Tersedia",
	"OSNotAvailable": "Versi OS Ialah Tidak Tersedia",
	"OSVersion": "Versi OS ialah {CurrentOsVersion}",
	"RebootReflash": "Bersedia untuk Kemaskini",
	"ReinstallationPackage": "Pakej Pemasangan Semula",
	"ReinstallationPkgVer": "Memasang semula:{OSVersion}",
	"RestartVehicle": "Sila hidupkan semula kenderaan supaya perubahan boleh diterapkan.",
	"Retry": "Cuba semula",
	"SEARCH_FAILED": "Gagal melaksanakan pengendalian carian.",
	"Search": "Cari",
	"SearchFailed": "Carian Tidak Berjaya",
	"SearchMusicDBUpdate": "Cari pakej Kemaskini untuk Pangkalan Data Muzik pada peranti USB anda?",
	"SearchSoftwareUpdates": "Cari pakej Kemaskini Sistem pada peranti USB anda?",
	"SearchingForMusicUpdates": "Mencari Kemaskini",
	"SearchingForSoftwareUpdates": "Mencari Kemaskini Sistem",
	"SigCheckFailed": "Semakan tandatangan pakej gagal",
	"SoftwareVersion": "Kemaskini Perisian",
	"SysCatalogRestart": "Pengkatalogan tidak akan disediakan. Mula Semula Akan dilaksanakan.",
	"SysInstallSuccess": "Pemasangan Perisian Versi {OsVersion} berjaya.",
	"SystemFailure": "Kegagalan Sistem",
	"SystemNA": "Sistem tidak tersedia sepenuhnya.",
	"SystemRestart": "Mula Semula Sistem akan dilaksanakan.",
	"SystemUpdate": "Kemaskini Sistem",
	"UNKNOWN": "Sebab tidak diketahui",
	"UPDATE_FAILED": "Gagal melaksanakan pengendalian Kemaskini.",
	"USBCataloging": "Katalog USB terkini akan disediakan.",
	"USBCatalogingNotAvailable": "Pengkatalogan USB Terkini tidak akan disediakan",
	"USBcatalog": "Pengkatalogan tidak akan tersedia.",
	"USER_TERMINATED": "Pengendalian Kemaskini dibatalkan oleh pengguna.",
	"UpdateToSoftwareVersion": "Adakah anda ingin memasang OS Kemaskini Perisian {InstallOsVersion}?",
	"UpdatesNA": "Kemaskini Sistem tidak akan tersedia.",
	"ValidatingUpdate": "Mengesahkan pakej Kemaskini sistem {OsVersion}",
	"ValidationFailed": "Pengesahan Gagal",
	"VehicleRestart": "Jgn hidupkan semula kenderaan.",
	"VersionNotAvailable": "Tidak Tersedia",
	"WebsiteInformation": "Sila lawat laman web Mazda untuk maklumat lanjut.",
	"searchAgain": "Sila Cari lagi.",
};

framework.registerAppDictLoaded("sysupdate", "ms_MY");