var Localization_sysupdateAppDict_it_IT = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Impossibile convalidare il certificato del pacchetto.",
	"AutoRetry": "Il sistema riproverà automaticamente l'aggiornamento.",
	"AvailablePackages": "Pacchetti aggiorn musica disponibili",
	"AvailableSoftwarePackages": "Aggiornamenti software disponibili",
	"BUSY": "L'operazione è stata richiesta in uno stato inappropriato.",
	"ConfirmFailSafeUpdateInstall": "Installare aggiornamento immagine fail-safe {FailsafeImageVersion}?",
	"Continue": "Continua",
	"CurrentDatabase": "La versione attuale del DB Musica è {CurrentVersion}.",
	"CurrentOSVersion": "Aggiorn software (attuale)",
	"CurrentSoftwareVersion": "Il sistema attuale {CurrentOsVersion} è in funzione.",
	"CurrentVersion": "Aggiorn musica (attuale)",
	"DEVICE_ERROR": "USB disconnesso",
	"DonotRestart": "Non riavviare il veicolo questa volta.",
	"FailSafeImage": "Pacchetto failsafe",
	"FailSafeImageUpdateNotify": "È necessario caricare un'immagine fail-safe, si prega di effettuare l'aggiornamento dell'immagine fail-safe.",
	"FailSafeNotAvailable": "Versione Fail Safe non disponibile",
	"FailSafeSysUpdate": "Installazione aggiornamento Fail-System {OSVersion}",
	"FailSafeVersion": "Versione Fail Safe è {CurrentFailSafeVersion}",
	"FailsafeAvailable": "È disponibile un'immagine fail-safe già esistente.",
	"FunctionNA": "Aggiorn. database musica non riuscito.",
	"GracenoteVersion": "Aggiornamento musica",
	"INCOMPATIBLE_VERSION": "Il pacchetto degli aggiornamenti non è compatibile con la versione attuale.",
	"INVALID": "Il contenuto del pacchetto aggiornamenti è incorretto o insufficiente.",
	"InsertUSBDialogText": "Inserire USB con pacchetto di re-installazione.",
	"Install": "Installa",
	"InstallDatabase": "Installare aggiornamento musica {InstallVersion}?",
	"InstallMusic": "Inst. aggiornamenti mus. {MusicVersion}",
	"InstallNotSuccessful": "Installazione non riuscita {errorType}.",
	"InstallSuccessful": "Installazione riuscita!",
	"InstallUnsuccessful": "Installazione non riuscita.",
	"InstallingFailsafeSystem": "Installazione aggiornamento Fail-System",
	"InstallingSysUpdates": "Installazione aggiornamenti sistema {OsVersion}",
	"MusicDBVersion": "La versione attuale del DB musica è {CurrentVersion}",
	"MusicInstallSuccess": "Installazione versione musica {MusicVersion} riuscita.",
	"NOT_FOUND": "Il pacchetto di aggiornamenti richiesto non è presente.",
	"NOT_SUPPORTED": "Operazione non consentita per modulo o funzionalità assente.",
	"NeedFailSafeImageUpdate": "È necessario l'aggiornamento dell'immagine file-safe. Contattare il concessionario più vicino.",
	"NoNewMusicPackages": "Nessun nuovo pacchetto aggiornamento musica disponibile.",
	"NoNewSoftwarePackages": "Nessun nuovo pachetto aggiornamento disponibile.",
	"NoReboot": "Riavvio non necessario",
	"NotAvailable": "Versione database musica\nnon disponibile.",
	"OSNotAvailable": "Versione OS non disponibile",
	"OSVersion": "La versione OS è {CurrentOsVersion}",
	"RebootReflash": "Preparazione all'aggiornamento",
	"ReinstallationPackage": "Pacchetto reinstallazione",
	"ReinstallationPkgVer": "Reinstallazione: {OSVersion}",
	"RestartVehicle": "Riavviare il veicolo affinché le modifiche vengano attuate.",
	"Retry": "Riprova",
	"SEARCH_FAILED": "Impossibile effettuare l'operazione di ricerca.",
	"Search": "Ricerca",
	"SearchFailed": "Nessun risultato trovato.",
	"SearchMusicDBUpdate": "Ricercare pacchetti aggiornamenti per database musica sul proprio USB?",
	"SearchSoftwareUpdates": "Ricercare pacchetti aggiornamenti sistema sul proprio dispositivo USB?",
	"SearchingForMusicUpdates": "Ricerca degli aggiornamenti",
	"SearchingForSoftwareUpdates": "Ricerca di aggiornamenti sistema",
	"SigCheckFailed": "Controllo firma pacchetto non riuscito.",
	"SoftwareVersion": "Aggiornamento software",
	"SysCatalogRestart": "La catalogazione non sarà disponibile. Si verificherà un riavvio.",
	"SysInstallSuccess": "Installazione version software {OsVersion}  riuscita.",
	"SystemFailure": "Blocco del sistema.",
	"SystemNA": "Il sistema non è completamente disp.",
	"SystemRestart": "Si verificherà un riavvio del sistema.",
	"SystemUpdate": "Aggior sistema",
	"UNKNOWN": "Motivo sconosciuto.",
	"UPDATE_FAILED": "Impossibile effettuare l'operazione di aggiornamento.",
	"USBCataloging": "La catalogazione USB corrente sarà disponibile.",
	"USBCatalogingNotAvailable": "La catalogazione USB corrente non sarà disponibile.",
	"USBcatalog": "La catalogazione non sarà disponibile.",
	"USER_TERMINATED": "L'operazione di aggiornamento è stata annullata dall'utente.",
	"UpdateToSoftwareVersion": "Installare l'aggiornamento software OS {InstallOsVersion}?",
	"UpdatesNA": "Gli aggiorn. di sistema non saranno disp.",
	"ValidatingUpdate": "Convalida pacchetto aggiornamento sistema {OsVersion}",
	"ValidationFailed": "Convalida non riuscita.",
	"VehicleRestart": "Non riavviare il veicolo questa volta.",
	"VersionNotAvailable": "Non disponibile",
	"WebsiteInformation": "Si prega di andare sul sito Web di Mazda per maggiori informazioni.",
	"searchAgain": "Ricerca di nuovo",
};

framework.registerAppDictLoaded("sysupdate", "it_IT");