var Localization_sysupdateAppDict_zh_CN = {
	//"stringId" : "localString"
	"AUTH_FAILED": "验证证书包失败。",
	"AutoRetry": "然后系统将自动重试此更新。",
	"AvailablePackages": "可用音乐更新包",
	"AvailableSoftwarePackages": "可用软件更新包",
	"BUSY": "在不适当的状态下请求了此操作。",
	"ConfirmFailSafeUpdateInstall": "是否要安装故障保护映像更新{FailsafeImageVersion}？",
	"Continue": "继续",
	"CurrentDatabase": "当前音乐数据库版本为{CurrentVersion}。",
	"CurrentOSVersion": "软件更新（当前）",
	"CurrentSoftwareVersion": "当前系统 {CurrentOsVersion} 正在运行。",
	"CurrentVersion": "音乐更新（当前）",
	"DEVICE_ERROR": "已断开USB的连接",
	"DonotRestart": "请勿在此时重启车辆。",
	"FailSafeImage": "故障保险包",
	"FailSafeImageUpdateNotify": "需要故障保护映像更新，请执行故障保护映像更新。",
	"FailSafeNotAvailable": "故障安全版本不可用",
	"FailSafeSysUpdate": "正在安装故障保护系统更新 {OSVersion}",
	"FailSafeVersion": "故障安全版本是{CurrentFailSafeVersion}",
	"FailsafeAvailable": "现有故障保护映像不可用。",
	"FunctionNA": "音乐数据库更新失败。",
	"GracenoteVersion": "音乐更新",
	"INCOMPATIBLE_VERSION": "更新包和当前版本不兼容。",
	"INVALID": "更新包内容错误或不完整。",
	"InsertUSBDialogText": "插入包含重装包的 USB。",
	"Install": "安装",
	"InstallDatabase": "是否要安装音乐更新{InstallVersion}？",
	"InstallMusic": "正在安装音乐更新 {MusicVersion}",
	"InstallNotSuccessful": "未成功安装 {errorType}",
	"InstallSuccessful": "安装成功",
	"InstallUnsuccessful": "安装失败",
	"InstallingFailsafeSystem": "正在安装故障保护系统更新",
	"InstallingSysUpdates": "正在安装系统更新 {OsVersion}",
	"MusicDBVersion": "音乐数据库版本为{CurrentVersion}",
	"MusicInstallSuccess": "版本{MusicVersion}音乐安装成功",
	"NOT_FOUND": "所需的更新包丢失。",
	"NOT_SUPPORTED": "因丢失模块或功能，不允许运行。",
	"NeedFailSafeImageUpdate": "需要故障保护映像更新才能继续，请联系最近的经销商。",
	"NoNewMusicPackages": "未获得新的音乐更新包。",
	"NoNewSoftwarePackages": "未获得新的更新包。",
	"NoReboot": "无需重启",
	"NotAvailable": "音乐数据库版本不可用",
	"OSNotAvailable": "操作系统版本不可用。",
	"OSVersion": "操作系统版本为{CurrentOsVersion}",
	"RebootReflash": "正在准备更新",
	"ReinstallationPackage": "重新安装包",
	"ReinstallationPkgVer": "重新安装包 {OSVersion}",
	"RestartVehicle": "请重新起动车辆，以便使更改生效。",
	"Retry": "重试",
	"SEARCH_FAILED": "无法执行搜索操作。",
	"Search": "搜索",
	"SearchFailed": "搜索失败",
	"SearchMusicDBUpdate": "在您的 USB 设备上搜索音乐数据库更新？",
	"SearchSoftwareUpdates": "在您的USB设备上搜索系统更新包？",
	"SearchingForMusicUpdates": "正在搜索更新",
	"SearchingForSoftwareUpdates": "正在搜索系统更新",
	"SigCheckFailed": "包签名检查失败",
	"SoftwareVersion": "软件更新",
	"SysCatalogRestart": "当前的USB目录将不可以被使用。 系统重启后生效。",
	"SysInstallSuccess": "版本 {OsVersion} 软件安装成功。",
	"SystemFailure": "系统故障",
	"SystemNA": "系统部分可用。",
	"SystemRestart": "系统重启后生效。",
	"SystemUpdate": "系统更新",
	"UNKNOWN": "原因未知",
	"UPDATE_FAILED": "无法执行更新操作。",
	"USBCataloging": "当前的USB目录可以被使用。",
	"USBCatalogingNotAvailable": "当前的USB目录将不可以被使用。",
	"USBcatalog": "将不提供USB目录。",
	"USER_TERMINATED": "更新操作被用户取消。",
	"UpdateToSoftwareVersion": "想要安装软件更新 OS {InstallOsVersion}？",
	"UpdatesNA": "将不提供系统更新。",
	"ValidatingUpdate": "正在验证系统更新包 {OsVersion}",
	"ValidationFailed": "验证失败",
	"VehicleRestart": "请勿在此时重启车辆。",
	"VersionNotAvailable": "不可用",
	"WebsiteInformation": "有关更多信息，请访问Mazda网站。",
	"searchAgain": "请重新搜索",
};

framework.registerAppDictLoaded("sysupdate", "zh_CN");