var Localization_sysupdateAppDict_sk_SK = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Zlyhalo potvrdenie platnosti certifikátu balíka.",
	"AutoRetry": "Sys. sa sám pokúsi opäť inštal.",
	"AvailablePackages": "Dostupné balíky aktual. hudby",
	"AvailableSoftwarePackages": "Dostupné balíky aktual. softvéru",
	"BUSY": "Operácia sa vyžaduje v príslušnom stave.",
	"ConfirmFailSafeUpdateInstall": "Chcete nainštalovať aktualizáciu obrazu zabezpečenia pri poruche {FailsafeImageVersion}?",
	"Continue": "Pokračovať",
	"CurrentDatabase": "Súčasná verzia hudobnej databázy je {CurrentVersion}.",
	"CurrentOSVersion": "Aktual. softvéru (aktuálna)",
	"CurrentSoftwareVersion": "Beží aktuálny systém {CurrentOsVersion}",
	"CurrentVersion": "Aktual. hudby (aktuálna)",
	"DEVICE_ERROR": "Odpojené USB",
	"DonotRestart": "Teraz vozidlo znovu neštartujte.",
	"FailSafeImage": "Fail-Safe Balík",
	"FailSafeImageUpdateNotify": "Je potrebná aktualizácia obrazu zabezpečenia pri poruche. Kontaktujte najbližšieho predajcu",
	"FailSafeNotAvailable": "Núdzový režim nie je dostupný",
	"FailSafeSysUpdate": "Inštaluje sa Fail-Safe akutalizácia {OSVersion}",
	"FailSafeVersion": "Núdzový režim verzia {CurrentFailSafeVersion}",
	"FailsafeAvailable": "Existujúce fail-safe je k dispozícii.",
	"FunctionNA": "Aktualiz. hudobnej databázy neúspešná.",
	"GracenoteVersion": "Aktualizácia hudby",
	"INCOMPATIBLE_VERSION": "Balík aktualizácie nie je kompatibilný so súčasnou palubnou verziou.",
	"INVALID": "Obsah balíka aktualizácie nie je správny alebo dostatočný.",
	"InsertUSBDialogText": "vložte USB s inštal. balíčkom.",
	"Install": "Inštalovať",
	"InstallDatabase": "Chcete nainštalovať aktualizáciu hudby {InstallVersion}?",
	"InstallMusic": "Inštaluje sa akt. hudby  {MusicVersion}",
	"InstallNotSuccessful": "Inšt. neú.{errorType}",
	"InstallSuccessful": "Inštalácia úspešná",
	"InstallUnsuccessful": "Inštalácia neúspešná",
	"InstallingFailsafeSystem": "Inštaluje sa Fail-Safe akutalizácia",
	"InstallingSysUpdates": "Inšt. sys. akt. {OsVersion}",
	"MusicDBVersion": "Verzia hudobnej databázy je {CurrentVersion}",
	"MusicInstallSuccess": "Inštalácia hudobnej verzie {MusicVersion} bola úspešná.",
	"NOT_FOUND": "Požadovaný balík aktualizácie chýba.",
	"NOT_SUPPORTED": "Operácia nebola povolená z dôvodu chýbajúceho modulu alebo funkčnosti.",
	"NeedFailSafeImageUpdate": "Pokračovať možno po aktualizácii obrazu zabezpečenia proti poruche. Kontaktujte najbližšieho predajcu.",
	"NoNewMusicPackages": "K dispozícii nie sú žiadne nové balíky aktualizácie hudby.",
	"NoNewSoftwarePackages": "K dispozícii nie sú žiadne nové balíky aktualizácie.",
	"NoReboot": "Reštartovanie sa nevyžaduje",
	"NotAvailable": "Hudobné databázy Verzia Nie je k dispozícii",
	"OSNotAvailable": "Nedostupná verzia OS",
	"OSVersion": "Verzia OS je {CurrentOsVersion}",
	"RebootReflash": "Pripravuje sa aktualizácia",
	"ReinstallationPackage": "Reinštalácia balíka",
	"ReinstallationPkgVer": "Reinštalácia: {OSVersion}",
	"RestartVehicle": "Rešt. voz., aby sa zmeny akt.",
	"Retry": "Skúsiť znova",
	"SEARCH_FAILED": "Zlyhalo uskutočnenie vyhľadávania.",
	"Search": "Hľadať",
	"SearchFailed": "Vyhľadávanie nebolo úspešné",
	"SearchMusicDBUpdate": "Hľadať na vašom zariadení USB balíky aktualizácií pre hudobnú databázu?",
	"SearchSoftwareUpdates": "Hľadať na vašom USB zariadení balíky aktualizácií systému?",
	"SearchingForMusicUpdates": "Hľadá sa aktualizácia",
	"SearchingForSoftwareUpdates": "Hľadá sa sys. Aktualizácia",
	"SigCheckFailed": "Kontrola podpisu balíka zlyhala",
	"SoftwareVersion": "Aktualizácia softvéru",
	"SysCatalogRestart": "Katalogizácia nebude k dispozícii. Uskutoční sa reštartovanie systému.",
	"SysInstallSuccess": "Verzia {OsVersion} sa inštalovala.",
	"SystemFailure": "Zlyhanie systému",
	"SystemNA": "Systém nie je plne k dispozícii.",
	"SystemRestart": "Uskutoční sa reštartovanie systému.",
	"SystemUpdate": "Aktualizácia systému",
	"UNKNOWN": "Príčina neznáma",
	"UPDATE_FAILED": "Zlyhalo uskutočnenie aktualizácie.",
	"USBCataloging": "Aktuálna USB katalogizácia bude čoskoro dostupná.",
	"USBCatalogingNotAvailable": "Aktuálnu USB katalogizácia nebude k dispozícii.",
	"USBcatalog": "USB katalogizácia nebude k dispozícii.",
	"USER_TERMINATED": "Aktualizáciu zrušil používateľ.",
	"UpdateToSoftwareVersion": "Inštalovať aktualizácie \nsoftvéru OS {InstallOsVersion}?",
	"UpdatesNA": "Systémová aktualiz. nebude dostupná.",
	"ValidatingUpdate": "Over. akt. bal. {OsVersion}",
	"ValidationFailed": "Overenie zlyhalo",
	"VehicleRestart": "Teraz vozidlo znovu neštartujte.",
	"VersionNotAvailable": "Nedostupné",
	"WebsiteInformation": "Pre viac informácii navštívte prosím webové stránky Mazda. ",
	"searchAgain": "Hľadajte znovu.",
};

framework.registerAppDictLoaded("sysupdate", "sk_SK");