var Localization_sysupdateAppDict_lt_LT = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Netinkamas paketo sertifikatas.",
	"AutoRetry": "Sistema automatiškai pabandys pakartoti naujinimą.",
	"AvailablePackages": "Yra muzikos naujinimo paketų",
	"AvailableSoftwarePackages": "Yra progr. Įr. naujinimo paketų",
	"BUSY": "Reikiami veiksmai yra netinkamame būvyje.",
	"ConfirmFailSafeUpdateInstall": "Ar norite įdiegti saugiojo veikimo vaizdo naujinimą {FailsafeImageVersion}?",
	"Continue": "Tęsti",
	"CurrentDatabase": "Dabartinė muzikos DB versija yra {CurrentVersion}.",
	"CurrentOSVersion": "Progr. Įr. Naujin. (esamas)",
	"CurrentSoftwareVersion": "Veikia esama sistema {CurrentOsVersion}",
	"CurrentVersion": "Muzikos naujin. (esamas)",
	"DEVICE_ERROR": "USB atjungtas",
	"DonotRestart": "Kol kas neužveskite automobilio iš naujo.",
	"FailSafeImage": "Saugiojo veikimo paketas",
	"FailSafeImageUpdateNotify": "Reikia saugiojo veikimo vaizdo naujinimo, atlikite saugiojo veikimo vaizdo naujinimą.",
	"FailSafeNotAvailable": "Saugios sistemos versija nenustatyta.",
	"FailSafeSysUpdate": "Naujinama saugiojo veikimo sistema {OSVersion}",
	"FailSafeVersion": "Saugios sistemos versija yra {CurrentFailSafeVersion}",
	"FailsafeAvailable": "Galimas esamas saugusis veikimas.",
	"FunctionNA": "Muz. Duom. bazės naujin. nesėkmingas.",
	"GracenoteVersion": "Muzikos naujinimas",
	"INCOMPATIBLE_VERSION": "Naujinimo paketas nesuderinamas su esama versija.",
	"INVALID": "Paketo naujinimo turinys yra neteisingas arba nepilnas. ",
	"InsertUSBDialogText": "Įstatykite USB su pakartotinio diegimo programine įranga",
	"Install": "Diegti",
	"InstallDatabase": "Ar norite įdiegti muzikos naujinimą {InstallVersion}?",
	"InstallMusic": "Diegiamas naujinimas {MusicVersion}",
	"InstallNotSuccessful": "Diegimas nepavyko {errorType}",
	"InstallSuccessful": "įdiegimas sėkmingas",
	"InstallUnsuccessful": "įdiegimas nesėkmingas",
	"InstallingFailsafeSystem": "Naujinama saugiojo veikimo sistema",
	"InstallingSysUpdates": "Diegiami sistemos naujinimai {OsVersion}",
	"MusicDBVersion": "Muzikos DB versija yra {CurrentVersion}",
	"MusicInstallSuccess": "{MusicVersion} versijos muzikos diegimas sėkmingas.",
	"NOT_FOUND": "Nėra reikiamo naujinimo paketo.",
	"NOT_SUPPORTED": "Neleidžiama atlikti veiksmo, nes trūksta modulio arba neveikia.",
	"NeedFailSafeImageUpdate": "Jei reikia tęsti saugiojo veikimo vaizdo nesklandumų šalinimą, kreipkitės į artimiausią prekybos atstovą.",
	"NoNewMusicPackages": "Naujų muzikos naujinimo paketų nėra.",
	"NoNewSoftwarePackages": "Naujų naujinimo paketų nėra.",
	"NoReboot": "Nereikia leisti iš naujo.",
	"NotAvailable": "Muzikinės duomenų bazės\nversija negalima",
	"OSNotAvailable": "OS versija nenustatyta.",
	"OSVersion": "OS versija yra {CurrentOsVersion}",
	"RebootReflash": "Ruošiamasi naujinti",
	"ReinstallationPackage": "Kartotinio diegimo paketas",
	"ReinstallationPkgVer": "Pakartotinis: {OSVersion}",
	"RestartVehicle": "Kad įsigaliotų pakeitimai, pakartotinai užveskite automobilį.",
	"Retry": "Bandyti dar kartą",
	"SEARCH_FAILED": "Nepavyko paleisti paieškos.",
	"Search": "Ieškoma naujinimų",
	"SearchFailed": "Paieška nesėkminga.",
	"SearchMusicDBUpdate": "Ieškoti muzikos duomenų bazės naujinimo paketų jūsų USB?",
	"SearchSoftwareUpdates": "Ieškoti sistemos naujinimo paketų jūsų USB įrenginyje?",
	"SearchingForMusicUpdates": "Ieškoma naujinimų",
	"SearchingForSoftwareUpdates": "Ieškoma sistemos naujinimų",
	"SigCheckFailed": "Nepavyko patikrinti paketo parašą",
	"SoftwareVersion": "Progr. Įr. naujinimas",
	"SysCatalogRestart": "Katalogavimas bus nepasiekiamas. Sistemos paleidimas iš naujo.",
	"SysInstallSuccess": "Sėkmingai įdiegta programinė įranga, versija {OsVersion}.",
	"SystemFailure": "Sistemos triktis",
	"SystemNA": "Sistema nėra visiškai pasiekiama.",
	"SystemRestart": "Bus atliktas sistemos paleidimas iš naujo.",
	"SystemUpdate": "Sistemos naujinimas",
	"UNKNOWN": "Priežastis nežinoma",
	"UPDATE_FAILED": "Nepavyko naujinimo veiksmai.",
	"USBCataloging": "Bus pasiekiamas dabartinis USB katalogavimas.",
	"USBCatalogingNotAvailable": "Dabartinę USB katalogavimas bus nepasiekiamas.",
	"USBcatalog": "USB katalogavimas bus nepasiekiamas.",
	"USER_TERMINATED": "Naujinimo veiksmus vartotojas atšaukė.",
	"UpdateToSoftwareVersion": "Ar norite įdiegti programinės įrangos naujinimo OS {InstallOsVersion}?",
	"UpdatesNA": "Nėra sustemos naujinimų.",
	"ValidatingUpdate": "Tikrinamas sistemos naujinimo paketas {OsVersion}",
	"ValidationFailed": "Patvirtinimas nepavyko",
	"VehicleRestart": "Kol kas neužveskite automobilio iš naujo.",
	"VersionNotAvailable": "Negalima",
	"WebsiteInformation": "Daugiau informacijos – „Mazda“ svetainėje.",
	"searchAgain": "Ieškokite dar kartą.",
};

framework.registerAppDictLoaded("sysupdate", "lt_LT");