var Localization_sysupdateAppDict_cn_HK = {
	//"stringId" : "localString"
	"AUTH_FAILED": "驗證更新包證書失敗",
	"AutoRetry": "之後系統會自動重新嘗試更新。",
	"AvailablePackages": "選取音樂更新包",
	"AvailableSoftwarePackages": "可用的軟體更新包。",
	"BUSY": "在不當狀態下請求了操作。",
	"ConfirmFailSafeUpdateInstall": "是否要安裝自動防故障影像更新 {FailsafeImageVersion}？",
	"Continue": "繼續",
	"CurrentDatabase": "當前的音樂資料庫版本為 {CurrentVersion}。",
	"CurrentOSVersion": "當前",
	"CurrentSoftwareVersion": "當前系統 {CurrentOsVersion} 正在運行。",
	"CurrentVersion": "當前",
	"DEVICE_ERROR": "USB 解除連線",
	"DonotRestart": "此時請勿重新啟動車輛。",
	"FailSafeImage": "自動防故障安裝包",
	"FailSafeImageUpdateNotify": "自動防故障影像需要更新。 請執行自動防故障影像更新。",
	"FailSafeNotAvailable": "自動防故障系統不可用",
	"FailSafeSysUpdate": "正在安裝自動防故障系統更新 {OSVersion}",
	"FailSafeVersion": "自動防故障系統版本為 {CurrentFailSafeVersion}",
	"FailsafeAvailable": "現有的自動防故障影像可供使用。",
	"FunctionNA": "音樂資料庫更新不成功",
	"GracenoteVersion": "音樂更新",
	"INCOMPATIBLE_VERSION": "更新包與當前主板版本不相容。",
	"INVALID": "更新包內容錯誤或不足。",
	"InsertUSBDialogText": "確保已插入帶有更新安裝包的 USB 裝置。",
	"Install": "安裝",
	"InstallDatabase": "是否要安裝音樂升級程式 {InstallVersion}？",
	"InstallMusic": "正在更新音樂資料庫 {MusicVersion}",
	"InstallNotSuccessful": "安裝不成功 {errorType}",
	"InstallSuccessful": "安裝成功",
	"InstallUnsuccessful": "安裝不成功",
	"InstallingFailsafeSystem": "正在安裝自動防故障影像更新",
	"InstallingSysUpdates": "更新系統 {OsVersion}",
	"MusicDBVersion": "音樂資料庫版本為 {CurrentVersion}",
	"MusicInstallSuccess": "版本為 {MusicVersion} 的音樂資料庫已成功更新。",
	"NOT_FOUND": "所需更新包丟失",
	"NOT_SUPPORTED": "由於缺少模組或功能導致不允許執行操作。",
	"NeedFailSafeImageUpdate": "自動防故障影像不可用。 請連絡離您最近的經銷商。",
	"NoNewMusicPackages": "沒有新的音樂更新包可供下戴",
	"NoNewSoftwarePackages": "沒有新的升級包可供使用",
	"NoReboot": "不需要重新開機",
	"NotAvailable": "音樂資料庫版本不可用",
	"OSNotAvailable": "作業系統版本不可用",
	"OSVersion": "作業系統版本為 {CurrentOsVersion}",
	"RebootReflash": "正在準備更新",
	"ReinstallationPackage": "重新安裝包",
	"ReinstallationPkgVer": "重新安裝包 {OSVersion}",
	"RestartVehicle": "請重新啟動車輛以使更改生效。",
	"Retry": "重試",
	"SEARCH_FAILED": "執行搜尋操作失敗。",
	"Search": "搜尋",
	"SearchFailed": "搜尋未成功",
	"SearchMusicDBUpdate": "是否在您的 USB 裝置上搜尋音樂資料庫更新包？",
	"SearchSoftwareUpdates": "在您的 USB 裝置上搜尋系統更新包？",
	"SearchingForMusicUpdates": "正在搜尋更新",
	"SearchingForSoftwareUpdates": "正在搜尋系統更新",
	"SigCheckFailed": "安裝包签名检查失敗",
	"SoftwareVersion": "軟體更新",
	"SysCatalogRestart": "當前 USB 目錄不可用。 系統重新啟動後生效。",
	"SysInstallSuccess": "{OsVersion} 版本的軟體安裝已成功。",
	"SystemFailure": "系統故障",
	"SystemNA": "系統不完全可用。",
	"SystemRestart": "需要重新啟動系統",
	"SystemUpdate": "系統更新",
	"UNKNOWN": "未知原因",
	"UPDATE_FAILED": "執行更新操作失敗。",
	"USBCataloging": "當前USB目錄可用。",
	"USBCatalogingNotAvailable": "當前 USB 目錄不可用。",
	"USBcatalog": "目錄不可用",
	"USER_TERMINATED": "使用者已取消更新操作",
	"UpdateToSoftwareVersion": "是否要安裝軟體升級作業系統 {InstallOsVersion}？",
	"UpdatesNA": "系統更新將不可用",
	"ValidatingUpdate": "正在驗證系統更新包 {OsVersion}",
	"ValidationFailed": "驗證失敗",
	"VehicleRestart": "此時請勿重新啟動車輛。",
	"VersionNotAvailable": "不可用",
	"WebsiteInformation": "請瀏覽 Mazda 網站以獲取更多資訊。",
	"searchAgain": "請再次搜尋",
};

framework.registerAppDictLoaded("sysupdate", "cn_HK");