var Localization_sysupdateAppDict_da_DK = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Kunne ikke validere pakkecertifikatet.",
	"AutoRetry": "Systemet vil automatisk forsøge opdatering igen.",
	"AvailablePackages": "Tilgæng. musikopdaterings-pakker",
	"AvailableSoftwarePackages": "Tilgængelige softwarepakker",
	"BUSY": "Operationen der anmodes om, er ikke hensigtsmæssig.",
	"ConfirmFailSafeUpdateInstall": "Vil du gerne installere sikkerhedskopi {FailsafeImageVersion}?",
	"Continue": "Fortsæt",
	"CurrentDatabase": "Den nuværende musikdabase version er {CurrentVersion}.",
	"CurrentOSVersion": "Softwareopdt. (nuv.)",
	"CurrentSoftwareVersion": "Det nuværende system {CurrentOsVersion} er aktivt.",
	"CurrentVersion": "Musikopdatering (nuv.)",
	"DEVICE_ERROR": "USB frakoblet",
	"DonotRestart": "Genstart ikke køretøjet nu",
	"FailSafeImage": "Sikkerhedskopi",
	"FailSafeImageUpdateNotify": "Behøver opdatering af sikkerhedskopi, udfør venligst opdatering.",
	"FailSafeNotAvailable": "Fail-safe versionen er ikke tilgængelig.",
	"FailSafeSysUpdate": "Indlæser sikkerhedskopi {OSVersion}",
	"FailSafeVersion": "Fail-safe versionen er {CurrentFailSafeVersion}",
	"FailsafeAvailable": "Eksisterende sikkerhedskopi er tilgængeligt",
	"FunctionNA": "Musikdatabasen er opdateret.",
	"GracenoteVersion": "Musikopdatering",
	"INCOMPATIBLE_VERSION": "Opdateringspakken er uforenelig med nuværende kortversion.",
	"INVALID": "Indholdet i opdateringspakken er forkert eller utilstrækkeligt.",
	"InsertUSBDialogText": "indsæt USB med geninstallerings-pakke.",
	"Install": "Installer",
	"InstallDatabase": "Ønsker du at installere musikopdatering {InstallVersion}?",
	"InstallMusic": "Installerer musik opdat. {MusicVersion}",
	"InstallNotSuccessful": "Installationen mislykkedes {errorType}",
	"InstallSuccessful": "Installering gennemført",
	"InstallUnsuccessful": "Installering mislykket",
	"InstallingFailsafeSystem": "Indlæser sikkerhedskopi",
	"InstallingSysUpdates": "Installerer systemopdateringer {OsVersion}",
	"MusicDBVersion": "Musikdabase version er {CurrentVersion}",
	"MusicInstallSuccess": "Installationen af version {MusicVersion} musik lykkedes.",
	"NOT_FOUND": "Den ønskede opdateringspakke mangler.",
	"NOT_SUPPORTED": "Handlingen er ikke tilladt pga. manglende modul eller funktionalitet",
	"NeedFailSafeImageUpdate": "Behøver opdatering af sikkerhedskopi for at fortsætte, kontakt nærmeste forhandler.",
	"NoNewMusicPackages": "Ingen nye musikopdaterings-pakker til rådighed.",
	"NoNewSoftwarePackages": "Der findes ingen nye opdateringspakker.",
	"NoReboot": "Genstart kræves ikke",
	"NotAvailable": "Musik Database udgave ikke tilgængelig",
	"OSNotAvailable": "OS-versionen er ikke tilgængelig.",
	"OSVersion": "OS-version er {CurrentOsVersion}",
	"RebootReflash": "Forbereder opdatering",
	"ReinstallationPackage": "Geninstallationspakke",
	"ReinstallationPkgVer": "Geninstallation: {OSVersion}",
	"RestartVehicle": "Genstart køretøjet for at ændringerne træder i kraft.",
	"Retry": "Prøv igen",
	"SEARCH_FAILED": "Kunne ikke udføre søgningen.",
	"Search": "Søg",
	"SearchFailed": "Søgning mislykkedes",
	"SearchMusicDBUpdate": "Søg efter opdatering til musikdatabasen på din USB?",
	"SearchSoftwareUpdates": "Søg efter systemopdateringspakker på din USB-enhed?",
	"SearchingForMusicUpdates": "Søger efter opdateringer",
	"SearchingForSoftwareUpdates": "Søg efter systemopdt.",
	"SigCheckFailed": "Kontrol af signatur mislykkedes",
	"SoftwareVersion": "Softwareopdatering",
	"SysCatalogRestart": "Katalogisering er ikke tilgængelig. Systemet vil genstarte.",
	"SysInstallSuccess": "Installation af version {OsVersion} software er  udført.",
	"SystemFailure": "Systemfejl",
	"SystemNA": "Systemet er ikke fuldt ud tilgængeligt.",
	"SystemRestart": "Systemet vil genstarte",
	"SystemUpdate": "Systemopdatering",
	"UNKNOWN": "Årsag ukendt",
	"UPDATE_FAILED": "Kunne ikke udføre opdateringen.",
	"USBCataloging": "Den nuværende USB-katalogisering vil være til rådighed.",
	"USBCatalogingNotAvailable": "Den aktuelle USB-katalogisering vil ikke være tilgængelig",
	"USBcatalog": "USB-katalogisering vil ikke være mulig.",
	"USER_TERMINATED": "Opdateringen er annulleret af brugeren.",
	"UpdateToSoftwareVersion": "Vil du gerne installere Softwareopdater. OS {InstallOsVersion}?",
	"UpdatesNA": "Systemopdat. er ikke tilgængelig",
	"ValidatingUpdate": "Godkender systemopdatering {OsVersion}",
	"ValidationFailed": "Validering mislykkedes",
	"VehicleRestart": "Genstart ikke køretøjet nu",
	"VersionNotAvailable": "Ikke tilgængelig",
	"WebsiteInformation": "Gå til Mazda websitet for yderligere oplysninger.",
	"searchAgain": "Venligst søg igen.",
};

framework.registerAppDictLoaded("sysupdate", "da_DK");