var Localization_sysupdateAppDict_lv_LV = {
	//"stringId" : "localString"
	"AUTH_FAILED": "Neizdevās apstiprināt pakotnes sertifikātu.",
	"AutoRetry": "Pēc tam sistēma automātiski atkārtoti mēģinās atjaunināt.",
	"AvailablePackages": "Pieejamas mūz. atjaun. pakotnes",
	"AvailableSoftwarePackages": "Pieej. programmat. atjaun. pakotn.",
	"BUSY": "Darbība ir pieprasīta nepiemērotā stāvoklī.",
	"ConfirmFailSafeUpdateInstall": "Vai instalēt atteikumdrošā attēla atjauninājumu {FailsafeImageVersion}?",
	"Continue": "Turpināt",
	"CurrentDatabase": "Pašreizējā mūzikas datu bāzes versija ir {CurrentVersion}.",
	"CurrentOSVersion": "Programmat. atjaunin. (pašr.)",
	"CurrentSoftwareVersion": "Darbojas pašreizējā sistēma {CurrentOsVersion}.",
	"CurrentVersion": "Mūzik. atjaun. (pašr.)",
	"DEVICE_ERROR": "USB atvienots",
	"DonotRestart": "Šajā laikā neiedarbiniet transportlīdzekli.",
	"FailSafeImage": "Atteikumdrošā pakotne",
	"FailSafeImageUpdateNotify": "Jāatjaunina atteikumdrošais attēls; atjauniniet atteikumdrošo attēlu.",
	"FailSafeNotAvailable": "Bezatteices versija nav pieejama.",
	"FailSafeSysUpdate": "Instalē bezatteices sist. atjaun {OSVersion}",
	"FailSafeVersion": "Bezatteices versija ir {CurrentFailSafeVersion}.",
	"FailsafeAvailable": "Esošās bezatteices attēls ir pieejams.",
	"FunctionNA": "Mūzikas datu bāze sekmīgi atjaunināta.",
	"GracenoteVersion": "Mūzikas atjauninājums",
	"INCOMPATIBLE_VERSION": "Atjauninājumu pakotne nav saderīga ar pašreizējo versiju.",
	"INVALID": "Atjauninājumu pakotnes saturs nav pareizs vai pietiekams.",
	"InsertUSBDialogText": "Ievietot USB ar atkārtotas instalēšanas pakotni.",
	"Install": "Instalēt",
	"InstallDatabase": "Vai instalēt mūzikas atjauninājumu {InstallVersion}?",
	"InstallMusic": "Instalē mūzikas {MusicVersion}",
	"InstallNotSuccessful": "Instalēšana neveiksmīga {errorType}",
	"InstallSuccessful": "Instalēšana sekmīga",
	"InstallUnsuccessful": "Instalēšana neizdevās",
	"InstallingFailsafeSystem": "Instalē bezatteices sist. atjaun.",
	"InstallingSysUpdates": "Uzstāda sistēmas atjauninājumus {OsVersion}",
	"MusicDBVersion": "Mūzikas datu bāzes versija ir {CurrentVersion}",
	"MusicInstallSuccess": "Versijas {MusicVersion} mūzika instalēta sekmīgi.",
	"NOT_FOUND": "Pieprasītā atjauninājumu pakotne nav atrasta.",
	"NOT_SUPPORTED": "Darbība nav atļauta, jo nav kāda moduļa vai funkcionalitātes.",
	"NeedFailSafeImageUpdate": "Lai turpinātu, jāatjaunina atteikumdrošais attēls; sazinieties ar tuvāko izplatītāju.",
	"NoNewMusicPackages": "Neviena jauna mūzikas atjauninājumu pakotne nav pieejama.",
	"NoNewSoftwarePackages": "Neviena jauna atjauninājumu pakotne nav pieejama.",
	"NoReboot": "Sistēma nav jāatsāknē",
	"NotAvailable": "Mūzikas datubāzes versija nav pieejama",
	"OSNotAvailable": "OS versija nav pieejama.",
	"OSVersion": "Operētājsistēmas versija ir {CurrentOsVersion}",
	"RebootReflash": "Sagatavo atjaunināšanai",
	"ReinstallationPackage": "Pārinstalēšanas pakotne",
	"ReinstallationPkgVer": "Pārinstalēšanas pakotne {OSVersion}",
	"RestartVehicle": "Lai izmaiņas stātos spēkā, atkārtoti iedarbiniet transportlīdzekli.",
	"Retry": "Mēģināt vēlreiz",
	"SEARCH_FAILED": "Neizdevās veikt meklēšanas funkciju.",
	"Search": "Meklēt",
	"SearchFailed": "Meklēšana neizdevās",
	"SearchMusicDBUpdate": "Vai meklēt mūzikas datu bāzes sistēmas atjauninājumu pakotnes USB ierīcē?",
	"SearchSoftwareUpdates": "Vai meklēt sistēmas atjauninājumu pakotnes USB ierīcē?",
	"SearchingForMusicUpdates": "Meklē atjauninājumus",
	"SearchingForSoftwareUpdates": "Meklē sistēmas atjauninājumus",
	"SigCheckFailed": "Pakotnes paraksta pārbaude neizdevās",
	"SoftwareVersion": "Programmat. atjaunin.",
	"SysCatalogRestart": "Katalogs nebūs pieejama. Sistēma tiks restartēta.",
	"SysInstallSuccess": "Programmatūras versijas {OsVersion} instalēšana bija veiksmīga.",
	"SystemFailure": "Sistēmas disfunkcija",
	"SystemNA": "Sistēma nav pilnībā pieejama.",
	"SystemRestart": "Sistēma tiks restartēta.",
	"SystemUpdate": "Sist. atjaunin.",
	"UNKNOWN": "Nezināms iemesls",
	"UPDATE_FAILED": "Neizdevās veikt atjaunināšanas funkciju.",
	"USBCataloging": "Būs pieejama pašreizējā USB kataloģizācija.",
	"USBCatalogingNotAvailable": "Pašreizējo USB iekļaušana sarakstā nebūs pieejama.",
	"USBcatalog": "USB iekļaušana sarakstā nebūs pieej.",
	"USER_TERMINATED": "Atjaunošanu atcēla lietotājs.",
	"UpdateToSoftwareVersion": "Vai vēlaties instalēt programmatūras atjaunināšanas OS {InstallOsVersion}?",
	"UpdatesNA": "Sistēmas atjauninājumi nebūs pieejami.",
	"ValidatingUpdate": "Validē sistēmas atjauninājumu pakotni {OsVersion}",
	"ValidationFailed": "Validācija neizdevās",
	"VehicleRestart": "Šajā laikā neiedarbiniet transportlīdzekli.",
	"VersionNotAvailable": "Nav pieejams",
	"WebsiteInformation": "Lūdzam apmeklēt Mazdas vietni, lai iegūtu papildinformāciju.",
	"searchAgain": "Meklējiet vēlreiz.",
};

framework.registerAppDictLoaded("sysupdate", "lv_LV");