var Localization_vehsettingsAppDict_th_TH = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "ปรับได้ ",
	"AdaptiveFront-lightingSystem": "ระบบปรับระดับไฟหน้ารถ",
	"AlertTiming": "จังหวะแจ้งเตือน",
	"AtLine": "ที่เส้น",
	"Auto": "อัตโนมัติ",
	"AutoHeadlightOn": "เปิดไฟหน้าอัตโนมัติ",
	"AutoWiper": "ระบบปัดน้ำฝนอัตโนมัติ",
	"BSMBuzzerVolume": "ระดับเสียง Blind Spot Monitoring",
	"Beep": "เสียงบี๊บ",
	"BeepVolume": "ระดับเสียงบี๊บ",
	"Beep_Line": "เสียงบี๊บ",
	"BeforeLine": "ก่อนที่",
	"Brightness": "ความสว่าง",
	"BrightnessControl": "การควบคุมความสว่าง",
	"Calibration": "การปรับเทียบ",
	"ChangingLASSettings": "การเปลี่ยนการตั้งค่าระบบ LAS",
	"Clock": "นาฬิกา",
	"Close": "ปิด",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยน Distance Recognition Support System (DRSS) กลับเป็นค่าเริ่มต้นหรือไม่",
	"DRSSResetError": "เกิดข้อผิดพลาดขณะเปลี่ยน Distance Recognition Support System (DRSS) คุณต้องการลองใหม่หรือไม่",
	"DRSSResetProgress": "กำลังเปลี่ยน Distance Recognition Support System (DRSS)",
	"Dark": "เข้ม",
	"DaytimeRunningLights": "ระบบไฟส่องสว่างกลางวัน",
	"Devices": "อุปกรณ์",
	"Display": "แสดงผล",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "ระบบล็อกประตู",
	"DoorLockMode": "โหมดล็อกประตูอัตโนมัติ",
	"DoorLockReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าการล็อกประตูกลับเป็นค่าเริ่มต้น",
	"DoorLockResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าการล็อกประตู คุณต้องการลองใหม่หรือไม่",
	"DoorLockResetProgress": "กำลังเปลี่ยนการตั้งค่าการล็อกประตู",
	"DoorRelockTime": "เวลาล็อกซ้ำอัตโนมัติ",
	"DriverAlert": "Driver Attention Alert",
	"Early": "ก่อนกำหนด",
	"ErrorLASSettings": "เกิดข้อผิดพลาดในการเปลี่ยนระบบ Lane-keep Assist System ต้องการลองใหม่หรือไม่?",
	"FOWReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าระบบเตือนภัยป้องกันการชนด้านหน้า (Forward Obstruction Warning (FOW)) กลับเป็นค่าเริ่มต้น",
	"FOWResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าระบบเตือนภัยป้องกันการชนด้านหน้า (Forward Obstruction Warning (FOW)) คุณต้องการลองใหม่หรือไม่",
	"FOWResetProgress": "กำลังเปลี่ยนการตั้งค่า Forward Obstruction Warning (FOW)",
	"Far": "ไกล",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าจอแสดงผลระหว่างการขับขี่ (Active Driving Display) กลับเป็นค่าเริ่มต้น",
	"HUDResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าการแสดงผลการอยู่ระหว่างการขับขี่ (Active Driving Display) คุณต้องการลองใหม่หรือไม่",
	"HUDResetProgress": "กำลังเปลี่ยนการตั้งค่า AD-Disp",
	"HeadlightOffTimer": "ตัวจับเวลาปิดไฟหน้า",
	"HeadlightOnWarning": "ไฟหน้ากำลังเปิดอยู่",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "ความสูง",
	"High": "สูง",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "สูง",
	"High_Vibration": "สูง",
	"InterioLightsTimeOutDoorsClosed": "ไฟในรถดับเมื่อปิดประตู",
	"InterioLightsTimeOutDoorsOpen": "ไฟในรถดับเมื่อเปิดประตู",
	"InteriorLightTimeoutDoorClosedTitle": "ไฟภายในรถดับ - ปิดประตู",
	"InteriorLightTimeoutDoorOpenTitle": "ไฟภายในรถดับ - เปิดประตู",
	"Intervention": "เข้าแก้ไข",
	"InterventionTiming": "จังหวะเข้าแก้ไข",
	"KeylessLockBeepVol": "ระดับเสียงเมื่อกดล็อกด้วยรีโมท",
	"LASAlert": "แจ้งเตือน LAS",
	"LASDefaultValues": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าระบบ Lane-keep Assist System กลับเป็นค่าตั้งต้น?",
	"LASEarly": "ก่อนกำหนด",
	"LASLate": "ล่าช้า",
	"LASSound": "ชนิดการแจ้งเตือน",
	"LASTiming": "เวลา LAS",
	"LDWSReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่า \nLane Departure Warning System (LDWS) \nกลับเป็นค่าเริ่มต้น\n",
	"LDWSResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าระบบเตือนการขับรถข้ามเลน Lane Departure Warning System (LDWS) คุณต้องการลองใหม่หรือไม่",
	"LDWSResetProgress": "กำลังเปลี่ยนการตั้งค่า Lane Departure Warning System (LDWS)",
	"LDWSTiming": "การควบคุมจังหวะ LDWS",
	"LaneDepartureAlert": "แจ้งเตือนการออกนอกช่องทาง",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "ล่าช้า",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "อ่อน",
	"LightOnReminderVolume": "ระดับเสียงเตือน",
	"Lighting": "ระบบไฟส่องสว่าง",
	"LightingReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าระบบไฟส่องสว่าง กลับเป็นค่าเริ่มต้น",
	"LightingResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าระบบไฟส่องสว่าง คุณต้องการลองใหม่หรือไม่",
	"LightingResetProgress": "กำลังเปลี่ยนการตั้งค่าระบบไฟส่องสว่าง",
	"LockShiftFromP": "ล็อก:เมื่อออกจากเกียร์ P",
	"LockShiftFromPUnlockInPark": "ล็อก:ออกเกียร์ P, ปลดล็อก:เข้าเกียร์ P",
	"LockUnlock": "ล็อก: ขณะขับ, ปลดล็อก: เมื่อจอด",
	"LockWhenDriving": "ล็อก: เมื่อขับขี่",
	"LockWhenDrivingUnlockIGNoff": "ล็อก: เมื่อขับ, ปลดล็อก: เมื่อปิดสวิตช์",
	"Long": "ไกล",
	"Low": "ต่ำ",
	"Low_SensitivityLAS": "ต่ำ",
	"Low_Vibration": "ต่ำ",
	"Manual": "ปรับเอง",
	"Med": "กลาง",
	"Medium": "ปานกลาง",
	"MediumDark": "เข้มกลาง",
	"MediumLight": "อ่อนกลาง",
	"Medium_Int_OFF": "กลาง",
	"Medium_SensitivityLAS": "กลาง",
	"Mid": "กลาง",
	"Middle": "กลาง",
	"Mode": "โหมด",
	"Navigation": "ระบบนำทาง",
	"Near": "ใกล้",
	"Off": "ปิด",
	"Often": "บ่อยครั้ง",
	"Often_Int_OFF": "บ่อยครั้ง",
	"OnceAllDoors": "หนึ่งครั้ง: ประตูทั้งหมด",
	"OnceDriversDoorTwiceAllDoors": "หนึ่งครั้ง:ด้านคนขับ สองครั้ง:ทุกประตู",
	"Open": "เปิด",
	"ParkingSensorIndication": "การบ่งชี้เซ็นเซอร์การจอดรถ",
	"RVMBuzzerVolume": "ระดับเสียง Rear Vehicle Monitoring",
	"Rare": "ไม่บ่อย",
	"Rare_Int_OFF": "ไม่บ่อย",
	"Reset": "รีเซ็ต",
	"RumbleStrips": "รัมเบิล",
	"RumbleStrips_line": "รัมเบิล",
	"RumbleVolume": "ระดับเสียง",
	"SBSReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่า Smart Brake Support (SBS) กลับเป็นค่าเริ่มต้น",
	"SBSResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่า Smart Brake Support (SBS) คุณต้องการลองใหม่หรือไม่",
	"SBSResetProgress": "กำลังเปลี่ยนการตั้งค่า Smart Brake Support (SBS)",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่า SBS/SCBS กลับเป็นค่าเริ่มต้น",
	"SBS_SCBSResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่า SBS/SCBS  คุณต้องการลองใหม่หรือไม่",
	"SBS_SCBSResetProgress": "กำลังเปลี่ยนการตั้งค่า SBS/SCBS",
	"SCBS": "Smart City Brake Support",
	"Safety": "ปลอดภัย",
	"Safetysettings": "การตั้งค่าความปลอดภัย",
	"Sensitivity": "ความไว",
	"Sensitivity_Intervention_OFF": "การเตือน",
	"Settings": "การตั้งค่า",
	"Short": "ใกล้",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "เสียง",
	"System": "ระบบ",
	"ThreeFlashTurnSignal": "สัญญาณไฟเลี้ยวกะพริบ 3 ครั้ง",
	"Timing": "การควบคุมจังหวะ",
	"Turn": "ไฟเลี้ยว",
	"TurnProgress": "กำลังเปลี่ยนการตั้งค่าการเลี้ยว",
	"TurnReset": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าไฟเลี้ยว กลับเป็นค่าเริ่มต้น",
	"TurnResetError": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าการเลี้ยว คุณต้องการลองใหม่หรือไม่",
	"TurnSettings": "ไฟเลี้ยว",
	"TurnSignalIndicatorVolume": "ความดังของไฟเลี้ยว",
	"UnlockMode": "โหมดปลดล็อก",
	"Vehicle": "รถ",
	"VehicleSettings": "การตั้งค่ารถ",
	"Vibration": "ระบบสั่น",
	"VibrationStrength": "ความแรงการสั่น",
	"Vibration_Line": "ระบบสั่น",
	"Volume": "ระดับเสียง",
	"WalkAwayLock": "ล็อกเมื่อเดินห่างออกไป",
	"Warning": "การเตือน",
	"WarningDistance": "ระยะการเตือน",
	"_0s": "0 วินาที",
	"_0seconds": "0 วินาที",
	"_10m": "10 นาที",
	"_10minutes": "10 นาที",
	"_120s": "120 วินาที",
	"_120seconds": "120 วินาที",
	"_15s": "15 วินาที",
	"_15seconds": "15 วินาที",
	"_30m": "30 นาที",
	"_30minutes": "30 นาที",
	"_30s": "30 วินาที",
	"_30seconds": "30 วินาที",
	"_60m": "60 นาที",
	"_60minutes": "60 นาที",
	"_60s": "60 วินาที",
	"_60seconds": "60 วินาที",
	"_7p5s": "7.5 วินาที",
	"_7p5seconds": "7.5 วินาที",
	"_90s": "90 วินาที",
	"_90seconds": "90 วินาที",
	"_AllDoors": "ทุก",
	"_Driver'sDoor": "ผู้ขับ",
	"on": "เปิด",
};

framework.registerAppDictLoaded("vehsettings", "th_TH");