var Localization_vehsettingsAppDict_zh_TW = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "自適應",
	"AdaptiveFront-lightingSystem": "自適應前照燈系統",
	"AlertTiming": "警告定時",
	"AtLine": "在線",
	"Auto": "自動",
	"AutoHeadlightOn": "自動大燈開啟",
	"AutoWiper": "感應式雨刷",
	"BSMBuzzerVolume": "Blind Spot Monitoring 音量",
	"Beep": "提示音",
	"BeepVolume": "提示音音量",
	"Beep_Line": "提示音",
	"BeforeLine": "線前",
	"Brightness": "亮度",
	"BrightnessControl": "亮度控制",
	"Calibration": "校準",
	"ChangingLASSettings": "正在變更Lane-keep Assist System設定",
	"Clock": "時鐘",
	"Close": "關閉",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "您確定要將Distance Recognition Support System設定復原為預設值嗎？",
	"DRSSResetError": "變更Distance Recognition Support System時發生錯誤。是否要重試？",
	"DRSSResetProgress": "正在變更Distance Recognition Support System",
	"Dark": "暗",
	"DaytimeRunningLights": "日間行駛燈",
	"Devices": "裝置",
	"Display": "顯示",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "車門鎖",
	"DoorLockMode": "自動落鎖模式",
	"DoorLockReset": "您確定要將車門鎖設定復原為預設值嗎？",
	"DoorLockResetError": "變更車門鎖設定時發生錯誤。是否要重試？",
	"DoorLockResetProgress": "正在變更車門鎖設定",
	"DoorRelockTime": "自動重鎖時間",
	"DriverAlert": "Driver Attention Alert",
	"Early": "早",
	"ErrorLASSettings": "變更Lane-keep Assist System時發生錯誤。是否要重試？",
	"FOWReset": "您確定要將Forward Obstruction Warning設定復原為預設值嗎？",
	"FOWResetError": "變更Forward Obstruction Warning設定時發生錯誤。是否要重試？",
	"FOWResetProgress": "正在變更Forward Obstruction Warning設定",
	"Far": "遠",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "您確定要將Active Driving Display設定復原為預設值嗎？",
	"HUDResetError": "修改Active Driving Display設定時發生錯誤。是否要重試？",
	"HUDResetProgress": "正在修改Active Driving Display設定",
	"HeadlightOffTimer": "大燈關閉計時器",
	"HeadlightOnWarning": "大燈開啟警告",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "高度",
	"High": "高",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "高",
	"High_Vibration": "高",
	"InterioLightsTimeOutDoorsClosed": "內飾燈逾時 - 關上車門時",
	"InterioLightsTimeOutDoorsOpen": "內飾燈逾時 – 開啟車門時",
	"InteriorLightTimeoutDoorClosedTitle": "內飾燈逾時 - 關上車門時",
	"InteriorLightTimeoutDoorOpenTitle": "內飾燈逾時 – 開啟車門時",
	"Intervention": "干預",
	"InterventionTiming": "干預定時",
	"KeylessLockBeepVol": "無鑰匙鎖車提示音音量",
	"LASAlert": "LAS警告",
	"LASDefaultValues": "您確定要將Lane-keep Assist System設定復原為預設值嗎？",
	"LASEarly": "早",
	"LASLate": "晚",
	"LASSound": "警告類型",
	"LASTiming": "LAS定時",
	"LDWSReset": "您確定要將Lane Departure Warning System設定復原為預設值嗎？",
	"LDWSResetError": "變更Lane Departure Warning System設定時發生錯誤。是否要重試？",
	"LDWSResetProgress": "正在變更Lane Departure Warning System設定",
	"LDWSTiming": "LDWS定時",
	"LaneDepartureAlert": "車道偏離警告",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "晚",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "亮",
	"LightOnReminderVolume": "亮燈提醒器音量",
	"Lighting": "照明",
	"LightingReset": "您確定要將照明設定復原為預設值嗎？",
	"LightingResetError": "變更照明設定時發生錯誤。是否要重試？",
	"LightingResetProgress": "正在變更照明設定",
	"LockShiftFromP": "鎖定：換出駐車檔 ",
	"LockShiftFromPUnlockInPark": "鎖定：換出駐車檔  解鎖：駐車狀態",
	"LockUnlock": "鎖定：行駛時 解鎖：駐車狀態",
	"LockWhenDriving": "鎖定：行駛時",
	"LockWhenDrivingUnlockIGNoff": "鎖定：行駛時解鎖：IGN關閉",
	"Long": "遠",
	"Low": "低",
	"Low_SensitivityLAS": "低",
	"Low_Vibration": "低",
	"Manual": "手動",
	"Med": "中等",
	"Medium": "中",
	"MediumDark": "中等暗度",
	"MediumLight": "中等亮度",
	"Medium_Int_OFF": "中等",
	"Medium_SensitivityLAS": "中等",
	"Mid": "中",
	"Middle": "中間",
	"Mode": "模式",
	"Navigation": "導航",
	"Near": "近",
	"Off": "關閉",
	"Often": "經常",
	"Often_Int_OFF": "經常",
	"OnceAllDoors": "一次：所有車門",
	"OnceDriversDoorTwiceAllDoors": "一次：駕駛員  兩次：所有車門",
	"Open": "開啟",
	"ParkingSensorIndication": "駐車感測器指示",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring 音量",
	"Rare": "很少",
	"Rare_Int_OFF": "很少",
	"Reset": "復位",
	"RumbleStrips": "振帶",
	"RumbleStrips_line": "振帶",
	"RumbleVolume": "振動帶音量",
	"SBSReset": "您確定要將Smart Brake Support設定復原為預設值嗎？",
	"SBSResetError": "變更Smart Brake Support設定時發生錯誤。是否要重試？",
	"SBSResetProgress": "正在變更Smart Brake Support設定",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "您確定要將SBS/SCBS設定復原為預設值嗎？",
	"SBS_SCBSResetError": "變更SBS/SCBS設定時發生錯誤。是否要重試？",
	"SBS_SCBSResetProgress": "正在變更 SBS/SCBS 設定",
	"SCBS": "Smart City Brake Support",
	"Safety": "安全",
	"Safetysettings": "安全設置",
	"Sensitivity": "敏感度",
	"Sensitivity_Intervention_OFF": "警告",
	"Settings": "設置",
	"Short": "近",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "聲音",
	"System": "系統",
	"ThreeFlashTurnSignal": "三次閃燈轉向訊號",
	"Timing": "定時",
	"Turn": "轉向",
	"TurnProgress": "正在變更轉向設定",
	"TurnReset": "您確定要將轉向設定復原為預設值嗎？",
	"TurnResetError": "變更轉向設定時發生錯誤。是否要重試？",
	"TurnSettings": "轉向",
	"TurnSignalIndicatorVolume": "轉向訊號音量",
	"UnlockMode": "解鎖模式",
	"Vehicle": "車輛",
	"VehicleSettings": "車輛設置",
	"Vibration": "振動",
	"VibrationStrength": "振動強度",
	"Vibration_Line": "振動",
	"Volume": "音量",
	"WalkAwayLock": "離車車鎖",
	"Warning": "警告",
	"WarningDistance": "警告距離",
	"_0s": "0 秒",
	"_0seconds": "0秒",
	"_10m": "10 分鐘",
	"_10minutes": "10分鐘",
	"_120s": "120 秒",
	"_120seconds": "120秒",
	"_15s": "15 秒",
	"_15seconds": "15秒",
	"_30m": "30 分鐘",
	"_30minutes": "30分鐘",
	"_30s": "30 秒",
	"_30seconds": "30秒",
	"_60m": "60 分鐘",
	"_60minutes": "60分鐘",
	"_60s": "60 秒",
	"_60seconds": "60秒",
	"_7p5s": "7.5 秒",
	"_7p5seconds": "7.5秒",
	"_90s": "90 秒",
	"_90seconds": "90秒",
	"_AllDoors": "全部",
	"_Driver'sDoor": "駕駛員",
	"on": "開啟",
};

framework.registerAppDictLoaded("vehsettings", "zh_TW");