var Localization_vehsettingsAppDict_lt_LT = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Adaptyvi",
	"AdaptiveFront-lightingSystem": "Adaptive Front-lighting System",
	"AlertTiming": "Įspėjimo laikas",
	"AtLine": "Ties l.",
	"Auto": "Auto",
	"AutoHeadlightOn": "Priekinių žibintų autom. įj.",
	"AutoWiper": "Valytuvas su lietaus jutikliu",
	"BSMBuzzerVolume": "Blind Spot Monitoring Garsumas",
	"Beep": "Pyptelėj",
	"BeepVolume": "Pyptelėjimo garsumas",
	"Beep_Line": "Pyptelėj",
	"BeforeLine": "Prieš l.",
	"Brightness": "Šviesumas",
	"BrightnessControl": "Šviesumo valdymas",
	"Calibration": "Kalibravimas",
	"ChangingLASSettings": "LAS nustatymųš keitimas",
	"Clock": "Laikrod.",
	"Close": "Užd.",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Ar tikrai norite atkurti numatytąsias Distance Recognition Support System (DRSS) nustatymų vertes?",
	"DRSSResetError": "Klaida keičiant Distance Recognition Support System (DRSS). Norite bandyti iš naujo?",
	"DRSSResetProgress": "Distance Recognition Support System (DRSS) keitimas",
	"Dark": "Tamsus",
	"DaytimeRunningLights": "Dieniniai žibintai",
	"Devices": "Įreng.",
	"Display": "Ekranas",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Durų užraktas",
	"DoorLockMode": "Autom. durų užrakinimo rež.",
	"DoorLockReset": "Ar tikrai norite atkurti durų užrakinimo nustatymų numatytąsias vertes?",
	"DoorLockResetError": "Klaida keičiant durų užrakinimo parametrus. Norite bandyti iš naujo?",
	"DoorLockResetProgress": "Durų užrakto parametrų keitimas",
	"DoorRelockTime": "Automatinio užsirakinimo laikas",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Anksti",
	"ErrorLASSettings": "Klaida keičiant Lane-keep Assist System. Ar norite bandyti iš naujo?",
	"FOWReset": "Ar tikrai norite atkurti Forward Obstruction Warning nustatymų numatytąsias vertes?",
	"FOWResetError": "Klaida keičiant Forward Obstruction Warning parametrus. Norite bandyti iš naujo?",
	"FOWResetProgress": "Forward Obstruction Warning (FOW) parametrų keitimas",
	"Far": "Toli",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Ar tikrai norite Active Driving Display nustatymų numatytąsias vertes?",
	"HUDResetError": "Klaida keičiant Active Driving Display nustatymus. Norite bandyti iš naujo?",
	"HUDResetProgress": "Active Driving Display parametrų keit.",
	"HeadlightOffTimer": "Priekinių žibintų išjungimo laikmatis",
	"HeadlightOnWarning": "Priek. Žib. Įj. įsp.",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Aukštis",
	"High": "Aukšt.",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Aukšt.",
	"High_Vibration": "Aukšt.",
	"InterioLightsTimeOutDoorsClosed": "Sal. apšv. skirt. laikas – durys užd.",
	"InterioLightsTimeOutDoorsOpen": "Sal. lemp. Skirt. laikas – durys atid.",
	"InteriorLightTimeoutDoorClosedTitle": "Sal. lemp. skirt. laikas – durys užd.",
	"InteriorLightTimeoutDoorOpenTitle": "Sal. lemp. skirt. laikas – durys atid.",
	"Intervention": "Įsijungimas",
	"InterventionTiming": "Įsijungimo laikas",
	"KeylessLockBeepVol": "Berakčio užrakto pyptelėjimo gars.",
	"LASAlert": "LAS įspėjimas",
	"LASDefaultValues": "Ar tikrai norite atkurti Lane-keep Assist System nustatymų numatytąsias vertes?",
	"LASEarly": "Anksti",
	"LASLate": "Vėlai",
	"LASSound": "Įspėjimo tipas",
	"LASTiming": "LAS laiko nustatymas",
	"LDWSReset": "Ar tikrai norite atkurti Lane Departure Warning System (LDWS) nustatymų numatytąsias vertes?",
	"LDWSResetError": "Klaida keičiant Lane Departure Warning System (LDWS) nustatymus. Norite bandyti iš naujo?",
	"LDWSResetProgress": "Lane Departure Warning System (LDWS) nustatymų keitimas",
	"LDWSTiming": "LDWS laiko nustatymas",
	"LaneDepartureAlert": "Įsp. apie išvaž. iš eismo juostos",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Vėlai",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Lengva",
	"LightOnReminderVolume": "Prim. apšv. įj. gars.",
	"Lighting": "Apšvietimas",
	"LightingReset": "Ar tikrai norite atkurti šviesų nustatymų numatytąsias vertes?",
	"LightingResetError": "Klaida keičiant šviesų nustatymus. Norite bandyti iš naujo?",
	"LightingResetProgress": "Šviesų nustatymų keitimas",
	"LockShiftFromP": "Užrakinti: perjungiant iš stovėjimo",
	"LockShiftFromPUnlockInPark": "Užr.: perj. iš stov.  Atrakinti: stovint",
	"LockUnlock": "Užrakinti: vairuojant atrak.: stovint",
	"LockWhenDriving": "Užrakinti: vairuojant",
	"LockWhenDrivingUnlockIGNoff": "Užr.: vairavimo metu atr.: degimas išj.",
	"Long": "Toli",
	"Low": "Žemas",
	"Low_SensitivityLAS": "Žemas",
	"Low_Vibration": "Žemas",
	"Manual": "Rank.",
	"Med": "Vid.",
	"Medium": "Vidutinis",
	"MediumDark": "Vid. Tam.",
	"MediumLight": "Vid. Švie.",
	"Medium_Int_OFF": "Vid",
	"Medium_SensitivityLAS": "Vid",
	"Mid": "Vidur.",
	"Middle": "Vid.",
	"Mode": "Režimas",
	"Navigation": "Navigacija",
	"Near": "Arti",
	"Off": "Išj. pr.",
	"Often": "Dažnai",
	"Often_Int_OFF": "Dažnai",
	"OnceAllDoors": "Vieną kartą: visos durys",
	"OnceDriversDoorTwiceAllDoors": "Vieną kart.: vair. Du kart.: visos dur.",
	"Open": "Atid.",
	"ParkingSensorIndication": "Pastatymo jutiklio parodymai",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Garsumas",
	"Rare": "Retas",
	"Rare_Int_OFF": "Retas",
	"Reset": "Atstatyti",
	"RumbleStrips": "Aps. j.",
	"RumbleStrips_line": "Aps. j.",
	"RumbleVolume": "Įsp. juostos gars.",
	"SBSReset": "Ar tikrai norite atkurti Smart Brake Support (SBS) nustatymų numatytąsias vertes?",
	"SBSResetError": "Klaida keičiant Smart Brake Support (SBS) nustatymus. Norite bandyti iš naujo?",
	"SBSResetProgress": "Smart Brake Support (SBS) nustatymų keitimas",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Ar tikrai norite atkurti SBS/SCBS nustatymų numatytąsias vertes?",
	"SBS_SCBSResetError": "Klaida keičiant SBS/SCBS nustatymus. Norite bandyti iš naujo?",
	"SBS_SCBSResetProgress": "SBS/SCBS verčių keitimas",
	"SCBS": "Smart City Brake Support",
	"Safety": "Sauga",
	"Safetysettings": "Saugos nustatymai",
	"Sensitivity": "Jautrumas",
	"Sensitivity_Intervention_OFF": "Įspėjimas",
	"Settings": "Nustatymai",
	"Short": "Arti",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Garsas",
	"System": "Sistema",
	"ThreeFlashTurnSignal": "3 mirksnių posūkio signalas",
	"Timing": "Laiko nustatymas",
	"Turn": "Sukti",
	"TurnProgress": "Posūkio nustatymų keitimas",
	"TurnReset": "Ar tikrai  norite atkurti posūkio nustatymų numatytąsias vertes?",
	"TurnResetError": "Klaida keičiant posūkio nustatymus. Norite bandyti iš naujo?",
	"TurnSettings": "Pasukti",
	"TurnSignalIndicatorVolume": "Posūkio signalo garsumas",
	"UnlockMode": "Atrakinimo režimas",
	"Vehicle": "Automo.",
	"VehicleSettings": "Aut. nustatymai",
	"Vibration": "Vibracija",
	"VibrationStrength": "Vibracijos stiprumas",
	"Vibration_Line": "Vibracija",
	"Volume": "Garsumas",
	"WalkAwayLock": "Užrakinimas nuėjus",
	"Warning": "Įspėjimas",
	"WarningDistance": "Įspėjimo atstumas",
	"_0s": "0 sek.",
	"_0seconds": "0 sekundžių",
	"_10m": "10 min.",
	"_10minutes": "10 minučių",
	"_120s": "120 sek.",
	"_120seconds": "120 sekundžių",
	"_15s": "15 sek.",
	"_15seconds": "15 sekundžių",
	"_30m": "30 min.",
	"_30minutes": "30 minučių",
	"_30s": "30 sek.",
	"_30seconds": "30 sekundžių",
	"_60m": "60 min.",
	"_60minutes": "60 minučių",
	"_60s": "60 sek.",
	"_60seconds": "60 sekundžių",
	"_7p5s": "7.5 sek.",
	"_7p5seconds": "7.5 sekundės",
	"_90s": "90 sek.",
	"_90seconds": "90 sekundžių",
	"_AllDoors": "Visi",
	"_Driver'sDoor": "Vair.",
	"on": "Įj.",
};

framework.registerAppDictLoaded("vehsettings", "lt_LT");