var Localization_vehsettingsAppDict_da_DK = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Adaptivt",
	"AdaptiveFront-lightingSystem": "Adaptivt forlygtesystem",
	"AlertTiming": "Tid for alarm",
	"AtLine": "Sen",
	"Auto": "Auto",
	"AutoHeadlightOn": "Følsomhed for lygtetænding",
	"AutoWiper": "Vinduesvisker m. regnsensor",
	"BSMBuzzerVolume": "Blind Spot Monitoring Volumen",
	"Beep": "Bip",
	"BeepVolume": "Bipvolumen",
	"Beep_Line": "Bip",
	"BeforeLine": "Tidlig",
	"Brightness": "Lysstyrke",
	"BrightnessControl": "Lysstyrkestyring",
	"Calibration": "Kalibrering",
	"ChangingLASSettings": "Ændring af indstillinger til LAS",
	"Clock": "Ur",
	"Close": "Luk",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Er du sikker på, du ønsker at nulstille indstillinger for Distance Recognition Support System?",
	"DRSSResetError": "Fejl ved ændring af indstillinger for Distance Recognition Support System. Vil du forsøge igen?",
	"DRSSResetProgress": "Ændrer  indstillinger for Distance Recognition Support System",
	"Dark": "Mørkt",
	"DaytimeRunningLights": "Kørelys",
	"Devices": "Enheder",
	"Display": "Display",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Dørlås",
	"DoorLockMode": "Automatisk dørlåsning",
	"DoorLockReset": "Er du sikker på, du ønsker at nulstille indstillinger for dørlåse?",
	"DoorLockResetError": "Fejl ved ændring af indstillinger for dørlåse. Vil du forsøge igen?",
	"DoorLockResetProgress": "Ændrer indstillinger for dørlåse",
	"DoorRelockTime": "Tid for automatisk genlåsning",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Tidlig",
	"ErrorLASSettings": "Der opstod en fejl under ændring af indstillingerne til Lane-keep Assist System. Vil du prøve igen?",
	"FOWReset": "Er du sikker på, du ønsker at nulstille indstillinger for Forward Obstruction Warning (FOW)?",
	"FOWResetError": "Fejl ved ændring af indstillinger for Forward Obstruction Warning (FOW). Vil du forsøge igen?",
	"FOWResetProgress": "Ændrer indstillinger for Forward Obstruction Warning (FOW)",
	"Far": "Fjern",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Er du sikker på, du ønsker at nulstille indstillinger for Active Driving Display?",
	"HUDResetError": "Fejl ved ændring af indstillinger for Active Driving Display. Vil du forsøge igen?",
	"HUDResetProgress": "Ændrer indstill. for Active Driving Display",
	"HeadlightOffTimer": "Forsinkelse forlygter",
	"HeadlightOnWarning": "Adv. lys tændt",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Højde",
	"High": "Høj",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Høj",
	"High_Vibration": "Høj",
	"InterioLightsTimeOutDoorsClosed": "Timeout for kabinelys: dør lukket",
	"InterioLightsTimeOutDoorsOpen": "Timeout for kabinelys: dør åben",
	"InteriorLightTimeoutDoorClosedTitle": "Timeout for kabinelys – dør lukket",
	"InteriorLightTimeoutDoorOpenTitle": "Timeout for kabinelys – dør åben",
	"Intervention": "Intervention",
	"InterventionTiming": "Tid for intervention",
	"KeylessLockBeepVol": "Lyd v. automatisk låsning",
	"LASAlert": "LAS-advarsel",
	"LASDefaultValues": "Er du sikker på, at du vil ændre indstillingerne til Lane-keep Assist System tilbage til standardværdier?",
	"LASEarly": "Tidlig",
	"LASLate": "Sent",
	"LASSound": "Alarmtype",
	"LASTiming": "LAS-timing",
	"LDWSReset": "Er du sikker på, du ønsker at nulstille indstillinger for Lane Departure Warning System (LDWS)?",
	"LDWSResetError": "Fejl ved ændring af indstillinger for Lane Departure Warning System (LDWS). Vil du forsøge igen?",
	"LDWSResetProgress": "Ændrer indstillinger for Lane Departure Warning System (LDWS)",
	"LDWSTiming": "LDWS Timing",
	"LaneDepartureAlert": "Vognbaneoverskridelse",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Sent",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Lyst",
	"LightOnReminderVolume": "Alarm tændt lys",
	"Lighting": "Lys",
	"LightingReset": "Er du sikker på, du ønsker at nulstille lysindstillinger?",
	"LightingResetError": "Fejl ved ændring af lysindstillinger. Vil du forsøge igen?",
	"LightingResetProgress": "Ændrer lysindstillinger",
	"LockShiftFromP": "Lås v. skift fra P.",
	"LockShiftFromPUnlockInPark": "Lås v. skift fra P. Lås op v.skift til P.",
	"LockUnlock": "Låst: Under kørsel lås op: I parkering",
	"LockWhenDriving": "Lås under kørsel",
	"LockWhenDrivingUnlockIGNoff": "Lås: under kørsel: Motor slukket",
	"Long": "Fjern",
	"Low": "Lav",
	"Low_SensitivityLAS": "Lav",
	"Low_Vibration": "Lav",
	"Manual": "Manuel",
	"Med": "Mel.",
	"Medium": "Mellem",
	"MediumDark": "Halvmørk.",
	"MediumLight": "Halvlyst",
	"Medium_Int_OFF": "Mel.",
	"Medium_SensitivityLAS": "Mel.",
	"Mid": "Mid.",
	"Middle": "Mellem",
	"Mode": "Tilstand",
	"Navigation": "Navigering",
	"Near": "Nær",
	"Off": "Fra",
	"Often": "Ofte",
	"Often_Int_OFF": "Ofte",
	"OnceAllDoors": "1 gang: Alle døre",
	"OnceDriversDoorTwiceAllDoors": "Et tryk: førerdør. To tryk: alle døre",
	"Open": "Åbn",
	"ParkingSensorIndication": "Parkeringssensorindikation",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Volumen",
	"Rare": "Sjælden",
	"Rare_Int_OFF": "Sjælden",
	"Reset": "Nulstil",
	"RumbleStrips": "Rum.",
	"RumbleStrips_line": "Rum.",
	"RumbleVolume": "Rumlestribe-vol.",
	"SBSReset": "Er du sikker på, du ønsker at nulstille indstillinger for Smart Brake Support?",
	"SBSResetError": "Fejl ved ændring af indstillinger for Smart Brake Support. Vil du forsøge igen?",
	"SBSResetProgress": "Ændrer indstillinger for Smart Brake Support",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Er du sikker på, du ønsker at nulstille indstillinger for SBS/SCBS?",
	"SBS_SCBSResetError": "Fejl ved ændring af indstillinger for SBS/SCBS. Vil du forsøge igen?",
	"SBS_SCBSResetProgress": "Ændrer indstillinger for SBS/SCBS",
	"SCBS": "Smart City Brake Support",
	"Safety": "Sikkerh.",
	"Safetysettings": "Sikkerhedsindst.",
	"Sensitivity": "Følsomhed",
	"Sensitivity_Intervention_OFF": "Advarsel",
	"Settings": "Indstillinger",
	"Short": "Nær",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Lyd",
	"System": "System",
	"ThreeFlashTurnSignal": "Komfortblink",
	"Timing": "Timing",
	"Turn": "Blinklys",
	"TurnProgress": "Ændrer indstillinger for blinklys",
	"TurnReset": "Er du sikker på, du ønsker at nulstille indstillinger for blinklys?",
	"TurnResetError": "Fejl ved ændring af indstillinger for blinklys. Vil du forsøge igen?",
	"TurnSettings": "Blinklys",
	"TurnSignalIndicatorVolume": "Volumen for blinklys",
	"UnlockMode": "Oplås tilstand",
	"Vehicle": "Køretøj",
	"VehicleSettings": "Indstil. for køretøj",
	"Vibration": "Vibration",
	"VibrationStrength": "Vibrationsstyrke",
	"Vibration_Line": "Vibration",
	"Volume": "Volumen",
	"WalkAwayLock": "Lås når bilen forlades",
	"Warning": "Advarsel",
	"WarningDistance": "Advarselsafstand",
	"_0s": "0 sek.",
	"_0seconds": "0 sekunder",
	"_10m": "10 min",
	"_10minutes": "10 minutter",
	"_120s": "120 sek.",
	"_120seconds": "120 sekunder",
	"_15s": "15 sek.",
	"_15seconds": "15 sekunder",
	"_30m": "30 min",
	"_30minutes": "30 minutter",
	"_30s": "30 sek.",
	"_30seconds": "30 sekunder",
	"_60m": "60 min",
	"_60minutes": "60 minutter",
	"_60s": "60 sek.",
	"_60seconds": "60 sekunder",
	"_7p5s": "7,5 sek.",
	"_7p5seconds": "7,5 sekunder",
	"_90s": "90 sek.",
	"_90seconds": "90 sekunder",
	"_AllDoors": "Alle",
	"_Driver'sDoor": "Fører",
	"on": "Til",
};

framework.registerAppDictLoaded("vehsettings", "da_DK");