var Localization_vehsettingsAppDict_pt_PT = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Adaptável",
	"AdaptiveFront-lightingSystem": "Sistema de Iluminação Frontal Adaptável",
	"AlertTiming": "Tempo do alerta",
	"AtLine": "Linha",
	"Auto": "Auto",
	"AutoHeadlightOn": "Farol Dianteiro Automático Ligado",
	"AutoWiper": "Limpa-pára-brisas com Sens. de Chuva",
	"BSMBuzzerVolume": "Blind Spot Monitoring Volume",
	"Beep": "Sinal",
	"BeepVolume": "Volume do Sinal",
	"Beep_Line": "Sinal",
	"BeforeLine": "Antes",
	"Brightness": "Luminosidade",
	"BrightnessControl": "Controlo de Luminosidade",
	"Calibration": "Calibragem",
	"ChangingLASSettings": "A alterar definições do LAS",
	"Clock": "Relógio",
	"Close": "Fechar",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Tem a certeza de que pretende reverter as definições de Distance Recognition Support System (DRSS) para os valores predefinidos?",
	"DRSSResetError": "Erro ao alterar as definições de Distance Recognition Support System (DRSS). Pretende tentar novamente?",
	"DRSSResetProgress": "A Alterar Distance Recognition Support System (DRSS)",
	"Dark": "Escuro",
	"DaytimeRunningLights": "Luzes Diurnas Permanentes",
	"Devices": "Disps.",
	"Display": "Ecrã",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Bloqueio de Portas",
	"DoorLockMode": "Modo Bloqueio de Portas Autom.",
	"DoorLockReset": "Tem a certeza de que pretende reverter as definições de Bloqueio de Portas para os valores predefinidos?",
	"DoorLockResetError": "Erro ao alterar definições de Bloqueio de Portas. Pretende tentar novamente?",
	"DoorLockResetProgress": "A Alterar Definições de Bloqueio de Portas",
	"DoorRelockTime": "Tempo de Novo Bloqueio Autom.",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Cedo",
	"ErrorLASSettings": "Erro ao alterar Lane-keep Assist System. Pretende tentar novamente?",
	"FOWReset": "Tem a certeza de que pretende reverter as definições de Forward Obstruction Warning (FOW) para os valores predefinidos?",
	"FOWResetError": "Erro ao alterar as definições de Forward Obstruction Warning (FOW). Pretende tentar novamente?",
	"FOWResetProgress": "A Alterar Forward Obstruction Warning (FOW)",
	"Far": "Longe",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Tem a certeza de que pretende reverter as definições de Active Driving Display para os valores predefinidos?",
	"HUDResetError": "Erro ao alterar as definições de Active Driving Display. Pretende tentar novamente?",
	"HUDResetProgress": "A Alterar Active Driving Display",
	"HeadlightOffTimer": "Temporizador para Desligar Faróis",
	"HeadlightOnWarning": "Aviso Faróis Ligs.",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Altura",
	"High": "Alto",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Alto",
	"High_Vibration": "Alto",
	"InterioLightsTimeOutDoorsClosed": "Tempo Ilum. Interior - Porta Fech.",
	"InterioLightsTimeOutDoorsOpen": "Tempo Ilum. Interior - Porta Aber.",
	"InteriorLightTimeoutDoorClosedTitle": "Tempo Luz Interior - Portas Fech.",
	"InteriorLightTimeoutDoorOpenTitle": "Tempo Luz Interior - Portas Aber.",
	"Intervention": "Intervenção",
	"InterventionTiming": "Tempo interven.",
	"KeylessLockBeepVol": "Vol. Sinal Bloqueio por Comando",
	"LASAlert": "Alerta LAS",
	"LASDefaultValues": "Tem a certeza de que pretende reverter as definições do Lane-keep Assist System para os respectivos valores predefinidos?",
	"LASEarly": "Cedo",
	"LASLate": "Atrasado",
	"LASSound": "Tipo de alerta",
	"LASTiming": "Tempo LAS",
	"LDWSReset": "Tem a certeza de que pretende reverter as definições de Lane Departure Warning System (LDWS) para os valores predefinidos?",
	"LDWSResetError": "Erro ao alterar as definições de Lane Departure Warning System (LDWS). Pretende tentar novamente?",
	"LDWSResetProgress": "A Alterar Lane Departure Warning System (LDWS)",
	"LDWSTiming": "Tempo de LDWS",
	"LaneDepartureAlert": "Alerta de saída de faixa",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Atrasado",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Luz",
	"LightOnReminderVolume": "Vol Lemb Luz",
	"Lighting": "Iluminação",
	"LightingReset": "Tem a certeza de que pretende reverter as definições de Iluminação para os valores predefinidos?",
	"LightingResetError": "Erro ao alterar definições de Iluminação. Pretende tentar novamente?",
	"LightingResetProgress": "A Alterar Definições de Iluminação",
	"LockShiftFromP": "Bloquear: Sair do Estacionamento ",
	"LockShiftFromPUnlockInPark": "Bloq: Fora estac Desbloq: Estac",
	"LockUnlock": "Bloq:Condução Desb:Estacionar",
	"LockWhenDriving": "Bloquear: Na Condução",
	"LockWhenDrivingUnlockIGNoff": "Bloq: Na Condução Desb:IGN Deslig.",
	"Long": "Longe",
	"Low": "Baixo",
	"Low_SensitivityLAS": "Baixo",
	"Low_Vibration": "Baixo",
	"Manual": "Man.",
	"Med": "Médio",
	"Medium": "Médio",
	"MediumDark": "Escuro Médio",
	"MediumLight": "Luz Média",
	"Medium_Int_OFF": "Médio",
	"Medium_SensitivityLAS": "Médio",
	"Mid": "Meio",
	"Middle": "Meio",
	"Mode": "Modo",
	"Navigation": "Navegação",
	"Near": "Próx.",
	"Off": "Deslig.",
	"Often": "Freq.",
	"Often_Int_OFF": "Freq.",
	"OnceAllDoors": "Uma Vez: Todas as Portas",
	"OnceDriversDoorTwiceAllDoors": "1 Vez: Condut. 2 Vezes: Tod. Portas",
	"Open": "Abrir",
	"ParkingSensorIndication": "Indicação dos Sensor de Estacionamento",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Volume",
	"Rare": "Raro",
	"Rare_Int_OFF": "Raro",
	"Reset": "Repor",
	"RumbleStrips": "Banda",
	"RumbleStrips_line": "Banda",
	"RumbleVolume": "Vol. Ban. Sonora",
	"SBSReset": "Tem a certeza de que pretende reverter as definições de Smart Brake Support (SBS) para os valores predefinidos?",
	"SBSResetError": "Erro ao alterar as definições de Smart Brake Support (SBS). Pretende tentar novamente?",
	"SBSResetProgress": "A Alterar Smart Brake Support (SBS)",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Tem a certeza de que pretende reverter as definições de SBS/SCBS para os valores predefinidos?",
	"SBS_SCBSResetError": "Erro ao alterar as definições de SBS/SCBS. Pretende tentar novamente?",
	"SBS_SCBSResetProgress": "A Alterar SBS/SCBS",
	"SCBS": "Smart City Brake Support",
	"Safety": "Seguran.",
	"Safetysettings": "Def. de Segur.",
	"Sensitivity": "Sensibilidade",
	"Sensitivity_Intervention_OFF": "Aviso",
	"Settings": "Definições",
	"Short": "Próx.",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Som",
	"System": "Sistema",
	"ThreeFlashTurnSignal": "Sinal Mudança de Direcção de 3 piscas",
	"Timing": "Tempo",
	"Turn": "Mudança de Direcção",
	"TurnProgress": "A Alterar Definições de Mudança de Direcção",
	"TurnReset": "Tem a certeza de que pretende reverter as definições de Mudança de Direcção para os valores predefinidos?",
	"TurnResetError": "Erro ao alterar definições de Mudança de Direcção. Pretende tentar novamente?",
	"TurnSettings": "Mudança de Direcção",
	"TurnSignalIndicatorVolume": "Vol. da Mudança Direcção",
	"UnlockMode": "Modo de Desbloqueio",
	"Vehicle": "Veículo",
	"VehicleSettings": "Def. do Veículo",
	"Vibration": "Vibração",
	"VibrationStrength": "Intensidade vibração",
	"Vibration_Line": "Vibração",
	"Volume": "Volume",
	"WalkAwayLock": "Bloqueio Automático (deixar)",
	"Warning": "Aviso",
	"WarningDistance": "Distân. de Aviso",
	"_0s": "0 s",
	"_0seconds": "0 segundos",
	"_10m": "10 min",
	"_10minutes": "10 minutos",
	"_120s": "120 s",
	"_120seconds": "120 segundos",
	"_15s": "15 s",
	"_15seconds": "15 segundos",
	"_30m": "30 min",
	"_30minutes": "30 minutos",
	"_30s": "30 s",
	"_30seconds": "30 segundos",
	"_60m": "60 min",
	"_60minutes": "60 minutos",
	"_60s": "60 s",
	"_60seconds": "60 segundos",
	"_7p5s": "7,5 s",
	"_7p5seconds": "7,5 segundos",
	"_90s": "90 s",
	"_90seconds": "90 segundos",
	"_AllDoors": "Todas",
	"_Driver'sDoor": "Conduc.",
	"on": "Em",
};

framework.registerAppDictLoaded("vehsettings", "pt_PT");