var Localization_vehsettingsAppDict_ru_RU = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Адаптивн",
	"AdaptiveFront-lightingSystem": "Aдаптивного головного освещения ",
	"AlertTiming": "Время предупрежд.",
	"AtLine": "В стр.",
	"Auto": "Авто",
	"AutoHeadlightOn": "Автоматическое включение фар",
	"AutoWiper": "Автомат.режим стекло-лей",
	"BSMBuzzerVolume": "Громк. Blind Spot Monitoring",
	"Beep": "Сигнал",
	"BeepVolume": "Громкость сигнала",
	"Beep_Line": "Сигнал",
	"BeforeLine": "Перед",
	"Brightness": "Яркость",
	"BrightnessControl": "Управление яркостью",
	"Calibration": "Калибровка",
	"ChangingLASSettings": "Изменение настроек LAS",
	"Clock": "Часы",
	"Close": "Закр.",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Вы действительно хотите выполнить возврат к настройкам Distance Recognition Support System (DRSS) по умолчанию?",
	"DRSSResetError": "Ошибка при изменении настроек Distance Recognition Support System (DRSS). Вы хотите повторить?",
	"DRSSResetProgress": "Изменение настроек Distance Recognition Support System (DRSS)",
	"Dark": "Темно",
	"DaytimeRunningLights": "Дневные ходовые огни",
	"Devices": "Устр-ва",
	"Display": "Дисплей",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Дверные замки",
	"DoorLockMode": "Режим авт. запирания двери",
	"DoorLockReset": "Вы уверены, что хотите вернуть настройки замков дверей на значения по умолчанию?",
	"DoorLockResetError": "Ошибка при изменении настроек замков дверей. Вы хотите повторить?",
	"DoorLockResetProgress": "Изменение настроек замков дверей",
	"DoorRelockTime": "Время авт. повт. запирания",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Раньше",
	"ErrorLASSettings": "Ошибка при изменении настроек Lane-keep Assist System. Хотите повторить?",
	"FOWReset": "Вы уверены, что хотите вернуть настройки Forward Obstruction Warning (FOW) на значения по умолчанию?",
	"FOWResetError": "Ошибка при изменении настроек Forward Obstruction Warning (FOW). Вы хотите повторить?",
	"FOWResetProgress": "Изменение настроек Forward Obstruction Warning (FOW)",
	"Far": "Дал.",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Вы уверены, что хотите вернуть настройки Active Driving Display на значения по умолчанию?",
	"HUDResetError": "Ошибка при изменении настроек Active Driving Display. Вы хотите повторить?",
	"HUDResetProgress": "Изменение настроек  AD-Disp",
	"HeadlightOffTimer": "Таймер отключения фар",
	"HeadlightOnWarning": "Пред. о вкл. фар",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Высота",
	"High": "Выс.",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Выс.",
	"High_Vibration": "Выс.",
	"InterioLightsTimeOutDoorsClosed": "Откл.освещ.салона при закр.дв.",
	"InterioLightsTimeOutDoorsOpen": "Откл.освещ.салона при откр.дв.",
	"InteriorLightTimeoutDoorClosedTitle": "Таймаут подсветки - Двери закр.",
	"InteriorLightTimeoutDoorOpenTitle": "Таймаут подсветки - Двери откр.",
	"Intervention": "Вмешательство",
	"InterventionTiming": "Время вмешательс.",
	"KeylessLockBeepVol": "Гром.сиг.зап.двр б/з клч",
	"LASAlert": "Сообщение LAS",
	"LASDefaultValues": "Вернуть настройки Lane-keep Assist System на значения по умолчанию?",
	"LASEarly": "Раньше",
	"LASLate": "Позже",
	"LASSound": "Тип предупреждения",
	"LASTiming": "Расчет времени LAS",
	"LDWSReset": "Вы уверены, что хотите вернуть настройки Lane Departure Warning System (LDWS) на значения по умолчанию?",
	"LDWSResetError": "Ошибка при изменении настроек Lane Departure Warning System (LDWS). Вы хотите повторить?",
	"LDWSResetProgress": "Изменение настроек Lane Departure Warning System (LDWS)",
	"LDWSTiming": "Расчет времени LDWS",
	"LaneDepartureAlert": "Предупр. о выезде за пред. пол.",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Позже",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Светло",
	"LightOnReminderVolume": "Громк. сигн. вкл-го осв-ия",
	"Lighting": "Освещение",
	"LightingReset": "Вы уверены, что хотите вернуть настройки освещения на значения по умолчанию?",
	"LightingResetError": "Ошибка при изменении настроек освещения. Вы хотите повторить?",
	"LightingResetProgress": "Изменение настроек освещения",
	"LockShiftFromP": "Блок: снятие с тормоза ",
	"LockShiftFromPUnlockInPark": "Блок: снятие с тормоза Разбл: при парк.",
	"LockUnlock": "Блок: разбл. при вожд.  Разбл: при парк.",
	"LockWhenDriving": "Блокировка: во время движения",
	"LockWhenDrivingUnlockIGNoff": "Блок: разбл. при вожд. Разбл: ЗЖГ выкл.",
	"Long": "Дал.",
	"Low": "Низ.",
	"Low_SensitivityLAS": "Низ.",
	"Low_Vibration": "Низ.",
	"Manual": "Ручн.",
	"Med": "Сред.",
	"Medium": "Средне",
	"MediumDark": "Средне темно",
	"MediumLight": "Средне светло",
	"Medium_Int_OFF": "Сред",
	"Medium_SensitivityLAS": "Сред",
	"Mid": "Сред.",
	"Middle": "Средн.",
	"Mode": "Режим",
	"Navigation": "Навигация",
	"Near": "Близ.",
	"Off": "Выкл",
	"Often": "Часто",
	"Often_Int_OFF": "Часто",
	"OnceAllDoors": "Один раз: все двери",
	"OnceDriversDoorTwiceAllDoors": "x1: дверь водителя x2: все двери",
	"Open": "Откр.",
	"ParkingSensorIndication": "Ультразвуковой датчик парковки",
	"RVMBuzzerVolume": "Громк. Rear Vehicle Monitoring",
	"Rare": "Редко",
	"Rare_Int_OFF": "Редко",
	"Reset": "Сбросить",
	"RumbleStrips": "Рокот",
	"RumbleStrips_line": "Рокот",
	"RumbleVolume": "Громкость рокота",
	"SBSReset": "Вы уверены, что хотите вернуть настройки Smart Brake Support (SBS) на значения по умолчанию?",
	"SBSResetError": "Ошибка при изменении настроек Smart Brake Support (SBS). Вы хотите повторить?",
	"SBSResetProgress": "Изменение настроек Smart Brake Support (SBS)",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Вы уверены, что хотите вернуть настройки SBS/SCBS на значения по умолчанию?",
	"SBS_SCBSResetError": "Ошибка при изменении настроек SBS/SCBS. Вы хотите повторить?",
	"SBS_SCBSResetProgress": "Изменение настроек SBS/SCBS",
	"SCBS": "Smart City Brake Support",
	"Safety": "Безопас.",
	"Safetysettings": "Настр. безопас.",
	"Sensitivity": "Чувствит.",
	"Sensitivity_Intervention_OFF": "Предупреждение",
	"Settings": "Настройки",
	"Short": "Близ.",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Звук",
	"System": "Система",
	"ThreeFlashTurnSignal": "Тройной сигнал поворота",
	"Timing": "Расчет времени",
	"Turn": "Указатель поворота",
	"TurnProgress": "Изм-ие настр.указ.поворота",
	"TurnReset": "Вернуть настройки указателей поворота на значения по умолчанию?",
	"TurnResetError": "Ошибка при изменении настроек указателя поворота. Повторить?",
	"TurnSettings": "Указатель поворота",
	"TurnSignalIndicatorVolume": "Громк. сигнала поворота",
	"UnlockMode": "Режим разблокировки",
	"Vehicle": "Авто",
	"VehicleSettings": "Настройки авто",
	"Vibration": "Вибрация",
	"VibrationStrength": "Сила вибрации",
	"Vibration_Line": "Вибрация",
	"Volume": "Громкость",
	"WalkAwayLock": "Запирание при покидании автомобиля",
	"Warning": "Предупреждение",
	"WarningDistance": "Расст. предупр.",
	"_0s": "0 с",
	"_0seconds": "0 секунд",
	"_10m": "10 мин",
	"_10minutes": "10 минут",
	"_120s": "120 с",
	"_120seconds": "120 секунд",
	"_15s": "15 с",
	"_15seconds": "15 секунд",
	"_30m": "30 мин",
	"_30minutes": "30 минут",
	"_30s": "30 с",
	"_30seconds": "30 секунд",
	"_60m": "60 мин",
	"_60minutes": "60 минут",
	"_60s": "60 с",
	"_60seconds": "60 секунд",
	"_7p5s": "7,5 с",
	"_7p5seconds": "7,5 секунд",
	"_90s": "90 с",
	"_90seconds": "90 секунд",
	"_AllDoors": "Все",
	"_Driver'sDoor": "Водит.",
	"on": "Вкл.",
};

framework.registerAppDictLoaded("vehsettings", "ru_RU");