var Localization_vehsettingsAppDict_sr_RS = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Prilagodljiv",
	"AdaptiveFront-lightingSystem": "Prilagodljivi sistem prednjih farova",
	"AlertTiming": "Pr. vr. za upoz.",
	"AtLine": "Na lin.",
	"Auto": "Auto",
	"AutoHeadlightOn": "Autom. uklj. prednjih svetala",
	"AutoWiper": "Brisač osetljiv na kišu",
	"BSMBuzzerVolume": "Blind Spot Monitoring Jač. zv.",
	"Beep": "Zvučni",
	"BeepVolume": "Jačina zvučnog signala",
	"Beep_Line": "Zvučni",
	"BeforeLine": "Pre lin.",
	"Brightness": "Osvetljenost",
	"BrightnessControl": "Kontrola osvetljenosti",
	"Calibration": "Baždarenje",
	"ChangingLASSettings": "Promena postavki LAS sistema",
	"Clock": "Sat",
	"Close": "Zatv.",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Da li ste sigurni da želite da vratite postavke Distance Recognition Support System (DRSS) na fabrički podrazumevane vrednosti?",
	"DRSSResetError": "Greška pri promeni postavki Distance Recognition Support System (DRSS). Da li želite da pokušate ponovo?",
	"DRSSResetProgress": "Promena postavki Distance Recognition Support System (DRSS)",
	"Dark": "Tamno",
	"DaytimeRunningLights": "Dnevna svetla",
	"Devices": "Uređaji",
	"Display": "Ekran",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Zaključavanje vrata",
	"DoorLockMode": "Režim autom. zaključ. vrata",
	"DoorLockReset": "Da li ste sigurni da želite da vratite postavke za zaključavanje vrata na fabrički podrazumevane vrednosti?",
	"DoorLockResetError": "Greška kod menjanja postavki za zaključavanje vrata. Da li želite da pokušate ponovo?",
	"DoorLockResetProgress": "Promena postavki za zaključavanje vrata",
	"DoorRelockTime": "Vreme autom. ponovnog zaključ.",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Rano",
	"ErrorLASSettings": "Greška pri promeni postavki Lane-keep Assist System. Da li želite da pokušate ponovo?",
	"FOWReset": "Da li ste sigurni da želite da vratite postavke Forward Obstruction Warning na fabrički podrazumevane vrednosti?",
	"FOWResetError": "Greška pri promeni postavki Forward Obstruction Warning. Da li želite da pokušate ponovo?",
	"FOWResetProgress": "Promena postavki Forward Obstruction Warning",
	"Far": "Daleko",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Da li ste sigurni da želite da vratite postavke Active Driving Display na fabrički podrazumevane vrednosti?",
	"HUDResetError": "Greška pri promeni postavki Active Driving Display. Da li želite da pokušate ponovo?",
	"HUDResetProgress": "Promena postavki Active Driving Display",
	"HeadlightOffTimer": "Tajmer za isklj. prednjih svetala",
	"HeadlightOnWarning": "Upoz.uklj.pr.svet.",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Visina",
	"High": "Visok",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Visok",
	"High_Vibration": "Visok",
	"InterioLightsTimeOutDoorsClosed": "Istek.vr.osvet. kabine - Vrata zatv.",
	"InterioLightsTimeOutDoorsOpen": "Istek.vr.osvetlj. kabine - Vrata otv.",
	"InteriorLightTimeoutDoorClosedTitle": "Kraj osvetlj.unut.kab.-Vrat.zatv.",
	"InteriorLightTimeoutDoorOpenTitle": "Kraj osvetlj.unut.kab.-Vrat.otv.",
	"Intervention": "Intervencija",
	"InterventionTiming": "Pr. vr. za inter.",
	"KeylessLockBeepVol": "Jačina zv. signala dalj. zaklj./otklj.",
	"LASAlert": "LAS upozorenje",
	"LASDefaultValues": "Da li ste sigurni da želite da vratite postavke Lane-keep Assist System na fabrički podrazumevane vrednosti?",
	"LASEarly": "Rano",
	"LASLate": "Kasno",
	"LASSound": "Vrsta upozorenja",
	"LASTiming": "Vremensko podešavanje LAS",
	"LDWSReset": "Da li ste sigurni da želite da vratite postavke Lane Departure Warning System (LDWS) na fabrički podrazumevane vrednosti?",
	"LDWSResetError": "Greška pri promeni postavki Lane Departure Warning System (LDWS). Da li želite da pokušate ponovo?",
	"LDWSResetProgress": "Promena postavki Lane Departure Warning System (LDWS)",
	"LDWSTiming": "Vremensko podešavanje LDWS",
	"LaneDepartureAlert": "Upozorenje o napuštanju trake",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Kasno",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Svetlo",
	"LightOnReminderVolume": "Jač. zv. uklj. sv.",
	"Lighting": "Osvetljenje",
	"LightingReset": "Da li ste sigurni da želite da vratite postavke za osvetljenje na fabrički podrazumevane vrednosti?",
	"LightingResetError": "Greška kod menjanja postavki za osvetljenje. Da li želite da pokušate ponovo?",
	"LightingResetProgress": "Promena postavki za osvetljenje",
	"LockShiftFromP": "Zaklj.: Ubac. u brzinu iz park. položaja",
	"LockShiftFromPUnlockInPark": "Zklj:Ubac. u brz. iz p.pol. - otklj:p.pol.",
	"LockUnlock": "Zaključano: Vožnja otključano: Parki.",
	"LockWhenDriving": "Zaključaj: Tokom vožnje",
	"LockWhenDrivingUnlockIGNoff": "Zaklj.:U vožnji otklj.:Auto isklj.",
	"Long": "Daleko",
	"Low": "Nizak",
	"Low_SensitivityLAS": "Nizak",
	"Low_Vibration": "Nizak",
	"Manual": "Ručno",
	"Med": "Sred.",
	"Medium": "Srednji",
	"MediumDark": "Sred.Tam.",
	"MediumLight": "Sred.Svet.",
	"Medium_Int_OFF": "Sred",
	"Medium_SensitivityLAS": "Sred",
	"Mid": "Sred.",
	"Middle": "Srednji",
	"Mode": "Režim",
	"Navigation": "Navigacija",
	"Near": "Blizu",
	"Off": "Isključ.",
	"Often": "Često",
	"Often_Int_OFF": "Često",
	"OnceAllDoors": "Jednom: Sva vrata",
	"OnceDriversDoorTwiceAllDoors": "Jedn.:Vozač.dva puta:Sva vrata",
	"Open": "Otvori",
	"ParkingSensorIndication": "Indikator parking senzora",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Jač. zv.",
	"Rare": "Retko",
	"Rare_Int_OFF": "Retko",
	"Reset": "Resetuj",
	"RumbleStrips": "Zv.tr.",
	"RumbleStrips_line": "Zv.tr.",
	"RumbleVolume": "Jačina zvuč. trake",
	"SBSReset": "Da li ste sigurni da želite da vratite postavke Smart Brake Support (SBS) na fabrički podrazumevane vrednosti?",
	"SBSResetError": "Greška pri promeni postavki Smart Brake Support (SBS). Da li želite da pokušate ponovo?",
	"SBSResetProgress": "Promena postavki Smart Brake Support (SBS)",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Da li ste sigurni da želite da vratite postavke SBS/SCBS na njihove fabrički podrazumevane vrednosti?",
	"SBS_SCBSResetError": "Greška pri promeni SBS/SCBS postavki. Da li želite da pokušate ponovo?",
	"SBS_SCBSResetProgress": "Promena SBS/SCBS postavki ",
	"SCBS": "Smart City Brake Support",
	"Safety": "Bezbedn.",
	"Safetysettings": "Bezb. postavke",
	"Sensitivity": "Osetljivost",
	"Sensitivity_Intervention_OFF": "Upozorenje",
	"Settings": "Postavke",
	"Short": "Blizu",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Zvuk",
	"System": "Sistem",
	"ThreeFlashTurnSignal": "Signal skretanja sa 3 treptaja",
	"Timing": "Podešavanje vremena",
	"Turn": "Skretanje",
	"TurnProgress": "Promena postavki za skretanje",
	"TurnReset": "Da li ste sigurni da želite da vratite postavke za skretanje na fabrički podrazumevane vrednosti?",
	"TurnResetError": "Greška kod menjanja postavki skretanja. Da li želite da pokušate ponovo?",
	"TurnSettings": "Uključi",
	"TurnSignalIndicatorVolume": "Jač.zv.sign.skretanja",
	"UnlockMode": "Režim otključavanja",
	"Vehicle": "Vozilo",
	"VehicleSettings": "Postavke vozila",
	"Vibration": "Vibracija",
	"VibrationStrength": "Jačina vibracije",
	"Vibration_Line": "Vibracija",
	"Volume": "Jačina zvuka",
	"WalkAwayLock": "Zaključavanje pri udaljavanju od vozila",
	"Warning": "Upozorenje",
	"WarningDistance": "Distan.za upozor.",
	"_0s": "0 s.",
	"_0seconds": "0 sekundi",
	"_10m": "10 min.",
	"_10minutes": "10 minuta",
	"_120s": "120 s",
	"_120seconds": "120 sekundi",
	"_15s": "15 s",
	"_15seconds": "15 sekundi",
	"_30m": "30 min.",
	"_30minutes": "30 minuta",
	"_30s": "30 s",
	"_30seconds": "30 sekundi",
	"_60m": "60 min.",
	"_60minutes": "60 minuta",
	"_60s": "60 s",
	"_60seconds": "60 sekundi",
	"_7p5s": "7.5 s",
	"_7p5seconds": "7.5 sekundi",
	"_90s": "90 s",
	"_90seconds": "90 sekundi",
	"_AllDoors": "Sve",
	"_Driver'sDoor": "Vožač.",
	"on": "Uklj.",
};

framework.registerAppDictLoaded("vehsettings", "sr_RS");