var Localization_vehsettingsAppDict_no_NO = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Tilpasningsbar",
	"AdaptiveFront-lightingSystem": "Adaptive frontlys",
	"AlertTiming": "Varslingstidspunkt",
	"AtLine": "V/linje",
	"Auto": "Auto",
	"AutoHeadlightOn": "Frontlys automatisk på",
	"AutoWiper": "Automatiske vindusviskere",
	"BSMBuzzerVolume": "Blind Spot Monitoring Volum",
	"Beep": "Pipelyd",
	"BeepVolume": "Lydsignalvolum",
	"Beep_Line": "Pipelyd",
	"BeforeLine": "F/linje",
	"Brightness": "Lysstyrke",
	"BrightnessControl": "Luminanskontroll",
	"Calibration": "Kalibrering",
	"ChangingLASSettings": "Endrer innstillinger for LAS",
	"Clock": "Klokke",
	"Close": "Lukke",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Er du sikker på at du vil tilbakestille Distance Recognition Support System (DRSS) til standardverdier?",
	"DRSSResetError": "Feil ved endring av Distance Recognition Support System (DRSS). Vil du prøve på nytt?",
	"DRSSResetProgress": "Endrer Distance Recognition Support System (DRSS)",
	"Dark": "Mørk",
	"DaytimeRunningLights": "Kjørelys",
	"Devices": "Enheter",
	"Display": "Skjerm",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Dørlås",
	"DoorLockMode": "Modus for automatisk dørlås",
	"DoorLockReset": "Er du sikker på at du vil tilbakestille dørlåsinnstillingene til standardverdiene?",
	"DoorLockResetError": "Feil ved endring av dørlåsinnstillinger. Vil du prøve på nytt?",
	"DoorLockResetProgress": "Endrer dørlåsinnstillinger",
	"DoorRelockTime": "Tid for autolås",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Tidlig",
	"ErrorLASSettings": "Feil ved endring av innstillingene for Lane  Lane-keep Assist System. Vil du prøve på nytt?",
	"FOWReset": "Er du sikker på at du vil tilbakestille innstillingene for Forward Obstruction Warning (FOW) til standardverdiene?",
	"FOWResetError": "Feil ved endring av innstillinger for Forward Obstruction Warning (FOW). Vil du prøve på nytt?",
	"FOWResetProgress": "Endrer innstillinger for Forward Obstruction Warning (FOW)",
	"Far": "Fjernt",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Er du sikker på at du vil tilbakestille  Active Driving Display til standardverdiene?",
	"HUDResetError": "Feil ved endring av innstillingene for Active Driving Display. Vil du prøve på nytt?",
	"HUDResetProgress": "Endrer Active Driving Display Settings",
	"HeadlightOffTimer": "Timer for frontlys",
	"HeadlightOnWarning": "Frontlysvarsel",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Høyde",
	"High": "Høy",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Høy",
	"High_Vibration": "Høy",
	"InterioLightsTimeOutDoorsClosed": "Timer for interiørlys, dør lukket",
	"InterioLightsTimeOutDoorsOpen": "Timer for interiørlys, dør åpen",
	"InteriorLightTimeoutDoorClosedTitle": "Timer for interiørlys, dør åpen",
	"InteriorLightTimeoutDoorOpenTitle": "Timer for interiørlys, dør lukket",
	"Intervention": "Intervensjon",
	"InterventionTiming": "Intervensjonstidspunkt",
	"KeylessLockBeepVol": "Volum, varseltone for nøkkelfri lås",
	"LASAlert": "LAS-varsel",
	"LASDefaultValues": "Er du sikker på at du vil tilbakestille innstillinger for Lane-keep Assist System til standardverdier?",
	"LASEarly": "Tidlig",
	"LASLate": "Sent",
	"LASSound": "Varslingstype",
	"LASTiming": "LAS Timing",
	"LDWSReset": "Er du sikker på at du vil tilbakestille innstillinger for Lane Departure Warning System (LDWS) til standardverdier?",
	"LDWSResetError": "Feil ved endring av innstillingene for Lane Departure Warning System (LDWS). Vil du prøve på nytt?",
	"LDWSResetProgress": "Endrer innstillingene for Lane Departure Warning System (LDWS)",
	"LDWSTiming": "LDWS-timing",
	"LaneDepartureAlert": "Banefravikningsvarsel",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Sent",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Lett",
	"LightOnReminderVolume": "Volum lysvarsler",
	"Lighting": "Belysning",
	"LightingReset": "Er du sikker på at du vil tilbakestille lysinnstillingene til standardverdiene?",
	"LightingResetError": "Feil ved endring av lysinnstillinger. Vil du prøve på nytt?",
	"LightingResetProgress": "Endrer lysinnstillingene",
	"LockShiftFromP": "Lås: Girer ut av Park ",
	"LockShiftFromPUnlockInPark": "Lås: Girer ut av Park Lås opp: I Park",
	"LockUnlock": "Lås: Ved kjøring Lås opp: I Park",
	"LockWhenDriving": "Lås: Ved kjøring",
	"LockWhenDrivingUnlockIGNoff": "Lås: Ved kjøring Lås opp: Tenning av",
	"Long": "Fjernt",
	"Low": "Lav",
	"Low_SensitivityLAS": "Lav",
	"Low_Vibration": "Lav",
	"Manual": "Man.",
	"Med": "Med",
	"Medium": "Middels",
	"MediumDark": "Mid mørk",
	"MediumLight": "Mid lys",
	"Medium_Int_OFF": "Med",
	"Medium_SensitivityLAS": "Med",
	"Mid": "Mid",
	"Middle": "Midte",
	"Mode": "Modus",
	"Navigation": "Navigering",
	"Near": "Nær",
	"Off": "Av",
	"Often": "Ofte",
	"Often_Int_OFF": "Ofte",
	"OnceAllDoors": "Én gang: Alle dører",
	"OnceDriversDoorTwiceAllDoors": "Én gang: Fører to ganger: Alle dører",
	"Open": "Åpne",
	"ParkingSensorIndication": "Indikasjon for parkeringssensor",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Volum",
	"Rare": "Sjelden",
	"Rare_Int_OFF": "Sjelden",
	"Reset": "Tilbakestill",
	"RumbleStrips": "Roml.",
	"RumbleStrips_line": "Roml.",
	"RumbleVolume": "Volum, romlefelt",
	"SBSReset": "Er du sikker på at du vil tilbakestille innstillingene for Smart Brake Support (SBS) til standardverdier?",
	"SBSResetError": "Feil ved endring av Smart Brake Support (SBS)-innstillingene. Vil du prøve på nytt?",
	"SBSResetProgress": "Endrer Smart Brake Support (SBS)-innstillinger",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Er du sikker på at du vil tilbakestille innstillingene for SBS/SCBS til standardverdiene?",
	"SBS_SCBSResetError": "Feil ved endring av SBS/SCBS innstillingene. Vil du prøve på nytt?",
	"SBS_SCBSResetProgress": "Endrer SBS/SCBS innstillingene",
	"SCBS": "Smart City Brake Support",
	"Safety": "Sikkerhet",
	"Safetysettings": "Sikkerhetsinnstillinger",
	"Sensitivity": "Følsomhet",
	"Sensitivity_Intervention_OFF": "Advarsel",
	"Settings": "Innstillinger",
	"Short": "Nær",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Lyd",
	"System": "System",
	"ThreeFlashTurnSignal": "Blinklys, 3-blink",
	"Timing": "Tidsplanlegging",
	"Turn": "Slå over",
	"TurnProgress": "Endrer svinginnstillingene",
	"TurnReset": "Er du sikker på at du vil tilbakestille svinginnstillingene til standardverdiene?",
	"TurnResetError": "Feil ved endring av svinginnstillinger. Vil du prøve på nytt?",
	"TurnSettings": "Blinklys",
	"TurnSignalIndicatorVolume": "Blinklys signalvolum",
	"UnlockMode": "Opplåst modus",
	"Vehicle": "Kjøretøy",
	"VehicleSettings": "Kjøretøyinnstillinger",
	"Vibration": "Vibrasjon",
	"VibrationStrength": "Vibrasjonsstyrke",
	"Vibration_Line": "Vibrasjon",
	"Volume": "Volum",
	"WalkAwayLock": "Walk Away-lås",
	"Warning": "Advarsel",
	"WarningDistance": "Advarselsavstand",
	"_0s": "0 s",
	"_0seconds": "0 sekunder",
	"_10m": "10 min",
	"_10minutes": "10 minutter",
	"_120s": "120 s",
	"_120seconds": "120 sekunder",
	"_15s": "15 s",
	"_15seconds": "15 sekunder",
	"_30m": "30 min",
	"_30minutes": "30 minutter",
	"_30s": "30 s",
	"_30seconds": "30 sekunder",
	"_60m": "60 min",
	"_60minutes": "60 minutter",
	"_60s": "60 s",
	"_60seconds": "60 sekunder",
	"_7p5s": "7,5 s",
	"_7p5seconds": "7,5 sekunder",
	"_90s": "90 s",
	"_90seconds": "90 sekunder",
	"_AllDoors": "Alle",
	"_Driver'sDoor": "Sjåfør.",
	"on": "På",
};

framework.registerAppDictLoaded("vehsettings", "no_NO");