var Localization_vehsettingsAppDict_it_IT = {
	//"stringId" : "localString"
	"AHBC": "Adaptive LED Headlights",
	"Adaptive": "Adattivo",
	"AdaptiveFront-lightingSystem": "Sistema luci anteriori adattive",
	"AlertTiming": "Momento Avviso",
	"AtLine": "InLinea",
	"Auto": "Auto",
	"AutoHeadlightOn": "Modalità fari accesi automatica",
	"AutoWiper": "Tergicristallo con sensore per pioggia",
	"BSMBuzzerVolume": "Blind Spot Monitoring Volume",
	"Beep": "Beep",
	"BeepVolume": "Volume Beep",
	"Beep_Line": "Beep",
	"BeforeLine": "Prima",
	"Brightness": "Luminosità",
	"BrightnessControl": "Controllo luminosità",
	"Calibration": "Calibrazione",
	"ChangingLASSettings": "Modifica impostazioni LAS",
	"Clock": "Orologio",
	"Close": "Chiudi",
	"ComingHomeLights": "Coming Home Light",
	"ComingHomeLightsTimer": "Coming Home Light",
	"DRSS": "Distance Recognition Support System",
	"DRSSReset": "Riportare le impostazioni Distance Recognition Support System (DRSS) ai valori predefiniti?",
	"DRSSResetError": "Errore nella variazione del Distance Recognition Support System (DRSS). Riprovare?",
	"DRSSResetProgress": "Variazione  Distance Recognition Support System (DRSS)",
	"Dark": "Scuro",
	"DaytimeRunningLights": "Luci diurne",
	"Devices": "Dispositi.",
	"Display": "Display",
	"DistanceRecognitionSupportSystem": "Distance Recognition Support System",
	"DoorLock": "Chiusura porte",
	"DoorLockMode": "Modalità porte chiuse automatica",
	"DoorLockReset": "Riportare le impostazioni dell'attivazione 3 lampeggi automatici dell'indicatore di direzione ai valori predefiniti?",
	"DoorLockResetError": "Errore nel cambio delle impostazioni chiusura portiere. Riprovare?",
	"DoorLockResetProgress": "Cambio impostazioni chiusura portiere",
	"DoorRelockTime": "Tempo nuova chiusura automatica",
	"DriverAlert": "Driver Attention Alert",
	"Early": "Presto",
	"ErrorLASSettings": "Errore nella modifica di Lane-keep Assist System. Riprovare?",
	"FOWReset": "Riportare le impostazioni Forward Obstruction Warning (FOW) ai valori predefiniti?",
	"FOWResetError": "Errore nel cambio delle impostazioni Forward Obstruction Warning (FOW). Riprovare?",
	"FOWResetProgress": "Cambio impostazioni Forward Obstruction Warning (FOW)",
	"Far": "Lonta",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "Riportare le impostazioni Active Driving Display ai valori predefiniti?",
	"HUDResetError": "Errore nel cambio delle impostazioni Active Driving Display. Riprovare?",
	"HUDResetProgress": "Cambio impostaz Active Driving Display",
	"HeadlightOffTimer": "Timer spegnimento fari",
	"HeadlightOnWarning": "Avviso fari accesi",
	"HeadsUpDisplay": "Active Driving Display",
	"Height": "Altezza",
	"High": "Alto",
	"HighBeamControl": "High Beam Control",
	"High_SensitivityLAS": "Alto",
	"High_Vibration": "Alto",
	"InterioLightsTimeOutDoorsClosed": "Timeout luci interne:Porte chiuse",
	"InterioLightsTimeOutDoorsOpen": "Timeout luci interne:Porte aperte",
	"InteriorLightTimeoutDoorClosedTitle": "Timeout luci interne: Portiere chiuse",
	"InteriorLightTimeoutDoorOpenTitle": "Timeout luci interne:Porte aperte",
	"Intervention": "Intervento",
	"InterventionTiming": "Momento Intervento",
	"KeylessLockBeepVol": "Vol segnale chiusura senza chiavi",
	"LASAlert": "Allerta LAS",
	"LASDefaultValues": "Riportare le impostazioni di Lane-keep Assist System ai valori predefiniti?",
	"LASEarly": "Presto",
	"LASLate": "Tardi",
	"LASSound": "Tipo di Avviso",
	"LASTiming": "Tempo LAS",
	"LDWSReset": "Riportare le impostazioni Lane Departure Warning System (LDWS) ai valori predefiniti?",
	"LDWSResetError": "Errore nella modifica delle impostazioni Lane Departure Warning System (LDWS). Riprovare?",
	"LDWSResetProgress": "Modifica impostazioni Lane Departure Warning System (LDWS)",
	"LDWSTiming": "Tempo LDWS",
	"LaneDepartureAlert": "Avviso di Abbandono Corsia",
	"LaneDepartureWarningSystem": "Lane Departure Warning System",
	"LaneKeepAssistSystem": "Lane-keep Assist System",
	"Late": "Tardi",
	"LeavingHomeLights": "Leaving Home Light",
	"Light": "Luce",
	"LightOnReminderVolume": "Volume luci accese",
	"Lighting": "Luci",
	"LightingReset": "Riportare le impostazioni delle luci ai loro valori predefiniti?",
	"LightingResetError": "Errore nel cambio impostazioni luci. Riprovare?",
	"LightingResetProgress": "Cambio impostazioni luci",
	"LockShiftFromP": "Blocco: spostare non su Park (P)",
	"LockShiftFromPUnlockInPark": "Blocco: Non su Park Sblocco: Su Park",
	"LockUnlock": "Blocco: se alla guida Sblocco: su Park",
	"LockWhenDriving": "Blocco: Se alla guida",
	"LockWhenDrivingUnlockIGNoff": "Blocco: se alla guida Sblocco: IGN off",
	"Long": "Lonta",
	"Low": "Basso",
	"Low_SensitivityLAS": "Basso",
	"Low_Vibration": "Basso",
	"Manual": "Manu",
	"Med": "Medio",
	"Medium": "Medio",
	"MediumDark": "Buio med",
	"MediumLight": "Luce med",
	"Medium_Int_OFF": "Medio",
	"Medium_SensitivityLAS": "Medio",
	"Mid": "Medio",
	"Middle": "Medio",
	"Mode": "Modalità",
	"Navigation": "Navigazione",
	"Near": "Vicino",
	"Off": "Off",
	"Often": "Spesso",
	"Often_Int_OFF": "Spesso",
	"OnceAllDoors": "Una volta: tutte le portiere",
	"OnceDriversDoorTwiceAllDoors": "1 volta: per conducente 2: Ogni porta",
	"Open": "Apri",
	"ParkingSensorIndication": "Indicazione sensore parcheggio",
	"RVMBuzzerVolume": "Rear Vehicle Monitoring Volume",
	"Rare": "Raro",
	"Rare_Int_OFF": "Raro",
	"Reset": "Resetta",
	"RumbleStrips": "Rum.",
	"RumbleStrips_line": "Rum.",
	"RumbleVolume": "Vol banda sonora",
	"SBSReset": "Riportare le impostazioni Smart Brake Support (SBS) ai valori predefiniti?",
	"SBSResetError": "Errore nel cambio delle impostazioni Smart Brake Support (SBS). Riprovare?",
	"SBSResetProgress": "Cambio impostazioni Smart Brake Support (SBS)",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "Riportare le impostazioni SBS/SCBS ai valori predefiniti?",
	"SBS_SCBSResetError": "Errore nel cambio delle impostazioni SBS/SCBS. Riprovare? ",
	"SBS_SCBSResetProgress": "Cambio impostazioni SBS/SCBS",
	"SCBS": "Smart City Brake Support",
	"Safety": "Sicurezza",
	"Safetysettings": "Impostazioni sicurezza",
	"Sensitivity": "Sensibilità",
	"Sensitivity_Intervention_OFF": "Attenzione",
	"Settings": "Impostazioni",
	"Short": "Vicino",
	"SmartBrakeSupport": "Smart Brake Support",
	"Sound": "Audio",
	"System": "Sistema",
	"ThreeFlashTurnSignal": "Freccia 3-flash",
	"Timing": "Timing",
	"Turn": "Gira",
	"TurnProgress": "Cambio impostazioni virata",
	"TurnReset": "Riportare le impostazioni attivazione automatica 3 lampeggi indicatori di direzione ai valori predefiniti?",
	"TurnResetError": "Errore nel cambio delle impostazioni dell'attivazione 3 lampeggi automatici dell'indicatore di direzione",
	"TurnSettings": "Gira",
	"TurnSignalIndicatorVolume": "Volume freccia",
	"UnlockMode": "Modalità sbloccato",
	"Vehicle": "Veicolo",
	"VehicleSettings": "Impostazioni veicolo",
	"Vibration": "Vibrazione",
	"VibrationStrength": "Intensità Vibrazione",
	"Vibration_Line": "Vibrazione",
	"Volume": "Volume",
	"WalkAwayLock": "Chiusura automatica",
	"Warning": "Attenzione",
	"WarningDistance": "Avviso distanza",
	"_0s": "0 s",
	"_0seconds": "0 secondi",
	"_10m": "10 min",
	"_10minutes": "10 minuti",
	"_120s": "120 s",
	"_120seconds": "120 secondi",
	"_15s": "15 s",
	"_15seconds": "15 secondi",
	"_30m": "30 min",
	"_30minutes": "30 minuti",
	"_30s": "30 s",
	"_30seconds": "30 secondi",
	"_60m": "60 min",
	"_60minutes": "60 minuti",
	"_60s": "60 s",
	"_60seconds": "60 secondi",
	"_7p5s": "7.5 s",
	"_7p5seconds": "7.5 secondi",
	"_90s": "90 s",
	"_90seconds": "90 secondi",
	"_AllDoors": "Tutte",
	"_Driver'sDoor": "Conduc.",
	"on": "On",
};

framework.registerAppDictLoaded("vehsettings", "it_IT");