var Localization_vehsettingsAppDict_ja_JP = {
	//"stringId" : "localString"
	"AHBC": "アダプティブLEDヘッドライト",
	"Adaptive": "自動",
	"AdaptiveFront-lightingSystem": "AFS",
	"AlertTiming": "警報タイミング",
	"AtLine": "行",
	"Auto": "自動",
	"AutoHeadlightOn": "オートライト点灯タイミング",
	"AutoWiper": "オートワイパー",
	"BSMBuzzerVolume": "BSM音量",
	"Beep": "ﾋﾞｰﾌﾟ",
	"BeepVolume": "ビープ音量",
	"Beep_Line": "ビープ音",
	"BeforeLine": "ﾗｲﾝ前",
	"Brightness": "明るさ",
	"BrightnessControl": "明るさ調節",
	"Calibration": "調整レベル",
	"ChangingLASSettings": "処理中…",
	"Clock": "時計",
	"Close": "閉じる",
	"ComingHomeLights": "カミングホームライト",
	"ComingHomeLightsTimer": "カミングホームライト",
	"DRSS": "車間認知支援システム",
	"DRSSReset": "設定値をリセットしても\nよろしいですか？",
	"DRSSResetError": "設定を変更できませんでした。\nリトライしますか？",
	"DRSSResetProgress": "処理中…",
	"Dark": "遅く",
	"DaytimeRunningLights": "デイタイムランニングライト",
	"Devices": "通信",
	"Display": "画面",
	"DistanceRecognitionSupportSystem": "車間認知支援システム",
	"DoorLock": "ドアロック",
	"DoorLockMode": "自動ドアロックモード",
	"DoorLockReset": "設定値をリセットしても\nよろしいですか？",
	"DoorLockResetError": "リセットできませんでした。\nリトライしますか？",
	"DoorLockResetProgress": "処理中…",
	"DoorRelockTime": "キーレス自動再ロック時間",
	"DriverAlert": "ドライバーアテンションアラート",
	"Early": "近い",
	"ErrorLASSettings": "リセットできませんでした。\nリトライしますか？",
	"FOWReset": "設定値をリセットしても\nよろしいですか？",
	"FOWResetError": "リセットできませんでした。\nリトライしますか？",
	"FOWResetProgress": "処理中…",
	"Far": "遠い",
	"ForwardObstructionWarning": "Forward Obstruction Warning",
	"HUD": "AD-Disp",
	"HUDReset": "設定値をリセットしても\nよろしいですか？",
	"HUDResetError": "リセットできませんでした。\nリトライしますか？",
	"HUDResetProgress": "処理中…",
	"HeadlightOffTimer": "ヘッドライト自動消灯時間",
	"HeadlightOnWarning": "ﾍｯﾄﾞﾗｲﾄON警告",
	"HeadsUpDisplay": "表示",
	"Height": "高さ",
	"High": "大",
	"HighBeamControl": "ハイビームコントロールシステム",
	"High_SensitivityLAS": "低い",
	"High_Vibration": "強",
	"InterioLightsTimeOutDoorsClosed": "ドアクローズ照明点灯時間",
	"InterioLightsTimeOutDoorsOpen": "ドアオープン照明点灯時間",
	"InteriorLightTimeoutDoorClosedTitle": "ドア開連動照明点灯時間",
	"InteriorLightTimeoutDoorOpenTitle": "ドア閉連動照明点灯時間",
	"Intervention": "ハンドルアシスト",
	"InterventionTiming": "アシストタイミング",
	"KeylessLockBeepVol": "キーレスアンサーバック音量",
	"LASAlert": "LAS 警告",
	"LASDefaultValues": "設定値をリセットしても\nよろしいですか？",
	"LASEarly": "早い",
	"LASLate": "遅い",
	"LASSound": "警報種類",
	"LASTiming": "LAS距離",
	"LDWSReset": "設定値をリセットしても\nよろしいですか？",
	"LDWSResetError": "リセットできませんでした。\nリトライしますか？",
	"LDWSResetProgress": "処理中…",
	"LDWSTiming": "警報距離",
	"LaneDepartureAlert": "警報(音/振動)",
	"LaneDepartureWarningSystem": "車線逸脱警報システム",
	"LaneKeepAssistSystem": "レーンキープ・アシスト・システム",
	"Late": "遠い",
	"LeavingHomeLights": "リービングホームライト",
	"Light": "早く",
	"LightOnReminderVolume": "ライトON警報",
	"Lighting": "照明",
	"LightingReset": "設定値をリセットしても\nよろしいですか？",
	"LightingResetError": "リセットできませんでした。\nリトライしますか？",
	"LightingResetProgress": "処理中…",
	"LockShiftFromP": "ﾛｯｸ : ｼﾌﾄ連動",
	"LockShiftFromPUnlockInPark": "ﾛｯｸ / ｱﾝﾛｯｸ : ｼﾌﾄ連動",
	"LockUnlock": "ﾛｯｸ : 車速、ｱﾝﾛｯｸ : ｼﾌﾄ連動",
	"LockWhenDriving": "ﾛｯｸ : 車速連動",
	"LockWhenDrivingUnlockIGNoff": "ﾛｯｸ : 車速、ｱﾝﾛｯｸ : 電源",
	"Long": "遠い",
	"Low": "小",
	"Low_SensitivityLAS": "高い",
	"Low_Vibration": "弱",
	"Manual": "手動",
	"Med": "標準",
	"Medium": "標準",
	"MediumDark": "少し遅く",
	"MediumLight": "少し早く",
	"Medium_Int_OFF": "標準",
	"Medium_SensitivityLAS": "標準",
	"Mid": "中",
	"Middle": "中間",
	"Mode": "設定",
	"Navigation": "ナビガイダンス",
	"Near": "近い",
	"Off": "OFF",
	"Often": "高い",
	"Often_Int_OFF": "高い",
	"OnceAllDoors": "1回 : すべてのドア",
	"OnceDriversDoorTwiceAllDoors": "1回 : 運転席、2回 : すべて",
	"Open": "開く",
	"ParkingSensorIndication": "パーキングセンサー表示",
	"RVMBuzzerVolume": "リアビークルモニタリング音量",
	"Rare": "低い",
	"Rare_Int_OFF": "低い",
	"Reset": "リセット",
	"RumbleStrips": "ﾗﾝﾌﾞﾙ",
	"RumbleStrips_line": "ランブル音",
	"RumbleVolume": "ランブル音量",
	"SBSReset": "設定値をリセットしても\nよろしいですか？",
	"SBSResetError": "リセットできませんでした。\nリトライしますか？",
	"SBSResetProgress": "処理中…",
	"SBSSCBS": "SBS/SCBS",
	"SBS_SCBSReset": "設定値をリセットしても\nよろしいですか？",
	"SBS_SCBSResetError": "リセットできませんでした。\nリトライしますか？",
	"SBS_SCBSResetProgress": "処理中…",
	"SCBS": "スマートシティーブレーキサポート",
	"Safety": "安全装備",
	"Safetysettings": "Settings",
	"Sensitivity": "アシスト感度",
	"Sensitivity_Intervention_OFF": "警報感度",
	"Settings": "Settings",
	"Short": "近い",
	"SmartBrakeSupport": "スマートブレーキサポート ",
	"Sound": "サウンド",
	"System": "システム",
	"ThreeFlashTurnSignal": "スリーフラッシュターンシグナル",
	"Timing": "警報距離",
	"Turn": "ターン",
	"TurnProgress": "処理中…",
	"TurnReset": "設定値をリセットしても\nよろしいですか？",
	"TurnResetError": "変更できませんでした。\nリトライしますか？",
	"TurnSettings": "ターン",
	"TurnSignalIndicatorVolume": "ウィンカー音量",
	"UnlockMode": "キーレスアンロックモード",
	"Vehicle": "車両装備",
	"VehicleSettings": "Settings",
	"Vibration": "ハンドル",
	"VibrationStrength": "ハンドル振動",
	"Vibration_Line": "ハンドル振動",
	"Volume": "音量",
	"WalkAwayLock": "キーレスオートロック",
	"Warning": "警報感度",
	"WarningDistance": "警告距離",
	"_0s": "0 秒",
	"_0seconds": "0 秒",
	"_10m": "10分",
	"_10minutes": "10 分",
	"_120s": "120秒",
	"_120seconds": "120 秒",
	"_15s": "15秒",
	"_15seconds": "15 秒",
	"_30m": "30分",
	"_30minutes": "30 分",
	"_30s": "30秒",
	"_30seconds": "30 秒",
	"_60m": "60分",
	"_60minutes": "60 分",
	"_60s": "60秒",
	"_60seconds": "60 秒",
	"_7p5s": "7.5秒",
	"_7p5seconds": "7.5 秒",
	"_90s": "90秒",
	"_90seconds": "90 秒",
	"_AllDoors": "全席",
	"_Driver'sDoor": "運転席",
	"on": "On",
};

framework.registerAppDictLoaded("vehsettings", "ja_JP");