var Localization_syssettingsAppDict_pt_BR = {
	//"stringId" : "localString"
	"About": "Sobre",
	"AdjustTime": "Ajustar hora",
	"AgreementsAndDisclaimers": "Acordos e isenção de responsabilidade",
	"AgreementsDisclaimersText": "Por favor, acesse www.MazdaEndUserAgreements-Copyrights.com para obter uma lista de licenças completa e todas as divulgações de copyright.",
	"Auto": "Auto",
	"Bluetooth": "Bluetooth",
	"Brightness": "Brilho",
	"Celsius": "° C",
	"ChooseLanguage": "Selecione o Idioma",
	"Clock": "Relógio",
	"Communication": "Comunicação",
	"CommunicationResetConfText": "Você tem certeza de que deseja restaurar as configurações de comunicação para os valores padrão de fábrica?",
	"CommunicationResetErrorRetryText": "Não é possível restaurar configurações de comunicação para os valores padrão de fábrica. Deseja tentar novamente?",
	"CommunicationResetProgressText": "Rest. config. de comunic. ao padrão de fáb.",
	"ContactsSortOrder": "Ordem de exibição de contatos",
	"ContactsSortOrderTitle": "Ordem de classificação dos contatos",
	"Contrast": "Contraste",
	"Day": "Dia ",
	"DayLightSavingsTime": "Horário de verão",
	"Display": "Tela",
	"DisplayResetConfText": "Você tem certeza de que deseja restaurar as configurações da tela para os valores padrão de fábrica?",
	"DisplayResetErrorText": "Não é possível restaurar configurações da tela para os valores padrão de fábrica. Deseja tentar novamente?",
	"DisplayResetProgressText": "Restaurando configurações de tela",
	"Distance": "Distância",
	"DownloadCallContacts": "Baixar contatos automaticamente",
	"DownloadCallEmail": "Baixar e mail automaticamente",
	"DownloadCallHistory": "Baixar hist. chamadas autom.",
	"DownloadCallText": "Baixar msg texto autom.",
	"Eastern": "Leste",
	"EditPresetMessage": "Editar msg predef. ",
	"EmailNotifications": "Notificações por e-mail",
	"EmailSmsNotifications": "Notificações de texto/E-mail",
	"FactoryReset": "Restaurar todas as configurações de fábrica",
	"FactoryResetConfText": "Você tem certeza de que deseja restaurar todas as configurações com os valores padrão de fábrica?",
	"FactoryResetErrorText": "Não é possível restaurar todas as configurações para os valores padrão de fábrica. Deseja tentar novamente?",
	"FactoryResetProgressText": "Restaurando todas as configurações",
	"Fahrenheit": "° F",
	"FirstLast": "Nome, Sobrenome",
	"Fixed": "Autom.",
	"GPSSync": "Sincronização de GPS",
	"Inband": "Telefone",
	"IncomingCallNotifications": "Notificações de chamada recebida",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English - AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português-BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français - CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français - EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Hexadecimal",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonésia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Numeric",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español - NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português-EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español - EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English - UK",
	"LANGS_US_ENGLISH": "English - US",
	"Language": "Idioma",
	"LanguageChangeErrorText": "Não é possível alterar o idioma. Deseja tentar novamente?",
	"LanguageChangeProgressText": "Alterando idioma",
	"LanguageChangeSuccess": "Idioma alterado com sucesso para {languageID}",
	"LanguageConfText": "Tem certeza de que deseja alterar o idioma para {languageID}?",
	"LanguageConfTextNoVR": "{languageID} é um idioma somente de exibição. As funções de voz usarão o inglês britânico. Alterar o idioma da tela para {languageID}? ",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} é um idioma somente de exibição. Para as funções de voz será considerado o {VRlanguageID}. Alterar o idioma do display para {languageID}? ",
	"LastFirst": "Sobrenome, Nome",
	"Miles": "mi",
	"Mobile911": "Chamada de emergência",
	"Mobile911Description": "Quanto ativado, o veículo fará chamadas de emergência em caso de acidentes. ",
	"Mode": "Sistema",
	"MusicDatabaseUpdate": "Atualização do banco de dados de músicas",
	"NaviVolumeTTS": "A navegação será realizada neste volume.",
	"NetworkManagement": "Wi-Fi",
	"Night": "Noite",
	"PhoneVolume": "Volume telef.",
	"PresetBeThereTen": "Chegarei em 10 minutos.",
	"PresetBeThereTwenty": "Chegarei em 20 minutos.",
	"PresetCallLater": "Ligo para você mais tarde.",
	"PresetCantTalk": "Não posso falar agora.",
	"PresetDriving": "Estou dirigindo neste momento.",
	"PresetMessages": "Editar mensagens predefinidas",
	"PresetMessagesTitle": "Mensagens predefinidas",
	"PresetNeedMore": "Preciso de mais orientações.",
	"PresetNo": "Não",
	"PresetOk": "Ok",
	"PresetPleaseCall": "Por favor, me ligue de volta.",
	"PresetStuck": "Estou em um engarrafamento.",
	"PresetThanks": "Obrigado!",
	"PresetWhere": "Onde você está?",
	"PresetWhy": "Por quê?",
	"PresetYes": "Sim",
	"Recent": "Recente",
	"Reset": "Reiniciar",
	"Ringtone": "Melodia de toque",
	"RingtoneVolumeTTS": "Chamadas telefônicas serão efetuadas neste volume.",
	"SMSNotifications": "Notificações de texto",
	"Safety": "Seg.",
	"SelectKBLang": "Selecionar teclado",
	"SelectTimeZone": "Selecione o fuso horário",
	"SetClockHrsMinus": "Diminuir horas",
	"SetClockHrsPlus": "Aumentar horas",
	"SetClockMinMinus": "Diminuir minutos",
	"SetClockMinPlus": "Aumentar minutos",
	"Settings": "Configurações",
	"SystemSettings": "Config. sistema",
	"Temp": "Temperatura ",
	"TimeFormat": "Formato de hora",
	"TimeZoneSelect": "Seleção de fuso horário",
	"ToolTips": "Dicas sobre a ferramenta",
	"TurnDisplayOff": "Desligar tela",
	"TurnDisplayOffShowClock": "Desligar tela e exibir relógio",
	"UTC0000Casablanca": "UTC Casablanca",
	"UTC0000CoordinatedUniversalTime": "UTC Horário Universal Coordenado",
	"UTC0000Dublin": "UTC Dublin, Edimburgo, Londres",
	"UTC0000Monrovia": "UTC Monróvia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Amsterdã, Berlin",
	"UTC0100Belgrade": "UTC+01:00 Belgrado, Ljubjana",
	"UTC0100Brussels": "UTC+01:00 Bruxelas, Madrid",
	"UTC0100Sarajevo": "UTC+01:00 Sarajevo, Skopje",
	"UTC0100WestCentralAfrica": "UTC+01:00 Centro-oeste da África",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Atenas, Bucareste",
	"UTC0200Beirut": "UTC+02:00 Beirute",
	"UTC0200Cairo": "UTC+02:00 Cairo",
	"UTC0200Damascus": "UTC+02:00 Damasco",
	"UTC0200EEurope": "UTC+02:00 Europa Oriental",
	"UTC0200Harare": "UTC+02:00 Harare, Pretória",
	"UTC0200Helsinki": "UTC+02:00 Helsinque, Kyiv, Riga",
	"UTC0200Istanbul": "UTC+02:00 Istambul",
	"UTC0200Jerusalem": "UTC+02:00 Jerusalém",
	"UTC0300Amman": "UTC+03:00 Amã",
	"UTC0300Baghdad": "UTC+03:00 Bagdá",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrado, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuwait, Riad",
	"UTC0300Nairobi": "UTC+03:00 Nairóbi",
	"UTC0330Tehran": "UTC+03:30 Teerã",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Mascate",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Moscou, Volgograd",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Cabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karachi",
	"UTC0500Tashkent": "UTC+05:00 Tashkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai, Nova Deli",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayawardenep.",
	"UTC0545Kathmandu": "UTC+05:45 Katmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburgo",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bangkok, Hanói",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Pequim, Hong Kong",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 Kuala Lumpur",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulaanbaatar",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Sapporo",
	"UTC0900Seoul": "UTC+09:00 Seul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Canberra, Sydney",
	"UTC1000Guam": "UTC+10:00 Guam, Port Moresby",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Nova Caledônia",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland, Wellington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Hor. Univ. coord.",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadã",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Açores",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Ilha de Cabo Verde",
	"UTCm0100Casablanca": "UTC-01:00 Casablanca",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Hor. Univ. Coord.",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Hor. Univ. Coord.",
	"UTCm0200MidAtlantic": "UTC-02:00 Atlântico Central",
	"UTCm0300Brasilia": "UTC-03:00 Brasília",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Caiena, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Groenlândia",
	"UTCm0300Montevideo": "UTC-03:00 Montevidéu",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Terra Nova",
	"UTCm0400Asuncion": "UTC-04:00 Assunção",
	"UTCm0400AtlanticTime": "UTC-04:00 Hor. Atlântico (Canadá)",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiabá",
	"UTCm0400Georgetown": "UTC-04:00 La Paz, Manaus",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogotá, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Oriental, EUA/Canadá.",
	"UTCm0500Indiana": "UTC-05:00 Indiana (Leste)",
	"UTCm0600CentralAmerica": "UTC-06:00 América Central",
	"UTCm0600CentralTime": "UTC-06:00 Central, EUA/Canadá.",
	"UTCm0600Guadalajara": "UTC-06:00 Cidade do México",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua, La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Montanhas, EUA/Canadá.",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja Califórnia",
	"UTCm0800PacificTime": "UTC-08:00 Pacífico, EUA/Canadá.",
	"UTCm0900Alaska": "UTC-09:00 Alasca",
	"UTCm1000Hawaii": "UTC-10:00 Havaí",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Hor. Universal Coord.",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Linha int. de data oeste",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} é somente para exibição. Para {languageID} prompts e sem voz: Não. Para voz e prompts em {languageVRTTSID}:Sim.",
	"UseUKEnglishText": "{languageID} é um idioma somente de exibição. Para comandos em {languageID} e sem voz: não. Para voz e comandos em inglês: sim.",
	"VRUK": "O idioma selecionado no momento não oferece suporte ao reconhecimento de voz.",
	"VRVolume": "Vol. Sist./toque",
	"VRVolumeTTS": "A orientação por voz será fornecida neste volume.",
	"VersionInfo": "Informações de versão",
	"_12h": "12 h",
	"_24h": "24 h",
};

framework.registerAppDictLoaded("syssettings", "pt_BR");