var Localization_syssettingsAppDict_sr_RS = {
	//"stringId" : "localString"
	"About": "око",
	"AdjustTime": "Podesi vreme",
	"AgreementsAndDisclaimers": "Ugovori i izjave o odricanju odgovornosti",
	"AgreementsDisclaimersText": "Idite na www.MazdaEndUserAgreements-Copyrights.com za poptunu listu licenci i copyright izjava o odricanju od odgovornosti",
	"Auto": "Auto.",
	"Bluetooth": "Bluetooth",
	"Brightness": "Osvetlj.",
	"Celsius": "°C",
	"ChooseLanguage": "Odaberite jezik",
	"Clock": "Sat",
	"Communication": "Komunikacija",
	"CommunicationResetConfText": "Jeste li sigurni da želite da vratite postavke komunikacije na fabrički podrazumevane vrednosti?",
	"CommunicationResetErrorRetryText": "Greška pri vraćanju postavki komunikacije na fabrički podrazumevane vrednosti. Da li želite da pokušate ponovo?",
	"CommunicationResetProgressText": "Vrać.postav.komun.na fabr.vrednosti",
	"ContactsSortOrder": "Redosled sortiranja kontakata",
	"ContactsSortOrderTitle": "Redosled sortiranja kontakata",
	"Contrast": "Kontrast",
	"Day": "Dan",
	"DayLightSavingsTime": "Vreme dnevne uštede",
	"Display": "Ekran",
	"DisplayResetConfText": "Jeste li sigurni da želite da vratite postavke ekrana na fabrički podrazumevane vrednosti?",
	"DisplayResetErrorText": "Greška pri vraćanju postavki ekrana na fabrički podrazumevane vrednosti. Da li želite da pokušate ponovo?",
	"DisplayResetProgressText": "Vraćanje postavki ek.na fabr.vrednosti",
	"Distance": "Udaljenost",
	"DownloadCallContacts": "Automatski preuzmi kontakte",
	"DownloadCallEmail": "Automatski preuzmi Email",
	"DownloadCallHistory": "Automatski preuzmi istoriju poziva",
	"DownloadCallText": "Automatski preuzmi SMS",
	"Eastern": "Istočno",
	"EditPresetMessage": "Uredi predporuku",
	"EmailNotifications": "Obaveštenja Email",
	"EmailSmsNotifications": "Obaveštenja Email/SMS-om",
	"FactoryReset": "Fabričko resetovanje",
	"FactoryResetConfText": "Sigurno želite da vratite sve postavke na podrazumevane? (Sistem će se ponovo pokrenuti nakon uspešnog resetovanja fabr. postavki.)",
	"FactoryResetErrorText": "Greška pri vraćanju postavki na fabrički podrazumevane vrednosti. Da li želite da pokušate ponovo?",
	"FactoryResetProgressText": "Vraćanje post. na fabr. Pod. vrednosti",
	"Fahrenheit": "°F",
	"FirstLast": "Ime, prezime",
	"Fixed": "Fiksni",
	"GPSSync": "GPS sinhronizacija",
	"Inband": "U op",
	"IncomingCallNotifications": "Obaveštenja o dolaznom pozivu",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "indonežanski",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "heksadecimalni",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "numerički",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "tajlandski",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Jezik",
	"LanguageChangeErrorText": "Greška pri promeni jezika. Da li želite da pokušate ponovo?",
	"LanguageChangeProgressText": "Promena jezika",
	"LanguageChangeSuccess": "Jezik promenjen na {languageID}",
	"LanguageConfText": "Jeste li sigurni da želite da promenite jezik u {languageID}?",
	"LanguageConfTextNoVR": "{languageID} jezik je samo jezik za prikaz. Za glasovne funkcije koristiće se britanski engleski. Želite li jezik za prikaz da promenite u {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} jezik je samo jezik za prikaz. Za glasovne funkcije koristiće se {VRlanguageID}. Želite li jezik za prikaz da promenite u {languageID}?",
	"LastFirst": "Prezime, ime",
	"Miles": "mi",
	"Mobile911": "Mobilni 192",
	"Mobile911Description": "Kada je uključeno, vozilo će automatski pozvati službu 192 nakon nesreće.",
	"Mode": "Režim",
	"MusicDatabaseUpdate": "Ažuriranje muzičke baze podataka",
	"NaviVolumeTTS": "Navigacija navođenje će se vršiti ovom jačinom звука.",
	"NetworkManagement": "Upravljanje mrežom",
	"Night": "Noć",
	"PhoneVolume": "Jačina zv. telef.",
	"PresetBeThereTen": "Biću tamo za 10 minuta.",
	"PresetBeThereTwenty": " Biću tamo za 20 minuta.",
	"PresetCallLater": "Pozvaću te kasnije.",
	"PresetCantTalk": "Ne mogu sada da razgovaram.",
	"PresetDriving": "Sada vozim.",
	"PresetMessages": "Podešene poruke",
	"PresetMessagesTitle": "Podešene poruke",
	"PresetNeedMore": " Potrebno mi je više instrukcija.",
	"PresetNo": "Ne",
	"PresetOk": "U redu",
	"PresetPleaseCall": "Pozovite me.",
	"PresetStuck": "Zaglavljen u saobraćaju.",
	"PresetThanks": "Hvala!",
	"PresetWhere": "Gde ste?",
	"PresetWhy": "Zašto?",
	"PresetYes": "Da",
	"Recent": "Nedavno",
	"Reset": "Resetuj",
	"Ringtone": "Ton zvona",
	"RingtoneVolumeTTS": "Telefonski poziv će biti ove jačine",
	"SMSNotifications": "Obaveštenja SMS",
	"Safety": "Bezbedn.",
	"SelectKBLang": "Izbor tastature",
	"SelectTimeZone": "Izbor vremenske zone",
	"SetClockHrsMinus": "Smanji broj sati",
	"SetClockHrsPlus": "Povećaj broj sati",
	"SetClockMinMinus": "Smanji broj minuta",
	"SetClockMinPlus": "Povećaj broj minuta",
	"Settings": "Postavke",
	"SystemSettings": "Sist. postavke",
	"Temp": "Temperatura ",
	"TimeFormat": "Format vremena",
	"TimeZoneSelect": "Vremenska zona je izabrana",
	"ToolTips": "Opisi alatki",
	"TurnDisplayOff": "ISKLJUČI ekran",
	"TurnDisplayOffShowClock": "ISKLJUČI ekran i prikaži sat",
	"UTC0000Casablanca": "UTC Kazablanka",
	"UTC0000CoordinatedUniversalTime": "UTC Koord. univ. vreme",
	"UTC0000Dublin": "UTC Dablin, London",
	"UTC0000Monrovia": "UTC Monrovija, Rejkjavik",
	"UTC0100Amsterdam": "UTC+01:00  Am, Bln, B, Rim",
	"UTC0100Belgrade": "UTC+01:00 Bgd, Bts, Bp, Prag",
	"UTC0100Brussels": "UTC+01:00 Bxl, Cph, Mad, Pariz",
	"UTC0100Sarajevo": "UTC+01:00 Sa, Sk, Varšava",
	"UTC0100WestCentralAfrica": "UTC+01:00 Zapadna Centr. Afr.",
	"UTC0100Windhoek": "UTC+01:00 Vindhuk",
	"UTC0200Athens": "UTC+02:00 Atina, Bukurešt",
	"UTC0200Beirut": "UTC+02:00 Bejrut",
	"UTC0200Cairo": "UTC+02:00 Kairo",
	"UTC0200Damascus": "UTC+02:00 Damask",
	"UTC0200EEurope": "UTC+02:00 Ist. Evropa",
	"UTC0200Harare": "UTC+02:00 Harare, Pretorija",
	"UTC0200Helsinki": "UTC+02:00 Kv, Riga, Talin, Vln",
	"UTC0200Istanbul": "UTC+02:00 Istambul",
	"UTC0200Jerusalem": "UTC+02:00 Jerusalim",
	"UTC0300Amman": "UTC+03:00 Aman",
	"UTC0300Baghdad": "UTC+03:00 Bagdad",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuvajt, Rijad",
	"UTC0300Nairobi": "UTC+03:00 Najrobi",
	"UTC0330Tehran": "UTC+03:30 Teheran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dabi, Muskat",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Moskva, Spb",
	"UTC0400PortLouis": "UTC+04:00 Port Luis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Jerevan",
	"UTC0430Kabul": "UTC+04:30 Kabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karači",
	"UTC0500Tashkent": "UTC+05:00 Taškent",
	"UTC0530Chennai": "UTC+05:30 Kolkata, Mum",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Džajavarden.",
	"UTC0545Kathmandu": "UTC+05:45 Katmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Daka",
	"UTC0600Ekaterinburg": "UTC+06:00 Jekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Jangon (Rangun)",
	"UTC0700Bangkok": "UTC+07:00 Bankok, Hanoj",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00  Pek, Urumći",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnojarsk",
	"UTC0800KualaLumpur": "UTC+08:00 Kuala Lumpur, Sing.",
	"UTC0800Perth": "UTC+08:00 Pert",
	"UTC0800Taipei": "UTC+08:00 Tajpei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulanbatar",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokio",
	"UTC0900Seoul": "UTC+09:00 Seul",
	"UTC0930Adelaide": "UTC+09:30 Adelejd",
	"UTC0930Darwin": "UTC+09:30 Darvin",
	"UTC1000Brisbane": "UTC+10:00 Brizbejn",
	"UTC1000Canberra": "UTC+10:00 Melburn, Sidnej",
	"UTC1000Guam": "UTC+10:00 Gvam, Port Morsbi",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Jakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Sol. Ostrva",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Okland, Velington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Koord. un. Vreme",
	"UTC1200Fiji": "UTC+12:00 Fidži",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nukualofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azori",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Zelenortska ostrva",
	"UTCm0100Casablanca": "UTC-01:00 Kazablanka",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Koord. univ. vreme",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Koord. univ. vr-02",
	"UTCm0200MidAtlantic": "UTC-02:00 Srednji Atlantik",
	"UTCm0300Brasilia": "UTC-03:00 Brazilijia",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Ajres",
	"UTCm0300Cayenne": "UTC-03:00 Kajena, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Grenland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Njufaundlend",
	"UTCm0400Asuncion": "UTC-04:00 Asunsion",
	"UTCm0400AtlanticTime": "UTC-04:00 Atlan. vreme (Kan.)",
	"UTCm0400Cuiaba": "UTC-04:00 Kujaba",
	"UTCm0400Georgetown": "UTC-04:00 Gtn, La Paz",
	"UTCm0400Santiago": "UTC-04:00 Santjago",
	"UTCm0430Caracas": "UTC-04:30 Karakas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Kito",
	"UTCm0500EasternTime": "UTC-05:00 Ist. am. vr. (SAD)",
	"UTCm0500Indiana": "UTC-05:00 Indijana (Istočna)",
	"UTCm0600CentralAmerica": "UTC-06:00 Sr. am. Vreme",
	"UTCm0600CentralTime": "UTC-06:00 Sr. am. vr. (SAD)",
	"UTCm0600Guadalajara": "UTC-06:00 Gdl, MC, Monterej",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskačevan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Čiv., La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Sj. am. pl. vr. ",
	"UTCm0800BajaCalifornia": "UTC-08:00 Donja Kalifornija",
	"UTCm0800PacificTime": "UTC-08:00 Pacifičko vr. (SAD)",
	"UTCm0900Alaska": "UTC-09:00 Aljaska",
	"UTCm1000Hawaii": "UTC-10:00 Havaji",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Koord. univ. vreme",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 M. granica dat.-zapa.",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} je samo jezik ekrana. Za {languageID} poruke bez glasa: ne. Za glas i poruke na {languageVRTTSID}:da.",
	"UseUKEnglishText": "{languageID} jezik je samo jezik za prikaz. Ako želite {languageID} jezik za poruke, ili želite režim bez glasovnih naredbi: „Ne“ Za glasovne naredbe i poruke na engleskom jeziku: „Da“",
	"VRUK": "Trenutni izbor jezika ne podržava prepoznavanje govora.",
	"VRVolume": "VR i ton zvona",
	"VRVolumeTTS": "Glasovno navođenje će se vršiti ovom jačinom zvuka",
	"VersionInfo": "Informacije o ovoj verziji",
	"_12h": "12 h",
	"_24h": "24 h",
};

framework.registerAppDictLoaded("syssettings", "sr_RS");