var Localization_syssettingsAppDict_he_IL = {
	//"stringId" : "localString"
	"About": "אוֹדוֹת",
	"AdjustTime": "התאם זמן",
	"AgreementsAndDisclaimers": "הסכמים והבהרות",
	"AgreementsDisclaimersText": "נא לבקר באתר www.MazdaEndUserAgreements-Copyrights.com  כדי לצפות ברשימה מלאה של רשיונות והסכמי זכויות יוצרים.",
	"Auto": "אוט'",
	"Bluetooth": "Bluetooth",
	"Brightness": "בהירות",
	"Celsius": "°C",
	"ChooseLanguage": "בחר שפה",
	"Clock": "שעון",
	"Communication": "תקשורת",
	"CommunicationResetConfText": "האם אתה בטוח שברצונך להחזיר את כל הגדרות התקשורת לערכי ברירת מחדל של היצרן שלהם?",
	"CommunicationResetErrorRetryText": "שגיאה בהחזרת הגדרות תקשורת לברירת מחדל של היצרן. האם ברצונך לנסות שוב?",
	"CommunicationResetProgressText": "משחזר הגדרות ת המחדל של תקשורת",
	"ContactsSortOrder": "סדר מיון אנשי קשר",
	"ContactsSortOrderTitle": "סדר מיון קישורים",
	"Contrast": "ניגודיות",
	"Day": "יום",
	"DayLightSavingsTime": "שעון קיץ",
	"Display": "הצג",
	"DisplayResetConfText": "האם אתה בטוח שברצונך להחזיר את כל הגדרות התצוגה לערכי ברירת המחדל שלהם?",
	"DisplayResetErrorText": "שגיאה בהחזרת הגדרות התצוגה לברירת מחדל של היצרן. האם ברצונך לנסות שוב?",
	"DisplayResetProgressText": "משחזר את הגדרות המפעל של תצוגה",
	"Distance": "מרחק",
	"DownloadCallContacts": "הורדת אנשי קשר אוטומטית",
	"DownloadCallEmail": "הורדת דואר אלקטרוני אוטומטית",
	"DownloadCallHistory": "הורדת היסטוריית שיחות אוטומטית",
	"DownloadCallText": "הורדת SMS אוטומטית",
	"Eastern": "מזרחי",
	"EditPresetMessage": "ערוך הודעות",
	"EmailNotifications": "הודעות Email",
	"EmailSmsNotifications": "הודעות Email/SMS",
	"FactoryReset": "איפוס יצרן",
	"FactoryResetConfText": "האם אתה בטוח שברצונך להחזיר את כל ההגדרות לברירת מחדל של היצרן שלהם? (מערכת תופעל מחדש באתחול יצרן מוצלח)",
	"FactoryResetErrorText": "שגיאה בהחזרת הגדרות לברירת מחדל של היצרן. האם ברצונך לנסות שוב?",
	"FactoryResetProgressText": "משחזר את הגדרות ברירת המחדל",
	"Fahrenheit": "°F",
	"FirstLast": "שם פרטי, שם משפחה",
	"Fixed": "קבוע",
	"GPSSync": "GPS Sync",
	"Inband": "In-b",
	"IncomingCallNotifications": "הודעות של שיחה נכנסת",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)\u200e",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)\u200e",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)\u200e",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)\u200e",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)\u200e",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)\u200e",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)\u200e",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)\u200e",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)\u200e",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)\u200e",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)\u200e",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)\u200e",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)\u200e",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)\u200e",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)\u200e",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)\u200e",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)\u200e",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)\u200e",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)\u200e",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)\u200e",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)\u200e",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)\u200e",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)\u200e",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)\u200e",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)\u200e",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)\u200e",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)\u200e",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)\u200e",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)\u200e",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)\u200e",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)\u200e",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)\u200e",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)\u200e",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)\u200e",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "ספירה על בסיס 16 ספרות",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "מספרי",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "שפה",
	"LanguageChangeErrorText": "שגיאה בהחלפת שפה. האם ברצונך לנסות שוב?",
	"LanguageChangeProgressText": "משנה שפה",
	"LanguageChangeSuccess": "שפה שונתה ל {languageID}",
	"LanguageConfText": "האם אתה בטוח שברצונך לשנות את השפה ל {languageID}?",
	"LanguageConfTextNoVR": " {languageID} היא שפת תצוגה בלבד. אנגלית בריטית תשמש לפונקציות קוליות. האם לשנות את שפת התצוגה ל {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": " {languageID} היא שפת תצוגה בלבד. {VRlanguageID} תשמש לפונקציות קוליות. האם לשנות את שפת התצוגה ל {languageID}?",
	"LastFirst": "שם משפחה, שם פרטי",
	"Miles": "mi",
	"Mobile911": "נייד 911",
	"Mobile911Description": "כאשר מופעל, הרכב יחייג 911 אוטומטית לאחר תאונה.",
	"Mode": "מצב",
	"MusicDatabaseUpdate": "עדכון מאגר מידע מוסיקלי",
	"NaviVolumeTTS": "ניווט יהיה ברמה זו.",
	"NetworkManagement": "ניהול רשת",
	"Night": "לילה",
	"PhoneVolume": "עוצמת טלפון",
	"PresetBeThereTen": "אהיה שם תוך 10 דקות.",
	"PresetBeThereTwenty": "אהיה שם תוך 20 דקות.",
	"PresetCallLater": "אתקשר יותר מאוחר.",
	"PresetCantTalk": "אינני יכול לדבר עכשיו",
	"PresetDriving": "נוהג עכשיו.",
	"PresetMessages": "עריכה מחדש של ההודעות",
	"PresetMessagesTitle": "עריכה מחדש של ההודעות",
	"PresetNeedMore": "אני זקוק ליותר הכוונה.",
	"PresetNo": "לא",
	"PresetOk": "OK",
	"PresetPleaseCall": "בקשה צלצל אלי",
	"PresetStuck": "תקוע בפקק.",
	"PresetThanks": "תודה!",
	"PresetWhere": "היכן אתה נמצא?",
	"PresetWhy": "למה?",
	"PresetYes": "כן",
	"Recent": "מקלדת אחרונה",
	"Reset": "איפוס",
	"Ringtone": "רינגטון",
	"RingtoneVolumeTTS": "שיחת טלפון תהיה בעוצמה זאת\n\n",
	"SMSNotifications": "הודעות SMS",
	"Safety": "בטיחות",
	"SelectKBLang": "בחר מקלדת",
	"SelectTimeZone": "בחר איזור זמן",
	"SetClockHrsMinus": "להקטין שעות",
	"SetClockHrsPlus": "להגדיל שעות",
	"SetClockMinMinus": "להקטין דקות",
	"SetClockMinPlus": "להגדיל דקות",
	"Settings": "הגדרות",
	"SystemSettings": "הגדרות המערכת",
	"Temp": "טמפרטורה",
	"TimeFormat": "תצוגת זמן",
	"TimeZoneSelect": "בחר איזור זמן",
	"ToolTips": "תיאורי כלים",
	"TurnDisplayOff": "כבה תצוגה",
	"TurnDisplayOffShowClock": "כבה תצוגה והראה את השעון",
	"UTC0000Casablanca": "UTC קזבלנקה",
	"UTC0000CoordinatedUniversalTime": "UTC זמן אוניברסלי מתואם",
	"UTC0000Dublin": "UTC דבלין, אדינבורו, ליסבון",
	"UTC0000Monrovia": "UTC מונרוביה, רייקיאויק",
	"UTC0100Amsterdam": "UTC+01:00 אמסטרדם, ברלין",
	"UTC0100Belgrade": "UTC+01:00 בלגרד, ברטיסלבה",
	"UTC0100Brussels": "UTC+01:00 בריסל, קופנהגן",
	"UTC0100Sarajevo": "UTC+01:00 סרייבו, סקופיה",
	"UTC0100WestCentralAfrica": "UTC+01:00 מערב אפריקה",
	"UTC0100Windhoek": "UTC+01:00 וינדהוק",
	"UTC0200Athens": "UTC+02:00 תונה, בוקרשט",
	"UTC0200Beirut": "UTC+02:00 ביירות",
	"UTC0200Cairo": "UTC+02:00 קהיר",
	"UTC0200Damascus": "UTC+02:00 דמשק",
	"UTC0200EEurope": "UTC+02:00 אירופה מזרחית",
	"UTC0200Harare": "UTC+02:00 הרארה, פרטוריה",
	"UTC0200Helsinki": "UTC+02:00 הלסנקי, קייב",
	"UTC0200Istanbul": "UTC+02:00 איסטנבול",
	"UTC0200Jerusalem": "UTC+02:00 ירושלים",
	"UTC0300Amman": "UTC+03:00 עמאן",
	"UTC0300Baghdad": "UTC+03:00 בגדד",
	"UTC0300Kaliningrad": "UTC+03:00 קלינינגרד, מינסק",
	"UTC0300Kuwait": "UTC+03:00 כווית, ריאד",
	"UTC0300Nairobi": "UTC+03:00 ניירובי",
	"UTC0330Tehran": "UTC+03:30 טהראן",
	"UTC0400AbuDhabi": "UTC+04:00  אבו דאבי, מוסקט",
	"UTC0400Baku": "UTC+04:00 בקו ",
	"UTC0400Moscow": "UTC+04:00 מוסקבה ",
	"UTC0400PortLouis": "UTC+04:00 פורט לואי",
	"UTC0400Tbilisi": "UTC+04:00 טביליסי",
	"UTC0400Yerevan": "UTC+04:00 ירוון",
	"UTC0430Kabul": "UTC+04:30 קבול",
	"UTC0500Islamabad": "UTC+05:00 איסלמאבאד",
	"UTC0500Tashkent": "UTC+05:00 טשקנט",
	"UTC0530Chennai": "UTC+05:30 צ'נאי, כלכותה",
	"UTC0530SriJayawardenepura": "UTC+05:30 סרי ג'אווארדנפורה",
	"UTC0545Kathmandu": "UTC+05:45 קטמנדו",
	"UTC0600Astana": "UTC+06:00 אסטנה",
	"UTC0600Dhaka": "UTC+06:00 דאקה",
	"UTC0600Ekaterinburg": "UTC+06:00 יקטירינבורג",
	"UTC0630Yangon": "UTC+06:30 יאנגון(רנגון)",
	"UTC0700Bangkok": "UTC+07:00 בנגקוק, האנוי",
	"UTC0700Novosibirsk": "UTC+07:00 נובוסיבירסק",
	"UTC0800Beijing": "UTC+08:00 בייג'ינג, צ'ונג'ינג",
	"UTC0800Krasnoyarsk": "UTC+08:00 קרסנויארסק ",
	"UTC0800KualaLumpur": "UTC+08:00 קואלה לומפור",
	"UTC0800Perth": "UTC+08:00 פרת'",
	"UTC0800Taipei": "UTC+08:00 טאיפיי",
	"UTC0800Ulaanbaatar": "UTC+08:00 אולאאנבטאר",
	"UTC0900Irkutsk": "UTC+09:00 אירקוטסק",
	"UTC0900Osaka": "UTC+09:00 אוסקה, טוקיו",
	"UTC0900Seoul": "UTC+09:00 סאול",
	"UTC0930Adelaide": "UTC+09:30 אדליד",
	"UTC0930Darwin": "UTC+09:30 דרווין",
	"UTC1000Brisbane": "UTC+10:00 בריזביין",
	"UTC1000Canberra": "UTC+10:00 מלבורן, סידני",
	"UTC1000Guam": "UTC+10:00 גואם, פורט מורסבי",
	"UTC1000Hobart": "UTC+10:00 הובארט",
	"UTC1000Yakutsk": "UTC+10:00 יקוטסק",
	"UTC1100SolomonIs": "UTC+11:00 האי סולומון",
	"UTC1100Vladivostok": "UTC+11:00 ולדיווסטוק",
	"UTC1200Auckland": "UTC+12:00 אוקלנד, וולינגטון",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 זמן אוניברסלי",
	"UTC1200Fiji": "UTC+12:00 פיג'י",
	"UTC1200Magadan": "UTC+12:00 מגדן",
	"UTC1300NukuAlofa": "UTC+13:00 נוקואלופה",
	"UTC1300Samoa": "UTC+13:00 סמואה",
	"UTCm0100Azores": "UTC-01:00 האיים האזוריים",
	"UTCm0100CapeVerdeIs": "UTC-01:00 האי קייפ ורדה",
	"UTCm0100Casablanca": "UTC-01:00 קזבלנקה",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 אוניברסלי מתואם",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 זמן אוניברסלי ",
	"UTCm0200MidAtlantic": "UTC-02:00 אמצע האטלנטי",
	"UTCm0300Brasilia": "UTC-03:00 ברזיליה",
	"UTCm0300BuenosAires": "UTC-03:00 בואנוס אירס",
	"UTCm0300Cayenne": "UTC-03:00 קאיין, פורטלזה",
	"UTCm0300Greenland": "UTC-03:00 גרינלנד",
	"UTCm0300Montevideo": "UTC-03:00 מונטווידאו",
	"UTCm0300Salvador": "UTC-03:00 סלבדור",
	"UTCm0330Newfoundland": "UTC-03:30 ניו פאונדלנד",
	"UTCm0400Asuncion": "UTC-04:00 אסונסיון",
	"UTCm0400AtlanticTime": "UTC-04:00 ​​האטלנטי, קנדה",
	"UTCm0400Cuiaba": "UTC-04:00 קויאבה",
	"UTCm0400Georgetown": "UTC-04:00 ג'ורג'טאון, סן חואן",
	"UTCm0400Santiago": "UTC-04:00 סנטיאגו",
	"UTCm0430Caracas": "UTC-04:30 קרקס",
	"UTCm0500Bogota": "UTC-05:00 בוגוטה, לימה",
	"UTCm0500EasternTime": "UTC-05:00 מזרחי, ארה\"ב",
	"UTCm0500Indiana": "UTC-05:00 אינדיאנה (מזרח)",
	"UTCm0600CentralAmerica": "UTC-06:00 מרכז אמריקה",
	"UTCm0600CentralTime": "UTC-06:00 מרכז, ארה\"ב,ויכול",
	"UTCm0600Guadalajara": "UTC-06:00 מקסיקו סיטי",
	"UTCm0600Saskatchewan": "UTC-06:00 ססקצ'ואן",
	"UTCm0700Arizona": "UTC-07:00 אריזונה",
	"UTCm0700Chihuahua": "UTC-07:00 צ'יוואווה, לה פאס",
	"UTCm0700MountainTime": "UTC-07:00 הרים(ארה\"ב/קנדה)",
	"UTCm0800BajaCalifornia": "UTC-08:00 באחה קליפורניה",
	"UTCm0800PacificTime": "UTC-08:00 שעון החוף ",
	"UTCm0900Alaska": "UTC-09:00 אלסקה",
	"UTCm1000Hawaii": "UTC-10:00 ממיר זמן אוניברסלי",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 זמן מתואם",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 קו תאריך הבינ.",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} היא שפת תצוגה בלבד. להנחיות ב{languageID} ללא קול: לא. להנחיות וקול ב{languageVRTTSID}:כן.",
	"UseUKEnglishText": " {languageID} היא שפת תצוגה בלבד. להנחיות ב{languageID} ללא קול: לא. להנחיות וקול באנגלית: כן.",
	"VRUK": "בחירת השפה הנוכחית לא תומכת בזיהוי הקול.",
	"VRVolume": "רינגטון ו-קול",
	"VRVolumeTTS": "הדרכה קולית תהיה בעוצמה זאת",
	"VersionInfo": "מידע על גרסה",
	"_12h": "12 ש",
	"_24h": "24 ש",
};

framework.registerAppDictLoaded("syssettings", "he_IL");