var Localization_syssettingsAppDict_ms_MY = {
	//"stringId" : "localString"
	"About": "Perihal",
	"AdjustTime": "Laraskan Masa",
	"AgreementsAndDisclaimers": "Perjanjian dan Penafian",
	"AgreementsDisclaimersText": "Sila pergi ke www.MazdaEndUserAgreements-Copyrights.com untuk mendapatkan senarai penuh pendedahan lesen dan hak cipta.",
	"Auto": "Auto",
	"Bluetooth": "Bluetooth",
	"Brightness": "Kecerahan",
	"Celsius": "°C",
	"ChooseLanguage": "Pilih Bahasa",
	"Clock": "Jam",
	"Communication": "Komunikasi",
	"CommunicationResetConfText": "Adakah anda pasti mahu mengembalikan tetapan komunikasi kepada nilai asal?",
	"CommunicationResetErrorRetryText": "Ralat berlaku semasa mengembalikan tetapan komunikasi kepada kilang asal. Anda ingin cuba semula?",
	"CommunicationResetProgressText": "Kmbalikn ttpn komunikasi kpd kilang asal",
	"ContactsSortOrder": "Tertib  Kenalan",
	"ContactsSortOrderTitle": "Tertib  Kenalan",
	"Contrast": "Kontras",
	"Day": "Siang",
	"DayLightSavingsTime": "Waktu Jimat Siang",
	"Display": "Paparan",
	"DisplayResetConfText": "Adakah anda pasti mahu mengembalikan tetapan paparan kepada nilai asal?",
	"DisplayResetErrorText": "Ralat berlaku semasa mengembalikan tetapan paparan kepada kilang asal. Anda ingin cuba semula?",
	"DisplayResetProgressText": "Kembalikan ttpn paparan kpd kilang asal.",
	"Distance": "Jarak",
	"DownloadCallContacts": "Muat Turun Kenalan Auto",
	"DownloadCallEmail": "Muat Turun E-mel Auto",
	"DownloadCallHistory": "Muat Turun Rekod Panggilan Auto",
	"DownloadCallText": "Muat Turun Teks Auto",
	"Eastern": "Timur",
	"EditPresetMessage": "Edit Msj Prattap",
	"EmailNotifications": "Pemberitahuan E-mel",
	"EmailSmsNotifications": "Pemberitahuan E-mel/SMS",
	"FactoryReset": "Tetapan Semula Kilang",
	"FactoryResetConfText": "Adakah anda pasti mahu mengembalikan semua tetapan kepada kilang asal? (Sistem anda but semula apabila tetapan semula kilang berjaya.)",
	"FactoryResetErrorText": "Ralat berlaku semasa mengembalikan tetapan kepada kilang asal. Anda ingin cuba semula?",
	"FactoryResetProgressText": "Kembalikan tetapan kepada lalai kilang",
	"Fahrenheit": "°F",
	"FirstLast": "Nama Pertama, Nama Keluarga",
	"Fixed": "Dibaiki",
	"GPSSync": "Penyelarasan GPS",
	"Inband": "Dlm jlr",
	"IncomingCallNotifications": "Pemberitahuan Panggilan Masuk",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Melayu (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Perenambelasan",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Angka",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Bahasa",
	"LanguageChangeErrorText": "Ralat semasa menukar bahasa. Anda ingin cuba semula?",
	"LanguageChangeProgressText": "Menukar Bahasa",
	"LanguageChangeSuccess": "Bahasa ditukar kepada {languageID}",
	"LanguageConfText": "Adakah anda pasti mahu menukar bahasa kepada {languageID}?",
	"LanguageConfTextNoVR": "{languageID} adalah bahasa yang Dipaparkan Sahaja. Bahasa Inggeris UK akan digunakan untuk fungsi-fungsi suara.",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} adalah bahasa yang Dipaparkan Sahaja. Bahasa {VRlanguageID} akan digunakan untuk fungsi-fungsi suara.",
	"LastFirst": "Nama Keluarga, Nama Pertama",
	"Miles": "mi",
	"Mobile911": "911 Mudah Alih",
	"Mobile911Description": "Bila dihdpkn, kndraan akan hubungi 911 secara automatik slps kmlngn.",
	"Mode": "Mod",
	"MusicDatabaseUpdate": "Kemaskini Pangkalan Data Muzik",
	"NaviVolumeTTS": "Navigasi akan menggunakan kelantangan ini.",
	"NetworkManagement": "Pengurusan Rangkaian",
	"Night": "Malam",
	"PhoneVolume": "Kelantangan Tel",
	"PresetBeThereTen": "Akan sampai dalam 10 minit.",
	"PresetBeThereTwenty": "Akan sampai dalam 20 minit.",
	"PresetCallLater": "Hubungi anda kemudian.",
	"PresetCantTalk": "Tak boleh bercakap sekarang.",
	"PresetDriving": "Sedang memandu.",
	"PresetMessages": "Mesej Pratetap",
	"PresetMessagesTitle": "Mesej Pratetap",
	"PresetNeedMore": "Saya memerlukan lagi arah.",
	"PresetNo": "Tidak",
	"PresetOk": "OK",
	"PresetPleaseCall": "Hubungi saya.",
	"PresetStuck": "Tersekat dalam kesesakan lalu lintas.",
	"PresetThanks": "Terima kasih!",
	"PresetWhere": "Awak di mana?",
	"PresetWhy": "Mengapa?",
	"PresetYes": "Ya",
	"Recent": "Baru-baru ini",
	"Reset": "Tetapkan semula",
	"Ringtone": "Nada dering",
	"RingtoneVolumeTTS": "Panggilan telefon akan menggunakan kelantangan ini",
	"SMSNotifications": "Pemberitahuan SMS",
	"Safety": "Keselam",
	"SelectKBLang": "Pilih Papan Kekunci",
	"SelectTimeZone": "Pilih Zon Waktu",
	"SetClockHrsMinus": "Kurangkan Jam",
	"SetClockHrsPlus": "Tambah Jam",
	"SetClockMinMinus": "Kurangkan Minit",
	"SetClockMinPlus": "Tambah Minit",
	"Settings": "Tetapan",
	"SystemSettings": "Tetapan Sistem",
	"Temp": "Suhu",
	"TimeFormat": "Format Masa",
	"TimeZoneSelect": "Pilihan Zon Waktu",
	"ToolTips": "Petua Alat",
	"TurnDisplayOff": "Matikan Paparan",
	"TurnDisplayOffShowClock": "Matikan Paparan dan Tunjuk Jam",
	"UTC0000Casablanca": "UTC Casablanca",
	"UTC0000CoordinatedUniversalTime": "UTC Masa Universal Terselaras",
	"UTC0000Dublin": "UTC Dublin, London",
	"UTC0000Monrovia": "UTC Monrovia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Berlin,Rome",
	"UTC0100Belgrade": "UTC+01:00 Belgrade, Bratislava",
	"UTC0100Brussels": "UTC+01:00 Brussels, Madrid",
	"UTC0100Sarajevo": "UTC+01:00 Sarajevo,Warsaw",
	"UTC0100WestCentralAfrica": "UTC+01:00 Afrika Tgh Barat",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Athens, Bucharest",
	"UTC0200Beirut": "UTC+02:00 Beirut",
	"UTC0200Cairo": "UTC+02:00 Keharah",
	"UTC0200Damascus": "UTC+02:00 Damyik",
	"UTC0200EEurope": "UTC+02:00 Eropah T",
	"UTC0200Harare": "UTC+02:00 Harare, Pretoria",
	"UTC0200Helsinki": "UTC+02:00 Riga, Tallinn",
	"UTC0200Istanbul": "UTC+02:00 Istanbul",
	"UTC0200Jerusalem": "UTC+02:00 Baitulmuqqadis",
	"UTC0300Amman": "UTC+03:00 Amman",
	"UTC0300Baghdad": "UTC+03:00 Baghdad",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuwait, Riyadh",
	"UTC0300Nairobi": "UTC+03:00 Nairobi",
	"UTC0330Tehran": "UTC+03:30 Tehran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Muscat",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Moscow,Volgograd",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Kabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karachi",
	"UTC0500Tashkent": "UTC+05:00 Tashkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai, New Delhi",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayaward.",
	"UTC0545Kathmandu": "UTC+05:45 Kathmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bangkok, Jakarta",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Beijing,Chongqing",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 K.Lumpur, S'pura",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulaanbaatar",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokyo",
	"UTC0900Seoul": "UTC+09:00 Seoul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Canberra, Sydney",
	"UTC1000Guam": "UTC+10:00 Guam,Port Moresby",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Kep. Solomon",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland,Wellington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 M. Univ Trlaras+12",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azores",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Kep. Cape Verde",
	"UTCm0100Casablanca": "UTC-01:00 Casablanca",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Masa Univ Terlaras",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 M. Univ Trlaras-02",
	"UTCm0200MidAtlantic": "UTC-02:00 Atlantik Tengah",
	"UTCm0300Brasilia": "UTC-03:00 Brasilia",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Cayenne, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Greenland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Newfoundland",
	"UTCm0400Asuncion": "UTC-04:00 Asuncion",
	"UTCm0400AtlanticTime": "UTC-04:00 Wkt Atlantik (Kan.)",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiaba",
	"UTCm0400Georgetown": "UTC-04:00 La Paz, San Juan",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Masa Timur (AS)",
	"UTCm0500Indiana": "UTC-05:00 Indiana (Timur)",
	"UTCm0600CentralAmerica": "UTC-06:00 Amerika Tengah",
	"UTCm0600CentralTime": "UTC-06:00 Waktu Tngh (AS)",
	"UTCm0600Guadalajara": "UTC-06:00 Mexico City",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua,La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Masa Gunung (AS)",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja California",
	"UTCm0800PacificTime": "UTC-08:00 Masa Pasifik (AS)",
	"UTCm0900Alaska": "UTC-09:00 Alaska",
	"UTCm1000Hawaii": "UTC-10:00 Hawaii",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Masa Univ Trlaras-11",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 BaratG/TrkhA/bngs",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} ialah bahasa Paparan Sahaja. Untuk prom {languageID} dan tiada Suara: Tidak. Untuk Suara dan Prom dalam {languageVRTTSID}:Ya.",
	"UseUKEnglishText": "{languageID} adalah bahasa yang Dipaparkan Sahaja. Untuk prom {languageID} dan tiada Suara langsung: Tidak. Untuk Suara dan Prom dalam Bahasa Inggeris: Ya.",
	"VRUK": "Pemilihan bahasa semasa tidak penyokong pengecaman suara.",
	"VRVolume": "VR&Nada dering",
	"VRVolumeTTS": "Panduan suara akan menggunakan kelantangan ini",
	"VersionInfo": "Maklumat Versi",
	"_12h": "12j",
	"_24h": "24j",
};

framework.registerAppDictLoaded("syssettings", "ms_MY");