var Localization_syssettingsAppDict_el_GR = {
	//"stringId" : "localString"
	"About": "Πληροφορίες",
	"AdjustTime": "Προσαρμογή χρόνου",
	"AgreementsAndDisclaimers": "Συμφωνίες και δηλώσεις",
	"AgreementsDisclaimersText": "Μεταβείτε στη διεύθυνση www.MazdaEndUserAgreements-Copyrights.com για την πλήρη λίστα πληροφοριών αδειών και πνευματικών δικαιωμάτων.",
	"Auto": "Αυτόμ.",
	"Bluetooth": "Bluetooth",
	"Brightness": "Φωτεινότητα",
	"Celsius": "°C",
	"ChooseLanguage": "Επιλέξτε γλώσσα",
	"Clock": "Ρολόι",
	"Communication": "Επικοινωνία",
	"CommunicationResetConfText": "Είστε βέβαιοι ότι θέλετε να κάνετε αναστροφή των ρυθμίσεων επικοινωνίας στις προεπιλεγμένες τιμές τους;",
	"CommunicationResetErrorRetryText": "Σφάλμα αναστροφής ρυθμίσεων επικοινωνίας σε εργοστασιακές επιλογές. Θέλετε να ξαναδοκιμάσετε;",
	"CommunicationResetProgressText": "Επαν ρυθμ.επικοιν. εργοστ. επιλογές",
	"ContactsSortOrder": "Σειρά ταξινόμησης επαφών",
	"ContactsSortOrderTitle": "Σειρά ταξινόμησης επαφών",
	"Contrast": "Αντίθεση",
	"Day": "Ημέρα",
	"DayLightSavingsTime": "Θερινή ώρα",
	"Display": "Οθόνη",
	"DisplayResetConfText": "Είστε βέβαιοι ότι θέλετε να κάνετε επαναφορά των ρυθμίσεων προβολής στις προεπιλεγμένες τιμές τους;",
	"DisplayResetErrorText": "Σφάλμα επαναφοράς ρυθμίσεων οθόνης σε εργοστασιακές επιλογές. Θέλετε να ξαναδοκιμάσετε;",
	"DisplayResetProgressText": "Επαναφ.εργοστ. επιλ ρυθμ. εμφάνισης ",
	"Distance": "Απόσταση",
	"DownloadCallContacts": "Αυτόματη λήψη επαφών",
	"DownloadCallEmail": "Αυτόματη λήψη Email",
	"DownloadCallHistory": "Αυτόματη λήψη ιστορικού λήψης",
	"DownloadCallText": "Αυτόματη λήψη SMS",
	"Eastern": "Ανατ.",
	"EditPresetMessage": "Επεξ. προκαθ. μην.",
	"EmailNotifications": "Ειδοποιήσεις Email",
	"EmailSmsNotifications": "Ειδοποιήσεις Email/SMS",
	"FactoryReset": "Εργοστασιακή επαναφορά",
	"FactoryResetConfText": "Θέλετε να επαναφέρετε όλες τις ρυθμίσεις στις εργ. προεπιλογές; (Το σύστημα θα επανεκκινηθεί κατά την επιτυχή επαναφορά εργοστ. ρυθμίσεων.)",
	"FactoryResetErrorText": "Σφάλμα επεναφοράς ρυθμίσεων σε εργοστασιακές επιλογές. Θέλετε να ξαναδοκιμάσετε;",
	"FactoryResetProgressText": "Επαναφορά στις εργοστασι. επιλογές",
	"Fahrenheit": "°F",
	"FirstLast": "Όνομα, Επώνυμο",
	"Fixed": "Σταθ.",
	"GPSSync": "Συγχρονισμός GPS",
	"Inband": "Ζώνη",
	"IncomingCallNotifications": "Ειδοποιήσεις εισερχόμενων κλήσεων",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Δεκαεξαδικό",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Αριθμητικό",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Γλώσσα",
	"LanguageChangeErrorText": "Σφάλμα αλλαγής γλώσσας. Θέλετε να ξαναδοκιμάσετε;",
	"LanguageChangeProgressText": "Αλλαγή γλώσσας",
	"LanguageChangeSuccess": "Η γλώσσα άλλαξε σε {languageID}",
	"LanguageConfText": "Είστε βέβαιοι ότι θέλετε να αλλάξετε τη γλώσσα σε {languageID};",
	"LanguageConfTextNoVR": "Τα {languageID} είναι Μόνο η γλώσσα Εμφάνισης. Τα Αγγλικά (ΗΒ) θα χρησιμοποιηθούν για τις  λειτουργίες φωνής. Να αλλάξει η γλώσσα εμφάνισης σε {languageID};",
	"LanguageConfTextNoVRNoUKEnglish": "Τα {languageID} είναι Μόνο η γλώσσα Εμφάνισης. {VRlanguageID} θα χρησιμοποιηθούν για τις  λειτουργίες φωνής. Να αλλάξει η γλώσσα εμφάνισης σε {languageID};",
	"LastFirst": "Επώνυμο, Όνομα",
	"Miles": "mi",
	"Mobile911": "Κινητό 911",
	"Mobile911Description": "Όταν είναι ενεργό, το όχημα καλεί αυτόματα το 911 μετά από ατύχημα.",
	"Mode": "Λειτουργία",
	"MusicDatabaseUpdate": "Ενημέρωση βάσης δεδομένων μουσικής",
	"NaviVolumeTTS": "Πλοήγηση θα είναι σ' αυτή την ένταση ήχου.",
	"NetworkManagement": "Διαχείριση δικτύου",
	"Night": "Νύχτα",
	"PhoneVolume": "Ένταση τηλεφ.",
	"PresetBeThereTen": "Να είστε εκεί σε 10 λεπτά.",
	"PresetBeThereTwenty": "Να είστε εκεί σε 20 λεπτά.",
	"PresetCallLater": "Θα σας καλέσω αργότερα.",
	"PresetCantTalk": "Δεν μπορώ να μιλήσω τώρα.",
	"PresetDriving": "Οδήγηση σε εξέλιξη τώρα.",
	"PresetMessages": "Προκαθορισμένα μηνύματα",
	"PresetMessagesTitle": "Προκαθορισμένα μηνύματα",
	"PresetNeedMore": "Χρειάζομαι περισσότερες οδηγίες.",
	"PresetNo": "Όχι",
	"PresetOk": "OK",
	"PresetPleaseCall": "Κάλεσέ με.",
	"PresetStuck": "Κόλλημα σε κίνηση.",
	"PresetThanks": "Ευχαριστώ!",
	"PresetWhere": "Πού είστε;",
	"PresetWhy": "Γιατί;",
	"PresetYes": "Ναι",
	"Recent": "Πρόσφατο",
	"Reset": "Επαναφορά",
	"Ringtone": "Ήχος κλήσης",
	"RingtoneVolumeTTS": "Η τηλεφωνική κλήση θα είναι σ' αυτή την ένταση ήχου",
	"SMSNotifications": "Ειδοποιήσεις SMS",
	"Safety": "ασφαλής",
	"SelectKBLang": "Επιλέξτε πληκτρολόγιο",
	"SelectTimeZone": "Επιλογή ζώνης ώρας",
	"SetClockHrsMinus": "Μείωση ωρών",
	"SetClockHrsPlus": "Αύξηση ωρών",
	"SetClockMinMinus": "Μείωση λεπτών",
	"SetClockMinPlus": "Αύξηση λεπτών",
	"Settings": "Ρυθμίσεις",
	"SystemSettings": "Ρυθμ. συστ.",
	"Temp": "Θερμοκρασία",
	"TimeFormat": "Μορφή ώρας",
	"TimeZoneSelect": "Επιλογή ζώνης ώρας",
	"ToolTips": "Συμβουλές εργαλείου",
	"TurnDisplayOff": "Απενεργοποίηση οθόνης",
	"TurnDisplayOffShowClock": "Απεν. οθόνης και εμφ. ρολογιού",
	"UTC0000Casablanca": "UTC Καζαμπλάνκα",
	"UTC0000CoordinatedUniversalTime": "UTC Συντον. Διεθνής Ώρα",
	"UTC0000Dublin": "UTC Δουβλ Εδιμβ Λισαβ Λονδ",
	"UTC0000Monrovia": "UTC Μονροβία, Ρέικιαβικ",
	"UTC0100Amsterdam": "UTC+01:00 Άμσ Βερ Βέρν Ρώμ ",
	"UTC0100Belgrade": "UTC+01:00 Βελιγ Μπρατ Βουδ ",
	"UTC0100Brussels": "UTC+01:00 Βρυξέλ Κοπεγχ",
	"UTC0100Sarajevo": "UTC+01:00 Σεράγ, Σκόπια",
	"UTC0100WestCentralAfrica": "UTC+01:00 Δυτι Κεντρική Αφρ.",
	"UTC0100Windhoek": "UTC+01:00 Γουίντχοκ",
	"UTC0200Athens": "UTC+02:00 Αθήνα, Βουκουρέ.",
	"UTC0200Beirut": "UTC+02:00 Βηρυτός",
	"UTC0200Cairo": "UTC+02:00 Κάιρο",
	"UTC0200Damascus": "UTC+02:00 Δαμασκός",
	"UTC0200EEurope": "UTC+02:00 Ανατολική Ευρώπη",
	"UTC0200Harare": "UTC+02:00 Χαράρε, Πραιτώρια",
	"UTC0200Helsinki": "UTC+02:00 Ελσίν, Κιβ, Ρίγα",
	"UTC0200Istanbul": "UTC+02:00 Ιστανμπούλ",
	"UTC0200Jerusalem": "UTC+02:00 Ιερουσαλήμ",
	"UTC0300Amman": "UTC+03:00 Αμμάν",
	"UTC0300Baghdad": "UTC+03:00 Βαγδάτη",
	"UTC0300Kaliningrad": "UTC+03:00 Καλίνινγκράντ",
	"UTC0300Kuwait": "UTC+03:00 Κουβέιτ, Ριάντ",
	"UTC0300Nairobi": "UTC+03:00 Ναϊρόμπι",
	"UTC0330Tehran": "UTC+03:30 Τεχεράνη",
	"UTC0400AbuDhabi": "UTC+04:00 Άμπου Νταμπι",
	"UTC0400Baku": "UTC+04:00 Μπακού",
	"UTC0400Moscow": "UTC+04:00 Μόσχ ",
	"UTC0400PortLouis": "UTC+04:00 Πορτ Λούι",
	"UTC0400Tbilisi": "UTC+04:00 Τμπίλισι",
	"UTC0400Yerevan": "UTC+04:00 Γιερεβάν",
	"UTC0430Kabul": "UTC+04:30 Καμπούλ",
	"UTC0500Islamabad": "UTC+05:00 Ισλαμαμπάντ",
	"UTC0500Tashkent": "UTC+05:00 Τασκένδη",
	"UTC0530Chennai": "UTC+05:30 Τσενάι Μουμπάι ",
	"UTC0530SriJayawardenepura": "UTC+05:30 Σρι Τζαγιαβαρν.",
	"UTC0545Kathmandu": "UTC+05:45 Κατμαντού",
	"UTC0600Astana": "UTC+06:00 Αστάνα",
	"UTC0600Dhaka": "UTC+06:00 Ντάκα",
	"UTC0600Ekaterinburg": "UTC+06:00 Εκατερίνμπεργκ",
	"UTC0630Yangon": "UTC+06:30 Γιανγκόν ",
	"UTC0700Bangkok": "UTC+07:00 Μπανγκόκ, Ανόι",
	"UTC0700Novosibirsk": "UTC+07:00 Νοβοσιμπίρσκ",
	"UTC0800Beijing": "UTC+08:00 Πεκίνο, Κονγκ",
	"UTC0800Krasnoyarsk": "UTC+08:00 Κρασνογιάρσκ",
	"UTC0800KualaLumpur": "UTC+08:00 Κουάλα Λουμπούρ",
	"UTC0800Perth": "UTC+08:00 Περθ",
	"UTC0800Taipei": "UTC+08:00 Ταϊπέι",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ουλααμπαατάρ",
	"UTC0900Irkutsk": "UTC+09:00 Ιρκούτσκ",
	"UTC0900Osaka": "UTC+09:00 Οσάκα, Τόκυο",
	"UTC0900Seoul": "UTC+09:00 Σεούλ",
	"UTC0930Adelaide": "UTC+09:30 Αδελαΐδα",
	"UTC0930Darwin": "UTC+09:30 Ντάργουιν",
	"UTC1000Brisbane": "UTC+10:00 Μπρίσμπεϊν",
	"UTC1000Canberra": "UTC+10:00 Κανμπέρα Μελβ.",
	"UTC1000Guam": "UTC+10:00 Γκουάμ",
	"UTC1000Hobart": "UTC+10:00 Χόμπαρτ",
	"UTC1000Yakutsk": "UTC+10:00 Γιάκουτσκ",
	"UTC1100SolomonIs": "UTC+11:00 Σολομόντα ",
	"UTC1100Vladivostok": "UTC+11:00 Βλαδιβοστόκ",
	"UTC1200Auckland": "UTC+12:00 Όκλαντ",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Συ. Παγκ Χρόνος",
	"UTC1200Fiji": "UTC+12:00 Φίτζι",
	"UTC1200Magadan": "UTC+12:00 Μαγκαντάν",
	"UTC1300NukuAlofa": "UTC+13:00 Νουκουαλόφα",
	"UTC1300Samoa": "UTC+13:00 Σαμόα",
	"UTCm0100Azores": "UTC-01:00 Αζόρες",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Νήσος Πράσ Ακρωτ",
	"UTCm0100Casablanca": "UTC-01:00 Καζαμπλάνκα",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Συγ. Παγκ. Χρόνος",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Συγχρ Παγκ. Χρ",
	"UTCm0200MidAtlantic": "UTC-02:00 Μέση Ατλαντική",
	"UTCm0300Brasilia": "UTC-03:00 Μπραζίλια",
	"UTCm0300BuenosAires": "UTC-03:00 Μπουένος Άιρες",
	"UTCm0300Cayenne": "UTC-03:00 Καγιέν, Φορταλέζα",
	"UTCm0300Greenland": "UTC-03:00 Γροιλανδία",
	"UTCm0300Montevideo": "UTC-03:00 Μοντεβιντέο",
	"UTCm0300Salvador": "UTC-03:00 Σαλβαντόρ",
	"UTCm0330Newfoundland": "UTC-03:00 Νιουφάουντλαντ",
	"UTCm0400Asuncion": "UTC-04:00 Ασουνσιόν",
	"UTCm0400AtlanticTime": "UTC-04:00 Ατλαντική ώρα ",
	"UTCm0400Cuiaba": "UTC-04:00 Κουιάμπα",
	"UTCm0400Georgetown": "UTC-04:00 Τζορτζτν Παζ Μαν ",
	"UTCm0400Santiago": "UTC-04:00 Σαντιάγκο",
	"UTCm0430Caracas": "UTC-04:30 Καράκας",
	"UTCm0500Bogota": "UTC-05:00 Μπογκοτά, Λίμα",
	"UTCm0500EasternTime": "UTC-05:00 Ανατολ Ώρα ",
	"UTCm0500Indiana": "UTC-05:00 Ινδιάνα ",
	"UTCm0600CentralAmerica": "UTC-06:00 Κεντρική Αμερική",
	"UTCm0600CentralTime": "UTC-06:00 Κεντρ ώρα ",
	"UTCm0600Guadalajara": "UTC-06:00 Γουαδαλαχ Μέξικο ",
	"UTCm0600Saskatchewan": "UTC-06:00 Σάσκετσουάν",
	"UTCm0700Arizona": "UTC-07:00 Αριζόνα",
	"UTCm0700Chihuahua": "UTC-07:00 Τσιουάουα Λα Παζ ",
	"UTCm0700MountainTime": "UTC-07:00 Ορεινή ώρα ",
	"UTCm0800BajaCalifornia": "UTC-08:00 Μπάχα Καλιφόρνια",
	"UTCm0800PacificTime": "UTC-08:00 Ειρην ΗΠΑ Καν.",
	"UTCm0900Alaska": "UTC-09:00 Αλάσκα",
	"UTCm1000Hawaii": "UTC-10:00 Χαβάη",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Συγ. Παγκ Χρόνος",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Γραμμ Ημ Δύση",
	"UseUKEng_Taiw_Braz_Cant_Text": "Τα {languageID} είναι γλώσσα προβολής μόνο. Για εντολές στα {languageID} και χωρίς Φωνή: Όχι. Για φωνή και εντολές στα {languageVRTTSID}:Ναι.",
	"UseUKEnglishText": "Τα {languageID} είναι Μόνο η γλώσσα Εμφάνισης. Για μηνύματα σε {languageID} και χωρίς φωνή: “Όχι”  Για Φωνή και Μηνύματα στα Αγγλικά: “Ναι”",
	"VRUK": "Η τρέχουσα επιλογή γλώσσας δεν υποστηρίζει αναγνώριση φωνής.",
	"VRVolume": "VR και ήχος κλ.",
	"VRVolumeTTS": "Η φωνητική καθοδήγηση θα είναι σ' αυτή την ένταση ήχου",
	"VersionInfo": "Στοιχεία έκδοσης",
	"_12h": "12 ώ.",
	"_24h": "24 ώ.",
};

framework.registerAppDictLoaded("syssettings", "el_GR");