var Localization_syssettingsAppDict_ru_RU = {
	//"stringId" : "localString"
	"About": "О программе",
	"AdjustTime": "Настроить часы",
	"AgreementsAndDisclaimers": "Соглашения и отказ от ответственности",
	"AgreementsDisclaimersText": "Полный список лицензий, а также информацию об авторских правах можно найти на сайте www.MazdaEndUserAgreements-Copyrights.com.",
	"Auto": "Авто",
	"Bluetooth": "Bluetooth",
	"Brightness": "Яркость",
	"Celsius": "°C",
	"ChooseLanguage": "Выберите язык",
	"Clock": "Часы",
	"Communication": "Связь",
	"CommunicationResetConfText": "Вы действительно хотите выполнить возврат к завод. настройкам связи?",
	"CommunicationResetErrorRetryText": "Ошибка при возврате к заводским настройкам связи. Хотите попробовать еще раз?",
	"CommunicationResetProgressText": "Возвр. к заводск. настр-кам связи",
	"ContactsSortOrder": "Порядок сортировки контактов",
	"ContactsSortOrderTitle": "Сорт-ка контактов",
	"Contrast": "Контраст",
	"Day": "День",
	"DayLightSavingsTime": "Летнее время",
	"Display": "Дисплей",
	"DisplayResetConfText": "Вы действительно хотите выполнить возврат к настройкам дисплея по умолчанию?",
	"DisplayResetErrorText": "Ошибка при возврате к заводским настройкам дисплея. Хотите попробовать еще раз?",
	"DisplayResetProgressText": "Возвр. к заводск. настр-кам дисплея",
	"Distance": "Расстояние",
	"DownloadCallContacts": "Автоматическая загрузка контактов",
	"DownloadCallEmail": "Автоматическая загрузка эл. почты",
	"DownloadCallHistory": "Автозагрузка истории вызовов",
	"DownloadCallText": "Автоматическая загрузка SMS",
	"Eastern": "Вост.",
	"EditPresetMessage": "Ред.стандарт.сообщ.",
	"EmailNotifications": "Email уведомления",
	"EmailSmsNotifications": "Уведомления по эл. почте/SMS",
	"FactoryReset": "Возврат к завод. настройкам",
	"FactoryResetConfText": "Вы хотите вернуться к заводским настройкам? (Будет выполнен возврат системы к заводским настройкам)",
	"FactoryResetErrorText": "Ошибка при возврате к заводским настройкам. Хотите попробовать еще раз?",
	"FactoryResetProgressText": "Возврат к заводским настройкам",
	"Fahrenheit": "°F",
	"FirstLast": "Имя, фамилия",
	"Fixed": "Фикс.",
	"GPSSync": "Синхронизация GPS",
	"Inband": "Встр.",
	"IncomingCallNotifications": "Уведомления о входящих вызовах",
	"Kilometers": "км",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Шестнадцатиричный",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Числовой",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Язык",
	"LanguageChangeErrorText": "Ошибка при изменении языка. Хотите попробовать еще раз?",
	"LanguageChangeProgressText": "Изменение языка",
	"LanguageChangeSuccess": "Язык изменен на {languageID}",
	"LanguageConfText": "Вы действительно хотите изменить язык на {languageID}?",
	"LanguageConfTextNoVR": " {languageID} - это исключительно язык отображения интерфейса. Для голосовых функций будет использован английский. Изменить язык интерфейса на {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": " {languageID} - это исключительно язык отображения интерфейса. Для голосовых функций будет использован {VRlanguageID}. Изменить язык интерфейса на {languageID}?",
	"LastFirst": "Фамилия, имя",
	"Miles": "ми",
	"Mobile911": "Телефон 112",
	"Mobile911Description": "В полож-и вкл., автом-ль при аварии автоматически позвонит 112.",
	"Mode": "Режим",
	"MusicDatabaseUpdate": "Обновление муз. базы данных",
	"NaviVolumeTTS": "Для Навигации будет установлен данный уровень громкости.",
	"NetworkManagement": "Управление сетевыми соединениями",
	"Night": "Ночь",
	"PhoneVolume": "Громк. телефона",
	"PresetBeThereTen": "Буду через 10 минут.",
	"PresetBeThereTwenty": "Буду через 20 минут.",
	"PresetCallLater": "Перезвоню позже.",
	"PresetCantTalk": "Не могу сейчас разговаривать.",
	"PresetDriving": "Я сейчас за рулем.",
	"PresetMessages": "Стандартные сообщения",
	"PresetMessagesTitle": "Стандартные сообщения",
	"PresetNeedMore": "Мне необходимы дополнит. указания.",
	"PresetNo": "Нет",
	"PresetOk": "OK",
	"PresetPleaseCall": "Перезвоните мне.",
	"PresetStuck": "Стою в пробке.",
	"PresetThanks": "Спасибо!",
	"PresetWhere": "Где вы?",
	"PresetWhy": "Почему?",
	"PresetYes": "Да",
	"Recent": "Недавние",
	"Reset": "Сброс",
	"Ringtone": "Рингтон",
	"RingtoneVolumeTTS": "Для телефонных вызовов будет установлен данный уровень громкости",
	"SMSNotifications": "SMS уведомления",
	"Safety": "Безопас.",
	"SelectKBLang": "Выбрать клавиатуру",
	"SelectTimeZone": "Выберите часовой пояс",
	"SetClockHrsMinus": "Уменьш.знач.час.",
	"SetClockHrsPlus": "Увелич.знач.час.",
	"SetClockMinMinus": "Уменьш.знач.мин.",
	"SetClockMinPlus": "Увелич.знач.мин.",
	"Settings": "Настройки",
	"SystemSettings": "Сист. настройки",
	"Temp": "Температура ",
	"TimeFormat": "Формат времени",
	"TimeZoneSelect": "Выбор часового пояса",
	"ToolTips": "Всплывающие подсказки",
	"TurnDisplayOff": "Выключить дисплей",
	"TurnDisplayOffShowClock": "Выкл. дисплей и отобр. часы",
	"UTC0000Casablanca": "UTC Касабланка",
	"UTC0000CoordinatedUniversalTime": "UTC-01:00 Всем. коорд. время",
	"UTC0000Dublin": "UTC Лондон,  Дублин",
	"UTC0000Monrovia": "UTC Монровия, Рейкьявик",
	"UTC0100Amsterdam": "UTC+01:00 Амстердам, Берлин",
	"UTC0100Belgrade": "UTC+01:00 Белград, Прага",
	"UTC0100Brussels": "UTC+01:00 Брюссель, Мадрид",
	"UTC0100Sarajevo": "UTC+01:00 Саравео, Скопье",
	"UTC0100WestCentralAfrica": "UTC+01:00 Запад Центр.Афр.",
	"UTC0100Windhoek": "UTC+01:00 Виндхук",
	"UTC0200Athens": "UTC+02:00 Афины, Бухарест",
	"UTC0200Beirut": "UTC+02:00 Бейрут",
	"UTC0200Cairo": "UTC+02:00 Каир",
	"UTC0200Damascus": "UTC+02:00 Дамаск",
	"UTC0200EEurope": "UTC+02:00 Вост. Европа",
	"UTC0200Harare": "UTC+02:00 Хараре, Претория",
	"UTC0200Helsinki": "UTC+02:00 Хельсинки, Киев",
	"UTC0200Istanbul": "UTC+02:00 Стамбул",
	"UTC0200Jerusalem": "UTC+02:00 Иерусалим",
	"UTC0300Amman": "UTC+03:00 Амман",
	"UTC0300Baghdad": "UTC+03:00 Багдад",
	"UTC0300Kaliningrad": "UTC+03:00 Калининград",
	"UTC0300Kuwait": "UTC+03:00 Кувейт, Рияд",
	"UTC0300Nairobi": "UTC+03:00 Найроби",
	"UTC0330Tehran": "UTC+03:30 Тегеран",
	"UTC0400AbuDhabi": "UTC+04:00 Абу Даби, Маскат",
	"UTC0400Baku": "UTC+04:00 Баку",
	"UTC0400Moscow": "UTC+04:00 Москва",
	"UTC0400PortLouis": "UTC+04:00 Порт-Луи",
	"UTC0400Tbilisi": "UTC+04:00 Тбилиси",
	"UTC0400Yerevan": "UTC+04:00 Ереван",
	"UTC0430Kabul": "UTC+04:30 Кабул",
	"UTC0500Islamabad": "UTC+05:00 Исламабад, Карачи",
	"UTC0500Tashkent": "UTC+05:00 Ташкент",
	"UTC0530Chennai": "UTC+05:30 Калькутта, Мумбаи",
	"UTC0530SriJayawardenepura": "UTC+05:30 Шри-Джаявард",
	"UTC0545Kathmandu": "UTC+05:45 Катманду",
	"UTC0600Astana": "UTC+06:00 Астана",
	"UTC0600Dhaka": "UTC+06:00 Дакка",
	"UTC0600Ekaterinburg": "UTC+06:00 Екатеринбург",
	"UTC0630Yangon": "UTC+06:30 Янгон (Рангун)",
	"UTC0700Bangkok": "UTC+07:00 Бангкок, Джакарт",
	"UTC0700Novosibirsk": "UTC+07:00 Новосибирск",
	"UTC0800Beijing": "UTC+08:00 Гонконг, Пекин",
	"UTC0800Krasnoyarsk": "UTC+08:00 Красноярск",
	"UTC0800KualaLumpur": "UTC+08:00 Куала Лумпур",
	"UTC0800Perth": "UTC+08:00 Перт",
	"UTC0800Taipei": "UTC+08:00 Тайбэй",
	"UTC0800Ulaanbaatar": "UTC+08:00 Улан-Батор",
	"UTC0900Irkutsk": "UTC+09:00 Иркутск",
	"UTC0900Osaka": "UTC+09:00 Осака, Токио",
	"UTC0900Seoul": "UTC+09:00 Сеул",
	"UTC0930Adelaide": "UTC+09:30 Аделаида",
	"UTC0930Darwin": "UTC+09:30 Дарвин",
	"UTC1000Brisbane": "UTC+10:00 Брисбейн",
	"UTC1000Canberra": "UTC+10:00 Канберра",
	"UTC1000Guam": "UTC+10:00 Гуам, Порт-Морсби",
	"UTC1000Hobart": "UTC+10:00 Хобарт",
	"UTC1000Yakutsk": "UTC+10:00 Якутск",
	"UTC1100SolomonIs": "UTC+11:00 Соломоновы о-ва",
	"UTC1100Vladivostok": "UTC+11:00 Владивосток",
	"UTC1200Auckland": "UTC+12:00 Окленд",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00  Всем. коорд. время +12",
	"UTC1200Fiji": "UTC+12:00 Фиджи",
	"UTC1200Magadan": "UTC+12:00 Магадан",
	"UTC1300NukuAlofa": "UTC+13:00 Нукуалофа",
	"UTC1300Samoa": "UTC+13:00 Самоа",
	"UTCm0100Azores": "UTC-01:00 Азорские острова",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Кабо-Верде",
	"UTCm0100Casablanca": "UTC-01:00 Касабланка",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Время по Гринвичу",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Всем. коорд. время -02",
	"UTCm0200MidAtlantic": "UTC-02:00 Среднеатлантичес.",
	"UTCm0300Brasilia": "UTC-03:00 Бразилиа",
	"UTCm0300BuenosAires": "UTC-03:00 Буэнос-Айрес",
	"UTCm0300Cayenne": "UTC-03:00 Кайенна",
	"UTCm0300Greenland": "UTC-03:00 Гренландия",
	"UTCm0300Montevideo": "UTC-03:00 Монтевидео",
	"UTCm0300Salvador": "UTC-03:00 Сальвадор",
	"UTCm0330Newfoundland": "UTC-03:30 Ньюфаундленд",
	"UTCm0400Asuncion": "UTC-04:00 Асунсьон",
	"UTCm0400AtlanticTime": "UTC-04:00 Атлант. время (Канада)",
	"UTCm0400Cuiaba": "UTC-04:00 Куяба",
	"UTCm0400Georgetown": "UTC-04:00 Джорджтаун",
	"UTCm0400Santiago": "UTC-04:00 Сантьяго",
	"UTCm0430Caracas": "UTC-04:30 Каракас",
	"UTCm0500Bogota": "UTC-05:00 Богота, Лима, Кито",
	"UTCm0500EasternTime": "UTC-05:00 Восточн.время (США)",
	"UTCm0500Indiana": "UTC-05:00 Индиана восточная",
	"UTCm0600CentralAmerica": "UTC-06:00 Централ. Америка",
	"UTCm0600CentralTime": "UTC-06:00 Центр.время (США)",
	"UTCm0600Guadalajara": "UTC-06:00 Гвадалахара",
	"UTCm0600Saskatchewan": "UTC-06:00 Саскачеван",
	"UTCm0700Arizona": "UTC-07:00 Аризона",
	"UTCm0700Chihuahua": "UTC-07:00 Чиуауа, Ла-Пас",
	"UTCm0700MountainTime": "UTC-07:00 Горное время (США)",
	"UTCm0800BajaCalifornia": "UTC-08:00 Нижняя Калифорн.",
	"UTCm0800PacificTime": "UTC-08:00 Тихоок.время (США)",
	"UTCm0900Alaska": "UTC-09:00 Аляска",
	"UTCm1000Hawaii": "UTC-10:00 Гавайи",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Всем. коорд. время",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 линия смены дат ",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} является языком только для отображения. Для подсказок на языке {languageID} без голоса: нет. Для голоса без подсказок на языке {languageVRTTSID}: да.",
	"UseUKEnglishText": "{languageID} - это исключительно язык отображения. Для подсказок {languageID} без голоса: Нет. Для подсказок на английском с голосом: Да",
	"VRUK": "Распознавание голоса не поддерживается для выбранного языка.",
	"VRVolume": "Громк. подсказ. ",
	"VRVolumeTTS": "Для голосовых подсказок будет установлен данный уровень громкости",
	"VersionInfo": "Информация о версии",
	"_12h": "12 ч.",
	"_24h": "24 ч.",
};

framework.registerAppDictLoaded("syssettings", "ru_RU");