var Localization_syssettingsAppDict_tr_TR = {
	//"stringId" : "localString"
	"About": "Hakkında",
	"AdjustTime": "Saati Ayarla",
	"AgreementsAndDisclaimers": "Sözleşmeler ve Feragatnameler",
	"AgreementsDisclaimersText": "Lisans ve telif hakkı bildirimlerinin tam listesi için www.MazdaEndUserAgreements-Copyrights.com adresini ziyaret edin.",
	"Auto": "Oto.",
	"Bluetooth": "Bluetooth",
	"Brightness": "Parlaklık",
	"Celsius": "°C",
	"ChooseLanguage": "Dil Seç",
	"Clock": "Saat",
	"Communication": "İletişim",
	"CommunicationResetConfText": "İletişim ayarlarını varsayılan fabrika ayarlarına geri almak istediğinizden emin misiniz?",
	"CommunicationResetErrorRetryText": "İletişim ayarları varsayılan fabrika ayarlarına geri alınırken hata oluştu. Yeniden denemek ister misiniz?",
	"CommunicationResetProgressText": "İletişim ayarları fabirka ayarlarına alınıyor",
	"ContactsSortOrder": "Bağlantı Sıralama Sırası",
	"ContactsSortOrderTitle": "Bağlantı Sıralama Sırası",
	"Contrast": "Kontrast",
	"Day": "Gün",
	"DayLightSavingsTime": "Yaz Saati",
	"Display": "Ekran",
	"DisplayResetConfText": "Ekran ayarlarını varsayılan fabrika ayarlarına geri almak istediğinizden emin misiniz?",
	"DisplayResetErrorText": "Ekran ayarları varsayılan fabrika ayarlarına geri alınırken hata oluştu. Yeniden denemek ister misiniz?",
	"DisplayResetProgressText": "Ekran fabrika ayarlarına geri alınıyor",
	"Distance": "Mesafe",
	"DownloadCallContacts": "Bağlantıları Otomatik İndir",
	"DownloadCallEmail": "E-postayı Otomatik İndir",
	"DownloadCallHistory": "Çağrı Geçmişini Otomatik İndir",
	"DownloadCallText": "SMS Otomatik İndir",
	"Eastern": "Doğu",
	"EditPresetMessage": "Önyr Msj Dznle",
	"EmailNotifications": "E-posta Bildirimleri",
	"EmailSmsNotifications": "E-posta/SMS Bildirimleri",
	"FactoryReset": "Fabrika Sıfırlama",
	"FactoryResetConfText": "Tüm ayarları varsayılan fabrika ayarlarına geri almak istediğinizden emin misiniz? (Sistem, başarılı bir fabrika sıfırlamasından sonra yeniden başlatılır.)",
	"FactoryResetErrorText": "Ayarları varsayılan fabrika ayarlarına geri alınırken hata oluştu. Yeniden denemek ister misiniz?",
	"FactoryResetProgressText": "Ayarlar vars. Fab. ayarlarına geri alınıyor",
	"Fahrenheit": "°F",
	"FirstLast": "Adı, Soyadı",
	"Fixed": "Sabit",
	"GPSSync": "GPS Senk.",
	"Inband": "A. Içi",
	"IncomingCallNotifications": "Gelen Çağrı Bildirimleri",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių   (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "On altı tabanlı",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Nümerik",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Dil",
	"LanguageChangeErrorText": "Dil değiştirilirken hata oluştu. Yeniden denemek ister misiniz?",
	"LanguageChangeProgressText": "Dil Değiştiriliyor",
	"LanguageChangeSuccess": "Dil {languageID} olarak değiştirildi",
	"LanguageConfText": "Dili {languageID} olarak değiştirmek istediğinizden emin misiniz?",
	"LanguageConfTextNoVR": "{languageID} Yalnızca Görüntüleme dilidir. Ses işlevleri için Birleşik Krallık İngilizcesi kullanılacak. Görüntüleme dili {languageID} olarak değiştirilsin mi?",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} Yalnızca Görüntüleme dilidir. Ses işlevleri için {VRlanguageID} kullanılacak. Görüntüleme dili {languageID} olarak değiştirilsin mi?",
	"LastFirst": "Soyadı, Adı",
	"Miles": "mi",
	"Mobile911": "Mobil 112",
	"Mobile911Description": "Açık konumdayken, araç bir kaza durumunda otomatik olarak 112'yi arayacaktır.",
	"Mode": "Mod",
	"MusicDatabaseUpdate": "Müzik Veritabanı Güncelleme",
	"NaviVolumeTTS": "Navigasyon bu ses seviyesinde gerçekleşecek.",
	"NetworkManagement": "Ağ Yönetimi",
	"Night": "Gece",
	"PhoneVolume": "Tel. Ses Seviyesi",
	"PresetBeThereTen": "10 dakika içerisinde orada olacağım.",
	"PresetBeThereTwenty": "20 dakika içerisinde orada olacağım.",
	"PresetCallLater": "Daha sonra ara.",
	"PresetCantTalk": "Şu anda konuşamıyorum.",
	"PresetDriving": "Şu anda araç kullanıyorum.",
	"PresetMessages": "Ayarlı Mesajlar",
	"PresetMessagesTitle": "Ayarlı Mesajlar",
	"PresetNeedMore": "Daha fazla yön tarifine ihtiyacım var.",
	"PresetNo": "Hayır",
	"PresetOk": "U redu",
	"PresetPleaseCall": "Lütfen, ara beni.",
	"PresetStuck": "Trafikte sıkıştım.",
	"PresetThanks": "Teşekkürler!",
	"PresetWhere": "Neredesin?",
	"PresetWhy": "Neden?",
	"PresetYes": "Evet",
	"Recent": "En Son",
	"Reset": "Sıfırla",
	"Ringtone": "Zil Sesi Tonu",
	"RingtoneVolumeTTS": "Telefon çağrısı bu ses seviyesinde gerçekleşecek",
	"SMSNotifications": "SMS Bildirimleri",
	"Safety": "Güvenlik",
	"SelectKBLang": "Klavye Seç",
	"SelectTimeZone": "Zaman Dilimi Seçin",
	"SetClockHrsMinus": "Saati Azalt",
	"SetClockHrsPlus": "Saati Arttır",
	"SetClockMinMinus": "Dakikayı Azalt",
	"SetClockMinPlus": "Dakikayı Arttır",
	"Settings": "Ayarlar",
	"SystemSettings": "Sistem Ayarları",
	"Temp": "Sıcaklık",
	"TimeFormat": "Saat Formatı",
	"TimeZoneSelect": "Zaman Dilimi Seçimi",
	"ToolTips": "Araç İpuçları",
	"TurnDisplayOff": "Ekranı KAPAT",
	"TurnDisplayOffShowClock": "Ekranı KAPAT ve Saati Göster",
	"UTC0000Casablanca": "UTC Kazablanka",
	"UTC0000CoordinatedUniversalTime": "UTC Koordinatlı Evrensel Saat",
	"UTC0000Dublin": "UTC Dublin, Edinburgh, Londra",
	"UTC0000Monrovia": "UTC Monrovia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Amsterdam,Roma",
	"UTC0100Belgrade": "UTC+01:00 Budapeşte, Ljubjana",
	"UTC0100Brussels": "UTC+01:00 Brüksel,Madrid,Paris",
	"UTC0100Sarajevo": "UTC+01:00 Sarajevo,Zagreb",
	"UTC0100WestCentralAfrica": "UTC+01:00 Batı Orta Afrika",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Atina, Bükreş",
	"UTC0200Beirut": "UTC+02:00 Beyrut",
	"UTC0200Cairo": "UTC+02:00 Kahire",
	"UTC0200Damascus": "UTC+02:00 Şam",
	"UTC0200EEurope": "UTC+02:00 D. Avrupa",
	"UTC0200Harare": "UTC+02:00 Harare, Pretoria",
	"UTC0200Helsinki": "UTC+02:00 Riga,Sofya,Vilnius",
	"UTC0200Istanbul": "UTC+02:00 İstanbul",
	"UTC0200Jerusalem": "UTC+02:00 Kudüs",
	"UTC0300Amman": "UTC+03:00 Amman",
	"UTC0300Baghdad": "UTC+03:00 Bağdat",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuveyt, Riyadh",
	"UTC0300Nairobi": "UTC+03:00 Nairobi",
	"UTC0330Tehran": "UTC+03:30 Tahran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Muscat",
	"UTC0400Baku": "UTC+04:00 Bakü",
	"UTC0400Moscow": "UTC+04:00 St. Petersburg",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tiflis",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Kabil",
	"UTC0500Islamabad": "UTC+05:00 İslamabad, Karaçi",
	"UTC0500Tashkent": "UTC+05:00 Taşkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayaward.",
	"UTC0545Kathmandu": "UTC+05:45 Katmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bangkok, Hanoi",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Beijing, Hong Kong",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 Kuala Lumpur",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulan Batur",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokyo",
	"UTC0900Seoul": "UTC+09:00 Seul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Melbourne, Sydney",
	"UTC1000Guam": "UTC+10:00 Moresby Limanı",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Solomon Adaları",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland,Wellington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Koor. Küresel Saat",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azorlar",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Cape Verde Adası",
	"UTCm0100Casablanca": "UTC-01:00 Kazablanka",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Koord. Evrnsl. Saat",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Koor.ı Evrensel Saat",
	"UTCm0200MidAtlantic": "UTC-02:00 Orta Atlantik",
	"UTCm0300Brasilia": "UTC-03:00 Brezilya",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Cayenne, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Grönland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Newfoundland",
	"UTCm0400Asuncion": "UTC-04:00 Asuncion",
	"UTCm0400AtlanticTime": "UTC-04:00 Atlantik Saati ",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiaba",
	"UTCm0400Georgetown": "UTC-04:00 Georgetown,La Paz",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Doğu Saati ",
	"UTCm0500Indiana": "UTC-05:00 Hindistan (Doğu)",
	"UTCm0600CentralAmerica": "UTC-06:00 Orta Amerika",
	"UTCm0600CentralTime": "UTC-06:00 Orta Bölge Saati ",
	"UTCm0600Guadalajara": "UTC-06:00 Guadalajara,Meksiko",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua, La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Dağ Saati ",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja California",
	"UTCm0800PacificTime": "UTC-08:00 Pasifik Saati ",
	"UTCm0900Alaska": "UTC-09:00 Alaska",
	"UTCm1000Hawaii": "UTC-10:00 Hawaii",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Koordinatlı Evr. Saat",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Ulus. Tarih Çizgisi Ba.",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID}, Yalnızca Ekran dilidir. {languageID} komutları ve Ses yok için: Hayır. {languageVRTTSID} dilindeki Ses ve Komutlar için: Evet.",
	"UseUKEnglishText": "{languageID} Yalnızca Görüntüleme dilidir. {languageID} uyarılar ve Sessiz mod için“Hayır” İngilizce Ses ve Uyarılar için: “Evet”",
	"VRUK": "Mevcut dil seçimi, ses algılama özelliğini desteklemiyor.",
	"VRVolume": "VR ve Zil Sesi",
	"VRVolumeTTS": "Sesli kılavuz bu ses seviyesinde gerçekleşecek",
	"VersionInfo": "Sürüm bilgisi",
	"_12h": "12sa",
	"_24h": "24sa",
};

framework.registerAppDictLoaded("syssettings", "tr_TR");