var Localization_syssettingsAppDict_en_AU = {
	//"stringId" : "localString"
	"About": "About",
	"AdjustTime": "Adjust Time",
	"AgreementsAndDisclaimers": "Agreements and Disclaimers",
	"AgreementsDisclaimersText": "Please go to www.MazdaEndUserAgreements-Copyrights.com for a complete list license and copyright disclosures.",
	"Auto": "Auto",
	"Bluetooth": "Bluetooth",
	"Brightness": "Brightness",
	"Celsius": "°C",
	"ChooseLanguage": "Choose Language",
	"Clock": "Clock",
	"Communication": "Communication",
	"CommunicationResetConfText": "Are you sure you want to revert Communication settings to their default values?",
	"CommunicationResetErrorRetryText": "Error reverting Communication settings to factory defaults. Would you like to retry?",
	"CommunicationResetProgressText": "Reverting Communication settings",
	"ContactsSortOrder": "Contact Sort Order",
	"ContactsSortOrderTitle": "Contacts Sort Order",
	"Contrast": "Contrast",
	"Day": "Day",
	"DayLightSavingsTime": "Daylight Savings Time",
	"Display": "Display",
	"DisplayResetConfText": "Are you sure you want to revert Display settings to their default values?",
	"DisplayResetErrorText": "Error reverting Display settings to factory defaults. Would you like to retry?",
	"DisplayResetProgressText": "Restoring Display settings",
	"Distance": "Distance",
	"DownloadCallContacts": "Auto Download Contacts",
	"DownloadCallEmail": "Auto  Download Email",
	"DownloadCallHistory": "Auto Download Call History",
	"DownloadCallText": "Auto Download SMS",
	"Eastern": "Eastern",
	"EditPresetMessage": "Edit Preset Message",
	"EmailNotifications": "Email Notifications",
	"EmailSmsNotifications": "Email/SMS Notifications",
	"FactoryReset": "Factory Reset",
	"FactoryResetConfText": "Are you sure you want to revert all settings to their factory default? (System will reboot on successful factory reset.)",
	"FactoryResetErrorText": "Error reverting settings to factory defaults. Would you like to retry?",
	"FactoryResetProgressText": "Reverting settings to factory defaults",
	"Fahrenheit": "°F",
	"FirstLast": "First Name, Last Name",
	"Fixed": "Fixed",
	"GPSSync": "GPS Sync",
	"Inband": "Phone",
	"IncomingCallNotifications": "Incoming Call Notifications",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Hexadecimal",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Numeric",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Language",
	"LanguageChangeErrorText": "Error changing language. Would you like to retry?",
	"LanguageChangeProgressText": "Changing Language",
	"LanguageChangeSuccess": "Language changed to {languageID}",
	"LanguageConfText": "Are you sure you want to change the language to {languageID}?",
	"LanguageConfTextNoVR": " {languageID} is a Display Only language. UK English will be used for voice functions. Change display language to  {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": " {languageID} is a Display Only language. {VRlanguageID} will be used for voice functions. Change display language to  {languageID}?",
	"LastFirst": "Last Name, First Name",
	"Miles": "mi",
	"Mobile911": "Mobile 000",
	"Mobile911Description": "When On, the vehicle will automatically make a 000 call after an accident.",
	"Mode": "Mode",
	"MusicDatabaseUpdate": "Music Database Update",
	"NaviVolumeTTS": "Navigation will be at this volume.",
	"NetworkManagement": "Network Management",
	"Night": "Night",
	"PhoneVolume": "Phone Volume",
	"PresetBeThereTen": "Be there in 10 minutes.",
	"PresetBeThereTwenty": "Be there in 20 minutes.",
	"PresetCallLater": "Call you later.",
	"PresetCantTalk": "Can’t talk now.",
	"PresetDriving": "Driving now.",
	"PresetMessages": "Preset Messages",
	"PresetMessagesTitle": "Preset Messages",
	"PresetNeedMore": "I need more directions.",
	"PresetNo": "No",
	"PresetOk": "OK",
	"PresetPleaseCall": "Please call me.",
	"PresetStuck": "Stuck in traffic.",
	"PresetThanks": "Thanks!",
	"PresetWhere": "Where are you?",
	"PresetWhy": "Why?",
	"PresetYes": "Yes",
	"Recent": "Recent",
	"Reset": "Reset",
	"Ringtone": "Ringtone",
	"RingtoneVolumeTTS": "Phone call will be at this volume",
	"SMSNotifications": "SMS Notifications",
	"Safety": "Safety",
	"SelectKBLang": "Select Keyboard",
	"SelectTimeZone": "Select Time Zone",
	"SetClockHrsMinus": "Decrease Hours",
	"SetClockHrsPlus": "Increase Hours",
	"SetClockMinMinus": "Decrease Minutes",
	"SetClockMinPlus": "Increase Minutes",
	"Settings": "Settings",
	"SystemSettings": "System Settings",
	"Temp": "Temperature ",
	"TimeFormat": "Time Format",
	"TimeZoneSelect": "Time Zone Select",
	"ToolTips": "Tool Tips",
	"TurnDisplayOff": "Turn Display Off",
	"TurnDisplayOffShowClock": "Turn Display Off and Show Clock",
	"UTC0000Casablanca": "UTC Casablanca",
	"UTC0000CoordinatedUniversalTime": "UTC Coord. Universal Time",
	"UTC0000Dublin": "UTC Dublin, Edinburgh, London",
	"UTC0000Monrovia": "UTC Monrovia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Amsterdam, Rome",
	"UTC0100Belgrade": "UTC+01:00 Belgrade, Budapest",
	"UTC0100Brussels": "UTC+01:00 Brussels,Madrid,Paris",
	"UTC0100Sarajevo": "UTC+01:00 Sarajevo, Warsaw",
	"UTC0100WestCentralAfrica": "UTC+01:00 West Central Afr.",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Athens, Bucharest",
	"UTC0200Beirut": "UTC+02:00 Beirut",
	"UTC0200Cairo": "UTC+02:00 Cairo",
	"UTC0200Damascus": "UTC+02:00 Damascus",
	"UTC0200EEurope": "UTC+02:00 E. Europe",
	"UTC0200Harare": "UTC+02:00 Harare, Pretoria",
	"UTC0200Helsinki": "UTC+02:00 Helsinki, Kyiv, Riga",
	"UTC0200Istanbul": "UTC+02:00 Istanbul",
	"UTC0200Jerusalem": "UTC+02:00 Jerusalem",
	"UTC0300Amman": "UTC+03:00 Amman",
	"UTC0300Baghdad": "UTC+03:00 Baghdad",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuwait, Riyadh",
	"UTC0300Nairobi": "UTC+03:00 Nairobi",
	"UTC0330Tehran": "UTC+03:30 Tehran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Muscat",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Moscow,Volgograd",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Kabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karachi",
	"UTC0500Tashkent": "UTC+05:00 Tashkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai, New Delhi",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayawarden.",
	"UTC0545Kathmandu": "UTC+05:45 Kathmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bangkok, Jakarta",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Beijing, Hong Kong",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 Kuala Lumpur",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulaanbaatar",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokyo",
	"UTC0900Seoul": "UTC+09:00 Seoul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Canberra,Sydney",
	"UTC1000Guam": "UTC+10:00 Guam,Port Moresby",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Solomon Is.",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland,Wellington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Coord. Univ. Time",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azores",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Cape Verde Is.",
	"UTCm0100Casablanca": "UTC-01:00 Casablanca",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Coord. Univ. Time",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Coord. Univ. Time",
	"UTCm0200MidAtlantic": "UTC-02:00 Mid-Atlantic",
	"UTCm0300Brasilia": "UTC-03:00 Brasilia",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Cayenne, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Greenland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Newfoundland",
	"UTCm0400Asuncion": "UTC-04:00 Asuncion",
	"UTCm0400AtlanticTime": "UTC-04:00 Atlantic T. (Can.)",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiaba",
	"UTCm0400Georgetown": "UTC-04:00 Georgetown",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Eastern T. (US/Can.)",
	"UTCm0500Indiana": "UTC-05:00 Indiana (East)",
	"UTCm0600CentralAmerica": "UTC-06:00 Central America",
	"UTCm0600CentralTime": "UTC-06:00 Central T. (US/Can.)",
	"UTCm0600Guadalajara": "UTC-06:00 Mexico City, Mont.",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua, La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Mt. Time (US/Can.)",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja California",
	"UTCm0800PacificTime": "UTC-08:00 Pac. Time (US/Can.)",
	"UTCm0900Alaska": "UTC-09:00 Alaska",
	"UTCm1000Hawaii": "UTC-10:00 Hawaii",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Coord. Univ. Time-11",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Int. Date Ln. West",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} is a Display Only language. For {languageID} prompts and no Voice: No. For Voice and Prompts in {languageVRTTSID}:Yes.",
	"UseUKEnglishText": "{languageID} is a Display Only language. For {languageID} prompts and no Voice: No. For Voice and Prompts in English: Yes.",
	"VRUK": "The current language selection does not support Voice Recognition.",
	"VRVolume": "VR and Ringtone",
	"VRVolumeTTS": "Voice guidance will be at this volume",
	"VersionInfo": "Version Information",
	"_12h": "12h",
	"_24h": "24h",
};

framework.registerAppDictLoaded("syssettings", "en_AU");