var Localization_syssettingsAppDict_sv_SE = {
	//"stringId" : "localString"
	"About": "Om",
	"AdjustTime": "Ställ in klockan",
	"AgreementsAndDisclaimers": "Godkännanden och friskrivningar",
	"AgreementsDisclaimersText": "Gå till www.MazdaEndUserAgreements-Copyrights.com för komplett lista med licens- och copyrightnoteringar.",
	"Auto": "Auto",
	"Bluetooth": "Bluetooth",
	"Brightness": "Ljusstyrka",
	"Celsius": "°C",
	"ChooseLanguage": "Välj språk",
	"Clock": "Klocka",
	"Communication": "Kommunikation",
	"CommunicationResetConfText": "Vill du verkligen återställa kommunikationsinställningarna till standardvärden?",
	"CommunicationResetErrorRetryText": "Fel vid återställning av kommunikationsinställningarna till fabriksinställning. Vill du prova igen?",
	"CommunicationResetProgressText": "Återställer kom-inställn. till standard.",
	"ContactsSortOrder": "Sorteringsordning för kontakter",
	"ContactsSortOrderTitle": "Sorteringsordn för kontakter",
	"Contrast": "Kontrast",
	"Day": "Dag",
	"DayLightSavingsTime": "Sommartid",
	"Display": "Display",
	"DisplayResetConfText": "Vill du verkligen återställa displayinställningarna till standardvärden?",
	"DisplayResetErrorText": "Fel vid återställning av displayinställningarna till fabriksinställning. Vill du prova igen?",
	"DisplayResetProgressText": "Återställer displayinställn. till standard.",
	"Distance": "Avstånd",
	"DownloadCallContacts": "Autohämtning av kontakter",
	"DownloadCallEmail": "Autohämtning av e-post",
	"DownloadCallHistory": "Autohämtning av samtalshistorik",
	"DownloadCallText": "Autohämtning av SMS",
	"Eastern": "Öster",
	"EditPresetMessage": "Redig förinställt",
	"EmailNotifications": "E-post-aviseringar",
	"EmailSmsNotifications": "E-post-/SMS-aviseringar",
	"FactoryReset": "Återställning till fabriksinställning",
	"FactoryResetConfText": "Vill du verkligen återställa alla inställningar till standardvärden? (Systemet startar om efter genomförd återställning till standardvärden.)",
	"FactoryResetErrorText": "Fel vid återställning av inställningar till fabriksinställning. Vill du prova igen?",
	"FactoryResetProgressText": "Återställer inställningar till standard.",
	"Fahrenheit": "°F",
	"FirstLast": "Förnamn, Efternamn",
	"Fixed": "Fast",
	"GPSSync": "GPS-synkronisering",
	"Inband": "Tel",
	"IncomingCallNotifications": "Inkommande samtalsaviseringar",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių   (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Hexadecimalt",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Numeriskt",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Språk",
	"LanguageChangeErrorText": "Fel vid byte av språk. Vill du prova igen?",
	"LanguageChangeProgressText": "Ändrar språk",
	"LanguageChangeSuccess": "Språk ändrat till {languageID}",
	"LanguageConfText": "Vill du verkligen ändra språk till {languageID}?",
	"LanguageConfTextNoVR": "{languageID} visar enda språket. Brittisk engelska används för röstfunktioner. Ändra displayens språk till  {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} visar enda språket. {VRlanguageID} används för röstfunktioner. Ändra displayens språk till  {languageID}?",
	"LastFirst": "Efternamn, Förnamn",
	"Miles": "mi",
	"Mobile911": "Mobil 112",
	"Mobile911Description": "Om påslaget ringer fordonet automatiskt 112 vid en olycka.",
	"Mode": "Läge",
	"MusicDatabaseUpdate": "Uppdatering av musikdatabas",
	"NaviVolumeTTS": "Navigation kommer att ha denna volym.",
	"NetworkManagement": "Nätverkshantering",
	"Night": "Natt",
	"PhoneVolume": "Telefonvolym",
	"PresetBeThereTen": "Kommer om 10 minuter.",
	"PresetBeThereTwenty": "Kommer om 20 minuter.",
	"PresetCallLater": "Ringer upp dig senare.",
	"PresetCantTalk": "Kan inte prata nu.",
	"PresetDriving": "Kör nu.",
	"PresetMessages": "Förinställda meddelanden",
	"PresetMessagesTitle": "Förinställda meddelanden",
	"PresetNeedMore": "Jag behöver mer köranvisningar.",
	"PresetNo": "Nej",
	"PresetOk": "U redu",
	"PresetPleaseCall": "Ring mig.",
	"PresetStuck": "Fast i trafiken.",
	"PresetThanks": "Tack så mycket!",
	"PresetWhere": "Var är du?",
	"PresetWhy": "Varför?",
	"PresetYes": "Ja",
	"Recent": "Nyligen",
	"Reset": "Återställ",
	"Ringtone": "Ringsignal",
	"RingtoneVolumeTTS": "Telefonsamtal kommer att ha denna volym",
	"SMSNotifications": "SMS-aviseringar",
	"Safety": "Säkerhet",
	"SelectKBLang": "Välj tangentbord",
	"SelectTimeZone": "Välj tidzon",
	"SetClockHrsMinus": "Minska timmar",
	"SetClockHrsPlus": "Öka timmar",
	"SetClockMinMinus": "Minska minuter",
	"SetClockMinPlus": "Öka minuter",
	"Settings": "Inställningar",
	"SystemSettings": "Systeminställning",
	"Temp": "Temperatur ",
	"TimeFormat": "Tidsformat",
	"TimeZoneSelect": "Val av tidzon",
	"ToolTips": "Verktygstips",
	"TurnDisplayOff": "Släck skärm",
	"TurnDisplayOffShowClock": "Släck skärm och visa klocka",
	"UTC0000Casablanca": "UTC Casablanca",
	"UTC0000CoordinatedUniversalTime": "UTC Coordinated Univ. Time",
	"UTC0000Dublin": "UTC Dublin, Edinburgh, London",
	"UTC0000Monrovia": "UTC Monrovia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Amsterdam, Berlin",
	"UTC0100Belgrade": "UTC+01:00 Budapest,Prag",
	"UTC0100Brussels": "UTC+01:00 Bryssel,Madrid,Paris",
	"UTC0100Sarajevo": "UTC+01:00 Sarajevo, Zagreb",
	"UTC0100WestCentralAfrica": "UTC+01:00 Västra Cent. Afrika",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Athen, Bucharest",
	"UTC0200Beirut": "UTC+02:00 Beirut",
	"UTC0200Cairo": "UTC+02:00 Kairo",
	"UTC0200Damascus": "UTC+02:00 Damaskus",
	"UTC0200EEurope": "UTC+02:00 Östeuropa",
	"UTC0200Harare": "UTC+02:00 Harare, Pretoria",
	"UTC0200Helsinki": "UTC+02:00 Kiev, Riga, Sofia",
	"UTC0200Istanbul": "UTC+02:00 Istanbul",
	"UTC0200Jerusalem": "UTC+02:00 Jerusalem",
	"UTC0300Amman": "UTC+03:00 Amman",
	"UTC0300Baghdad": "UTC+03:00 Bagdad",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuwait, Riyadh",
	"UTC0300Nairobi": "UTC+03:00 Nairobi",
	"UTC0330Tehran": "UTC+03:30 Teheran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Muscat",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Moskva,Volgograd",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Kabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karachi",
	"UTC0500Tashkent": "UTC+05:00 Tashkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai, New Delhi",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayawarden.",
	"UTC0545Kathmandu": "UTC+05:45 Katmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bangkok, Hanoi",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Beijing,Hongkong",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 Kuala Lumpur",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulanbatar",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokyo",
	"UTC0900Seoul": "UTC+09:00 Seoul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Canberra, Sydney",
	"UTC1000Guam": "UTC+10:00 Guam,Port Moresby",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Solomonöarna",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland,Wellington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Coord.Univ. Time+12",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azorerna",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Kap Verde",
	"UTCm0100Casablanca": "UTC-01:00 Casablanca",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 Coord. Univ. Time",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Coord. Univ. Time-2",
	"UTCm0200MidAtlantic": "UTC-02:00 Mellanatlanten",
	"UTCm0300Brasilia": "UTC-03:00 Brasilien",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Cayenne, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Grönland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Newfoundland",
	"UTCm0400Asuncion": "UTC-04:00 Asuncion",
	"UTCm0400AtlanticTime": "UTC-04:00 Atlantic Time (Kan)",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiaba",
	"UTCm0400Georgetown": "UTC-04:00 Georgetown,La Paz",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Eastern-US/Kan",
	"UTCm0500Indiana": "UTC-05:00 Indiana (Öst)",
	"UTCm0600CentralAmerica": "UTC-06:00 Centralamerika",
	"UTCm0600CentralTime": "UTC-06:00 Central-US/Kan",
	"UTCm0600Guadalajara": "UTC-06:00 Mexico City",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua, La Paz",
	"UTCm0700MountainTime": "UTC-07:00 Mountain-US/Kan",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja California",
	"UTCm0800PacificTime": "UTC-08:00 Pacific-US/Kan",
	"UTCm0900Alaska": "UTC-09:00 Alaska",
	"UTCm1000Hawaii": "UTC-10:00 Hawaii",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Coord. Univ. Time-11",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Int. västra datum.",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} är endast ett visningsspråk. För {languageID} meddelanden och ingen röst: Nej. För röster och meddelanden på {languageVRTTSID}: Ja.",
	"UseUKEnglishText": "{languageID} visar enda språket. För {languageID} anvisningar och ingen röst: “Nej” För röst och anvisningar på engelska: “Ja”",
	"VRUK": "Det aktuella valda språket stöder inte röstigenkänning.",
	"VRVolume": "VR och ringsignal",
	"VRVolumeTTS": "Röstvägledning sker med denna volym",
	"VersionInfo": "Versionsinformation",
	"_12h": "12 t",
	"_24h": "24 t",
};

framework.registerAppDictLoaded("syssettings", "sv_SE");