var Localization_syssettingsAppDict_id_ID = {
	//"stringId" : "localString"
	"About": "Tentang",
	"AdjustTime": "Sesuaikan Waktu",
	"AgreementsAndDisclaimers": "Kesepakatan dan Penyangkalan",
	"AgreementsDisclaimersText": "Masuk ke www.MazdaEndUserAgreements-Copyrights.com utk  melihat lisensi daftar selengkapnya & pengungkapan hak paten.",
	"Auto": "Otmts",
	"Bluetooth": "Bluetooth",
	"Brightness": "Kecerahan",
	"Celsius": "°C",
	"ChooseLanguage": "Pilih Bahasa",
	"Clock": "Jam",
	"Communication": "Komunikasi",
	"CommunicationResetConfText": "Anda yakin ingin mengembalikan setelan komunikasi ke setelan awalnya?",
	"CommunicationResetErrorRetryText": "Gagal mengembalikan pengaturan komunikasi ke standar pabrik. Anda ingin mencoba lagi?",
	"CommunicationResetProgressText": "Mengembalikan ke bawaan pabrik",
	"ContactsSortOrder": "Atur Urutan Kontak",
	"ContactsSortOrderTitle": "Atur Urutan Kontak",
	"Contrast": "Kontras",
	"Day": "Siang",
	"DayLightSavingsTime": "Waktu Siang",
	"Display": "Layar",
	"DisplayResetConfText": "Anda yakin ingin mengembalikan setelan layar ke setelan standar?",
	"DisplayResetErrorText": "Gagal mengembalikan setelan layar ke standar pabrik. Anda ingin mencoba lagi?",
	"DisplayResetProgressText": "Mengembalikan ke bawaan pabrik",
	"Distance": "Jarak",
	"DownloadCallContacts": "Unduh Kontak Otomatis",
	"DownloadCallEmail": "Unduh Email Otomatis",
	"DownloadCallHistory": "Unduh Riwayat Panggilan otomatis",
	"DownloadCallText": "Unduh Teks Otomatis",
	"Eastern": "Timur",
	"EditPresetMessage": "Edit Pesan Bawaan",
	"EmailNotifications": "Pemberitahuan Email",
	"EmailSmsNotifications": "Pemberitahuan Email/SMS",
	"FactoryReset": "Setel Ulang Standar Pabrik",
	"FactoryResetConfText": "Anda yakin ingin mengembalikan semua setelan ke standar pabrik? (Sistem akan dihidupkan ulang setelah penyetelan ulang pabrik berhasil.)",
	"FactoryResetErrorText": "Gagal mengembalikan setelan ke standar pabrik. Anda ingin mencoba lagi?",
	"FactoryResetProgressText": "Setelan kembali ke bawaan pabrik",
	"Fahrenheit": "°F",
	"FirstLast": "Nama Depan, Nama Belakang",
	"Fixed": "Tetap",
	"GPSSync": "Penyelarasan GPS",
	"Inband": "InBand",
	"IncomingCallNotifications": "Pemberitahuan Panggilan Masuk",
	"Kilometers": "km",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "Heksadesimal",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "Numerik",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "Bahasa",
	"LanguageChangeErrorText": "Gagal mengubah bahasa. Anda ingin mencoba lagi?",
	"LanguageChangeProgressText": "Mengganti Bahasa",
	"LanguageChangeSuccess": "Bahasa telah diubah menjadi {languageID}",
	"LanguageConfText": "Apakah Anda yakin ingin mengganti bahasa ke {languageID}?",
	"LanguageConfTextNoVR": " {languageID} adalah bahasa Tampilan Saja. Bahasa Inggris UK akan digunakan untuk fungsi suara. Ubah ke  {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": " {languageID} adalah bahasa Tampilan Saja. Bahasa {VRlanguageID} akan digunakan untuk fungsi suara. Ubah ke  {languageID}?",
	"LastFirst": "Nama Belakang, Nama Depan",
	"Miles": "mi",
	"Mobile911": "Ponsel 911",
	"Mobile911Description": "Ketika aktif, kendaraan akan otomatis memanggil 911 setelah terjadi kecelakaan.",
	"Mode": "Mode",
	"MusicDatabaseUpdate": "Pembaruan Pusat data Musik",
	"NaviVolumeTTS": "Volume petunjuk Navigasi akan berada pada level ini.",
	"NetworkManagement": "Manajemen Jaringan",
	"Night": "Malam",
	"PhoneVolume": "Volume Telepon",
	"PresetBeThereTen": "Sampai di sana 10 menit lagi.",
	"PresetBeThereTwenty": "Sampai di sana 20 menit lagi.",
	"PresetCallLater": "Nanti saya telepon Anda",
	"PresetCantTalk": "Tak bisa bicara sekarang.",
	"PresetDriving": "Sedang mengemudi",
	"PresetMessages": "Pesan Bawaan",
	"PresetMessagesTitle": "Pesan Bawaan",
	"PresetNeedMore": "Saya perlu petunjuk lagi",
	"PresetNo": "Tidak",
	"PresetOk": "OK",
	"PresetPleaseCall": "Tolong telepon saya",
	"PresetStuck": "Terjebak kemacetan.",
	"PresetThanks": "Trims!",
	"PresetWhere": "Anda di mana?",
	"PresetWhy": "Kenapa?",
	"PresetYes": "Ya",
	"Recent": "Terbaru",
	"Reset": "Setel Ulang",
	"Ringtone": "Nada Dering",
	"RingtoneVolumeTTS": "Volume panggilan telepon akan berada pada level ini",
	"SMSNotifications": "Pemberitahuan SMS",
	"Safety": "Keaman",
	"SelectKBLang": "Pilih Keyboard",
	"SelectTimeZone": "Pilih Zona Waktu",
	"SetClockHrsMinus": "Kurangi Jam",
	"SetClockHrsPlus": "Tambah Jam",
	"SetClockMinMinus": "Kurangi Menit",
	"SetClockMinPlus": "Tambah Menit",
	"Settings": "Setelan",
	"SystemSettings": "Setelan Sistem",
	"Temp": "Suhu",
	"TimeFormat": "Format Waktu",
	"TimeZoneSelect": "Zona Waktu Dipilih",
	"ToolTips": "Kiat Alat",
	"TurnDisplayOff": "MATIKAN Layar",
	"TurnDisplayOffShowClock": "MATIKAN Layar dan Tampilkan Jam",
	"UTC0000Casablanca": "UTC Casablanca",
	"UTC0000CoordinatedUniversalTime": "UTC Wkt Univ. Terkoordinasi",
	"UTC0000Dublin": "UTC Dublin, Lisbon, London",
	"UTC0000Monrovia": "UTC Monrovia, Reykjavik",
	"UTC0100Amsterdam": "UTC+01:00 Eropa Teng. Barat",
	"UTC0100Belgrade": "UTC+01:00 Eropa Teng. Timur",
	"UTC0100Brussels": "UTC+01:00 Eropa Teng. Barat",
	"UTC0100Sarajevo": "UTC+01:00 Srjevo, Warsaw",
	"UTC0100WestCentralAfrica": "UTC+01:00 Afr.Teng Bag Barat",
	"UTC0100Windhoek": "UTC+01:00 Windhoek",
	"UTC0200Athens": "UTC+02:00 Athena, Bukares",
	"UTC0200Beirut": "UTC+02:00 Beirut",
	"UTC0200Cairo": "UTC+02:00 Kairo",
	"UTC0200Damascus": "UTC+02:00 Damaskus",
	"UTC0200EEurope": "UTC+02:00 Eropa Timur",
	"UTC0200Harare": "UTC+02:00 Harare, Pretoria",
	"UTC0200Helsinki": "UTC+02:00 Eropa Timur",
	"UTC0200Istanbul": "UTC+02:00 Istanbul",
	"UTC0200Jerusalem": "UTC+02:00 Yerusalem",
	"UTC0300Amman": "UTC+03:00 Amman",
	"UTC0300Baghdad": "UTC+03:00 Baghdad",
	"UTC0300Kaliningrad": "UTC+03:00 Kaliningrad, Minsk",
	"UTC0300Kuwait": "UTC+03:00 Kuwait, Riyadh",
	"UTC0300Nairobi": "UTC+03:00 Nairobi",
	"UTC0330Tehran": "UTC+03:30 Teheran",
	"UTC0400AbuDhabi": "UTC+04:00 Abu Dhabi, Muskat",
	"UTC0400Baku": "UTC+04:00 Baku",
	"UTC0400Moscow": "UTC+04:00 Rusia Barat",
	"UTC0400PortLouis": "UTC+04:00 Port Louis",
	"UTC0400Tbilisi": "UTC+04:00 Tbilisi",
	"UTC0400Yerevan": "UTC+04:00 Yerevan",
	"UTC0430Kabul": "UTC+04:30 Kabul",
	"UTC0500Islamabad": "UTC+05:00 Islamabad, Karachi",
	"UTC0500Tashkent": "UTC+05:00 Tashkent",
	"UTC0530Chennai": "UTC+05:30 Mumbai, New Delhi",
	"UTC0530SriJayawardenepura": "UTC+05:30 Sri Jayawardenep.",
	"UTC0545Kathmandu": "UTC+05:45 Kathmandu",
	"UTC0600Astana": "UTC+06:00 Astana",
	"UTC0600Dhaka": "UTC+06:00 Dhaka",
	"UTC0600Ekaterinburg": "UTC+06:00 Ekaterinburg",
	"UTC0630Yangon": "UTC+06:30 Yangon (Rangoon)",
	"UTC0700Bangkok": "UTC+07:00 Bngkok,Hanoi,Jkrta",
	"UTC0700Novosibirsk": "UTC+07:00 Novosibirsk",
	"UTC0800Beijing": "UTC+08:00 Cina, Hong Kong",
	"UTC0800Krasnoyarsk": "UTC+08:00 Krasnoyarsk",
	"UTC0800KualaLumpur": "UTC+08:00 K.Lumpur, Sngapura",
	"UTC0800Perth": "UTC+08:00 Perth",
	"UTC0800Taipei": "UTC+08:00 Taipei",
	"UTC0800Ulaanbaatar": "UTC+08:00 Ulan Bator",
	"UTC0900Irkutsk": "UTC+09:00 Irkutsk",
	"UTC0900Osaka": "UTC+09:00 Osaka, Tokyo",
	"UTC0900Seoul": "UTC+09:00 Seoul",
	"UTC0930Adelaide": "UTC+09:30 Adelaide",
	"UTC0930Darwin": "UTC+09:30 Darwin",
	"UTC1000Brisbane": "UTC+10:00 Brisbane",
	"UTC1000Canberra": "UTC+10:00 Canberra, Sydney",
	"UTC1000Guam": "UTC+10:00 Guam,Port Moresby",
	"UTC1000Hobart": "UTC+10:00 Hobart",
	"UTC1000Yakutsk": "UTC+10:00 Yakutsk",
	"UTC1100SolomonIs": "UTC+11:00 Salomon, Kaledonia",
	"UTC1100Vladivostok": "UTC+11:00 Vladivostok",
	"UTC1200Auckland": "UTC+12:00 Auckland,Welington",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 Wkt Univ.Trkord+12",
	"UTC1200Fiji": "UTC+12:00 Fiji",
	"UTC1200Magadan": "UTC+12:00 Magadan",
	"UTC1300NukuAlofa": "UTC+13:00 Nuku'alofa",
	"UTC1300Samoa": "UTC+13:00 Samoa",
	"UTCm0100Azores": "UTC-01:00 Azores",
	"UTCm0100CapeVerdeIs": "UTC-01:00 Tanjung Verde",
	"UTCm0100Casablanca": "UTC-01:00 Casablanca",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00  Wkt Univ.Trkoord",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 Wkt Univ.Trkord-02",
	"UTCm0200MidAtlantic": "UTC-02:00 Prtengahan Atlantik",
	"UTCm0300Brasilia": "UTC-03:00 Brasilia",
	"UTCm0300BuenosAires": "UTC-03:00 Buenos Aires",
	"UTCm0300Cayenne": "UTC-03:00 Cayenne, Fortaleza",
	"UTCm0300Greenland": "UTC-03:00 Greenland",
	"UTCm0300Montevideo": "UTC-03:00 Montevideo",
	"UTCm0300Salvador": "UTC-03:00 Salvador",
	"UTCm0330Newfoundland": "UTC-03:30 Newfoundland",
	"UTCm0400Asuncion": "UTC-04:00 Asuncion",
	"UTCm0400AtlanticTime": "UTC-04:00 Wkt Atlantis (Knd)",
	"UTCm0400Cuiaba": "UTC-04:00 Cuiaba",
	"UTCm0400Georgetown": "UTC-04:00 Georgetown",
	"UTCm0400Santiago": "UTC-04:00 Santiago",
	"UTCm0430Caracas": "UTC-04:30 Caracas",
	"UTCm0500Bogota": "UTC-05:00 Bogota, Lima, Quito",
	"UTCm0500EasternTime": "UTC-05:00 Wkt Tmur(AS&Knd)",
	"UTCm0500Indiana": "UTC-05:00 Indiana (Timur)",
	"UTCm0600CentralAmerica": "UTC-06:00 Amrk (Bag Tengah)",
	"UTCm0600CentralTime": "UTC-06:00 Wkt Teng(AS&Knd)",
	"UTCm0600Guadalajara": "UTC-06:00 Guadalajara,Meksiko",
	"UTCm0600Saskatchewan": "UTC-06:00 Saskatchewan",
	"UTCm0700Arizona": "UTC-07:00 Arizona",
	"UTCm0700Chihuahua": "UTC-07:00 Chihuahua, La Paz",
	"UTCm0700MountainTime": "UTC-06:00 Wkt Pgun(AS&Knd)",
	"UTCm0800BajaCalifornia": "UTC-08:00 Baja California",
	"UTCm0800PacificTime": "UTC-08:00 Wkt Psfik(AS&Knd)",
	"UTCm0900Alaska": "UTC-09:00 Alaska",
	"UTCm1000Hawaii": "UTC-10:00 Hawaii",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 Wkt Univ.Terkord -11",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 Wkt Int'l Bag. Barat",
	"UseUKEng_Taiw_Braz_Cant_Text": "Untuk Petunjuk Bahasa {languageID} tanpa suara: Tidak. Untuk Petunjuk dan Suara  dalam Bahasa {languageVRTTSID}: Ya",
	"UseUKEnglishText": "{languageID} adalah bahasa Tampilan Saja. Untuk perintah {languageID} dan tidak ada Suara: Tidak. Untuk Suara dan Perintah dalam Bahasa Inggris: Ya.",
	"VRUK": "Pilihan bahasa saat ini tidak mendukung pengenalan suara.",
	"VRVolume": "VR&Nada Dering",
	"VRVolumeTTS": "Volume petunjuk suara akan berada pada level ini",
	"VersionInfo": "Informasi Versi",
	"_12h": "12h",
	"_24h": "24h",
};

framework.registerAppDictLoaded("syssettings", "id_ID");