var Localization_syssettingsAppDict_th_TH = {
	//"stringId" : "localString"
	"About": "เกี่ยวกับ",
	"AdjustTime": "ปรับเวลา",
	"AgreementsAndDisclaimers": "ข้อตกลงและการปฏิเสธความรับผิด",
	"AgreementsDisclaimersText": "โปรดไปที่ www.MazdaEndUserAgreements-Copyrights.com เพื่อดูใบอนุญาตรายการทั้งหมดและการเปิดเผยลิขสิทธิ์",
	"Auto": "อัตโนมัติ",
	"Bluetooth": "Bluetooth",
	"Brightness": "ความสว่าง",
	"Celsius": "°C",
	"ChooseLanguage": "เลือกภาษา",
	"Clock": "นาฬิกา",
	"Communication": "การสื่อสาร",
	"CommunicationResetConfText": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าการสื่อสารกลับเป็นค่าเริ่มต้น",
	"CommunicationResetErrorRetryText": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าการสื่อสารกลับเป็นค่าเริ่มต้นจากโรงงาน คุณต้องการลองใหม่หรือไม่",
	"CommunicationResetProgressText": "กลับไปที่การตั้งค่าเริ่มต้นจากโรงงาน",
	"ContactsSortOrder": "จัดเรียงลำดับผู้ติดต่อ",
	"ContactsSortOrderTitle": "จัดเรียงลำดับผู้ติดต่อ",
	"Contrast": "ความคมชัด",
	"Day": "กลางวัน",
	"DayLightSavingsTime": "เวลาออมแสง",
	"Display": "แสดงผล",
	"DisplayResetConfText": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าการแสดงผลกลับเป็นค่าเริ่มต้น",
	"DisplayResetErrorText": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่าการแสดงผลกลับเป็นค่าเริ่มต้นจากโรงงาน คุณต้องการลองใหม่หรือไม่",
	"DisplayResetProgressText": "กลับไปที่การตั้งค่าเริ่มต้นจากโรงงาน",
	"Distance": "ระยะทาง",
	"DownloadCallContacts": "ดาวน์โหลดรายชื่อผู้ติดต่ออัตโนมัติ",
	"DownloadCallEmail": "ดาวน์โหลดอีเมลอัตโนมัติ",
	"DownloadCallHistory": "ดาวน์โหลดประวัติการโทรอัตโนมัติ",
	"DownloadCallText": "ดาวน์โหลด SMS อัตโนมัติ",
	"Eastern": "ตอ.",
	"EditPresetMessage": "แก้ไขข้อความที่ตั้งไว้:",
	"EmailNotifications": "การแจ้งเตือนทางอีเมล",
	"EmailSmsNotifications": "การแจ้งเตือนทางอีเมล/SMS",
	"FactoryReset": "รีเซ็ตเป็นค่าจากโรงงาน",
	"FactoryResetConfText": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนการตั้งค่าทั้งหมดกลับเป็นค่าเริ่มต้นจากโรงงาน (ระบบจะรีบูตหลังจากรีเซ็ตเป็นค่าเริ่มต้นจากโรงงานเรียบร้อยแล้ว)",
	"FactoryResetErrorText": "เกิดข้อผิดพลาดขณะเปลี่ยนการตั้งค่ากลับเป็นค่าเริ่มต้นจากโรงงาน คุณต้องการลองใหม่หรือไม่",
	"FactoryResetProgressText": "เปลี่ยนการตั้งค่ากลับเป็นค่าเริ่มต้น",
	"Fahrenheit": "°F",
	"FirstLast": "ชื่อ, นามสกุล",
	"Fixed": "แก้ไข",
	"GPSSync": "ซิงค์ GPS",
	"Inband": "โทรศัพท์",
	"IncomingCallNotifications": "การแจ้งเตือนสายเรียกเข้า",
	"Kilometers": "กม.",
	"LANGS_AU_ENGLISH": "English‑AU",
	"LANGS_BG_BULGARIAN": "Български",
	"LANGS_BR_PORTUGUESE": "Português‑BR",
	"LANGS_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_CH_CANTONESE": "Cantonese",
	"LANGS_CN_CHINESE": "简体中文",
	"LANGS_CN_CROATIAN": "Hrvatski",
	"LANGS_CN_FRENCH": "Français‑CN",
	"LANGS_CZ_CZECH": "Čeština",
	"LANGS_DA_DANISH": "Dansk",
	"LANGS_DE_GERMAN": "Deutsch",
	"LANGS_ET_ESTONIAN": "Eesti",
	"LANGS_FI_FINNISH": "Suomi",
	"LANGS_FR_FRENCH": "Français‑EU",
	"LANGS_GCC_ARABIC": "العربية",
	"LANGS_GR_GREEK": "Ελληνικά",
	"LANGS_HB_HEBREW": "עברית",
	"LANGS_HK_CANTONESE": "廣州話",
	"LANGS_HU_HUNGARIAN": "Magyar",
	"LANGS_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_IT_ITALIAN": "Italiano",
	"LANGS_JA_JAPANESE": "日本語",
	"LANGS_KB_ABC_AU_ENGLISH": "English‑AU (ABC)",
	"LANGS_KB_ABC_BG_BULGARIAN": "Български (БДС)",
	"LANGS_KB_ABC_BR_PORTUGUESE": "Português‑BR (ABC)",
	"LANGS_KB_ABC_BS_MALAYSIA": "Bahasa Malaysia (ABC)",
	"LANGS_KB_ABC_CN_CHINESE": "简体中文 (按字母顺序)",
	"LANGS_KB_ABC_CN_CROATIAN": "Hrvatski  (Abeceda)",
	"LANGS_KB_ABC_CN_FRENCH": "Français‑CN (ABC)",
	"LANGS_KB_ABC_CZ_CZECH": "Čeština (ABC)",
	"LANGS_KB_ABC_DA_DANISH": "Dansk (ABC)",
	"LANGS_KB_ABC_DE_GERMAN": "Deutsch (ABC)",
	"LANGS_KB_ABC_ENGLISH": "ABC",
	"LANGS_KB_ABC_ET_ESTONIAN": "Eesti (ABC)",
	"LANGS_KB_ABC_FI_FINNISH": "Suomi (aakkoset)",
	"LANGS_KB_ABC_FR_FRENCH": "Français‑EU (ABC)",
	"LANGS_KB_ABC_GCC_ARABIC": "العربية (ترتيب أبجدي)\u200f",
	"LANGS_KB_ABC_HU_HUNGARIAN": "Magyar (ABC)",
	"LANGS_KB_ABC_IN_INDONESIA": "Bahasa Indonesia (ABC)",
	"LANGS_KB_ABC_IT_ITALIAN": "Italiano (ABC)",
	"LANGS_KB_ABC_LT_LITHUANIAN": "Lietuvių   (ABC)",
	"LANGS_KB_ABC_LV_LATVIAN": "Latviešu valoda (ABC)",
	"LANGS_KB_ABC_NA_SPANISH": "Español‑NA (ABC)",
	"LANGS_KB_ABC_NL_DUTCH": "Nederlands (ABC)",
	"LANGS_KB_ABC_NO_NORWEGIAN": "Norsk (ABC)",
	"LANGS_KB_ABC_PL_POLISH": "Polski (AĄB)",
	"LANGS_KB_ABC_PT_PORTUGUESE": "Português‑EU (ABC)",
	"LANGS_KB_ABC_RO_ROMANIAN": "Română (Alfabetică)",
	"LANGS_KB_ABC_RU_RUSSIAN": "Русский (АБВ)",
	"LANGS_KB_ABC_SE_SERBIAN": "Српски (АБВ)",
	"LANGS_KB_ABC_SK_SLOVAK": "Slovenský (ABC)",
	"LANGS_KB_ABC_SP_SPANISH": "Español‑EU (ABC)",
	"LANGS_KB_ABC_SW_SWEDISH": "Svenska (ABC)",
	"LANGS_KB_ABC_TH_THAI": "ภาษาไทย (พยัญชนะ)",
	"LANGS_KB_ABC_TR_TURKISH": "Türkçe (ABC)",
	"LANGS_KB_ABC_TW_CHINESE": "繁體中文 (字母順序)",
	"LANGS_KB_ABC_UK_ENGLISH": "English‑UK (ABC)",
	"LANGS_KB_ABC_US_ENGLISH": "English‑US (ABC)",
	"LANGS_KB_ADR_ENGLISH": "English‑AU",
	"LANGS_KB_AU_ENGLISH": "English‑AU",
	"LANGS_KB_BG_BULGARIAN": "Български",
	"LANGS_KB_BR_PORTUGUESE": "Português‑BR",
	"LANGS_KB_BS_MALAYSIA": "Bahasa Malaysia",
	"LANGS_KB_CN_CHINESE": "简体中文",
	"LANGS_KB_CN_CROATIAN": "Hrvatski",
	"LANGS_KB_CN_FRENCH": "Français‑CN",
	"LANGS_KB_CZ_CZECH": "Čeština",
	"LANGS_KB_DA_DANISH": "Dansk",
	"LANGS_KB_DE_GERMAN": "Deutsch",
	"LANGS_KB_ET_ESTONIAN": "Eesti",
	"LANGS_KB_FI_FINNISH": "Suomi",
	"LANGS_KB_FR_FRENCH": "Français‑EU",
	"LANGS_KB_GCC_ARABIC": "العربية",
	"LANGS_KB_GR_GREEK": "Ελληνικά",
	"LANGS_KB_HB_HEBREW": "עברית",
	"LANGS_KB_HK_CANTONESE": "廣州話",
	"LANGS_KB_HU_HUNGARIAN": "Magyar",
	"LANGS_KB_Hex": "เลขฐานสิบหก",
	"LANGS_KB_IN_INDONESIA": "Bahasa Indonesia",
	"LANGS_KB_IT_ITALIAN": "Italiano",
	"LANGS_KB_JA_JAPANESE": "日本語",
	"LANGS_KB_KO_KOREAN": "Korean",
	"LANGS_KB_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_KB_LV_LATVIAN": "Latviešu valoda",
	"LANGS_KB_NA_SPANISH": "Español‑NA",
	"LANGS_KB_NL_DUTCH": "Nederlands",
	"LANGS_KB_NO_NORWEGIAN": "Norsk",
	"LANGS_KB_PL_POLISH": "Polski",
	"LANGS_KB_PT_PORTUGUESE": "Português‑EU",
	"LANGS_KB_RO_ROMANIAN": "Română",
	"LANGS_KB_RU_RUSSIAN": "Русский",
	"LANGS_KB_SE_SERBIAN": "Srpski",
	"LANGS_KB_SK_SLOVAK": "Slovenský",
	"LANGS_KB_SP_SPANISH": "Español‑EU",
	"LANGS_KB_SW_SWEDISH": "Svenska",
	"LANGS_KB_TH_THAI": "ภาษาไทย",
	"LANGS_KB_TR_TURKISH": "Türkçe",
	"LANGS_KB_TW_CHINESE": "繁體中文",
	"LANGS_KB_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_KB_UK_ENGLISH": "English‑UK",
	"LANGS_KB_US_ENGLISH": "English‑US",
	"LANGS_KB_numeric": "ตัวเลข",
	"LANGS_KO_KOREAN": "Korean",
	"LANGS_LT_LITHUANIAN": "Lietuvių  ",
	"LANGS_LV_LATVIAN": "Latviešu valoda",
	"LANGS_MN_CHINESE": "Chinese",
	"LANGS_NA_SPANISH": "Español‑NA",
	"LANGS_NL_DUTCH": "Nederlands",
	"LANGS_NO_NORWEGIAN": "Norsk",
	"LANGS_PL_POLISH": "Polski",
	"LANGS_PT_PORTUGUESE": "Português‑EU",
	"LANGS_RO_ROMANIAN": "Română",
	"LANGS_RU_RUSSIAN": "Русский",
	"LANGS_SE_SERBIAN": "Srpski",
	"LANGS_SK_SLOVAK": "Slovenský",
	"LANGS_SP_SPANISH": "Español‑EU",
	"LANGS_SW_SWEDISH": "Svenska",
	"LANGS_TH_THAI": "ภาษาไทย",
	"LANGS_TR_TURKISH": "Türkçe",
	"LANGS_TW_CHINESE": "繁體中文",
	"LANGS_TW_CHINESE_TAIWAN": "繁體中文(華語)",
	"LANGS_TW_MANDARIN": "繁體中文(台灣)",
	"LANGS_UK_ENGLISH": "English‑UK",
	"LANGS_US_ENGLISH": "English‑US",
	"Language": "ภาษา",
	"LanguageChangeErrorText": "เกิดข้อผิดพลาดขณะเปลี่ยนภาษา คุณต้องการลองใหม่หรือไม่",
	"LanguageChangeProgressText": "กำลังเปลี่ยนภาษา",
	"LanguageChangeSuccess": "เปลี่ยนภาษาเป็น {languageID}",
	"LanguageConfText": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนภาษาเป็น {languageID}",
	"LanguageConfTextNoVR": " {languageID} เป็นภาษาสำหรับแสดงผลเท่านั้น สำหรับฟังก์ชั่นเสียงจะใช้ภาษาอังกฤษ UK \nต้องการเปลี่่ยนภาษาแสดงผลเป็น {languageID}?",
	"LanguageConfTextNoVRNoUKEnglish": "{languageID} เป็นภาษาสำหรับแสดงผลเท่านั้น สำหรับฟังก์ชั่นเสียง {VRlanguageID} \nต้องการเปลี่่ยนภาษาแสดงผลเป็น {languageID}?",
	"LastFirst": "นามสกุล, ชื่อ",
	"Miles": "ไมล์",
	"Mobile911": "Mobile 191",
	"Mobile911Description": "เมื่อเปิด รถจะโทรติดต่อ 191 โดยอัตโนมัติหลังจากเกิดอุบัติเหตุ",
	"Mode": "โหมด",
	"MusicDatabaseUpdate": "อัปเดตฐานข้อมูลเพลง",
	"NaviVolumeTTS": "ระบบนำทางจะอยู่ที่ระดับเสียงนี้",
	"NetworkManagement": "การจัดการเครือข่าย",
	"Night": "กลางคืน",
	"PhoneVolume": "ระดับเสียงโทร",
	"PresetBeThereTen": "ไปถึงภายใน 10 นาที",
	"PresetBeThereTwenty": "ไปถึงภายใน 20 นาที",
	"PresetCallLater": "โทรหาคุณในภายหลัง",
	"PresetCantTalk": "ไม่สะดวกคุยในตอนนี้",
	"PresetDriving": "กำลังขับรถอยู่",
	"PresetMessages": "ข้อความที่กำหนดไว้ล่วงหน้า",
	"PresetMessagesTitle": "ข้อความที่กำหนดไว้ล่วงหน้า",
	"PresetNeedMore": "ฉันต้องการคำแนะนำเส้นทางมากขึ้น",
	"PresetNo": "ไม่",
	"PresetOk": "ตกลง",
	"PresetPleaseCall": "โปรดโทรหาฉัน",
	"PresetStuck": "รถติด",
	"PresetThanks": "ขอบคุณ",
	"PresetWhere": "คุณอยู่ที่ไหน",
	"PresetWhy": "ทำไม",
	"PresetYes": "ใช่",
	"Recent": "ประวัติ",
	"Reset": "รีเซ็ต",
	"Ringtone": "ริงโทน",
	"RingtoneVolumeTTS": "ความดังของโทรศัพท์จะอยู่ที่ระดับเสียงนี้",
	"SMSNotifications": "การแจ้งเตือนทางSMS",
	"Safety": "ปลอดภัย",
	"SelectKBLang": "เลือกแป้นพิมพ์",
	"SelectTimeZone": "เลือกโซนเวลา",
	"SetClockHrsMinus": "ลดชั่วโมง",
	"SetClockHrsPlus": "เพิ่มชั่วโมง",
	"SetClockMinMinus": "ลดนาที",
	"SetClockMinPlus": "เพิ่มนาที",
	"Settings": "การตั้งค่า",
	"SystemSettings": "การตั้งค่าระบบ",
	"Temp": "อุณหภูมิ",
	"TimeFormat": "รูปแบบเวลา",
	"TimeZoneSelect": "การเลือกโซนเวลา",
	"ToolTips": "คำแนะนำเครื่องมือ",
	"TurnDisplayOff": "ปิดการแสดงผล",
	"TurnDisplayOffShowClock": "ปิดหน้าจอแสดงผลและแสดงนาฬิกา",
	"UTC0000Casablanca": "UTC คาซาบลังกา",
	"UTC0000CoordinatedUniversalTime": "UTC เวลามาตรฐานสากล",
	"UTC0000Dublin": "UTC ดับลิน เอดินบะระ ลอนดอน",
	"UTC0000Monrovia": "UTC มันโรเวีย เรกยะวิก",
	"UTC0100Amsterdam": "UTC+01:00 อัมสเตอร์ดัม โรม",
	"UTC0100Belgrade": "UTC+01:00 เบลเกรด บูดาเปสต์",
	"UTC0100Brussels": "UTC+01:00 บรัสเซลส์ ปารีส",
	"UTC0100Sarajevo": "UTC+01:00 ซาเรเยโว สคอปเย",
	"UTC0100WestCentralAfrica": "UTC+01:00 แอฟริกาตะวันตกกลาง",
	"UTC0100Windhoek": "UTC+01:00 วินด์ฮุก",
	"UTC0200Athens": "UTC+02:00 เอเธนส์ บูคาเรสท์",
	"UTC0200Beirut": "UTC+02:00 เบรุต",
	"UTC0200Cairo": "UTC+02:00 ไคโร",
	"UTC0200Damascus": "UTC+02:00 ดามัสกัส",
	"UTC0200EEurope": "UTC+02:00 ยุโรปตะวันออก",
	"UTC0200Harare": "UTC+02:00 ฮาราเร พริทอเรีย",
	"UTC0200Helsinki": "UTC+02:00 เฮลซิงกิ โซเฟีย",
	"UTC0200Istanbul": "UTC+02:00 อิสตันบูล",
	"UTC0200Jerusalem": "UTC+02:00 เยรูซาเล็ม",
	"UTC0300Amman": "UTC+03:00 อัมมาน",
	"UTC0300Baghdad": "UTC+03:00 แบกแดด",
	"UTC0300Kaliningrad": "UTC+03:00 คาลินินกราด",
	"UTC0300Kuwait": "UTC+03:00 คูเวต ริยาด",
	"UTC0300Nairobi": "UTC+03:00 ไนโรบี",
	"UTC0330Tehran": "UTC+03:30 เตหะราน",
	"UTC0400AbuDhabi": "UTC+04:00 อาบูดาบี มัสแกต",
	"UTC0400Baku": "UTC+04:00 บาคู",
	"UTC0400Moscow": "UTC+04:00 มอสโก",
	"UTC0400PortLouis": "UTC+04:00 พอร์ตหลุยส์",
	"UTC0400Tbilisi": "UTC+04:00 ทบิลิซี",
	"UTC0400Yerevan": "UTC+04:00 เยเรวาน",
	"UTC0430Kabul": "UTC+04:30 คาบูล",
	"UTC0500Islamabad": "UTC+05:00 อิสลามาบัด การาจี",
	"UTC0500Tashkent": "UTC+05:00 แทชเคนท์",
	"UTC0530Chennai": "UTC+05:30 มุมไบ นิวเดลี",
	"UTC0530SriJayawardenepura": "UTC+05:30 ศรีชยาวาเดเนปุระ",
	"UTC0545Kathmandu": "UTC+05:45 กาฐมาณฑุ",
	"UTC0600Astana": "UTC+06:00 อัสตานา",
	"UTC0600Dhaka": "UTC+06:00 ดากา",
	"UTC0600Ekaterinburg": "UTC+06:00 เอคเตอรินเบิร์ก",
	"UTC0630Yangon": "UTC+06:30 ย่างกุ้ง (ร่างกุ้ง)",
	"UTC0700Bangkok": "UTC+07:00 กรุงเทพฯ จาการ์ตา",
	"UTC0700Novosibirsk": "UTC+07:00 โนโวซิเบียร์ซค์",
	"UTC0800Beijing": "UTC+08:00 ปักกิ่ง ฮ่องกง",
	"UTC0800Krasnoyarsk": "UTC+08:00 คราสโนยาร์สค์",
	"UTC0800KualaLumpur": "UTC+08:00 กัวลาลัมเปอร์",
	"UTC0800Perth": "UTC+08:00 เพิร์ธ",
	"UTC0800Taipei": "UTC+08:00 ไทเป",
	"UTC0800Ulaanbaatar": "UTC+08:00 อูลานบาตอร์",
	"UTC0900Irkutsk": "UTC+09:00 เออคุทสค์",
	"UTC0900Osaka": "UTC+09:00 โอซากา โตเกียว",
	"UTC0900Seoul": "UTC+09:00 โซล",
	"UTC0930Adelaide": "UTC+09:30 แอดิเลด",
	"UTC0930Darwin": "UTC+09:30 ดาร์วิน",
	"UTC1000Brisbane": "UTC+10:00 บริสเบน",
	"UTC1000Canberra": "UTC+10:00 เมลเบิร์น ซิดนีย์",
	"UTC1000Guam": "UTC+10:00 เกาะกวม",
	"UTC1000Hobart": "UTC+10:00 โฮบาร์ต",
	"UTC1000Yakutsk": "UTC+10:00 ยาคุตสค์",
	"UTC1100SolomonIs": "UTC+11:00 หมู่เกาะโซโลมอน",
	"UTC1100Vladivostok": "UTC+11:00 วลาดิวอสต็อก",
	"UTC1200Auckland": "UTC+12:00 โอคแลนด์ เวลลิงตัน",
	"UTC1200CoordinatedUniversalTime12": "UTC+12:00 เวลามาตรฐานสากล+12",
	"UTC1200Fiji": "UTC+12:00 ฟิจิ",
	"UTC1200Magadan": "UTC+12:00 มากาดาน",
	"UTC1300NukuAlofa": "UTC+13:00 นูกูอโลฟา",
	"UTC1300Samoa": "UTC+13:00 ซามัว",
	"UTCm0100Azores": "UTC-01:00 อะซอร์ส",
	"UTCm0100CapeVerdeIs": "UTC-01:00 หมู่เกาะเคปเวิร์ด",
	"UTCm0100Casablanca": "UTC-01:00 คาซาบลังกา",
	"UTCm0100CoordinatedUniversalTime": "UTC-01:00 เวลามาตรฐานสากล",
	"UTCm0200CoordinatedUniversalTime02": "UTC-02:00 เวลามาตรฐานสากล-02",
	"UTCm0200MidAtlantic": "UTC-02:00 แอตแลนติกกลาง",
	"UTCm0300Brasilia": "UTC-03:00 บราซิเลีย",
	"UTCm0300BuenosAires": "UTC-03:00 บัวโนสไอเรส",
	"UTCm0300Cayenne": "UTC-03:00 กาแยน ฟอร์ตาเลซา",
	"UTCm0300Greenland": "UTC-03:00 กรีนแลนด์",
	"UTCm0300Montevideo": "UTC-03:00 มอนเตวิเดโอ",
	"UTCm0300Salvador": "UTC-03:00 ซัลวาดอร์",
	"UTCm0330Newfoundland": "UTC-03:30 นิวฟาวด์แลนด์",
	"UTCm0400Asuncion": "UTC-04:00 อะซุนซิออง",
	"UTCm0400AtlanticTime": "UTC-04:00 แอตแลนติก (แคนาดา)",
	"UTCm0400Cuiaba": "UTC-04:00 กุยกาบา",
	"UTCm0400Georgetown": "UTC-04:00 จอร์จทาวน์ ลาปาซ",
	"UTCm0400Santiago": "UTC-04:00 ซานติอาโก",
	"UTCm0430Caracas": "UTC-04:30 คารากัส",
	"UTCm0500Bogota": "UTC-05:00 โบโกตา ลิมา กีโต",
	"UTCm0500EasternTime": "UTC-05:00 เวลาตะวันออก",
	"UTCm0500Indiana": "UTC-05:00 อินเดียนา",
	"UTCm0600CentralAmerica": "UTC-06:00 อเมริกากลาง",
	"UTCm0600CentralTime": "UTC-06:00 เวลาภาคกลาง",
	"UTCm0600Guadalajara": "UTC-06:00 กัวดาลาฮารา",
	"UTCm0600Saskatchewan": "UTC-06:00 ซัสแคตเชวัน",
	"UTCm0700Arizona": "UTC-07:00 แอริโซนา",
	"UTCm0700Chihuahua": "UTC-07:00 ชิวาวา ลาปาซ",
	"UTCm0700MountainTime": "UTC-07:00 เวลาเขตเทือกเขา",
	"UTCm0800BajaCalifornia": "UTC-08:00 บาฮา แคลิฟอร์เนีย",
	"UTCm0800PacificTime": "UTC-08:00 เวลาแปซิฟิก",
	"UTCm0900Alaska": "UTC-09:00 อะแลสกา",
	"UTCm1000Hawaii": "UTC-10:00 ฮาวาย",
	"UTCm1100CoordinatedUniversalTime11": "UTC-11:00 เวลามาตรฐานสากล-11",
	"UTCm1200InternationalDateLineWest": "UTC-12:00 เส้นแบ่งวันสากลตต.",
	"UseUKEng_Taiw_Braz_Cant_Text": "{languageID} เป็นภาษาที่ใช้แสดงเท่านั้น สำหรับพร้อมท์ {languageID} และไม่มีเสียง: ไม่ใช่ สำหรับเสียงและพร้อมท์ใน {languageVRTTSID}:ใช่",
	"UseUKEnglishText": "{languageID} เป็นภาษาสำหรับแสดงผลเท่านั้น\nสำหรับ {languageID} ข้อความและไม่ใช้เสียง:ไม่ สำหรับเสียงและข้อความในอังกฤษ: ใช่",
	"VRUK": "ภาษาที่เลือกในปัจจุบันไม่รองรับการจดจำเสียง",
	"VRVolume": "VR และริงโทน",
	"VRVolumeTTS": "ความดังของเสียงคำแนะนำจะอยู่ที่ระดับเสียงนี้",
	"VersionInfo": "ข้อมูลเวอร์ชั่น",
	"_12h": "12 ชม.",
	"_24h": "24 ชม.",
};

framework.registerAppDictLoaded("syssettings", "th_TH");