var Localization_cdAppDict_bg_BG = {
	//"stringId" : "localString"
	"Albums": "Албуми",
	"AllAlbums": "Всички албуми",
	"AllArtists": "Всички изпълнители",
	"AllSongs": "Всички песни",
	"Artists": "Изпълнители",
	"Disc": "Диск",
	"DiscError": "Грешка в диска",
	"DiscErrorNotification": "Възникна грешка в диска",
	"DiscInserted": "Дискът е поставен",
	"DiscNotPlayable": "Този диск не може да се възпроизвежда",
	"EjectedDisc": "Дискът е изваден",
	"EjectingDisc": "Изваждане на диск",
	"FilesNotPlayable": "Файловете не се възпроизв.",
	"Folders": "Папки",
	"Genres": "Жанрове",
	"Loading": "Дискът се зарежда",
	"MechanicalError": "Механична грешка в CD",
	"MechanicalErrorNotification": "Механична грешка в CD плейъра",
	"NoDiscInserted": "Няма поставен диск",
	"NoPlayableSongs": "На този диск няма песни, които могат да се възпроизвеждат.",
	"NowPlayingCurrentFileNumber": "Номер на файла {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Песен {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Текуща папка",
	"SelectRootFolderTooltip": "Главна папка",
	"SelectRootMenuTooltip": "Главно меню",
	"SelectTrackListTooltip": "Списък с песни",
	"Track": "Песен {trackNumber}",
	"UpdateComplete": "CD плейърът е актуализиран",
	"Updating": "CD плейърът се актуализира",
	"VrHelp_NowPlaying_Data_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Data_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Data_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Data_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Data_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Data_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Data_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Data_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Sound Settings",
	"VrHelp_NowPlaying_Music_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Music_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Music_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Music_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Music_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Music_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Music_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Music_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Sound Settings",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "bg_BG");