var Localization_cdAppDict_tr_TR = {
	//"stringId" : "localString"
	"Albums": "Albümler",
	"AllAlbums": "Tüm Albümler",
	"AllArtists": "Tüm Sanatçılar",
	"AllSongs": "Tüm Şarkılar",
	"Artists": "Sanatçılar",
	"Disc": "Disk",
	"DiscError": "Disk Hatası",
	"DiscErrorNotification": "Disk Hatası Oluştu",
	"DiscInserted": "Disk takıldı",
	"DiscNotPlayable": "Bu disk çalınamıyor",
	"EjectedDisc": "Disk Çıkartıldı",
	"EjectingDisc": "Disk Çıkartılıyor",
	"FilesNotPlayable": "Dosyalar Çalınamıyor",
	"Folders": "Klasörler",
	"Genres": "Türler",
	"Loading": "Disk Yükleniyor",
	"MechanicalError": "Mekanik CD Hatası",
	"MechanicalErrorNotification": "Mekanik CD Oynatıcı Hatası",
	"NoDiscInserted": "Takılı Disk Yok",
	"NoPlayableSongs": "Bu diskte çalınabilecek şarkı bulunmuyor.",
	"NowPlayingCurrentFileNumber": "Dosya Numarası {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Parça {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Geçerli Klasör",
	"SelectRootFolderTooltip": "Kök Klasör",
	"SelectRootMenuTooltip": "Osnovni meni",
	"SelectTrackListTooltip": "Parça Listesi",
	"Track": "Parça {trackNumber}",
	"UpdateComplete": "CD Oynatıcı güncellendi",
	"Updating": "CD Oynatıcı güncelleniyor",
	"VrHelp_NowPlaying_Data_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Data_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Data_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Data_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Data_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Data_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Data_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Data_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Sound Settings",
	"VrHelp_NowPlaying_Music_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Music_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Music_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Music_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Music_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Music_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Music_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Music_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Sound Settings",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "tr_TR");