var Localization_cdAppDict_et_EE = {
	//"stringId" : "localString"
	"Albums": "Albumid",
	"AllAlbums": "Kõik albumid",
	"AllArtists": "Kõik artistid",
	"AllSongs": "Kõik lood",
	"Artists": "Artistid",
	"Disc": "Plaat",
	"DiscError": "Plaadi viga",
	"DiscErrorNotification": "Ilmnes plaadi viga",
	"DiscInserted": "Plaat on sisestatud",
	"DiscNotPlayable": "Plaat ei ole esitatav",
	"EjectedDisc": "Plaat väljastatud",
	"EjectingDisc": "Plaadi väljastamine",
	"FilesNotPlayable": "Failid pole esitatavad",
	"Folders": "Kaustad",
	"Genres": "Žanrid",
	"Loading": "Plaadi laadimine",
	"MechanicalError": "CD mehaaniline viga",
	"MechanicalErrorNotification": "CD-mängija mehaaniline viga",
	"NoDiscInserted": "Plaati pole sisestatud",
	"NoPlayableSongs": "Plaadil pole ühtki esitatavat lugu.",
	"NowPlayingCurrentFileNumber": "Faili # {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Pala {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Praegune kaust",
	"SelectRootFolderTooltip": "Juurkaust",
	"SelectRootMenuTooltip": "Juurmenüü",
	"SelectTrackListTooltip": "Palade loend",
	"Track": "Pala {trackNumber}",
	"UpdateComplete": "CD-mängija värskendam. lõppenud",
	"Updating": "CD-mängija värskendamine",
	"VrHelp_NowPlaying_Data_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Data_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Data_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Data_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Data_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Data_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Data_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Data_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Sound Settings",
	"VrHelp_NowPlaying_Music_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Music_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Music_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Music_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Music_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Music_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Music_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Music_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Sound Settings",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "et_EE");