var Localization_cdAppDict_ru_RU = {
	//"stringId" : "localString"
	"Albums": "Альбомы",
	"AllAlbums": "Все альбомы",
	"AllArtists": "Все исполнители",
	"AllSongs": "Все песни",
	"Artists": "Исполнители",
	"Disc": "Диск",
	"DiscError": "Ошибка чтения диска",
	"DiscErrorNotification": "Ошибка чтения диска",
	"DiscInserted": "Диск вставлен",
	"DiscNotPlayable": "Невозможно воспроизвести диск",
	"EjectedDisc": "Диск извлечен",
	"EjectingDisc": "Извлечение диска",
	"FilesNotPlayable": "Невозможно воспроизвести файлы",
	"Folders": "Папки",
	"Genres": "Жанры",
	"Loading": "Загрузка диска",
	"MechanicalError": "Механич. ошибка CD",
	"MechanicalErrorNotification": "Механич. ошибка CD-плеера",
	"NoDiscInserted": "Диск не вставлен",
	"NoPlayableSongs": "Диск не содержит воспроизводимых песен",
	"NowPlayingCurrentFileNumber": "Номер файла {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Трек {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Текущая папка",
	"SelectRootFolderTooltip": "Корневая папка",
	"SelectRootMenuTooltip": "Корневое меню",
	"SelectTrackListTooltip": "Список треков",
	"Track": "Трек {trackNumber}",
	"UpdateComplete": "Обновл. CD-плеера завершено",
	"Updating": "Выполняется обновл. CD-плеера",
	"VrHelp_NowPlaying_Data_Help_Left1": "Развлечения",
	"VrHelp_NowPlaying_Data_Help_Left2": "Список треков",
	"VrHelp_NowPlaying_Data_Help_Left3": "Повторить",
	"VrHelp_NowPlaying_Data_Help_Left4": "В случайном порядке",
	"VrHelp_NowPlaying_Data_Help_Left5": "Сканировать",
	"VrHelp_NowPlaying_Data_Help_Right1": "Предыдущий /Следующий",
	"VrHelp_NowPlaying_Data_Help_Right2": "Воспроизведение / Пауза",
	"VrHelp_NowPlaying_Data_Help_Right3": "Перемотка / Быстро вперед",
	"VrHelp_NowPlaying_Data_Help_Right4": "Трек (номером)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Настройки звука",
	"VrHelp_NowPlaying_Music_Help_Left1": "Развлечения",
	"VrHelp_NowPlaying_Music_Help_Left2": "Список треков",
	"VrHelp_NowPlaying_Music_Help_Left3": "Повторить",
	"VrHelp_NowPlaying_Music_Help_Left4": "В случайном порядке",
	"VrHelp_NowPlaying_Music_Help_Left5": "Сканировать",
	"VrHelp_NowPlaying_Music_Help_Right1": "Предыдущий /Следующий",
	"VrHelp_NowPlaying_Music_Help_Right2": "Воспроизведение / Пауза",
	"VrHelp_NowPlaying_Music_Help_Right3": "Перемотка / Быстро вперед",
	"VrHelp_NowPlaying_Music_Help_Right4": "Трек (номером)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Настройки звука",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "ru_RU");