var Localization_cdAppDict_da_DK = {
	//"stringId" : "localString"
	"Albums": "Album",
	"AllAlbums": "Alle album",
	"AllArtists": "Alle kunstnere",
	"AllSongs": "Alle sange ",
	"Artists": "Kunstnere",
	"Disc": "Disk",
	"DiscError": "Diskfejl.",
	"DiscErrorNotification": "Der opstod en diskfejl",
	"DiscInserted": "Disk indsat",
	"DiscNotPlayable": "Disken kan ikke afspilles",
	"EjectedDisc": "Disk skubbet ud",
	"EjectingDisc": "Disk skubbes ud",
	"FilesNotPlayable": "Filerne kan ikke afspilles",
	"Folders": "Mapper",
	"Genres": "Genrer",
	"Loading": "Disk indlæses",
	"MechanicalError": "Mekanisk fejl i CD",
	"MechanicalErrorNotification": "Mekanisk fejl i CD-afspiller",
	"NoDiscInserted": "Der er ikke isat nogen disk",
	"NoPlayableSongs": "Denne disk har ikke nogen spilbare sange.",
	"NowPlayingCurrentFileNumber": "Fil nummer {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Track {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Nuværende mappe",
	"SelectRootFolderTooltip": "Hovedmappe",
	"SelectRootMenuTooltip": "Hovedmenu",
	"SelectTrackListTooltip": "Trackliste",
	"Track": "Track {trackNumber}",
	"UpdateComplete": "CD-afspiller er opdateret",
	"Updating": "CD-afspiller opdateres",
	"VrHelp_NowPlaying_Data_Help_Left1": "Underholdning",
	"VrHelp_NowPlaying_Data_Help_Left2": "Trackliste",
	"VrHelp_NowPlaying_Data_Help_Left3": "Gentag",
	"VrHelp_NowPlaying_Data_Help_Left4": "Bland",
	"VrHelp_NowPlaying_Data_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Data_Help_Right1": "Forrige/Næste",
	"VrHelp_NowPlaying_Data_Help_Right2": "Afspil/Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Spol tilbage/Hurtigt frem",
	"VrHelp_NowPlaying_Data_Help_Right4": "Track(nummer)",
	"VrHelp_NowPlaying_Data_Help_Right5": "LydIndstillinger",
	"VrHelp_NowPlaying_Music_Help_Left1": "Underholdning",
	"VrHelp_NowPlaying_Music_Help_Left2": "Trackliste",
	"VrHelp_NowPlaying_Music_Help_Left3": "Gentag",
	"VrHelp_NowPlaying_Music_Help_Left4": "Bland",
	"VrHelp_NowPlaying_Music_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Music_Help_Right1": "Forrige/Næste",
	"VrHelp_NowPlaying_Music_Help_Right2": "Afspil/Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Spol tilbage/Hurtigt frem",
	"VrHelp_NowPlaying_Music_Help_Right4": "Track(nummer)",
	"VrHelp_NowPlaying_Music_Help_Right5": "LydIndstillinger",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "da_DK");