var Localization_cdAppDict_pl_PL = {
	//"stringId" : "localString"
	"Albums": "Albumy",
	"AllAlbums": "Wszystkie albumy",
	"AllArtists": "Wszyscy wykonawcy",
	"AllSongs": "Wszystkie utwory ",
	"Artists": "Wykonawcy",
	"Disc": "Płyta",
	"DiscError": "Błąd płyty",
	"DiscErrorNotification": "Wystąpił błąd płyty.",
	"DiscInserted": "Płyta włożona",
	"DiscNotPlayable": "Nie można odtworzyć płyty.",
	"EjectedDisc": "Płyta wysunięta",
	"EjectingDisc": "Wysuwanie płyty",
	"FilesNotPlayable": "Nie można odtworzyć plików.",
	"Folders": "Foldery",
	"Genres": "Gatunki",
	"Loading": "Ładowanie płyty",
	"MechanicalError": "Usterka mechaniczna napędu CD",
	"MechanicalErrorNotification": "Usterka mechaniczna odtwarzacza CD",
	"NoDiscInserted": "Nie włożono płyty",
	"NoPlayableSongs": "Na płycie nie ma utworów do odtwarzania",
	"NowPlayingCurrentFileNumber": "Numer pliku {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Track {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Folder bieżący",
	"SelectRootFolderTooltip": "Folder główny",
	"SelectRootMenuTooltip": "Menu główne",
	"SelectTrackListTooltip": "Lista ścieżek",
	"Track": "Track {trackNumber}",
	"UpdateComplete": "Aktualizacja odtwarz. CD zakończ.",
	"Updating": "Aktualizowanie odtwarzacza CD",
	"VrHelp_NowPlaying_Data_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Data_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Data_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Data_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Data_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Data_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Data_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Data_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Sound Settings",
	"VrHelp_NowPlaying_Music_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Music_Help_Left2": "Track List",
	"VrHelp_NowPlaying_Music_Help_Left3": "Repeat",
	"VrHelp_NowPlaying_Music_Help_Left4": "Shuffle",
	"VrHelp_NowPlaying_Music_Help_Left5": "Scan",
	"VrHelp_NowPlaying_Music_Help_Right1": "Previous / Next",
	"VrHelp_NowPlaying_Music_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Rewind / Fast Forward",
	"VrHelp_NowPlaying_Music_Help_Right4": "Track (number)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Sound Settings",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "pl_PL");