var Localization_cdAppDict_fi_FI = {
	//"stringId" : "localString"
	"Albums": "Albumit",
	"AllAlbums": "Kaikki albumit",
	"AllArtists": "Kaikki esittäjät",
	"AllSongs": "Kaikki kappaleet ",
	"Artists": "Esittäjät",
	"Disc": "Levy",
	"DiscError": "Levyvirhe",
	"DiscErrorNotification": "Tapahtui levyvirhe",
	"DiscInserted": "Levy laitettu asemaan",
	"DiscNotPlayable": "Tämä levy ei ole toistettavissa",
	"EjectedDisc": "Levy poistettu asemasta",
	"EjectingDisc": "Poistetaan levyä asemasta",
	"FilesNotPlayable": "Tiedostot eivät ole toistettavia",
	"Folders": "Kansiot",
	"Genres": "Tyylilajit",
	"Loading": "Levyä luetaan",
	"MechanicalError": "CD:n mekaaninen virhe",
	"MechanicalErrorNotification": "CD-soittimen mekaaninen virhe",
	"NoDiscInserted": "Ei levyä asemassa",
	"NoPlayableSongs": "Tällä levyllä ei ole toistettavia kappaleita.",
	"NowPlayingCurrentFileNumber": "Tiedoston # {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Raita {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Nykyinen kansio",
	"SelectRootFolderTooltip": "Pääkansio",
	"SelectRootMenuTooltip": "Päävalikko",
	"SelectTrackListTooltip": "Kappaleluettelo",
	"Track": "Raita {trackNumber}",
	"UpdateComplete": "CD-soittimen päivitys valmis",
	"Updating": "CD-soitinta päivitetään",
	"VrHelp_NowPlaying_Data_Help_Left1": "Viihde",
	"VrHelp_NowPlaying_Data_Help_Left2": "Kappaleluettelo",
	"VrHelp_NowPlaying_Data_Help_Left3": "Toisto",
	"VrHelp_NowPlaying_Data_Help_Left4": "Satunnainen soitto",
	"VrHelp_NowPlaying_Data_Help_Left5": "Haku",
	"VrHelp_NowPlaying_Data_Help_Right1": "Edellinen/Seuraava",
	"VrHelp_NowPlaying_Data_Help_Right2": "Toista / Tauko",
	"VrHelp_NowPlaying_Data_Help_Right3": "Siirry taaksepäin/Siirry eteenpäin",
	"VrHelp_NowPlaying_Data_Help_Right4": "Kappale (numero)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Ääniasetukset",
	"VrHelp_NowPlaying_Music_Help_Left1": "Viihde",
	"VrHelp_NowPlaying_Music_Help_Left2": "Kappaleluettelo",
	"VrHelp_NowPlaying_Music_Help_Left3": "Toisto",
	"VrHelp_NowPlaying_Music_Help_Left4": "Satunnainen soitto",
	"VrHelp_NowPlaying_Music_Help_Left5": "Haku",
	"VrHelp_NowPlaying_Music_Help_Right1": "Edellinen/Seuraava",
	"VrHelp_NowPlaying_Music_Help_Right2": "Toista / Tauko",
	"VrHelp_NowPlaying_Music_Help_Right3": "Siirry taaksepäin/Siirry eteenpäin",
	"VrHelp_NowPlaying_Music_Help_Right4": "Kappale (numero)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Ääniasetukset",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "fi_FI");