var Localization_cdAppDict_fr_FR = {
	//"stringId" : "localString"
	"Albums": "Albums",
	"AllAlbums": "Tous les albums",
	"AllArtists": "Tous les artistes",
	"AllSongs": "Tous les morceaux ",
	"Artists": "Artistes",
	"Disc": "CD",
	"DiscError": "Erreur de CD ",
	"DiscErrorNotification": "Une erreur de CD/DVD est survenue",
	"DiscInserted": "Disque inséré",
	"DiscNotPlayable": "Ce CD n'est pas lisible",
	"EjectedDisc": "CD/DVD éjecté",
	"EjectingDisc": "Éjection du disque",
	"FilesNotPlayable": "Impossible de lire les fichiers",
	"Folders": "Dossiers",
	"Genres": "Genres",
	"Loading": "Chargement du disque",
	"MechanicalError": "Erreur mécanique du CD",
	"MechanicalErrorNotification": "Erreur mécanique du lecteur CD",
	"NoDiscInserted": "Aucun CD/DVD inséré",
	"NoPlayableSongs": "Ce disque ne contient aucun morceau lisible.",
	"NowPlayingCurrentFileNumber": "Fichier {currentFile}/{totalFiles}",
	"NowPlayingCurrentTrack": "Piste {currentFile}/{totalFiles}",
	"SelectCurrentFolderTooltip": "Dossier courant",
	"SelectRootFolderTooltip": "Répertoire racine",
	"SelectRootMenuTooltip": "Menu racine",
	"SelectTrackListTooltip": "Liste de pistes",
	"Track": "Piste {trackNumber}",
	"UpdateComplete": "Mise à jour du lecteur CD terminée",
	"Updating": "Mise à jour du lecteur CD",
	"VrHelp_NowPlaying_Data_Help_Left1": "Divertissements",
	"VrHelp_NowPlaying_Data_Help_Left2": " Liste de pistes",
	"VrHelp_NowPlaying_Data_Help_Left3": " Lecture en Boucle",
	"VrHelp_NowPlaying_Data_Help_Left4": " Lecture aléatoire",
	"VrHelp_NowPlaying_Data_Help_Left5": "Balayage",
	"VrHelp_NowPlaying_Data_Help_Right1": "Précédent / Suivant",
	"VrHelp_NowPlaying_Data_Help_Right2": "Lire/Pause",
	"VrHelp_NowPlaying_Data_Help_Right3": "Retour rapide/Avance rapide",
	"VrHelp_NowPlaying_Data_Help_Right4": "Piste(nombre)",
	"VrHelp_NowPlaying_Data_Help_Right5": "Paramètres audio",
	"VrHelp_NowPlaying_Music_Help_Left1": "Divertissements",
	"VrHelp_NowPlaying_Music_Help_Left2": " Liste de pistes",
	"VrHelp_NowPlaying_Music_Help_Left3": " Lecture en Boucle",
	"VrHelp_NowPlaying_Music_Help_Left4": " Lecture aléatoire",
	"VrHelp_NowPlaying_Music_Help_Left5": "Balayage",
	"VrHelp_NowPlaying_Music_Help_Right1": "Précédent / Suivant",
	"VrHelp_NowPlaying_Music_Help_Right2": "Lire/Pause",
	"VrHelp_NowPlaying_Music_Help_Right3": "Retour rapide/Avance rapide",
	"VrHelp_NowPlaying_Music_Help_Right4": "Piste(nombre)",
	"VrHelp_NowPlaying_Music_Help_Right5": "Paramètres audio",
	"sbNameId": "CD",
};

framework.registerAppDictLoaded("cd", "fr_FR");