var Localization_warnguideAppDict_de_DE = {
    //"stringId" : "localString"
    "Warnings" : "Warnmeldungen",
    "NoWarnings" : "Keine Warnmeldungen gefunden",
    "WarningSafetyMessage" : "Aus Sicherheitsgründen, Alarm\nAnleitung wird nicht ange.",
    "WarningGuidance" : "Warnmeldungen",
    "AuxBattLowShrt" : "12V-Batterie fast leer",
    "DriveBattDropShrt" : "Hochvoltbatterie fast leer",
    "ControlSystemErrorShrt" : "Fehler Parkposition-Steuersystems",
    "EngineOilPressureErrorShrt" : "Niedriger Motoröldruck",
    "HybridSysErrorShrt" : "Hybrid-Systemstörung",
    "HybridSysOverheatShrt" : "Hybridsystemüberhitzung",
    "PpositionRequestShrt" : "Parkpositionsanfrage",
    "ChargingSysErrorShrt" : "Ladesystemfehlfunktion",
    "BrakeSysErrorShrt" : "Bremssystemfehlfunktion",
    "EcbSysErrorShrt" : "Bremssystemfehlfunktion",
    "AbsSysErrorShrt" : "ABS-Fehlfunktion",
    "DscSysErrorShrt" : "DSC-Fehlfunktion",
    "DropKeyBattChrgShrt" : "Schlüsselbatterie schwach",
    "EngOilPressureErrorShrt" : "Niedriger Motoröldruck",
    "ChrgSysErrorShrt" : "Ladesystemfehlfunktion",
    "EloopSysErrorShrt" : "i-ELOOP-Systemfehlfunktion",
    "EloopChargingShrt" : "i-ELOOP-Ladung",
    "LowBrakeFluidShrt" : "Niedriger Bremsflüssigkeitsstand",
    "BrakeSystemErrorShrt" : "Bremssystemfehlfunktion",
    "LowTireAirPressureShrt" : "Niedriger Reifendruck",
    "EngCoolntTempHighOnShrt" : "Temperatur Motorkühlmittel hoch",
    "EngineWaterTempRiseShrt" : "Temperatur Motorkühlmittel hoch",
    "SystemInspectionShrt" : "4WD-System Inspektion",
    "AccumulationDpfShrt" : "PM-Akkumulation in DPF",
    "RoadSurfaceIcingCautionShrt" : "Vorsicht: Vereisung d. Straßenbel.",
    "LowFuelShrt" : "Niedriger Kraftstoffstand",
    "FuelCapInspectionShrt" : "Tankdeckel Verschlusskontrolle",
    "PowerSteeringSysErrorShrt" : "Servolenkung SystemFehlfunktion",
    "EngSystemErrorShrt" : "Motorsystemfehlfunktion",
    "AirbagSysPretensionerSysErrorShrt" : "Airbagsyst./Gurtstraffersyst.-fehl.",
    "AbsSystemErrorShrt" : "ABS-Fehlfunktion",
    "DscSystemErrorShrt" : "DSC-Fehlfunktion",
    "RvmSysErrorShrt" : "RVM-Fehlfunktion",
    "BsmSystemErrorShrt" : "BSM-Fehlfunktion",
    "AfsSystemErrorShrt" : "AFS-Fehlfunktion",
    "AutoLevelSystemErrorShrt" : "Auto-Regulierungs-Systemfehler",
    "IstopSysErrorShrt" : "i-stop-Systemfehlfunktion",
    "TpmsSysErrorShrt" : "Fehlfunktion TPMS-System",
    "KeylesSysErrorShrt" : "Fehler b. schlüssellosen Zugangssy.",
    "FWDSysErrorShrt" : "4WD-Systemfehlfunktion",
    "DPFErrorShrt" : "DPF-Fehler",
    "AutoTransSysErrorShrt" : "Fehlfunktion Automatikgetriebe",
    "BattManagSysErrorShrt" : "Fehlfkt. Batteriemgmnt.-System",
    "BrakOverrideSysErrorShrt" : "Bremsüberbrückung-Systemfehler",
    "MRCCSysErrorShrt" : "MRCC-Fehlfunktion",
    "SBSSysErrorShrt" : "SBS-Fehlfunktion",
    "FOWSysError" : "FOW-Fehlfunktion",
    "DRSSSysErrorShrt" : "DRSS-Fehlfunktion",
    "FOWMRCCRadarSoilingShrt" : "FOW/MRCC- Radarfehlfunktion",
    "FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS-Radarfehler",
    "SBSMRCCRadarSoilingShrt" : "SBS/MRCC -Radarfehlfunktion",
    "SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS-Radarfehler",
    "MRCCUnavailableShrt" : "MRCC nicht verfügbar",
    "SBSBrakeUnavailableShrt" : "SBS-Bremsen nicht verfügbar",
    "SBSBrakeMRCCUnavailableShrt" : "SBS-Bremsen/MRCC nicht verf.",
    "SCBSSysErrorShrt" : "SCBS-Fehlfunktion",
    "SCBSWindshieldSoilingShrt" : "SCBS-Fehlfunktion",
    "SCBSUnavailableShrt" : "SCBS nicht verfügbar",
    "LDWSSysErrorShrt" : "LDWS-Fehlfunktion",
    "HBCSysErrorShrt" : "HBC-Fehlfunktion",
    "HBCLLDWSCamDisconnectShrt" : "HBC/LDWS Kamerafehlfunktion",
    "HBCLDWSSysErrorShrt" : "HBC/LDWS-  Systemfehlfunktion",
    "HBCLDWSWindshieldFogShrt" : "HBC/LDWS-  Systemfehlfunktion",
    "SedimenterWarningShrt" : "Sediment. Inspektion",
    "FuelAirFilterCartReplacePeriodShrt" : "Ersetz. Kraftst.-Luftfilterpatr. erf.",
    "VehicleSysErrorShrt" : "Fahrzeug Systemfehlfunktion",
    "LowWasheFluidShrt" : "Niedr. Scheibenrein.-Flüssigkeit",
    "EngineWaterTempDropShrt" : "Temperatur Motorkühlm. niedrig",
    "PreheatingDispLampShrt" : "Vorheizen der Glühkerzen",
    "AuxBattLowLong" : "Niedrige Ladung der 12V-Batterie.\n· Wenn diese Anzeige häufig während der Fahrt leuchtet, kann die Batterie beeinträchtigt werden. Lassen Sie das Fahrzeug von einem Händler überprüfen.\n· Wenn diese Anzeige ständig leuchtet und sich nicht ausschalten lässt, ist die 12V-Batterie leer. Sehen Sie vor dem Start des Hybridsystems in der Bedienungsanleitung nach und lassen das Fahrzeug von einem Händler überprüfen.",
    "DriveBattDropLong" : "Die verbleibende Ladung der Hochvoltbatterie ist gering, weil das Getriebe lange in der neutralen Position verblieben ist. \nIn der Position Neutral ist Aufladen nicht möglich. Bei langen Stillstandszeiten auf die Position Parken stellen. \nStarten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu.",
    "ControlSystemErrorLong" : "Fehlfunktion des Parkposition-Steuersystems \nWenn dies nicht überprüft wird, kann das zu den folgenden Situationen führen: \n・Der Park-Schließechanismus funktioniert ggf. nicht. Parken Sie auf einer flachen Stelle und verwenden Sie die Feststellbremse. \n・Der Netzschalter läßt sich ggf. nicht ausschalten. Drücken Sie zum Ausschalten wiederholt den Netzschalter. \n・ Die Anzeige\"Feststellbremse beim Parken verwenden\" geht beim Fahren und bei Anhalten aus. \nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "EngineOilPressureErrorLong" : "Niedriger Motoröldruck \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Ölstand. Falls erforderlich, Öl hinzufügen. \nLassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.\n",
    "HybridSysErrorLong" : "Hybridsystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "HybridSysOverheatLong" : "Hybridsystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "PpositionRequestLong" : "Stellen Sie den Schalthebel auf Parken. \nDies hat eine der folgenden Ursachen: \n・ Das Batteriesystem wurde mit einer anderen Schalthebel-Position als P gestartet oder gestoppt.\n・Die Fahrerseitentür wurde mit der Schalthebel-Position  N, D oder B geöffnet.\n ・ Die verbleibende Batterieladung ist abgefallen, weil die Schalthebel-Position eine lange Zeit auf Neutral stand. Starten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu. ",
    "ChargingSysErrorLong" : "Ladesystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden.  Das Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "BrakeSysErrorLong" : "Niedriger Bremsflüssigkeitsstand oder Bremssystemfehlfunktion. Das Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.",
    "EcbSysErrorLong" : "Fehlfunktion der Nutzbremse oder des elektronisch gesteuerten Bremssystems. \nDas Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "AbsSysErrorLong" : "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "DscSysErrorLong" : "Fehlfunktion der Dynamischen Stabilitätskontrolle (DSC), des Traktionskontrollsystems (TCS) oder des Berganfahrassistenten (HLA). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "DropKeyBattChrgLong" : "Schlüsselbatterie schwach \nSofort die Schlüsselbatterie ersetzen.\n",
    "EngOilPressureErrorLong" : "Niedriger Motoröldruck \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Ölstand. Falls erforderlich, Öl hinzufügen. \nLassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.\n",
    "ChrgSysErrorLong" : "Ladesystemfehlfunktion \nDas Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "EloopSysErrorLong" : "i-ELOOP-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "EloopChargingLong" : "i-ELOOP wird geladen. \nÜberprüfen Sie bei laufendem Motor, dass der Ladevorgang  abgeschlossen und die Warnanzeige aus ist. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "LowBrakeFluidLong" : "Der Bremsflüssigkeitsstand ist niedrig. \nDas Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "BrakeSystemErrorLong" : "Elektronisch überwachte Bremssystemfehlfunktion. \nDas Fahrzeug sofort an einem sicheren Ort anhalten und von einem Händler überprüfen lassen.\n",
    "LowTireAirPressureLong" : "Geringer Reifenluftdruck in einem oder mehreren Reifen. \nDen Luftdruck der Reifen prüfen und auf den richtigen Luftdruck ausgleichen. Drücken Sie nach dem Ausgleichen des Reifendrucks den TPMS SET Schalter, bis Sie einen Piepston hören.\n",
    "EngCoolntTempHighOnLong" : "Motor überhitzt sich\nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.",
    "EngineWaterTempRiseLong" : "Der Motor fängt an heiß zu laufen. \nFahren Sie langsam oder halten Sie das Fahrzeug an, bis die Anzeige aufhört zu blinken. Wenn die Anzeige auch nach dem Anhalten des Fahrzeugs weiter blinkt, ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.\n",
    "SystemInspectionLong" : "Die Differentialöl-Temperatur ist ungewöhnlich hoch oder ein großer Rotations-Unterschied ist in den Vorder- und Hinterreifen aufgetreten (z. B. beim Versuch aus Schlamm herauszufahren). \nDas Fahrzeug an einer sicheren Stelle anhalten und erst weiterfahren, nachdem die Warnanzeige ausgegangen ist. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "AccumulationDpfLong" : "Die im Diesel-Partikelfilter (DPF) gesammelten Partikel (PM), haben den Verordnungswert überschritten. \nFahren Sie für etwa 10 bis 15 Minuten bei voll aufgewärmten Motor (blaues Temperatur-Licht aus) bei einer Geschwindigkeit von 10 mph (15km/h) oder mehr, um die PM zu beseitigen.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "RoadSurfaceIcingCautionLong" : "Die Außentemperatur beträgt 4°C oder weniger. \nAchten Sie beim Fahren auf vereiste Straßenbelege.\n",
    "LowFuelLong" : "Die Kraftstoffanzeige ist niedrig. \nDas Fahrzeug bald tanken.\n",
    "FuelCapInspectionLong" : "Der Tankdeckel ist möglicherweise nicht richtig verschlossen. \nÜberprüfen Sie, ob der Tankdeckel richtig geschlossen ist. \nNach Aufsetzen und Festziehen des Tankdeckels geht diese Anzeige für ein paar Fahrzyklen nicht aus bis bestätigt werden kann, dass das System in Ordnung ist.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "PowerSteeringSysErrorLong" : "Servolenkung-Fehlfunktion \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "EngSystemErrorLong" : "Motorsystemfehlfunktion  Lassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.",
    "AirbagSysPretensionerSysErrorLong" : "Airbag/Sicherheitsgurt-Fehlfunktion \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "AbsSystemErrorLong" : "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "DscSystemErrorLong" : "Fehlfunktion der dynamischen Stabilitätskontrolle (DSC), des Traktionskontrollsystems (TCS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "RvmSysErrorLong" : "Im RVM-System ist ein Fehler aufgetreten.\nÜberprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung  oder falls mit Schnee bedeckt.\nLassen Sie Ihr Fahrzeug von einem Mazda-Händler überprüfen, wenn dieses Warnlicht nicht ausgeht.\n",
    "BsmSystemErrorLong" : "Blind Spot Monitoring  (BSM) / Rear Cross Traffic Alert (RCTA). \nÜberprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung  oder falls mit Schnee bedeckt. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
    "AfsSystemErrorLong" : "Fehlfunktion Adaptives Frontlicht System (AFS)  Lassen Sie Ihr Fahrzeug von einem Mazda-Händler überprüfen, wenn die Warnleuchte weiterhin blinkt.",
    "AutoLevelSystemErrorLong" : "Fehlfunktion des automatischen Scheinwerfer-Nivellierungssystems \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Warnlicht weiterhin leuchtet.\n",
    "IstopSysErrorLong" : "i-stop-Betrieb ist nicht möglich.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "TpmsSysErrorLong" : "Fehlfunktion des Reifendrucküberwachungs-Systems (TPMS) \nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "KeylesSysErrorLong" : "Schlüssellos Eingabesystemfehlfunktion \nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "FWDSysErrorLong" : "Fehlfunktion des 4WD-Systems oder Größenunterschied zwischen Vorder-und Hinterreifen. \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "DPFErrorLong" : "Diesel-Partikelfilter (DPF) Fehlfunktion \nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "AutoTransSysErrorLong" : "Automatikgetriebe-Fehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden.  Lassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.  \n",
    "BattManagSysErrorLong" : "Batteriemanagement-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen.\n",
    "BrakOverrideSysErrorLong" : "Bremsschalterfehlfunktion. \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
    "MRCCSysErrorLong" : "Feil ved Mazda Radar Cruise Control (MRCC). La en forhandler sjekke kjøretøyet.\n",
    "SBSSysErrorLong" : "Im SBS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "FOWSysErrorLong" : "Feil ved Forward Obstruction Warning (FOW)-systemet.\nLa en forhandler sjekke kjøretøyet.\n",
    "DRSSSysErrorLong" : "Im DRSS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
    "FOWMRCCRadarSoilingLong" : "FOW/MRCC/Radar (Sensor) Fehlfunktion \nReinigen Sie die gesamte Oberfläche des vorderen Kühlergrill-Emblems, falls verschmutzt oder mit Schnee bedeckt.  \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "FOWMRCCDRSSRadarSoilingLong" : "Das FOW/MRCC/DRSS-Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radars (Sensor).\n",
    "SBSMRCCRadarSoilingLong" : "Das SBS/MRCC Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radars (Sensor).\n",
    "SBSMRCCDRSSRadarSoilingLong" : "Das SBS/MRCC/DRSS-Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radars (Sensor).\n",
    "MRCCUnavailableLong" : "Mazda-Radar-Tempomat (MRCC) momentan nicht verfügbar.",
    "SBSBrakeUnavailableLong" : "SBS-Bremsen momentan nicht verfügbar.",
    "SBSBrakeMRCCUnavailableLong" : "SBS-Bremsen/MRCC momentan nicht verfügbar.",
    "SCBSSysErrorLong" : "Smart City Brake Support (SCBS) Fehlfunktion. \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen.",
    "SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) Fehlfunktion. \nReinigen Sie die vordere Windschutzscheibe.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) momentan nicht verfügbar.",
    "LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) Fehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen.\n",
    "HBCSysErrorLong" : "High Beam Control (HBC) Fehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen.",
    "HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nRengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
    "HBCLDWSSysErrorLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) Fehlfunktion Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
    "HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) Fehlfunktion \nEnteisen Sie den Windschutz.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "SedimenterWarningLong" : "Die Menge des im Sedimenter angesammelten Wassers übersteigt den geschätzten Wert. \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "FuelAirFilterCartReplacePeriodLong" : "Die Kraftstoff-Luftfilterpatrone muss ersetzt werden.",
    "VehicleSysErrorLong" : "Fahrzeug Systemfehler \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen.\n",
    "LowWasheFluidLong" : "Der Waschflüssigkeitsstand ist gering. \nFüllen Sie die Waschflüssigkeit auf.\n",
    "EngineWaterTempDropLong" : "Motorkühlmittel ist kalt und es ist keine warme Luft für Heizung/Defroster verfügbar. Das Fahrzeug darf mit ein-oder ausgeschalteter Anzeige gefahren werden.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
    "PreheatingDispLampLong" : "Glühkerzen sind am Vorheizen. \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
    "HybrdSysMalHighPrt" : "Hybrid-Systemstörung. Halten Sie das Fahrzeug sofort an einem sicheren Ort an.",
    "ChargSysMalHighPrt" : "Systemstörung beim Aufladen. Halten Sie das Fahrzeug sofort an einem sicheren Ort an.",
    "IeloopChrgHighPrt" : "i-ELOOP-Ladevorg. Bitte b. laufend. Motor prüfen, ob Ladevorg. abgeschlossen u. Warnanzeige ausgeschaltet ist.",
    "EngnCoolTempHighHighPrt" : "Fahrzeug-Kühlmitteltemperatur hoch. Halten Sie das Fahrzeug sofort an einem sicheren Ort an.",
    "lowBattStartEngine" : "Batterie fast leer! Motor anlassen!",
    "engineOilPressure" : "Motoröldruck",
    "brakeFluid" : "Bremsflüssigkeitsstand niedrig",
    "highVoltage" : "Hochspannungsbatterie schwach",
};

framework.registerAppDictLoaded("warnguide", "de_DE");