var Localization_warnguideAppDict_ro_RO = {
    //"stringId" : "localString"
    "Warnings" : "Avertismente",
    "NoWarnings" : "Niciun avertisment găsit",
    "WarningSafetyMessage" : "Din motive de siguranţă, nu se afişează ghidul de avertizare.",
    "WarningGuidance" : "Avertisment ghidare",
    "AuxBattLowShrt" : "Baterie 12 V descărcată",
    "DriveBattDropShrt" : "Baterie înaltă tensiune descărcată",
    "ControlSystemErrorShrt" : "Defecţiune sist. ctr. poz. parcare",
    "EngineOilPressureErrorShrt" : "Presiune ulei de motor scăzută",
    "HybridSysErrorShrt" : "Defecţiune sistem hibrid",
    "HybridSysOverheatShrt" : "Sistemul hibrid se supraîncălzeşte",
    "PpositionRequestShrt" : "Solicitare poziţie de parcare",
    "ChargingSysErrorShrt" : "Defecţiune sistem de încărcare",
    "BrakeSysErrorShrt" : "Defecţiune la sistemul de frânare",
    "EcbSysErrorShrt" : "Defecţiune la sistemul de frânare",
    "AbsSysErrorShrt" : "Defecţiune ABS",
    "DscSysErrorShrt" : "Defecţiune DSC",
    "DropKeyBattChrgShrt" : "Bateria cheii în curs de epuizare",
    "EngOilPressureErrorShrt" : "Presiune ulei de motor scăzută",
    "ChrgSysErrorShrt" : "Defecţiune sistem de încărcare",
    "EloopSysErrorShrt" : "Defecţiune sistem i-ELOOP",
    "EloopChargingShrt" : "Se încarcă i-ELOOP",
    "LowBrakeFluidShrt" : "Lichid de frână scăzut",
    "BrakeSystemErrorShrt" : "Defecţiune la sistemul de frânare",
    "LowTireAirPressureShrt" : "Presiune pneuri scăzută",
    "EngCoolntTempHighOnShrt" : "Temp. Ridicată lichid de răcire",
    "EngineWaterTempRiseShrt" : "Temp. Ridicată lichid de răcire",
    "SystemInspectionShrt" : "Inspecţie sistem 4WD",
    "AccumulationDpfShrt" : "Acumulare particule în DPF",
    "RoadSurfaceIcingCautionShrt" : "Atenţie! Polei pe carosabil!",
    "LowFuelShrt" : "Nivel redus combustibil",
    "FuelCapInspectionShrt" : "Verif. cap. alimentare combustibil",
    "PowerSteeringSysErrorShrt" : "Defecţiune sistem servodirecţie",
    "EngSystemErrorShrt" : "Defecţiune sistem motor",
    "AirbagSysPretensionerSysErrorShrt" : "Defecţiune sist. airbag / pretens.",
    "AbsSystemErrorShrt" : "Defecţiune ABS",
    "DscSystemErrorShrt" : "Defecţiune DSC",
    "RvmSysErrorShrt" : "Defecţiune RVM",
    "BsmSystemErrorShrt" : "Defecţiune BSM",
    "AfsSystemErrorShrt" : "Defecţiune AFS",
    "AutoLevelSystemErrorShrt" : "Defecţiune sist. regl. autom. nivel",
    "IstopSysErrorShrt" : "Defecţiune sistem i-stop",
    "TpmsSysErrorShrt" : "Defecţiune sistem TPMS",
    "KeylesSysErrorShrt" : "Defecţiune acces fără cheie",
    "FWDSysErrorShrt" : "Defecţiune sistem 4WD",
    "DPFErrorShrt" : "Eroare DPF",
    "AutoTransSysErrorShrt" : "Defecţiune transmisie automată",
    "BattManagSysErrorShrt" : "Defecţiune sist. gest. baterie",
    "BrakOverrideSysErrorShrt" : "Defecţiune sist. antibloc. acceler.",
    "MRCCSysErrorShrt" : "Defecţiune MRCC",
    "SBSSysErrorShrt" : "Defecţiune SBS",
    "FOWSysError" : "Defecţiune FOW",
    "DRSSSysErrorShrt" : "Defecţiune DRSS",
    "FOWMRCCRadarSoilingShrt" : "Defecţiune radar FOW/MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Defecţ. radar FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Defecţiune radar SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Defecţ. radar SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC indisponibil",
    "SBSBrakeUnavailableShrt" : "Frână SBS indisponibilă",
    "SBSBrakeMRCCUnavailableShrt" : "Frână SBS/MRCC indisponibilă",
    "SCBSSysErrorShrt" : "Defecţiune SCBS",
    "SCBSWindshieldSoilingShrt" : "Defecţiune SCBS",
    "SCBSUnavailableShrt" : "SCBS indisponibil",
    "LDWSSysErrorShrt" : "Defecţiune LDWS",
    "HBCSysErrorShrt" : "Defecţiune HBC",
    "HBCLLDWSCamDisconnectShrt" : "Defecţiune HBC/cameră LDWS",
    "HBCLDWSSysErrorShrt" : "Defecţiune HBC/sistem LDWS",
    "HBCLDWSWindshieldFogShrt" : "Defecţiune HBC/sistem LDWS",
    "SedimenterWarningShrt" : "Control sedimentator",
    "FuelAirFilterCartReplacePeriodShrt" : "Înloc. cartuş filtru combust.-aer",
    "VehicleSysErrorShrt" : "Defecţiune sistem vehicul",
    "LowWasheFluidShrt" : "Nivel redus lichid de parbriz",
    "EngineWaterTempDropShrt" : "Temp. lichid de răcire scăzută",
    "PreheatingDispLampShrt" : "Preîncălzire bujii incandescente",
    "AuxBattLowLong" : "Nivelul de încărcare al bateriei de 12 V este scăzut.\n・Dacă acest indicator se aprinde frecvent în timpul condusului, este posibil ca bateria să fie deteriorată. Solicitaţi verificarea vehiculului de către reprezentanţă.\n・În cazul în care acest indicator este aprins în mod constant şi nu se stinge, bateria de 12V este complet nefuncţională. Consultaţi manualul de utilizare înainte de a porni sistemul hibrid şi solicitaţi verificarea vehiculului de către reprezentanţă.",
    "DriveBattDropLong" : "Puterea reziduală din bateria de înaltă tensiune este redusă deoarece transmisia a fost în poziţia Neutru pentru o lungă perioadă de timp.\nÎncărcarea nu se poate realiza cu transmisia în poziţia Neutru. Alegeţi poziţia de Parcare pentru staţionarea îndelungată.\nReporniţi sistemul hibrid apăsând butonul de alimentare dacă este cazul.",
    "ControlSystemErrorLong" : "Defecţiune sistem de control al poziţiei de parcare.\nDacă nu este verificată, poate genera una dintre următoarele probleme:\n・Este posibil ca mecanismul de blocare la parcare să nu funcţioneze. Parcaţi într-un loc plan şi acţionaţi ferm frâna de parcare.\n・Este posibil ca butonul de alimentare să nu se dezactiveze. Apăsaţi repetat butonul de alimentare pentru a dezactiva.\n・ Mesajul „Acţionaţi frâna de parcare când parcaţi” se va dezactiva când conduceţi şi se va activa când opriţi.\nSolicitaţi imediat verificarea vehiculului la reprezentanţă.\n",
    "EngineOilPressureErrorLong" : "Presiune ulei de motor scăzută.\nOpriţi imediat vehiculul într-un loc sigur, opriţi motorul şi verificaţi nivelul uleiului de motor. Adăugaţi ulei dacă este cazul.\nSolicitaţi imediat verificarea vehiculului la reprezentanţă dacă acest indicator se aprinde după ce aţi completat cu ulei sau dacă nivelul de ulei de motor este corect.\n",
    "HybridSysErrorLong" : "Defecţiune sistem hibrid.\nVehiculul poate suferi avarii în cazul în care continuaţi să conduceţi. Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.\n\n",
    "HybridSysOverheatLong" : "Defecţiune sistem hibrid.\nVehiculul poate suferi avarii în cazul în care continuaţi să conduceţi. Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.",
    "PpositionRequestLong" : "Cuplaţi transmisia în poziţia Parcare.\nAceasta este provocată de unul dintre următorii factori:\n・ Sistemul bateriei a fost pornit sau oprit cu transmisia în altă poziţie decât Parcare\n・ Uşa şoferului a fost deschisă cu transmisia în poziţia N, D sau B\n・ Nivelul de încărcare rezidual al bateriei de înaltă tensiune este scăzut deoarece transmisia a fost în poziţia Neutru pentru o lungă perioadă de timp\nReporniţi sistemul hibrid apăsând butonul de alimentare dacă este cazul.\n",
    "ChargingSysErrorLong" : "Defecţiune sistem de încărcare. Vehiculul poate suferi avarii în cazul în care continuaţi să conduceţi.  Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.",
    "BrakeSysErrorLong" : "Nivelul lichidului de frână este scăzut sau sistemul de frânare s-a defectat.  Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.",
    "EcbSysErrorLong" : "Defecţiune la sistemul de frânare regenerativă sau la sistemul de frânare controlată electronic.\nOpriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.\n",
    "AbsSysErrorLong" : "Defecţiune sistem antiblocare frână (ABS).\nSolicitaţi imediat verificarea vehiculului la reprezentanţă.\n",
    "DscSysErrorLong" : "Defecţiune la controlul dinamic al stabilităţii (DSC), sistemul de control al tracţiunii (TCS) sau pornirea asistată în pantă (HLA). Solicitaţi imediat verificarea vehiculului la reprezentanţă.",
    "DropKeyBattChrgLong" : "Bateria cheii este în curs de epuizare. Înlocuiţi imediat bateria cheii.",
    "EngOilPressureErrorLong" : "Presiune ulei de motor scăzută.\nOpriţi imediat vehiculul într-un loc sigur, opriţi motorul şi verificaţi nivelul uleiului de motor. Adăugaţi ulei dacă este cazul.\nSolicitaţi imediat verificarea vehiculului la reprezentanţă dacă acest indicator se aprinde după ce aţi completat cu ulei sau dacă nivelul de ulei de motor este corect.\n",
    "ChrgSysErrorLong" : "Defecţiune sistem de încărcare.\nOpriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.\n",
    "EloopSysErrorLong" : "Defecţiune sistem i-ELOOP.\nSolicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "EloopChargingLong" : "Se încarcă i-ELOOP.\nCu motorul pornit, verificaţi dacă s-a încheiat încărcarea şi dacă indicatorul de avertizare s-a stins. Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "LowBrakeFluidLong" : "Nivelul lichidului de frână este scăzut. Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.",
    "BrakeSystemErrorLong" : "Defecţiune la sistemul de frânare cu comandă electronică. Opriţi imediat vehiculul într-un loc sigur şi solicitaţi verificarea sa de către reprezentanţă.",
    "LowTireAirPressureLong" : "Presiune scăzută în unul sau mai multe pneuri.\nVerificaţi presiunea în pneuri şi aduceţi-o la nivelul corect.  Apăsaţi comutatorul TMPS SET după ce aţi reglat presiunea în pneuri până ce auziţi un semnal sonor.\n",
    "EngCoolntTempHighOnLong" : "Motorul se supraîncălzeşte. Opriţi imediat vehiculul într-un loc sigur, opriţi motorul şi luaţi măsurile necesare.  Consultaţi manualul de utilizare.",
    "EngineWaterTempRiseLong" : "Motorul începe să se supraîncălzească. Rulaţi cu viteză mică sau opriţi vehiculul până ce indicatorul nu se mai aprinde. Dacă acesta continuă să se aprindă, chiar şi după ce aţi oprit vehiculul, luaţi măsurile necesare. Consultaţi manualul de utilizare.",
    "SystemInspectionLong" : "Temperatura uleiului din diferenţial este anormal de ridicată sau a apărut o diferenţă semnificativă de viteză de rotaţie între pneurile faţă şi spate (ca atunci când încercaţi să ieşiţi din noroi).\nOpriţi vehiculul într-un loc sigur şi continuaţi să conduceţi după ce indicatorul de avertizare s-a dezactivat. Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "AccumulationDpfLong" : "Particulele colectate în filtrul de particule diesel (DPF) au depăşit valoarea reglementată.\nConduceţi aproximativ 10-15 minute cu motorul bine încălzit (indicatorul albastru de temperatură dezactivat) la o viteză de 10 mph (15 km/h) sau mai mare pentru a elimina particulele.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "RoadSurfaceIcingCautionLong" : "Temperatura exterioară este de 4 °C sau mai mică.\nAveţi grijă la porţiunile cu polei de pe carosabil în timp ce conduceţi.\n",
    "LowFuelLong" : "Nivelul din rezervorul de combustibil este scăzut. Alimentaţi vehiculul cât mai curând.",
    "FuelCapInspectionLong" : "Este posibil să nu fie fixat corect capacul de alimentare cu combustibil.\nVerificaţi dacă a fost fixat şi strâns corect capacul de alimentare cu combustibil.\nDupă fixarea şi strângerea capacului de alimentare cu combustibil, acest indicator nu se va dezactiva timp de câteva cicluri de conducere până când se poate confirma că sistemul funcţionează corespunzător.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "PowerSteeringSysErrorLong" : "Defecţiune la servodirecţia electrică. Staţionaţi într-un loc sigur şi opriţi motorul.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "EngSystemErrorLong" : "Defecţiune sistem motor.  Solicitaţi imediat verificarea vehiculului la reprezentanţă.",
    "AirbagSysPretensionerSysErrorLong" : "Defecţiune airbag/centură de siguranţă.\nSolicitaţi imediat verificarea vehiculului la reprezentanţă\n",
    "AbsSystemErrorLong" : "Defecţiune sistem antiblocare frână (ABS).\nSolicitaţi imediat verificarea vehiculului la reprezentanţă.\n",
    "DscSystemErrorLong" : "Defecţiune la controlul dinamic al stabilităţii (DSC) sau la sistemul de control al tracţiunii (TCS). Solicitaţi imediat verificarea vehiculului la reprezentanţă.",
    "RvmSysErrorLong" : "Există o eroare în sistemul RVM. Verificaţi dacă suprafaţa barei spate prezintă anomalii şi curăţaţi-o dacă este murdară sau acoperită cu zăpadă. Solicitaţi verificarea vehiculului la o reprezentanţă Mazda dacă acest indicator de avertizare rămâne aprins.",
    "BsmSystemErrorLong" : "Defecţiune la Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nVerificaţi dacă suprafaţa barei spate prezintă anomalii şi curăţaţi-o dacă este murdară sau acoperită cu zăpadă. Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "AfsSystemErrorLong" : "Defecţiune la sistemul de faruri adaptive (AFS).  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul continuă să se aprindă intermitent.",
    "AutoLevelSystemErrorLong" : "Defecţiune la sistemul de reglare automată a nivelului farurilor. Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "IstopSysErrorLong" : "Utilizarea i-stop nu este posibilă. Solicitaţi verificarea vehiculului la o reprezentanţă Mazda.",
    "TpmsSysErrorLong" : "Defecţiune la sistemul de monitorizare a presiunii în pneuri (TPMS). Solicitaţi verificarea vehiculului la reprezentanţă.",
    "KeylesSysErrorLong" : "Defecţiune sistem de acces fără cheie. Solicitaţi verificarea vehiculului la reprezentanţă.",
    "FWDSysErrorLong" : "Defecţiune sistem 4WD sau dimensiunea pneurilor faţă este diferită de cea a pneurilor spate.\nSolicitaţi verificarea vehiculului la reprezentanţă.\n",
    "DPFErrorLong" : "Defecţiune filtru de particule diesel (DPF). Solicitaţi verificarea vehiculului la reprezentanţă.",
    "AutoTransSysErrorLong" : "Defecţiune transmisie automată.\nVehiculul poate suferi avarii în cazul în care continuaţi să conduceţi.  Solicitaţi imediat verificarea vehiculului la reprezentanţă.  \n",
    "BattManagSysErrorLong" : "Defecţiune la sistemul de gestionare a bateriei.\nSolicitaţi verificarea vehiculului la reprezentanţă.\n",
    "BrakOverrideSysErrorLong" : "Defecţiune la contactorul frânei. Solicitaţi imediat verificarea vehiculului la reprezentanţă.",
    "MRCCSysErrorLong" : "Defecţiune la Mazda Radar Cruise Control (MRCC). Solicitaţi verificarea vehiculului la reprezentanţă.",
    "SBSSysErrorLong" : "Există o eroare în sistemul SBS. Solicitaţi verificarea vehiculului la o reprezentanţă Mazda.",
    "FOWSysErrorLong" : "Defecţiune la Forward Obstruction Warning (FOW). Solicitaţi verificarea vehiculului la reprezentanţă.",
    "DRSSSysErrorLong" : "Există o eroare în sistemul DRSS. Solicitaţi verificarea vehiculului la o reprezentanţă Mazda.",
    "FOWMRCCRadarSoilingLong" : "Defecţiune radar (senzor) FOW/MRCC. Curăţaţi întreaga suprafaţă a siglei de pe masca frontală dacă este murdară sau acoperită de zăpadă.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "FOWMRCCDRSSRadarSoilingLong" : "Radarul (senzorul) FOW/MRCC/DRSS s-a murdărit.\nCurăţaţi întreaga suprafaţă a radarului (senzorului).\n",
    "SBSMRCCRadarSoilingLong" : "Radarul (senzorul) SBS/MRCC s-a murdărit.\nCurăţaţi întreaga suprafaţă a radarului (senzorului).\n",
    "SBSMRCCDRSSRadarSoilingLong" : "Radarul (senzorul) SBS/MRCC/DRSS s-a murdărit.\nCurăţaţi întreaga suprafaţă a radarului (senzorului).\n",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) este momentan indisponibil.",
    "SBSBrakeUnavailableLong" : "Frână SBS momentan indisponibilă.",
    "SBSBrakeMRCCUnavailableLong" : "Frână SBS/MRCC momentan indisponibile.",
    "SCBSSysErrorLong" : "Defecţiune la Smart City Brake Support (SCBS) .\nSolicitaţi imediat verificarea vehiculului la reprezentanţă.",
    "SCBSWindshieldSoilingLong" : "Defecţiune la Smart City Brake Support (SCBS).\nCurăţaţi parbrizul.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS)  este momentan indisponibil.",
    "LDWSSysErrorLong" : "Defecţiune la Lane Departure Warning System (LDWS).\nSolicitaţi verificarea vehiculului la reprezentanţă.",
    "HBCSysErrorLong" : "Defecţiune la High Beam Control (HBC). Solicitaţi verificarea vehiculului la reprezentanţă.",
    "HBCLLDWSCamDisconnectLong" : "Defecţiune la High Beam Control (HBC)/Lane Departure Warning System (LDWS. Curăţaţi parbrizul.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "HBCLDWSSysErrorLong" : "Defecţiune la High Beam Control (HBC)/Lane Departure Warning System (LDWS). Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "HBCLDWSWindshieldFogLong" : "Defecţiune la High Beam Control (HBC)/Lane Departure Warning System (LDWS). Dejivraţi parbrizul.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "SedimenterWarningLong" : "Cantitatea de apă acumulată în sedimentator depăşeşte cantitatea nominală.\nSolicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.\n",
    "FuelAirFilterCartReplacePeriodLong" : "Cartuşul filtrului combustibil-aer necesită înlocuire.",
    "VehicleSysErrorLong" : "Defecţiune sistem vehicul. Solicitaţi verificarea vehiculului la reprezentanţă.",
    "LowWasheFluidLong" : "Nivelul lichidului de parbriz este scăzut. Completaţi cu lichid de parbriz.",
    "EngineWaterTempDropLong" : "Lichidul de răcire este rece, iar radiatorul/dejivrorul nu dispun de aer cald. Vehiculul poate fi condus cu indicatorul activat sau dezactivat.  Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "PreheatingDispLampLong" : "Se încălzesc bujiile incandescente. Solicitaţi verificarea vehiculului la reprezentanţă dacă indicatorul rămâne aprins.",
    "HybrdSysMalHighPrt" : "Defecţiune sistem hibrid. Opriţi imediat vehiculul la loc sigur.",
    "ChargSysMalHighPrt" : "Defecţiune sistem de încărcare. Opriţi imediat vehiculul la loc sigur.",
    "IeloopChrgHighPrt" : "Se încarcă i-ELOOP. Cu motorul pornit, verificaţi dacă încărcarea este completă şi dacă martorul de avertizare este oprit.",
    "EngnCoolTempHighHighPrt" : "Temperatură lichid de răcire motor ridicată. Opriţi imediat vehiculul la loc sigur.",
    "lowBattStartEngine" : "Baterie scăzută! Porniţi motorul!",
    "engineOilPressure" : "Presiunea uleiului de motor",
    "brakeFluid" : "Lichid de frână scăzut",
    "highVoltage" : "Baterie de voltaj mare scăzută",
};

framework.registerAppDictLoaded("warnguide", "ro_RO");