var Localization_warnguideAppDict_fi_FI = {
    //"stringId" : "localString"
    "Warnings" : "Varoituksia",
    "NoWarnings" : "Ei varoituksia",
    "WarningSafetyMessage" : "Varoituksia ei näytetä turvallisuussyistä.",
    "WarningGuidance" : "Varoitukset",
    "AuxBattLowShrt" : "12 V akku lähes tyhjä",
    "DriveBattDropShrt" : "Korkeajänniteakku lähes tyhjä",
    "ControlSystemErrorShrt" : "P-asennon valvontajärj. häiriö",
    "EngineOilPressureErrorShrt" : "Alhainen moottorin öljynpaine",
    "HybridSysErrorShrt" : "Hybridijärjestelmän toimintahäiriö",
    "HybridSysOverheatShrt" : "Hybridijärjestelmä ylikuumenee",
    "PpositionRequestShrt" : "Pysäköintiasentopyyntö",
    "ChargingSysErrorShrt" : "Latausjärjestelmän toimintahäiriö",
    "BrakeSysErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
    "EcbSysErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
    "AbsSysErrorShrt" : "ABS-jarrujen toimintahäiriö",
    "DscSysErrorShrt" : "DSC-järjestelmän toimintahäiriö",
    "DropKeyBattChrgShrt" : "Avaimen pariston virta vähissä",
    "EngOilPressureErrorShrt" : "Alhainen moottorin öljynpaine",
    "ChrgSysErrorShrt" : "Latausjärjestelmän toimintahäiriö",
    "EloopSysErrorShrt" : "i-ELOOP-järjestelmän toim.häiriö",
    "EloopChargingShrt" : "i-ELOOP latautuu",
    "LowBrakeFluidShrt" : "Alhainen jarrunesteen määrä",
    "BrakeSystemErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
    "LowTireAirPressureShrt" : "Alhainen rengaspaine",
    "EngCoolntTempHighOnShrt" : "Jäähd.nesteen korkea lämpötila",
    "EngineWaterTempRiseShrt" : "Jäähd.nesteen korkea lämpötila",
    "SystemInspectionShrt" : "Nelivetojärjestelmän tarkistus",
    "AccumulationDpfShrt" : "Hiukkaskeräänt. DPF-suotimessa",
    "RoadSurfaceIcingCautionShrt" : "Jäätyneen tienpinnan varoitus",
    "LowFuelShrt" : "Polttoaine vähissä",
    "FuelCapInspectionShrt" : "Polttoainekorkin tarkistus",
    "PowerSteeringSysErrorShrt" : "Ohjaustehostimen toimintahäiriö",
    "EngSystemErrorShrt" : "Moottorijärjestelmän häiriö",
    "AirbagSysPretensionerSysErrorShrt" : "Turvatyynyn/vyönkiristimen häiriö",
    "AbsSystemErrorShrt" : "ABS-jarrujen toimintahäiriö",
    "DscSystemErrorShrt" : "DSC-järjestelmän toimintahäiriö",
    "RvmSysErrorShrt" : "RVM-järjestelmän toimintahäiriö",
    "BsmSystemErrorShrt" : "BSM-järjestelmän toimintahäiriö",
    "AfsSystemErrorShrt" : "AFS-valojen toimintahäiriö",
    "AutoLevelSystemErrorShrt" : "Autom. tasonsäädön häiriö",
    "IstopSysErrorShrt" : "i-stop-järjestelmän toimintahäiriö",
    "TpmsSysErrorShrt" : "TPMS-järjestelmän toimintahäiriö",
    "KeylesSysErrorShrt" : "Avaimettoman käytön häiriö",
    "FWDSysErrorShrt" : "Nelivetojärjestelmän häiriö",
    "DPFErrorShrt" : "Hiukkassuodattimen häiriö",
    "AutoTransSysErrorShrt" : "Automaattivaihteiston häiriö",
    "BattManagSysErrorShrt" : "Akunhallintajärjestelmän häiriö",
    "BrakOverrideSysErrorShrt" : "Jarrujen ohitusjärjestelmän häiriö",
    "MRCCSysErrorShrt" : "MRCC-järjestelmän toimintahäiriö",
    "SBSSysErrorShrt" : "SBS-järjestelmän toimintahäiriö",
    "FOWSysError" : "FOW-järjestelmän toimintahäiriö",
    "DRSSSysErrorShrt" : "DRSS-järjestelmän toimintahäiriö",
    "FOWMRCCRadarSoilingShrt" : "FOW/MRCC-tutkan toimintahäiriö",
    "FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS-tutkan häiriö",
    "SBSMRCCRadarSoilingShrt" : "SBS-/MRCC-tutkan toimintahäiriö",
    "SBSMRCCDRSSRadarSoilingShrt" : "SBS-/MRCC-/DRSS-tutkan häiriö",
    "MRCCUnavailableShrt" : "MRCC-järj. ei ole käytettävissä",
    "SBSBrakeUnavailableShrt" : "SBS-jarrutus ei ole käytettävissä",
    "SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC ei ole käytettävissä",
    "SCBSSysErrorShrt" : "SCBS-järjestelmän toimintahäiriö",
    "SCBSWindshieldSoilingShrt" : "SCBS-järjestelmän toimintahäiriö",
    "SCBSUnavailableShrt" : "SCBS-järj. ei ole käytettävissä",
    "LDWSSysErrorShrt" : "Kaistavahdin toimintahäiriö",
    "HBCSysErrorShrt" : "Kaukovalojärj. (HBC) häiriö",
    "HBCLLDWSCamDisconnectShrt" : "HBC/LDWS-kameran häiriö",
    "HBCLDWSSysErrorShrt" : "HBC/LDWS-kameran häiriö",
    "HBCLDWSWindshieldFogShrt" : "HBC/LDWS-kameran häiriö",
    "SedimenterWarningShrt" : "Vedenerottimen tarkastus",
    "FuelAirFilterCartReplacePeriodShrt" : "Polttoaine- ja ilmansuodatin täytyy vaihtaa",
    "VehicleSysErrorShrt" : "Auton järjestelmän toimintahäiriö",
    "LowWasheFluidShrt" : "Lasinpesuneste vähissä",
    "EngineWaterTempDropShrt" : "Jäähd.nesteen alhainen lämpötila",
    "PreheatingDispLampShrt" : "Hehkutus käynnissä",
    "AuxBattLowLong" : "12 V akun varaus on vähissä.\n・Jos tämä merkkivalo palaa useasti ajon aikana, akun kunto on voinut heikentyä. Tarkistuta auto myyjäliikkeessä.\n・Jos tämä merkkivalo palaa jatkuvasti ajon aikana, 12 V akku on täysin tyhjä / ei toimi. Katso lisätietoja Omistajan käsikirjasta ennen hybridijärjestelmän käynnistämistä ja tarkistuta auto Mazda-liikkeessä.",
    "DriveBattDropLong" : "Korkeajänniteakun varaus on alhainen, koska vaihde oli pitkään vapaalla (Neutral-asennossa). Lataus ei toimi, kun vaihde on vapaalla (Neutral). Aseta vaihde P-asentoon, kun olet pysähdyksissä pitkään. Käynnistä hybridijärjestelmä tarvittaessa uudelleen virtapainikkeesta.",
    "ControlSystemErrorLong" : "Pysäköintiasennon valvontajärjestelmän toimintahäiriö.\nJos tätä ei valita, seurauksena voi olla jokin seuraavista tilanteista:\n・Pysäköintijarrun mekanismi ei toimi välttämättä. Pysäköi tasaiseen paikkaan ja kytke pysäköintijarru huolellisesti.\n・Virtakytkin ei mene Off-asentoon. Sammuta virta painamalla virtakytkintä toistuvasti.\n・ \"Kytke pysäköintijarru pysäköitäessä\" -näyttö sammuu ajettaessa ja syttyy pysähdyttäessä.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "EngineOilPressureErrorLong" : "Alhainen moottorin öljynpaine.\nPysäytä auto välittömästi turvalliseen paikkaan, sammuta moottori ja tarkista moottoriöljyn määrä. Lisää öljyä tarvittaessa.\nTarkistuta auto välittömästi myyjäliikkeessä, jos tämä merkkivalo syttyy öljyn lisäämisen jälkeen tai jos moottorissa on riittävästi öljyä.\n",
    "HybridSysErrorLong" : "Hybridijärjestelmän toimintahäiriö.\nAuto saattaa rikkoutua, jos jatkat ajamista. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.\n",
    "HybridSysOverheatLong" : "Hybridijärjestelmän toimintahäiriö.\nAuto saattaa rikkoutua, jos jatkat ajamista. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "PpositionRequestLong" : "Vaihda P- eli pysäköintivaihteelle.\nSyynä on jokin seuraavista:\n・ Akkujärjestelmä käynnistettiin tai sammutettiin, kun jokin muu kuin P-vaihde oli päällä\n・ Kuljettajan ovi avattiin, kun N-, D- tai B-vaihde oli päällä\n・ Vara-akun varaus on alhainen, koska vaihde oli pitkään vapaalla (Neutral-asennossa)\nKäynnistä hybridijärjestelmä tarvittaessa uudelleen virtapainikkeesta.",
    "ChargingSysErrorLong" : "Latausjärjestelmän toimintahäiriö. \nAuto saattaa rikkoutua, jos jatkat ajamista.  Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.\n",
    "BrakeSysErrorLong" : "Jarruneste vähissä tai jarrujärjestelmässä toimintahäiriö.  Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "EcbSysErrorLong" : "Jarrutehon talteenoton tai sähköisesti ohjatun jarrujärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "AbsSysErrorLong" : "Lukkiutumattomien jarrujen (ABS) toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "DscSysErrorLong" : "Ajonvakautusjärjestelmän (DSC), luistonestojärjestelmän (TCS) tai mäkilähtöavustimen (HLA) toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "DropKeyBattChrgLong" : "Avaimen pariston varaus on vähissä.\nVaihda avaimen paristo välittömästi.\n",
    "EngOilPressureErrorLong" : "Alhainen moottorin öljynpaine.\nPysäytä auto välittömästi turvalliseen paikkaan, sammuta moottori ja tarkista moottoriöljyn määrä. Lisää öljyä tarvittaessa.\nTarkistuta auto välittömästi myyjäliikkeessä jos tämä merkkivalo syttyy öljyn lisäämisen jälkeen tai jos moottorissa on riittävästi öljyä.\n",
    "ChrgSysErrorLong" : "Latausjärjestelmän toimintahäiriö.\nPysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "EloopSysErrorLong" : "i-ELOOP-järjestelmän toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "EloopChargingLong" : "i-ELOOP latautuu.\nKun moottori on käynnissä, tarkista että lataus on suoritettu loppuun ja että varoitusvalo on sammunut. Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "LowBrakeFluidLong" : "Jarruneste on vähissä.\nPysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "BrakeSystemErrorLong" : "Sähköisen jarrujärjestelmän toimintahäiriö.\nPysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto Mazda-liikkeessä.",
    "LowTireAirPressureLong" : "Alhainen rengaspaine vähintään yhdessä renkaassa.\nTarkista renkaiden ilmanpaineet ja säädä tarvittaessa oikeaan arvoon.  Kun renkaiden ilmanpaineet on säädetty, paina TPMS SET -kytkintä niin kauan että kuulet äänimerkin.",
    "EngCoolntTempHighOnLong" : "Moottori ylikuumenee.\nPysäytä ajoneuvo välittömästi turvalliseen paikkaan, sammuta moottori ja ryhdy tarvittaviin toimenpiteisiin.  Katso lisätietoja omistajan käsikirjasta.\n",
    "EngineWaterTempRiseLong" : "Moottori alkaa kuumentua.\nAja hitaasti tai pysäytä auto ja odota, että merkkivalo lakkaa vilkkumasta. Jos merkkivalo ei lakkaa vilkkumasta auton pysäyttämisen jälkeen, ryhdy tarvittaviin toimenpiteisiin. Katso lisätietoja omistajan käsikirjasta.\n",
    "SystemInspectionLong" : "Tasauspyörästön öljyn lämpötila on epätavallisen korkea tai etu- ja takarenkaiden pyörimisnopeuksissa on ollut merkittäviä eroja (esimerkiksi mudasta lähdettäessä).\nPysäytä auto turvalliseen paikkaan ja jatka vasta kun varoitusvalo on sammunut. Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.\n",
    "AccumulationDpfLong" : "Diesel-järjestelmän hiukkassuodattimeen (DPF) kerääntynyt hiukkasmassa ylittää sallitun arvon.\nAja noin 10–15 minuuttia vähintään 15 km/h:n (10 mph) nopeudella niin, että moottori on lämmennyt kokonaan (sininen lämpötilavalo on sammunut), jotta hiukkasmassa poistuu suodattimesta.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "RoadSurfaceIcingCautionLong" : "Ulkolämpötila on enintään 4 °C.\nVaro jäisiä tienpintoja.\n",
    "LowFuelLong" : "Polttoaine on vähissä.\nTankkaa auto pian.\n",
    "FuelCapInspectionLong" : "Polttoainesäiliön korkki ei ole välttämättä kunnolla paikoillaan.\nTarkista, että polttoainesäiliön korkki on paikoillaan ja riittävän tiukasti kiinni.\nKun polttoainesäiliön korkki on asetettu paikoilleen ja kiristetty huolellisesti, merkkivalo sammuu vasta muutaman ajokerran jälkeen, kun kaikki on varmasti kunnossa.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "PowerSteeringSysErrorLong" : "Sähköisen ohjaustehostimen toimintahäiriö.\nPysäytä auto turvalliseen paikkaan ja sammuta moottori.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "EngSystemErrorLong" : "Moottorijärjestelmän toimintahäiriö.  Tarkistuta auto välittömästi Mazda-liikkeessä.",
    "AirbagSysPretensionerSysErrorLong" : "Turvatyynyn/turvavyön toimintahäiriö.",
    "AbsSystemErrorLong" : "Lukkiutumattomien jarrujen (ABS) toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "DscSystemErrorLong" : "Ajonvakautusjärjestelmän (DSC) tai luistonestojärjestelmän (TCS) toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "RvmSysErrorLong" : "RVM-järjestelmässä on virhe.\nTarkista, ettei takapuskurin pinnassa näy mitään epätavallista ja puhdista puskuri, jos se on lian tai lumen peitossa.\nTarkistuta auto Mazda-liikkeessä jos tämä varoitusvalo ei sammu.",
    "BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/ Rear Cross Traffic Alert (RCTA) toimintahäiriö.\nTarkista, ettei takapuskurin pinnassa näy mitään epätavallista ja puhdista puskuri, jos se on lian tai lumen peitossa. Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "AfsSystemErrorLong" : "Mukautuvien etuvalojen (AFS) toimintahäiriö.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei lakkaa vilkkumasta.",
    "AutoLevelSystemErrorLong" : "Ajovalojen korkeudensäädön toimintahäiriö\nTarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "IstopSysErrorLong" : "i-stop ei voi käyttää.\nTarkistuta auto Mazda-liikkeessä.\n",
    "TpmsSysErrorLong" : "Rengaspaineen valvontajärjestelmän (TPMS) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "KeylesSysErrorLong" : "Avaimeton käyttö -järjestelmän toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "FWDSysErrorLong" : "Nelivetojärjestelmän toimintahäiriö tai edessä ja takana on erikokoiset renkaat.\nTarkistuta auto Mazda-liikkeessä.",
    "DPFErrorLong" : "Dieselin hiukkassuodattimen (DPF) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "AutoTransSysErrorLong" : "Automaattivaihteiston toimintahäiriö.\nAuto saattaa rikkoutua, jos jatkat ajamista.  Tarkistuta auto välittömästi Mazda-liikkeessä.  ",
    "BattManagSysErrorLong" : "Akunhallintajärjestelmän toimintahäiriö. Tarkistuta auto Mazda-liikkeessä.",
    "BrakOverrideSysErrorLong" : "Jarrukytkimen toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "SBSSysErrorLong" : "SBS-järjestelmässä on virhe.\nTarkistuta auto Mazda-liikkeessä.\n",
    "FOWSysErrorLong" : "Forward Obstruction Warning (FOW) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "DRSSSysErrorLong" : "DRSS-järjestelmässä on virhe.\nTarkistuta auto Mazda-liikkeessä.\n",
    "FOWMRCCRadarSoilingLong" : "FOW/MRCC-tutkan (anturin) toimintahäiriö.\nPuhdista etupuskuri kauttaaltaan, jos se on lian tai lumen peitossa.  \nTarkistuta auto Mazda-liikkeessä, jos merkkivalo ei sammu.",
    "FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
    "SBSMRCCRadarSoilingLong" : "SBS/MRCC-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
    "SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
    "MRCCUnavailableLong" : "Mazda MRCC-vakionopeussäädin ei ole tällä hetkellä käytettävissä.",
    "SBSBrakeUnavailableLong" : "SBS-jarrutustoiminto ei ole tällä hetkellä käytettävissä.",
    "SBSBrakeMRCCUnavailableLong" : "SBS-jarrutustoiminto/MRCC-vakionopeussäädin ei ole tällä hetkellä käytettävissä.",
    "SCBSSysErrorLong" : "Smart City Brake Support (SCBS) toimintahäiriö.\nTarkistuta auto välittömästi Mazda-liikkeessä.",
    "SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) toimintahäiriö.\nPuhdista tuulilasi.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "SCBSUnavailableLong" : "Smart City Brake Support  (SCBS) ei ole tällä hetkellä käytettävissä.",
    "LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.\n",
    "HBCSysErrorLong" : "High Beam Control (HBC) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS)  toimintahäiriö.\nPuhdista tuulilasi.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "HBCLDWSSysErrorLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) toimintahäiriö. Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) toimintahäiriö.\nPoista huurre tuulilasista.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "SedimenterWarningLong" : "Vedenerottimeen kertynyt vesi ylittää suunnitellut määrän.\nTarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "FuelAirFilterCartReplacePeriodLong" : "Polttoaine- ja ilmansuodatin on vaihdettava.",
    "VehicleSysErrorLong" : "Auton järjestelmän toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
    "LowWasheFluidLong" : "Lasinpesuneste on vähissä. Lisää lasinpesunestettä.",
    "EngineWaterTempDropLong" : "Jäähdytysneste on kylmää eikä lämmityslaite/lasinlämmitin saa mistään lämmintä ilmaa. Autoa voi ajaa vaikka tämä merkkivalo palaa.  Tarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "PreheatingDispLampLong" : "Hehkutus käynnissä.\nTarkistuta auto Mazda-liikkeessä jos merkkivalo ei sammu.",
    "HybrdSysMalHighPrt" : "Hybridijärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan.",
    "ChargSysMalHighPrt" : "Latausjärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan.",
    "IeloopChrgHighPrt" : "i-ELOOP latautuu. Kun moottori on käynnissä, tarkista että lataus on valmis ja varoitusvalo sammunut.",
    "EngnCoolTempHighHighPrt" : "Jäähdytysnesteen korkea lämpötila. Pysäytä auto välittömästi turvalliseen paikkaan.",
    "lowBattStartEngine" : "Akku lähes tyhjä. Käynnistä auto!",
    "engineOilPressure" : "Moottorin öljynpaine",
    "brakeFluid" : "Jarruneste on vähissä",
    "highVoltage" : "Korkeajänniteakku lähes tyhjä",
};

framework.registerAppDictLoaded("warnguide", "fi_FI");