var Localization_warnguideAppDict_nl_NL = {
    //"stringId" : "localString"
    "Warnings" : "Waarschuwingen",
    "NoWarnings" : "Geen waarschuwingen gevonden",
    "WarningSafetyMessage" : "De waarschuwingsinformatie wordt om veiligheidsredenen niet weergegeven.",
    "WarningGuidance" : "Waarschuwing",
    "AuxBattLowShrt" : "12V Battery Low",
    "DriveBattDropShrt" : "High Voltage Battery Low",
    "ControlSystemErrorShrt" : "Park Position Control System Malfunction",
    "EngineOilPressureErrorShrt" : "Oliedruk motor laag",
    "HybridSysErrorShrt" : "Defect Hybride Systeem",
    "HybridSysOverheatShrt" : "Oververhitting hybride systeem",
    "PpositionRequestShrt" : "Park Position Request",
    "ChargingSysErrorShrt" : "Storing oplaadsysteem",
    "BrakeSysErrorShrt" : "Storing remsysteem",
    "EcbSysErrorShrt" : "Storing remsysteem",
    "AbsSysErrorShrt" : "Storing ABS",
    "DscSysErrorShrt" : "Storing DSC",
    "DropKeyBattChrgShrt" : "Key Battery Low",
    "EngOilPressureErrorShrt" : "Oliedruk motor laag",
    "ChrgSysErrorShrt" : "Storing oplaadsysteem",
    "EloopSysErrorShrt" : "Storing i-ELOOP-systeem",
    "EloopChargingShrt" : "i-ELOOP laadt op",
    "LowBrakeFluidShrt" : "Remvloeistofpeil laag",
    "BrakeSystemErrorShrt" : "Storing remsysteem",
    "LowTireAirPressureShrt" : "Bandendruk laag",
    "EngCoolntTempHighOnShrt" : "Hoge temperatuur motorkoelvloeistof",
    "EngineWaterTempRiseShrt" : "Hoge temperatuur motorkoelvloeistof",
    "SystemInspectionShrt" : "Inspectie 4WD-systeem",
    "AccumulationDpfShrt" : "Roetdeeltjes ophoping in DPF",
    "RoadSurfaceIcingCautionShrt" : "Waarschuwing glad wegdek",
    "LowFuelShrt" : "Brandstofpeil laag",
    "FuelCapInspectionShrt" : "Inspectie tankdop",
    "PowerSteeringSysErrorShrt" : "Storing stuurbekrachtiging",
    "EngSystemErrorShrt" : "Storing motorsysteem",
    "AirbagSysPretensionerSysErrorShrt" : "Stor. airbag/gordelspanning",
    "AbsSystemErrorShrt" : "Storing ABS",
    "DscSystemErrorShrt" : "Storing DSC",
    "RvmSysErrorShrt" : "Storing RVM",
    "BsmSystemErrorShrt" : "Storing BSM",
    "AfsSystemErrorShrt" : "Storing AFS",
    "AutoLevelSystemErrorShrt" : "Stor. autom. Koplampinstelling",
    "IstopSysErrorShrt" : "Storing i-stop systeem",
    "TpmsSysErrorShrt" : "Storing TPMS-systeem",
    "KeylesSysErrorShrt" : "Storing keyless entry",
    "FWDSysErrorShrt" : "Storing 4WD-systeem",
    "DPFErrorShrt" : "DPF-fout",
    "AutoTransSysErrorShrt" : "Storing Battery Management System",
    "BattManagSysErrorShrt" : "Storing Brake Override System",
    "BrakOverrideSysErrorShrt" : "Storing Brake Overridesysteem",
    "MRCCSysErrorShrt" : "Storing MRCC",
    "SBSSysErrorShrt" : "Storing SBS",
    "FOWSysError" : "Storing FOW",
    "DRSSSysErrorShrt" : "Storing DRSS",
    "FOWMRCCRadarSoilingShrt" : "Radarstoring FOW/MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Radarstoring FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Radarstoring SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Radarstoring SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC niet beschikbaar",
    "SBSBrakeUnavailableShrt" : "SBS-rem niet beschikbaar",
    "SBSBrakeMRCCUnavailableShrt" : "SBS-rem/MRCC niet beschikbaar",
    "SCBSSysErrorShrt" : "Storing SCBS",
    "SCBSWindshieldSoilingShrt" : "Storing SCBS",
    "SCBSUnavailableShrt" : "SCBS niet beschikbaar",
    "LDWSSysErrorShrt" : "Storing LDWS",
    "HBCSysErrorShrt" : "Storing HBC",
    "HBCLLDWSCamDisconnectShrt" : "Camerastoring HBC/LDWS",
    "HBCLDWSSysErrorShrt" : "Systeemstoring HBC/LDWS",
    "HBCLDWSWindshieldFogShrt" : "Systeemstoring HBC/LDWS",
    "SedimenterWarningShrt" : "Inspectie waterafscheider ",
    "FuelAirFilterCartReplacePeriodShrt" : "Vervang brandstof-/luchtfilter ",
    "VehicleSysErrorShrt" : "Systeemstoring voertuig",
    "LowWasheFluidShrt" : "Ruitenwisservloeistofpeil laag",
    "EngineWaterTempDropShrt" : "Temp. motorkoelvloeistof laag",
    "PreheatingDispLampShrt" : "Voorgloeien gloeibougies",
    "AuxBattLowLong" : "De 12V-accu is bijna leeg.\n・Als dit lampje vaak brandt tijdens het rijden, kan het zijn dat de accu capaciteit verloren heeft. Laat het voertuig nakijken door uw dealer.\n・Als dit lampje permanent brandt en niet uitgaat, is de 12V-accu leeg. Raadpleeg de gebruikershandleiding voordat u het hybride systeem start en laat het voertuig nakijken door uw dealer.",
    "DriveBattDropLong" : "Het resterende vermogen in de hoogspanningsaccu is laag omdat de versnelling langdurig in de vrijstand heeft gestaan.\nOpladen is niet mogelijk in de vrijstand. Schakel naar de parkeerstand wanneer het voertuig langdurig stilstaat.\nStart het hybride systeem indien nodig opnieuw op door op de start-/stopknop te drukken.\n",
    "ControlSystemErrorLong" : "Storing controlesysteem parkeerstand.\nIndien dit niet wordt nagekeken, kan dit leiden tot de volgende situaties:\n・Het parkeerblokkeringsmechanisme werkt niet. Parkeer op een vlakke locatie en trek de handrem stevig aan.\n・De start-/stopknop kan niet uitgeschakeld worden. Druk herhaaldelijk op de start-/stopknop om uit te schakelen.\n・De melding \"Handrem aantrekken bij het parkeren\" verdwijnt tijdens het rijden en verschijnt na het stoppen.\nLaat het voertuig onmiddellijk nakijken door de dealer.\n",
    "EngineOilPressureErrorLong" : "Motoroliedruk laag.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en controleer het motoroliepeil. Vul de olie indien nodig bij.\nLaat het voertuig onmiddellijk nakijken door een dealer als deze indicator aangaat nadat u de olie hebt bijgevuld of wanneer het oliepeil goed is.\n",
    "HybridSysErrorLong" : "Storing hybride systeem.\nHet voertuig kan schade oplopen als u blijft rijden. Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
    "HybridSysOverheatLong" : "Storing hybride systeem.\nHet voertuig kan schade oplopen als u blijft rijden. Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
    "PpositionRequestLong" : "Schakel de versnelling naar de parkeerstand.\nDit heeft een van de volgende oorzaken:\n・ Het accusysteem is gestart of gestopt terwijl de versnelling in een andere stand dan de parkeerstand stond\n・ De deur aan de bestuurderskant werd geopend terwijl de versnelling in de N-, D- of B-stand stond\n・De resterende lading in de hoogspanningsaccu is laag omdat de transmissie langdurig in de vrijstand heeft gestaan\nStart het hybride systeem indien nodig opnieuw op door op de start-/stopknop te drukken.",
    "ChargingSysErrorLong" : "Storing oplaadsysteem. \nHet voertuig kan schade oplopen als u blijft rijden.  Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
    "BrakeSysErrorLong" : "Remvloeistofpeil laag of storing remsysteem.  Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.",
    "EcbSysErrorLong" : "Storing regeneratief remmen of elektronisch bestuurd remsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
    "AbsSysErrorLong" : "Storing antiblokkeersysteem (ABS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "DscSysErrorLong" : "Storing Dynamic Stability Control (DSC), Traction Control System (TCS) of automatische remfunctie tegen wegrollen op een helling (HLA).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "DropKeyBattChrgLong" : "Sleutelbatterij laag.\nVervang de sleutelbatterij onmiddellijk.\n",
    "EngOilPressureErrorLong" : "Motoroliedruk laag.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en controleer het motoroliepeil. Vul de olie indien nodig bij.\nLaat het voertuig onmiddellijk nakijken door een dealer als deze indicator aangaat nadat u de olie hebt bijgevuld of wanneer het oliepeil goed is.\n",
    "ChrgSysErrorLong" : "Storing oplaadsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
    "EloopSysErrorLong" : "Storing i-ELOOP-systeem.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "EloopChargingLong" : "i-ELOOP wordt opgeladen.\nControleer terwijl de motor draait of het opladen voltooid is en de waarschuwingsindicator uit is. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "LowBrakeFluidLong" : "Remvloeistofpeil is laag.\nZet het voertuig onmiddellijk op een veilige plek stil en laat hem nakijken door een dealer.",
    "BrakeSystemErrorLong" : "Storing elektronisch bestuurd remsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat hem nakijken door een dealer.\n",
    "LowTireAirPressureLong" : "Lage bandenspanning in één of meer banden.\nControleer de luchtdruk van de banden en vul aan tot de juiste luchtdruk.  Druk na het aanpassen van de bandenspanning op de TPMS SET-schakelaar totdat u een piep hoort.\n",
    "EngCoolntTempHighOnLong" : "Motor raakt oververhit.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en neem gepaste maatregelen.  Raadpleeg de gebruikershandleiding.\n",
    "EngineWaterTempRiseLong" : "Motor wordt heet.\nRij langzaam of zet het voertuig stil totdat de indicator niet meer knippert. Neem gepaste maatregelen als de indicator ook na het stoppen blijft knipperen. Raadpleeg de gebruikershandleiding.",
    "SystemInspectionLong" : "De differentieelolietemperatuur is abnormaal hoog of er heeft zich een groot rotatieverschil voorgedaan tussen de voor- en achterbanden (bijvoorbeeld wanneer er geprobeerd wordt om los te komen uit de modder).\nZet het voertuig op een veilige plaats stil en rijd weer verder nadat de waarschuwingsindicator uit is gegaan. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "AccumulationDpfLong" : "De ophoping van roetdeeltjes (PM) in het roetfilter (DPF) heeft de voorgeschreven limiet overschreden.\nRijd gedurende 10 tot 15 minuten met een volledig opgewarmde motor (blauw temperatuurlicht uit) met een snelheid van 15 km/u of meer om de roetdeeltjes te elimineren.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "RoadSurfaceIcingCautionLong" : "Buitentemperatuur is 4 °C of lager.\nLet tijdens het rijden op glad wegdek.\n",
    "LowFuelLong" : "Brandstofpeil is laag.\nU moet binnenkort tanken.\n",
    "FuelCapInspectionLong" : "De tankdop is mogelijk niet goed geplaatst.\nControleer of de tankdop goed geplaatst en vastgedraaid is.\nNadat de tankdop goed geplaatst en vastgedraaid is, zal deze indicator nog een aantal rijcycli aanblijven totdat geverifieerd kan worden dat het systeem in orde is.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "PowerSteeringSysErrorLong" : "Storing elektrische stuurbekrachtiging.\nZet het voertuig op een veilige plaatst stil en zet de motor af.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "EngSystemErrorLong" : "Storing motorsysteem.  Laat het voertuig onmiddellijk nakijken door een dealer.",
    "AirbagSysPretensionerSysErrorLong" : "Storing airbag/gordel.\nLaat het voertuig onmiddellijk nakijken door een dealer\n",
    "AbsSystemErrorLong" : "Storing antiblokkeersysteem (ABS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "DscSystemErrorLong" : "Storing dynamische stabiliteitscontrole (DCS) of tractiecontrolesysteem (TCS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "RvmSysErrorLong" : "Er is een fout in het RVM-systeem.\nControleer op afwijkingen in het oppervlak van de achterbumper en maak schoon als er vuil of sneeuw opzit.\nLaat uw voertuig nakijken door een Mazda-dealer als dit waarschuwingslampje niet uitgaat.\n",
    "BsmSystemErrorLong" : "Storing Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nControleer op afwijkingen in het oppervlak van de achterbumper en maak schoon als er vuil of sneeuw opzit. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "AfsSystemErrorLong" : "Storing adaptief bochtenverlichtingssysteem (AFS).  Laat het voertuig nakijken door een dealer als deze indicator blijft knipperen.",
    "AutoLevelSystemErrorLong" : "Storing automatische koplamphoogteregelaar.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "IstopSysErrorLong" : "i-stop-besturing is niet mogelijk.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
    "TpmsSysErrorLong" : "Storing controlesysteem bandenspanning (TPMS).\nLaat het voertuig nakijken door een dealer.\n",
    "KeylesSysErrorLong" : "Storing keyless entry systeem.\nLaat het voertuig nakijken door een dealer.",
    "FWDSysErrorLong" : "Storing 4WD-systeem of de maat van de banden is voor en achter verschillend.\nLaat het voertuig nakijken door een dealer.",
    "DPFErrorLong" : "Storing roetfilter (DPF).\nLaat het voertuig nakijken door een dealer.\n",
    "AutoTransSysErrorLong" : "Storing automatische versnellingsbak.\nHet voertuig kan schade oplopen als u blijft rijden.  Laat het voertuig onmiddellijk nakijken door een dealer.  \n",
    "BattManagSysErrorLong" : "Storing accubeheersysteem.\nLaat het voertuig nakijken door een dealer.\n",
    "BrakOverrideSysErrorLong" : "Storing remlichtschakelaar.\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "MRCCSysErrorLong" : "Storing Mazda Radar Cruise Control (MRCC).\nLaat het voertuig nakijken door een dealer.\n",
    "SBSSysErrorLong" : "Er is een fout in het SBS-systeem.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
    "FOWSysErrorLong" : "Storing Forward Obstruction Warning (FOW)-systeem.\nLaat het voertuig nakijken door een dealer.",
    "DRSSSysErrorLong" : "Er is een fout in het DRSS-systeem.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
    "FOWMRCCRadarSoilingLong" : "Radarstoring (sensor) FOW/MRCC.\nMaak het hele oppervlak van het grille-embleem aan de voorkant schoon als dit vies of met sneeuw bedekt is.  \nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
    "FOWMRCCDRSSRadarSoilingLong" : "De FOW/MRCC/DRSS-radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
    "SBSMRCCRadarSoilingLong" : "De SBS/MRCC -radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
    "SBSMRCCDRSSRadarSoilingLong" : "De FOW/MRCC/DRSS-radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) is op dit moment niet beschikbaar.",
    "SBSBrakeUnavailableLong" : "SBS-rem op dit moment niet beschikbaar.",
    "SBSBrakeMRCCUnavailableLong" : "SBS-rem/MRCC op dit moment niet beschikbaar.",
    "SCBSSysErrorLong" : "Storing Smart City Brake Support (SCBS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
    "SCBSWindshieldSoilingLong" : "Storing Smart City Brake Support (SCBS).\nMaak de voorruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) op dit moment niet beschikbaar.",
    "LDWSSysErrorLong" : "Storing Lane Departure Warning System (LDWS).\nLaat het voertuig nakijken door een dealer.",
    "HBCSysErrorLong" : "Storing High Beam Control (HBC).\nLaat het voertuig nakijken door een dealer.",
    "HBCLLDWSCamDisconnectLong" : "Storing High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nMaak de ruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
    "HBCLDWSSysErrorLong" : "Storing High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
    "HBCLDWSWindshieldFogLong" : "Storing High Beam Control (HBC)/Lane Departure Warning System (LDWS). Ontdooi de voorruit.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
    "SedimenterWarningLong" : "De hoeveelheid water die zich in de waterafscheider heeft opgehoopt, overschrijdt de gespecificeerde hoeveelheid.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "FuelAirFilterCartReplacePeriodLong" : "Het brandstof/luchtfilterpatroon moet vervangen worden.",
    "VehicleSysErrorLong" : "Systeemstoring voertuig.\nLaat het voertuig nakijken door een dealer.\n",
    "LowWasheFluidLong" : "Ruitenwisservloeistofpeil is laag.\nVul de ruitenwisservloeistof bij.\n",
    "EngineWaterTempDropLong" : "Motorkoelvloeistof is koud en er is geen warme lucht beschikbaar voor verwarmen/ontdooien. Er kan met het voertuig gereden worden met de indicator aan of uit.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
    "PreheatingDispLampLong" : "Gloeibougies gloeien voor.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
    "HybrdSysMalHighPrt" : "Hybride Systeem Defect. Voertuig onmiddellijk stoppen op een veilige plaats.",
    "ChargSysMalHighPrt" : "Oplading Systeem Defect. Voertuig onmiddellijk stoppen op een veilige plaats.",
    "IeloopChrgHighPrt" : "i-ELOOP opladen. Terwijl de motor draait, controleer dan of het opladen voltooid is en het waarschuwingslampje uit is.",
    "EngnCoolTempHighHighPrt" : "Motorkoelvloeistoftemperatuur Hoog. Voertuig onmiddellijk stoppen op een veilige plaats.",
    "lowBattStartEngine" : "Accu bijna leeg! Start motor!",
    "engineOilPressure" : "Oliedrukmeter",
    "brakeFluid" : "Laag niveau remvloeistof",
    "highVoltage" : "Hoge spanning Accu laag",
};

framework.registerAppDictLoaded("warnguide", "nl_NL");