var Localization_warnguideAppDict_es_ES = {
    //"stringId" : "localString"
    "Warnings" : "Advertencias ",
    "NoWarnings" : "No hay Advertencias",
    "WarningSafetyMessage" : "Por motivos de seguridad, la Guía de Advertencia no se muestra en la pantalla.",
    "WarningGuidance" : "Guía de advertencia",
    "AuxBattLowShrt" : "Batería de 12 V Baja",
    "DriveBattDropShrt" : "Batería de Alto voltaje de baja",
    "ControlSystemErrorShrt" : "Fallo del Sistema de Control de la Posición de Parking",
    "EngineOilPressureErrorShrt" : "Presión de Aceite de Motor Baja.",
    "HybridSysErrorShrt" : "Fallo del Sistema Híbrido",
    "HybridSysOverheatShrt" : "Sobrecalentamiento Sist. Híbrido",
    "PpositionRequestShrt" : "Solicitud Posic Aparcamiento",
    "ChargingSysErrorShrt" : "Fallo en el Sistema de Carga",
    "BrakeSysErrorShrt" : "Fallo en el Sistema de Frenos",
    "EcbSysErrorShrt" : "Fallo en el Sistema de Frenos",
    "AbsSysErrorShrt" : "Fallo de ABS",
    "DscSysErrorShrt" : "Fallo de DSC",
    "DropKeyBattChrgShrt" : "Batería de la llave baja",
    "EngOilPressureErrorShrt" : "Presión de Aceite de Motor Baja",
    "ChrgSysErrorShrt" : "Fallo en el Sistema de Carga",
    "EloopSysErrorShrt" : "Fallo en el Sistema i-ELOOP",
    "EloopChargingShrt" : "Cargando i-ELOOP",
    "LowBrakeFluidShrt" : "Líquido de Frenos Bajo",
    "BrakeSystemErrorShrt" : "Fallo en el Sistema de Frenos",
    "LowTireAirPressureShrt" : "Baja presión aire de llanta",
    "EngCoolntTempHighOnShrt" : "Temperatura del refrigerador del motor alta",
    "EngineWaterTempRiseShrt" : "Temperatura del refrigerador del motor alta",
    "SystemInspectionShrt" : "Inspección del Sistema 4WD",
    "AccumulationDpfShrt" : "Acumulación de PM en DPF",
    "RoadSurfaceIcingCautionShrt" : "Caución Carretera con Hielo",
    "LowFuelShrt" : "Combustible bajo",
    "FuelCapInspectionShrt" : "Inspecc Tapa Comb",
    "PowerSteeringSysErrorShrt" : "Fallo Sist. Direc. Asistida",
    "EngSystemErrorShrt" : "Fallo en el Sistema de Motor",
    "AirbagSysPretensionerSysErrorShrt" : "Fallo Sist.  Pretensores/Airbag",
    "AbsSystemErrorShrt" : "Fallo de ABS",
    "DscSystemErrorShrt" : "Fallo de DSC",
    "RvmSysErrorShrt" : "Fallo de RVM",
    "BsmSystemErrorShrt" : "Fallo de BSM",
    "AfsSystemErrorShrt" : "Fallo de AFS",
    "AutoLevelSystemErrorShrt" : "Fallo Sist Autonivelado",
    "IstopSysErrorShrt" : "Fallo en el Sistema i-stop",
    "TpmsSysErrorShrt" : "Fallo Sist. TPMS",
    "KeylesSysErrorShrt" : "Fallo en el Acceso sin Llave",
    "FWDSysErrorShrt" : "Fallo en el Sistema 4WD",
    "DPFErrorShrt" : "Error de DPF",
    "AutoTransSysErrorShrt" : "Fallo Transmisión Auto",
    "BattManagSysErrorShrt" : "Fallo Sist. Gestión Batería ",
    "BrakOverrideSysErrorShrt" : "Fallo Sist Mando Frenos",
    "MRCCSysErrorShrt" : "Fallo en el MRCC",
    "SBSSysErrorShrt" : "Fallo en el SBS",
    "FOWSysError" : "Fallo en el FOW",
    "DRSSSysErrorShrt" : "Fallo en el DRSS",
    "FOWMRCCRadarSoilingShrt" : "Fallo en el Radar FOW/MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Fallo Radar FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Fallo en el Radar SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Fallo Radar SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC No disponible",
    "SBSBrakeUnavailableShrt" : "Frenos SBS No Disponibles",
    "SBSBrakeMRCCUnavailableShrt" : "Frenos SBS/MRCC No Dispon.",
    "SCBSSysErrorShrt" : "Fallo en el SCBS",
    "SCBSWindshieldSoilingShrt" : "Fallo en el SCBS",
    "SCBSUnavailableShrt" : "SCBS No Disponible",
    "LDWSSysErrorShrt" : "Fallo en el LDWS",
    "HBCSysErrorShrt" : "Fallo en el HBC",
    "HBCLLDWSCamDisconnectShrt" : "Fallo en la Cámara HBC/LDWS",
    "HBCLDWSSysErrorShrt" : "Fallo en el Sistema HBC/LDWS",
    "HBCLDWSWindshieldFogShrt" : "Fallo en el Sistema HBC/LDWS",
    "SedimenterWarningShrt" : "Inspección del Sedimentador",
    "FuelAirFilterCartReplacePeriodShrt" : "Cambiar Cart. Filtro Comb-Aire",
    "VehicleSysErrorShrt" : "Fallo en el Sistema del Vehículo",
    "LowWasheFluidShrt" : "Líquido de Limpiaparabrisas Bajo",
    "EngineWaterTempDropShrt" : "Temp. Refrig. de Motor Baja",
    "PreheatingDispLampShrt" : "Precalent. Bujías Incandesc.",
    "AuxBattLowLong" : "La carga de la batería de 12V es baja.\nSi este indicador se enciende frecuentemente mientras conduce, la batería puede estar dañada. Revise su vehículo en un Servicio Autorizado Mazda.\nSi este indicador queda fijo y no se apaga, la batería de 12V estará agotada. Consulte el Manual del Propietario antes de iniciar el sistema híbrido y revise el vehículo en un Servicio Autorizado Mazda.",
    "DriveBattDropLong" : "La energía residual en la batería de alto voltaje es baja debido a que la transmisión ha estado por un largo período de tiempo en posición Neutra. No es posible cargar en posición Neutra. Cambie a posición Parking cuando detenga el vehículo durante un largo período de tiempo. Reinicie el sistema híbrido presionando el botón de arranque si es necesario.",
    "ControlSystemErrorLong" : "Fallo en el Sistema de  control de posición de aparcamiento\nSi permaneció sin revisar, puede llevar a cabo cualquiera de las siguientes acciones:\nEl mecanismo de bloqueo de aparcamiento puede no funcionar correctamente. Estacione en un lugar plano y active el freno de estacionamiento.\nEl interruptor dearranque no se puede apagar. Pulse repetidamente el interruptor de arranque para apagarlo.\nLa pantalla “Establezca el Freno de Aparcamiento Cuando Estacione” se apagará cuando circule o cuando se detenga.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente.",
    "EngineOilPressureErrorLong" : "Presión de Aceite de Motor Baja.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, e inspeccione el nivel de aceite del motor. Añada aceite si es necesario.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente si este indicador se enciende después de haber añadido aceite o  el nivel de aceite del motor está bien.",
    "HybridSysErrorLong" : "Fallo en el Sistema Híbrido. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "HybridSysOverheatLong" : "Fallo en el Sistema Híbrido. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "PpositionRequestLong" : "Cambie la transmisión a Parking.\nEsto es causado por una de los siguientes motivos:\n· El sistema de batería se inicio o se detuvo con la transmsión en una posición distinta de Parking\n· La puerta del conductor se abrió con la transmisión en posición N, D, o B\n· La carga restante de la batería de alto voltaje es baja debido a que la transmisión se ha mantenido en posición Neutra por un largo período de tiempo\nReinicie el sistema híbrido pulsando el interruptor de arranque en caso necesario.",
    "ChargingSysErrorLong" : "Fallo en el Sistema de Carga. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "BrakeSysErrorLong" : "El nivel del líquido de frenos está bajo o hay un fallo en el sistema de frenos.  Detenga el vehículo inmediatamente en una zona segura y  revise el vehículo en un Servicio Autorizado Mazda.",
    "EcbSysErrorLong" : "Fallo en el sistema de frenada regenerativa o en el sistema de frenada electrónica. Detenga el vehículo inmediatamente en una zona segura y revise su vehículo en un Servicio Autorizado Mazda.",
    "AbsSysErrorLong" : "Fallo en el sistema de frenos antibloqueo (ABS). Revise el vehículo en un Servicio Autorizado Mazda inmediatamente.",
    "DscSysErrorLong" : "Fallo en el sistema de ayuda de arranque en pendientes (HLA), en el sistema de control de tracción (TCS), o en el control de estabilidad dinámico (DSC).Haga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente.",
    "DropKeyBattChrgLong" : "La batería de la llave es baja. Sustituya la batería de la llave en el menor tiempo posible",
    "EngOilPressureErrorLong" : "Presión de Aceite de Motor Baja.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, e inspeccione el nivel de aceite del motor. Añada aceite si es necesario.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente si este indicador se enciende después de haber añadido aceite o  el nivel de aceite del motor está bien.",
    "ChrgSysErrorLong" : "Fallo en el Sistema de Carga. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "EloopSysErrorLong" : "Fallo en el sistema i-ELOOP, haga revisar el vehículo por un Servicio Autorizado Mazda si el indicador permanece activado.",
    "EloopChargingLong" : "Cargando i-ELOOP.\nCon el motor en marcha, verifique que la carga esté completa y que el indicador de advertencia esté apagado. Revise el vehículo por un Servicio Autorizado Mazda  si este indicador permanece activado.",
    "LowBrakeFluidLong" : "El nivel de líquido de frenos está bajo.\nDetenga el vehículo inmediatamente en un lugar seguro y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "BrakeSystemErrorLong" : "Fallo en el sistema de frenos controlado electrónicamente. Detenga el vehículo inmediatamente en un lugar seguro y haga revisar el vehículo por un Servicio Autorizado Mazda.",
    "LowTireAirPressureLong" : "Presión de aire de neumáticos baja en una o más ruedas.\nRevise la presión de aire de los neumáticos y ajústela a la presión de aire correcta.  Oprima el interruptor TPMS SET después de ajustar la presión del neumático hasta que escuche un pitido.\n",
    "EngCoolntTempHighOnLong" : "El motor se está sobrecalentado.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, y tome las acciones adecuadas.  Consulte el Manual del Usuario.\n",
    "EngineWaterTempRiseLong" : "El motor está empezando a calentarse.\nConduzca lentamente o detenga el vehículo hasta que el indicador deje de parpadear. Si continua intermitente, incluso después de haber detenido el vehículo, tome las acciones adecuadas. Consulte el Manual del Usuario.\n",
    "SystemInspectionLong" : "La temperatura del aceite del diferencial es excesivamente alta o la diferencia de giro entre las ruedas delanteras y traseras es excesiva (como cuando intenta salir del barro). Detenga el vehículo en un lugar seguro y vuelva a conducir después de que el indicador de alarma se apague. Haga revisar el vehículo por un Servicio Autorizado Mazda si este indicador permanece activado.",
    "AccumulationDpfLong" : "Las particulas (PM) atrapadas en el filtro de particulas diesel (DPF) han excedido el valor de regulación. Conduzca el vehículo durante unos 10 o 15 minutos con el motor caliente (testigo de temperatura azul apagado) a una velocidad de 15 km/h (10mph) o más para eliminar las PM. Haga revisar el vehículo por un Servicio Autorizado Mazda si el indicador permanece activado ",
    "RoadSurfaceIcingCautionLong" : "La temperatura exterior es de 4ºC o menos. Tenga cuidado. Posible formación de hielo en la carretera.",
    "LowFuelLong" : "El nivel de combustible es bajo. Reposte el vehículo lo más pronto posible.",
    "FuelCapInspectionLong" : "El tapón del deposito podría no estar cerrado correctamente. Compruebe que el  tapón del deposito esta correctamente colocado y apretado. Tras cerrar y apretar correctamente el tapón de combustible, el indicador no se apagará hasta confirmar que el sistema funciona correctamente. Haga revisar el vehículo por un Servicio Autorizado Mazda si este indicador permanece activado.",
    "PowerSteeringSysErrorLong" : "Fallo en la dirección asistida eléctrica.\nDetenga el vehículo en un lugar seguro y apague el motor.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece Activado.",
    "EngSystemErrorLong" : "Fallo en el Sistema del Motor.  Haga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "AirbagSysPretensionerSysErrorLong" : "Fallo en el Airbag / cinturón de seguridad.\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "AbsSystemErrorLong" : "Fallo en el sistema de frenos antibloqueo (ABS).\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "DscSystemErrorLong" : "Fallo en el sistema de control de tracción (TCS) o en el control de estabilidad dinámico (DSC).\nHaga revisar el vehículo por un Servcicio Autorizado inmediatamente.",
    "RvmSysErrorLong" : "Hay un error en el sistema RVM.\nVerifique si hay anomalías en la superficie del  paragolpes trasero, y limpielo si está sucio o cubierto con nieve.\nHaga revisar el vehículo por un Servicio Autorizado Mazda si este testigo de aviso permanece activado.",
    "BsmSystemErrorLong" : "Fallo en Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA),\nVerifique si hay anomalías en la superficie del paragolpes trasero y límpielo si está sucio o cubierto con nieve. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
    "AfsSystemErrorLong" : "Fallo en el sistema de luces adaptativas (AFS).  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece parpadeando.",
    "AutoLevelSystemErrorLong" : "Fallo en el sistema de autonivelado de luces.\nHaga revisar el vehículo por un Sevicio Autorizado si este indicador permanece activado.",
    "IstopSysErrorLong" : "No es posible el funcionamiento del sistema i-stop.\nHaga revisar su vehículo por un Servicio Autorizado Mazda.",
    "TpmsSysErrorLong" : "Fallo en el sistema de control de presión de neumáticos (TPMS).\nHaga revisar el vehículo por un Sercvicio Autorizado.",
    "KeylesSysErrorLong" : "Fallo en el cierre centralizado. Haga revisar el vehículo por un Servicio Autorizado.",
    "FWDSysErrorLong" : "Fallo en el sistema de tracción en las cuatro ruedas (4WD) o el tamaño de neumáticos delanteros y traseros es diferente.\nHaga revisar el vehículo por un Servicio Autorizado.",
    "DPFErrorLong" : "Fallo en el filtro de partículas diesel (DPF)\nHaga revisar el vehículo por un Servicio Autorizado.",
    "AutoTransSysErrorLong" : "Fallo en la caja de cambios automática.\nSi continúa conduciendo puede causar  un daño al vehículo.  Haga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "BattManagSysErrorLong" : "Fallo en el Sistema de Gestión de Batería.\nHaga revisar el vehículo por un Servicio Autorizado.",
    "BrakOverrideSysErrorLong" : "Fallo en el interruptor de frenos.\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "MRCCSysErrorLong" : "Fallo en el Mazda Radar Cruise Control (MRCC).\nHaga revisar el vehículo por un Servicio Autorizado.",
    "SBSSysErrorLong" : "Hay un error en el sistema SBS.\nHaga revisar su vehículo con un Servicio Autorizado Mazda.",
    "FOWSysErrorLong" : "Fallo en el Forward Obstruction Warning (FOW).\nHaga revisar el vehículo por un Servicio Autorizado.",
    "DRSSSysErrorLong" : "Hay un error en el sistema DRSS.\nHaga revisar su vehículo por un Servicio Autorizado Mazda.",
    "FOWMRCCRadarSoilingLong" : "Fallo en el sensor FOW/MRCC.\nLimpie toda la superficie del logotipo de la rejilla frontal si está sucia o cubierta de nieve.  \nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece Activado.",
    "FOWMRCCDRSSRadarSoilingLong" : "El sensor FOW/MRCC/DRSS está sucio. Limpie toda la superficie del sensor.",
    "SBSMRCCRadarSoilingLong" : "El sensor SBS/MRCC está sucio.\nLimpie toda la superficie del sensor.",
    "SBSMRCCDRSSRadarSoilingLong" : "El sensor SBS/MRCC/DRSS está sucio.\nLimpie toda la superficie del sensor.",
    "MRCCUnavailableLong" : "El Mazda Radar Cruise Control (MRCC)  no está disponible en estos momentos.",
    "SBSBrakeUnavailableLong" : "El sistema de frenos SBS no está disponible en estos momentos.",
    "SBSBrakeMRCCUnavailableLong" : "El sistema de frenos SBS/MRCC no está disponible en estos momentos.",
    "SCBSSysErrorLong" : "Fallo en el sistema de Smart City Brake Support (SCBS).\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
    "SCBSWindshieldSoilingLong" : "Fallo en el sistema de Smart City Brake Support (SCBS).\nLimpie el parabrisas delantero.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
    "SCBSUnavailableLong" : "El sistema de Smart City Brake Support (SCBS) no está disponible en estos momentos.",
    "LDWSSysErrorLong" : "Fallo en el sistema de Lane Departure Warning System (LDWS).\nHaga revisar el vehículo por un Servicio Autorizado.",
    "HBCSysErrorLong" : "Fallo en el High beam control (HBC).\nHaga revisar el vehículo por un Servicio Autorizado.",
    "HBCLLDWSCamDisconnectLong" : "Fallo en el sistema de High Beam Control (HBC)/Lane Departure Warning System (LDWS) .\nLimpie el parabrisas.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
    "HBCLDWSSysErrorLong" : "Fallo en el sistema de High Beam Control (HBC)/Lane Departure Warning System (LDWS). Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
    "HBCLDWSWindshieldFogLong" : "Fallo en el sistema de High beam control (HBC)/Lane departure warning system (LDWS).\nDesempañe el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.\n",
    "SedimenterWarningLong" : "La cantidad de agua acumulada en el sedimentador excede la cantidad nominal.\nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.\n",
    "FuelAirFilterCartReplacePeriodLong" : "El filtro de combustible - aire necesita reemplazarse. ",
    "VehicleSysErrorLong" : "Fallo de  sistema en el vehículo.\nHaga revisar el vehículo por un Servicio Autorizado.\n",
    "LowWasheFluidLong" : "El nivel de líquido limpiador está bajo.\nVuelva a llenar el líquido limpiador.\n",
    "EngineWaterTempDropLong" : "El refrigerante del motor está frío y no hay aire caliente disponible para el calentador / desempañador. El vehículo puede conducirse con el indicador activado o apagado.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
    "PreheatingDispLampLong" : "Precalentamiento de Bujías Incandescentes.\nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.\n",
    "HybrdSysMalHighPrt" : "Fallo del Sistema Híbrido. Detenga el vehículo inmediatamente en un lugar seguro.",
    "ChargSysMalHighPrt" : "Fallo del Sistema de Carga. Detenga el vehículo inmediatamente en un lugar seguro.",
    "IeloopChrgHighPrt" : "Cargando i-ELOOP. Con motor en marcha, revise que la carga esté completa y el indicador de advertencia esté apagado.",
    "EngnCoolTempHighHighPrt" : "Temperatura de Refrigerante de Motor Alta. Detenga el vehículo inmediatamente en un lugar seguro.",
    "lowBattStartEngine" : "¡Batería baja! ¡Arranque el motor!",
    "engineOilPressure" : "Presión del aceite del motor",
    "brakeFluid" : "Nivel de líquido de frenos bajo",
    "highVoltage" : "Batería de alto voltaje baja",
};

framework.registerAppDictLoaded("warnguide", "es_ES");