var Localization_warnguideAppDict_fr_FR = {
    //"stringId" : "localString"
    "Warnings" : "Mises en garde",
    "NoWarnings" : "Aucune mise en garde trouvée",
    "WarningSafetyMessage" : "Pour des raisons de sécurité, les mises en garde ne sont pas affichées.",
    "WarningGuidance" : "Mise en garde",
    "AuxBattLowShrt" : "Batterie 12V faible",
    "DriveBattDropShrt" : "Batterie haute tension faible",
    "ControlSystemErrorShrt" : "Err syst control posit Stationmt",
    "EngineOilPressureErrorShrt" : "Faible press. huile lubrif moteur",
    "HybridSysErrorShrt" : "Défaillance du système hybride",
    "HybridSysOverheatShrt" : "Surchauffe du système hybride",
    "PpositionRequestShrt" : "Demande position Stationment",
    "ChargingSysErrorShrt" : "Défaillance système de charge",
    "BrakeSysErrorShrt" : "Défaillance du système de frein",
    "EcbSysErrorShrt" : "Défaillance du système de frein",
    "AbsSysErrorShrt" : "Défaillance de l'ABS",
    "DscSysErrorShrt" : "Défaillance du système DSC",
    "DropKeyBattChrgShrt" : "Batterie principale faible",
    "EngOilPressureErrorShrt" : "Faible press. huile lubrif moteur",
    "ChrgSysErrorShrt" : "Défaillance système de charge",
    "EloopSysErrorShrt" : "Défaillance du système i-ELOOP ",
    "EloopChargingShrt" : "Charge i-ELOOP ",
    "LowBrakeFluidShrt" : "Niveau bas du liquide de frein",
    "BrakeSystemErrorShrt" : "Défaillance du système de frein",
    "LowTireAirPressureShrt" : "Faible pression des pneus",
    "EngCoolntTempHighOnShrt" : "Temp élevée du liq refroidismnt",
    "EngineWaterTempRiseShrt" : "Temp élevée du liq refroidismnt",
    "SystemInspectionShrt" : "Inspection du système 4WD",
    "AccumulationDpfShrt" : "Accumulati. particules dans FAP",
    "RoadSurfaceIcingCautionShrt" : "Attention route verglacée",
    "LowFuelShrt" : "Niveau de carburant faible",
    "FuelCapInspectionShrt" : "Inspection bouchon carburant",
    "PowerSteeringSysErrorShrt" : "Défaillance direction assistée",
    "EngSystemErrorShrt" : "Défaillance du moteur",
    "AirbagSysPretensionerSysErrorShrt" : "Déf Airbag/dispos prétension",
    "AbsSystemErrorShrt" : "Défaillance de l'ABS",
    "DscSystemErrorShrt" : "Défaillance du système DSC",
    "RvmSysErrorShrt" : "Défaillance du RVM",
    "BsmSystemErrorShrt" : "Défaillance du BSM",
    "AfsSystemErrorShrt" : "Défaillance de l'AFS",
    "AutoLevelSystemErrorShrt" : "Défaillance syst nivellement auto",
    "IstopSysErrorShrt" : "Défaillance du système i-stop",
    "TpmsSysErrorShrt" : "Défaillance du système TPMS",
    "KeylesSysErrorShrt" : "Défaillance du système sans clé",
    "FWDSysErrorShrt" : "Défaillance du système 4WD",
    "DPFErrorShrt" : "Erreur du FPD",
    "AutoTransSysErrorShrt" : "Défaillance transmission auto",
    "BattManagSysErrorShrt" : "Défaillance syst gestion batterie",
    "BrakOverrideSysErrorShrt" : "Défaillance syst priorité freins",
    "MRCCSysErrorShrt" : "Défaillance du MRCC",
    "SBSSysErrorShrt" : "Défaillance du SBS",
    "FOWSysError" : "Défaillance du FOW",
    "DRSSSysErrorShrt" : "Défaillance du DRSS",
    "FOWMRCCRadarSoilingShrt" : "Défaillance radar FOW / MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Défaill. radar FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Défaillance radar SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Défaillan radar SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC non disponible",
    "SBSBrakeUnavailableShrt" : "Sys. d'aide au freinage indisp.",
    "SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC indisponibles.",
    "SCBSSysErrorShrt" : "Défaillance du SCBS",
    "SCBSWindshieldSoilingShrt" : "Défaillance du SCBS",
    "SCBSUnavailableShrt" : "SCBS non disponible",
    "LDWSSysErrorShrt" : "Défaillance du LDWS",
    "HBCSysErrorShrt" : "Défaillance de l'HBC",
    "HBCLLDWSCamDisconnectShrt" : "Défaillance caméra HBC/LDWS",
    "HBCLDWSSysErrorShrt" : "Défaillance système HBC/LDWS",
    "HBCLDWSWindshieldFogShrt" : "Défaillance système HBC/LDWS",
    "SedimenterWarningShrt" : "Inspection du sédimenteur",
    "FuelAirFilterCartReplacePeriodShrt" : "Remplacer filtre à air/essence",
    "VehicleSysErrorShrt" : "Défaillance système du véhicule",
    "LowWasheFluidShrt" : "Niveau bas du liquide lave-glace ",
    "EngineWaterTempDropShrt" : "Temp bas liq refroidsmnt moteur",
    "PreheatingDispLampShrt" : "Préchauff bougies réchauffage",
    "AuxBattLowLong" : "La charge de la batterie 12V est faible.\nSi l'indicateur s'allume fréquemment lorsque vous roulez, la batterie pourrait être usée. Faîtes réviser votre véhicule par un revendeur.\nSi ce témoin est allumé en permanence et ne s'éteint pas, la batterie 12V est usée. Référez-vous au manuel d utilisation avant de démarrer le système hybride et faites réviser le véhicule par un concessionaire.",
    "DriveBattDropLong" : "La puissance résiduelle dans la batterie haute tension est faible parce que la transmission est en position neutre pendant une longue période.  La charge n'est pas possible en position Neutre.  Se mettre en position Stationnement lorsqu'à l'arrêt pendant une longue période.  Redémarrez le système hybride en appuyant sur le démarreur si nécessaire.",
    "ControlSystemErrorLong" : "Défaillance du système de contrôle de la position Stationnement.  Si le véhicule n'est pas révisé, cela peut amener à une des situations suivantes :  Le frein de stationnement pourrait ne plus fonctionner.  Stationner dans un endroit plat et enclencher le frein de stationnement.  Le moteur peut ne plus s'éteindre.  Appuyez de manière répétée sur le démarreur pour l'éteindre.  Le message \"Enclencher le frein de stationnement lors du stationnement\" s'éteint lors de la conduite et s'allume à l'arrêt.  Faites réviser votre véhicule par un concessionaire immédiatement.",
    "EngineOilPressureErrorLong" : "Pression d'huile moteur basse.  Arrêtez le véhicule immédiatement dans un endroit sûr, arrêtez le moteur et vérifiez le niveau d'huile moteur.  Ajoutez de l'huile si nécessaire.  Faîtes réviser le véhicule par un revendeur immédiatement si l'indicateur s'allume après avoir ajouté de l'huile ou si le niveau d'huile moteur est correct.",
    "HybridSysErrorLong" : "Défaillance du système hybride.  Le véhicule pourrait être endommagé si vous continuez de rouler.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "HybridSysOverheatLong" : "Défaillance du système hybride.  Le véhicule pourrait être endommagé si vous continuez de rouler.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "PpositionRequestLong" : "Mettre la transmission en position Stationnement.  Cela est dû à :  Le système de batterie a démarré ou s'est arrêté avec la transmission dans une position autre que celle de Stationnement.  La porte côté conducteur a été ouverte avec la transmission en position N, D ou B. La puissance résiduelle dans la batterie haute tension est faible parce que la transmission est en position neutre pendant une longue période.  La charge n'est pas possible en position Neutre. Redémarrer le système hybride en appuyant sur le démarreur si nécessaire.",
    "ChargingSysErrorLong" : "Défaillance du système de charge.  Le véhicule pourrait être endommagé si vous continuez de rouler.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "BrakeSysErrorLong" : "Niveau bas de liquide de frein ou défaillance du système de frein.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "EcbSysErrorLong" : "Défaillance du système de freinage par récupération ou de freinage électronique.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "AbsSysErrorLong" : "Défaillance du système d'anti-blocage des freins (ABS).  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "DscSysErrorLong" : "Défaillance de la commande dynamique de stabilité (DSC), du système de contrôle de traction (TCS), ou de l'aide au démarrage en côte (ADC).  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "DropKeyBattChrgLong" : "La batterie principale est faible.  Remplacez la batterie principale immédiatement.",
    "EngOilPressureErrorLong" : "Pression d'huile moteur basse. Arrêtez le véhicule immédiatement dans un endroit sûr, arrêtez le moteur et vérifiez le niveau d'huile moteur. Ajoutez de l'huile si nécessaire. Faîtes réviser le véhicule par un revendeur immédiatement si l'indicateur s'allume après avoir ajouté de l'huile ou si le niveau d'huile moteur est correct.",
    "ChrgSysErrorLong" : "Défaillance du système de charge.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "EloopSysErrorLong" : "Défaillance du système i-ELOOP.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "EloopChargingLong" : "L'i-ELOOP est en train de charger.  Avec le moteur en marche, vérifiez que le chargement est complet et que l'indicateur lumineux est éteint.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "LowBrakeFluidLong" : "Le niveau de liquide de frein est faible.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "BrakeSystemErrorLong" : "Défaillance du système de freinage électronique.  Arrêtez le véhicule immédiatement dans un endroit sûr et faîtes réviser le véhicule par un revendeur.",
    "LowTireAirPressureLong" : "Pression d'air des pneus faible pour un ou plusieurs pneus.  Vérifiez la pression d'air des pneus et ajustez à la pression adaptée.  Appuyez sur le bouton RÉGLAGE TPMS après avoir ajusté la pression des pneus jusqu'à ce que vous entendiez un bip.",
    "EngCoolntTempHighOnLong" : "Le moteur est en surchauffe.  Arrêtez le véhicule immédiatement dans un endroit sûr, arrêtez le moteur et prenez les mesures adaptées.  Référez-vous au manuel d'utilisation.",
    "EngineWaterTempRiseLong" : "Le moteur commence à chauffer.  Conduisez lentement ou arrêtez le véhicule jusqu'à ce que l'indicateur s'arrête de clignoter.  S'il continue de clignoter, même après avoir arrêté le véhicule, prenez les mesures adaptées.  Référez-vous au manuel d'utilisation.",
    "SystemInspectionLong" : "La température de l'huile du différentiel est anormalement élevée ou une large différence de rotation s'est produite au niveau des pneus avant (comme lorsqu'on essaie de désembourber le véhicule de la boue).  Arrêtez le véhicule dans un endroit sûr et continuez à conduire après extinction du voyant. Faites réviser le véhicule par un revendeur si le voyant reste allumé.",
    "AccumulationDpfLong" : "Les particules en suspension (PM) collectées dans le filtre à particules diesel (FAP) ont dépassé la valeur réglementaire.  Roulez pendant 10 à 15 minutes avec le moteur préchauffé (voyant de temp. bleu) à un vitesse de 15km/h ou plus pour éliminer les PM.  Faites réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "RoadSurfaceIcingCautionLong" : "La température extérieure est de 4°C ou moins.  Faîtes attention aux routes verglacées en conduisant.",
    "LowFuelLong" : "Le niveau de carburant dans le réservoir est bas.  Faites le plein dès que possible.",
    "FuelCapInspectionLong" : "Le bouchon du réservoir peut ne pas être fermé correctement.  Vérifiez que le bouchon du réservoir soit fermé et serré correctement.   Après avoir installé et serré le bouchon du réservoir correctement, cet indicateur ne s'éteindra pas pendant quelques cycles de conduite jusqu'à ce que le fonctionnement correct du système soit confirmé.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "PowerSteeringSysErrorLong" : "Défaillance de la direction assistée électrique.  Arrêtez le véhicule immédiatement dans un endroit sûr et arrêtez le moteur.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "EngSystemErrorLong" : "Défaillance du système moteur.  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "AirbagSysPretensionerSysErrorLong" : "Défaillance de l'airbag/de la ceinture de sécurité.  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "AbsSystemErrorLong" : "Défaillance du système d'anti-blocage des freins (ABS).  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "DscSystemErrorLong" : "Défaillance de la commande dynamique de stabilité (DSC) ou du système de contrôle de traction (TCS).  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "RvmSysErrorLong" : "Erreur du système RVM.  Vérifiez la présence d'anomalies sur la surface du pare-chocs arrière et nettoyez si sale ou couvert de neige.  Faîtes réviser votre véhicule par un revendeur Mazda si l'indicateur reste allumé.",
    "BsmSystemErrorLong" : "Défaillance du système de Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).  Vérifiez la présence d'anomalies sur la surface du pare-chocs arrière et nettoyez si sale ou couvert de neige.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "AfsSystemErrorLong" : "Défaillance du système d'éclairage avant (AFS).  Faîtes réviser le véhicule par un revendeur si l'indicateur continue à clignoter.",
    "AutoLevelSystemErrorLong" : "Défaillance du système de nivellement.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "IstopSysErrorLong" : "Le fonctionnement du système i-stop n'est possible.  Faîtes réviser votre véhicule par un revendeur Mazda.",
    "TpmsSysErrorLong" : "Défaillance du système de surveillance de pression des pneus (TPMS).  Faîtes réviser votre véhicule par un revendeur.",
    "KeylesSysErrorLong" : "Défaillance du système sans clé.  Faîtes réviser votre véhicule par un revendeur.",
    "FWDSysErrorLong" : "Défaillance du système 4WD ou différence dans la taille des pneus arrière et avant.  Faîtes réviser votre véhicule par un revendeur.",
    "DPFErrorLong" : "Défaillance du filtre à particules diesel (FAP).  Faîtes réviser votre véhicule par un revendeur.",
    "AutoTransSysErrorLong" : "Défaillance de la transmission automatique.  Le véhicule pourrait être endommagé si vous continuez de rouler.  Faîtes réviser votre véhicule par un revendeur immédiatement.  ",
    "BattManagSysErrorLong" : "Défaillance du système de gestion de la batterie.  Faîtes réviser votre véhicule par un revendeur.",
    "BrakOverrideSysErrorLong" : "Défaillance du commutateur du frein.  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "MRCCSysErrorLong" : "Défaillance du Mazda Radar Cruise Control (MRCC).  Faîtes réviser votre véhicule par un revendeur.",
    "SBSSysErrorLong" : "Erreur du système SBS.  Faîtes réviser votre véhicule par un revendeur Mazda.",
    "FOWSysErrorLong" : "Défaillance du Forward Obstuction Warning (FOW). Faîtes réviser votre véhicule par un revendeur.",
    "DRSSSysErrorLong" : "Erreur du système DRSS.  Faîtes réviser votre véhicule par un revendeur Mazda.",
    "FOWMRCCRadarSoilingLong" : "Défaillance du radar (capteur) du système FOW / MRCC.  Nettoyez toute la surface de l'emblème de la calandre si sale ou couverte de neige.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "FOWMRCCDRSSRadarSoilingLong" : "Le radar (capteur) FOW/MRCC/DRSS est sale.  Nettoyez toute la surface du radar (capteur).",
    "SBSMRCCRadarSoilingLong" : "Le radar (capteur) SBS/MRCC est sale.  Nettoyez toute la surface du radar (capteur).",
    "SBSMRCCDRSSRadarSoilingLong" : "Le radar (capteur) SBS/MRCC/DRSS est sale.  Nettoyez toute la surface du radar (capteur).",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) actuellement indisponible.",
    "SBSBrakeUnavailableLong" : "SBS actuellement indisponible.",
    "SBSBrakeMRCCUnavailableLong" : "SBS/MRCC actuellement indisponibles.",
    "SCBSSysErrorLong" : "Défaillance de Smart City Brake Support (SCBS).  Faîtes réviser votre véhicule par un revendeur immédiatement.",
    "SCBSWindshieldSoilingLong" : "Défaillance de Smart City Brake Support (SCBS). Nettoyez le pare-brise avant.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) actuellement indisponible.",
    "LDWSSysErrorLong" : "Défaillance du Lane Departure Warning System (LDWS).  Faîtes réviser votre véhicule par un revendeur.",
    "HBCSysErrorLong" : "Défaillance du High Beam Control (HBC). Faîtes réviser votre véhicule par un revendeur.",
    "HBCLLDWSCamDisconnectLong" : "Défaillance du High Beam Control (HBC)/Lane Departure Warning System (LDWS). Nettoyez le pare-brise. Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "HBCLDWSSysErrorLong" : "Défaillance du High Beam Control (HBC)/Lane Departure Warning System (LDWS). Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "HBCLDWSWindshieldFogLong" : "Défaillance du High Beam Control (HBC)/Lane Departure Warning System (LDWS) malfunction..  Dégivrez le pare-brise. Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "SedimenterWarningLong" : "La quantité d'eau accumulée dans le sédimenteur dépasse la quantité limite.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "FuelAirFilterCartReplacePeriodLong" : "La cartouche du filtre à air doit être remplacée.",
    "VehicleSysErrorLong" : "Défaillance du système du véhicule.  Faîtes réviser votre véhicule par un revendeur.",
    "LowWasheFluidLong" : "Le niveau de liquide lave-glace est bas.  Remplissez le réservoir du liquide lave-glace.",
    "EngineWaterTempDropLong" : "Le liquide de refroidissement du moteur est froid et aucun air chaud pour le chauffage / dégivrage. Le véhicule peut rouler avec l'indicateur allumé ou éteint.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "PreheatingDispLampLong" : "Préchauffage des bougies.  Faîtes réviser le véhicule par un revendeur si l'indicateur reste allumé.",
    "HybrdSysMalHighPrt" : "Défaillance du système hybride. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "ChargSysMalHighPrt" : "Défaillance du système de charge. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "IeloopChrgHighPrt" : "i-ELOOP en charge. Avec le moteur en marche, vérifier que la charge est terminée et le voyant éteint.",
    "EngnCoolTempHighHighPrt" : "Température élevée du liquide de refroidissement. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "lowBattStartEngine" : "Batterie faible ! Démarrez moteur !",
    "engineOilPressure" : "Pression d’huile de moteur",
    "brakeFluid" : "Niveau bas de liquide de frein",
    "highVoltage" : "Batterie haute tension faible",
};

framework.registerAppDictLoaded("warnguide", "fr_FR");