var Localization_warnguideAppDict_sv_SE = {
    //"stringId" : "localString"
    "Warnings" : "Varningar",
    "NoWarnings" : "Hittade inga varningar",
    "WarningSafetyMessage" : "Av säkerhetsskäl visas inte varningsvägledning.",
    "WarningGuidance" : "Vägledningsvarn",
    "AuxBattLowShrt" : "12v batteri lågt",
    "DriveBattDropShrt" : "hög spänning låg batterinivå",
    "ControlSystemErrorShrt" : "Fel på parkeringshjälpsystem",
    "EngineOilPressureErrorShrt" : "Lågt motoroljetryck",
    "HybridSysErrorShrt" : "Fel på hybridsystem",
    "HybridSysOverheatShrt" : "Hybridsystemet överhettat",
    "PpositionRequestShrt" : "Begäran om parkeringshjälp",
    "ChargingSysErrorShrt" : "Fel på laddningssystem",
    "BrakeSysErrorShrt" : "Fel på bromssystem",
    "EcbSysErrorShrt" : "Fel på bromssystem",
    "AbsSysErrorShrt" : "Fel på ABS",
    "DscSysErrorShrt" : "Fel på DSC",
    "DropKeyBattChrgShrt" : "Batteriet i nyckeln är svagt",
    "EngOilPressureErrorShrt" : "Lågt motoroljetryck",
    "ChrgSysErrorShrt" : "Fel på laddningssystem",
    "EloopSysErrorShrt" : "Fel på i-ELOOP-system",
    "EloopChargingShrt" : "Laddar i-ELOOP",
    "LowBrakeFluidShrt" : "Låg nivå på bromsvätska",
    "BrakeSystemErrorShrt" : "Fel på bromssystem",
    "LowTireAirPressureShrt" : "Lågt lufttryck",
    "EngCoolntTempHighOnShrt" : "Hög temperatur på kylvätska",
    "EngineWaterTempRiseShrt" : "Hög temperatur på kylvätska",
    "SystemInspectionShrt" : "4WD-systemkontroll",
    "AccumulationDpfShrt" : "PM-ackumulering i DPF",
    "RoadSurfaceIcingCautionShrt" : "Varning för isigt underlag",
    "LowFuelShrt" : "Låg bränslenivå",
    "FuelCapInspectionShrt" : "Bränslelockkontroll",
    "PowerSteeringSysErrorShrt" : "Fel på servostyrningsystem",
    "EngSystemErrorShrt" : "Fel på motorsystem",
    "AirbagSysPretensionerSysErrorShrt" : "Fel på airbag-/försträckarsystem",
    "AbsSystemErrorShrt" : "Fel på ABS",
    "DscSystemErrorShrt" : "Fel på DSC",
    "RvmSysErrorShrt" : "Fel på RVM",
    "BsmSystemErrorShrt" : "Fel på BSM",
    "AfsSystemErrorShrt" : "Fel på AFS",
    "AutoLevelSystemErrorShrt" : "Fel på automatisk nivåreglering",
    "IstopSysErrorShrt" : "Fel på i-stop-system",
    "TpmsSysErrorShrt" : "Fel på TPMS-system",
    "KeylesSysErrorShrt" : "Fel på nyckelfri öppning",
    "FWDSysErrorShrt" : "Fel på 4WD-system",
    "DPFErrorShrt" : "Fel på DPF",
    "AutoTransSysErrorShrt" : "Fel på automatisk växellåda",
    "BattManagSysErrorShrt" : "Fel på batterihantering",
    "BrakOverrideSysErrorShrt" : "Fel på förbikoppling bromssystem",
    "MRCCSysErrorShrt" : "Fel på MRCC",
    "SBSSysErrorShrt" : "Fel på SBS",
    "FOWSysError" : "Fel på FOW",
    "DRSSSysErrorShrt" : "Fel på DRSS",
    "FOWMRCCRadarSoilingShrt" : "Fel på FOW/MRCC-radar",
    "FOWMRCCDRSSRadarSoilingShrt" : "Fel på FOW/MRCC/DRSS-radar",
    "SBSMRCCRadarSoilingShrt" : "Fel på SBS/MRCC-radar",
    "SBSMRCCDRSSRadarSoilingShrt" : "Fel på SBS/MRCC/DRSS-radar",
    "MRCCUnavailableShrt" : "MRCC inte tillgänglig",
    "SBSBrakeUnavailableShrt" : "SBS bromsfunktion inte tillgänglig",
    "SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC inte tillg",
    "SCBSSysErrorShrt" : "Fel på SCBS",
    "SCBSWindshieldSoilingShrt" : "Fel på SCBS",
    "SCBSUnavailableShrt" : "SCBS inte tillgänglig",
    "LDWSSysErrorShrt" : "Fel på LDWS",
    "HBCSysErrorShrt" : "Fel på HBC",
    "HBCLLDWSCamDisconnectShrt" : "Fel på HBC/LDWS-kamera",
    "HBCLDWSSysErrorShrt" : "Fel på HBC/LDWS-system",
    "HBCLDWSWindshieldFogShrt" : "Fel på HBC/LDWS-system",
    "SedimenterWarningShrt" : "Sedimenterkontroll",
    "FuelAirFilterCartReplacePeriodShrt" : "Byt bränsle-/luftfilterkassett",
    "VehicleSysErrorShrt" : "Fel på fordonsystem",
    "LowWasheFluidShrt" : "Låg nivå på spolarvätska",
    "EngineWaterTempDropShrt" : "Låg temperatur på kylvätska",
    "PreheatingDispLampShrt" : "Glödstiften förvärms.",
    "AuxBattLowLong" : "12 V batteriladdningen är låg.\nOm denna indikator lyser ofta under körning kan batteriet vara dåligt. Kontrollera fordonet hos återförsäljare.\nOm denna indikator lyser konstant och inte släcks, är 12 V batteriet dött. Läs i ägarmanualen före start av hybridsystemet och kontrollera fordonet hos återförsäljare.",
    "DriveBattDropLong" : "Resteffekten i högspänningsbatteriet är låg eftersom växeln har varit i neutralläge under en lång tid.\nDet går inte att ladda i neutralt läge. Ändra till parkeringsläge när du stannar under längre tid.\nStarta om hybridsystemet genom att trycka på strömbrytaren vid behov.\n\n",
    "ControlSystemErrorLong" : "Fel på parkeringshjälpsystem.\nOm det inte kontrolleras kan det leda till något av följande:\n・Parkeringslåsmekanismen kanske inte fungerar. Parkera på plant underlag och dra åt parkeringsbromsen ordentligt.\n・Strömbrytaren kanske inte släcks. Tryck upprepade gånger på strömbrytaren till den slocknar.\n・ \"Dra åt parkeringsbromsen vid parkering\" slocknar under körning och tänds vid stopp.\nKontrollera omedelbart fordonet på verkstad.\n",
    "EngineOilPressureErrorLong" : "Lågt motoroljetryck.\nStanna omedelbart fordonet på en säker plats, stäng av motorn och kontrollera nivån på motoroljan. Fyll på olja vid behov.\nKontrollera omedelbart fordonet på verkstad om denna indikator tänds efter att olja fyllts på eller om oljenivån är OK.\n",
    "HybridSysErrorLong" : "Fel på hybridsystem.\nFordonet kan skadas om du fortsätter köra. Stanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "HybridSysOverheatLong" : "Fel på hybridsystem.\nFordonet kan skadas om du fortsätter köra. Stanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "PpositionRequestLong" : "Ändra växelläge till parkeringsläge.\nDet orsakas av något av följande:\n・ Systemet har startats eller stoppats med växelväljaren i annat läge än parkeringsläge\n・ Dörren på förarsidan har öppnats med växelväljaren i något av lägena N, D eller B\n・ Den kvarvarande batteriladdningen är låg eftersom växelväljaren varit i neutral länge\nStarta om hybridsystemet vid behov genom att trycka på strömbrytaren.\n\n",
    "ChargingSysErrorLong" : "Fel på laddningssystem. \nFordonet kan skadas om du fortsätter köra.  Stanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "BrakeSysErrorLong" : "Låg bromsvätskenivå eller fel på bromssystem.  Stanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.",
    "EcbSysErrorLong" : "Fel på bromskraftåtervinning eller det elektroniska bromssystemet.\nStanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "AbsSysErrorLong" : "Fel på låsningsfria bromsar (ABS).\nKontrollera omedelbart fordonet på verkstad.\n",
    "DscSysErrorLong" : "Fel på stabilitetskontroll (Dynamic Stability Control, DSC), spårningskontroll (Traction Control System, TCS) eller start i backe-hjälp (Hill Launch Assist, HLA).\nKontrollera omedelbart fordonet på verkstad.\n",
    "DropKeyBattChrgLong" : "Batteriet i nyckeln är svagt.\nByt snarast ut batteriet i nyckeln.\n",
    "EngOilPressureErrorLong" : "Lågt motoroljetryck.\nStanna omedelbart fordonet på en säker plats, stäng av motorn och kontrollera nivån på motoroljan. Fyll på olja vid behov.\nKontrollera omedelbart fordonet på verkstad om denna indikator tänds efter att olja fyllts på eller om oljenivån är OK.\n",
    "ChrgSysErrorLong" : "Fel på laddningssystem.\nStanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "EloopSysErrorLong" : "Fel på i-ELOOP-system.\nKontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "EloopChargingLong" : "i-ELOOP laddas.\nMed motorn igång kontrollerar du att laddningen är slutförd och varningsindikatorn har släckts. Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "LowBrakeFluidLong" : "Låg bromsvätskenivå.\nStanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "BrakeSystemErrorLong" : "Fel på det elektroniska bromssystemet.\nStanna omedelbart fordonet på en säker plats och kontrollera fordonet av verkstad.\n",
    "LowTireAirPressureLong" : "Lågt lufttryck i ett eller flera däck.\nKontrollera lufttryck i däcken och justera till korrekt tryck.  Tryck på TPMS SET när lufttrycket justerats tills ett pip hörs.\n",
    "EngCoolntTempHighOnLong" : "Motorn överhettas.\nStanna omedelbart fordonet på en säker plats, stäng av motorn och vidta nödvändiga åtgärder.  Läs i ägarmanualen.\n",
    "EngineWaterTempRiseLong" : "Motorn börjar att bli varm.\nKör långsamt eller stanna fordonet tills indikatorn slutar blinka. Om den fortsätter blinka, även då fordonet har stoppats, ska du vidta nödvändiga åtgärder. Läs i ägarmanualen.\n",
    "SystemInspectionLong" : "Temperaturen på differentialoljan är extremt hög eller så har en stor rotationsskillnad uppstått i främre och bakre hjulen (som när du försöker köra i lera).\nStanna fordonet på en säker plats och fortsätt sedan köra när varningsindikatorn har slocknat. Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "AccumulationDpfLong" : "Partikelmängden (PM) i dieselpartikelfiltret (DPF) har överskridit tillåtet värde.\nKör i 10 till 15 minuter med motorn helt uppvärmd (den blåa templampan ska inte lysa) i cirka 15 km/h (10 mph) eller mer för att eliminera PM.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "RoadSurfaceIcingCautionLong" : "Utetemperaturen är 4°C eller lägre.\nSe upp för ishalka när du kör.\n",
    "LowFuelLong" : "Låg nivå i bränsletanken.\nFyll på bränsle snarast.\n",
    "FuelCapInspectionLong" : "Bränslelocket kanske inte sitter på ordentligt.\nKontrollera att bränslelocket sitter på och är ordentligt åtdraget.\nEfter att bränslelocket satts på och dragits åt släcks inte indikatorn förrän efter lite körning då det är bekräftat att systemet är OK.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "PowerSteeringSysErrorLong" : "Fel på elektrisk servostyrning.\nStanna fordonet på en säker plats och stäng av motorn.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "EngSystemErrorLong" : "Fel på motorsystem.  Kontrollera omedelbart fordonet på verkstad.",
    "AirbagSysPretensionerSysErrorLong" : "Fel på airbag/säkerhetsbälte",
    "AbsSystemErrorLong" : "Fel på låsningsfria bromsar (ABS).\nKontrollera omedelbart fordonet på verkstad.\n",
    "DscSystemErrorLong" : "Fel på stabilitetskontroll (Dynamic Stability Control, DSC) eller spårningskontroll (Traction Control System, TCS).\nKontrollera omedelbart fordonet på verkstad.\n",
    "RvmSysErrorLong" : "Det finns fel i RVM-systemet.\nKontrollera ytan på bakre stötfångaren och rengör om den är smutsig eller täckt med snö.\nKontrollera fordonet på en Mazda-verkstad om varningslampan fortsätter lysa.\n",
    "BsmSystemErrorLong" : "Fel på Blind Spot Monitoring System (BSM)/Rear Cross Traffic Alert (RCTA).\nKontrollera ytan på bakre stötfångaren och rengör om den är smutsig eller täckt med snö. Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "AfsSystemErrorLong" : "Fel på adaptivt strålkastarsystem (AFS).  Kontrollera fordonet på verkstad om indikatorn fortsätter blinka.",
    "AutoLevelSystemErrorLong" : "Fel på automatisk nivåreglering av strålkastare\nKontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "IstopSysErrorLong" : "i-stop fungerar inte.\nKontrollera fordonet på en Mazda-verkstad.\n",
    "TpmsSysErrorLong" : "Fel på lufttryckskontrollsystem (TPMS).\nKontrollera fordonet på verkstad.\n",
    "KeylesSysErrorLong" : "Fel på nyckelfri öppning-systemet\nKontrollera fordonet på verkstad.\n",
    "FWDSysErrorLong" : "Fel på 4WD-system eller så är däckstorleken olika på fram- och bakhjul.\nKontrollera fordonet på verkstad.",
    "DPFErrorLong" : "Fel på dieselpartikelfilter (DPF).\nKontrollera fordonet på verkstad.\n",
    "AutoTransSysErrorLong" : "Fel på automatisk växellåda.\nFordonet kan skadas om du fortsätter köra.  Kontrollera omedelbart fordonet på verkstad.  \n",
    "BattManagSysErrorLong" : "Fel på batterihantering.\nKontrollera fordonet på verkstad.\n",
    "BrakOverrideSysErrorLong" : "Fel på bromsbrytare.\nKontrollera omedelbart fordonet på verkstad.\n",
    "MRCCSysErrorLong" : "Fel på Mazda Radar Cruise Control (MRCC).\nKontrollera fordonet på verkstad.",
    "SBSSysErrorLong" : "Det finns fel i SBS-systemet.\nKontrollera fordonet på en Mazda-verkstad.\n",
    "FOWSysErrorLong" : "Fel på Forward Obstruction Warning (FOW).\nKontrollera fordonet på verkstad.",
    "DRSSSysErrorLong" : "Det finns fel i DRSS-systemet.\nKontrollera fordonet på en Mazda-verkstad.\n",
    "FOWMRCCRadarSoilingLong" : "Fel på FOW/MRCC-radar (sensor).\nRengör hela ytan på emblemet i grillen om det är smutsigt eller täckt av snö.  \nKontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS-radarn (sensorn) är nedsmutsad.\nRengör hela ytan på radarn (sensorn).\n",
    "SBSMRCCRadarSoilingLong" : "SBS/MRCC-radarn (sensorn) är nedsmutsad.\nRengör hela ytan på radarn (sensorn).\n",
    "SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS-radarn (sensorn) är nedsmutsad.\nRengör hela ytan på radarn (sensorn).\n",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) är för närvarande inte tillgänglig.",
    "SBSBrakeUnavailableLong" : "SBS bromsfunktion är för närvarande inte tillgänglig.",
    "SBSBrakeMRCCUnavailableLong" : "SBS bromsfunktion/MRCC för närvarande inte tillgängligt.",
    "SCBSSysErrorLong" : "Fel på Smart City Brake Support (SCBS).\nKontrollera omedelbart fordonet på verkstad.\n",
    "SCBSWindshieldSoilingLong" : "Fel på Smart City Brake Support (SCBS).\nRengör vindrutan.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) är för närvarande inte tillgänglig.",
    "LDWSSysErrorLong" : "Fel på Lane Departure Warning System (LDWS).\nKontrollera fordonet på verkstad.\n",
    "HBCSysErrorLong" : "Fel på High Beam Control (HBC).\nKontrollera fordonet på verkstad.\n",
    "HBCLLDWSCamDisconnectLong" : "Fel på High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nRengör vindrutan.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "HBCLDWSSysErrorLong" : "Fel på High Beam Control (HBC)/Lane Departure Warning System (LDWS). Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.",
    "HBCLDWSWindshieldFogLong" : "Fel på High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nFrosta av vindrutan.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "SedimenterWarningLong" : "Vattenmängden i sedimenter överskrider den rekommenderade mängden.\nKontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "FuelAirFilterCartReplacePeriodLong" : "Bränsle-/luftfilterkassetten måste bytas ut.",
    "VehicleSysErrorLong" : "Fel på fordonsystem.\nKontrollera fordonet på verkstad.\n",
    "LowWasheFluidLong" : "Låg spolarvätskenivå.\nFyll på spolarvätska.\n",
    "EngineWaterTempDropLong" : "Motorns kylvätska är kall och det finns ingen varm luft för uppvärmning/defroster. Fordonet kan köras med indikatorn både på och av.  Kontrollera fordonet på verkstad om indikatorn fortsätter lysa.",
    "PreheatingDispLampLong" : "Glödstiften förvärms.\nKontrollera fordonet på verkstad om indikatorn fortsätter lysa.\n",
    "HybrdSysMalHighPrt" : "Fel på hybridsystem. Stanna omedelbart fordonet på en säker plats.",
    "ChargSysMalHighPrt" : "Fel på laddningssystem. Stanna omedelbart fordonet på en säker plats.",
    "IeloopChrgHighPrt" : "Laddar i-ELOOP. Med motorn igång kontrollerar du att laddningen är slutförd och varningsindikatorn har släckts.",
    "EngnCoolTempHighHighPrt" : "Hög temperatur på kylvätska. Stanna omedelbart fordonet på en säker plats.",
    "lowBattStartEngine" : "Svagt batteri! Starta motorn!",
    "engineOilPressure" : "Motoroljetryck",
    "brakeFluid" : "Låg bromsvätskenivå",
    "highVoltage" : "Svagt högspänningsbatteri",
};

framework.registerAppDictLoaded("warnguide", "sv_SE");