var Localization_warnguideAppDict_en_UK = {
    //"stringId" : "localString"
    "Warnings" : "Warnings",
    "NoWarnings" : "No Warnings found",
    "WarningSafetyMessage" : "For safety reasons, Warning Guidance is not displayed.",
    "WarningGuidance" : "Warning Guidance",
    "AuxBattLowShrt" : "12V Battery Low",
    "DriveBattDropShrt" : "High Voltage Battery Low",
    "ControlSystemErrorShrt" : "Park Position Cntrl System Error",
    "EngineOilPressureErrorShrt" : "Low Engine Oil Pressure",
    "HybridSysErrorShrt" : "Hybrid System Malfunction",
    "HybridSysOverheatShrt" : "Hybrid System Overheating",
    "PpositionRequestShrt" : "Park Position Request",
    "ChargingSysErrorShrt" : "Charging System Malfunction",
    "BrakeSysErrorShrt" : "Brake System Malfunction",
    "EcbSysErrorShrt" : "Brake System Malfunction",
    "AbsSysErrorShrt" : "ABS Malfunction",
    "DscSysErrorShrt" : "DSC Malfunction",
    "DropKeyBattChrgShrt" : "Key Battery Low",
    "EngOilPressureErrorShrt" : "Low Engine Oil Pressure",
    "ChrgSysErrorShrt" : "Charging System Malfunction",
    "EloopSysErrorShrt" : "i-ELOOP System Malfunction",
    "EloopChargingShrt" : "i-ELOOP Charging",
    "LowBrakeFluidShrt" : "Low Brake Fluid",
    "BrakeSystemErrorShrt" : "Brake System Malfunction",
    "LowTireAirPressureShrt" : "Low Tyre Air Pressure",
    "EngCoolntTempHighOnShrt" : "Engine Coolant Temperature High",
    "EngineWaterTempRiseShrt" : "Engine Coolant Temperature High",
    "SystemInspectionShrt" : "4WD System Inspection",
    "AccumulationDpfShrt" : "PM Accumulation in DPF",
    "RoadSurfaceIcingCautionShrt" : "Road Surface Icing Caution",
    "LowFuelShrt" : "Low Fuel",
    "FuelCapInspectionShrt" : "Fuel Cap Inspection",
    "PowerSteeringSysErrorShrt" : "Power Steering System Error",
    "EngSystemErrorShrt" : "Engine System Malfunction",
    "AirbagSysPretensionerSysErrorShrt" : "Safety Restraint System Error",
    "AbsSystemErrorShrt" : "ABS Malfunction",
    "DscSystemErrorShrt" : "DSC Malfunction",
    "RvmSysErrorShrt" : "RVM Malfunction",
    "BsmSystemErrorShrt" : "BSM Malfunction",
    "AfsSystemErrorShrt" : "AFS Malfunction",
    "AutoLevelSystemErrorShrt" : "Auto-levelling System Malfunction",
    "IstopSysErrorShrt" : "i-stop System Malfunction",
    "TpmsSysErrorShrt" : "TPMS System Malfunction",
    "KeylesSysErrorShrt" : "Keyless Entry Malfunction",
    "FWDSysErrorShrt" : "4WD System Malfunction",
    "DPFErrorShrt" : "DPF Error",
    "AutoTransSysErrorShrt" : "Auto. Transmission Malfunction",
    "BattManagSysErrorShrt" : "Battery Mgmt. Sys. Malfunction",
    "BrakOverrideSysErrorShrt" : "Brake Override Sys.Malfunction",
    "MRCCSysErrorShrt" : "MRCC Malfunction",
    "SBSSysErrorShrt" : "SBS Malfunction",
    "FOWSysError" : "FOW Malfunction",
    "DRSSSysErrorShrt" : "DRSS Malfunction",
    "FOWMRCCRadarSoilingShrt" : "FOW/MRCC Radar Malfunction",
    "FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS Radar Error",
    "SBSMRCCRadarSoilingShrt" : "SBS/MRCC Radar Malfunction",
    "SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS Radar Malf.",
    "MRCCUnavailableShrt" : "MRCC Unavailable",
    "SBSBrakeUnavailableShrt" : "SBS Brake Unavailable",
    "SBSBrakeMRCCUnavailableShrt" : "SBS Brake/MRCC Unavailable",
    "SCBSSysErrorShrt" : "SCBS Malfunction",
    "SCBSWindshieldSoilingShrt" : "SCBS Malfunction",
    "SCBSUnavailableShrt" : "SCBS Unavailable",
    "LDWSSysErrorShrt" : "LDWS Malfunction",
    "HBCSysErrorShrt" : "HBC Malfunction",
    "HBCLLDWSCamDisconnectShrt" : "HBC/LDWS Camera Malfunction",
    "HBCLDWSSysErrorShrt" : "HBC/LDWS System Malfunction",
    "HBCLDWSWindshieldFogShrt" : "HBC/LDWS System Malfunction",
    "SedimenterWarningShrt" : "Sedimenter Inspection",
    "FuelAirFilterCartReplacePeriodShrt" : "Fuel-Air Filter Replacement Rqd.",
    "VehicleSysErrorShrt" : "Vehicle System Malfunction",
    "LowWasheFluidShrt" : "Low Washer Fluid",
    "EngineWaterTempDropShrt" : "Engine Coolant Temperature Low",
    "PreheatingDispLampShrt" : "Glow Plugs Preheating",
    "AuxBattLowLong" : "The 12V Battery Charge is Low.\n・If this indicator is On frequently while driving, the Battery may be degraded. Have the vehicle checked by a dealer.\n・If this Indicator is on constantly and does not turn Off, the 12V Battery is dead. Refer to the Owner's Manual before starting the Hybrid System and have the vehicle checked by a dealer.",
    "DriveBattDropLong" : "The Residual Power in the High Voltage Battery is Low because the transmission has been in the Neutral position for a long time. Charging is not possible in Neutral. Shift to Park when stopped for a long time. Restart the Hybrid System by pressing the Power Switch if necessary.",
    "ControlSystemErrorLong" : "Park Position Control System Malfunction.\nIf left unchecked, can lead to any of the following situations:\n・The Parking Lock mechanism may not function. Park on a flat location and securely set the Parking Brake.\n・The Power Switch may not turn Off. Repeatedly press the Power Switch to turn Off.\n・ \"Set Parking Brake When Parking\" display will turn Off when driving and On when stopped.\nHave the vehicle checked by the dealer immediately.",
    "EngineOilPressureErrorLong" : "Low Engine Oil Pressure. Stop the vehicle immediately in a safe place, turn Off the Engine, and inspect the Engine Oil Level. Add Oil if necessary. Have the vehicle checked by a dealer immediately if this Indicator turns On after adding Oil or the Engine Oil level is OK.",
    "HybridSysErrorLong" : "Hybrid System Malfunction. Damage to the vehicle may occur if you continue to drive. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "HybridSysOverheatLong" : "Hybrid System Malfunction. Damage to the vehicle may occur if you continue to drive. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "PpositionRequestLong" : "Shift the Transmission to Park.\nThis is caused by one of the following:\n・ The Battery System was started or stopped with the transmssion in a position other than Park\n・ The Driver-side Door was opened with the transmission in the N, D, or B  position\n・ The Residual High Voltage Battery Charge is Low because the transmission was in Neutral for a long time.\nRestart the Hybrid System by pressing the Power Switch if necessary.",
    "ChargingSysErrorLong" : "Charging System Malfunction. Damage to the vehicle may occur if you continue to drive.  Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "BrakeSysErrorLong" : "Brake Fluid Level is Low or Brake System Malfunction.  Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "EcbSysErrorLong" : "Regenerative Braking or Electronically-Controlled Brake System Malfunction. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "AbsSysErrorLong" : "Anti-lock Brake System (ABS) Malfunction. Have the vehicle checked by a dealer immediately.",
    "DscSysErrorLong" : "Dynamic Stability Control (DSC), Traction Control System (TCS), or Hill Launch Assist (HLA) Malfunction. Have the vehicle checked by a dealer immediately.",
    "DropKeyBattChrgLong" : "Key Battery is Low. Replace the Key Battery immediately.",
    "EngOilPressureErrorLong" : "Low Engine Oil Pressure. Stop the vehicle immediately in a safe place, turn Off the Engine, and inspect the Engine Oil Level. Add Oil if necessary. Have the vehicle checked by a dealer immediately if this Indicator turns On after adding Oil or the Engine Oil Level is OK.",
    "ChrgSysErrorLong" : "Charging System Malfunction. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "EloopSysErrorLong" : "i-ELOOP System Malfunction. Have the vehicle checked by a dealer if this Indicator stays On.",
    "EloopChargingLong" : "i-ELOOP is charging. With the Engine running, check that charging is complete and the Warning Indicator is Off. Have the vehicle checked by a dealer if this Indicator stays On.",
    "LowBrakeFluidLong" : "Brake Fluid Level is Low. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "BrakeSystemErrorLong" : "Electronically-Controlled Brake System Malfunction. Stop the vehicle immediately in a safe place and have the vehicle checked by a dealer.",
    "LowTireAirPressureLong" : "Low Air Pressure in one or more Tyres.  Check the Air Pressure of the Tyres and adjust to the correct Air Pressure.  Press the TPMS SET switch after adjusting the Tyre pressure until you hear a Beep.",
    "EngCoolntTempHighOnLong" : "Engine is Overheating. Stop the vehicle immediately in a safe place, turn Off the Engine, and take proper actions.  Refer to the Owner's Manual.",
    "EngineWaterTempRiseLong" : "Engine is starting to run Hot. Drive slowly or stop the vehicle until the Indicator stops Flashing. If it keeps Flashing, even after stopping the vehicle, take proper actions. Refer to the Owner's Manual.",
    "SystemInspectionLong" : "The Differential Oil Temperature is Abnormally High or a Large Rotational Difference has occurred in the Front and Rear tyres (such as when trying to get out from mud). Stop the vehicle in a safe place and continue to drive after the Warning Indicator has turned Off. Have the vehicle checked by a dealer if this Indicator stays On.",
    "AccumulationDpfLong" : "The Particulate Matter (PM) collected in the Diesel Particulate Filter (DPF) has exceeded the Regulation Value. Drive for about 10 to 15 minutes with the Engine Fully Warmed-Up (Blue Temp Light Off) at a speed of 10 mph (15km/h) or more to eliminate the PM.  Have the vehicle checked by a dealer if this Indicator stays On.",
    "RoadSurfaceIcingCautionLong" : "Outside Temperature is 4°C or Lower. Watch for Icy Road Surfaces while driving.",
    "LowFuelLong" : "Fuel Tank Level is Low. Refuel the vehicle soon.",
    "FuelCapInspectionLong" : "The Fuel Cap may not be installed properly. Check that the Fuel Cap has been installed and tightened properly. After installing and tightening the Fuel Cap properly, this Indicator will not turn Off for a few drive cycles until it can be confirmed that the system is OK.  Have the vehicle checked by a dealer if this Indicator stays On.",
    "PowerSteeringSysErrorLong" : "Electric Power Steering Malfunction. Stop the vehicle in a safe place and turn Off the Engine.  Have the vehicle checked by a dealer if this Indicator stays On.",
    "EngSystemErrorLong" : "Engine System Malfunction.  Have the vehicle checked by a dealer immediately.",
    "AirbagSysPretensionerSysErrorLong" : "Airbag/Seatbelt Malfunction. Have the vehicle checked by a dealer immediately",
    "AbsSystemErrorLong" : "Anti-lock Brake System (ABS) Malfunction. Have the vehicle checked by a dealer immediately.",
    "DscSystemErrorLong" : "Dynamic Stability Control (DSC)or Traction Control System (TCS) Malfunction. Have the vehicle checked by a dealer immediately.",
    "RvmSysErrorLong" : "There is an error in the RVM System. Check for abnormalities in the Rear Bumper Surface, and clean if soiled or covered with snow. Have your vehicle checked by a Mazda dealer if this Warning Lamp stays On.",
    "BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA) Malfunction. Check for abnormalities in the Rear Bumper Surface and clean if dirty or covered with snow. Have the vehicle checked by a dealer if this Indicator stays On.",
    "AfsSystemErrorLong" : "Adaptive Front-lighting System (AFS) Malfunction. Have the vehicle checked by a dealer if this Indicator keeps Flashing.",
    "AutoLevelSystemErrorLong" : "Headlight Auto-leveling System Malfunction. Have the vehicle checked by a dealer if this Indicator stays On.",
    "IstopSysErrorLong" : "i-stop operation is not possible. Have your vehicle checked at a Mazda dealer.",
    "TpmsSysErrorLong" : "Tyre Pressure Monitoring System (TPMS) Malfunction.  Have the vehicle checked by a dealer.",
    "KeylesSysErrorLong" : "Keyless Entry System Malfunction. Have the vehicle checked by a dealer.",
    "FWDSysErrorLong" : "4WD System Malfunction or Tyre Size is different between the Front and Rear Tyres. Have the vehicle checked by a dealer.",
    "DPFErrorLong" : "Diesel Particulate Filter (DPF) Malfunction. Have the vehicle checked by a dealer.",
    "AutoTransSysErrorLong" : "Automatic Transmission Malfunction. Damage to the vehicle may occur if you continue to drive. Have the vehicle checked by a dealer immediately.  ",
    "BattManagSysErrorLong" : "Battery Management System Malfunction. Have the vehicle checked by a dealer.",
    "BrakOverrideSysErrorLong" : "Brake Switch Malfunction. Have the vehicle checked by a dealer immediately.",
    "MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) Malfunction. Have the vehicle checked by a dealer.",
    "SBSSysErrorLong" : "There is an error in the SBS System. Have your vehicle checked at a Mazda dealer.",
    "FOWSysErrorLong" : "Forward Obstruction Warning (FOW) System Malfunction. Have the vehicle checked by a dealer.",
    "DRSSSysErrorLong" : "There is an error in the DRSS System. Have your vehicle checked at a Mazda dealer.",
    "FOWMRCCRadarSoilingLong" : "FOW/MRCC Radar (Sensor) Malfunction. Clean the entire surface of the Front Grill Emblem if dirty or covered with snow. Have the vehicle checked by a dealer if this Indicator stays On.",
    "FOWMRCCDRSSRadarSoilingLong" : "The FOW/MRCC/DRSS Radar (Sensor) is soiled. Clean the entire surface of the Radar (Sensor).",
    "SBSMRCCRadarSoilingLong" : "The SBS/MRCC Radar (Sensor) is soiled. Clean the entire surface of the Radar (Sensor).",
    "SBSMRCCDRSSRadarSoilingLong" : "The SBS/MRCC/DRSS Radar (Sensor) is soiled. Clean the entire surface of the Radar (Sensor).",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) currently unavailable.",
    "SBSBrakeUnavailableLong" : "SBS Brake currently unavailable.",
    "SBSBrakeMRCCUnavailableLong" : "SBS Brake/MRCC currently unavailable.",
    "SCBSSysErrorLong" : "Smart City Brake Support (SCBS) Malfunction. Have the vehicle checked by a dealer immediately.",
    "SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) Malfunction. Clean the front windscreen.  Have the vehicle checked by a dealer if this Indicator Stays On.",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) currently unavailable.",
    "LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) Malfunction. Have the vehicle checked by a dealer.\n",
    "HBCSysErrorLong" : "High Beam Control (HBC) Malfunction. Have the vehicle checked by a dealer.\n",
    "HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) Malfunction. Clean the Windscreen. Have the vehicle checked by a dealer if this Indicator stays On.",
    "HBCLDWSSysErrorLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) Malfunction. Have the vehicle checked by a dealer if this Indicator stays On.",
    "HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) Malfunction. Defrost the Windscreen. Have the vehicle checked by a dealer if this Indicator stays On.",
    "SedimenterWarningLong" : "The amount of water accumulated in the Sedimenter exceeds the rated amount.\nHave the vehicle checked by a dealer if this Indicator stays On.",
    "FuelAirFilterCartReplacePeriodLong" : "The Fuel-Air Filter Cartridge needs to be replaced.",
    "VehicleSysErrorLong" : "Vehicle System malfunction. Have the vehicle checked by a dealer.",
    "LowWasheFluidLong" : "Washer Fluid Level is Low. Refill the Washer Fluid.",
    "EngineWaterTempDropLong" : "Engine Coolant is Cold and No Warm Air is available for Heater/Defroster. Vehicle can be driven with the Indicator On or Off.  Have the vehicle checked by a dealer if this Indicator stays On.",
    "PreheatingDispLampLong" : "Glow Plugs are Preheating. Have the vehicle checked by a dealer if this Indicator stays On.",
    "HybrdSysMalHighPrt" : "Hybrid System Malfunction. Stop vehicle immediately in a safe place.",
    "ChargSysMalHighPrt" : "Charging System Malfunction. Stop vehicle immediately in a safe place.",
    "ChargSysMalHighPrt" : "Charging System Malfunction. Stop vehicle immediately in a safe place.",
    "IeloopChrgHighPrt" : "i-ELOOP Charging. With the Engine running, check that the charging is complete and the Warning Indicator is Off.",
    "EngnCoolTempHighHighPrt" : "Engine Coolant Temperature High. Stop vehicle immediately in a safe place.",
    "lowBattStartEngine" : "Low Battery! Start Engine!",
    "engineOilPressure" : "Engine Oil Pressure",
    "brakeFluid" : "Brake Fluid Level Low",
    "highVoltage" : "High Voltage Battery Low",
};

framework.registerAppDictLoaded("warnguide", "en_UK");