var Localization_warnguideAppDict_lt_LT = {
    //"stringId" : "localString"
    "Warnings" : "Įspėjimai",
    "NoWarnings" : "Įspėjimų nerasta",
    "WarningSafetyMessage" : "Saugos sumetimais įspėjimų nurodymai nerodomi.",
    "WarningGuidance" : "Įspėjimo nurodymai",
    "AuxBattLowShrt" : "12V akum. žemas įkr. lygis",
    "DriveBattDropShrt" : "Aukštos įt. akum. žemas įkr. l.",
    "ControlSystemErrorShrt" : "Stovėjimo pad. kontr. sist. triktis",
    "EngineOilPressureErrorShrt" : "Variklyje žemas alyvos slėgis",
    "HybridSysErrorShrt" : "Hibridinės sistemos triktis. ",
    "HybridSysOverheatShrt" : "Hibridinė sistema perkaito",
    "PpositionRequestShrt" : "Stovėjimo padėties užklausa",
    "ChargingSysErrorShrt" : "Įkrovimo sistemos triktis",
    "BrakeSysErrorShrt" : "Stabdžių sistemos triktis",
    "EcbSysErrorShrt" : "Stabdžių sistemos triktis",
    "AbsSysErrorShrt" : "ABS triktis",
    "DscSysErrorShrt" : "DSC triktis",
    "DropKeyBattChrgShrt" : "Senka rakto maitinimo elementas",
    "EngOilPressureErrorShrt" : "Variklyje žemas alyvos slėgis",
    "ChrgSysErrorShrt" : "Įkrovimo sistemos triktis",
    "EloopSysErrorShrt" : "i-ELOOP sistemos triktis",
    "EloopChargingShrt" : "i-ELOOP įkrovimas",
    "LowBrakeFluidShrt" : "Mažai stabdžių skysčio",
    "BrakeSystemErrorShrt" : "Stabdžių sistemos triktis",
    "LowTireAirPressureShrt" : "Žemas padangos oro slėgis",
    "EngCoolntTempHighOnShrt" : "Aukšta aušinimo skysčio temp.",
    "EngineWaterTempRiseShrt" : "Aukšta aušinimo skysčio temp.",
    "SystemInspectionShrt" : "4WD sistemos tikrinimas",
    "AccumulationDpfShrt" : "PM akumuliavimas DPF-e",
    "RoadSurfaceIcingCautionShrt" : "Įsp. dėl kelio paviršiaus apledėjimo",
    "LowFuelShrt" : "Mažai degalų",
    "FuelCapInspectionShrt" : "Degalų bako dangtelio tikrinimas",
    "PowerSteeringSysErrorShrt" : "Vairo stiprintuvo sistemos triktis",
    "EngSystemErrorShrt" : "Variklio sistemos triktis",
    "AirbagSysPretensionerSysErrorShrt" : "Or. pag. sist./autom. įtr. rit. t.",
    "AbsSystemErrorShrt" : "ABS triktis",
    "DscSystemErrorShrt" : "DSC triktis",
    "RvmSysErrorShrt" : "RVM triktis",
    "BsmSystemErrorShrt" : "BSM triktis",
    "AfsSystemErrorShrt" : "AFS triktis",
    "AutoLevelSystemErrorShrt" : "Autom. išlyginimo sist. triktis",
    "IstopSysErrorShrt" : "i-stop sistemos triktis",
    "TpmsSysErrorShrt" : "TPMS sistemos triktis",
    "KeylesSysErrorShrt" : "Berakčio įėjimo triktis",
    "FWDSysErrorShrt" : "4WD sistemos triktis",
    "DPFErrorShrt" : "DPF klaida",
    "AutoTransSysErrorShrt" : "Automatinės pavarų dėžės triktis",
    "BattManagSysErrorShrt" : "Akumuliatoriaus vald. sist. triktis",
    "BrakOverrideSysErrorShrt" : "Stabdžio atjungimo sist. triktis",
    "MRCCSysErrorShrt" : "MRCC triktis",
    "SBSSysErrorShrt" : "SBS triktis",
    "FOWSysError" : "FOW triktis",
    "DRSSSysErrorShrt" : "DRSS triktis",
    "FOWMRCCRadarSoilingShrt" : "FOW/MRCC radaro triktis",
    "FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRC /DRSS rad. triktis",
    "SBSMRCCRadarSoilingShrt" : "SBS/MRCC radaro triktis",
    "SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS rad. triktis",
    "MRCCUnavailableShrt" : "MRCC nepasiekiamas",
    "SBSBrakeUnavailableShrt" : "SBS stabdys nepasiekiamas",
    "SBSBrakeMRCCUnavailableShrt" : "SBS stabdys / MRCC nep.",
    "SCBSSysErrorShrt" : "SCBS triktis",
    "SCBSWindshieldSoilingShrt" : "SCBS triktis",
    "SCBSUnavailableShrt" : "SCBS nepasiekiama",
    "LDWSSysErrorShrt" : "LDWS triktis",
    "HBCSysErrorShrt" : "HBC triktis",
    "HBCLLDWSCamDisconnectShrt" : "HBC/LDWS kameros triktis",
    "HBCLDWSSysErrorShrt" : "HBC/LDWS sistemos triktis",
    "HBCLDWSWindshieldFogShrt" : "HBC/LDWS sistemos triktis",
    "SedimenterWarningShrt" : "Nusodinimo įtaiso tikrinimas",
    "FuelAirFilterCartReplacePeriodShrt" : "Reikia pakeisti kuro oro filtro kasetę",
    "VehicleSysErrorShrt" : "Automobilio sistemos triktis",
    "LowWasheFluidShrt" : "Mažai apliejiklio skysčio",
    "EngineWaterTempDropShrt" : "Žema variklio auš. skys. temp.",
    "PreheatingDispLampShrt" : "Šildomos žvakės",
    "AuxBattLowLong" : "12V akumuliatoriaus įkrova yra žema. ・Jei šis indikatorius dažnai įsijungia važiuojant, akumuliatoriaus veikimas galėjo pablogėti. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n・Jei šis indikatorius yra nuolat įjungtas ir neišsijungia, 12V akumuliatorius yra visiškai iškrautas. Prieš paleisdami hibridinę sistemą, žr. eksploatacijos instrukciją ir kreipkitės į prekybos atstovą, kad patikrintų ",
    "DriveBattDropLong" : "Likutinė energija aukštos įtampos akumuliatoriuje yra žema, nes pavarų svirtis ilgą laiką buvo neutralioje padėtyje. Neutralioje padėtyje įkrovimas neįmanomas. Sustoję ilgesniam laikui perjunkite į stovėjimo padėtį.\nPrireikus iš naujo paleiskite hibridinę sistemą paspausdami maitinimo jungiklį.\n",
    "ControlSystemErrorLong" : "Stovėjimo padėties kontrolės sistemos triktis. Jei nepatikrinsite, gali susidaryti viena iš šių situacijų: ・Stovėjimo užrakto mechanizmas gali neveikti. Pastatykite lygioje vietoje ir patikimai įjunkite stovėjimo stabdį.\n・Maitinimo jungiklis gali neišsijungti. Pakartotinai spausdami maitinimo jungiklį išjunkite.\n・ Ekranas „Įjunkite stovėjimo stabdį stovėdami“ dings važiuojant ir atsiras sustojus.\nNedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n",
    "EngineOilPressureErrorLong" : "Žemas variklio alyvos slėgis. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir patikrinkite variklio alyvos lygį. Įpilkite alyvos, jei reikia. Jei ši lemputė užsidega įpylus alyvos arba jei alyvos lygis tinkamas, nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HybridSysErrorLong" : "Hibridinės sistemos triktis. Važiuodami toliau galite sugadinti automobilį. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HybridSysOverheatLong" : "Hibridinės sistemos triktis. Važiuodami toliau galite sugadinti automobilį. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "PpositionRequestLong" : "Perjunkite pavaros svirtį į stovėjimo padėtį. Tai atsitiko dėl vienos iš žemiau pateiktų priežasčių:・ Akumuliatoriaus sistema buvo įjungta arba išjungta, kai pavarų svirtis buvo ne stovėjimo padėtyje\n・ Vairuotojo durys buvo atidarytos, kai pavaros svirtis buvo padėtyje N, D arba B\n・ Likutinė aukštos įtampos akumuliatoriaus įkrova yra žema, nes pavara buvo neutralioje padėtyje ilgą laiką\nPrireikus paleiskite hibridinę sistemą iš naujo paspausdami maitinimo jungiklį.\n",
    "ChargingSysErrorLong" : "Įkrovimo sistemos triktis. Važiuodami toliau galite sugadinti automobilį.  Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "BrakeSysErrorLong" : "Žemas stabdžių skysčio lygis arba stabdžių sistemos triktis.  Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "EcbSysErrorLong" : "Regeneracinio stabdymo arba elektroniniu būdu valdomos stabdžių sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AbsSysErrorLong" : "Stabdžių antiblokavimo sistemos (ABS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "DscSysErrorLong" : "Dinaminio stabilumo valdymo sistemos (DSC), traukos valdymo sistemos (TCS) arba pajudėjimo įkalnėje pagalbos sistemos (HLA) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "DropKeyBattChrgLong" : "Senka rakto maitinimo elementas. Nedelsdami pakeiskite rakto maitinimo elementą.",
    "EngOilPressureErrorLong" : "Žemas variklio alyvos slėgis. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir patikrinkite variklio alyvos lygį. Įpilkite alyvos, jei reikia. Jei ši lemputė užsidega įpylus alyvos arba jei alyvos lygis tinkamas, nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "ChrgSysErrorLong" : "Įkrovimo sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "EloopSysErrorLong" : "i-ELOOP sistemos triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "EloopChargingLong" : "i-ELOOP įkrovimas. Varikliui veikiant patikrinkite, ar įkrovimas baigėsi ir įspėjamoji lemputė užgeso. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "LowBrakeFluidLong" : "Žemas stabdžių skysčio lygis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "BrakeSystemErrorLong" : "Elektroniniu būdu valdomos stabdžių sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "LowTireAirPressureLong" : "Žemas oro slėgis vienoje ar keliose padangose. Tikrinkite oro slėgį padangose ir sureguliuokite tinkamą oro slėgį.  Sureguliavę slėgį padangose, spauskite jungiklį TPMS SET, kol išgirsite pyptelėjimą.",
    "EngCoolntTempHighOnLong" : "Variklis kaista. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir imkitės reikiamų veiksmų.  Žr. eksploatacijos instrukciją.",
    "EngineWaterTempRiseLong" : "Variklis pradeda kaisti. Važiuokite lėtai arba sustokite, kol lemputė nesiliaus mirksėti. Jei toliau mirksi net ir sustojus, imkitės reikiamų veiksmų. Žr. eksploatacijos instrukciją.",
    "SystemInspectionLong" : "Diferencialo alyvos temperatūra neįprastai aukšta arba susidarė didelis sukimosi skirtumas tarp priekinių ir galinių ratų (pvz., bandant išvažiuoti iš purvo). Sustokite saugioje vietoje ir tęskite kelionę, kai įspėjamoji lemputė užges. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AccumulationDpfLong" : "Kietųjų dalelių (PM) kiekis, surinktas dyzelino dalelių filtre (DPF), viršijo norminę vertę. 10–15 minučių važiuokite iki galo įkaitusiu varikliu (mėlyna temperatūros lemputė turi užgesti) 10 myl./val. (15 km/val.) ar didesniu greičiu, kad pašalintumėte kietąsias daleles.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "RoadSurfaceIcingCautionLong" : "Lauko temperatūra yra 4 °C arba žemesnė. Važiuodami saugokitės apledėjusių kelio paviršių.",
    "LowFuelLong" : "Žemas degalų lygis bake. Greitu metu įpilkite degalų.",
    "FuelCapInspectionLong" : "Galbūt netinkamai uždėtas degalų bako dangtelis. Patikrinkite, ar degalų bako dangtelis tinkamai uždėtas ir priveržtas.\nUždėjus ir tinkamai priveržus degalų bako dangtelį, ši lemputė neužges kelis važiavimo ciklus, kol nebus įsitikinta, kad sistemoje viskas gerai.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n",
    "PowerSteeringSysErrorLong" : "Elektrinio vairo stiprintuvo triktis. Sustokite saugioje vietoje ir išjunkite variklį.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "EngSystemErrorLong" : "Variklio sistemos triktis.  Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AirbagSysPretensionerSysErrorLong" : "Oro pagalvės/saugos diržo triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį",
    "AbsSystemErrorLong" : "Stabdžių antiblokavimo sistemos (ABS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį. ",
    "DscSystemErrorLong" : "Dinaminio stabilumo valdymo sistemos (DSC) arba traukos valdymo sistemos (TCS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "RvmSysErrorLong" : "Įvyko klaida RVM sistemoje. Tikrinkite galinio buferio paviršių ir nuvalykite, jei nešvarus arba padengtas sniegu.\nJei ši įspėjamoji lemputė toliau švies, kreipkitės į Mazda atstovą, kad patikrintų automobilį.\n",
    "BsmSystemErrorLong" : "Blind Spot Monitoring (BSM) /Rear Cross Traffic Alert (RCTA) sistemos triktis. Tikrinkite galinio buferio paviršių ir nuvalykite, jei nešvarus arba padengtas sniegu. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AfsSystemErrorLong" : "Adaptyviosios priekinio apšvietimo sistemos (AFS) triktis.  Jei ši lemputė nesiliaus mirksėti, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AutoLevelSystemErrorLong" : "Priekinių žibintų automatinio išlyginimo sistemos triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "IstopSysErrorLong" : "i-stop veikimas neįmanomas. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
    "TpmsSysErrorLong" : "Slėgio padangose stebėjimo sistemos (TPMS) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "KeylesSysErrorLong" : "Berakčio įėjimo triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "FWDSysErrorLong" : "4WD sistemos triktis arba skiriasi galinių ir priekinių padangų dydis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "DPFErrorLong" : "Dyzelino dalelių filtro (DPF) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "AutoTransSysErrorLong" : "Automatinės pavarų dėžės triktis. Važiuodami toliau galite sugadinti automobilį.  Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "BattManagSysErrorLong" : "Akumuliatoriaus valdymo sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "BrakOverrideSysErrorLong" : "Stabdžio jungiklio triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "SBSSysErrorLong" : "Įvyko klaida SBS sistemoje. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
    "FOWSysErrorLong" : "Forward Obstruction Warning  (FOW) sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "DRSSSysErrorLong" : "Įvyko klaida DRSS sistemoje. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
    "FOWMRCCRadarSoilingLong" : "FOW/MRCC radaro (jutiklio) triktis. Nuvalykite visą priekinių grotelių emblemos paviršių, jei nešvarus arba padengtas sniegu.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
    "SBSMRCCRadarSoilingLong" : "SBS/MRCC radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
    "SBSMRCCDRSSRadarSoilingLong" : "SB /MRCC/DRSS radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
    "MRCCUnavailableLong" : "Mazda radaro pastovaus greičio reguliatorius (MRCC) šiuo metu nepasiekiamas.",
    "SBSBrakeUnavailableLong" : "SBS stabdys šiuo metu nepasiekiamas.",
    "SBSBrakeMRCCUnavailableLong" : "SBS stabdys/MRCC šiuo metu nepasiekiamas.",
    "SCBSSysErrorLong" : "Smart City Brake Support  (SCBS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) šiuo metu nepasiekiama.",
    "LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HBCSysErrorLong" : "High Beam Control (HBC) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HBCLDWSSysErrorLong" : "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HBCLDWSWindshieldFogLong" : "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis. Pašildykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "SedimenterWarningLong" : "Nusodinimo įtaise susikaupusio vandens kiekis viršija normą. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "FuelAirFilterCartReplacePeriodLong" : "Reikia pakeisti degalų oro filtro kasetę.",
    "VehicleSysErrorLong" : "Automobilio sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "LowWasheFluidLong" : "Žemas langų apiplovimo skysčio lygis. Įpilkite apliejiklio skysčio.",
    "EngineWaterTempDropLong" : "Variklio aušinimo skystis šaltas ir šildytuve/stiklo šildytuve nėra šilto oro.  Automobiliu galima važiuoti ir lemputei švytint, ir nešvytint.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "PreheatingDispLampLong" : "Šildomos žvakės. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
    "HybrdSysMalHighPrt" : "Hibridinės sistemos triktis. Nedelsdami sustokite saugioje vietoje.",
    "ChargSysMalHighPrt" : "Įkrovimo sistemos triktis. Nedelsdami sustokite saugioje vietoje.",
    "IeloopChrgHighPrt" : "i-ELOOP įkrovimas. Varikliui veikiant patikrinkite, ar įkrovimas baigėsi ir įspėjamoji lemputė užgeso.",
    "EngnCoolTempHighHighPrt" : "Aukšta variklio aušinimo skysčio temperatūra. Nedelsdami sustokite saugioje vietoje.",
    "lowBattStartEngine" : "Akum. išsikrovęs! Užveskite variklį!",
    "engineOilPressure" : "Variklio alyvos slėgis",
    "brakeFluid" : "Žemas stabdžių skysčio lygis",
    "highVoltage" : "Aukštos įtampos akum. išsikrovęs",
};

framework.registerAppDictLoaded("warnguide", "lt_LT");