var Localization_warnguideAppDict_it_IT = {
    //"stringId" : "localString"
    "Warnings" : "Avvisi",
    "NoWarnings" : "Nessun avviso trovato.",
    "WarningSafetyMessage" : "Per ragioni di sicurezza, la guida agli avvisi non è visualizzata.",
    "WarningGuidance" : "Guida avvisi",
    "AuxBattLowShrt" : "Batteria 12V quasi scarica",
    "DriveBattDropShrt" : "Batteria ad alta tensione quasi scarica",
    "ControlSystemErrorShrt" : "Guasto posizione parcheggio",
    "EngineOilPressureErrorShrt" : "Pressione olio motore bassa",
    "HybridSysErrorShrt" : "Guasto sistema ibrido",
    "HybridSysOverheatShrt" : "Surriscaldamento sistema ibrido",
    "PpositionRequestShrt" : "Richiesta posizione parcheggio",
    "ChargingSysErrorShrt" : "Guasto sistema ricarica",
    "BrakeSysErrorShrt" : "Guasto sistema frenata",
    "EcbSysErrorShrt" : "Guasto sistema frenata",
    "AbsSysErrorShrt" : "Guasto ABS",
    "DscSysErrorShrt" : "Guasto DSC",
    "DropKeyBattChrgShrt" : "Batteria della chiave quasi scarica",
    "EngOilPressureErrorShrt" : "Pressione olio motore bassa",
    "ChrgSysErrorShrt" : "Guasto sistema ricarica",
    "EloopSysErrorShrt" : "Guasto sistema i-ELOOP",
    "EloopChargingShrt" : "Caricamento i-ELOOP",
    "LowBrakeFluidShrt" : "Fluido freni basso",
    "BrakeSystemErrorShrt" : "Guasto sistema frenata",
    "LowTireAirPressureShrt" : "Pressione aria gomme bassa",
    "EngCoolntTempHighOnShrt" : "Temp refrigerante motore alta",
    "EngineWaterTempRiseShrt" : "Temp refrigerante motore alta",
    "SystemInspectionShrt" : "Ispezione sistema 4WD",
    "AccumulationDpfShrt" : "Accumulo PM in DPF",
    "RoadSurfaceIcingCautionShrt" : "Attenzione superficie ghiacciata",
    "LowFuelShrt" : "Poco carburante",
    "FuelCapInspectionShrt" : "Ispezione coperchio carburante",
    "PowerSteeringSysErrorShrt" : "Guasto servosterzo elettrico",
    "EngSystemErrorShrt" : "Guasto sistema del motore",
    "AirbagSysPretensionerSysErrorShrt" : "Guasto airbag/pretensionatori",
    "AbsSystemErrorShrt" : "Guasto ABS",
    "DscSystemErrorShrt" : "Guasto DSC",
    "RvmSysErrorShrt" : "Guasto RVM",
    "BsmSystemErrorShrt" : "Guasto BSM",
    "AfsSystemErrorShrt" : "Guasto AFS",
    "AutoLevelSystemErrorShrt" : "Guasto livellamento automatico",
    "IstopSysErrorShrt" : "Guasto sistema i-stop",
    "TpmsSysErrorShrt" : "Guasto sistema TPMS",
    "KeylesSysErrorShrt" : "Guasto apertura senza chiavi",
    "FWDSysErrorShrt" : "Guasto sistema 4WD",
    "DPFErrorShrt" : "Errore DPF",
    "AutoTransSysErrorShrt" : "Guasto cambio automatico",
    "BattManagSysErrorShrt" : "Guasto sistema gestione batteria",
    "BrakOverrideSysErrorShrt" : "Guasto riconoscimento frenata",
    "MRCCSysErrorShrt" : "Guasto MRCC",
    "SBSSysErrorShrt" : "Guasto SBS",
    "FOWSysError" : "Guasto FOW",
    "DRSSSysErrorShrt" : "Guasto DRSS",
    "FOWMRCCRadarSoilingShrt" : "Guasto radar FOW/MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Guasto radar FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Guasto radar SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Guasto radar SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC non disponibile",
    "SBSBrakeUnavailableShrt" : "Frenata SBS non disponibile.",
    "SBSBrakeMRCCUnavailableShrt" : "Frenata SBS/MRCC non disponibile",
    "SCBSSysErrorShrt" : "Guasto SCBS",
    "SCBSWindshieldSoilingShrt" : "Guasto SCBS",
    "SCBSUnavailableShrt" : "SCBS non disponibile",
    "LDWSSysErrorShrt" : "Guasto LDWS",
    "HBCSysErrorShrt" : "Guasto HBC",
    "HBCLLDWSCamDisconnectShrt" : "Guasto telecamera HBC/LDWS",
    "HBCLDWSSysErrorShrt" : "Guasto sistema HBC/LDWS",
    "HBCLDWSWindshieldFogShrt" : "Guasto sistema HBC/LDWS",
    "SedimenterWarningShrt" : "Ispezione sedimentatore",
    "FuelAirFilterCartReplacePeriodShrt" : "Cambiare filtro carburante-aria",
    "VehicleSysErrorShrt" : "Guasto sistema veicolo",
    "LowWasheFluidShrt" : "Poco fluido pulente",
    "EngineWaterTempDropShrt" : "Temp refrigerante motore bassa",
    "PreheatingDispLampShrt" : "Riscaldamento candelette",
    "AuxBattLowLong" : "La batteria 12V è quasi scarica.\n· Se questo indicatore si accende frequentemente durante la guida, la batteria potrebbe essere danneggiata. Far controllare il veicolo da un concessionario.\n· Se questa spia si accende costantemente e non si spegne, la batteria 12V è fuori uso. Fare riferimento al manuale di istruzioni prima di avviare il sistema ibrido e far controllare il veicolo da un concessionario.",
    "DriveBattDropLong" : "La potenza residua nella batteria ad alta tensione è bassa perché il cambio è stato in posizione di folle per lungo tempo. Con il cambio su N, il caricamento non avviene. Posizionare su Park se ci si ferma a lungo.\nRiavviare il sistema ibrido premendo il pulsante di accensione se necessario.",
    "ControlSystemErrorLong" : "Guasto sistema di controllo posizione parcheggio. Se non controllato, può causare le seguenti situazioni:\n・Il meccanismo del blocco parcheggio potrebbe non funzionare. Parcheggiare, quindi,  in una zona pianeggiante e azionare il freno a mano.                ・Il pulsante di accensione potrebbe non spegnersi. Premere ripetutamente il pulsante per spegnerlo.\n・ Il display \"\"Azionare freno a mano quando si parcheggia\"\" si può spegnere mentre guidate e accendere se vi fermate.\nIn questo caso, far controllare immediatamente il veicolo da un concessionario.\n",
    "EngineOilPressureErrorLong" : "Pressione olio motore bassa. Fermare immediatamente il veicolo in un posto sicuro, spegnere il motore e controllare il livello di olio. Aggiungere olio se necessario. Far controllare immediatamente il veicolo da un concessionario se la spia si accende dopo aver aggiunto dell'olio o se il livello di olio nel motore è giusto.",
    "HybridSysErrorLong" : "Guasto sistema ibrido. Se si continua a guidare, si potrebbe danneggiare il veicolo. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "HybridSysOverheatLong" : "Guasto sistema ibrido. Se si continua a guidare, si potrebbe danneggiare il veicolo. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "PpositionRequestLong" : "Riportare il cambio su Park. Questo può essere causato dalle situazioni seguenti:\n・ Il sistema della batteria è stato avviato o fermato con il cambio in una posizione diversa da Park.\n・La porta del conducente è stata aperta con il cambio in N, D o B.\n・ La batteria ad alta tensione è quasi scarica perché il cambio è stato in folle per lungo tempo.\nRiavviare il sistema ibrido premendo il pulsante di accensione, se necessario.\n",
    "ChargingSysErrorLong" : "Guasto sistema di ricarica. Se si continua a guidare, si potrebbe danneggiare il veicolo.  Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "BrakeSysErrorLong" : "Livello olio freni basso o malfunzionamento del sistema di frenata.  Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "EcbSysErrorLong" : "Guasto sistema di frenata rigenerativa o controllata elettricamente. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "AbsSysErrorLong" : "Guasto sistema antibloccaggio (ABS). Far controllare immediatamente il veicolo da un concessionario.",
    "DscSysErrorLong" : "Guasto controllo stabilità dinamica (DSC), sistema controllo trazione (TCS) o assistenza per ripartenza in salita (HLA). Far immediatamente controllare il veicolo da un concessionario.",
    "DropKeyBattChrgLong" : "Livello batteria chiave basso. Sostituire immediatamente la batteria della chiave.",
    "EngOilPressureErrorLong" : "Pressione olio motore bassa. Fermare immediatamente il veicolo in un posto sicuro, spegnere il motore e controllare il livello di olio. Aggiungere olio se necessario. Far controllare immediatamente il veicolo da un concessionario se la spia si accende dopo aver aggiunto dell'olio o se il livello di olio nel motore è giusto.",
    "ChrgSysErrorLong" : "Guasto sistema di ricarica. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "EloopSysErrorLong" : "Guasto sistema i-ELOOP. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "EloopChargingLong" : "Caricamento i-ELOOP. Con il motore in funzione, controllare che il caricamento sia completo e la spia spenta. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "LowBrakeFluidLong" : "Il livello del fluido freni è basso. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un fornitore.",
    "BrakeSystemErrorLong" : "Guasto sistema di frenata controllato elettronicamente. Fermare immediatamente il veicolo in un posto sicuro e farlo controllare da un concessionario.",
    "LowTireAirPressureLong" : "Pressione dell'aria bassa in una o più gomme. Controllare la pressione dell'aria delle gomme e modificarla se necessario.  Premere il pulsante TPMS SET dopo aver modificato la pressione fin quando non si sente un beep.",
    "EngCoolntTempHighOnLong" : "Il motore è surriscaldato. Fermare immediatamente il veicolo in un posto sicuro, spegnere il motore e fare ciò che è necessario.  Far riferimento al manuale per le istruzioni.",
    "EngineWaterTempRiseLong" : "Il motore sta cominciando a surriscaldarsi. Guidare lentamente o fermare il veicolo fin quando la spia non smetta di lampeggiare. Se continua anche dopo lo spegnimento del veicolo, comportarsi di conseguenza. Far riferimento al manuale per le istruzioni.",
    "SystemInspectionLong" : "La temperatura dell'olio differenziale è troppo alta o si è verificata una differenza di rotazione tra le ruote posteriori e anteriori (come quando si cerca di tirar fuori il veicolo dal fango). Fermare il veicolo in un luogo sicuro e continuare a guidare dopo che la spia si sia spenta. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "AccumulationDpfLong" : "La sostanza particolata (PM) raccolta nel filtro particolato diesel (DPF) ha superato il limite regolare. Guidare per 10-15 minuti con il motore riscaldato (spia temperatura blu spenta) a una velocità di 15km/h o più per eliminare il PM.  Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "RoadSurfaceIcingCautionLong" : "La temperatura esterna è di 4°C o meno. Controllare che il manto stradale non sia ghiacciato mentre si guida.",
    "LowFuelLong" : "Il livello di carburante è basso. Far rifornimento presto.",
    "FuelCapInspectionLong" : "Il coperchio del carburante non è posizionato correttamente. Controllare che sia stato posizionato e chiuso correttamente.\nDopo averlo chiuso in maniera appropriata, la spia non si spegnerà per pochi cicli di guida fin quando il sistema non sarà a posto.  Far controllare il veicolo da un concessionario se la spia rimane accesa.\n",
    "PowerSteeringSysErrorLong" : "Guasto servosterzo elettrico. Fermare il veicolo in un posto sicuro e spegnere il motore.  Far controllare il veicolo da un concessionario se l'indicatore rimane acceso.",
    "EngSystemErrorLong" : "Guasto al sistema del motore. Far immediatamente controllare il veicolo da un concessionario.",
    "AirbagSysPretensionerSysErrorLong" : "Guasto Airbag/Cinture. Far controllare immediatamente il veicolo da un concessionario.",
    "AbsSystemErrorLong" : "Guasto sistema antibloccaggio (ABS). Far controllare immediatamente il veicolo da un concessionario.",
    "DscSystemErrorLong" : "Guasto controllo stabilità dinamica (DSC) o sistema controllo trazione (TCS).  Far immediatamente controllare il veicolo da un concessionario.",
    "RvmSysErrorLong" : "Si è verificato un errore nel sistema RVM. Controllare che non ci siano anomalie sulla superficie del paraurti posteriore e pulire se sporco o coperto da neve.\nFar controllare il veicolo da un concessionario Mazda se la spia rimane accesa.\n",
    "BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA). Controllare se ci sono anomalie sulla superficie del paraurti posteriore e pulirlo se ricoperto da polvere o neve. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "AfsSystemErrorLong" : "Guasto sistema luci anteriori adattive (AFS)  Far controllare il veicolo da un concessionario se la spia continua a lampeggiare.",
    "AutoLevelSystemErrorLong" : "Guasto al sistema livellamento automatico fari. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "IstopSysErrorLong" : "Impossibile operare con i-stop. Far controllare il veicolo da un concessionario Mazda.",
    "TpmsSysErrorLong" : "Guasto sistema monitoraggio pressione (TPMS). Far controllare immediatamente il veicolo da un concessionario.",
    "KeylesSysErrorLong" : "Guasto apertura senza chiavi. Far controllare immediatamente il veicolo da un concessionario.",
    "FWDSysErrorLong" : "Guasto sistema 4WD o differenza di grandezza tra le ruote anteriori e posteriori. Far controllare il veicolo da un concessionario.",
    "DPFErrorLong" : "Guasto filtro particolato Diesel (DPF). Far controllare il veicolo da un concessionario.",
    "AutoTransSysErrorLong" : "Guasto trasmissione automatica. Se si continua a guidare, si potrebbe danneggiare il veicolo.  Far immediatamente controllare il veicolo da un concessionario.  ",
    "BattManagSysErrorLong" : "Guasto sistema gestione batteria. Far controllare immediatamente il veicolo da un concessionario.",
    "BrakOverrideSysErrorLong" : "Guasto cambio freno. Far controllare immediatamente il veicolo da un concessionario.",
    "MRCCSysErrorLong" : "Guasto Mazda Radar Cruise Control (MRCC). Far controllare il veicolo da un concessionario.",
    "SBSSysErrorLong" : "Si è verificato un errore nel sistema SBS. Far controllare il veicolo da un concessionario Mazda.",
    "FOWSysErrorLong" : "Guasto sistema Forward Obstruction Warning (FOW). Far controllare immediatamente il veicolo da un concessionario.",
    "DRSSSysErrorLong" : "Il dispositivo USB è stato disconnesso. Si è verificato un errore nel sistema DRSS.\r\nFar controllare il veicolo da un concessionario Mazda.",
    "FOWMRCCRadarSoilingLong" : "Guasto radar (sensore) FOW/MRCC.\nPulire tutta la superficie dello stemma anteriore se è coperto da polvere o neve.  Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "FOWMRCCDRSSRadarSoilingLong" : "Il radar (sensore) FOW/MRCC/DRSS è sporco. Pulire l'intera superficie del radar (sensore).",
    "SBSMRCCRadarSoilingLong" : "Il radar (sensore) SBS/MRCC è sporco. Pulire l'intera superficie del radar (sensore).",
    "SBSMRCCDRSSRadarSoilingLong" : "Il radar (sensore) SBS/MRCC è sporco. Pulire l'intera superficie del radar (sensore).",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) non è attualmente disponibile.",
    "SBSBrakeUnavailableLong" : "Frenata SBS attualmente non disponibile.",
    "SBSBrakeMRCCUnavailableLong" : "Frenata SBS/MRCC attualmente non disponibile.",
    "SCBSSysErrorLong" : "Guasto Smart City Brake Support (SCBS). Far controllare immediatamente il veicolo da un concessionario.",
    "SCBSWindshieldSoilingLong" : "Guasto Smart City Brake Support (SCBS). Pulire il parabrezza anteriore.  Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) attualmente non disponibile.",
    "LDWSSysErrorLong" : "Guasto Lane Departure Warning System (LDWS). Far controllare immediatamente il veicolo da un concessionario.",
    "HBCSysErrorLong" : "Guasto High Beam Control (HBC). Far controllare il veicolo da un concessionario.",
    "HBCLLDWSCamDisconnectLong" : "Guasto High Beam Control (HBC)/Lane Departure Warning System (LDWS). Pulire il parabrezza.  Far controllare il veicolo da un concessionario se la freccia rimane accesa.",
    "HBCLDWSSysErrorLong" : "Guasto High Beam Control (HBC)/Lane Departure Warning System (LDWS). Far controllare il veicolo da un concessionario se la freccia rimane accesa.",
    "HBCLDWSWindshieldFogLong" : "Guasto High Beam Control (HBC)/Lane Departure Warning System (LDWS). Scongelare il parabrezza.  Far controllare il veicolo da un concessionario se la freccia rimane accesa.",
    "SedimenterWarningLong" : "La quantità di acqua accumulata nel sedimentatore supera il limite prestabilito. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "FuelAirFilterCartReplacePeriodLong" : "È necessario sostituire il filtro carburante-aria.",
    "VehicleSysErrorLong" : "Guasto sistema veicolo. Far controllare immediatamente il veicolo da un concessionario.",
    "LowWasheFluidLong" : "Il livello del fluido pulente è basso. Rimettere fluido pulente.",
    "EngineWaterTempDropLong" : "Il refrigerante del motore è freddo e non è disponibile aria calda per il riscaldamento o lo scongelamento. Il veicolo può essere guidato con la spia accesa o spenta.  Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "PreheatingDispLampLong" : "Le candelette si stanno riscaldando. Far controllare il veicolo da un concessionario se la spia rimane accesa.",
    "HybrdSysMalHighPrt" : "Guasto sistema ibrido. Fermare subito il veicolo in un posto sicuro. ",
    "ChargSysMalHighPrt" : "Guasto sistema di ricarica. Fermare subito il veicolo in un posto sicuro.",
    "IeloopChrgHighPrt" : "Caricamento i-ELOOP. Con il motore in funzione, controllare che il caricamento sia completo e la spia spenta. ",
    "EngnCoolTempHighHighPrt" : "Temperatura refrigerante motore alta. Fermare il veicolo in un posto sicuro.",
    "lowBattStartEngine" : "Batteria scarica. Accendere il motore",
    "engineOilPressure" : "Pressione olio motore",
    "brakeFluid" : "Livello fluido freni basso",
    "highVoltage" : "Voltaggio alto, batteria scarica",
};

framework.registerAppDictLoaded("warnguide", "it_IT");