var Localization_warnguideAppDict_lv_LV = {
    //"stringId" : "localString"
    "Warnings" : "Brīdinājumi",
    "NoWarnings" : "Brīdinājumi nav atrasti ",
    "WarningSafetyMessage" : "Drošības nolūkos brīdinājuma norāde netiek rādīta.",
    "WarningGuidance" : "Brīdinājuma norāde",
    "AuxBattLowShrt" : "Zems 12V akumulatora uzl. līm.",
    "DriveBattDropShrt" : "Zems augstspr. akumul. uzl. līm.",
    "ControlSystemErrorShrt" : "Parkošanās sistēmas disfunkcija",
    "EngineOilPressureErrorShrt" : "Zems motoreļļas spiediens",
    "HybridSysErrorShrt" : "Hibrīdsistēmas disfunkcija",
    "HybridSysOverheatShrt" : "Hibrīdsistēma ir pārkarsusi",
    "PpositionRequestShrt" : "Jāaktivizē parkošanās stāvoklis",
    "ChargingSysErrorShrt" : "Uzlādes sistēmas disfunkcija",
    "BrakeSysErrorShrt" : "Bremžu sistēmas disfunkcija",
    "EcbSysErrorShrt" : "Bremžu sistēmas disfunkcija",
    "AbsSysErrorShrt" : "ABS disfunkcija",
    "DscSysErrorShrt" : "DSC disfunkcija",
    "DropKeyBattChrgShrt" : "Zems atslēgas bater. uzlād. līm.",
    "EngOilPressureErrorShrt" : "Zems motoreļļas spiediens",
    "ChrgSysErrorShrt" : "Uzlādes sistēmas disfunkcija",
    "EloopSysErrorShrt" : "i-ELOOP sistēmas disfunkcija",
    "EloopChargingShrt" : "Notiek i-ELOOP uzlāde",
    "LowBrakeFluidShrt" : "Zems bremžu šķidruma līmenis",
    "BrakeSystemErrorShrt" : "Bremžu sistēmas disfunkcija",
    "LowTireAirPressureShrt" : "Zems gaisa spiediens riepās ",
    "EngCoolntTempHighOnShrt" : "Augsta motora dzesētāja temp. ",
    "EngineWaterTempRiseShrt" : "Augsta motora dzesētāja temp. ",
    "SystemInspectionShrt" : "4WD sistēmas pārbaude",
    "AccumulationDpfShrt" : "Cieto daļ. uzkrāš. dīzeļd. cieto daļ. filtrā",
    "RoadSurfaceIcingCautionShrt" : "Brīdin. par ceļa virsm. apled.",
    "LowFuelShrt" : "Zems degvielas līmenis",
    "FuelCapInspectionShrt" : "Degvielas tvertnes vāciņa pārbaude",
    "PowerSteeringSysErrorShrt" : "Stūres pastiprin. sist. disfunkc.",
    "EngSystemErrorShrt" : "Motora sistēmas disfunkcija",
    "AirbagSysPretensionerSysErrorShrt" : "Droš. spilv. sist./spriegotāju sist. disfunkc.",
    "AbsSystemErrorShrt" : "ABS disfunkcija",
    "DscSystemErrorShrt" : "DSC disfunkcija",
    "RvmSysErrorShrt" : "RVM disfunkcija",
    "BsmSystemErrorShrt" : "BSM disfunkcija",
    "AfsSystemErrorShrt" : "AFS disfunkcija",
    "AutoLevelSystemErrorShrt" : "Autom. pārnesumk. disfunkc.",
    "IstopSysErrorShrt" : "i-stop sistēmas disfunkcija",
    "TpmsSysErrorShrt" : "TPMS sistēmas disfunkcija",
    "KeylesSysErrorShrt" : "Bezatslēgas ievades kļūme",
    "FWDSysErrorShrt" : "4WD sistēmas disfunkcija",
    "DPFErrorShrt" : "Dīzeļd. cieto daļ. filtra kļūda",
    "AutoTransSysErrorShrt" : "Autom. transmis. disfunkc.",
    "BattManagSysErrorShrt" : "Akumul. pārvald. sist. disfunkc.",
    "BrakOverrideSysErrorShrt" : "Bremžu ped. priorit. sist. disfunkc.",
    "MRCCSysErrorShrt" : "MRCC disfunkcija",
    "SBSSysErrorShrt" : "SBS disfunkcija",
    "FOWSysError" : "FOW disfunkcija",
    "DRSSSysErrorShrt" : "DRSS disfunkcija",
    "FOWMRCCRadarSoilingShrt" : "FOW/MRCC radara disfunkcija",
    "FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS radara disfunkcija",
    "SBSMRCCRadarSoilingShrt" : "SBS/MRCC radara disfunkcija",
    "SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS radara disfunkcija",
    "MRCCUnavailableShrt" : "MRCC nav pieejams",
    "SBSBrakeUnavailableShrt" : "SBS bremzes nav pieejamas",
    "SBSBrakeMRCCUnavailableShrt" : "SBS bremzes/MRCC nav pieejams",
    "SCBSSysErrorShrt" : "SCBS disfunkcija",
    "SCBSWindshieldSoilingShrt" : "SCBS disfunkcija",
    "SCBSUnavailableShrt" : "SCBS nav pieejama",
    "LDWSSysErrorShrt" : "LDWS disfunkcija",
    "HBCSysErrorShrt" : "HBC disfunkcija",
    "HBCLLDWSCamDisconnectShrt" : "HBC/LDWS kameras disfunkcija",
    "HBCLDWSSysErrorShrt" : "HBC/LDWS sistēmas disfunkcija",
    "HBCLDWSWindshieldFogShrt" : "HBC/LDWS sistēmas disfunkcija",
    "SedimenterWarningShrt" : "Ūdens separatora pārbaude",
    "FuelAirFilterCartReplacePeriodShrt" : "Jānomaina degvielas gaisa filtra elements",
    "VehicleSysErrorShrt" : "Transportl. sist. Disfunkcija",
    "LowWasheFluidShrt" : "Zems logu mazg. šķ. līm.",
    "EngineWaterTempDropShrt" : "Zema motora dzes. šķidr. temp.",
    "PreheatingDispLampShrt" : "Kvēlsveces uzsildītas",
    "AuxBattLowLong" : "Zems 12V akumulatora uzlādes līmenis. \n・Ja signāllampiņa bieži deg braukšanas laikā, iespējams, akumulators ir bojāts. Transportlīdzeklis jāpārbauda pie izplatītāja.\n・Ja šis rādītājs deg pastāvīgi un neizslēdzas, 12V akumulators nedarbojas. Pirms hibrīdsistēmas startēšanas skatiet īpašnieka rokasgrāmatu un pārbaudiet transportlīdzekli pie izplatītāja.",
    "DriveBattDropLong" : "Augstsprieguma akumulatora atlikusī jauda ir zema, jo pārnesums ir bijis neitrālā stāvoklī ilgu laiku. Neitrālā stāvoklī uzlāde nav iespējama. Pārslēdziet stāvēšanas pārnesumā, kad stāvat ilgāku laiku. Ja nepieciešams, restartējiet hibrīdsistēmu, nospiežot barošanas slēdzi.",
    "ControlSystemErrorLong" : "Parkošanās sistēmas disfunkcija. Ja netiek veikta pārbaude, var notikt jebkura no tālāk minētajām situācijām. \n・Pārnesumkārbas bloķēšanas mehānisms var nedarboties. Novietojiet transportlīdzekli uz līdzenas virsmas un drošā veidā aktivizējiet stāvbremzi. \n・Barošanas slēdzis var neizslēgties. Spiediet barošanas slēdzi atkārtoti, lai izslēgtu. \n・Braukšanas un apstāšanās laikā tiks izslēgts displejs “Aktivizējiet stāvbremzi parkošanās laikā”. \nTransportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "EngineOilPressureErrorLong" : "Zems motoreļļas spiediens. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un pārbaudiet motoreļļas līmeni. Ja nepieciešams, pielejiet eļļu. Ja pēc eļļas pieliešanas iedegas šī signāllampiņa vai motoreļļas līmenis ir atbilstošs, nekavējoties nogādājiet automašīnu pie izplatītāja, lai veiktu pārbaudi.",
    "HybridSysErrorLong" : "Hibrīdsistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "HybridSysOverheatLong" : "Hibrīdsistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt. ",
    "PpositionRequestLong" : "Pārslēdziet pārnesumkārbu stāvēšanas pārnesumā. To izraisa kāds no tālāk norādītajiem iemesliem:\n・Akumulatora sistēma tika palaista vai apturēta pārnesumā, kas nav stāvēšanas pārnesums \n・Vadītāja puses durvis tika atvērtas ar pārnesumu stāvoklī N, D vai B \n・Augstsprieguma akumulatora atlikusī jauda ir zema, jo pārnesums ir bijis neitrālā stāvoklī ilgu laiku. \nJa nepieciešams, restartējiet hibrīdsistēmu, nospiežot barošanas slēdzi.\n",
    "ChargingSysErrorLong" : "Uzlādes sistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "BrakeSysErrorLong" : "Zems bremžu šķidruma līmenis vai bremžu sistēmas disfunkcija.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "EcbSysErrorLong" : "Reģeneratīvo bremžu vai elektroniski kontrolēto bremžu sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "AbsSysErrorLong" : "Bremžu pretbloķēšanas sistēmas (ABS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "DscSysErrorLong" : "Dinamiskās stabilitātes kontroles sistēmas (DSC), saķeres kontroles sistēmas (TCS) vai palīgsistēmas braukšanai no kalna (HDC) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "DropKeyBattChrgLong" : "Atslēgas baterijas uzlādes līmenis ir zems. Nekavējoties nomainiet atslēgas bateriju.",
    "EngOilPressureErrorLong" : "Zems motoreļļas spiediens. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un pārbaudiet motoreļļas līmeni. Ja nepieciešams, pielejiet eļļu. Ja pēc eļļas pieliešanas iedegas šī signāllampiņa vai motoreļļas līmenis ir atbilstošs, nekavējoties nogādājiet automašīnu pie izplatītāja, lai veiktu pārbaudi.",
    "ChrgSysErrorLong" : "Uzlādes sistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "EloopSysErrorLong" : "i-ELOOP sistēmas disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "EloopChargingLong" : "Notiek i-ELOOP uzlāde. Motoram darbojoties, pārbaudiet, vai uzlāde ir pabeigta un brīdinājuma signāllampiņa ir nodzisusi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "LowBrakeFluidLong" : "Zems bremžu šķidruma līmenis. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "BrakeSystemErrorLong" : "Elektroniski kontrolētās bremžu sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
    "LowTireAirPressureLong" : "Zems riepu gaisa spiediens vienā vai vairākās riepās. Pārbaudiet riepu gaisa spiedienu un piepūtiet līdz pareizajam gaisa spiedienam. Pēc riepu spiediena noregulēšanas spiediet slēdzi TPMS SET, līdz atskan signāls.",
    "EngCoolntTempHighOnLong" : "Motors ir pārkarsis. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un veiciet atbilstošās darbības.  Skatiet īpašnieka rokasgrāmatu.",
    "EngineWaterTempRiseLong" : "Motors tiek iedarbināts uzsilšanai. Brauciet lēnām vai apstājieties un uzgaidiet, kamēr signāllampiņa pārstāj mirgot. Ja tā turpina mirgot pat pēc apstāšanās, veiciet atbilstošās darbības. Skatiet īpašnieka rokasgrāmatu.",
    "SystemInspectionLong" : "Diferenciāļa eļļas temperatūra ir neadekvāti augsta vai radusies liela griešanās atšķirība starp priekšējām un aizmugurējām riepām (piemēram, kad mēģina tikt ārā no dubļiem). Apturiet transportlīdzekli drošā vietā un turpiniet braukt tikai pēc tam, kad signāllampiņa ir nodzisusi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "AccumulationDpfLong" : "Cietās daļiņas, kas savāktas dīzeļdegvielas cieto daļiņu filtrā, pārsniedz noteikto vērtību. Brauciet aptuveni 10–15 minūtes ar pilnīgi uzsilušu motoru (zilā\n temperatūras lampiņa ir izslēgta) ar ātrumu 15 km/h (10 jūdzes stundā) vai vairāk, lai likvidētu cietās daļiņas\nJa šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "RoadSurfaceIcingCautionLong" : "Āra temperatūra ir līdz 4 °C. Braukšanas laikā uzmanieties no apledojušām ceļa virsmām.",
    "LowFuelLong" : "Degvielas tvertnes līmenis ir zems. Pēc iespējas drīzāk uzpildiet degvielu.",
    "FuelCapInspectionLong" : "Iespējams, degvielas tvertnes vāciņš nav ievietots pareizi. Pārbaudiet, vai degvielas tvertnes vāciņš ir ievietots un pareizi pievilkts. Pēc degvielas tvertnes vāciņa atbilstošas ievietošanas un pievilkšanas signāllampiņa nenodzisīs dažu braukšanas ciklu laikā, kamēr tā nepārliecināsies, ka sistēma darbojas pareizi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "PowerSteeringSysErrorLong" : "Elektriskā stūres pastiprinātāja disfunkcija. Apturiet transportlīdzekli drošā vietā un izslēdziet motoru.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "EngSystemErrorLong" : "Motora sistēmas disfunkcija.  Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "AirbagSysPretensionerSysErrorLong" : "Drošības spilvena/drošības jostas disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "AbsSystemErrorLong" : "Bremžu pretbloķēšanas sistēmas (ABS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "DscSystemErrorLong" : "Dinamiskas stabilitātes kontroles sistēmas (DSC) vai saķeres kontroles sistēmas (TCS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "RvmSysErrorLong" : "RVM sistēmā ir kļūda. Pārbaudiet, vai uz aizmugurējā bufera virsmas nav defektu, un, ja tas ir netīrs vai pārklāts ar sniegu, notīriet to. Ja šī brīdinājuma lampiņa joprojām deg, pārbaudiet transportlīdzekli pie Mazda izplatītāja.",
    "BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA) disfunkcija. Pārbaudiet, vai uz aizmugurējā bufera virsmas nav defektu, un, ja tas ir netīrs vai pārklāts ar sniegu, notīriet to.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "AfsSystemErrorLong" : "Adaptīvās priekšējo lukturu sistēmas (AFS) disfunkcija.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "AutoLevelSystemErrorLong" : "Priekšējo lukturu automātiskās līmeņošanas sistēmas disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "IstopSysErrorLong" : "i-stop darbība nav iespējama. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
    "TpmsSysErrorLong" : "Riepu gaisa spiediena uzraudzības sistēmas (TPMS) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "KeylesSysErrorLong" : "Bezatslēgas ievades sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "FWDSysErrorLong" : "4WD sistēmas disfunkcija vai atšķiras priekšējo un aizmugurējo riepu izmēri. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "DPFErrorLong" : "Dīzeļdegvielas cieto daļiņu filtra (DPF) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "AutoTransSysErrorLong" : "Autom. transmis. disf. Ja turpināsiet braukt, var rasties transportl. bojājumi.  Transportl. nekav. jāpārbauda pie izplatītāja.  ",
    "BattManagSysErrorLong" : "Akumul. pārvald. sist. disfunkc. Transportl. jāpārbauda pie izplatītāja.",
    "BrakOverrideSysErrorLong" : "Bremžu slēdža disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "SBSSysErrorLong" : "SBS sistēmā ir kļūda. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
    "FOWSysErrorLong" : "Forward Obstruction Warning (FOW) sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "DRSSSysErrorLong" : "DRSS sistēmā ir kļūda. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
    "FOWMRCCRadarSoilingLong" : "FOW/MRCC radara (sensora) disfunkcija.  Ja priekšējā režģa emblēma ir netīra vai klāta ar sniegu, notīriet visu virsmu.  \nJa šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.\n",
    "FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
    "SBSMRCCRadarSoilingLong" : "SBS/MRCC radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
    "SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
    "MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) šobrīd nav pieejams.",
    "SBSBrakeUnavailableLong" : "SBS bremzes šobrīd nav pieejamas.",
    "SBSBrakeMRCCUnavailableLong" : "SBS bremzes/MRCC šobrīd nav pieejams.",
    "SCBSSysErrorLong" : "Smart City Brake Support (SCBS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
    "SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) disfunkcija. Notīriet priekšējo vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "SCBSUnavailableLong" : "Smart City Brake Support (SCBS) šobrīd nav pieejama.",
    "LDWSSysErrorLong" : "Lane Departure Warning System (LDWS)  disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "HBCSysErrorLong" : "High Beam Control (HBC)  disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) disfunkcija. Notīriet vējstiklu.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "HBCLDWSSysErrorLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)/Lane Departure Warning System (LDWS) disfunkcija. Atkausējiet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "SedimenterWarningLong" : "Ūdens separatorā uzkrātais daudzums pārsniedz nominālo daudzumu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "FuelAirFilterCartReplacePeriodLong" : "Jānomaina degvielas gaisa filtra elements.",
    "VehicleSysErrorLong" : "Transportlīdzekļa sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
    "LowWasheFluidLong" : "Zems logu mazgāšanas sistēmas šķidruma līmenis. Uzpildiet logu mazgāšanas šķidrumu.",
    "EngineWaterTempDropLong" : "Motora dzesēšanas šķidrums ir auksts, un sildīšanas sistēmai/atkausētājam nav pieejams silts gaiss. Transportlīdzekli drīkst vadīt ar iedegtu vai neiedegtu signāllampiņu.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "PreheatingDispLampLong" : "Kvēlsveces ir uzsildītas. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
    "HybrdSysMalHighPrt" : "Hibrīdsistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā.",
    "ChargSysMalHighPrt" : "Uzlādes sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā.",
    "IeloopChrgHighPrt" : "Uzlādē i-ELOOP. Dzinēj. darbojoties, pārb., vai uzlāde ir pabeigta un brīdin. lamp. ir nodzisusi. ",
    "EngnCoolTempHighHighPrt" : "Motora dzesēšanas šķidruma temperatūra ir augsta. Nekavējoties apturiet transportlīdzekli drošā vietā.",
    "lowBattStartEngine" : "Tukša baterija! Iedarbiniet dzinēju!",
    "engineOilPressure" : "Motoreļļas spiediens",
    "brakeFluid" : "Zems bremžu šķidruma līmenis",
    "highVoltage" : "Zems augstsprieguma akumulatora uzlādes līmenis",
};

framework.registerAppDictLoaded("warnguide", "lv_LV");