var Localization_warnguideAppDict_fr_CN = {
    //"stringId" : "localString"
    "Warnings" : "Mises en garde",
    "NoWarnings" : "Aucun avertissement trouvé",
    "WarningSafetyMessage" : "Pour des raisons de sécurité, les conseils de mise en garde ne sont pas affichés.",
    "WarningGuidance" : "Liste des alertes",
    "AuxBattLowShrt" : "Batterie 12V faible",
    "DriveBattDropShrt" : "Batterie haute tension faible",
    "ControlSystemErrorShrt" : "Défaillance syst controle de Park",
    "EngineOilPressureErrorShrt" : "Faible pression huile moteur",
    "HybridSysErrorShrt" : "Défaillance du système hybride",
    "HybridSysOverheatShrt" : "Surchauffe du système hybride",
    "PpositionRequestShrt" : "Demande de la position Park",
    "ChargingSysErrorShrt" : "Défaillance du système de charge",
    "BrakeSysErrorShrt" : "Défaillance syst de freinage",
    "EcbSysErrorShrt" : "Défaillance syst de freinage",
    "AbsSysErrorShrt" : "Défaillance du système ABS",
    "DscSysErrorShrt" : "Défaillance du système DSC",
    "DropKeyBattChrgShrt" : "Batterie principale faible",
    "EngOilPressureErrorShrt" : "Faible pression huile moteur",
    "ChrgSysErrorShrt" : "Défaillance du système de charge",
    "EloopSysErrorShrt" : "Défaillance du système i-ELOOP",
    "EloopChargingShrt" : "Chargement d’i-ELOOP",
    "LowBrakeFluidShrt" : "Niveau du liquide des freins bas",
    "BrakeSystemErrorShrt" : "Défaillance syst de freinage",
    "LowTireAirPressureShrt" : "Faible pression des pneus",
    "EngCoolntTempHighOnShrt" : "Temp élevée du liq refroidissemt",
    "EngineWaterTempRiseShrt" : "Temp élevée du liq refroidissemt",
    "SystemInspectionShrt" : "Inspection syst 4 roues motrices",
    "AccumulationDpfShrt" : "Accumulation particules ds FAP",
    "RoadSurfaceIcingCautionShrt" : "Avertissement glace sur route",
    "LowFuelShrt" : "Niveau du carburant bas",
    "FuelCapInspectionShrt" : "Inspection du bouchon carburant",
    "PowerSteeringSysErrorShrt" : "Défaillance de direction assistée",
    "EngSystemErrorShrt" : "Défaillance du système moteur",
    "AirbagSysPretensionerSysErrorShrt" : "Déf coussin gonfl/syst prétension",
    "AbsSystemErrorShrt" : "Défaillance du système ABS",
    "DscSystemErrorShrt" : "Défaillance du système DSC",
    "RvmSysErrorShrt" : "Défaillance du RVM",
    "BsmSystemErrorShrt" : "Défaillance du BSM",
    "AfsSystemErrorShrt" : "Défaillance du AFS",
    "AutoLevelSystemErrorShrt" : "Défaillance syst nivellement auto",
    "IstopSysErrorShrt" : "Défaillance du systmème i-stop",
    "TpmsSysErrorShrt" : "Défaillance du système TPMS",
    "KeylesSysErrorShrt" : "Défaillance entrée sans clé",
    "FWDSysErrorShrt" : "Défaillance syst 4 roues motrices",
    "DPFErrorShrt" : "Erreur du DPF",
    "AutoTransSysErrorShrt" : "Défaillance transmission auto",
    "BattManagSysErrorShrt" : "Défaillance de gestion batterie",
    "BrakOverrideSysErrorShrt" : "Défaillance syst priorité freins",
    "MRCCSysErrorShrt" : "Défaillance  du MRCC",
    "SBSSysErrorShrt" : "Défaillancen du SBS",
    "FOWSysError" : "Défaillance du FOW",
    "DRSSSysErrorShrt" : "Défaillance du DRSS",
    "FOWMRCCRadarSoilingShrt" : "Défaillance du radar FOW/MRCC",
    "FOWMRCCDRSSRadarSoilingShrt" : "Défaillance  FOW/MRCC/DRSS",
    "SBSMRCCRadarSoilingShrt" : "Défaillance du radar SBS/MRCC",
    "SBSMRCCDRSSRadarSoilingShrt" : "Défaill radar SBS/MRCC/DRSS",
    "MRCCUnavailableShrt" : "MRCC non disponible",
    "SBSBrakeUnavailableShrt" : "Freins SBS non disponibles",
    "SBSBrakeMRCCUnavailableShrt" : "Freins SBS/MRCC non disponibles",
    "SCBSSysErrorShrt" : "Défaillance du SCBS",
    "SCBSWindshieldSoilingShrt" : "Défaillance du SCBS",
    "SCBSUnavailableShrt" : "SCBS non disponible",
    "LDWSSysErrorShrt" : "Défaillance du LDWS",
    "HBCSysErrorShrt" : "Défaillance du HBC",
    "HBCLLDWSCamDisconnectShrt" : "Défaillance caméra HBC/AFIL",
    "HBCLDWSSysErrorShrt" : "Défaillance système HBC/LDWS",
    "HBCLDWSWindshieldFogShrt" : "Défaillance système HBC/LDWS",
    "SedimenterWarningShrt" : "Inspection du sédimenteur",
    "FuelAirFilterCartReplacePeriodShrt" : "Rempl cartouch filtr air-carburant",
    "VehicleSysErrorShrt" : "Défailllance système du véhicule",
    "LowWasheFluidShrt" : "Niveau du liquide lave-glace bas",
    "EngineWaterTempDropShrt" : "Temp basse liq refroid moteur",
    "PreheatingDispLampShrt" : "Bougies en préchauffage",
    "AuxBattLowLong" : "La batterie de 12V est presque déchargée. Si ce témoin est fréquemment allumé pendant la conduite, la batterie est peut être abîmée. Faites vérifier le véhicule par un concessionnaire. Si ce témoin est allumé en permanence et ne s'éteint pas, la batterie de 12V doit être remplacée. Reportez-vous au manuel d’utilisation avant de démarrer le système hybride et faites vérifier le véhicule par un concessionnaire.",
    "DriveBattDropLong" : "La charge résiduelle de la batterie haute tension est faible parce que le véhicule a été en position neutre pendant longtemps. La recharge ne fonctionne pas en position neutre. Passez à la position Staionnement si le véhicule est arrêté sur une longue durée. Redémarrez le système hybride en appuyant sur le commutateur d'alimentation si nécessaire.",
    "ControlSystemErrorLong" : "Défaillance du système de contrôle de la position de stationnement. Si rien n'est fait, l'une des situations suivantes peut survenir : Le mécanisme de verrouillage en stationnement peut ne pas fonctionner. Stationnez sur une surface plane et enclenchez le frein de stationnement. Le commutateur d'alimentation peut ne pas s'éteindre. Appuyez plusieurs fois sur le commutateur d'alimentation pour l'éteindre. Le message « Enclencher le frein de stationnement » disparait lorsque vous conduisez et s’affiche à l'arrêt. Faites immédiatement vérifier le véhicule par un concessionnaire.",
    "EngineOilPressureErrorLong" : "Pression d'huile du moteur faible. \nArrêter le véhicule immédiatement dans un endroit sûr, couper le moteur et vérifier le niveau d'huile moteur. Ajouter de l'huile si nécessaire. \nFaites vérifier le véhicule par un concessionnaire immédiatement si ce voyant s'allume après avoir ajouté de l'huile ou si le niveau d'huile est OK.\n",
    "HybridSysErrorLong" : "Défaillance du système hybride. \nDes dommages au véhicule peuvent se produire si vous continuez à conduire. Arrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "HybridSysOverheatLong" : "Défaillance du système hybride. \nDes dommages au véhicule peuvent se produire si vous continuez à conduire. Arrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "PpositionRequestLong" : "Mettre la transmission en position Stationnement.  Cela est dû à une des causes suivantes:  Le système de batterie a démarré ou s'est arrêté avec la transmission dans une position autre que celle de Stationnement;  La porte côté conducteur a été ouverte avec la transmission en position N, D ou B;  La charge de la batterie haute tension résiduelle est faible car la transmission est au point mort depuis longtemps.  Redémarrez le système hybride en pressant sur le commutateur d'alimentation si nécessaire.",
    "ChargingSysErrorLong" : "Défaillance du système de charge. \nDes dommages au véhicule peuvent se produire si vous continuez à conduire. Arrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "BrakeSysErrorLong" : "Niveau de liquide des freins est faible ou mauvais fonctionnement du système des freins. Arrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.",
    "EcbSysErrorLong" : "Défaillance du système de freinage par récupération ou du système des freins à commande électronique. \nArrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "AbsSysErrorLong" : "Mauvais fonctionnement du système des freins antiblocage (ABS). \nFaire vérifier le véhicule immédiatement chez un concessionnaire.",
    "DscSysErrorLong" : "Défaillance du contrôle dynamique de stabilité (DSC), système antipatinage (TCS) ou assistance au lancement en pente(HLA). \nFaire vérifier le véhicule immédiatement chez un concessionnaire.\n",
    "DropKeyBattChrgLong" : "Batterie principale faible \nRemplacer la batterie principale immédiatement.\n",
    "EngOilPressureErrorLong" : "Pression d'huile du moteur faible. \nArrêter le véhicule immédiatement dans un endroit sûr, couper le moteur et vérifier le niveau d'huile moteur. Ajouter de l'huile si nécessaire. \nFaites vérifier le véhicule par un concessionnaire immédiatement si ce voyant s'allume après avoir ajouté de l'huile ou si le niveau d'huile est OK.\n",
    "ChrgSysErrorLong" : "Défaillance du système de charge. \nArrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "EloopSysErrorLong" : "Défaillance du système i-ELOOP. \nFaire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "EloopChargingLong" : "i-ELOOP est en charge. \nPendant que le moteur est en marche, vérifier que la charge est terminée et que la lampe témoin est éteinte. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "LowBrakeFluidLong" : "Niveau du liquide des freins est bas. \nArrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "BrakeSystemErrorLong" : "Défaillance du système de freinage à commande électronique \nArrêter le véhicule immédiatement dans un endroit sûr et faites vérifier le véhicule par un concessionnaire.\n",
    "LowTireAirPressureLong" : "Pression d'air dans un ou plusieurs pneus basse. \nVérifiez et au besoin ajuster la pression d'air des pneus. Après avoir ajusté la pression des pneus appuyez sur l'interrupteur de TMPS SET jusqu'à ce que vous entendiez un bip.\n",
    "EngCoolntTempHighOnLong" : "Moteur est en surchauffe. \nArrêter le véhicule immédiatement dans un endroit sûr, couper le moteur et prendre les actions appropriées. Consulter votre manuel d'utilisation.\n",
    "EngineWaterTempRiseLong" : "Moteur commence à surchauffer. \nConduisez lentement ou arrêter le véhicule jusqu'à ce que le voyant cesse de clignoter. Si elle clignote toujours, même après l'arrêt du véhicule, prendre des mesures appropriées. Consulter votre manuel d'utilisation.\n",
    "SystemInspectionLong" : "La température de l'huile du différentiel est anormalement élevée ou une grande différence de rotation s'est produite dans les pneus avant et arrière (par exemple, en tentant de se sortir de la boue). \nArrêter le véhicule dans un endroit sûr et reprendre la conduite après que l'avertisseur soit éteint. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "AccumulationDpfLong" : "Les matières particulaires (PM) collectées dans le filtre à particules diesel (DPF) a dépassé la valeur réglementaire. \nConduire pendant environ 10 à 15 minutes avec la moteur réchauffé (lumière température bleue éteinte) à une vitesse de 10 mi/h (15km/h) ou plus pour éliminer le PM. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "RoadSurfaceIcingCautionLong" : "Température extérieure est de 4° C ou moins. \nFaites attention aux chaussées glacées.\n",
    "LowFuelLong" : "Niveau de carburant est bas. \nFaire le plein du véhicule bientôt.\n",
    "FuelCapInspectionLong" : "Le bouchon du réservoir  peut ne pas être installé correctement. \nVérifier que le bouchon du réservoir soit  installé et bien serré. \nAprès avoir installé et serrer le bouchon correctement, cet indicateur ne s'éteint pas pendant quelques cycles jusqu'à ce qu'il est confirmé que le système est OK. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "PowerSteeringSysErrorLong" : "Défaillance du système de direction assistée électrique. \nArrêter le véhicule dans un endroit sûr et couper le moteur. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "EngSystemErrorLong" : "Défaillance du système moteur. Faire vérifier le véhicule immédiatement chez un concessionnaire.",
    "AirbagSysPretensionerSysErrorLong" : "Défiance du sac gonflable/ceinture de sécurité. \nFaire vérifier le véhicule immédiatement chez un concessionnaire\n",
    "AbsSystemErrorLong" : "Mauvais fonctionnement du système des freins antiblocage (ABS). \nFaire vérifier le véhicule immédiatement chez un concessionnaire.\n",
    "DscSystemErrorLong" : "Défaillance du contrôle dynamique de stabilité (DSC) ou système antipatinage (TCS). \nFaire vérifier le véhicule immédiatement chez un concessionnaire.\n",
    "RvmSysErrorLong" : "Une erreur du système RVM est survenue.\nRechercher les anomalies dans la surface du pare-chocs arrière et nettoyer cette surface si elle est souillée ou recouverte de neige.\nFaire vérifier le véhicule par un concessionnaire Mazda si la lampe témoin reste allumée.\n",
    "BsmSystemErrorLong" : " Défaillance du Système de Surveillance d'angle mort (BSM) / Alerte de trafic transversal arrière(RCTA). \nRechercher les anomalies dans la surface du pare-chocs arrière et nettoyer cette surface si elle est souillée ou recouverte de neige. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "AfsSystemErrorLong" : "Défiance du Système d'éclairage avant adaptatif (AFS). Faire vérifier le véhicule par un concessionnaire Mazda si la lampe témoin clignote toujours.",
    "AutoLevelSystemErrorLong" : "Défaillance du système de nivellement automatique des phares. \nFaire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "IstopSysErrorLong" : "L’opération i-stop n'est pas possible.\nFaire vérifier le véhicule par un concessionnaire Mazda.\n",
    "TpmsSysErrorLong" : "Défllance du système de surveillance de la pression des pneus (TPMS). \nFaire vérifier votre véhicule chez un concessionnaire.\n",
    "KeylesSysErrorLong" : "Défaillance du système d’entrée sans clé. \nFaire vérifier votre véhicule chez un concessionnaire.\n",
    "FWDSysErrorLong" : "Défaillance du système 4 roues motrices ou la taille des pneus est différente entre pneus avant et arrière. \nFaire vérifier votre véhicule chez un concessionnaire.",
    "DPFErrorLong" : "Défaillance du filtre à particules diesel (DPF). \nFaire vérifier votre véhicule chez un concessionnaire.",
    "AutoTransSysErrorLong" : "Défaillance de la transmission automatique. \nDes dommages au véhicule peuvent se produire si vous continuez à conduire. Faire vérifier le véhicule immédiatement chez un concessionnaire.  ",
    "BattManagSysErrorLong" : "Défaillance  du système de gestion de la batterie. \nFaire vérifier votre véhicule chez un concessionnaire.",
    "BrakOverrideSysErrorLong" : "Défaillance du commutateur de freinage \nFaire vérifier le véhicule immédiatement chez un concessionnaire.",
    "MRCCSysErrorLong" : "Défaillance du régulateur de vitesse radar Mazda (MRCC). \nFaire vérifier votre véhicule chez un concessionnaire.",
    "SBSSysErrorLong" : "Une erreur du système SBS est survenue.\nFaire vérifier le véhicule par un concessionnaire Mazda.",
    "FOWSysErrorLong" : "Défaillance du système d'avertissement d’obstacle avant (FOW). \nFaire vérifier votre véhicule chez un concessionnaire.",
    "DRSSSysErrorLong" : "Une erreur du système DRSS est survenue.\nFaire vérifier le véhicule par un concessionnaire Mazda.",
    "FOWMRCCRadarSoilingLong" : "Défaillance du radar FOW/MRCC \nNettoyer toute la surface de l'emblème de calandre si sale ou recouverte de neige. \nFaire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "FOWMRCCDRSSRadarSoilingLong" : "Le radar FOW/CRCR/DRSS (capteur) est souillé.\nNettoyer toute la surface du radar (capteur).\n",
    "SBSMRCCRadarSoilingLong" : "Le radar SBS/MRCC (capteur) est souillé.\nNettoyer toute la surface du radar (capteur).\n",
    "SBSMRCCDRSSRadarSoilingLong" : "Le radar SBS/CRCR/DRSS (capteur) est souillé.\nNettoyer toute la surface du radar (capteur).\n",
    "MRCCUnavailableLong" : "Régulateur de vitesse radar Mazda (MRCC) actuellement indisponible.",
    "SBSBrakeUnavailableLong" : "Frein SBS est présentement indisponible.",
    "SBSBrakeMRCCUnavailableLong" : "Frein SBS / MRCC est présentement indisponible.",
    "SCBSSysErrorLong" : "Défaillance du freinage ville intelligent (SCBS). \nFaire vérifier le véhicule immédiatement chez un concessionnaire.\n",
    "SCBSWindshieldSoilingLong" : "Défaillance du freinage ville intelligent (SCBS). \nNettoyer le pare-brise. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "SCBSUnavailableLong" : "Support du freinage ville intelligent (SCBS) actuellement indisponible.",
    "LDWSSysErrorLong" : "Défaillance du système de détection de déviation de trajectoire(LDWS). \nFaire vérifier votre véhicule chez un concessionnaire.\n",
    "HBCSysErrorLong" : "Défaillance du contrôleur des feux de route (HBC). \nFaire vérifier votre véhicule chez un concessionnaire.\n",
    "HBCLLDWSCamDisconnectLong" : "Défaillance du système de contrôleur des feux de route  (HBC) / détection de déviation de trajectoire(LDWS). \nNettoyer le pare-brise. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "HBCLDWSSysErrorLong" : "Défaillance du système de contrôleur des feux de route  (HBC) / détection de déviation de trajectoire(LDWS). Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "HBCLDWSWindshieldFogLong" : "Défaillance du système de contrôleur des feux de route  (HBC) / détection de déviation de trajectoire(LDWS). \nDégivrer le pare-brise. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "SedimenterWarningLong" : "La quantité d'eau accumulée dans le sédimenteur dépasse le montant permis. \nFaire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.\n",
    "FuelAirFilterCartReplacePeriodLong" : "Le filtre à air-combustible doit être remplacé.",
    "VehicleSysErrorLong" : "Défaillance du système de véhicule. \nFaire vérifier votre véhicule chez un concessionnaire.",
    "LowWasheFluidLong" : "Le niveau du liquide de lave-glace est bas. \nRemplir le liquide de lave-glace.\n",
    "EngineWaterTempDropLong" : "Liquide de refroidissement du moteur est froid et aucun air chaud n'est disponible pour le chauffage/dégivrage. Véhicule peut être conduit avec le voyant allumé ou éteint. Faire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "PreheatingDispLampLong" : "Bougies de préchauffage en opération \nFaire vérifier le véhicule par un concessionnaire si la lampe témoin reste allumée.",
    "HybrdSysMalHighPrt" : "Défaillance du système hybride. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "ChargSysMalHighPrt" : "Défaillance du système de charge. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "IeloopChrgHighPrt" : "i-ELOOP en charge. Avec moteur en marche, vérifier fin de charge et voyant d'avertissement éteint",
    "EngnCoolTempHighHighPrt" : "Température élevée du liquide de refroidissement. Arrêter le véhicule immédiatement dans un endroit sûr.",
    "lowBattStartEngine" : "Batterie faible! Démarrez moteur!",
    "engineOilPressure" : "Pression d’huile de moteur",
    "brakeFluid" : "Niveau bas de liquide de frein",
    "highVoltage" : "Batterie haute tension faible",
};

framework.registerAppDictLoaded("warnguide", "fr_CN");