var Localization_netmgmtAppDict_th_TH = {
	//"stringId" : "localString"
	"Connect": "เชื่อมต่อ",
	"ConnectTo": "เชื่อมต่อไปยัง {networkName}",
	"Connecting": "กำลังเชื่อมต่อ",
	"ConnectionError": "การเชื่อมต่อขัดข้อง",
	"ConnectionSetup": "การตั้งค่า",
	"Delete": "ลบ",
	"DeleteANetwork": "ลบเครือข่ายเพื่อดำเนินการต่อ",
	"DeleteConfirmation": "คุณแน่ใจหรือไม่ว่าต้องการลบ {networkName}",
	"DeleteNetwork": "ลบเครือข่าย Wi-Fi",
	"Disconnect": "ยกเลิกการเชื่อมต่อ",
	"Disconnecting": "กำลังยกเลิกการเชื่อมต่อ",
	"DoYouWantToConnect": "คุณต้องการเชื่อมต่อหรือไม่",
	"EnterPassword": "ป้อนรหัสผ่าน",
	"ErrorDHCP": "DHCP ขัดข้อง ไม่สามารถทำการตั้งค่าได้",
	"ErrorInternal": "ข้อผิดพลาดภายใน",
	"ErrorNetwork": "เครือข่ายขัดข้อง",
	"GUI_WifiNetworkLost_Alert": "เครือข่าย Wi-Fi หายไป",
	"GUI_WrongPassword_Alert": "รหัสผ่านไม่ถูกต้อง",
	"InvalidPassword": "รหัสผ่านไม่ถูกต้อง",
	"MaxNetworksReached": "เครือข่ายถูกเพิ่มในรายการเครือข่ายถึงจำนวนสูงสุดแล้ว",
	"NameSSID": "ชื่อ (SSID)",
	"NetworkConnection": "การเชื่อมต่อเครือข่าย",
	"NetworkDisconnected": "ยกเลิกการเชื่อมต่อ {networkName} แล้ว",
	"NoNetworkConnectivity": "ไม่มีภาวะเชื่อมต่อเครือข่าย",
	"None": "ไม่มี",
	"OtherNetwork": "เครือข่ายอื่น",
	"Password": "รหัสผ่าน",
	"Retry": "ลองใหม่",
	"SavedNetworks": "เครือข่ายที่บันทึกไว้",
	"SecurityOptions": "ความปลอดภัยตัวเลือก",
	"SecurityType": "ชนิดของการรักษาความปลอดภัย",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "th_TH");