var Localization_netmgmtAppDict_ms_MY = {
	//"stringId" : "localString"
	"Connect": "Sambung",
	"ConnectTo": "Sambung ke {networkName}",
	"Connecting": "Menyambung",
	"ConnectionError": "Ralat Sambungan",
	"ConnectionSetup": "Persediaan Smbngan",
	"Delete": "Padam",
	"DeleteANetwork": "Padamkan Rangkaian untuk meneruskan",
	"DeleteConfirmation": "Adakah anda pasti mahu memadamkan {networkName}?",
	"DeleteNetwork": "Padamkan Rangkaian Wi-Fi",
	"Disconnect": "Putuskan Sambungan",
	"Disconnecting": "Memutuskan sambungan",
	"DoYouWantToConnect": "Adakah anda mahu menyambung?",
	"EnterPassword": "Msk Kata Laluan",
	"ErrorDHCP": "Ralat DHCP. Gagal memperoleh tetapan.",
	"ErrorInternal": "Ralat Dalaman",
	"ErrorNetwork": "Ralat Rangkaian",
	"GUI_WifiNetworkLost_Alert": "Rangkaian Wi-Fi Terputus",
	"GUI_WrongPassword_Alert": "Kata Laluan Salah",
	"InvalidPassword": "Kata Laluan Tidak Sah",
	"MaxNetworksReached": "Rangkaian maksimun telah ditambahkan pada Senarai Rangkaian.",
	"NameSSID": "Nama (SSID)",
	"NetworkConnection": "Smbngn Rngkaian",
	"NetworkDisconnected": "Sambungan {networkName} telah Diputuskan",
	"NoNetworkConnectivity": "Tiada Sambungan Rangkaian",
	"None": "Tiada",
	"OtherNetwork": "Rangkaian Lain",
	"Password": "Kata Laluan",
	"Retry": "Cuba semula",
	"SavedNetworks": "Rangkaian Disimpan",
	"SecurityOptions": "Pilihan Keselamatan",
	"SecurityType": "Jenis Keselamatan",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "ms_MY");