var Localization_netmgmtAppDict_en_US = {
	//"stringId" : "localString"
	"Connect": "Connect",
	"ConnectTo": "Connect to {networkName}",
	"Connecting": "Connecting",
	"ConnectionError": "Connection Error",
	"ConnectionSetup": "Setup",
	"Delete": "Delete",
	"DeleteANetwork": "Delete a Network to continue",
	"DeleteConfirmation": "Are you sure you want to delete {networkName}?",
	"DeleteNetwork": "Delete Wi-Fi Network",
	"Disconnect": "Disconnect",
	"Disconnecting": "Disconnecting",
	"DoYouWantToConnect": "Do you want to setup?",
	"EnterPassword": "Enter Password",
	"ErrorDHCP": "DHCP Error. Failed to acquire Settings.",
	"ErrorInternal": "Internal Error",
	"ErrorNetwork": "Network Error",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi Network Lost",
	"GUI_WrongPassword_Alert": "Wrong Password",
	"InvalidPassword": "Invalid Password",
	"MaxNetworksReached": "Maximum Networks have been added to the Network List.",
	"NameSSID": "Name (SSID)",
	"NetworkConnection": "Wi-Fi",
	"NetworkDisconnected": "{networkName} has been disconnected.",
	"NoNetworkConnectivity": "Network Connection Needed",
	"None": "None",
	"OtherNetwork": "Other Network",
	"Password": "Password",
	"Retry": "Retry",
	"SavedNetworks": "Saved Networks",
	"SecurityOptions": "Security Options",
	"SecurityType": "Security Type",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "en_US");