var Localization_netmgmtAppDict_pt_BR = {
	//"stringId" : "localString"
	"Connect": "Conectar",
	"ConnectTo": "Conectar a {networkName}",
	"Connecting": "Conectando",
	"ConnectionError": "Erro de conexão",
	"ConnectionSetup": "Configuração",
	"Delete": "Excluir",
	"DeleteANetwork": "Exclua uma rede para continuar",
	"DeleteConfirmation": "Tem certeza de que deseja excluir {networkName}?",
	"DeleteNetwork": "Excluir Rede Wi-Fi",
	"Disconnect": "Desconectar",
	"Disconnecting": "Desconectando",
	"DoYouWantToConnect": "Você deseja configurar",
	"EnterPassword": "Inserir senha",
	"ErrorDHCP": "Erro de DHCP. Falha ao adquirir configurações.",
	"ErrorInternal": "Erro interno",
	"ErrorNetwork": "Erro de rede",
	"GUI_WifiNetworkLost_Alert": "Rede Wi-Fi perdida",
	"GUI_WrongPassword_Alert": "Senha incorreta",
	"InvalidPassword": "Senha incorreta",
	"MaxNetworksReached": "O número máximo de redes foi adicionado à lista de redes.",
	"NameSSID": "Nome (SSID)",
	"NetworkConnection": "Wi-Fi",
	"NetworkDisconnected": "A rede {networkName} foi desconectada.",
	"NoNetworkConnectivity": "Conexão de rede obrigatória",
	"None": "Nenhum",
	"OtherNetwork": "Outra rede",
	"Password": "Senha",
	"Retry": "Repetir",
	"SavedNetworks": "Redes salvas",
	"SecurityOptions": "Opções de segurança",
	"SecurityType": "Tipo de segurança",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "pt_BR");