var Localization_netmgmtAppDict_nl_NL = {
	//"stringId" : "localString"
	"Connect": "Verbinden",
	"ConnectTo": "Verbinden met {networkName}",
	"Connecting": "Verbinden",
	"ConnectionError": "Verbindingsfout",
	"ConnectionSetup": "Set-up verbinding",
	"Delete": "Verwijderen",
	"DeleteANetwork": "Verwijder een netwerk om verder te gaan",
	"DeleteConfirmation": "Weet u zeker dat u {networkName} wilt verwijderen?",
	"DeleteNetwork": "Wi-Fi-netwerk verwijderen",
	"Disconnect": "Verbinding verbreken",
	"Disconnecting": "Verbreken",
	"DoYouWantToConnect": "Wilt u verbinding maken?",
	"EnterPassword": "Voer wachtwoord in",
	"ErrorDHCP": "DHCP Fout. Het verwerven van instellingen mislukt.",
	"ErrorInternal": "Interne fout",
	"ErrorNetwork": "Netwerkfout",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi Netwerk Verloren",
	"GUI_WrongPassword_Alert": "Onjuist wachtwoord",
	"InvalidPassword": "Ongeldig wachtwoord",
	"MaxNetworksReached": "Maximum Networks is aan de netwerklijst toegevoegd.",
	"NameSSID": "Naam (SSID)",
	"NetworkConnection": "Netwerkverbinding",
	"NetworkDisconnected": "{networkName} is losgekoppeld",
	"NoNetworkConnectivity": "Geen netwerkverbinding",
	"None": "--",
	"OtherNetwork": "Ander Netwerk",
	"Password": "Wachtwoord",
	"Retry": "Opnieuw proberen",
	"SavedNetworks": "Opgeslagen netwerken",
	"SecurityOptions": "Beveiligingsopties",
	"SecurityType": "Beveiligingstype",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "nl_NL");