var Localization_netmgmtAppDict_it_IT = {
	//"stringId" : "localString"
	"Connect": "Connetti",
	"ConnectTo": "Connetti a {networkName}",
	"Connecting": "Connessione in corso",
	"ConnectionError": "Errore connessione",
	"ConnectionSetup": "Impostaz connessio",
	"Delete": "Elimina",
	"DeleteANetwork": "Elimina una rete per continuare",
	"DeleteConfirmation": "Eliminare {networkName}?",
	"DeleteNetwork": "Elimina rete Wi-Fi",
	"Disconnect": "Disconnetti",
	"Disconnecting": "Disconnessione in corso",
	"DoYouWantToConnect": "Connettersi?",
	"EnterPassword": "Inserisci password",
	"ErrorDHCP": "Errore DHCP. Acquisizione impostazioni impossibile.",
	"ErrorInternal": "Errore interno",
	"ErrorNetwork": "Errore rete",
	"GUI_WifiNetworkLost_Alert": "Rete Wi-Fi persa.",
	"GUI_WrongPassword_Alert": "Password errata",
	"InvalidPassword": "Password non valida",
	"MaxNetworksReached": "È stato aggiunto il numero massimo di reti all'elenco reti.",
	"NameSSID": "Nome (SSID)",
	"NetworkConnection": "Connessione rete",
	"NetworkDisconnected": "{networkName} è stato disconnesso.",
	"NoNetworkConnectivity": "Connettività di rete assente.",
	"None": "--",
	"OtherNetwork": "Altra rete",
	"Password": "Password",
	"Retry": "Riprova",
	"SavedNetworks": "Reti salvate",
	"SecurityOptions": "Opzioni sicurezza",
	"SecurityType": "Tipo sicurezza",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "it_IT");