var Localization_netmgmtAppDict_hu_HU = {
	//"stringId" : "localString"
	"Connect": "Csatlakozás",
	"ConnectTo": "{networkName} hálózathoz csatl.",
	"Connecting": "Kapcsolódás",
	"ConnectionError": "Csatlakozási hiba",
	"ConnectionSetup": "Kapcsolatbeállítás",
	"Delete": "Törlés",
	"DeleteANetwork": "A folytatáshoz törölni kell egy hálózatot",
	"DeleteConfirmation": "Biztos törölni kívánja ezt: {networkName}?",
	"DeleteNetwork": "Wi-Fi hálózat törlése",
	"Disconnect": "Húzza ki",
	"Disconnecting": "Kapcsolat bontása",
	"DoYouWantToConnect": "Kíván csatlakozni?",
	"EnterPassword": "Jelszó megadása",
	"ErrorDHCP": "DHCP-hiba. Beállítások lekérése sikertelen.",
	"ErrorInternal": "Belső hiba",
	"ErrorNetwork": "Hálózati hiba",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi hálózat megszakadt",
	"GUI_WrongPassword_Alert": "Helytelen jelszó",
	"InvalidPassword": "Érvénytelen jelszó",
	"MaxNetworksReached": "Maximális számú hálózatot adtak a hálózati listához.",
	"NameSSID": "Név (SSID)",
	"NetworkConnection": "Hálózati csatlakozás",
	"NetworkDisconnected": "{networkName} leválasztva",
	"NoNetworkConnectivity": "Nincs hálózati kapcsolat",
	"None": "--",
	"OtherNetwork": "Egyéb hálózat",
	"Password": "Jelszó",
	"Retry": "Visszatérés",
	"SavedNetworks": "Mentett hálózatok",
	"SecurityOptions": "Biztonsági opciók",
	"SecurityType": "Biztonság típusa",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "hu_HU");