var Localization_netmgmtAppDict_cn_HK = {
	//"stringId" : "localString"
	"Connect": "連線",
	"ConnectTo": "連線到 {networkName}",
	"Connecting": "正在連線",
	"ConnectionError": "連線錯誤",
	"ConnectionSetup": "設定",
	"Delete": "刪除",
	"DeleteANetwork": "刪除網路以繼續",
	"DeleteConfirmation": "確定要刪除{networkName}？",
	"DeleteNetwork": "刪除 Wi-Fi 網路",
	"Disconnect": "斷開連線",
	"Disconnecting": "正在斷開連線",
	"DoYouWantToConnect": "是否要設定？",
	"EnterPassword": "輸入密碼",
	"ErrorDHCP": "DHCP 錯誤。 獲取設定失敗。",
	"ErrorInternal": "內部錯誤",
	"ErrorNetwork": "網路錯誤",
	"GUI_WifiNetworkLost_Alert": "失去 Wi-Fi 網路",
	"GUI_WrongPassword_Alert": "錯誤密碼",
	"InvalidPassword": "密碼無效",
	"MaxNetworksReached": "新增至網路清單中的網路數目已達到最大限制。",
	"NameSSID": "名稱 (SSID)",
	"NetworkConnection": "Wi-Fi",
	"NetworkDisconnected": "{networkName} 已斷開連線。",
	"NoNetworkConnectivity": "需要網路連線",
	"None": "無",
	"OtherNetwork": "其他網路",
	"Password": "密碼",
	"Retry": "重試",
	"SavedNetworks": "已儲存網路",
	"SecurityOptions": "安全選項",
	"SecurityType": "安全類型",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "cn_HK");