var Localization_netmgmtAppDict_cs_CS = {
	//"stringId" : "localString"
	"Connect": "Připojit",
	"ConnectTo": "Připojit k síti {networkName}",
	"Connecting": "Připojování",
	"ConnectionError": "Chyba spojení",
	"ConnectionSetup": "Nastavení připojení",
	"Delete": "Odstranit",
	"DeleteANetwork": "Smažte síť a pokračujte",
	"DeleteConfirmation": "Opravdu chcete odstranit {networkName}?",
	"DeleteNetwork": "Smazat síť Wi-Fi",
	"Disconnect": "Odpojit",
	"Disconnecting": "Odpojování",
	"DoYouWantToConnect": "Chcete připojit?",
	"EnterPassword": "Zadejte heslo",
	"ErrorDHCP": "Chyba DHCP. Nezdařilo se načíst nastavení.",
	"ErrorInternal": "Vnitřní chyba",
	"ErrorNetwork": "Chyba sítě",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi síť byla ztracena",
	"GUI_WrongPassword_Alert": "Nesprávné heslo",
	"InvalidPassword": "Neplatné heslo",
	"MaxNetworksReached": "Maximální počet sítí byl přidán do seznamu sítí.",
	"NameSSID": "Název (SSID)",
	"NetworkConnection": "Síťové připojení",
	"NetworkDisconnected": "Síť {networkName} byla odpojena",
	"NoNetworkConnectivity": "Žádné síťové připojení",
	"None": "--",
	"OtherNetwork": "Další síť",
	"Password": "Heslo",
	"Retry": "Zkusit znovu",
	"SavedNetworks": "Uložené síťové nastavení",
	"SecurityOptions": "Bezpečnostní nastavení",
	"SecurityType": "Bezpečnostní typ",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "cs_CS");