var Localization_netmgmtAppDict_he_IL = {
	//"stringId" : "localString"
	"Connect": "התחבר",
	"ConnectTo": "התחבר ל {networkName}",
	"Connecting": "מתחבר",
	"ConnectionError": "שגיאת התקשרות",
	"ConnectionSetup": "הגדרת חיבור",
	"Delete": "מחק",
	"DeleteANetwork": "מחק רשת להמשך",
	"DeleteConfirmation": "האם אתה בטוח שברצונך למחוק {networkName}?",
	"DeleteNetwork": "מחק רשת Wi-Fi",
	"Disconnect": "התנתק",
	"Disconnecting": "מתנתק",
	"DoYouWantToConnect": "האם ברצונך להתחבר?",
	"EnterPassword": "הכנס סיסמה",
	"ErrorDHCP": "שגיאת DHCP.  כשל בהשגת הגדרות.",
	"ErrorInternal": "שגיאה פנימית",
	"ErrorNetwork": "שגיאת רשת",
	"GUI_WifiNetworkLost_Alert": "רשת Wi-Fi אבדה",
	"GUI_WrongPassword_Alert": "סיסמה לא נכונה",
	"InvalidPassword": "סיסמה אינה תקפה",
	"MaxNetworksReached": "מספר הרשתות המרבי הוסף לרשימת הרשתות.",
	"NameSSID": "שם (SSID)",
	"NetworkConnection": "חיבור לרשת",
	"NetworkDisconnected": "התנתק {networkName}",
	"NoNetworkConnectivity": "אין התחברות לרשת",
	"None": "--",
	"OtherNetwork": "רשת אחרת",
	"Password": "סיסמה",
	"Retry": "נסה שנית",
	"SavedNetworks": "רשתות שמורות",
	"SecurityOptions": "אפשרויות בטוחות",
	"SecurityType": "סוג בטיחות",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "he_IL");