var Localization_netmgmtAppDict_pt_PT = {
	//"stringId" : "localString"
	"Connect": "Ligar",
	"ConnectTo": "Ligar a {networkName}",
	"Connecting": "A Ligar",
	"ConnectionError": "Erro de Ligação",
	"ConnectionSetup": "Configur. da Ligação",
	"Delete": "Eliminar",
	"DeleteANetwork": "Elimine uma rede para prosseguir",
	"DeleteConfirmation": "Tem a certeza de que pretende eliminar  {networkName}?",
	"DeleteNetwork": "Eliminar Rede Wi-Fi",
	"Disconnect": "Desligar",
	"Disconnecting": "A Desligar",
	"DoYouWantToConnect": "Quer ligar-se?",
	"EnterPassword": "Introd. Palavra-passe",
	"ErrorDHCP": "Erro DHCP. Falha ao obter definições.",
	"ErrorInternal": "Erro Interno",
	"ErrorNetwork": "Erro de Rede",
	"GUI_WifiNetworkLost_Alert": "Rede Wi-Fi Perdida",
	"GUI_WrongPassword_Alert": "Palavra-passe Incorrecta",
	"InvalidPassword": "Palavra-passe Inválida",
	"MaxNetworksReached": "O número máximo de Redes foi adicionado à Lista de Redes.",
	"NameSSID": "Nome (SSID)",
	"NetworkConnection": "Ligação de Rede",
	"NetworkDisconnected": " {networkName} foi Desligada",
	"NoNetworkConnectivity": "Sem Ligação à Rede",
	"None": "--",
	"OtherNetwork": "Outra Rede",
	"Password": "Palavra-passe",
	"Retry": "Tentar Novamente",
	"SavedNetworks": "Redes Guardadas",
	"SecurityOptions": "Opções de Segurança",
	"SecurityType": "Tipo de Segurança",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "pt_PT");