var Localization_netmgmtAppDict_pl_PL = {
	//"stringId" : "localString"
	"Connect": "Połącz",
	"ConnectTo": "Podłącz do {networkName}",
	"Connecting": "Łączenie",
	"ConnectionError": "Błąd połączenia",
	"ConnectionSetup": "Konfiguracja połącz.",
	"Delete": "Wymaż",
	"DeleteANetwork": "Usuń sieć",
	"DeleteConfirmation": "Czy na pewno chcesz wymazać {networkName}?",
	"DeleteNetwork": "Usuń sieć Wi-Fi",
	"Disconnect": "Rozłącz",
	"Disconnecting": "Rozłączanie",
	"DoYouWantToConnect": "Czy chcesz połączyć się?",
	"EnterPassword": "Wprowadź hasło",
	"ErrorDHCP": "Błąd DHCP. Nie pobrano ustawień.",
	"ErrorInternal": "Błąd wewnętrzny",
	"ErrorNetwork": "Błąd sieci.",
	"GUI_WifiNetworkLost_Alert": "Utrata połączenia z siecią Wi-Fi",
	"GUI_WrongPassword_Alert": "Nieprawidłowe hasło",
	"InvalidPassword": "Nieprawidłowe hasło",
	"MaxNetworksReached": "Do listy sieci dodano maksymalną liczbę sieci.",
	"NameSSID": "Nazwa (SSID)",
	"NetworkConnection": "Sieć",
	"NetworkDisconnected": "{networkName} została odłączona",
	"NoNetworkConnectivity": "Brak możliwości połączenia w sieci",
	"None": "--",
	"OtherNetwork": "Inna sieć",
	"Password": "Hasło",
	"Retry": "Ponów",
	"SavedNetworks": "Zapisane sieci",
	"SecurityOptions": "Opcje zabezpieczeń",
	"SecurityType": "Typ zabezpieczeń",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "pl_PL");