var Localization_netmgmtAppDict_da_DK = {
	//"stringId" : "localString"
	"Connect": "Tilslut",
	"ConnectTo": "Tilslut til {networkName}",
	"Connecting": "Tilslutter",
	"ConnectionError": "Forbindelsesfejl",
	"ConnectionSetup": "Opsætn.af forb.",
	"Delete": "Slet",
	"DeleteANetwork": "Slet et netværk for at fortsætte",
	"DeleteConfirmation": "Er du sikker på, at du vil slette {networkName}?",
	"DeleteNetwork": "Slet Wi-Fi netværk",
	"Disconnect": "Afbryd",
	"Disconnecting": "Frakobler ",
	"DoYouWantToConnect": "Ønsker du at tilslutte?",
	"EnterPassword": "Indtast adgangskode",
	"ErrorDHCP": "DHCP fejl. Kunne ikke hente indstillinger.",
	"ErrorInternal": "Intern fejl",
	"ErrorNetwork": "Netværksfejl",
	"GUI_WifiNetworkLost_Alert": "Mistet forbindelse til Wi-Fi-netværk",
	"GUI_WrongPassword_Alert": "Forkert adgangskode",
	"InvalidPassword": "Ugyldig adgangskode",
	"MaxNetworksReached": "Maks. antal netværk er tilføjet netvæskslisten",
	"NameSSID": "Navn (SSID)",
	"NetworkConnection": "Netværksforb.",
	"NetworkDisconnected": "{networkName} er blevet afbrudt",
	"NoNetworkConnectivity": "Ingen netværksforbindelse",
	"None": "--",
	"OtherNetwork": "Andet netværk",
	"Password": "Adgangskode",
	"Retry": "Prøv igen",
	"SavedNetworks": "Gemte netværk",
	"SecurityOptions": "Sikkerhedsindstillinger",
	"SecurityType": "Sikkerhedstype",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "da_DK");