var Localization_netmgmtAppDict_zh_TW = {
	//"stringId" : "localString"
	"Connect": "連接",
	"ConnectTo": "連接到 {networkName}",
	"Connecting": "正在連接",
	"ConnectionError": "連接錯誤",
	"ConnectionSetup": "連接設定",
	"Delete": "刪除",
	"DeleteANetwork": "刪除一個網路，繼續",
	"DeleteConfirmation": "確定要刪除 {networkName} 嗎？",
	"DeleteNetwork": "刪除 Wi-Fi 網路",
	"Disconnect": "斷開",
	"Disconnecting": "正在斷開連接",
	"DoYouWantToConnect": "是否希望連接？",
	"EnterPassword": "輸入密碼",
	"ErrorDHCP": "DHCP錯誤。獲得設置失敗。",
	"ErrorInternal": "內部錯誤",
	"ErrorNetwork": "網路錯誤",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi 網路遺失",
	"GUI_WrongPassword_Alert": "密碼錯誤",
	"InvalidPassword": "無效的密碼",
	"MaxNetworksReached": "已將最多網路新增到了網路清單中。",
	"NameSSID": "名稱/SSID",
	"NetworkConnection": "網路連接",
	"NetworkDisconnected": "{networkName} 已斷開連接",
	"NoNetworkConnectivity": "無網路連接",
	"None": "無",
	"OtherNetwork": "其他網路",
	"Password": "網路連接",
	"Retry": "重試",
	"SavedNetworks": "已儲存的網路",
	"SecurityOptions": "安全選項",
	"SecurityType": "安全類型",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "zh_TW");