var Localization_netmgmtAppDict_sr_RS = {
	//"stringId" : "localString"
	"Connect": "Poveži",
	"ConnectTo": "Poveži na {networkName}",
	"Connecting": "Povezivanje",
	"ConnectionError": "Greška veze",
	"ConnectionSetup": "Podeš. Veze",
	"Delete": "Izbriši",
	"DeleteANetwork": "Za nastavak obrišite mrežu",
	"DeleteConfirmation": "Jeste li sigurni da želite da izbrišete {networkName}?",
	"DeleteNetwork": "Izbriši Wi-Fi mrežu",
	"Disconnect": "Prekini vezu",
	"Disconnecting": "Sidanje sa Wi-Fi mreže",
	"DoYouWantToConnect": "Želite da se povežete?",
	"EnterPassword": "Unesi lozinku",
	"ErrorDHCP": "Greška DHCP-a. Pribavljanje podešavanja nije uspelo",
	"ErrorInternal": "Interna greška",
	"ErrorNetwork": "Greška na mreži",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi mreža izgubljena",
	"GUI_WrongPassword_Alert": "Pogrešna lozinka",
	"InvalidPassword": "Nevažeća lozinka",
	"MaxNetworksReached": " Maks. broj mreža je dodat na Listu mreža. Brisanje mreže za nastavak.",
	"NameSSID": "Ime (SSID)",
	"NetworkConnection": "Mrežna veza",
	"NetworkDisconnected": "Veza sa {networkName} je prekinuta",
	"NoNetworkConnectivity": "Ne postoji veza sa mrežom",
	"None": "--",
	"OtherNetwork": "Druga mreža",
	"Password": "Lozinka",
	"Retry": "Pokušaj ponovo",
	"SavedNetworks": "Sačuvane mreže",
	"SecurityOptions": "Opcije bezbednosti",
	"SecurityType": "Tip bezbednosti",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "sr_RS");