var Localization_netmgmtAppDict_ja_JP = {
	//"stringId" : "localString"
	"Connect": "接続",
	"ConnectTo": "接続 : {networkName}",
	"Connecting": "接続中...",
	"ConnectionError": "接続エラー",
	"ConnectionSetup": "接続設定",
	"Delete": "削除",
	"DeleteANetwork": "新しく登録するには、\nネットワークの削除が必要です。",
	"DeleteConfirmation": "{networkName} を削除しますか？",
	"DeleteNetwork": "Wi-Fiネットワークを削除",
	"Disconnect": "接続を解除",
	"Disconnecting": "接続を解除中...",
	"DoYouWantToConnect": "接続しますか？",
	"EnterPassword": "パスワード",
	"ErrorDHCP": "DHCPエラーが発生しました。\n設定を取得できません。",
	"ErrorInternal": "内部エラーが発生しました。",
	"ErrorNetwork": "ネットワークエラーが発生しました。",
	"GUI_WifiNetworkLost_Alert": "Wi-Fi Network Lost",
	"GUI_WrongPassword_Alert": "パスワードが\n正しくありません。",
	"InvalidPassword": "パスワードが間違っています。",
	"MaxNetworksReached": "ネットワークの登録数が\n上限に達しました。",
	"NameSSID": "Name (SSID)",
	"NetworkConnection": "Settings",
	"NetworkDisconnected": "{networkName}\n接続を解除しました。",
	"NoNetworkConnectivity": "ネットワーク接続が必要です。",
	"None": "なし",
	"OtherNetwork": "その他のネットワーク",
	"Password": "パスワード",
	"Retry": "リトライ",
	"SavedNetworks": "ネットワーク",
	"SecurityOptions": "セキュリティオプション",
	"SecurityType": "セキュリティタイプ",
	"WEP": "WEP",
	"WPA": "WPA",
	"WPA2": "WPA2",
	"WPAWPA2": "WPA/WPA2",
	"WiFi": "Wi-Fi",
};

framework.registerAppDictLoaded("netmgmt", "ja_JP");