var Localization_btaudioAppDict_sv_SE = {
	//"stringId" : "localString"
	"BTAudio": "BT-ljud {deviceName}",
	"BTDeviceDisconnect": "BT-enhet frånkopplad",
	"BrowsingUnsupported": "Kan inte bläddra till ansluten enhet",
	"DeviceUnsupported": "Enheten stöds inte",
	"DeviceUnsupportedDescription": "Vill du parkoppla någon annan enhet?",
	"Disconnect": "Bluetooth-anslutning för ljud bruten",
	"MobileDeviceError": "Fel på mobilenhet",
	"MobileDeviceErrorDescription": "Kontrollera din mobila enhet så att allting fungerar som det ska.",
	"SongUnsupported": "Enheten kan inte läsa filen",
	"TooltipRootMenu": "Rotmeny",
	"Tooltip_IcnUmpPlayOrStop": "Pusti/Zaustavi",
	"Unknown": "Okänd",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Spela upp/Stopp",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Ljudinställningar",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Föregående",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Spela upp / Paus",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": " Nästa",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Ljudinställningar",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Upprepa",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Blanda",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Sök",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Föregående",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Spola tillbaka",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Spela upp / Paus",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Snabbspola framåt",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": " Nästa",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Ljudinställningar",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Rotmeny",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Upprepa",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Blanda",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Sök",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Föregående / Nästa",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Spola tillbaka",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Spela upp / Paus",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Snabbspola framåt",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Ljudinställningar",
};

framework.registerAppDictLoaded("btaudio", "sv_SE");