var Localization_btaudioAppDict_et_EE = {
	//"stringId" : "localString"
	"BTAudio": "BT heli – {deviceName}",
	"BTDeviceDisconnect": "Bluetooth-seadme üh. katkestatud",
	"BrowsingUnsupported": "Ühendatud seadme sirvimine ebaõnnestus.",
	"DeviceUnsupported": "Seade pole toetatud",
	"DeviceUnsupportedDescription": "Kas soovite siduda mõne muu seadme?",
	"Disconnect": "Bluetooth-audioühendus kadus",
	"MobileDeviceError": "Mobiilseadme viga",
	"MobileDeviceErrorDescription": "Kontrollige, kas mobiilseade töötab õigesti.",
	"SongUnsupported": "Seade ei suuda faili lugeda",
	"TooltipRootMenu": "Juurmenüü",
	"Tooltip_IcnUmpPlayOrStop": "Esita/peata",
	"Unknown": "Tundmatu",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Play / Stop",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Sound Settings",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Previous",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Play / Pause",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Next",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Sound Settings",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Repeat",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Shuffle",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Scan",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Previous",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Rewind",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Play / Pause",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Fast Forward",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Next",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Root Menu",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Repeat",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Shuffle",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Scan",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Previous / Next",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Rewind",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Fast Forward",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Sound Settings",
};

framework.registerAppDictLoaded("btaudio", "et_EE");