var Localization_btaudioAppDict_ja_JP = {
	//"stringId" : "localString"
	"BTAudio": "Bluetooth - {deviceName}",
	"BTDeviceDisconnect": "Bluetooth Device Disconnected",
	"BrowsingUnsupported": "リストを表示できません。",
	"DeviceUnsupported": "Bluetooth Audio 非対応の機器です。",
	"DeviceUnsupportedDescription": "他の機器と接続しますか？",
	"Disconnect": "Bluetooth接続エラーが発生しました。",
	"MobileDeviceError": "接続エラーが発生しました。",
	"MobileDeviceErrorDescription": "ご使用の携帯機器を確認してください。",
	"SongUnsupported": "ファイルを読み込めませんでした。",
	"TooltipRootMenu": "メニュー",
	"Tooltip_IcnUmpPlayOrStop": "再生/停止",
	"Unknown": "Unknown",
	"VrHelp_NowPlayingA2DP_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlayingA2DP_Help_Left2": "再生/停止",
	"VrHelp_NowPlayingA2DP_Help_Left3": "サウンド設定",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "前へ",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "再生/ 一時停止",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "次へ",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "サウンド設定",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "リピート",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "シャッフル",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "スキャン",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "前へ",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "巻き戻し",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "再生/ 一時停止",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "早送り",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "次へ",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "サウンド設定",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "メニュー",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "リピート",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "シャッフル",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "スキャン",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "前へ /次へ",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "巻き戻し",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "再生/ 一時停止",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "早送り",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "サウンド設定",
};

framework.registerAppDictLoaded("btaudio", "ja_JP");