var Localization_btaudioAppDict_pl_PL = {
	//"stringId" : "localString"
	"BTAudio": "Sprzęt audio BT — {deviceName}",
	"BTDeviceDisconnect": "Urządzenie Bluetooth rozłączone",
	"BrowsingUnsupported": "Nie można przeglądać zawartości podłączonego urządzenia.",
	"DeviceUnsupported": "Urządzenie niekompatybilne",
	"DeviceUnsupportedDescription": "Czy sparować inne urządzenie?",
	"Disconnect": "Zerwane połączenie Bluetooth",
	"MobileDeviceError": "Błąd urządzenia przenośnego",
	"MobileDeviceErrorDescription": "Sprawdź, czy urządzenie przenośne działa prawidłowo.",
	"SongUnsupported": "Urządzenie nie może odczytać pliku",
	"TooltipRootMenu": "Menu główne",
	"Tooltip_IcnUmpPlayOrStop": "Odtwarzaj/zatrzymaj",
	"Unknown": "Nieznany",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Play / Stop",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Sound Settings",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Previous",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Play / Pause",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Next",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Sound Settings",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Repeat",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Shuffle",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Scan",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Previous",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Rewind",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Play / Pause",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Fast Forward",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Next",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Root Menu",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Repeat",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Shuffle",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Scan",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Previous / Next",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Rewind",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Fast Forward",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Sound Settings",
};

framework.registerAppDictLoaded("btaudio", "pl_PL");