var Localization_btaudioAppDict_de_DE = {
	//"stringId" : "localString"
	"BTAudio": "BT-Audio - {deviceName}",
	"BTDeviceDisconnect": "Bluetooth-Gerät getrennt",
	"BrowsingUnsupported": "Kann das verbundene Gerät nicht durchsuchen",
	"DeviceUnsupported": "Gerät wird nicht unterstützt",
	"DeviceUnsupportedDescription": "Möchten Sie ein weiteres Gerät hinzufügen ?",
	"Disconnect": "Bluetooth-Audioverbindung wurde unterbrochen",
	"MobileDeviceError": "Mobilgerät-Fehler",
	"MobileDeviceErrorDescription": "Überprüfen Sie Ihr Mobilgerät.",
	"SongUnsupported": "Gerät kann Datei nicht lesen",
	"TooltipRootMenu": "Stamm-Menü",
	"Tooltip_IcnUmpPlayOrStop": "Wiedergabe/Stopp",
	"Unknown": "Unbekannt",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Wiedergabe / Stopp",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Toneinstellungen",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Vorheriger",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Wiedergabe/Pause",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Nächster",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Toneinstellungen",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Wiederholen",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Mischen",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Abstimmen",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Vorheriger",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Rücklauf",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Wiedergabe/Pause",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Vorlauf",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Nächster",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Toneinstellungen.",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Stammmenü",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Wiederholen",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Mischen",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Abstimmen",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Vorheriger / Nächster",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Rücklauf",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Wiedergabe/Pause",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Vorlauf",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Toneinstellungen.",
};

framework.registerAppDictLoaded("btaudio", "de_DE");