var Localization_btaudioAppDict_nl_NL = {
	//"stringId" : "localString"
	"BTAudio": "BT Audio - {deviceName}",
	"BTDeviceDisconnect": "BT-apparaat uitgeschakeld",
	"BrowsingUnsupported": "Kan niet browsen op het aangesloten apparaat.",
	"DeviceUnsupported": "Apparaat is niet Ondersteund",
	"DeviceUnsupportedDescription": "Wilt u een ander apparaat koppelen?",
	"Disconnect": "Bluetooth Audio Verbinding Verbroken",
	"MobileDeviceError": "Fout mobiel apparaat",
	"MobileDeviceErrorDescription": "Contr. uw mobiele appar. om er zeker van te zijn dat alles goed function.",
	"SongUnsupported": "Apparaat Kan Bestand Niet Lezen",
	"TooltipRootMenu": "Rootmenu",
	"Tooltip_IcnUmpPlayOrStop": "Play/Stop",
	"Unknown": "Onbekend",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingA2DP_Help_Left2": " Afspelen / Stop",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Geluidsinstellingen",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Vorige",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": " Afspelen / Pauze",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Volgende",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Geluidsinstellingen",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Herhalen",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Shuffle",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Scannen",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Vorige",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Terugspoelen",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": " Afspelen / Pauze",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Snel doorspoelen",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Volgende",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Geluidsinstellingen",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Rootmenu",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Herhalen",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Shuffle",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Scannen",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Vorige /  Volgende",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Terugspoelen",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": " Afspelen / Pauze",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Snel doorspoelen",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Geluidsinstellingen",
};

framework.registerAppDictLoaded("btaudio", "nl_NL");