var Localization_btaudioAppDict_da_DK = {
	//"stringId" : "localString"
	"BTAudio": "BT Audio - {deviceName}",
	"BTDeviceDisconnect": "BT-enhed frakoblet",
	"BrowsingUnsupported": "Kan ikke gennemse den tilsluttede enhed",
	"DeviceUnsupported": "Enheden understøttes ikke",
	"DeviceUnsupportedDescription": "Ønsker du at parre endnu en enhed?",
	"Disconnect": "Bluetooth lydforbindelse mistet",
	"MobileDeviceError": "Fejl: mobilenhed",
	"MobileDeviceErrorDescription": "Kontrollér din mobilenhed så du er sikker på, at alt fungerer korrekt.",
	"SongUnsupported": "Enheden kan ikke læse filen",
	"TooltipRootMenu": "Hovedmenu",
	"Tooltip_IcnUmpPlayOrStop": "Afspil/stop",
	"Unknown": "Ukendt",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Underholdning",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Afspil/Stop",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Lydindstillinger",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Underholdning",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Forrige",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Afspil/Pause",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Næste",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Lydindstillinger",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Underholdning",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Gentag",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Bland",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Scan",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Previous",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Spol tilbage",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Afspil/Pause",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Hurtigt frem",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Næste",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Lydindstillinger",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Underholdning",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Hovedmenu",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Gentag",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Bland",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Scan",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Forrige/Næste",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Spol tilbage",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Afspil/Pause",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Hurtigt frem",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Lydindstillinger",
};

framework.registerAppDictLoaded("btaudio", "da_DK");