var Localization_btaudioAppDict_zh_TW = {
	//"stringId" : "localString"
	"BTAudio": "BT音頻-{deviceName}",
	"BTDeviceDisconnect": "已斷開 BT 裝置的連接",
	"BrowsingUnsupported": "不能瀏覽已連接裝置。",
	"DeviceUnsupported": "裝置不受支援",
	"DeviceUnsupportedDescription": "是否要配對另一個裝置？",
	"Disconnect": "Bluetooth音頻連接遺失",
	"MobileDeviceError": "移動設備錯誤",
	"MobileDeviceErrorDescription": "檢查您的移動裝置，確保一切工作正常。",
	"SongUnsupported": "裝置無法讀取檔案",
	"TooltipRootMenu": "根功能表",
	"Tooltip_IcnUmpPlayOrStop": "播放/停止",
	"Unknown": "未知的",
	"VrHelp_NowPlayingA2DP_Help_Left1": "娛樂",
	"VrHelp_NowPlayingA2DP_Help_Left2": "播放 / 停止",
	"VrHelp_NowPlayingA2DP_Help_Left3": "聲音設置",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "上一個",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "下一個",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "聲音設置",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "重複",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "隨機播放",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "掃描",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "上一個",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "倒帶",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "快進",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "下一個",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "根菜單",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "重複",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "隨機播放",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "掃描",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "上一個 / 下一個",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "倒帶",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "快進",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "聲音設置",
};

framework.registerAppDictLoaded("btaudio", "zh_TW");