var Localization_btaudioAppDict_cn_HK = {
	//"stringId" : "localString"
	"BTAudio": "Bluetooth {deviceName}",
	"BTDeviceDisconnect": "BT 裝置已斷開連線",
	"BrowsingUnsupported": "無法檢視已連線裝置上的內容。",
	"DeviceUnsupported": "不支援裝置",
	"DeviceUnsupportedDescription": "是否連線另一台裝置？",
	"Disconnect": "Bluetooth音訊連線遺失",
	"MobileDeviceError": "行動裝置錯誤",
	"MobileDeviceErrorDescription": "檢查您的行動裝置。",
	"SongUnsupported": "裝置無法讀取音訊檔案。",
	"TooltipRootMenu": "主功能表",
	"Tooltip_IcnUmpPlayOrStop": "播放/停止",
	"Unknown": "未知",
	"VrHelp_NowPlayingA2DP_Help_Left1": "娛樂",
	"VrHelp_NowPlayingA2DP_Help_Left2": "播放 / 停止",
	"VrHelp_NowPlayingA2DP_Help_Left3": "聲音設置",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "上一個",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "下一個",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "聲音設置",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "重複",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "隨機播放",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "掃描",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "上一個",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "倒帶",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "快進",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "下一個",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "娛樂",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "根菜單",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "重複",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "隨機播放",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "掃描",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "上一個 / 下一個",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "倒帶",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "播放 / 暫停",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "快進",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "聲音設置",
};

framework.registerAppDictLoaded("btaudio", "cn_HK");