var Localization_satradioAppDict_sk_SK = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Kanály odblokované pre reláciu",
    "ChannelList" : "Zoznam kanálov",
    "ParentalLock" : "Rodičovský zámok",
    "LockCurrentChannel" : "Zamknúť aktu. kanál",
    "EditPINCode" : "Upraviť PIN kód",
    "InitializePINCode" : "Inicializovať PIN kód",
    "EnterPIN" : "Zadať PIN",
    "EnterFactoryPINToReset" : "Resetovanie - PIN",
    "EnterNewPIN" : "Zadať nový PIN",
    "IsThisCorrect" : "Je to správne?",
    "PINSet" : "Nastavenie PIN",
    "AllChannels" : "Všetky kanály",
    "XM" : "XM",
    "SelectLockButton" : "Vyberte tlačidlo zámku a odom. kanále pre reláciu",
    "RadioID" : "ID rádia: {radioId}",
    "XMChannelNotAvailable" : "XM kanál nie je k dispozícii",
    "XMChannelNotAuthorized" : "XM kanál nie je autorizovaný",
    "NoXMSignal" : "Žiaden XM signál",
    "CheckXMAntenna" : "Skontrolujte XM anténu",
    "XMChannelOffAir" : "XM kanál nevysiela",
    "LoadingXM" : "Zavádzanie XM",
    "CheckXMTuner" : "Skontrolujte XM tuner",
    "CategoryAllChannels" : "Kategória: Všetky kanály",
    "CategoryList" : "Zoznam kategórií",
    "SessionLock" : "Zámok relácie",
    "ResetPINCode" : "Resetovať PIN kód",
    "WrongPIN" : "Nesprávny PIN kód",
    "PleaseTryAgain" : "Skúste znovu",
    "Category" : "Kategória: {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "sk_SK");