var Localization_satradioAppDict_th_TH = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "ปลดล็อกช่องสำหรับเซสชันแล้ว",
    "ChannelList" : "รายการช่อง",
    "ParentalLock" : "การล็อกโดยผู้ปกครอง",
    "LockCurrentChannel" : "ล็อกช่องปัจจุบัน",
    "EditPINCode" : "แก้ไขรหัส PIN",
    "InitializePINCode" : "เริ่มการทำงานของรหัส PIN",
    "EnterPIN" : "ป้อนรหัส PIN",
    "EnterFactoryPINToReset" : "ป้อน PIN งานเพื่อรีเซ็ต",
    "EnterNewPIN" : "ป้อนรหัส PIN ใหม่",
    "IsThisCorrect" : "ถูกต้องหรือไม่",
    "PINSet" : "ตั้งค่า PIN",
    "AllChannels" : "ช่องทั้งหมด",
    "XM" : "XM",
    "SelectLockButton" : "เลือกปุ่มล็อกเพื่อปลดล็อกช่องสำหรับเซสชัน",
    "RadioID" : "ID วิทยุ : {radioId}",
    "XMChannelNotAvailable" : "ช่องสัญญาณ XM ไม่พร้อมใช้งาน",
    "XMChannelNotAuthorized" : "ไม่อนุญาตให้ใช้ช่องสัญญาณ XM",
    "NoXMSignal" : "ไม่มีสัญญาณ XM ",
    "CheckXMAntenna" : "ตรวจสอบเสาอากาศ XM ",
    "XMChannelOffAir" : "ช่องสัญญาณ XM ไม่ออกอากาศ",
    "LoadingXM" : "การโหลด XM",
    "CheckXMTuner" : "ตรวจสอบตัวปรับสัญญาณ XM",
    "CategoryAllChannels" : "หมวดหมู่ : ช่องทั้งหมด",
    "CategoryList" : "รายการหมวดหมู่",
    "SessionLock" : "ล็อกเซสชัน",
    "ResetPINCode" : "รีเซ็ตรหัส PIN",
    "WrongPIN" : "PIN ไม่ถูกต้อง",
    "PleaseTryAgain" : "โปรดลองใหม่อีกครั้ง",
    "Category" : "หมวดหมู่ : {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "th_TH");