var Localization_satradioAppDict_it_IT = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Canali sbloccati per la sessione",
    "ChannelList" : "Elenco canali",
    "ParentalLock" : "Controllo genitori",
    "LockCurrentChannel" : "Blocca canale attuale",
    "EditPINCode" : "Modifica codice PIN",
    "InitializePINCode" : "Inizializza codice PIN",
    "EnterPIN" : "Inserisci PIN",
    "EnterFactoryPINToReset" : "Pin per reset",
    "EnterNewPIN" : "Nuovo PIN",
    "IsThisCorrect" : "È corretto?",
    "PINSet" : "PIN impostato",
    "AllChannels" : "Tutti i canali",
    "XM" : "XM",
    "SelectLockButton" : "Premi il puls. \"Blocco\" per sbloc. i canali per la sess.",
    "RadioID" : "ID Radio: {radioId}",
    "XMChannelNotAvailable" : "Canale XM non disponibile.",
    "XMChannelNotAuthorized" : "Canale XM non autorizzato.",
    "NoXMSignal" : "Nessun segnale XM",
    "CheckXMAntenna" : "Controlla Antenna XM",
    "XMChannelOffAir" : "Canale XM non trasmesso",
    "LoadingXM" : "Caricamento XM",
    "CheckXMTuner" : "Controlla Tuner XM",
    "CategoryAllChannels" : "Categoria : Tutti i canali",
    "CategoryList" : "Elenco categorie",
    "SessionLock" : "Blocco sessione",
    "ResetPINCode" : "Resetta Codice PIN",
    "WrongPIN" : "PIN errato.",
    "PleaseTryAgain" : "Riprova",
    "Category" : "Categoria : {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Cambia sorgente",
    "VrHelp_NowPlaying_Help_Left2" : "Preferiti",
    "VrHelp_NowPlaying_Help_Left3" : "Elenco canali",
    "VrHelp_NowPlaying_Help_Left4" : "Scansione",
    "VrHelp_NowPlaying_Help_Left5" : "Successivo",
    "VrHelp_NowPlaying_Help_Right1" : "Precedente",
    "VrHelp_NowPlaying_Help_Right2" : "Controllo genitori",
    "VrHelp_NowPlaying_Help_Right3" : "Impostazioni audio",
    "VrHelp_NowPlaying_Help_Right4" : "Canale (numero)",
    "VrHelp_NowPlaying_Help_Right5" : "Riproduci (nome canale)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Blocca canale attuale",
    "VrHelp_ParentalLock_Help_1_Left2" : "Sblocca canale attuale",
    "VrHelp_ParentalLock_Help_1_Left3" : "Controllo genitori acceso",
    "VrHelp_ParentalLock_Help_1_Left4" : "Controllo genitori spento",
    "VrHelp_ParentalLock_Help_1_Left5" : "Inizializza codice Pin",
    "VrHelp_ParentalLock_Help_1_Right1" : "Azzera codice PIN",
    "VrHelp_ParentalLock_Help_2_Left1" : "Blocca canale attuale",
    "VrHelp_ParentalLock_Help_2_Left2" : "Sblocca canale attuale",
    "VrHelp_ParentalLock_Help_2_Left3" : "Controllo genitori acceso",
    "VrHelp_ParentalLock_Help_2_Left4" : "Controllo genitori spento",
    "VrHelp_ParentalLock_Help_2_Left5" : "Modifica codice PIN",
    "VrHelp_ParentalLock_Help_2_Right1" : "Resetta codice PIN",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(cifre 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Annulla",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Inizializza codice Pin",
    "VrHelp_PinEntryReset_Help_Left1" : "(cifre 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "Ok",
    "VrHelp_PinEntryReset_Help_Left3" : "Annulla",
    "VrHelp_PinEntryNew_Help_Left1" : "(cifre 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "Ok",
    "VrHelp_PinEntryNew_Help_Left3" : "Annulla",
};

framework.registerAppDictLoaded("satradio", "it_IT");