var Localization_satradioAppDict_sv_SE = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Kanalerna är upplåsta för session",
    "ChannelList" : "Kanallista",
    "ParentalLock" : "Föräldralås",
    "LockCurrentChannel" : "Lås aktuell kanal",
    "EditPINCode" : "Ange PIN-kod",
    "InitializePINCode" : "Initiera PIN-kod",
    "EnterPIN" : "Ange PIN",
    "EnterFactoryPINToReset" : "Fabriks-PIN, återst",
    "EnterNewPIN" : "Ange ny PIN",
    "IsThisCorrect" : "Är detta rätt?",
    "PINSet" : "PIN inställd",
    "AllChannels" : "Alla kanaler",
    "XM" : "XM",
    "SelectLockButton" : "Välj låsknapp för att låsa upp kanaler för sessionen",
    "RadioID" : "Radio-ID: {radioId}",
    "XMChannelNotAvailable" : "XM-kanal är inte tillgänglig",
    "XMChannelNotAuthorized" : "XM-kanal är inte godkänd",
    "NoXMSignal" : "Ingen XM-signal",
    "CheckXMAntenna" : "Kontrollera XM-antennen",
    "XMChannelOffAir" : "XM-kanal sänder inte",
    "LoadingXM" : "Läser in XM",
    "CheckXMTuner" : "Kontrollera XM-radiodelen",
    "CategoryAllChannels" : "Kategori: Alla kanaler",
    "CategoryList" : "Kategorilista",
    "SessionLock" : "Sessionslås",
    "ResetPINCode" : "Återställ PIN-kod",
    "WrongPIN" : "Fel PIN",
    "PleaseTryAgain" : "Prova på nytt.",
    "Category" : "Kategori: {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Ändra källa",
    "VrHelp_NowPlaying_Help_Left2" : "Favoriter",
    "VrHelp_NowPlaying_Help_Left3" : "Kanallista",
    "VrHelp_NowPlaying_Help_Left4" : "Sök",
    "VrHelp_NowPlaying_Help_Left5" : "Nästa",
    "VrHelp_NowPlaying_Help_Right1" : "Föregående",
    "VrHelp_NowPlaying_Help_Right2" : "Föräldralås",
    "VrHelp_NowPlaying_Help_Right3" : "Ljudinställningar",
    "VrHelp_NowPlaying_Help_Right4" : "Kanal (nummer)",
    "VrHelp_NowPlaying_Help_Right5" : "Spela (kanalnamn)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lås aktuell kanal",
    "VrHelp_ParentalLock_Help_1_Left2" : "Lås upp aktuell kanal",
    "VrHelp_ParentalLock_Help_1_Left3" : "Föräldralås på",
    "VrHelp_ParentalLock_Help_1_Left4" : "Föräldralås av",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initiera PIN-kod",
    "VrHelp_ParentalLock_Help_1_Right1" : "Återställ PIN-kod",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lås aktuell kanal",
    "VrHelp_ParentalLock_Help_2_Left2" : "Lås upp aktuell kanal",
    "VrHelp_ParentalLock_Help_2_Left3" : "Föräldralås på",
    "VrHelp_ParentalLock_Help_2_Left4" : "Föräldralås av",
    "VrHelp_ParentalLock_Help_2_Left5" : "Redigera PIN-kod",
    "VrHelp_ParentalLock_Help_2_Right1" : "Återställ PIN-kod",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(siffrorna 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Rensa",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initiera PIN-kod",
    "VrHelp_PinEntryReset_Help_Left1" : "(siffrorna 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Rensa",
    "VrHelp_PinEntryNew_Help_Left1" : "(siffrorna 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Rensa",
};

framework.registerAppDictLoaded("satradio", "sv_SE");