var Localization_satradioAppDict_hu_HU = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "A csatornák munkamenet céljából nyitva vannak",
    "ChannelList" : "Csatornák listája",
    "ParentalLock" : "Gyerekzár",
    "LockCurrentChannel" : "Aktuál.csatorna eltárol",
    "EditPINCode" : "PIN-kód szerkesztése",
    "InitializePINCode" : "PIN-kód inicializálása",
    "EnterPIN" : "PIN-kód beírása",
    "EnterFactoryPINToReset" : "Gy. PIN-kód váll.",
    "EnterNewPIN" : "Új PIN-kód beír.",
    "IsThisCorrect" : "Rendben?",
    "PINSet" : "PIN-kód beállítása",
    "AllChannels" : "Összes csatorna",
    "XM" : "XM",
    "SelectLockButton" : "Feloldásához válassza a Zárolás gombot",
    "RadioID" : "Rádió azonosítója: {radioId}",
    "XMChannelNotAvailable" : "Nem elérhető XM-csatorna",
    "XMChannelNotAuthorized" : "Nem hitelesített XM-csatorna",
    "NoXMSignal" : "Nincs XM-jel",
    "CheckXMAntenna" : "XM-antenna ellenőrzése",
    "XMChannelOffAir" : "Adásszünet az XM-csatornán",
    "LoadingXM" : "XM betöltése",
    "CheckXMTuner" : "XM-tuner ellenőrzése",
    "CategoryAllChannels" : "Kategória Összes csatorna",
    "CategoryList" : "Kategórialista",
    "SessionLock" : "Munkamenet-zárolás",
    "ResetPINCode" : "PIN-kód visszaállítása",
    "WrongPIN" : "Helytelen PIN",
    "PleaseTryAgain" : "Próbálja újra",
    "Category" : "Kategória {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "hu_HU");