var Localization_satradioAppDict_no_NO = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Kanalene er låst opp for økten",
    "ChannelList" : "Kanalliste",
    "ParentalLock" : "Barnelås",
    "LockCurrentChannel" : "Lås gjeldende kanal",
    "EditPINCode" : "Rediger PIN-kode",
    "InitializePINCode" : "Initialiser PIN-kode",
    "EnterPIN" : "Legg inn PIN",
    "EnterFactoryPINToReset" : "Angi fab.-PIN, n.st.",
    "EnterNewPIN" : "Angi ny PIN",
    "IsThisCorrect" : "Er dette korrekt?",
    "PINSet" : "Stille inn PIN",
    "AllChannels" : "Alle kanaler",
    "XM" : "XM",
    "SelectLockButton" : "Velg låseknappen for å låse opp kanaler",
    "RadioID" : "Radio-ID: {radioId}",
    "XMChannelNotAvailable" : "XM-kanalen er ikke tilgjengelig",
    "XMChannelNotAuthorized" : "XM-kanalen er ikke autorisert",
    "NoXMSignal" : "Intet XM-signal",
    "CheckXMAntenna" : "Sjekk XM-antennen",
    "XMChannelOffAir" : "XM-kanalen er ikke på lufta",
    "LoadingXM" : "Laster XM",
    "CheckXMTuner" : "Sjekk XM-mottakeren",
    "CategoryAllChannels" : "Kategori: Alle kanaler",
    "CategoryList" : "Kategoriliste",
    "SessionLock" : "Sesjonslås",
    "ResetPINCode" : "Tilbakestill PIN-kode",
    "WrongPIN" : "Feil PIN",
    "PleaseTryAgain" : "Prøv på nytt",
    "Category" : "Kategori: {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "no_NO");