var Localization_satradioAppDict_lt_LT = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Kanalai atrakinti seansui",
    "ChannelList" : "Kanalų sąrašas",
    "ParentalLock" : "Užraktas nuo vaikų",
    "LockCurrentChannel" : "Užrakinti dab. kan.",
    "EditPINCode" : "Redaguoti PIN kodą",
    "InitializePINCode" : "Inicijuoti PIN kodą",
    "EnterPIN" : "Įveskite PIN",
    "EnterFactoryPINToReset" : "Įv. Gam. PIN nust.",
    "EnterNewPIN" : "Įveskite naują PIN",
    "IsThisCorrect" : "Teisingai?",
    "PINSet" : "PIN nustatytas",
    "AllChannels" : "Visi kanalai",
    "XM" : "XM",
    "SelectLockButton" : "Pasirinkd. užrakto mygtuką atrakin. kan. seansui",
    "RadioID" : "Radijo ID : {radioId}",
    "XMChannelNotAvailable" : "XM kanalas nepasiekiamas",
    "XMChannelNotAuthorized" : "XM kanalas neleidžiamas",
    "NoXMSignal" : "XM signalo nėra",
    "CheckXMAntenna" : "Patikrinkite XM anteną",
    "XMChannelOffAir" : "XM kanalas netransliuojamas",
    "LoadingXM" : "Įkeliamas XM",
    "CheckXMTuner" : "Patikrinkite XM imtuvą",
    "CategoryAllChannels" : "Kategorija: visi kanalai",
    "CategoryList" : "Kategorijų sąrašas",
    "SessionLock" : "Seanso užraktas",
    "ResetPINCode" : "Iš naujo nustatyti PIN kodą",
    "WrongPIN" : "Neteisingas PIN",
    "PleaseTryAgain" : "Bandykite dar kartą",
    "Category" : "Kategorija: {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "lt_LT");