var Localization_satradioAppDict_zh_CN = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "會話頻道已解鎖",
    "ChannelList" : "频道列表",
    "ParentalLock" : "家长锁",
    "LockCurrentChannel" : "锁定当前频道",
    "EditPINCode" : "编辑 PIN 码",
    "InitializePINCode" : "初始化 PIN 码",
    "EnterPIN" : "输入 PIN",
    "EnterFactoryPINToReset" : "输入工厂PIN重设",
    "EnterNewPIN" : "输入新 PIN",
    "IsThisCorrect" : "是否正确？",
    "PINSet" : "PIN 设置",
    "AllChannels" : "所有频道",
    "XM" : "XM",
    "SelectLockButton" : "选择锁定按钮，解锁用户会话的频道",
    "RadioID" : "无线电台ID：{radioId}",
    "XMChannelNotAvailable" : "XM频道不可用",
    "XMChannelNotAuthorized" : "XM频道未授权",
    "NoXMSignal" : "无XM信号",
    "CheckXMAntenna" : "检查XM天线",
    "XMChannelOffAir" : "XM频道不可用",
    "LoadingXM" : "正在加载XM",
    "CheckXMTuner" : "检查XM调谐器",
    "CategoryAllChannels" : "类别：所有频道",
    "CategoryList" : "类别列表",
    "SessionLock" : "会话锁定",
    "ResetPINCode" : "重置PIN码",
    "WrongPIN" : "PIN错误",
    "PleaseTryAgain" : "请重试",
    "Category" : "类别：{cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "更改来源",
    "VrHelp_NowPlaying_Help_Left2" : "收藏夹",
    "VrHelp_NowPlaying_Help_Left3" : "频道列表",
    "VrHelp_NowPlaying_Help_Left4" : "扫描",
    "VrHelp_NowPlaying_Help_Left5" : "下一曲",
    "VrHelp_NowPlaying_Help_Right1" : "上一个",
    "VrHelp_NowPlaying_Help_Right2" : "家长锁",
    "VrHelp_NowPlaying_Help_Right3" : "声音设置",
    "VrHelp_NowPlaying_Help_Right4" : "频道（编号）",
    "VrHelp_NowPlaying_Help_Right5" : "播放（频道名称）",
    "VrHelp_ParentalLock_Help_1_Left1" : "锁定当前频道",
    "VrHelp_ParentalLock_Help_1_Left2" : "解锁当前频道",
    "VrHelp_ParentalLock_Help_1_Left3" : "家长锁开",
    "VrHelp_ParentalLock_Help_1_Left4" : "家长锁关",
    "VrHelp_ParentalLock_Help_1_Left5" : "初始化 PIN 码",
    "VrHelp_ParentalLock_Help_1_Right1" : "重置PIN码",
    "VrHelp_ParentalLock_Help_2_Left1" : "锁定当前频道",
    "VrHelp_ParentalLock_Help_2_Left2" : "解锁当前频道",
    "VrHelp_ParentalLock_Help_2_Left3" : "家长锁开",
    "VrHelp_ParentalLock_Help_2_Left4" : "家长锁关",
    "VrHelp_ParentalLock_Help_2_Left5" : "编辑 PIN 码",
    "VrHelp_ParentalLock_Help_2_Right1" : "重置PIN码",
    "VrHelp_PinEntryUnlock_Help_Left1" : "（数字 0-9）",
    "VrHelp_PinEntryUnlock_Help_Left2" : "确定",
    "VrHelp_PinEntryUnlock_Help_Left3" : "清除",
    "VrHelp_PinEntryUnlock_Help_Left4" : "初始化 PIN 码",
    "VrHelp_PinEntryReset_Help_Left1" : "（数字 0-9）",
    "VrHelp_PinEntryReset_Help_Left2" : "确定",
    "VrHelp_PinEntryReset_Help_Left3" : "清除",
    "VrHelp_PinEntryNew_Help_Left1" : "（数字 0-9）",
    "VrHelp_PinEntryNew_Help_Left2" : "确定",
    "VrHelp_PinEntryNew_Help_Left3" : "清除",
};

framework.registerAppDictLoaded("satradio", "zh_CN");