var Localization_satradioAppDict_ms_MY = {
    //"stringId" : "localString"
    "ChannelsUnlockedForSession" : "Saluran Dibuka Untuk Sesi",
    "ChannelList" : "Senarai Saluran",
    "ParentalLock" : "Kunci Ibu Bapa",
    "LockCurrentChannel" : "Kunci Saluran Semasa",
    "EditPINCode" : "Edit Kod PIN",
    "InitializePINCode" : "Mulakan Kod PIN",
    "EnterPIN" : "Masukkan PIN",
    "EnterFactoryPINToReset" : "Msk PIN Klg Set",
    "EnterNewPIN" : "Masuk PIN Baru",
    "IsThisCorrect" : "Adakah ini betul?",
    "PINSet" : "PIN Ditetapkan",
    "AllChannels" : "Semua Saluran",
    "XM" : "XM",
    "SelectLockButton" : "Pilih Butang Kunci untuk membuka saluran bagi sesi",
    "RadioID" : "ID Radio: {radioId}",
    "XMChannelNotAvailable" : "Saluran XM Tidak Tersedia",
    "XMChannelNotAuthorized" : "Saluran XM Tidak Dibenarkan",
    "NoXMSignal" : "Tiada Isyarat XM",
    "CheckXMAntenna" : "Periksa Antena XM",
    "XMChannelOffAir" : "Saluran XM Tidak Disiarkan",
    "LoadingXM" : "Memuatkan XM",
    "CheckXMTuner" : "Periksa Penala XM",
    "CategoryAllChannels" : "Kategori : Semua Saluran",
    "CategoryList" : "Senarai Kategori",
    "SessionLock" : "Kunci Sesi",
    "ResetPINCode" : "Tetapkan Semula Kod PIN",
    "WrongPIN" : "PIN Salah",
    "PleaseTryAgain" : "Sila Cuba Lagi",
    "Category" : "Kategori : {cachedSelectedGenre}",
    "VrHelp_NowPlaying_Help_Left1" : "Change Source",
    "VrHelp_NowPlaying_Help_Left2" : "Favorites",
    "VrHelp_NowPlaying_Help_Left3" : "Channel List",
    "VrHelp_NowPlaying_Help_Left4" : "Scan",
    "VrHelp_NowPlaying_Help_Left5" : "Next",
    "VrHelp_NowPlaying_Help_Right1" : "Previous",
    "VrHelp_NowPlaying_Help_Right2" : "Parental Lock",
    "VrHelp_NowPlaying_Help_Right3" : "Sound Settings",
    "VrHelp_NowPlaying_Help_Right4" : "Channel (number)",
    "VrHelp_NowPlaying_Help_Right5" : "Play (channel name)",
    "VrHelp_ParentalLock_Help_1_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_1_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_1_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_1_Left5" : "Initialize PIN Code",
    "VrHelp_ParentalLock_Help_1_Right1" : "Reset PIN Code",
    "VrHelp_ParentalLock_Help_2_Left1" : "Lock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left2" : "Unlock Current Channel",
    "VrHelp_ParentalLock_Help_2_Left3" : "Parental Lock On",
    "VrHelp_ParentalLock_Help_2_Left4" : "Parental Lock Off",
    "VrHelp_ParentalLock_Help_2_Left5" : "Edit PIN Code",
    "VrHelp_ParentalLock_Help_2_Right1" : "Reset PIN Code",
    "VrHelp_PinEntryUnlock_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryUnlock_Help_Left2" : "OK",
    "VrHelp_PinEntryUnlock_Help_Left3" : "Clear",
    "VrHelp_PinEntryUnlock_Help_Left4" : "Initialize PIN Code",
    "VrHelp_PinEntryReset_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryReset_Help_Left2" : "OK",
    "VrHelp_PinEntryReset_Help_Left3" : "Clear",
    "VrHelp_PinEntryNew_Help_Left1" : "(digits 0-9)",
    "VrHelp_PinEntryNew_Help_Left2" : "OK",
    "VrHelp_PinEntryNew_Help_Left3" : "Clear",
};

framework.registerAppDictLoaded("satradio", "ms_MY");