var Localization_systemAppDict_pl_PL = {
    //"stringId" : "localString"
    "Communication" : "Komunikacja",
    "Entertainment" : "Rozrywka",
    "Settings" : "Ustawienia",
    "Pandora" : "Aplikacja Pandora",
    "Connect" : "Połącz",
    "Contacts" : "Kontakty",
    "Email" : "Email",
    "Sms" : "Wiadomość SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Niepodłączony telefon",
    "NoConnectionNotifyText" : "Czy połączyć telefon teraz?",
    "DialPhone" : "Wybierz numer",
    "CallHistory" : "Historia połączeń",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Przychodząca wiadomość od:",
    "NotifyReadNow" : "Czy odczytać teraz?",
    "NotifyOff" : "Wył. Powiad.",
    "NotifyIgnore" : "Ignoruj",
    "NotifyRead" : "Odczyt",
    "Notifications" : "Powiadomienia",
    "Applications" : "Aplikacje",
    "NavigationTitle" : "Nawigacja",
    "FavoritesItem" : "Ulubione",
    "ActiveCallItem" : "Połączenie aktywne",
    "UsbAudioAWithDevice" : "USB 1 — {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 — {deviceName}",
    "BluetoothWithDevice" : "Bluetooth — {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Informacje o natężeniu ruchu",
    "HDTrafficItem" : "Radio HD — mapa natężenia ruchu",
    "NoDeviceTitle" : "Brak połączonego urządzenia.",
    "NoDeviceText" : "Czy połączyć urządzenie teraz?",
    "EcoenergyApp" : "Układ zużycia paliwa",
    "SchedMaintenanceApp" : "Konserwacja",
    "WarnGuidanceApp" : "Wskazówka ostrzegawcza",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Identyfikacja kierowcy",
    "VehicleDataTransferItem" : "Przesyłanie danych pojazdu",
    "TempWarning" : "Ostrzeżenie o wys. Temp.",
    "WarningTitle" : "OSTRZEŻENIE!",
    "DisclaimerText" : "Rozproszenie może spowodować wypadek. Nie używaj podczas jazdy. Zawsze skup się na prowadzeniu pojazdu i przestrzegaj przepisów ruchu drogowego. Zobacz instr. obsługi.",
    "TempWarningText" : "Zbyt wysoka temp. wyświetlacza. Ekran może nie działać prawidłowo do czasu schłodzenia.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Menu rozrywki",
    "ReconnectBTAudio" : "Pon. łącz. z BluetoothAudio - wzn.odtw.",
    "ReconnectPandora" : "Pon. łącz. z BluetoothAudio - Pandora",
    "ReconnectStitcher" : "Pon. łącz. z BluetoothAudio- Stitcher",
    "ReconnectAhaRadio" : "Pon. łącz. z BluetoothAudio - Aha Radio",
    "ReconnectUSB" : "Pon. podłącz.USB - wznow. odtw.",
    "ReconnectCD" : "Weryf. dysku CD do wznow. odtw.",
    "ReconnectDVD" : "Weryf. dysku DVD do wznow. odtw.  ",
    "ReconnectFailedBTAudio" : "Nie można ponownie podłączyć Bluetooth Audio",
    "ReconnectFailedUSB" : "Zawartość urządzenia USB została zmieniona. Nie można wznowić odtwarzania.",
    "ReconnectFailedCD" : "Dysk CD został wyjęty. Nie można wznowić odtwarzania.",
    "ReconnectFailedDVD" : "Dysk DVD został wyjęty. Nie można wznowić odtwarzania.",
    "AudioSourceNotAvailableBTAudio" : "Niedostępne Bluetooth Audio ",
    "AudioSourceNotAvailableUSB" : "Zawartość  USB została zmieniona.",
    "AudioSourceNotAvailableCD" : "Dysk CD został wyjęty.",
    "AudioSourceNotAvailableDVD" : "Dysk DVD został wyjęty.",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "General Tutorial",
    "RetryLabel" : "Audio",
    "VideoSignalLost" : "Sygnał video utracony",
    "CheckAntenna" : "Sprawdź antenę",
    "CheckTuner" : "Sprawdź tuner",
    "ChannelOffAir" : "Kanał nie nadaje",
    "ChannelUnauth" : "Kanał nieautoryzowany",
    "AhaMaintError" : "Błąd konserwacji aha",
    "TextSent" : "SMS wysłana",
    "TextDownloaded" : "SMS wysłana",
    "agree" : "Zgadzam się",
};

framework.registerAppDictLoaded("system", "pl_PL");