var Localization_systemAppDict_th_TH = {
    //"stringId" : "localString"
    "Communication" : "การสื่อสาร",
    "Entertainment" : "ความบันเทิง",
    "Settings" : "การตั้งค่า",
    "Pandora" : "Pandora",
    "Connect" : "เชื่อมต่อ",
    "Contacts" : "รายชื่อผู้ติดต่อ",
    "Email" : "อีเมล",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "ช่องเสริม",
    "NoConnectionNotifyTitle" : "ไม่มีโทรศัพท์ที่เชื่อมต่อ",
    "NoConnectionNotifyText" : "คุณต้องการเชื่อมต่อโทรศัพท์เดี๋ยวนี้หรือไม่",
    "DialPhone" : "กดโทรศัพท์",
    "CallHistory" : "ประวัติการโทร",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "ข้อความเข้าจาก:",
    "NotifyReadNow" : "คุณต้องการอ่านเดี๋ยวนี้หรือไม่",
    "NotifyOff" : "ปิดแจ้งเตือน",
    "NotifyIgnore" : "ละเว้น",
    "NotifyRead" : "อ่าน",
    "Notifications" : "การแจ้งเตือน",
    "Applications" : "แอปพลิเคชัน",
    "NavigationTitle" : "ระบบนำทาง",
    "FavoritesItem" : "รายการโปรด",
    "ActiveCallItem" : "สายที่ใช้งานอยู่",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "บลูทูธ - {deviceName}",
    "DVDItem" : "แผ่น DVD",
    "TVItem" : "ทีวี",
    "TrafficAlertsItem" : "ข้อมูลการจราจร",
    "HDTrafficItem" : "แผนที่การจราจร HD Radio™",
    "NoDeviceTitle" : "ไม่ได้เชื่อมต่ออุปกรณ์",
    "NoDeviceText" : "คุณต้องการเชื่อมต่ออุปกรณ์เดี๋ยวนี้หรือไม่",
    "EcoenergyApp" : "การตรวจสอบการประหยัดเชื้อเพลิง",
    "SchedMaintenanceApp" : "การบำรุงรักษา",
    "WarnGuidanceApp" : "คำแนะนำการเตือน",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "ใบอนุญาตขับขี่รถยนต์",
    "VehicleDataTransferItem" : "การถ่ายโอนข้อมูลรถ",
    "TempWarning" : "ไฟเตือนอุณหภูมิ",
    "WarningTitle" : "คำเตือน",
    "DisclaimerText" : "การรบกวนสมาธิอาจทำให้เกิดอุบัติเหตุได้ ห้ามใช้งานขณะขับรถ มีสมาธิในการขับรถและปฏิบัติตามกฎจราจรเสมอ ดูคู่มือการใช้งาน",
    "TempWarningText" : "จอแสดงผลร้อนเกินไป ประสิทธิภาพของจอแสดงผลอาจลดลงจนกว่าจะเย็น",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "เมนูความบันเทิง",
    "ReconnectBTAudio" : "กำลังเชื่อมต่อบลูทูธเพื่อกลับไปเล่นต่อ",
    "ReconnectPandora" : "กำลังเชื่อมต่อบลูทูธสำหรับ Pandora",
    "ReconnectStitcher" : "กำลังเชื่อมต่อบลูทูธสำหรับ Stitcher",
    "ReconnectAhaRadio" : "กำลังเชื่อมต่อบลูทูธสำหรับ aha Radio",
    "ReconnectUSB" : "กำลังเชื่อมต่อบลูทูธเพื่อกลับไปเล่นต่อ",
    "ReconnectCD" : "กำลังตรวจสอบแผ่น CD เพื่อกลับไปเล่นต่อ",
    "ReconnectDVD" : "กำลังตรวจสอบแผ่นDVDเพื่อกลับไปเล่นต่อ",
    "ReconnectFailedBTAudio" : "ไม่สามารถเชื่อมต่อสัญญาณเสียงบลูทูธใหม่",
    "ReconnectFailedUSB" : "อุปกรณ์ USB มีการเปลี่ยนแปลง ไม่สามารถเล่นต่อ",
    "ReconnectFailedCD" : "นำแผ่น CD ออกแล้ว ไม่สามารถเล่นต่อ",
    "ReconnectFailedDVD" : "แผ่น DVD ถูกนำออกแล้ว ไม่สามารถเล่นต่อ",
    "AudioSourceNotAvailableBTAudio" : "ไม่มีสัญญาณเสียงบลูทูธ",
    "AudioSourceNotAvailableUSB" : "อุปกรณ์ USB มีการเปลี่ยนแปลง",
    "AudioSourceNotAvailableCD" : "นำแผ่น CD ออกแล้ว",
    "AudioSourceNotAvailableDVD" : "แผ่น DVD ถูกนำออกแล้ว",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "ไม่สามารถเรียกข้อมูลรายชื่อการแจ้งเตือนได้",
    "RetryLabel" : "ลองใหม่",
    "VideoSignalLost" : "สัญญาณวิดีโอขาดหาย",
    "CheckAntenna" : "ตรวจสอบเสาอากาศ",
    "CheckTuner" : "ตรวจสอบที่ปรับคลื่น",
    "ChannelOffAir" : "สถานีไม่ออกอากาศ",
    "ChannelUnauth" : "สถานีที่ไม่อนุญาต",
    "AhaMaintError" : "ข้อผิดพลาดในการดูแลรักษา aha",
    "TextSent" : "ข้อความถูกส่งแล้ว",
    "TextDownloaded" : "ข้อความถูกดาวน์โหลดแล้ว",
    "agree" : "ผมเห็นด้วย",
};

framework.registerAppDictLoaded("system", "th_TH");