var Localization_systemAppDict_he_IL = {
    //"stringId" : "localString"
    "Communication" : "תקשורת",
    "Entertainment" : "בידור",
    "Settings" : "הגדרות",
    "Pandora" : "פנדורה",
    "Connect" : "קשר",
    "Contacts" : "קישורים ",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "תקליטור",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM   ",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "אין טלפון מחובר",
    "NoConnectionNotifyText" : "האם ברצונך לחבר את הטלפון עכשיו?",
    "DialPhone" : "חייג בטלפון",
    "CallHistory" : "הסטוריית שיחות ",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "הודעה נכנסת מ:",
    "NotifyReadNow" : "האם ברצונך לקרוא את זה עכשיו?",
    "NotifyOff" : "הודעה מכובה",
    "NotifyIgnore" : "התעלם",
    "NotifyRead" : "קרא",
    "Notifications" : "הודעות",
    "Applications" : "יישומים",
    "NavigationTitle" : "ניווט",
    "FavoritesItem" : "מועדפים",
    "ActiveCallItem" : "שיחה פעילה",
    "UsbAudioAWithDevice" : "{deviceName}-USB 1",
    "UsbAudioBWithDevice" : "{deviceName}-USB 2",
    "BluetoothWithDevice" : "Bluetooth -{deviceName} ",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "מידע על תנועה",
    "HDTrafficItem" : "   מפת תנועה HD Radio™   ",
    "NoDeviceTitle" : "אין מכשיר מחובר",
    "NoDeviceText" : "האם ברצונך לחבר את המכשיר עכשיו?",
    "EcoenergyApp" : "משק הדלק",
    "SchedMaintenanceApp" : "תחזוקה",
    "WarnGuidanceApp" : "אזהרת הדרכה",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "בחירת נהג ",
    "VehicleDataTransferItem" : "העברת נתוני רכב",
    "TempWarning" : "התראת טמפרטורה",
    "WarningTitle" : "אזהרה!",
    "DisclaimerText" : "הסחת דעת עלולה לגרום לתאונות. אל תתעסק עם המערכת כשאתה נוהג. תמיד התרכז בנהיגה וציית לתקנות התעבורה. ראה מדריך למשתמש.",
    "TempWarningText" : "צג חם מדי. ביצועי מסך עשויים להיות חלשים יותר עד שהוא מתקרר",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "תפריט בידור",
    "ReconnectBTAudio" : "מחבר מחדש Bluetooth כדי לחדש את",
    "ReconnectPandora" : "מחבר מחדש שמע Bluetooth לפנדורה",
    "ReconnectStitcher" : "מחבר מחדש אודיו Bluetooth לStitcher",
    "ReconnectAhaRadio" : "מחבר מחדש שמע Bluetooth לרדיו aha",
    "ReconnectUSB" : "מחבר מחדש מכשיר USB לחידוש",
    "ReconnectCD" : "מאמת CD לחידוש ההשמעה",
    "ReconnectDVD" : "מאמת DVD לחידוש ההקרנה",
    "ReconnectFailedBTAudio" : "לא ניתן לחבר מחדש אודיו Bluetooth",
    "ReconnectFailedUSB" : "התקן USB  הוחלף לא ניתן לחדש את ההפעלה.",
    "ReconnectFailedCD" : "תקליטור הוסר. אינו מסוגל לחדש את ההפעלה.",
    "ReconnectFailedDVD" : "די-וי-די הוסר. אינו יכול לחדש  את ההפעלה.",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth אודיו אינו זמין",
    "AudioSourceNotAvailableUSB" : "התקן USB  הוחלף",
    "AudioSourceNotAvailableCD" : "תקליטור הוסר",
    "AudioSourceNotAvailableDVD" : "די-וי-די הוסר",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "לא ניתן לאחזר רשימת הודעות",
    "RetryLabel" : "נסה שנית",
    "VideoSignalLost" : "אות וידאו אבד",
    "CheckAntenna" : "בדוק אנטנה",
    "CheckTuner" : "בדוק מקלט",
    "ChannelOffAir" : "הערוץ לא משודר",
    "ChannelUnauth" : "הערוץ לא מורשה",
    "AhaMaintError" : "שגיאת תחזוקת aha",
    "TextSent" : "SMS נשלח",
    "TextDownloaded" : "SMS הורד",
    "agree" : "אני מסכים",
};

framework.registerAppDictLoaded("system", "he_IL");