var Localization_systemAppDict_et_EE = {
    //"stringId" : "localString"
    "Communication" : "Kommunikatsioon",
    "Entertainment" : "Meelelahutus",
    "Settings" : "Sätted",
    "Pandora" : "Pandora",
    "Connect" : "Ühenda",
    "Contacts" : "Kontaktid",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Ühtki telefoni pole ühendatud",
    "NoConnectionNotifyText" : "Kas soovite nüüd telefoni ühendada?",
    "DialPhone" : "Helista telefonile",
    "CallHistory" : "Kõnelogi",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Sissetulev sõnum adressaadilt:",
    "NotifyReadNow" : "Kas soovite seda nüüd lugeda?",
    "NotifyOff" : "Teavit. väljas.",
    "NotifyIgnore" : "Ignoreeri",
    "NotifyRead" : "Loe",
    "Notifications" : "Teatised",
    "Applications" : "Rakendused",
    "NavigationTitle" : "Navigatsioon",
    "FavoritesItem" : "Lemmikud",
    "ActiveCallItem" : "Aktiivne kõne",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Lisateave",
    "HDTrafficItem" : "HD Radio™ liikluskaart",
    "NoDeviceTitle" : "Ühtegi seadet pole ühendatud",
    "NoDeviceText" : "Kas soovite nüüd mõne seadme ühendada?",
    "EcoenergyApp" : "Kütusekulu",
    "SchedMaintenanceApp" : "Hooldus",
    "WarnGuidanceApp" : "Hoiatusteated",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Juhi identifitseerimine",
    "VehicleDataTransferItem" : "Sõiduki andmete edastamine",
    "TempWarning" : "Temperatuurihoiatus",
    "WarningTitle" : "HOIATUS!",
    "DisclaimerText" : "Tähelepanu hajumine võib põhjustada õnnetusi. Ärge kasutage juhtimise ajal. Keskenduge alati juhtimisele ja jälgige liiklusreegleid. Vaadake kasutusjuhendit.",
    "TempWarningText" : "Näidik on üle kuumenenud. Näidik ei pruugi kuni jahtumiseni korralikult töötada.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Meelelahutuse menüü",
    "ReconnectBTAudio" : "Bluetooth-heli taasüh. taasesituseks",
    "ReconnectPandora" : "Bluetooth-heli taasühend. Pandora jaoks",
    "ReconnectStitcher" : "Bluetooth-heli taasühend. Stitcher jaoks",
    "ReconnectAhaRadio" : "Bluetooth-heli taasüh. aha Radio jaoks",
    "ReconnectUSB" : "USB-seadme taasüh. taasesituseks",
    "ReconnectCD" : "CD kontrollimine taasesituse jätkamiseks",
    "ReconnectDVD" : "DVD kontrollimine taasesituse jätkam.",
    "ReconnectFailedBTAudio" : "Bluetooth-audio taasühendamine ebaõnnestus",
    "ReconnectFailedUSB" : "USB-seade on muutunud. Esitamist ei saa jätkata.",
    "ReconnectFailedCD" : "CD eemaldati. Esitamist ei saa jätkata.",
    "ReconnectFailedDVD" : "DVD eemaldati. Esitamist ei saa jätkata.",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth-audio pole saadaval",
    "AudioSourceNotAvailableUSB" : "USB-seade on muutunud",
    "AudioSourceNotAvailableCD" : "CD eemaldati",
    "AudioSourceNotAvailableDVD" : "DVD eemaldati",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Teavituste loendit ei saa tuua",
    "RetryLabel" : "Uuesti",
    "VideoSignalLost" : "Videosignaal on katkenud",
    "CheckAntenna" : "Kontrollige antenni",
    "CheckTuner" : "Kontrollige tuunerit",
    "ChannelOffAir" : "Kanal pole eetris",
    "ChannelUnauth" : "Kanal on lubamatu",
    "AhaMaintError" : "aha hooldustõrge",
    "TextSent" : "SMS on saadetud",
    "TextDownloaded" : "SMS on alla laaditud",
    "agree" : "Nõustun",
};

framework.registerAppDictLoaded("system", "et_EE");