var Localization_systemAppDict_de_DE = {
    //"stringId" : "localString"
    "Communication" : "Kommunikation",
    "Entertainment" : "Unterhaltung",
    "Settings" : "Einstellungen",
    "Pandora" : "Pandora",
    "Connect" : "Verbinden",
    "Contacts" : "Kontakte",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Kein Telefon angeschlossen",
    "NoConnectionNotifyText" : "Möchten Sie jetzt ein Telefon verbinden?",
    "DialPhone" : "Telefon anrufen",
    "CallHistory" : "Anrufhistorie",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Eingehende Nachricht von:",
    "NotifyReadNow" : "Möchten Sie es nun lesen?",
    "NotifyOff" : "Benachr. aus",
    "NotifyIgnore" : "Ignorieren",
    "NotifyRead" : "Lesen",
    "Notifications" : "Benachrichtigungen",
    "Applications" : "Anwendungen",
    "NavigationTitle" : "Navigation",
    "FavoritesItem" : "Favoriten",
    "ActiveCallItem" : "Aktiver Anruf",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Verkehrsinformation",
    "HDTrafficItem" : "HD Radio™ Verkehrskarte",
    "NoDeviceTitle" : "Kein Gerät verbunden",
    "NoDeviceText" : "Möchten Sie jetzt ein Gerät verbinden?",
    "EcoenergyApp" : "Kraftstoffverbrauch",
    "SchedMaintenanceApp" : "Wartung",
    "WarnGuidanceApp" : "Warnmeldungen",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Fahrer-Identifizierung",
    "VehicleDataTransferItem" : "Fahrzeugdaten-Übermittlung",
    "TempWarning" : "Temperaturalarm",
    "WarningTitle" : "Alarm!",
    "DisclaimerText" : "Ablenkung kann Unfälle verursachen. Nicht während der Fahrt benutzen. Immer auf das Fahren konzentrieren und die Verkehrsregeln beachten. Siehe Bedienungsanleitung.",
    "TempWarningText" : "Anzeige ist zu heiss. Bildschirmdarstellung kann verringert sein, bis er abkühlt",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Unterhaltungsmenü",
    "ReconnectBTAudio" : "Ern. Bluetooth Audioverb. z. WdgForts. ",
    "ReconnectPandora" : "Ern. Bluetooth Audioverb. für Pandora",
    "ReconnectStitcher" : "Ern. Bluetooth Audioverb. für Stitcher",
    "ReconnectAhaRadio" : "Ern. Bluetooth Audioverb. für aha Radio",
    "ReconnectUSB" : "Ern. USB-Geräteverb. für Wiedergabe",
    "ReconnectCD" : "Überprüfe CD, um Wiedergabe fortzus.",
    "ReconnectDVD" : "Überprüfe DVD, um Wiedergabe fortzus.",
    "ReconnectFailedBTAudio" : "Kann Bluetooth-Audio nicht wiederverbinden.",
    "ReconnectFailedUSB" : "USB-Gerät hat sich geändert. Kann Wiedergabe nicht fortsetzen.",
    "ReconnectFailedCD" : "CD wurde entfernt. Wiedergabe fortsetzen nicht möglich",
    "ReconnectFailedDVD" : "Die DVD wurde entfernt. Kann Wiedergabe nicht fortsetzen.",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth-Audio nicht verfügbar",
    "AudioSourceNotAvailableUSB" : "USB-Gerät hat sich geändert",
    "AudioSourceNotAvailableCD" : "CD wurde entfernt",
    "AudioSourceNotAvailableDVD" : "DVD wurde nicht entfernt",
    "VrHelp_HomeScreen_Help_Left1" : "Unterhaltung",
    "VrHelp_HomeScreen_Help_Left2" : "Kommunikation",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Einstellungen",
    "VrHelp_HomeScreen_Help_Left5" : "Anwendungen",
    "VrHelp_HomeScreen_Help_Right1" : "Favoriten",
    "FailedNotificationRetrieval" : "Meldungsliste kann nicht geladen werden",
    "RetryLabel" : "Wiederholen",
    "VideoSignalLost" : "Videosignal verloren",
    "CheckAntenna" : "Antenne überprüfen",
    "CheckTuner" : "Tuner überprüfen",
    "ChannelOffAir" : "Sender sendet nicht",
    "ChannelUnauth" : "Unerlaubter Sender",
    "AhaMaintError" : "aha-Wartungsfehler",
    "TextSent" : "SMS gesendet",
    "TextDownloaded" : "SMS heruntergeladen",
    "agree" : "Ich stimme zu",
};

framework.registerAppDictLoaded("system", "de_DE");