var Localization_systemAppDict_ms_MY = {
    //"stringId" : "localString"
    "Communication" : "Komunikasi",
    "Entertainment" : "Hiburan",
    "Settings" : "Tetapan",
    "Pandora" : "Pandora",
    "Connect" : "Sambung",
    "Contacts" : "Kenalan",
    "Email" : "E-mel",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "PG",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Tiada Telefon Disambungkan",
    "NoConnectionNotifyText" : "Adakah anda ingin menyambungkan telefon sekarang?",
    "DialPhone" : "Telefon Dail",
    "CallHistory" : "Sejarah Panggilan",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Mesej Masuk daripada:",
    "NotifyReadNow" : "Adakah anda mahu membaca skrg?",
    "NotifyOff" : "Maklum Mati",
    "NotifyIgnore" : "Abaikan",
    "NotifyRead" : "Baca",
    "Notifications" : "Pemberitahuan",
    "Applications" : "Aplikasi",
    "NavigationTitle" : "Pandu Arah",
    "FavoritesItem" : "Kegemaran",
    "ActiveCallItem" : "Panggilan Aktif",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName} ",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Maklumat Lalu Lintas",
    "HDTrafficItem" : "Peta Trafik HD Radio™",
    "NoDeviceTitle" : "Tiada Peranti Disambungkan",
    "NoDeviceText" : "Adakah anda ingin menyambungkan peranti sekarang?",
    "EcoenergyApp" : "Pengawas Ekonomi Bahan Api",
    "SchedMaintenanceApp" : "Penyelenggaraan",
    "WarnGuidanceApp" : "Panduan Amaran",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Pilihan Pemandu",
    "VehicleDataTransferItem" : "Pemindahan Data Kenderaan",
    "TempWarning" : "Amaran Suhu",
    "WarningTitle" : "AMARAN!",
    "DisclaimerText" : "Gangguan boleh mengakibatkan kemalangan. Jangan kendalikan semasa memandu. Sentiasa berikan tumpuan kepada pemanduan dan patuhi peraturan lalu lintas. Lihat Panduan Pemilik.",
    "TempWarningText" : "Paparan terlalu panas. Prestasi skrin mungkin turun sehingga skrin sejuk.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Menu Hiburan",
    "ReconnectBTAudio" : "Samb sem. audio BT utk terus bermain",
    "ReconnectPandora" : "Sambung semula audio BT utk Pandora",
    "ReconnectStitcher" : "Sambung semula audio BT utk Stitcher",
    "ReconnectAhaRadio" : "Sambung semula audio BT utk aha Radio",
    "ReconnectUSB" : "Smbg semula prnt USB utk smbg m/blk",
    "ReconnectCD" : "Sahkan CD utk meneruskan main balik",
    "ReconnectDVD" : "Sahkan DVD utk meneruskan main balik",
    "ReconnectFailedBTAudio" : "Gagal Menyambung Semula Audio Bluetooth",
    "ReconnectFailedUSB" : "Peranti USB telah berubah. Tidak dapat menyambung semula rakaman.",
    "ReconnectFailedCD" : "CD telah dikeluarkan. Tidak dapat menyambung semula rakaman.",
    "ReconnectFailedDVD" : "DVD telah dikeluarkan. Tidak dapat menyambung semula rakaman.",
    "AudioSourceNotAvailableBTAudio" : "Audio Bluetooth Tidak Tersedia",
    "AudioSourceNotAvailableUSB" : "Peranti USB telah berubah",
    "AudioSourceNotAvailableCD" : "CD telah dikeluarkan",
    "AudioSourceNotAvailableDVD" : "DVD telah dikeluarkan",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Tidak dapat mengambil semula Senarai Pemberitahuan",
    "RetryLabel" : "Cuba Semula",
    "VideoSignalLost" : "Isyarat Video Tiada",
    "CheckAntenna" : "Periksa Antena",
    "CheckTuner" : "Periksa Penala",
    "ChannelOffAir" : "Saluran Tidak Bersiaran",
    "ChannelUnauth" : "Saluran Tidak Dibenarkan",
    "AhaMaintError" : "Ralat Penyelenggaraan aha",
    "TextSent" : "Teks Dihantar",
    "TextDownloaded" : "Teks Dimuat Turun",
    "agree" : "Saya Setuju",
};

framework.registerAppDictLoaded("system", "ms_MY");