var Localization_systemAppDict_it_IT = {
    //"stringId" : "localString"
    "Communication" : "Comunicazione",
    "Entertainment" : "Intrattenimento",
    "Settings" : "Impostazioni",
    "Pandora" : "Pandora",
    "Connect" : "Connetti",
    "Contacts" : "Contatti",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Nessun telefono connesso.",
    "NoConnectionNotifyText" : "Connettere un telefono ora?",
    "DialPhone" : "Telefono con tastiera",
    "CallHistory" : "Registro chiamate",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Messaggio in arrivo da:",
    "NotifyReadNow" : "Leggere ora?",
    "NotifyOff" : "Notify off",
    "NotifyIgnore" : "Ignora",
    "NotifyRead" : "Leggi",
    "Notifications" : "Notifiche",
    "Applications" : "Applicazioni",
    "NavigationTitle" : "Navigazione",
    "FavoritesItem" : "Preferiti",
    "ActiveCallItem" : "Chiamata attiva",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Informazioni sul traffico",
    "HDTrafficItem" : "Informazioni sul traffico Radio HD",
    "NoDeviceTitle" : "Nessun dispositivo connesso.",
    "NoDeviceText" : "Connettere il dispositivo ora?",
    "EcoenergyApp" : "Livello carburante",
    "SchedMaintenanceApp" : "Manutenzione",
    "WarnGuidanceApp" : "Guida avvisi",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Selezione conducente",
    "VehicleDataTransferItem" : "Trasferimento dati veicolo",
    "TempWarning" : "Avviso temperatura",
    "WarningTitle" : "ATTENZIONE!",
    "DisclaimerText" : "La distrazione può causare incidenti. Non fare niente mentre si guida. Rimanere concentrati sulla guida e rispettare le norme stradali. Leggere il manuale di istruzioni.",
    "TempWarningText" : "Il display è troppo caldo. La prestazione dello schermo potrebbe diminuire fin quando non si raffredda.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Menu intrattenimento",
    "ReconnectBTAudio" : "Riconnes audio Bluetooth per riprod",
    "ReconnectPandora" : "Riconnes audio Bluetooth per Pandora",
    "ReconnectStitcher" : "Riconnes audio Bluetooth per Stitcher",
    "ReconnectAhaRadio" : "Riconnes audio Bluetooth per Radio aha",
    "ReconnectUSB" : "Riconnes dispositivo USB per riproduzione",
    "ReconnectCD" : "Verifica Cd per ripristino riproduzione",
    "ReconnectDVD" : "Verifica DVD per ripristino riproduzione",
    "ReconnectFailedBTAudio" : "Impossibile connettere di nuovo l'audio Bluetooth.",
    "ReconnectFailedUSB" : "Il dispositivo USB è cambiato. Impossibile ripristinare la riproduzione.",
    "ReconnectFailedCD" : "Il cd è stato estratto. Impossibile ripristinare la riproduzione.",
    "ReconnectFailedDVD" : "Il DVD è stato estratto. Impossibile ripristinare la riproduzione.",
    "AudioSourceNotAvailableBTAudio" : "Audio Bluetooth non disponibile.",
    "AudioSourceNotAvailableUSB" : "Il dispositivo USB è cambiato",
    "AudioSourceNotAvailableCD" : "Il CD è stato ritirato.",
    "AudioSourceNotAvailableDVD" : "Il DVD è stato ritirato.",
    "VrHelp_HomeScreen_Help_Left1" : "Intrattenimento",
    "VrHelp_HomeScreen_Help_Left2" : "Comunicazione",
    "VrHelp_HomeScreen_Help_Left3" : "Navigazione",
    "VrHelp_HomeScreen_Help_Left4" : "Impostazioni",
    "VrHelp_HomeScreen_Help_Left5" : "Applicazioni",
    "VrHelp_HomeScreen_Help_Right1" : "Preferiti",
    "FailedNotificationRetrieval" : "Impossibile recuperare l'elenco notifiche.",
    "RetryLabel" : "Riprova",
    "VideoSignalLost" : "Segnale video perso",
    "CheckAntenna" : "Controlla antenna",
    "CheckTuner" : "Controlla Tuner ",
    "ChannelOffAir" : "Canale non in diretta",
    "ChannelUnauth" : "Canale non autorizzato",
    "AhaMaintError" : "Errore manutenzione aha.",
    "TextSent" : "SMS inviato",
    "TextDownloaded" : "SMS scaricato",
    "agree" : "Accetto",
};

framework.registerAppDictLoaded("system", "it_IT");