var Localization_systemAppDict_tr_TR = {
    //"stringId" : "localString"
    "Communication" : "İletişim",
    "Entertainment" : "Eğlence",
    "Settings" : "Ayarlar",
    "Pandora" : "Pandora",
    "Connect" : "Bağlan",
    "Contacts" : "Bağlantılar",
    "Email" : "E-posta",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Telefon Bağlı Değil",
    "NoConnectionNotifyText" : "Şimdi bir telefon bağlamak ister misiniz?",
    "DialPhone" : "Numara Çevir",
    "CallHistory" : "Çağrı Geçmişi",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Gelen mesaj, kimden:",
    "NotifyReadNow" : "Şimdi okumak ister misiniz?",
    "NotifyOff" : "Bildirim Kapalı",
    "NotifyIgnore" : "Yok Say",
    "NotifyRead" : "Oku",
    "Notifications" : "Bildirimler",
    "Applications" : "Uygulamalar",
    "NavigationTitle" : "Navigasyon",
    "FavoritesItem" : "Favoriler",
    "ActiveCallItem" : "Etkin Çağrı",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Trafik Bilgisi",
    "HDTrafficItem" : "HD Radio™ Trafik Haritası",
    "NoDeviceTitle" : "Bağlı Aygıt Yok",
    "NoDeviceText" : "Şimdi bir aygıtı bağlamak ister misiniz?",
    "EcoenergyApp" : "Yakıt Ekonomisi",
    "SchedMaintenanceApp" : "Bakım",
    "WarnGuidanceApp" : "Uyarı Kılavuzu",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Sürücü Tanımı",
    "VehicleDataTransferItem" : "Araç Veri Transferi",
    "TempWarning" : "Sıcaklık Uyarısı",
    "WarningTitle" : "UYARI!",
    "DisclaimerText" : "Dikkat kaybı kazalara neden olabilir. Araç sürerken çalıştırmayın. Daima yola odaklanın ve trafik kurallarına uyun. Kullanıcı Kılavuzunu okuyun.",
    "TempWarningText" : "Ekran çok sıcak. Soğuyana kadar ekran performansı düşük olabilir.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Eğlence Menüsü",
    "ReconnectBTAudio" : "Oynatma için Bluetooth sesi bağlanıyor",
    "ReconnectPandora" : "Pandora için Bluetooth sesi bağlanıyor",
    "ReconnectStitcher" : "Stitcher için Bluetooth sesi bağlanıyor",
    "ReconnectAhaRadio" : "aha Radio için Bluetooth sesi bağlanıyor",
    "ReconnectUSB" : "Oynatma için USB aygıtı bağlanıyor",
    "ReconnectCD" : "Oynatma için CD doğrulanıyor",
    "ReconnectDVD" : "Oynatma için DVD doğrulanıyor",
    "ReconnectFailedBTAudio" : "Bluetooth Ses Bağlantısı Kurulamıyor",
    "ReconnectFailedUSB" : "USB aygıtı değişti. Oynatmaya devam edilemiyor.",
    "ReconnectFailedCD" : "CD çıkartıldı. Oynatmaya devam edilemiyor.",
    "ReconnectFailedDVD" : "DVD çıkartıldı. Oynatmaya devam edilemiyor.",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth Ses Mevcut Değil",
    "AudioSourceNotAvailableUSB" : "USB aygıtı değişti",
    "AudioSourceNotAvailableCD" : "CD çıkartıldı",
    "AudioSourceNotAvailableDVD" : "DVD çıkartıldı",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Bildirim Listesi alınamıyor",
    "RetryLabel" : "Tekrar Dene",
    "VideoSignalLost" : "Izgubljen video signal",
    "CheckAntenna" : "Proverite antenu",
    "CheckTuner" : "Proverite radio",
    "ChannelOffAir" : "Stanica se ne emituje",
    "ChannelUnauth" : "Stanica nije autorizovana",
    "AhaMaintError" : "Greška pri održ. aha",
    "TextSent" : "SMS Gönderildi",
    "TextDownloaded" : "SMS İndirildi",
    "agree" : "Kabul Ediyorum",
};

framework.registerAppDictLoaded("system", "tr_TR");