var Localization_systemAppDict_ja_JP = {
    //"stringId" : "localString"
    "Communication" : "Communication",
    "Entertainment" : "Entertainment",
    "Settings" : "Settings",
    "Pandora" : "Pandora",
    "Connect" : "はい",
    "Contacts" : "連絡先",
    "Email" : "メール",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Bluetooth機器が接続されていません。",
    "NoConnectionNotifyText" : "接続しますか？",
    "DialPhone" : "ダイヤル",
    "CallHistory" : "履歴",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "新着メッセージ",
    "NotifyReadNow" : "今すぐ読みますか？",
    "NotifyOff" : "通知しない",
    "NotifyIgnore" : "あとで",
    "NotifyRead" : "読む",
    "Notifications" : "新着通知",
    "Applications" : "Applications",
    "NavigationTitle" : "Navigation",
    "FavoritesItem" : "お気に入り",
    "ActiveCallItem" : "通話中画面",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "交通情報",
    "HDTrafficItem" : "HD Radio™ 交通マップ",
    "NoDeviceTitle" : "Bluetooth機器が接続されていません。",
    "NoDeviceText" : "接続しますか？",
    "EcoenergyApp" : "燃費モニター",
    "SchedMaintenanceApp" : "メンテナンス",
    "WarnGuidanceApp" : "ウォーニングガイダンス",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "ドライバー選択",
    "VehicleDataTransferItem" : "車両データの転送",
    "TempWarning" : "温度警告",
    "WarningTitle" : "安全のために",
    "DisclaimerText" : "運転される方は走行中に\n使用しないでください。\n走行する際は実際の交通規制に\n従ってください。",
    "TempWarningText" : "ディスプレイが非常に熱くなっています。\n温度が下がるまで、画面の性能が\n低下するおそれがあります。",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Entertainment",
    "ReconnectBTAudio" : "Bluetooth Audioに接続中...",
    "ReconnectPandora" : "Pandoraに接続中...",
    "ReconnectStitcher" : "Stitcherに接続中...",
    "ReconnectAhaRadio" : "ahaに接続中...",
    "ReconnectUSB" : "USB読み込み中...",
    "ReconnectCD" : "CD読み込み中...",
    "ReconnectDVD" : "DVD読み込み中...",
    "ReconnectFailedBTAudio" : "Bluetooth接続エラーが発生しました。",
    "ReconnectFailedUSB" : "USBを再生できませんでした。",
    "ReconnectFailedCD" : "CDを再生できませんでした。",
    "ReconnectFailedDVD" : "DVDを再生できませんでした。",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth Audio Not Available",
    "AudioSourceNotAvailableUSB" : "USB device has changed",
    "AudioSourceNotAvailableCD" : "CD was removed",
    "AudioSourceNotAvailableDVD" : "DVD was removed",
    "VrHelp_HomeScreen_Help_Left1" : "エンターテイメント",
    "VrHelp_HomeScreen_Help_Left2" : "通信 (コミュニケーション)",
    "VrHelp_HomeScreen_Help_Left3" : "ナビゲーション",
    "VrHelp_HomeScreen_Help_Left4" : "設定 (セッティング)",
    "VrHelp_HomeScreen_Help_Left5" : "アプリケーション",
    "VrHelp_HomeScreen_Help_Right1" : "お気に入り",
    "FailedNotificationRetrieval" : "新着通知を取得できませんでした。",
    "RetryLabel" : "リトライ",
    "VideoSignalLost" : "Lost Video Signal",
    "CheckAntenna" : "Check Antenna",
    "CheckTuner" : "Check Tuner",
    "ChannelOffAir" : "Channel Off Air",
    "ChannelUnauth" : "Channel Unauthorized",
    "AhaMaintError" : "Aha Maintenance Error",
    "TextSent" : "SMS送信完了",
    "TextDownloaded" : "SMS更新完了",
    "agree" : "OK",
};

framework.registerAppDictLoaded("system", "ja_JP");