var Localization_systemAppDict_id_ID = {
    //"stringId" : "localString"
    "Communication" : "Komunikasi",
    "Entertainment" : "Hiburan",
    "Settings" : "Setelan",
    "Pandora" : "Pandora",
    "Connect" : "Hubungkan",
    "Contacts" : "Kontak",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Tidak Ada Telepon Tersambung",
    "NoConnectionNotifyText" : "Apakah Anda ingin terhubung ke telepon sekarang?",
    "DialPhone" : "Telepon Pemanggil",
    "CallHistory" : "Riwayat Panggilan",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Pesan Masuk dari:",
    "NotifyReadNow" : "Anda ingin membacanya sekarang?",
    "NotifyOff" : "Tanda Mati",
    "NotifyIgnore" : "Abaikan",
    "NotifyRead" : "Baca",
    "Notifications" : "Pemberitahuan",
    "Applications" : "Aplikasi",
    "NavigationTitle" : "Navigasi",
    "FavoritesItem" : "Favorit",
    "ActiveCallItem" : "Panggilan Aktif",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Informasi Lalu Lintas",
    "HDTrafficItem" : "Peta Lalu Lintas HD Radio™",
    "NoDeviceTitle" : "Tidak Ada Perangkat Tersambung",
    "NoDeviceText" : "Apakah Anda ingin terhubung ke perangkat sekarang?",
    "EcoenergyApp" : "Pemantau Kehematan Bahan Bakar",
    "SchedMaintenanceApp" : "Perawatan",
    "WarnGuidanceApp" : "Jarak Peringatan",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Identifikasi Pengendara",
    "VehicleDataTransferItem" : "Transfer Data Kendaraan",
    "TempWarning" : "Peringatan Suhu",
    "WarningTitle" : "PERINGATAN!",
    "DisclaimerText" : "Gangguan dapat menyebabkan kecelakaan. Jangan operasikan saat berkendara. Selalu konsentrasi berkemudi dan taati peraturan lalu-lintas. Lihat Manual Pemilik.",
    "TempWarningText" : "Layar terlalu panas. Kinerja layar menurun hingga suhu mendingin.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Menu Hiburan",
    "ReconnectBTAudio" : "Sambung lagi audio Bluetooth u/ lanjut",
    "ReconnectPandora" : "Sambung ulang Bluetooth u/ Pandora",
    "ReconnectStitcher" : "Sambung ulang Bluetooth u/ Stitcher",
    "ReconnectAhaRadio" : "Sambung ulang Bluetooth u/ Aha Radio",
    "ReconnectUSB" : "Sambung lagi USB untuk melanjutkan",
    "ReconnectCD" : "Mmverifikasi CD u/ lanjut putar",
    "ReconnectDVD" : "Mmverifikasi DVD u/ lanjut putar",
    "ReconnectFailedBTAudio" : "Tidak dapat menyambungkan Audio Bluetooth",
    "ReconnectFailedUSB" : "Perangkat USB berubah. Tidak dapat melanjutkan pemutaran.",
    "ReconnectFailedCD" : "CD telah dicopot. Tidak dapat melanjutkan pemutaran.",
    "ReconnectFailedDVD" : "DVD telah dicopot. Tidak dapat melanjutkan pemutaran.",
    "AudioSourceNotAvailableBTAudio" : "Audio Bluetooth Tidak Tersedia",
    "AudioSourceNotAvailableUSB" : "Perangkat USB berubah",
    "AudioSourceNotAvailableCD" : "CD telah dicopot",
    "AudioSourceNotAvailableDVD" : "DVD telah dicopot",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Tidak dapat mengembalikan Daftar Pemberitahuan",
    "RetryLabel" : "Coba Lagi",
    "VideoSignalLost" : "Sinyal Video Hilang",
    "CheckAntenna" : "Periksa Antena",
    "CheckTuner" : "Periksa Tuner",
    "ChannelOffAir" : "Saluran Tidak Mengudara",
    "ChannelUnauth" : "Saluran Tanpa Autorisasi",
    "AhaMaintError" : "Kesalahan Perawatan aha",
    "TextSent" : "Teks Terkirim",
    "TextDownloaded" : "Teks Diunduh",
    "agree" : "Saya Setuju",
};

framework.registerAppDictLoaded("system", "id_ID");