var Localization_systemAppDict_hu_HU = {
    //"stringId" : "localString"
    "Communication" : "Kommunikáció",
    "Entertainment" : "Szórakozás",
    "Settings" : "Beállítások",
    "Pandora" : "Pandora",
    "Connect" : "Csatlakoztat",
    "Contacts" : "Névjegyek",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Nincs csatlakoztatva telefon",
    "NoConnectionNotifyText" : "Csatlakoztatja a telefont most?",
    "DialPhone" : "Lemez kiadása...",
    "CallHistory" : "Híváselőzmények",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Bejövő üzenet küldője:",
    "NotifyReadNow" : "Elolvassa most?",
    "NotifyOff" : "Értesítés kik.",
    "NotifyIgnore" : "Mellőzés",
    "NotifyRead" : "Olvasás",
    "Notifications" : "Értesítések",
    "Applications" : "Alkalmazások",
    "NavigationTitle" : "Navigáció",
    "FavoritesItem" : "Kedvencek",
    "ActiveCallItem" : "Aktív hívás",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Közlekedési információk",
    "HDTrafficItem" : "HD Radio™ közúti térkép",
    "NoDeviceTitle" : "Nincs eszköz csatlakoztatva",
    "NoDeviceText" : "Most csatlakoztatja az eszközt?",
    "EcoenergyApp" : "Üa-gazdaságossági",
    "SchedMaintenanceApp" : "Karbantartás",
    "WarnGuidanceApp" : "Figyelmeztetés",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Vezetőazonosítás",
    "VehicleDataTransferItem" : "Járműadatok átvitele",
    "TempWarning" : "Hőmérsékleti figyelmeztetés",
    "WarningTitle" : "FIGYELEM!",
    "DisclaimerText" : "A figyelem megszakítása balesethez vezethet. Vezetés közben ne használja. Figyelmét a vezetésre összpontosítsa és tartsa be a szabályokat.  Lásd: Felhasználói útmutató.",
    "TempWarningText" : "Túlmelegedett a képernyő. Teljesítménye lehűlésig gyengébb lehet.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Szórakozás menü",
    "ReconnectBTAudio" : "BT hangk. újral. a lejátszás folyt. érd.",
    "ReconnectPandora" : "BT hangk. újral. a Pandora számára.",
    "ReconnectStitcher" : "BT hangk. újral. a Stitcher számára.",
    "ReconnectAhaRadio" : "BT hangk. újral. az aha rádió számára.",
    "ReconnectUSB" : "USB-eszköz újracs. a lejátszás f. érd.",
    "ReconnectCD" : "CD ell. a lejátszás folytatása előtt.",
    "ReconnectDVD" : "DVD ell. a lejátszás folytatása előtt.",
    "ReconnectFailedBTAudio" : "Sikertelen a Bluetooth hang újracsatlakoztatása",
    "ReconnectFailedUSB" : "Módosult USB-eszköz. A lejátszás nem folytatható.",
    "ReconnectFailedCD" : "CD eltávolítva. A lejátszás nem folytatható.",
    "ReconnectFailedDVD" : "DVD eltávolítva. A lejátszás nem folytatható.",
    "AudioSourceNotAvailableBTAudio" : "Nem áll rendelk.-re Bluetooth hang",
    "AudioSourceNotAvailableUSB" : "Módosult USB-eszköz",
    "AudioSourceNotAvailableCD" : "CD eltávolítva",
    "AudioSourceNotAvailableDVD" : "DVD eltávolítva",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Nem lehetséges az értesítési lista letöltése.",
    "RetryLabel" : "Újrapróbálkozás",
    "VideoSignalLost" : "Képjel vesztés",
    "CheckAntenna" : "Ellenőrizze az antennát.",
    "CheckTuner" : "Ellenőrizze a tunert.",
    "ChannelOffAir" : "Csatorna adásszünet",
    "ChannelUnauth" : "Nem engedélyezett csatorna",
    "AhaMaintError" : "aha karbantartási üzenet",
    "TextSent" : "SMS elküldve",
    "TextDownloaded" : "SMS letöltve",
    "agree" : "Elfogadom",
};

framework.registerAppDictLoaded("system", "hu_HU");