var Localization_systemAppDict_nl_NL = {
    //"stringId" : "localString"
    "Communication" : "Communicatie",
    "Entertainment" : "Entertainment",
    "Settings" : "Instellingen",
    "Pandora" : "Pandora",
    "Connect" : "Verbinden",
    "Contacts" : "Contactpersonen",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Geen Telefoon verbonden",
    "NoConnectionNotifyText" : "Wilt u nu een telefoon koppelen?",
    "DialPhone" : "Bellen",
    "CallHistory" : "Belgeschiedenis",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Binnenkomend Bericht van:",
    "NotifyReadNow" : "Wilt u het nu lezen?",
    "NotifyOff" : "Mededel. UIT",
    "NotifyIgnore" : "Negeren",
    "NotifyRead" : "Lezen",
    "Notifications" : "Mededelingen",
    "Applications" : "Applicaties",
    "NavigationTitle" : "Navigatie",
    "FavoritesItem" : "Favorieten",
    "ActiveCallItem" : "Actieve oproep",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Verkeersinformatie",
    "HDTrafficItem" : "HD Radio™ wegenkaart",
    "NoDeviceTitle" : "Geen apparaat aangesloten",
    "NoDeviceText" : "Wilt u nu een apparaat aansluiten?",
    "EcoenergyApp" : "Brandstofverbruiks",
    "SchedMaintenanceApp" : "Onderhoud",
    "WarnGuidanceApp" : "Waarschuwing",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Identificatie bestuurder",
    "VehicleDataTransferItem" : "Gegevensoverdracht voertuig",
    "TempWarning" : "Temperatuurwaarschuwing",
    "WarningTitle" : "WAARSCHUWING!",
    "DisclaimerText" : "Afleiding kan leiden tot ongelukken. Bedien het apparaat niet tijdens het rijden. Concentreer u altijd op de weg en houd u aan de verkeersregels. Zie handleiding.",
    "TempWarningText" : "Display is te heet. Schermprestatie kan afnemen totdat de display is afgekoeld.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Entertainment Menu",
    "ReconnectBTAudio" : "Bluet. audio opn. verb. om afsp. te herv.",
    "ReconnectPandora" : "Bluetooth audio voor Pandora opn. Verb.",
    "ReconnectStitcher" : "Bluetooth audio voor Stitcher opn. Verb.",
    "ReconnectAhaRadio" : "Bluetooth audio vr Aha Radio opn. Verb.",
    "ReconnectUSB" : "USB app. opn. Verb. om afsp. te herv. ",
    "ReconnectCD" : "CD verifiëren om afspelen te hervatten",
    "ReconnectDVD" : "DVD verifiëren om afspelen te herv.",
    "ReconnectFailedBTAudio" : "Bluetooth audio kan niet opnieuw worden verbonden",
    "ReconnectFailedUSB" : "USB-apparaat is gewijzigd. Opnieuw afspelen mislukt.",
    "ReconnectFailedCD" : "CD werd verwijderd. Opnieuw afspelen mislukt.",
    "ReconnectFailedDVD" : "DVD werd verwijderd. Opnieuw afspelen mislukt.",
    "AudioSourceNotAvailableBTAudio" : "Bluetooth Audio Niet Beschikbaar",
    "AudioSourceNotAvailableUSB" : "USB-apparaat is gewijzigd",
    "AudioSourceNotAvailableCD" : "CD werd verwijderd",
    "AudioSourceNotAvailableDVD" : "DVD werd verwijderd",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communicatie",
    "VrHelp_HomeScreen_Help_Left3" : "Navigatie",
    "VrHelp_HomeScreen_Help_Left4" : "Instellingen",
    "VrHelp_HomeScreen_Help_Left5" : "Applicaties",
    "VrHelp_HomeScreen_Help_Right1" : "Favorieten",
    "FailedNotificationRetrieval" : "Mededelingslijst terughalen mislukt",
    "RetryLabel" : "Opnieuw proberen",
    "VideoSignalLost" : "Videosignaal verbroken",
    "CheckAntenna" : "Controleer antenne",
    "CheckTuner" : "Controleer audio",
    "ChannelOffAir" : "Kanaal uit de lucht",
    "ChannelUnauth" : "Ongeautoriseerd kanaal",
    "AhaMaintError" : "aha onderhoudsfout",
    "TextSent" : "SMS verzonden",
    "TextDownloaded" : "SMS gedownload",
    "agree" : "Mee eens",
};

framework.registerAppDictLoaded("system", "nl_NL");