var Localization_systemAppDict_ar_SA = {
    //"stringId" : "localString"
    "Communication" : "الاتصالات",
    "Entertainment" : " الترفيه",
    "Settings" : "الإعدادات",
    "Pandora" : "تطبيق Pandora",
    "Connect" : "اتصال",
    "Contacts" : "جهات الاتصال",
    "Email" : "بريد إلكتروني",
    "Sms" : "رسائل قصيرة",
    "CdPlayer" : "قرص مضغوط",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "منفذ USB 1",
    "UsbAudioB" : "منفذ USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "مساعد",
    "NoConnectionNotifyTitle" : "لا يوجد هاتف متصل",
    "NoConnectionNotifyText" : "هل ترغب في توصيل هاتف الآن؟",
    "DialPhone" : "هاتف الاتصال",
    "CallHistory" : "سجل المكالمة",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "رسالة واردة من:",
    "NotifyReadNow" : "هل ترغب في قراءته الآن؟",
    "NotifyOff" : "إبطال التن…",
    "NotifyIgnore" : "تجاهل",
    "NotifyRead" : "قراءة",
    "Notifications" : "الإخطارات",
    "Applications" : "التطبيقات",
    "NavigationTitle" : "التنقل",
    "FavoritesItem" : "المفضلات",
    "ActiveCallItem" : "مكالمة نشطة",
    "UsbAudioAWithDevice" : "منفذ USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "منفذ USB 2 - {deviceName}",
    "BluetoothWithDevice" : "البلوتوث - {deviceName}",
    "DVDItem" : "قرص الفيديو الرقمي",
    "TVItem" : "التلفزيون",
    "TrafficAlertsItem" : "المعلومات المتعلقة بحركة المرور",
    "HDTrafficItem" : "HD Radio™ خريطة حركة المرور",
    "NoDeviceTitle" : "لا يوجد جهاز متصل",
    "NoDeviceText" : "هل ترغب في توصيل جهاز الآن؟",
    "EcoenergyApp" : "مراقبة الاقتصاد في الوقود",
    "SchedMaintenanceApp" : "الصيانة",
    "WarnGuidanceApp" : "التوجيه التحذيري",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "تحديد السائق",
    "VehicleDataTransferItem" : "نقل بيانات المركبة",
    "TempWarning" : "تحذير درجة الحرارة",
    "WarningTitle" : "تحذير!",
    "DisclaimerText" : "قد يتسبب تشتت الانتباه في وقوع حوادث. تجنب التشغيل أثناء القيادة. احرص دائمًا على التركيز واتباع لوائح المرور. انظر كتيب المالك.",
    "TempWarningText" : "جهاز العرض ساخن للغاية. قد ينخفض أداء الشاشة حتى تبرد.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "قائمة الترفيه",
    "ReconnectBTAudio" : "إعادة اتصال صوت بلوتوث لاستكما…",
    "ReconnectPandora" : "إعادة اتصال صوت بلوتوث لـPandora",
    "ReconnectStitcher" : "إعادة اتصال صوت بلوتوث لـStitcher",
    "ReconnectAhaRadio" : "إعادة اتصال صوت بلوتوث لراديو aha",
    "ReconnectUSB" : "إعادة اتصال USB لاستئناف التشغيل",
    "ReconnectCD" : "يتحقق من CD لاستئناف التشغيل",
    "ReconnectDVD" : "يتحقق من DVD لاستئناف التشغيل",
    "ReconnectFailedBTAudio" : "لم يتمكن من إعادة الاتصال بصوت البلوتوث.",
    "ReconnectFailedUSB" : "تم تغيير منفذ USB. لم يتمكن من استئناف التشغيل.",
    "ReconnectFailedCD" : "تمت إزالة القرص المضغوط. تعذر استئناف التشغيل.",
    "ReconnectFailedDVD" : "تمت إزالة قرص الفيديو الرقمي. تعذر استئناف التشغيل.",
    "AudioSourceNotAvailableBTAudio" : "صوت البلوتوث غير متاح",
    "AudioSourceNotAvailableUSB" : "تم تغيير منفذ USB",
    "AudioSourceNotAvailableCD" : "تمت إزالة القرص المضغوط",
    "AudioSourceNotAvailableDVD" : "تمت إزالة قرص الفيديو الرقمي",
    "VrHelp_HomeScreen_Help_Left1" : " الترفيه",
    "VrHelp_HomeScreen_Help_Left2" : "الاتصالات",
    "VrHelp_HomeScreen_Help_Left3" : "التنقل",
    "VrHelp_HomeScreen_Help_Left4" : "الإعدادات",
    "VrHelp_HomeScreen_Help_Left5" : "التطبيقات",
    "VrHelp_HomeScreen_Help_Right1" : "المفضلات",
    "FailedNotificationRetrieval" : "تعذر استرجاع قائمة الإخطارات",
    "RetryLabel" : "أعد المحاولة",
    "VideoSignalLost" : "تم فقد إشارة الفيديو",
    "CheckAntenna" : "تفقد الهوائي",
    "CheckTuner" : "تفقد المولف",
    "ChannelOffAir" : "القناة غير مذاعة",
    "ChannelUnauth" : "القناة غير معتمدة",
    "AhaMaintError" : "خطأ في صيانة aha",
    "TextSent" : "تم إرسال النص",
    "TextDownloaded" : "تم تنزيل النص",
    "agree" : "أوافق",
};

framework.registerAppDictLoaded("system", "ar_SA");