var Localization_systemAppDict_cs_CS = {
    //"stringId" : "localString"
    "Communication" : "Komunikace",
    "Entertainment" : "Zábava",
    "Settings" : "Nastavení",
    "Pandora" : "Pandora",
    "Connect" : "Připojit",
    "Contacts" : "Kontakty",
    "Email" : "Email",
    "Sms" : "SMS",
    "CdPlayer" : "CD",
    "Bluetooth" : "Bluetooth",
    "UsbAudioA" : "USB 1",
    "UsbAudioB" : "USB 2",
    "FmRadio" : "FM",
    "AmRadio" : "AM",
    "SdarsRadio" : "XM",
    "AuxIn" : "AUX",
    "NoConnectionNotifyTitle" : "Není připojen telefon",
    "NoConnectionNotifyText" : "Chcete telefon připojit ihned?",
    "DialPhone" : "Klávesnice telefonu",
    "CallHistory" : "Historie hovorů",
    "AhaRadio" : "aha",
    "NotifyIncomingMsg" : "Doručená zpráva – odesílatel:",
    "NotifyReadNow" : "Přečíst hned?",
    "NotifyOff" : "Vyp ozn.",
    "NotifyIgnore" : "Ignorovat",
    "NotifyRead" : "Načíst",
    "Notifications" : "Oznámení",
    "Applications" : "Aplikace",
    "NavigationTitle" : "Navigace",
    "FavoritesItem" : "Oblíbené",
    "ActiveCallItem" : "Aktivní hovor",
    "UsbAudioAWithDevice" : "USB 1 - {deviceName}",
    "UsbAudioBWithDevice" : "USB 2 - {deviceName}",
    "BluetoothWithDevice" : "Bluetooth - {deviceName}",
    "DVDItem" : "DVD",
    "TVItem" : "TV",
    "TrafficAlertsItem" : "Dopravní informace",
    "HDTrafficItem" : "HD Radio™ Traffic Map",
    "NoDeviceTitle" : "Není připojeno žádné zařízení.",
    "NoDeviceText" : "Chcete zařízení připojit ihned?",
    "EcoenergyApp" : "Spotřeba Paliva",
    "SchedMaintenanceApp" : "Údržba",
    "WarnGuidanceApp" : "Var.nav.",
    "IntelligentDriveMasterItem" : "i-DM",
    "DriverIDItem" : "Identifikace řidiče",
    "VehicleDataTransferItem" : "Přenos dat vozidla",
    "TempWarning" : "Teplotní varování",
    "WarningTitle" : "VÝSTRAHA!",
    "DisclaimerText" : "Rozptýlení může způsobit nehody. Nepoužívejte jej při jízdě. Vždy se soustřeďte na řízení a dodržujte pravidla silničního provozu. Viz. Návod k obsluze.",
    "TempWarningText" : "Displej je přehřátý. Do zchladnutí může být omezeno zobrazování.",
    "StitcherItem" : "Stitcher",
    "ReconnectEntMenuButton" : "Nabídka zábavy",
    "ReconnectBTAudio" : "Opět. připoj. Bluetooth k obn. přehráv.",
    "ReconnectPandora" : "Opět.připoj. Bluetooth audio pro Pandora",
    "ReconnectStitcher" : "Opět.připoj. Bluetooth audio pro Stitcher",
    "ReconnectAhaRadio" : "Opět.připoj. Bluetooth pro aha Radio",
    "ReconnectUSB" : "Opět.připoj. USB zaříz. pro obnov. přehr.",
    "ReconnectCD" : "Kontrola CD k obnov. přehrávání",
    "ReconnectDVD" : "Kontrola DVD k obnov. přehrávání",
    "ReconnectFailedBTAudio" : "Připojení zvukového zařízení přes Bluetooth se nezdařilo.",
    "ReconnectFailedUSB" : "Zařízení USB změněno. Přehrávání nemůže pokračovat.",
    "ReconnectFailedCD" : "Byl odebrán disk CD. Přehrávání nemůže pokračovat.",
    "ReconnectFailedDVD" : "Disk DVD byl odebrán. Přehrávání nemůže pokračovat.",
    "AudioSourceNotAvailableBTAudio" : "Audio Bluetooth není k dispozici",
    "AudioSourceNotAvailableUSB" : "Zařízení USB změněno",
    "AudioSourceNotAvailableCD" : "Byl odebrán disk CD.",
    "AudioSourceNotAvailableDVD" : "Disk odebrán",
    "VrHelp_HomeScreen_Help_Left1" : "Entertainment",
    "VrHelp_HomeScreen_Help_Left2" : "Communication",
    "VrHelp_HomeScreen_Help_Left3" : "Navigation",
    "VrHelp_HomeScreen_Help_Left4" : "Settings",
    "VrHelp_HomeScreen_Help_Left5" : "Applications",
    "VrHelp_HomeScreen_Help_Right1" : "Favorites",
    "FailedNotificationRetrieval" : "Nelze načíst seznam oznámení",
    "RetryLabel" : "Zkusit znovu",
    "VideoSignalLost" : "Video signál je ztracen",
    "CheckAntenna" : "Zkontrolujte anténu",
    "CheckTuner" : "Zkontrolujte tuner",
    "ChannelOffAir" : "Kanál Air vyp.",
    "ChannelUnauth" : "Neautorizovaný kanál",
    "AhaMaintError" : "aha Chyba údržby",
    "TextSent" : "SMS odeslaná",
    "TextDownloaded" : "SMS stažená",
    "agree" : "Souhlasím",
};

framework.registerAppDictLoaded("system", "cs_CS");