var Localization_xmdataAppDict_es_MX = {
	//"stringId" : "localString"
	"5DayWeather": "Clima de 5 días",
	"AccountNo": "N.º de serie {number}",
	"AddStock": "Añadir existencias",
	"Alerts": "Alertas",
	"ChangeCity": "Cambiar ciudad ",
	"ChangeCurrentCity": "Cambiar ciudad actual",
	"CityList": "Lista de ciudades",
	"CurrentWeather": "Clima actual",
	"Distance": "Distancia",
	"EditStocks": "Editar existencias",
	"EnterTicker": "Ingresar identificador de existencias",
	"FuelPrices": "Precios del combustible",
	"HourlyPrice": "Precios por hora",
	"Movies": "Películas",
	"NextDay": "Día siguiente",
	"NextGame": "Siguiente juego",
	"NextMovie": "Siguiente película",
	"Parking": "Aparcamiento",
	"PreviousDay": "Día anterior",
	"PreviousGame": "Juego anterior",
	"PreviousMovie": "Película anterior",
	"Price": "Precio",
	"RemoveStock": "¿Eliminar existencias?",
	"RouteTo": "Ruta a",
	"SelectCity": "Seleccionar ciudad",
	"SelectEvent": "Seleccionar evento",
	"SelectLeague": "Seleccionar liga",
	"SelectSport": "Seleccionar deporte",
	"SelectTeam": "Seleccionar equipo",
	"Sports": "Deportes",
	"StockNotFound": "Existencias no encontradas.",
	"StockRemoved": "Existencias eliminadas.",
	"Stocks": "Existencias",
	"Synopsis": "Sinopsis",
	"TodaysWeather": "Clima de hoy",
	"Traffic": "Tráfico",
	"TuneAwayBroadcast": "Sintonizar transmisión del equipo visitante",
	"TuneHomeBroadcast": "Sintonizar transmisión del equipo local",
	"TuneNationalBroadcast": "Sintonizar transmisión nacional",
	"Weather": "Clima  ",
	"WeatherAndSecurityAlerts": "Alertas de clima y seguridad",
	"WeatherForecast": "Pronóstico del tiempo",
	"WeatherRadar": "Radar meteorológico",
	"XMAlerts": "Alertas XM",
	"XMFuelPrices": "Precios del combustible XM",
	"XMLastTeam": "Últimos equipos vistos",
	"XMLeagueOffSeason": "Liga actualmente fuera de temporada",
	"XMMovies": "Películas XM",
	"XMParking": "Aparcamiento XM",
	"XMServiceLoading": "{Selected Service} se está cargando",
	"XMServices": "Servicios XM",
	"XMSportNext": "Siguiente evento",
	"XMSportNoSchedule": "No hay juegos programados para el deporte o evento seleccionado.",
	"XMSportOffSeason": "El deporte o evento seleccionado está fuera de temporada",
	"XMSportPrevious": "Evento anterior",
	"XMSports": "Deportes XM",
	"XMStockDelay": "Todos los datos de existencias se pueden demorar hasta 15 minutos.",
	"XMStockLimit": "Limitado a 20 existencias",
	"XMStocks": "Existencias XM",
	"XMSubscriptionExpired": "Su suscripción XM ha caducado.  Renueve su suscripción llamando a XM al {number}.",
	"XMSubscriptionExpiring": "Su suscripción XM caduca en {days} días.  Renueve su suscripción llamando a XM al {Number}.",
	"XMTeams": "Equipos",
	"XMTraffic": "Tráfico XM",
	"XMWeather": "Clima XM  ",
	"XMWeatherForecast": "Pronóstico del tiempo XM",
	"XMWeatherRadar": "Radar meteorológico XM",
	"ZoomIn": "Acercar",
	"ZoomOut": "Alejar",
};

framework.registerAppDictLoaded("xmdata", "es_MX");