var Localization_xmdataAppDict_fr_CN = {
	//"stringId" : "localString"
	"5DayWeather": "Prévisions météo 5 jours",
	"AccountNo": "No de série {number}",
	"AddStock": "Ajouter un titre boursier",
	"Alerts": "Alertes",
	"ChangeCity": "Changer de ville ",
	"ChangeCurrentCity": "Changer de ville",
	"CityList": "Liste des villes",
	"CurrentWeather": "Météo actuelle",
	"Distance": "Distance",
	"EditStocks": "Éditer le boursiers",
	"EnterTicker": "Entrer le symbole du titre boursier",
	"FuelPrices": "Prix du carburant",
	"HourlyPrice": "Cotations horaires",
	"Movies": "Films",
	"NextDay": "Jour suivant",
	"NextGame": "Match suivant",
	"NextMovie": "Film suivant",
	"Parking": "Parking",
	"PreviousDay": "Jour précédent",
	"PreviousGame": "Match précédent",
	"PreviousMovie": "Film précédent",
	"Price": "Prix",
	"RemoveStock": "Supprimer le titre boursier?",
	"RouteTo": "Aller à",
	"SelectCity": "Choisir une ville",
	"SelectEvent": "Sélectionner l'événement",
	"SelectLeague": "Sélectionner la ligue",
	"SelectSport": "Sélectionner le sport",
	"SelectTeam": "Sélectionner l'équipe",
	"Sports": "Sports",
	"StockNotFound": "Titre boursier introuvable.",
	"StockRemoved": "Titre boursier supprimé.",
	"Stocks": "Titres boursiers",
	"Synopsis": "Synopsis",
	"TodaysWeather": "Météo du jour",
	"Traffic": "Navigation",
	"TuneAwayBroadcast": "Syntoniser la diffusion à l'extérieur",
	"TuneHomeBroadcast": "Syntoniser la diffusion à domicile",
	"TuneNationalBroadcast": "Syntoniser la diffusion nationale",
	"Weather": "Navigation  ",
	"WeatherAndSecurityAlerts": "Alertes Météo et de Sécurité",
	"WeatherForecast": "Prévisions météo",
	"WeatherRadar": "Radar météo",
	"XMAlerts": "Alertes XM",
	"XMFuelPrices": "Prix du carburant XM ",
	"XMLastTeam": "Dernières équipes visualisées",
	"XMLeagueOffSeason": "Ligue actuellement hors saison",
	"XMMovies": "Films XM ",
	"XMParking": "Parking XM",
	"XMServiceLoading": "{Selected Service} en cours de chargement",
	"XMSportNext": "Événement suivant",
	"XMSportNoSchedule": "Aucun match n'est programmé pour le sport ou l'événement sélectionné.",
	"XMSportOffSeason": "Le sport ou l'événement sélectionné est hors saison",
	"XMSportPrevious": "Événement précédent",
	"XMSports": "Sports XM ",
	"XMStockDelay": "Toutes les données boursières peuvent être retardées jusqu'à 15 minutes.",
	"XMStockLimit": "Limite de 20 titres boursiers",
	"XMStocks": "Bourse XM ",
	"XMSubscriptionExpired": "Votre abonnement à XM est expiré.  Pour le renouveler, joignez XM au{number}",
	"XMSubscriptionExpiring": "Votre abonnement à XM vient à échéance dans {days} jours.  Pour le renouveler, joignez XM au{Number}",
	"XMTeams": "Équipes",
	"XMTraffic": "Circulation XM ",
	"XMWeather": "Météo XM   ",
	"XMWeatherForecast": "Prévisions météo XM ",
	"XMWeatherRadar": "Radar météo XM ",
	"ZoomIn": "Zoom avant",
	"ZoomOut": "Zoom arrière",
	"xmdata": "Services XM ",
};

framework.registerAppDictLoaded("xmdata", "fr_CN");