var Localization_tutorialAppDict_fr_FR = {
    //"stringId" : "localString"
    "GeneralTutorial" : "1 Guide général",
    "AudioTutorial" : "2 Guide audio",
    "PhoneTutorial" : "3 Guide téléphonique",
    "AdvancedVoiceTutorial" : "4 Tutoriels pour commande voc avancée",
    "Entertainment" : "Divertissements",
    "Communications" : "Communications",
    "Navigation" : "Navigation",
    "Applications" : "Applications",
    "Favorites" : "Favoris",
    "Settings" : "Paramètres",
    "MainMenu" : "Menu principal",
    "Call" : "Appeler",
    "PlayAlbum" : "Lire l’album",
    "FMRadio" : "Radio FM",
    "AMRadio" : "Radio AM",
    "CDPlayer" : "Lecteur CD",
    "USBAudio" : "Audio par clé USB",
    "XMRadio" : "Radio XM",
    "TuneFreq" : "Régler sur fréquence FM ou AM",
    "TuneChnlName" : "Régler sur nom du canal XM",
    "PlayArtist" : "Lire l’artiste",
    "BrowseSongs" : "Parcourir les morceaux",
    "CallName" : "Appeler un nom",
    "DialPad" : "Clavier",
    "Redial" : "Recomposer (dernier appel sortant)",
    "CallBack" : "Rappeler (dernier appel entrant)",
    "BrowseContacts" : "Parcourir les contacts",
    "RecentCalls" : "Appels récents",
    "ShowMessage" : "Afficher le message",
    "GoToEmail" : "Aller aux Email",
    "TalkIntPrompt" : "La touche Parler interrompt les commandes vocales",
    "SpeakAfterBeep" : "Parler après le bip",
    "SpeakAvoidPause" : "Parler naturellement, éviter les pauses",
    "MinimizeNoise" : "Réduire le bruit (ventilation, fenêtres)",
    "Help" : "Aide",
    "StepByStep" : "Etape par étape",
    "CombineVoice" : "Associer les commandes vocales",
    "GeneralVoiceCtrlTutorial" : "Tutoriel général",
    "AudioCtrlTutorial" : "Audio",
    "PhoneTutorialTitle" : "Téléphone",
    "TutorialSelection" : "Sélectionner le tutoriel",
    "AdvancedVoice" : "Commande vocale avancée",
};

framework.registerAppDictLoaded("tutorial", "fr_FR");