var Localization_tutorialAppDict_da_DK = {
    //"stringId" : "localString"
    "GeneralTutorial" : "1 Generel vejledning",
    "AudioTutorial" : "2 Audio vejledning",
    "PhoneTutorial" : "3 Telefon vejledning",
    "AdvancedVoiceTutorial" : "4 Avanceret stemme vejledning",
    "Entertainment" : "Underholdning",
    "Communications" : "Kommunikation",
    "Navigation" : "Navigering",
    "Applications" : "Applikationer",
    "Favorites" : "Favoritter ",
    "Settings" : "Indstillinger",
    "MainMenu" : "Hovedmenu",
    "Call" : "Ring op",
    "PlayAlbum" : "Afspil album",
    "FMRadio" : "FM-radio",
    "AMRadio" : "AM-radio",
    "CDPlayer" : "CD-afspiller",
    "USBAudio" : "USB-audio",
    "XMRadio" : "XM-radio",
    "TuneFreq" : "Stil ind på FM- eller AM-frekvens",
    "TuneChnlName" : "Stil ind på XM-kanal navn",
    "PlayArtist" : "Afspil kunstner",
    "BrowseSongs" : "Gennemse sange",
    "CallName" : "Ring til navn",
    "DialPad" : "Tastatur",
    "Redial" : "Genopkald (sidste udgående opkald)",
    "CallBack" : "Ring tilbage (sidste indgåede opkald)",
    "BrowseContacts" : "Gennemse kontakter",
    "RecentCalls" : "Seneste opkald",
    "ShowMessage" : "Vis besked",
    "GoToEmail" : "Gå til Email",
    "TalkIntPrompt" : "Taleknap afbryder stemmemeddelelser",
    "SpeakAfterBeep" : "Tal efter bippet",
    "SpeakAvoidPause" : "Tal almindeligt, undgå pauser",
    "MinimizeNoise" : "Minimér støj (blæsere, vinduer)",
    "Help" : "Hjælp",
    "StepByStep" : "Trin for trin",
    "CombineVoice" : "Kombinér stemmekommandoer",
    "GeneralVoiceCtrlTutorial" : "Generel vejledning",
    "AudioCtrlTutorial" : "Audio",
    "PhoneTutorialTitle" : "Telefon",
    "TutorialSelection" : "Vælg vejledning",
    "AdvancedVoice" : "Avanceret stemme",
};

framework.registerAppDictLoaded("tutorial", "da_DK");