var Localization_tutorialAppDict_nl_NL = {
    //"stringId" : "localString"
    "GeneralTutorial" : "1 Handleiding",
    "AudioTutorial" : "2 Handleiding “Audio”",
    "PhoneTutorial" : "3 Handleiding “Telefoon”",
    "AdvancedVoiceTutorial" : "4 Handleiding “Spraak”",
    "Entertainment" : "Entertainment",
    "Communications" : "Communicatie",
    "Navigation" : "Navigatie",
    "Applications" : "Applicaties",
    "Favorites" : "Favorieten",
    "Settings" : "Instellingen",
    "MainMenu" : "Hoofdmenu",
    "Call" : "Bellen",
    "PlayAlbum" : "Album afspelen",
    "FMRadio" : "FM Radio",
    "AMRadio" : "AM-radio",
    "CDPlayer" : "CD-speler",
    "USBAudio" : "USB Audio",
    "XMRadio" : "XM Radio",
    "TuneFreq" : "FM of AM frequentie",
    "TuneChnlName" : "XM-kanaal",
    "PlayArtist" : "Artiest afspelen",
    "BrowseSongs" : "Muziek browsen",
    "CallName" : "Bellen op naam",
    "DialPad" : "Nummerscherm",
    "Redial" : "Opnieuw bellen (last incoming call)",
    "CallBack" : "Terugbellen (last incoming call)",
    "BrowseContacts" : "Contactpersonen browsen",
    "RecentCalls" : "Recente oproepen",
    "ShowMessage" : "Bericht weergeven",
    "GoToEmail" : "Ga naar “Email”",
    "TalkIntPrompt" : "De spreekknop onderbreekt spraakprompts",
    "SpeakAfterBeep" : "Spreek na de pieptoon",
    "SpeakAvoidPause" : "Spreek duidelijk, vermijd pauzes",
    "MinimizeNoise" : "Geluid minimaliseren (vents, windows)",
    "Help" : "Help",
    "StepByStep" : "Stap-voor-stap",
    "CombineVoice" : "Spraakcommando’s combineren",
    "GeneralVoiceCtrlTutorial" : "Algemene handleiding",
    "AudioCtrlTutorial" : "Audio",
    "PhoneTutorialTitle" : "Telefoon",
    "TutorialSelection" : "Handleiding selecteren",
    "AdvancedVoice" : "Geavanceerde spraak",
};

framework.registerAppDictLoaded("tutorial", "nl_NL");