var Localization_tutorialAppDict_ru_RU = {
    //"stringId" : "localString"
    "GeneralTutorial" : "1 Общее руководство",
    "AudioTutorial" : "2 Руководство по аудиосистеме",
    "PhoneTutorial" : "3 Руководство по эксплуатации тел.",
    "AdvancedVoiceTutorial" : "4 Расшир. голосовое руководство",
    "Entertainment" : "Развлечения",
    "Communications" : "Связь",
    "Navigation" : "Навигация",
    "Applications" : "Приложения",
    "Favorites" : "Избранное",
    "Settings" : "Настройки",
    "MainMenu" : "Главное меню",
    "Call" : "Вызов",
    "PlayAlbum" : "Воспроизвести альбом",
    "FMRadio" : "FM радио",
    "AMRadio" : "АМ радио",
    "CDPlayer" : "CD-плеер",
    "USBAudio" : "USB-аудио",
    "XMRadio" : "XM радио",
    "TuneFreq" : "Переключить на FM или AM частоту",
    "TuneChnlName" : "Переключить на имя XM канала",
    "PlayArtist" : "Воспроизвести исполнителя",
    "BrowseSongs" : "Просмотр песен",
    "CallName" : "Название вызова",
    "DialPad" : "Меню ввода номера",
    "Redial" : "Повторный набор (посл. исход.)",
    "CallBack" : "Перезвонить (на послед. вход.)",
    "BrowseContacts" : "Просмотр контактов",
    "RecentCalls" : "Недавние вызовы",
    "ShowMessage" : "Показать сообщение",
    "GoToEmail" : "Перейти к Email",
    "TalkIntPrompt" : "Кнопка «Говорить» прерывает голосовые подсказки",
    "SpeakAfterBeep" : "Говорите после сигнала",
    "SpeakAvoidPause" : "Говорите естественно, избегайте пауз",
    "MinimizeNoise" : "Снизить шум (отверстия, окна)",
    "Help" : "Справка",
    "StepByStep" : "Пошагово",
    "CombineVoice" : "Комбинировать голосовые команды",
    "GeneralVoiceCtrlTutorial" : "Общее руководство",
    "AudioCtrlTutorial" : "Аудио",
    "PhoneTutorialTitle" : "Телефон",
    "TutorialSelection" : "Выбрать руководство",
    "AdvancedVoice" : "Расширенное голосовое",
};

framework.registerAppDictLoaded("tutorial", "ru_RU");