var Localization_tutorialAppDict_mn_TW = {
	//"stringId" : "localString"
	"AMRadio": "AM 廣播電台",
	"AdvancedVoice": "4 進階語音使用指南",
	"AdvancedVoiceTutorial": "4 進階語音使用指南",
	"Applications": "應用程式",
	"AudioCtrlTutorial": "2 音訊使用指南",
	"AudioTutorial": "2 音訊使用指南",
	"BrowseContacts": "瀏覽聯絡人",
	"BrowseSongs": "瀏覽歌曲",
	"CDPlayer": "CD播放器",
	"Call": "撥打電話",
	"CallBack": "回電 (最後一通來電)",
	"CallName": "呼叫「姓名」",
	"CombineVoice": "複合式語音指令",
	"Communications": "通訊",
	"DialPad": "撥號鍵盤顯示",
	"Entertainment": "娛樂",
	"FMRadio": "FM 廣播電台",
	"Favorites": "我的最愛",
	"GeneralTutorial": "1 主要功能使用指南",
	"GeneralVoiceCtrlTutorial": "1 主要功能使用指南",
	"GoToEmail": "移至電子郵件",
	"Help": "說明",
	"MainMenu": "主選單",
	"MinimizeNoise": "減低噪音 (出風口，車窗等)",
	"Navigation": "導航",
	"PhoneTutorial": "3 電話使用指南",
	"PhoneTutorialTitle": "3 電話使用指南",
	"PlayAlbum": "播放專輯",
	"PlayArtist": "依演出者播放",
	"RecentCalls": "最近通話",
	"Redial": "重撥 (最後一次撥出電話)",
	"Settings": "設定",
	"ShowMessage": "顯示訊息",
	"SpeakAfterBeep": "嗶嗶聲後講話",
	"SpeakAvoidPause": "用平常方式講話，勿刻意中斷",
	"StepByStep": "逐步下達語音指令",
	"TalkIntPrompt": "使用通話按鍵來中斷語音提示",
	"TuneChnlName": "調整至 XM「頻道名稱」",
	"TuneFreq": "FM/AM廣播選台",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "藍牙",
	"TutorialSelection": "選擇使用指南清單",
	"TutorialTV": "TV",
	"USBAudio": "USB隨身碟",
	"XMRadio": "XM 廣播電台",
};

framework.registerAppDictLoaded("tutorial", "mn_TW");