var Localization_tutorialAppDict_es_MX = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AdvancedVoice": "Voz avanzada",
	"AdvancedVoiceTutorial": "4 Tutorial de Voz Avanzado",
	"Applications": "Aplicaciones ",
	"AudioCtrlTutorial": "Audio",
	"AudioTutorial": "2 Tutorial de Audio",
	"BrowseContacts": "Buscar Contactos",
	"BrowseSongs": "Buscar Canciones",
	"CDPlayer": "Reproductor de CD",
	"Call": "Llamada ",
	"CallBack": "Devolución de llamada (última llamada entrante)",
	"CallName": "Llamar a Nombre",
	"CombineVoice": "Combinar comandos de voz",
	"Communications": "Comunicación",
	"DialPad": "Teclado de Marcación",
	"Entertainment": "Entretenimiento",
	"FMRadio": "Radio FM",
	"Favorites": "Favoritos ",
	"GeneralTutorial": "1 Tutorial General",
	"GeneralVoiceCtrlTutorial": "Tutorial General",
	"GoToEmail": "Ir a Email",
	"Help": "Ayuda",
	"MainMenu": "Menú Principal",
	"MinimizeNoise": "Minimice el ruido (Ventanas, climatizador)",
	"Navigation": "Navegación",
	"PhoneTutorial": "3 Tutorial de Teléfono",
	"PhoneTutorialTitle": "Teléfono",
	"PlayAlbum": "Reproducir Álbum",
	"PlayArtist": "Reproducir Artista",
	"RecentCalls": "Llamadas Recientes ",
	"Redial": "Volver a marcar (última llamada saliente)",
	"Settings": "Configuraciones",
	"ShowMessage": "Mostrar Mensaje",
	"SpeakAfterBeep": "Hable después del pitido",
	"SpeakAvoidPause": "Hable natural, evite pausas",
	"StepByStep": "Paso a paso",
	"TalkIntPrompt": "El botón Talk interrumpe los avisos de voz",
	"TuneChnlName": "Sintonizar nombre de canal XM",
	"TuneFreq": "Sintonizar frecuencia FM o AM",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Seleccionar tutorial",
	"TutorialTV": "TV",
	"USBAudio": "Audio USB",
	"XMRadio": "Radio XM",
};

framework.registerAppDictLoaded("tutorial", "es_MX");