var Localization_tutorialAppDict_sv_SE = {
	//"stringId" : "localString"
	"AMRadio": "AM radio",
	"AdvancedVoice": "Avancerad röst",
	"AdvancedVoiceTutorial": "4 Avancerad rösthandledning",
	"Applications": "Program",
	"AudioCtrlTutorial": "Ljud",
	"AudioTutorial": "2 Ljudhandledning",
	"BrowseContacts": "Bläddra bland kontakter",
	"BrowseSongs": "Bläddra bland låtar",
	"CDPlayer": "CD-spelare",
	"Call": "Samtal",
	"CallBack": "Ring tillbaka (senaste inkommande samtal)",
	"CallName": "Ring namn",
	"CombineVoice": "Kombinera röstkommandon",
	"Communications": "Kommunikationer",
	"DialPad": "Knappsats",
	"Entertainment": "Underhållning",
	"FMRadio": "FM radio",
	"Favorites": "Favoriter",
	"GeneralTutorial": "1 Allmän handledning",
	"GeneralVoiceCtrlTutorial": "Allmän handledning",
	"GoToEmail": "Gå till e-post",
	"Help": "Hjälp",
	"MainMenu": "Huvudmeny",
	"MinimizeNoise": "Minimera brus (ventilation, fönster)",
	"Navigation": "Navigation",
	"PhoneTutorial": "3 Telefonhandledning",
	"PhoneTutorialTitle": "Telefon",
	"PlayAlbum": "Spela upp album",
	"PlayArtist": "Spela upp artist",
	"RecentCalls": "Senaste samtal",
	"Redial": "Ring upp igen (senaste utgående samtal)",
	"Settings": "Inställningar",
	"ShowMessage": "Visa meddelande",
	"SpeakAfterBeep": "Tala efter pipet",
	"SpeakAvoidPause": "Tala som vanligt, undvik pauser",
	"StepByStep": "Steg för steg",
	"TalkIntPrompt": "Talknappen avbryter röstkommandon",
	"TuneChnlName": "Ställ in på XM-kanal",
	"TuneFreq": "Ställ in på FM- eller AM-frekvens",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Markera handledning",
	"TutorialTV": "TV",
	"USBAudio": "USB-ljud",
	"XMRadio": "XM-radio",
};

framework.registerAppDictLoaded("tutorial", "sv_SE");