var Localization_tutorialAppDict_ja_JP = {
	//"stringId" : "localString"
	"AMRadio": "AM",
	"AdvancedVoice": "4. 音声入力",
	"AdvancedVoiceTutorial": "4. 音声入力",
	"Applications": "ｱﾌﾟﾘｹｰｼｮﾝ",
	"AudioCtrlTutorial": "2. ｴﾝﾀｰﾃｲﾒﾝﾄ",
	"AudioTutorial": "2. ｴﾝﾀｰﾃｲﾒﾝﾄ",
	"BrowseContacts": "連絡先を表示",
	"BrowseSongs": "曲を表示",
	"CDPlayer": "CD/DVD",
	"Call": "電話をかける",
	"CallBack": "ｺｰﾙﾊﾞｯｸ",
	"CallName": "電話",
	"CombineVoice": "音声ｺﾏﾝﾄﾞは組み合わせ可能",
	"Communications": "ｺﾐｭﾆｹｰｼｮﾝ",
	"DialPad": "ﾀﾞｲﾔﾙ",
	"Entertainment": "ｴﾝﾀｰﾃｲﾒﾝﾄ",
	"FMRadio": "FM",
	"Favorites": "お気に入り",
	"GeneralTutorial": "1. 音声ｺﾝﾄﾛｰﾙ全般",
	"GeneralVoiceCtrlTutorial": "1. 音声ｺﾝﾄﾛｰﾙ全般",
	"GoToEmail": "メールを送信",
	"Help": "ﾍﾙﾌﾟ",
	"MainMenu": "ﾒｲﾝﾒﾆｭｰ",
	"MinimizeNoise": "車内の騒音を抑えてください",
	"Navigation": "ﾅﾋﾞｹﾞｰｼｮﾝ",
	"PhoneTutorial": "3. 電話機能",
	"PhoneTutorialTitle": "3. 電話機能",
	"PlayAlbum": "ｱﾙﾊﾞﾑを再生",
	"PlayArtist": "ｱｰﾃｨｽﾄを再生",
	"RecentCalls": "最近の通話履歴",
	"Redial": "ﾘﾀﾞｲﾔﾙ",
	"Settings": "ｾｯﾃｨﾝｸﾞ",
	"ShowMessage": "ﾒｯｾｰｼﾞを表示",
	"SpeakAfterBeep": "通知音の後に話してください",
	"SpeakAvoidPause": "自然に話してください",
	"StepByStep": "順番にｺﾏﾝﾄﾞを話してください",
	"TalkIntPrompt": "[ﾄｰｸﾎﾞﾀﾝ] でｶﾞｲﾀﾞﾝｽを省略",
	"TuneChnlName": "{XM Channel} を選局",
	"TuneFreq": "“ﾗｼﾞｵの周波数” を選局",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "音声認識の使い方",
	"TutorialTV": "TV",
	"USBAudio": "USBｵｰﾃﾞｨｵ",
	"XMRadio": "XM",
};

framework.registerAppDictLoaded("tutorial", "ja_JP");