var Localization_tutorialAppDict_da_DK = {
	//"stringId" : "localString"
	"AMRadio": "AM radio",
	"AdvancedVoice": "Avanceret stemme",
	"AdvancedVoiceTutorial": "4 Avanceret stemme vejledning",
	"Applications": "Applikationer",
	"AudioCtrlTutorial": "Audio",
	"AudioTutorial": "2 Audio vejledning",
	"BrowseContacts": "Gennemse kontakter",
	"BrowseSongs": "Gennemse sange",
	"CDPlayer": "CD-afspiller",
	"Call": "Ring op",
	"CallBack": "Ring tilbage (sidste indgåede opkald)",
	"CallName": "Ring til navn",
	"CombineVoice": "Kombinér stemmekommandoer",
	"Communications": "Kommunikation",
	"DialPad": "Tastatur",
	"Entertainment": "Underholdning",
	"FMRadio": "FM radio",
	"Favorites": "Favoritter ",
	"GeneralTutorial": "1 Generel vejledning",
	"GeneralVoiceCtrlTutorial": "Generel vejledning",
	"GoToEmail": "Gå til Email",
	"Help": "Hjælp",
	"MainMenu": "Hovedmenu",
	"MinimizeNoise": "Minimér støj (blæsere, vinduer)",
	"Navigation": "Navigering",
	"PhoneTutorial": "3 Telefon vejledning",
	"PhoneTutorialTitle": "Telefon",
	"PlayAlbum": "Afspil album",
	"PlayArtist": "Afspil kunstner",
	"RecentCalls": "Seneste opkald",
	"Redial": "Genopkald (sidste udgående opkald)",
	"Settings": "Indstillinger",
	"ShowMessage": "Vis besked",
	"SpeakAfterBeep": "Tal efter bippet",
	"SpeakAvoidPause": "Tal almindeligt, undgå pauser",
	"StepByStep": "Trin for trin",
	"TalkIntPrompt": "Taleknap afbryder stemmemeddelelser",
	"TuneChnlName": "Stil ind på XM-kanal navn",
	"TuneFreq": "Stil ind på FM- eller AM-frekvens",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Vælg vejledning",
	"TutorialTV": "TV",
	"USBAudio": "USB-audio",
	"XMRadio": "XM radio",
};

framework.registerAppDictLoaded("tutorial", "da_DK");