var Localization_tutorialAppDict_en_US = {
	//"stringId" : "localString"
	"AMRadio": "AM Radio",
	"AdvancedVoice": "Advanced Voice Tutorial",
	"AdvancedVoiceTutorial": "4 Advanced Voice Tutorial",
	"Applications": "Applications",
	"AudioCtrlTutorial": "Audio Tutorial",
	"AudioTutorial": "2 Audio Tutorial",
	"BrowseContacts": "Browse Contacts",
	"BrowseSongs": "Browse Songs",
	"CDPlayer": "CD Player",
	"Call": "Call",
	"CallBack": "Call Back (last incoming call)",
	"CallName": "Call \"name\"",
	"CombineVoice": "Combine Commands",
	"Communications": "Communication",
	"DialPad": "Dial Pad",
	"Entertainment": "Entertainment",
	"FMRadio": "FM Radio",
	"Favorites": "Favorites",
	"GeneralTutorial": "1 General Tutorial",
	"GeneralVoiceCtrlTutorial": "General Tutorial",
	"GoToEmail": "Go To Email",
	"Help": "Help",
	"MainMenu": "Main Menu",
	"MinimizeNoise": "Minimize Noise (vents, windows)",
	"Navigation": "Navigation",
	"PhoneTutorial": "3 Phone Tutorial",
	"PhoneTutorialTitle": "Phone Tutorial",
	"PlayAlbum": "Play Album",
	"PlayArtist": "Play Artist",
	"RecentCalls": "Recent Calls",
	"Redial": "Redial (last outgoing call)",
	"Settings": "Settings",
	"ShowMessage": "Show Message",
	"SpeakAfterBeep": "Speak After Beep",
	"SpeakAvoidPause": "Speak Naturally, Avoid Pauses",
	"StepByStep": "Step-by-Step",
	"TalkIntPrompt": "Interrupt Voice Prompts with Talk Button",
	"TuneChnlName": "Tune to XM \"channel name\"",
	"TuneFreq": "Tune to FM/AM \"frequency\"",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Select Tutorial by Line Number",
	"TutorialTV": "TV",
	"USBAudio": "USB Audio",
	"XMRadio": "XM Radio",
};

framework.registerAppDictLoaded("tutorial", "en_US");