var Localization_tutorialAppDict_pt_PT = {
	//"stringId" : "localString"
	"AMRadio": "Rádio AM",
	"AdvancedVoice": "Voz Avançada",
	"AdvancedVoiceTutorial": "4 Tutorial de Voz Avançado",
	"Applications": "Aplicações",
	"AudioCtrlTutorial": "Áudio",
	"AudioTutorial": "2 Tutorial de Áudio",
	"BrowseContacts": "Procurar Contactos",
	"BrowseSongs": "Procurar Músicas",
	"CDPlayer": "Leitor de CD",
	"Call": "Chamada",
	"CallBack": "Chamada de Retorno (última chamada recebida)",
	"CallName": "Nome de Chamada",
	"CombineVoice": "Combinar comandos de voz",
	"Communications": "Comunicações",
	"DialPad": "Teclado de Telefone",
	"Entertainment": "Entretenimento",
	"FMRadio": "Rádio FM",
	"Favorites": "Favoritos",
	"GeneralTutorial": "1 Tutorial Geral",
	"GeneralVoiceCtrlTutorial": "Tutorial Geral",
	"GoToEmail": "Ir para Correio Electrónico",
	"Help": "Ajuda",
	"MainMenu": "Menu Principal",
	"MinimizeNoise": "Reduzir o ruído (saídas de ar, janelas)",
	"Navigation": "Navegação",
	"PhoneTutorial": "3 Tutorial de Telefone",
	"PhoneTutorialTitle": "Telefone",
	"PlayAlbum": "Reproduzir Álbum",
	"PlayArtist": "Reproduzir Artista",
	"RecentCalls": "Chamadas Recentes",
	"Redial": "Remarcar (última chamada efectuada)",
	"Settings": "Definições",
	"ShowMessage": "Mostrar Mensagem",
	"SpeakAfterBeep": "Fale após o sinal",
	"SpeakAvoidPause": "Fale naturalmente, evite as pausas",
	"StepByStep": "Passo a passo",
	"TalkIntPrompt": "O botão Falar interrompe os comandos de voz",
	"TuneChnlName": "Sintonizar nome do canal XM",
	"TuneFreq": "Sintonizar frequência FM ou AM",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Seleccionar Tutorial",
	"TutorialTV": "TV",
	"USBAudio": "Áudio USB",
	"XMRadio": "Rádio XM",
};

framework.registerAppDictLoaded("tutorial", "pt_PT");