var Localization_tutorialAppDict_zh_CN = {
	//"stringId" : "localString"
	"AMRadio": "AM 收音机",
	"AdvancedVoice": "语音识别教程",
	"AdvancedVoiceTutorial": "4 语音识别教程",
	"Applications": "应用程序",
	"AudioCtrlTutorial": "音频",
	"AudioTutorial": "2 音频教程",
	"BrowseContacts": "浏览联系人",
	"BrowseSongs": "浏览歌曲",
	"CDPlayer": "CD播放器",
	"Call": "呼叫",
	"CallBack": "回拨（上次来电）",
	"CallName": "呼叫姓名",
	"CombineVoice": "结合语音命令",
	"Communications": "通讯",
	"DialPad": "拨号盘",
	"Entertainment": "娱乐",
	"FMRadio": "FM 收音机",
	"Favorites": "收藏夹",
	"GeneralTutorial": "1 一般语音教程",
	"GeneralVoiceCtrlTutorial": "一般语音教程",
	"GoToEmail": "转到电子邮件",
	"Help": "帮助",
	"MainMenu": "主菜单",
	"MinimizeNoise": "将噪音降至最低（通风口，车窗）",
	"Navigation": "导航",
	"PhoneTutorial": "3 电话教程",
	"PhoneTutorialTitle": "电话",
	"PlayAlbum": "播放唱片集",
	"PlayArtist": "播放艺术家",
	"RecentCalls": "最近呼叫",
	"Redial": "重拨（上次呼出电话）",
	"Settings": "设置",
	"ShowMessage": "显示消息",
	"SpeakAfterBeep": "听到提示音后说",
	"SpeakAvoidPause": "自然地说，避免停顿",
	"StepByStep": "逐步",
	"TalkIntPrompt": "讲话按钮打断语音提示",
	"TuneChnlName": "调至 XM 频道名称",
	"TuneFreq": "调至 FM 或 AM 频率",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "选择教程",
	"TutorialTV": "TV",
	"USBAudio": "USB音频",
	"XMRadio": "XM广播",
};

framework.registerAppDictLoaded("tutorial", "zh_CN");