var Localization_tutorialAppDict_ru_RU = {
	//"stringId" : "localString"
	"AMRadio": "Радио AM ",
	"AdvancedVoice": "Расширенное голосовое",
	"AdvancedVoiceTutorial": "4 Расшир. голосовое руководство",
	"Applications": "Приложения",
	"AudioCtrlTutorial": "Аудио",
	"AudioTutorial": "2 Руководство по аудиосистеме",
	"BrowseContacts": "Просмотр контактов",
	"BrowseSongs": "Просмотр песен",
	"CDPlayer": "CD-плеер",
	"Call": "Вызов",
	"CallBack": "Перезвонить (на послед. вход.)",
	"CallName": "Название вызова",
	"CombineVoice": "Комбинировать голосовые команды",
	"Communications": "Связь",
	"DialPad": "Клавиаткра набора",
	"Entertainment": "Развлечения",
	"FMRadio": "Радио FM ",
	"Favorites": "Избранное",
	"GeneralTutorial": "1 Общее руководство",
	"GeneralVoiceCtrlTutorial": "Общее руководство",
	"GoToEmail": "Перейти к эл. сообщ.",
	"Help": "Справка",
	"MainMenu": "Главное меню",
	"MinimizeNoise": "Снизить шум (вент.отв., окна)",
	"Navigation": "Навигация",
	"PhoneTutorial": "3 Руководство по эксплуатации тел.",
	"PhoneTutorialTitle": "Телефон",
	"PlayAlbum": "Воспроизвести альбом",
	"PlayArtist": "Воспроизвести исполнителя",
	"RecentCalls": "Недавние вызовы",
	"Redial": "Повторный набор (посл. исход.)",
	"Settings": "Настройки",
	"ShowMessage": "Показать сообщение",
	"SpeakAfterBeep": "Говорите после сигнала",
	"SpeakAvoidPause": "Говорите естественно, избегайте пауз",
	"StepByStep": "Поэтапно",
	"TalkIntPrompt": "Кнопка «Говорить» прерывает голосовые подсказки",
	"TuneChnlName": "Переключить на название канала XM ",
	"TuneFreq": "Переключить на частоту FM или AM ",
	"TutorialAUX": "AUX",
	"TutorialBluetooth": "Bluetooth",
	"TutorialSelection": "Выбрать руководство",
	"TutorialTV": "TB",
	"USBAudio": "USB-аудио",
	"XMRadio": "XM радио",
};

framework.registerAppDictLoaded("tutorial", "ru_RU");