var Localization_xmaudioAppDict_es_MX = {
	//"stringId" : "localString"
	"Add": "Añadir",
	"AddAsSmartFavorite": "Añadir {ChannelName} como un Favorito inteligente o un Favorito normal",
	"AddSmartFavoriteCnfm": "¿Está seguro que desea añadir {Favorite Channel Name} a Favoritos inteligentes?",
	"CallXM": "Llamar a XM",
	"ChangeCategory": "Cambiar categoría",
	"ChannelDescriptionService": "Servicio de descripción de canales",
	"ChannelList": "Lista de canales",
	"ChannelsUnlocked": "Canales desbloqueados para la sesión",
	"CheckXMAntenna": "Verificar Antena XM",
	"CheckXMTuner": "Verificar Sintonizador XM",
	"CitySelection": "Selección de ciudad",
	"CreateNewTuneMixChannel": "Crear nuevo canal de combinación de sintonizaciones",
	"DeleteSmartFavoriteCnfm": "¿Está seguro que desea eliminar {Smart Favorite Channel Name} de Favoritos?",
	"DeleteSmartFavoriteCnfm_2": "¿Está seguro que dese eliminar {Smart Favorite Channel Name} de Favoritos inteligentes? Se mantendrá como un favorito normal.",
	"DeleteTuneMixChannelCnfm": "¿Está seguro que desea eliminar {TuneMix Channel Name}?",
	"DisableAlerts": "Deshabilitar alertas",
	"Dismiss": "Ignorar",
	"EditPINCode": "Canales desbloqueados para la sesión",
	"EditSmartFavorite": "Editar Favorito inteligente",
	"EditTuneMixChannel": "Editar canal de combinación de sintonizaciones",
	"EnterDefaultPIN": "PIN incorrecto.  Intente de nuevo.",
	"EnterPIN": "Ingrese el PIN predeterminado",
	"EveryOtherReport": "Cada dos informes",
	"EveryReport": "Cada informe",
	"Favorite": "Favorito ",
	"LastAlert": "Última alerta",
	"Listen": "Escuchar  ",
	"ListenNow": "Escuchar ahora",
	"LoadingXM": "Cargando XM",
	"LockCurrentChannel": "Bloquear canal actual",
	"MLB": "MLB",
	"Move": "Mover",
	"NCAA(Football)": "NCAA (fútbol americano)",
	"NFL": "NFL",
	"NHL": "NHL",
	"NextAlert": "Siguiente alerta",
	"NoXMSignal": "No hay señal XM",
	"None": "Ninguno",
	"Only10TuneMixAllowed": "Solo se permiten 10 canales de combinación de sintonizaciones.",
	"OnlyFirstReport": "Solo primer informe después del inicio del vehículo",
	"OnlyFirstReportInGame": "Solo primer informe del juego",
	"PINCorrectCnfm": "¿Es correcto?",
	"PINReset": "Reinicio de PIN",
	"PINSet": "Reinicio de PIN",
	"ParentalLock": "Establezca un nuevo PIN",
	"ParentalLockPinSettings": "Configuración de PIN de bloqueo parental",
	"PlayingAlert": "Alerta de reproducción",
	"RadioID": "Identificación de radio: {Radio Serial Number}",
	"RemoveSmartFavorite": "Eliminar Favorito inteligente",
	"RemoveTuneMixChannel": "Eliminar canal de combinación de sintonizaciones",
	"ReportFrequency": "Frecuencia de informes",
	"ResetPINCode": "¿Es correcto?",
	"ReturnToPrevious": "Volver a anterior",
	"SelectAFavoriteTeam": "Seleccionar un equipo favorito",
	"SelectASport": "Seleccionar un deporte",
	"SelectCity": "Seleccionar una ciudad",
	"SelectPriorityPosition": "Seleccionar posición de prioridad",
	"SelectSettings": "Seleccione el icono de Configuración a continuación para desbloquear el canal/la sesión.",
	"SelectStationToEdit": "Seleccionar emisora para editar",
	"SelectStationToRemove": "Seleccionar emisora para eliminar",
	"SelectStationsForTuneMix": "Seleccionar emisoras para combinación de sintonizaciones",
	"SelectStationsToAdd": "Seleccionar emisoras para añadir combinación de sintonizaciones",
	"SelectTuneMixChannelToDelete": "Seleccionar canal de combinación de sintonizaciones para eliminar",
	"SelectTuneMixChannelToEdit": "Seleccionar canal de combinación de sintonizaciones para editar",
	"SessionLock": "Bloqueo de sesión",
	"SetNewPIN": "Establezca un nuevo PIN",
	"SmartFavorite": "Favorito inteligente ",
	"SmartFavoriteOptions": "Opciones de Favoritos inteligentes",
	"SmartFavorites": "Favoritos inteligentes",
	"SportSelection": "Selección de deporte",
	"SportsFlash": "Flash deportivo  ",
	"SportsFlashAvailable": "Flash deportivo {Alert Team} disponible",
	"SportsFlashPriority": "Prioridad del Flash deportivo",
	"SportsFlashSetup": "Configuración de Flash deportivo",
	"Traffic&WeatherNow": "Tráfico y Clima ahora",
	"Traffic&WeatherNowSetup": "Configuración de Tráfico y Clima ahora",
	"TrafficAndWeatherAvailable": "Tráfico y Clima para {alert city} disponibles. ",
	"TuneMixChannelCreated": "{TuneMix Channel Name} se creó",
	"TuneMixChannels": "Canales de combinación de sintonizaciones",
	"TuneMixChannelsList": "Lista de canales de combinación de sintonizaciones",
	"TuneScan": "Exploración de sintonización",
	"TuneStart": "Inicio de sintonización",
	"TurnAlertsOff": "Desactivar alertas",
	"UnableToSave": "No se puede guardar.  Favoritos inteligentes llenos.",
	"WrongPIN": "PIN incorrecto.  Intente de nuevo.",
	"XM": "XM",
	"XMChannelNotAuthorized": "Canal XM no autorizado",
	"XMChannelNotAvailable": "Canal XM no disponible",
	"XMChannelOffAir": "Canal XM fuera del aire",
	"XMSettings": "Configuración XM",
	"iTunesTagging": "Etiquetado iTunes",
};

framework.registerAppDictLoaded("xmaudio", "es_MX");