var Localization_ecoenergyAppDict_lv_LV = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Darbin. ilgums",
	"ApplicationsMenu": "Lietojumprogrammas",
	"Average": "Vidēji",
	"AverageFuelEconomy": "Vidēji (šajā brauc.)",
	"Back": "Atpakaļ",
	"CancelBtn": "Atcelt",
	"CelebrationMessage": "Apsveicam!",
	"ConfirmBtn": "Atiestatīt",
	"CummulativeFuelEconomy": "Vidēji (kopš atiestat.)",
	"CummulativeFuelEconomyReset": "Vid. degv. ekon. vēsture",
	"CurrentDriveFuelTitle": "Degv. ekon. (šis brauc.)",
	"CurrentStatus": "Pašr.",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV attālums",
	"EcoDriveStatus": "Eko braukš. statuss",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Nevar aktivizēt.",
	"ErrorBrake": "Pielietojiet lielāku bremžu spiedienu",
	"ErrorEngineRestart": "Motors ir jāiedarbina atkārtoti",
	"ErrorReady": "Sistēma gatava.",
	"ErrorShift": "Pārslēdziet uz neitrālo pārnesumu",
	"ErrorSteering": "Pagrieziet stūri uz centru",
	"ErrorUnknown": "i‑stop nav pieejams.",
	"HEVAverage": "Vidēji",
	"HEVThisDrive": "Šajā brauc.",
	"HidePanel": "Aizv.",
	"IgnitionOff": "Rādīt ekrānu, ja aizdedze izslēgta",
	"Km": "km",
	"LoadEEM": "Degvielas Patēriņš Ielādē",
	"LoadEEMHEV": "Diskdziņa monitors Ielādē",
	"Miles": "mi",
	"NotReady": "NAV GATAVS",
	"OneDrv": "Viena br.",
	"Ready": "GATAVS",
	"Reset": "Atiestatīt vidējo aprēķinu",
	"ResetConfirm": "Vai tiešām vēlaties atjaunot vidējais Degvielas Patēriņš?",
	"ResetUnsuccessful": "Neizdevās veikt atiestati. Vai mēģināt vēlreiz?",
	"RetryBtn": "Mēģināt vēlreiz",
	"SbnTitleId": "Degvielas Patēriņš",
	"SelectSettings": "Iestatījumi",
	"Settings": "Iestatījumi",
	"SettingsRetryMsg": "Nevar mainīt iestatījumu Sinhronizēt vidējo nobraukumu ar A nobraukumu",
	"SinceReset": "(kopš atiestat.)",
	"StopTimeTitle": "Stāvēš.",
	"SwitchView": "Nākamais ekrāns",
	"SyncTripA": "Sinhr. vid. nobr. ar A nobr.",
	"ThisDrive": " ",
	"TotalActive": "Darbin. Ilg.",
	"TotalTimeTitle": "Kop. laiks",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Kum. EV braukš. attāl.",
	"driveMonitor": "Diskdziņa monitors",
	"energyFlow": "Enerģijas plūsma",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop Efektivitātes ",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Viena brauciena EV attāl.",
};

framework.registerAppDictLoaded("ecoenergy", "lv_LV");