var Localization_ecoenergyAppDict_ar_SA = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "تنشيط الوقت",
	"ApplicationsMenu": "التطبيقات",
	"Average": "متوسط",
	"AverageFuelEconomy": "متوسط: هذه الرحلة",
	"Back": "رجوع",
	"CancelBtn": "إلغاء",
	"CelebrationMessage": "تهانينا!",
	"ConfirmBtn": "أعد ضبط",
	"CummulativeFuelEconomy": "متوسط (منذ إعادة الضبط)",
	"CummulativeFuelEconomyReset": "سجل متوسط اقتصاد الوقود",
	"CurrentDriveFuelTitle": "إقتصاد وقود (هذه الرحلة)",
	"CurrentStatus": "الحالي",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "مسافة EV",
	"EcoDriveStatus": "قيادة اقتصادية",
	"ElapsedTimeInMin": "د",
	"ErrorActivated": "لا يمكن التنشيط.",
	"ErrorBrake": "يرجى  زيادة الضغط على المكابح.",
	"ErrorEngineRestart": "يجب إعادة بدء تشغيل المحرك.",
	"ErrorReady": "جاهز.",
	"ErrorShift": "يرجى الانتقال إلى وضع محايد.",
	"ErrorSteering": "يرجى إدارة عجلة القيادة إلى المنتصف.",
	"ErrorUnknown": "خاصية i‑stop غير متاحة.",
	"HEVAverage": "متوسط",
	"HEVThisDrive": "هذه الرحلة",
	"HidePanel": "إخفاء الأزرار",
	"IgnitionOff": "عرض الشاشة عند إبطال المحرك",
	"Km": "كم",
	"LoadEEM": "إقتصاد وقود التحميل جارٍ",
	"LoadEEMHEV": "شاشة القيادة التحميل جارٍ",
	"Miles": "ميل",
	"NotReady": "غير جاهز",
	"OneDrv": "رحلة واحدة",
	"Ready": "جاهز",
	"Reset": "إعادة ضبط المتوسط",
	"ResetConfirm": "هل أنت بالتأكيد تريد إعادة ضبط متوسط اقتصاد الوقود؟",
	"ResetUnsuccessful": "لم تنجح إعادة الضبط. هل ترغب في إعادة المحاولة؟",
	"RetryBtn": "أعد المحاولة",
	"SbnTitleId": "إقتصاد وقود",
	"SelectSettings": "الإعدادات",
	"Settings": "الإعدادات",
	"SettingsRetryMsg": "لا يمكن تغيير إعداد متوسط المزامنة و الرحلة ا",
	"SinceReset": "(منذ إعادة الضبط)",
	"StopTimeTitle": "إيقاف الوقت",
	"SwitchView": "الشاشة التالية",
	"SyncTripA": "متوسط المزامنة و الرحلة ا",
	"ThisDrive": "(هذه الرحلة)",
	"TotalActive": "نشط الوقت",
	"TotalTimeTitle": "زمن كلي",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "مسافة قيادة EV التراكمية",
	"driveMonitor": "شاشة القيادة",
	"energyFlow": "تدفق الطاقة",
	"engineId": "ENGINE",
	"iStopBoost": "إجمالي متوسط ​​بالاستفادة من i‑stop",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (هذه الرحلة)",
	"kml": "كم/ل",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "مسافة EV لمحرك واحد",
};

framework.registerAppDictLoaded("ecoenergy", "ar_SA");