var Localization_ecoenergyAppDict_sk_SK = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Čas aktívny",
	"ApplicationsMenu": "Aplikácie",
	"Average": "Priemer",
	"AverageFuelEconomy": "Priem. (Te.o poh.)",
	"Back": "Späť",
	"CancelBtn": "Zrušiť",
	"CelebrationMessage": "Gratulujeme!",
	"ConfirmBtn": "Reset",
	"CummulativeFuelEconomy": "Priemer (od res.)",
	"CummulativeFuelEconomyReset": "História priem. spot. paliva",
	"CurrentDriveFuelTitle": "Úspora paliva",
	"CurrentStatus": "Aktuál.",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV vzdialenosť",
	"EcoDriveStatus": "Stav ekon. pohonu",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Nedá sa aktivovať.",
	"ErrorBrake": "Pribrzdite viac",
	"ErrorEngineRestart": "Motor je potrebné naštartovať znovu",
	"ErrorReady": "Hotovo.",
	"ErrorShift": "Zaraďte neutrál",
	"ErrorSteering": "Otočte volant do stredu ",
	"ErrorUnknown": "i‑stop nie je k dispozícii",
	"HEVAverage": "Priemer",
	"HEVThisDrive": "Táto jazda",
	"HidePanel": "Skryť tlačidlá",
	"IgnitionOff": "Zobraziť pri vypínaní zapalovania",
	"Km": "km",
	"LoadEEM": "Spotreba Paliva Nahráva sa",
	"LoadEEMHEV": "Monitor jazdy Nahráva sa",
	"Miles": "mi",
	"NotReady": "NEPRIPRAVENÉ",
	"OneDrv": "Jed. Prej.",
	"Ready": "PRIPRAVENÉ",
	"Reset": "Resetovat priemer",
	"ResetConfirm": "Naozaj chcete obnoviť  priemerná spotreba paliva?",
	"ResetUnsuccessful": "Resetovanie nebolo úspešné. Chcete pokus zopakovať?",
	"RetryBtn": "Zopakovať pokus",
	"SbnTitleId": "Spotreba Paliva",
	"SelectSettings": "Nastavenia",
	"Settings": "Nastavenia",
	"SettingsRetryMsg": "Synchr. priemer a trasa A Nastavenie nemožno zmeniť",
	"SinceReset": "od res.",
	"StopTimeTitle": "Čas zast",
	"SwitchView": "Ďalšia obrazovka",
	"SyncTripA": "Synchr. priemer a trasa A",
	"ThisDrive": " ",
	"TotalActive": "Čas aktívny",
	"TotalTimeTitle": "Čas cel.",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Kumul. prejd. vzdial. EV",
	"driveMonitor": "Monitor jazdy",
	"energyFlow": "Tok energie",
	"engineId": "ENGINE",
	"iStopBoost": "Celk. prínos i-stop, vzd.",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i-stop ON/Táto jazda",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Jednot. EV prejdená vzdialen.",
};

framework.registerAppDictLoaded("ecoenergy", "sk_SK");