var Localization_ecoenergyAppDict_et_EE = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Aeg aktiivne",
	"ApplicationsMenu": "Rakendused",
	"Average": "Keskmine",
	"AverageFuelEconomy": "Keskmine (sõit)",
	"Back": "Tagasi ",
	"CancelBtn": "Tühista",
	"CelebrationMessage": "Õnnitleme!",
	"ConfirmBtn": "Lähtesta ",
	"CummulativeFuelEconomy": "Keskmine",
	"CummulativeFuelEconomyReset": "Keskmise kütusekulu ajalugu",
	"CurrentDriveFuelTitle": "Kütusekulu (sõit)",
	"CurrentStatus": "Aktiivne",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV-kaugus",
	"EcoDriveStatus": "Ökosõidu olek",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Ei saa aktiveerida.",
	"ErrorBrake": "Vajutage rohkem pidurit.",
	"ErrorEngineRestart": "Mootor tuleb taaskäivitada",
	"ErrorReady": "Valmis.",
	"ErrorShift": "Võtke käik välja.",
	"ErrorSteering": "Keerake rool keskele.",
	"ErrorUnknown": "i‑stop pole saadaval.",
	"HEVAverage": "Keskmine",
	"HEVThisDrive": "See sõit",
	"HidePanel": "Peida nupud",
	"IgnitionOff": "Kuva ekraani, kui süüde väljas",
	"Km": "km",
	"LoadEEM": "Kütusekulu Laadimine",
	"LoadEEMHEV": "Keskmine Laadimine",
	"Miles": "mi",
	"NotReady": "POLE VALMIS",
	"OneDrv": "Ühe sõidu",
	"Ready": "VALMIS",
	"Reset": "Lähtesta keskmine",
	"ResetConfirm": "Kas olete veendunud, et tahate algseadistada keskmist kütusesäästu? ",
	"ResetUnsuccessful": "Lähtestamine ebaõnnestus. Kas proovida uuesti?",
	"RetryBtn": "Uuesti",
	"SbnTitleId": "Kütusekulu",
	"SelectSettings": "Sätted",
	"Settings": "Sätted",
	"SettingsRetryMsg": "Keskmise ja sõidu A sünkroonimise säte muutmine ebaõnnestus",
	"SinceReset": "(Kuna Reset)",
	"StopTimeTitle": "Aeg peatatud",
	"SwitchView": "Järgmine kuva",
	"SyncTripA": "Sünkrooni keskmine ja sõit A",
	"ThisDrive": "(see sõit)",
	"TotalActive": "Aeg akt.",
	"TotalTimeTitle": "Koguaeg",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Kumulatiivne EV-sõidukaugus",
	"driveMonitor": "Sõidu monitor",
	"energyFlow": "Energiavool",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop, Mille andnud",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (see sõit)",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Ühe sõidu EV-kaugus",
};

framework.registerAppDictLoaded("ecoenergy", "et_EE");