var Localization_ecoenergyAppDict_hu_HU = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Aktív idő",
	"ApplicationsMenu": "Alkalmazások",
	"Average": "Átlag",
	"AverageFuelEconomy": "Átlag(Jelen megh.)",
	"Back": "Vissza",
	"CancelBtn": "Mégse",
	"CelebrationMessage": "Gratulálunk!",
	"ConfirmBtn": "Visszaállítás",
	"CummulativeFuelEconomy": "Átlag (Reposi.)",
	"CummulativeFuelEconomyReset": "Átlagfogyasztás előzmények",
	"CurrentDriveFuelTitle": "Üa.-gazd.(Jelen meghajtás)",
	"CurrentStatus": "Aktuális",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV-távolsága",
	"EcoDriveStatus": "Eco drive állapota",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Nem lehet aktiválni.",
	"ErrorBrake": "Jobban nyomja meg a féket.",
	"ErrorEngineRestart": "A motort újra kell indítani",
	"ErrorReady": "Kész.",
	"ErrorShift": "Tegye üres állásba.",
	"ErrorSteering": "Fordítsa egyenesbe a kormánykereket. ",
	"ErrorUnknown": "i‑stop nem áll rendelkezésre.",
	"HEVAverage": "Átlag",
	"HEVThisDrive": "Jelen megh",
	"HidePanel": "Gombok elrejtése",
	"IgnitionOff": "Képernyő megj. levett gyújtásnál",
	"Km": "km",
	"LoadEEM": "Üzemanyagfogyasztás Betöltés",
	"LoadEEMHEV": "Menetciklus felügyelő Betöltés",
	"Miles": "mi",
	"NotReady": "NINCS KÉSZEN",
	"OneDrv": "Eg. Vez.",
	"Ready": "KÉSZ",
	"Reset": "Átlag alaphelyzetbe állítása",
	"ResetConfirm": "Biztosan szeretné visszaállítani az átlagos üzemanyag-fogyasztást?",
	"ResetUnsuccessful": "Sikertelen visszaállítás. Újrapróbálkozik?",
	"RetryBtn": "Újrapróbálkozás",
	"SbnTitleId": "Üzemanyagfogyasztás",
	"SelectSettings": "Beállítások",
	"Settings": "Beállítások",
	"SettingsRetryMsg": "Nem módosíthatók a szink. átlag és A út beállítások",
	"SinceReset": "(Reposi.)",
	"StopTimeTitle": "Leállított idő",
	"SwitchView": "Következő képernyő",
	"SyncTripA": "Szink. átlag és A út",
	"ThisDrive": "(Desta Vez)",
	"TotalActive": "Összes Akt",
	"TotalTimeTitle": "Összes idő",
	"Wh": "Watt",
	"batteryId": "BATTERY",
	"cumulativeEV": "Halm. EV vezetési távolság",
	"driveMonitor": "Menetciklus felügyelő",
	"energyFlow": "Energia áramlás",
	"engineId": "ENGINE",
	"iStopBoost": "Teljes tartomány i‑stop",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Egyszeri vezetés EV-távolsága",
};

framework.registerAppDictLoaded("ecoenergy", "hu_HU");