var Localization_ecoenergyAppDict_pt_PT = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Tempo Activo",
	"ApplicationsMenu": "Aplicações",
	"Average": "Média",
	"AverageFuelEconomy": "Méd. (Desta Vez)",
	"Back": "Voltar",
	"CancelBtn": "Cancelar",
	"CelebrationMessage": "Parabéns!",
	"ConfirmBtn": "Repor",
	"CummulativeFuelEconomy": "Média Reposi.",
	"CummulativeFuelEconomyReset": "Hist. Poup. Méd. Combu.",
	"CurrentDriveFuelTitle": "Poup. Total (Desta Vez)",
	"CurrentStatus": "Actual",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "Distância EV",
	"EcoDriveStatus": "Estado Eco Drive",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Não é possível activar.",
	"ErrorBrake": "Aplique mais pressão no travão.",
	"ErrorEngineRestart": "É necessário reiniciar o motor",
	"ErrorReady": "Pronto.",
	"ErrorShift": "Mude para ponto morto.",
	"ErrorSteering": "Rode o volante para o centro.",
	"ErrorUnknown": "i‑stop não está disponível.",
	"HEVAverage": "Média",
	"HEVThisDrive": "Esta Viag.",
	"HidePanel": "Ocultar Botões",
	"IgnitionOff": "Mostr. Ecrã com Ignição Deslig.",
	"Km": "km",
	"LoadEEM": "Poupança Combustível A carregar",
	"LoadEEMHEV": "Monitor de Condução A carregar",
	"Miles": "mi",
	"NotReady": "NÃO PRONTO",
	"OneDrv": "Conduç.",
	"Ready": "PREPARADO",
	"Reset": "Repor Média",
	"ResetConfirm": "Tem a certeza que pretende repor a poupança média de combustível?",
	"ResetUnsuccessful": "A reposição foi bem sucedida. Pretende tentar novamente?",
	"RetryBtn": "Tentar Novamente",
	"SbnTitleId": "Poupança Combustível",
	"SelectSettings": "Definições",
	"Settings": "Definições",
	"SettingsRetryMsg": "Nâo Foi Possível Alterar a Definição de Sincronizar Média e Viagem A",
	"SinceReset": "Reposi.",
	"StopTimeTitle": "Parado",
	"SwitchView": "Ecrã Seguinte",
	"SyncTripA": "Sincronizar Média e Viagem A",
	"ThisDrive": "Desta Vez",
	"TotalActive": "T. Activo",
	"TotalTimeTitle": "Total",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Dist. Cond. EV Acum.",
	"driveMonitor": "Monitor de Condução",
	"energyFlow": "Fluxo de Energia",
	"engineId": "ENGINE",
	"iStopBoost": "Aumento de Alcance por i‑stop",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (Desta Vez)",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Distân. EV de Uma Conduç.",
};

framework.registerAppDictLoaded("ecoenergy", "pt_PT");