var Localization_ecoenergyAppDict_cs_CS = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Aktivní stav",
	"ApplicationsMenu": "Aplikace",
	"Average": "Průměr",
	"AverageFuelEconomy": "Průměr (za tuto jízdu)",
	"Back": "Zpět",
	"CancelBtn": "Zrušit",
	"CelebrationMessage": "Gratulujeme",
	"ConfirmBtn": "Restartovat",
	"CummulativeFuelEconomy": "Průměr (Od resetu)",
	"CummulativeFuelEconomyReset": "Prům. dlouhodobá spotřeba",
	"CurrentDriveFuelTitle": "Spotřeba (tato jízda)",
	"CurrentStatus": "Aktuální",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "Jedna jízda",
	"EcoDriveStatus": "Ekojízda",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Nemůže být aktivován.",
	"ErrorBrake": "Prosím, použijte větší brzdný tlak.",
	"ErrorEngineRestart": "Motor je třeba znovu nastartovat.",
	"ErrorReady": "Připraven.",
	"ErrorShift": "Prosím, zařaďte neutrál",
	"ErrorSteering": "Prosím, otočte volantem do středu",
	"ErrorUnknown": "i‑stop není dostupný.",
	"HEVAverage": "Průměr",
	"HEVThisDrive": "Tato jízda",
	"HidePanel": "Skrýt tlačítka",
	"IgnitionOff": "Obr.zap.při vyp. motoru",
	"Km": "km",
	"LoadEEM": "Spotřeba Paliva Načítání",
	"LoadEEMHEV": "Monitor jízdy Načítání",
	"Miles": "mi",
	"NotReady": "NEPŘIPRAVEN",
	"OneDrv": "Jednotlivá",
	"Ready": "PŘIPRAVEN",
	"Reset": "Resetovat průměrnou spotřebu",
	"ResetConfirm": "Opravdu chcete restartovat průměrnou ekonomickou spotřebu?",
	"ResetUnsuccessful": "Vynulování se nezdařilo. Zkusit znovu?",
	"RetryBtn": "Zkusit znovu",
	"SbnTitleId": "Spotřeba Paliva",
	"SelectSettings": "Nastavení",
	"Settings": "Nastavení",
	"SettingsRetryMsg": "Nastavení synchro průměru a denní spotřeby A nelze měnit",
	"SinceReset": "(Od resetu)",
	"StopTimeTitle": "Celá jízda",
	"SwitchView": "Následující zobrazení",
	"SyncTripA": "Sync průměr a denní spotřeba A",
	"ThisDrive": " ",
	"TotalActive": "Aktivní st.",
	"TotalTimeTitle": "Čas celk.",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Kumulat. EV ujetá vzdálenost",
	"driveMonitor": "Monitor jízdy",
	"energyFlow": "Tok Energie",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop, Rozsah Povzbuzováno",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (za tuto jízdu)",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Jednotlivá EV ujetá vzdálenost",
};

framework.registerAppDictLoaded("ecoenergy", "cs_CS");