var Localization_ecoenergyAppDict_zh_CN = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "活动时间",
	"ApplicationsMenu": "应用程序",
	"Average": "平均",
	"AverageFuelEconomy": "平均（本次驾驶）",
	"Back": "返回",
	"CancelBtn": "取消",
	"CelebrationMessage": "祝贺！",
	"ConfirmBtn": "复位",
	"CummulativeFuelEconomy": "平均（自复位）",
	"CummulativeFuelEconomyReset": "平均燃油经济性历史",
	"CurrentDriveFuelTitle": "燃油经济性（本次驾驶）",
	"CurrentStatus": "当前",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV 距离",
	"EcoDriveStatus": "经济驾驶状态",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "无法激活。",
	"ErrorBrake": "请应用更多制动压力。",
	"ErrorEngineRestart": "发动机需要重启",
	"ErrorReady": "准备好。",
	"ErrorShift": "请换到空档。",
	"ErrorSteering": "请将方向盘转到中心。",
	"ErrorUnknown": "i‑stop 不可用。",
	"HEVAverage": "平均",
	"HEVThisDrive": "此行程",
	"HidePanel": "隐藏按钮",
	"IgnitionOff": "熄火时显示屏幕",
	"Km": "公里",
	"LoadEEM": "燃油经济性 [监测器] 正在加载",
	"LoadEEMHEV": "驾驶显示器正在加载",
	"Miles": "英里",
	"NotReady": "未准备好",
	"OneDrv": "一次行驶",
	"Ready": "准备好",
	"Reset": "复位平均",
	"ResetConfirm": "您确定要复位平均燃油经济吗？",
	"ResetUnsuccessful": "复位失败。您是否希望重试？",
	"RetryBtn": "重试",
	"SbnTitleId": "燃油经济性 [监测器]",
	"SelectSettings": "设置",
	"Settings": "设置",
	"SettingsRetryMsg": "无法修改同步平均和里程 A 设置",
	"SinceReset": "（自复位）",
	"StopTimeTitle": "停止时间",
	"SwitchView": "下一屏幕",
	"SyncTripA": "同步平均和里程 A",
	"ThisDrive": "(此驾驶)",
	"TotalActive": "活动时间",
	"TotalTimeTitle": "总时间",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "累计 EV 行驶距离",
	"driveMonitor": "驾驶显示器",
	"energyFlow": "能量流",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop 增加的总行程",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON（本次驾驶）",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "一次行驶 EV 距离",
};

framework.registerAppDictLoaded("ecoenergy", "zh_CN");