var Localization_ecoenergyAppDict_sv_SE = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Tid Aktiv",
	"ApplicationsMenu": "Program",
	"Average": "Snitt",
	"AverageFuelEconomy": "Snitt (Körn)",
	"Back": "Bakåt",
	"CancelBtn": "Avbryt",
	"CelebrationMessage": "Gratulerar!",
	"ConfirmBtn": "Återst",
	"CummulativeFuelEconomy": "Snitt (Eft 0)",
	"CummulativeFuelEconomyReset": "Snittförbr (Hist)",
	"CurrentDriveFuelTitle": "Förbr (Denna Körn)",
	"CurrentStatus": "Aktuell",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV-sträcka",
	"EcoDriveStatus": "Ekokörning",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Kan inte aktiveras.",
	"ErrorBrake": "Tryck hårdare på bromsen.",
	"ErrorEngineRestart": "Motorn behöver startas om",
	"ErrorReady": "Klar.",
	"ErrorShift": "Lägg växeln i neutral.",
	"ErrorSteering": "Vrid ratten till rakt fram.",
	"ErrorUnknown": "i‑stop är inte tillgängligt.",
	"HEVAverage": "Medel",
	"HEVThisDrive": "Körningen",
	"HidePanel": "Dölj knappar",
	"IgnitionOff": "Visa skärm när tändning av",
	"Km": "km",
	"LoadEEM": "Bränsleförbrukning Laddar",
	"LoadEEMHEV": "Körkontroll Laddar",
	"Miles": "mi",
	"NotReady": "INTE KLAR",
	"OneDrv": "En gång",
	"Ready": "KLAR",
	"Reset": "Nollställ Snitt",
	"ResetConfirm": "Är du säker på att du vill ställa tillbaka till genomsnittlig bränsleförbrukning?",
	"ResetUnsuccessful": "Återställning misslyckades. Vill du prova igen?",
	"RetryBtn": "Prova igen",
	"SbnTitleId": "Bränsleförbrukning",
	"SelectSettings": "Inställningar",
	"Settings": "Inställningar",
	"SettingsRetryMsg": "Synkronisera Snitt och Trip A-inställning kunde inte ändras",
	"SinceReset": "Eft 0",
	"StopTimeTitle": "Stoppad",
	"SwitchView": "Nästa Skärm",
	"SyncTripA": "Synka Snitt och Trip A",
	"ThisDrive": " ",
	"TotalActive": "Tid Aktiv",
	"TotalTimeTitle": "Total Tid",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Ackum. EV-körsträcka",
	"driveMonitor": "Körkontroll",
	"energyFlow": "Energiflöde",
	"engineId": "ENGINE",
	"iStopBoost": "Räckvidd tack vare i‑stop",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Enstaka EV-sträcka",
};

framework.registerAppDictLoaded("ecoenergy", "sv_SE");