var Localization_ecoenergyAppDict_id_ID = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Waktu Aktif",
	"ApplicationsMenu": "Aplikasi",
	"Average": "Rata-rata",
	"AverageFuelEconomy": "Rata-rata",
	"Back": "Kembali",
	"CancelBtn": "Batal",
	"CelebrationMessage": "Selamat!",
	"ConfirmBtn": "Setel Ulang",
	"CummulativeFuelEconomy": "Rata-rata (Sjk Reset)",
	"CummulativeFuelEconomyReset": "Riwayat Rata2 Keiritan BBM",
	"CurrentDriveFuelTitle": "Kehematan Bakar",
	"CurrentStatus": "Saat ini",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "Jarak EV",
	"EcoDriveStatus": "Status Eco Drive",
	"ElapsedTimeInMin": "m",
	"ErrorActivated": "Tidak dapat diaktifkan.",
	"ErrorBrake": "Mohon tambahkan tekanan pedal rem",
	"ErrorEngineRestart": "Mesin perlu dihidupkan kembali",
	"ErrorReady": "Siap.",
	"ErrorShift": "Mohon pindahkan ke netral",
	"ErrorSteering": "Mohon putar kemudi ke arah lurus",
	"ErrorUnknown": "i‑stop tidak tersedia.",
	"HEVAverage": "Rata-rata",
	"HEVThisDrive": "Driving ini",
	"HidePanel": "Menu Aplikasi",
	"IgnitionOff": "Layar Hidup saat Kontak Mati",
	"Km": "km",
	"LoadEEM": "Kehematan Bakar Memuat Data",
	"LoadEEMHEV": "Pemantau Perjalanan Memuat Data",
	"Miles": "mi",
	"NotReady": "TIDAK SIAP",
	"OneDrv": "Satu Drive",
	"Ready": "SIAP",
	"Reset": "Setel Ulang Rata-rata",
	"ResetConfirm": "Anda yakin ingin set ulang riwayat rata2x kehematan BBM?",
	"ResetUnsuccessful": "Setel ulang gagal. Apakah Anda ingin mencoba lagi?",
	"RetryBtn": "Coba Lagi",
	"SbnTitleId": "Kehematan Bakar",
	"SelectSettings": "Setelan",
	"Settings": "Setelan",
	"SettingsRetryMsg": "Setelan Sinkronisasi Rata2 dan Trip A Tidak Dapat Diubah",
	"SinceReset": "(Sjk Reset)",
	"StopTimeTitle": "Saat Berhenti",
	"SwitchView": "Layar Selanjutnya",
	"SyncTripA": "Sinkronisasi Rata2 dan Trip A",
	"ThisDrive": "(Perjlnan Ini)",
	"TotalActive": "Wkt Aktif",
	"TotalTimeTitle": "Total",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Jrk Berkendara EV Kum.",
	"driveMonitor": "Pemantau Perjalanan",
	"energyFlow": "Arus Energi",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop Jarak Ditambah",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Jarak Berkendara EV Skrg",
};

framework.registerAppDictLoaded("ecoenergy", "id_ID");