var Localization_ecoenergyAppDict_el_GR = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Ενερ. χρόνος",
	"ApplicationsMenu": "Εφαρμογές",
	"Average": "Μέσος",
	"AverageFuelEconomy": "Μέση τιμή (τρέχον)",
	"Back": "Επιστροφή",
	"CancelBtn": "Ακύρωση",
	"CelebrationMessage": "Συγχαρητήρια!",
	"ConfirmBtn": "Επαναφορά",
	"CummulativeFuelEconomy": "Μέσος",
	"CummulativeFuelEconomyReset": "Ιστ. μέσης εξοικ. καυσίμων",
	"CurrentDriveFuelTitle": "Εξοικ. καυσίμων (τρέχον)",
	"CurrentStatus": "Τώρα",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "Απόσταση EV",
	"EcoDriveStatus": "Κατάσταση Eco Drive",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Δεν μπορεί να ενεργοποιηθεί.",
	"ErrorBrake": "Εφαρμόστε πίεση στα φρένα.",
	"ErrorEngineRestart": "Πρέπει να γίνει επανεκκίνηση του κινητήρα",
	"ErrorReady": "Έτοιμο.",
	"ErrorShift": "Βάλτε νεκρά.",
	"ErrorSteering": "Γυρίστε το τιμόνι στο κέντρο.",
	"ErrorUnknown": "Το i‑stop δεν είναι διαθέσιμο.",
	"HEVAverage": "Μέσος",
	"HEVThisDrive": "Τρέχο. οδή.",
	"HidePanel": "Απόκρυψη κουμπιών",
	"IgnitionOff": "Οθονη εκκιν. Ανενεργή",
	"Km": "km",
	"LoadEEM": "οικονομία καυσίμου Γίνεται φόρτωση",
	"LoadEEMHEV": "Παρακολούθηση οδήγησης Γίνεται φόρτωση",
	"Miles": "mi",
	"NotReady": "ΑΝΕΤΟΙΜΟ",
	"OneDrv": "Οδή. Μίας",
	"Ready": "ΕΤΟΙΜΟ",
	"Reset": "Επαναφορά μέσου όρου",
	"ResetConfirm": "Είστε βέβαιοι ότι θέλετε να επαναφέρετε τη μέση οικονομία καυσίμου;",
	"ResetUnsuccessful": "Η επαναφορά ήταν ανεπιτυχής. Θέλετε να δοκιμάσετε ξανά;",
	"RetryBtn": "Δοκιμάστε ξανά",
	"SbnTitleId": "οικονομία καυσίμου",
	"SelectSettings": "Ρυθμίσεις",
	"Settings": "Ρυθμίσεις",
	"SettingsRetryMsg": "συγχρονισμού μέσου όρου και Διαδρομής Α",
	"SinceReset": "(Από επαν.)",
	"StopTimeTitle": "Χρ. διακ.",
	"SwitchView": "Επόμενη οθόνη",
	"SyncTripA": "Συγχρ. μέσ. όρου και Διαδρ. Α",
	"ThisDrive": "(Τρέχον)",
	"TotalActive": "Εν. Χρόνος",
	"TotalTimeTitle": "Συν. χρ.",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Αθρ. απόσταση οδήγησης EV",
	"driveMonitor": "Παρακολούθηση οδήγησης",
	"energyFlow": "Ροή ενέργειας",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop εύρος ενίσχυσε",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (τρέχον)",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Από. EV οδήγ. μίας φοράς",
};

framework.registerAppDictLoaded("ecoenergy", "el_GR");