var Localization_ecoenergyAppDict_ru_RU = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Время работы",
	"ApplicationsMenu": "Приложения",
	"Average": "Ср.расх.",
	"AverageFuelEconomy": "Средн. (тек.поездка)",
	"Back": "Назад",
	"CancelBtn": "Отменить",
	"CelebrationMessage": "Поздравляем!",
	"ConfirmBtn": "Сбросить",
	"CummulativeFuelEconomy": "Ср.расх.",
	"CummulativeFuelEconomyReset": "История средн.эк.топлива",
	"CurrentDriveFuelTitle": "Эк.топлива (тек.поездка)",
	"CurrentStatus": "Текущ.",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "EV Расстояние",
	"EcoDriveStatus": "Статус Eco Drive",
	"ElapsedTimeInMin": "мин",
	"ErrorActivated": "Невозможно активировать.",
	"ErrorBrake": "Сильнее нажмите на педаль тормоза.",
	"ErrorEngineRestart": "Необходимо перезапустить двигатель",
	"ErrorReady": "Готово.",
	"ErrorShift": "Включите нейтраль.",
	"ErrorSteering": "Поверните руль в центр. положение.",
	"ErrorUnknown": "Система i‑stop не функционирует.",
	"HEVAverage": "Средний",
	"HEVThisDrive": "Этот диск",
	"HidePanel": "Скрыть кнопки",
	"IgnitionOff": "Показ. экр. при выкл. заж.",
	"Km": "км",
	"LoadEEM": "Экономия топлива Загрузка",
	"LoadEEMHEV": "Мониторинг диска Загрузка",
	"Miles": "ми",
	"NotReady": "НЕ ГОТОВО",
	"OneDrv": "1 поездка",
	"Ready": "ГОТОВО",
	"Reset": "Сбросить среднее",
	"ResetConfirm": "Вы уверены, что хотите сбросить показания о среднем объеме сэкономленного топлива?",
	"ResetUnsuccessful": "Сброс был неудачным. Вы хотите снова повторить?",
	"RetryBtn": "Повтор",
	"SbnTitleId": "Экономия топлива",
	"SelectSettings": "Настройки",
	"Settings": "Настройки",
	"SettingsRetryMsg": "Настройка \"Синхр. средн. и путь А\" невозможно изменить",
	"SinceReset": "(с мом. сброс)",
	"StopTimeTitle": "Время остан.",
	"SwitchView": "Следующий экран",
	"SyncTripA": "Синхр. средн. и путь А",
	"ThisDrive": " ",
	"TotalActive": "Время акт",
	"TotalTimeTitle": "Общ. вр.",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Сумм. расст. поезд. EV",
	"driveMonitor": "Мониторинг диска",
	"energyFlow": "Поток энергии",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop, диапазон повышенный",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (данная езда)",
	"kml": "км/л",
	"lkm": "л/100км",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Расст. поезд. EV",
};

framework.registerAppDictLoaded("ecoenergy", "ru_RU");