var Localization_ecoenergyAppDict_fr_CN = {
	//"stringId" : "localString"
	"ActuationTimeTitle": "Temps actif",
	"ApplicationsMenu": "Applications",
	"Average": "Moyenne",
	"AverageFuelEconomy": "Moyenne (ce trajet)",
	"Back": "Retour",
	"CancelBtn": "Annuler",
	"CelebrationMessage": "Félicitations !",
	"ConfirmBtn": "Réinitialiser",
	"CummulativeFuelEconomy": "Moyenne",
	"CummulativeFuelEconomyReset": "Hist conso carburant moy",
	"CurrentDriveFuelTitle": "Conso carburant (trajet)",
	"CurrentStatus": "Actuelle",
	"DPFissue2": "JAPAN ONLY",
	"EVDistn": "Distance EV",
	"EcoDriveStatus": "Conduite éco",
	"ElapsedTimeInMin": "min",
	"ErrorActivated": "Impossible d’activer.",
	"ErrorBrake": "Appuyer plus fortement sur les freins.",
	"ErrorEngineRestart": "Le moteur doit être redémarré",
	"ErrorReady": "Prêt.",
	"ErrorShift": "Veuillez passer au point mort.",
	"ErrorSteering": "Veuillez recentrer le volant.",
	"ErrorUnknown": "i‑stop n’est pas disponible.",
	"HEVAverage": "Moyenne",
	"HEVThisDrive": "Ce trajet",
	"HidePanel": "Masquer les touches",
	"IgnitionOff": "Afficher écran à l’arrêt moteur",
	"Km": "km",
	"LoadEEM": "Consommation En cours de chargement",
	"LoadEEMHEV": "Asst de conduite cours de chargement",
	"Miles": "mi",
	"NotReady": "PAS PRÊT",
	"OneDrv": "Trajet",
	"Ready": "PRÊT",
	"Reset": "Réinitialiser la moyenne",
	"ResetConfirm": "Êtes-vous certain de vouloir réinitialiser l'économie moyenne de carburant?",
	"ResetUnsuccessful": "Échec de la réinitialisation Voulez-vous réessayer ?",
	"RetryBtn": "Réessayer",
	"SbnTitleId": "Consommation",
	"SelectSettings": "Paramètres",
	"Settings": "Paramètres",
	"SettingsRetryMsg": "Moyenne sync et trajet A n’ont pu être modifiés",
	"SinceReset": "(depuis réinit)",
	"StopTimeTitle": "Temps arrêté",
	"SwitchView": "Écran suivant",
	"SyncTripA": "Moyenne sync et trajet A",
	"ThisDrive": "(Ce tajet)",
	"TotalActive": "Temps actif",
	"TotalTimeTitle": "Durée tot",
	"Wh": "Wh",
	"batteryId": "BATTERY",
	"cumulativeEV": "Dist. conduite EV cum.",
	"driveMonitor": "Assistant de conduite",
	"energyFlow": "Flux d’énergie",
	"engineId": "ENGINE",
	"iStopBoost": "i‑stop Autonomie Boostée ",
	"iStopOn": "i‑stop ON",
	"iStopOnTitle": "% i‑stop ON (ce trajet)",
	"kml": "km/L",
	"lkm": "L/100km",
	"motorId": "MOTOR",
	"mpg": "mpg",
	"oneDriveEV": "Distance EV pour un trajet",
};

framework.registerAppDictLoaded("ecoenergy", "fr_CN");