var Localization_pandoraAppDict_no_NO = {
	//"stringId" : "localString"
	"AZ": "A–Å",
	"AddBookmark_Alert": "Legge til bokmerke",
	"AddGenreStation": "Legg til: {genreStation}",
	"AddStation": "Legg til stasjon",
	"AddStationOption": "Opprette en ny stasjon:",
	"AddStationOptionButton3": "Artist",
	"AddingFavorites": "Legger stasjon til Favoritter",
	"AddingStation": "Legger til stasjon",
	"BluetoothAudioLost": "Lydtilkobling tapt, Bluetooth",
	"Bookmark": "Pandora bokmerkealternativ",
	"BookmarkAlreadyAdded": "Bokmerke fantes allerede",
	"BookmarkArtist": "Bokmerke, artist",
	"BookmarkSong": "Bokmerke, sang",
	"Buffering": "Bufrer",
	"ConnectionLost1": "Forbindelsen er brutt",
	"ConnectionLost2": "Sørg for at dataforbindelsen på den mobile enheten fungerer slik den skal.",
	"Date": "Dato",
	"DeleteFavorites": "Fjerner stasjon fra Favoritter",
	"FavoritesLimitReached": "Favoritter full",
	"FromCurrentArtist": "Fra nåværende artist",
	"FromCurrentSong": "Fra nåværende sang",
	"InsufficientConnectivity": "Utilstrekkelig forbindelse til å åpne Pandora.",
	"InsufficientConnectivity_Alert": "Utilstrekkelig forbindelse",
	"InvalidLogin1": "Ugyldig innlogging",
	"InvalidLogin2": "Autentisering mislyktes.",
	"LicensingRestriction1": "Lisensbegrensninger",
	"LicensingRestriction2": "Pandora er ikke tilgjengelig utenfor USA.",
	"LicensingRestrictions_Alert": "Lisensrestriksjoner",
	"Loading": "Vennligst legg til stasjon.",
	"MobileDevice1": "Feil ved mobil enhet",
	"MobileDevice2": "Sørg for at alt fungere slik det skal for den mobile enheten.",
	"NoBookmark_Alert": "Kan ikke legge til bokm.",
	"NoCurrentStation": "Stasjon fjernet",
	"NoDeviceConnected": "Ingen enheter koblet til",
	"NoFavoritesStationsCreated": "Ingen favorittstasjoner opprettet.",
	"NoPandora1": "Kan ikke finne Pandora",
	"NoPandora2": "Sjekk at Pandora-programmet er installert på den mobile enheten.",
	"NoRating_Alert": "Kan ikke legge til rang.",
	"NoStationFound1": "Fant ingen stasjoner",
	"NoStationFound2": "Du må ha minst én Pandora-stasjon satt opp først.",
	"Nostationsadded": "Ingen stasjoner lagt til.",
	"NotSupportedVersion1": "Oppgrader Pandora-versjonen på den mobile enheten.",
	"OverLimit": "Beklager, våre musikklisenser tvinger oss til å begrense antallet sanger du kan hoppe over.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Legge til/Endre Pandora-favoritter",
	"PandoraDeleteConfirmation": "Er du sikker på at du vil slette favoritten {name}?",
	"PandoraFavorites": "Pandora-favoritter",
	"PandoraFavoritesAvailable": "Pandora-favoritt allerede tilgjengelig",
	"PandoraFavoritesConfirm": "Vil du bytte ut én?",
	"PandoraFavoritesDelete": "Velg Pandora-favoritt som skal slettes",
	"PandoraFavoritesMax": "Du har nådd maksimum antall Pandora-favoritter.",
	"PandoraFavoritesMove": "Velg Pandora-favoritt som skal flyttes",
	"PandoraFavoritesReplace": "Bytt ut med {active station}",
	"PandoraFavoritesSelect": "Velg Pandora-favoritt som skal byttes ut",
	"PandoraMaintinence": "Beklager, Pandora blir for tiden vedlikeholdt.",
	"PandoraMoveFavorite": "Flytt",
	"PandoraReplaceButtonText": "Bytt",
	"PandoraSelectPosition": "Velg posisjon",
	"Quit": "Avslutt",
	"SelectStation": "Forrige spillestasjon ble fjernet",
	"Setup": "Oppsett",
	"SetupBluetoothDeviceNow": "Sette opp Bluetooth-enhet nå?",
	"Shuffle": "Miks",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Sorter etter",
	"SortByAZ": "Sorter etter: A–Å",
	"SortByDate": "Sorter etter: Dato",
	"StationCreationError": "Det oppstod en feil ved oppretting av stasjon.",
	"StationLimitRecahed": "Stasjon-liste full",
	"StationList": "Stasjonsliste",
	"StationListTab": "Favoritter",
	"ThumbsDown": "Tommelen ned",
	"ThumbsUp": "Tommelen opp",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Underholdningsmeny",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Kan ikke legge til bokmerke",
	"sbnConnectionError": "Nettverksforbindelsen er brutt",
	"sbnConnectivityError": "Utilstrekkelig forbindelse",
	"sbnMobileDeviceError": "Feil ved mobil enhet",
	"sbnOverLimit": "Overhoppgrensen er nådd",
	"sbnPandoraMaintErr": "Vedlikeholdsfeil, Pandora",
	"sbnRatingFailed": "Kan ikke legge til rangering",
	"sbnStationDeleted": "Ingen nåværende stasjoner",
	"skip_Tooltip": "Hopp over",
};

framework.registerAppDictLoaded("pandora", "no_NO");