var Localization_pandoraAppDict_el_GR = {
	//"stringId" : "localString"
	"AZ": "A-Ω",
	"AddBookmark_Alert": "Προσθήκη σελιδοδείκτη",
	"AddGenreStation": "Προσθ. σταθμ: {genreStation}",
	"AddStation": "Προσθέστε σταθμό ",
	"AddStationOption": "Δημιουργία Νέου Σταθμού",
	"AddStationOptionButton3": "Καλλιτέχνης",
	"AddingFavorites": "Προσθήκη σταθμού στα Αγαπημένα",
	"AddingStation": "Προσθήκη σταθμού",
	"BluetoothAudioLost": "Απώλεια σύνδεσης ήχου Bluetooth",
	"Bookmark": "Επιλογή σελιδοδείκτη Pandora",
	"BookmarkAlreadyAdded": "Ο σελιδοδείκτης ήδη προστέθηκε. ",
	"BookmarkArtist": "Προσθήκη σελιδ. για καλλιτέχνη",
	"BookmarkSong": "Προσθήκη σελιδ. για τραγούδι",
	"Buffering": "Ενδιάμεση μνήμη",
	"ConnectionLost1": "Απώλεια σύνδεσης",
	"ConnectionLost2": "Βεβαιωθείτε ότι η σύνδεση δεδομένων στην κινητή συσκευή σας λειτουργεί κανονικά",
	"Date": "Ημερομηνία",
	"DeleteFavorites": "Αφαίρεση σταθμού από τα Αγαπημένα",
	"FavoritesLimitReached": "Εξαντλήθηκε όριο Αγαπ.",
	"FromCurrentArtist": "Από τον τρέχοντα καλλιτέχνη",
	"FromCurrentSong": "Από το τρέχον τραγούδι",
	"InsufficientConnectivity": "Ανεπαρκής συνδεσιμότητα για άνοιγμα Pandora.",
	"InsufficientConnectivity_Alert": "Ανεπαρκής συνδεσιμότητα",
	"InvalidLogin1": "Άκυρη είσοδος",
	"InvalidLogin2": "Η επικύρωση απέτυχε.",
	"LicensingRestriction1": "Περιορισμός άδειας",
	"LicensingRestriction2": "Το Pandora δεν είναι διαθέσιμο εκτός των ΗΠΑ.",
	"LicensingRestrictions_Alert": "Περιορισμοί άδειας",
	"Loading": "Προσθέστε ένα Σταθμό. ",
	"MobileDevice1": "Σφάλμα κινητής συσκευής",
	"MobileDevice2": "Βεβαιωθείτε ότι όλα λειτουργούν κανονικά με την κινητή συσκευή σας",
	"NoBookmark_Alert": "Αδύνατη προσθήκη σελιδ.",
	"NoCurrentStation": "Ο σταθμός αφαιρέθηκε",
	"NoDeviceConnected": "Καμία συνδεδεμένη συσκευή",
	"NoFavoritesStationsCreated": "Δεν δημιουργήθηκαν αγαπημένοι σταθμοί.",
	"NoPandora1": "Pandora δεν βρέθηκε",
	"NoPandora2": "Βεβαιωθείτε ότι η εφαρμογή Pandora είναι ήδη εγκατεστημένη στην κινητή συσκευή σας",
	"NoRating_Alert": "Μη προσθ. αξιολόγ",
	"NoStationFound1": "Δεν βρέθηκε κανένας σταθμός",
	"NoStationFound2": "Πρέπει να έχετε τουλάχιστον έναν σταθμό Pandora ρυθμισμένο πρώτα.",
	"Nostationsadded": "Δεν προστέθηκαν σταθμοί ",
	"NotSupportedVersion1": "Αναβαθμίστε την έκδοση Pandora στην κινητή συσκευή σας.",
	"OverLimit": "Δυστυχώς, οι άδειες μουσικής μας μας αναγκάζουν να περιορίσουμε τον αριθμό των τραγουδιών που μπορείτε να παραλείψετε.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Προσθήκη/επεξεργασία Αγαπημένων του Pandora",
	"PandoraDeleteConfirmation": "Είστε βέβαιοι ότι θέλετε να διαγράψετε το Αγαπημένο {name};",
	"PandoraFavorites": "Αγαπημένα του Pandora",
	"PandoraFavoritesAvailable": "Το Αγαπημένο του Pandora υπάρχει ήδη",
	"PandoraFavoritesConfirm": "Θέλετε να αντικαταστήσετε κάποιο;",
	"PandoraFavoritesDelete": "Επιλέξτε το Αγαπημένο του Pandora που θα διαγραφεί",
	"PandoraFavoritesMax": "Έχει συμπληρωθεί ο μέγιστος αριθμός Αγαπημένων τουPandora.",
	"PandoraFavoritesMove": "Επιλέξτε το Αγαπημένο του Pandora που θα μετακινηθεί",
	"PandoraFavoritesReplace": "Αντικατάσταση με {active station}",
	"PandoraFavoritesSelect": "Επιλέξτε το Αγαπημένο του Pandora που θα αντικατασταθεί",
	"PandoraMaintinence": "Δυστυχώς, το Pandora είναι υπό συντήρηση επί του παρόντος.",
	"PandoraMoveFavorite": "Μετακίνηση",
	"PandoraReplaceButtonText": "Αντικατάσταση",
	"PandoraSelectPosition": "Επιλέξτε θέση",
	"Quit": "Έξοδος",
	"SelectStation": "Ο προηγούμενος Σταθμός Ακρόασης καταργήθηκε",
	"Setup": "Ρύθμιση",
	"SetupBluetoothDeviceNow": "Ρύθμιση συσκευής Bluetooth τώρα;",
	"Shuffle": "Τυχαία σειρά",
	"ShuffleNotAddedFavorites": "NA ONLY",
	"SortBy": "Ταξινόμηση κατά",
	"SortByAZ": "Ταξινόμηση κατά: A-Ω",
	"SortByDate": "Ταξινόμηση κατά: Ημερομηνία",
	"StationCreationError": "Υπήρξε σφάλμα κατά τη δημιουργία ενός Σταθμού.",
	"StationLimitRecahed": "Εξαντλήθηκε το όριο του σταθμού",
	"StationList": "Λίστα σταθμών",
	"StationListTab": "Αγαπημένα",
	"ThumbsDown": "Αποδοκιμασία",
	"ThumbsUp": "Επιδοκιμασία",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Μενού ψυχαγωγίας",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Αδύνατη προσθήκη σελιδοδείκτη",
	"sbnConnectionError": "Απώλεια σύνδεσης δικτύου",
	"sbnConnectivityError": "Ανεπαρκής συνδεσιμότητα",
	"sbnMobileDeviceError": "Σφάλμα κινητής συσκευής",
	"sbnOverLimit": "Παράλειψη επίτευξης ορίου",
	"sbnPandoraMaintErr": "Σφάλμα συντήρησης Pandora",
	"sbnRatingFailed": "Αδύνατη προσθήκη ονομ. τιμής",
	"sbnStationDeleted": "Δεν υπάρχει τρέχων σταθμός",
	"skip_Tooltip": "Παράβλεψη",
};

framework.registerAppDictLoaded("pandora", "el_GR");