var Localization_pandoraAppDict_he_IL = {
	//"stringId" : "localString"
	"AZ": "א-ת",
	"AddBookmark_Alert": "הוספת סימניה",
	"AddGenreStation": "הוסף תחנה: {genreStation}",
	"AddStation": "הוסף תחנה",
	"AddStationOption": "צור תחנה חדשה:",
	"AddStationOptionButton3": "אמן",
	"AddingFavorites": "מוסיף תחנה למועדפים",
	"AddingStation": "מוסיף תחנה",
	"BluetoothAudioLost": "חיבור אודיו Bluetooth אבד",
	"Bookmark": "אופציה של סימנית פנדורה",
	"BookmarkAlreadyAdded": "סימניה כבר נוספה.",
	"BookmarkArtist": "סמן אומן",
	"BookmarkSong": "סמן שיר",
	"Buffering": "חציצה",
	"ConnectionLost1": "תקשורת אבדה",
	"ConnectionLost2": "וודאה שחיבור הנתונים במכשירך הנייד פועלת כשורה.",
	"Date": "תאריך",
	"DeleteFavorites": "מוחק תחנה מהמועדפים",
	"FavoritesLimitReached": "הגעת לגבול המועדפים",
	"FromCurrentArtist": "מהאמן הנוכחי",
	"FromCurrentSong": "מהשיר הנוכחי",
	"InsufficientConnectivity": "קישוריות בלתי מספקת על מנת לפתוח פנדורה.",
	"InsufficientConnectivity_Alert": "קישוריות לא מספקת",
	"InvalidLogin1": "קוד כניסה אינו תקף",
	"InvalidLogin2": "אימות נכשל",
	"LicensingRestriction1": "הגבלת רשיון",
	"LicensingRestriction2": "פנדורה לא זמינה מחוץ לארצות הברית.",
	"LicensingRestrictions_Alert": "הגבלות הרשאה",
	"Loading": "אנא הוסף תחנה.",
	"MobileDevice1": "שגיאת מכשיר נייד",
	"MobileDevice2": "וודא שהכל פועל כשורה במכשירך הנייד..",
	"NoBookmark_Alert": "הוספת סימניה נכשלה",
	"NoCurrentStation": "התחנה הוסרה",
	"NoDeviceConnected": "אין מכשיר מחובר",
	"NoFavoritesStationsCreated": "לא נוצרו תחנות מועדפות.",
	"NoPandora1": "פנדורה לא נמצאה",
	"NoPandora2": "וודא שיישום פנדורה כבר מותקן במכשירך הנייד.",
	"NoRating_Alert": "הדירוג נכשל",
	"NoStationFound1": "לא נמצא תחנה",
	"NoStationFound2": "אתה חייב שתהיה לך לפחות תחנת פנדורה אחת מותקנת.",
	"Nostationsadded": "לא נוספו תחנות.",
	"NotSupportedVersion1": "נא לשדרג את גרסת פנדורה במכשיר הנייד שלך.",
	"OverLimit": "מצטערים, רשיונות המוזיקה מאלצים אותנו להגביל את מספר הרצועות עליהן ניתן לדלג.",
	"Pandora": "פנדורה",
	"PandoraAddEditFavorites": "הוסף/ערוך מועדפים של  Pandora‏ ",
	"PandoraDeleteConfirmation": "האם אתה בטוח שברצונך למחוק את המועדף {name}‏?",
	"PandoraFavorites": "מועדפים של Pandora‏ ‎",
	"PandoraFavoritesAvailable": "מועדף של Pandora‏ כבר זמין.",
	"PandoraFavoritesConfirm": "האם אתה מעוניין להחליף אחד מהם?",
	"PandoraFavoritesDelete": "בחר מועדף של Pandora‏ למחיקה",
	"PandoraFavoritesMax": "הגעת למספר המרבי של מועדפים של Pandora‏.",
	"PandoraFavoritesMove": "בחר מועדף של Pandora‏ להעברה",
	"PandoraFavoritesReplace": "החלף עם {active station}",
	"PandoraFavoritesSelect": "בחר מועדף של Pandora‏ להחלפה",
	"PandoraMaintinence": "סליחה, פנדורה עכשיו בתחזוקה.",
	"PandoraMoveFavorite": "העבר",
	"PandoraReplaceButtonText": "החלף",
	"PandoraSelectPosition": "בחר מיקום",
	"Quit": "צא",
	"SelectStation": "התחנה הקודמת הוסרה",
	"Setup": "הגדרות",
	"SetupBluetoothDeviceNow": " להגדיר התקן Bluetooth עכשיו?",
	"Shuffle": "סדר אקראי",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "מיין לפי",
	"SortByAZ": "מיין לפי: א-ת",
	"SortByDate": "מיין לפי: תאריך",
	"StationCreationError": "הייתה שגיאה בזמן יצירת תחנה.",
	"StationLimitRecahed": "הגעת לגבול התחנות",
	"StationList": "רשימת תחנות",
	"StationListTab": "מועדפים",
	"ThumbsDown": "אגודל מטה",
	"ThumbsUp": "אגודל מעלה",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "תפריט בידור",
	"sbNameId": "פנדורה",
	"sbnBookmarkFailed": "לא ניתן להוסיף סימנייה",
	"sbnConnectionError": "חיבור לרשת אבד",
	"sbnConnectivityError": "קישוריות בלתי מספקת",
	"sbnMobileDeviceError": "שגיאת מכשיר נייד",
	"sbnOverLimit": "הגעת לגבול הדילוג האפשרי",
	"sbnPandoraMaintErr": "שגיאת תחזוקת פנדורה",
	"sbnRatingFailed": "לא ניתן להוסיף דירוג",
	"sbnStationDeleted": "אין תחנה שמתנגנת כעת",
	"skip_Tooltip": "דלג",
};

framework.registerAppDictLoaded("pandora", "he_IL");