var Localization_pandoraAppDict_lv_LV = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Grāmatzīmes pievienošana",
	"AddGenreStation": "Pievienojiet staciju: {genreStation}",
	"AddStation": "Pievienojiet staciju",
	"AddStationOption": "Izveidot jaunu staciju:",
	"AddStationOptionButton3": "Mākslinieks",
	"AddingFavorites": "Pievieno staciju Iecienītajām",
	"AddingStation": "Pievieno staciju",
	"BluetoothAudioLost": "Bluetooth audio savienojums ir zaudēts",
	"Bookmark": "Pandora grāmatzīmes opcija",
	"BookmarkAlreadyAdded": "Grāmatzīme jau pievienota",
	"BookmarkArtist": "Atzīmēt izpildītāju ar grāmatzīmi",
	"BookmarkSong": "Atzīmēt dziesmu ar grāmatzīmi",
	"Buffering": "Buferizācija",
	"ConnectionLost1": "Savienojums zaudēts",
	"ConnectionLost2": "Pārbaudiet, vai mobilās ierīces datu savienojums darbojas pareizi.",
	"Date": "Datums",
	"DeleteFavorites": "Noņem staciju no Iecienītajām",
	"FavoritesLimitReached": "Sasniegts izlasei limits",
	"FromCurrentArtist": "No pašreizējā izpildītāja",
	"FromCurrentSong": "No pašreizējās dziesmas",
	"InsufficientConnectivity": "Nepietiekama savienojamība Pandora atvēršanai.",
	"InsufficientConnectivity_Alert": "Nepietiekama savienojamība",
	"InvalidLogin1": "Nederīga pieteikšanās",
	"InvalidLogin2": "Autentifikācijas kļūme.",
	"LicensingRestriction1": "Licencēšanas ierobežojums",
	"LicensingRestriction2": "Pandora nav pieejama ārpus Amerikas Savienotajām Valstīm.",
	"LicensingRestrictions_Alert": "Licences ierobežojumi",
	"Loading": "Lūdzu, pievienojiet staciju",
	"MobileDevice1": "Mobilās ierīces kļūda",
	"MobileDevice2": "Pārbaudiet, vai mobilajā ierīcē viss darbojas pareizi.",
	"NoBookmark_Alert": "Nevar pievienot grāmatz.",
	"NoCurrentStation": "Stacija ir izņemta",
	"NoDeviceConnected": "Nav pievienota neviena ierīce",
	"NoFavoritesStationsCreated": "Nav atlasīta neviena izlases stacija.",
	"NoPandora1": "Pandora nav atrasta",
	"NoPandora2": "Pārbaudiet, vai lietojumprogramma Pandora jau ir instalēta mobilajā ierīcē.",
	"NoRating_Alert": "Nevar pievienot novērt.",
	"NoStationFound1": "Neviena stacija nav atrasta",
	"NoStationFound2": "Vispirms ir jāiestata vismaz viena Pandora stacija.",
	"Nostationsadded": "Nav pievienota neviena stacija.",
	"NotSupportedVersion1": "Lūdzu, atjauniniet Pandora versiju savā mobilajā ierīcē.",
	"OverLimit": "Diemžēl mūsu mūzikas licencēm ir ierobežojumi, cik daudz ierakstu drīkstat izlaist.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Pievienot/rediģēt Pandora izlasi",
	"PandoraDeleteConfirmation": "Vai tiešām vēlaties dzēst izlasi {name}?",
	"PandoraFavorites": "Pandora izlase",
	"PandoraFavoritesAvailable": "Pandora izlase, kas jau ir pieejama",
	"PandoraFavoritesConfirm": "Vai vēlaties kādu aizstāt?",
	"PandoraFavoritesDelete": "Atlasīt Pandora izlasi, ko dzēst",
	"PandoraFavoritesMax": "Jūs esat sasniedzis maksimālo  Pandora izlašu skaitu.",
	"PandoraFavoritesMove": "Atlasīt Pandora izlasi, ko pārvietot",
	"PandoraFavoritesReplace": "Aizstāt ar {active station}",
	"PandoraFavoritesSelect": "Atlasīt Pandora izlasi, ko aizstāt",
	"PandoraMaintinence": "Diemžēl lietojumprogrammai Pandora šobrīd tiek veikta tehniskā apkope.",
	"PandoraMoveFavorite": "Pārvietot",
	"PandoraReplaceButtonText": "Aizstāt",
	"PandoraSelectPosition": "Atlasīt pozīciju",
	"Quit": "Iziet",
	"SelectStation": "Iepriekš atskaņotā stacija tika noņemta",
	"Setup": "Iestatīšana",
	"SetupBluetoothDeviceNow": "Vai iestatīt Bluetooth ierīci tūlīt?",
	"Shuffle": "Jauktā secībā",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Kārtot pēc:",
	"SortByAZ": "Kārtot pēc: A-Z",
	"SortByDate": "Kārtot pēc: datuma",
	"StationCreationError": "Kļūda stacijas izveidošanā.",
	"StationLimitRecahed": "Sasniegts staciju limits",
	"StationList": "Staciju saraksts",
	"StationListTab": "Izlase",
	"ThumbsDown": "Īkšķis uz leju",
	"ThumbsUp": "Īkšķis uz augšu",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Izklaides izvēlne",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Nevar pievienot grāmatzīmi",
	"sbnConnectionError": "Tīkla savienojums zaudēts",
	"sbnConnectivityError": "Nepietiekama savienojamība",
	"sbnMobileDeviceError": "Mobilās ierīces kļūda",
	"sbnOverLimit": "Sasniegts izlaišanas ierobež.",
	"sbnPandoraMaintErr": "Pandora apkopes kļūda",
	"sbnRatingFailed": "Nevar pievienot novērtējumu",
	"sbnStationDeleted": "No pašreizējās stacijas",
	"skip_Tooltip": "Izlaist",
};

framework.registerAppDictLoaded("pandora", "lv_LV");