var Localization_pandoraAppDict_mn_TW = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "正在新增書籤",
	"AddGenreStation": "新增電台 :  {genreStation}",
	"AddStation": "新增電台",
	"AddStationOption": "建立新播放台：",
	"AddStationOptionButton3": "演出者",
	"AddingFavorites": "正在將電台新增至我的最愛",
	"AddingStation": "正在新增電台",
	"BluetoothAudioLost": "藍牙連線已中斷",
	"Bookmark": "Pandora 書籤選項",
	"BookmarkAlreadyAdded": "已新增書籤。",
	"BookmarkArtist": "給演出者加書籤",
	"BookmarkSong": "給歌曲加書籤",
	"Buffering": "緩衝中",
	"ConnectionLost1": "連線已中斷 ",
	"ConnectionLost2": "請確認智慧手機的連線功能",
	"Date": "日期",
	"DeleteFavorites": "正在將電台從我的最愛移除",
	"FavoritesLimitReached": "已達到我的最愛限制",
	"FromCurrentArtist": "從目前演出者",
	"FromCurrentSong": "從目前歌曲",
	"InsufficientConnectivity": "連線功能不足以開啟 Pandora",
	"InsufficientConnectivity_Alert": "連線功能不足",
	"InvalidLogin1": "登入無效",
	"InvalidLogin2": "驗證失敗。 請確定已在行動裝置上登入。",
	"LicensingRestriction1": "授權限制",
	"LicensingRestriction2": "Pandora 無法在美國以外使用。",
	"LicensingRestrictions_Alert": "授權限制",
	"Loading": "請新增電台。",
	"MobileDevice1": "行動裝置錯誤",
	"MobileDevice2": "請確定行動裝置上的一切都適當地運作。",
	"NoBookmark_Alert": "無法新增書籤",
	"NoCurrentStation": "目前沒有正在播放的電台",
	"NoDeviceConnected": "未連接裝置",
	"NoFavoritesStationsCreated": "未建立最愛的播放台。",
	"NoPandora1": "找不到 Pandora",
	"NoPandora2": "請確定已將 Pandora 應用程式安裝在行動裝置上。",
	"NoRating_Alert": "無法新增評等",
	"NoStationFound1": "找不到電台",
	"NoStationFound2": "請在行動裝置上至少建立一個 Pandora 電台。",
	"Nostationsadded": "沒有新增電台。",
	"NotSupportedVersion1": "請升級行動裝置上 Pandora 的版本。",
	"OverLimit": "對不起，我們的音樂授權強制我們限制您可跳過的曲目數目。",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "新增/編輯 Pandora 最愛",
	"PandoraDeleteConfirmation": "您確定要刪除最愛 {name}？",
	"PandoraFavorites": "Pandora 最愛",
	"PandoraFavoritesAvailable": "Pandora 最愛已經可以使用",
	"PandoraFavoritesConfirm": "您要取代其中一個嗎？",
	"PandoraFavoritesDelete": "選取要刪除的 Pandora 最愛",
	"PandoraFavoritesMax": "您已達到 Pandora 最愛的數目上限。",
	"PandoraFavoritesMove": "選取要移動的 Pandora 最愛",
	"PandoraFavoritesReplace": "取代為 {active station}",
	"PandoraFavoritesSelect": "選取要取代的 Pandora 最愛",
	"PandoraMaintinence": "對不起，Pandora 目前正在維修中。",
	"PandoraMoveFavorite": "移動",
	"PandoraReplaceButtonText": "取代",
	"PandoraSelectPosition": "選取位置",
	"Quit": "退出",
	"SelectStation": "已移除之前的播放台",
	"Setup": "設定",
	"SetupBluetoothDeviceNow": "要現在設定藍牙裝置嗎?",
	"Shuffle": "隨機播放",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "排序依據",
	"SortByAZ": "排序依據 :  A-Z",
	"SortByDate": "排序依據 :  日期",
	"StationCreationError": "建立電台時發生錯誤。",
	"StationLimitRecahed": "電台儲存數量已達上限",
	"StationList": "電台清單",
	"StationListTab": "我的最愛",
	"ThumbsDown": "遜斃了",
	"ThumbsUp": "讚",
	"VrHelp_BookmarkOptions_Help_Left1": "藝術家",
	"VrHelp_BookmarkOptions_Help_Left2": "歌曲",
	"VrHelp_NowPlaying_Help_Left1": "更改來源",
	"VrHelp_NowPlaying_Help_Left2": "電台列表",
	"VrHelp_NowPlaying_Help_Left3": "拇指朝下",
	"VrHelp_NowPlaying_Help_Left4": "拇指朝上",
	"VrHelp_NowPlaying_Help_Left5": "對歌曲設置書籤",
	"VrHelp_NowPlaying_Help_Right1": "對藝術家設置書籤",
	"VrHelp_NowPlaying_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3": "跳過",
	"VrHelp_NowPlaying_Help_Right4": "聲音設置",
	"VrHelp_SortBy_Help_Left1": "日期",
	"VrHelp_SortBy_Help_Left2": "A 到 Z",
	"entMenu": "娛樂清単",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "無法新增書籤",
	"sbnConnectionError": "網路連線已中斷",
	"sbnConnectivityError": "連線功能不足",
	"sbnMobileDeviceError": "行動裝置錯誤",
	"sbnOverLimit": "已達到跳過限制",
	"sbnPandoraMaintErr": "Pandora 維修錯誤",
	"sbnRatingFailed": "無法新增評等",
	"sbnStationDeleted": "無目前電台",
	"skip_Tooltip": "跳過",
};

framework.registerAppDictLoaded("pandora", "mn_TW");