var Localization_pandoraAppDict_sr_RS = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Dodavanje obeleživača",
	"AddGenreStation": "Dodaj stanicu: {genreStation}",
	"AddStation": "Dodaj stanicu",
	"AddStationOption": "Napravi novu stanicu:",
	"AddStationOptionButton3": "Umetnik",
	"AddingFavorites": "Dodavanje stanice u omiljene",
	"AddingStation": "Dodavanje stanice",
	"BluetoothAudioLost": "Bluetooth Audio veza je izgubljena",
	"Bookmark": " Opcija obeleživač Pandora",
	"BookmarkAlreadyAdded": "Obeleživač je već dodat.",
	"BookmarkArtist": "Obeleži izvođača",
	"BookmarkSong": "Obeleži pesmu",
	"Buffering": "Skupljam podatke",
	"ConnectionLost1": "Veza je izgubljena",
	"ConnectionLost2": "Uverite se da veza za prenos podataka na vašem mobilnom uređaju radi pravilno.",
	"Date": "Datum",
	"DeleteFavorites": "Uklanjanje stanice iz omiljenih",
	"FavoritesLimitReached": "Dostignuto ogran. Omiljenih",
	"FromCurrentArtist": "Od trenutnog izvođača",
	"FromCurrentSong": "Od trenutne pesme",
	"InsufficientConnectivity": "Nedovoljna povezanost za otvaranje Pandore.",
	"InsufficientConnectivity_Alert": "Nedovoljna konekcija",
	"InvalidLogin1": "Nevažeći podaci za prijavljivanje",
	"InvalidLogin2": " Provera identiteta nije uspela.",
	"LicensingRestriction1": "Ograničenje licenciranja",
	"LicensingRestriction2": "Pandora nije dostupna van Sjedinjenih Država.",
	"LicensingRestrictions_Alert": "Ograničenje licence",
	"Loading": "Molimo, dodajte stanicu.",
	"MobileDevice1": "Greška u mobilnom uređaju",
	"MobileDevice2": "Uverite se da sve pravilno funkcioniše kod vašeg mobilnog uređaja.",
	"NoBookmark_Alert": "Nemoguće obelež.",
	"NoCurrentStation": "Stanica nije uključena",
	"NoDeviceConnected": "Nije povezan nijedan uređaj",
	"NoFavoritesStationsCreated": "Nije napravljena ni jedna omiljena stanica.",
	"NoPandora1": "Pandora nije nađena",
	"NoPandora2": "Uverite se da je Pandora aplikacija već instalirana na vašem mobilnom uređaju.",
	"NoRating_Alert": "Nemoguće dodati ocenu",
	"NoStationFound1": "Nije pronađena nijedna stanica",
	"NoStationFound2": "Morate prvo da imate bar jednu podešenu Pandora stanicu.",
	"Nostationsadded": "Stanice nisu dodate.",
	"NotSupportedVersion1": "Molimo ažurirajte verziju Pandore na vašem mobilnom uređaju.",
	"OverLimit": "Nažalost, naše dozvole za muziku nas prisiljavaju da ograničimo broj pesama koje možete da preskočite.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Dodaj/uredi Pandora omiljene",
	"PandoraDeleteConfirmation": "Jeste li sigurni da želite da izbrišete omiljeni {name}?",
	"PandoraFavorites": "Pandora omiljeni",
	"PandoraFavoritesAvailable": "Pandora omiljeni je već dostupan",
	"PandoraFavoritesConfirm": "Želite li neki da zamenite?",
	"PandoraFavoritesDelete": "Izaberite Pandora omiljeni koji želite da izbrišete",
	"PandoraFavoritesMax": "Dostigli ste maksimalni broj Pandora omiljenih.",
	"PandoraFavoritesMove": "Izaberite Pandora omiljeni koji želite da pomerite",
	"PandoraFavoritesReplace": "Zameni sa {active station}",
	"PandoraFavoritesSelect": "Izaberite Pandora omiljeni koji želite da zamenite",
	"PandoraMaintinence": "Nažalost, Pandora se trenutno održava",
	"PandoraMoveFavorite": "Pomeri",
	"PandoraReplaceButtonText": "Zameni",
	"PandoraSelectPosition": "Izaberite položaj",
	"Quit": "Zatvori",
	"SelectStation": "Prethodna izabrana stanica je uklonjena",
	"Setup": "Podešavanje",
	"SetupBluetoothDeviceNow": "Podesiti Bluetooth uređaj sada?",
	"Shuffle": "Slučajna reprodukcija pesama",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Sortiraj po",
	"SortByAZ": "Sortiraj po: A-Z",
	"SortByDate": "Sortiraj po: Datum",
	"StationCreationError": "Došlo je do greške pri kreiranju stanice.",
	"StationLimitRecahed": "Dostignuto je ograničenje broja stanica",
	"StationList": "Lista stanica",
	"StationListTab": "Omiljeni",
	"ThumbsDown": "Palac nadole",
	"ThumbsUp": "Palac nagore",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Meni Zabava",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Nije moguće dodati obeleživač",
	"sbnConnectionError": "Izgubljena je mrežna veza",
	"sbnConnectivityError": "Nedovoljna povezanost",
	"sbnMobileDeviceError": "Greška u mobilnom uređaju",
	"sbnOverLimit": "Ogran.preskakanja dostignuto",
	"sbnPandoraMaintErr": "Greška u održavanju Pandore",
	"sbnRatingFailed": "Nije moguće dodati ocenu",
	"sbnStationDeleted": "Nema nijedne radio stanice",
	"skip_Tooltip": "Sledeća",
};

framework.registerAppDictLoaded("pandora", "sr_RS");