var Localization_pandoraAppDict_it_IT = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Aggiunta segnalibro…",
	"AddGenreStation": "Aggiungi Stazione: {genreStation}",
	"AddStation": "Aggiungi Stazione",
	"AddStationOption": "Crea nuova stazione:",
	"AddStationOptionButton3": "Artista",
	"AddingFavorites": "Aggiunta Stazione ai Preferiti in corso",
	"AddingStation": "Aggiunta Stazione in corso",
	"BluetoothAudioLost": "Connessione Bluetooth automatica persa.",
	"Bookmark": "Opzione segnalibro Pandora",
	"BookmarkAlreadyAdded": "Un segnalibro è già stato creato.",
	"BookmarkArtist": "Metti segnalibro ad artista",
	"BookmarkSong": "Metti segnalibro alla canzone",
	"Buffering": "Buffering",
	"ConnectionLost1": "Connessione persa.",
	"ConnectionLost2": "Assicurarsi che la connessione dati del proprio telefono funzioni correttamente.",
	"Date": "Data",
	"DeleteFavorites": "Eliminazione Stazione dai Preferiti in corso",
	"FavoritesLimitReached": "Raggiunto il limite Preferiti",
	"FromCurrentArtist": "Dall'artista corrente",
	"FromCurrentSong": "Dalla canzone corrente",
	"InsufficientConnectivity": "Connettività insufficiente per aprire Pandora.",
	"InsufficientConnectivity_Alert": "Connettività insufficiente",
	"InvalidLogin1": "Accesso non valido.",
	"InvalidLogin2": "Autenticazione non riuscita.",
	"LicensingRestriction1": "Restrizione di licenza",
	"LicensingRestriction2": "Pandora non è disponibile fuori dagli Stati Uniti.",
	"LicensingRestrictions_Alert": "Restrizioni di licenza",
	"Loading": "Si prega di aggiungere una Stazione",
	"MobileDevice1": "Errore cellulare.",
	"MobileDevice2": "Assicurarsi che il proprio cellulare funzioni correttamente.",
	"NoBookmark_Alert": "Segnalibro impossibile.",
	"NoCurrentStation": "Stazione è stata rimossa",
	"NoDeviceConnected": "Nessun dispositivo connesso.",
	"NoFavoritesStationsCreated": "nessuna stazione preferita creata.",
	"NoPandora1": "Applicazione Pandora non trovata",
	"NoPandora2": "Assicurarsi che l'applicazione Pandora sia già installata sul proprio cellulare.",
	"NoRating_Alert": "Valutazione impossibile.",
	"NoStationFound1": "Nessuna stazione trovata.",
	"NoStationFound2": "Bisogna avere almeno una stazione Pandora impostata prima.",
	"Nostationsadded": "Nessuna stazione aggiunta.",
	"NotSupportedVersion1": "Si prega di aggiornare la versione di Pandora sul proprio cellulare.",
	"OverLimit": "Ci dispiace ma le nostre licenze di musica ci obbligano a limitare il numero delle tracce che si possono saltare.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Aggiungi/Modifica Preferiti Pandora",
	"PandoraDeleteConfirmation": "Eliminare il Preferito {name}?",
	"PandoraFavorites": "Preferiti Pandora",
	"PandoraFavoritesAvailable": "Preferito Pandora già disponibile",
	"PandoraFavoritesConfirm": "Sostituirne uno?",
	"PandoraFavoritesDelete": "Selezionare il Preferito Pandora da eliminare",
	"PandoraFavoritesMax": "Numero massimo di Preferiti Pandora raggiunto.",
	"PandoraFavoritesMove": "Selezionare il Preferito Pandora da spostare",
	"PandoraFavoritesReplace": "Sostituisci con {active station}",
	"PandoraFavoritesSelect": "Selezionare il Preferito Pandora da sostituire",
	"PandoraMaintinence": "Ci scusiamo, Pandora è attualmente in assistenza.",
	"PandoraMoveFavorite": "Sposta",
	"PandoraReplaceButtonText": "Sostituisci",
	"PandoraSelectPosition": "Seleziona posizione",
	"Quit": "Esci",
	"SelectStation": "Stazione di gioco precedente rimossa",
	"Setup": "Imposta",
	"SetupBluetoothDeviceNow": "Impostare dispositivo Bluetooth ora?",
	"Shuffle": "Mischia",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Ordina per",
	"SortByAZ": "Ordina per: A-Z",
	"SortByDate": "Ordina per: Data",
	"StationCreationError": "Si è verificato un errore in fase di creazione di una Stazione.",
	"StationLimitRecahed": "Raggiunto il limite delle Stazioni",
	"StationList": "Elenco stazioni",
	"StationListTab": "Preferiti",
	"ThumbsDown": "Non mi piace",
	"ThumbsUp": "Mi piace",
	"VrHelp_BookmarkOptions_Help_Left1": "Metti segnalibro all'artista",
	"VrHelp_BookmarkOptions_Help_Left2": "Metti segnalibro alla canzone",
	"VrHelp_NowPlaying_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_Help_Left2": "Elenco stazioni",
	"VrHelp_NowPlaying_Help_Left3": "Non mi piace",
	"VrHelp_NowPlaying_Help_Left4": "Mi piace",
	"VrHelp_NowPlaying_Help_Left5": " Metti segnalibro alla canzone",
	"VrHelp_NowPlaying_Help_Right1": "Metti segnalibro all'artista",
	"VrHelp_NowPlaying_Help_Right2": "Riproduci / Pausa",
	"VrHelp_NowPlaying_Help_Right3": "successivo",
	"VrHelp_NowPlaying_Help_Right4": "Impostazioni audio",
	"VrHelp_SortBy_Help_Left1": "Data",
	"VrHelp_SortBy_Help_Left2": "Dalla A alla Z",
	"entMenu": "Menu intrattenimento",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Impossibile aggiungere segnalibro.",
	"sbnConnectionError": "Connessione rete persa",
	"sbnConnectivityError": "Connettività insufficiente.",
	"sbnMobileDeviceError": "Errore cellulare.",
	"sbnOverLimit": "Limite passaggi raggiunto.",
	"sbnPandoraMaintErr": "Errore assistenza Pandora.",
	"sbnRatingFailed": "Impossibile aggiungere valutazione.",
	"sbnStationDeleted": "Nessuna stazione al momento.",
	"skip_Tooltip": "Salta",
};

framework.registerAppDictLoaded("pandora", "it_IT");