var Localization_pandoraAppDict_id_ID = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Menambahkan Penanda",
	"AddGenreStation": "Tambah Stasiun: {genreStation}",
	"AddStation": "Tambah Stasiun",
	"AddStationOption": "Buat Stasiun baru:",
	"AddStationOptionButton3": "Artis",
	"AddingFavorites": "Tambah Stasiun ke Favorit",
	"AddingStation": "Tambah Stasiun",
	"BluetoothAudioLost": "Koneksi Audio Bluetooth Hilang",
	"Bookmark": "Opsi Penanda Pandora",
	"BookmarkAlreadyAdded": "Bookmark sudah ditambah",
	"BookmarkArtist": "Tandai Artis",
	"BookmarkSong": "Tandai Lagu",
	"Buffering": "Memuat",
	"ConnectionLost1": "Koneksi Hilang",
	"ConnectionLost2": "Pastikan koneksi data di perangkat seluler Anda berfungsi normal.",
	"Date": "Tanggal",
	"DeleteFavorites": "Hapus Stasiun dari Favorit",
	"FavoritesLimitReached": "Batas Favorit Tercapai",
	"FromCurrentArtist": "Dari Artis Saat ini",
	"FromCurrentSong": "Dari Lagu Saat Ini",
	"InsufficientConnectivity": "Konektivitas tidak Mencukupi untuk membuka Pandora.",
	"InsufficientConnectivity_Alert": "Konektivitas Tidak Mencukupi",
	"InvalidLogin1": "Login Tidak Sah",
	"InvalidLogin2": "Otentikasi gagal.",
	"LicensingRestriction1": "Pembatasan Pemberian Lisensi",
	"LicensingRestriction2": "Pandora tidak tersedia di luar Amerika Serikat.",
	"LicensingRestrictions_Alert": "Batasan Lisensi",
	"Loading": "Harap tambah Stasiun",
	"MobileDevice1": "Galat Perangkat Seluler",
	"MobileDevice2": "Pastikan segalanya berfungsi normal dengan perangkat seluler Anda.",
	"NoBookmark_Alert": "Tak bs tambah bookmark",
	"NoCurrentStation": "Stasiun Dihilangkan",
	"NoDeviceConnected": "Tidak Ada Perangkat Tersambung",
	"NoFavoritesStationsCreated": "Tidak ada stasiun favorit yang dibuat.",
	"NoPandora1": "Pandora Tidak Ditemukan",
	"NoPandora2": "Pastikan aplikasi Pandora telah terinstal di perangkat seluler Anda.",
	"NoRating_Alert": "Tak bisa tambah peringkat",
	"NoStationFound1": "Pemancar tidak ditemukan",
	"NoStationFound2": "Anda harus memiliki setidaknya satu stasiun Pandora yang telah disiapkan.",
	"Nostationsadded": "Tak ada stasiun yang ditambahkan.",
	"NotSupportedVersion1": "Silakan tingkatkan versi Pandora di Perangkat Seluler Anda.",
	"OverLimit": "Maaf, lisensi musik kami membatasi jumlah track yang dapat Anda lewati.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Tambah/Edit Favorit Pandora",
	"PandoraDeleteConfirmation": "Anda yakin ingin menghapus Favorite {name}?",
	"PandoraFavorites": "Favorit Pandora",
	"PandoraFavoritesAvailable": "Favorit Pandora telah tersedia",
	"PandoraFavoritesConfirm": "Anda ingin mengganti salah satunya?",
	"PandoraFavoritesDelete": "Pilih Favorit Pandora yang Akan Dihapus",
	"PandoraFavoritesMax": "Jumlah Favorit Pandora Anda sudah maksimal.",
	"PandoraFavoritesMove": "Pilih Favorit Pandora yang Akan Dipindahkan",
	"PandoraFavoritesReplace": "Ganti dengan {active station}",
	"PandoraFavoritesSelect": "Pilih Favorit Pandora yang Akan Diganti",
	"PandoraMaintinence": "Maaf, saat ini Pandora sedang diperbaiki.",
	"PandoraMoveFavorite": "Pindahkan",
	"PandoraReplaceButtonText": "Ganti",
	"PandoraSelectPosition": "Pilih Posisi",
	"Quit": "Keluar",
	"SelectStation": "Stasiun Pemutaran Sebelumnya Telah Dihapus",
	"Setup": "Persiapan",
	"SetupBluetoothDeviceNow": "Siapkan Perangkat Bluetooth Sekarang?",
	"Shuffle": "Acak",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Urut Mnrt",
	"SortByAZ": "Urut Mnrt: A-Z",
	"SortByDate": "Urut Mnrt: Tanggal",
	"StationCreationError": "Ada kesalahan saat membuat Stasiun",
	"StationLimitRecahed": "Batas Stasiun Tercapai",
	"StationList": "Daftar Stasiun",
	"StationListTab": "Favorit",
	"ThumbsDown": "Tidak Oke",
	"ThumbsUp": "Oke",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Menu Hiburan",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Tak dapat menambahkan penanda",
	"sbnConnectionError": "Koneksi Jaringan Hilang",
	"sbnConnectivityError": "Konektivitas tidak Mencukupi",
	"sbnMobileDeviceError": "Galat Perangkat Seluler",
	"sbnOverLimit": "Batas pelewatan tercapai",
	"sbnPandoraMaintErr": "Perawatan Pandora Galat",
	"sbnRatingFailed": "Tak bisa tambah peringkat",
	"sbnStationDeleted": "Tidak Ada Stasiun Saat ini",
	"skip_Tooltip": "Lewatkan",
};

framework.registerAppDictLoaded("pandora", "id_ID");