var Localization_pandoraAppDict_lt_LT = {
	//"stringId" : "localString"
	"AZ": "A–Z",
	"AddBookmark_Alert": "Pridedama žymelė",
	"AddGenreStation": "Pridėti stotį: {genreStation}",
	"AddStation": "Pridėti stotį",
	"AddStationOption": "Kurti naują stotį:",
	"AddStationOptionButton3": "Atlikėjas",
	"AddingFavorites": "Stotis pridedama prie parankinių",
	"AddingStation": "Stotis pridedama",
	"BluetoothAudioLost": "Neprijungtas Bluetooth audio įrenginys",
	"Bookmark": "Pandora žymėjimo galimybės",
	"BookmarkAlreadyAdded": "Žymelė jau pridėta.",
	"BookmarkArtist": "Žymėti atlikėją",
	"BookmarkSong": "Žymėti kūrinį",
	"Buffering": "Vykdoma buferizacija",
	"ConnectionLost1": "Dingo ryšys",
	"ConnectionLost2": "Įsitikinkite, kad duomenų ryšys jūsų mobiliajame įrenginyje veikia tinkamai.",
	"Date": "Data",
	"DeleteFavorites": "Stotis šalinama iš parankinių",
	"FavoritesLimitReached": "Pasiekta parankinių riba",
	"FromCurrentArtist": "Iš dabartinio atlikėjo",
	"FromCurrentSong": "Iš dabartinės dainos",
	"InsufficientConnectivity": "Ryšys nepakankamas Pandora atidaryti.",
	"InsufficientConnectivity_Alert": "Nepakankamas ryšys",
	"InvalidLogin1": "Neteisingas prisijungimo vardas",
	"InvalidLogin2": "Nepavyko identifikuoti.",
	"LicensingRestriction1": "Licencijos apribojimai",
	"LicensingRestriction2": "Pandora nepasiekiama už JAV ribų.",
	"LicensingRestrictions_Alert": "Licencijos apribojimai",
	"Loading": "Pridėkite stotį.",
	"MobileDevice1": "Mobiliojo įrenginio klaida",
	"MobileDevice2": "Įsitikinkite, kad mobilusis įrenginys veikia tinkamai.",
	"NoBookmark_Alert": "Nepavyko pridėti žymelės",
	"NoCurrentStation": "Stotis pašalinta",
	"NoDeviceConnected": "Neprijungtas joks įrenginys",
	"NoFavoritesStationsCreated": "Nėra sukurtų parankinių stočių.",
	"NoPandora1": "Pandora nerasta",
	"NoPandora2": "Įsitikinkite, kad Pandora programa jau įdiegta mobiliajame įrenginyje.",
	"NoRating_Alert": "Nepavyko pridėti reitingo",
	"NoStationFound1": "Stočių nerasta",
	"NoStationFound2": "Iš pradžių turite nustatyti bent vieną Pandora stotį.",
	"Nostationsadded": "Stočių nepridėta.",
	"NotSupportedVersion1": "Savo mobiliajame įrenginyje atnaujinkite Pandora versiją.",
	"OverLimit": "Atsiprašome, mūsų muzikos licencijos verčia mus riboti kūrinių, kuriuos galite praleisti, skaičių.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Pridėti / redaguoti Pandora parankinius",
	"PandoraDeleteConfirmation": "Ar tikrai norite pašalinti parankinį {name}?",
	"PandoraFavorites": "Pandora parankiniai",
	"PandoraFavoritesAvailable": "Pandora parankinis jau yra",
	"PandoraFavoritesConfirm": "Ar norite vieną iš jų sukeisti?",
	"PandoraFavoritesDelete": "Pasirinkite norimą pašalinti Pandora parankinį",
	"PandoraFavoritesMax": "Pasiekėte maksimalų Pandora parankinių skaičių.",
	"PandoraFavoritesMove": "Pasirinkite norimą perkelti Pandora parankinį",
	"PandoraFavoritesReplace": "Sukeisti su {active station}",
	"PandoraFavoritesSelect": "Pasirinkite norimą sukeisti Pandora parankinį",
	"PandoraMaintinence": "Atsiprašome, šiuo metu vykdoma Pandora priežiūra",
	"PandoraMoveFavorite": "Perkelti",
	"PandoraReplaceButtonText": "Sukeisti",
	"PandoraSelectPosition": "Parinkti vietą",
	"Quit": "Baigti",
	"SelectStation": "Ankstesnė leidžiama stotis pašalinta",
	"Setup": "Sąranka",
	"SetupBluetoothDeviceNow": "Nustatyti Bluetooth įrenginį dabar?",
	"Shuffle": "Maišyti",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Rikiuoti pagal",
	"SortByAZ": "Rikiuoti pagal: A–Z",
	"SortByDate": "Rikiuoti pagal: data",
	"StationCreationError": "Kuriant stotį atsirado klaida",
	"StationLimitRecahed": "Pasiekta stočių kiekio riba",
	"StationList": "Stočių sąrašas",
	"StationListTab": "Mėgstamiausi",
	"ThumbsDown": "Nepritarti",
	"ThumbsUp": "Pritarti",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Pramogų meniu",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Nepavyko pridėti žymelės",
	"sbnConnectionError": "Dingo tinklo ryšys",
	"sbnConnectivityError": "Nepakankamas ryšys",
	"sbnMobileDeviceError": "Mobiliojo įrenginio klaida",
	"sbnOverLimit": "Pasiekta praleidimo riba",
	"sbnPandoraMaintErr": "Pandora priežiūros klaida",
	"sbnRatingFailed": "Nepavyko pridėti reitingo",
	"sbnStationDeleted": "Nėra dabartinės stoties",
	"skip_Tooltip": "Praleisti",
};

framework.registerAppDictLoaded("pandora", "lt_LT");