var Localization_pandoraAppDict_ja_JP = {
	//"stringId" : "localString"
	"AZ": "ABC順",
	"AddBookmark_Alert": "ブックマークを追加しています",
	"AddGenreStation": "放送局を追加: {genreStation}",
	"AddStation": "放送局を追加",
	"AddStationOption": "新しいステーションを作成：",
	"AddStationOptionButton3": "アーティスト",
	"AddingFavorites": "放送局をお気に入りに追加中です",
	"AddingStation": "放送局を追加中です",
	"BluetoothAudioLost": "Bluetoothオーディオ接続を失いました",
	"Bookmark": "Pandoraブックマークオプション",
	"BookmarkAlreadyAdded": "ブックマークは追加済です",
	"BookmarkArtist": "アーティストをブックマーク",
	"BookmarkSong": "曲をブックマーク",
	"Buffering": "Buffering",
	"ConnectionLost1": "接続を失いました",
	"ConnectionLost2": "モバイル機器のデータ接続が、正しく機能していることを確認してください。",
	"Date": "日付",
	"DeleteFavorites": "お気に入りから放送局を削除しています",
	"FavoritesLimitReached": "お気に入りがいっぱいです",
	"FromCurrentArtist": "現在のアーティストから",
	"FromCurrentSong": "現在の曲から",
	"InsufficientConnectivity": "接続信号不足のため、Pandoraを開くことができません。",
	"InsufficientConnectivity_Alert": "NA",
	"InvalidLogin1": "無効なログイン",
	"InvalidLogin2": "認証に失敗しました。",
	"LicensingRestriction1": "ライセンス制限",
	"LicensingRestriction2": "アメリカ国外でPandoraを使用することはできません。",
	"LicensingRestrictions_Alert": "NA",
	"Loading": "放送局を追加してください",
	"MobileDevice1": "モバイル機器のエラー",
	"MobileDevice2": "モバイル機器が正常に機能しているかどうか、確認してください。",
	"NoBookmark_Alert": "ブックマークを追加できませんでした",
	"NoCurrentStation": "ステーションが削除されました",
	"NoDeviceConnected": "デバイスが接続されていません",
	"NoFavoritesStationsCreated": "お気に入りのステーションが作成されていません。",
	"NoPandora1": "Pandoraが見つかりません",
	"NoPandora2": "モバイル機器にPandoraアプリケーションが既にインストールされていることを確認してください。",
	"NoRating_Alert": "評価を追加できませんでした",
	"NoStationFound1": "ステーションが見つかりません",
	"NoStationFound2": "先にPandoraステーションを少なくとも1つ作成しておく必要があります。",
	"Nostationsadded": "追加された放送局はありませんでした。",
	"NotSupportedVersion1": "NA",
	"OverLimit": "申し訳ありません。当社の音楽ライセンスにより、トラックのスキップ回数が制限されています。",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Pandora Favoriteを追加／削除",
	"PandoraDeleteConfirmation": "Favoriteの {name}を削除してもよろしいですか？",
	"PandoraFavorites": "Pandora Favorites",
	"PandoraFavoritesAvailable": "すでにPandora Favoriteを利用しています",
	"PandoraFavoritesConfirm": "置き換えますか？",
	"PandoraFavoritesDelete": "削除するPandora Favoriteを選択",
	"PandoraFavoritesMax": "Pandora Favoriteの上限に達しました。",
	"PandoraFavoritesMove": "移動するPandora Favoriteを選択",
	"PandoraFavoritesReplace": " {active station}と置き換える",
	"PandoraFavoritesSelect": "置き換えるPandora Favoriteを選択",
	"PandoraMaintinence": "申し訳ありません。Pandoraは現在保守作業中です。",
	"PandoraMoveFavorite": "移動",
	"PandoraReplaceButtonText": "置き換え",
	"PandoraSelectPosition": "位置を選択",
	"Quit": "終了",
	"SelectStation": "N/A",
	"Setup": "設定",
	"SetupBluetoothDeviceNow": "Bluetoothデバイスを今すぐ設定しますか？",
	"Shuffle": "シャッフル",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "並べ替え順",
	"SortByAZ": "並べ替え:ABC順",
	"SortByDate": "並べ替え: 日付",
	"StationCreationError": "放送局の新規作成でエラーが発生しました",
	"StationLimitRecahed": "放送局がいっぱいです",
	"StationList": "ステーションリスト",
	"StationListTab": "お気に入り",
	"ThumbsDown": "Dislike",
	"ThumbsUp": "Like",
	"VrHelp_BookmarkOptions_Help_Left1": "アーティストをブックマーク",
	"VrHelp_BookmarkOptions_Help_Left2": "曲をブックマーク",
	"VrHelp_NowPlaying_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlaying_Help_Left2": "放送局",
	"VrHelp_NowPlaying_Help_Left3": "ディスライク",
	"VrHelp_NowPlaying_Help_Left4": "ライク",
	"VrHelp_NowPlaying_Help_Left5": "曲をブックマーク",
	"VrHelp_NowPlaying_Help_Right1": "アーティストをブックマーク",
	"VrHelp_NowPlaying_Help_Right2": "再生/ 一時停止",
	"VrHelp_NowPlaying_Help_Right3": "次へ",
	"VrHelp_NowPlaying_Help_Right4": "サウンド設定",
	"VrHelp_SortBy_Help_Left1": "日付",
	"VrHelp_SortBy_Help_Left2": "ABC順",
	"entMenu": "Entertainment",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "ブックマークを追加できません",
	"sbnConnectionError": "ネットワーク接続を失いました",
	"sbnConnectivityError": "接続信号が不足しています",
	"sbnMobileDeviceError": "モバイル機器にエラー発生",
	"sbnOverLimit": "スキップ回数の上限に達しました",
	"sbnPandoraMaintErr": "Pandoraの保守エラー",
	"sbnRatingFailed": "評価を追加できません",
	"sbnStationDeleted": "NA",
	"skip_Tooltip": "Skip",
};

framework.registerAppDictLoaded("pandora", "ja_JP");