var Localization_pandoraAppDict_en_US = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Adding Bookmark",
	"AddGenreStation": "Add Station: {genreStation}",
	"AddStation": "Add Station",
	"AddStationOption": "Create a New Station:",
	"AddStationOptionButton3": "Artist",
	"AddingFavorites": "Adding Station to Favorites",
	"AddingStation": "Adding Station",
	"BluetoothAudioLost": "Bluetooth Audio Connection Lost",
	"Bookmark": "Pandora Bookmark Option",
	"BookmarkAlreadyAdded": "Bookmark was already added.",
	"BookmarkArtist": "Bookmark Artist",
	"BookmarkSong": "Bookmark Song",
	"Buffering": "Buffering",
	"ConnectionLost1": "Connection Lost",
	"ConnectionLost2": "Make sure the data connection on your mobile device is available.",
	"Date": "Date",
	"DeleteFavorites": "Removing Station from Favorites",
	"FavoritesLimitReached": "Favorites Limit Reached",
	"FromCurrentArtist": "From Current Artist",
	"FromCurrentSong": "From Current Song",
	"InsufficientConnectivity": "Insufficient Connectivity to Open Pandora",
	"InsufficientConnectivity_Alert": "Insufficient Connectivity",
	"InvalidLogin1": "Invalid Login",
	"InvalidLogin2": "Authentication failed. Make sure you are logged in on your mobile device.",
	"LicensingRestriction1": "Licensing Restriction",
	"LicensingRestriction2": "Pandora is not available outside the United States.",
	"LicensingRestrictions_Alert": "License Restrictions",
	"Loading": "Please add a Station.",
	"MobileDevice1": "Mobile Device Error",
	"MobileDevice2": "Make sure everything is functioning properly on your mobile device.",
	"NoBookmark_Alert": "Unable to Add Bookmark",
	"NoCurrentStation": "Station Removed ",
	"NoDeviceConnected": "No Device Connected",
	"NoFavoritesStationsCreated": "No favorite stations created.",
	"NoPandora1": "Pandora Not Found",
	"NoPandora2": "Make sure the Pandora application is already installed on your mobile device.",
	"NoRating_Alert": "Unable to Add the Rating",
	"NoStationFound1": "No Station Found",
	"NoStationFound2": "Please create at least one Pandora station on your mobile device.",
	"Nostationsadded": "No stations added.",
	"NotSupportedVersion1": "Please upgrade the version of Pandora on your Mobile Device.",
	"OverLimit": "Sorry, our music licenses force us to limit the number of tracks you may skip.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Add/Edit Pandora Favorites",
	"PandoraDeleteConfirmation": "Are you sure you want to delete the Favorite {name}?",
	"PandoraFavorites": "Pandora Favorites",
	"PandoraFavoritesAvailable": "Pandora Favorite already available",
	"PandoraFavoritesConfirm": "Would you like to replace one?",
	"PandoraFavoritesDelete": "Select Pandora Favorite to Delete",
	"PandoraFavoritesMax": "You have reached the maximum number of Pandora Favorites.",
	"PandoraFavoritesMove": "Select Pandora Favorite to Move",
	"PandoraFavoritesReplace": "Replace with {active station}",
	"PandoraFavoritesSelect": "Select Pandora Favorite to Replace",
	"PandoraMaintinence": "Sorry, Pandora is currently under maintenance.",
	"PandoraMoveFavorite": "Move",
	"PandoraReplaceButtonText": "Replace",
	"PandoraSelectPosition": "Select Position",
	"Quit": "Quit",
	"SelectStation": "Previous Playing Station was Removed",
	"Setup": "Setup",
	"SetupBluetoothDeviceNow": "Setup Bluetooth Device Now?",
	"Shuffle": "Shuffle",
	"ShuffleNotAddedFavorites": "Shuffle Station cannot be added to Favorites. ",
	"SortBy": "Sort By",
	"SortByAZ": "Sort By: A-Z",
	"SortByDate": "Sort By: Date",
	"StationCreationError": "There was an error while creating a Station.",
	"StationLimitRecahed": "Station Limit Reached",
	"StationList": "Station List",
	"StationListTab": "Favorites",
	"ThumbsDown": "Thumbs Down",
	"ThumbsUp": "Thumbs Up",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Audio Sources",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Unable to Add Bookmark",
	"sbnConnectionError": "Network Connection Lost",
	"sbnConnectivityError": "Insufficient Connectivity",
	"sbnMobileDeviceError": "Mobile Device Error",
	"sbnOverLimit": "Skip Limit Reached",
	"sbnPandoraMaintErr": "Pandora Maintenance Error",
	"sbnRatingFailed": "Unable to Add Rating",
	"sbnStationDeleted": "No Current Station",
	"skip_Tooltip": "Skip",
};

framework.registerAppDictLoaded("pandora", "en_US");