var Localization_pandoraAppDict_pt_BR = {
	//"stringId" : "localString"
	"AZ": "De A a Z",
	"AddBookmark_Alert": "Adicionado aos favoritos",
	"AddGenreStation": "Adicionar estação: {genreStation}",
	"AddStation": "Adicionar estação",
	"AddStationOption": "Criar uma nova estação:",
	"AddStationOptionButton3": "Artista",
	"AddingFavorites": "Adicionando estação aos favoritos",
	"AddingStation": "Adicionando estação",
	"BluetoothAudioLost": "Conexão de áudio Bluetooth perdida",
	"Bookmark": "Opção adic. fav. ao Pandora",
	"BookmarkAlreadyAdded": "Favorito já havia sido adicionado.",
	"BookmarkArtist": "Adicionar artista aos favoritos",
	"BookmarkSong": "Adicionar música aos favoritos",
	"Buffering": "Armazenando em buffer",
	"ConnectionLost1": "Conexão perdida",
	"ConnectionLost2": "Certifique-se de que a conexão de dados do seu dispositivo móvel está disponível.",
	"Date": "Data",
	"DeleteFavorites": "Removendo estação dos favoritos",
	"FavoritesLimitReached": "Limite de fav. alcançado",
	"FromCurrentArtist": "Do artista atual",
	"FromCurrentSong": "Da música atual",
	"InsufficientConnectivity": "Conectividade insuficiente para abrir o Pandora",
	"InsufficientConnectivity_Alert": "Conectividade insuficiente",
	"InvalidLogin1": "Login incorreto",
	"InvalidLogin2": "Falha na autenticação. Certifique-se de que esteja conectado em seu dispositivo móvel.",
	"LicensingRestriction1": "Restrição de licenciamento",
	"LicensingRestriction2": "O Pandora não está disponível fora dos Estados Unidos.",
	"LicensingRestrictions_Alert": "Restrições de licença",
	"Loading": "Por favor, adicione uma estação.",
	"MobileDevice1": "Erro no dispositivo móvel",
	"MobileDevice2": "Certifique-se de que tudo esteja funcionando corretamente em seu dispositivo móvel.",
	"NoBookmark_Alert": "Não é possível adic. fav.",
	"NoCurrentStation": "Nenhuma estação tocando no momento",
	"NoDeviceConnected": "Nenhum dispositivo conectado",
	"NoFavoritesStationsCreated": "Não há estações favoritas criadas.",
	"NoPandora1": "Pandora não encontrado",
	"NoPandora2": "Certifique-se de que o aplicativo Pandora já esteja instalado em seu dispositivo móvel.",
	"NoRating_Alert": "Não é possível adic. class.",
	"NoStationFound1": "Nenhuma estação encontrada",
	"NoStationFound2": "Por favor, criar pelo menos uma estação Pandora em seu dispositivo móvel.",
	"Nostationsadded": "Nenhuma estação adicionada.",
	"NotSupportedVersion1": "Por favor, atualize a versão do Pandora do seu dispositivo móvel.",
	"OverLimit": "Desculpe, nossas licenças musicais nos forçam a limitar o número de faixas que você pode ignorar.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Adic/Edi favoritos do Pandora",
	"PandoraDeleteConfirmation": "Tem certeza que deseja excluir o favorito {name}?",
	"PandoraFavorites": "Favoritos do Pandora",
	"PandoraFavoritesAvailable": "Favorito do  Pandora já está disponível",
	"PandoraFavoritesConfirm": "Deseja substituir algum?",
	"PandoraFavoritesDelete": "Selecione o favorito a ser excluído",
	"PandoraFavoritesMax": "Você alcançou o número máximo de favoritos do Pandora.",
	"PandoraFavoritesMove": "Selecione o favorito a ser movido",
	"PandoraFavoritesReplace": "Substituir por  {active station}",
	"PandoraFavoritesSelect": "Selecione o favorito a ser subst.",
	"PandoraMaintinence": "Desculpe, o Pandora encontra-se em manutenção no momento.",
	"PandoraMoveFavorite": "Mover",
	"PandoraReplaceButtonText": "Substituir",
	"PandoraSelectPosition": "Selecionar posição",
	"Quit": "Sair",
	"SelectStation": "A estação que estava tocando antes foi removida",
	"Setup": "Configuração",
	"SetupBluetoothDeviceNow": "Configurar dispositivo Bluetooth agora?",
	"Shuffle": "Ordem aleatória",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Ordenar por",
	"SortByAZ": "Ordenar por: De A a Z",
	"SortByDate": "Ordenar por: Data",
	"StationCreationError": "Houve um erro ao criar uma estação.",
	"StationLimitRecahed": "Limite de estações alcançado",
	"StationList": "Lista de estações",
	"StationListTab": "Favoritos",
	"ThumbsDown": "Descurtir",
	"ThumbsUp": "Curtir",
	"VrHelp_BookmarkOptions_Help_Left1": "Adicionar o intérprete aos favoritos",
	"VrHelp_BookmarkOptions_Help_Left2": "Adicionar a canção aos favoritos",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Lista de estações",
	"VrHelp_NowPlaying_Help_Left3": "Desaprovar",
	"VrHelp_NowPlaying_Help_Left4": "Aprovar",
	"VrHelp_NowPlaying_Help_Left5": "Adicionar a canção aos favoritos",
	"VrHelp_NowPlaying_Help_Right1": "Adicionar o intérprete aos favoritos",
	"VrHelp_NowPlaying_Help_Right2": "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right3": "Seguinte",
	"VrHelp_NowPlaying_Help_Right4": "Definições de som",
	"VrHelp_SortBy_Help_Left1": "Data",
	"VrHelp_SortBy_Help_Left2": "A a Z",
	"entMenu": "Entretenimento",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Não é possível adicionar favoritos",
	"sbnConnectionError": "Conexão de rede perdida",
	"sbnConnectivityError": "Conectividade insuficiente",
	"sbnMobileDeviceError": "Erro no dispositivo móvel",
	"sbnOverLimit": "Limite de itens ignorados alcançado",
	"sbnPandoraMaintErr": "Erro de manutenção do Pandora",
	"sbnRatingFailed": "Não é possível adicionar classif.",
	"sbnStationDeleted": "Nenhuma estação no momento",
	"skip_Tooltip": "Ignorar",
};

framework.registerAppDictLoaded("pandora", "pt_BR");