var Localization_pandoraAppDict_th_TH = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "การเพิ่มบุ๊กมาร์ก",
	"AddGenreStation": "เพิ่มสถานี: {genreStation}",
	"AddStation": "เพิ่มสถานี",
	"AddStationOption": "สร้างสถานีใหม่:",
	"AddStationOptionButton3": "ศิลปิน",
	"AddingFavorites": "กำลังเพิ่มสถานีไปยังรายการโปรด",
	"AddingStation": "กำลังเพิ่มสถานี",
	"BluetoothAudioLost": "การเชื่อมต่อระบบเสียงผ่านบลูทูธขาดหายไป",
	"Bookmark": "ตัวเลือกบุ๊กมาร์ก Pandora",
	"BookmarkAlreadyAdded": "เพิ่มบุ๊กมาร์กแล้ว",
	"BookmarkArtist": "บุ๊กมาร์กศิลปิน",
	"BookmarkSong": "บุ๊กมาร์กเพลง",
	"Buffering": "กำลังบัฟเฟอร์",
	"ConnectionLost1": "การเชื่อมต่อขาดหายไป",
	"ConnectionLost2": "ตรวจสอบให้แน่ใจว่าการเชื่อมต่อข้อมูลบนอุปกรณ์เคลื่อนที่ของคุณทำงานอย่างถูกต้อง",
	"Date": "วันที่",
	"DeleteFavorites": "กำลังลบออกจากรายการโปรด",
	"FavoritesLimitReached": "รายการโปรดถึงขีดจำกัด",
	"FromCurrentArtist": "จากศิลปินปัจจุบัน",
	"FromCurrentSong": "จากเพลงปัจจุบัน",
	"InsufficientConnectivity": "การเชื่อมต่อไม่เพียงพอที่จะเปิด Pandora",
	"InsufficientConnectivity_Alert": "การเชื่อมต่อไม่เพียงพอ",
	"InvalidLogin1": "ล็อกอินไม่ถูกต้อง",
	"InvalidLogin2": "การพิสูจน์ตัวตนล้มเหลว",
	"LicensingRestriction1": "การจำกัดในการอนุญาต",
	"LicensingRestriction2": "Pandora ไม่สามารถใช้งานนอกประเทศสหรัฐอเมริกา",
	"LicensingRestrictions_Alert": "ข้อจำกัดสิทธิ์การใช้งาน",
	"Loading": "โปรดเพิ่มสถานี",
	"MobileDevice1": "ข้อผิดพลาดของอุปกรณ์เคลื่อนที่",
	"MobileDevice2": "ตรวจสอบให้แน่ใจว่าระบบทุกอย่างทำงานกับอุปกรณ์เคลื่อนที่ของคุณอย่างถูกต้อง",
	"NoBookmark_Alert": "เราไม่สามารถเพิ่มบุ๊กมาร์ก",
	"NoCurrentStation": "สถานีถูกลบแล้ว",
	"NoDeviceConnected": "ไม่ได้เชื่อมต่ออุปกรณ์",
	"NoFavoritesStationsCreated": "ไม่มีการสร้างสถานีโปรดขึ้น",
	"NoPandora1": "ไม่พบ Pandora",
	"NoPandora2": "ตรวจสอบให้แน่ใจว่าติดตั้งแอปพลิเคชัน Pandora บนอุปกรณ์เคลื่อนที่ของคุณแล้ว",
	"NoRating_Alert": "เราไม่สามารถเพิ่มคะแนน",
	"NoStationFound1": "ไม่พบสถานี",
	"NoStationFound2": "คุณต้องติดตั้งสถานี Pandora อย่างน้อยหนึ่งสถานีก่อน",
	"Nostationsadded": "ไม่มีการเพิ่มสถานี",
	"NotSupportedVersion1": "โปรดอัพเกรดรุ่นของ Pandora บนอุปกรณ์เคลื่อนที่ของคุณ",
	"OverLimit": "ขออภัย ลิขสิทธิ์เพลงของเราบังคับให้เราจำกัดจำนวนแทร็กที่คุณสามารถข้ามได้",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "เพิ่ม/แก้ไขรายการเพลงโปรดใน Pandora ",
	"PandoraDeleteConfirmation": "แน่ใจหรือไม่ว่าคุณต้องการลบรายการเพลงโปรด {name}",
	"PandoraFavorites": "รายการเพลงโปรดใน Pandora",
	"PandoraFavoritesAvailable": "มีรายการเพลงโปรดใน Pandora อยู่แล้ว",
	"PandoraFavoritesConfirm": "คุณต้องการเปลี่ยนรายการเพลงหรือไม่",
	"PandoraFavoritesDelete": "เลือกรายการเพลงโปรดใน Pandora เพื่อลบ",
	"PandoraFavoritesMax": "คุณเลือกรายการเพลงโปรดใน Pandora ครบจำนวนสูงสุดแล้ว",
	"PandoraFavoritesMove": "เลือกรายการเพลงโปรดใน Pandora เพื่อย้าย",
	"PandoraFavoritesReplace": "แทนที่ด้วย {active station}",
	"PandoraFavoritesSelect": "เลือกรายการเพลงโปรดใน Pandora เพื่อเปลี่ยน",
	"PandoraMaintinence": "ขออภัย ขณะนี้ Pandora กำลังอยู่ระหว่างการบำรุงรักษา",
	"PandoraMoveFavorite": "ย้าย",
	"PandoraReplaceButtonText": "เปลี่ยน",
	"PandoraSelectPosition": "เลือกตำแหน่ง",
	"Quit": "ออก",
	"SelectStation": "สถานีการเล่นก่อนหน้านี้ถูกลบออกไป",
	"Setup": "การติดตั้ง",
	"SetupBluetoothDeviceNow": "ติดตั้งอุปกรณ์บลูทูธเดี๋ยวนี้หรือไม่",
	"Shuffle": "สลับ",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "เรียงตาม",
	"SortByAZ": "เรียงตาม: A-Z",
	"SortByDate": "เรียงตาม: วันที่",
	"StationCreationError": "เกิดข้อผิดพลาดขณะสร้างสถานี",
	"StationLimitRecahed": "เต็มขีดจำกัดจำนวนสถานีแล้ว",
	"StationList": "รายการสถานี",
	"StationListTab": "รายการโปรด",
	"ThumbsDown": "คว่ำหัวแม่มือลง",
	"ThumbsUp": "ยกหัวแม่มือขึ้น",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "เมนูความบันเทิง",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "ไม่สามารถเพิ่มบุ๊กมาร์ก",
	"sbnConnectionError": "การเชื่อมต่อเครือข่ายขาดหายไป",
	"sbnConnectivityError": "การเชื่อมต่อไม่เพียงพอ",
	"sbnMobileDeviceError": "ข้อผิดพลาดของอุปกรณ์เคลื่อนที่",
	"sbnOverLimit": "ถึงขีดจำกัดการข้าม",
	"sbnPandoraMaintErr": "ข้อผิดพลาดในการบำรุงรักษา Pandora",
	"sbnRatingFailed": "ไม่สามารถเพิ่มคะแนน",
	"sbnStationDeleted": "ไม่มีสถานีปัจจุบัน",
	"skip_Tooltip": "ข้าม",
};

framework.registerAppDictLoaded("pandora", "th_TH");