var Localization_pandoraAppDict_da_DK = {
	//"stringId" : "localString"
	"AZ": "A-Å",
	"AddBookmark_Alert": "Tilføjer bogmærke",
	"AddGenreStation": "Tilføj Station: {genreStation}",
	"AddStation": "Tilføj station",
	"AddStationOption": "Opret en ny station:",
	"AddStationOptionButton3": "Kunstner",
	"AddingFavorites": "Tilføjer station til Favoritter",
	"AddingStation": "Tilføjer station",
	"BluetoothAudioLost": "Forbindelse til Bluetooth-audio mistet",
	"Bookmark": "Pandora bogmærke",
	"BookmarkAlreadyAdded": "Bogmærke var alle tilføjet.",
	"BookmarkArtist": "Bogmærk kunstner",
	"BookmarkSong": "Bogmærk sang",
	"Buffering": "Buffering",
	"ConnectionLost1": "Forbindelse mistet",
	"ConnectionLost2": "Kontrollér, at dataforbindelsen på din mobilenhed virker korrekt.",
	"Date": "Dato",
	"DeleteFavorites": "Fjerner station fra Favoritter",
	"FavoritesLimitReached": "Grænsen Favorit er nået",
	"FromCurrentArtist": "Fra aktuel kunstner",
	"FromCurrentSong": "Fra aktuel sang",
	"InsufficientConnectivity": "Utilstrækkelig forbindelse til at åbne Pandora.",
	"InsufficientConnectivity_Alert": "Utilstrækkelig forbindelse",
	"InvalidLogin1": "Forkert brugernavn",
	"InvalidLogin2": "Godkendelse mislykkedes.",
	"LicensingRestriction1": "Licensbegrænsning",
	"LicensingRestriction2": "Pandora er ikke tilgængelig uden for USA.",
	"LicensingRestrictions_Alert": "Licensbegrænsninger",
	"Loading": "Tilføj en station",
	"MobileDevice1": "Fejl i mobilenhed",
	"MobileDevice2": "Kontrollér, at alt virker korrekt på din mobilenhed.",
	"NoBookmark_Alert": "Vi kunne ikke tilføje bog.",
	"NoCurrentStation": "Station fjernet",
	"NoDeviceConnected": "Der er ikke tilsluttet nogen enhed",
	"NoFavoritesStationsCreated": "Ingen yndlingsstationer oprettet.",
	"NoPandora1": "Pandora blev ikke fundet",
	"NoPandora2": "Kontrollér, at Pandora-app'en er installeret på din mobilenhed.",
	"NoRating_Alert": "Vi kunne ikke tilføje bed.",
	"NoStationFound1": "Der blev ikke fundet stationer",
	"NoStationFound2": "Du skal have mindst én Pandora-station indstillet først.",
	"Nostationsadded": "Ingen stationer blev tilføjet.",
	"NotSupportedVersion1": "Opgradér venligst Pandora-versionen på din mobilenhed.",
	"OverLimit": "Vi beklager, vores musiklicenser pålægger os at begrænse antallet af numre, du kan springe over.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Tilføj/rediger Pandora-favoritter",
	"PandoraDeleteConfirmation": "Er du sikker på, at du vil slette favoritten {name}?",
	"PandoraFavorites": "Pandora-favoritter",
	"PandoraFavoritesAvailable": "Pandora-favorit findes allerede",
	"PandoraFavoritesConfirm": "Vil du erstatte en?",
	"PandoraFavoritesDelete": "Vælg den Pandora-favorit, der skal slettes",
	"PandoraFavoritesMax": "Du har nået det maksimale antal Pandora-favoritter.",
	"PandoraFavoritesMove": "Vælg den Pandora-favorit, der skal flyttes",
	"PandoraFavoritesReplace": "Erstat med  {active station}",
	"PandoraFavoritesSelect": "Vælg den Pandora-favorit, der skal erstattes",
	"PandoraMaintinence": "Der bliver desværre udført vedligeholdelse på Pandora i øjeblikket.",
	"PandoraMoveFavorite": "Flyt",
	"PandoraReplaceButtonText": "Erstat",
	"PandoraSelectPosition": "Vælg position",
	"Quit": "Afslut",
	"SelectStation": "Den forrige afspillede station blev fjernet",
	"Setup": "Opsætning",
	"SetupBluetoothDeviceNow": "Opsæt Bluetooth-enhed nu?",
	"Shuffle": "Bland",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Sortér efter",
	"SortByAZ": "Sorter efter: A-Å",
	"SortByDate": "Sorter efter: dato",
	"StationCreationError": "Der opstod en fejl under oprettelse af en station.",
	"StationLimitRecahed": "Grænsen for Station er nået",
	"StationList": "Stationsliste",
	"StationListTab": "Foretrukne",
	"ThumbsDown": "Tommelfinger nedad",
	"ThumbsUp": "Tommelfinger opad",
	"VrHelp_BookmarkOptions_Help_Left1": "Bogmærke for kunstner",
	"VrHelp_BookmarkOptions_Help_Left2": "Bogmærke for sang",
	"VrHelp_NowPlaying_Help_Left1": "Underholdning",
	"VrHelp_NowPlaying_Help_Left2": "Stationsliste",
	"VrHelp_NowPlaying_Help_Left3": "Tommelfinger nedad",
	"VrHelp_NowPlaying_Help_Left4": "Tommelfinger opad",
	"VrHelp_NowPlaying_Help_Left5": "Bogmærk sang",
	"VrHelp_NowPlaying_Help_Right1": "Bogmærk kunstner",
	"VrHelp_NowPlaying_Help_Right2": "Afspil/Pause",
	"VrHelp_NowPlaying_Help_Right3": "Næste",
	"VrHelp_NowPlaying_Help_Right4": "LydIndstillinger",
	"VrHelp_SortBy_Help_Left1": "Dato",
	"VrHelp_SortBy_Help_Left2": "A til Z",
	"entMenu": "Underholdningsmenu",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Kunne ikke tilføje bogmærke",
	"sbnConnectionError": "Forbindelse til netværket mistet",
	"sbnConnectivityError": "Utilstrækkelig forbindelse",
	"sbnMobileDeviceError": "Fejl i mobilenhed",
	"sbnOverLimit": "Grænse for \"spring over\" nået",
	"sbnPandoraMaintErr": "Fejl i vedligeholdelse af Pandora",
	"sbnRatingFailed": "Kunne ikke tilføje bedømmelse",
	"sbnStationDeleted": "Ingen nuværende station",
	"skip_Tooltip": "Spring over",
};

framework.registerAppDictLoaded("pandora", "da_DK");