var Localization_pandoraAppDict_sk_SK = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Pridáva sa záložka",
	"AddGenreStation": "Pridať stanicu: {genreStation}",
	"AddStation": "Pridať stanicu",
	"AddStationOption": "Vytvoriť novú stanicu:",
	"AddStationOptionButton3": "Umelec",
	"AddingFavorites": "Stanica sa pridáva medzi obľúbené",
	"AddingStation": "Pridáva sa stanica",
	"BluetoothAudioLost": "Bluetooth audio strate spojenia",
	"Bookmark": "Možnosť záložky Pandora",
	"BookmarkAlreadyAdded": "Záložka už bola pridaná.",
	"BookmarkArtist": "Záložka k interpretovi",
	"BookmarkSong": "Záložka k skladbe",
	"Buffering": "Buferovanie",
	"ConnectionLost1": "Pripojenie prerušené",
	"ConnectionLost2": "Presvedčite sa, že dátové pripojenie na vašom mobilnom zariadení správne funguje.",
	"Date": "Dátum",
	"DeleteFavorites": "Stanica sa odstraňuje z obľúbených",
	"FavoritesLimitReached": "Dosiahli limit obľúbených",
	"FromCurrentArtist": "Od aktuálneho interpréta",
	"FromCurrentSong": "Od aktuálnej skladby",
	"InsufficientConnectivity": "Nedostatočné pripojenie na otvorenie aplikácie Pandora.",
	"InsufficientConnectivity_Alert": "Nedostatočné pripojenie",
	"InvalidLogin1": "Neplatné prihlásenie",
	"InvalidLogin2": "Autentifikácia zlyhala.",
	"LicensingRestriction1": "Licenčné obmedzenie",
	"LicensingRestriction2": "Mimo Spojených štátov nie je aplikácia Pandora dostupná.",
	"LicensingRestrictions_Alert": "Obmedzenie licencie",
	"Loading": "Pridajte, prosím, stanicu.",
	"MobileDevice1": "Chyba mobilného zariadenia",
	"MobileDevice2": "Presvedčite sa, že na vašom mobilnom zariadení všetko správne funguje.",
	"NoBookmark_Alert": "Nemohli sme pridať značku",
	"NoCurrentStation": "Stanica bola odstránená",
	"NoDeviceConnected": "Nie je pripojené žiadne zariadenie",
	"NoFavoritesStationsCreated": "Neboli vytvorené žiadne obľúbené stanice.",
	"NoPandora1": "Aplikácia Pandora sa nenašla",
	"NoPandora2": "Presvedčite sa, že aplikácia Pandora je už na vašom mobilnom zariadení nainštalovaná.",
	"NoRating_Alert": "Nemohli sme pridať hodn.",
	"NoStationFound1": "Nenašla sa žiadna stanica",
	"NoStationFound2": "Najprv musíte nastaviť najmenej jednu stanicu aplikácie Pandora.",
	"Nostationsadded": "Neboli pridané žiadne stanice.",
	"NotSupportedVersion1": "Prosíme, aktualizujte verziu Pandory na vašom mobilnom zariadení.",
	"OverLimit": "Naše hudobné licencie nás, žiaľ, nútia limitovať počet skladieb, ktoré môžete preskočiť.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Pridať alebo upraviť obľúbené položky rádia Pandora ",
	"PandoraDeleteConfirmation": "Naozaj chcete odstrániť obľúbenú položku {name}?",
	"PandoraFavorites": "Obľúbené položky rádia Pandora",
	"PandoraFavoritesAvailable": "Obľúbená položka rádia Pandora je už k dispozícii",
	"PandoraFavoritesConfirm": "Chceli by ste jednu nahradiť?",
	"PandoraFavoritesDelete": "Vybrať obľúbenú položku rádia Pandora, ktorú chcete odstrániť",
	"PandoraFavoritesMax": "Dosiahli ste maximálny počet obľúbených položiek rádia Pandora.",
	"PandoraFavoritesMove": "Vybrať obľúbenú položku rádia Pandora, ktorú chcete presunúť",
	"PandoraFavoritesReplace": "Nahradiť položkou {active station}",
	"PandoraFavoritesSelect": "Vybrať obľúbenú položku rádia Pandora, ktorú chcete nahradiť",
	"PandoraMaintinence": "Je nám ľúto, na Pandore sa momentálne vykonáva údržba.",
	"PandoraMoveFavorite": "Presunúť",
	"PandoraReplaceButtonText": "Nahradiť",
	"PandoraSelectPosition": "Vybrať pozíciu",
	"Quit": "Ukončiť",
	"SelectStation": "Predchádzajúca prehrávaná stanica bola odstránená",
	"Setup": "Nastavenie",
	"SetupBluetoothDeviceNow": "Nastaviť Bluetooth zariadenie teraz?",
	"Shuffle": "Shuffle",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Triediť podľa",
	"SortByAZ": "Triediť podľa: A-Z",
	"SortByDate": "Triediť podľa: Dátum",
	"StationCreationError": "Pri vytváraní stanice sa vyskytla chyba.",
	"StationLimitRecahed": "Dosiahli ste limit staníc",
	"StationList": "Zoznam staníc",
	"StationListTab": "Obľúbené",
	"ThumbsDown": "Nepáči sa",
	"ThumbsUp": "Páči sa",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Ponuka zábavy",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Nemožno pridať značku",
	"sbnConnectionError": "Sieťové prepojenie prerušené",
	"sbnConnectivityError": "Nedostatočné pripojenie",
	"sbnMobileDeviceError": "Chyba mobilného zariadenia",
	"sbnOverLimit": "Preskočiť dosiahnutý limit",
	"sbnPandoraMaintErr": "Chyba údržby aplikácie Pandora",
	"sbnRatingFailed": "Nemožno pridať hodnotenie",
	"sbnStationDeleted": "Žiadna aktuálna stanica",
	"skip_Tooltip": "Preskočiť",
};

framework.registerAppDictLoaded("pandora", "sk_SK");