var Localization_pandoraAppDict_pl_PL = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "Dodawanie zakładki",
	"AddGenreStation": "Dodaj stację: {genreStation}",
	"AddStation": "Dodaj stację",
	"AddStationOption": "Utwórz nową stację:",
	"AddStationOptionButton3": "Artysta",
	"AddingFavorites": "Dodawanie stacji do Ulubionych",
	"AddingStation": "Dodawanie stacji",
	"BluetoothAudioLost": "Połączenie sprzętu audio Bluetooth utracone",
	"Bookmark": "Opcje zakładek aplikacji Pandora",
	"BookmarkAlreadyAdded": "Zakładka została dodana.",
	"BookmarkArtist": "Dodaj wykonawcę do zakładek",
	"BookmarkSong": "Dodaj utwór do zakładek",
	"Buffering": "Buforowanie",
	"ConnectionLost1": "Połączenie utracone",
	"ConnectionLost2": "Sprawdź, czy połączenie danych na urządzeniu przenośnym działa prawidłowo.",
	"Date": "Data",
	"DeleteFavorites": "Usuwanie stacji z Ulubionych",
	"FavoritesLimitReached": "Osiągnięto limit Ulubionych",
	"FromCurrentArtist": "Od aktualnego wykonawcy",
	"FromCurrentSong": "Od aktualnej piosenki",
	"InsufficientConnectivity": "Niewystarczająca przepustowość, aby otworzyć aplikację Pandora.",
	"InsufficientConnectivity_Alert": "Niewystarczająca przepustowość",
	"InvalidLogin1": "Nieprawidłowy login",
	"InvalidLogin2": "Nieudane uwierzytelnienie ",
	"LicensingRestriction1": "Ograniczenie licencjonowania",
	"LicensingRestriction2": "Aplikacja Pandora jest dostępna tylko na terenie Stanów Zjednoczonych.",
	"LicensingRestrictions_Alert": "Ograniczenia gwarancji",
	"Loading": "Proszę dodać stację.",
	"MobileDevice1": "Błąd urządzenia przenośnego.",
	"MobileDevice2": "Sprawdź, czy urządzenie przenośne działa prawidłowo.",
	"NoBookmark_Alert": "Nie można dodać zakładki.",
	"NoCurrentStation": "Usunięto stację",
	"NoDeviceConnected": "Brak podłączonego urządzenia",
	"NoFavoritesStationsCreated": "Nie utworzono ulubionych stacji.",
	"NoPandora1": "Nie znaleziono aplikacji Pandora.",
	"NoPandora2": "Sprawdź, czy aplikacja Pandora jest już zainstalowana na urządzeniu przenośnym.",
	"NoRating_Alert": "Nie można dodać oceny.",
	"NoStationFound1": "Nie znaleziono stacji.",
	"NoStationFound2": "Musisz najpierw ustawić co najmniej jedną stację w aplikacji Pandora.",
	"Nostationsadded": "Nie dodano stacji.",
	"NotSupportedVersion1": "Zaktualizuj aplikację Pandora na urządzeniu przenośnym.",
	"OverLimit": "Niestety, zgodnie z warunkami licencji muzyki liczba ścieżek, które można pominąć, jest ograniczona.",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "Dodaj/edytuj ulubione stacje Pandora",
	"PandoraDeleteConfirmation": "Czy na pewno chcesz usunąć stację {name} z ulubionych?",
	"PandoraFavorites": "Ulubione stacje Pandora",
	"PandoraFavoritesAvailable": "Ulubiona stacja Pandora jest już dostępna.",
	"PandoraFavoritesConfirm": "Czy chcesz zastąpić jedną z zapisanych?",
	"PandoraFavoritesDelete": "Wybierz ulubioną stację Pandora do usunięcia.",
	"PandoraFavoritesMax": "Osiągnięto maksymalną liczbę ulubionych stacji Pandora.",
	"PandoraFavoritesMove": "Wybierz ulubioną stację Pandora do przeniesienia.",
	"PandoraFavoritesReplace": "Zastąp stacją: {active station}",
	"PandoraFavoritesSelect": "Wybierz ulubioną stację Pandora do zastąpienia.",
	"PandoraMaintinence": "Aktualnie w serwisie Pandora trwają prace konserwacyjne.",
	"PandoraMoveFavorite": "Przenieś",
	"PandoraReplaceButtonText": "Zastąp",
	"PandoraSelectPosition": "Wybierz pozycję",
	"Quit": "Zakończ",
	"SelectStation": "Usunięto poprzednio odtwarzaną stację.",
	"Setup": "Ustawienia",
	"SetupBluetoothDeviceNow": "Skonfigurować teraz urządzenie Bluetooth?",
	"Shuffle": "Odtwarzanie losowe",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "Sortuj według",
	"SortByAZ": "Sortuj wg: A-Z",
	"SortByDate": "Sortuj wg: data",
	"StationCreationError": "Błąd podczas tworzenia stacji.",
	"StationLimitRecahed": "Osiągnięto limit stacji",
	"StationList": "Lista stacji",
	"StationListTab": "Ulubione",
	"ThumbsDown": "Nie lubię tego.",
	"ThumbsUp": "Lubię to.",
	"VrHelp_BookmarkOptions_Help_Left1": "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5": "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1": "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3": "Next",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
	"VrHelp_SortBy_Help_Left1": "Date",
	"VrHelp_SortBy_Help_Left2": "A to Z",
	"entMenu": "Menu funkcji rozrywki",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "Nie można dodać zakładki.",
	"sbnConnectionError": "Połączenie sieciowe utracone",
	"sbnConnectivityError": "Niewystarczająca przepustowość",
	"sbnMobileDeviceError": "Błąd urządzenia przenośnego.",
	"sbnOverLimit": "Osiągnięto limit pomijania",
	"sbnPandoraMaintErr": "Błąd konserwacji aplikacji Pandora.",
	"sbnRatingFailed": "Nie można dodać oceny.",
	"sbnStationDeleted": "Brak bieżącej stacji",
	"skip_Tooltip": "Dalej",
};

framework.registerAppDictLoaded("pandora", "pl_PL");