var Localization_pandoraAppDict_zh_TW = {
	//"stringId" : "localString"
	"AZ": "A-Z",
	"AddBookmark_Alert": "新增書籤",
	"AddGenreStation": "添加電台: {genreStation}",
	"AddStation": "添加電台",
	"AddStationOption": "建立新播放台：",
	"AddStationOptionButton3": "藝術家",
	"AddingFavorites": "添加電台到我的最愛",
	"AddingStation": "正在添加電台",
	"BluetoothAudioLost": "無法連接Bluetooth音頻",
	"Bookmark": "Pandora 書籤選項",
	"BookmarkAlreadyAdded": "書籤已被添加。",
	"BookmarkArtist": "對藝術家設置書籤",
	"BookmarkSong": "對歌曲設置書籤",
	"Buffering": "正在緩衝",
	"ConnectionLost1": "無法連接",
	"ConnectionLost2": "確保您的移動裝置上的資料連接工作正常。",
	"Date": "日期",
	"DeleteFavorites": "從我的最愛中移除電台",
	"FavoritesLimitReached": "已達到我的最愛限制",
	"FromCurrentArtist": "從目前藝術家",
	"FromCurrentSong": "從目前歌曲",
	"InsufficientConnectivity": "開啟Pandora的連接訊號不足。",
	"InsufficientConnectivity_Alert": "連接不充分",
	"InvalidLogin1": "登録無效",
	"InvalidLogin2": "鑒定失敗。",
	"LicensingRestriction1": "許可限制",
	"LicensingRestriction2": "Pandora在美國以外地區不可用。",
	"LicensingRestrictions_Alert": "許可限制",
	"Loading": "請添加一個電台。",
	"MobileDevice1": "移動裝置錯誤",
	"MobileDevice2": "確保您的移動裝置一切工作正常。",
	"NoBookmark_Alert": "我們無法新增書籤",
	"NoCurrentStation": "電臺已移除",
	"NoDeviceConnected": "無設備連接",
	"NoFavoritesStationsCreated": "未建立最愛的播放台。",
	"NoPandora1": "未找到Pandora",
	"NoPandora2": "確保您的移動裝置已安裝了 Pandora 應用程式。",
	"NoRating_Alert": "我們無法新增評価",
	"NoStationFound1": "未找到電臺",
	"NoStationFound2": "您首先必須至少設定一個 Pandora 電臺。",
	"Nostationsadded": "無新增電台。",
	"NotSupportedVersion1": "請升級您的行動裝置上的 Pandora 版本。",
	"OverLimit": "對不起，我們的音樂許可迫使我們限制您可能跳過的曲目數。",
	"Pandora": "Pandora",
	"PandoraAddEditFavorites": "新增/編輯 Pandora 最愛",
	"PandoraDeleteConfirmation": "您確定要刪除最愛 {name}？",
	"PandoraFavorites": "Pandora 收藏夾",
	"PandoraFavoritesAvailable": "Pandora 最愛已經可以使用",
	"PandoraFavoritesConfirm": "您要取代其中一個嗎？",
	"PandoraFavoritesDelete": "選取要刪除的 Pandora 最愛",
	"PandoraFavoritesMax": "您已達到 Pandora 最愛的數目上限。",
	"PandoraFavoritesMove": "選取要移動的 Pandora 最愛",
	"PandoraFavoritesReplace": "取代為 {active station}",
	"PandoraFavoritesSelect": "選取要取代的 Pandora 最愛",
	"PandoraMaintinence": "對不起，Pandora目前正在維護中。",
	"PandoraMoveFavorite": "移動",
	"PandoraReplaceButtonText": "取代",
	"PandoraSelectPosition": "選取位置",
	"Quit": "放棄",
	"SelectStation": "已移除之前的播放台",
	"Setup": "設定",
	"SetupBluetoothDeviceNow": "現在就設置Bluetooth設備？",
	"Shuffle": "隨機播放",
	"ShuffleNotAddedFavorites": " ",
	"SortBy": "排序方式",
	"SortByAZ": "排序方式：A-Z",
	"SortByDate": "排序方式：日期",
	"StationCreationError": "創建電台時出現了一個錯誤。",
	"StationLimitRecahed": "已達到電台限制",
	"StationList": "電台列表",
	"StationListTab": "收藏夾",
	"ThumbsDown": "不喜歡",
	"ThumbsUp": "喜歡",
	"VrHelp_BookmarkOptions_Help_Left1": "藝術家",
	"VrHelp_BookmarkOptions_Help_Left2": "歌曲",
	"VrHelp_NowPlaying_Help_Left1": "更改來源",
	"VrHelp_NowPlaying_Help_Left2": "電台列表",
	"VrHelp_NowPlaying_Help_Left3": "拇指朝下",
	"VrHelp_NowPlaying_Help_Left4": "拇指朝上",
	"VrHelp_NowPlaying_Help_Left5": "對歌曲設置書籤",
	"VrHelp_NowPlaying_Help_Right1": "對藝術家設置書籤",
	"VrHelp_NowPlaying_Help_Right2": "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3": "跳過",
	"VrHelp_NowPlaying_Help_Right4": "聲音設置",
	"VrHelp_SortBy_Help_Left1": "日期",
	"VrHelp_SortBy_Help_Left2": "A 到 Z",
	"entMenu": "娛樂功能表",
	"sbNameId": "Pandora",
	"sbnBookmarkFailed": "無法新增書籤",
	"sbnConnectionError": "網路無法連接",
	"sbnConnectivityError": "連接訊號不足",
	"sbnMobileDeviceError": "移動裝置錯誤",
	"sbnOverLimit": "達到跳過限制",
	"sbnPandoraMaintErr": "Pandora維護錯誤",
	"sbnRatingFailed": "無法新增評価",
	"sbnStationDeleted": "目前無電臺",
	"skip_Tooltip": "跳過",
};

framework.registerAppDictLoaded("pandora", "zh_TW");