var Localization_idmAppDict_nl_NL = {
    //"stringId" : "localString"
    "SwitchView" : "Volgend scherm",
    "simpleMode" : "i-DM simpele modus",
    "scoreTransition" : "Score overgang",
    "driver" : "Chauffeur",
    "currScore" : "Huidige score",
    "currDrvTrnd" : "Huidige rijstijl",
    "avgScore" : "Gem. score",
    "trainingMode" : "i-DM trainingsmodus",
    "settingIDM" : "i-DM",
    "settings" : "Instellingen",
    "HidePanel" : "Toetsen verbergen",
    "ApplicationsMenu" : "Applicaties",
    "SelectSettings" : "Instellingen selecteren",
    "meterAmbientDisplay" : "Display Buitentemp.",
    "endingScreen" : "Eindscherm",
    "stageUp" : "Stage Up!",
    "AmbienceRetryMsg" : "Wijzigen instelling Meter Ambient Display mislukt. Wilt u het opnieuw proberen?",
    "RetryBtn" : "Opnieuw proberen",
    "CancelBtn" : "Annuleren",
    "avg" : "Gemiddelde",
    "current" : "Huidige",
    "Excellent" : "Uitstekend",
    "VeryGood" : "Erg goed",
    "Good" : "Goed",
    "GoodWork" : "Goed werk",
    "DroveAsExpected" : "Deze keer reed u precies als verwacht. Laten we nog een rit maken.",
    "HaveAFeel" : "U hebt het in uw vingers. Ga zo door.",
    "HangOfIt" : "U krijgt de slag te pakken. Ga zo door.",
    "NoFrequentAccel" : "Minder vaak optrekken resulteert in een soepelere bediening van het voertuig.",
    "NoFrequentBrake" : "Minder vaak remmen resulteert in een soepelere bediening van het voertuig.",
    "NoFrequentSteer" : "Minder vaak onnodig sturen resulteert in een soepelere bediening van het voertuig.",
    "AccelSmoothly" : "Rustig optrekken verhoogt het rijcomfort.",
    "DecelSmoothly" : "Rustig afremmen verhoogt het rijcomfort.",
    "GentleSteering" : "Rustig sturen verhoogt het rijcomfort.",
    "OperateClutch" : "Rustig en correct gebruik van de koppeling verhoogt het rijcomfort.",
    "GoodJobNotEnoughData" : "Goed gedaan! De huidige rit bevatte te weinig gegevens voor een diagnose.",
    "brake" : "Rem",
    "steer" : "Sturen",
    "acc" : "Versnelling",
    "min" : "min",
    "minsago" : "minuten geleden",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "score",
    "drvAdvice" : "Rij-advies",
};

framework.registerAppDictLoaded("idm", "nl_NL");