var Localization_idmAppDict_th_TH = {
    //"stringId" : "localString"
    "SwitchView" : "หน้าจอถัดไป",
    "simpleMode" : "โหมดธรรมดาของ i-DM",
    "scoreTransition" : "การเปลี่ยนคะแนน",
    "driver" : "คนขับ",
    "currScore" : "คะแนนปัจจุบัน",
    "currDrvTrnd" : "แนวโน้มการขับรถปัจจุบัน",
    "avgScore" : "คะแนนเฉลี่ย",
    "trainingMode" : "โหมดการสอนของ i-DM",
    "settingIDM" : "i-DM",
    "settings" : "การตั้งค่า",
    "HidePanel" : "ซ่อนปุ่ม",
    "ApplicationsMenu" : "แอปพลิเคชัน",
    "SelectSettings" : "เลือกการตั้งค่า",
    "meterAmbientDisplay" : "จอแสดงบริเวณโดยรอบ",
    "endingScreen" : "หน้าจอสิ้นสุด",
    "stageUp" : "ขึ้นไปอีกขั้นหนึ่ง!",
    "AmbienceRetryMsg" : "ไม่สามารถเปลี่ยนการตั้งค่าจอแสดงบริเวณโดยรอบ คุณต้องการลองอีกครั้งหรือไม่",
    "RetryBtn" : "ลองใหม่",
    "CancelBtn" : "ยกเลิก",
    "avg" : "เฉลี่ย",
    "current" : "ปัจจุบัน",
    "Excellent" : "เยี่ยม",
    "VeryGood" : "ดีมาก",
    "Good" : "ดี",
    "GoodWork" : "ทำได้ดี",
    "DroveAsExpected" : "ครั้งนี้ คุณขับรถได้ตามที่คาดหมาย ช่วยพาไปขับรถอีก",
    "HaveAFeel" : "คุณเริ่มรู้สึกคุ้นเคยแล้ว พยายามต่อไป",
    "HangOfIt" : "คุณเริ่มจับทางได้แล้ว พยายามต่อไป",
    "NoFrequentAccel" : "การควบคุมไม่ให้เร่งเครื่องบ่อยครั้งจะทำให้รถวิ่งได้ราบรื่นขึ้น",
    "NoFrequentBrake" : "การควบคุมไม่ให้เบรกบ่อยครั้งจะทำให้รถวิ่งได้ราบรื่นขึ้น",
    "NoFrequentSteer" : "การควบคุมไม่ให้หมุนพวงมาลัยบ่อยครั้งจะทำให้รถวิ่งได้ราบรื่นขึ้น",
    "AccelSmoothly" : "การค่อยๆ เร่งเครื่องด้วยความระมัดระวังจะทำให้รถวิ่งได้สบายยิ่งขึ้น",
    "DecelSmoothly" : "การค่อยๆ เบาเครื่องด้วยความระมัดระวังจะทำให้รถวิ่งได้สบายยิ่งขึ้น",
    "GentleSteering" : "การค่อยๆ หมุนพวงมาลัยด้วยความระมัดระวังจะทำให้รถวิ่งได้สบายยิ่งขึ้น",
    "OperateClutch" : "การค่อยๆ เหยียบคลัตช์อย่างถูกต้องด้วยความระมัดระวังจะทำให้รถวิ่งได้สบายยิ่งขึ้น",
    "GoodJobNotEnoughData" : "ดีมาก! การวิ่งในขณะนี้ ไม่ได้รับข้อมูลเพียงพอสำหรับการวินิจฉัย",
    "brake" : "เบรค",
    "steer" : "การขับขี่",
    "acc" : "การเร่งความเร็ว",
    "min" : "นาที",
    "minsago" : "นาทีที่ผ่านมา",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "คะแนน",
    "drvAdvice" : "คำแนะนำในการขับขี่",
};

framework.registerAppDictLoaded("idm", "th_TH");