var Localization_idmAppDict_pt_PT = {
    //"stringId" : "localString"
    "SwitchView" : "Ecrã Seguinte",
    "simpleMode" : "Modo Simples i-DM",
    "scoreTransition" : "Trans. da Pontuação",
    "driver" : "Condutor",
    "currScore" : "Pont. Actual",
    "currDrvTrnd" : "Tendência da Condução Actual",
    "avgScore" : "Média Pont.",
    "trainingMode" : "Modo Prepar. i-DM",
    "settingIDM" : "i-DM",
    "settings" : "Definições",
    "HidePanel" : "Ocultar Botões",
    "ApplicationsMenu" : "Aplicações",
    "SelectSettings" : "Seleccionar Definições",
    "meterAmbientDisplay" : "Visualiz. do Indicador Ambiente",
    "endingScreen" : "Ecrã de Fim",
    "stageUp" : "Mais Uma Fase!",
    "AmbienceRetryMsg" : "Não foi possível alterar a Definição Visualização do Indicador de Ambiente. Pretende tentar novamente?",
    "RetryBtn" : "Repetir",
    "CancelBtn" : "Cancelar",
    "avg" : "Média",
    "current" : "Actual",
    "Excellent" : "Excelente",
    "VeryGood" : "Muito Bom",
    "Good" : "Bom",
    "GoodWork" : "Bom Trabalho",
    "DroveAsExpected" : "Desta vez conduziu tal como era esperado. Conduza-me outra vez.",
    "HaveAFeel" : "Já sabe como é. Continue.",
    "HangOfIt" : "Está a apanhar-lhe o jeito. Continue.",
    "NoFrequentAccel" : "Se evitar acelerações frequentes terá uma deslocação mais estável.",
    "NoFrequentBrake" : "Se evitar travagens frequentes terá uma deslocação mais estável.",
    "NoFrequentSteer" : "Se evitar movimentos frequentes no volante terá uma deslocação mais estável.",
    "AccelSmoothly" : "Se acelerar devagar terá uma condução mais confortável.",
    "DecelSmoothly" : "Se desacelerar devagar terá uma condução mais confortável.",
    "GentleSteering" : "Se tiver uma utilização suave do volante terá uma condução mais confortável.",
    "OperateClutch" : "Se tiver uma utilização correcta da embraiagem terá uma conduç. mais confort.",
    "GoodJobNotEnoughData" : "Bom trabalho! A cond. actual não obteve dados suficien. para efect. um diagno.",
    "brake" : "Travão",
    "steer" : "Direcção",
    "acc" : "Aceleração",
    "min" : "min",
    "minsago" : "minutos atrás",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "contagem",
    "drvAdvice" : "Condução Conselho",
};

framework.registerAppDictLoaded("idm", "pt_PT");