var Localization_idmAppDict_ru_RU = {
    //"stringId" : "localString"
    "SwitchView" : "Следующий экран",
    "simpleMode" : "Простой режим i-DM",
    "scoreTransition" : "Оценка поездки",
    "driver" : "Водитель",
    "currScore" : "Теку. оценка",
    "currDrvTrnd" : "Текущий стиль вождения",
    "avgScore" : "Средняя оце",
    "trainingMode" : "обуч режим i-DM",
    "settingIDM" : "i-DM",
    "settings" : "Настройки",
    "HidePanel" : "Скрыть кнопки",
    "ApplicationsMenu" : "Приложения",
    "SelectSettings" : "Выберите настройки",
    "meterAmbientDisplay" : "Дисплей наружной обстановки",
    "endingScreen" : "Завершающий экран",
    "stageUp" : "На уровень вверх!",
    "AmbienceRetryMsg" : "Невозможно изменить настройки дисплея наружной обстановки. Хотите попробовать еще раз?",
    "RetryBtn" : "Повтор",
    "CancelBtn" : "Отмена",
    "avg" : "Средний",
    "current" : "Текущий",
    "Excellent" : "Превосходно",
    "VeryGood" : "Очень хорошо",
    "Good" : "Хорошо",
    "GoodWork" : "Отлично",
    "DroveAsExpected" : "В этот раз вы вели автомобиль как ожидалось. Попробуйте еще раз.",
    "HaveAFeel" : "Вы уже прочувствовали этот режим. Продолжайте в том же духе.",
    "HangOfIt" : "Вы уже почти освоились. Продолжайте в том же духе.",
    "NoFrequentAccel" : "Для более плавного движения воздержитесь от частых ускорений.",
    "NoFrequentBrake" : "Для более плавного движения воздержитесь от частого торможения.",
    "NoFrequentSteer" : "Для более плавного движения воздержитесь от частого перестроения.",
    "AccelSmoothly" : "Для более комфортного дви. Исполь. плавное ускорение.",
    "DecelSmoothly" : "Для более комфортного дви. Исполь. плавное тормож.",
    "GentleSteering" : "Для более комфор. движения выполняйте перест. более аккуратно.",
    "OperateClutch" : "Для более комфортного движения полностью выжимайте сцепление.",
    "GoodJobNotEnoughData" : "Отлично! В этот раз собрано недост. данных для опред. уровня подготовки.",
    "brake" : "тормоз",
    "steer" : "вождение",
    "acc" : "Yскорение",
    "min" : "мин",
    "minsago" : "минут назад",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "счет",
    "drvAdvice" : "Советы по вождению",
};

framework.registerAppDictLoaded("idm", "ru_RU");