var Localization_idmAppDict_cs_CS = {
    //"stringId" : "localString"
    "SwitchView" : "Následující zobrazení",
    "simpleMode" : "i-DM Jednod. režim",
    "scoreTransition" : "Přechodný stav",
    "driver" : "Řidič",
    "currScore" : "Aktuální stav",
    "currDrvTrnd" : "Aktuální trend",
    "avgScore" : "Průměrný stav",
    "trainingMode" : "i-DM Trénink. režim",
    "settingIDM" : "i-DM",
    "settings" : "Nastavení",
    "HidePanel" : "Skrýt tlačítka",
    "ApplicationsMenu" : "Aplikace",
    "SelectSettings" : "Vybrat nastavení",
    "meterAmbientDisplay" : "Zobrazení měření prostředí",
    "endingScreen" : "Konečné zobrazení",
    "stageUp" : "Vyšší úroveň!",
    "AmbienceRetryMsg" : "Není možné změnit nastavení zobrazení Měření prostředí. Přejete si akci zopakovat?",
    "RetryBtn" : "Zkusit znovu",
    "CancelBtn" : "Zrušit",
    "avg" : "Průměr st.",
    "current" : "Aktuální st.",
    "Excellent" : "Výborně",
    "VeryGood" : "Velmi dobře",
    "Good" : "Dobře",
    "GoodWork" : "Dostačná práce",
    "DroveAsExpected" : "Tentokrát jste jel, jak se očekávalo. Řiď mě znovu.",
    "HaveAFeel" : "Již máte cit. Jen tak dál.",
    "HangOfIt" : "Začínáte si být jistý. Jen tak dál.",
    "NoFrequentAccel" : "Omezení častého zrychlení bude mít za následek lepší provoz.",
    "NoFrequentBrake" : "Omezení častého brždění bude mít za následek lepší provoz.",
    "NoFrequentSteer" : "Omezení častého zatáčení bude mít za následek lepší provoz.",
    "AccelSmoothly" : "Péče o pozvolné zrychlení bude mít za následek pohodlnější provoz.",
    "DecelSmoothly" : "Péče o pozvolné zpomalení bude mít za následek pohodlnější provoz.",
    "GentleSteering" : "Péče o pozvolné zatáčení bude mít za následek pohodlnější provoz.",
    "OperateClutch" : "Péče o správné použití spojky bude mít za následek pohodlnější provoz.",
    "GoodJobNotEnoughData" : "Dobrá práce! Současný chod nezískal dostatek dat pro stanovení diagnózy.",
    "brake" : "Brzda",
    "steer" : "řízení",
    "acc" : "Zrychlení",
    "min" : "min",
    "minsago" : "minutami",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "hodnocení",
    "drvAdvice" : "Jízda v zimě",
};

framework.registerAppDictLoaded("idm", "cs_CS");