var Localization_idmAppDict_et_EE = {
    //"stringId" : "localString"
    "SwitchView" : "Järgmine kuva",
    "simpleMode" : "i-DM-i lihtrežiim",
    "scoreTransition" : "Tulemuse ülekanne",
    "driver" : "Juht",
    "currScore" : "Praeg. Tulem.",
    "currDrvTrnd" : "Praegune sõidutrend",
    "avgScore" : "Keskm. tulem.",
    "trainingMode" : "i-DM-i harjutusrežiim",
    "settingIDM" : "i-DM",
    "settings" : "Sätted",
    "HidePanel" : "Peida nupud",
    "ApplicationsMenu" : "Rakendused",
    "SelectSettings" : "Valige sätted",
    "meterAmbientDisplay" : "Ümbruse mõõtandmete kuvamine",
    "endingScreen" : "Lõpetamiskuva",
    "stageUp" : "Järgmine etapp!",
    "AmbienceRetryMsg" : "Ümbruse mõõtandmete kuvamise sätet ei saanud muuta. Kas soovite uuesti proovida?",
    "RetryBtn" : "Proovi uuesti",
    "CancelBtn" : "Tühista",
    "avg" : "Keskmine",
    "current" : "Praegune",
    "Excellent" : "Suurepärane",
    "VeryGood" : "Väga hea",
    "Good" : "Hea",
    "GoodWork" : "Tubli töö",
    "DroveAsExpected" : "Seekord sõitsite nii, nagu peab. Lähme uuesti sõitma.",
    "HaveAFeel" : "Olete juba lainel. Laske samamoodi edasi.",
    "HangOfIt" : "Hakkate juba pihta saama. Laske samamoodi edasi.",
    "NoFrequentAccel" : "Sagedastest kiirendustest hoidumine muudaks sõidu sujuvamaks.",
    "NoFrequentBrake" : "Sagedastest pidurdustest hoidumine muudaks sõidu sujuvamaks.",
    "NoFrequentSteer" : "Sagedastest roolikeeramistest hoidumine muudaks sõidu sujuvamaks.",
    "AccelSmoothly" : "Sujuvam kiirendamine teeb sõidu mugavamaks.",
    "DecelSmoothly" : "Sujuvam pidurdamine teeb sõidu mugavamaks.",
    "GentleSteering" : "Sujuvam roolikeeramine teeb sõidu mugavamaks.",
    "OperateClutch" : "Siduri õige kasutamine teeb sõidu mugavamaks.",
    "GoodJobNotEnoughData" : "Tubli töö! Praegusest sõidust ei saanud diagnoosimiseks piisavalt andmeid.",
    "brake" : "Pidur",
    "steer" : "Rooliv",
    "acc" : "Kiirendus",
    "min" : "min",
    "minsago" : "minutit tagasi",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "tulemus",
    "drvAdvice" : "Sõidu Nõuanded",
};

framework.registerAppDictLoaded("idm", "et_EE");