var Localization_idmAppDict_ar_SA = {
    //"stringId" : "localString"
    "SwitchView" : "الشاشة التالية",
    "simpleMode" : "وضع i-DM البسيط",
    "scoreTransition" : "انتقال النتيجة الإجمالية",
    "driver" : "السائق",
    "currScore" : "النتيجة الإجمالية الحالية",
    "currDrvTrnd" : "اتجاه القيادة الحالي",
    "avgScore" : "متوسط النتيجة الإجمالية",
    "trainingMode" : "وضع تدريب i-DM",
    "settingIDM" : "i-DM",
    "settings" : "الإعدادات",
    "HidePanel" : "إخفاء الأزرار",
    "ApplicationsMenu" : "التطبيقات",
    "SelectSettings" : "حدد التطبيقات",
    "meterAmbientDisplay" : "شاشة بيانات العداد",
    "endingScreen" : "شاشة الإنهاء",
    "stageUp" : "مرحلة لأعلى!",
    "AmbienceRetryMsg" : "لم يتمكن من تغيير إعداد شاشة بيانات العداد. هل ترغب في إعادة المحاولة؟",
    "RetryBtn" : "أعد المحاولة",
    "CancelBtn" : "إلغاء",
    "avg" : "متوسط",
    "current" : "حالي",
    "Excellent" : "ممتاز",
    "VeryGood" : "جيد جدًا",
    "Good" : "جيد",
    "GoodWork" : "عمل جيد",
    "DroveAsExpected" : "لقد قمت بالقيادة هذه المرة كما هو متوقع. قُدني مرة أخرى. ",
    "HaveAFeel" : "لديك بالفعل شعور تجاه ذلك. حافظ عليه.",
    "HangOfIt" : "أنت تتولى زمامها. حافظ عليه.",
    "NoFrequentAccel" : "كبحك لغمار نفسك من زيادة السرعة بشكل متكرر سينجم عنه انطلاقًا أكثر سلاسة.",
    "NoFrequentBrake" : "كبحك لغمار نفسك من الفرملة المتكررة سينجم عنه انطلاقًا أكثر سلاسة.",
    "NoFrequentSteer" : "كبحك لغمار نفسك من التوجيه المتكرر لدفة القيادة سينجم عنه انطلاقًا أكثر سلاسة.",
    "AccelSmoothly" : "الاهتمام بزيادة السرعة بسلاسة سينجم عنه المزيد من الانطلاق المريح.",
    "DecelSmoothly" : "الاهتمام بخفض السرعة بسلاسة سينجم عنه المزيد من الانطلاق المريح.",
    "GentleSteering" : "الاهتمام بإدارة دفة القيادة بلطف سينجم عنه المزيد من الانطلاق المريح.",
    "OperateClutch" : "الاهتمام بإدارة الدبرياج على النحو الصحيح سينجم عنه المزيد من الانطلاق المريح.",
    "GoodJobNotEnoughData" : "عمل جيد! لم يحصل الاتجاه الحالي على بيانات كافية من التشخيص.",
    "brake" : "فرامل",
    "steer" : "عجلة القيادة",
    "acc" : "تسارع",
    "min" : "دقيقة",
    "minsago" : "منذ دقائق",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "علامة",
    "drvAdvice" : "إرشادات القيادة",
};

framework.registerAppDictLoaded("idm", "ar_SA");