var Localization_idmAppDict_fr_CN = {
    //"stringId" : "localString"
    "SwitchView" : "Écran suivant.",
    "simpleMode" : "Mode simple i-DM",
    "scoreTransition" : "Transition de score",
    "driver" : "Conducteur",
    "currScore" : "Score actuel",
    "currDrvTrnd" : "Tendance de conduite actuelle",
    "avgScore" : "Score moyen",
    "trainingMode" : "Mode formation i-DM",
    "settingIDM" : "i-DM",
    "settings" : "Paramètres",
    "HidePanel" : "Masquer les touches",
    "ApplicationsMenu" : "Applications",
    "SelectSettings" : "Sélectionner paramètres",
    "meterAmbientDisplay" : "Affichage mesures ambiantes",
    "endingScreen" : "Dernier écran",
    "stageUp" : "Étape précédente !",
    "AmbienceRetryMsg" : "Impossible de changer les paramètres de l’affichage des mesures ambiantes. Voulez-vous réessayer ?",
    "RetryBtn" : "Réessayer",
    "CancelBtn" : "Annuler",
    "avg" : "Moyenne",
    "current" : "En cours",
    "Excellent" : "Excellent",
    "VeryGood" : "Très bien",
    "Good" : "Bien",
    "GoodWork" : "Bon travail",
    "DroveAsExpected" : "Cette fois, vous avez conduit comme prévu. Emmenez-moi faire un tour à nouveau.",
    "HaveAFeel" : "Vous comprenez déjà ce qui est nécessaire. Continuez.",
    "HangOfIt" : "Vous prenez le coup. Continuez.",
    "NoFrequentAccel" : "Évitez les accélérations fréquentes pour un fonctionnement plus fluide.",
    "NoFrequentBrake" : "Évitez les freinages fréquents pour un fonctionnement plus fluide.",
    "NoFrequentSteer" : "Évitez les coups de volants fréquents pour un fonctionnement plus fluide.",
    "AccelSmoothly" : "Accélérez en douceur pour une conduite plus agréable.",
    "DecelSmoothly" : "Décélérez en douceur pour une conduite plus agréable.",
    "GentleSteering" : "Tournez le volant en douceur pour une conduite plus agréable.",
    "OperateClutch" : "Changez de vitesse en douceur pour une conduite plus agréable.",
    "GoodJobNotEnoughData" : "Bravo ! Le trajet en cours n’a pas permis de collecter suffisamment de données pour un diagnostic.",
    "brake" : "Frein",
    "steer" : "Pilotage",
    "acc" : "Accélération",
    "min" : "min",
    "minsago" : "il ya minutes",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "score",
    "drvAdvice" : "Conseils de conduite",
};

framework.registerAppDictLoaded("idm", "fr_CN");