var Localization_idmAppDict_fi_FI = {
    //"stringId" : "localString"
    "SwitchView" : "Seuraava näyttö",
    "simpleMode" : "i-DM helppo tila",
    "scoreTransition" : "Tuloksen siirto",
    "driver" : "Kuljettaja",
    "currScore" : "Nykyinen tulos",
    "currDrvTrnd" : "Nykyinen ajotapa",
    "avgScore" : "Keskim. tulos",
    "trainingMode" : "i-DM harjoittelutila",
    "settingIDM" : "i-DM",
    "settings" : "Asetukset",
    "HidePanel" : "Piilota painikkeet",
    "ApplicationsMenu" : "Sovellukset",
    "SelectSettings" : "Valitse asetukset",
    "meterAmbientDisplay" : "Mittarin  näyttö",
    "endingScreen" : "Lopetusnäyttö",
    "stageUp" : "Seuraava vaihe!",
    "AmbienceRetryMsg" : "Mittarin näytön asetusta ei voitu muuttaa. Haluatko yrittää uudelleen?",
    "RetryBtn" : "Yritä uudelleen",
    "CancelBtn" : "Peruuta",
    "avg" : "Keskiarvo",
    "current" : "Tämänhet.",
    "Excellent" : "Erinomainen",
    "VeryGood" : "Erittäin hyvä",
    "Good" : "Hyvä",
    "GoodWork" : "Hienoa työtä",
    "DroveAsExpected" : "Tällä kertaa ajoit juuri odotetun mukaisesti. Lähdetään uudelle ajelulle.",
    "HaveAFeel" : "Tämähän sujuu jo hyvin. Jatka samaa rataa.",
    "HangOfIt" : "Sinähän alat oppia. Jatka samaa rataa.",
    "NoFrequentAccel" : "Toistuvien kiihdytysten välttäminen tekee ajosta miellyttävämpää.",
    "NoFrequentBrake" : "Toistuvien jarrutusten välttäminen tekee ajosta miellyttävämpää.",
    "NoFrequentSteer" : "Toistuvien ohjausliikkeiden välttäminen tekee ajosta miellyttävämpää.",
    "AccelSmoothly" : "Tasainen kiihdytys tekee ajosta mukavampaa.",
    "DecelSmoothly" : "Vauhdin tasainen hiljentäminen tekee ajosta mukavampaa.",
    "GentleSteering" : "Pienet ohjausliikkeet tekevät ajosta mukavampaa.",
    "OperateClutch" : "Kytkimen oikea käyttö tekee ajosta mukavampaa.",
    "GoodJobNotEnoughData" : "Hienoa työtä! Tällä käyntikerralla ei saatu kerättyä riittäv. tietoja diagnoosia varten.",
    "brake" : "Jarru",
    "steer" : "Ohjaus",
    "acc" : "Kaasu",
    "min" : "min",
    "minsago" : "minuuttia sitten",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "pisteet",
    "drvAdvice" : "Ajo-ohje",
};

framework.registerAppDictLoaded("idm", "fi_FI");