var Localization_idmAppDict_lv_LV = {
    //"stringId" : "localString"
    "SwitchView" : "Nākamais ekrāns",
    "simpleMode" : "i-DM vienk. režīms",
    "scoreTransition" : "Pārejas posma vērt.",
    "driver" : "Vadītājs",
    "currScore" : "Pašreiz. Nov.",
    "currDrvTrnd" : "Pašreizējā braukšanas tendence",
    "avgScore" : "Vidējais vērt.",
    "trainingMode" : "i-DM apmāc. režīms",
    "settingIDM" : "i-DM",
    "settings" : "Iestatījumi",
    "HidePanel" : "Aizv.",
    "ApplicationsMenu" : "Lietojumprogrammas",
    "SelectSettings" : "Atlasīt iestatījumus",
    "meterAmbientDisplay" : "Ambienta mērītāja displejs",
    "endingScreen" : "Beigu ekrāns",
    "stageUp" : "Nākamais posms!",
    "AmbienceRetryMsg" : "Nevar mainīt ambienta mērītāja displeja iestatījumu. Vai vēlaties mēģināt vēlreiz?",
    "RetryBtn" : "Mēģināt vēlreiz",
    "CancelBtn" : "Atcelt",
    "avg" : "Vidēji",
    "current" : "Pašreizējais",
    "Excellent" : "Teicami",
    "VeryGood" : "Ļoti labi",
    "Good" : "Labi",
    "GoodWork" : "Labs darbs",
    "DroveAsExpected" : "Šoreiz braucāt kā gaidīts. Ņemiet mani braukšanai vēlreiz.",
    "HaveAFeel" : "Jums ir laba izjūta. Tā turpiniet!",
    "HangOfIt" : "Jūs jau saprotiet. Tā turpiniet!",
    "NoFrequentAccel" : "Lerobežojot biežus paātrināj., nodrošiniet vienmērīgāku braukšanu.",
    "NoFrequentBrake" : "Ierobežojot biežu bremzēšanu, nodrošiniet vienmērīgāku braukšanu.",
    "NoFrequentSteer" : "Ierobežojot biežu stūrēšanu, nodrošiniet vienmērīgāku braukšanu.",
    "AccelSmoothly" : "Cenšoties paātrināt vienmērīgi, nodrošiniet ērtāku braukšanu.",
    "DecelSmoothly" : "Cenšoties samazināt ātrumu vienmērīgi, nodrošiniet ērtāku braukšanu.",
    "GentleSteering" : "Cenšoties stūrēt ar maigām kustībām, nodrošiniet ērtāku braukšanu.",
    "OperateClutch" : "Cenšoties pienācīgi darbināt sajūgu, nodrošiniet ērtāku braukšanu.",
    "GoodJobNotEnoughData" : "Labs darbs! Pašreizējā braucienā neieguva pietiekami daudz datu diagnozei.",
    "brake" : "Bremze",
    "steer" : "Stūrēšana",
    "acc" : "Paātrināj.",
    "min" : "min",
    "minsago" : "minūtes atpakaļ",
    "stage1" : "1st STAGE",
    "stage2" : "2nd STAGE",
    "stage3" : "3rd STAGE",
    "stage4" : "4th STAGE",
    "stage5" : "5th STAGE",
    "stageinvalid" : "INVALID STAGE",
    "score" : "rezultāts",
    "drvAdvice" : "Braukšanas padoms",
};

framework.registerAppDictLoaded("idm", "lv_LV");