var Localization_netmgmtAppDict_el_GR = {
    //"stringId" : "localString"
    "ConnectTo" : "Σύνδεση με {networkName}",
    "Connecting" : "Σύνδεση",
    "Retry" : "Δοκιμάστε ξανά",
    "ConnectionError" : "Σφάλμα σύνδεσης",
    "ErrorDHCP" : "Σφάλμα DHCP. Απέτυχε η λήψη των ρυθμίσεων.",
    "ErrorInternal" : "Εσωτερικό σφάλμα",
    "ErrorNetwork" : "Σφάλμα δικτύου",
    "ConnectionSetup" : "Ρύθμιση σύνδεσης",
    "DoYouWantToConnect" : "Θέλετε να συνδεθείτε;",
    "NoNetworkConnectivity" : "Δεν υπάρχει συνδεσιμότητα δικτύου",
    "DeleteConfirmation" : "Θέλετε σίγουρα να διαγράψετε το {networkName};",
    "Disconnect" : "Αποσύνδεση",
    "NetworkDisconnected" : "Το {networkName} έχει αποσυνδεθεί",
    "InvalidPassword" : "Άκυρος κωδ. Πρόσβασης",
    "MaxNetworksReached" : "Έχει προστεθεί ο μέγιστος αριθμός δικτύων στη λίστα δικτύων.",
    "Delete" : "Διαγραφή",
    "SecurityOptions" : "Επιλογές ασφαλείας",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Σύνδεση",
    "None" : "Κανένα",
    "Password" : "Κωδικός πρόσβασης",
    "NetworkConnection" : "Σύνδεση δικτύου",
    "DeleteNetwork" : "Διαγραφή δικτύου Wi-Fi",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Όνομα (SSID)",
    "OtherNetwork" : "Άλλο δίκτυο",
    "SecurityType" : "Τύπος ασφαλείας",
    "Disconnecting" : "Αποσύνδεση",
    "EnterPassword" : "Καταχ. Κωδικού",
    "SavedNetworks" : "Αποθηκευμένα δίκτυα",
    "GUI_WrongPassword_Alert" : "Λανθασμένος κωδ. πρόσβασης",
    "GUI_WifiNetworkLost_Alert" : "Απώλεια δικτύου Wi-Fi",
    "DeleteANetwork" : "Διαγράψτε δίκτυο για να συνεχίσετε",
};

framework.registerAppDictLoaded("netmgmt", "el_GR");