var Localization_netmgmtAppDict_fr_FR = {
    //"stringId" : "localString"
    "ConnectTo" : "Connexion à {networkName}",
    "Connecting" : "En cours de connexion",
    "Retry" : "Réessayer",
    "ConnectionError" : "Erreur de connexion",
    "ErrorDHCP" : "Erreur DHCP. Échec d'acquisition des paramètres.",
    "ErrorInternal" : "Erreur interne",
    "ErrorNetwork" : "Erreur de réseau",
    "ConnectionSetup" : "Config de connexion",
    "DoYouWantToConnect" : "Voulez-vous vous connecter ?",
    "NoNetworkConnectivity" : "Aucune connectivité du réseau",
    "DeleteConfirmation" : "Êtes-vous sûr de vouloir supprimer {networkName} ?",
    "Disconnect" : "Déconnecter",
    "NetworkDisconnected" : "{networkName} a été déconnecté",
    "InvalidPassword" : "Mot de passe non valide",
    "MaxNetworksReached" : "Le nombre maximal de réseaux a été ajouté à la liste de réseaux.",
    "Delete" : "Supprimer",
    "SecurityOptions" : "Options de sécurité",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Connecter ",
    "None" : "Aucun",
    "Password" : "Mot de passe",
    "NetworkConnection" : "Connexion réseau",
    "DeleteNetwork" : "Supprimer le réseau Wi-Fi",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Nom (SSID)",
    "OtherNetwork" : "Autre réseau",
    "SecurityType" : "Type de sécurité",
    "Disconnecting" : "En cours de déconnexion",
    "EnterPassword" : "Entrer mot passe",
    "SavedNetworks" : "Réseaux enregistré",
    "GUI_WrongPassword_Alert" : "Mot de Passe Incorrect",
    "GUI_WifiNetworkLost_Alert" : "Perte du réseau Wi-Fi",
    "DeleteANetwork" : "Supprimer un réseau pour continuer",
};

framework.registerAppDictLoaded("netmgmt", "fr_FR");