var Localization_netmgmtAppDict_ru_RU = {
    //"stringId" : "localString"
    "ConnectTo" : "Подключиться к {networkName}",
    "Connecting" : "Подключение",
    "Retry" : "Повтор",
    "ConnectionError" : "Ошибка соединения",
    "ErrorDHCP" : "Ошибка DHCP. Настройки не получены.",
    "ErrorInternal" : "Внутренняя ошибка",
    "ErrorNetwork" : "Ошибка сети",
    "ConnectionSetup" : "Настройка подкл.",
    "DoYouWantToConnect" : "Вы хотите подключиться?",
    "NoNetworkConnectivity" : "Подключение к сети отсутствует",
    "DeleteConfirmation" : "Вы уверены, что хотите удалить {networkName}?",
    "Disconnect" : "Разорвать соединение",
    "NetworkDisconnected" : "{networkName} отключена",
    "InvalidPassword" : "Пароль недействителен",
    "MaxNetworksReached" : "В список сетей было добавлено максимальное количество сетей.",
    "Delete" : "Удалить",
    "SecurityOptions" : "Параметры защиты",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Подключить",
    "None" : "Нет",
    "Password" : "Сетевое соединение ",
    "NetworkConnection" : "Подкл. к сети",
    "DeleteNetwork" : "Удалить Wi-Fi сеть",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Имя (SSID)",
    "OtherNetwork" : "Другая сеть",
    "SecurityType" : "Тип защиты",
    "Disconnecting" : "Отключение",
    "EnterPassword" : "Введите пароль",
    "SavedNetworks" : "Сохраненные сети",
    "GUI_WrongPassword_Alert" : "Неправильный пароль",
    "GUI_WifiNetworkLost_Alert" : "Сеть Wi-Fi потеряна",
    "DeleteANetwork" : "Для продолжения удалите сеть",
};

framework.registerAppDictLoaded("netmgmt", "ru_RU");