var Localization_netmgmtAppDict_sr_RS = {
    //"stringId" : "localString"
    "ConnectTo" : "Poveži na {networkName}",
    "Connecting" : "Povezivanje",
    "Retry" : "Pokušaj ponovo",
    "ConnectionError" : "Greška veze",
    "ErrorDHCP" : " Greška DHCP-a. Pribavljanje podešavanja nije uspelo",
    "ErrorInternal" : "Interna greška",
    "ErrorNetwork" : "Greška na mreži",
    "ConnectionSetup" : "Podeš. Veze",
    "DoYouWantToConnect" : "Želite da se povežete?",
    "NoNetworkConnectivity" : "Ne postoji veza sa mrežom",
    "DeleteConfirmation" : "Jeste li sigurni da želite da izbrišete {networkName}?",
    "Disconnect" : "Prekini vezu",
    "NetworkDisconnected" : " Veza sa {networkName} je prekinuta",
    "InvalidPassword" : "Nevažeća lozinka",
    "MaxNetworksReached" : " Maks. broj mreža je dodat na Listu mreža. Brisanje mreže za nastavak.",
    "Delete" : "Izbriši",
    "SecurityOptions" : "Opcije bezbednosti",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Poveži",
    "None" : "Nijedno",
    "Password" : "Lozinka",
    "NetworkConnection" : "Mrežna veza",
    "DeleteNetwork" : "Izbriši Wi-Fi mrežu",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Ime (SSID)",
    "OtherNetwork" : "Druga mreža",
    "SecurityType" : "Tip bezbednosti",
    "Disconnecting" : "Sidanje sa Wi-Fi mreže",
    "EnterPassword" : "Unesi lozinku",
    "SavedNetworks" : "Sačuvane mreže",
    "GUI_WrongPassword_Alert" : "Pogrešna lozinka",
    "GUI_WifiNetworkLost_Alert" : " Wi-Fi mreža izgubljena",
    "DeleteANetwork" : "Za nastavak obrisati jednu mrežu",
};

framework.registerAppDictLoaded("netmgmt", "sr_RS");