var Localization_netmgmtAppDict_tr_TR = {
    //"stringId" : "localString"
    "ConnectTo" : "{networkName}'e bağlan",
    "Connecting" : "Bağlanılıyor",
    "Retry" : "Tekrar Deneyin",
    "ConnectionError" : "Bağlantı Hatası",
    "ErrorDHCP" : "DHCP Hatası. Ayarlar alınamıyor.",
    "ErrorInternal" : "Dahili Hata",
    "ErrorNetwork" : "Ağ Hatası",
    "ConnectionSetup" : "Bağlantı Kurulumu",
    "DoYouWantToConnect" : "Bağlanmak ister misiniz?",
    "NoNetworkConnectivity" : "Ağ Bağlantısı Yok",
    "DeleteConfirmation" : "{networkName}'i silmek istediğinizden emin misiniz?",
    "Disconnect" : "Bağlantıyı Kes",
    "NetworkDisconnected" : "{networkName} Bağlantısı kesildi",
    "InvalidPassword" : "Geçersiz Parola",
    "MaxNetworksReached" : "Ağ Listesine maksimum sayıda Ağ eklendi.",
    "Delete" : "Sil",
    "SecurityOptions" : "Güvenlik Seçenekleri",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Bağlan",
    "None" : "Yok",
    "Password" : "Parola",
    "NetworkConnection" : "Ağ Bağlantısı",
    "DeleteNetwork" : "Wi-Fi Ağını Silin",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Adı (SSID)",
    "OtherNetwork" : "Diğer Ağ",
    "SecurityType" : "Güvenlik Tipi",
    "Disconnecting" : "Bağlantı Kesiliyor",
    "EnterPassword" : "Parolayı Gir",
    "SavedNetworks" : "Kaydedilen Ağlar",
    "GUI_WrongPassword_Alert" : "Yanlış Parola",
    "GUI_WifiNetworkLost_Alert" : "Wi-Fi Ağı Kesildi",
    "DeleteANetwork" : "Devam etmek için bir Ağ seçin",
};

framework.registerAppDictLoaded("netmgmt", "tr_TR");