var Localization_netmgmtAppDict_no_NO = {
    //"stringId" : "localString"
    "ConnectTo" : "Koblet til {networkName}",
    "Connecting" : "Tilkopling",
    "Retry" : "Prøv på nytt",
    "ConnectionError" : "Tilkoblingsfeil",
    "ErrorDHCP" : "DHCP-feil. Kan ikke hente innstillinger.",
    "ErrorInternal" : "Intern feil",
    "ErrorNetwork" : "Nettverksfeil",
    "ConnectionSetup" : "Oppsett av tilkobling",
    "DoYouWantToConnect" : "Ønsker du å koble til?",
    "NoNetworkConnectivity" : "Ingen nettverksforbindelser",
    "DeleteConfirmation" : "Er du sikker på at du vil slette {networkName}?",
    "Disconnect" : "Kople fra",
    "NetworkDisconnected" : "{networkName} ble frakoblet",
    "InvalidPassword" : "Ugyldig passord",
    "MaxNetworksReached" : "Maksimalt antall nettverk er lagt til nettverklisten.",
    "Delete" : "Slett",
    "SecurityOptions" : "Sikkerhetsalternativer",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Koble til",
    "None" : "Ingen",
    "Password" : "Passord",
    "NetworkConnection" : "Nettverkstilkobling",
    "DeleteNetwork" : "Slette Wi-Fi-nettverk",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Navn (SSID)",
    "OtherNetwork" : "Annet nettverk",
    "SecurityType" : "Sikkerhetstype",
    "Disconnecting" : "Kobler fra",
    "EnterPassword" : "Angi passord",
    "SavedNetworks" : "Lagrede nettverk",
    "GUI_WrongPassword_Alert" : "Feil passord",
    "GUI_WifiNetworkLost_Alert" : "Wi-Fi-nettverk tapt",
    "DeleteANetwork" : "Slett et nettverk for å fortsette",
};

framework.registerAppDictLoaded("netmgmt", "no_NO");