var Localization_netmgmtAppDict_zh_CN = {
    //"stringId" : "localString"
    "ConnectTo" : "连接到 {networkName}",
    "Connecting" : "正在连接",
    "Retry" : "重试",
    "ConnectionError" : "连接错误",
    "ErrorDHCP" : "DHCP错误。获取设置失败。",
    "ErrorInternal" : "内部错误",
    "ErrorNetwork" : "网络错误",
    "ConnectionSetup" : "连接设置",
    "DoYouWantToConnect" : "是否希望连接？",
    "NoNetworkConnectivity" : "无网络连接",
    "DeleteConfirmation" : "确定要删除 {networkName} 吗？",
    "Disconnect" : "断开",
    "NetworkDisconnected" : "{networkName} 已断开连接",
    "InvalidPassword" : "密码无效",
    "MaxNetworksReached" : "已将最多网络添加到了网络列表中。",
    "Delete" : "删除",
    "SecurityOptions" : "安全选项",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "连接",
    "None" : "沒有",
    "Password" : "密码",
    "NetworkConnection" : "网络连接",
    "DeleteNetwork" : "删除 Wi-Fi 网络",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "名称/SSID",
    "OtherNetwork" : "其他网络",
    "SecurityType" : "安全类型",
    "Disconnecting" : "正在断开连接",
    "EnterPassword" : "输入密码",
    "SavedNetworks" : "已保存的网络",
    "GUI_WrongPassword_Alert" : "密码错误",
    "GUI_WifiNetworkLost_Alert" : "Wi-Fi 网络丢失",
    "DeleteANetwork" : "删除一个网络，继续",
};

framework.registerAppDictLoaded("netmgmt", "zh_CN");