var Localization_netmgmtAppDict_id_ID = {
    //"stringId" : "localString"
    "ConnectTo" : "Sambungkan ke {networkName}",
    "Connecting" : "Menyambungkan",
    "Retry" : "Coba Lagi",
    "ConnectionError" : "Galat Koneksi",
    "ErrorDHCP" : "Galat DHCP. Gagal mendapatkan setelan.",
    "ErrorInternal" : "Galat Internal",
    "ErrorNetwork" : "Galat Jaringan",
    "ConnectionSetup" : "Setelan Koneksi",
    "DoYouWantToConnect" : "Apakah Anda ingin tersambung?",
    "NoNetworkConnectivity" : "Tidak Ada Konektivitas Jaringan",
    "DeleteConfirmation" : "Apakah Anda yakin ingin menghapus {networkName}?",
    "Disconnect" : "Putuskan sambungan",
    "NetworkDisconnected" : "{networkName} telah Diputuskan",
    "InvalidPassword" : "Kata Sandi Tidak Sah",
    "MaxNetworksReached" : "Jaringan Maksimum telah ditambahkan ke Daftar Jaringan",
    "Delete" : "Hapus",
    "SecurityOptions" : "Opsi Keamanan",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Sambungkan",
    "None" : "Tidak Ada",
    "Password" : "Kata Sandi",
    "NetworkConnection" : "Koneksi Jaringan",
    "DeleteNetwork" : "Hapus Jaringan Wi-Fi",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Nama (SSID)",
    "OtherNetwork" : "Jaringan Lainnya",
    "SecurityType" : "Jenis Keamanan",
    "Disconnecting" : "Memutus Sambungan",
    "EnterPassword" : "Masukkan Sandi",
    "SavedNetworks" : "Jaringan Tersimpan",
    "GUI_WrongPassword_Alert" : "Kata Sandi Salah",
    "GUI_WifiNetworkLost_Alert" : "Jaringan Wi-Fi Hilang",
    "DeleteANetwork" : "Hapus Jaringan untuk lanjut",
};

framework.registerAppDictLoaded("netmgmt", "id_ID");