var Localization_netmgmtAppDict_ro_RO = {
    //"stringId" : "localString"
    "ConnectTo" : "Conectare la {networkName}",
    "Connecting" : "Conectare",
    "Retry" : "Reîncercare",
    "ConnectionError" : "Eroare de conectare",
    "ErrorDHCP" : "Eroare DHCP. Nu s-au putut prelua setările.",
    "ErrorInternal" : "Eroare internă",
    "ErrorNetwork" : "Eroare reţea",
    "ConnectionSetup" : "Setare conexiune",
    "DoYouWantToConnect" : "Doriţi să conectaţi?",
    "NoNetworkConnectivity" : "Reţeaua nu are conectivitate",
    "DeleteConfirmation" : "Confirmaţi ştergerea {networkName}?",
    "Disconnect" : "Deconectare",
    "NetworkDisconnected" : "{networkName} a fost deconectată",
    "InvalidPassword" : "Parolă nevalidă",
    "MaxNetworksReached" : "Nr. max. de reţele adăugate la listă.",
    "Delete" : "Ştergere",
    "SecurityOptions" : "Opţiuni de securitate",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA/WPA2",
    "Connect" : "Conectare",
    "None" : "Niciunul",
    "Password" : "Parolă",
    "NetworkConnection" : "Conexiune reţea",
    "DeleteNetwork" : "Eliminare reţea Wi-Fi",
    "WiFi" : "Wi-Fi",
    "NameSSID" : "Denumire (SSID)",
    "OtherNetwork" : "Altă reţea",
    "SecurityType" : "Tip securitate",
    "Disconnecting" : "Deconectare",
    "EnterPassword" : "Introduceţi parola",
    "SavedNetworks" : "Reţele salvate",
    "GUI_WrongPassword_Alert" : "Parolă incorectă",
    "GUI_WifiNetworkLost_Alert" : "Semnal reţea Wi-Fi întrerupt",
    "DeleteANetwork" : "ştergeţi o reţea pt. a continua",
};

framework.registerAppDictLoaded("netmgmt", "ro_RO");