var Localization_netmgmtAppDict_lt_LT = {
    //"stringId" : "localString"
    "ConnectTo" : "Prijungti prie {networkName}",
    "Connecting" : "Jungiamasi",
    "Retry" : "Bandyti dar kartą",
    "ConnectionError" : "Ryšio klaida",
    "ErrorDHCP" : "DHCP klaida. Neteisingi aptikimo nustatymai.",
    "ErrorInternal" : "Vidinė klaida",
    "ErrorNetwork" : "Tinklo klaida",
    "ConnectionSetup" : "Sujungimo sąranka",
    "DoYouWantToConnect" : "Ar norite prisijungti?",
    "NoNetworkConnectivity" : "Nėra tinklo",
    "DeleteConfirmation" : "Ar tikrai norite panaikinti {networkName}?",
    "Disconnect" : "Atjungti",
    "NetworkDisconnected" : "Tinklas {networkName} atjungtas ",
    "InvalidPassword" : "Neteisingas slaptažodis",
    "MaxNetworksReached" : "Į tinklo sąrašą įtrautas maksimalus tinklų skaičius",
    "Delete" : "Naikinti",
    "SecurityOptions" : "Apsaugos parinktys",
    "WEP" : "WEP",
    "WPA" : "WPA",
    "WPA2" : "WPA2",
    "WPAWPA2" : "WPA / WPA2",
    "Connect" : "Prijungti",
    "None" : "Nėra",
    "Password" : "Slaptažodis",
    "NetworkConnection" : "Tinklo ryšys",
    "DeleteNetwork" : "Ištrinti „Wi-Fi“ tinklą",
    "WiFi" : "\"Wi-Fi\"",
    "NameSSID" : "Pavadinimas (SSID)",
    "OtherNetwork" : "Kitas tinklas",
    "SecurityType" : "Apsaugos tipas",
    "Disconnecting" : "Atsijungiama",
    "EnterPassword" : "Įveskite slaptažodį",
    "SavedNetworks" : "Įrašyti tinklai",
    "GUI_WrongPassword_Alert" : "Neteisingas slaptažodis",
    "GUI_WifiNetworkLost_Alert" : "Nuo \"Wi-Fi\" tinklo atsijungė",
    "DeleteANetwork" : "Norėdami tęsti ištrinkite tinklą",
};

framework.registerAppDictLoaded("netmgmt", "lt_LT");