var Localization_idmAppDict_hr_HR = {
	//"stringId" : "localString"
	"AccelSmoothly": "Pažljivo glatko ubrzavanje rezultirat će udobnijim radom.",
	"AmbienceRetryMsg": "Postavke zaslon s informacijama nije moguće promijeniti. Želite li pok. ponovno?",
	"ApplicationsMenu": "Aplikacije",
	"CancelBtn": "Otkaži",
	"DecelSmoothly": "Pažljivo glatko usporavanje rezultirat će udobnijim radom.",
	"DroveAsExpected": "Ovaj ste put vozili prema očekivanju. Ponovo me povedi na vožnju.",
	"Excellent": "Odlično",
	"GentleSteering": "Lagano okretanje upravljača rezultirat će udobnijim radom.",
	"Good": "Dobro",
	"GoodJob": "Dobar posao!",
	"GoodJobNotEnoughData": "Dobar posao! Trenutačni prolaz nije dobio dovoljno pod. za dijagnozu.",
	"GoodWork": "Dobar posao",
	"HangOfIt": "Postali se profesionalac. Samo nastavite.",
	"HaveAFeel": "Već imate osjećaj za ovo. Samo nastavite.",
	"HidePanel": "Sakrij gumbe",
	"LoadiDM": "i-DM Učitavanje",
	"NoFrequentAccel": "Izbjegavanje čestih ubrzavanja rezultirat će glatkijim radom.",
	"NoFrequentBrake": "Izbjegavanje čestih kočenja rezultirat će glatkijim radom.",
	"NoFrequentSteer": "Izbjegavanje čestih okretanja upravljača rezultirat će glatkijim radom.",
	"NotEnoughData": "Trenutačni prolaz nije dobio dovoljno pod. za dijagnozu.",
	"OperateClutch": "Pažljivo rukovanje spojkom rezultirat će udobnijim radom.",
	"RetryBtn": "Pon. pok.",
	"SelectSettings": "Odaberi postavke",
	"SwitchView": "Sljedeći zaslon",
	"VeryGood": "Vrlo dobro",
	"acc": "Ubrzanje",
	"avg": "Prosjek",
	"avgScore": "Prosj. rezul.",
	"brake": "Kočnica",
	"currDrvTrnd": "Tren. način vož.",
	"currScore": "Tren. rez.",
	"current": "Trenut.",
	"driver": "Vozač",
	"drvAdvice": "Savjeti za vožnju",
	"endingScreen": "Završni zaslon",
	"meterAmbientDisplay": "Zaslon s informacijama",
	"min": "min",
	"minsago": "minuta ranije",
	"score": "rezultat",
	"scoreTransition": "Prijenos rezul.",
	"settingIDM": "i-DM",
	"settings": "Postavke",
	"simpleMode": "i-DM jedn. način",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Stupanj više!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Upravni",
	"trainingMode": "i-DM način obuke",
};

framework.registerAppDictLoaded("idm", "hr_HR");