var Localization_idmAppDict_pt_BR = {
	//"stringId" : "localString"
	"AccelSmoothly": "Acelerar com delicadeza resultará em um percurso mais suave",
	"AmbienceRetryMsg": "Não é possível alterar a configuração do display do ambiente do medidor. Deseja tentar novamente?",
	"ApplicationsMenu": "Aplicativos",
	"CancelBtn": "Cancelar",
	"DecelSmoothly": "Desacelerar com delicadeza resultará em um percurso  mais suave",
	"DroveAsExpected": "Desta vez você dirigiu exatamente conforme o esperado. Leve-me a conduzir novamente.",
	"Excellent": "Excelente",
	"GentleSteering": "Não girar o volante bruscamentei resultará em um percurso mais suave.",
	"Good": "Bom",
	"GoodJob": "Bom trabalho!",
	"GoodJobNotEnoughData": "Muito bem! O percurso atual não gerou dados suficientes para um diagnóstico.",
	"GoodWork": "Bom trabalho",
	"HangOfIt": "Você está pegando a ideia. Continue assim.",
	"HaveAFeel": "Você já está pegando o jeito. Continue assim.",
	"HidePanel": "Ocultar botões",
	"LoadiDM": "Carregando i-DM",
	"NoFrequentAccel": "Evitar acelerações frequentes resultará em um percurso mais suave.",
	"NoFrequentBrake": "Evitar frenagens frequentes resultará em um percurso mais suave.",
	"NoFrequentSteer": "Não girar o volante bruscamentei resultará em um percurso mais suave.",
	"NotEnoughData": "Não foi possível obter dados suficientes para um diagnóstico no percurso atual.",
	"OperateClutch": "Acionar a embreagem com delicadeza resultará em um percurso mais suave.",
	"RetryBtn": "Repetir",
	"SelectSettings": "Selecionar configurações",
	"SwitchView": "Próxima tela",
	"VeryGood": "Muito bem",
	"acc": "Aceleração",
	"avg": "Média",
	"avgScore": "Pont. média ",
	"brake": "Freio",
	"currDrvTrnd": "Tendência de percurso atual",
	"currScore": "Pont. atual",
	"current": "Atual",
	"driver": "Motorista",
	"drvAdvice": "Dica de direção",
	"endingScreen": "Tela de encerramento",
	"meterAmbientDisplay": "Display de ambiente do medidor",
	"min": "min",
	"minsago": "minutos atrás",
	"score": "pontuação",
	"scoreTransition": "Pont. transição",
	"settingIDM": "i-DM",
	"settings": "Configurações",
	"simpleMode": "i-DM modo simples",
	"stage1": "1o ESTÁGIO",
	"stage2": "2o ESTÁGIO",
	"stage3": "3o ESTÁGIO",
	"stage4": "4o ESTÁGIO",
	"stage5": "5o ESTÁGIO",
	"stageUp": "Novo estágio!",
	"stageinvalid": "ESTÁGIO NÃO VÁLIDO",
	"steer": "Direção",
	"trainingMode": "i-DM modo trein.",
};

framework.registerAppDictLoaded("idm", "pt_BR");