var Localization_idmAppDict_nl_NL = {
	//"stringId" : "localString"
	"AccelSmoothly": "Rustig optrekken verhoogt het rijcomfort.",
	"AmbienceRetryMsg": "Wijzigen instelling Meter Ambient Display mislukt. Wilt u het opnieuw proberen?",
	"ApplicationsMenu": "Applicaties",
	"CancelBtn": "Annuleren",
	"DecelSmoothly": "Rustig afremmen verhoogt het rijcomfort.",
	"DroveAsExpected": "Deze keer reed u precies als verwacht. Laten we nog een rit maken.",
	"Excellent": "Uitstekend",
	"GentleSteering": "Rustig sturen verhoogt het rijcomfort.",
	"Good": "Goed",
	"GoodJob": "Goed gedaan!",
	"GoodJobNotEnoughData": "Goed gedaan! De huidige rit bevatte te weinig gegevens voor een diagnose.",
	"GoodWork": "Goed werk",
	"HangOfIt": "U krijgt de slag te pakken. Ga zo door.",
	"HaveAFeel": "U hebt het in uw vingers. Ga zo door.",
	"HidePanel": "Toetsen verbergen",
	"LoadiDM": "i-DM Laden",
	"NoFrequentAccel": "Minder vaak optrekken resulteert in een soepelere bediening van het voertuig.",
	"NoFrequentBrake": "Minder vaak remmen resulteert in een soepelere bediening van het voertuig.",
	"NoFrequentSteer": "Minder vaak onnodig sturen resulteert in een soepelere bediening van het voertuig.",
	"NotEnoughData": "De huidige rit bevatte te weinig gegevens voor een diagnose.",
	"OperateClutch": "Rustig en correct gebruik van de koppeling verhoogt het rijcomfort.",
	"RetryBtn": "Opnieuw proberen",
	"SelectSettings": "Instellingen selecteren",
	"SwitchView": "Volgend scherm",
	"VeryGood": "Erg goed",
	"acc": "Versnelling",
	"avg": "Gemiddelde",
	"avgScore": "Gem. score",
	"brake": "Rem",
	"currDrvTrnd": "Huidige rijstijl",
	"currScore": "Huidige score",
	"current": "Huidige",
	"driver": "Chauffeur",
	"drvAdvice": "Rij-advies",
	"endingScreen": "Eindscherm",
	"meterAmbientDisplay": "Display Buitentemp.",
	"min": "min",
	"minsago": "minuten geleden",
	"score": "score",
	"scoreTransition": "Score overgang",
	"settingIDM": "i-DM",
	"settings": "Instellingen",
	"simpleMode": "i-DM simpele modus",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Stage Up!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Sturen",
	"trainingMode": "i-DM trainingsmodus",
};

framework.registerAppDictLoaded("idm", "nl_NL");