var Localization_idmAppDict_cn_HK = {
	//"stringId" : "localString"
	"AccelSmoothly": "小心地逐漸加速讓您的行駛更加舒適。",
	"AmbienceRetryMsg": "無法改變環境顯示儀設定。 是否要重試？",
	"ApplicationsMenu": "應用程式",
	"CancelBtn": "取消",
	"DecelSmoothly": "小心地逐漸減速讓您的行駛更加舒適。",
	"DroveAsExpected": "您已按照預期完成本次行駛。 讓我再開一次。",
	"Excellent": "好極了",
	"GentleSteering": "小心地逐漸轉彎讓您的行駛更加舒適。",
	"Good": "好",
	"GoodJob": "做得好！",
	"GoodJobNotEnoughData": "做得好！ 當前行車未獲得足夠的資料以用於診斷。",
	"GoodWork": "幹得好",
	"HangOfIt": "您已找到竅門。 繼續努力。",
	"HaveAFeel": "您已開始熟悉。 繼續努力。",
	"HidePanel": "隱藏按鈕",
	"LoadiDM": "正在載入 i-DM",
	"NoFrequentAccel": "不要頻繁地加速，這樣才能順利行駛。",
	"NoFrequentBrake": "不要頻繁地刹車，這樣才能順利行駛。",
	"NoFrequentSteer": "不要頻繁地轉向，這樣才能順利行駛。",
	"NotEnoughData": "當前行車未獲得足夠的資料以用於診斷。",
	"OperateClutch": "小心地逐漸操作離合器讓您的行駛更加舒適。",
	"RetryBtn": "重試",
	"SelectSettings": "設定",
	"SwitchView": "下一頁",
	"VeryGood": "非常好",
	"acc": "加速",
	"avg": "平均耗油量",
	"avgScore": "平均分數",
	"brake": "制動",
	"currDrvTrnd": "目前駕駛趨勢",
	"currScore": "目前分數",
	"current": "當前",
	"driver": "駕駛者",
	"drvAdvice": "駕駛建議",
	"endingScreen": "結束畫面",
	"meterAmbientDisplay": "環境顯示儀",
	"min": "分鐘",
	"minsago": "分鐘之前",
	"score": "得分",
	"scoreTransition": "分數走勢",
	"settingIDM": "i-DM",
	"settings": "設定",
	"simpleMode": "i-DM 簡單模式",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Stage Up！",
	"stageinvalid": "INVALID STAGE",
	"steer": "轉向",
	"trainingMode": "i-DM 培訓模式",
};

framework.registerAppDictLoaded("idm", "cn_HK");