var Localization_idmAppDict_et_EE = {
	//"stringId" : "localString"
	"AccelSmoothly": "Sujuvam kiirendamine teeb sõidu mugavamaks.",
	"AmbienceRetryMsg": "Ümbruse mõõtandmete kuvamise sätet ei saanud muuta. Kas soovite uuesti proovida?",
	"ApplicationsMenu": "Rakendused",
	"CancelBtn": "Tühista",
	"DecelSmoothly": "Sujuvam pidurdamine teeb sõidu mugavamaks.",
	"DroveAsExpected": "Seekord sõitsite nii, nagu peab. Lähme uuesti sõitma.",
	"Excellent": "Suurepärane",
	"GentleSteering": "Sujuvam roolikeeramine teeb sõidu mugavamaks.",
	"Good": "Hea",
	"GoodJob": "Tubli töö!",
	"GoodJobNotEnoughData": "Tubli töö! Praegusest sõidust ei saanud diagnoosimiseks piisavalt andmeid.",
	"GoodWork": "Tubli töö",
	"HangOfIt": "Hakkate juba pihta saama. Laske samamoodi edasi.",
	"HaveAFeel": "Olete juba lainel. Laske samamoodi edasi.",
	"HidePanel": "Peida nupud",
	"LoadiDM": "i-DM Laadimine",
	"NoFrequentAccel": "Sagedastest kiirendustest hoidumine muudaks sõidu sujuvamaks.",
	"NoFrequentBrake": "Sagedastest pidurdustest hoidumine muudaks sõidu sujuvamaks.",
	"NoFrequentSteer": "Sagedastest roolikeeramistest hoidumine muudaks sõidu sujuvamaks.",
	"NotEnoughData": "Toimunud otsing ei kogunud diagnoosiks piisavalt andmeid.",
	"OperateClutch": "Siduri õige kasutamine teeb sõidu mugavamaks.",
	"RetryBtn": "Proovi uuesti",
	"SelectSettings": "Valige sätted",
	"SwitchView": "Järgmine kuva",
	"VeryGood": "Väga hea",
	"acc": "Kiirendus",
	"avg": "Keskmine",
	"avgScore": "Keskm. tulem.",
	"brake": "Pidur",
	"currDrvTrnd": "Praegune sõidutrend",
	"currScore": "Praeg. Tulem.",
	"current": "Praegune",
	"driver": "Juht",
	"drvAdvice": "Sõidu Nõuanded",
	"endingScreen": "Lõpetamiskuva",
	"meterAmbientDisplay": "Ümbruse mõõtandmete kuvamine",
	"min": "min",
	"minsago": "minutit tagasi",
	"score": "tulemus",
	"scoreTransition": "Tulemuse ülekanne",
	"settingIDM": "i-DM",
	"settings": "Sätted",
	"simpleMode": "i-DM-i lihtrežiim",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Järgmine etapp!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Rooliv",
	"trainingMode": "i-DM-i harjutusrežiim",
};

framework.registerAppDictLoaded("idm", "et_EE");