var Localization_idmAppDict_ru_RU = {
	//"stringId" : "localString"
	"AccelSmoothly": "Для более комфортного движения ускоряйтесь плавно.",
	"AmbienceRetryMsg": "Невозможно изменить настройки подсветки. Хотите попробовать еще раз?",
	"ApplicationsMenu": "Приложения",
	"CancelBtn": "Отмена",
	"DecelSmoothly": "Для более комфортного движения тормозите плавно.",
	"DroveAsExpected": "Ваше вождение соответствало ожиданиям.  ",
	"Excellent": "Превосходно",
	"GentleSteering": "Для более комфортного движения старайтесь рулить плавно.",
	"Good": "Хорошо",
	"GoodJob": "Отлично!",
	"GoodJobNotEnoughData": "Отлично! В этот раз собрано недост. данных для диагноза ошибок.",
	"GoodWork": "Отлично",
	"HangOfIt": "Вы уже почти освоились. Продолжайте в том же духе.",
	"HaveAFeel": "Вы уже прочувствовали этот режим. Продолжайте в том же духе.",
	"HidePanel": "Скрыть кнопки",
	"LoadiDM": "i-DM Загрузка",
	"NoFrequentAccel": "Для более плавного движения воздержитесь от частых ускорений.",
	"NoFrequentBrake": "Для более плавного движения воздержитесь от частого торможения.",
	"NoFrequentSteer": "Для более плавного движения старайтесь избегать резкого поворота руля.",
	"NotEnoughData": "В этот раз собрано недост. данных для диагностики.",
	"OperateClutch": "Для  комфорт. движения остор. перекл. передачи и плавно отпукайте сцепл.",
	"RetryBtn": "Повтор",
	"SelectSettings": "Выберите настройки",
	"SwitchView": "Следующий экран",
	"VeryGood": "Очень хорошо",
	"acc": "Yскорение",
	"avg": "Средний",
	"avgScore": "Средн. оценка",
	"brake": "Торможение",
	"currDrvTrnd": "Текущий стиль вождения",
	"currScore": "Тек. оценка",
	"current": "Текущий",
	"driver": "Водитель",
	"drvAdvice": "Советы по вождению",
	"endingScreen": "Завершающий экран",
	"meterAmbientDisplay": "Подсветка экоана",
	"min": "мин",
	"minsago": "минут назад",
	"score": "счет",
	"scoreTransition": "Перенос оценки",
	"settingIDM": "i-DM",
	"settings": "Настройки",
	"simpleMode": "Простой режим i-DM",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "На уровень вверх!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Руление",
	"trainingMode": "Oбуч режим i-DM",
};

framework.registerAppDictLoaded("idm", "ru_RU");