var Localization_idmAppDict_tr_TR = {
	//"stringId" : "localString"
	"AccelSmoothly": "Ako ubrzavate lagano vaša vožnja će biti prijatnija.",
	"AmbienceRetryMsg": "Sayaç Ortam Ekranı Ayarı değiştirilemedi. Tekrar denemek ister misiniz?",
	"ApplicationsMenu": "Uygulamalar",
	"CancelBtn": "İptal",
	"DecelSmoothly": "Ako usporavate lagano vaša vožnja će biti prijatnija.",
	"DroveAsExpected": "Ovoga puta ste vozili kao što je bilo očekivano. Povedite me opet u vožnju.",
	"Excellent": "Odlinčno",
	"GentleSteering": "Ako skrećete postepeno vaša vožnja će biti prijatnija.",
	"Good": "Dobro",
	"GoodJob": "Odlično!",
	"GoodJobNotEnoughData": "Odlično! Tokom ove vožnje nije prikupljeno dovoljno podataka za dijagnozu.",
	"GoodWork": "Dobro odrađeno",
	"HangOfIt": "Baš vam dobro ide. Samo tako nastavite.",
	"HaveAFeel": "Već imate osećaj za ovo. Samo tako nastavite.",
	"HidePanel": "Düğmeleri Gizle",
	"LoadiDM": "i-DM Yükleniyor",
	"NoFrequentAccel": "Ako se uzdržite od naglog ubrzanja vaša vožnja će biti ugodnija.",
	"NoFrequentBrake": "Ako se uzdržite od naglog kočenja vaša vožnja će biti ugodnija.",
	"NoFrequentSteer": "Ako se uzdržite od naglog skretanja vaša vožnja će biti ugodnija.",
	"NotEnoughData": "Tokom ove vožnje nije prikupljeno dovoljno podataka za dijagnozu.",
	"OperateClutch": "Ako pravilno menjate brzine vaša vošnja će biti prijatnija.",
	"RetryBtn": "Tekrar Dene",
	"SelectSettings": "Ayarları Seç",
	"SwitchView": "Sonraki Ekran",
	"VeryGood": "Vrlo dobro",
	"acc": "Hızlanma",
	"avg": "Ortalama",
	"avgScore": "Ortal. Değer",
	"brake": "Fren",
	"currDrvTrnd": "Mevcut Sürüş Trendi",
	"currScore": "Mevcut Değer",
	"current": "Mevcut",
	"driver": "Sürücü",
	"drvAdvice": "Sürüş Tavsiyesi",
	"endingScreen": "Bitiş Ekranı",
	"meterAmbientDisplay": "Ortam Ekranını Ölç",
	"min": "dak",
	"minsago": "dakika önce",
	"score": "puan",
	"scoreTransition": "Değer Geçişi",
	"settingIDM": "i-DM",
	"settings": "Ayarlar",
	"simpleMode": "i-DM Basit Modu",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "İşte Karşınızda!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Idare",
	"trainingMode": "i-DM Eğitim Modu",
};

framework.registerAppDictLoaded("idm", "tr_TR");