var Localization_idmAppDict_lt_LT = {
	//"stringId" : "localString"
	"AccelSmoothly": "Tolygiai greitėdami važiuosite daug patogiau.",
	"AmbienceRetryMsg": "Negalima pakeisti aplinkos matavimo duomenų ekrano nustatymų. Norite bandyti dar kartą?",
	"ApplicationsMenu": "Programos",
	"CancelBtn": "Atšaukti",
	"DecelSmoothly": "Tolygiai lėtėdami važiuosite daug patogiau.",
	"DroveAsExpected": "Šį kartą vairavote, kaip buvo tikėtasi. Vežkite mane dar kartą.",
	"Excellent": "Puikiai",
	"GentleSteering": "Nesmarkiai sukiodami vairą važiuosite daug patogiau",
	"Good": "Gerai",
	"GoodJob": "Geras darbas!",
	"GoodJobNotEnoughData": "Geras darbas! Šis važiavimas nesurinko pakankamai duomenų diagnostikai.",
	"GoodWork": "Geras darbas",
	"HangOfIt": "Jūs jau baigiate priprasti. Taip ir toliau",
	"HaveAFeel": "Jūs jau pradedate jausti. Taip ir toliau.",
	"HidePanel": "Slėpti mygtukus",
	"LoadiDM": "i-DM Įkeliama",
	"NoFrequentAccel": "Venkite dažnai spausti akseleratorių. Tai leis jums važiuoti tolygiau",
	"NoFrequentBrake": "Venkite dažnai stabdyti. Tai leis jums važiuoti tolygiau.",
	"NoFrequentSteer": "Venkite dažnai sukioti vairą. Tai leis jums važiuoti tolygiau.",
	"NotEnoughData": "Šis važiavimas nesurinko pakankamai duomenų diagnostikai.",
	"OperateClutch": "Tinkamai naudodami sankabą važiuosite daug patogiau.",
	"RetryBtn": "Bandyti dar kartą",
	"SelectSettings": "Parametrų pasirinkimas",
	"SwitchView": "Kitas ekranas",
	"VeryGood": "Labai gerai",
	"acc": "Pagreitis",
	"avg": "Vidurkis",
	"avgScore": "Vidut. taškai",
	"brake": "Stabdys",
	"currDrvTrnd": "Esama vairavimo tendencija",
	"currScore": "Esami taškai",
	"current": "Esamas",
	"driver": "Vairuotojas",
	"drvAdvice": "Vairavimo patarimai",
	"endingScreen": "Ekranas išsijungia",
	"meterAmbientDisplay": "Apl. matavimo duomenų ekranas",
	"min": "min.",
	"minsago": "prieš",
	"score": "rezultatas",
	"scoreTransition": "Taškų perkėlimas",
	"settingIDM": "i-DM",
	"settings": "Nustatymai",
	"simpleMode": "Paprastas i-DM rež.",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Etapas užbaigtas!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Vairavimas",
	"trainingMode": "i-DM mokymo režimas",
};

framework.registerAppDictLoaded("idm", "lt_LT");