var Localization_idmAppDict_el_GR = {
	//"stringId" : "localString"
	"AccelSmoothly": "Αν έχετε το νου σας και επιταχύνετε ομαλά, θα οδηγείτε πιο άνετα.",
	"AmbienceRetryMsg": "Δεν ήταν δυνατή η αλλαγή της ρύθμισης εμφάνισης μέτρησης περιβάλλοντος. Θέλετε να προσπαθήσετε ξανά;",
	"ApplicationsMenu": "Εφαρμογές",
	"CancelBtn": "Ακύρωση",
	"DecelSmoothly": "Αν έχετε το νου σας και επιβραδύνετε ομαλά, θα οδηγείτε πιο άνετα.",
	"DroveAsExpected": "Αυτή τη φορά οδηγήσατε όπως αναμενόταν. Οδηγήστε ξανά.",
	"Excellent": "Εξαιρετικό",
	"GentleSteering": "Αν έχετε το νου σας και στρίβετε ομαλά, θα οδηγείτε πιο άνετα.",
	"Good": "Καλό",
	"GoodJob": "Μπράβο!",
	"GoodJobNotEnoughData": "Μπράβο! Αυτή η οδήγηση δεν είχε αρκετά δεδομένα για διάγνωση.",
	"GoodWork": "Μπράβο",
	"HangOfIt": "Αρχίσατε να τα καταφέρνετε. Συνεχίσετε την καλή δουλειά.",
	"HaveAFeel": "Ήδη γνωρίζετε τι να κάνετε. Συνεχίστε την καλή δουλειά.",
	"HidePanel": "Απόκρυψη κουμπιών",
	"LoadiDM": "i-DM Γίνεται φόρτωση",
	"NoFrequentAccel": "Αν δεν επιταχύνετε συχνά, θα οδηγείτε πιο ομαλά.",
	"NoFrequentBrake": "Αν δεν φρενάρετε συχνά, θα οδηγείτε πιο ομαλά.",
	"NoFrequentSteer": "Αν δεν στρίβετε συχνά το τιμόνι, θα οδηγείτε πιο ομαλά.",
	"NotEnoughData": "Αυτή η διαδρομή δεν είχε αρκετά δεδομένα για διάγνωση.",
	"OperateClutch": "Αν έχετε το νου σας και χειρίζεστε το συμπλέκτη πιο ομαλά, θα οδηγείτε πιο άνετα.",
	"RetryBtn": "Νέα προσπάθεια",
	"SelectSettings": "Επιλέξτε ρυθμίσεις",
	"SwitchView": "Επόμενη οθόνη",
	"VeryGood": "Πολύ καλό",
	"acc": "Επιτάχυνση",
	"avg": "Μέσος",
	"avgScore": "Μέση βαθμ.",
	"brake": "Φρένο",
	"currDrvTrnd": "Τρέχουσα τάση οδήγησης",
	"currScore": "Τρέχ. Βαθμολ.",
	"current": "Τρέχων",
	"driver": "Οδηγός",
	"drvAdvice": "Συμβουλές οδηγήσης",
	"endingScreen": "Τελική οθόνη",
	"meterAmbientDisplay": "Εμφάνιση μέτρ. περιβάλλ.",
	"min": "λεπ.",
	"minsago": "λεπτά πριν",
	"score": "βαθμολογία",
	"scoreTransition": "Μετάβαση βαθμολ.",
	"settingIDM": "i-DM",
	"settings": "Ρυθμίσεις",
	"simpleMode": "Απλή λειτουργ. i-DM",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Επίπεδο επάνω!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Τιμόνι",
	"trainingMode": "Εκπαίδευση σε i-DM",
};

framework.registerAppDictLoaded("idm", "el_GR");