var Localization_idmAppDict_sr_RS = {
	//"stringId" : "localString"
	"AccelSmoothly": "Ako ubrzavate lagano vaša vožnja će biti prijatnija.",
	"AmbienceRetryMsg": "Nije moguće izmeniti postavke ekrana sa mernim elementima. Želite li da pokušate ponovo?",
	"ApplicationsMenu": "Aplikacije",
	"CancelBtn": "Poništi",
	"DecelSmoothly": "Ako usporavate lagano vaša vožnja će biti prijatnija.",
	"DroveAsExpected": "Ovoga puta ste vozili kao što je bilo očekivano. Povedite me opet u vožnju.",
	"Excellent": "Odlinčno",
	"GentleSteering": "Ako skrećete postepeno vaša vožnja će biti prijatnija.",
	"Good": "Dobro",
	"GoodJob": "Odlično!",
	"GoodJobNotEnoughData": "Odlično! Tokom ove vožnje nije prikupljeno dovoljno podataka za dijagnozu.",
	"GoodWork": "Dobro odrađeno",
	"HangOfIt": "Baš vam dobro ide. Samo tako nastavite.",
	"HaveAFeel": "Već imate osećaj za ovo. Samo tako nastavite.",
	"HidePanel": "Sakri dugmiće",
	"LoadiDM": "i-DM Učitavanje",
	"NoFrequentAccel": "Ako se uzdržite od naglog ubrzanja vaša vožnja će biti ugodnija.",
	"NoFrequentBrake": "Ako se uzdržite od naglog kočenja vaša vožnja će biti ugodnija.",
	"NoFrequentSteer": "Ako se uzdržite od naglog skretanja vaša vožnja će biti ugodnija.",
	"NotEnoughData": "Tokom ove vožnje nije prikupljeno dovoljno podataka za dijagnozu.",
	"OperateClutch": "Ako pravilno menjate brzine vaša vošnja će biti prijatnija.",
	"RetryBtn": "Pokušaj ponovo",
	"SelectSettings": "Odaberite postavke",
	"SwitchView": "Sledeći ekran",
	"VeryGood": "Vrlo dobro",
	"acc": "Gas",
	"avg": "Prosek",
	"avgScore": "Prosečan rez.",
	"brake": "Kočnice",
	"currDrvTrnd": "Trenutni način vožnje",
	"currScore": "Trenutni rez.",
	"current": "Trenutni ",
	"driver": "Vozač",
	"drvAdvice": "Savet za vožnju",
	"endingScreen": "Završni ekran",
	"meterAmbientDisplay": "Ekran sa mernim elementima",
	"min": "min",
	"minsago": "minuta je prošlo",
	"score": "rezultat",
	"scoreTransition": "Prenos rezultata",
	"settingIDM": "i-DM",
	"settings": "Postavke",
	"simpleMode": "i-DM način rada",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Nova tapa!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Upravljanje",
	"trainingMode": "i-DM obuka",
};

framework.registerAppDictLoaded("idm", "sr_RS");