var Localization_idmAppDict_sv_SE = {
	//"stringId" : "localString"
	"AccelSmoothly": "Ako ubrzavate lagano vaša vožnja će biti prijatnija.",
	"AmbienceRetryMsg": "Kunde inte ändra inställning för mätare omgivande skärm. Vill du prova igen?",
	"ApplicationsMenu": "Program",
	"CancelBtn": "Avbryt",
	"DecelSmoothly": "Ako usporavate lagano vaša vožnja će biti prijatnija.",
	"DroveAsExpected": "Ovoga puta ste vozili kao što je bilo očekivano. Povedite me opet u vožnju.",
	"Excellent": "Odlinčno",
	"GentleSteering": "Ako skrećete postepeno vaša vožnja će biti prijatnija.",
	"Good": "Dobro",
	"GoodJob": "Odlično!",
	"GoodJobNotEnoughData": "Odlično! Tokom ove vožnje nije prikupljeno dovoljno podataka za dijagnozu.",
	"GoodWork": "Dobro odrađeno",
	"HangOfIt": "Baš vam dobro ide. Samo tako nastavite.",
	"HaveAFeel": "Već imate osećaj za ovo. Samo tako nastavite.",
	"HidePanel": "Dölj knappar",
	"LoadiDM": "i-DM Laddar",
	"NoFrequentAccel": "Ako se uzdržite od naglog ubrzanja vaša vožnja će biti ugodnija.",
	"NoFrequentBrake": "Ako se uzdržite od naglog kočenja vaša vožnja će biti ugodnija.",
	"NoFrequentSteer": "Ako se uzdržite od naglog skretanja vaša vožnja će biti ugodnija.",
	"NotEnoughData": "Nuvarande körning innehåller inte tillräckligt med data för  analys.",
	"OperateClutch": "Ako pravilno menjate brzine vaša vošnja će biti prijatnija.",
	"RetryBtn": "Prova igen",
	"SelectSettings": "Välj inställningar",
	"SwitchView": "Nästa skärm",
	"VeryGood": "Vrlo dobro",
	"acc": "Hastighets.",
	"avg": "Genomsnitt",
	"avgScore": "Genomsnitts.",
	"brake": "Broms",
	"currDrvTrnd": "Aktuell körtrend",
	"currScore": "Aktuell poäng",
	"current": "Aktuell",
	"driver": "Förare",
	"drvAdvice": "Köranvisning",
	"endingScreen": "Avslutningsbild",
	"meterAmbientDisplay": "Mätare omgivande skärm",
	"min": "min",
	"minsago": "minuter sedan",
	"score": "poäng",
	"scoreTransition": "Poängöverföring",
	"settingIDM": "i-DM",
	"settings": "Inställningar",
	"simpleMode": "i-DM basläge",
	"stage1": "1st STAGE",
	"stage2": "2nd STAGE",
	"stage3": "3rd STAGE",
	"stage4": "4th STAGE",
	"stage5": "5th STAGE",
	"stageUp": "Upp ett stadie!",
	"stageinvalid": "INVALID STAGE",
	"steer": "Styrning",
	"trainingMode": "i-DM träningsläge",
};

framework.registerAppDictLoaded("idm", "sv_SE");