var Localization_amradioAppDict_id_ID = {
    //"stringId" : "localString"
    "UpdateStationList" : "Perbarui Daftar Stasiun",
    "AutoMemory" : "Daftar Memori Otomatis",
    "AMRadio" : "Radio AM",
    "UpdatingStationList" : "Memperbarui Daftar Stasiun",
    "Noresultsfound" : "Hasil tidak ditemukan",
    "TagSaved" : "Tag Disimpan ke iPod",
    "Remaining" : "{numberOfTags} Tersisa",
    "TagDuplicateIpodFull" : "Tag Telah Tersimpan",
    "TagSavedtoSystem" : "Tag Disimpan ke Sistem",
    "IopdFull" : "iPod Penuh",
    "ErrorNoMemorySystem" : "Memori Penuh",
    "ConnectiPod" : "Smbng iPod utk Trnsfr Tag",
    "ErrorNoMemoryAll" : "Semua Memori Penuh",
    "CannotBesaved" : "Tag Tidak Dapat Disimpan",
    "ErrorConnection" : "Galat Saat Mentransfer Tag ke iPod",
    "ErrorIpodFail" : "iPod Galat",
    "Reconnect" : "Cabut dan Sambung Lagi",
    "TagNotYetProcessed" : "Tag Belum Diproses",
    "TagTransferNoMemory" : "Tak Bisa Transfer Tag",
    "TagTransferIpodFull" : "Semua Tag Ditransfer",
    "TagTransferSuccess" : "Tag Ditransfer ke iPod",
    "TagSavedsbn" : "Tag Disimpan",
    "MemoryFullsbn" : "Memori Tag Penuh",
    "Back" : "Kembali",
    "Settings" : "Setelan",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Genre: {genreName}",
    "TrafficAlertOn" : "Peringatan Lalu-Lintas Aktif",
    "TrafficAlertOff" : "Peringatan Lalu-Lintas Nonaktif",
    "TagCaptured" : "Label Disimpan",
    "favorites_Tooltip" : "Favorit",
    "prev_Tooltip" : "Cari Sebelumnya",
    "next_Tooltip" : "Cari Berikutnya",
};

framework.registerAppDictLoaded("amradio", "id_ID");