var Localization_amradioAppDict_pl_PL = {
    //"stringId" : "localString"
    "UpdateStationList" : "Uaktualnij listę stacji",
    "AutoMemory" : "Lista zapamiętanych automatycznie",
    "AMRadio" : "Radio AM",
    "UpdatingStationList" : "Uaktualnianie listy stacji",
    "Noresultsfound" : "Nie znaleziono wyników.",
    "TagSaved" : "Znacznik zapisany w iPod",
    "Remaining" : "{numberOfTags} pozost.",
    "TagDuplicateIpodFull" : "Znacznik jest już zapisany",
    "TagSavedtoSystem" : "Znacznik zapisany w syst.",
    "IopdFull" : "Pamięć tabletu iPod pełna",
    "ErrorNoMemorySystem" : "Pamięć pełna",
    "ConnectiPod" : "Podł. iPod by przesł. znacz.",
    "ErrorNoMemoryAll" : "Pamięć pełna",
    "CannotBesaved" : "Zapis znaczn. niemożliwy",
    "ErrorConnection" : "Błąd podczas przesyłania znaczników do tabletu iPod.",
    "ErrorIpodFail" : "Błąd tabletu iPod.",
    "Reconnect" : "Odłącz i połącz ponownie",
    "TagNotYetProcessed" : "Znacznik nieprzetw.",
    "TagTransferNoMemory" : "Przesł. znaczn. niemożliwe",
    "TagTransferIpodFull" : "Wszystkie znaczn. przesł.",
    "TagTransferSuccess" : "Znaczn. przesłane do iPod",
    "TagSavedsbn" : "Znacznik zapisany",
    "MemoryFullsbn" : "Pamięć znaczników pełna",
    "Back" : "Do tyłu",
    "Settings" : "Ustawienia",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Gatunek: {genreName}",
    "TrafficAlertOn" : "Wyświetlanie alertów o ruchu drogowym wł.",
    "TrafficAlertOff" : "Wyświetlanie alertów o ruchu drogowym wył.",
    "TagCaptured" : "Znacznik uchwycony",
    "favorites_Tooltip" : "Ulubione",
    "prev_Tooltip" : "Szukaj poprzedniej",
    "next_Tooltip" : "Szukaj następnej",
};

framework.registerAppDictLoaded("amradio", "pl_PL");