var Localization_amradioAppDict_no_NO = {
    //"stringId" : "localString"
    "UpdateStationList" : "Oppdater stasjonsliste",
    "AutoMemory" : "Autominneliste",
    "AMRadio" : "AM-radio",
    "UpdatingStationList" : "Oppdaterer stasjonsliste",
    "Noresultsfound" : "Fant ingen resultater",
    "TagSaved" : "Taggen er lagret på iPod",
    "Remaining" : "{numberOfTags} gjenstår",
    "TagDuplicateIpodFull" : "Taggen er allerede lagret",
    "TagSavedtoSystem" : "Taggen er lagret på syst.",
    "IopdFull" : "iPod er full",
    "ErrorNoMemorySystem" : "Minnet er fullt",
    "ConnectiPod" : "Koble iPod til Tags",
    "ErrorNoMemoryAll" : "Minne er fullt",
    "CannotBesaved" : "Taggene kan ikke lagres",
    "ErrorConnection" : "Feil ved overføring av tagger til iPod",
    "ErrorIpodFail" : "iPod-feil",
    "Reconnect" : "Koble fra og til på nytt",
    "TagNotYetProcessed" : "Taggen er ikke behandlet ennå",
    "TagTransferNoMemory" : "Kan ikke overføre tagger",
    "TagTransferIpodFull" : "Alle taggene er overført",
    "TagTransferSuccess" : "Taggene overført til iPod",
    "TagSavedsbn" : "Taggen er lagret",
    "MemoryFullsbn" : "Tagg-minnet er fullt",
    "Back" : "Tilbake",
    "Settings" : "Innstillinger",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Sjanger: {genreName}",
    "TrafficAlertOn" : "Trafikkvarsel på",
    "TrafficAlertOff" : "Trafikkvarsel av",
    "TagCaptured" : "Tagg opptak",
    "favorites_Tooltip" : "Favoritter",
    "prev_Tooltip" : "Gå til forrige",
    "next_Tooltip" : "Gå til neste",
};

framework.registerAppDictLoaded("amradio", "no_NO");