var Localization_amradioAppDict_sk_SK = {
    //"stringId" : "localString"
    "UpdateStationList" : "Aktualizovať zoznam staníc",
    "AutoMemory" : "Zoznam automatickej pamäte",
    "AMRadio" : "AM rádio",
    "UpdatingStationList" : "Aktualizácia zoznamu staníc",
    "Noresultsfound" : "Nenašli sa žiadne výsledky",
    "TagSaved" : "Značka uložená do iPodu",
    "Remaining" : "Zostáva {numberOfTags}",
    "TagDuplicateIpodFull" : "Značka už uložená",
    "TagSavedtoSystem" : "Značka uložená do sys.",
    "IopdFull" : "iPod je plný",
    "ErrorNoMemorySystem" : "Pamäť plná",
    "ConnectiPod" : "Prip. iPod na pren. zn.",
    "ErrorNoMemoryAll" : "Celá pamäť plná",
    "CannotBesaved" : "Značky nemožno uložiť",
    "ErrorConnection" : "Chyba počas prenosu značiek do zariadenia iPod",
    "ErrorIpodFail" : "Chyba iPod-u",
    "Reconnect" : "Odpojiť a znovu pripojiť",
    "TagNotYetProcessed" : "Značka ešte nie je spracovaná",
    "TagTransferNoMemory" : "Značky nemožno preniesť",
    "TagTransferIpodFull" : "Všetky značky prenesené",
    "TagTransferSuccess" : "Tagy prenesené do iPodu",
    "TagSavedsbn" : "Značka uložená",
    "MemoryFullsbn" : "Pamäť značiek plná",
    "Back" : "Späť",
    "Settings" : "Nastavenia",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žáner: {genreName}",
    "TrafficAlertOn" : "Premávka zap.",
    "TrafficAlertOff" : "Premávka zap.",
    "TagCaptured" : "Značka zachytená",
    "favorites_Tooltip" : "Obľúbené",
    "prev_Tooltip" : "Vyhľadať predošlé",
    "next_Tooltip" : "Vyhľadať nasledovné",
};

framework.registerAppDictLoaded("amradio", "sk_SK");