var Localization_amradioAppDict_hr_HR = {
    //"stringId" : "localString"
    "UpdateStationList" : "Ažuriraj popis postaja",
    "AutoMemory" : "Popis automatske memorije",
    "AMRadio" : "AM radio",
    "UpdatingStationList" : "Ažuriranje popisa postaja ",
    "Noresultsfound" : "Nisu pronađeni rezultati",
    "TagSaved" : "Oznaka spremljena u iPod",
    "Remaining" : "Preostalo {numberOfTags}",
    "TagDuplicateIpodFull" : "Oznaka je već spremljena",
    "TagSavedtoSystem" : "Oznaka spremljena u sust.",
    "IopdFull" : "iPod pun",
    "ErrorNoMemorySystem" : "Puna memorija",
    "ConnectiPod" : "Pov. iPod na oznake prijen.",
    "ErrorNoMemoryAll" : "Memorija je puna",
    "CannotBesaved" : "Oznake nemoguće spremiti",
    "ErrorConnection" : "Pogreška pri prijenosu oznaka na iPod",
    "ErrorIpodFail" : "Pogreška iPoda",
    "Reconnect" : "Isključi i ponovno poveži",
    "TagNotYetProcessed" : "Oznaka još nije obrađena",
    "TagTransferNoMemory" : "Oznake nemoguće prenijeti",
    "TagTransferIpodFull" : "Sve oznake prenesene",
    "TagTransferSuccess" : "Oznake prenesene u iPod",
    "TagSavedsbn" : "Oznaka spremljena",
    "MemoryFullsbn" : "Memorija oznaka puna",
    "Back" : "Natrag",
    "Settings" : "Postavke",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žanr: {genreName}",
    "TrafficAlertOn" : "Promet. upoz. uklj.",
    "TrafficAlertOff" : "Promet. upoz. isklj.",
    "TagCaptured" : "Oznaka snimlj.",
    "favorites_Tooltip" : "Favoriti",
    "prev_Tooltip" : "Traži prethodno",
    "next_Tooltip" : "Traži sljedeće",
};

framework.registerAppDictLoaded("amradio", "hr_HR");