var Localization_amradioAppDict_lv_LV = {
    //"stringId" : "localString"
    "UpdateStationList" : "Atjaunināt staciju sarakstu",
    "AutoMemory" : "Automātiskās atmiņas saraksts",
    "AMRadio" : "AM radio",
    "UpdatingStationList" : "Atjaunina staciju sarakstu",
    "Noresultsfound" : "Nav atrasts neviens rezultāts",
    "TagSaved" : "Atzīme saglabāta iPod ier.",
    "Remaining" : "Atlik. {numberOfTags} atz.",
    "TagDuplicateIpodFull" : "Atzīme jau saglabāta",
    "TagSavedtoSystem" : "Atzīme saglabāta sistēmā",
    "IopdFull" : "iPod pilna",
    "ErrorNoMemorySystem" : "Atmiņa pilna",
    "ConnectiPod" : "Piev. iPod, lai pārs. atzīm.",
    "ErrorNoMemoryAll" : "Visa atmiņa ir pilna",
    "CannotBesaved" : "Atzīmes nevar saglabāt",
    "ErrorConnection" : "Kļūda, pārsūtot atzīmes uz iPod",
    "ErrorIpodFail" : "iPod kļūda",
    "Reconnect" : "Atvienot un pievienot",
    "TagNotYetProcessed" : "Atzīme vēl nav apstrādāta",
    "TagTransferNoMemory" : "Nevar pārsūtīt atzīmes",
    "TagTransferIpodFull" : "Visas atzīmes pārsūtītas",
    "TagTransferSuccess" : "Atzīmes pārsūt. uz iPod",
    "TagSavedsbn" : "Atzīme saglabāta",
    "MemoryFullsbn" : "Atzīmju atmiņa pilna",
    "Back" : "Atpakaļ",
    "Settings" : "Iestatījumi",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žanrs: {genreName}",
    "TrafficAlertOn" : "Satiksmes brīdinājumi ieslēgti",
    "TrafficAlertOff" : "Satiksmes brīdinājumi izslēgti",
    "TagCaptured" : "Atzīme uztverta",
    "favorites_Tooltip" : "Izlase",
    "prev_Tooltip" : "Meklēt iepriekšējo",
    "next_Tooltip" : "Meklēt nākamo",
};

framework.registerAppDictLoaded("amradio", "lv_LV");