var Localization_amradioAppDict_et_EE = {
    //"stringId" : "localString"
    "UpdateStationList" : "Värskenda jaamade loendit",
    "AutoMemory" : "Automaatse mälu loend",
    "AMRadio" : "AM-raadio",
    "UpdatingStationList" : "Jaamade loendi värskendamine",
    "Noresultsfound" : "Tulemusi ei leitud",
    "TagSaved" : "Silt on iPodi salvestatud",
    "Remaining" : "{numberOfTags} jäänud",
    "TagDuplicateIpodFull" : "Silt on juba salvestatud",
    "TagSavedtoSystem" : "Silt süsteemi salvestatud",
    "IopdFull" : "iPod täis",
    "ErrorNoMemorySystem" : "Mälu täis",
    "ConnectiPod" : "Üh iPod siltide edastam",
    "ErrorNoMemoryAll" : "Kogu mälu on täis",
    "CannotBesaved" : "Silte ei saa salvestada",
    "ErrorConnection" : "Viga siltide edastamisel iPodi",
    "ErrorIpodFail" : "iPodi viga",
    "Reconnect" : "Lahutage ja ühend. uuesti",
    "TagNotYetProcessed" : "Silti pole veel töödeldud",
    "TagTransferNoMemory" : "Silte ei saa edastada",
    "TagTransferIpodFull" : "Kõik sildid edastatud",
    "TagTransferSuccess" : "Sildid on iPodi edastatud",
    "TagSavedsbn" : "Silt on salvestatud",
    "MemoryFullsbn" : "Sildi mälu täis",
    "Back" : "Tagasi",
    "Settings" : "Sätted",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žanr: {genreName}",
    "TrafficAlertOn" : "Liiklusteated sees",
    "TrafficAlertOff" : "Liiklusteated väljas",
    "TagCaptured" : "Silt jäädvustatud",
    "favorites_Tooltip" : "Lemmikud",
    "prev_Tooltip" : "Otsi eelmist",
    "next_Tooltip" : "Otsi järgmist",
};

framework.registerAppDictLoaded("amradio", "et_EE");