var Localization_amradioAppDict_es_MX = {
    //"stringId" : "localString"
    "UpdateStationList" : "Actualizar lista de emisoras",
    "AutoMemory" : "Lista de memoria automática ",
    "AMRadio" : "Radio AM",
    "UpdatingStationList" : "Actualizando lista de emisoras",
    "Noresultsfound" : "No se encontraron resultados",
    "TagSaved" : "Etiq Guardada en iPod",
    "Remaining" : "{numberOfTags} Restant",
    "TagDuplicateIpodFull" : "Etiq Guardada",
    "TagSavedtoSystem" : "Etiq Guardada en Sist",
    "IopdFull" : "iPod Lleno",
    "ErrorNoMemorySystem" : "Memoria llena",
    "ConnectiPod" : "Conect iPod y Trans Etiq",
    "ErrorNoMemoryAll" : "Memoria Llena",
    "CannotBesaved" : "No puede Guardar Etiq",
    "ErrorConnection" : "Error mientras se transferían etiquetas al iPod",
    "ErrorIpodFail" : "Error de iPod",
    "Reconnect" : "Desconectar y Reconectar",
    "TagNotYetProcessed" : "La Etiqueta Aún no se ha Procesado",
    "TagTransferNoMemory" : "No puede Transf. Etiq",
    "TagTransferIpodFull" : "Todas las Etiq Transferidas",
    "TagTransferSuccess" : "Eyiq transferidas a iPod",
    "TagSavedsbn" : "Etiqueta Guardada",
    "MemoryFullsbn" : "Memoria de Etiquetas Llena",
    "Back" : "Atrás  ",
    "Settings" : "Configuración",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entretenimiento ",
    "VrHelp_NowPlaying_US_Help_Left2" : "Memoria Automática",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favoritos",
    "VrHelp_NowPlaying_US_Help_Left4" : "Añadir a Favoritos",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD Encendido / Apagado",
    "VrHelp_NowPlaying_US_Help_Right1" : "Explorar",
    "VrHelp_NowPlaying_US_Help_Right2" : "Sintonizar",
    "VrHelp_NowPlaying_US_Help_Right3" : "Etiquetado iTunes",
    "VrHelp_NowPlaying_US_Help_Right4" : "Buscar Anterior",
    "VrHelp_NowPlaying_US_Help_Right5" : "Buscar Siguiente",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entretenimiento ",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Memoria Automática",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favoritos",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Añadir a Favoritos",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Explorar",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Sintonizar",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Buscar Anterior",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Buscar Siguiente",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Alerta de Tráfico",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Configuración de Sonido",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entretenimiento ",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Memoria Automática",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favoritos",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Añadir a Favoritos",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Explorar",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Sintonizar",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Buscar Anterior",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Buscar Siguiente",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Configuración de Sonido",
    "VrHelp_AutoMemory_Help1_Left1" : "(frecuencia)",
    "VrHelp_AutoMemory_Help1_Left2" : "Actualizar Lista",
    "VrHelp_AutoMemory_Help2_Left1" : "Actualizar Lista",
    "VrHelp_Tune_Help1_Left1" : "(frecuencia)",
    "VrHelp_Tune_Help1_Left2" : "Sintonizar Abajo",
    "VrHelp_Tune_Help1_Left3" : "Sintonizar Arriba",
    "VrHelp_Tune_Help2_Left1" : "(frecuencia)",
    "VrHelp_Tune_Help2_Left2" : "Sintonizar Abajo",
    "VrHelp_Tune_Help2_Left3" : "Sintonizar Arriba",
    "GenreName" : "Género: {genreName}",
    "TrafficAlertOn" : "Alerta de Tráfico On",
    "TrafficAlertOff" : "Alerta de Tráfico Off",
    "TagCaptured" : "Etiqueta Capturada",
    "favorites_Tooltip" : "Favoritos",
    "prev_Tooltip" : "Buscar Anterior ",
    "next_Tooltip" : "Buscar Siguiente",
};

framework.registerAppDictLoaded("amradio", "es_MX");