var Localization_amradioAppDict_ms_MY = {
    //"stringId" : "localString"
    "UpdateStationList" : "Kemas Kini Senarai Stesen",
    "AutoMemory" : "Senarai Memori Auto",
    "AMRadio" : "Radio AM",
    "UpdatingStationList" : "Mengemas Kini Senarai Stesen",
    "Noresultsfound" : "Tiada hasil ditemui",
    "TagSaved" : "Teg Disimpan pada iPod",
    "Remaining" : "{numberOfTags} Berbaki",
    "TagDuplicateIpodFull" : "Teg Telah Disimpan",
    "TagSavedtoSystem" : "Teg Disimpan pada Sistem",
    "IopdFull" : "iPod Penuh",
    "ErrorNoMemorySystem" : "Memori Penuh",
    "ConnectiPod" : "Sambung iPod utk Pindah Teg",
    "ErrorNoMemoryAll" : "Semua Memori Penuh",
    "CannotBesaved" : "Teg Tidak Dapat Disimpan",
    "ErrorConnection" : "Ralat Berlaku Semasa Memindahkan Teg ke iPod",
    "ErrorIpodFail" : "Ralat iPod",
    "Reconnect" : "Tanggal & Samb. Semula",
    "TagNotYetProcessed" : "Teg Belum Diproses Lagi",
    "TagTransferNoMemory" : "Tdk Blh Pindah Tag",
    "TagTransferIpodFull" : "Semua Teg Dipindahkan",
    "TagTransferSuccess" : "Teg Dipindahkan ke iPod",
    "TagSavedsbn" : "Teg Disimpan",
    "MemoryFullsbn" : "Memori Teg Penuh",
    "Back" : "Kembali",
    "Settings" : "Tetapan",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Genre: {genreName}",
    "TrafficAlertOn" : "Makluman Lalu Lintas Dihidupkan",
    "TrafficAlertOff" : "Makluman Lalu Lintas Dimatikan",
    "TagCaptured" : "Teg Dirakamkan",
    "favorites_Tooltip" : "Kegemaran",
    "prev_Tooltip" : "Cari Sebelumnya",
    "next_Tooltip" : "Cari Seterusnya",
};

framework.registerAppDictLoaded("amradio", "ms_MY");