var Localization_amradioAppDict_cs_CS = {
    //"stringId" : "localString"
    "UpdateStationList" : "Aktualizovat seznam stanic",
    "AutoMemory" : "Automatický seznam paměti",
    "AMRadio" : "Rádio AM",
    "UpdatingStationList" : "Aktualizace seznamu stanic",
    "Noresultsfound" : "Nebyl nalezen žádný výsledek",
    "TagSaved" : "Záložka uložena do iPodu",
    "Remaining" : "Zůstává {numberOfTags}",
    "TagDuplicateIpodFull" : "Záložka je již uložena.",
    "TagSavedtoSystem" : "Záložka uložena v systém",
    "IopdFull" : "iPod zaplněn",
    "ErrorNoMemorySystem" : "Paměť zaplněna",
    "ConnectiPod" : "Připojit iPod k záložkám",
    "ErrorNoMemoryAll" : "Paměť je plná",
    "CannotBesaved" : "Záložky nelze uložit",
    "ErrorConnection" : "Při přenosu záložek do iPodu došlo k chybě.",
    "ErrorIpodFail" : "Chyba iPodu",
    "Reconnect" : "Odpojit a znovu zapojit",
    "TagNotYetProcessed" : "Záložka zatím nezpracována.",
    "TagTransferNoMemory" : "Nelze přenést záložky",
    "TagTransferIpodFull" : "Všechny zálož. přeneseny",
    "TagTransferSuccess" : "Zálož. přeneseny do iPodu",
    "TagSavedsbn" : "Záložka uložena",
    "MemoryFullsbn" : "Paměť záložek je plná.",
    "Back" : "Vzadu",
    "Settings" : "Nastavení",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žánr : {genreName}",
    "TrafficAlertOn" : "Dopravní výstraha Zapn.",
    "TrafficAlertOff" : "Dopravní výstraha Vypn.",
    "TagCaptured" : "Zaškrtnutí zaznamenáno",
    "favorites_Tooltip" : "Oblíbené",
    "prev_Tooltip" : "Vyhledat předchozí",
    "next_Tooltip" : "Vyhledat další",
};

framework.registerAppDictLoaded("amradio", "cs_CS");