var Localization_amradioAppDict_bg_BG = {
    //"stringId" : "localString"
    "UpdateStationList" : "Актуал. спис. станции",
    "AutoMemory" : "Списък с авт. запаметени",
    "AMRadio" : "Радио AM",
    "UpdatingStationList" : "Актуал. спис. станции",
    "Noresultsfound" : "Няма намерени резултати",
    "TagSaved" : "Тагът е записан в iPod",
    "Remaining" : "Остават {numberOfTags}",
    "TagDuplicateIpodFull" : "Тагът е вече записан",
    "TagSavedtoSystem" : "Тагът е записан в сист.",
    "IopdFull" : "iPod е пълен",
    "ErrorNoMemorySystem" : "Паметта е пълна",
    "ConnectiPod" : "Свър. iPod за прехв. таг.",
    "ErrorNoMemoryAll" : "Цялата памет е пълна",
    "CannotBesaved" : "Таг-те не се записв.",
    "ErrorConnection" : "Грешка при прехвърляне на тагове в iPod",
    "ErrorIpodFail" : "Грешка в iPod",
    "Reconnect" : "Извади и свържи отново",
    "TagNotYetProcessed" : "Тагът още не е обработен",
    "TagTransferNoMemory" : "Таг-те не се прехв.",
    "TagTransferIpodFull" : "Вс. таг-ве са прехв.",
    "TagTransferSuccess" : "Таг-те прехв. в iPod",
    "TagSavedsbn" : "Тагът е записан",
    "MemoryFullsbn" : "Паметта за тагове е пълна",
    "Back" : "Назад",
    "Settings" : "Настройки",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Жанр: {genreName}",
    "TrafficAlertOn" : "Включено предупреждение за движението",
    "TrafficAlertOff" : "Изключено предупреждение за движението",
    "TagCaptured" : "Тагът е снет",
    "favorites_Tooltip" : "Предпочитани",
    "prev_Tooltip" : "Търсене на предишна",
    "next_Tooltip" : "Търсене на следваща",
};

framework.registerAppDictLoaded("amradio", "bg_BG");