var Localization_amradioAppDict_tr_TR = {
    //"stringId" : "localString"
    "UpdateStationList" : "İstasyon Listesini Güncelle",
    "AutoMemory" : "Otomatik Hafıza Listesi",
    "AMRadio" : "AM Radyo",
    "UpdatingStationList" : "İstasyon Listesi Güncelleniyor",
    "Noresultsfound" : "Sonuç bulunamadı",
    "TagSaved" : "Etiket iPod'a Kaydedildi",
    "Remaining" : "Kalan: {numberOfTags}",
    "TagDuplicateIpodFull" : "Etiket Zaten Kayıtlı",
    "TagSavedtoSystem" : "Etiket Sisteme Kaydedildi",
    "IopdFull" : "iPod Dolu",
    "ErrorNoMemorySystem" : "Hafıza Dolu",
    "ConnectiPod" : "Etiket için iPod'u Bağla",
    "ErrorNoMemoryAll" : "Tüm Hafıza Dolu",
    "CannotBesaved" : "Etiketler Kaydedilemiyor",
    "ErrorConnection" : "Etiketler iPod'a Aktarılırken Hata Oluştu",
    "ErrorIpodFail" : "iPod Hatası",
    "Reconnect" : "Çıkar ve Yeniden Bağla",
    "TagNotYetProcessed" : "Etiket Henüz İşlenmedi",
    "TagTransferNoMemory" : "Etiketler Aktarılamıyor",
    "TagTransferIpodFull" : "Tüm Etiketler Aktarıldı",
    "TagTransferSuccess" : "Etiketler iPod'a Aktarıldı",
    "TagSavedsbn" : "Etiket Kaydedildi",
    "MemoryFullsbn" : "Etiket Hafızası Dolu",
    "Back" : "Geri",
    "Settings" : "Ayarlar",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Tür: {genreName}",
    "TrafficAlertOn" : "Trafik Uyarısı Açık",
    "TrafficAlertOff" : "Trafik Uyarısı Kapalı",
    "TagCaptured" : "Etiket Alındı",
    "favorites_Tooltip" : "Omiljeni",
    "prev_Tooltip" : "Predhodna",
    "next_Tooltip" : "Sledeća",
};

framework.registerAppDictLoaded("amradio", "tr_TR");