var Localization_amradioAppDict_sr_RS = {
    //"stringId" : "localString"
    "UpdateStationList" : "Ažuriraj listu stanica",
    "AutoMemory" : "Lista automatske memorije",
    "AMRadio" : "AM radio",
    "UpdatingStationList" : "Ažuriranje liste stanica",
    "Noresultsfound" : "Nema pronađenih rezultata",
    "TagSaved" : "Oznaka sačuv.na iPod-u",
    "Remaining" : "{numberOfTags} preostalo",
    "TagDuplicateIpodFull" : "Oznaka je već sačuvana",
    "TagSavedtoSystem" : "Ozn.sačuv. u sist.",
    "IopdFull" : "iPod je pun",
    "ErrorNoMemorySystem" : "Puna memorija",
    "ConnectiPod" : "Poveži iPod za prenos ozn",
    "ErrorNoMemoryAll" : "Sva memorija je puna",
    "CannotBesaved" : "Nemoguće sačuvati ozn.",
    "ErrorConnection" : "Greška pri prenosu oznaka na iPod",
    "ErrorIpodFail" : "Greška u iPod-u",
    "Reconnect" : "Izvucite i ponovo povežite",
    "TagNotYetProcessed" : "Oznaka još nije obrađena",
    "TagTransferNoMemory" : "Ozn.se ne mogu preneti",
    "TagTransferIpodFull" : "Sve oznake su prebačene",
    "TagTransferSuccess" : "Ozn. su prebačene",
    "TagSavedsbn" : "Oznaka je sačuvana",
    "MemoryFullsbn" : "Memorija oznaka je puna",
    "Back" : "Nazad",
    "Settings" : "Postavke",
    "VrHelp_NowPlaying_US_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_US_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_US_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_US_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_US_Help_Left5" : "HD On / Off",
    "VrHelp_NowPlaying_US_Help_Right1" : "Scan",
    "VrHelp_NowPlaying_US_Help_Right2" : "Tune",
    "VrHelp_NowPlaying_US_Help_Right3" : "iTunes Tagging",
    "VrHelp_NowPlaying_US_Help_Right4" : "Seek Previous",
    "VrHelp_NowPlaying_US_Help_Right5" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_EU_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_EU_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_EU_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_EU_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_EU_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_EU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_EU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_EU_Help_Right4" : "Traffic Alert",
    "VrHelp_NowPlaying_EU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlaying_Japan_Help_Left1" : "Entertainment",
    "VrHelp_NowPlaying_Japan_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlaying_Japan_Help_Left3" : "Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left4" : "Add to Favorites",
    "VrHelp_NowPlaying_Japan_Help_Left5" : "Scan",
    "VrHelp_NowPlaying_Japan_Help_Right1" : "Tune",
    "VrHelp_NowPlaying_Japan_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlaying_Japan_Help_Right3" : "Seek Next",
    "VrHelp_NowPlaying_Japan_Help_Right4" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_Help1_Left1" : "(frequency)",
    "VrHelp_Tune_Help1_Left2" : "Tune Down",
    "VrHelp_Tune_Help1_Left3" : "Tune Up",
    "VrHelp_Tune_Help2_Left1" : "(frequency)",
    "VrHelp_Tune_Help2_Left2" : "Tune Down",
    "VrHelp_Tune_Help2_Left3" : "Tune Up",
    "GenreName" : "Žanr: {genreName}",
    "TrafficAlertOn" : "Upozorenja o stanju saobraćaja uključena",
    "TrafficAlertOff" : "Upozorenja o stanju saobraćaja isključena",
    "TagCaptured" : "Oznaka sačuvana",
    "favorites_Tooltip" : "Omiljeni",
    "prev_Tooltip" : "Predhodna",
    "next_Tooltip" : "Sledeća",
};

framework.registerAppDictLoaded("amradio", "sr_RS");