var Localization_ecoenergyAppDict_zh_TW = {
    //"stringId" : "localString"
    "EcoDriveStatus" : "經濟駕駛狀態",
    "CurrentDriveFuelTitle" : "燃油經濟性（本磁碟機）",
    "CummulativeFuelEconomyReset" : "平均燃油經濟性歷史",
    "AverageFuelEconomy" : "平均（本磁碟機）",
    "ElapsedTimeInMin" : "分鐘",
    "CurrentStatus" : "目前",
    "Ready" : "準備好",
    "NotReady" : "未準備好",
    "ErrorSteering" : "請將方向盤切換到中心。",
    "ErrorBrake" : "請應用更多制動壓力。",
    "ErrorShift" : "請換到空檔。",
    "ErrorEngineRestart" : "發動機需要重啟",
    "ErrorUnknown" : "i-stop 不可用。",
    "TotalTimeTitle" : "總時間",
    "CummulativeFuelEconomy" : "均（自復位）",
    "ActuationTimeTitle" : "活動時間",
    "StopTimeTitle" : "停止時間",
    "CelebrationMessage" : "祝賀！",
    "Settings" : "設定",
    "kml" : "km/L",
    "mpg" : "mpg",
    "lkm" : "L/100km",
    "SbnTitleId" : "燃油經濟性監視器",
    "iStopOnTitle" : "% i-stop ON（本磁碟機）",
    "iStopBoost" : "i-stop 增加的總行程",
    "ResetUnsuccessful" : "復位失敗。您是否希望重試？",
    "CancelBtn" : "取消",
    "RetryBtn" : "重試",
    "IgnitionOff" : "熄火時顯示幕幕",
    "SyncTripA" : "同步平均和里程 A",
    "Km" : "公里",
    "Miles" : "英里",
    "HidePanel" : "隱藏按鈕",
    "ApplicationsMenu" : "應用程式",
    "Reset" : "復位平均",
    "SelectSettings" : "設定",
    "SettingsRetryMsg" : "無法修改同步平均和里程 A 設定",
    "iStopOn" : "i-stop ON",
    "ErrorReady" : "準備好。",
    "ErrorActivated" : "無法啟動。",
    "SwitchView" : "下一螢幕",
    "energyFlow" : "能量流",
    "cumulativeEV" : "累計 EV 行駛距離",
    "oneDriveEV" : "累計 EV 行駛距離",
    "TotalActive" : "活動時間",
    "SinceReset" : "（自復位）",
    "ThisDrive" : "（本次行駛）",
    "Average" : "平均",
    "OneDrv" : "一次行駛",
    "EVDistn" : "EV 距離",
    "Wh" : "Wh",
    "batteryId" : "BATTERY",
    "motorId" : "MOTOR",
    "engineId" : "ENGINE",
};

framework.registerAppDictLoaded("ecoenergy", "zh_TW");