var Localization_ecoenergyAppDict_sv_SE = {
    //"stringId" : "localString"
    "EcoDriveStatus" : "Ekokörning",
    "CurrentDriveFuelTitle" : "Förbr (Denna Körn)",
    "CummulativeFuelEconomyReset" : "Snittförbr (Hist)",
    "AverageFuelEconomy" : "Snitt (Körn)",
    "ElapsedTimeInMin" : "min",
    "CurrentStatus" : "Aktuell",
    "Ready" : "KLAR",
    "NotReady" : "INTE KLAR",
    "ErrorSteering" : "Vrid ratten till rakt fram.",
    "ErrorBrake" : "Tryck hårdare på bromsen.",
    "ErrorShift" : "Lägg växeln i neutral.",
    "ErrorEngineRestart" : "Motorn behöver startas om",
    "ErrorUnknown" : "i-stop är inte tillgängligt.",
    "TotalTimeTitle" : "Total Tid",
    "CummulativeFuelEconomy" : "Snitt (Eft 0)",
    "ActuationTimeTitle" : "Tid Aktiv",
    "StopTimeTitle" : "Stoppad",
    "CelebrationMessage" : "Gratulerar!",
    "Settings" : "Inställningar",
    "kml" : "km/L",
    "mpg" : "mpg",
    "lkm" : "L/100km",
    "SbnTitleId" : "Bränsleförbruknings",
    "iStopOnTitle" : "% i-stop ON",
    "iStopBoost" : "Räckvidd tack vare i-stop",
    "ResetUnsuccessful" : "Återställning misslyckades. Vill du prova igen?",
    "CancelBtn" : "Avbryt",
    "RetryBtn" : "Prova igen",
    "IgnitionOff" : "Visa skärm när tändning av",
    "SyncTripA" : "Synka Snitt och Trip A",
    "Km" : "km",
    "Miles" : "mi",
    "HidePanel" : "Dölj knappar",
    "ApplicationsMenu" : "Program",
    "Reset" : "Nollställ Snitt",
    "SelectSettings" : "Inställningar",
    "SettingsRetryMsg" : "Synkronisera Snitt och Trip A-inställning kunde inte ändras",
    "iStopOn" : "i-stop ON",
    "ErrorReady" : "Klar.",
    "ErrorActivated" : "Kan inte aktiveras.",
    "SwitchView" : "Nästa Skärm",
    "energyFlow" : "Energiflöde",
    "cumulativeEV" : "Ackumulerad EV-körsträcka",
    "oneDriveEV" : "Enstaka EV-sträcka",
    "TotalActive" : "Tid Aktiv",
    "SinceReset" : "Eft 0",
    "ThisDrive" : " ",
    "Average" : "Snitt",
    "OneDrv" : "En gång",
    "EVDistn" : "EV-sträcka",
    "Wh" : "Wh",
    "batteryId" : "BATTERY",
    "motorId" : "MOTOR",
    "engineId" : "ENGINE",
};

framework.registerAppDictLoaded("ecoenergy", "sv_SE");