var Localization_ecoenergyAppDict_ro_RO = {
    //"stringId" : "localString"
    "EcoDriveStatus" : "Status Eco Drive",
    "CurrentDriveFuelTitle" : "Ecn. combus. (acest drum)",
    "CummulativeFuelEconomyReset" : "Istoric econ. combust. medie",
    "AverageFuelEconomy" : "Medie (drum act.)",
    "ElapsedTimeInMin" : "min",
    "CurrentStatus" : "Curent",
    "Ready" : "PREGĂTIT",
    "NotReady" : "NEPREGĂTIT",
    "ErrorSteering" : "Întoarceţi volanul spre centru.",
    "ErrorBrake" : "Aplicaţi mai multă presiune pe frână.",
    "ErrorShift" : "Schimbaţi la neutru.",
    "ErrorEngineRestart" : "Motorul trebuie să fie repornit",
    "ErrorUnknown" : "i-stop nu este disponibil",
    "TotalTimeTitle" : "Timp total",
    "CummulativeFuelEconomy" : "Med. (dp. rst.)",
    "ActuationTimeTitle" : "Durată activare",
    "StopTimeTitle" : "Oprire",
    "CelebrationMessage" : "Felicitări!",
    "Settings" : "Setări",
    "kml" : "km/L",
    "mpg" : "mpg",
    "lkm" : "L/100km",
    "SbnTitleId" : "Economie Combustibil",
    "iStopOnTitle" : "% i-stop ON",
    "iStopBoost" : "i-stop Autonomie amplificată",
    "ResetUnsuccessful" : "Resetarea a fost nereuşită. Reîncercaţi?",
    "CancelBtn" : "Anulare",
    "RetryBtn" : "Reîncercare",
    "IgnitionOff" : "Afiş. ecran la decuplare contact",
    "SyncTripA" : "Sincronizare medie şi Parcurs A",
    "Km" : "km",
    "Miles" : "mi",
    "HidePanel" : "Ascundere butoane",
    "ApplicationsMenu" : "Aplicaţii",
    "Reset" : "Resetare medie",
    "SelectSettings" : "Setări",
    "SettingsRetryMsg" : "Sincronizare medie şi Parcurs A nu au putut fi modificate",
    "iStopOn" : "i-stop ON",
    "ErrorReady" : "Pregătit.",
    "ErrorActivated" : "Nu se poate activa.",
    "SwitchView" : "Ecranul următor",
    "energyFlow" : "Flux de energie",
    "cumulativeEV" : "Dist. cumulativă de condus EV",
    "oneDriveEV" : "Distanţa EV o cursă",
    "TotalActive" : "Activ ",
    "SinceReset" : " ",
    "ThisDrive" : " ",
    "Average" : "Medie",
    "OneDrv" : "O cursă",
    "EVDistn" : "Distanţa EV",
    "Wh" : "Wh",
    "batteryId" : "BATERIE",
    "motorId" : "MOTOR",
    "engineId" : "MOTOR",
};

framework.registerAppDictLoaded("ecoenergy", "ro_RO");