var Localization_ecoenergyAppDict_ar_SA = {
    //"stringId" : "localString"
    "EcoDriveStatus" : "قيادة اقتصادية",
    "CurrentDriveFuelTitle" : "وقود اقتصادي (هذا المحرك)",
    "CummulativeFuelEconomyReset" : "سجل متوسط اقتصاد الوقود",
    "AverageFuelEconomy" : "متوسط (المحرك)",
    "ElapsedTimeInMin" : "دقيقة",
    "CurrentStatus" : "الحالي",
    "Ready" : "جاهز",
    "NotReady" : "غير جاهز",
    "ErrorSteering" : "يرجى إدارة عجلة القيادة إلى المنتصف.",
    "ErrorBrake" : "يرجى  زيادة الضغط على المكابح.",
    "ErrorShift" : "يرجى الانتقال إلى وضع محايد.",
    "ErrorEngineRestart" : "يجب إعادة بدء تشغيل المحرك.",
    "ErrorUnknown" : "خاصية i-stop غير متاحة.",
    "TotalTimeTitle" : "زمن كلي",
    "CummulativeFuelEconomy" : "متوسط (م…",
    "ActuationTimeTitle" : "تنشيط الوقت",
    "StopTimeTitle" : "إيقاف الوقت",
    "CelebrationMessage" : "تهانينا!",
    "Settings" : "الإعدادات",
    "kml" : "كم/ل",
    "mpg" : "mpg",
    "lkm" : "ل/100كم",
    "SbnTitleId" : "مراقبة الاقتصاد في الوقود",
    "iStopOnTitle" : "% i-stop ON (هذا المحرك)",
    "iStopBoost" : "إجمالي النطاق الخاضع للتحسين بواسطة i-stop",
    "ResetUnsuccessful" : "لم تنجح إعادة الضبط. هل ترغب في إعادة المحاولة؟",
    "CancelBtn" : "إلغاء",
    "RetryBtn" : "أعد المحاولة",
    "IgnitionOff" : "عرض الشاشة عند إبطال المحرك",
    "SyncTripA" : "متوسط المزامنة وTrip A",
    "Km" : "كم",
    "Miles" : "ميل",
    "HidePanel" : "إخفاء الأزرار",
    "ApplicationsMenu" : "التطبيقات",
    "Reset" : "إعادة ضبط المتوسط",
    "SelectSettings" : "الإعدادات",
    "SettingsRetryMsg" : "لا يمكن تغيير إعداد متوسط المزامنة وTrip A",
    "iStopOn" : "i-stop ON",
    "ErrorReady" : "جاهز.",
    "ErrorActivated" : "لا يمكن التنشيط.",
    "SwitchView" : "الشاشة التالية",
    "energyFlow" : "تدفق الطاقة",
    "cumulativeEV" : "مسافة قيادة EV التراكمية",
    "oneDriveEV" : "مسافة EV لمحرك واحد",
    "TotalActive" : "تنشيط الوقت",
    "SinceReset" : "(منذ إعادة الضبط)",
    "ThisDrive" : "(هذا المحرك)",
    "Average" : "متوسط",
    "OneDrv" : "محرك واحد",
    "EVDistn" : "مسافة EV",
    "Wh" : "Wh",
    "batteryId" : "BATTERY",
    "motorId" : "MOTOR",
    "engineId" : "ENGINE",
};

framework.registerAppDictLoaded("ecoenergy", "ar_SA");