var Localization_ecoenergyAppDict_ru_RU = {
    //"stringId" : "localString"
    "EcoDriveStatus" : "Статус Eco Drive",
    "CurrentDriveFuelTitle" : "Эк. топ-а (дан. езда)",
    "CummulativeFuelEconomyReset" : "Ист. срд. эк. топлива",
    "AverageFuelEconomy" : "Срд. (дан. езда)",
    "ElapsedTimeInMin" : "мин",
    "CurrentStatus" : "Текущ.",
    "Ready" : "ГОТОВО",
    "NotReady" : "НЕ ГОТОВО",
    "ErrorSteering" : "Поверните рулевое колесо центр.",
    "ErrorBrake" : "Сильнее нажмите на педаль тормоза",
    "ErrorShift" : "Переключитесь на нейтральную.",
    "ErrorEngineRestart" : "Необходимо перезапустить двигатель",
    "ErrorUnknown" : "сервис i-stop недоступен.",
    "TotalTimeTitle" : "Общ. врм",
    "CummulativeFuelEconomy" : "Срд. (п-е сбрс.)",
    "ActuationTimeTitle" : "Время актив.",
    "StopTimeTitle" : "Oстан.",
    "CelebrationMessage" : "Поздравляем!",
    "Settings" : "Настройки",
    "kml" : "км/л",
    "mpg" : "mpg",
    "lkm" : "л/100км",
    "SbnTitleId" : "экономии топлива",
    "iStopOnTitle" : "% i-stop ON (данная езда)",
    "iStopBoost" : "i-stop, диапазон повышенный",
    "ResetUnsuccessful" : "Сброс был неудачным. Вы хотите снова повторить?",
    "CancelBtn" : "Отменить",
    "RetryBtn" : "Повтор",
    "IgnitionOff" : "Пкз. экр. при Выкл. заж.",
    "SyncTripA" : "Синхр. средн. и путь А",
    "Km" : "км",
    "Miles" : "миль",
    "HidePanel" : "Скрыть кнопки",
    "ApplicationsMenu" : "Приложения",
    "Reset" : "Сбросить среднее",
    "SelectSettings" : "Настройки",
    "SettingsRetryMsg" : "Настройка \"Синхр. средн. и путь А\" невозможно изменить",
    "iStopOn" : "i-stop ON",
    "ErrorReady" : "Готово.",
    "ErrorActivated" : "Невозможно активировать.",
    "SwitchView" : "Следующий экран",
    "energyFlow" : "Поток энергии",
    "cumulativeEV" : "Сумм. путь на электропр.",
    "oneDriveEV" : "Длина одной п. на электр.",
    "TotalActive" : "Время акт",
    "SinceReset" : " ",
    "ThisDrive" : " ",
    "Average" : "Средний",
    "OneDrv" : "Езда",
    "EVDistn" : "EV Расстояние",
    "Wh" : "Wh",
    "batteryId" : "BATTERY",
    "motorId" : "MOTOR",
    "engineId" : "ENGINE",
};

framework.registerAppDictLoaded("ecoenergy", "ru_RU");