var Localization_schedmaintAppDict_pt_PT = {
	//"stringId" : "localString"
	"Back": "Voltar",
	"Cancel": "Cancelar",
	"Distance": "Distância",
	"Fixed": "Fixo",
	"Flexible": "Flexível",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Manutenção",
	"OK": "OK",
	"Off": "Deslig.",
	"Reset": "Repor",
	"Retry": "Tentar Novamente",
	"Setting": "Definição",
	"Time": "Hora",
	"confirmOffOil": "Tem a certeza de que pretende desactivar a Mudança de Óleo?",
	"confirmOffSchedule": "Tem a certeza de que pretende desactivar a Manutenção Agendada?",
	"confirmOffTire": "Tem a certeza de que pretende desactivar a Rotação dos Pneus?",
	"confirmResetOil": "Tem a certeza de que pretende repor a Mudança de Óleo?",
	"confirmResetSchedule": "Tem a certeza de que pretende repor a Manutenção Agendada?",
	"confirmResetTire": "Tem a certeza de que pretende repor a Rotação dos Pneus?",
	"day": "{value} dia",
	"days": "{value} dias",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} dia",
	"dueInTimeDays": "{dueInTime} dias",
	"dueInTimeMonths": "{dueInTime} meses",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Tem a certeza de que pretende definir a opção Mudança de Óleo como Fixo?",
	"flexibleOilChange": "A escolha de definições Flexível requer a utilização do óleo de motor recomendado pela Mazda.",
	"month": "{value} mês",
	"months": "{value} meses",
	"oilChange": "Mudança de Óleo",
	"oilChangeDue": "Efectuar Mudança de Óleo!",
	"oilLife": "Vida Útil do Óleo",
	"oilSettingError": "Erro de Definição de Óleo",
	"resetFail": "Falha na Reposição",
	"retryFixed": "Não foi possível alterar a definição para Fixo",
	"retryFlexible": "Não foi possível alterar a definição para Flexível",
	"retryOff": "Não foi possível desactivar a definição",
	"scheduled": "Agendada",
	"scheduledDueIn": "Vence em:",
	"scheduledMaintenanceDue": "Efectuar Manutenção!",
	"settingInterval": "A Definir Intervalo",
	"tireRotation": "Rotação dos Pneus",
	"tireRotationDue": "Efectuar a Rotação dos Pneus!",
	"tryAgain": "Pretende tentar novamente?",
	"turnOff": "Desligar",
};

framework.registerAppDictLoaded("schedmaint", "pt_PT");