var Localization_schedmaintAppDict_sk_SK = {
	//"stringId" : "localString"
	"Back": "Späť",
	"Cancel": "Zrušiť",
	"Distance": "Vzdial.",
	"Fixed": "Fixné",
	"Flexible": "Flexib.",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Údržba",
	"OK": "OK",
	"Off": "Vypn.",
	"Reset": "Reset",
	"Retry": "Zopakovať pokus",
	"Setting": "Nastavenie",
	"Time": "Čas",
	"confirmOffOil": "Naozaj chcete vypnúť výmenu oleja?",
	"confirmOffSchedule": "Naozaj vyp. plán. údrž.?",
	"confirmOffTire": "Naozaj vyp. rotáciu kolies?",
	"confirmResetOil": "Naozaj chcete obnoviť výmenu oleja?",
	"confirmResetSchedule": "Naozaj obn. plán. údrž.?",
	"confirmResetTire": "Naozaj chcete obnoviť rotáciu kolies?",
	"day": "{value} deň",
	"days": "{value} dní",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} dní",
	"dueInTimeDays": "{dueInTime} deň",
	"dueInTimeMonths": "{dueInTime} mesiacov",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Naozaj chcete zmeniť na fixné nastavenie výmeny oleja?",
	"flexibleOilChange": "Flexibilné nastavenie používa motorový olej od spol. Mazda.",
	"month": "{value} mesiac",
	"months": "{value} mesiacov",
	"oilChange": "Výmena oleja",
	"oilChangeDue": "Stanovená výmena oleja!",
	"oilLife": "Životnosť oleja",
	"oilSettingError": "Chyba nastavenia oleja",
	"resetFail": "Resetovanie neúspešné",
	"retryFixed": "Nastavenie sa nedalo zmeniť na fixné",
	"retryFlexible": "Nastavenie sa nedalo zmeniť na flexibilné",
	"retryOff": "Nastavenie sa nedalo vypnúť",
	"scheduled": "Plánované",
	"scheduledDueIn": "Servis o:",
	"scheduledMaintenanceDue": "Deň servisu:",
	"settingInterval": "Interval nastavenia",
	"tireRotation": "Rotácia pneumatík",
	"tireRotationDue": "Stanovená rotácia pneumatík!",
	"tryAgain": "Chcete skúsiť znova?",
	"turnOff": "Vypnúť",
};

framework.registerAppDictLoaded("schedmaint", "sk_SK");