var Localization_schedmaintAppDict_ro_RO = {
	//"stringId" : "localString"
	"Back": "Înapoi",
	"Cancel": "Anulare",
	"Distance": "Distanţă",
	"Fixed": "Fix",
	"Flexible": "Flexibil",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Întreţinere",
	"OK": "OK",
	"Off": "Oprit",
	"Reset": "Resetare",
	"Retry": "Reîncercare",
	"Setting": "Setare",
	"Time": "Oră",
	"confirmOffOil": "Sunteţi sigur că doriţi să dezactivaţi schimbul de ulei?",
	"confirmOffSchedule": "Sunteţi sigur că doriţi să dezactivaţi întreţinerea programată?",
	"confirmOffTire": "Sunteţi sigur că doriţi să dezactivaţi permutarea pneurilor?",
	"confirmResetOil": "Sunteţi sigur că doriţi să resetaţi schimbul de ulei? ",
	"confirmResetSchedule": "Sunteţi sigur că doriţi să resetaţi întreţinerea programată?",
	"confirmResetTire": "Sunteţi sigur că doriţi să resetaţi permutarea pneurilor?",
	"day": "{value} zi",
	"days": "{value} zile",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} zi",
	"dueInTimeDays": "{dueInTime} zile",
	"dueInTimeMonths": "{dueInTime} luni ",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Sunteţi sigur că doriţi să setaţi schimbul de ulei la fix?",
	"flexibleOilChange": "Alegerea setărilor flexibile presupune folosirea uleiului de motor recomandat de Mazda.",
	"month": "{value} lună",
	"months": "{value} luni",
	"oilChange": "Schimb de ulei",
	"oilChangeDue": "Urmează schimbul de ulei!",
	"oilLife": "Durabilitate ulei",
	"oilSettingError": "Eroare setare ulei",
	"resetFail": "Resetare nereuşită",
	"retryFixed": "Setarea nu a putut fi stabilită la fix.",
	"retryFlexible": "Setarea nu a putut fi stabilită la Flexibil.",
	"retryOff": "Setarea nu a putut fi oprită",
	"scheduled": "Programat",
	"scheduledDueIn": "Timp rămas:",
	"scheduledMaintenanceDue": "Urmează revizia!",
	"settingInterval": "Interval setare",
	"tireRotation": "Permutare pneuri",
	"tireRotationDue": "Urmează permutarea pneurilor!",
	"tryAgain": "Doriţi să reîncercaţi?",
	"turnOff": "Oprire",
};

framework.registerAppDictLoaded("schedmaint", "ro_RO");