var Localization_schedmaintAppDict_mn_TW = {
	//"stringId" : "localString"
	"Back": "回上頁",
	"Cancel": "取消",
	"Distance": "距離",
	"Fixed": "固定",
	"Flexible": "彈性",
	"KM": "{value} 公里",
	"MILE": "{value} 英哩",
	"Maintenance": "維修保養",
	"OK": "確定",
	"Off": "關閉",
	"Reset": "初始設定",
	"Retry": "重試",
	"Setting": "設定",
	"Time": "時間",
	"confirmOffOil": "確定要關閉「更換機油」週期提示嗎?",
	"confirmOffSchedule": "確定要關閉「定期保養」週期提示嗎?",
	"confirmOffTire": "確定要關閉「輪胎對調」週期提示嗎?",
	"confirmResetOil": "確定要重設「更換機油」週期嗎?",
	"confirmResetSchedule": "確定要重設「定期保養」週期嗎?",
	"confirmResetTire": "確定要重設「輪胎對調」週期嗎?",
	"day": "{value} 日",
	"days": "{value} 日",
	"dueInKm": "{dueInDistance} 公里",
	"dueInMile": "{dueInDistance} 英哩",
	"dueInTimeDay": "{dueInTime} 日",
	"dueInTimeDays": "{dueInTime} 日",
	"dueInTimeMonths": "{dueInTime} 月",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} 公里",
	"dueUnitOilMile": "{dueInOil} 英哩",
	"fixedConfirm": "確定要將更換機油週期設定為「固定」嗎",
	"flexibleOilChange": "需要使用 Mazda 推薦機油才能選擇「彈性」週期設定。",
	"month": "{value} 個月",
	"months": "{value} 個月",
	"oilChange": "更換機油",
	"oilChangeDue": "指定機油更換時間已到!",
	"oilLife": "機油壽命",
	"oilSettingError": "機油設定錯誤",
	"resetFail": "初始設定失敗",
	"retryFixed": "無法將設定變成「固定」",
	"retryFlexible": "無法將設定變成「彈性」",
	"retryOff": "無法關閉設定。",
	"scheduled": "定期保養設定",
	"scheduledDueIn": "到期日 : ",
	"scheduledMaintenanceDue": "指定保養日期已到!",
	"settingInterval": "設定間隔",
	"tireRotation": "輪胎對調設定",
	"tireRotationDue": "指定輪胎對調時間已到!",
	"tryAgain": "要重試嗎?",
	"turnOff": "關閉",
};

framework.registerAppDictLoaded("schedmaint", "mn_TW");