var Localization_schedmaintAppDict_fr_CN = {
	//"stringId" : "localString"
	"Back": "Retour",
	"Cancel": "Annuler",
	"Distance": "Distance",
	"Fixed": "Fixe",
	"Flexible": "Flexible",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Entretien",
	"OK": "OK",
	"Off": "Désact.",
	"Reset": "Réinitialiser",
	"Retry": "Réessayer",
	"Setting": "Paramètre",
	"Time": "Heure",
	"confirmOffOil": "Êtes-vous sûr de vouloir désactiver la Vidange ?",
	"confirmOffSchedule": "Êtes-vous sûr de vouloir désactiver l’Entretien Programmé ?",
	"confirmOffTire": "Êtes-vous sûr de vouloir désactiver la Permutation des pneus ?",
	"confirmResetOil": "Êtes-vous sûr de vouloir réinitialiser la vidange ?",
	"confirmResetSchedule": "Êtes-vous sûr de vouloir réinitialiser l’Entretien Programmé ?",
	"confirmResetTire": "Êtes-vous sûr de vouloir réinitialiser la Permutation des pneus ?",
	"day": "{value} jour",
	"days": "{value} jours",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} jour",
	"dueInTimeDays": "{dueInTime} jours",
	"dueInTimeMonths": "{dueInTime} mois",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Êtes-vous sûr de vouloir modifier les paramètres de vidange à Fixe ?",
	"flexibleOilChange": "La sélection des paramètres flexibles nécessite l'utilisation d’une huile moteur recommandée par Mazda.",
	"month": "{value} mois",
	"months": "{value} mois",
	"oilChange": "Vidange ",
	"oilChangeDue": "Vidange nécessaire !",
	"oilLife": "Durée huile",
	"oilSettingError": "Erreur réglage huile",
	"resetFail": "Échec de réinitialisation",
	"retryFixed": "Impossible de modifier à Fixe",
	"retryFlexible": "Impossible de modifier à Flexible",
	"retryOff": "Ce paramètre ne peut être désactivé",
	"scheduled": "Programmé",
	"scheduledDueIn": "Due à:",
	"scheduledMaintenanceDue": "Révision requise !",
	"settingInterval": "Intervalle paramètre",
	"tireRotation": "Permutation des pneus",
	"tireRotationDue": "Rotation des pneus en raison!",
	"tryAgain": "Voulez-vous réessayer ?",
	"turnOff": "Éteindre",
};

framework.registerAppDictLoaded("schedmaint", "fr_CN");