var Localization_schedmaintAppDict_lv_LV = {
	//"stringId" : "localString"
	"Back": "Atpakaļ",
	"Cancel": "Atcelt",
	"Distance": "Attālums",
	"Fixed": "Fiksēta",
	"Flexible": "Elastīgs",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Apkope",
	"OK": "Labi",
	"Off": "Izslēgts",
	"Reset": "Atiestatīt",
	"Retry": "Mēģināt vēlreiz",
	"Setting": "Iestatījumi",
	"Time": "Laiks",
	"confirmOffOil": "Vai tiešām vēlaties izslēgt eļļas nomaiņu?",
	"confirmOffSchedule": "Vai tiešām vēlaties izslēgt plānoto tehnisko apkopi?",
	"confirmOffTire": "Vai tiešām vēlaties izslēgt riepu pārlikšanu?",
	"confirmResetOil": "Vai tiešām vēlaties atjaunot eļļas nomaiņu?",
	"confirmResetSchedule": "Vai tiešām vēlaties atjaunot plānoto tehnisko apkopi?",
	"confirmResetTire": "Vai tiešām vēlaties atjaunot riepu pārlikšanu?",
	"day": "{value} diena",
	"days": "{value} dienas",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} dienā",
	"dueInTimeDays": "{dueInTime} dienās",
	"dueInTimeMonths": "{dueInTime} mēnešos",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Vai tiešām vēlaties uzstādīt fiksētu eļļas nomaiņu?",
	"flexibleOilChange": "Izvēloties pielāgojamus iestatījumus, jāizmanto Mazda ieteiktā motoreļļa.",
	"month": "{value} mēnesis",
	"months": "{value} mēneši",
	"oilChange": "Eļļas maiņa",
	"oilChangeDue": "Jāveic eļļas maiņa!",
	"oilLife": "Eļļas kalpošanas laiks",
	"oilSettingError": "Eļļas iestatījumu kļūda",
	"resetFail": "Atiestate neizdevās",
	"retryFixed": "Iestatījumu nevar pārveidot par fiksētu",
	"retryFlexible": "Iestatījumu nevar pārveidot par pielāgojamu",
	"retryOff": "Iestatījumu nevar izslēgt",
	"scheduled": "Plānotā",
	"scheduledDueIn": "Apkope pēc:",
	"scheduledMaintenanceDue": "Plānotā apkope!",
	"settingInterval": "Iestatīšanas intervāls",
	"tireRotation": "Riepu pārlikšana",
	"tireRotationDue": "Jāveic riepu pārlikšana!",
	"tryAgain": "Vai vēlaties mēģināt vēlreiz?",
	"turnOff": "Izslēgt",
};

framework.registerAppDictLoaded("schedmaint", "lv_LV");