var Localization_schedmaintAppDict_bg_BG = {
	//"stringId" : "localString"
	"Back": "Назад",
	"Cancel": "Отказ",
	"Distance": "Разстоя.",
	"Fixed": "Фикси.",
	"Flexible": "Гъвкав",
	"KM": "{value} км",
	"MILE": "{value} mi",
	"Maintenance": "Поддръжка",
	"OK": "OK",
	"Off": "Изкл.",
	"Reset": "Нулиране",
	"Retry": "Повторен опит",
	"Setting": "Настройки",
	"Time": "Час",
	"confirmOffOil": "Наистина ли искате да изключите смяната на маслото?",
	"confirmOffSchedule": "Наистина ли искате да изключите планираната поддръжка?",
	"confirmOffTire": "Наистина ли искате да изключите ротацията на гумите?",
	"confirmResetOil": "Наистина ли искате да нулирате смяната на маслото?",
	"confirmResetSchedule": "Наистина ли искате да нулирате планираната поддръжка?",
	"confirmResetTire": "Наистина ли искате да нулирате ротацията на гумите?",
	"day": "{value} ден",
	"days": "{value} дни",
	"dueInKm": "{dueInDistance} км",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} ден",
	"dueInTimeDays": "{dueInTime} дни",
	"dueInTimeMonths": "{dueInTime} месеца",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} км",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Наистина ли искате да зададете „Фиксиран“ за „Смяна на маслото“?",
	"flexibleOilChange": "Изборът на настройка „Гъвкав“ изисква използване на препоръчаното от Mazda моторно масло.",
	"month": "{value} месец",
	"months": "{value} месеца",
	"oilChange": "Смяна на маслото",
	"oilChangeDue": "Смяна масло!",
	"oilLife": "Живот на маслото",
	"oilSettingError": "Грешка в настройките за маслото",
	"resetFail": "Неуспешно нулиране",
	"retryFixed": "Настройката не може да се промени на „Фиксиран“",
	"retryFlexible": "Настройката не може да се промени на „Гъвкав“",
	"retryOff": "Настройката не може да се изключи",
	"scheduled": "Планирана",
	"scheduledDueIn": "Срок:",
	"scheduledMaintenanceDue": "Срокът е настъпил!",
	"settingInterval": "Настр. на интервала",
	"tireRotation": "Ротация на гумите",
	"tireRotationDue": "Извършв. ротация гуми!",
	"tryAgain": "Искате ли да опитате отново?",
	"turnOff": "Изключване",
};

framework.registerAppDictLoaded("schedmaint", "bg_BG");