var Localization_schedmaintAppDict_he_IL = {
	//"stringId" : "localString"
	"Back": "חזור",
	"Cancel": "בטל",
	"Distance": "מרחק",
	"Fixed": "קבוע",
	"Flexible": "גמיש",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "תחזוקה",
	"OK": "OK",
	"Off": "כבוי",
	"Reset": "איפוס",
	"Retry": "נסה שנית",
	"Setting": "הגדרות",
	"Time": "זמן",
	"confirmOffOil": "האם אתה בטוח שברצונך לכבות את החלפת השמן?",
	"confirmOffSchedule": "האם אתה בטוח שברצונך לכבות את התחזוקה המתוזמנת?",
	"confirmOffTire": "האם אתה בטוח שברצונך לכבות את סיבוב הצמיגים?",
	"confirmResetOil": "האם אתה בטוח שברצונך להגדיר מחדש החלפת שמן?",
	"confirmResetSchedule": "האם אתה בטוח שברצונך להגדיר מחדש תחזוקה מתוזמנת?",
	"confirmResetTire": "האם אתה בטוח שברצונך להגדיר מחדש סיבוב צמיגים?",
	"day": "{value} יום",
	"days": "{value} ימים",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} יום",
	"dueInTimeDays": "{dueInTime} ימים",
	"dueInTimeMonths": "{dueInTime} חודשים",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "האם אתה בטוח שברצונך להגדיר את החלפת השמן כקבועה?",
	"flexibleOilChange": "בחירת הגדרות גמישות מחייבת שימוש בשמן מנוע מומלץ של Mazda.",
	"month": "{value} חודש",
	"months": "{value} חודשים",
	"oilChange": "החלפת שמן",
	"oilChangeDue": "הגיע מועד החלפת שמן!",
	"oilLife": "אורך חיי דלק",
	"oilSettingError": "שגיאת הגדרת דלק",
	"resetFail": "האיפוס נכשל",
	"retryFixed": "לא ניתן לשנות הגדרה זו לקבועה",
	"retryFlexible": "לא ניתן לשנות הגדרה זו לגמישה",
	"retryOff": "לא ניתן להפסיק הגדרה זו",
	"scheduled": "מתוזמן",
	"scheduledDueIn": "חל ב",
	"scheduledMaintenanceDue": "הגיע המועד המתוכנן!",
	"settingInterval": "מגדיר מרווח",
	"tireRotation": "סבב צמיגים",
	"tireRotationDue": "הגיע המועד של סבב צמיגים!",
	"tryAgain": "האם תרצה לנסות שנית?",
	"turnOff": "כבה",
};

framework.registerAppDictLoaded("schedmaint", "he_IL");