var Localization_schedmaintAppDict_th_TH = {
	//"stringId" : "localString"
	"Back": "ย้อนกลับ",
	"Cancel": "ยกเลิก",
	"Distance": "ระยะทาง",
	"Fixed": "คงที่",
	"Flexible": "ยืดหยุ่น",
	"KM": "{value} กม.",
	"MILE": "{value} ไมล์",
	"Maintenance": "การบำรุงรักษา",
	"OK": "ตกลง",
	"Off": "ปิด",
	"Reset": "รีเซ็ต",
	"Retry": "ลองใหม่",
	"Setting": "การตั้งค่า",
	"Time": "เวลา",
	"confirmOffOil": "แน่ใจหรือไม่ว่าต้องการปิดการเปลี่ยนน้ำมันเครื่อง",
	"confirmOffSchedule": "แน่ใจหรือไม่ว่าต้องการปิดการบำรุงรักษาตามกำหนดเวลา",
	"confirmOffTire": "แน่ใจหรือไม่ว่าต้องการปิดการเตือนการสลับตำแหน่งยาง",
	"confirmResetOil": "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการเปลี่ยนน้ำมันเครื่อง",
	"confirmResetSchedule": "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการบำรุงรักษาตามกำหนดเวลา",
	"confirmResetTire": "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการสลับตำแหน่งยาง",
	"day": "{value} วัน",
	"days": "{value} วัน",
	"dueInKm": "{dueInDistance} กม.",
	"dueInMile": "{dueInDistance} ไมล์",
	"dueInTimeDay": "{dueInTime} วัน",
	"dueInTimeDays": "{dueInTime} วัน",
	"dueInTimeMonths": "{dueInTime} เดือน",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} กม.",
	"dueUnitOilMile": "{dueInOil} ไมล์",
	"fixedConfirm": "แน่ใจหรือไม่ว่าต้องการกำหนดการตั้งค่าการเปลี่ยนน้ำมันเป็นแบบยืดหยุ่น",
	"flexibleOilChange": "การเลือกการตั้งค่าแบบยืดหยุ่นกำหนดให้ต้องใช้น้ำมันเครื่องที่ Mazda แนะนำ",
	"month": "{value} เดือน",
	"months": "{value} เดือน",
	"oilChange": "การเปลี่ยนถ่ายน้ำมันเครื่อง",
	"oilChangeDue": "ครบกำหนดการเปลี่ยนถ่ายน้ำมัน!",
	"oilLife": "อายุการใช้งานของน้ำมัน",
	"oilSettingError": "ข้อผิดพลาดการตั้งค่าน้ำมัน",
	"resetFail": "การรีเซ็ตล้มเหลว",
	"retryFixed": "ไม่สามารถเปลี่ยนการตั้งค่าเป็นแบบคงที่ได้",
	"retryFlexible": "ไม่สามารถเปลี่ยนการตั้งค่าเป็นแบบยืดหยุ่นได้",
	"retryOff": "ไม่สามารถปิดการตั้งค่าได้",
	"scheduled": "ตามกำหนด",
	"scheduledDueIn": "ครบกำหนด:",
	"scheduledMaintenanceDue": "ครบกำหนดเวลา!",
	"settingInterval": "ระยะเวลาการตั้งค่า",
	"tireRotation": "การสลับยาง",
	"tireRotationDue": "ถึงกำหนดสลับยาง !",
	"tryAgain": "คุณต้องการลองอีกครั้งหรือไม่",
	"turnOff": "ปิด",
};

framework.registerAppDictLoaded("schedmaint", "th_TH");