var Localization_schedmaintAppDict_ar_SA = {
	//"stringId" : "localString"
	"Back": "رجوع",
	"Cancel": "إلغاء",
	"Distance": "المسافة",
	"Fixed": "ثابت",
	"Flexible": "مرن",
	"KM": "{value} كم",
	"MILE": "{value} ميل",
	"Maintenance": "الصيانة",
	"OK": "موافق",
	"Off": "إيقاف",
	"Reset": "إعادة ضبط",
	"Retry": "أعد المحاولة",
	"Setting": "الإعدادات",
	"Time": "الوقت",
	"confirmOffOil": "هل أنت متأكد من رغبتك في إيقاف تغيير الزيت؟",
	"confirmOffSchedule": "هل أنت متأكد من رغبتك في إيقاف الصيانة المجدولة؟",
	"confirmOffTire": "هل أنت متأكد من رغبتك في إيقاف تدوير الإطار؟",
	"confirmResetOil": "هل أنت متأكد من رغبتك في إعادة تعيين تغيير الزيت؟",
	"confirmResetSchedule": "هل أنت متأكد من رغبتك في إعادة تعيين الصيانة المجدولة؟",
	"confirmResetTire": "هل أنت متأكد من رغبتك في إعادة تعيين تدوير الإطار؟",
	"day": "{value}يوم ",
	"days": "{value} أيام",
	"dueInKm": "{dueInDistance} كم",
	"dueInMile": "{dueInDistance} ميل",
	"dueInTimeDay": "{dueInTime} يوم",
	"dueInTimeDays": "{dueInTime} أيام",
	"dueInTimeMonths": "{dueInTime} شهر",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} كم",
	"dueUnitOilMile": "{dueInOil} ميل",
	"fixedConfirm": "هل أنت متأكد من رغبتك في ضبط تغيير الزيت على ثابت؟",
	"flexibleOilChange": "يتطلب اختيار إعدادات مرنة استخدام زيت محرك موصى به   من طرف  Mazda.",
	"month": "{value} شهر",
	"months": "{value} شهور",
	"oilChange": "تغيير الزيت",
	"oilChangeDue": "وجوب تغيير الزيت!",
	"oilLife": "عمر الزيت",
	"oilSettingError": "خطأ في إعداد الزيت",
	"resetFail": "فشل إعادة الضبط",
	"retryFixed": "لا يمكن تحويل الإعداد إلى ثابت",
	"retryFlexible": "لا يمكن تحويل الإعداد إلى مرن",
	"retryOff": "لا يمكن إيقاف الإعداد",
	"scheduled": "مجدول",
	"scheduledDueIn": "مستحق في",
	"scheduledMaintenanceDue": "المستحق حسب الجدول!",
	"settingInterval": "الفاصل الزمني للإعداد",
	"tireRotation": "تدوير الإطار",
	"tireRotationDue": "تدوير الإطار المستحق!",
	"tryAgain": "هل ترغب في إعادة المحاولة؟",
	"turnOff": "إيقاف",
};

framework.registerAppDictLoaded("schedmaint", "ar_SA");