var Localization_schedmaintAppDict_fi_FI = {
	//"stringId" : "localString"
	"Back": "Takaisin",
	"Cancel": "Peruuta",
	"Distance": "Etäisyys",
	"Fixed": "Kiinteä",
	"Flexible": "Joust.",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Huolto",
	"OK": "OK",
	"Off": "Pois",
	"Reset": "Palauta",
	"Retry": "Yritä uudelleen",
	"Setting": "Asetukset",
	"Time": "Aika",
	"confirmOffOil": "Haluatko varmasti poistaa  öljynvaihdon käytöstä?",
	"confirmOffSchedule": "Haluatko varmasti poistaa  määräaikaishuollon käytöstä?",
	"confirmOffTire": "Haluatko varmasti poistaa  renkaiden paikanvaihdon käytöstä?",
	"confirmResetOil": "Haluatko varmasti nollata öljynvaihdon tiedot?",
	"confirmResetSchedule": "Haluatko varmasti nollata määräaikaishuollon tiedot?",
	"confirmResetTire": "Haluatko varmasti nollata renkaiden paikanvaihdon tiedot?",
	"day": "{value} päivä",
	"days": "{value} päivää",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} pv",
	"dueInTimeDays": "{dueInTime} pv",
	"dueInTimeMonths": "{dueInTime} kk",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Haluatko varmasti vaihtaa Öljynvaihto-asetukseksi Kiinteä?",
	"flexibleOilChange": "Joustavien asetusten valitseminen edellyttää Mazda suositteleman moottoriöljyn käyttöä.",
	"month": "{value} kuukausi",
	"months": "{value} kuukautta",
	"oilChange": "Öljynvaihto",
	"oilChangeDue": "Suorita öljynvaihto!",
	"oilLife": "Öljyn ikä",
	"oilSettingError": "Öljyasetusvirhe",
	"resetFail": "Nollaus epäonnistui",
	"retryFixed": "Asetuksen arvoksi ei voitu vaihtaa Kiinteä",
	"retryFlexible": "Asetuksen arvoksi ei voitu vaihtaa Joustava",
	"retryOff": "Asetusta ei voitu kytkeä pois päältä",
	"scheduled": "Määräaikaishuolto",
	"scheduledDueIn": "Viim:",
	"scheduledMaintenanceDue": "Suoritettava heti!",
	"settingInterval": "Vaihtovälin määritys",
	"tireRotation": "Renkaiden paikanvaihto",
	"tireRotationDue": "Suorita renkaiden paikanvaihto!",
	"tryAgain": "Haluatko yrittää uudelleen?",
	"turnOff": "Kytke pois päältä",
};

framework.registerAppDictLoaded("schedmaint", "fi_FI");