var Localization_schedmaintAppDict_ja_JP = {
	//"stringId" : "localString"
	"Back": "戻る",
	"Cancel": "キャンセル",
	"Distance": "距離",
	"Fixed": "手動",
	"Flexible": "自動",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "メンテナンス",
	"OK": "OK",
	"Off": "OFF",
	"Reset": "リセット",
	"Retry": "リトライ",
	"Setting": "設定",
	"Time": "期間",
	"confirmOffOil": "オイル点検/交換を\nOFFにしてもよろしいですか？",
	"confirmOffSchedule": "定期点検を\nOFFにしてもよろしいですか？",
	"confirmOffTire": "タイヤ交換を\nOFFにしてもよろしいですか？ ",
	"confirmResetOil": "オイル点検/交換を\nリセットしてもよろしいですか？",
	"confirmResetSchedule": "定期点検を\nリセットしてもよろしいですか？",
	"confirmResetTire": "タイヤ交換を\nリセットしてもよろしいですか？ ",
	"day": "{value} 日",
	"days": "{value} 日",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} 日",
	"dueInTimeDays": "{dueInTime} 日",
	"dueInTimeMonths": "{dueInTime} ヵ月",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "オイル点検/交換を\n手動に設定してもよろしいですか?",
	"flexibleOilChange": "自動オイル交換機能は、\nマツダ社推奨のオイルの場合のみ\n使用できます。",
	"month": "{value} ヵ月",
	"months": "{value} ヵ月",
	"oilChange": "オイル点検/交換",
	"oilChangeDue": "オイル点検/交換の時期です",
	"oilLife": "オイル寿命",
	"oilSettingError": "オイル設定エラー",
	"resetFail": "リセットに失敗しました。\nリトライしますか？",
	"retryFixed": "手動に設定できませんでした。",
	"retryFlexible": "自動に設定できませんでした。 ",
	"retryOff": "設定をOFFにできませんでした。\nリトライしますか？",
	"scheduled": "定期点検",
	"scheduledDueIn": "残り",
	"scheduledMaintenanceDue": "定期点検時期です",
	"settingInterval": "設定",
	"tireRotation": "タイヤ交換",
	"tireRotationDue": "タイヤ交換の時期です",
	"tryAgain": "リトライしますか？",
	"turnOff": "OFF",
};

framework.registerAppDictLoaded("schedmaint", "ja_JP");