var Localization_schedmaintAppDict_it_IT = {
	//"stringId" : "localString"
	"Back": "Indietro",
	"Cancel": "Annulla",
	"Distance": "Distanza",
	"Fixed": "Fisso",
	"Flexible": "Flessib.",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Manutenzione",
	"OK": "OK",
	"Off": "Spento",
	"Reset": "Resetta",
	"Retry": "Riprova",
	"Setting": "Impostazione",
	"Time": "Tempo",
	"confirmOffOil": "Disattivare avviso per cambio olio?",
	"confirmOffSchedule": "Disattivare avvisi per manutenzione programmata?",
	"confirmOffTire": "Disattivare avvisi per rotazione pneumatici?",
	"confirmResetOil": "Resettare avviso per cambio olio?",
	"confirmResetSchedule": "Resettare avvisi per manutenzione programmata?",
	"confirmResetTire": "Resettare avvisi per rotazione pneumatici?",
	"day": "{value} giorno",
	"days": "{value} giorni",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} giorni",
	"dueInTimeDays": "{dueInTime} mesi",
	"dueInTimeMonths": "{dueInTime} mesi",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Impostare il cambio olio su \"fisso\"?",
	"flexibleOilChange": "La scelta di impostazioni modificabili comporta l'utlizzo dell'olio raccomandato da Mazda.",
	"month": "{value} mese",
	"months": "{value} mesi",
	"oilChange": "Cambio olio",
	"oilChangeDue": "Cambio olio necessario!",
	"oilLife": "Dettaglio cambio olio",
	"oilSettingError": "Errore impostazioni olio",
	"resetFail": "Reset non riuscito.",
	"retryFixed": "Impossibile impostare su \"fisso\".",
	"retryFlexible": "Impossibile impostare su \"modificabile\".",
	"retryOff": "L'impostazione potrebbe non essere spenta.",
	"scheduled": "Programmato",
	"scheduledDueIn": "Da fare tra:",
	"scheduledMaintenanceDue": "Da fare ora!",
	"settingInterval": "Impostazione intervallo",
	"tireRotation": "Rotazione gomme",
	"tireRotationDue": "Rotazione gomme necassaria!",
	"tryAgain": "Riprovare?",
	"turnOff": "Spegni",
};

framework.registerAppDictLoaded("schedmaint", "it_IT");