var Localization_schedmaintAppDict_sv_SE = {
	//"stringId" : "localString"
	"Back": "Tillbaka",
	"Cancel": "Avbryt",
	"Distance": "Avstånd",
	"Fixed": "Fast",
	"Flexible": "Flexibel",
	"KM": "{value} km",
	"MILE": "{value} mi",
	"Maintenance": "Underhåll",
	"OK": "OK",
	"Off": "Av",
	"Reset": "Återställ",
	"Retry": "Prova igen",
	"Setting": "Inställning",
	"Time": "Tid",
	"confirmOffOil": "Vill du verkligen stänga av oljebyte?",
	"confirmOffSchedule": "Vill du verkligen stänga av underhållsschema?",
	"confirmOffTire": "Vill du verkligen stänga av däckrotation?",
	"confirmResetOil": "Vill du verkligen nollställa oljebyte?",
	"confirmResetSchedule": "Vill du verkligen nollställa underhållsschema?",
	"confirmResetTire": "Vill du verkligen nollställa däckrotation?",
	"day": "{value} dag",
	"days": "{value} dagar",
	"dueInKm": "{dueInDistance} km",
	"dueInMile": "{dueInDistance} mi",
	"dueInTimeDay": "{dueInTime} dag",
	"dueInTimeDays": "{dueInTime} dagar",
	"dueInTimeMonths": "{dueInTime} månader",
	"dueUnitFlexible": "{dueInOil} %",
	"dueUnitOilKm": "{dueInOil} km",
	"dueUnitOilMile": "{dueInOil} mi",
	"fixedConfirm": "Vill du verkligen ställa in oljebyte på fast?",
	"flexibleOilChange": "Väljer du flexibla inställningar måste du använda motorolja som rekommenderas av Mazda.",
	"month": "{value} månad",
	"months": "{value} månader",
	"oilChange": "Oljebyte",
	"oilChangeDue": "Dags för oljebyte!",
	"oilLife": "Oljestatus",
	"oilSettingError": "Fel på oljeinställning",
	"resetFail": "Återställning misslyckades",
	"retryFixed": "Inställning kunde inte ändras till fast",
	"retryFlexible": "Inställning kunde inte ändras till flexibel",
	"retryOff": "Inställning kunde inte slås av",
	"scheduled": "Planerad",
	"scheduledDueIn": "Planerad till:",
	"scheduledMaintenanceDue": "Dags för planerad service!",
	"settingInterval": "Ställer in intervall",
	"tireRotation": "Däckrotation",
	"tireRotationDue": "Dags för däckrotation!",
	"tryAgain": "Vill du prova igen?",
	"turnOff": "Stäng av",
};

framework.registerAppDictLoaded("schedmaint", "sv_SE");