var Localization_dabAppDict_bg_BG = {
	//"stringId" : "localString"
	"DABAnalog": "Aналог",
	"DABBandIII": "Радиовълни III",
	"DABBandSettingsList": "Наст.на РАДИОВЪЛНИ",
	"DABBandSettingsTitle": "Наст.на РАДИОВЪЛНИ",
	"DABBoth": "Двете",
	"DABChangeEnsemble": "Сменете колекцията",
	"DABDABLink": "DAB-DAB връзка",
	"DABDigital": "цифров",
	"DABEnsembleList": "Списък с колекции",
	"DABEnsembleListTitle": "Изберете колекция",
	"DABEnsembleListTitle2": "Списък с колекции",
	"DABEnsembleListUpdateComplete": "Списък със станции актуализиран",
	"DABFMLink": "DAB-FM връзка",
	"DABLBand": "Дълги радиовълни",
	"DABListNotAvailable": "Списък станции неналичен",
	"DABNoResultsFound": "Няма намерени резултати",
	"DABNoSignal": "Няма сигнал",
	"DABPleaseUpdateList": "Актуализиране на списъка",
	"DABRadio": "DAB Радио",
	"DABRadioText": "Радио текст",
	"DABSelectEnsemble": "Изберете колекция",
	"DABSettings": "DAB Настройки",
	"DABSettingsListTitle": "Настройки",
	"DABSettingsNowPlaying": "DAB настройки",
	"DABSignalLost": "{ChNum} Няма сигнал",
	"DABSignalSearch": "Търсене…",
	"DABStationListUpdateFailedSelect": "Списък станции неактулизиран",
	"DABStationListUpdated": "Списък със станции актуализиран",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Изкл. предупреждение за движението",
	"DABTrafficAlertOn": "Вкл. предупреждение за движението",
	"DABUnableToUpdateStationList": "Списък неактулизиран",
	"DABUpdate": "Актуализация",
	"DABUpdateEnsemble": "Актуализация на Списъка със станции?",
	"DABUpdateEnsembleList": "Акт. Списък със станции",
	"DABUpdateList": "Актуализиране на списъка",
	"DABUpdateStation": "Да се актуализира ли списъкът със станции?",
	"DABUpdatingEnsembleList": "Актуал. сисъка със станции",
	"DABUpdatingList": "Актуализира списъка…",
	"DABUpdatingListNowPlaying": "Актуализира списъка…",
	"StationListTab": "Списък със станции",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "bg_BG");