var Localization_dabAppDict_sk_SK = {
	//"stringId" : "localString"
	"DABAnalog": "Analógové",
	"DABBandIII": "Pásmo III",
	"DABBandSettingsList": "Nastenia vysiel. pásma",
	"DABBandSettingsTitle": "Nastenia vysiel. pásma",
	"DABBoth": "Obidve",
	"DABChangeEnsemble": "Zmeňte, prosím, skupinu",
	"DABDABLink": "Prepojenie DAB-DAB",
	"DABDigital": "Digitálne",
	"DABEnsembleList": "Zoznam skupín",
	"DABEnsembleListTitle": "Vyberte skupín",
	"DABEnsembleListTitle2": "Zoznam skupín",
	"DABEnsembleListUpdateComplete": "Zoznam skupín sa aktualizoval",
	"DABFMLink": "Prepojenie DAB-FM",
	"DABLBand": "Pásmo L",
	"DABListNotAvailable": "Zoznam staníc nie je dostupný",
	"DABNoResultsFound": "Nenašli sa žiadne výsledky",
	"DABNoSignal": "Žiadny signál",
	"DABPleaseUpdateList": "Aktualizujte, prosím, zoznam",
	"DABRadio": "Rádio DAB",
	"DABRadioText": "Rozhlasový text",
	"DABSelectEnsemble": "Vyberte skupín",
	"DABSettings": "Nastavenia DAB",
	"DABSettingsListTitle": "Nastavenia",
	"DABSettingsNowPlaying": "Nastavenia DAB",
	"DABSignalLost": "{ChNum} Video signál sa stratil",
	"DABSignalSearch": "Vyhľadáva sa…",
	"DABStationListUpdateFailedSelect": "Zoznam staníc nemožno aktualiz.",
	"DABStationListUpdated": "Aktualizuje sa zoznam staníc",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Premávka (TA) vyp",
	"DABTrafficAlertOn": "Premávka (TA) zap",
	"DABUnableToUpdateStationList": "Nemožno aktualizovať",
	"DABUpdate": "Aktualizovať",
	"DABUpdateEnsemble": "Chcete ho aktualizovať?",
	"DABUpdateEnsembleList": "Aktualizovať zoznam skupín",
	"DABUpdateList": "Aktualizujte zoznam",
	"DABUpdateStation": "Aktualizovať zoznam staníc?",
	"DABUpdatingEnsembleList": "Aktualizuje sa zoznam skupín",
	"DABUpdatingList": "Zoznam sa aktualizuje…",
	"DABUpdatingListNowPlaying": "Zoznam sa aktualizuje…",
	"StationListTab": "Zoznam staníc",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "sk_SK");