var Localization_dabAppDict_el_GR = {
	//"stringId" : "localString"
	"DABAnalog": "Αναλογικό",
	"DABBandIII": "Ζώνη Ⅲ",
	"DABBandSettingsList": "Ρυθμίσεις ΖΩΝΗΣ",
	"DABBandSettingsTitle": "Ρυθμίσεις ΖΩΝΗΣ",
	"DABBoth": "Και οι δύο",
	"DABChangeEnsemble": "Αλλάξτε το σύνολο",
	"DABDABLink": "Σύνδεση DAB-DAB",
	"DABDigital": "Ψηφιακό",
	"DABEnsembleList": "Λίστα συνόλου",
	"DABEnsembleListTitle": "Επιλέξτε ομάδα σταθμών",
	"DABEnsembleListTitle2": "Λίστα συνόλου",
	"DABEnsembleListUpdateComplete": "Η λίστα συνόλου ενημερώθηκε",
	"DABFMLink": "Σύνδεση DAB-FM",
	"DABLBand": "Ζώνη L",
	"DABListNotAvailable": "Μη διαθέσιμη λίστα σταθμών ",
	"DABNoResultsFound": "Δεν βρέθηκε κανένα αποτέλεσμα",
	"DABNoSignal": "Χωρίς σήμα",
	"DABPleaseUpdateList": "Να γίνει ενημέρωση λίστας",
	"DABRadio": "DAB Ράδιο",
	"DABRadioText": "Ραδ. κείμ.",
	"DABSelectEnsemble": "Επιλέξτε ομάδα σταθμών",
	"DABSettings": "DAB Ρυθμίσεις",
	"DABSettingsListTitle": "Ρυθμίσεις",
	"DABSettingsNowPlaying": "DAB ρυθμίσεις",
	"DABSignalLost": "Χάθηκε το σήμα {ChNum}",
	"DABSignalSearch": "Γίνεται αναζήτηση…",
	"DABStationListUpdateFailedSelect": "Αποτυχία ενημέρ. λίστ. σταθμών",
	"DABStationListUpdated": "Ενημερώθηκε η λίστα σταθμών",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Ειδοποίηση κίνησης (TA) ανενεργή",
	"DABTrafficAlertOn": "Ειδοποίηση κίνησης (TA) ενεργή",
	"DABUnableToUpdateStationList": "Απέτυχε η ενημέρωση",
	"DABUpdate": "Ενημέρωση",
	"DABUpdateEnsemble": "Να ενημερωθεί η λίστα συνόλου;",
	"DABUpdateEnsembleList": "Ενημέρωση λίστας συνόλου",
	"DABUpdateList": "Ενημέρωση λίστας",
	"DABUpdateStation": "Ενημέρωση λίστας σταθμών; ",
	"DABUpdatingEnsembleList": "Ενημέρωση λίστας συνόλου",
	"DABUpdatingList": "Γίνεται ενημέρωση λίστας…",
	"DABUpdatingListNowPlaying": "Γίνεται ενημέρωση λίστας…",
	"StationListTab": "Λίστα σταθμών",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "el_GR");