var Localization_dabAppDict_no_NO = {
	//"stringId" : "localString"
	"DABAnalog": "Analog",
	"DABBandIII": "Bånd III",
	"DABBandSettingsList": "BÅND-innstillinger",
	"DABBandSettingsTitle": "BÅND-innstillinger",
	"DABBoth": "Begge",
	"DABChangeEnsemble": "Vennligst velg annet ensemble",
	"DABDABLink": "DAB-DAB-link",
	"DABDigital": "Digital",
	"DABEnsembleList": "Ensemble-oversikt",
	"DABEnsembleListTitle": "Velg Ensemble",
	"DABEnsembleListTitle2": " Ensemble-oversikt",
	"DABEnsembleListUpdateComplete": "Ensemble-listen er oppdatert",
	"DABFMLink": "DAB-FM-link",
	"DABLBand": "L-bånd",
	"DABListNotAvailable": "Stasjonsliste ikke tilgjengelig",
	"DABNoResultsFound": "Fant ingen resultater",
	"DABNoSignal": "Ingen signal",
	"DABPleaseUpdateList": "Vennligst oppdater liste",
	"DABRadio": "DAB radio",
	"DABRadioText": "Radiotekst",
	"DABSelectEnsemble": "Velg Ensemble",
	"DABSettings": "DAB-innstillinger",
	"DABSettingsListTitle": "Innstillinger",
	"DABSettingsNowPlaying": "DAB Innstillinger",
	"DABSignalLost": "Tapt {ChNum}signal",
	"DABSignalSearch": "Søker…",
	"DABStationListUpdateFailedSelect": "Kan ikke oppdatere stasjonsliste",
	"DABStationListUpdated": "Stasjonsliste oppdatert",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Trafikkmelding (TA) av",
	"DABTrafficAlertOn": "Trafikkmelding (TA) på",
	"DABUnableToUpdateStationList": "Kan ikke oppdatere",
	"DABUpdate": "Oppdater",
	"DABUpdateEnsemble": "Ønsker du å oppdatere ensemble-liste?",
	"DABUpdateEnsembleList": "Velg Ensemble",
	"DABUpdateList": "Oppdater liste",
	"DABUpdateStation": "Oppdatere stasjonsliste?",
	"DABUpdatingEnsembleList": "Oppdaterer ensemble-liste",
	"DABUpdatingList": "Oppdaterer liste…",
	"DABUpdatingListNowPlaying": "Oppdaterer liste…",
	"StationListTab": "Stasjonsliste",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "no_NO");