var Localization_dabAppDict_th_TH = {
	//"stringId" : "localString"
	"DABAnalog": "อะนาล็อค",
	"DABBandIII": "Band III",
	"DABBandSettingsList": "การตั้งค่า Band",
	"DABBandSettingsTitle": "การตั้งค่า Band",
	"DABBoth": "ทั้งคู่ ",
	"DABChangeEnsemble": "โปรดเปลี่ยนกลุ่มสถานี",
	"DABDABLink": "ลิงค์ DAB-DAB",
	"DABDigital": "ดิจิตอล",
	"DABEnsembleList": "รายการกลุ่มสถานี",
	"DABEnsembleListTitle": "เลือกกลุ่มสถานี",
	"DABEnsembleListTitle2": "รายการกลุ่มสถานี",
	"DABEnsembleListUpdateComplete": "อัปเดตรายชื่อกลุ่มสถานีแล้ว",
	"DABFMLink": "ลิงค์ DAB-FM",
	"DABLBand": "L Band",
	"DABListNotAvailable": "รายการสถานีไม่พร้อมใช้งาน",
	"DABNoResultsFound": "ไม่พบผลลัพธ์",
	"DABNoSignal": "ไม่มีสัญญาณ",
	"DABPleaseUpdateList": "โปรดอัปเดตรายชื่อ",
	"DABRadio": "วิทยุ DAB",
	"DABRadioText": "Radio Text",
	"DABSelectEnsemble": "เลือกกลุ่มสถานี",
	"DABSettings": "การตั้งค่า DAB",
	"DABSettingsListTitle": "การตั้งค่า",
	"DABSettingsNowPlaying": "การตั้งค่า DAB",
	"DABSignalLost": "{ChNum} ขาดหายสัญญาณ",
	"DABSignalSearch": "กำลังค้นหา…",
	"DABStationListUpdateFailedSelect": "ไม่สามารถอัปเดตรายการสถานี",
	"DABStationListUpdated": "รายการสถานีอัปเดตแล้ว",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "ปิดการประกาศการจราจร",
	"DABTrafficAlertOn": "เปิดการประกาศการจราจร",
	"DABUnableToUpdateStationList": "ไม่สามารถอัปเดตรายการส",
	"DABUpdate": "อัปเดต",
	"DABUpdateEnsemble": "ต้องการอัปเดตรายชื่อกลุ่มสถานี?",
	"DABUpdateEnsembleList": "กำลังอัปเดตรายชื่อกลุ่มสถานี",
	"DABUpdateList": "รายการอัปเดต",
	"DABUpdateStation": "ต้องการอัปเดตรายการสถานี?",
	"DABUpdatingEnsembleList": "กำลังอัปเดตรายชื่อกลุ่มสถานี",
	"DABUpdatingList": "กำลังอัปเดตรายการ…",
	"DABUpdatingListNowPlaying": "กำลังอัปเดตรายการ…",
	"StationListTab": "รายการสถานี",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "th_TH");