var Localization_dabAppDict_zh_TW = {
	//"stringId" : "localString"
	"DABAnalog": "模擬",
	"DABBandIII": "頻帶 III",
	"DABBandSettingsList": "頻帶設置",
	"DABBandSettingsTitle": "頻帶設置",
	"DABBoth": "兩",
	"DABChangeEnsemble": "請更改電台合集",
	"DABDABLink": "DAB-DAB鏈接",
	"DABDigital": "數碼",
	"DABEnsembleList": "電台合集清單",
	"DABEnsembleListTitle": "選擇電台合集清單",
	"DABEnsembleListTitle2": "電台合集清單",
	"DABEnsembleListUpdateComplete": "電台合集清單已更新",
	"DABFMLink": "DAB-FM鏈接",
	"DABLBand": "L 頻帶",
	"DABListNotAvailable": "電台列表不可用",
	"DABNoResultsFound": "沒有找到結果",
	"DABNoSignal": "無信號",
	"DABPleaseUpdateList": "請更新清單",
	"DABRadio": "DAB無線電",
	"DABRadioText": "無線電文字",
	"DABSelectEnsemble": "選擇電台合集清單",
	"DABSettings": "DAB設置",
	"DABSettingsListTitle": "設置",
	"DABSettingsNowPlaying": "DAB設置",
	"DABSignalLost": "{ChNum} 訊號遺失",
	"DABSignalSearch": "搜尋中…",
	"DABStationListUpdateFailedSelect": "電台列表更新失敗",
	"DABStationListUpdated": "電台列表已更新",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "關閉交通警告(TA)",
	"DABTrafficAlertOn": "開啟交通警告(TA)",
	"DABUnableToUpdateStationList": "電台列表更新失敗",
	"DABUpdate": "更新",
	"DABUpdateEnsemble": "是否要更新電台合集清單?",
	"DABUpdateEnsembleList": "更新電台合集清單",
	"DABUpdateList": "更新清單",
	"DABUpdateStation": "更新電台清單?",
	"DABUpdatingEnsembleList": "正在更新電台合集清單",
	"DABUpdatingList": "正在更新清單…",
	"DABUpdatingListNowPlaying": "正在更新清單…",
	"StationListTab": "電台列表",
	"VrHelp_NowPlaying_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Help_Left2": "電台列表",
	"VrHelp_NowPlaying_Help_Left3": "最愛",
	"VrHelp_NowPlaying_Help_Left4": "掃描",
	"VrHelp_NowPlaying_Help_Left5": "交通警告(TA)",
	"VrHelp_NowPlaying_Help_Right1": "上一個",
	"VrHelp_NowPlaying_Help_Right2": "下一個",
	"VrHelp_NowPlaying_Help_Right3": "DAB 設定",
	"VrHelp_NowPlaying_Help_Right4": "聲音設定",
};

framework.registerAppDictLoaded("dab", "zh_TW");