var Localization_dabAppDict_it_IT = {
	//"stringId" : "localString"
	"DABAnalog": "Analogico",
	"DABBandIII": "Banda Ⅲ",
	"DABBandSettingsList": "Impostazioni BANDA",
	"DABBandSettingsTitle": "Impostazioni BANDA",
	"DABBoth": "Entrambe",
	"DABChangeEnsemble": "Si pr. di mod. l'elenco d'esecuzione",
	"DABDABLink": "Colleg. DAB-DAB",
	"DABDigital": "Digitale",
	"DABEnsembleList": "Elenco d'esecuzione",
	"DABEnsembleListTitle": "Seleziona esecuzione",
	"DABEnsembleListTitle2": "Elenco d'esecuzione",
	"DABEnsembleListUpdateComplete": "Elenco d'esecuzione aggiornato",
	"DABFMLink": "Colleg. DAB-FM",
	"DABLBand": "Banda L",
	"DABListNotAvailable": "Elenco stazioni non disponibile",
	"DABNoResultsFound": "Nessun risultato trovato.",
	"DABNoSignal": "Nessun segnale",
	"DABPleaseUpdateList": "Si prega di aggiornare l'elenco",
	"DABRadio": "Radio DAB",
	"DABRadioText": "Radiotesto",
	"DABSelectEnsemble": "Seleziona esecuzione",
	"DABSettings": "Impostazioni DAB",
	"DABSettingsListTitle": "Impostazioni",
	"DABSettingsNowPlaying": "Impostazioni DAB",
	"DABSignalLost": "{ChNum} Segnale perso",
	"DABSignalSearch": "Ricerca…",
	"DABStationListUpdateFailedSelect": "Impossibile aggiornare elenco ",
	"DABStationListUpdated": "Elenco stazioni aggiornato",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Annuncio sul traffico (TA) spento",
	"DABTrafficAlertOn": "Annuncio sul traffico (TA) acceso",
	"DABUnableToUpdateStationList": "Impossibile aggiornare",
	"DABUpdate": "Aggiorna",
	"DABUpdateEnsemble": "Aggiornare elenco d'esecuzione?",
	"DABUpdateEnsembleList": "Aggiorna elenco d'esecuzione",
	"DABUpdateList": "Aggiorna elenco",
	"DABUpdateStation": "Aggiornare elenco stazioni?",
	"DABUpdatingEnsembleList": "Agg. elenco d'esecuzione in corso",
	"DABUpdatingList": "Aggiornamento elenco in corso…",
	"DABUpdatingListNowPlaying": "Aggiornamento elenco in corso…",
	"StationListTab": "Elenco stazioni",
	"VrHelp_NowPlaying_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_Help_Left2": "Elenco stazioni",
	"VrHelp_NowPlaying_Help_Left3": "Preferiti",
	"VrHelp_NowPlaying_Help_Left4": "Scansione",
	"VrHelp_NowPlaying_Help_Left5": "Annuncio sul traffico (TA)",
	"VrHelp_NowPlaying_Help_Right1": "precedente",
	"VrHelp_NowPlaying_Help_Right2": "Successivo",
	"VrHelp_NowPlaying_Help_Right3": "Impostazioni DAB ",
	"VrHelp_NowPlaying_Help_Right4": "Impostazioni audio",
};

framework.registerAppDictLoaded("dab", "it_IT");