var Localization_dabAppDict_ar_SA = {
	//"stringId" : "localString"
	"DABAnalog": "تناظرية",
	"DABBandIII": "النطاق III",
	"DABBandSettingsList": "إعدادات النطاق",
	"DABBandSettingsTitle": "إعدادات النطاق",
	"DABBoth": "الاثنان معًا",
	"DABChangeEnsemble": "الرجاء تغيير المجموعة",
	"DABDABLink": "رابط DAB-DAB",
	"DABDigital": "رقمية",
	"DABEnsembleList": "اختر المجموعة",
	"DABEnsembleListTitle": "اختر مجموعة",
	"DABEnsembleListTitle2": "قائمة المجموعات",
	"DABEnsembleListUpdateComplete": "تم تحديث المجموعة",
	"DABFMLink": "رابط DAB-FM",
	"DABLBand": "النطاق L",
	"DABListNotAvailable": "قائمة المحطات غير متوفرة",
	"DABNoResultsFound": "لم يتم العثور على نتائج",
	"DABNoSignal": "لا توجد إشارة",
	"DABPleaseUpdateList": "الرجاء تحديث القائمة",
	"DABRadio": "راديو DAB\n",
	"DABRadioText": "النصوص الإذاعية",
	"DABSelectEnsemble": "اختر مجموعة",
	"DABSettings": "إعدادات DAB",
	"DABSettingsListTitle": "إعدادات",
	"DABSettingsNowPlaying": "إعدادات",
	"DABSignalLost": "{ChNum}  الإشارة المفقودة",
	"DABSignalSearch": "جارٍ البحث عن إشارة…",
	"DABStationListUpdateFailedSelect": "فشل تحديث قائمة المحطات",
	"DABStationListUpdated": "تحديث قائمة المحطات ",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "إيقاف تنبيه التنقل",
	"DABTrafficAlertOn": "تشغيل تنبيه التنقل",
	"DABUnableToUpdateStationList": "فشل تحديث قائمة المحطات",
	"DABUpdate": "تحديث",
	"DABUpdateEnsemble": "الإذاعية غير متاحة. هل تريد تحديثها؟",
	"DABUpdateEnsembleList": "تحديث قائمة المجموعة",
	"DABUpdateList": "تحديث القائمة",
	"DABUpdateStation": "تحديث قائمة المحطات؟",
	"DABUpdatingEnsembleList": "جارٍ تحديث قائمة المجموعة",
	"DABUpdatingList": "تحديث القائمة…",
	"DABUpdatingListNowPlaying": "تحديث القائمة…",
	"StationListTab": "قائمة المحطات",
	"VrHelp_NowPlaying_Help_Left1": "ترفيه ",
	"VrHelp_NowPlaying_Help_Left2": "قائمة المحطات",
	"VrHelp_NowPlaying_Help_Left3": "المفضلة",
	"VrHelp_NowPlaying_Help_Left4": "المسح الضوئي ",
	"VrHelp_NowPlaying_Help_Left5": "تنبيه التنقل",
	"VrHelp_NowPlaying_Help_Right1": "والسابق",
	"VrHelp_NowPlaying_Help_Right2": "التالي",
	"VrHelp_NowPlaying_Help_Right3": "الإعدادات DAB",
	"VrHelp_NowPlaying_Help_Right4": "إعدادات الصوت",
};

framework.registerAppDictLoaded("dab", "ar_SA");