var Localization_dabAppDict_ms_MY = {
	//"stringId" : "localString"
	"DABAnalog": "Analog",
	"DABBandIII": "Jalur III",
	"DABBandSettingsList": "Tetapan Jalur",
	"DABBandSettingsTitle": "Tetapan Jalur",
	"DABBoth": "Kedua",
	"DABChangeEnsemble": "Sila ubah Ensembel",
	"DABDABLink": "Pautan DAB-DAB",
	"DABDigital": "Digital",
	"DABEnsembleList": "Senarai Ensembel",
	"DABEnsembleListTitle": "Pilih Ensembel",
	"DABEnsembleListTitle2": "Senarai Ensembel",
	"DABEnsembleListUpdateComplete": "Senarai Ensembel Dikemas kini",
	"DABFMLink": "Pautan DAB-FM",
	"DABLBand": "Jalur L",
	"DABListNotAvailable": "Senarai Stesen Tidak Tersedia",
	"DABNoResultsFound": "Tiada hasil ditemui",
	"DABNoSignal": "Tiada isyarat",
	"DABPleaseUpdateList": "Sila kemas kini senarai",
	"DABRadio": "Radio DAB ",
	"DABRadioText": "Teks Radio",
	"DABSelectEnsemble": "Pilih Ensembel",
	"DABSettings": "Tetapan DAB",
	"DABSettingsListTitle": "Tetapan",
	"DABSettingsNowPlaying": "Tetapan DAB",
	"DABSignalLost": "{ChNum} Isyarat Terputus",
	"DABSignalSearch": "Mencari…",
	"DABStationListUpdateFailedSelect": "Tidak Dapat Kemas kini Stesen",
	"DABStationListUpdated": "Senarai Stesen Dikemas kini",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Makluman Lalu Lintas Dimatikan",
	"DABTrafficAlertOn": "Makluman Lalu Lintas  Dihidupkan",
	"DABUnableToUpdateStationList": "Tidak Dpt Kemaskini",
	"DABUpdate": "Kemas kini",
	"DABUpdateEnsemble": "Kemas kini Senarai Ensembel?",
	"DABUpdateEnsembleList": "Kemas kini Senarai Ensembel",
	"DABUpdateList": "Kemas kini senarai",
	"DABUpdateStation": "Kemas kini Senarai Stesen?",
	"DABUpdatingEnsembleList": "Mengemas kini Senarai Ensembel",
	"DABUpdatingList": "Mengemas kini Senarai…",
	"DABUpdatingListNowPlaying": "Kemas Kini Senarai...",
	"StationListTab": "Senarai Stesen",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "ms_MY");