var Localization_dabAppDict_de_DE = {
	//"stringId" : "localString"
	"DABAnalog": "Analog",
	"DABBandIII": "Band Ⅲ",
	"DABBandSettingsList": "BAND-Einstellungen",
	"DABBandSettingsTitle": "BAND-Einstellungen",
	"DABBoth": "Beide",
	"DABChangeEnsemble": "Bitte das Ensemble austauschen",
	"DABDABLink": "DAB-DAB Link",
	"DABDigital": "Digital",
	"DABEnsembleList": "Ensembleliste",
	"DABEnsembleListTitle": "Ensemble wählen",
	"DABEnsembleListTitle2": "Ensembleliste",
	"DABEnsembleListUpdateComplete": "Ensembleliste aktualisiert",
	"DABFMLink": "DAB-FM Link",
	"DABLBand": "L-Band",
	"DABListNotAvailable": "Senderliste nicht verfügbar",
	"DABNoResultsFound": "Nicht gefunden",
	"DABNoSignal": "Kein Signal",
	"DABPleaseUpdateList": "Bitte Liste aktualisieren",
	"DABRadio": "DAB Radio",
	"DABRadioText": "Radiotext",
	"DABSelectEnsemble": "Ensemble wählen",
	"DABSettings": "DAB-Einstellungen",
	"DABSettingsListTitle": "DAB-Einstellungen",
	"DABSettingsNowPlaying": "DAB-Einstellungen",
	"DABSignalLost": "{ChNum} Signal verloren",
	"DABSignalSearch": "Auf der Suche…",
	"DABStationListUpdateFailedSelect": "Kann Senderliste nicht aktualisieren",
	"DABStationListUpdated": "Senderliste aktualisiert",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Verkehrsmeldung (TA)  aus",
	"DABTrafficAlertOn": "Verkehrsmeldung  (TA) an",
	"DABUnableToUpdateStationList": "Kann nicht aktualisieren",
	"DABUpdate": "Aktualisieren",
	"DABUpdateEnsemble": "Ensembleliste aktualisieren?",
	"DABUpdateEnsembleList": "Ensembleliste aktualisieren",
	"DABUpdateList": "Liste aktualisieren",
	"DABUpdateStation": "Senderliste aktualisieren?",
	"DABUpdatingEnsembleList": "Aktualisierung der Ensembleliste",
	"DABUpdatingList": "Liste wird aktualisiert…",
	"DABUpdatingListNowPlaying": "Liste wird aktualisiert…",
	"StationListTab": "Senderliste",
	"VrHelp_NowPlaying_Help_Left1": "Unterhaltung",
	"VrHelp_NowPlaying_Help_Left2": "Senderliste",
	"VrHelp_NowPlaying_Help_Left3": "Favoriten",
	"VrHelp_NowPlaying_Help_Left4": "Abstimmen",
	"VrHelp_NowPlaying_Help_Left5": "Verkehrsmeldung (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Vorheriger",
	"VrHelp_NowPlaying_Help_Right2": "Nächster",
	"VrHelp_NowPlaying_Help_Right3": "DAB-Einstellungen",
	"VrHelp_NowPlaying_Help_Right4": "Toneinstellungen.",
};

framework.registerAppDictLoaded("dab", "de_DE");