var Localization_dabAppDict_zh_CN = {
	//"stringId" : "localString"
	"DABAnalog": "模拟",
	"DABBandIII": "频带III",
	"DABBandSettingsList": "带设置",
	"DABBandSettingsTitle": "频带设置",
	"DABBoth": "两",
	"DABChangeEnsemble": "请更改电台合集",
	"DABDABLink": "DAB-DAB 链接",
	"DABDigital": "数码",
	"DABEnsembleList": "电台合集列表 ",
	"DABEnsembleListTitle": "选择电台合集",
	"DABEnsembleListTitle2": "电台合集列表",
	"DABEnsembleListUpdateComplete": "电台合集列表已更新",
	"DABFMLink": "DAB-FM 链接",
	"DABLBand": "L 频带",
	"DABListNotAvailable": "电台列表不可用 ",
	"DABNoResultsFound": "没有找到结果",
	"DABNoSignal": "无信号",
	"DABPleaseUpdateList": "请更新列表",
	"DABRadio": "DAB广播",
	"DABRadioText": "广播文字",
	"DABSelectEnsemble": "选择电台合集",
	"DABSettings": "DAB设置",
	"DABSettingsListTitle": "设置",
	"DABSettingsNowPlaying": "DAB设置",
	"DABSignalLost": "{ChNum} 信号丢失",
	"DABSignalSearch": "搜索中…",
	"DABStationListUpdateFailedSelect": "无法更新电台列表",
	"DABStationListUpdated": "电台列表已更新",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "关闭交通警告 (TA) ",
	"DABTrafficAlertOn": "打开交通警告 (TA) ",
	"DABUnableToUpdateStationList": "无法更新电台列表",
	"DABUpdate": "更新",
	"DABUpdateEnsemble": "是否要更新电台合集列表？",
	"DABUpdateEnsembleList": "更新电台合集列表",
	"DABUpdateList": "更新列表",
	"DABUpdateStation": "更新电台列表?",
	"DABUpdatingEnsembleList": "更新电台合集列表中",
	"DABUpdatingList": "正在更新列表…",
	"DABUpdatingListNowPlaying": "正在更新列表…",
	"StationListTab": "电台列表",
	"VrHelp_NowPlaying_Help_Left1": "娱乐",
	"VrHelp_NowPlaying_Help_Left2": "电台列表",
	"VrHelp_NowPlaying_Help_Left3": "收藏夹",
	"VrHelp_NowPlaying_Help_Left4": "扫描",
	"VrHelp_NowPlaying_Help_Left5": "交通警告 (TA) ",
	"VrHelp_NowPlaying_Help_Right1": "上一个",
	"VrHelp_NowPlaying_Help_Right2": "下一个",
	"VrHelp_NowPlaying_Help_Right3": "DAB 设置",
	"VrHelp_NowPlaying_Help_Right4": "声音设置",
};

framework.registerAppDictLoaded("dab", "zh_CN");