var Localization_dabAppDict_lt_LT = {
	//"stringId" : "localString"
	"DABAnalog": "Analoginis",
	"DABBandIII": "III dažnių juosta",
	"DABBandSettingsList": "Dažnių juostos nustatymai",
	"DABBandSettingsTitle": "Dažnių juostos nustatymai",
	"DABBoth": "Abi",
	"DABChangeEnsemble": "Pakeiskite stočių grupę",
	"DABDABLink": "DAB-DAB sąsaja",
	"DABDigital": "Skaitmeninis",
	"DABEnsembleList": "Stočių grupių sąrašas",
	"DABEnsembleListTitle": "Pasirinkite stočių grupę",
	"DABEnsembleListTitle2": "Stočių grupių sąrašas",
	"DABEnsembleListUpdateComplete": "Stočių grupių sąrašas atnaujintas",
	"DABFMLink": "DAB-FM sąsaja",
	"DABLBand": "L dažnių juosta",
	"DABListNotAvailable": "Stočių sąrašas nepasiekiamas ",
	"DABNoResultsFound": "Rezultatų nerasta",
	"DABNoSignal": "Nėra signalo",
	"DABPleaseUpdateList": "Atnaujinkite sąrašą",
	"DABRadio": "DAB radijas",
	"DABRadioText": "Radijo tekstas",
	"DABSelectEnsemble": "Pasirinkite stočių grupę",
	"DABSettings": "DAB nustatymai",
	"DABSettingsListTitle": "Nustatymai",
	"DABSettingsNowPlaying": "DAB nustatymai",
	"DABSignalLost": "{ChNum} Prarastas signalas",
	"DABSignalSearch": "Ieškoma…",
	"DABStationListUpdateFailedSelect": "Nepavyksta naujinti stočių sąrašo",
	"DABStationListUpdated": "Stočių sąrašas atnaujintas",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Pranešimas apie eismą išjungtas",
	"DABTrafficAlertOn": "Pranešimas apie eismą įjungtas",
	"DABUnableToUpdateStationList": "Nepavyksta naujinti",
	"DABUpdate": "Naujinti",
	"DABUpdateEnsemble": "Naujinti stočių grupių sąrašą?",
	"DABUpdateEnsembleList": "Naujinti stočių grupių sąrašą",
	"DABUpdateList": "Atnaujinkite sąrašą",
	"DABUpdateStation": "Naujinti stočių sąrašą?",
	"DABUpdatingEnsembleList": "Naujinamas stočių grupių sąrašas",
	"DABUpdatingList": "Naujinamas sąrašas…",
	"DABUpdatingListNowPlaying": "Naujinamas sąrašas…",
	"StationListTab": "Stočių sąrašas",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "lt_LT");