var Localization_dabAppDict_id_ID = {
	//"stringId" : "localString"
	"DABAnalog": "Analog",
	"DABBandIII": "Band III",
	"DABBandSettingsList": "Setelan Band",
	"DABBandSettingsTitle": "Setelan Band",
	"DABBoth": "Keduanya",
	"DABChangeEnsemble": "Harap ubah Ansambel",
	"DABDABLink": "Link DAB-DAB",
	"DABDigital": "Digital",
	"DABEnsembleList": "Daftar Ansambel",
	"DABEnsembleListTitle": "Pilih Ansembel",
	"DABEnsembleListTitle2": "Daftar Ansambel",
	"DABEnsembleListUpdateComplete": "Daftar Ansambel Diperbarui",
	"DABFMLink": "Link DAB-FM",
	"DABLBand": "Band L",
	"DABListNotAvailable": "Daftar Stasiun Tak Tersedia",
	"DABNoResultsFound": "Hasil tidak ditemukan",
	"DABNoSignal": "Tak Ada Sinyal",
	"DABPleaseUpdateList": "Harap perbarui daftar",
	"DABRadio": "Radio DAB",
	"DABRadioText": "Teks Radio",
	"DABSelectEnsemble": "Pilih Ansembel",
	"DABSettings": "Setelan DAB",
	"DABSettingsListTitle": "Setelan",
	"DABSettingsNowPlaying": "Setelan DAB",
	"DABSignalLost": "{ChNum} Sinyal Hilang",
	"DABSignalSearch": "Mencari…",
	"DABStationListUpdateFailedSelect": "Tak Dapat Memperbarui Daftar.",
	"DABStationListUpdated": "Daftar Stasiun Diperbarui",
	"DABStatusBarTitle": "DAB",
	"DABTrafficAlertOff": "Pemberitahuan Lalu-Lintas (TA) non aktif",
	"DABTrafficAlertOn": "Pemberitahuan Lalu-Lintas (TA) aktif",
	"DABUnableToUpdateStationList": "Tak Dapat Memperbarui",
	"DABUpdate": "Perbarui",
	"DABUpdateEnsemble": "Perbarui?",
	"DABUpdateEnsembleList": "Perbarui Daftar Ansambel",
	"DABUpdateList": "Perbarui daftar",
	"DABUpdateStation": "Perbarui Daftar Stasiun?",
	"DABUpdatingEnsembleList": "Perbarui Daftar Ansambel",
	"DABUpdatingList": "Memperbarui Daftar…",
	"DABUpdatingListNowPlaying": "Memperbarui Daftar…",
	"StationListTab": "Daftar Stasiun",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Station List",
	"VrHelp_NowPlaying_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Help_Left5": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_Help_Right1": "Previous",
	"VrHelp_NowPlaying_Help_Right2": "Next",
	"VrHelp_NowPlaying_Help_Right3": "DAB Settings",
	"VrHelp_NowPlaying_Help_Right4": "Sound Settings",
};

framework.registerAppDictLoaded("dab", "id_ID");