var Localization_warnguideAppDict_zh_TW = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "防抱死制動系統(ABS)故障。\n讓經銷商立即檢查車輛。\n",
	"AbsSysErrorShrt": "ABS故障",
	"AbsSystemErrorLong": "防抱死制動系統(ABS)故障。\n讓經銷商立即檢查車輛。\n",
	"AbsSystemErrorShrt": "ABS故障",
	"AccumulationDpfLong": "柴油微粒濾清器(DPF)中收集的顆粒物(PM)超過了法規值。\n在發動機完全預熱（藍色溫度燈關閉）後以10英哩/小時（15公裏/小時）或更高的速度行駛約10至15分鐘，以便消除顆粒物。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"AccumulationDpfShrt": "DPF中的PM累積",
	"ActiveBonnetSystemMalfunctionLong": "Active Bonnet 系統故障。\n如果該指示燈持續亮起或閃動，請讓經銷商檢查車輛。",
	"ActiveBonnetSystemMalfunctionShrt": "Active Bonnet 系統故障",
	"AfsSystemErrorLong": "自適應前照燈系統(AFS)故障。如果該指示燈一直閃爍，則讓經銷商檢查車輛。",
	"AfsSystemErrorShrt": "AFS故障",
	"AirbagSysPretensionerSysErrorLong": "安全氣囊/安全帶故障。讓經銷商立即檢查車輛",
	"AirbagSysPretensionerSysErrorShrt": "安全氣囊系統/預緊器系統故障",
	"AutoLevelSystemErrorLong": "大燈自動調平系統故障。\n如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"AutoLevelSystemErrorShrt": "自動調平系統故障",
	"AutoLevelSystemErrorShrtJ03": "大燈系統故障",
	"AutoTransSysErrorLong": "自動變速器故障。\n如果您繼續行駛，可能會損壞車輛。讓經銷商立即檢查車輛。\n",
	"AutoTransSysErrorShrt": "自動變速器故障",
	"AuxBattLowLong": "12V 電池電量低。\n・如果在行駛時該指示燈頻繁亮起，則表明電池效能可能下降。讓經銷商檢查車輛。\n・如果該指示燈長明不熄，則表明 12V 電池電量耗盡。查閱汽車使用者手冊之後，再啟動混合系統，並讓經銷商檢查車輛。\n",
	"AuxBattLowShrt": "12V 電池電量低",
	"BattManagSysErrorLong": "電池管理系統故障。讓經銷商檢查車輛。",
	"BattManagSysErrorShrt": "電池管理系統故障",
	"BrakOverrideSysErrorLong": "制動開關故障。\n讓經銷商立即檢查車輛。\n",
	"BrakOverrideSysErrorShrt": "制動優先系統故障",
	"BrakeSysErrorLong": "制動液液位低或制動系統故障。立即將車輛停在安全位置，並讓經銷商檢查車輛。",
	"BrakeSysErrorShrt": "制動系統故障",
	"BrakeSystemErrorLong": "電子控制制動系統故障。\n立即將車輛停在安全位置，並讓經銷商檢查車輛。\n",
	"BrakeSystemErrorShrt": "制動系統故障",
	"BsmSystemErrorLong": "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA)故障。\n檢查後保險槓表面是否有異常，如果較髒或者被雪覆蓋，則進行清潔。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"BsmSystemErrorShrt": "BSM故障",
	"ChargSysMalHighPrt": "充電系統故障。立即將車輛停在安全位置。",
	"ChargingSysErrorLong": "充電系統故障。\n如果您繼續行駛，可能會損壞車輛。立即將車輛停在安全位置，並讓經銷商檢查車輛。\n",
	"ChargingSysErrorShrt": "充電系統故障",
	"ChrgSysErrorLong": "充電系統故障。\n立即將車輛停在安全位置，並讓經銷商檢查車輛。\n",
	"ChrgSysErrorShrt": "充電系統故障",
	"ControlSystemErrorLong": "駐車位置控制系統故障。\n如果未檢查，可能導致下列任何一種情況：\n・駐車鎖定機構可能不工作。停在平坦位置上，並牢牢地設定駐車制動器。\n・電源開關可能沒有關閉。反復按電源開關，將其關閉。\n・ 行駛時「停車時設定駐車制動器」顯示將會關閉，在停車時將會開啟。\n讓經銷商立即檢查車輛。\n",
	"ControlSystemErrorShrt": "駐車位置控制系統故障",
	"DPFErrorLong": "柴油微粒過濾器(DPF)故障。\n讓經銷商檢查車輛。\n",
	"DPFErrorShrt": "DPF錯誤",
	"DRSSSysErrorLong": "DRSS系統出現錯誤。\n讓Mazda經銷商檢查您的車輛。\n",
	"DRSSSysErrorShrt": "DRSS故障",
	"DriveBattDropLong": "高壓電池殘餘電量低，因為變速器長時間一直位於空檔的位置。在空檔時無法充電。當長時間停車時，換到駐車檔。必要時按電源開關，重啟混合系統。\n",
	"DriveBattDropShrt": "高壓電池電量低",
	"DropKeyBattChrgLong": "鑰匙電池電量低。\n立即更換鑰匙電池。\n",
	"DropKeyBattChrgShrt": "鑰匙電池電量低",
	"DscSysErrorLong": "Dynamic Stability Control (DSC)、Traction Control System (TCS)或Hill Launch Assist (HLA)故障。\n讓經銷商立即檢查車輛。\n",
	"DscSysErrorShrt": "DSC故障",
	"DscSystemErrorLong": "動態穩定控制(DSC)或牽引力控制系統(TCS)故障。\n讓經銷商立即檢查車輛。\n",
	"DscSystemErrorShrt": "DSC故障",
	"EcbSysErrorLong": "再生制動或電子控制制動系統故障。\n立即將車輛停在安全地方，並讓經銷商檢查車輛。\n",
	"EcbSysErrorShrt": "制動系統故障",
	"ElectricParkingBrakeHighLong": "Electric parking brake故障。如果即使在操作電子駐車開關時，該指示燈還一直閃爍，立即將車輛停在平坦和安全的位置，並讓經銷商檢查車輛。",
	"ElectricParkingBrakeLong": "Electric parking brake故障。如果即使在操作電子駐車開關時，該指示燈還是一直亮，則讓經銷商檢查車輛。",
	"ElectricParkingBrakeShrt": "Electric parking brake故障",
	"ElectricVacuumPumpSystemMalfunctionLong": "電動真空泵系統發生故障。\n若不解決該問題可能導致系統故障，從而將造成意外的危險或損壞。\n請立即諮詢Mazda經銷商並對該故障進行檢查。",
	"ElectricVacuumPumpSystemMalfunctionShrt": "電動真空泵系統故障",
	"EloopChargingLong": "i‑ELOOP正在充電。\n在發動機正在運轉時，檢查充電是否完成以及警告指示燈是否關閉。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"EloopChargingShrt": "i‑ELOOP正在充電",
	"EloopSysErrorLong": "i‑ELOOP 系統故障.\n如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"EloopSysErrorShrt": "i‑ELOOP 系統故障",
	"EngCoolntTempHighOnLong": "發動機過熱。\n立即將車輛停在安全地方，然後關閉發動機並採取正確措施。請參閱所有者手冊。\n",
	"EngCoolntTempHighOnShrt": "發動機冷卻液溫度高",
	"EngOilPressureErrorLong": "發動機油壓力低。\n立即將車輛停在安全地方，然後關閉發動機，檢查發動機油液位。如有必要，新增機油。\n如果在新增機油或發動機油液位正常後該指示亮起，則讓經銷商立即檢查車輛。\n",
	"EngOilPressureErrorShrt": "發動機油壓力低",
	"EngSystemErrorLong": "發動機系統故障。讓經銷商立即檢查車輛。",
	"EngSystemErrorShrt": "發動機系統故障",
	"EngineOilPressureErrorLong": "發動機油壓力低。\n立即將車輛停在安全地方，然後關閉發動機，檢查發動機油液位。如有必要，新增機油。\n如果在新增機油或發動機油液位正常後該指示亮起，則讓經銷商立即檢查車輛。\n",
	"EngineOilPressureErrorShrt": "發動機油壓力低",
	"EngineWaterTempDropLong": "發動機冷卻液已冷，沒有暖空氣可供加熱器/除霜器使用。該指示燈亮起或熄滅時均可駕駛車輛。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"EngineWaterTempDropShrt": "發動機冷卻液溫度低",
	"EngineWaterTempRiseLong": "發動機開始變熱。\n緩慢行駛或者停車，直到該指示燈停止閃爍。如果即使在停車後該指示燈還一直閃爍，則採取正確措施。請參閱所有者手冊。",
	"EngineWaterTempRiseShrt": "發動機冷卻液溫度高",
	"EngnCoolTempHighHighPrt": "發動機冷卻液溫度高。立即將車輛停在安全位置。",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS雷達（感測器）被弄髒。\n清潔雷達（感測器）的整個表面。\n",
	"FOWMRCCDRSSRadarSoilingShrt": "FOW/MRCC/DRSS雷達故障",
	"FOWMRCCRadarSoilingLong": "FOW/MRCC雷達（感測器）故障。\n如果前格柵標徽較髒或者被雪覆蓋，則清潔其整個表面。\n如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"FOWMRCCRadarSoilingShrt": "FOW/MRCC雷達故障",
	"FOWSysError": "FOW故障",
	"FOWSysErrorLong": "Forward Obstruction Warning (FOW)系統故障。\n讓經銷商檢查車輛。",
	"FWDSysErrorLong": "4WD系統故障或前後輪胎的輪胎尺寸不同。\n讓經銷商檢查車輛。\n",
	"FWDSysErrorShrt": "4WD系統故障",
	"FuelAirFilterCartReplacePeriodLong": "需要更換燃油-空氣濾清器濾芯。",
	"FuelAirFilterCartReplacePeriodShrt": "需要更換燃油-空氣濾清器濾芯",
	"FuelCapInspectionLong": "可能沒有正確安裝油箱蓋。\n檢查是否已正確安裝並擰緊了油箱蓋。\n正確安裝並擰緊了油箱蓋後，該指示燈在幾個行駛週期內不會關閉，直至能夠確認系統正常後才會關閉。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"FuelCapInspectionShrt": "油箱蓋檢查",
	"HBCLDWSSysErrorLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)故障。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSSysErrorLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS)故障。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSSysErrorLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)故障。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSSysErrorLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)故障。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSSysErrorShrt": "HBC/LDWS 系統故障",
	"HBCLDWSSysErrorShrt_2": "HBC/LAS 系統故障",
	"HBCLDWSSysErrorShrt_3": "ALH/LDWS 系統故障",
	"HBCLDWSSysErrorShrt_4": "ALH/LAS 系統故障",
	"HBCLDWSWindshieldFogLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)故障。\n給擋風玻璃除霜。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSWindshieldFogLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS)故障。給擋風玻璃除霜。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSWindshieldFogLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)故障。給擋風玻璃除霜。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSWindshieldFogLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)故障。給擋風玻璃除霜。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLDWSWindshieldFogShrt": "HBC/LDWS 系統故障",
	"HBCLDWSWindshieldFogShrt_2": "HBC/LAS 系統故障",
	"HBCLDWSWindshieldFogShrt_3": "ALH/LDWS 系統故障",
	"HBCLDWSWindshieldFogShrt_4": "ALH/LAS 系統故障",
	"HBCLLDWSCamDisconnectLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)故障。\n清潔擋風玻璃。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"HBCLLDWSCamDisconnectLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS)故障。清潔擋風玻璃。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)故障。清潔擋風玻璃。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)故障。清潔擋風玻璃。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectShrt": "HBC/LDWS攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_2": "HBC/ LAS攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_3": "ALH/LDWS攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_4": "ALH/LAS攝像頭故障",
	"HBCSysErrorLong": "High Beam Control (HBC)故障。\n讓經銷商檢查車輛。",
	"HBCSysErrorLong_2": "Adaptive LED Headlights (ALH)故障。讓經銷商檢查車輛。",
	"HBCSysErrorShrt": "HBC故障",
	"HBCSysErrorShrt_2": "ALH故障",
	"HeadlightSystemErrorLongJ03": "大燈系統故障。讓Mazda經銷商檢查您的車輛。",
	"HybrdSysMalHighPrt": "混合系統故障。立即將車輛停在安全位置。",
	"HybridSysErrorLong": "混合系統故障。\n如果您繼續行駛，可能會損壞車輛。立即將車輛停在安全地方，並讓經銷商檢查車輛。\n",
	"HybridSysErrorShrt": "混合系統故障",
	"HybridSysOverheatLong": "混合系統故障。\n如果您繼續行駛，可能會損壞車輛。立即將車輛停在安全地方，並讓經銷商檢查車輛。\n",
	"HybridSysOverheatShrt": "混合系統過熱",
	"IeloopChrgHighPrt": "i‑ELOOP正在充電。在發動機正在運轉時，檢查充電是否完成以及警告指示燈是否關閉。",
	"IstopSysErrorLong": "i‑stop無法執行。\n讓Mazda經銷商檢查您的車輛。\n",
	"IstopSysErrorShrt": "i‑stop 系統故障",
	"KeylesSysErrorLong": "無鑰匙進入系統故障。\n讓經銷商檢查車輛。\n",
	"KeylesSysErrorShrt": "無鑰匙進入故障",
	"LDWSSysErrorLong": "Lane Departure Warning System (LDWS)故障。\n讓經銷商檢查車輛。",
	"LDWSSysErrorLong_2": "Lane-keep Assist System (LAS)故障。讓經銷商檢查車輛。",
	"LDWSSysErrorShrt": "LDWS故障",
	"LDWSSysErrorShrt_2": "LAS故障",
	"LowBrakeFluidLong": "制動液液位低。\n立即將車輛停在安全位置，並讓經銷商檢查車輛。\n",
	"LowBrakeFluidShrt": "制動液量低",
	"LowFuelLong": "油箱液位較低。\n立即給車輛加油。\n",
	"LowFuelShrt": "燃油量低",
	"LowTireAirPressureFlatLong": "胎壓低\n如果在TPMS警告燈亮起後，輪胎氣壓急劇下降，或者如果輪胎被刺破，爆胎警告燈也將亮起。如果洩氣保用輪胎被刺破，小心駕駛車輛到最近的Mazda經銷商並更換輪胎。",
	"LowTireAirPressureLong": "一個或多個輪胎的胎壓低。\n檢查輪胎的氣壓並調整到正常氣壓。調整輪胎氣壓直至聽到嘟嘟聲後，按TPMS SET開關。",
	"LowTireAirPressureShrt": "輪胎氣壓低",
	"LowWasheFluidLong": "洗滌液液位低。加注洗滌液。",
	"LowWasheFluidShrt": "洗滌液量低",
	"MRCCSysErrorLong": "Mazda Radar Cruise Control (MRCC)故障。\n讓經銷商檢查車輛。",
	"MRCCSysErrorShrt": "MRCC故障",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC)目前不可用。",
	"MRCCUnavailableShrt": "MRCC不可用",
	"NoWarnings": "未發現警告",
	"PowerSteeringSysErrorLong": "電動助力轉向故障。\n將車輛停在安全位置，然後關閉發動機。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"PowerSteeringSysErrorShrt": "電動助力轉向系統故障",
	"PpositionRequestLong": "將變速器換到駐車檔。\n這是由下列一種情況導致的：\n・ 當變速器位於非駐車檔的位置時啟動或停止了電池系統\n・ 當變速器位於 N、D 或 B 位置時開啟了駕駛員一側的車門\n・ 高壓電池殘餘電量低，因為變速器長時間位於空檔的位置\n必要時按電源開關，重啟混合系統。\n\n",
	"PpositionRequestShrt": "駐車位置請求",
	"PreheatingDispLampLong": "預熱塞正在預熱。\n如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"PreheatingDispLampShrt": "預熱塞正在預熱",
	"RoadSurfaceIcingCautionLong": "室外溫度為4°C或更低。\n行駛時請留心結冰路面。\n",
	"RoadSurfaceIcingCautionShrt": "路面結冰警告",
	"RvmSysErrorLong": "RVM系統出現錯誤。\n檢查後保險槓表面是否有異常，如果較髒或者被雪覆蓋，則進行清潔。\n如果該警告燈一直亮，則讓Mazda經銷商檢查您的車輛。\n",
	"RvmSysErrorShrt": "RVM故障",
	"SBSBrakeMRCCUnavailableLong": "SBS Brake/MRCC目前不可用。",
	"SBSBrakeMRCCUnavailableShrt": "SBS制動器/MRCC不可用",
	"SBSBrakeUnavailableLong": "SBS制動器目前不可用。",
	"SBSBrakeUnavailableShrt": "SBS制動器不可用",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS雷達（感測器）被弄髒。\n清潔雷達（感測器）的整個表面。\n",
	"SBSMRCCDRSSRadarSoilingShrt": "SBS/MRCC/DRSS雷達故障",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC雷達（感測器）被弄髒。\n清潔雷達（感測器）的整個表面。\n",
	"SBSMRCCRadarSoilingShrt": "SBS/MRCC雷達故障",
	"SBSSysErrorLong": "SBS系統出現錯誤。\n讓Mazda經銷商檢查您的車輛。\n",
	"SBSSysErrorShrt": "SBS故障",
	"SCBSSysErrorLong": "Smart City Brake Support (SCBS)故障。\n讓經銷商立即檢查車輛。\n",
	"SCBSSysErrorShrt": "SCBS故障",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS)目前不可用。",
	"SCBSUnavailableShrt": "SCBS不可用",
	"SCBSWindshieldSoilingLong": "Smart City Brake Support (SCBS)故障。\n清潔前擋風玻璃。如果該指示燈一直亮，則讓經銷商檢查車輛。",
	"SCBSWindshieldSoilingShrt": "SCBS故障",
	"SedimenterWarningLong": "沉澱分離器中積聚的水量超過額定量。\n如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"SedimenterWarningShrt": "沉澱分離器檢查",
	"SystemInspectionLong": "差速器油溫異常高，或者前後輪胎出現較大旋轉差異（例如在嘗試將車從泥漿中開出來時）。\n將車輛停在安全位置，然後在警告指示燈熄滅時繼續行駛。如果該指示燈一直亮，則讓經銷商檢查車輛。\n",
	"SystemInspectionShrt": "4WD系統檢查",
	"TpmsSysErrorLong": "胎壓監測系統(TPMS)故障。\n讓經銷商檢查車輛。\n",
	"TpmsSysErrorShrt": "TPMS系統故障",
	"VehicleSysErrorLong": "車輛系統故障。\n讓經銷商檢查車輛。\n",
	"VehicleSysErrorShrt": "車輛系統故障",
	"WarningGuidance": "警告指導",
	"WarningSafetyMessage": "出於安全原因，不顯示警告指導。",
	"Warnings": "警告",
	"brakeFluid": "制動液液位低",
	"engineOilPressure": "發動機油壓力",
	"highVoltage": "高電壓電池電量低",
	"lowBattStartEngine": "電池電量低！起動發動機！",
};

framework.registerAppDictLoaded("warnguide", "zh_TW");