var Localization_warnguideAppDict_hr_HR = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Kvar sustava ABS-a.\nOdmah kontaktirajte servis\n",
	"AbsSysErrorShrt": "Kvar ABS-a",
	"AbsSystemErrorLong": "Kvar sustava ABS-a.\nOdmah kontaktirajte servis.\n",
	"AbsSystemErrorShrt": "Kvar ABS-a",
	"AccumulationDpfLong": "Čestice (PM) prikupljene u filtru čestica (DPF) prekoračile su propisanu vrijednost.\nVozite otprilike 10 do 15 minuta s potpuno zagrijanim motorom (plavo svjetlo temp. je isključeno) brzinom od 15 km/h ili većom kako biste eliminirali čstice.  Ako ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"AccumulationDpfShrt": "Akumulacija čestica u DPF-u",
	"ActiveBonnetSystemMalfunctionLong": "Kvar na sustavu Active Bonnet.\nOdvedite vozilo na provjeru u servis ako lampica nastavi svijetliti ili treperiti.",
	"ActiveBonnetSystemMalfunctionShrt": "Kvar na sustavu Active Bonnet",
	"AfsSystemErrorLong": "Provjeritenepravilnosti na površini stražnjeg odbojnika i očistite ga ako je prljav ili prekriven snijegom. Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"AfsSystemErrorShrt": "Kvar AFS-a",
	"AirbagSysPretensionerSysErrorLong": "Kvar zračnog jastuka/sigurnosnog pojasa. Odmah kontaktirajte servis.",
	"AirbagSysPretensionerSysErrorShrt": "Kvar zračnih jastuka/zatezača pojasa",
	"AutoLevelSystemErrorLong": "Kvar sustava podešavanja prednjih svjetala.\nAko ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"AutoLevelSystemErrorShrt": "Kvar sustava podeš. svj. snopa",
	"AutoLevelSystemErrorShrtJ03": "Kvar sustava prednjih svjetala",
	"AutoTransSysErrorLong": "Kvar automatskog prijenosa.\nAko nastavite voziti, možete oštetiti vozilo.  Kontaktirajte servis.  \n",
	"AutoTransSysErrorShrt": "Kvar automatskog prijenosa",
	"AuxBattLowLong": "Punjenje 12V akumulatora je nedovoljno.\n・Ako se ovaj indikator često uključuje tijekom vožnje, akumulator je možda istrošen. Pregledajte vozilo u servisu.\n・Ako je ovaj indikator upaljen stalno i ne isključuje se, 12V akumulator potpuno istrošen. Prije pokretanja hibridnog sustava pogledajte priručnik vlasnika i kontaktirajte servis.",
	"AuxBattLowShrt": "12V nizak napon akumulatora",
	"BattManagSysErrorLong": "Kvar sustava upravljanja akumulatorom.\nKontaktirajte servis.\n",
	"BattManagSysErrorShrt": "Kvar sust. uprav. akumulatorom",
	"BrakOverrideSysErrorLong": "Kvar prekidača kočnice.\nOdmah kontaktirajte servis.\n",
	"BrakOverrideSysErrorShrt": "Kvar sust. pametne pap. koč.",
	"BrakeSysErrorLong": "Niska razina tekućine za kočnice ili kvar sustava kočenja.  Odmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.",
	"BrakeSysErrorShrt": "Kvar sustava kočenja",
	"BrakeSystemErrorLong": "Kvar elektronički reguliranog sustava kočenja.\nOdmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.\n",
	"BrakeSystemErrorShrt": "Kvar sustava kočenja",
	"BsmSystemErrorLong": "Kvar na Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nProvjerite nepravilnosti na površini stražnjeg odbojnika i očistite ga ako je prljav ili prekriven snijegom. Ako ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"BsmSystemErrorShrt": "Kvar BSM-a",
	"ChargSysMalHighPrt": "Kvar sustava punjenja. Odmah zaustavite vozilo na sigurnome mjestu.",
	"ChargingSysErrorLong": "Kvar sustava punjenja. \nAko nastavite voziti, možete oštetiti vozilo.  Odmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.\n",
	"ChargingSysErrorShrt": "Kvar sustava punjenja",
	"ChrgSysErrorLong": "Kvar sustava punjenja.\nOdmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.\n",
	"ChrgSysErrorShrt": "Kvar sustava punjenja",
	"ControlSystemErrorLong": "Kvar sustava kontrole parkiranja.\nAko se ostavi bez provjere, može doći do bilo koje od sljedećih situacija:\n・Mehanizam parking-blokade možda neće raditi. Parkirajte na ravnom mjestu i snažno potegnite ručnu kočnicu.\n・Sklopka paljenja možda se neće isključiti. Uzastopce pritišćite sklopku paljenja kako biste je isključili.\n・ Prikaz \"Prilikom parkiranja povucite ručnu kočnicu\" će se isključiti tijekom vožnje, a uključiti prilikom zaustavljanja.\nOdmah dajte vozilo na pregled prodavaču.\n",
	"ControlSystemErrorShrt": "Kvar sustava parkirnih senzora",
	"DPFErrorLong": "Kvar filtra čestica (DPF). Kontaktirajte servis.",
	"DPFErrorShrt": "Pogreška DPF-a",
	"DRSSSysErrorLong": "U DRSS sustavu postoji pogreška.\nKontaktirajte servis.\n",
	"DRSSSysErrorShrt": "Kvar DRSS-a",
	"DriveBattDropLong": "Preostala snaga visokonaponskog akumulatora se potrošila jer je mjenjač dugo bio u neutralnom položaju.\nU položaju praznog hoda punjenje nije moguće. Kada se zaustavljate na dulje vrijeme, prebacite u \"Park\".\nAko je potrebno, pritiskom sklopke paljenja ponovno pokrenite hibridni sustav.\n",
	"DriveBattDropShrt": "Nizak napon visokonaponskog akumulatora",
	"DropKeyBattChrgLong": "Niska razina napunjenosti glavnog akumulatora.\nOdmah zamijenite glavni akumulator.\n",
	"DropKeyBattChrgShrt": "Nizak napon glavnog akumulatora",
	"DscSysErrorLong": "Kvar sustava Dynamic Stability Control (DSC), Traction Control System (TCS) ili funkcije za Hill Launch Assist (HLA).\nOdmah kontaktirajte servis.\n",
	"DscSysErrorShrt": "Kvar DSC-a",
	"DscSystemErrorLong": "Kvar sustava kontrole dinamičke stabilnosti (DSC) ili kontrole proklizavanja.\nOdmah kontaktirajte servis.\n",
	"DscSystemErrorShrt": "Kvar DSC-a",
	"EcbSysErrorLong": "Kvar sustava regenerativnog kočenja ili elektronički upravljanog kočenja.\nOdmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.\n",
	"EcbSysErrorShrt": "Kvar sustava kočenja",
	"ElectricParkingBrakeHighLong": "Dogodio se kvar u sustavu parkirne kočnice. Obratite se svojem distributeru Mazda vozila radi provjere.",
	"ElectricParkingBrakeLong": "Dogodio se kvar u sustavu parkirne kočnice. Obratite se svojem distributeru Mazda vozila radi provjere.",
	"ElectricParkingBrakeShrt": "Kvar sustava parkirne kočnice",
	"ElectricVacuumPumpSystemMalfunctionLong": "Dogodio se kvar u sustavu električne vakuumske pumpe. Ako se neispravnost ne riješi, sustav može zakazati i predstavljati neočekivanu opasnost ili prouzročiti kvar. Smjesta se obratite koncesionaru Mazda vozila radi provjere. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Kvar sustava električne vakuumske pumpe",
	"EloopChargingLong": "i‑ELOOP se puni.\nDok motor radi provjerite je li punjenje dovršeno i je li indikator upozorenja isključen. Ako ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"EloopChargingShrt": "Punjenje i‑ELOOP-a",
	"EloopSysErrorLong": "Kvar i‑ELOOP sustava.\nAko ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"EloopSysErrorShrt": "Kvar i‑ELOOP sustava",
	"EngCoolntTempHighOnLong": "Motor se pregrijava.\nOdmah na sigurnom mjestu zaustavite vozilo, ugasite motor i poduzmite odgovarajuće korake.  Pogledajte priručnik za vlasnika.\n",
	"EngCoolntTempHighOnShrt": "Visoka temp. rashl. tek. motora",
	"EngOilPressureErrorLong": "Nizak tlak ulja motora\nOdmah na sigurnom mjestu zaustavite vozilo, ugasite motor i provjerite razinu ulja motora. Po potrebi dolijte ulje.\nAko ovaj indikator ostane uključen nakon dodavanja ulja ili ako je razina ulja motora u redu, kontaktirajte servis.\n",
	"EngOilPressureErrorShrt": "Nizak tlak ulja motora",
	"EngSystemErrorLong": "Kvar motora.  Odmah kontaktirajte servis.",
	"EngSystemErrorShrt": "Kvar motora",
	"EngineOilPressureErrorLong": "Nizak tlak ulja motora\nOdmah na sigurnom mjestu zaustavite vozilo, ugasite motor i provjerite razinu ulja motora. Po potrebi dolijte ulje.\nAko ovaj indikator ostane uključen nakon dodavanja ulja ili ako je razina ulja motora u redu, kontaktirajte servis.\n",
	"EngineOilPressureErrorShrt": "Nizak tlak ulja motora",
	"EngineWaterTempDropLong": "Rashladna tekućina motora je hladna, a iz grijača/odmrzivača nema toplog zraka. Vozilo se može voziti s uključenim ili isključenim indikatorom.  Ako ovaj indikator ostaje uključen, dajte vozilo na pregled prodavaču.",
	"EngineWaterTempDropShrt": "Niska temp. rashl. tek. motora",
	"EngineWaterTempRiseLong": "Motor postaje vruć.\nVozite sporo ili zaustavite vozilo dok indikator ne prestane treptati. Ako nastavi treptati i nakon zaustavljanja vozila, poduzmite odgovarajuće korake. Pogledajte priručnik za vlasnika.\n",
	"EngineWaterTempRiseShrt": "Visoka temp. rashl. tek. motora",
	"EngnCoolTempHighHighPrt": "Visoka temp. rashl. tek. Odmah zaustavite vozilo na sigurnome mjestu.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS radar (senzor) je zaprljan. Očistite cijelu površinu radara (senzora).",
	"FOWMRCCDRSSRadarSoilingShrt": "Kvar FOW/MRCC/DRSS radara",
	"FOWMRCCRadarSoilingLong": "Kvar FOW/MRCC radara (senzora).\nOčistite cijeli znak na prednjoj rešetki ako je prljav ili prekriven snijegom.  \nAko ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"FOWMRCCRadarSoilingShrt": "Kvar FOW/MRCC radara",
	"FOWSysError": "Kvar FOW-a",
	"FOWSysErrorLong": "Forward Obstruction Warning (FOW).\nKontaktirajte servis.",
	"FWDSysErrorLong": "Kvar sustava 4WD ili je veličina guma različita na prednjim i stražnjim kotačima.\nKontaktirajte servis.\n",
	"FWDSysErrorShrt": "Kvar sustava 4WD",
	"FuelAirFilterCartReplacePeriodLong": "Potrebno je zamijeniti filtar gorivo ili zraka.",
	"FuelAirFilterCartReplacePeriodShrt": "Potr. zamjena uloška fil. gorivo-zrak",
	"FuelCapInspectionLong": "Čep spremnika za gorivo nije ispravno postavljen.\nProvjerite je li čep spremnika ispravno postavljen i pritegnut.\nNakon ispravnog postavljanja i pritezanja, ovaj indikator neće se isključiti tijekom nekoliko ciklusa vožnje sve dok se ne može potvrditi da je sustav u redu.  Ako ovaj indikator ostaje i tada uključen, kontaktirajte servis.\n",
	"FuelCapInspectionShrt": "Provjerite poklopac spremnika goriva",
	"HBCLDWSSysErrorLong": "Kvar High Beam Control (HBC)/Lane Departure Warning System (LDWS). Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"HBCLDWSSysErrorLong_2": "Kvar High Beam Control (HBC)/Lane-keep Assist System (LAS). Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"HBCLDWSSysErrorLong_3": "Kvar Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLDWSSysErrorLong_4": "Kvar Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLDWSSysErrorShrt": "Kvar HBC/LDWS sustava",
	"HBCLDWSSysErrorShrt_2": "Kvar HBC/LAS sustava",
	"HBCLDWSSysErrorShrt_3": "Kvar ALH/LDWS sustava",
	"HBCLDWSSysErrorShrt_4": "Kvar ALH/LAS sustava",
	"HBCLDWSWindshieldFogLong": "Kvar High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nOdmrznite vjetrobransko staklo.  Ako ovaj indikator ostaje uključen, dajte vozilo na pregled prodavaču.",
	"HBCLDWSWindshieldFogLong_2": "Kvar High Beam Control (HBC)/Lane-keep Assist System (LAS). Odmrznite vjetrobransko staklo. Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLDWSWindshieldFogLong_3": "Kvar Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Odmrznite vjetrobransko staklo. Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"HBCLDWSWindshieldFogLong_4": "Kvar Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Odmrznite vjetrobransko staklo. Ako ovaj indikator ostane uključen, kontaktirajte servis.",
	"HBCLDWSWindshieldFogShrt": "Kvar HBC/LDWS sustava",
	"HBCLDWSWindshieldFogShrt_2": "Kvar HBC/LAS sustava",
	"HBCLDWSWindshieldFogShrt_3": "Kvar ALH/LDWS sustava",
	"HBCLDWSWindshieldFogShrt_4": "Kvar ALH/LAS sustava",
	"HBCLLDWSCamDisconnectLong": "Kvar High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nOčistite vjetrobransko staklo.  Ako ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"HBCLLDWSCamDisconnectLong_2": "Kvar High Beam Control (HBC)/Lane-keep Assist System (LAS).\nOčistite vjetrobransko staklo. Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLLDWSCamDisconnectLong_3": "Kvar Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Očistite vjetrobransko staklo. Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLLDWSCamDisconnectLong_4": "Kvar Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Očistite vjetrobransko staklo. Ako ovaj indikator ostaje uključen, kontaktirajte servis. ",
	"HBCLLDWSCamDisconnectShrt": "Kvar HBC/LDWS kamere",
	"HBCLLDWSCamDisconnectShrt_2": "Kvar HBC/LAS kamere",
	"HBCLLDWSCamDisconnectShrt_3": "Kvar ALH/LDWS kamere",
	"HBCLLDWSCamDisconnectShrt_4": "Kvar ALH/LAS kamere",
	"HBCSysErrorLong": "Kvar High Beam Control (HBC).\nKontaktirajte servis.",
	"HBCSysErrorLong_2": "Kvar Adaptive LED Headlights (ALH). Kontaktirajte servis.",
	"HBCSysErrorShrt": "Kvar HBC-a",
	"HBCSysErrorShrt_2": "Kvar ALH",
	"HeadlightSystemErrorLongJ03": "Dogodio se kvar u sustavu prednjih svjetala. Ako svjetlo upozorenja neprestano treperi, obratite se svojem distributeru Mazda vozila.",
	"HybrdSysMalHighPrt": "Kvar hibridnog sustava. Odmah zaustavite vozilo na sigurnome mjestu.",
	"HybridSysErrorLong": "Kvar hibridnog sustava.\nAko nastavite voziti, možete oštetiti vozilo. Odmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.",
	"HybridSysErrorShrt": "Kvar hibridnog sustava",
	"HybridSysOverheatLong": "Kvar hibridnog sustava.\nAko nastavite voziti, možete oštetiti vozilo. Odmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.",
	"HybridSysOverheatShrt": "Pregrijavanje hibridnog sustava",
	"IeloopChrgHighPrt": "i‑ELOOP se puni. Dok motor radi provjerite je li punjenje dovršeno i je li indikator upozorenja isključen.",
	"IstopSysErrorLong": "Rad i‑stop-a nije moguć.\nKontaktirajte servis.\n",
	"IstopSysErrorShrt": "Kvar i‑stop sustava",
	"KeylesSysErrorLong": "Kvar sustava za daljinsko otključavanje.\nKontaktirajte servis.\n",
	"KeylesSysErrorShrt": "Kvar sustava za bezključno otklj.",
	"LDWSSysErrorLong": "Kvar Lane Departure Warning System (LDWS).\nKontaktirajte servis.",
	"LDWSSysErrorLong_2": "Kvar Lane-keep Assist System (LAS). Kontaktirajte servis.",
	"LDWSSysErrorShrt": "Kvar LDWS-a",
	"LDWSSysErrorShrt_2": "Kvar LAS",
	"LowBrakeFluidLong": "Niska razina tekućine za kočnice.\nOdmah na sigurnom mjestu zaustavite vozilo i kontaktirajte servis.\n",
	"LowBrakeFluidShrt": "Niska razina kočione tekućine",
	"LowFuelLong": "Malo goriva u spremniku. Dopunite spremnik.",
	"LowFuelShrt": "Malo goriva u spremniku",
	"LowTireAirPressureFlatLong": "Ako se tlak u gumama jako smanji nakon paljenja TPMS svjetla upozorenja, ili je guma probušena, upalit će se i svjetlo upozorenja o probušenoj gumi. Ako je guma probušena, pažljivo odvezite vozilo do najbližeg koncesionara Mazda vozila i promijenite je.",
	"LowTireAirPressureLong": "Nizak tlak u jednoj ili više guma.\nProvjerite tlak u gumama, a zatim ga prilagodite ispravnom tlaku.  Nakon prilagodbe tlaka u gumama pritišćite prekidač TPMS SET dok ne začujete bip.",
	"LowTireAirPressureShrt": "Nizak tlak u gumama",
	"LowWasheFluidLong": "Niska razina tekućine za pranje stakla. Dolijte tekućinu za pranje stakla.",
	"LowWasheFluidShrt": "Niska razina tekućine za pranje stakla",
	"MRCCSysErrorLong": "Kvar na Mazda Radar Cruise Control (MRCC). Kontaktirajte servis.",
	"MRCCSysErrorShrt": "Kvar MRCC-a",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) trenutačno nije dostupan.",
	"MRCCUnavailableShrt": "MRCC nedostupan",
	"NoWarnings": "Upozorenja nisu pronađena",
	"PowerSteeringSysErrorLong": "Kvar električnog servo upravljača.\nVozilo zaustavite na sigurnom mjestu i ugasite motor.  Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"PowerSteeringSysErrorShrt": "Kvar servo upravljača",
	"PpositionRequestLong": "Prebacite prijenos na \"Park\".\nUzrok ovoga nešto je od sljedećeg:\n・ Sustav baterije je pokrenut ili zaustavljen s prijenosom u položaju različitom od parkiranog\n・ Vrata na strani vozača otvorena su s prijenosom u praznom hodu, brzini ili vožnji unatrag\n・ Ostatni napon visokonaponske baterije je nizak jer je mjenjač u dugo u neutralnom položaju.\nAko je potrebno, pritiskom sklopke paljenja ponovno pokrenite hibridni sustav.\n",
	"PpositionRequestShrt": "Zahtjeva se položaj \"Park\"",
	"PreheatingDispLampLong": "Grijači se pregrijavaju.\nAko ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"PreheatingDispLampShrt": "Predgrijavanje grijača",
	"RoadSurfaceIcingCautionLong": "Vanjska temperatura iznosi 4°C ili manje.\nMoguća je poledica.",
	"RoadSurfaceIcingCautionShrt": "Moguća poledica",
	"RvmSysErrorLong": "U RVM sustavu postoji pogreška.\nProvjerite nepravilnosti na površini stražnjeg odbojnika i očistite ga ako je prljav ili prekriven snijegom. Ako ovo svjetlo upozorenja ostaje uključeno, kontaktirajte servis.\n",
	"RvmSysErrorShrt": "Kvar RVM-a",
	"SBSBrakeMRCCUnavailableLong": "SBS kočnica/MRCC trenutačno nisu dostupni.",
	"SBSBrakeMRCCUnavailableShrt": "SBS kočnica/MRCC nedostupni",
	"SBSBrakeUnavailableLong": "SBS kočnica trenutačno nije dostupna.",
	"SBSBrakeUnavailableShrt": "SBS kočnica nedostupna",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS radar (senzor) je zaprljan.\nOčistite cijelu površinu radara (senzora).\n",
	"SBSMRCCDRSSRadarSoilingShrt": "Kvar SBS/MRCC/DRSS radara",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC/ radar (senzor) je zaprljan. Očistite cijelu površinu radara (senzora).",
	"SBSMRCCRadarSoilingShrt": "Kvar SBS/MRCC radara",
	"SBSSysErrorLong": "U SBS sustavu postoji pogreška.\nKontaktirajte servis.\n",
	"SBSSysErrorShrt": "Kvar SBS-a",
	"SCBSSysErrorLong": "Kvar Smart City Brake Support (SCBS).\nOdmah kontaktirajte servis.",
	"SCBSSysErrorShrt": "Kvar SCBS-a",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) trenutačno nije dostupna.",
	"SCBSUnavailableShrt": "SCBS nedostupan",
	"SCBSWindshieldSoilingLong": "Kvar Smart City Brake Support (SCBS).\nOčistite prednje vjetrobransko staklo.  Ako ovaj indikator ostaje uključen, kontaktirajte servis.",
	"SCBSWindshieldSoilingShrt": "Kvar SCBS-a",
	"SedimenterWarningLong": "Količina vode akumulirana u taložniku prelazi nazivnu količinu.\nAko ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"SedimenterWarningShrt": "Provjera taložnika",
	"SystemInspectionLong": "Temperatura ulja diferencijala neuobičajeno je visoka ili je došlo do velike razlike u rotaciji na prednjim i stražnjim gumama (poput one kada pokušavate izaći iz blata).\nVozilo zaustavite na sigurnom mjestu, a nakon što se indikator upozorenja isključi nastavite voziti. Ako ovaj indikator ostaje uključen, kontaktirajte servis.\n",
	"SystemInspectionShrt": "Provjera sustava 4WD",
	"TpmsSysErrorLong": "Kvar sustava nadzora tlaka u gumama (TPMS).\nKontaktirajte servis.\n",
	"TpmsSysErrorShrt": "Kvar sustava TPMS",
	"VehicleSysErrorLong": "Kvar sustava vozila. Kontaktirajte servis.",
	"VehicleSysErrorShrt": "Kvar sustava vozila",
	"WarningGuidance": "Pregled upozorenja",
	"WarningSafetyMessage": "Navođenje s upozorenjima nije prikazano iz sigurnosnih razloga.",
	"Warnings": "Upozorenja",
	"brakeFluid": "Niska razina koč. tekuć.",
	"engineOilPressure": "Tlak ulja motora",
	"highVoltage": "Niska raz. nap. visokonap. bat.",
	"lowBattStartEngine": "Nisko nap. bat.! Pokreni motor!",
};

framework.registerAppDictLoaded("warnguide", "hr_HR");