var Localization_warnguideAppDict_de_DE = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
	"AbsSysErrorShrt": "ABS-Fehlfunktion",
	"AbsSystemErrorLong": "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"AbsSystemErrorShrt": "ABS-Fehlfunktion",
	"AccumulationDpfLong": "Die im Diesel-Partikelfilter (DPF) gesammelten Partikel (PM), haben den Grenzwert überschritten. \nFahren Sie für etwa 10 bis 15 Minuten bei voll aufgewärmten Motor (blaues Temperatur-Licht aus) bei einer Geschwindigkeit von 10 mph (15km/h) oder mehr, um die PM zu beseitigen.  Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet",
	"AccumulationDpfShrt": "Rußpartikelansammlung im DPF",
	"ActiveBonnetSystemMalfunctionLong": "Fehlfunktion im Active Bonnet system.\nLassen Sie das Fahrzeug von einem Händler überprüfen, falls diese Anzeige anbleibt oder weiterhin blinkt.",
	"ActiveBonnetSystemMalfunctionShrt": "Fehlfunktion im Active Bonnet system",
	"AfsSystemErrorLong": "Fehlfunktion Kurvenlicht (AFS). Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn die Warnleuchte weiterhin blinkt.",
	"AfsSystemErrorShrt": "AFS-Fehlfunktion",
	"AirbagSysPretensionerSysErrorLong": "Airbag/Sicherheitsgurt-Fehlfunktion \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"AirbagSysPretensionerSysErrorShrt": "Airbagsyst./Gurtstraffersyst.-fehl.",
	"AutoLevelSystemErrorLong": "Fehlfunktion der automatischen Scheinwerferhöhenverstellung. \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Warnlicht weiterhin leuchtet.",
	"AutoLevelSystemErrorShrt": "Auto-Regulierungs-Systemfehler",
	"AutoLevelSystemErrorShrtJ03": "Scheinwerfersystem-Fehlfunktion",
	"AutoTransSysErrorLong": "Automatikgetriebe-Fehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden.  Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.  ",
	"AutoTransSysErrorShrt": "Fehlfunktion Automatikgetriebe",
	"AuxBattLowLong": "Niedrige Ladung der 12V-Starterbatterie.\n· Wenn diese Anzeige häufig während der Fahrt leuchtet, kann die Batterie beeinträchtigt werden. Lassen Sie das Fahrzeug von einem Händler überprüfen.\n· Wenn diese Anzeige ständig leuchtet und nicht mehr ausgeht, ist die 12V-Statrerbatterie leer. Sehen Sie vor dem Start des Hybridsystems in der Bedienungsanleitung nach und lassen das Fahrzeug von einem Händler überprüfen.",
	"AuxBattLowShrt": "12V-Batterie fast leer",
	"BattManagSysErrorLong": "Batteriemanagement-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"BattManagSysErrorShrt": "Fehlfkt. Batteriesteuerung",
	"BrakOverrideSysErrorLong": "Bremsschalterfehlfunktion. \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"BrakOverrideSysErrorShrt": "Bremsüberbrückung-Systemfehler",
	"BrakeSysErrorLong": "Niedriger Bremsflüssigkeitsstand oder Bremssystemfehlfunktion. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"BrakeSysErrorShrt": "Bremssystemfehlfunktion",
	"BrakeSystemErrorLong": "Fehlfunktion im elektronisch überwachten Bremssystem. \nDas Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"BrakeSystemErrorShrt": "Bremssystemfehlfunktion",
	"BsmSystemErrorLong": "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA). \nÜberprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung  oder falls mit Schnee bedeckt. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"BsmSystemErrorShrt": "BSM-Fehlfunktion",
	"ChargSysMalHighPrt": "Systemstörung des Ladesystems. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"ChargingSysErrorLong": "Ladesystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden.  Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.\n",
	"ChargingSysErrorShrt": "Ladesystemfehlfunktion",
	"ChrgSysErrorLong": "Ladesystemfehlfunktion \nDas Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"ChrgSysErrorShrt": "Ladesystemfehlfunktion",
	"ControlSystemErrorLong": "Fehler Einparkhilfe. Wenn dies nicht überprüft wird, kann das zu den folgenden Situationen führen: \n・Der Park-Schließechanismus funktioniert ggf. nicht. Parken Sie auf einer flachen Stelle und verwenden Sie die Feststellbremse. \n・Der Netzschalter läßt sich ggf. nicht ausschalten. Drücken Sie zum Ausschalten wiederholt den Netzschalter. \n・ Die Anzeige\"Feststellbremse beim Parken verwenden\" geht beim Fahren und bei Anhalten aus. \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.\n",
	"ControlSystemErrorShrt": "Fehler Einparkhilfe",
	"DPFErrorLong": "Diesel-Partikelfilter (DPF) Fehlfunktion \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"DPFErrorShrt": "DPF-Fehler",
	"DRSSSysErrorLong": "Im DRSS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"DRSSSysErrorShrt": "DRSS-Fehlfunktion",
	"DriveBattDropLong": "Die verbleibende Ladung der Hochvoltbatterie ist gering, weil das Getriebe lange in der Neutral Position verblieben ist. \nIn der Position Neutral ist ein Aufladen nicht möglich. Stellen Sie bei langen Stillstandszeiten auf die Position Parken. \nStarten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu.",
	"DriveBattDropShrt": "Hochvoltbatterie fast leer",
	"DropKeyBattChrgLong": "Schlüsselbatterie schwach \nSofort die Schlüsselbatterie ersetzen.\n",
	"DropKeyBattChrgShrt": "Schlüsselbatterie schwach",
	"DscSysErrorLong": "Fehlfunktion der Dynamic Stability Control (DSC), des Traction Control System (TCS) oder des Hill Launch Assist (HLA). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
	"DscSysErrorShrt": "DSC-Fehlfunktion",
	"DscSystemErrorLong": "Fehlfunktion der dynamischen Stabilitätskontrolle (DSC) oder des Traktionskontrollsystems (TCS). \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"DscSystemErrorShrt": "DSC-Fehlfunktion",
	"EcbSysErrorLong": "Fehlfunktion bei der Bremsrückgewinnung oder des elektronisch gesteuerten Bremssystems. \nDas Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.\n",
	"EcbSysErrorShrt": "Bremssystemfehlfunktion",
	"ElectricParkingBrakeHighLong": "Eine Fehlfunkion ist bei der Parkbremse aufgetreten. Zur Inspektion konsultieren Sie Ihren Mazda-Händler.",
	"ElectricParkingBrakeLong": "Eine Fehlfunkion ist bei der Parkbremse aufgetreten. Zur Inspektion konsultieren Sie Ihren Mazda-Händler.",
	"ElectricParkingBrakeShrt": "Parkbremsen-Fehlfunktion",
	"ElectricVacuumPumpSystemMalfunctionLong": "Eine Fehlfunktion ist in der  elektrischen Unterdruckpumpe der Bremse aufgetreten. Ohne Korrektur kann das System ausfallen, wodurch Gefahr oder Fehlfunktion droht. Konsultieren Sie sofort Ihren Mazda-Händler und lassen Sie diesen Fehler inspizieren. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Bremssystem-Unterdruckpumpe - Fehlfunktion",
	"EloopChargingLong": "i‑ELOOP wird geladen. \nÜberprüfen Sie bei laufendem Motor, dass der Ladevorgang  abgeschlossen und die Warnanzeige aus ist. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"EloopChargingShrt": "i‑ELOOP-Ladung",
	"EloopSysErrorLong": "i‑ELOOP-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"EloopSysErrorShrt": "i‑ELOOP-Systemfehlfunktion",
	"EngCoolntTempHighOnLong": "Motor überhitzt sich\nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.",
	"EngCoolntTempHighOnShrt": "Temperatur Motorkühlmittel hoch",
	"EngOilPressureErrorLong": "Niedriger Motoröldruck \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Ölstand. Falls erforderlich, Öl hinzufügen. \nLassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.",
	"EngOilPressureErrorShrt": "Niedriger Motoröldruck",
	"EngSystemErrorLong": "Motorsystemfehlfunktion  Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"EngSystemErrorShrt": "Motorsystemfehlfunktion",
	"EngineOilPressureErrorLong": "Niedriger Motoröldruck \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Motorölstand. Falls erforderlich, Öl hinzufügen. \nLassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.",
	"EngineOilPressureErrorShrt": "Niedriger Motoröldruck",
	"EngineWaterTempDropLong": "Motorkühlmittel ist kalt und es ist keine warme Luft für Heizung/Defroster verfügbar. Das Fahrzeug darf mit ein-oder ausgeschalteter Anzeige gefahren werden.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"EngineWaterTempDropShrt": "Temperatur Motorkühlm. niedrig",
	"EngineWaterTempRiseLong": "Der Motor fängt an heiß zu laufen. \nFahren Sie langsam oder halten Sie das Fahrzeug an, bis die Anzeige aufhört zu blinken. Wenn die Anzeige auch nach dem Anhalten des Fahrzeugs weiter blinkt, ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.\n",
	"EngineWaterTempRiseShrt": "Temperatur Motorkühlmittel hoch",
	"EngnCoolTempHighHighPrt": "Fahrzeug-Kühlmitteltemperatur hoch. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"FOWMRCCDRSSRadarSoilingLong": "Das FOW/MRCC/DRSS-Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radar (Sensors).",
	"FOWMRCCDRSSRadarSoilingShrt": "FOW/MRCC/DRSS-Radarfehlfunktion",
	"FOWMRCCRadarSoilingLong": "FOW/MRCC/Radar (Sensor) Fehlfunktion \nReinigen Sie die gesamte Oberfläche des vorderen Kühlergrill-Emblems, falls verschmutzt oder mit Schnee bedeckt.  \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"FOWMRCCRadarSoilingShrt": "FOW/MRCC- Radarfehlfunktion",
	"FOWSysError": "FOW-Fehlfunktion",
	"FOWSysErrorLong": "Im Forward Obstruction Warning (FOW) System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"FWDSysErrorLong": "Fehlfunktion des 4WD-Systems oder Größenunterschied zwischen Vorder-und Hinterreifen. \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"FWDSysErrorShrt": "4WD-Systemfehlfunktion",
	"FuelAirFilterCartReplacePeriodLong": "Der Kraftstoff-Luftfiltereinsatz muss ersetzt werden.",
	"FuelAirFilterCartReplacePeriodShrt": "Kraftstoffilter-Luftfiltereinsatz erneuern",
	"FuelCapInspectionLong": "Der Tankdeckel ist möglicherweise nicht richtig verschlossen. \nÜberprüfen Sie, ob der Tankdeckel richtig geschlossen ist. \nNach Aufsetzen und Festziehen des Tankdeckels bleibt diese Anzeige zunächst für ein paar Fahrzyklen an bis bestätigt werden kann, dass das System in Ordnung ist.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"FuelCapInspectionShrt": "Tankdeckel Verschlusskontrolle",
	"HBCLDWSSysErrorLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)  Fehlfunktion. \n Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorShrt": "HBC/LDWS-  Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_2": "HBC/LAS Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_3": "ALH/LDWS Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_4": "ALH/LAS Systemfehlfunktion",
	"HBCLDWSWindshieldFogLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)  Fehlfunktion. Enteisen Sie die Windschutzscheibe.\n Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogShrt": "HBC/LDWS-  Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_2": "HBC/LAS Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_3": "ALH/LDWS Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_4": "ALH/LAS Systemfehlfunktion",
	"HBCLLDWSCamDisconnectLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS)  Fehlfunktion. \nReinigen Sie die  Windschutzscheibe.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectShrt": "HBC/LDWS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_2": "HBC/LAS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_3": "ALH/LDWS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_4": "ALH/LAS Kamerafehlfunktion",
	"HBCSysErrorLong": "High Beam Control (HBC) Fehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"HBCSysErrorLong_2": "Adaptive LED Headlights (ALH) Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"HBCSysErrorShrt": "HBC-Fehlfunktion",
	"HBCSysErrorShrt_2": "ALH Fehlfunktion",
	"HeadlightSystemErrorLongJ03": "Eine Fehlfunktion ist im Scheinwerfersystem aufgetreten. Falls die Warnleuchte kontinuierlich blinkt, konsultieren Sie Ihren Mazda-Händler.",
	"HybrdSysMalHighPrt": "Hybrid-Systemstörung. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"HybridSysErrorLong": "Hybridsystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"HybridSysErrorShrt": "Hybrid-Systemstörung",
	"HybridSysOverheatLong": "Hybridsystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"HybridSysOverheatShrt": "Hybridsystemüberhitzung",
	"IeloopChrgHighPrt": "i‑ELOOP-Ladevorg. Bitte b. laufend. Motor prüfen, ob Ladevorg. abgeschlossen u. Warnanzeige ausgeschaltet ist.",
	"IstopSysErrorLong": "i‑stop-Betrieb ist nicht möglich.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"IstopSysErrorShrt": "i‑stop-Systemfehlfunktion",
	"KeylesSysErrorLong": "Schlüssellos Zugangssystem Fehlunktion \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"KeylesSysErrorShrt": "Fehler b. schlüssellosem Zugangssystem",
	"LDWSSysErrorLong": "Lane Departure Warning System (LDWS) Fehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"LDWSSysErrorLong_2": "Lane-keep Assist System (LAS) Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen",
	"LDWSSysErrorShrt": "LDWS-Fehlfunktion",
	"LDWSSysErrorShrt_2": "LAS Fehlfunktion",
	"LowBrakeFluidLong": "Der Bremsflüssigkeitsstand ist niedrig. \nDas Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"LowBrakeFluidShrt": "Niedriger Bremsflüssigkeitsstand",
	"LowFuelLong": "Die Kraftstoffanzeige ist niedrig. \nDas Fahrzeug bald tanken.\n",
	"LowFuelShrt": "Niedriger Kraftstoffstand",
	"LowTireAirPressureFlatLong": "Falls sich der Reifendruck extrem verringert, nachdem die TPMS-Warnleuchte aufleuchtete oder falls ein Reifen beschädigt ist, leuchtet auch die Reifenpannen-Warnleuchte  auf. Falls ein Runflat-Reifen beschädigt ist, fahren Sie das Fahrzeug vorsichtig zum nächstliegenden Mazda-Händler und lassen Sie den Reifen wechseln.",
	"LowTireAirPressureLong": "Geringer Reifenluftdruck in einem oder mehreren Reifen. \nDen Luftdruck der Reifen prüfen und auf den richtigen Luftdruck einstellen. Drücken Sie nach dem Einstellen des Reifendrucks den TPMS SET Schalter, bis Sie einen Piepston hören.",
	"LowTireAirPressureShrt": "Geringer Reifendruck",
	"LowWasheFluidLong": "Der Waschflüssigkeitsstand ist gering. \nFüllen Sie die Waschflüssigkeit auf.\n",
	"LowWasheFluidShrt": "Niedr. Scheibenrein.-Flüssigkeit",
	"MRCCSysErrorLong": "Fehlfunktion Mazda Radar Cruise Control (MRCC). Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"MRCCSysErrorShrt": "MRCC-Fehlfunktion",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) momentan nicht verfügbar.",
	"MRCCUnavailableShrt": "MRCC nicht verfügbar",
	"NoWarnings": "Keine Warnmeldungen gefunden",
	"PowerSteeringSysErrorLong": "Servolenkung-Fehlfunktion \nHalten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab.  Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"PowerSteeringSysErrorShrt": "Servolenkung SystemFehlfunktion",
	"PpositionRequestLong": "Stellen Sie den Schalthebel auf Parken. \nDies hat eine der folgenden Ursachen: \n・ Das Batteriesystem wurde mit einer anderen Schalthebel-Position als P gestartet oder gestoppt.\n・Die Fahrerseitentür wurde mit der Schalthebel-Position  N, D oder B geöffnet.\n ・ Die verbleibende Batterieladung ist abgefallen, weil die Schalthebel-Position eine lange Zeit auf Neutral stand. Starten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu. ",
	"PpositionRequestShrt": "Parkpositionsanfrage",
	"PreheatingDispLampLong": "Vorglühen. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"PreheatingDispLampShrt": "Vorglühen",
	"RoadSurfaceIcingCautionLong": "Die Außentemperatur beträgt 4°C oder weniger. \nAchten Sie beim Fahren auf vereiste Straßen.",
	"RoadSurfaceIcingCautionShrt": "Vorsicht: Vereisung d. Straßenbel.",
	"RvmSysErrorLong": "Im RVM-System ist ein Fehler aufgetreten.\nÜberprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung  oder falls mit Schnee bedeckt.\nLassen Sie Ihr Fahrzeug von einem Mazda-Händler überprüfen, wenn dieses Warnlicht nicht ausgeht.\n",
	"RvmSysErrorShrt": "RVM-Fehlfunktion",
	"SBSBrakeMRCCUnavailableLong": "SBS-Bremsen/MRCC momentan nicht verfügbar.",
	"SBSBrakeMRCCUnavailableShrt": "SBS/MRCC nicht verfügbar",
	"SBSBrakeUnavailableLong": "SBS-Bremsen momentan nicht verfügbar.",
	"SBSBrakeUnavailableShrt": "SBS nicht verfügbar",
	"SBSMRCCDRSSRadarSoilingLong": "Das SBS/MRCC/DRSS-Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radar (Sensors).",
	"SBSMRCCDRSSRadarSoilingShrt": "SBS/MRCC/DRSS-Radarfehler",
	"SBSMRCCRadarSoilingLong": "Das SBS/MRCC Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radar (Sensors).",
	"SBSMRCCRadarSoilingShrt": "SBS/MRCC -Radarfehlfunktion",
	"SBSSysErrorLong": "Im SBS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"SBSSysErrorShrt": "SBS-Fehlfunktion",
	"SCBSSysErrorLong": "Smart City Brake Support (SCBS) Fehlfunktion. \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"SCBSSysErrorShrt": "SCBS-Fehlfunktion",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) momentan nicht verfügbar.",
	"SCBSUnavailableShrt": "SCBS nicht verfügbar",
	"SCBSWindshieldSoilingLong": "Smart City Brake Support (SCBS) Fehlfunktion. \nReinigen Sie die  Windschutzscheibe.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SCBSWindshieldSoilingShrt": "SCBS-Fehlfunktion",
	"SedimenterWarningLong": "Die Menge des im Sedimenter angesammelten Wassers übersteigt den kalkulierten Wert. \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SedimenterWarningShrt": "Sediment. Inspektion",
	"SystemInspectionLong": "Die Differentialöl-Temperatur ist ungewöhnlich hoch oder ein großer Rotations-Unterschied ist in den Vorder- und Hinterreifen aufgetreten (z. B. beim Versuch aus Schlamm herauszufahren). \nDas Fahrzeug an einer sicheren Stelle anhalten und erst weiterfahren, nachdem die Warnanzeige ausgegangen ist. Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SystemInspectionShrt": "4WD-System Inspektion",
	"TpmsSysErrorLong": "Fehlfunktion des Reifendrucküberwachungs-Systems (TPMS) \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"TpmsSysErrorShrt": "Fehlfunktion TPMS-System",
	"VehicleSysErrorLong": "Fahrzeug Systemfehler \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"VehicleSysErrorShrt": "Fahrzeug Systemfehlfunktion",
	"WarningGuidance": "Warnmeldung",
	"WarningSafetyMessage": "Aus Sicherheitsgründen wird die Warnmeldung nicht agezeigt",
	"Warnings": "Warnmeldungen",
	"brakeFluid": "Bremsflüssigkeitsstand niedrig",
	"engineOilPressure": "Motoröldruck",
	"highVoltage": "Hochspannungsbatterie schwach",
	"lowBattStartEngine": "Batterie fast leer! Motor anlassen!",
};

framework.registerAppDictLoaded("warnguide", "de_DE");