var Localization_warnguideAppDict_pl_PL = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Usterka układu zapobiegającego blokowaniu kół (ABS). \nOddaj natychmiast pojazd do kontroli do serwisu.",
	"AbsSysErrorShrt": "Usterka układu ABS",
	"AbsSystemErrorLong": "Usterka układu zapobiegającego blokowaniu kół (ABS). Oddaj natychmiast pojazd do kontroli do serwisu.",
	"AbsSystemErrorShrt": "Usterka układu ABS",
	"AccumulationDpfLong": "Ilość sadzy nagromadzonej w filtrze cząstek stałych (DPF) przekroczyła wartość graniczną. \nJedź przez około od 10 do 15 minut z rozgrzanym silnikiem (niebieski wskaźnik temperatury nie świeci) z prędkością 15 km/godz. lub wyższą, aby pozbyć się cząstek stałych. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"AccumulationDpfShrt": "Nagromadzenie sadzy w filtrze cząstek stałych (DPF)",
	"ActiveBonnetSystemMalfunctionLong": "Usterka systemu Active Bonnet.\nJeśli ten wskaźnik pozostaje włączony lub miga, oddaj samochód do serwisu.",
	"ActiveBonnetSystemMalfunctionShrt": "Usterka systemu Active Bonnet",
	"AfsSystemErrorLong": "Usterka układu adaptacyjnego doświetlania zakrętów (AFS). Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik ciągle miga.",
	"AfsSystemErrorShrt": "Usterka układu AFS",
	"AirbagSysPretensionerSysErrorLong": "Usterka poduszki powietrznej lub pasa bezpieczeństwa. \nOddaj natychmiast pojazd do kontroli do serwisu.",
	"AirbagSysPretensionerSysErrorShrt": "Awaria poduszek\\napinaczów pasów bezpieczeństwa",
	"AutoLevelSystemErrorLong": "Usterka układu automatycznego poziomowania reflektorów. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"AutoLevelSystemErrorShrt": "Usterka układu autom. poziomowania reflektorów",
	"AutoLevelSystemErrorShrtJ03": "Usterka układu świateł przednich",
	"AutoTransSysErrorLong": "Usterka automatycznej skrzyni biegów. \nKontynuowanie jazdy może spowodować uszkodzenia pojazdu. Oddaj natychmiast pojazd do kontroli do serwisu. ",
	"AutoTransSysErrorShrt": "Usterka aut. skrzyni biegów",
	"AuxBattLowLong": "Stan akumulatora 12 V  jest niski.\n・Jeśli ten wskaźnik świeci często podczas jazdy, może to oznaczać, że sprawność akumulatora jest obniżona. Oddaj pojazd do kontroli do serwisu.\n・Jeśli ten wskaźnik świeci ciągle i się nie wyłącza akumulator 12 V jest wyczerpany. Przed uruchomieniem układu hybrydowego zapoznaj się z instrukcją obsługi i oddaj pojazd do kontroli do serwisu.",
	"AuxBattLowShrt": "Niski stan akumulatora 12 V",
	"BattManagSysErrorLong": "Usterka układu sterowania akumulatorem. \nOddaj pojazd do kontroli do serwisu.",
	"BattManagSysErrorShrt": "Usterka systemu ster. Akumulatorem",
	"BrakOverrideSysErrorLong": "Usterka włącznika pedału hamulca. \nOddaj natychmiast pojazd do kontroli do serwisu.",
	"BrakOverrideSysErrorShrt": "Usterka układu wyboru ham.",
	"BrakeSysErrorLong": "Niski poziom płynu hamulcowego lub usterka układu hamulcowego. Zatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"BrakeSysErrorShrt": "Usterka układu hamulcowego",
	"BrakeSystemErrorLong": "Usterka elektronicznie sterowanego układu hamulcowego. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"BrakeSystemErrorShrt": "Usterka układu hamulcowego",
	"BsmSystemErrorLong": "Usterka układu Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA). \nSprawdź powierzchnię tylnego zderzaka i wyczyść go, jeśli jest zabrudzony lub pokryty śniegiem. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"BsmSystemErrorShrt": "Usterka układu BSM",
	"ChargSysMalHighPrt": "Awaria układu ładowania. Zatrzymaj się natychmiast w bezpiecznym miejscu.",
	"ChargingSysErrorLong": "Usterka układu ładowania akumulatora. \nKontynuowanie jazdy może spowodować uszkodzenia pojazdu. Zatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"ChargingSysErrorShrt": "Usterka układu ładowania",
	"ChrgSysErrorLong": "Usterka układu ładowania akumulatora. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"ChrgSysErrorShrt": "Usterka układu ładowania",
	"ControlSystemErrorLong": "Usterka układu kontroli pozycji parkowania. \nJeśli układ nie zostanie skontrolowany, może dojść do jednej z następujących sytuacji: \n・Mechanizm blokady hamulca postojowego może nie działać. Zaparkuj pojazd na płaskim podłożu i mocno zaciągnij hamulec postojowy. \n・Wyłącznik może nie rozłączać. Kilkakrotnie naciśnij wyłącznik, aby wyłączyć. \n・Komunikat \"Zaciągnij hamulec postojowy podczas parkowania\" nie będzie wyświetlany podczas jazdy i na postoju. \nOddaj natychmiast pojazd do kontroli do serwisu.\n",
	"ControlSystemErrorShrt": "Awaria czujników parkowania",
	"DPFErrorLong": "Usterka filtra cząstek stałych (DPF). \nOddaj pojazd do kontroli do serwisu.",
	"DPFErrorShrt": "Błąd filtra cząstek stałych (DPF)",
	"DRSSSysErrorLong": "Błąd w systemie DRSS. \nOddaj pojazd do kontroli do autoryzowanego serwisu Mazda.\n",
	"DRSSSysErrorShrt": "Usterka układu DRSS",
	"DriveBattDropLong": "Prąd resztkowy w akumulatorze wysokonapięciowym jest bliski wyczerpania, ponieważ dźwignia zmiany biegów przez długi czas była w pozycji Neutralnej.\nGdy dźwignia skrzyni biegów jest w pozycji Neutralnej, ładowanie akumulatora nie jest możliwe. W przypadku długiego postoju przełącz dźwignię zmiany biegów w pozycję Parkowanie. \nPonownie uruchom układ hybrydowy, naciskając włącznik zasilania w razie potrzeby.\n",
	"DriveBattDropShrt": "Niski stan naładowania akumulatora wysokiego napięcia",
	"DropKeyBattChrgLong": "Rozładowana bateria w kluczyku. Wymień natychmiast baterię w kluczyku.",
	"DropKeyBattChrgShrt": "Rozładowana bateria kluczyka",
	"DscSysErrorLong": "Usterka układu Dynamic Stability Control (DSC), Traction Control System (TCS) lub Hill Launch Assist (HLA). Oddaj natychmiast pojazd do kontroli do serwisu. ",
	"DscSysErrorShrt": "Usterka układu DSC",
	"DscSystemErrorLong": "Usterka układu dynamicznej kontroli stabilności toru jazdy (DSC) lub kontroli trakcji (TCS). Oddaj natychmiast pojazd do kontroli do serwisu.",
	"DscSystemErrorShrt": "Usterka układu DSC",
	"EcbSysErrorLong": "Usterka układu odzysku energii podczas hamowania lub elektronicznie sterowanego układu hamulcowego. Zatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"EcbSysErrorShrt": "Usterka układu hamulcowego",
	"ElectricParkingBrakeHighLong": "Wystąpiła usterka w układzie hamulca postojowego. Skontaktuj się z dealerem Mazda, by sprawdzić usterkę.",
	"ElectricParkingBrakeLong": "Wystąpiła usterka w układzie hamulca postojowego. Skontaktuj się z dealerem Mazda, by sprawdzić usterkę.",
	"ElectricParkingBrakeShrt": "Usterka układu hamulca postojowego",
	"ElectricVacuumPumpSystemMalfunctionLong": "Wystąpiła usterka w układzie elektrycznej pompy próżniowej. Zlekceważenie tego błędu może doprowadzić do awarii układu, co spowoduje nieoczekiwane zagrożenie lub nieprawidłowe działanie. Natychmiast skontaktuj się z dealerem Mazda w celu sprawdzenia błędu. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Usterka układu elektrycznej pompy próżniowej",
	"EloopChargingLong": "Trwa ładowanie układu i‑ELOOP. \nPrzy uruchomionym silniku poczekaj na zakończenie ładowania i zgaśniecie wskaźnika. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"EloopChargingShrt": "Ładowanie i‑ELOOP",
	"EloopSysErrorLong": "Usterka układu i‑ELOOP. \nOddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"EloopSysErrorShrt": "Usterka układu i‑ELOOP",
	"EngCoolntTempHighOnLong": "Przegrzanie silnika. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu, zgaś silnik i wykonaj odpowiednie działania. Zapoznaj się z instrukcją obsługi pojazdu.\n",
	"EngCoolntTempHighOnShrt": "Wysoka temperatura płynu chłodzącego silnika",
	"EngOilPressureErrorLong": "Niskie ciśnienie oleju silnikowego. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu, zgaś silnik i sprawdź poziom oleju silnikowego. Uzupełnij olej w razie potrzeby. \nOddaj natychmiast pojazd do kontroli do serwisu, jeśli wskaźnik zaświeci po uzupełnieniu oleju lub gdy poziom oleju silnikowego jest prawidłowy.\n",
	"EngOilPressureErrorShrt": "Niskie ciśnienie oleju silnikowego",
	"EngSystemErrorLong": "Usterka układu sterowania silnikiem. Oddaj natychmiast pojazd do kontroli do serwisu.",
	"EngSystemErrorShrt": "Usterka układu sterowania silnikiem",
	"EngineOilPressureErrorLong": "Niskie ciśnienie oleju silnikowego. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu, zgaś silnik i sprawdź poziom oleju silnikowego. Uzupełnij olej w razie potrzeby. \nOddaj natychmiast pojazd do kontroli do serwisu, jeśli wskaźnik zaświeci po uzupełnieniu oleju lub gdy poziom oleju silnikowego jest prawidłowy.\n",
	"EngineOilPressureErrorShrt": "Niskie ciśnienie oleju silnikowego",
	"EngineWaterTempDropLong": "Płyn chłodzący silnika jest zimny, nie można ogrzać powietrza za pomocą nagrzewnicy. Pojazd można prowadzić, niezależnie od tego, czy wskaźnik świeci, czy nie. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"EngineWaterTempDropShrt": "Niska temperatura płynu chłodzącego silnika",
	"EngineWaterTempRiseLong": "Silnik przegrzewa się. \nJedź powoli lub zatrzymaj pojazd, aż wskaźnik przestanie migać. Jeśli mimo zatrzymania pojazdu wskaźnik nadal będzie migał, wykonaj odpowiednie działania. Zapoznaj się z instrukcją obsługi pojazdu.\n",
	"EngineWaterTempRiseShrt": "Wysoka temperatura płynu chłodzącego silnika",
	"EngnCoolTempHighHighPrt": "Wysoka temperatura płynu chłodzącego. Zatrzymaj się natychmiast w bezpiecznym miejscu.",
	"FOWMRCCDRSSRadarSoilingLong": "Radar (czujnik) układu FOW/MRCC/DRSS jest zabrudzony. \nWyczyść całą powierzchnię emblematu Mazda na atrapie chłodnicy.\n",
	"FOWMRCCDRSSRadarSoilingShrt": "Usterka radaru układu FOW/MRCC/DRSS",
	"FOWMRCCRadarSoilingLong": "Usterka radaru (czujnika) układu FOW/MRCC. Wyczyść całą powierzchnię znaku na osłonie chłodnicy, jeśli jest brudna lub pokryta śniegiem. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"FOWMRCCRadarSoilingShrt": "Usterka radaru układu FOW/MRCC",
	"FOWSysError": "Usterka układu FOW",
	"FOWSysErrorLong": "Usterka układu Forward Obstruction Warning (FOW). Oddaj pojazd do kontroli do serwisu.",
	"FWDSysErrorLong": "Usterka układu napędu na cztery koła lub na przedniej i tylnej osi zamontowano koła o różnych rozmiarach. \nOddaj pojazd do kontroli do serwisu.",
	"FWDSysErrorShrt": "Usterka napędu 4x4",
	"FuelAirFilterCartReplacePeriodLong": "Wymagana jest wymiana wkładu filtra paliwa i filtra powietrza.",
	"FuelAirFilterCartReplacePeriodShrt": "Wymagana wymiana filtra paliwa i filtra powietrza",
	"FuelCapInspectionLong": "Korek wlewu paliwa może być założony nieprawidłowo. \nSprawdź, czy korek wlewu paliwa został prawidłowo założony i dokręcony. \nPo prawidłowym założeniu i dokręceniu korka wlewu paliwa wskaźnik przestanie świecić dopiero po kilku jazdach, gdy będzie można potwierdzić, że system działa prawidłowo. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"FuelCapInspectionShrt": "Kontrola korka wlewu paliwa",
	"HBCLDWSSysErrorLong": "Usterka układu High Beam Control (HBC)/Lane Departure Warning System (LDWS). Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"HBCLDWSSysErrorLong_2": "Błędne działanie High Beam Control (HBC)/Lane-keep Assist System (LAS). Pojazd musi być sprawdzony przez sprzedawcę, jeżeli ten wskaźnik świeci. ",
	"HBCLDWSSysErrorLong_3": "Błędne działanie Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Pojazd musi być sprawdzony przez sprzedawcę, jeżeli ten wskaźnik świeci.",
	"HBCLDWSSysErrorLong_4": "Błędne działanie Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Pojazd musi być sprawdzony przez sprzedawcę, jeżeli ten wskaźnik świeci.",
	"HBCLDWSSysErrorShrt": "Usterka układu HBC/LDWS",
	"HBCLDWSSysErrorShrt_2": "Usterka systemu HBC/LAS",
	"HBCLDWSSysErrorShrt_3": "Usterka systemu ALH/LDWS",
	"HBCLDWSSysErrorShrt_4": "Usterka systemu ALH/LAS",
	"HBCLDWSWindshieldFogLong": "Usterka układu High Beam Control (HBC)/Lane Departure Warning System (LDWS). \nOdszroń przednią szybę. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"HBCLDWSWindshieldFogLong_2": "Błędne działanie High Beam Control (HBC)/Lane-keep Assist System (LAS). Należy odmrozić przednią szybę.   Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"HBCLDWSWindshieldFogLong_3": "Błędne działanie Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Należy odmrozić przednią szybę.  Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"HBCLDWSWindshieldFogLong_4": "Błędne działanie Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Należy odmrozić przednią szybę.  Pojazd musi być sprawdzony przez sprzedawcę, jeżeli ten wskaźnik świeci.",
	"HBCLDWSWindshieldFogShrt": "Usterka układu HBC/LDWS",
	"HBCLDWSWindshieldFogShrt_2": "Błędne działanie HBC/LAS System",
	"HBCLDWSWindshieldFogShrt_3": "Usterka systemu ALH/LDWS",
	"HBCLDWSWindshieldFogShrt_4": "Usterka systemu ALH/LAS",
	"HBCLLDWSCamDisconnectLong": "Usterka układu High Beam Control (HBC)/Lane Departure Warning System (LDWS). Wyczyść przednią szybę. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"HBCLLDWSCamDisconnectLong_2": "Błędne działanie High Beam Control (HBC)/Lane-keep Assist System (LAS). Należy wyczyścić przednią szybę. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"HBCLLDWSCamDisconnectLong_3": "Błędne działanie Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Należy wyczyścić przednią szybę. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"HBCLLDWSCamDisconnectLong_4": "Błędne działanie Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Należy wyczyścić przednią szybę.  Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"HBCLLDWSCamDisconnectShrt": "Usterka kamery układu HBC/LDWS",
	"HBCLLDWSCamDisconnectShrt_2": "Usterka kamery układu HBC/LAS ",
	"HBCLLDWSCamDisconnectShrt_3": "Usterka kamery układu ALH/LDWS",
	"HBCLLDWSCamDisconnectShrt_4": "Usterka kamery układu ALH/LAS",
	"HBCSysErrorLong": "Usterka układu High Beam Control (HBC). Oddaj pojazd do kontroli do serwisu.",
	"HBCSysErrorLong_2": "Błędne działanie Adaptive LED Headlights (ALH). Oddaj pojazd do kontroli do serwisu.",
	"HBCSysErrorShrt": "Usterka układu HBC",
	"HBCSysErrorShrt_2": "Błędne działanie ALH",
	"HeadlightSystemErrorLongJ03": "Wystąpiła usterka w układzie świateł przednich. Jeśli lampka ostrzegawcza ciągle miga, skontaktuj się z dealerem Mazda.",
	"HybrdSysMalHighPrt": "Awaria układu hybrydowego. Zatrzymaj się natychmiast w bezpiecznym miejscu.",
	"HybridSysErrorLong": "Usterka układu hybrydowego. \nKontynuowanie jazdy może spowodować uszkodzenia pojazdu. Zatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"HybridSysErrorShrt": "Awaria układu hybrydowego",
	"HybridSysOverheatLong": "Usterka układu hybrydowego. \nKontynuowanie jazdy może spowodować uszkodzenia pojazdu. Zatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"HybridSysOverheatShrt": "Przegrzewanie układu hybrydowego",
	"IeloopChrgHighPrt": "Ładowanie uk. i‑ELOOP. Przy pracującym silniku sprawdź, czy ładowanie jest zakończone i czy zgasła kontrolka.",
	"IstopSysErrorLong": "System i‑stop jest niedostępny. Oddaj pojazd do kontroli do autoryzowanego serwisu Mazda.",
	"IstopSysErrorShrt": "Usterka systemu i‑stop",
	"KeylesSysErrorLong": "Usterka systemu dostępu bez kluczyka. Oddaj pojazd do kontroli do serwisu.",
	"KeylesSysErrorShrt": "Usterka systemu dostępu bez kluczyka",
	"LDWSSysErrorLong": "Usterka układu Lane Departure Warning System (LDWS). Oddaj pojazd do kontroli do serwisu.",
	"LDWSSysErrorLong_2": "Błędne działanie Lane-keep Assist System (LAS). Pojazd musi być sprawdzony przez sprzedawcę.",
	"LDWSSysErrorShrt": "Usterka układu LDWS",
	"LDWSSysErrorShrt_2": "Błędne działanie LAS",
	"LowBrakeFluidLong": "Niski poziom płynu hamulcowego. \nZatrzymaj natychmiast pojazd w bezpiecznym miejscu i oddaj go do kontroli do serwisu.",
	"LowBrakeFluidShrt": "Niski poziom płynu hamulcow.",
	"LowFuelLong": "Niski poziom paliwa w zbiorniku. Uzupełnij jak najszybciej paliwo.",
	"LowFuelShrt": "Niski poziom paliwa",
	"LowTireAirPressureFlatLong": "Jeśli ciśnienie w oponie znacznie spadnie po zaświeceniu się lampki ostrzegawczej TPMS lub przebiciu opony, zaświeci się także lampka ostrzegawcza przebitej opony. W razie przebicia opony typu run-flat powoli udaj się z pojazdem do najbliższego dealera Mazda, by wymienić oponę.",
	"LowTireAirPressureLong": "Niski poziom ciśnienia powietrza w co najmniej jednej oponie. \nSprawdź ciśnienie powietrza w oponach i ustaw poprawny poziom ciśnienia. Po ustawieniu ciśnienia powietrza naciśnij przełącznik TPMS SET, aż wyemitowany zostanie sygnał dźwiękowy.",
	"LowTireAirPressureShrt": "Niskie ciśnienie powietrza w oponie",
	"LowWasheFluidLong": "Niski poziom płynu spryskiwaczy. Uzupełnij płyn spryskiwaczy.",
	"LowWasheFluidShrt": "Niski poziom płynu spryskiwaczy",
	"MRCCSysErrorLong": "Usterka Mazda Radar Cruise Control (MRCC). Oddaj pojazd do kontroli do serwisu.",
	"MRCCSysErrorShrt": "Usterka tempomatu MRCC",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) jest aktualnie niedostępny.",
	"MRCCUnavailableShrt": "Tempomat MRCC niedostępny",
	"NoWarnings": "Nie znaleziono ostrzeżeń",
	"PowerSteeringSysErrorLong": "Usterka elektrycznego wspomagania układu kierowniczego. Zatrzymaj pojazd w bezpiecznym miejscu i zgaś silnik. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"PowerSteeringSysErrorShrt": "Usterka wspom. układu kierown.",
	"PpositionRequestLong": "Przełącz dźwignię skrzyni biegów w pozycję Parkowanie. \nKomunikat jest wyświetlany w następujących sytuacjach: \n・ Układ akumulatora został uruchomiony lub zatrzymany, gdy dźwignia skrzyni biegów znajdowała się w pozycji innej niż Parkowanie.\n・ Drzwi po stronie kierowcy były otwarte, gdy dźwignia skrzyni biegów znajdowała się w pozycji N, D lub B.\n・Naładowanie akumulatora wysokonapięciowego prądem resztkowym nie było możliwe, ponieważ dźwignia skrzyni biegów przez długi czas była w pozycji Neutralna.\nPonownie uruchom układ hybrydowy, naciskając wyłącznik w razie potrzeby.\n",
	"PpositionRequestShrt": "Żądanie pozycji parkowania",
	"PreheatingDispLampLong": "Świece żarowe się nagrzewają. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"PreheatingDispLampShrt": "Nagrzewanie świec żarowych",
	"RoadSurfaceIcingCautionLong": "Temperatura otoczenia jest równa lub niższa niż 4°C. \nOstrożnie, drogi mogą być oblodzone!",
	"RoadSurfaceIcingCautionShrt": "Ostrzeżenie o oblodzeniu na drodze",
	"RvmSysErrorLong": "Usterka układu RVM (Monitorowania tyłu pojazdu). Sprawdź powierzchnię tylnego zderzaka i wyczyść go, jeśli jest zabrudzony lub pokryty śniegiem. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"RvmSysErrorShrt": "Usterka układu RVM",
	"SBSBrakeMRCCUnavailableLong": "Układ SBS/MRCC jest aktualnie niedostępny.",
	"SBSBrakeMRCCUnavailableShrt": "Układ SBS/MRCC niedostępny",
	"SBSBrakeUnavailableLong": "Układ SBS jest aktualnie niedostępny.",
	"SBSBrakeUnavailableShrt": "Układ SBS niedostępny",
	"SBSMRCCDRSSRadarSoilingLong": "Radar (czujnik) układu SBS/MRCC/DRSS jest zabrudzony. \nWyczyść całą powierzchnię emblematu Mazda na atrapie chłodnicy.\n",
	"SBSMRCCDRSSRadarSoilingShrt": "Usterka radaru układu SBS/MRCC/DRSS",
	"SBSMRCCRadarSoilingLong": "Radar (czujnik) układu SBS/MRCC jest zabrudzony. \nWyczyść całą powierzchnię emblematu Mazda na atrapie chłodnicy.\n",
	"SBSMRCCRadarSoilingShrt": "Usterka radaru układu SBS/MRCC",
	"SBSSysErrorLong": "Błąd w systemie SBS. \nOddaj pojazd do kontroli do autoryzowanego serwisu Mazda.\n",
	"SBSSysErrorShrt": "Usterka układu SBS",
	"SCBSSysErrorLong": "Usterka układu Smart City Brake Support (SCBS). Oddaj natychmiast pojazd do kontroli do serwisu.",
	"SCBSSysErrorShrt": "Usterka układu SCBS",
	"SCBSUnavailableLong": "Układ Smart City Brake Support (SCBS) jest aktualnie niedostępny.",
	"SCBSUnavailableShrt": "Układ SCBS niedostępny",
	"SCBSWindshieldSoilingLong": "Usterka układu Smart City Brake Support (SCBS). Wyczyść przednią szybę. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"SCBSWindshieldSoilingShrt": "Usterka układu SCBS",
	"SedimenterWarningLong": "Poziom wody w osadniku przekracza dopuszczalną wartość. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.",
	"SedimenterWarningShrt": "Kontrola osadnika wody",
	"SystemInspectionLong": "Temperatura oleju w mechanizmie różnicowym jest nadmiernie wysoka lub wystąpiła duża różnica prędkości obrotowej kół przedniej i tylnej osi, np. podczas wyjeżdżania z błota. \nZatrzymaj pojazd w bezpiecznym miejscu i kontynuuj jazdę, gdy wskaźnik ostrzegawczy przestanie świecić. Oddaj pojazd do kontroli do serwisu, jeśli wskaźnik świeci ciągle.\n",
	"SystemInspectionShrt": "Kontrola napędu 4x4",
	"TpmsSysErrorLong": "Usterka układu monitorowania ciśnienia w oponach (TPMS). \nOddaj pojazd do kontroli do serwisu.",
	"TpmsSysErrorShrt": "Usterka systemu TPMS",
	"VehicleSysErrorLong": "Usterka układu pojazdu. \nOddaj pojazd do kontroli do serwisu.",
	"VehicleSysErrorShrt": "Usterka układu pojazdu",
	"WarningGuidance": "Ostrzeżenie",
	"WarningSafetyMessage": "Ze względu na bezpieczeństwo wskazówka ostrzegawcza nie jest wyświetlana.",
	"Warnings": "Lista ostrzeżeń",
	"brakeFluid": "Niski poziom płynu hamulcowego",
	"engineOilPressure": "Ciśnienie oleju silnikowego",
	"highVoltage": "Niskie napięcie akumulatora wysokonapięciowego",
	"lowBattStartEngine": "Niskie napięcie akumulatora! Włącz silnik!",
};

framework.registerAppDictLoaded("warnguide", "pl_PL");