var Localization_warnguideAppDict_et_EE = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Blokeerumisvastase pidurisüsteemi (ABS) rike. Laske sõidukit kohe esinduses kontrollida.",
	"AbsSysErrorShrt": "ABS-rike",
	"AbsSystemErrorLong": "Blokeerumisvastase pidurisüsteemi (ABS) rike. Laske sõidukit kohe esinduses kontrollida.",
	"AbsSystemErrorShrt": "ABS-rike",
	"AccumulationDpfLong": "Kübemefiltrisse (DPF) kogunenud osakesed (PM) ületavad lubatud kogust. Sõitke osakeste kõrvaldamiseks umbes 10 kuni 15 minutit täiesti soojenenud mootoriga (sinine temperatuuri tuli kustunud) kiirusega 10 mph (15 km/h) või enam. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"AccumulationDpfShrt": "Kübemefiltri (DPF) ummistumine",
	"ActiveBonnetSystemMalfunctionLong": "Active Bonnet süsteemi rike.\nKui indikaator jääb põlema või vilgub pidevalt, siis laske sõidukit teeninduses kontrollida.",
	"ActiveBonnetSystemMalfunctionShrt": "Active Bonnet süsteemi rike",
	"AfsSystemErrorLong": "Kohanduva esitulede süsteemi (AFS) rike.  Kui see indikaator vilgub jätkuvalt, siis laske sõidukit esinduses kontrollida.",
	"AfsSystemErrorShrt": "AFS-rike",
	"AirbagSysPretensionerSysErrorLong": "Turvapadja/turvavöö rike. Laske sõidukit kohe esinduses kontrollida",
	"AirbagSysPretensionerSysErrorShrt": "Turvapadja-/eelpingutisüst. rike",
	"AutoLevelSystemErrorLong": "Esitulede automaatse reguleerimissüsteemi rike. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"AutoLevelSystemErrorShrt": "Automaatse reguleerimissüst. rike",
	"AutoLevelSystemErrorShrtJ03": "Esitulede süsteemi talitlushäire",
	"AutoTransSysErrorLong": "Automaatkäigukasti rike. Sõitmist jätkates võite sõidukit kahjustada.  Laske sõidukit kohe esinduses kontrollida. ",
	"AutoTransSysErrorShrt": "Automaatkäigukasti rike",
	"AuxBattLowLong": "12V aku hakkab tühjaks saama.・Kui see indikaator süttib sõidu ajal sageli, siis võib aku olla vananenud. Laske sõidukit esinduses kontrollida. ・Kui see põleb pidevalt ja ei lülitu välja, 12V aku on surnud.  Lugege enne hübriidsüsteemi käivitamist kasutusjuhendit ja laske sõidukit esinduses kontrollida.",
	"AuxBattLowShrt": "12 V Aku Madal",
	"BattManagSysErrorLong": "Aku juhtimissüsteemi rike. Laske sõidukit esinduses kontrollida.",
	"BattManagSysErrorShrt": "Aku juhtimissüsteemi rike",
	"BrakOverrideSysErrorLong": "Pidurilüliti rike. Laske sõidukit kohe esinduses kontrollida.",
	"BrakOverrideSysErrorShrt": "Piduri alistussüsteemi rike",
	"BrakeSysErrorLong": "Pidurivedeliku tase on madal või pidurisüsteemi rike. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"BrakeSysErrorShrt": "Pidurisüsteemi rike",
	"BrakeSystemErrorLong": "Elektroonilise juhtimisega pidurisüsteemi rike. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"BrakeSystemErrorShrt": "Pidurisüsteemi rike",
	"BsmSystemErrorLong": "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA) rike. Kontrollige tagastange pinna kõrvalekaldeid ja puhastage, kui see on määrdunud või lumega kaetud. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"BsmSystemErrorShrt": "BSM-rike",
	"ChargSysMalHighPrt": "Laadimissüsteemi rike. Peatage sõiduk kohe ohutus kohas.",
	"ChargingSysErrorLong": "Laadimissüsteemi rike.Sõitmist jätkates võite sõidukit kahjustada.  Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"ChargingSysErrorShrt": "Laadimissüsteemi rike",
	"ChrgSysErrorLong": "Laadimissüsteemi rike. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"ChrgSysErrorShrt": "Laadimissüsteemi rike",
	"ControlSystemErrorLong": "Parkimisasendi kontrollsüsteemi rike. Kontrollimata jätmine võib kaasa tuua mõne järgmistest olukordadest: ・Parkimisluku mehhanism ei pruugi töötada. Parkige tasasele pinnale ja rakendage käsipidur. ・Süütelüliti ei pruugi välja lülituda. Vajutage välja lülitamiseks korduvalt süütelülitit. ・ “Rakendage parkimisel seisupidur” kuva lülitub sõidu ajal välja ja seiskumise ajal sisse. Laske sõidukit kohe esinduses kontrollida.",
	"ControlSystemErrorShrt": "Parkimisasendi kontrollsüst. rike",
	"DPFErrorLong": "Kübemefiltri (DPF) rike. Laske sõidukit esinduses kontrollida.",
	"DPFErrorShrt": "DPF-i viga",
	"DRSSSysErrorLong": "DRSS-süsteemis on viga. Laske sõidukit Mazda esinduses kontrollida.",
	"DRSSSysErrorShrt": "DRSS-rike",
	"DriveBattDropLong": "Järelejäänud Power High Voltage aku on tühi, sest käigukast on neutraalasendis pikka aega. Laadimine pole neutraalasendis võimalik. Valige pikemal peatumisel parkimisasend. Taaskäivitage hübriidsüsteem, vajutades vajadusel toitelülitit.",
	"DriveBattDropShrt": "Kõrge Pinge Aku Madal",
	"DropKeyBattChrgLong": "Võtme patarei on tühi. Vahetage kohe võtme patarei.",
	"DropKeyBattChrgShrt": "Võtme patarei on tühi",
	"DscSysErrorLong": "Dynamic Stability Control (DSC), Traction Control System (TCS) või Hill Launch Assist (HLA) rike. Laske sõidukit kohe esinduses kontrollida.",
	"DscSysErrorShrt": "DSC-rike",
	"DscSystemErrorLong": "Dünaamilise stabiilsuskontrolli (DSC) või veojõu kontrollsüsteemi (TCS) rike. Laske sõidukit kohe esinduses kontrollida.",
	"DscSystemErrorShrt": "DSC-rike",
	"EcbSysErrorLong": "Regeneratiivne pidurdus või elektroonilise juhtimisega pidurisüsteemi rike. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"EcbSysErrorShrt": "Pidurisüsteemi rike",
	"ElectricParkingBrakeHighLong": "Seisupiduri süsteemis ilmnes talitlushäire. Vea kõrvaldamiseks pidage nõu oma Mazda edasimüüjaga.",
	"ElectricParkingBrakeLong": "Seisupiduri süsteemis ilmnes talitlushäire. Vea kõrvaldamiseks pidage nõu oma Mazda edasimüüjaga.",
	"ElectricParkingBrakeShrt": "Seisupiduri süsteemi talitlushäire",
	"ElectricVacuumPumpSystemMalfunctionLong": "Elektrilise vaakumpumba süsteemis ilmnes talitlushäire. Selle vea parandamata jätmine võib põhjustada süsteemi tõrget, mis tekitab ootamatuid ohuolukordi või talitlushäireid. Konsulteerige kohe oma Mazda edasimüüjaga ja laske vea põhjus välja selgitada. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Elektrilise vaakumpumba süsteemi talitlushäire",
	"EloopChargingLong": "i‑ELOOP laadimine. Kontrollige töötava mootoriga, kas laadimine on lõppenud ja hoiatuse indikaator on kustunud. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"EloopChargingShrt": "i‑ELOOP laadimine",
	"EloopSysErrorLong": "i‑ELOOP süsteemi rike. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"EloopSysErrorShrt": "i‑ELOOP süsteemi rike",
	"EngCoolntTempHighOnLong": "Mootor kuumeneb üle. Peatage sõiduk kohe ohutus kohas, lülitage mootor välja ja tehke vajalikud sammud.  Lugege kasutusjuhendit.",
	"EngCoolntTempHighOnShrt": "Mootori jahutustemp. on kõrge",
	"EngOilPressureErrorLong": "Mootori õlirõhk madal. Peatage sõiduk kohe ohutus kohas, lülitage mootor välja ja kontrollige mootori õlitaset. Lisage vajadusel õli. Kui see indikaator jääb pärast õli lisamist või õige õlitaseme korral põlema, siis laske sõidukit kohe esinduses kontrollida.",
	"EngOilPressureErrorShrt": "Mootori õlirõhk madal.",
	"EngSystemErrorLong": "Mootorisüsteemi rike.  Laske sõidukit kohe esinduses kontrollida.",
	"EngSystemErrorShrt": "Mootorisüsteemi rike",
	"EngineOilPressureErrorLong": "Mootori õlirõhk madal. Peatage sõiduk kohe ohutus kohas, lülitage mootor välja ja kontrollige mootori õlitaset. Lisage vajadusel õli. Kui see indikaator jääb pärast õli lisamist või õige õlitaseme korral põlema, siis laske sõidukit kohe esinduses kontrollida.",
	"EngineOilPressureErrorShrt": "Mootori õlirõhk madal.",
	"EngineWaterTempDropLong": "Mootori jahutusvedelik on külm ja soojenduse/sulatuse jaoks pole sooja õhku. Sõidukit saab juhtida, kui indikaator on sees või väljas.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"EngineWaterTempDropShrt": "Mootori jahutusv. temp madal",
	"EngineWaterTempRiseLong": "Mootor hakkab kuumenema. Sõitke aeglaselt või peatage sõiduk, kuni indikaator lõpetab vilkumise. Kui see jätkab pärast sõiduki seiskamist vilkumist, siis tehke vajalikud sammud. Lugege kasutusjuhendit.",
	"EngineWaterTempRiseShrt": "Mootori jahutustemp. on kõrge",
	"EngnCoolTempHighHighPrt": "Mootori jahutusvedeliku temperatuur on kõrge. Peatage sõiduk kohe ohutus kohas.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS radar (andur) on määrdunud. Puhastage kogu radari (anduri) pind.",
	"FOWMRCCDRSSRadarSoilingShrt": "FOW/MRCC/DRSS-radari rike",
	"FOWMRCCRadarSoilingLong": "FOW/MRCC radari (anduri) rike. Puhastage kogu eesmise iluvõre embleemi pind, kui see on must või lumega kaetud. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"FOWMRCCRadarSoilingShrt": "FOW/MRCC radari rike",
	"FOWSysError": "FOW-rike",
	"FOWSysErrorLong": "Forward Obstruction Warning (FOW) rike. Laske sõidukit esinduses kontrollida.",
	"FWDSysErrorLong": "4WD süsteemi tõrge või rehvisuurus on eesmistel ja tagumistel rehvidel erinev. Laske sõidukit esinduses kontrollida.",
	"FWDSysErrorShrt": "4WD süsteemi tõrge",
	"FuelAirFilterCartReplacePeriodLong": "Kütuse-õhu filtri element tuleb vahetada.",
	"FuelAirFilterCartReplacePeriodShrt": "Vahetage kütuse-õhufiltri element",
	"FuelCapInspectionLong": "Kütusepaagi kork ei pruugi olla korralikult paigaldatud. Kontrollige, kas kütusepaagi kork on korralikult paigaldatud ja kinni keeratud.\nPärast kütusepaagi korgi paigaldamist ja kinnikeeramist ei lülitu see indikaator mõne sõidutsükli vältel välja, kuni on kindel, et süsteem on korras.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"FuelCapInspectionShrt": "Kütusepaagi korgi ülevaatus",
	"HBCLDWSSysErrorLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) rike. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"HBCLDWSSysErrorLong_2": "High Beam Control-i (HBC)/Lane-keep Assist System-i (LAS) rike. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSSysErrorLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) rike. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSSysErrorLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) rike. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSSysErrorShrt": "HBC/LDWS-süsteemi rike",
	"HBCLDWSSysErrorShrt_2": "HBC/LAS süsteemi rike",
	"HBCLDWSSysErrorShrt_3": "ALH/LDWS süsteemi rike",
	"HBCLDWSSysErrorShrt_4": "ALH/LAS süsteemi rike",
	"HBCLDWSWindshieldFogLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) rike.\nSulatage esiklaasi.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.\n",
	"HBCLDWSWindshieldFogLong_2": "High Beam Control-i (HBC)/Lane-keep Assist System-i (LAS) rike. Sulatage esiklaasi. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSWindshieldFogLong_3": "Adaptive LED Headlights-i (ALH)/Lane Departure Warning System-i (LDWS) rike. Sulatage esiklaasi. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSWindshieldFogLong_4": "Adaptive LED Headlights-i (ALH)/Lane-keep Assist System-i (LAS) rike. Sulatage esiklaasi. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLDWSWindshieldFogShrt": "HBC/LDWS-süsteemi rike",
	"HBCLDWSWindshieldFogShrt_2": "HBC/LAS süsteemi rike",
	"HBCLDWSWindshieldFogShrt_3": "ALH/LDWS süsteemi rike",
	"HBCLDWSWindshieldFogShrt_4": "ALH/LAS süsteemi rike",
	"HBCLLDWSCamDisconnectLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) rike. Puhastage esiklaasi.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"HBCLLDWSCamDisconnectLong_2": "High Beam Control-i (HBC)/Lane-keep Assist System- (LAS) rike. Puhastage esiklaas. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLLDWSCamDisconnectLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) rike. Puhastage esiklaas. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLLDWSCamDisconnectLong_4": "Adaptive LED Headlights-i (ALH)/Lane-keep Assist System-i (LAS) rike. Puhastage esiklaas. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"HBCLLDWSCamDisconnectShrt": "HBC/LDWS kaamera rike",
	"HBCLLDWSCamDisconnectShrt_2": "HBC / LAS kaamera rike",
	"HBCLLDWSCamDisconnectShrt_3": "ALH/LDWS kaamera rike",
	"HBCLLDWSCamDisconnectShrt_4": "ALH/LAS kaamera rike",
	"HBCSysErrorLong": "High Beam Control (HBC) rike. Laske sõidukit esinduses kontrollida.",
	"HBCSysErrorLong_2": "Adaptive LED Headlights (ALH)",
	"HBCSysErrorShrt": "HBC-rike",
	"HBCSysErrorShrt_2": "ALH-i rike",
	"HeadlightSystemErrorLongJ03": "Esitulede süsteemis ilmnes talitlushäire. Kui hoiatuslamp vilgub pidevalt, pidage nõu oma Mazda edasimüüjaga.",
	"HybrdSysMalHighPrt": "Hübriidsüsteemi rike. Peatage sõiduk kohe ohutus kohas.",
	"HybridSysErrorLong": "Hübriidsüsteemi rike. Sõitmist jätkates võite sõidukit kahjustada. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"HybridSysErrorShrt": "Hübriidsüsteemi rike.",
	"HybridSysOverheatLong": "Hübriidsüsteemi rike. Sõitmist jätkates võite sõidukit kahjustada. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"HybridSysOverheatShrt": "Hübriidsüsteemi ülekuumenemine",
	"IeloopChrgHighPrt": "i‑ELOOP laadimine. Kontrollige töötava mootoriga, kas laadimine on lõppenud ja hoiatuse indikaator on kustunud.",
	"IstopSysErrorLong": "i‑stop kasutamine pole võimalik. Laske sõidukit Mazda esinduses kontrollida.",
	"IstopSysErrorShrt": "i‑stop süsteemi rike",
	"KeylesSysErrorLong": "Võtmeta sisenemise süsteemi rike. Laske sõidukit esinduses kontrollida.",
	"KeylesSysErrorShrt": "Võtmeta sisenemise rike",
	"LDWSSysErrorLong": "Lane Departure Warning System (LDWS) rike. Laske sõidukit esinduses kontrollida.",
	"LDWSSysErrorLong_2": "Lane-keep Assist System-i (LAS) rike. Kui indikaator jääb põlema, laske sõidukit esinduses kontrollida.",
	"LDWSSysErrorShrt": "LDWS-rike",
	"LDWSSysErrorShrt_2": "LAS-i rike",
	"LowBrakeFluidLong": "Pidurivedeliku tase on madal. Peatage sõiduk kohe ohutus kohas ja laske see esinduses üle vaadata.",
	"LowBrakeFluidShrt": "Pidurivedeliku tase madal",
	"LowFuelLong": "Kütusepaagi tase on madal. Lisage peagi kütust.",
	"LowFuelShrt": "Madal kütuse tase",
	"LowTireAirPressureFlatLong": "Kui rehvirõhk väheneb oluliselt pärast rehvirõhu jälgimissüsteemi  hoiatuslambi süttimist või kui rehv on läbi torgatud, süttib ka tühja rehvi hoiatuslamp. Kui mobiilrehv on läbi torgatud, sõitke sõidukiga ettevaatlikult lähima Mazda edasimüüja juurde ja laske rehv välja vahetada.",
	"LowTireAirPressureLong": "Madal rehvirõhk ühes või mitmes rehvis. \nKontrollige rehvide rõhku ja reguleerige õige tasemeni.  Vajutage pärast rehvirõhu reguleerimist lülitit TPMS SET, kuni kuulete helisignaali.",
	"LowTireAirPressureShrt": "Madal rehvirõhk",
	"LowWasheFluidLong": "Pesuvedeliku tase on madal. Lisage pesuvedelikku.",
	"LowWasheFluidShrt": "Pesuvedeliku tase madal",
	"MRCCSysErrorLong": "Mazda Radar Cruise Control (MRCC) rike. Laske sõidukit esinduses kontrollida.",
	"MRCCSysErrorShrt": "MRCC-rike",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) pole hetkel saadaval.",
	"MRCCUnavailableShrt": "MRCC pole kasutatav",
	"NoWarnings": "Hoiatusi ei leitud",
	"PowerSteeringSysErrorLong": "Elektrilise roolivõimendi rike. Peatage sõiduk ohutus kohas ja lülitage mootor välja.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"PowerSteeringSysErrorShrt": "Roolivõimendi süsteemi rike.",
	"PpositionRequestLong": "Viige käigukang parkimisasendisse. Selle põhjuseks võib olla: ・ Akusüsteem käivitati või peatati, kui käigukang ei olnud parkimisasendis ・ Juhipoolne uks avati, kui käigukang oli asendis N, D või B ・ Järele kõrgepinge aku hakkab tühjaks saama, sest edastamine oli Neutral pikka aega\nTaaskäivitage hübriidsüsteem, vajutades vajadusel toitelülitit.\n",
	"PpositionRequestShrt": "Parkimisasendi päring",
	"PreheatingDispLampLong": "Soojendusküünlad soojenevad. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"PreheatingDispLampShrt": "Soojendusküünlad soojenevad",
	"RoadSurfaceIcingCautionLong": "Välistemperatuur on 4 °C või madalam. Pange sõidu ajal tähele teepinna jäidet.",
	"RoadSurfaceIcingCautionShrt": "Teepinna jäite hoiatus",
	"RvmSysErrorLong": "RVM-süsteemis on viga. Kontrollige tagastange pinna kõrvalekaldeid ja puhastage, kui see on määrdunud või lumega kaetud. Kui indikaator jääb põlema, siis laske sõidukit Mazda esinduses kontrollida.",
	"RvmSysErrorShrt": "RVM-rike",
	"SBSBrakeMRCCUnavailableLong": "SBS pidur/MRCC pole hetkel kasutatav.",
	"SBSBrakeMRCCUnavailableShrt": "SBS pidur/MRCC pole kasutatav",
	"SBSBrakeUnavailableLong": "SBS pidur pole hetkel kasutatav.",
	"SBSBrakeUnavailableShrt": "SBS pidur pole kasutatav",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS radar (andur) on määrdunud. \nPuhastage kogu radari (anduri) pind\n\n",
	"SBSMRCCDRSSRadarSoilingShrt": "SBS/MRCC/DRSS-radari rike",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC radar (andur) on määrdunud.",
	"SBSMRCCRadarSoilingShrt": "SBS/MRCC radari rike",
	"SBSSysErrorLong": "SBS-süsteemis on viga. Laske sõidukit Mazda esinduses kontrollida.",
	"SBSSysErrorShrt": "SBS-rike",
	"SCBSSysErrorLong": "Smart City Brake Support (SCBS) rike. Laske sõidukit kohe esinduses kontrollida.",
	"SCBSSysErrorShrt": "SCBS-rike",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) pole hetkel saadaval.",
	"SCBSUnavailableShrt": "SCBS pole kasutatav",
	"SCBSWindshieldSoilingLong": "Smart City Brake Support (SCBS) rike. Puhastage esiklaasi.  Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida. ",
	"SCBSWindshieldSoilingShrt": "SCBS-rike",
	"SedimenterWarningLong": "Sadestisse kogunenud vee kogus ületab ettenähtud taset. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"SedimenterWarningShrt": "Sadesti ülevaatus",
	"SystemInspectionLong": "Diferentsiaali õlitemperatuur on ebatavaliselt kõrge või esi- ja tagarehvide pöörlemiskiirustes on suur erinevus (nagu näiteks mudasse kinni jäädes). Peatage sõiduk ohutus kohas ja jätkake sõitu pärast hoiatustule kustumist. Kui indikaator jääb põlema, siis laske sõidukit esinduses kontrollida.",
	"SystemInspectionShrt": "4WD süsteemi ülevaatus",
	"TpmsSysErrorLong": "Rehvirõhu seiresüsteemi (TPMS) rike. Laske sõidukit esinduses kontrollida.",
	"TpmsSysErrorShrt": "TPMS-süsteemi rike",
	"VehicleSysErrorLong": "Sõiduki süsteemi rike.\nLaske sõidukit esinduses kontrollida.\n",
	"VehicleSysErrorShrt": "Sõiduki süsteemi rike",
	"WarningGuidance": "Hoiatusteated",
	"WarningSafetyMessage": "Ohutuse huvides hoiatusteateid ei kuvata.",
	"Warnings": "Hoiatused",
	"brakeFluid": "Pidurivedeliku tase on madal",
	"engineOilPressure": "Mootori õlirõhk",
	"highVoltage": "Kõrgepingeaku on tühjenemas",
	"lowBattStartEngine": "Aku on tühjenemas. Käivit. mootor!",
};

framework.registerAppDictLoaded("warnguide", "et_EE");