var Localization_warnguideAppDict_no_NO = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Feil ved systemet for blokkeringsfrie bremser (ABS).\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"AbsSysErrorShrt": "Feil ved ABS",
	"AbsSystemErrorLong": "Feil ved systemet for blokkeringsfrie bremser (ABS).\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"AbsSystemErrorShrt": "Feil ved ABS",
	"AccumulationDpfLong": "Partiklene (PM) som er samlet opp i dieselpartikkelfilteret (DPF) har overskredet verdien i forskriften.\nKjør i ca. 10 til 15 minutter mens maskinen er helt varm (blått temp. lys er av) i 15 km/t eller mer for å eliminere PM.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"AccumulationDpfShrt": "PM-akkumulering i DPF",
	"ActiveBonnetSystemMalfunctionLong": "Feil på Active Bonnet System. Bilen må undersøkes av forhandleren hvis denne indikatorlampen forblir tent eller fortsetter å blinke.",
	"ActiveBonnetSystemMalfunctionShrt": "Feil på Active Bonnet System",
	"AfsSystemErrorLong": "Feil ved adaptive frontlys (AFS)  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsetter å blinke.",
	"AfsSystemErrorShrt": "Feil ved AFS",
	"AirbagSysPretensionerSysErrorLong": "Feil ved airbag/setebeltestrammere.\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"AirbagSysPretensionerSysErrorShrt": "Feil ved airbag/beltestrammer",
	"AutoLevelSystemErrorLong": "Feil ved automatisk nivåregulering for frontlyktene.\nLa en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"AutoLevelSystemErrorShrt": "Feil ved Auto-leveling",
	"AutoLevelSystemErrorShrtJ03": "Feil på frontlyssystem",
	"AutoTransSysErrorLong": "Feil ved den automatiske girkassen.\nDet kan oppstå skade på kjøretøyet hvis du fortsetter å kjøre.  La en forhandler sjekke kjøretøyet umiddelbart.  ",
	"AutoTransSysErrorShrt": "Feil ved automatkasse",
	"AuxBattLowLong": "12V batterinivået er svakt.\n・Hvis denne varsellampen er ofte på mens du kjører, kan det hende at batteriet er svekket. La en forhandler sjekke bilen.\n・Hvis denne varsellampen er konstant på og ikke slås av, er 12V-batteriet utladet. Se brukerhåndboken før du starter hybridsystemet og la en forhandler sjekke bilen.",
	"AuxBattLowShrt": "12V batteri svakt",
	"BattManagSysErrorLong": "Feil ved batterisystemet.\nLa en forhandler sjekke kjøretøyet.",
	"BattManagSysErrorShrt": "Feil ved batterisystem",
	"BrakOverrideSysErrorLong": "Feil ved bremsebryteren.\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"BrakOverrideSysErrorShrt": "Feil ved bremsesystem",
	"BrakeSysErrorLong": "Bremsevæskenivået er for lavt eller det er feil i bremsesystemet.  Stopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke bilen.",
	"BrakeSysErrorShrt": "Feil ved bremsesystemet",
	"BrakeSystemErrorLong": "Feil ved det elektronisk styrte bremsesystemet.\nStopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"BrakeSystemErrorShrt": "Feil ved bremsesystemet",
	"BsmSystemErrorLong": "Feil ved Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nSe etter feil i overflaten på bakre støtfanger og rengjør den hvis den er skitten eller dekket med snø. La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"BsmSystemErrorShrt": "Feil ved BSM",
	"ChargSysMalHighPrt": "Feil ved ladesystemet. Stopp kjøretøyet umiddelbart på et sikkert sted.",
	"ChargingSysErrorLong": "Feil ved ladesystemet.\nDet kan oppstå skade på kjøretøyet hvis du fortsetter å kjøre.  Stopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke bilen.",
	"ChargingSysErrorShrt": "Feil ved ladesystemet",
	"ChrgSysErrorLong": "Feil ved ladesystemet.\nStopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"ChrgSysErrorShrt": "Feil ved ladesystemet",
	"ControlSystemErrorLong": "Feil ved parkeringskontrollsystem. Hvis dette ikke sjekkes, kan det føre til følgelde situasjoner:\n・Parkeringslåsmekanismen vil muligens ikke fungere. Parkér på et flatt sted og sett på parkeringsbremsen.\n・Strømbryteren vil muligens ikke kunne slås av. Trykk på strømbryteren flere ganger for å slå av.\n・Visning av \"Sett på parkeringsbremsen når du parkerer\" vil bli slått av når du kjører og på når du stopper.\nLa forhandleren sjekke kjøretøyet umiddelbart.",
	"ControlSystemErrorShrt": "Feil ved parkeringskontrollsystem",
	"DPFErrorLong": "Feil ved dieselpartikkelfilter (DPF).\nLa en forhandler sjekke kjøretøyet.",
	"DPFErrorShrt": "Feil ved DPF",
	"DRSSSysErrorLong": "Det finnes en feil i DRSS-systemet.\nLa en Mazda-forhandler sjekke kjøretøyet.",
	"DRSSSysErrorShrt": "Feil ved DRSS",
	"DriveBattDropLong": "Drivbatteriet er svakt fordi giret har vært i nøytral stilling i lang tid. Flytt til park når bilen er stoppet over lengre tid. Start hybridsystemet om nødvendig på nytt ved å trykke på strømbryteren.",
	"DriveBattDropShrt": "Høyspenningsbatteriet svakt",
	"DropKeyBattChrgLong": "Nøkkelbatteriet er svakt.\nSkift nøkkelbatteri umiddelbart.",
	"DropKeyBattChrgShrt": "Nøkkelbatteriet er svakt",
	"DscSysErrorLong": "Feil ved Dynamic Stability Control (DSC), Traction Control System (TCS) eller Hill Launch Assist (HLA).\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"DscSysErrorShrt": "Feil ved DSC",
	"DscSystemErrorLong": "Feil ved dynamisk stabilitetskontroll (DSC) eller systemet for veigrepskontroll (TCS).\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"DscSystemErrorShrt": "Feil ved DSC",
	"EcbSysErrorLong": "Feil ved systemet for regenerativ bremsing eller elektroniske bremser.\nStopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"EcbSysErrorShrt": "Feil ved bremsesystemet",
	"ElectricParkingBrakeHighLong": "En feil oppsto i systemet for parkeringsbrems. Kontakt Mazda-forhandleren for inspeksjon.",
	"ElectricParkingBrakeLong": "En feil oppsto i systemet for parkeringsbrems. Kontakt Mazda-forhandleren for inspeksjon.",
	"ElectricParkingBrakeShrt": "Feil i systemet for parkeringsbrems",
	"ElectricVacuumPumpSystemMalfunctionLong": "Det oppsto en feil i systemet for den elektriske vakuumpumpen. Hvis denne feilen ikke korrigeres, kan systemet svikte, hvilket vil føre til uventet fare eller svikt. Kontakt Mazda-forhandleren umiddelbart og få feilen undersøkt. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Feil i systemet for elektrisk vakuumpumpe",
	"EloopChargingLong": "i‑ELOOP lader.\nSjekk at ladingen er fullført og at varsellampen er slått av mens motoren er i gang. La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"EloopChargingShrt": "i‑ELOOP lader",
	"EloopSysErrorLong": "Feil ved i‑ELOOP-systemet.\nLa en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"EloopSysErrorShrt": "Feil ved i‑ELOOP-systemet",
	"EngCoolntTempHighOnLong": "Motoren overopphetes.\nStopp kjøretøyet umiddelbart på et sikkert sted, slå av motoren og iverksett egnede tiltak.  Se brukerhåndboken.",
	"EngCoolntTempHighOnShrt": "Høy temperatur på kjølevæske",
	"EngOilPressureErrorLong": "Lavt motoroljetrykk.\nStopp kjøretøyet umiddelbart på et sikkert sted, slå av motoren og sjekk motoroljenivået. Etterfyll med olje om nødvendig.\nLa en forhandler sjekke kjøretøyet umiddelbart hvis denne varsellampen slås på etter at du har etterfylt med olje eller hvis motoroljenivået er OK.",
	"EngOilPressureErrorShrt": "Lavt motoroljetrykk",
	"EngSystemErrorLong": "Feil i motorsystem. La en forhandler sjekke kjøretøyet umiddelbart.",
	"EngSystemErrorShrt": "Feil i motorsystem",
	"EngineOilPressureErrorLong": "Lavt motoroljetrykk.\nStopp kjøretøyet umiddelbart på et sikkert sted, slå av motoren og sjekk motoroljenivået. Etterfyll med olje om nødvendig.\nLa en forhandler sjekke kjøretøyet umiddelbart hvis denne varsellampen slås på etter at du har etterfylt med olje eller hvis motoroljenivået er OK.",
	"EngineOilPressureErrorShrt": "Lavt motoroljetrykk",
	"EngineWaterTempDropLong": "Kjølevæsken er kald og det finnes ingen varm luft for varmeapparat/defroster. Kjøretøyet kan kjøres med varsellampen på eller av.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"EngineWaterTempDropShrt": "Lav temperatur på kjølevæske",
	"EngineWaterTempRiseLong": "Motoren begynner å bli for varm.\nKjør sakte eller stopp motoren til varsellampen slutter å blinke. Hvis den fortsatt blinker, selv etter at kjøretøyet er stoppet, må du iverksette egnede tiltak. Se brukerhåndboken.",
	"EngineWaterTempRiseShrt": "Høy temperatur på kjølevæske",
	"EngnCoolTempHighHighPrt": "Høy temperatur på kjølevæske. Stopp kjøretøyet umiddelbart på et sikkert sted.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW-/MRCC-/DRSS- radar (sensor) er skitten.\nRengjør hele overflaten på radaren (sensor).",
	"FOWMRCCDRSSRadarSoilingShrt": "Feil ved FOW/MRCC/DRSS radar",
	"FOWMRCCRadarSoilingLong": "FOW-/MRCC- radar (sensor)-feil.\nRengjør hele overflaten på frontgrillemblemet hvis det er skittent eller tildekket med snø.  \nLa en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"FOWMRCCRadarSoilingShrt": "Feil ved FOW/MRCC radar",
	"FOWSysError": "Feil ved FOW",
	"FOWSysErrorLong": "Feil ved Forward Obstruction Warning (FOW). La en forhandler sjekke kjøretøyet.",
	"FWDSysErrorLong": "Systemfeil for 4WD eller dekkstørrelsen på front- og bakhjulene er ulik.\nLa en forhandler sjekke kjøretøyet.",
	"FWDSysErrorShrt": "Systemfeil, 4WD",
	"FuelAirFilterCartReplacePeriodLong": "Luft/dristoffilter må skiftes.",
	"FuelAirFilterCartReplacePeriodShrt": "Luft/drivstoffilter må skiftes",
	"FuelCapInspectionLong": "Bensinlokket er muligens ikke satt skikkelig på.\nSjekk at bensinlokket er satt skikkelig på og tilstrammet slik det skal.\nEtter at bensinlokket er satt på og strammet til slik det skal, vil denne varsellampen lyse par kjøresykluser til det kan bekreftes at systemet er OK.  La en forhandler sjekke kjøretøyet hvis varsellampen ikke slukker.",
	"FuelCapInspectionShrt": "Inspeksjon, bensinlokk",
	"HBCLDWSSysErrorLong": "Feil ved High Beam Control (HBC)/Lane Departure Warning System (LDWS). La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSSysErrorLong_2": "Feil ved High Beam Control (HBC)/Lane-keep Assist System (LAS). La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSSysErrorLong_3": "Feil ved Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). La en forhandler sjekke kjøretøyet.",
	"HBCLDWSSysErrorLong_4": "Feil ved Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). La en forhandler sjekke kjøretøyet. ",
	"HBCLDWSSysErrorShrt": "Feil ved HBC/LDWS kamera",
	"HBCLDWSSysErrorShrt_2": "Feil ved HBC/LAS systemet",
	"HBCLDWSSysErrorShrt_3": "Feil ved ALH/LDWS systemet",
	"HBCLDWSSysErrorShrt_4": "Feil ved ALH/LAS systemet",
	"HBCLDWSWindshieldFogLong": "Feil ved High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nFjern is og dugg fra frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSWindshieldFogLong_2": "Feil ved High Beam Control (HBC)/Lane-keep Assist System (LAS).  Fjern is og dugg fra frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSWindshieldFogLong_3": "Feil ved Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Fjern is og dugg fra frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSWindshieldFogLong_4": "Feil ved Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Fjern is og dugg fra frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLDWSWindshieldFogShrt": "Feil ved HBC/LDWS kamera",
	"HBCLDWSWindshieldFogShrt_2": "Feil ved HBC/LAS systemet",
	"HBCLDWSWindshieldFogShrt_3": "Feil ved ALH/LDWS systemet",
	"HBCLDWSWindshieldFogShrt_4": "Feil ved ALH/LAS systemet",
	"HBCLLDWSCamDisconnectLong": "Feil ved High Beam Control (HBC)/Lane Departure Warning System (LDWS).\nRengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLLDWSCamDisconnectLong_2": "Feil ved High Beam Control (HBC)/Lane-keep Assist System (LAS). Rengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLLDWSCamDisconnectLong_3": "Feil ved Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Rengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLLDWSCamDisconnectLong_4": "Feil ved Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Rengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"HBCLLDWSCamDisconnectShrt": "Feil ved HBC/LDWS kamera",
	"HBCLLDWSCamDisconnectShrt_2": "Feil ved HBC/LAS kamera",
	"HBCLLDWSCamDisconnectShrt_3": "Feil ved ALH/LDWS kamera",
	"HBCLLDWSCamDisconnectShrt_4": "Feil ved ALH/LAS kamera",
	"HBCSysErrorLong": "Feil ved High Beam Control (HBC).\nLa en forhandler sjekke kjøretøyet.",
	"HBCSysErrorLong_2": "Feil ved Adaptive LED Headlights (ALH). La en forhandler sjekke kjøretøyet.",
	"HBCSysErrorShrt": "Feil ved HBC",
	"HBCSysErrorShrt_2": "Feil ved ALH",
	"HeadlightSystemErrorLongJ03": "En feil oppsto i frontlyssystemet. Hvis varsellampen blinker kontinuerlig, kontakt Mazda-forhandleren.",
	"HybrdSysMalHighPrt": "Feilved hybridsystem. Stopp kjøretøyet umiddelbart på et sikkert sted.",
	"HybridSysErrorLong": "Feil, hybridsystem.\nDet kan oppstå skade på kjøretøyet hvis du fortsetter å kjøre. Stopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"HybridSysErrorShrt": "Feil i hybridsystem",
	"HybridSysOverheatLong": "Feil ved hybridsystem.\nDet kan oppstå skade på kjøretøyet hvis du fortsetter å kjøre. Stopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"HybridSysOverheatShrt": "Hybridsystemet overopphetet",
	"IeloopChrgHighPrt": "i‑ELOOP lader. Sjekk at ladingen er fullført og at varsellampen er slått av mens motoren er i gang.",
	"IstopSysErrorLong": "i‑stop kan ikke aktiveres.\nLa en Mazda-forhandler sjekke kjøretøyet.",
	"IstopSysErrorShrt": "Feil ved i‑stop",
	"KeylesSysErrorLong": "Feil ved Keyless Entry.\nLa en forhandler sjekke kjøretøyet.",
	"KeylesSysErrorShrt": "Feil ved Keyless Entry",
	"LDWSSysErrorLong": "Feil ved Lane Departure Warning System (LDWS).\nLa en forhandler sjekke kjøretøyet.",
	"LDWSSysErrorLong_2": "Feil ved Lane-keep Assist System (LAS). La en forhandler sjekke kjøretøyet.",
	"LDWSSysErrorShrt": "Feil ved LDWS",
	"LDWSSysErrorShrt_2": "Feil ved LAS",
	"LowBrakeFluidLong": "Bremsevæskenivået er lavt.\nStopp kjøretøyet umiddelbart på et sikkert sted og la en forhandler sjekke kjøretøyet.",
	"LowBrakeFluidShrt": "Lavt bremsevæskenivå",
	"LowFuelLong": "Lavt nivå i drivstofftanken.\nFyll drivstoff.",
	"LowFuelShrt": "Lavt drivstoffnivå",
	"LowTireAirPressureFlatLong": "Hvis dekktrykket reduseres kraftig etter at TPMS-varsellampen er tent, eller hvis et dekk er punktert tennes også varsellampen for punktert dekk. Hvis et sikkerhetsdekk punkterer, kjør bilen til nærmeste Mazda-forhandler og få skiftet dekket.",
	"LowTireAirPressureLong": "Lavt trykk i ett eller flere dekk.\nSjekk lufttrykket i dekkene og juster til korrekt lufttrykk.  Trykk på bryteren TPMS SET etter at du har justert dekktrykket, til du hører en varselstone.",
	"LowTireAirPressureShrt": "Lavt dekktrykk",
	"LowWasheFluidLong": "Vindusspylervæskenivå er lavt.\nEtterfyll med spylervæske.",
	"LowWasheFluidShrt": "Lavt spylervæske nivå",
	"MRCCSysErrorLong": "Feil ved Mazda Radar Cruise Control (MRCC).\nLa en forhandler sjekke kjøretøyet.",
	"MRCCSysErrorShrt": "Feil ved MRCC",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) er ikke tilgjengelig nå.",
	"MRCCUnavailableShrt": "MRCC utilgjengelig",
	"NoWarnings": "Fant ingen advarsler",
	"PowerSteeringSysErrorLong": "Feil ved elektrisk servostyring.\nStopp kjøretøyet på et sikkert sted og slå av motoren.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"PowerSteeringSysErrorShrt": "Feil ved elektrisk servostyring",
	"PpositionRequestLong": "Sett giret i park.\nDette er forårsaket av én av følgende:\n・ Batterisystemet ble startet eller stoppet mens giret var i en annen stilling enn park\n・ Førerdøren ble åpnet mens giret var i én av stillingene N, D eller B\n・ Høyspenningsbatteriet er svakt fordi giret var i nøytral i lang tid.\nStart om nødvendig hybridsystemet på nytt ved å trykke på strømbryteren.",
	"PpositionRequestShrt": "Forespørsel, park. Plassering",
	"PreheatingDispLampLong": "Glødepluggene forvarmes.\nLa en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"PreheatingDispLampShrt": "Glødepluggene forvarmes",
	"RoadSurfaceIcingCautionLong": "Utendørstemperaturen er 4 °C eller lavere.\nVær oppmerksom på glatte veier når du kjører.",
	"RoadSurfaceIcingCautionShrt": "Varsling om glatt vei",
	"RvmSysErrorLong": "Det finnes en feil i RVM-systemet.\nSe etter feil i overflaten på bakre støtfanger og rengjør den hvis den er skitten eller dekket med snø.\nLa en Mazda-forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"RvmSysErrorShrt": "Feil ved RVM",
	"SBSBrakeMRCCUnavailableLong": "SBS-brems/MRCC er ikke tilgjengelig nå.",
	"SBSBrakeMRCCUnavailableShrt": "SBS-brems/MRCC utilgjengelig",
	"SBSBrakeUnavailableLong": "SBS-brems er ikke tilgjengelig nå.",
	"SBSBrakeUnavailableShrt": "SBS-brems utilgjengelig",
	"SBSMRCCDRSSRadarSoilingLong": "SBS-/MRCC-/DRSS radar (sensor) er skitten.\nRengjør hele overflaten på radaren (sensor).",
	"SBSMRCCDRSSRadarSoilingShrt": "Feil ved SBS/MRCC/DRSS radar",
	"SBSMRCCRadarSoilingLong": "SBS-/MRCC- radar (sensor) er skitten.\nRengjør hele overflaten på radaren (sensor).",
	"SBSMRCCRadarSoilingShrt": "Feil ved SBS/MRCC radar",
	"SBSSysErrorLong": "Det finnes en feil i SBS-systemet.\nLa en Mazda-forhandler sjekke kjøretøyet.",
	"SBSSysErrorShrt": "Feil ved SBS",
	"SCBSSysErrorLong": "Feil ved Smart City Brake Support (SCBS).\nLa en forhandler sjekke kjøretøyet umiddelbart.",
	"SCBSSysErrorShrt": "Feil ved SCBS",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) er ikke tilgjengelig nå.",
	"SCBSUnavailableShrt": "SCBS utilgjengelig",
	"SCBSWindshieldSoilingLong": "Feil ved Smart City Brake Support (SCBS).\nRengjør frontruten.  La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"SCBSWindshieldSoilingShrt": "Feil ved SCBS",
	"SedimenterWarningLong": "Mengden vann som er samlet opp i sedimenteren overskrider oppgitt mengde.\nLa en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"SedimenterWarningShrt": "Sediment inspeksjon",
	"SystemInspectionLong": "Differensialoljetemperaturen er unormalt høy eller det har oppstått en stor rotasjonsforskjell på front- og bakhjulene (for eksempel når du prøver å kjøre deg løs fra søle).\nStopp kjøretøyet på et sikkert sted og fortsett med å kjøre etter at varsellampen er slått av. La en forhandler sjekke kjøretøyet hvis denne varsellampen fortsatt er på.",
	"SystemInspectionShrt": "Systeminspeksjon, 4WD",
	"TpmsSysErrorLong": "Feil i overvåkingssystemet for dekktrykk (TPMS).\nLa en forhandler sjekke kjøretøyet.",
	"TpmsSysErrorShrt": "Feil ved TPMS",
	"VehicleSysErrorLong": "Feil ved kjøretøysystemet.\nLa en forhandler sjekke kjøretøyet.",
	"VehicleSysErrorShrt": "Feil ved kjøretøysystemet",
	"WarningGuidance": "Advarselsveiledning",
	"WarningSafetyMessage": "Advarselsveiledningen vises ikke av sikkerhetsårsaker.",
	"Warnings": "Advarsler",
	"brakeFluid": "Lavt bremsevæskenivå",
	"engineOilPressure": "Motorens oljetrykk",
	"highVoltage": "Svakt høyspenningsbatteri",
	"lowBattStartEngine": "Svakt batteri! Start motoren!",
};

framework.registerAppDictLoaded("warnguide", "no_NO");