var Localization_warnguideAppDict_tr_TR = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Kilitlemeyi önleyen fren sistemi (ABS) arızası.\nAracınızı derhal bayiinize kontrol ettirin.",
	"AbsSysErrorShrt": "ABS Arzası",
	"AbsSystemErrorLong": "Kilitlenmeyi önleyen fren sistemi (ABS) arızası.\nAracınızı derhal bayiinize kontrol ettirin.",
	"AbsSystemErrorShrt": "ABS Arızası",
	"AccumulationDpfLong": "Dizel partikül filtresinde (DPF) toplanan partikül maddeler (PM) regülasyon değerini aşmıştır.\nPM'nin temizlenmesi için, motor tam ısınmış konumdayken (mavi ısı ışığı söner) aracınızı 15km/sa (10 mil/sa) veya daha yüksek bir hızda yaklaşık 10 ila 15 dakika sürün.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"AccumulationDpfShrt": "PDF'de PM Birikti",
	"ActiveBonnetSystemMalfunctionLong": "Active Bonnet Sistemi Arızası. Bu gösterge yanmaya veya yanıp sönmeye devam ederse aracınızı bir bayiye kontrol ettirin.",
	"ActiveBonnetSystemMalfunctionShrt": "Active Bonnet Sistemi Arızası",
	"AfsSystemErrorLong": "Direksiyona duyarlı far sistemi (AFS) arızası.  Bu gösterge yanıp sönmeye devam ediyorsa, aracınızı bayiinize kontrol ettirin.",
	"AfsSystemErrorShrt": "AFS Arızası",
	"AirbagSysPretensionerSysErrorLong": "Hava yastığı/emniyet kemeri arızası.\nAracınızı derhal bayiinize kontrol ettirin\n",
	"AirbagSysPretensionerSysErrorShrt": "Hava Yastığı/Ön Gerdirici S. Arızası",
	"AutoLevelSystemErrorLong": "Far otomatik dengeleme sistemi arızası.\nBu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"AutoLevelSystemErrorShrt": "Otomatik-Seviye Ayar Sistemi Arızası",
	"AutoLevelSystemErrorShrtJ03": "Far Sistemi arızası",
	"AutoTransSysErrorLong": "Otomatik şanzıman arızası.\nBu şekilde kullanılmaya devam edilirse, araçta hasar meydana gelebilir.  Aracınızı derhal bayiinize kontrol ettirin.  \n",
	"AutoTransSysErrorShrt": "Otomatik Şanzıman Arızası",
	"AuxBattLowLong": "12V akü şarjı düşüktür.\n・Sürüş sırasında bu gösterge sık sık yanıyorsa, akü zayıflamış olabilir. Aracınızı yetkili servise kontrol ettirin.\n・Bu gösterge sürekli yanıyorsa ve sönmüyorsa, 12V akünün ömrü bitmiştir. Hibrit sistemi başlatmadan önce Kullanıcı Kılavuzuna bakın ve aracınızı bir yetkili servise kontrol ettirin.\n",
	"AuxBattLowShrt": "12V Akü Düşük",
	"BattManagSysErrorLong": "Akü yönetimi sistemi arızası.\nAracınızı bayiinize kontrol ettirin\n",
	"BattManagSysErrorShrt": "Akü Yönetim Sistemi Arızası",
	"BrakOverrideSysErrorLong": "Fren anahtarı arızası.\nAracınızı derhal bayiinize kontrol ettirin.\n",
	"BrakOverrideSysErrorShrt": "Fren Atlatma Sistemi Arızası",
	"BrakeSysErrorLong": "Fren sıvısı seviyesi düşüktür veya fren sistemi arızalıdır.                                                             Aracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.",
	"BrakeSysErrorShrt": "Fren Sistemi Arızası",
	"BrakeSystemErrorLong": "Elektronik kumandalı fren sistemi arızası.\nAracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"BrakeSystemErrorShrt": "Fren Sistemi Arızası",
	"BsmSystemErrorLong": "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA) arızası.\nArka tampon üzerini kontrol edin ve kirle veya karla kaplıysa temizleyin. Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"BsmSystemErrorShrt": "BSM Arızası",
	"ChargSysMalHighPrt": "Şarj Sistemi Arızası. Aracı derhal güvenli bir yerde durdurun.",
	"ChargingSysErrorLong": "Şarj sistemi arızası. \nBu şekilde kullanılmaya devam edilirse, araçta hasar meydana gelebilir.  Aracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"ChargingSysErrorShrt": "Şarj Sistemi Arızası",
	"ChrgSysErrorLong": "Şarj sistemi arızası.\nAracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"ChrgSysErrorShrt": "Şarj Sistemi Arızası",
	"ControlSystemErrorLong": "Park konumu kontrol sistemi arızası.\nKontrol edilmezse, aşağıdaki durumlardan birine neden olabilir:\n・Park kilit mekanizması çalışmayabilir. Düz bir yere park edin ve el frenini sağlam şekilde çekin.\n・Kontak düğmesi kapanmayabilir. Kapatmak için kontak düğmesine arka arkaya basın.\n・ \"Park Halindeyken El Frenini Çekin\" göstergesi, sürüş sırasında söner ve durulduğunda yanar.\nAracınızı derhal bayinize kontrol ettirin.",
	"ControlSystemErrorShrt": "Park Konumu Kontrol Sistemi Arızası",
	"DPFErrorLong": "Dizel partikül filtresi (DPF) arızası.\nAracınızı bayiinize kontrol ettirin\n",
	"DPFErrorShrt": "DPF Hatası",
	"DRSSSysErrorLong": "DRSS sisteminde bir hata vardır.\nAracınızı bir Mazda bayisine kontrol ettirin.\n",
	"DRSSSysErrorShrt": "DRSS Arızası",
	"DriveBattDropLong": "Vites uzun süre boşta bırakıldığından Yüksek Gerilimli Aküde Artakalan Güç Düşmüştür. Boşta şarj mümkün değildir. Uzun süre duraklayacağınız zaman vitesi Park konumuna alın. Gerekirse, Kontak Düğmesine basarak Hibrit Sistemi yeniden başlatın.",
	"DriveBattDropShrt": "Yüksek Gerilimli Akü Düşük",
	"DropKeyBattChrgLong": "Kumanda pil seviyesi düşüktür.\nKumanda pilini derhal değiştirin.",
	"DropKeyBattChrgShrt": "Akumanda Pili Düşük",
	"DscSysErrorLong": "Dynamic Stability Control (DSC), Traction Control System (TCS) veya Hill Launch Assist (HLA) sistemi arızası.\nAracınızı derhal bayiinize kontrol ettirin.\n",
	"DscSysErrorShrt": "DSC Arızası",
	"DscSystemErrorLong": "Dinamik denge kontrolü (DSC) veya çekiş kontrolü sistemi (TCS) arızası.\nAracınızı derhal bayiinize kontrol ettirin.\n",
	"DscSystemErrorShrt": "DSC Arızası",
	"EcbSysErrorLong": "Rejeneratif fren veya elektronik kumandalı fren sistemi arızalıdır.\nAracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"EcbSysErrorShrt": "Fren Sistemi Arızası",
	"ElectricParkingBrakeHighLong": "El Freni sisteminde bir arıza oluştu. Denetim için Mazda Bayiinize danışın.",
	"ElectricParkingBrakeLong": "El Freni sisteminde bir arıza oluştu. Denetim için Mazda Bayiinize danışın.",
	"ElectricParkingBrakeShrt": "El Freni sistemi arızası",
	"ElectricVacuumPumpSystemMalfunctionLong": "Elektrikli vakum pompası sisteminde bir arıza oluştu. Bu hatanın giderilmemesi sistemin çalışmamasına ve dolayısıyla  beklenmedik bir tehlikeye veya aracın arızalanmasına neden olabilir. Mazda Bayiinize danışın ve hatayı kontrol ettirin. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Elektrikli vakum pompası sistemi arızası",
	"EloopChargingLong": "i‑ELOOP şarj oluyor.\nMotor çalışırken, şarj işleminin tamamlandığını ve uyarı göstergesinin söndüğünü kontrol edin. Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"EloopChargingShrt": "i‑ELOOP Şarj Oluyor",
	"EloopSysErrorLong": "i‑ELOOP sistemi arızası.\nBu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"EloopSysErrorShrt": "i‑ELOOP Sistemi Arızası",
	"EngCoolntTempHighOnLong": "Motor aşırı ısınmıştır.\nAracınızı derhal güvenli bir yerde durdurun, motoru kapatın ve gerekli önlemleri alın.  Kullanıcı Kılavuzuna bakın.\n",
	"EngCoolntTempHighOnShrt": "Motor Soğutucu Sıcaklığı Yüksek",
	"EngOilPressureErrorLong": "Düşük motor yağı basıncı.\nAracınızı derhal güvenli bir yerde durdurun, motoru kapatın ve motor yağı seviyesini kontrol edin. Gerekirse, yağ ilave edin.\nYağ ilave edildikten sonra ve motor yağı seviyesi Normal konumuna geldikten sonra bu gösterge hala yanıyorsa, aracınızı derhal bayiinize kontrol ettirin.\n",
	"EngOilPressureErrorShrt": "Düşük Motor Yağı Basıncı",
	"EngSystemErrorLong": "Motor sistemi arızası.  Aracınızı derhal bayiinize kontrol ettirin.",
	"EngSystemErrorShrt": "Motor Sistemi Arızası",
	"EngineOilPressureErrorLong": "Düşük motor yağı basıncı.\nAracınızı derhal güvenli bir yerde durdurun, motoru kapatın ve motor yağı seviyesini kontrol edin. Gerekirse, yağ ilave edin.\nYağ ilave edildikten sonra ve motor yağı seviyesi Normal konumuna geldikten sonra bu gösterge hala yanıyorsa, aracınızı derhal bayiinize kontrol ettirin.\n",
	"EngineOilPressureErrorShrt": "Düşük Motor Yağı Basıncı",
	"EngineWaterTempDropLong": "Motor soğutucusu soğuktur ve ısıtıcı/buz çözücü için sıcak hava mevcut değildir. Araç gösterge açık veya kapalı konumdayken sürülebilir.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"EngineWaterTempDropShrt": "Motor Soğutucu Sıcaklığı Düşük",
	"EngineWaterTempRiseLong": "Motor sıcak çalışıyor.\nAracı göstergenin yanıp sönmesi durana kadar yavaş sürün veya durun. Aracı durdurduktan sonra da yanıp sönmeye devam ediyorsa, gerekli önlemleri alın. Kullanıcı Kılavuzuna bakın.\n",
	"EngineWaterTempRiseShrt": "Motor Soğutucu Sıcaklığı Yüksek",
	"EngnCoolTempHighHighPrt": "Motor Soğutucu Sıcaklığı Yüksek. Aracı derhal güvenli bir yerde durdurun.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS radarı (sensör) kirlidir.\nTüm radar (sensör) yüzeyini temizleyin.\n\n",
	"FOWMRCCDRSSRadarSoilingShrt": "FOW/MRCC/DRSS Radar Arızası",
	"FOWMRCCRadarSoilingLong": "FOW/MRCC radarı (sensör) arızası.\nKirle veya karla kaplıysa, ön ızgara ambleminin bulunduğu alanı temizleyin.  \nBu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"FOWMRCCRadarSoilingShrt": "FOW/MRCC Radar Arızası",
	"FOWSysError": "FOW Arızası",
	"FOWSysErrorLong": "Forward Obstruction Warning (FOW) sistemi arızası.\nAracınızı bayiinize kontrol ettirin.",
	"FWDSysErrorLong": "4WD sistemi arızalıdır veya lastik boyutu ön ve arka tekerler arasında farklıdır.\nAracınızı bayiinize kontrol ettirin.\n",
	"FWDSysErrorShrt": "4WD Sistemi Arızası",
	"FuelAirFilterCartReplacePeriodLong": "Yakıt-Hava Filtre Değişimi Gerekli",
	"FuelAirFilterCartReplacePeriodShrt": "Yakıt-Hava Filtre Değişimi Gerekli",
	"FuelCapInspectionLong": "Yakıt kapağı doğru şekilde takılmamış olabilir.\nYakıt kapağının takıldığını ve doğru şekilde sıkıldığını kontrol edin.\nYakıt kapağı doğru şekilde takıldıktan ve sıkıldıktan sonra, birkaç sürüşün ardından sistemin Sorunsuz olduğu doğrulandığında bu gösterge sönecektir.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"FuelCapInspectionShrt": "Yakıt Depo Kapağı Kontrolü",
	"HBCLDWSSysErrorLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) arızası. Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"HBCLDWSSysErrorLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Arızası. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSSysErrorLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Arızası. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSSysErrorLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Arızası. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSSysErrorShrt": "HBC/LDWS Sistemi Arızası",
	"HBCLDWSSysErrorShrt_2": "HBC/LAS Sistemi Arızası",
	"HBCLDWSSysErrorShrt_3": "ALH/LDWS Sistemi Arızası",
	"HBCLDWSSysErrorShrt_4": "ALH/LAS Sistemi Arızası",
	"HBCLDWSWindshieldFogLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) arızası.\nÖn camın buzunu çözdürün.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"HBCLDWSWindshieldFogLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Arızası. Ön camın buzunu çözdürün. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSWindshieldFogLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Arızası. Ön camın buzunu çözdürün. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSWindshieldFogLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Arızası. Ön camın buzunu çözdürün. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLDWSWindshieldFogShrt": "HBC/LDWS Sistemi Arızası",
	"HBCLDWSWindshieldFogShrt_2": "HBC/LAS Sistemi Arızası",
	"HBCLDWSWindshieldFogShrt_3": "ALH/LDWS Sistemi Arızası",
	"HBCLDWSWindshieldFogShrt_4": "ALH/LAS Sistemi Arızası",
	"HBCLLDWSCamDisconnectLong": "High Beam Control (HBC)/Lane Departure Warning System (LDWS) arızası.\nÖn camı temizleyin.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"HBCLLDWSCamDisconnectLong_2": "High Beam Control (HBC)/Lane-keep Assist System (LAS) Arızası. Ön camı temizleyin. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLLDWSCamDisconnectLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Arızası. Ön camı temizleyin. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLLDWSCamDisconnectLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Arızası. Ön camı temizleyin. Bu gösterge hala yanıyorsa aracı bayiinize kontrol ettirin.",
	"HBCLLDWSCamDisconnectShrt": "HBC/LDWS Kamera Arızası",
	"HBCLLDWSCamDisconnectShrt_2": "HBC/LAS Kamera Arızası",
	"HBCLLDWSCamDisconnectShrt_3": "ALH/LDWS Kamera Arızası",
	"HBCLLDWSCamDisconnectShrt_4": "ALH/LAS Kamera Arızası",
	"HBCSysErrorLong": "High Beam Control (HBC) arızası.\nAracınızı bayiinize kontrol ettirin.",
	"HBCSysErrorLong_2": "Adaptive LED Headlights (ALH) Arızası. Aracı bayiinize kontrol ettirin.",
	"HBCSysErrorShrt": "HBC Arızası",
	"HBCSysErrorShrt_2": "ALH Arızası",
	"HeadlightSystemErrorLongJ03": "Far sisteminde bir arıza oluştu. İkaz lambası sürekli yanıp sönerse, Mazda Bayiinize danışın.",
	"HybrdSysMalHighPrt": "Hibrit Sistem Arızası. Aracı derhal güvenli bir yerde durdurun.",
	"HybridSysErrorLong": "Hibrit sistem arızası.\nBu şekilde kullanılmaya devam edilirse, araçta hasar meydana gelebilir. Aracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\nBoşta şarj mümkün değildir. Uzun süre duracaksanız, vitesi Park konumuna alın.",
	"HybridSysErrorShrt": "Hibrit Sistem Arızası",
	"HybridSysOverheatLong": "Hibrit sistem arızası.\nBu şekilde kullanılmaya devam edilirse, araçta hasar meydana gelebilir. Aracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"HybridSysOverheatShrt": "Hibrit Sistem Aşırı Isınması",
	"IeloopChrgHighPrt": "i‑ELOOP Şarj Oluyor. Motor çalışırken, şarjın tamamlandığını ve uyarı göstergesinin söndüğünü kontrol edin.",
	"IstopSysErrorLong": "i‑stop kullanımı mümkün değildir.\nAracınızı bir Mazda bayisine kontrol ettirin.\n",
	"IstopSysErrorShrt": "i‑stop Sistemi Arızası",
	"KeylesSysErrorLong": "Anahtarsız giriş sistemi arızası.\nAracınızı bayiinize kontrol ettirin\n",
	"KeylesSysErrorShrt": "Anahtarsız Giriş Arızası",
	"LDWSSysErrorLong": "Lane Departure Warning System (LDWS) arızası.\nAracınızı bayiinize kontrol ettirin.",
	"LDWSSysErrorLong_2": "Lane-keep Assist System (LAS) Arızası. Aracı bayiinize kontrol ettirin..",
	"LDWSSysErrorShrt": "LDWS Arızası",
	"LDWSSysErrorShrt_2": "LAS Arızası",
	"LowBrakeFluidLong": "Fren sıvısı seviyesi düşüktür.\nAracınızı derhal güvenli bir yerde durdurun ve bayiinize kontrol ettirin.\n",
	"LowBrakeFluidShrt": "Düşük Fren Sıvısı",
	"LowFuelLong": "Yakıt deposu seviyesi düşük.\nMümkün olduğunda depoyu doldurun.\n",
	"LowFuelShrt": "Düşük Yakıt",
	"LowTireAirPressureFlatLong": "TPMS ikaz lambası yandıktan sonra lastik basıncı aşırı düşerse veya lastik patlamışsa, patlak lastik ikaz lambası da yanar. Patlak yol alabilen lastik patladıysa, aracınızı dikkatle en yakın  Mazda Bayiine sürün ve lastiği değiştirtin.",
	"LowTireAirPressureLong": "Bir veya daha fazla lastikte düşük lastik hava basıncı.\nLastiklerin hava basıncını kontrol edin ve doğru hava basıncına ayarlayın.  Lastik hava basıncını ayarladıktan sonra bir bip sesi duyana kadar TPMS AYARI düğmesine basın.",
	"LowTireAirPressureShrt": "Düşük Lastik Basıncı",
	"LowWasheFluidLong": "Silecek suyu seviyesi düşüktür. Silecek suyunu doldurunz.",
	"LowWasheFluidShrt": "Düşük Silecek Suyu",
	"MRCCSysErrorLong": "Mazda Radar Cruise Control (MRCC) arızası.\nAracınızı bayiinize kontrol ettirin.",
	"MRCCSysErrorShrt": "MRCC Arızası",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) şu anda mevcut değildir.",
	"MRCCUnavailableShrt": "MRCC Kullanılamıyor",
	"NoWarnings": "Uyarı bulunamadı",
	"PowerSteeringSysErrorLong": "Elektronik hidrolik direksiyon arızası.\nAracınızı derhal güvenli bir yerde durdurun ve motoru kapatın.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"PowerSteeringSysErrorShrt": "Hidrolik Direksiyon Sistemi Arızası",
	"PpositionRequestLong": "Vites Park konumuna alınız.\nNedeni şunlardan biri olabilir:\n・ Akü sistemi vites Park dışındaki bir konumdayken başlatılmış veya durdurulmuştur\n・ Vites N, D veya B konumundayken sürücü tarafındaki kapı açılmıştır\n・ Vites uzun süre Boşta bırakıldığından, artık yüksek gerilimli pil şarjı düşmüştür\nGerekirse, kontak düğmesine basarak hibrit sistemi yeniden başlatın.",
	"PpositionRequestShrt": "Park Konumu Talebi",
	"PreheatingDispLampLong": "Isıtma bujileri ön ısıtılıyordur.\nBu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"PreheatingDispLampShrt": "Isıtma bujileri ön ısıtılıyor",
	"RoadSurfaceIcingCautionLong": "Dış ortam sıcaklığı 4°C veya daha düşüktür.\nSürüş sırasında buzlu yol yüzeylerine karşı dikkatli olun.\n",
	"RoadSurfaceIcingCautionShrt": "Yol Yüzeyi Buzlanma Uyarısı",
	"RvmSysErrorLong": "RVM sisteminde bir hata vardır.\nArka tampon üzerini kontrol edin ve kirle veya karla kaplıysa temizleyin.\nBu uyarı lambası sabit yanıyorsa, aracınızı bir Mazda bayisine kontrol ettirin.\n",
	"RvmSysErrorShrt": "RVM Arızası",
	"SBSBrakeMRCCUnavailableLong": "SBS Freni/MRCC şu anda kullanılamıyor.",
	"SBSBrakeMRCCUnavailableShrt": "SBS Freni/MRCC Kullanılamıyor",
	"SBSBrakeUnavailableLong": "SBS Freni şu anda kullanılamıyor.",
	"SBSBrakeUnavailableShrt": "SBS Freni Kullanılamıyor",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS radarı (sensör) kirlidir.\nTüm radar (sensör) yüzeyini temizleyin.\n",
	"SBSMRCCDRSSRadarSoilingShrt": "SBS/MRCC/DRSS Radar Arızası",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC radarı (sensör) kirlidir.\nTüm radar (sensör) yüzeyini temizleyin.",
	"SBSMRCCRadarSoilingShrt": "SBS/MRCC Radar Arızası",
	"SBSSysErrorLong": "SBS sisteminde bir hata vardır.\nAracınızı bir Mazda bayisine kontrol ettirin.\n",
	"SBSSysErrorShrt": "SBS Arızası",
	"SCBSSysErrorLong": "Smart City Brake Support (SCBS) arızası.\nAracınızı derhal bayiinize kontrol ettirin.",
	"SCBSSysErrorShrt": "SCBS Arızası",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) şu anda mevcut değildir.",
	"SCBSUnavailableShrt": "SCBS Kullanılamıyor",
	"SCBSWindshieldSoilingLong": "Smart City Brake Support (SCBS) arızası.\nÖn camı temizleyin.  Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.",
	"SCBSWindshieldSoilingShrt": "SCBS Arızası",
	"SedimenterWarningLong": "Sedimenterde biriken su miktarı anma değerini geçmiştir.\nBu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"SedimenterWarningShrt": "Sedimenter Kontrolü",
	"SystemInspectionLong": "Diferansiyel yağ sıcaklığı anormal derecede yüksektir veya ön ve arka lastiklerde (örneğin çamurdan çıkmaya çalışırken olduğu gibi) yüksek bir dönüş farkı meydana gelmiştir.\nAracınızı güvenli bir yerde durdurun, uyarı göstergesi söndükten sonra yolunuza devam edebilirsiniz. Bu gösterge sabit yanıyorsa, aracınızı bayiinize kontrol ettirin.\n",
	"SystemInspectionShrt": "4WD Sistemi Kontrolü",
	"TpmsSysErrorLong": "Lastik basıncı takip sistemi (TPMS) arızası.\nAracınızı bayiinize kontrol ettirin.\n",
	"TpmsSysErrorShrt": "TPMS Sistemi Arızası",
	"VehicleSysErrorLong": "Araç sistemi arızası.\nAracınızı bayiinize kontrol ettirin.\n",
	"VehicleSysErrorShrt": "Araç Sistemi Arızası",
	"WarningGuidance": "Uyarı Kılavuzu",
	"WarningSafetyMessage": "Güvenlik nedeniyle, Uyarı Kılavuzu görüntülenmiyor.",
	"Warnings": "Uyarılar",
	"brakeFluid": "Fren Sıvısı Seviyesi Düşük",
	"engineOilPressure": "Motor Yağı Basıncı",
	"highVoltage": "Yüksek Gerilim Pil Düşük",
	"lowBattStartEngine": "Düşük Pil! Motoru Çalıştırın!",
};

framework.registerAppDictLoaded("warnguide", "tr_TR");