var Localization_warnguideAppDict_lt_LT = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Stabdžių antiblokavimo sistemos (ABS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"AbsSysErrorShrt": "ABS triktis",
	"AbsSystemErrorLong": "Stabdžių antiblokavimo sistemos (ABS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį. ",
	"AbsSystemErrorShrt": "ABS triktis",
	"AccumulationDpfLong": "Kietųjų dalelių (PM) kiekis, surinktas dyzelino dalelių filtre (DPF), viršijo norminę vertę. 10–15 minučių važiuokite iki galo įkaitusiu varikliu (mėlyna temperatūros lemputė turi užgesti) 10 myl./val. (15 km/val.) ar didesniu greičiu, kad pašalintumėte kietąsias daleles.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"AccumulationDpfShrt": "PM akumuliavimas DPF-e",
	"ActiveBonnetSystemMalfunctionLong": "Active Bonnet sistemos triktis.\nJei ši lemputė toliau šviečia arba mirksi, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"ActiveBonnetSystemMalfunctionShrt": "Active Bonnet sistemos triktis",
	"AfsSystemErrorLong": "Adaptyviosios priekinio apšvietimo sistemos (AFS) triktis.  Jei ši lemputė nesiliaus mirksėti, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"AfsSystemErrorShrt": "AFS triktis",
	"AirbagSysPretensionerSysErrorLong": "Oro pagalvės/saugos diržo triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį",
	"AirbagSysPretensionerSysErrorShrt": "Or. pag. sist./autom. įtr. rit. t.",
	"AutoLevelSystemErrorLong": "Priekinių žibintų automatinio išlyginimo sistemos triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"AutoLevelSystemErrorShrt": "Autom. išlyginimo sist. triktis",
	"AutoLevelSystemErrorShrtJ03": "Netinkamai veikia priekinių žibintų sistema",
	"AutoTransSysErrorLong": "Automatinės pavarų dėžės triktis. Važiuodami toliau galite sugadinti automobilį.  Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"AutoTransSysErrorShrt": "Automatinės pavarų dėžės triktis",
	"AuxBattLowLong": "12V akumuliatoriaus įkrova yra žema. ・Jei šis indikatorius dažnai įsijungia važiuojant, akumuliatoriaus veikimas galėjo pablogėti. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n・Jei šis indikatorius yra nuolat įjungtas ir neišsijungia, 12V akumuliatorius yra visiškai iškrautas. Prieš paleisdami hibridinę sistemą, žr. eksploatacijos instrukciją ir kreipkitės į prekybos atstovą, kad patikrintų ",
	"AuxBattLowShrt": "12V akum. žemas įkr. lygis",
	"BattManagSysErrorLong": "Akumuliatoriaus valdymo sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"BattManagSysErrorShrt": "Akumuliatoriaus vald. sist. triktis",
	"BrakOverrideSysErrorLong": "Stabdžio jungiklio triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"BrakOverrideSysErrorShrt": "Stabdžio atjungimo sist. triktis",
	"BrakeSysErrorLong": "Žemas stabdžių skysčio lygis arba stabdžių sistemos triktis.  Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"BrakeSysErrorShrt": "Stabdžių sistemos triktis",
	"BrakeSystemErrorLong": "Elektroniniu būdu valdomos stabdžių sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"BrakeSystemErrorShrt": "Stabdžių sistemos triktis",
	"BsmSystemErrorLong": "Blind Spot Monitoring (BSM) /Rear Cross Traffic Alert (RCTA) sistemos triktis. Tikrinkite galinio buferio paviršių ir nuvalykite, jei nešvarus arba padengtas sniegu. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"BsmSystemErrorShrt": "BSM triktis",
	"ChargSysMalHighPrt": "Įkrovimo sistemos triktis. Nedelsdami sustokite saugioje vietoje.",
	"ChargingSysErrorLong": "Įkrovimo sistemos triktis. Važiuodami toliau galite sugadinti automobilį.  Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"ChargingSysErrorShrt": "Įkrovimo sistemos triktis",
	"ChrgSysErrorLong": "Įkrovimo sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"ChrgSysErrorShrt": "Įkrovimo sistemos triktis",
	"ControlSystemErrorLong": "Stovėjimo padėties kontrolės sistemos triktis. Jei nepatikrinsite, gali susidaryti viena iš šių situacijų: ・Stovėjimo užrakto mechanizmas gali neveikti. Pastatykite lygioje vietoje ir patikimai įjunkite stovėjimo stabdį.\n・Maitinimo jungiklis gali neišsijungti. Pakartotinai spausdami maitinimo jungiklį išjunkite.\n・ Ekranas „Įjunkite stovėjimo stabdį stovėdami“ dings važiuojant ir atsiras sustojus.\nNedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n",
	"ControlSystemErrorShrt": "Stovėjimo pad. kontr. sist. triktis",
	"DPFErrorLong": "Dyzelino dalelių filtro (DPF) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"DPFErrorShrt": "DPF klaida",
	"DRSSSysErrorLong": "Įvyko klaida DRSS sistemoje. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
	"DRSSSysErrorShrt": "DRSS triktis",
	"DriveBattDropLong": "Likutinė energija aukštos įtampos akumuliatoriuje yra žema, nes pavarų svirtis ilgą laiką buvo neutralioje padėtyje. Neutralioje padėtyje įkrovimas neįmanomas. Sustoję ilgesniam laikui perjunkite į stovėjimo padėtį.\nPrireikus iš naujo paleiskite hibridinę sistemą paspausdami maitinimo jungiklį.\n",
	"DriveBattDropShrt": "Aukštos įt. akum. žemas įkr. l.",
	"DropKeyBattChrgLong": "Senka rakto maitinimo elementas. Nedelsdami pakeiskite rakto maitinimo elementą.",
	"DropKeyBattChrgShrt": "Senka rakto maitinimo elementas",
	"DscSysErrorLong": "Dynamic Stability Control sistemos (DSC), Traction Control System (TCS) arba Hill Launch Assist (HLA) sistemos triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"DscSysErrorShrt": "DSC triktis",
	"DscSystemErrorLong": "Dinaminio stabilumo valdymo sistemos (DSC) arba traukos valdymo sistemos (TCS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"DscSystemErrorShrt": "DSC triktis",
	"EcbSysErrorLong": "Regeneracinio stabdymo arba elektroniniu būdu valdomos stabdžių sistemos triktis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EcbSysErrorShrt": "Stabdžių sistemos triktis",
	"ElectricParkingBrakeHighLong": "Įvyko stovėjimo stabdžio sistemos gedimas.\nKreipkitės į Mazda prekybos atstovą dėl patikros.",
	"ElectricParkingBrakeLong": "Įvyko stovėjimo stabdžio sistemos gedimas.\nKreipkitės į Mazda prekybos atstovą dėl patikros.",
	"ElectricParkingBrakeShrt": "Netinkamai veikia stovėjimo stabdžio sistema",
	"ElectricVacuumPumpSystemMalfunctionLong": "Įvyko elektrinio vakuumo siurblio sistemos gedimas.\nJei šios problemos neišspręsite, sistema gali nustoti veikusi, o dėl to gali kilti pavojus arba įvykti gedimas.\nNedelsdami kreipkitės į Mazda prekybos atstovą dėl patikros.",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Netinkamai veikia elektrinio vakuumo siurblio sistema",
	"EloopChargingLong": "i‑ELOOP įkrovimas. Varikliui veikiant patikrinkite, ar įkrovimas baigėsi ir įspėjamoji lemputė užgeso. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EloopChargingShrt": "i‑ELOOP įkrovimas",
	"EloopSysErrorLong": "i‑ELOOP sistemos triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EloopSysErrorShrt": "i‑ELOOP sistemos triktis",
	"EngCoolntTempHighOnLong": "Variklis kaista. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir imkitės reikiamų veiksmų.  Žr. eksploatacijos instrukciją.",
	"EngCoolntTempHighOnShrt": "Aukšta aušinimo skysčio temp.",
	"EngOilPressureErrorLong": "Žemas variklio alyvos slėgis. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir patikrinkite variklio alyvos lygį. Įpilkite alyvos, jei reikia. Jei ši lemputė užsidega įpylus alyvos arba jei alyvos lygis tinkamas, nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EngOilPressureErrorShrt": "Variklyje žemas alyvos slėgis",
	"EngSystemErrorLong": "Variklio sistemos triktis.  Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EngSystemErrorShrt": "Variklio sistemos triktis",
	"EngineOilPressureErrorLong": "Žemas variklio alyvos slėgis. Nedelsdami sustokite saugioje vietoje, išjunkite variklį ir patikrinkite variklio alyvos lygį. Įpilkite alyvos, jei reikia. Jei ši lemputė užsidega įpylus alyvos arba jei alyvos lygis tinkamas, nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EngineOilPressureErrorShrt": "Variklyje žemas alyvos slėgis",
	"EngineWaterTempDropLong": "Variklio aušinimo skystis šaltas ir šildytuve/stiklo šildytuve nėra šilto oro.  Automobiliu galima važiuoti ir lemputei švytint, ir nešvytint.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"EngineWaterTempDropShrt": "Žema variklio auš. skys. temp.",
	"EngineWaterTempRiseLong": "Variklis pradeda kaisti. Važiuokite lėtai arba sustokite, kol lemputė nesiliaus mirksėti. Jei toliau mirksi net ir sustojus, imkitės reikiamų veiksmų. Žr. eksploatacijos instrukciją.",
	"EngineWaterTempRiseShrt": "Aukšta aušinimo skysčio temp.",
	"EngnCoolTempHighHighPrt": "Aukšta variklio aušinimo skysčio temperatūra. Nedelsdami sustokite saugioje vietoje.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
	"FOWMRCCDRSSRadarSoilingShrt": "FOW/MRCC/DRSS rad. triktis",
	"FOWMRCCRadarSoilingLong": "FOW/MRCC radaro (jutiklio) triktis. Nuvalykite visą priekinių grotelių emblemos paviršių, jei nešvarus arba padengtas sniegu.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"FOWMRCCRadarSoilingShrt": "FOW/MRCC radaro triktis",
	"FOWSysError": "FOW triktis",
	"FOWSysErrorLong": "Forward Obstruction Warning (FOW) sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"FWDSysErrorLong": "4WD sistemos triktis arba skiriasi galinių ir priekinių padangų dydis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"FWDSysErrorShrt": "4WD sistemos triktis",
	"FuelAirFilterCartReplacePeriodLong": "Reikia pakeisti degalų oro filtro kasetę.",
	"FuelAirFilterCartReplacePeriodShrt": "Reikia pakeisti kuro oro filtro kasetę",
	"FuelCapInspectionLong": "Galbūt netinkamai uždėtas degalų bako dangtelis. Patikrinkite, ar degalų bako dangtelis tinkamai uždėtas ir priveržtas.\nUždėjus ir tinkamai priveržus degalų bako dangtelį, ši lemputė neužges kelis važiavimo ciklus, kol nebus įsitikinta, kad sistemoje viskas gerai.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.\n",
	"FuelCapInspectionShrt": "Degalų bako dangtelio tikrinimas",
	"HBCLDWSSysErrorLong": "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSSysErrorLong_2": "High Beam Control (HBC) / Lane-keep Assist System (LAS) triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSSysErrorLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSSysErrorLong_4": "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) triktis. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSSysErrorShrt": "HBC/LDWS sistemos triktis",
	"HBCLDWSSysErrorShrt_2": "HBC/LAS sistemos triktis",
	"HBCLDWSSysErrorShrt_3": "ALH/LDWS sistemos triktis",
	"HBCLDWSSysErrorShrt_4": "ALH/LAS sistemos triktis",
	"HBCLDWSWindshieldFogLong": "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis. Pašildykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSWindshieldFogLong_2": "High Beam Control (HBC) / Lane-keep Assist System (LAS) triktis. Pašildykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSWindshieldFogLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) triktis. Pašildykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSWindshieldFogLong_4": "Adaptive LED Headlights (ALH) / Lane-keep Assist System (LAS) triktis. Pašildykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLDWSWindshieldFogShrt": "HBC/LDWS sistemos triktis",
	"HBCLDWSWindshieldFogShrt_2": "HBC/LAS sistemos triktis",
	"HBCLDWSWindshieldFogShrt_3": "ALH/LDWS sistemos triktis",
	"HBCLDWSWindshieldFogShrt_4": "ALH/LAS sistemos triktis",
	"HBCLLDWSCamDisconnectLong": "High Beam Control (HBC) /Lane Departure Warning System (LDWS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLLDWSCamDisconnectLong_2": "High Beam Control (HBC) / Lane-keep Assist System (LAS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLLDWSCamDisconnectLong_3": "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLLDWSCamDisconnectLong_4": "Adaptive LED Headlights (ALH) / Lane-keep Assist System (LAS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCLLDWSCamDisconnectShrt": "HBC/LDWS Kameros Triktis",
	"HBCLLDWSCamDisconnectShrt_2": "HBC/LAS Kameros Triktis",
	"HBCLLDWSCamDisconnectShrt_3": "ALH/LDWS Kameros Triktis",
	"HBCLLDWSCamDisconnectShrt_4": "ALH/LAS Kameros Triktis",
	"HBCSysErrorLong": "High Beam Control (HBC) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCSysErrorLong_2": "Adaptive LED Headlights (ALH) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HBCSysErrorShrt": "HBC triktis",
	"HBCSysErrorShrt_2": "ALH triktis",
	"HeadlightSystemErrorLongJ03": "Įvyko priekinių žibintų sistemos gedimas. Jei nuolatos mirksi įspėjamoji lemputė, kreipkitės į Mazda prekybos atstovą.",
	"HybrdSysMalHighPrt": "Hibridinės sistemos triktis. Nedelsdami sustokite saugioje vietoje.",
	"HybridSysErrorLong": "Hibridinės sistemos triktis. Važiuodami toliau galite sugadinti automobilį. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HybridSysErrorShrt": "Hibridinės sistemos triktis. ",
	"HybridSysOverheatLong": "Hibridinės sistemos triktis. Važiuodami toliau galite sugadinti automobilį. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"HybridSysOverheatShrt": "Hibridinė sistema perkaito",
	"IeloopChrgHighPrt": "i‑ELOOP įkrovimas. Varikliui veikiant patikrinkite, ar įkrovimas baigėsi ir įspėjamoji lemputė užgeso.",
	"IstopSysErrorLong": "i‑stop veikimas neįmanomas. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
	"IstopSysErrorShrt": "i‑stop sistemos triktis",
	"KeylesSysErrorLong": "Berakčio įėjimo triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"KeylesSysErrorShrt": "Berakčio įėjimo triktis",
	"LDWSSysErrorLong": "Lane Departure Warning System (LDWS) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"LDWSSysErrorLong_2": "Lane-keep Assist System (LAS) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"LDWSSysErrorShrt": "LDWS triktis",
	"LDWSSysErrorShrt_2": "LAS triktis",
	"LowBrakeFluidLong": "Žemas stabdžių skysčio lygis. Nedelsdami sustokite saugioje vietoje ir kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"LowBrakeFluidShrt": "Mažai stabdžių skysčio",
	"LowFuelLong": "Žemas degalų lygis bake. Greitu metu įpilkite degalų.",
	"LowFuelShrt": "Mažai degalų",
	"LowTireAirPressureFlatLong": "Jei žymiai sumažėja slėgis padangose, užsidega TPMS įspėjamoji lemputė, o jei padanga praduriama, užsidega ir pradurtos padangos įspėjamoji lemputė.\nJei praduriama padanga, pritaikyta važiuoti joje nesant oro, atsargiai automobiliu nuvažiuokite iki artimiausio Mazda prekybos salono, kad padangą pakeistų.\n",
	"LowTireAirPressureLong": "Žemas oro slėgis vienoje ar keliose padangose. \nTikrinkite oro slėgį padangose ir sureguliuokite tinkamą oro slėgį.  Sureguliavę slėgį padangose, spauskite jungiklį TPMS SET, kol išgirsite pyptelėjimą.",
	"LowTireAirPressureShrt": "Žemas slėgis padangose",
	"LowWasheFluidLong": "Žemas langų apiplovimo skysčio lygis. Įpilkite apliejiklio skysčio.",
	"LowWasheFluidShrt": "Mažai apliejiklio skysčio",
	"MRCCSysErrorLong": "Mazda Radar Cruise Control (MRCC) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"MRCCSysErrorShrt": "MRCC triktis",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) šiuo metu nepasiekiamas.",
	"MRCCUnavailableShrt": "MRCC nepasiekiamas",
	"NoWarnings": "Įspėjimų nerasta",
	"PowerSteeringSysErrorLong": "Elektrinio vairo stiprintuvo triktis. Sustokite saugioje vietoje ir išjunkite variklį.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"PowerSteeringSysErrorShrt": "Vairo stiprintuvo sistemos triktis",
	"PpositionRequestLong": "Perjunkite pavaros svirtį į stovėjimo padėtį. Tai atsitiko dėl vienos iš žemiau pateiktų priežasčių:・ Akumuliatoriaus sistema buvo įjungta arba išjungta, kai pavarų svirtis buvo ne stovėjimo padėtyje\n・ Vairuotojo durys buvo atidarytos, kai pavaros svirtis buvo padėtyje N, D arba B\n・ Likutinė aukštos įtampos akumuliatoriaus įkrova yra žema, nes pavara buvo neutralioje padėtyje ilgą laiką\nPrireikus paleiskite hibridinę sistemą iš naujo paspausdami maitinimo jungiklį.\n",
	"PpositionRequestShrt": "Stovėjimo padėties užklausa",
	"PreheatingDispLampLong": "Šildomos žvakės. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"PreheatingDispLampShrt": "Šildomos žvakės",
	"RoadSurfaceIcingCautionLong": "Lauko temperatūra yra 4 °C arba žemesnė. Važiuodami saugokitės apledėjusių kelio paviršių.",
	"RoadSurfaceIcingCautionShrt": "Įsp. dėl kelio paviršiaus apledėjimo",
	"RvmSysErrorLong": "Įvyko klaida RVM sistemoje. Tikrinkite galinio buferio paviršių ir nuvalykite, jei nešvarus arba padengtas sniegu.\nJei ši įspėjamoji lemputė toliau švies, kreipkitės į Mazda atstovą, kad patikrintų automobilį.\n",
	"RvmSysErrorShrt": "RVM triktis",
	"SBSBrakeMRCCUnavailableLong": "SBS stabdys/MRCC šiuo metu nepasiekiamas.",
	"SBSBrakeMRCCUnavailableShrt": "SBS stabdys / MRCC nep.",
	"SBSBrakeUnavailableLong": "SBS stabdys šiuo metu nepasiekiamas.",
	"SBSBrakeUnavailableShrt": "SBS stabdys nepasiekiamas",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
	"SBSMRCCDRSSRadarSoilingShrt": "SBS/MRCC/DRSS rad. triktis",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC radaras (jutiklis) užterštas. Nuvalykite visą radaro (jutiklio) paviršių.",
	"SBSMRCCRadarSoilingShrt": "SBS/MRCC radaro triktis",
	"SBSSysErrorLong": "Įvyko klaida SBS sistemoje. Kreipkitės į Mazda atstovą, kad patikrintų automobilį.",
	"SBSSysErrorShrt": "SBS triktis",
	"SCBSSysErrorLong": "Smart City Brake Support  (SCBS) triktis. Nedelsdami kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"SCBSSysErrorShrt": "SCBS triktis",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) šiuo metu nepasiekiama.",
	"SCBSUnavailableShrt": "SCBS nepasiekiama",
	"SCBSWindshieldSoilingLong": "Smart City Brake Support (SCBS) triktis. Nuvalykite priekinį stiklą.  Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"SCBSWindshieldSoilingShrt": "SCBS triktis",
	"SedimenterWarningLong": "Nusodinimo įtaise susikaupusio vandens kiekis viršija normą. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"SedimenterWarningShrt": "Nusodinimo įtaiso tikrinimas",
	"SystemInspectionLong": "Diferencialo alyvos temperatūra neįprastai aukšta arba susidarė didelis sukimosi skirtumas tarp priekinių ir galinių ratų (pvz., bandant išvažiuoti iš purvo). Sustokite saugioje vietoje ir tęskite kelionę, kai įspėjamoji lemputė užges. Jei ši lemputė toliau švies, kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"SystemInspectionShrt": "4WD sistemos tikrinimas",
	"TpmsSysErrorLong": "Slėgio padangose stebėjimo sistemos (TPMS) triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"TpmsSysErrorShrt": "TPMS sistemos triktis",
	"VehicleSysErrorLong": "Automobilio sistemos triktis. Kreipkitės į prekybos atstovą, kad patikrintų automobilį.",
	"VehicleSysErrorShrt": "Automobilio sistemos triktis",
	"WarningGuidance": "Įspėjimo nurodymai",
	"WarningSafetyMessage": "Saugos sumetimais įspėjimų nurodymai nerodomi.",
	"Warnings": "Įspėjimai",
	"brakeFluid": "Žemas stabdžių skysčio lygis",
	"engineOilPressure": "Variklio alyvos slėgis",
	"highVoltage": "Aukštos įtampos akum. išsikrovęs",
	"lowBattStartEngine": "Akum. išsikrovęs! Užveskite variklį!",
};

framework.registerAppDictLoaded("warnguide", "lt_LT");