var Localization_warnguideAppDict_sr_RS = {
	//"stringId" : "localString"
	"AbsSysErrorLong": "Neispravnost sistema protiv blokiranja kočnica (ABS).\nNeka prodavac odmah proveri vozilo.\n",
	"AbsSysErrorShrt": "Neispravnost ABS sistema",
	"AbsSystemErrorLong": "Neispravnost sistema protiv blokiranja kočnica (ABS).\nNeka prodavac odmah proveri vozilo.\n",
	"AbsSystemErrorShrt": "Neispravnost ABS sistema",
	"AccumulationDpfLong": "Čestice (PM) koje su nakupljene u filteru za čestice dizel goriva (DPF) su premašile regulacionu vrednost.\nVozite oko 10 do 15 minuta sa potpuno zagrejanim motorom (plavo svetlo za temperaturu je ugašeno) pri brzini od 10 mph (15km/h) ili više da biste eliminisali PM.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"AccumulationDpfShrt": " Akumulacija PM u DPF-u",
	"ActiveBonnetSystemMalfunctionLong": "Kvar na sistemu Active Bonnet. Ako ovaj indikator ostane upaljen ili nastavi da treperi odvezite vozilo na pregled.",
	"ActiveBonnetSystemMalfunctionShrt": "Kvar na sistemu Active Bonnet",
	"AfsSystemErrorLong": "Neispravnost prilagodljivog sistema prednjih svetala (AFS).  Ako ovaj indikator nastavi da treperi, neka prodavac proveri vozilo.",
	"AfsSystemErrorShrt": "Neispravnost AFS sistema",
	"AirbagSysPretensionerSysErrorLong": "Neispravnost vazdušnog jastuka/sigurnosnog pojasa. Neka prodavac odmah proveri vozilo",
	"AirbagSysPretensionerSysErrorShrt": "Neispr. sistem vazd.jast./predzat.",
	"AutoLevelSystemErrorLong": "Neispravnost sistema automatske nivelacije prednjih svetala. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"AutoLevelSystemErrorShrt": "Neispr. sistem autom. nivelacije",
	"AutoLevelSystemErrorShrtJ03": "Kvar sistema prednjih svetala",
	"AutoTransSysErrorLong": "Neispravnost automatskog menjača. Ako nastavite da vozite, može doći do oštećenja vozila.  Neka prodavac odmah proveri vozilo. ",
	"AutoTransSysErrorShrt": "Neispr.automat.menjača",
	"AuxBattLowLong": "Skoro prazan akomulator\n・Ako je ovaj indikator često upaljen tokom vožnje, možda je akumulator oslabio. Neka prodavac proveri vozilo.\n・Ako ovaj indikator konstantno upaljen i ne isključuje se akomulator vše ne radi. Pogledajte Priručnik za vlasnika pre uključivanja hibridnog sistema i neka prodavac proveri vozilo.",
	"AuxBattLowShrt": "Skoro prazan akomulator",
	"BattManagSysErrorLong": "Nesipravnost sistema upravljanja akumulatorom. Neka prodavac proveri vozilo.",
	"BattManagSysErrorShrt": "Neispr. sistem upr. akumulatorom",
	"BrakOverrideSysErrorLong": "Neispravnost prekidača kočnice.\nNeka prodavac odmah proveri vozilo.\n",
	"BrakOverrideSysErrorShrt": "Neispr. sistem prioriteta kočnice",
	"BrakeSysErrorLong": "Nivo kočionog ulja je nizak ili neispravnost kočionog sistema.  Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.",
	"BrakeSysErrorShrt": "Neispravnost kočionog sistema",
	"BrakeSystemErrorLong": "Neispravnost elektronski kontrolisanog kočionog sistema. Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.",
	"BrakeSystemErrorShrt": "Neispravnost kočionog sistema",
	"BsmSystemErrorLong": "Neispravnost Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nProverite da li postoje nepravilnosti na površini zadnjeg odbojnika i očistite ga ako je prljav ili pokriven snegom. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"BsmSystemErrorShrt": "Neispravnost BSM uređaja",
	"ChargSysMalHighPrt": "Neispravnost sistema punjenja. Odmah zaustavite vozilo na bezbednom mestu.",
	"ChargingSysErrorLong": "Neispravnost sistema punjenja. Ako nastavite da vozite, može doći do oštećenja vozila.  Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.",
	"ChargingSysErrorShrt": "Neispravnost sistema punjenja",
	"ChrgSysErrorLong": "Neispravnost sistema punjenja. Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.",
	"ChrgSysErrorShrt": "Neispravnost sistema punjenja",
	"ControlSystemErrorLong": "Neispravnost sistema za kontrolu parking položaja.\nAko se ne proveri, može dovesti do neke od sledećih situacija:\n・Mehanizam zaključavanja parkirnog položaja možda neće raditi. Parkirajte na ravnom mestu i sigurno aktivirajte ručnu kočnicu.\n・Prekidač za uključivanje/isključivanje napajanja možda neće da se isključi. Pritisnite prekidač za uključivanje/isključivanje napajanja više puta da biste ga isključili.\n・ Prikaz „Aktivirajte ručnu kočnicu kada parkirate“ će se isključiti tokom vožnje i uključiti kod zaustavljanja.\nNeka prodavac odmah proveri vozilo.\n",
	"ControlSystemErrorShrt": "Neispr. sistem za kontr. park. ",
	"DPFErrorLong": "Neispravan filter za čestice u dizel gorivu (DPF). Neka prodavac proveri vozilo.",
	"DPFErrorShrt": "Greška u DPF filteru",
	"DRSSSysErrorLong": "Postoji greška u DRSS sistemu.\nNeka prodavac Mazda automobila proveri vaše vozilo.\n",
	"DRSSSysErrorShrt": "Neispravnost DRSS sistema",
	"DriveBattDropLong": "Preostala struja u bateriji visokog napona slaba, jer je prenos bio dugo vremena u neutralnom položaju. Punjenje nije moguće u neutralnom položaju. Prebacite u parkirnu položaj ako dugo stojite. Ako je potrebno, ponovo pokrenite hibridni sistem pritiskom na prekidač za napajanje.",
	"DriveBattDropShrt": "Skoro prazna baterija visokog napona",
	"DropKeyBattChrgLong": "Baterija ključa je slaba. Odmah zamenite bateriju ključa.",
	"DropKeyBattChrgShrt": "Slaba baterija ključa",
	"DscSysErrorLong": "Neispravnost sistema Dynamic Stability Control (DSC), Traction Control System (TCS) ili Hill Launch Assist (HLA). Neka prodavac odmah proveri vozilo.",
	"DscSysErrorShrt": "Neispravnost DSC sistema",
	"DscSystemErrorLong": "Neispravnost sistema dinamičke kontrole stabilnosti (DSC) ili sistema kontrole vuče (TCS). Neka prodavac odmah proveri vozilo.",
	"DscSystemErrorShrt": "Neispravnost DSC sistema",
	"EcbSysErrorLong": "Neispravnost sistema regenerativnog kočenja ili elektronski kontrolisanog kočionog sistema. Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.",
	"EcbSysErrorShrt": "Neispravnost kočionog sistema",
	"ElectricParkingBrakeHighLong": "Došlo je do kvara u sistemu parkirne kočnice. Posavetujte se sa svojim Mazda dilerom radi pregleda.",
	"ElectricParkingBrakeLong": "Došlo je do kvara u sistemu parkirne kočnice. Posavetujte se sa svojim Mazda dilerom radi pregleda.",
	"ElectricParkingBrakeShrt": "Kvar sistema parkirne kočnice",
	"ElectricVacuumPumpSystemMalfunctionLong": "Došlo je do kvara u sistemu električne vakuumske pumpe. Ako ne rešite ovu grešku sistem može da otkaže, što će predstavljati neočekivanu opasnost ili dovesti do nepravilnog rada. Posavetujte se odmah sa svojim Mazda dilerom i zatražite pregled greške. ",
	"ElectricVacuumPumpSystemMalfunctionShrt": "Kvar sistema električne vakuumske pumpe",
	"EloopChargingLong": "i‑ELOOP se puni.\nDok motor radi, proverite da li je punjenje završeno i da li je indikator upozorenja ugašen. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"EloopChargingShrt": "Punjenje i‑ELOOP sistema",
	"EloopSysErrorLong": "Neispravnost i‑ELOOP sistema.\nAko ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"EloopSysErrorShrt": "Neispravnost i‑ELOOP sistema",
	"EngCoolntTempHighOnLong": "Motor se pregreva. Odmah zaustavite vozilo na bezbednom mestu, isključite motor i preduzmite odgovarajuće mere.  Pogledajte uputstvo za korisnike.",
	"EngCoolntTempHighOnShrt": "Visoka temp.rashl.tečnosti ",
	"EngOilPressureErrorLong": "Nizak pritisak motornog ulja.\nOdmah zaustavite vozilo na bezbednom mestu, isključite motor i proverite nivo motornog ulja. Dodajte ulje ako je neophodno.\nNeka prodavac odmah proveri vozilo ako se ovaj indikator upali odmah nakon dodavanja ulja ili ako je nivo motornog ulja u redu.\n",
	"EngOilPressureErrorShrt": " Nizak pritisak motornog ulja",
	"EngSystemErrorLong": "Neispravnost sistema motora.  Neka prodavac odmah proveri vozilo.",
	"EngSystemErrorShrt": "Neispravnost sistema motora",
	"EngineOilPressureErrorLong": "Nizak pritisak motornog ulja.\nOdmah zaustavite vozilo na bezbednom mestu, isključite motor i proverite nivo motornog ulja. Dodajte ulje ako je neophodno.\nNeka prodavac odmah proveri vozilo ako se ovaj indikator upali odmah nakon dodavanja ulja ili ako je nivo motornog ulja u redu.\n",
	"EngineOilPressureErrorShrt": "Nizak pritisak motornog ulja",
	"EngineWaterTempDropLong": "Rashladna tečnost motora je hladna i nema toplog vazduha za grejalicu/odmagljivač. Vozilo može da se vozi bez obzira na to da li je ovaj indikator upaljen ili ugašen.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"EngineWaterTempDropShrt": "Temp. rashl. tečnosti  je niska",
	"EngineWaterTempRiseLong": "Motor počinje da se zagreva. Vozite sporije ili zaustavite vozilo dok indikator ne prestane da treperi. Ako i dalje treperi, čak i nakon zaustavljanja vozila, preduzmite odgovarajuće mere. Pogledajte uputstvo za korisnike.",
	"EngineWaterTempRiseShrt": "Visoka temep.rashl.tečnosti ",
	"EngnCoolTempHighHighPrt": "Visoka temeprtura rashladne tečnosti u motoru. Odmah zaustavite vozilo na bezbednom mestu.",
	"FOWMRCCDRSSRadarSoilingLong": "FOW/MRCC/DRSS radar (senzor) je zaprljan.\nOčistite celu površinu radara (senzora).\n",
	"FOWMRCCDRSSRadarSoilingShrt": "Neispr. FOW/MRCC/DRSS radar",
	"FOWMRCCRadarSoilingLong": "Neispravnost FOW/MRCC radara (senzora). Očistite kompletnu površinu grba na prednjoj rešetki ako je prljava ili pokrivena snegom. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.  ",
	"FOWMRCCRadarSoilingShrt": "Neispravnost FOW/MRCC radara",
	"FOWSysError": "Neispravnost FOW sistema",
	"FOWSysErrorLong": "Neispravnost sistema Forward Obstruction Warning (FOW). Neka prodavac proveri vozilo.",
	"FWDSysErrorLong": "Neispravnost sistema pogona na 4 točka ili razlika u veličini prednjih i zadnjih pneumatika. Neka prodavac proveri vozilo.",
	"FWDSysErrorShrt": "Neispr. sistem pogona na 4 točka",
	"FuelAirFilterCartReplacePeriodLong": "Patrona filtera za gorivo-vazduh treba da se zameni.",
	"FuelAirFilterCartReplacePeriodShrt": "Zamenite filtere za gorivo-vazduh",
	"FuelCapInspectionLong": "Zatvarač otvora za ulivanje goriva možda nije pravilno postavljen.\nProverite da li je zatvarač otvora za ulivanje goriva pravilno postavljen i zategnut.\nNakon pravilnog postavljanja i zatezanja zatvarača otvora za ulivanje goriva, ovaj indikator se neće gasiti tokom nekoliko ciklusa vožnje dok se ne potvrdi da je sistem u redu.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"FuelCapInspectionShrt": "Provera čepa za gorivo",
	"HBCLDWSSysErrorLong": "Neispravnost High Beam Control (HBC)/Lane Departure Warning System (LDWS). Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSSysErrorLong_2": "Neispravnost High Beam Control (HBC)/Lane-keep Assist System (LAS). Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSSysErrorLong_3": "Neispravnost Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSSysErrorLong_4": "Nesipravnost Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSSysErrorShrt": "Neispravnost HBC/LDWS sistema",
	"HBCLDWSSysErrorShrt_2": "Neispravnost HBC/LAS sistema",
	"HBCLDWSSysErrorShrt_3": "Neispravnost ALH/LDWS sistema",
	"HBCLDWSSysErrorShrt_4": "Nesipravnost ALH/LAS sistema",
	"HBCLDWSWindshieldFogLong": "Neispravnost High Beam Control (HBC)/Lane Departure Warning System (LDWS). Odledite vetrobransko staklo.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSWindshieldFogLong_2": "Neispravnost High Beam Control (HBC)/Lane-keep Assist System (LAS). Odledite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSWindshieldFogLong_3": "Neispravnost Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Odledite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSWindshieldFogLong_4": "Neispravnost Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Odledite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLDWSWindshieldFogShrt": "Neispravnost HBC/LDWS sistema",
	"HBCLDWSWindshieldFogShrt_2": "Neispravnost HBC/LAS sistema",
	"HBCLDWSWindshieldFogShrt_3": "Neispravnost ALH/LDWS sistema",
	"HBCLDWSWindshieldFogShrt_4": "Neispravnost ALH/LAS sistema",
	"HBCLLDWSCamDisconnectLong": "Neispravnost High Beam Control (HBC)/Lane Departure Warning System (LDWS). Očistite vetrobransko staklo.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLLDWSCamDisconnectLong_2": "Neispravnost High Beam Control (HBC)/Lane-keep Assist System (LAS). Očistite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLLDWSCamDisconnectLong_3": "Neispravnost Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Očistite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLLDWSCamDisconnectLong_4": "Neispravnost Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Očistite vetrobransko staklo. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"HBCLLDWSCamDisconnectShrt": "Neispravnost HBC/LDWS kamere",
	"HBCLLDWSCamDisconnectShrt_2": "Neispravnost HBC/LAS kamere",
	"HBCLLDWSCamDisconnectShrt_3": "Neispravnost ALH/LDWS kamere",
	"HBCLLDWSCamDisconnectShrt_4": "Neispravnost ALH/LAS kamere",
	"HBCSysErrorLong": "High Beam Control (HBC). Neka prodavac proveri vozilo.",
	"HBCSysErrorLong_2": "Neispravnost Adaptive LED Headlights (ALH). Neka prodavac proveri vozilo.",
	"HBCSysErrorShrt": "Neispravnost HBC sistema",
	"HBCSysErrorShrt_2": "Neispravnost ALH sistema",
	"HeadlightSystemErrorLongJ03": "Došlo je do kvara u sistemu prednjih svetala. Ukoliko svetlo upozorenja neprekidno treperi, posavetujte se sa svojim Mazda dilerom.",
	"HybrdSysMalHighPrt": "Neispravnost hibridnog sistema. Odmah zaustavite vozilo na bezbednom mestu.",
	"HybridSysErrorLong": "Neispravnost hibridnog sistema.\nAko nastavite da vozite, može doći do oštećenja vozila. Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.\n",
	"HybridSysErrorShrt": "Neispravnost hibridnog sistema",
	"HybridSysOverheatLong": "Neispravnost hibridnog sistema.\nAko nastavite da vozite, može doći do oštećenja vozila. Odmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.\n",
	"HybridSysOverheatShrt": "Hibridni sistem se pregreva",
	"IeloopChrgHighPrt": "Punjenje i‑ELOOP –a. Dok motor radi proverite da li je punjenje završeno i da li je isključen indikator upozorenja.",
	"IstopSysErrorLong": "i‑stop ne može da radi. Neka prodavac Mazda automobila proveri vaše vozilo.",
	"IstopSysErrorShrt": "Neispravnost i‑stop sistema",
	"KeylesSysErrorLong": "Neispravnost sistema daljinskog zaključavanja i otključavanja. Neka prodavac proveri vozilo.",
	"KeylesSysErrorShrt": "Neispr.sist.dalji.zaklj. i otklj.",
	"LDWSSysErrorLong": "Neispravnost Lane Departure Warning System (LDWS). Neka prodavac proveri vozilo.",
	"LDWSSysErrorLong_2": "Neispravnost Lane-keep Assist System (LAS). Neka prodavac proveri vozilo.",
	"LDWSSysErrorShrt": "Neispravnost LDWS sistema",
	"LDWSSysErrorShrt_2": "Neispravnost LAS",
	"LowBrakeFluidLong": "Nivo kočionog ulja je nizak.\nOdmah zaustavite vozilo na bezbednom mestu i neka prodavac proveri vozilo.\n",
	"LowBrakeFluidShrt": "Nizak nivo kočionog ulja",
	"LowFuelLong": "Nizak nivo goriva u rezervoaru. Dopunite gorivo što pre.",
	"LowFuelShrt": "Nizak nivo goriva",
	"LowTireAirPressureFlatLong": "Ukoliko se pritisak u pneumatiku naglo smanji nakon što se upali TPMS upozoravajuće svetlo ili ako se pneumatik probuši, pali se i upozoravajuće svetlo za ispumpani pneumatik.  Ukoliko se probuši „run-flat“ pneumatik, pažljivo upravljajte vozilom do najbližeg Mazda dilera i obavite zamenu pneumatika.",
	"LowTireAirPressureLong": "Proverite pritisak vazduha u pneumaticima i podesite pravilan pritisak vazduha.\nPretisnite prekidač TPMS SET nakon podešavanja pritiska u pneumaticima dok ne čujete zvučni signal.",
	"LowTireAirPressureShrt": "Nizak pritisak vazduha u pneumatiku",
	"LowWasheFluidLong": "Nivo tečnosti za pranje vetrobrana je nizak. Dopunite tečnost za pranje vetrobrana.",
	"LowWasheFluidShrt": "Nizak nivo tečnosti za vetrobran",
	"MRCCSysErrorLong": "Neispravnost Mazda Radar Cruise Control (MRCC). Neka prodavac proveri vozilo.",
	"MRCCSysErrorShrt": "Neispravan MRCC",
	"MRCCUnavailableLong": "Mazda Radar Cruise Control (MRCC) trenutno nije dostupan.",
	"MRCCUnavailableShrt": "MRCC nije dostupan",
	"NoWarnings": "Upozorenja nisu pronađena",
	"PowerSteeringSysErrorLong": "Neispravnost električnog servo upravljača. Zaustavite vozilo na bezbednom mestu i isključite motor.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"PowerSteeringSysErrorShrt": "Neispr. sistem servo upravljača",
	"PpositionRequestLong": "Prebacite menjač u parkirni položaj.\nDo ovoga dolazi zbog jednog od sledećih slučajeva:\n・ Sistem akumulatora je pokrenut ili zaustavljen sa menjačem postavljenim u položaj koji nije parkirni\n・ Vrata na strani vozača su bila otvorena dok je menjač bio u položaju N, D ili B\n・ Baterija visokog napona je skoro prazna, jer je prijenos bio je u neutralnom položaju dugo vremena.\nAko je potrebno, ponovo pokrenite hibridni sistem pritiskom na prekidač za uključivanje/isključivanje napajanja.",
	"PpositionRequestShrt": "Zahtev za parkirni položaj",
	"PreheatingDispLampLong": "Grejači se zagrevaju unapred. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"PreheatingDispLampShrt": "Grejači se zagrevaju unapred",
	"RoadSurfaceIcingCautionLong": "Spoljana temperatura je 4°C ili niža. Pazite na zaleđene površine puta dok vozite.",
	"RoadSurfaceIcingCautionShrt": "Budite oprezni na zaleđenom putu",
	"RvmSysErrorLong": "Postoji greška u RVM sistemu.\nProverite da li postoje nepravilnosti na površini zadnjeg odbojnika i očistite ga ako je prljav ili pokriven snegom.\nAko ova lampica upozorenja ostane upaljena, neka prodavac Mazda automobila proveri vaše vozilo.\n",
	"RvmSysErrorShrt": "Neispravnost RVM uređaja",
	"SBSBrakeMRCCUnavailableLong": "SBS kočnica/MRCC trenutno nije dostupan.",
	"SBSBrakeMRCCUnavailableShrt": "SBS kočnica/MRCC nije dostupan",
	"SBSBrakeUnavailableLong": "SBS kočnica trenutno nije dostupna.",
	"SBSBrakeUnavailableShrt": "SBS kočnica nije dostupna",
	"SBSMRCCDRSSRadarSoilingLong": "SBS/MRCC/DRSS radar (senzor) je zaprljan.\nOčistite celu površinu radara (senzora).\n",
	"SBSMRCCDRSSRadarSoilingShrt": "Neispr. SBS/MRCC/DRSS radar",
	"SBSMRCCRadarSoilingLong": "SBS/MRCC radar (senzor) je zaprljan.\nOčistite celu površinu radara (senzora).\n",
	"SBSMRCCRadarSoilingShrt": "Neispravnost SBS /MRCC radara",
	"SBSSysErrorLong": "Postoji greška u SBS sistemu.\nNeka prodavac Mazda automobila proveri vaše vozilo.\n",
	"SBSSysErrorShrt": "Neispravnost SBS",
	"SCBSSysErrorLong": "Neispravnost Smart City Brake Support (SCBS). Neka prodavac odmah proveri vozilo.",
	"SCBSSysErrorShrt": "Neispravnost SCBS",
	"SCBSUnavailableLong": "Smart City Brake Support (SCBS) trenutno nije dostupan.",
	"SCBSUnavailableShrt": "SCBS nije dostupan",
	"SCBSWindshieldSoilingLong": "Neispravnost Smart City Brake Support (SCBS). Očistite vetrobransko staklo.  Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.",
	"SCBSWindshieldSoilingShrt": "Neispravnost SCBS",
	"SedimenterWarningLong": "Količina vode koja se sakuplja u taložniku prekoračuje procenjenu količinu.\nAko ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"SedimenterWarningShrt": "Pregled taložnika",
	"SystemInspectionLong": "Diferencijalna temperatura ulja je abnormalno visoka ili je došlo do velike razlike u rotaciji prednjih i zadnjih pneumatika (kao što se dešava kada pokušavate da izađete iz blata).\nZaustavite vozilo na bezbednom mestu i nastavite sa vožnjom nakon što se indikator upozorenja ugasi. Ako ovaj indikator ostane upaljen, neka prodavac proveri vozilo.\n",
	"SystemInspectionShrt": "Neispr.sist. za kontr.pog.na 4 t.",
	"TpmsSysErrorLong": "Neispravnost sistema za nadzor pritiska u pneumaticima (TPMS). Neka prodavac proveri vozilo.",
	"TpmsSysErrorShrt": "Neispr.sist. za kontr.pritis.u gumama",
	"VehicleSysErrorLong": "Neispravnost sistema vozila. Neka prodavac proveri vozilo.",
	"VehicleSysErrorShrt": "Neispravnost sistema vozila",
	"WarningGuidance": "Upute upozorenja",
	"WarningSafetyMessage": "Iz razloga bezbednosti, upozoravajuće uputstvo nije prikazano.",
	"Warnings": "Upozorenja",
	"brakeFluid": "Nizak nivo tečnosti za kočnice",
	"engineOilPressure": "Pritisak ulja u motoru",
	"highVoltage": "Bat. vis.volt.skoro prazana",
	"lowBattStartEngine": "Nizak akom.! Uključ.motor!",
};

framework.registerAppDictLoaded("warnguide", "sr_RS");