var Localization_contactsAppDict_sk_SK = {
	//"stringId" : "localString"
	"AccessDenied": "Prístup do telefónneho zoznamu zamietnutý",
	"Address": "Adresa:",
	"CHDownloadFailed": "Nemožno prevziať históriu hovorov.",
	"CHImportUnsupported": "Importovanie histórie hovorov toto zariadenie nepodporuje.",
	"CancelImport": "Zrušiť import",
	"CancellingImport": "Načítavanie sa ruší",
	"ConatctImport": "Načítať kontakt",
	"ConnFailed": "Nedalo sa pripojiť",
	"ConnectionLost": "Strata spojenia",
	"ContactReadUnsuccess": "Prečítanie mena kontaktu bolo neúspešné.",
	"ContactRestoredInfo": "Kontakt bude obnovený pri automatickom preberaní kontaktov.",
	"ContactsFull": "Pamäť kontaktov je plná.",
	"DeleteError": "Nemožno odstrániť kontakt",
	"DeleteInProgress": "Kontakt sa odstraňuje",
	"DeleteSuccessMsg": "Všetky kont. úspešne odstránené.",
	"DeleteSuccessSingle": "Kontakt úspešne odstránený",
	"DeviceConnectFailed": "Nie je možné pripojiť sa k zariadeniu.",
	"EditContacts": "Upraviť kontakty",
	"ErrorUnknown": "Neznáma chyba",
	"HomePhnNumber": "Domov:",
	"ImportAllContacts": "Importovať všetky kontakty",
	"ImportConfirm": "Skontrolujte svoje mobilné zariadenie. Na prevzatie sa môže vyžadovať povolenie.",
	"ImportError": "Nie je možné prevz. zoznam kont.",
	"ImportFailureSbn": "Preberanie neúspešné",
	"ImportProgress": "Kontakty sa načítavajú",
	"ImportSuccess": "Načítanie {ImportedEntries} z  {TotalEntries} kontaktov prebehlo úspešne.",
	"ImportSuccessSbn": "Import úspešný",
	"ImportUnsupported": "Importovanie zoznamu kontaktov nie je týmto zariadením podporované.",
	"MobilePhnNumber": "Mobil:",
	"NoChSupport": "Telefón nepodporuje históriu volaní",
	"NoImportSupport": "Telefón nepodporuje import",
	"OtherPhnNumber": "Iné:",
	"PhonebookFull": "Telefónny zoznam plný",
	"PhonebookNotAvailable": "Telefónny zoznam nie je k dispozícii",
	"ReadContact": "Čítanie mena kontaktu",
	"RemoveContact": "Odstrániť kontakt",
	"SelectContact": "Vybrať kontakt",
	"SelectFavoritesCurrentContact": "Pridať kontakt do obľúbených",
	"SelectRemove": "Chcete odstrániť kontakt? Kontakty sa z mobilného zariadenia neodstránia.",
	"SelectedContactImport": "Import zvoleného kontaktu",
	"SingleImportTimeout": "Časový limit samostatného importu",
	"SpeedThresholdExceeded": "Prekročený limit rýchlosti",
	"SystemError": "Systémová chyba",
	"TimeOut": "Ukončenie o ({timeout}) sekúnd",
	"TypeDisambTitle": "Zvoľte číslo",
	"UnknownError": "Chyba neznámeho pôvodu",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Vyberte kontakt pre načítanie z mobilného zariadenia.",
	"WorkPhnNumber": "Práca:",
};

framework.registerAppDictLoaded("contacts", "sk_SK");