var Localization_contactsAppDict_nl_NL = {
	//"stringId" : "localString"
	"AccessDenied": "Toegang tot telefoonboek geweigerd",
	"Address": "Adres:",
	"CHDownloadFailed": "Downloaden oproepgeschiedenis mislukt.",
	"CHImportUnsupported": "Oproepgeschiedenis import wordt niet ondersteund door dit apparaat",
	"CancelImport": "Import annuel.",
	"CancellingImport": "Import annuleren",
	"ConatctImport": "Import. Contact.",
	"ConnFailed": "Verbinding mislukt",
	"ConnectionLost": "Verbinding Verbroken",
	"ContactReadUnsuccess": "Naam contactpersoon lezen mislukt",
	"ContactRestoredInfo": "Contact wordt hersteld als automatisch downloaden van contacten is ingeschakeld.",
	"ContactsFull": "De opslagruimte voor contactpersonen is vol.",
	"DeleteError": "Kan contactpersoon niet verwijderen",
	"DeleteInProgress": "Contactpersoon verwijderen",
	"DeleteSuccessMsg": "Alle contact. succesvol verwijderd.",
	"DeleteSuccessSingle": "Contactper. Succesvol Verwijderd",
	"DeviceConnectFailed": "Verbinding met apparaat mislukt.",
	"EditContacts": "Contactpersonen bewerken",
	"ErrorUnknown": "Onbekende fout",
	"HomePhnNumber": "Thuis:",
	"ImportAllContacts": "Alle contactpersonen importeren",
	"ImportConfirm": "Controleer uw mobiele apparaat. Toestemming om te downloaden kan nodig zijn.",
	"ImportError": "Cont. kon niet worden gedownload.",
	"ImportFailureSbn": "Import mislukt",
	"ImportProgress": "Contacten importeren",
	"ImportSuccess": "{ImportedEntries} van {TotalEntries} contactpers. zijn geïmport.",
	"ImportSuccessSbn": "Importeren gelukt",
	"ImportUnsupported": "Import contacten niet ondersteund door dit apparaat",
	"MobilePhnNumber": "Mobiel:",
	"NoChSupport": "Telefoon ondersteunt geen import van belhistorie",
	"NoImportSupport": "Telefoon ondersteunt geen import",
	"OtherPhnNumber": "Andere:",
	"PhonebookFull": "Telefoonboek vol",
	"PhonebookNotAvailable": "Telefoonboek niet beschikbaar",
	"ReadContact": "Contactpersoon Naam Lezen",
	"RemoveContact": "Contactpersoon Verwijderen",
	"SelectContact": "Selecteer een contactpersoon",
	"SelectFavoritesCurrentContact": "Contact Toevoegen aan Favorieten",
	"SelectRemove": "Wilt u een contactpersoon verwijderen? De contactpersonen worden niet van het mobiele apparaat verwijderd.",
	"SelectedContactImport": "Geselecteerde contactpers. import.",
	"SingleImportTimeout": "Time-out enkele invoer",
	"SpeedThresholdExceeded": "Snelheidsgrens overschreden",
	"SystemError": "Systeemfout",
	"TimeOut": "Time-out over ({timeout}) sec.",
	"TypeDisambTitle": "Selecteer een nummer",
	"UnknownError": "Reden foutmelding onbekend",
	"VrHelp_Contacts_Help_Left1": "Naam van Contactpersoon",
	"VrHelp_Contacts_Help_Left2": "Toevoegen aan Favorieten",
	"VrHelp_Contacts_Help_Left3": "Contactpersonen Bewerken",
	"VrHelp_EditContacts_Help1_Left1": "Alles Contactpersonen Importeren",
	"VrHelp_EditContacts_Help1_Left2": "Geselecteerde Contact Importeren",
	"WaitForPhoneData": "Selecteer een Contactpersoon om te importeren vanuit het mobiele apparaat.",
	"WorkPhnNumber": "Werk:",
};

framework.registerAppDictLoaded("contacts", "nl_NL");