var Localization_contactsAppDict_en_US = {
	//"stringId" : "localString"
	"AccessDenied": "Access Denied",
	"Address": "Address:",
	"CHDownloadFailed": "Failed to Import Call History",
	"CHImportUnsupported": "Call History Import is not supported by this device.",
	"CancelImport": "Cancel Import",
	"CancellingImport": "Canceling Import",
	"ConatctImport": "Import Contacts",
	"ConnFailed": "Unable to connect. Please check your device.",
	"ConnectionLost": "Connection lost. Please check your device.",
	"ContactReadUnsuccess": "Read Contact Name Unsuccessful",
	"ContactRestoredInfo": "Contact will be restored if Automatic Contacts Import Setting is On.",
	"ContactsFull": "Contact storage is full.",
	"DeleteError": "Unable to Remove Contact",
	"DeleteInProgress": "Removing Contact",
	"DeleteSuccessMsg": "All Contacts Successfully Removed",
	"DeleteSuccessSingle": "Contact Successfully Removed ",
	"DeviceConnectFailed": "Could not connect to the device.",
	"EditContacts": "Edit Contacts",
	"ErrorUnknown": "Unknown Error",
	"HomePhnNumber": "Home:",
	"ImportAllContacts": "Import All Contacts",
	"ImportConfirm": "Please check your mobile device. Permission to import may be required.",
	"ImportError": "Unable to Import Contacts",
	"ImportFailureSbn": "Unable to Import",
	"ImportProgress": "Importing Contacts",
	"ImportSuccess": "{ImportedEntries} of {TotalEntries} contacts were imported.",
	"ImportSuccessSbn": "Import Success",
	"ImportUnsupported": "Contact list import is not supported by this device.",
	"MobilePhnNumber": "Mobile:",
	"NoChSupport": "Your device does not support Call History Import. ",
	"NoImportSupport": "Your device does not support Import.",
	"OtherPhnNumber": "Other:",
	"PhonebookFull": "System Memory Full",
	"PhonebookNotAvailable": "Contact Format Not Supported",
	"ReadContact": "Read Contact Name",
	"RemoveContact": "Remove Contact",
	"SelectContact": "Select a Contact by Line Number",
	"SelectFavoritesCurrentContact": "Add Contact to Favorites",
	"SelectRemove": "Would you like to remove contact? Contacts will not be removed from the Mobile Device.",
	"SelectedContactImport": "Import Selected Contact",
	"SingleImportTimeout": "Import Timeout. Please check your device.",
	"SpeedThresholdExceeded": "While the Vehicle is in Motion",
	"SystemError": "System Error",
	"TimeOut": "Timeout in ({timeout}) seconds",
	"TypeDisambTitle": "Select a Line Number",
	"UnknownError": "Error Reason Not Known",
	"VrHelp_Contacts_Help_Left1": "Contact Name",
	"VrHelp_Contacts_Help_Left2": "Add Contact to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Select a Contact to import from the Mobile Device.",
	"WorkPhnNumber": "Work:",
};

framework.registerAppDictLoaded("contacts", "en_US");