var Localization_contactsAppDict_fi_FI = {
	//"stringId" : "localString"
	"AccessDenied": "Puhelinluettelon käyttö estetty",
	"Address": "Osoite:",
	"CHDownloadFailed": "Puheluhistorian lataaminen ei onnistunut.",
	"CHImportUnsupported": "Laite ei tue historiatietojen tuontia.",
	"CancelImport": "Per. tuonti",
	"CancellingImport": "Tuontia peruutetaan",
	"ConatctImport": "Yht.tiedon tuonti",
	"ConnFailed": "Yhteysvirhe",
	"ConnectionLost": "Yhteys katkesi",
	"ContactReadUnsuccess": "Yhteystiedon nimen luku epäonnistui",
	"ContactRestoredInfo": "Yht.tieto palautetaan, jos autom. lataus on päällä.",
	"ContactsFull": "Yhteystietojen tallennustila on täynnä.",
	"DeleteError": "Yhteystiedon poistaminen ei onnistunut",
	"DeleteInProgress": "Poistetaan yhteystietoa",
	"DeleteSuccessMsg": "Kaikkien yhteyst. poist. onnistui.",
	"DeleteSuccessSingle": "Yhteystiedon poistaminen onnistui ",
	"DeviceConnectFailed": "Laitteen yhdistäminen epäonnistui.",
	"EditContacts": "Muokkaa yhteystietoja",
	"ErrorUnknown": "Tuntematon virhe",
	"HomePhnNumber": "Koti:",
	"ImportAllContacts": "Tuo kaikki yhteystiedot",
	"ImportConfirm": "Tarkista mobiililaitteesi. Lataaminen saattaa vaatia luvan.",
	"ImportError": "Yhteystiet. lataaminen ei onnist.",
	"ImportFailureSbn": "Tuonti epäonnistui",
	"ImportProgress": "Tuodaan yhteystietoja",
	"ImportSuccess": "Tuotiin {ImportedEntries} / {TotalEntries} yhteystietoa.",
	"ImportSuccessSbn": "Tuonti onnistui",
	"ImportUnsupported": "Laite ei tue yhteystietoluettelon tuontia.",
	"MobilePhnNumber": "Matkapuhelin:",
	"NoChSupport": "Puhelin ei tue puheluhistorian tuontia",
	"NoImportSupport": "Puhelin ei tue tuontitoimintoa",
	"OtherPhnNumber": "Muu:",
	"PhonebookFull": "Puhelinluettelo täynnä",
	"PhonebookNotAvailable": "Puhelinluettelo ei ole käytettävissä",
	"ReadContact": "Lue yhteystiedon nimi",
	"RemoveContact": "Poista yhteystieto",
	"SelectContact": "Valitse yhteystieto",
	"SelectFavoritesCurrentContact": "Lisää yhteystieto suosikkeihin",
	"SelectRemove": "Haluatko poistaa yhteystiedon? Yhteystietoja ei poisteta mobiililaitteesta.",
	"SelectedContactImport": "Tuo valittu yhteystieto",
	"SingleImportTimeout": "Yhden tuonnin aikakatkaisu",
	"SpeedThresholdExceeded": "Nopeusrajoitus ylitetty",
	"SystemError": "Järjestelmävirhe",
	"TimeOut": "Aikakatkaisu ({timeout}) s kuluttua",
	"TypeDisambTitle": "Valitse numero",
	"UnknownError": "Virhe, jonka syy ei ole tiedossa",
	"VrHelp_Contacts_Help_Left1": "Yhteystiedon nimi",
	"VrHelp_Contacts_Help_Left2": "Lisää suosikkeihin",
	"VrHelp_Contacts_Help_Left3": "Muokkaa yhteystietoja",
	"VrHelp_EditContacts_Help1_Left1": "Tuo kaikki yhteystiedot",
	"VrHelp_EditContacts_Help1_Left2": "Tuo valittu yhteystieto",
	"WaitForPhoneData": "Valitse mobiililaitteesta tuotava yhteystieto.",
	"WorkPhnNumber": "Työ:",
};

framework.registerAppDictLoaded("contacts", "fi_FI");