var Localization_contactsAppDict_ja_JP = {
	//"stringId" : "localString"
	"AccessDenied": "連絡先へアクセスできませんでした。",
	"Address": "住所 : ",
	"CHDownloadFailed": "発着信履歴を同期できませんでした。",
	"CHImportUnsupported": "ご使用の携帯機器は、発着信履歴の\n同期機能に対応していません。",
	"CancelImport": "同期中止",
	"CancellingImport": "キャンセル中...",
	"ConatctImport": "連絡先の同期",
	"ConnFailed": "接続に失敗しました。",
	"ConnectionLost": "携帯機器に接続できませんでした。",
	"ContactReadUnsuccess": "名前を読み上げることが\nできませんでした。",
	"ContactRestoredInfo": "連絡先自動同期設定がONの場合は、\n次回起動時に再度同期されます。",
	"ContactsFull": "連絡先ストレージが一杯です。",
	"DeleteError": "連絡先を削除できませんでした。",
	"DeleteInProgress": "削除中...",
	"DeleteSuccessMsg": "すべての連絡先を削除しました。",
	"DeleteSuccessSingle": "連絡先を削除しました",
	"DeviceConnectFailed": "携帯機器に接続できませんでした。",
	"EditContacts": "連絡先を編集",
	"ErrorUnknown": "不明なエラーです。",
	"HomePhnNumber": "自宅 : ",
	"ImportAllContacts": "すべての連絡先を同期",
	"ImportConfirm": "携帯機器を確認してください。\n機器によっては同期の許可が必要です。",
	"ImportError": "連絡先を同期できませんでした。",
	"ImportFailureSbn": "同期失敗",
	"ImportProgress": "連絡先を同期中...",
	"ImportSuccess": "{TotalEntries}件中 {ImportedEntries}件 の\n連絡先が同期されました。",
	"ImportSuccessSbn": "同期完了",
	"ImportUnsupported": "ご使用の携帯機器は、\n連絡先の同期機能に対応していません。",
	"MobilePhnNumber": "携帯 : ",
	"NoChSupport": "ご使用の機器は、\n履歴機能に対応していません。",
	"NoImportSupport": "ご使用の機器は、連絡先の\n同期機能に対応していません。",
	"OtherPhnNumber": "その他 : ",
	"PhonebookFull": "連絡先の件数が上限に達しました。",
	"PhonebookNotAvailable": "連絡先は利用できません。",
	"ReadContact": "名前の発音を確認",
	"RemoveContact": "連絡先を削除",
	"SelectContact": "連絡先を選択してください",
	"SelectFavoritesCurrentContact": "お気に入りに追加",
	"SelectRemove": "連絡先を削除しますか？\n連絡先は携帯機器からは\n削除されません。",
	"SelectedContactImport": "選択した連絡先を同期",
	"SingleImportTimeout": "タイムアウトしました。",
	"SpeedThresholdExceeded": "走行中は使用できません。",
	"SystemError": "システムエラー",
	"TimeOut": "タイムアウトまで : {timeout} 秒",
	"TypeDisambTitle": "番号を選択してください",
	"UnknownError": "原因不明のエラーが発生しました。",
	"VrHelp_Contacts_Help_Left1": "(名前)",
	"VrHelp_Contacts_Help_Left2": "お気に入りに追加",
	"VrHelp_Contacts_Help_Left3": "連絡先を編集",
	"VrHelp_EditContacts_Help1_Left1": "すべての連絡先を同期",
	"VrHelp_EditContacts_Help1_Left2": "選択した連絡先を同期",
	"WaitForPhoneData": "ご使用の携帯機器から同期する連絡先を選択してください。",
	"WorkPhnNumber": "勤務先 : ",
};

framework.registerAppDictLoaded("contacts", "ja_JP");