var Localization_contactsAppDict_zh_CN = {
	//"stringId" : "localString"
	"AccessDenied": "已拒绝电话簿访问",
	"Address": "地址:",
	"CHDownloadFailed": "无法下载通话记录。",
	"CHImportUnsupported": "此设备不支持通话记录导入。",
	"CancelImport": "取消导入",
	"CancellingImport": "正在取消导入",
	"ConatctImport": "联系人导入",
	"ConnFailed": "连接失败",
	"ConnectionLost": "连接丢失",
	"ContactReadUnsuccess": "读取联系人姓名失败",
	"ContactRestoredInfo": "如果打开自动联系人下载设置，联系人将恢复。",
	"ContactsFull": "联系人存储空间已满。",
	"DeleteError": "无法移除联系人",
	"DeleteInProgress": "正在移除联系人",
	"DeleteSuccessMsg": "已成功移除所有联系人。",
	"DeleteSuccessSingle": "成功移除联系人 ",
	"DeviceConnectFailed": "无法连接到设备。",
	"EditContacts": "编辑联系人",
	"ErrorUnknown": "未知错误",
	"HomePhnNumber": "住宅电话:",
	"ImportAllContacts": "导入所有联系人",
	"ImportConfirm": "请检查您的移动设备。可能需要下载权限。",
	"ImportError": "无法下载联系人列表。",
	"ImportFailureSbn": "导入失败",
	"ImportProgress": "正在导入联系人",
	"ImportSuccess": "导入了{ImportedEntries}/{TotalEntries}的联系人。",
	"ImportSuccessSbn": "导入成功",
	"ImportUnsupported": "此设备不支持联系人列表导入。",
	"MobilePhnNumber": "手机:",
	"NoChSupport": "电话不支持通话记录导入",
	"NoImportSupport": "电话不支持导入",
	"OtherPhnNumber": "其它电话:",
	"PhonebookFull": "电话簿已满",
	"PhonebookNotAvailable": "未获得电话簿",
	"ReadContact": "读取联系人姓名",
	"RemoveContact": "移除联系人",
	"SelectContact": "选择一名联系人",
	"SelectFavoritesCurrentContact": "将联系人添加到收藏夹",
	"SelectRemove": "是否想要移除联系人？联系人不会从移动设备中移除。",
	"SelectedContactImport": "导入选定的联系人",
	"SingleImportTimeout": "单个导入超时",
	"SpeedThresholdExceeded": "超出讲话阈值",
	"SystemError": "系统错误",
	"TimeOut": "({timeout}) 秒后时间到",
	"TypeDisambTitle": "选择一个号码",
	"UnknownError": "错误原因不明",
	"VrHelp_Contacts_Help_Left1": "(联系人姓名)",
	"VrHelp_Contacts_Help_Left2": "添加到收藏夹",
	"VrHelp_Contacts_Help_Left3": "编辑联系人",
	"VrHelp_EditContacts_Help1_Left1": "导入所有联系人",
	"VrHelp_EditContacts_Help1_Left2": "导入选定的联系人",
	"WaitForPhoneData": "选择一名要从移动设备导入的联系人。",
	"WorkPhnNumber": "工作电话:",
};

framework.registerAppDictLoaded("contacts", "zh_CN");