var Localization_contactsAppDict_it_IT = {
	//"stringId" : "localString"
	"AccessDenied": "Accesso a rubrica negato.",
	"Address": "Indirizzo:",
	"CHDownloadFailed": "Download registro chiamate non riuscito.",
	"CHImportUnsupported": "L'importazione registro chiamate non è supportata dal dispositivo.",
	"CancelImport": "Annulla imp.",
	"CancellingImport": "Annullamento importazione",
	"ConatctImport": "Import. contatto",
	"ConnFailed": "Connessione non riuscita.",
	"ConnectionLost": "Connessione persa.",
	"ContactReadUnsuccess": "Lettura nome contatto non riuscita.",
	"ContactRestoredInfo": "I contatti saranno ripristinati se impostato il download automatico.",
	"ContactsFull": "Memoria contatti piena.",
	"DeleteError": "Impossibile eliminare il contatto.",
	"DeleteInProgress": "Eliminazione contatto",
	"DeleteSuccessMsg": "Eliminazione contatti riuscita.",
	"DeleteSuccessSingle": "Eliminazione contatto riuscita.",
	"DeviceConnectFailed": "Non è possibile connettersi al dispositivo.",
	"EditContacts": "Modifica contatti",
	"ErrorUnknown": "Errore sconosciuto.",
	"HomePhnNumber": "Casa:",
	"ImportAllContacts": "Importa tutti i contatti",
	"ImportConfirm": "Controllare il cellulare. Potrebbe essere necessario un permesso di download.",
	"ImportError": "Impossibile scaricare l'elenco cont.",
	"ImportFailureSbn": "Importazione non riuscita.",
	"ImportProgress": "Importazione contatti in corso",
	"ImportSuccess": "{ImportedEntries} di {TotalEntries} contatti sono stati importati.",
	"ImportSuccessSbn": "Importazione riuscita.",
	"ImportUnsupported": "L'importazione dell'elenco contatti non è supportata da questo dispositivo.",
	"MobilePhnNumber": "Cellulare:",
	"NoChSupport": "Il telefono non supporta l'importazione del registro chiamate.",
	"NoImportSupport": "Il telefono non supporta l'importazione.",
	"OtherPhnNumber": "Altro:",
	"PhonebookFull": "Rubrica piena",
	"PhonebookNotAvailable": "Rubrica non disponibile.",
	"ReadContact": "Leggi nome contatto",
	"RemoveContact": "Elimina contatto",
	"SelectContact": "Seleziona un contatto",
	"SelectFavoritesCurrentContact": "Aggiungi contatto a preferiti",
	"SelectRemove": "Vuoi eliminare il contatto? I contatti non saranno rimossi dal cellulare.",
	"SelectedContactImport": "Importa contatto selezionato",
	"SingleImportTimeout": "Sospensione importazione singola",
	"SpeedThresholdExceeded": "Limite di velocità superato",
	"SystemError": "Errore di sistema.",
	"TimeOut": "Tempo scaduto tra ({timeout}) secondi.",
	"TypeDisambTitle": "Seleziona un numero",
	"UnknownError": "Motivo dell'errore sconosciuto.",
	"VrHelp_Contacts_Help_Left1": "Nome contatto",
	"VrHelp_Contacts_Help_Left2": "Aggiungi ai preferiti",
	"VrHelp_Contacts_Help_Left3": "Modifica contatti",
	"VrHelp_EditContacts_Help1_Left1": "Importa tutti i contatti",
	"VrHelp_EditContacts_Help1_Left2": "Importa contatto selezionato",
	"WaitForPhoneData": "Seleziona un contatto da importare dal cellulare.",
	"WorkPhnNumber": "Lavoro:",
};

framework.registerAppDictLoaded("contacts", "it_IT");