var Localization_contactsAppDict_fr_CN = {
	//"stringId" : "localString"
	"AccessDenied": "Accès refusé au répertoire",
	"Address": "Adresse:",
	"CHDownloadFailed": "Impossible de télécharger l’historique des appels.",
	"CHImportUnsupported": "Importation de l'historique des appels non prise en charge par ce système.",
	"CancelImport": "Annuler imp.",
	"CancellingImport": "Importation en cours d’annulation",
	"ConatctImport": "Import. du contact",
	"ConnFailed": "Échec de connexion",
	"ConnectionLost": "Pas de connexion",
	"ContactReadUnsuccess": "Échec de lecture du contact",
	"ContactRestoredInfo": "Le contact sera restauré si le téléchargement automatique est activé.",
	"ContactsFull": "La mémoire de stockage des contacts est pleine.",
	"DeleteError": "Impossible de supprimer le contact",
	"DeleteInProgress": "Contact en cours de suppression",
	"DeleteSuccessMsg": "Suppr. de tous les contacts réussie.",
	"DeleteSuccessSingle": "Suppression du contact réussie",
	"DeviceConnectFailed": "Impossible de se connecter au système.",
	"EditContacts": "Modifier les contacts",
	"ErrorUnknown": "Erreur inconnue",
	"HomePhnNumber": "Maison:",
	"ImportAllContacts": "Importer tous les contacts",
	"ImportConfirm": "Vérifier votre dispositif mobile. Une autorisation de téléchargement peut être nécessaire.",
	"ImportError": "Impos. de télécharger liste des cont.",
	"ImportFailureSbn": "Échec d’importation",
	"ImportProgress": "Importation des contacts en cours",
	"ImportSuccess": "{ImportedEntries} des  {TotalEntries}  contacts a été réussie.",
	"ImportSuccessSbn": "Importation réussie",
	"ImportUnsupported": "La liste de contacts importée n'est pas prise en charge par ce système.",
	"MobilePhnNumber": "Mobile:",
	"NoChSupport": "Le téléphone ne permet pas l’importation de l’historique d’appels",
	"NoImportSupport": "Le téléphone ne permet pas l’importation",
	"OtherPhnNumber": "Autre:",
	"PhonebookFull": "Répertoire complet",
	"PhonebookNotAvailable": "Répertoire non disponible",
	"ReadContact": "Lire le nom du contact",
	"RemoveContact": "Supprimer le contact",
	"SelectContact": "Sélectionner un contact",
	"SelectFavoritesCurrentContact": "Ajouter un contact dans les Favoris",
	"SelectRemove": "Voulez-vous supprimer ce contact ? Les contacts ne seront pas supprimés du dispositif mobile.",
	"SelectedContactImport": "Importer le contact sélectioné",
	"SingleImportTimeout": "Durée d'importation écoulée",
	"SpeedThresholdExceeded": "Seuil de vitesse dépassé",
	"SystemError": "Erreur système",
	"TimeOut": "Expiration dans ({timeout}) secondes",
	"TypeDisambTitle": "Sélectionner un numéro",
	"UnknownError": "Erreur - Motif inconnu",
	"VrHelp_Contacts_Help_Left1": "Nom du contact",
	"VrHelp_Contacts_Help_Left2": "Ajouter aux favoris",
	"VrHelp_Contacts_Help_Left3": "Modifier les contacts",
	"VrHelp_EditContacts_Help1_Left1": "Importer tous les contacts",
	"VrHelp_EditContacts_Help1_Left2": "Importer le contact sélectionné",
	"WaitForPhoneData": "Sélectionner un contact à importer du dispositif mobile.",
	"WorkPhnNumber": "Travail:",
};

framework.registerAppDictLoaded("contacts", "fr_CN");