var Localization_contactsAppDict_mn_TW = {
	//"stringId" : "localString"
	"AccessDenied": "拒絕存取通訊簿",
	"Address": "地址 : ",
	"CHDownloadFailed": "無法下載通話記錄。",
	"CHImportUnsupported": "此行動裝置不支援通話記錄下載。",
	"CancelImport": "取消下載",
	"CancellingImport": "取消下載中",
	"ConatctImport": "下載通訊錄",
	"ConnFailed": "無法連接。 請檢查裝置。",
	"ConnectionLost": "失去連線",
	"ContactReadUnsuccess": "讀取聯絡人姓名失敗",
	"ContactRestoredInfo": "如將「自動下載通訊錄」設定於開啟狀態，\n下次啟動時將自動下載。",
	"ContactsFull": "通訊簿記憶體已滿",
	"DeleteError": "無法刪除聯絡人",
	"DeleteInProgress": "正在刪除聯絡人",
	"DeleteSuccessMsg": "已順利刪除所有聯絡人",
	"DeleteSuccessSingle": "已順利刪除聯絡人",
	"DeviceConnectFailed": "無法連接通信裝置。",
	"EditContacts": "編輯通訊簿",
	"ErrorUnknown": "不明的錯誤",
	"HomePhnNumber": "自宅電話 : ",
	"ImportAllContacts": "下載所有聯絡人",
	"ImportConfirm": "請確認您的行動裝置。下載可能需要權限。",
	"ImportError": "無法下載聯絡人。",
	"ImportFailureSbn": "無法下載",
	"ImportProgress": "正在下載通訊錄",
	"ImportSuccess": "已下載 {ImportedEntries} 個聯絡人 (總共 {TotalEntries} 個)。",
	"ImportSuccessSbn": "下載成功",
	"ImportUnsupported": "此行動裝置不支援通訊錄下載。",
	"MobilePhnNumber": "行動電話 : ",
	"NoChSupport": "裝置不支援「匯入通話歷史記錄」。",
	"NoImportSupport": "裝置不支援「匯入」。",
	"OtherPhnNumber": "其他電話 : ",
	"PhonebookFull": "系統記憶體已滿",
	"PhonebookNotAvailable": "不支援聯絡人格式",
	"ReadContact": "讀取聯絡人姓名",
	"RemoveContact": "刪除聯絡人",
	"SelectContact": "選擇一個聯絡人",
	"SelectFavoritesCurrentContact": "將聯絡人新增至我的最愛",
	"SelectRemove": "要刪除此聯絡人嗎?此聯絡人將不會從手機刪除。",
	"SelectedContactImport": "下載選定聯絡人",
	"SingleImportTimeout": "下載逾時",
	"SpeedThresholdExceeded": "行駛中無法使用",
	"SystemError": "系統錯誤",
	"TimeOut": "在 ({timeout}) 秒鐘後逾時",
	"TypeDisambTitle": "選取一個電話號碼",
	"UnknownError": "原因不明錯誤",
	"VrHelp_Contacts_Help_Left1": "(聯繫人姓名)",
	"VrHelp_Contacts_Help_Left2": "添加到收藏夾",
	"VrHelp_Contacts_Help_Left3": "編輯聯繫人",
	"VrHelp_EditContacts_Help1_Left1": "導入所有聯繫人",
	"VrHelp_EditContacts_Help1_Left2": "導入選定的聯繫人",
	"WaitForPhoneData": "從行動裝置下載通訊錄",
	"WorkPhnNumber": "公司電話 : ",
};

framework.registerAppDictLoaded("contacts", "mn_TW");