var Localization_contactsAppDict_sv_SE = {
	//"stringId" : "localString"
	"AccessDenied": "Åtkomst till telefonbok nekad",
	"Address": "Adress:",
	"CHDownloadFailed": "Kunde inte ladda ned samtalshistorik.",
	"CHImportUnsupported": "Import av samtalshistorik stöds inte av den här enheten.",
	"CancelImport": "Avbryt imp.",
	"CancellingImport": "Avbryter import",
	"ConatctImport": "Kontaktimport",
	"ConnFailed": "Kunde inte ansluta",
	"ConnectionLost": "Anslutning bruten",
	"ContactReadUnsuccess": "Kunde inte läsa kontaktnamnet",
	"ContactRestoredInfo": "Kontakterna återställs om automatisk nedladdning är påslagen.",
	"ContactsFull": "Kontaktminnet är fullt.",
	"DeleteError": "Kan inte ta bort kontakt",
	"DeleteInProgress": "Tar bort kontakt",
	"DeleteSuccessMsg": "Alla kontakter har raderats.",
	"DeleteSuccessSingle": "Kontakten har raderats ",
	"DeviceConnectFailed": "Kunde inte ansluta till enheten.",
	"EditContacts": "Redigera kontakter",
	"ErrorUnknown": "Okänt fel",
	"HomePhnNumber": "Hem:",
	"ImportAllContacts": "Importera alla kontakter",
	"ImportConfirm": "Kontrollera din mobila enhet. Det kan krävas godkännande för att ladda ned.",
	"ImportError": "Kun. inte ladda ned lista med kont.",
	"ImportFailureSbn": "Fel vid import",
	"ImportProgress": "Importerar kontakter",
	"ImportSuccess": "{ImportedEntries} av {TotalEntries} kontakter har importerats.",
	"ImportSuccessSbn": "Importen slutförd",
	"ImportUnsupported": "Import av kontaktlistan stöds inte av den här enheten.",
	"MobilePhnNumber": "Mobil:",
	"NoChSupport": "Telefon ne podržava uvoz istorije poziva",
	"NoImportSupport": "Telefonen stöder inte import",
	"OtherPhnNumber": "Annat:",
	"PhonebookFull": "Imenik je pun",
	"PhonebookNotAvailable": "Telefonbok finns inte",
	"ReadContact": "Läs kontaktnamn",
	"RemoveContact": "Ta bort kontakt",
	"SelectContact": "Välj en kontakt",
	"SelectFavoritesCurrentContact": "Lägg till kontakt i favoriter",
	"SelectRemove": "Vill du ta bort kontakten? Kontakter tas inte bort från den mobila enheten.",
	"SelectedContactImport": "Importera vald kontakt",
	"SingleImportTimeout": "Timeout för enstaka import",
	"SpeedThresholdExceeded": "Hastighetsgräns överskriden",
	"SystemError": "Sistemska greška",
	"TimeOut": "Timeout om ({timeout}) sek",
	"TypeDisambTitle": "Välj en siffra",
	"UnknownError": "Okänt fel",
	"VrHelp_Contacts_Help_Left1": "Kontaktnamn",
	"VrHelp_Contacts_Help_Left2": "Lägg till i favoriter",
	"VrHelp_Contacts_Help_Left3": "Redigera kontakter",
	"VrHelp_EditContacts_Help1_Left1": "Importera alla kontakter",
	"VrHelp_EditContacts_Help1_Left2": "Importera vald kontakt",
	"WaitForPhoneData": "Välj en kontakt att importera från den mobila enheten.",
	"WorkPhnNumber": "Arbete:",
};

framework.registerAppDictLoaded("contacts", "sv_SE");