var Localization_contactsAppDict_ms_MY = {
	//"stringId" : "localString"
	"AccessDenied": "Akses Buku Telefon Ditolak",
	"Address": "Alamat:",
	"CHDownloadFailed": "Tidak dapat memuat rutun Rekod Panggilan",
	"CHImportUnsupported": "Peranti ini tidak menyokong import Rekod panggilan",
	"CancelImport": "Batal Import",
	"CancellingImport": "Membatalkan Import",
	"ConatctImport": "Import Kenalan",
	"ConnFailed": "Sambungan gagal",
	"ConnectionLost": "Sambungan Terputus",
	"ContactReadUnsuccess": "Tidak Berjaya Membaca Nama Kenalan",
	"ContactRestoredInfo": "Kenalan akan dipulihkan jika seting muat turun kenalan automatik dihidupkan.",
	"ContactsFull": "Storan Kenalan penuh.",
	"DeleteError": "Tidak Dapata memadamkan kenalan",
	"DeleteInProgress": "Memadami Kenalan",
	"DeleteSuccessMsg": "Berjaya Dipadamkan",
	"DeleteSuccessSingle": "Kenalan Berjaya Dipadamkan",
	"DeviceConnectFailed": "Tidak dapat bersambung ke peranti.",
	"EditContacts": "Edit Kenalan",
	"ErrorUnknown": "Ralat Tidak Diketahui",
	"HomePhnNumber": "Rumah:",
	"ImportAllContacts": "Import Semua Kenalan",
	"ImportConfirm": "Sila periksa peranti mudah alaih anda. Kebenaran untuk memuat turun mungkin diperlukan.",
	"ImportError": "Tak dpt m/turun senarai hubungan",
	"ImportFailureSbn": "Import Gagal",
	"ImportProgress": "Mengimport Kenalan",
	"ImportSuccess": "{ImportedEntries} daripada {TotalEntries} kenalan telah diimport.",
	"ImportSuccessSbn": "Import Berjaya",
	"ImportUnsupported": "Mengimport senarai kenalan tidak disokong oleh peranti ini.",
	"MobilePhnNumber": "Mudah Alih:",
	"NoChSupport": "Telefon tidak menyokong Import Rekod Panggilan",
	"NoImportSupport": "Telefon tidak menyokong import",
	"OtherPhnNumber": "Lain-lain:",
	"PhonebookFull": "Buku Telefon penuh",
	"PhonebookNotAvailable": "Buku Telefon Tidak Tersedia",
	"ReadContact": "Baca Nama Kenalan",
	"RemoveContact": "Padamkan Kenalan",
	"SelectContact": "Pilih Kenalan",
	"SelectFavoritesCurrentContact": "Tambah Kenalan pada Kegemaran",
	"SelectRemove": "Adakah anda ingin padamkan kenalan? Kenalan tidak akan dipadamkan daripada peranti mudah alih.",
	"SelectedContactImport": "Import Kenalan Pilihan",
	"SingleImportTimeout": "Tamat Masa Import Tunggal",
	"SpeedThresholdExceeded": "Melebihi Nilai Ambang Kelajuan",
	"SystemError": "Ralat Sistem",
	"TimeOut": "Tamat masa dalam ({timeout}) saat",
	"TypeDisambTitle": "Pilih Nombor",
	"UnknownError": "Sebab Ralat Tidak Diketahui",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Pilih kenalan untuk diimport dari peranti mudah alih.",
	"WorkPhnNumber": "Tempat kerja:",
};

framework.registerAppDictLoaded("contacts", "ms_MY");