var Localization_contactsAppDict_sr_RS = {
	//"stringId" : "localString"
	"AccessDenied": "Odbijen pristup imeniku",
	"Address": "Adresa:",
	"CHDownloadFailed": "Nije moguće preuzeti istoriju poziva.",
	"CHImportUnsupported": "Ovaj uređaj ne podržava uvoz istorije.",
	"CancelImport": "Otkaži uvoz",
	"CancellingImport": "Otkazivanje uvoza",
	"ConatctImport": "Uvoz kontakta",
	"ConnFailed": "Povezivanje nije uspelo",
	"ConnectionLost": "Veza je izgubljena",
	"ContactReadUnsuccess": "Neuspešno čitanje imena kontakta",
	"ContactRestoredInfo": "Kod automatskog preuzimanja kontakt će biti obnovljen ",
	"ContactsFull": "Memorija kontakata je puna.",
	"DeleteError": "Nije moguće ukloniti kontakt",
	"DeleteInProgress": "Uklanjanje kontakta",
	"DeleteSuccessMsg": "Svi kontakti su uspešno uklonjeni.",
	"DeleteSuccessSingle": "Kontakt uspešno uklonjen ",
	"DeviceConnectFailed": "Povezivanje sa uređajem nije bilo moguće.",
	"EditContacts": "Uređivanje kontakta",
	"ErrorUnknown": "Nepoznata greška",
	"HomePhnNumber": "Kuća:",
	"ImportAllContacts": "Uvezi sve kontakte",
	"ImportConfirm": "Proverite svoj mobilni uređaj. Možda je potrebna dozvola za preuzimanje.",
	"ImportError": "Nije moguće preuzeti listu kontakta.",
	"ImportFailureSbn": "Neuspešan uvoz",
	"ImportProgress": "Uvezivanje kontakta",
	"ImportSuccess": "Uvezeno je {ImportedEntries} od {TotalEntries} kontakata.",
	"ImportSuccessSbn": "Uspešan uvoz",
	"ImportUnsupported": "Ovaj uređaj ne podržava uvoz liste kontakata",
	"MobilePhnNumber": "Mobilni:",
	"NoChSupport": "Telefon ne podržava uvoz istorije poziva",
	"NoImportSupport": "Telefon ne podržava uvoz",
	"OtherPhnNumber": "Ostali:",
	"PhonebookFull": "Imenik je pun",
	"PhonebookNotAvailable": "Imenik nije dostupan",
	"ReadContact": "Čitanje imena kontakta",
	"RemoveContact": "Ukloni kontakt",
	"SelectContact": "Izaberite kontakt",
	"SelectFavoritesCurrentContact": "Dodaj kontakt u Omiljene",
	"SelectRemove": "Da li želite da uklonite kontakt? Kontakti neće biti uklonjeni iz mobilnog uređaja.",
	"SelectedContactImport": "Uvezi izabrane kontakte",
	"SingleImportTimeout": "Isteklo vreme za jedan uvoz",
	"SpeedThresholdExceeded": "Prekoračena je granična vrednost brzine",
	"SystemError": "Sistemska greška",
	"TimeOut": "Prekid procesa za ({timeout}) sekundi",
	"TypeDisambTitle": "Izaberite broj",
	"UnknownError": "Uzrok greške nije poznat",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Izaberite kontakt za uvoz iz mobilnog uređaja.",
	"WorkPhnNumber": "Posao:",
};

framework.registerAppDictLoaded("contacts", "sr_RS");