var Localization_contactsAppDict_cs_CS = {
	//"stringId" : "localString"
	"AccessDenied": "Přístup k telefonnímu seznamu odmítnut",
	"Address": "Adresa:",
	"CHDownloadFailed": "Historii hovorů nelze stáhnout.",
	"CHImportUnsupported": "Toto zařízení nedokáže importovat historii hovorů.",
	"CancelImport": "Zrušit import",
	"CancellingImport": "Zrušit Importování",
	"ConatctImport": "Import kontaktu",
	"ConnFailed": "Připojení selhalo",
	"ConnectionLost": "Spojení bylo ztraceno.",
	"ContactReadUnsuccess": "Načtení jména kontaktu se nezdařilo",
	"ContactRestoredInfo": "Je-li zapnuté automatické stahování kontaktů, kontakt bude obnoven.",
	"ContactsFull": "Úložiště kontaktů je plné.",
	"DeleteError": "Kontakt nelze odstranit.",
	"DeleteInProgress": "Odstranit kontakt",
	"DeleteSuccessMsg": "Všechny kont. byly úspěšně odstr.",
	"DeleteSuccessSingle": "Kontakt odstraněn",
	"DeviceConnectFailed": "Připojení k zařízení se nezdařilo.",
	"EditContacts": "Upravit kontakty",
	"ErrorUnknown": "Neznámá chyba",
	"HomePhnNumber": "Domů:",
	"ImportAllContacts": "Importovat všechny kontakty",
	"ImportConfirm": "Zkontrolujte si mobilní zařízení.  Ke stahování bude asi vyžadováno povolení.",
	"ImportError": "Seznam kontaktů nelze stáhnout. ",
	"ImportFailureSbn": "Import nebyl úspěšný",
	"ImportProgress": "Importování kontaktů",
	"ImportSuccess": "Bylo importováno {ImportedEntries} z {TotalEntries} kontaktů",
	"ImportSuccessSbn": "Import byl úspěšný",
	"ImportUnsupported": "Toto zařízení nedokáže importovat seznam kontaktů.",
	"MobilePhnNumber": "Mobil:",
	"NoChSupport": "Telefon nepodporuje import historie hovorů",
	"NoImportSupport": "Telefon nepodporuje import",
	"OtherPhnNumber": "Jiný:",
	"PhonebookFull": "Telefonní seznam je plný",
	"PhonebookNotAvailable": "Telefonní seznam není k dispozici",
	"ReadContact": "Načíst jméno v kontaktu",
	"RemoveContact": "Odstranit kontakt",
	"SelectContact": "Vybrat kontakt",
	"SelectFavoritesCurrentContact": "Přidat kontakt mezi oblíbené",
	"SelectRemove": "Chcete kontakt odstranit? Kontakty nebudou odstraněny z mobilního zařízení.",
	"SelectedContactImport": "Importovat vybraný kontakt",
	"SingleImportTimeout": "Časový limit jednoho importu",
	"SpeedThresholdExceeded": "Byla překročena mez rychlosti.",
	"SystemError": "Systémová chyba",
	"TimeOut": "Časový limit během ({timeout}) sekund",
	"TypeDisambTitle": "Vyberte číslo",
	"UnknownError": "Došlo k neznámé chybě",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Vyberte kontakt pro import z mobilního zařízení.",
	"WorkPhnNumber": "Práce:",
};

framework.registerAppDictLoaded("contacts", "cs_CS");