var Localization_contactsAppDict_he_IL = {
	//"stringId" : "localString"
	"AccessDenied": "גישה לספר הטלפונים נדחתה",
	"Address": "כתובת",
	"CHDownloadFailed": "הורדת היסטוריית שיחות נכשלה.",
	"CHImportUnsupported": "המכשיר אינו תומך בייבוא היסטוריית שיחות.",
	"CancelImport": "בטל ייבוא",
	"CancellingImport": "מבטל ייבוא",
	"ConatctImport": "ייבוא איש קשר",
	"ConnFailed": "החיבור נכשל",
	"ConnectionLost": "החיבור נותק",
	"ContactReadUnsuccess": "קריאת שם איש קשר נכשלה",
	"ContactRestoredInfo": "איש הקשר ישוחזר אם הגדרת הורדה אוטומטית של אנשי קשר במצב מופעל.",
	"ContactsFull": "אחסון אנשי הקשר מלא.",
	"DeleteError": "לא ניתן להסיר איש קשר",
	"DeleteInProgress": "מסיר איש קשר",
	"DeleteSuccessMsg": "כל אנשי הקשר הוסרו בהצלחה.",
	"DeleteSuccessSingle": "איש הקשר הוסר בהצלחה",
	"DeviceConnectFailed": "לא ניתן להתחבר למכשיר.",
	"EditContacts": "ערוך אנשי קשר",
	"ErrorUnknown": "שגיאה בלתי-ידועה",
	"HomePhnNumber": "מס' טלפון בית",
	"ImportAllContacts": "ייבא את כל אנשי הקשר",
	"ImportConfirm": "אנא, בדוק את המכשיר הנייד שלך.  ייתכן שתתבקש לאשר את ההורדה.",
	"ImportError": "הורדת רשימת אנשי קשר נכשלה",
	"ImportFailureSbn": "הייבוא נכשל",
	"ImportProgress": "מייבא אנשי קשר",
	"ImportSuccess": "אנשי הקשר, יובאו {ImportedEntries} מתוך {TotalEntries}",
	"ImportSuccessSbn": "הייבוא הצליח",
	"ImportUnsupported": "המכשיר אינו תומך בייבוא רשימת אנשי קשר.",
	"MobilePhnNumber": "מס' טלפון נייד",
	"NoChSupport": "הטלפון אינו תומך בייבוא היסטוריית שיחות",
	"NoImportSupport": "טלפון אינו תומך בייבוא",
	"OtherPhnNumber": "מס' טלפון אחר",
	"PhonebookFull": "הטלפון מלא",
	"PhonebookNotAvailable": "ספר הטלפונים אינו זמין",
	"ReadContact": "קרא שם איש קשר",
	"RemoveContact": "הסר איש קשר",
	"SelectContact": "בחר איש קשר",
	"SelectFavoritesCurrentContact": "הוסף איש קשר למועדפים",
	"SelectRemove": "האם ברצונך להסיר את איש הקשר? אנשי הקשר לא יוסרו מהמכשיר הנייד.",
	"SelectedContactImport": "ייבא איש קשר נבחר",
	"SingleImportTimeout": "גמר זמן בייבוא בודד",
	"SpeedThresholdExceeded": "חריגה מסף מהירות",
	"SystemError": "שגיאת מערכת",
	"TimeOut": "גמר זמן בתוך ({timeout}) שניות",
	"TypeDisambTitle": "בחר מספר",
	"UnknownError": "סיבת השגיאה אינה ידועה.",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "בחר איש קשר לייבוא ממכשיר נייד.",
	"WorkPhnNumber": "מס' טלפון עבודה",
};

framework.registerAppDictLoaded("contacts", "he_IL");