var Localization_contactsAppDict_no_NO = {
	//"stringId" : "localString"
	"AccessDenied": "Tilgang til telefonkatalogen ble avvist",
	"Address": "Adresse:",
	"CHDownloadFailed": "Kan ikke laste ned samtalehistorikk.",
	"CHImportUnsupported": "Import av samtalehistorikk støttes ikke av denne enheten.",
	"CancelImport": "Avbryt imp.",
	"CancellingImport": "Import avbrytes",
	"ConatctImport": "Kontaktimport",
	"ConnFailed": "Tilkoblingen sviktet",
	"ConnectionLost": "Forbindelsen er brutt",
	"ContactReadUnsuccess": "Lesing av kontaktnavn mislyktes",
	"ContactRestoredInfo": "Kont. vil bli gjenoppret. hvis innstillingen for aut. nedlasting av kont. er på.",
	"ContactsFull": "Kontaktfolder er fullt.",
	"DeleteError": "Kan ikke fjerne kontakt",
	"DeleteInProgress": "Fjerner kontakt",
	"DeleteSuccessMsg": "Alle kontaktene ble fjernet.",
	"DeleteSuccessSingle": "Kontakten ble fjernet ",
	"DeviceConnectFailed": "Kan ikke koble til enheten.",
	"EditContacts": "Rediger kontakter",
	"ErrorUnknown": "Ukjent feil",
	"HomePhnNumber": "Hjem:",
	"ImportAllContacts": "Importer alle kontakter",
	"ImportConfirm": "Sjekk den mobile enheten. Det kan hende du må ha tillatelse til å laste ned.",
	"ImportError": "Kan ikke laste ned kontaktliste.",
	"ImportFailureSbn": "Importering mislyktes",
	"ImportProgress": "Importerer kontakter",
	"ImportSuccess": "{ImportedEntries} av {TotalEntries} kontakter ble importert.",
	"ImportSuccessSbn": "Importering vellykket",
	"ImportUnsupported": "Import av kontaktliste støttes ikke av denne enheten.",
	"MobilePhnNumber": "Mobil:",
	"NoChSupport": "Telefonen støtter ikke import av samtalehistorikk",
	"NoImportSupport": "Telefonen støtter ikke import",
	"OtherPhnNumber": "Annet:",
	"PhonebookFull": "Telefonkatalogen er full",
	"PhonebookNotAvailable": "Telefonkatalogen er ikke tilgjengelig",
	"ReadContact": "Les kontaktnavn",
	"RemoveContact": "Fjern kontakt",
	"SelectContact": "Velg en kontakt",
	"SelectFavoritesCurrentContact": "Legg kontakt til favoritter",
	"SelectRemove": "Vil du fjerne kontakten? Kontakter vil ikke bli fjernet fra den mobile enheten.",
	"SelectedContactImport": "Importer valgte kontakt",
	"SingleImportTimeout": "Tidsavbrudd, enkel importering",
	"SpeedThresholdExceeded": "Hastighetsgrense er overskredet",
	"SystemError": "Systemfeil",
	"TimeOut": "Tidsavbrudd om ({timeout}) sekunder",
	"TypeDisambTitle": "Velg et nummer",
	"UnknownError": "Feil med ukjent årsak",
	"VrHelp_Contacts_Help_Left1": "Contact name",
	"VrHelp_Contacts_Help_Left2": "Add to Favorites",
	"VrHelp_Contacts_Help_Left3": "Edit Contacts",
	"VrHelp_EditContacts_Help1_Left1": "Import All Contacts",
	"VrHelp_EditContacts_Help1_Left2": "Import Selected Contact",
	"WaitForPhoneData": "Velg en kontakt som skal importeres fra den mobile enheten.",
	"WorkPhnNumber": "Arbeid:",
};

framework.registerAppDictLoaded("contacts", "no_NO");