var Localization_contactsAppDict_cn_HK = {
	//"stringId" : "localString"
	"AccessDenied": "訪問被拒絕",
	"Address": "地址：",
	"CHDownloadFailed": "通話記錄匯入失敗",
	"CHImportUnsupported": "此裝置不支援通話記錄匯入。",
	"CancelImport": "取消匯入",
	"CancellingImport": "正在取消匯入",
	"ConatctImport": "匯入聯絡人",
	"ConnFailed": "無法連線 請檢查您的裝置。",
	"ConnectionLost": "失去連線。 請檢查您的裝置。",
	"ContactReadUnsuccess": "讀取聯絡人姓名失敗",
	"ContactRestoredInfo": "自動匯入連絡人設定已開啟時將還原連絡人。",
	"ContactsFull": "聯絡人儲存空間已滿。",
	"DeleteError": "無法移除連絡人",
	"DeleteInProgress": "正在移除聯絡人",
	"DeleteSuccessMsg": "已成功移除所有聯絡人",
	"DeleteSuccessSingle": "已成功移除連絡人 ",
	"DeviceConnectFailed": "無法連線到裝置。",
	"EditContacts": "編輯聯絡人",
	"ErrorUnknown": "未知錯誤",
	"HomePhnNumber": "家庭電話：",
	"ImportAllContacts": "匯入所有聯絡人",
	"ImportConfirm": "請檢查您的行動裝置。可能需要授權許可。",
	"ImportError": "無法匯入聯絡人",
	"ImportFailureSbn": "無法匯入",
	"ImportProgress": "正在匯入聯絡人",
	"ImportSuccess": "{ImportedEntries} / {TotalEntries} 個聯絡人已匯入。",
	"ImportSuccessSbn": "匯入成功",
	"ImportUnsupported": "此裝置不支援聯絡人清單匯入。",
	"MobilePhnNumber": "手機：",
	"NoChSupport": "您的裝置不支援通話記錄匯入。 ",
	"NoImportSupport": "您的裝置不支援匯入。",
	"OtherPhnNumber": "其他：",
	"PhonebookFull": "系統記憶體已滿",
	"PhonebookNotAvailable": "不支援連絡人格式",
	"ReadContact": "讀取聯絡人姓名",
	"RemoveContact": "移除聯絡人",
	"SelectContact": "選取聯絡人",
	"SelectFavoritesCurrentContact": "將聯絡人新增至我的最愛",
	"SelectRemove": "是否要移除聯絡人？ 將不從行動裝置移除聯絡人。",
	"SelectedContactImport": "匯入選定聯絡人",
	"SingleImportTimeout": "匯入超時。 請檢查您的裝置。",
	"SpeedThresholdExceeded": "車輛正在行駛中",
	"SystemError": "系統錯誤",
	"TimeOut": "在 ({timeout}) 秒後逾時",
	"TypeDisambTitle": "選取行號",
	"UnknownError": "錯誤原因未知",
	"VrHelp_Contacts_Help_Left1": "(聯繫人姓名)",
	"VrHelp_Contacts_Help_Left2": "添加到收藏夾",
	"VrHelp_Contacts_Help_Left3": "編輯聯繫人",
	"VrHelp_EditContacts_Help1_Left1": "導入所有聯繫人",
	"VrHelp_EditContacts_Help1_Left2": "導入選定的聯繫人",
	"WaitForPhoneData": "選取要從行動裝置匯入的聯絡人。",
	"WorkPhnNumber": "工作電話：",
};

framework.registerAppDictLoaded("contacts", "cn_HK");