var Localization_stitcherAppDict_cn_HK = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth音訊連線遺失",
	"Browse": "瀏覽節目",
	"Buffering": "正在緩衝",
	"ConnectionLost": "無網路連線",
	"ConnectionLostDetails": "確保您的行動裝置上的資料連線可用。",
	"EmptyStationList": "無項目",
	"EndOfPlaylist_Alert": "播放清單結束",
	"Global_AddingFavorite": "將此節目新增至選定電臺",
	"Global_RemovingFavorite": "將此節目從電臺移除",
	"Global_UnableToAddFavorite": "無法新增節目",
	"Global_UnableToAddRating": "無法新增評分",
	"Global_UnableToRemoveFavorite": "無法移除節目",
	"Loading": "載入",
	"LoginFirst": "請先登錄",
	"LoginFirstDetails": "必須登錄您的行動裝置的 Stitcher。",
	"MobileDeviceError": "行動裝置錯誤",
	"MobileDeviceErrorDetails": "確認您的行動裝置運作正常。",
	"SaveChanges": "存儲變更",
	"ShowDuration": "{duration} 分鐘",
	"SlectTheStations": "將節目新增至這些電臺",
	"StitcherNotFound": "未找到 Stitcher",
	"StitcherNotFoundDetails": "確保 Stitcher 應用程式已經安裝在您的行動裝置上。",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "娛樂",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "電台列表",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "不喜歡",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "喜歡",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "添加到收藏夾",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "從收藏夾中移除",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "後退30秒",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "播放 / 暫停",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "下一個",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "聲音設置",
	"dislike": "不喜好",
	"entMenu": "音訊源",
	"like": "喜好",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "cn_HK");