var Localization_stitcherAppDict_cs_CS = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Spojení audiopřípojky Bluetooth bylo ztraceno.",
	"Browse": "Procházet",
	"Buffering": "Vyrovnávání paměti",
	"ConnectionLost": "Žádné připojení k síti",
	"ConnectionLostDetails": "Datové připojení mobilního přístroje musí řádně fungovat.",
	"EmptyStationList": "Žádný obsah",
	"EndOfPlaylist_Alert": "Konec seznamu skladeb",
	"Global_AddingFavorite": "Přidání programu ke zvolené stanici",
	"Global_RemovingFavorite": "Odebrání programu ze zvolené stanice",
	"Global_UnableToAddFavorite": "Nelze přidat program.",
	"Global_UnableToAddRating": "Nelze přidat hodnocení",
	"Global_UnableToRemoveFavorite": "Program nelze odstranit",
	"Loading": "Načítání",
	"LoginFirst": "Nejprve se přihlaste",
	"LoginFirstDetails": "Musíte se na mobilním zařízení přihlásit do aplikace Stitcher.",
	"MobileDeviceError": "Chyba mobilního zařízení",
	"MobileDeviceErrorDetails": "Zkontrolujte , zda mobilní zařizení řádně funguje.",
	"SaveChanges": "Uložit změny",
	"ShowDuration": "{duration} min",
	"SlectTheStations": "Přidat programu k této stanici(cím)",
	"StitcherNotFound": "Služba Stitcher nebyla nalezena",
	"StitcherNotFoundDetails": "Aplikace Stitcher musí být v mobilním zařízení nainstalována.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Nelíbí se",
	"entMenu": "Nabídka zábavy",
	"like": "Líbí se",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "cs_CS");