var Localization_stitcherAppDict_ar_SA = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "تم فقد اتصال Bluetooth الصوتي",
	"Browse": "استعراض",
	"Buffering": "التخزين المؤقت جار",
	"ConnectionLost": "لا يوجد اتصال بالشبكة",
	"ConnectionLostDetails": "تأكد من أن اتصال البيانات على هاتفك الجوال يعمل على النحو الصحيح.",
	"EmptyStationList": "لا توجد عناصر",
	"EndOfPlaylist_Alert": "نهاية قائمة التشغيل",
	"Global_AddingFavorite": "إضافة عرض إلى المحطة المحددة",
	"Global_RemovingFavorite": "إزالة عرض من محطة",
	"Global_UnableToAddFavorite": "لم يتمكن من إضافة عرض",
	"Global_UnableToAddRating": "لم يتمكن من إضافة تصنيف",
	"Global_UnableToRemoveFavorite": "لم يتمكن من حذف العرض",
	"Loading": "التحميل جار",
	"LoginFirst": "يرجى تسجيل الدخول أولاً",
	"LoginFirstDetails": "يجب أن تقوم بتسجيل الدخول على Stitcher في هاتفك الجوال.",
	"MobileDeviceError": "حدث خطأ في الهاتف الجوال",
	"MobileDeviceErrorDetails": "تأكد من أن هاتفك الجوال يعمل على النحو الصحيح.",
	"SaveChanges": "حفظ التغييرات",
	"ShowDuration": "{duration} دقيقة",
	"SlectTheStations": "إضافة عرض إلى هذه المحطات",
	"StitcherNotFound": "لم يتم العثور على Stitcher",
	"StitcherNotFoundDetails": "تأكد من أن تطبيق Stitcher مثبت بالفعل على هاتفك الجوال.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "ترفيه ",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "قائمة المحطات",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "والإبهام إلي الأسفل",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "والإبهام إلي الأعلى",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "واضف إلي المفضلات",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "والإزالة من المفضلات",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "الرجوع 30 ثانية",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "وبدء التشغيل/ والتوقف المؤقت",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "التالي",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "إعدادات الصوت",
	"dislike": "لا يعجبني",
	"entMenu": "قائمة الترفيه",
	"like": "يعجبني",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "ar_SA");