var Localization_stitcherAppDict_no_NO = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth forbindelse brutt",
	"Browse": "Bla",
	"Buffering": "Bufrer",
	"ConnectionLost": "Ingen nettverkskobling",
	"ConnectionLostDetails": "Sørg for at dataforbindelsen på den mobile enheten fungerer slik den skal.",
	"EmptyStationList": "Ingen enheter",
	"EndOfPlaylist_Alert": "Slutt på spilleliste",
	"Global_AddingFavorite": "Legge program til valgt stasjon",
	"Global_RemovingFavorite": "Fjerne program fra stasjonen",
	"Global_UnableToAddFavorite": "Kan ikke legge til program",
	"Global_UnableToAddRating": "Kan ikke legge til rangering",
	"Global_UnableToRemoveFavorite": "Kan ikke fjerne program",
	"Loading": "Laster",
	"LoginFirst": "Logg inn først",
	"LoginFirstDetails": "Du må være logget inn på Stitcher på den mobile enheten.",
	"MobileDeviceError": "Feil ved mobil enhet",
	"MobileDeviceErrorDetails": "Sjekk at den mobile enheten fungerer slik den skal.",
	"SaveChanges": "Lagre endringer",
	"ShowDuration": "{duration} minutter",
	"SlectTheStations": "Legg program til disse stasjon",
	"StitcherNotFound": "Kan ikke finne Stitcher",
	"StitcherNotFoundDetails": "Sjekk at Stitcher-programmet er installert på den mobile enheten.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Liker ikke",
	"entMenu": "Underholdningsmeny",
	"like": "Liker",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "no_NO");