var Localization_stitcherAppDict_id_ID = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Koneksi Audio Bluetooth Hilang",
	"Browse": "Telusuri",
	"Buffering": "Memuat",
	"ConnectionLost": "Tidak Ada Koneksi Jaringan",
	"ConnectionLostDetails": "Pastikan koneksi data di perangkat seluler Anda berfungsi normal.",
	"EmptyStationList": "Tidak ada item",
	"EndOfPlaylist_Alert": "Bagian Akhir Daftar Putar",
	"Global_AddingFavorite": "Menambah Pertunjukan Stasiun Terpilih",
	"Global_RemovingFavorite": "Menghapus Pertunjukan dari stasiun",
	"Global_UnableToAddFavorite": "Tidak Dapat Menambah Pertunjukan",
	"Global_UnableToAddRating": "Tidak dapat menambahkan peringkat",
	"Global_UnableToRemoveFavorite": "Tidak Dapat Menghapus Pertunjukan",
	"Loading": "Memuat",
	"LoginFirst": "Silakan Login Dahulu",
	"LoginFirstDetails": "Anda harus masuk Stitcher di perangkat seluler Anda.",
	"MobileDeviceError": "Perangkat seluler eror",
	"MobileDeviceErrorDetails": "Periksa apakah perangkat seluler Anda berfungsi normal.",
	"SaveChanges": "Simpan Perubahan",
	"ShowDuration": "{duration} menit",
	"SlectTheStations": "Tambah pertunjukan ke stasiun ini",
	"StitcherNotFound": "Stitcher Tidak Ditemukan",
	"StitcherNotFoundDetails": "Pastikan aplikasi Stitcher sudah terinstal di perangkat seluler Anda.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Tidak Suka",
	"entMenu": "Menu Hiburan",
	"like": "Suka",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "id_ID");