var Localization_stitcherAppDict_nl_NL = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth Audio Verbinding Verbroken",
	"Browse": "Browsen",
	"Buffering": "Bufferen",
	"ConnectionLost": "Geen netwerkverbinding",
	"ConnectionLostDetails": "Zorg ervoor dat de gegevensverbinding op uw mobiele apparaat naar behoren functioneert.",
	"EmptyStationList": "Geen Items",
	"EndOfPlaylist_Alert": "Einde van de afspeellijst",
	"Global_AddingFavorite": "Programma wordt toegevoegd aan geselecteerde zender",
	"Global_RemovingFavorite": "Programma wordt verwijderd van zender",
	"Global_UnableToAddFavorite": "Kan geen programma toevoegen",
	"Global_UnableToAddRating": "Kan geen rating toevoegen",
	"Global_UnableToRemoveFavorite": "Kan programma niet verwijderen",
	"Loading": "Wordt geladen",
	"LoginFirst": "Eerst inloggen aub",
	"LoginFirstDetails": "U moet ingelogd zijn om Stitcher te gebruiken op uw mobiele apparaat.",
	"MobileDeviceError": "Fout mobiel apparaat",
	"MobileDeviceErrorDetails": "Selecteer te verwijderen apparaat",
	"SaveChanges": "Wijzigingen opslaan",
	"ShowDuration": "{duration} minuten",
	"SlectTheStations": "Show toevoegen",
	"StitcherNotFound": "Stitcher niet gevonden",
	"StitcherNotFoundDetails": "Zorg ervoor dat de Stitcher app op uw mobiele apparaat geïnstalleerd is.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": " Zenderlijst",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Toevoegen aan Favorieten",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Favoriet verwijderen",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "30 seconden terug",
	"VrHelp_NowPlayingOnDemand_Help_Right3": " Afspelen / Pauze",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Volgende",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Geluidsinstellingen",
	"dislike": "Dislike",
	"entMenu": "Entertainment Menu",
	"like": "Like",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "nl_NL");