var Localization_stitcherAppDict_ms_MY = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Sambungan Audio Bluetooth Terputus",
	"Browse": "Lihat",
	"Buffering": "Menimbal",
	"ConnectionLost": "Tiada Sambungan Rangkaian",
	"ConnectionLostDetails": "Pastikan sambungan data pada peranti mudah alih anda berfungsi dengan betul.",
	"EmptyStationList": "Tiada Butiran",
	"EndOfPlaylist_Alert": "Senarai Main Tamat",
	"Global_AddingFavorite": "Menambah Rancangan pada Stesen Terpilih",
	"Global_RemovingFavorite": "Mengeluarkan Rancangan dari Stesen",
	"Global_UnableToAddFavorite": "Tidak dapat menambah rancangan",
	"Global_UnableToAddRating": "Tidak dapat menambah penarafan",
	"Global_UnableToRemoveFavorite": "Tidak dapat mengeluarkan rancangan",
	"Loading": "Memuatkan",
	"LoginFirst": "Sila Log Masuk Terlebih Dahulu",
	"LoginFirstDetails": "Anda mesti log masuk ke Stitcher pada peranti mudah alih anda.",
	"MobileDeviceError": "Ralat Peranti Mudah Alih",
	"MobileDeviceErrorDetails": "Pastikan bahawa peranti mudah alih anda berfungsi dengan betul.",
	"SaveChanges": "Simpan Perubahan",
	"ShowDuration": "{duration} minit",
	"SlectTheStations": "Tambah rancangan pada stesen ini",
	"StitcherNotFound": "Stitcher Tidak Ditemui",
	"StitcherNotFoundDetails": "Pastikan aplikasi Stitcher telah dipasang pada peranti mudah alih anda.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Tidak Suka",
	"entMenu": "Menu Hiburan",
	"like": "Suka",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "ms_MY");