var Localization_stitcherAppDict_pt_BR = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Conexão de áudio Bluetooth perdida",
	"Browse": "Procurar programas",
	"Buffering": "Armaz. em buffer",
	"ConnectionLost": "Sem conexão de rede",
	"ConnectionLostDetails": "Certifique-se de que a conexão de dados do seu dispositivo móvel está disponível.",
	"EmptyStationList": "Nenhum item",
	"EndOfPlaylist_Alert": "Fim da lista de reprodução",
	"Global_AddingFavorite": "Adicionando este programa à estação selecionada",
	"Global_RemovingFavorite": "Removendo este programa da estação",
	"Global_UnableToAddFavorite": "Não é possível adicionar programa",
	"Global_UnableToAddRating": "Não é possível adicionar classificação",
	"Global_UnableToRemoveFavorite": "Não é possível remover programa",
	"Loading": "Carregando",
	"LoginFirst": "Efetue login primeiro",
	"LoginFirstDetails": "Você precisa estar conectado ao Stitcher em seu dispositivo móvel.",
	"MobileDeviceError": "Erro no dispositivo móvel",
	"MobileDeviceErrorDetails": "Certifique-se de que o seu dispositivo móvel esteja funcionando corretamente.",
	"SaveChanges": "Salvar alterações",
	"ShowDuration": "{duration} min",
	"SlectTheStations": "Adic. progr. a estas estações",
	"StitcherNotFound": "Stitcher não encontrado",
	"StitcherNotFoundDetails": "Certifique-se de que o aplicativo Stitcher já esteja instalado em seu dispositivo móvel.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entretenimento",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Lista de estações",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Desaprovar",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Aprovar",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Adicionar favorito",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remover favorito",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Retroceder 30 segundos",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Reproduzir / Pausar",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Seguinte",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Definições de som",
	"dislike": "Descurtir",
	"entMenu": "Entretenimento",
	"like": "Curtir",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "pt_BR");