var Localization_stitcherAppDict_lv_LV = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth audio savienojums ir zaudēts",
	"Browse": "Pārlūkot",
	"Buffering": "Buferizācija",
	"ConnectionLost": "Nav tīkla savienojuma",
	"ConnectionLostDetails": "Pārbaudiet, vai mobilās ierīces datu savienojums darbojas pareizi.",
	"EmptyStationList": "Nav neviena vienuma",
	"EndOfPlaylist_Alert": "Atskaņošanas saraksta beigas",
	"Global_AddingFavorite": "Pārraides pievienošana atlasītajai stacijai",
	"Global_RemovingFavorite": "Noņem iestatījumu Rādīt no stacijas",
	"Global_UnableToAddFavorite": "Nevar pievienot pārraidi",
	"Global_UnableToAddRating": "Nevar pievienot novērtējumu",
	"Global_UnableToRemoveFavorite": "Nevar noņemt pārraidi",
	"Loading": "Ielādē",
	"LoginFirst": "Vispirms piesakieties",
	"LoginFirstDetails": "Vispirms mobilajā ierīcē jāpiesakās lietojumprogrammā Stitcher.",
	"MobileDeviceError": "Mobilās ierīces kļūda",
	"MobileDeviceErrorDetails": "Pārbaudiet, vai mobilā ierīce darbojas pareizi.",
	"SaveChanges": "Saglabāt izmaiņas",
	"ShowDuration": "{duration} minūtes",
	"SlectTheStations": "Pievienot pārraidi stacijai (-ām)",
	"StitcherNotFound": "Stitcher nav atrasta",
	"StitcherNotFoundDetails": "Pārbaudiet, vai lietojumprogramma Stitcher jau ir instalēta mobilajā ierīcē.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Nepatīk",
	"entMenu": "Izklaides izvēlne",
	"like": "Patīk",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "lv_LV");