var Localization_stitcherAppDict_en_AU = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth Audio Connection Lost",
	"Browse": "Browse",
	"Buffering": "Buffering",
	"ConnectionLost": "No Network Connection",
	"ConnectionLostDetails": "Make sure the data connection on your mobile device is functioning properly.",
	"EmptyStationList": "No Items",
	"EndOfPlaylist_Alert": "End of Playlist",
	"Global_AddingFavorite": "Adding Show to Selected Station",
	"Global_RemovingFavorite": "Removing Show from Station",
	"Global_UnableToAddFavorite": "Unable to Add Show",
	"Global_UnableToAddRating": "Unable to Add Rating",
	"Global_UnableToRemoveFavorite": "Unable to Remove Show",
	"Loading": "Loading",
	"LoginFirst": "Please Login First",
	"LoginFirstDetails": "You must be logged in to Stitcher on your mobile device.",
	"MobileDeviceError": "Mobile Device Error",
	"MobileDeviceErrorDetails": "Check that your mobile device is functioning properly.",
	"SaveChanges": "Save Changes",
	"ShowDuration": "{duration} minutes",
	"SlectTheStations": "Add show to these station(s)",
	"StitcherNotFound": "Stitcher Not Found",
	"StitcherNotFoundDetails": "Make sure the Stitcher application is already installed on your mobile device.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favourites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favourites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Dislike",
	"entMenu": "Entertainment Menu",
	"like": "Like",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "en_AU");