var Localization_stitcherAppDict_bg_BG = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Изгубена е връзката със звуковото устройство с Bluetooth",
	"Browse": "Разглеждане",
	"Buffering": "Буфериране",
	"ConnectionLost": "Няма връзка с мрежата",
	"ConnectionLostDetails": "Уверете се, че връзката за данни на мобилното устройство работи изправно.",
	"EmptyStationList": "Няма елементи",
	"EndOfPlaylist_Alert": "Край на списъка",
	"Global_AddingFavorite": "Добавяне на програма към избраната станция",
	"Global_RemovingFavorite": "Изтриване на програма от станция",
	"Global_UnableToAddFavorite": "Програмата не може да се добави",
	"Global_UnableToAddRating": "Категорията не може да се добави",
	"Global_UnableToRemoveFavorite": "Програмата не може да се изтрие",
	"Loading": "Зареждане",
	"LoginFirst": "Влезте първо в системата",
	"LoginFirstDetails": "Трябва да сте влезли в Stitcher на мобилното устройство.",
	"MobileDeviceError": "Грешка в мобил. Устройство",
	"MobileDeviceErrorDetails": "Проверете дали мобилното устройство функционира изправно.",
	"SaveChanges": "Запис на промените",
	"ShowDuration": "{duration} минути",
	"SlectTheStations": "Добавяне на програма",
	"StitcherNotFound": "Stitcher не е намерено",
	"StitcherNotFoundDetails": "Уверете се, че приложението Stitcher е вече инсталирано на мобилното устройство.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Не харесвам",
	"entMenu": "Меню Развлечения",
	"like": "Харесвам",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "bg_BG");