var Localization_stitcherAppDict_es_ES = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Conexión de Audio Bluetooth Perdida",
	"Browse": "Buscar ",
	"Buffering": "Almacenando",
	"ConnectionLost": "Sin conexión de red",
	"ConnectionLostDetails": "Asegúrese que la conexión de datos en su dispositivo móvil está funcionando adecuadamente. ",
	"EmptyStationList": "No hay artículos",
	"EndOfPlaylist_Alert": "Fin de la lista de reproducción",
	"Global_AddingFavorite": "Añadiendo show a la emisora seleccionada",
	"Global_RemovingFavorite": "Quitando show desde la emisora",
	"Global_UnableToAddFavorite": "No se pudo añadir show",
	"Global_UnableToAddRating": "No se pudo añadir clasificación",
	"Global_UnableToRemoveFavorite": "No se puede eliminar show",
	"Loading": "Cargando ",
	"LoginFirst": "Primero inicie sesión",
	"LoginFirstDetails": "Debe haberse iniciado la sesión a Stitcher en su móvil",
	"MobileDeviceError": "Error del dispositivo móvil",
	"MobileDeviceErrorDetails": "Verifique que su dispositivo móvil esté funcionando adecuadamente.",
	"SaveChanges": "Guardar cambios",
	"ShowDuration": "{duration} minutos",
	"SlectTheStations": "Añadir show a estas emisoras",
	"StitcherNotFound": "Stitcher no encontrado",
	"StitcherNotFoundDetails": "Asegúrese que la aplicación Stitcher ya esté instalada en su dispositivo móvil.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entretenimiento",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Lista de Emisoras",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "No me gusta",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Me gusta",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Añadir a favoritos",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Eliminar favorito",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Volver 30 segundos",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Reproducir/Pausa",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Siguiente",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Ajustes de sonido",
	"dislike": "No me gusta",
	"entMenu": "Menú entretenimiento",
	"like": "Me gusta",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "es_ES");