var Localization_stitcherAppDict_sk_SK = {
	//"stringId" : "localString"
	"BTAudioConnectionLost": "Bluetooth audio strate spojenia",
	"Browse": "Prehliadanie",
	"Buffering": "Ukladanie do vyrovnávacej pamäte",
	"ConnectionLost": "Bez pripojenia",
	"ConnectionLostDetails": "Presvedčite sa, že dátové pripojenie na vašom mobilnom zariadení funguje správne.",
	"EmptyStationList": "Žiadne položky",
	"EndOfPlaylist_Alert": "Koniec zoznamu skladieb",
	"Global_AddingFavorite": "Pridanie relácie k vybranej stanici",
	"Global_RemovingFavorite": "Odstránenie relácie zo stanice",
	"Global_UnableToAddFavorite": "Nemožno pridať ukážku",
	"Global_UnableToAddRating": "Nemožno pridať hodnotenie",
	"Global_UnableToRemoveFavorite": "Nemožno odstrániť ukážku",
	"Loading": "Načítava sa",
	"LoginFirst": "Najskôr sa, prosím, prihláste",
	"LoginFirstDetails": "Na svojom mobilnom zariadení sa musíte prihlásiť do služby Stitcher.",
	"MobileDeviceError": "Chyba mobilného zariadenia",
	"MobileDeviceErrorDetails": "Skontrolujte, či vaše mobilné zariadenie funguje správne.",
	"SaveChanges": "Uložiť zmeny",
	"ShowDuration": "{duration} minút",
	"SlectTheStations": "Pridať reláciu do týchto staníc",
	"StitcherNotFound": "Služba Stitcher sa nenašla",
	"StitcherNotFoundDetails": "Presvedčite sa, či aplikácia Stitcher je už na vašom mobilnom zariadení nainštalovaná.",
	"VrHelp_NowPlayingOnDemand_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOnDemand_Help_Left2": "Station List",
	"VrHelp_NowPlayingOnDemand_Help_Left3": "Thumbs Down",
	"VrHelp_NowPlayingOnDemand_Help_Left4": "Thumbs Up",
	"VrHelp_NowPlayingOnDemand_Help_Left5": "Add to Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right1": "Remove Favorites",
	"VrHelp_NowPlayingOnDemand_Help_Right2": "Back 30 Seconds",
	"VrHelp_NowPlayingOnDemand_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingOnDemand_Help_Right4": "Next",
	"VrHelp_NowPlayingOnDemand_Help_Right5": "Sound Settings",
	"dislike": "Nepáči sa mi",
	"entMenu": "Ponuka zábavy",
	"like": "Páči sa mi",
	"sbNameId": "Stitcher",
};

framework.registerAppDictLoaded("stitcher", "sk_SK");