var Localization_smsAppDict_es_MX = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "Documentos Adjuntos No Admitidos",
	"AutoDownload": "SMS Descargados",
	"Back": "Atrás  ",
	"ContinueMessage": "Continuar Mensaje",
	"Delete": "Eliminar",
	"DeleteFail": "No se puede eliminar",
	"DeleteFailDesc": "No se puede eliminar mensaje",
	"Discard": "Descartar",
	"DiscardConfirm": "¿Desea descartar el mensaje actual?",
	"DownloadFail": "No se puede descargar",
	"DownloadFailDesc": "No se puede obtener información del teléfono",
	"DownloadSmsMessages": "Actualizar Buzón de entrada",
	"From": "De: {from}",
	"Inbox": "Buzón de entrada",
	"InstanceDisconnectDesc": "No se puede conectar a la cuenta",
	"ListDownloadFail": "No se puede descargar la lista",
	"MemoryFull": "Memoria llena",
	"Message": "Mensaje: {Msg}",
	"MessagePreset": "Mensaje preconfigurado",
	"NotificationNotSupported": "Notificación no admitida",
	"Reply": "Responder ",
	"Retry": "Reintentar ",
	"Return": "Volver ",
	"SMSDeleteConfirm": "Este mensaje se eliminará del dispositivo móvil y no se podrá recuperar. ¿Está seguro de que  desea eliminarlo?",
	"SelectContact": "Seleccionar contacto",
	"SelectMessage": "Seleccionar Mensaje",
	"Send": "Enviar",
	"SendConfirm": "¿Desea continuar enviando este mensaje?",
	"SendFail": "No se puede enviar",
	"SendFailDesc": "No se puede enviar mensaje al teléfono",
	"SendingMessage": "Enviando SMS",
	"SpeedRestriction": "Por su seguridad, el mensaje no se visualiza.",
	"TTSReadFail": "No se puede leer mensaje",
	"TextMessageSent": "SMS Enviado",
	"TextMessages": "Mensajes de SMS",
	"To": "Para: {To}",
	"UnfinishedTextMessage": "Un mensaje sin terminar necesita su atención.",
	"Updating": "Actualizando ",
	"VrHelp_SMSMessageDetail_Help_Left1": "Comunicación",
	"VrHelp_SMSMessageDetail_Help_Left2": "Buzón de entrada",
	"VrHelp_SMSMessageDetail_Help_Left3": "Reproducir/Pausa",
	"VrHelp_SMSMessageDetail_Help_Left4": "Anterior",
	"VrHelp_SMSMessageDetail_Help_Left5": "Siguiente",
	"VrHelp_SMSMessageDetail_Help_Right1": "Responder",
	"VrHelp_SMSMessageDetail_Help_Right2": "Llamar",
	"VrHelp_SMSMessageDetail_Help_Right3": "Eliminar",
	"VrHelp_SMSReply_Help_Left1": "Añadir Mensaje",
	"VrHelp_SMSReply_Help_Left2": "Enviar",
};

framework.registerAppDictLoaded("sms", "es_MX");