var Localization_smsAppDict_pt_PT = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "Anexos Não Suportados",
	"AutoDownload": "SMS Transferidas",
	"Back": "Voltar",
	"ContinueMessage": "Continuar Mensagem",
	"Delete": "Eliminar",
	"DeleteFail": "Não é possível eliminar",
	"DeleteFailDesc": "Não é possível eliminar a mensagem",
	"Discard": "Rejeitar",
	"DiscardConfirm": "Pretende rejeitar a mensagem actual?",
	"DownloadFail": "Não é possível transferir",
	"DownloadFailDesc": "Não é possível obter informações a partir do telefone",
	"DownloadSmsMessages": "Actualizar pasta A Receber",
	"From": "De: {from}",
	"Inbox": "A Receber",
	"InstanceDisconnectDesc": "Não é possível ligar à conta",
	"ListDownloadFail": "Não é possível transferir a lista",
	"MemoryFull": "Memória Cheia",
	"Message": "Mensagem: {Msg}",
	"MessagePreset": "Mensagem Predefinida",
	"NotificationNotSupported": "Notificação não suportada",
	"Reply": "Responder",
	"Retry": "Repetir",
	"Return": "Voltar",
	"SMSDeleteConfirm": "Esta mensagem será eliminada do dispositivo móvel e não é possível anular o procedimento. Tem a certeza de que pretende eliminar?",
	"SelectContact": "Seleccionar Contacto",
	"SelectMessage": "Seleccionar Mensagem",
	"Send": "Enviar",
	"SendConfirm": "Pretende continuar a enviar esta mensagem?",
	"SendFail": "Não é possível enviar",
	"SendFailDesc": "Não é possível enviar a mensagem para o telefone",
	"SendingMessage": "A Enviar Mensagem",
	"SpeedRestriction": "Para sua segurança, a mensagem não é apresentada.",
	"TTSReadFail": "Não é possível ler a mensagem",
	"TextMessageSent": "SMS Enviada",
	"TextMessages": "SMS",
	"To": "Para: {To}",
	"UnfinishedTextMessage": "Uma mensagem incompleta requer a sua atenção.",
	"Updating": "A Actualizar",
	"VrHelp_SMSMessageDetail_Help_Left1": "Comunicação",
	"VrHelp_SMSMessageDetail_Help_Left2": "A Receber",
	"VrHelp_SMSMessageDetail_Help_Left3": "Reproduzir / Pausar",
	"VrHelp_SMSMessageDetail_Help_Left4": "Anterior",
	"VrHelp_SMSMessageDetail_Help_Left5": "Seguinte",
	"VrHelp_SMSMessageDetail_Help_Right1": "Responder",
	"VrHelp_SMSMessageDetail_Help_Right2": "Telefonar",
	"VrHelp_SMSMessageDetail_Help_Right3": "Eliminar",
	"VrHelp_SMSReply_Help_Left1": "Adicionar Mensagem",
	"VrHelp_SMSReply_Help_Left2": "Enviar",
};

framework.registerAppDictLoaded("sms", "pt_PT");