var Localization_smsAppDict_fr_FR = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "Pièces jointes non acceptées",
	"AutoDownload": "SMS téléchargés",
	"Back": "Retour",
	"ContinueMessage": "Continuer message",
	"Delete": "Supprimer",
	"DeleteFail": "Impossible de supprimer",
	"DeleteFailDesc": "Impossible de supprimer le message",
	"Discard": "Ne pas enregistrer",
	"DiscardConfirm": "Voulez-vous supprimer le message en cours ?",
	"DownloadFail": "Impossible de télécharger",
	"DownloadFailDesc": "Impossible d'obtenir des données du téléphone",
	"DownloadSmsMessages": "Màj de boîte de réception",
	"From": "De : {from}",
	"Inbox": "Boîte de réception",
	"InstanceDisconnectDesc": "Connexion au compte impossible",
	"ListDownloadFail": "Impossible de télécharger la liste",
	"MemoryFull": "Mémoire pleine",
	"Message": "Message : {Msg}",
	"MessagePreset": "Prédéfinition du message",
	"NotificationNotSupported": "Notification non acceptée",
	"Reply": "Répondre",
	"Retry": "Réessayer",
	"Return": "Retour",
	"SMSDeleteConfirm": "Cet email sera supprimé du dispositif mobile. Cette opération ne peut être annulée. Etes-vous sûr de vouloir supprimer ?",
	"SelectContact": "Sélectionner un contact",
	"SelectMessage": "Sélectionner un message",
	"Send": "Envoyer",
	"SendConfirm": "Voulez-vous poursuivre l’envoi de ce message ?",
	"SendFail": "Impossible d’envoyer",
	"SendFailDesc": "Impossible d'envoyer un message au téléphone",
	"SendingMessage": "En cours d’envoi du message",
	"SpeedRestriction": "Pour votre sécurité, le message n’est pas affiché.",
	"TTSReadFail": "Impossible de lire le message",
	"TextMessageSent": "SMS envoyé",
	"TextMessages": "SMS",
	"To": "A : {To}",
	"UnfinishedTextMessage": "Un message inachevé nécessite votre attention.",
	"Updating": "Mise à jour en cours",
	"VrHelp_SMSMessageDetail_Help_Left1": "Communication",
	"VrHelp_SMSMessageDetail_Help_Left2": "Boîte de réception",
	"VrHelp_SMSMessageDetail_Help_Left3": "Lire/Pause",
	"VrHelp_SMSMessageDetail_Help_Left4": "Précédent",
	"VrHelp_SMSMessageDetail_Help_Left5": "Suivant",
	"VrHelp_SMSMessageDetail_Help_Right1": "Répondre",
	"VrHelp_SMSMessageDetail_Help_Right2": "Appeler",
	"VrHelp_SMSMessageDetail_Help_Right3": "Supprimer",
	"VrHelp_SMSReply_Help_Left1": "Ajouter un message",
	"VrHelp_SMSReply_Help_Left2": "Envoyer",
};

framework.registerAppDictLoaded("sms", "fr_FR");