var Localization_smsAppDict_th_TH = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "ไม่รองรับไฟล์แนบ",
	"AutoDownload": "SMS ดาวน์โหล",
	"Back": "ย้อนกลับ",
	"ContinueMessage": "ทำข้อความต่อไป",
	"Delete": "ลบ",
	"DeleteFail": "ไม่สามารถลบ",
	"DeleteFailDesc": "ไม่สามารถลบข้อความ",
	"Discard": "ยกเลิก",
	"DiscardConfirm": "คุณต้องการลบข้อความปัจจุบันหรือไม่",
	"DownloadFail": "ไม่สามารถดาวน์โหลด",
	"DownloadFailDesc": "ไม่สามารถรับข้อมูลจากโทรศัพท์",
	"DownloadSmsMessages": "อัปเดตกล่องจดหมายขาเข้า",
	"From": "จาก: {from}",
	"Inbox": "กล่องจดหมายขาเข้า",
	"InstanceDisconnectDesc": "ไม่สามารถเชื่อมต่อกับบัญชีได้",
	"ListDownloadFail": "ไม่สามารถดาวน์โหลดรายการ",
	"MemoryFull": "หน่วยความจำเต็ม",
	"Message": "ข้อความ: {Msg}",
	"MessagePreset": "ข้อความที่กำหนดไว้ล่วงหน้า",
	"NotificationNotSupported": "ไม่รองรับการแจ้งเตือน",
	"Reply": "ตอบกลับ",
	"Retry": "ลองใหม่",
	"Return": "กลับคืน",
	"SMSDeleteConfirm": "ข้อความนี้จะถูกลบออกจากอุปกรณ์เคลื่อนที่และไม่สามารถกู้คืนได้ คุณแน่ใจหรือไม่ว่าต้องการลบ",
	"SelectContact": "เลือกผู้ติดต่อ",
	"SelectMessage": "เลือกข้อความ",
	"Send": "ส่ง",
	"SendConfirm": "คุณยังต้องการส่งข้อความนี้หรือไม่",
	"SendFail": "ไม่สามารถส่ง",
	"SendFailDesc": "ไม่สามารถส่งข้อความไปยังโทรศัพท์",
	"SendingMessage": "กำลังส่งข้อความ",
	"SpeedRestriction": "เพื่อความปลอดภัยของคุณ ข้อความจะไม่ถูกแสดง",
	"TTSReadFail": "ไม่สามารถอ่านข้อความ",
	"TextMessageSent": "SMS ถูกส่งแล้ว",
	"TextMessages": "SMS",
	"To": "ถึง: {To}",
	"UnfinishedTextMessage": "มีข้อความที่ไม่สมบูรณ์ที่คุณต้องจัดการ",
	"Updating": "กำลังอัปเดต",
	"VrHelp_SMSMessageDetail_Help_Left1": "Communication",
	"VrHelp_SMSMessageDetail_Help_Left2": "Inbox",
	"VrHelp_SMSMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_SMSMessageDetail_Help_Left4": "Previous",
	"VrHelp_SMSMessageDetail_Help_Left5": "Next",
	"VrHelp_SMSMessageDetail_Help_Right1": "Reply",
	"VrHelp_SMSMessageDetail_Help_Right2": "Call",
	"VrHelp_SMSMessageDetail_Help_Right3": "Delete",
	"VrHelp_SMSReply_Help_Left1": "Add Message",
	"VrHelp_SMSReply_Help_Left2": "Send",
};

framework.registerAppDictLoaded("sms", "th_TH");