var Localization_smsAppDict_cs_CS = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "Příslušenství není podporováno",
	"AutoDownload": "SMS staženy",
	"Back": "Zpět",
	"ContinueMessage": "Pokračovat ve zprávě",
	"Delete": "Vymazat",
	"DeleteFail": "Nelze odstranit",
	"DeleteFailDesc": "Nelze odstranit zprávu",
	"Discard": "Odstranit",
	"DiscardConfirm": "Chcete tuto zprávu odstranit?",
	"DownloadFail": "Nelze stáhnout",
	"DownloadFailDesc": "Nelze získat údaje z telefonu",
	"DownloadSmsMessages": "Aktualizovat schránku",
	"From": "Odesílatel: {from}",
	"Inbox": "Přijaté zprávy",
	"InstanceDisconnectDesc": "Nelze se připojit k účtu",
	"ListDownloadFail": "Nelze stáhnout seznam",
	"MemoryFull": "Paměť zaplněna",
	"Message": "Zpráva: {Msg}",
	"MessagePreset": "Uložit jako šablonu",
	"NotificationNotSupported": "Oznamování není podporováno",
	"Reply": "Odpovědět",
	"Retry": "Opakovat pokus",
	"Return": "Vrátit",
	"SMSDeleteConfirm": "Tato zpráva bude z mobilního přístroje odstraněna bez možnosti obnovení. Opravdu jej chcete odstranit?",
	"SelectContact": "Vyberte kontakt",
	"SelectMessage": "Vybrat zprávu",
	"Send": "Odeslat",
	"SendConfirm": "Chcete pokračovat v odesílání této zprávy?",
	"SendFail": "Nelze odeslat",
	"SendFailDesc": "Nelze odeslat zprávu do telefonu",
	"SendingMessage": "Odesílání zprávě\n",
	"SpeedRestriction": "Pro vaši bezpečnost se zpráva nezobrazuje.",
	"TTSReadFail": "Nelze přečíst zprávu",
	"TextMessageSent": "SMS odeslána",
	"TextMessages": "SMS",
	"To": "Adresát: {To}",
	"UnfinishedTextMessage": "Nedokončenou zprávu je třeba ukončit.",
	"Updating": "Aktualizace",
	"VrHelp_SMSMessageDetail_Help_Left1": "Communication",
	"VrHelp_SMSMessageDetail_Help_Left2": "Inbox",
	"VrHelp_SMSMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_SMSMessageDetail_Help_Left4": "Previous",
	"VrHelp_SMSMessageDetail_Help_Left5": "Next",
	"VrHelp_SMSMessageDetail_Help_Right1": "Reply",
	"VrHelp_SMSMessageDetail_Help_Right2": "Call",
	"VrHelp_SMSMessageDetail_Help_Right3": "Delete",
	"VrHelp_SMSReply_Help_Left1": "Add Message",
	"VrHelp_SMSReply_Help_Left2": "Send",
};

framework.registerAppDictLoaded("sms", "cs_CS");