var Localization_smsAppDict_mn_TW = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "系統無法開啟此附件",
	"AutoDownload": "簡訊已下載",
	"Back": "回上頁",
	"ContinueMessage": "繼續傳送訊息",
	"Delete": "刪除",
	"DeleteFail": "無法刪除",
	"DeleteFailDesc": "無法刪除訊息",
	"Discard": "刪除",
	"DiscardConfirm": "確定要刪除此訊息嗎?",
	"DownloadFail": "無法下載",
	"DownloadFailDesc": "無法從行動電話取得訊息",
	"DownloadSmsMessages": "更新收件匣",
	"From": "發件人 :  {from}",
	"Inbox": "收件匣",
	"InstanceDisconnectDesc": "無法連接用戶",
	"ListDownloadFail": "無法下載清單",
	"MemoryFull": "記憶體已滿",
	"Message": "本文 : {Msg}",
	"MessagePreset": "預設訊息",
	"NotificationNotSupported": "系統無法開啟此通知",
	"Reply": "回覆",
	"Retry": "重試",
	"Return": "返回",
	"SMSDeleteConfirm": "此訊息將從系統和行動裝置刪除。 無法復原。 您確定要刪除嗎?",
	"SelectContact": "選取聯絡人",
	"SelectMessage": "選取訊息",
	"Send": "傳送",
	"SendConfirm": "要繼續傳送此訊息嗎?",
	"SendFail": "無法傳送",
	"SendFailDesc": "無法將訊息傳送至行動電話",
	"SendingMessage": "正在傳送訊息",
	"SpeedRestriction": "為了安全起見，此訊息將不顯示。",
	"TTSReadFail": "無法讀取訊息",
	"TextMessageSent": "簡訊已傳出",
	"TextMessages": "簡訊",
	"To": "收件人 :  {To}",
	"UnfinishedTextMessage": "未完成的簡訊，要刪除嗎？",
	"Updating": "更新中",
	"VrHelp_SMSMessageDetail_Help_Left1": "通訊",
	"VrHelp_SMSMessageDetail_Help_Left2": "收件箱",
	"VrHelp_SMSMessageDetail_Help_Left3": "播放 / 暫停",
	"VrHelp_SMSMessageDetail_Help_Left4": "上一個",
	"VrHelp_SMSMessageDetail_Help_Left5": "下一個",
	"VrHelp_SMSMessageDetail_Help_Right1": "回覆",
	"VrHelp_SMSMessageDetail_Help_Right2": "呼叫",
	"VrHelp_SMSMessageDetail_Help_Right3": "刪除",
	"VrHelp_SMSReply_Help_Left1": "添加消息",
	"VrHelp_SMSReply_Help_Left2": "發送",
};

framework.registerAppDictLoaded("sms", "mn_TW");