var Localization_smsAppDict_tr_TR = {
	//"stringId" : "localString"
	"AttachmentNotSupported": "Ekler Desteklenmiyor",
	"AutoDownload": "SMS İndirildi",
	"Back": "Geri",
	"ContinueMessage": "Mesaja Devam Et",
	"Delete": "Sil",
	"DeleteFail": "SMS Silme Hatası",
	"DeleteFailDesc": "Mesaj silinemiyor",
	"Discard": "Sil",
	"DiscardConfirm": "Mevcut mesajı silmek ister misiniz?",
	"DownloadFail": "SMS İndirme Hatası",
	"DownloadFailDesc": "Telefondan bilgi alınamıyor",
	"DownloadSmsMessages": "Gelen Kutusunu Güncelle",
	"From": "Kimden: {from}",
	"Inbox": "Prijemno sanduče",
	"InstanceDisconnectDesc": "Hesaba bağlanılamıyor",
	"ListDownloadFail": "SMS Listesi İndirme Hatası",
	"MemoryFull": "Hafıza Dolu Hatası",
	"Message": "Mesaj: {Msg}",
	"MessagePreset": "Mevcut Mesaj",
	"NotificationNotSupported": "Bildirimi Desteklemeyen Hata",
	"Reply": "Yanıtla",
	"Retry": "Yeniden Dene",
	"Return": "Geri Dön",
	"SMSDeleteConfirm": "Bu mesaj mobil aygıtınızdan geri alınamayacak şekilde silinecektir. Silmek istediğinizden emin misiniz?",
	"SelectContact": "Bağlantı Seç",
	"SelectMessage": "Mesaj Seçin",
	"Send": "Gönder",
	"SendConfirm": "Bu mesajı göndermeye devam etmek istiyor musunuz?",
	"SendFail": "SMS Gönderim Hatası",
	"SendFailDesc": "Mesaj telefona gönderilemiyor",
	"SendingMessage": "Mesaj Gönderiliyor",
	"SpeedRestriction": "Güvenliğiniz için, mesaj görüntülenmiyor",
	"TTSReadFail": "Mesaj okuma hatası",
	"TextMessageSent": "SMS Gönderildi",
	"TextMessages": "SMS",
	"To": "Kime: {To}",
	"UnfinishedTextMessage": "Bitmemiş bir mesaj, işlem yapmanızı gerektiriyor.",
	"Updating": "Güncelleniyor",
	"VrHelp_SMSMessageDetail_Help_Left1": "Communication",
	"VrHelp_SMSMessageDetail_Help_Left2": "Inbox",
	"VrHelp_SMSMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_SMSMessageDetail_Help_Left4": "Previous",
	"VrHelp_SMSMessageDetail_Help_Left5": "Next",
	"VrHelp_SMSMessageDetail_Help_Right1": "Reply",
	"VrHelp_SMSMessageDetail_Help_Right2": "Call",
	"VrHelp_SMSMessageDetail_Help_Right3": "Delete",
	"VrHelp_SMSReply_Help_Left1": "Add Message",
	"VrHelp_SMSReply_Help_Left2": "Send",
};

framework.registerAppDictLoaded("sms", "tr_TR");