var Localization_amradioAppDict_el_GR = {
	//"stringId" : "localString"
	"AMRadio": "Ραδιόφωνο ΑΜ",
	"AutoMemory": "Λίστα αυτόματης μνήμης",
	"Back": "Πίσω",
	"CannotBesaved": "Αδύνατη αποθ. ετικετών",
	"ConnectiPod": "Σύνδ. iPod για μεταφ. ετικ.",
	"ErrorConnection": "Σφάλμα κατά τη μεταφορά ετικετών σε iPod",
	"ErrorIpodFail": "Σφάλμα iPod",
	"ErrorNoMemoryAll": "Μνήμη πλήρης",
	"ErrorNoMemorySystem": "Πλήρης μνήμη",
	"GenreName": "Είδος: {genreName}",
	"IopdFull": "Πλήρες iPod",
	"MemoryFullsbn": "Πλήρης μνήμη ετικέτας",
	"Noresultsfound": "Δε βρέθηκε αποτέλεσμα",
	"PartialTransfer": "Μερική Μεταφορά",
	"Reconnect": "Αποσύνδ. και επανασ.",
	"Remaining": "Ακόμη {numberOfTags}",
	"Settings": "Ρυθμίσεις",
	"TagCaptured": "Ετικέτα ελήφθη",
	"TagDuplicateIpodFull": "Ετικέτα ήδη αποθ.",
	"TagNotYetProcessed": "Δεν έγινε επεξεργασία ετικέτας ακόμη",
	"TagSaved": "Ετικέτα αποθ. σε iPod",
	"TagSavedsbn": "Ετικέτα αποθηκευμένη",
	"TagSavedtoSystem": "Ετικέτα αποθ. στο σύσ.",
	"TagTransferIpodFull": "Όλες οι ετικέτες μεταφ.",
	"TagTransferNoMemory": "Αδύνατη μετ. ετικετών",
	"TagTransferSuccess": "Ετικέτες μεταφ. σε iPod",
	"TrafficAlertOff": "Ειδοποίηση κίνησης (TA) - ανενεργή",
	"TrafficAlertOn": "Ειδοποίηση κίνησης (TA)- ενεργή",
	"UpdateStationList": "Ενημέρωση λίστας σταθμών",
	"UpdatingStationList": "Ενημέρωση λίστας σταθμών",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Αγαπημένα",
	"next_Tooltip": "Αναζήτηση επόμενου",
	"prev_Tooltip": "Αναζήτηση προηγούμενου",
};

framework.registerAppDictLoaded("amradio", "el_GR");