var Localization_amradioAppDict_ro_RO = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AutoMemory": "Listă automată memorie",
	"Back": "Înapoi",
	"CannotBesaved": "Etich. nu se pot salva",
	"ConnectiPod": "Conect. iPod transf. etich.",
	"ErrorConnection": "Eroare la transferarea etichetelor pe iPod",
	"ErrorIpodFail": "Eroare iPod",
	"ErrorNoMemoryAll": "Toate memoriile sunt pline",
	"ErrorNoMemorySystem": "Memorie plină",
	"GenreName": "Gen: {genreName}",
	"IopdFull": "iPod plin",
	"MemoryFullsbn": "Memorie etichete plină",
	"Noresultsfound": "Nu s-au găsit rezultate",
	"PartialTransfer": "Transfer Parţial",
	"Reconnect": "Decuplaţi şi reconectaţi",
	"Remaining": "{numberOfTags} rămase",
	"Settings": "Setări",
	"TagCaptured": "Marcare captată",
	"TagDuplicateIpodFull": "Etichetă deja salvată",
	"TagNotYetProcessed": "Etichetă încă neprocesată",
	"TagSaved": "Etichetă salvată pe iPod",
	"TagSavedsbn": "Etichetă salvată",
	"TagSavedtoSystem": "Etichetă salvată în sistem",
	"TagTransferIpodFull": "Toate etichetele transf.",
	"TagTransferNoMemory": "Nu se pot transf. etich.",
	"TagTransferSuccess": "Etichete transf. pe iPod",
	"TrafficAlertOff": "Informaţii trafic oprite",
	"TrafficAlertOn": "Informaţii trafic pornite",
	"UpdateStationList": "Actualizare listă de posturi",
	"UpdatingStationList": "Se actualizează lista de posturi",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Favorite",
	"next_Tooltip": "Căutare următor",
	"prev_Tooltip": "Căutare precedent",
};

framework.registerAppDictLoaded("amradio", "ro_RO");