var Localization_amradioAppDict_en_UK = {
	//"stringId" : "localString"
	"AMRadio": "AM Radio",
	"AutoMemory": "Auto Memory List",
	"Back": "Back",
	"CannotBesaved": "Tags Cannot be Saved",
	"ConnectiPod": "Connect iPod to Transfer",
	"ErrorConnection": "Error While Transferring Tags to iPod",
	"ErrorIpodFail": "iPod Error",
	"ErrorNoMemoryAll": "All Memory Full",
	"ErrorNoMemorySystem": "Memory Full",
	"GenreName": "Genre: {genreName}",
	"IopdFull": "iPod Full",
	"MemoryFullsbn": "Tag Memory Full",
	"Noresultsfound": "No Results Found",
	"PartialTransfer": "Partial Transfer",
	"Reconnect": "Unplug and Reconnect",
	"Remaining": "{numberOfTags} Remaining",
	"Settings": "Settings",
	"TagCaptured": "Tag Captured",
	"TagDuplicateIpodFull": "Tag Already Saved",
	"TagNotYetProcessed": "Tag Not Yet Processed",
	"TagSaved": "Tag Saved to iPod",
	"TagSavedsbn": "Tag Saved",
	"TagSavedtoSystem": "Tag Saved to System",
	"TagTransferIpodFull": "All Tags Transferred",
	"TagTransferNoMemory": "Cannot Transfer Tags",
	"TagTransferSuccess": "Tags Transferred to iPod",
	"TrafficAlertOff": "Traffic Announcement  (TA) Off",
	"TrafficAlertOn": "Traffic Announcement  (TA) On",
	"UpdateStationList": "Update Station List",
	"UpdatingStationList": "Updating Station List",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favourites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favourites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favourites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Favourites",
	"next_Tooltip": "Seek Next",
	"prev_Tooltip": "Seek Previous",
};

framework.registerAppDictLoaded("amradio", "en_UK");