var Localization_amradioAppDict_zh_TW = {
	//"stringId" : "localString"
	"AMRadio": "AM",
	"AutoMemory": "自動記憶清單",
	"Back": "返回",
	"CannotBesaved": "無法儲存標籤",
	"ConnectiPod": "連接 iPod 以轉移標籤",
	"ErrorConnection": "向 iPod 轉移標籤時出現錯誤",
	"ErrorIpodFail": "iPod錯誤",
	"ErrorNoMemoryAll": "所有記憶體已滿",
	"ErrorNoMemorySystem": "記憶體已滿",
	"GenreName": "類型：{genreName}",
	"IopdFull": "iPod已滿",
	"MemoryFullsbn": "標籤記憶體已滿",
	"Noresultsfound": "沒有找到結果",
	"PartialTransfer": "部分轉移",
	"Reconnect": "拔掉並重新連接",
	"Remaining": "剩餘{numberOfTags}",
	"Settings": "設置",
	"TagCaptured": "標籤已捕獲",
	"TagDuplicateIpodFull": "標籤已儲存",
	"TagNotYetProcessed": "標籤尚未處理",
	"TagSaved": "標籤被儲存到iPod",
	"TagSavedsbn": "標籤已儲存",
	"TagSavedtoSystem": "標籤被儲存到系統",
	"TagTransferIpodFull": "已轉移所有標籤",
	"TagTransferNoMemory": "無法轉移標籤",
	"TagTransferSuccess": "標籤被轉移到iPod",
	"TrafficAlertOff": "關閉交通警告(TA)",
	"TrafficAlertOn": "開啟交通警告(TA)",
	"UpdateStationList": "更新電台列表",
	"UpdatingStationList": "正在更新電台列表",
	"VrHelp_AutoMemory_Help1_Left1": "（頻率）",
	"VrHelp_AutoMemory_Help1_Left2": "更新列表",
	"VrHelp_AutoMemory_Help2_Left1": "更新列表",
	"VrHelp_NowPlaying_EU_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_EU_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_EU_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_EU_Help_Left4": "掃描",
	"VrHelp_NowPlaying_EU_Help_Left5": "調台",
	"VrHelp_NowPlaying_EU_Help_Right1": "交通警告(TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "搜索上一個",
	"VrHelp_NowPlaying_EU_Help_Right3": "搜索下一個",
	"VrHelp_NowPlaying_EU_Help_Right4": "聲音設置",
	"VrHelp_NowPlaying_Japan_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Japan_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_Japan_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_Japan_Help_Left4": "掃描",
	"VrHelp_NowPlaying_Japan_Help_Left5": "調台",
	"VrHelp_NowPlaying_Japan_Help_Right1": "搜索上一個",
	"VrHelp_NowPlaying_Japan_Help_Right2": "搜索下一個",
	"VrHelp_NowPlaying_Japan_Help_Right3": "聲音設置",
	"VrHelp_NowPlaying_US_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_US_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_US_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_US_Help_Left4": "打開 HD / 關閉 HD",
	"VrHelp_NowPlaying_US_Help_Left5": "掃描",
	"VrHelp_NowPlaying_US_Help_Right1": "調台",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes 標記",
	"VrHelp_NowPlaying_US_Help_Right3": "搜索上一個",
	"VrHelp_NowPlaying_US_Help_Right4": "搜索下一個",
	"VrHelp_NowPlaying_US_Help_Right5": "聲音設置",
	"VrHelp_Tune_Help1_Left1": "（頻率）",
	"VrHelp_Tune_Help1_Left2": "向下調台",
	"VrHelp_Tune_Help1_Left3": "向上調台",
	"VrHelp_Tune_Help2_Left1": "（頻率）",
	"VrHelp_Tune_Help2_Left2": "向下調台",
	"VrHelp_Tune_Help2_Left3": "向上調台",
	"favorites_Tooltip": "收藏夾",
	"next_Tooltip": "搜索下一個",
	"prev_Tooltip": "搜索上一個",
};

framework.registerAppDictLoaded("amradio", "zh_TW");