var Localization_amradioAppDict_lt_LT = {
	//"stringId" : "localString"
	"AMRadio": "AM radijas",
	"AutoMemory": "Automatinės atminties sąrašas",
	"Back": "Atgal",
	"CannotBesaved": "Įrašyti žymių negalima",
	"ConnectiPod": "Prijungti iPod žym. Perd.",
	"ErrorConnection": "Klaida perduodant žymes į iPod",
	"ErrorIpodFail": "iPod klaida",
	"ErrorNoMemoryAll": "Visa atmintis užpildyta",
	"ErrorNoMemorySystem": "Atmintis užpildyta",
	"GenreName": "Žanras: {genreName}",
	"IopdFull": "iPod užpildytas",
	"MemoryFullsbn": "Žymių atmintis užpildyta",
	"Noresultsfound": "Rezultatų nerasta",
	"PartialTransfer": "Dalinis perdavimas",
	"Reconnect": "Atjungti ir vėl prijungti",
	"Remaining": "Liko {numberOfTags}",
	"Settings": "Nustatymai",
	"TagCaptured": "Žymė užfiksuota",
	"TagDuplicateIpodFull": "Žymė jau įrašyta",
	"TagNotYetProcessed": "Žymė dar neapdorota",
	"TagSaved": "Žymė įrašyta iPod",
	"TagSavedsbn": "Žymė įrašyta",
	"TagSavedtoSystem": "Žymė įrašyta sistemoje",
	"TagTransferIpodFull": "Visos žymės perkeltos",
	"TagTransferNoMemory": "Negalima perduoti žymių",
	"TagTransferSuccess": "Žymės perkeltos į iPod",
	"TrafficAlertOff": "Pranešimas apie eismą išjungtas",
	"TrafficAlertOn": "Pranešimas apie eismą įjungtas",
	"UpdateStationList": "Atnaujinti stočių sąrašą",
	"UpdatingStationList": "Naujinamas stočių sąrašas",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Mėgstamiausi",
	"next_Tooltip": "Ieškoti tolimesnio",
	"prev_Tooltip": "Ieškoti prieš tai buvusio",
};

framework.registerAppDictLoaded("amradio", "lt_LT");