var Localization_amradioAppDict_no_NO = {
	//"stringId" : "localString"
	"AMRadio": "AM radio",
	"AutoMemory": "Autominneliste",
	"Back": "Tilbake",
	"CannotBesaved": "Taggene kan ikke lagres",
	"ConnectiPod": "Koble iPod til Tags",
	"ErrorConnection": "Feil ved overføring av tagger til iPod",
	"ErrorIpodFail": "iPod-feil",
	"ErrorNoMemoryAll": "Minne er fullt",
	"ErrorNoMemorySystem": "Minnet er fullt",
	"GenreName": "Sjanger: {genreName}",
	"IopdFull": "iPod er full",
	"MemoryFullsbn": "Tagg-minnet er fullt",
	"Noresultsfound": "Fant ingen resultater",
	"PartialTransfer": "Delvis overføring",
	"Reconnect": "Koble fra og til på nytt",
	"Remaining": "{numberOfTags} gjenstår",
	"Settings": "Innstillinger",
	"TagCaptured": "Tagg opptak",
	"TagDuplicateIpodFull": "Taggen er allerede lagret",
	"TagNotYetProcessed": "Taggen er ikke behandlet ennå",
	"TagSaved": "Taggen er lagret på iPod",
	"TagSavedsbn": "Taggen er lagret",
	"TagSavedtoSystem": "Taggen er lagret på syst.",
	"TagTransferIpodFull": "Alle taggene er overført",
	"TagTransferNoMemory": "Kan ikke overføre tagger",
	"TagTransferSuccess": "Taggene overført til iPod",
	"TrafficAlertOff": "Trafikkmelding (TA) av",
	"TrafficAlertOn": "Trafikkmelding (TA) på",
	"UpdateStationList": "Oppdater stasjonsliste",
	"UpdatingStationList": "Oppdaterer stasjonsliste",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Favoritter",
	"next_Tooltip": "Gå til neste",
	"prev_Tooltip": "Gå til forrige",
};

framework.registerAppDictLoaded("amradio", "no_NO");