var Localization_amradioAppDict_he_IL = {
	//"stringId" : "localString"
	"AMRadio": "רדיו AM",
	"AutoMemory": "רשימת זכרון אוטומטי",
	"Back": "חזרה",
	"CannotBesaved": "לא ניתן לשמור תגיות",
	"ConnectiPod": "חבראייפודלהעבירתאגיות",
	"ErrorConnection": "שגיאה בזמן העברת תגיות ל-iPod",
	"ErrorIpodFail": "שגיאת iPod",
	"ErrorNoMemoryAll": "כל הזכרון מלא",
	"ErrorNoMemorySystem": "זיכרון מלא",
	"GenreName": "סוג: {genreName}",
	"IopdFull": "iPod  מלא",
	"MemoryFullsbn": "זיכרון התגיות מלא",
	"Noresultsfound": "לא נמצאו תוצאות",
	"PartialTransfer": "העברה חלקית",
	"Reconnect": "נתק וחבר מחדש",
	"Remaining": "נותרו {numberOfTags}",
	"Settings": "הגדרות",
	"TagCaptured": "התג אותר",
	"TagDuplicateIpodFull": "התגית נשמרה כבר",
	"TagNotYetProcessed": "התגית עדיין לא מעובדת",
	"TagSaved": "תגית נשמרה ב-iPod",
	"TagSavedsbn": "תגית נשמרה",
	"TagSavedtoSystem": "התגית נשמרה במערכת",
	"TagTransferIpodFull": "כל התגיות הועברו",
	"TagTransferNoMemory": "לא יכול להעביר תגיות",
	"TagTransferSuccess": "תגיות הועברו ל-iPod",
	"TrafficAlertOff": "הודעת תנועה כבוי",
	"TrafficAlertOn": "הודעת תנועה מופעל",
	"UpdateStationList": "עדכן רשימת תחנות",
	"UpdatingStationList": "מעדכן את רשימת התחנות",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)\u200e",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "מועדפים",
	"next_Tooltip": "חפש הבא",
	"prev_Tooltip": "חפש קודם",
};

framework.registerAppDictLoaded("amradio", "he_IL");