var Localization_amradioAppDict_ar_SA = {
	//"stringId" : "localString"
	"AMRadio": "راديو AM",
	"AutoMemory": "قائمة الذاكرة التلقائية",
	"Back": "رجوع",
	"CannotBesaved": "لا يمكن حفظ العلامات",
	"ConnectiPod": "صل iPod لنقل العلامات",
	"ErrorConnection": "حدث خطأ أثناء نقل العلامات إلى iPod",
	"ErrorIpodFail": "حدث خطا في جهاز الـiPod",
	"ErrorNoMemoryAll": "الذاكرة ممتلئة بالكامل",
	"ErrorNoMemorySystem": "الذاكرة ممتلئة",
	"GenreName": "النوع: {genreName}",
	"IopdFull": "جهاز الـiPod ممتلئ",
	"MemoryFullsbn": "ذاكرة العلامات ممتلئة",
	"Noresultsfound": "لم يتم العثور على نتائج",
	"PartialTransfer": "نقل جزئي",
	"Reconnect": "افصل وأعد التوصيل",
	"Remaining": "متبقي {numberOfTags}",
	"Settings": "الإعدادات",
	"TagCaptured": "العلامة المرجعية الملتقطة",
	"TagDuplicateIpodFull": "تم حفظ العلامة بالفعل",
	"TagNotYetProcessed": "لم يتم معالجة العلامة بعد",
	"TagSaved": "حفظت العلامة على iPod",
	"TagSavedsbn": "تم حفظ العلامة",
	"TagSavedtoSystem": "حفظت العلامة في النظام",
	"TagTransferIpodFull": "تم نقل جميع العلامات",
	"TagTransferNoMemory": "لا يمكن نقل العلامات",
	"TagTransferSuccess": "تم نقل العلامات إلى iPod",
	"TrafficAlertOff": "إيقاف تنبيه التنقل",
	"TrafficAlertOn": "تشغيل تنبيه التنقل",
	"UpdateStationList": "تحديث قائمة المحطة",
	"UpdatingStationList": "تحديث قائمة المحطة",
	"VrHelp_AutoMemory_Help1_Left1": "(التردد)",
	"VrHelp_AutoMemory_Help1_Left2": "تحديث القائمة",
	"VrHelp_AutoMemory_Help2_Left1": "تحديث القائمة",
	"VrHelp_NowPlaying_EU_Help_Left1": "ترفيه ",
	"VrHelp_NowPlaying_EU_Help_Left2": "الذاكرة التلقائية ",
	"VrHelp_NowPlaying_EU_Help_Left3": "المفضلة",
	"VrHelp_NowPlaying_EU_Help_Left4": "المسح الضوئي ",
	"VrHelp_NowPlaying_EU_Help_Left5": "وضبط الراديو",
	"VrHelp_NowPlaying_EU_Help_Right1": "تنبيه التنقل",
	"VrHelp_NowPlaying_EU_Help_Right2": "بحث عن السابق",
	"VrHelp_NowPlaying_EU_Help_Right3": "بحث عن التالي",
	"VrHelp_NowPlaying_EU_Help_Right4": "إعدادات الصوت",
	"VrHelp_NowPlaying_Japan_Help_Left1": "ترفيه ",
	"VrHelp_NowPlaying_Japan_Help_Left2": "الذاكرة التلقائية ",
	"VrHelp_NowPlaying_Japan_Help_Left3": "المفضلة",
	"VrHelp_NowPlaying_Japan_Help_Left4": "المسح الضوئي ",
	"VrHelp_NowPlaying_Japan_Help_Left5": "وضبط الراديو",
	"VrHelp_NowPlaying_Japan_Help_Right1": "بحث عن السابق",
	"VrHelp_NowPlaying_Japan_Help_Right2": "بحث عن التالي",
	"VrHelp_NowPlaying_Japan_Help_Right3": "إعدادات الصوت",
	"VrHelp_NowPlaying_US_Help_Left1": "ترفيه ",
	"VrHelp_NowPlaying_US_Help_Left2": "الذاكرة التلقائية ",
	"VrHelp_NowPlaying_US_Help_Left3": "المفضلة",
	"VrHelp_NowPlaying_US_Help_Left4": "وتشغيل / وايقاف HD",
	"VrHelp_NowPlaying_US_Help_Left5": "المسح الضوئي ",
	"VrHelp_NowPlaying_US_Help_Right1": "وضبط الراديو",
	"VrHelp_NowPlaying_US_Help_Right2": "علامة iTunes",
	"VrHelp_NowPlaying_US_Help_Right3": "بحث عن السابق",
	"VrHelp_NowPlaying_US_Help_Right4": "بحث عن التالي",
	"VrHelp_NowPlaying_US_Help_Right5": "إعدادات الصوت",
	"VrHelp_Tune_Help1_Left1": "(التردد)",
	"VrHelp_Tune_Help1_Left2": "توليف لأسفل",
	"VrHelp_Tune_Help1_Left3": "توليف لأعلى",
	"VrHelp_Tune_Help2_Left1": "(التردد)",
	"VrHelp_Tune_Help2_Left2": "توليف لأسفل",
	"VrHelp_Tune_Help2_Left3": "توليف لأعلى",
	"favorites_Tooltip": "المفضلات",
	"next_Tooltip": "بحث عن التالي",
	"prev_Tooltip": "بحث عن السابق",
};

framework.registerAppDictLoaded("amradio", "ar_SA");