var Localization_amradioAppDict_et_EE = {
	//"stringId" : "localString"
	"AMRadio": "AM raadio",
	"AutoMemory": "Automaatse mälu loend",
	"Back": "Tagasi",
	"CannotBesaved": "Silte ei saa salvestada",
	"ConnectiPod": "Üh iPod siltide edastam",
	"ErrorConnection": "Viga siltide edastamisel iPodi",
	"ErrorIpodFail": "iPodi viga",
	"ErrorNoMemoryAll": "Kogu mälu on täis",
	"ErrorNoMemorySystem": "Mälu täis",
	"GenreName": "Žanr: {genreName}",
	"IopdFull": "iPod täis",
	"MemoryFullsbn": "Sildi mälu täis",
	"Noresultsfound": "Tulemusi ei leitud",
	"PartialTransfer": "Sõidu monitor",
	"Reconnect": "Lahutage ja ühend. uuesti",
	"Remaining": "{numberOfTags} jäänud",
	"Settings": "Sätted",
	"TagCaptured": "Silt jäädvustatud",
	"TagDuplicateIpodFull": "Silt on juba salvestatud",
	"TagNotYetProcessed": "Silti pole veel töödeldud",
	"TagSaved": "Silt on iPodi salvestatud",
	"TagSavedsbn": "Silt on salvestatud",
	"TagSavedtoSystem": "Silt süsteemi salvestatud",
	"TagTransferIpodFull": "Kõik sildid edastatud",
	"TagTransferNoMemory": "Silte ei saa edastada",
	"TagTransferSuccess": "Sildid on iPodi edastatud",
	"TrafficAlertOff": "Liiklusteade (TA) väljas",
	"TrafficAlertOn": "Liiklusteade (TA) sees",
	"UpdateStationList": "Värskenda jaamade loendit",
	"UpdatingStationList": "Jaamade loendi värskendamine",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Lemmikud",
	"next_Tooltip": "Otsi järgmist",
	"prev_Tooltip": "Otsi eelmist",
};

framework.registerAppDictLoaded("amradio", "et_EE");