var Localization_amradioAppDict_ms_MY = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AutoMemory": "Senarai Memori Auto",
	"Back": "Kembali",
	"CannotBesaved": "Teg Tidak Dapat Disimpan",
	"ConnectiPod": "Smbng iPod utk Pindah Teg",
	"ErrorConnection": "Ralat Berlaku Semasa Memindahkan Teg ke iPod",
	"ErrorIpodFail": "Ralat iPod",
	"ErrorNoMemoryAll": "Semua Memori Penuh",
	"ErrorNoMemorySystem": "Memori Penuh",
	"GenreName": "Genre: {genreName}",
	"IopdFull": "iPod Penuh",
	"MemoryFullsbn": "Memori Teg Penuh",
	"Noresultsfound": "Tiada hasil ditemui",
	"PartialTransfer": "Pindahan Separa",
	"Reconnect": "Tanggal & Samb. Semula",
	"Remaining": "{numberOfTags} Berbaki",
	"Settings": "Tetapan",
	"TagCaptured": "Teg Dirakamkan",
	"TagDuplicateIpodFull": "Teg Telah Disimpan",
	"TagNotYetProcessed": "Teg Belum Diproses Lagi",
	"TagSaved": "Teg Disimpan pada iPod",
	"TagSavedsbn": "Teg Disimpan",
	"TagSavedtoSystem": "Teg Disimpan pada Sistem",
	"TagTransferIpodFull": "Semua Teg Dipindahkan",
	"TagTransferNoMemory": "Tdk Blh Pindah Tag",
	"TagTransferSuccess": "Teg Dipindahkan ke iPod",
	"TrafficAlertOff": "Makluman Lalu Lintas  (TA) Dimatikan",
	"TrafficAlertOn": "Makluman Lalu Lintas  (TA) Dihidupkan",
	"UpdateStationList": "Kemaskini Senarai Stesen",
	"UpdatingStationList": "Mengemas Kini Senarai Stesen",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Kegemaran",
	"next_Tooltip": "Cari Seterusnya",
	"prev_Tooltip": "Cari Sebelumnya",
};

framework.registerAppDictLoaded("amradio", "ms_MY");