var Localization_amradioAppDict_mn_TW = {
	//"stringId" : "localString"
	"AMRadio": "AM 廣播電台",
	"AutoMemory": "電台清單",
	"Back": "回上頁",
	"CannotBesaved": "無法儲存標籤",
	"ConnectiPod": "連接 iPod 以傳送",
	"ErrorConnection": "將標籤傳送至 iPod 時發生錯誤",
	"ErrorIpodFail": "iPod 錯誤",
	"ErrorNoMemoryAll": "所有記憶體皆已滿",
	"ErrorNoMemorySystem": "記憶體已滿",
	"GenreName": "類型 :  {genreName}",
	"IopdFull": "iPod 已滿",
	"MemoryFullsbn": "標籤記憶體已滿",
	"Noresultsfound": "查無搜尋結果",
	"PartialTransfer": "部分傳送",
	"Reconnect": "拔除並重新連接",
	"Remaining": "剩餘 {numberOfTags}",
	"Settings": "設定",
	"TagCaptured": "已擷取標籤",
	"TagDuplicateIpodFull": "已儲存標籤",
	"TagNotYetProcessed": "尚未處理標籤",
	"TagSaved": "標籤已儲存至 iPod",
	"TagSavedsbn": "已儲存標籤",
	"TagSavedtoSystem": "標籤已儲存至系統",
	"TagTransferIpodFull": "已傳送所有標籤",
	"TagTransferNoMemory": "無法傳送標籤",
	"TagTransferSuccess": "標籤已傳送至 iPod",
	"TrafficAlertOff": "關閉路況提示(TA)",
	"TrafficAlertOn": "開啟路況提示(TA)",
	"UpdateStationList": "更新電台清單",
	"UpdatingStationList": "正在更新電台清單",
	"VrHelp_AutoMemory_Help1_Left1": "（頻率）",
	"VrHelp_AutoMemory_Help1_Left2": "更新列表",
	"VrHelp_AutoMemory_Help2_Left1": "更新列表",
	"VrHelp_NowPlaying_EU_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_EU_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_EU_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_EU_Help_Left4": "掃描",
	"VrHelp_NowPlaying_EU_Help_Left5": "調台",
	"VrHelp_NowPlaying_EU_Help_Right1": "交通警告(TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "搜索上一個",
	"VrHelp_NowPlaying_EU_Help_Right3": "搜索下一個",
	"VrHelp_NowPlaying_EU_Help_Right4": "聲音設置",
	"VrHelp_NowPlaying_Japan_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_Japan_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_Japan_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_Japan_Help_Left4": "掃描",
	"VrHelp_NowPlaying_Japan_Help_Left5": "調台",
	"VrHelp_NowPlaying_Japan_Help_Right1": "搜索上一個",
	"VrHelp_NowPlaying_Japan_Help_Right2": "搜索下一個",
	"VrHelp_NowPlaying_Japan_Help_Right3": "聲音設置",
	"VrHelp_NowPlaying_US_Help_Left1": "娛樂",
	"VrHelp_NowPlaying_US_Help_Left2": "自動記憶",
	"VrHelp_NowPlaying_US_Help_Left3": "收藏夾",
	"VrHelp_NowPlaying_US_Help_Left4": "打開 HD / 關閉 HD",
	"VrHelp_NowPlaying_US_Help_Left5": "掃描",
	"VrHelp_NowPlaying_US_Help_Right1": "調台",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes 標記",
	"VrHelp_NowPlaying_US_Help_Right3": "搜索上一個",
	"VrHelp_NowPlaying_US_Help_Right4": "搜索下一個",
	"VrHelp_NowPlaying_US_Help_Right5": "聲音設置",
	"VrHelp_Tune_Help1_Left1": "（頻率）",
	"VrHelp_Tune_Help1_Left2": "向下調台",
	"VrHelp_Tune_Help1_Left3": "向上調台",
	"VrHelp_Tune_Help2_Left1": "（頻率）",
	"VrHelp_Tune_Help2_Left2": "向下調台",
	"VrHelp_Tune_Help2_Left3": "向上調台",
	"favorites_Tooltip": "我的最愛",
	"next_Tooltip": "搜尋下一個",
	"prev_Tooltip": "搜尋上一個",
};

framework.registerAppDictLoaded("amradio", "mn_TW");