var Localization_amradioAppDict_it_IT = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AutoMemory": "Elenco memoria automatica",
	"Back": "Indietro",
	"CannotBesaved": "Impossibile salvare le tag",
	"ConnectiPod": "Conn iPod per trasfer tag",
	"ErrorConnection": "Errore durante il trasferimento dell'etichetta su iPod.",
	"ErrorIpodFail": "Errore iPod ",
	"ErrorNoMemoryAll": "Memoria piena",
	"ErrorNoMemorySystem": "Memoria piena",
	"GenreName": "Genere: {genreName}",
	"IopdFull": "iPod Pieno.",
	"MemoryFullsbn": "Memoria etichette piena",
	"Noresultsfound": "Nessun risultato trovato",
	"PartialTransfer": "Trasferimento parziale",
	"Reconnect": "Sconnetti e riconnetti",
	"Remaining": "{numberOfTags} Rimanenti",
	"Settings": "Impostazioni",
	"TagCaptured": "Tag preso",
	"TagDuplicateIpodFull": "Etichetta già salvata",
	"TagNotYetProcessed": "Etichetta non ancora processata.",
	"TagSaved": "Etichetta salvata su iPod",
	"TagSavedsbn": "Etichetta salvata",
	"TagSavedtoSystem": "Tag salvata su sistema",
	"TagTransferIpodFull": "Tutte le tag trasferite.",
	"TagTransferNoMemory": "Impossibile trasferire tag.",
	"TagTransferSuccess": "Tag trasferite su iPod.",
	"TrafficAlertOff": "Annunci sul traffico (TA) spento",
	"TrafficAlertOn": "Annunci sul traffico (TA) acceso",
	"UpdateStationList": "Aggiorna elenco stazioni",
	"UpdatingStationList": "Aggiornamento elenco stazioni",
	"VrHelp_AutoMemory_Help1_Left1": "(frequenza)",
	"VrHelp_AutoMemory_Help1_Left2": "Aggiorna elenco",
	"VrHelp_AutoMemory_Help2_Left1": "Aggiorna elenco",
	"VrHelp_NowPlaying_EU_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_EU_Help_Left2": "Memoria automatica",
	"VrHelp_NowPlaying_EU_Help_Left3": "Preferiti",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scansione",
	"VrHelp_NowPlaying_EU_Help_Left5": "Sintonizza",
	"VrHelp_NowPlaying_EU_Help_Right1": "Annuncio sul traffico (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Cerca precedente",
	"VrHelp_NowPlaying_EU_Help_Right3": "Cerca successivo ",
	"VrHelp_NowPlaying_EU_Help_Right4": "Impostazioni audio",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Memoria automatica",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Preferiti",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scansione",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Sintonizza",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Cerca precedente",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Cerca successivo ",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Impostazioni audio",
	"VrHelp_NowPlaying_US_Help_Left1": "Intrattenimento",
	"VrHelp_NowPlaying_US_Help_Left2": "Memoria automatica",
	"VrHelp_NowPlaying_US_Help_Left3": "Preferiti",
	"VrHelp_NowPlaying_US_Help_Left4": "HD acceso / spento",
	"VrHelp_NowPlaying_US_Help_Left5": "Scansione",
	"VrHelp_NowPlaying_US_Help_Right1": "Sintonizza",
	"VrHelp_NowPlaying_US_Help_Right2": "Tag iTunes",
	"VrHelp_NowPlaying_US_Help_Right3": "Cerca precedente",
	"VrHelp_NowPlaying_US_Help_Right4": "Cerca successivo ",
	"VrHelp_NowPlaying_US_Help_Right5": "Impostazioni audio",
	"VrHelp_Tune_Help1_Left1": "(frequenza)",
	"VrHelp_Tune_Help1_Left2": "Sintonizza avanti",
	"VrHelp_Tune_Help1_Left3": "Sintonizza indietro",
	"VrHelp_Tune_Help2_Left1": "(frequenza)",
	"VrHelp_Tune_Help2_Left2": "Sintonizza avanti",
	"VrHelp_Tune_Help2_Left3": "Sintonizza indietro",
	"favorites_Tooltip": "Preferiti",
	"next_Tooltip": "Cerca successivo",
	"prev_Tooltip": "Cerca precedente",
};

framework.registerAppDictLoaded("amradio", "it_IT");