var Localization_amradioAppDict_es_ES = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AutoMemory": "Lista de emisoras auto memorizadas",
	"Back": "Volver",
	"CannotBesaved": "No puede guardar Etiq.",
	"ConnectiPod": "Conec iPod y Transf. Etiq.",
	"ErrorConnection": "Error mientras se transferían etiquetas al iPod",
	"ErrorIpodFail": "Error de iPod",
	"ErrorNoMemoryAll": "Toda la memoria llena",
	"ErrorNoMemorySystem": "Memoria llena",
	"GenreName": "Género: {genreName}",
	"IopdFull": "iPod Lleno",
	"MemoryFullsbn": "Memoria de Etiquetas Llena",
	"Noresultsfound": "No se encontraron resultados",
	"PartialTransfer": "Transferencia parcial",
	"Reconnect": "Desconectar y Reconectar",
	"Remaining": "{numberOfTags} Restant",
	"Settings": "Configuraciones",
	"TagCaptured": "Etiqueta capturada",
	"TagDuplicateIpodFull": "Etiqueta ya guardada",
	"TagNotYetProcessed": "La Etiqueta Aún no se ha Procesado",
	"TagSaved": "Etiqueta guardada en iPod",
	"TagSavedsbn": "Etiqueta Guardada",
	"TagSavedtoSystem": "Etiqueta Guardada el Sist",
	"TagTransferIpodFull": "Todas Etiq. transf.",
	"TagTransferNoMemory": "No puede Transf. Etiq.",
	"TagTransferSuccess": "Etiq. Transf. a iPod",
	"TrafficAlertOff": "Anuncio de tráfico (TA) apagado",
	"TrafficAlertOn": "Anuncio de tráfico (TA) encendido",
	"UpdateStationList": "Actualizar lista de emisoras",
	"UpdatingStationList": "Actualizando lista de emisoras",
	"VrHelp_AutoMemory_Help1_Left1": "(frecuencia)",
	"VrHelp_AutoMemory_Help1_Left2": "Actualizar Lista",
	"VrHelp_AutoMemory_Help2_Left1": "Actualizar Lista",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entretenimiento",
	"VrHelp_NowPlaying_EU_Help_Left2": "Memoria automática",
	"VrHelp_NowPlaying_EU_Help_Left3": " Favoritos",
	"VrHelp_NowPlaying_EU_Help_Left4": "Explorar",
	"VrHelp_NowPlaying_EU_Help_Left5": "Sintonizar",
	"VrHelp_NowPlaying_EU_Help_Right1": "Anuncio de tráfico (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Buscar Anterior",
	"VrHelp_NowPlaying_EU_Help_Right3": "Buscar Siguiente",
	"VrHelp_NowPlaying_EU_Help_Right4": "Ajustes de sonido",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entretenimiento",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Memoria Automática",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favoritos",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Explorar",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Sintonizar",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Buscar Anterior",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Buscar Siguiente",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Ajustes de sonido",
	"VrHelp_NowPlaying_US_Help_Left1": "Entretenimiento",
	"VrHelp_NowPlaying_US_Help_Left2": "Memoria automática",
	"VrHelp_NowPlaying_US_Help_Left3": " Favoritos",
	"VrHelp_NowPlaying_US_Help_Left4": "HD Encendido / Apagado",
	"VrHelp_NowPlaying_US_Help_Left5": "Explorar",
	"VrHelp_NowPlaying_US_Help_Right1": "Sintonizar",
	"VrHelp_NowPlaying_US_Help_Right2": "Etiquetado de iTunes",
	"VrHelp_NowPlaying_US_Help_Right3": "Buscar Anterior",
	"VrHelp_NowPlaying_US_Help_Right4": "Buscar Siguiente",
	"VrHelp_NowPlaying_US_Help_Right5": "Ajustes de sonido",
	"VrHelp_Tune_Help1_Left1": "(frecuencia)",
	"VrHelp_Tune_Help1_Left2": "Sintonizar Abajo",
	"VrHelp_Tune_Help1_Left3": "Sintonizar Arriba",
	"VrHelp_Tune_Help2_Left1": "(frecuencia)",
	"VrHelp_Tune_Help2_Left2": "Sintonizar Abajo",
	"VrHelp_Tune_Help2_Left3": "Sintonizar Arriba",
	"favorites_Tooltip": "Favoritos",
	"next_Tooltip": "Buscar Siguiente",
	"prev_Tooltip": "Buscar Anterior ",
};

framework.registerAppDictLoaded("amradio", "es_ES");