var Localization_amradioAppDict_ja_JP = {
	//"stringId" : "localString"
	"AMRadio": "AM",
	"AutoMemory": "放送局",
	"Back": "戻る",
	"CannotBesaved": "タグを保存できません。",
	"ConnectiPod": "iPodに接続してタグを転送",
	"ErrorConnection": "iPodにタグを転送中に\nエラーが発生しました。",
	"ErrorIpodFail": "iPodエラー",
	"ErrorNoMemoryAll": "メモリが一杯です。",
	"ErrorNoMemorySystem": "メモリが一杯です。",
	"GenreName": "ジャンル : {genreName}",
	"IopdFull": "iPod Full",
	"MemoryFullsbn": "タグメモリが一杯です",
	"Noresultsfound": "放送局が見つかりませんでした",
	"PartialTransfer": "N/A",
	"Reconnect": "プラグを抜いて再接続",
	"Remaining": "残り: {numberOfTags}",
	"Settings": "設定",
	"TagCaptured": "N/A",
	"TagDuplicateIpodFull": "タグは保存済み",
	"TagNotYetProcessed": "タグはまだ処理されて\nいません。",
	"TagSaved": "タグをiPodに保存しました。",
	"TagSavedsbn": "タグを保存しました",
	"TagSavedtoSystem": "タグは保存されました。",
	"TagTransferIpodFull": "タグをすべて転送しました。",
	"TagTransferNoMemory": "タグを転送できません。",
	"TagTransferSuccess": "iPodにタグを転送しました。",
	"TrafficAlertOff": "交通情報オフ",
	"TrafficAlertOn": "交通情報オン",
	"UpdateStationList": "リストを更新",
	"UpdatingStationList": "更新中...",
	"VrHelp_AutoMemory_Help1_Left1": "(周波数)",
	"VrHelp_AutoMemory_Help1_Left2": "リストを更新",
	"VrHelp_AutoMemory_Help2_Left1": "リストを更新",
	"VrHelp_NowPlaying_EU_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlaying_EU_Help_Left2": "放送局",
	"VrHelp_NowPlaying_EU_Help_Left3": "お気に入り",
	"VrHelp_NowPlaying_EU_Help_Left4": "スキャン",
	"VrHelp_NowPlaying_EU_Help_Left5": "チューニング",
	"VrHelp_NowPlaying_EU_Help_Right1": "交通情報",
	"VrHelp_NowPlaying_EU_Help_Right2": "シークダウン",
	"VrHelp_NowPlaying_EU_Help_Right3": "シークアップ",
	"VrHelp_NowPlaying_EU_Help_Right4": "サウンド設定",
	"VrHelp_NowPlaying_Japan_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlaying_Japan_Help_Left2": "放送局",
	"VrHelp_NowPlaying_Japan_Help_Left3": "お気に入り",
	"VrHelp_NowPlaying_Japan_Help_Left4": "スキャン",
	"VrHelp_NowPlaying_Japan_Help_Left5": "チューニング",
	"VrHelp_NowPlaying_Japan_Help_Right1": "シークダウン",
	"VrHelp_NowPlaying_Japan_Help_Right2": "シークアップ",
	"VrHelp_NowPlaying_Japan_Help_Right3": "サウンド設定",
	"VrHelp_NowPlaying_US_Help_Left1": "エンターテイメント",
	"VrHelp_NowPlaying_US_Help_Left2": "放送局",
	"VrHelp_NowPlaying_US_Help_Left3": "お気に入り",
	"VrHelp_NowPlaying_US_Help_Left4": "HDオン/オフ",
	"VrHelp_NowPlaying_US_Help_Left5": "スキャン",
	"VrHelp_NowPlaying_US_Help_Right1": "チューニング",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "シークダウン",
	"VrHelp_NowPlaying_US_Help_Right4": "シークアップ",
	"VrHelp_NowPlaying_US_Help_Right5": "サウンド設定",
	"VrHelp_Tune_Help1_Left1": "(周波数)",
	"VrHelp_Tune_Help1_Left2": "周波数を下げる",
	"VrHelp_Tune_Help1_Left3": "周波数を上げる",
	"VrHelp_Tune_Help2_Left1": "(周波数)",
	"VrHelp_Tune_Help2_Left2": "周波数を下げる",
	"VrHelp_Tune_Help2_Left3": "周波数を上げる",
	"favorites_Tooltip": "お気に入り",
	"next_Tooltip": "次へ",
	"prev_Tooltip": "前へ",
};

framework.registerAppDictLoaded("amradio", "ja_JP");