var Localization_amradioAppDict_pl_PL = {
	//"stringId" : "localString"
	"AMRadio": "Radio AM",
	"AutoMemory": "Lista zapamiętanych automatycznie",
	"Back": "Do tyłu",
	"CannotBesaved": "Zapis znaczn. niemożliwy",
	"ConnectiPod": "Podł. iPod by przesł. znacz.",
	"ErrorConnection": "Błąd podczas przesyłania znaczników do tabletu iPod.",
	"ErrorIpodFail": "Błąd tabletu iPod.",
	"ErrorNoMemoryAll": "Pamięć pełna",
	"ErrorNoMemorySystem": "Pamięć pełna",
	"GenreName": "Gatunek: {genreName}",
	"IopdFull": "Pamięć tabletu iPod pełna",
	"MemoryFullsbn": "Pamięć znaczników pełna",
	"Noresultsfound": "Nie znaleziono wyników.",
	"PartialTransfer": "Częściowo przesłane",
	"Reconnect": "Odłącz i połącz ponownie",
	"Remaining": "{numberOfTags} pozost.",
	"Settings": "Ustawienia",
	"TagCaptured": "Znacznik uchwycony",
	"TagDuplicateIpodFull": "Znacznik jest już zapisany",
	"TagNotYetProcessed": "Znacznik nieprzetw.",
	"TagSaved": "Znacznik zapisany w iPod",
	"TagSavedsbn": "Znacznik zapisany",
	"TagSavedtoSystem": "Znacznik zapisany w syst.",
	"TagTransferIpodFull": "Wszystkie znaczn. przesł.",
	"TagTransferNoMemory": "Przesł. znaczn. niemożliwe",
	"TagTransferSuccess": "Znaczn. przesłane do iPod",
	"TrafficAlertOff": "Wyłącz komunikat drogowy",
	"TrafficAlertOn": "Włącz komunikat drogowy",
	"UpdateStationList": "Odśwież listę stacji",
	"UpdatingStationList": "Odświeżanie listy stacji",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_NowPlaying_EU_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_EU_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_EU_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_EU_Help_Left4": "Scan",
	"VrHelp_NowPlaying_EU_Help_Left5": "Tune",
	"VrHelp_NowPlaying_EU_Help_Right1": "Traffic Announcement  (TA)",
	"VrHelp_NowPlaying_EU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlaying_EU_Help_Right3": "Seek Next",
	"VrHelp_NowPlaying_EU_Help_Right4": "Sound Settings",
	"VrHelp_NowPlaying_Japan_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Japan_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_Japan_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_Japan_Help_Left4": "Scan",
	"VrHelp_NowPlaying_Japan_Help_Left5": "Tune",
	"VrHelp_NowPlaying_Japan_Help_Right1": "Seek Previous",
	"VrHelp_NowPlaying_Japan_Help_Right2": "Seek Next",
	"VrHelp_NowPlaying_Japan_Help_Right3": "Sound Settings",
	"VrHelp_NowPlaying_US_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_US_Help_Left2": "Auto Memory",
	"VrHelp_NowPlaying_US_Help_Left3": "Favorites",
	"VrHelp_NowPlaying_US_Help_Left4": "HD On / Off",
	"VrHelp_NowPlaying_US_Help_Left5": "Scan",
	"VrHelp_NowPlaying_US_Help_Right1": "Tune",
	"VrHelp_NowPlaying_US_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlaying_US_Help_Right3": "Seek Previous",
	"VrHelp_NowPlaying_US_Help_Right4": "Seek Next",
	"VrHelp_NowPlaying_US_Help_Right5": "Sound Settings",
	"VrHelp_Tune_Help1_Left1": "(frequency)",
	"VrHelp_Tune_Help1_Left2": "Tune Down",
	"VrHelp_Tune_Help1_Left3": "Tune Up",
	"VrHelp_Tune_Help2_Left1": "(frequency)",
	"VrHelp_Tune_Help2_Left2": "Tune Down",
	"VrHelp_Tune_Help2_Left3": "Tune Up",
	"favorites_Tooltip": "Ulubione",
	"next_Tooltip": "Szukaj następnej",
	"prev_Tooltip": "Szukaj poprzedniej",
};

framework.registerAppDictLoaded("amradio", "pl_PL");