var Localization_phoneAppDict_es_MX = {
	//"stringId" : "localString"
	"ActiveCall": "Llamada Activa",
	"ActiveCall1DTMF": "Teléfono",
	"ActiveCall2DTMF": "Teléfono",
	"ActiveCallDTMF": "Teléfono",
	"ActiveCallMergedDTMF": "Teléfono",
	"AddCall": "Añadir Llamada",
	"AllCalls": "Todas las llamadas",
	"Answer": "Responder",
	"Call": "Llamada",
	"Call1Active": "Llamada activa 1",
	"Call2Active": "Llamada activa 2",
	"CallConfirmationTextThird": "Diga \"Sí\" para continuar",
	"CallEnd": "Llamada finalizada {callEndTimer}",
	"CallHistory": "Historial de llamadas",
	"CallOnHandset": "Llamada en Teléfono",
	"CannotAddCall": "No se puede añadir la llamada",
	"CannotPlaceCall": "No se puede hacer la llamada",
	"ConferenceCall": "Llamada de conferencia",
	"Connecting": "Conectando",
	"Dial": "Marcar",
	"DialPad": "Teléfono",
	"EndAnswer": "Fin + Resp",
	"HoldAnswer": "Esp + Resp",
	"Home": "Casa:",
	"HomeType": "Casa",
	"Ignore": "Ignorar",
	"IncomingCall": "Llamada entrante",
	"MissedCalls": "Llamadas perdidas",
	"Mobile": "Móvil:",
	"MobileType": "Móvil",
	"Name": "Nombre ",
	"NoCallHistoryData": "La información del Historial de Llamadas no está disponible",
	"Number": "Número ",
	"NumberorName": "¿Desea llamar por Número o por Nombre?",
	"Other": "Otro:",
	"OtherType": "Otro",
	"Phone": "Teléfono",
	"PhoneConnectionLost": "Conexión de Teléfono Perdida",
	"Private": "Privado ",
	"RedialNoDataFirst": "La información del Historial de Llamadas no está disponible",
	"RedialNoDataSecond": "¿Desea volver a marcar?",
	"SelectContact": "Seleccionar Contacto",
	"SelectNumber": "Seleccione Número",
	"Unknown": "Desconocido ",
	"VrHelp_DialPad_Help_Digits_Left1": "(dígitos 0-9, *, #,+)",
	"VrHelp_DialPad_Help_Digits_Left2": "Llamar",
	"VrHelp_DialPad_Help_Digits_Left3": "Eliminar",
	"VrHelp_DialPad_Help_Digits_Left4": "Borrar todo",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(dígitos 0-9, *, #,+)",
	"Work": "Trabajo:",
	"WorkType": "Trabajo",
};

framework.registerAppDictLoaded("phone", "es_MX");