var Localization_phoneAppDict_da_DK = {
	//"stringId" : "localString"
	"ActiveCall": "Aktivt opkald",
	"ActiveCall1DTMF": "Telefon",
	"ActiveCall2DTMF": "Telefon",
	"ActiveCallDTMF": "Telefon",
	"ActiveCallMergedDTMF": "Telefon",
	"AddCall": "Tilføj opkald",
	"AllCalls": "Alle opkald",
	"Answer": "Besvar",
	"Call": "Ring op",
	"Call1Active": "Opkald 1 aktivt",
	"Call2Active": "Opkald 2 aktivt",
	"CallConfirmationTextThird": "Sig \"Ja\" for at fortsætte",
	"CallEnd": "Opkald afsluttet {callEndTimer}",
	"CallHistory": "Opkaldsdata",
	"CallOnHandset": "Ring med håndsæt",
	"CannotAddCall": "Kan ikke tilføje opkald",
	"CannotPlaceCall": "Opkald kan ikke foretages",
	"ConferenceCall": "Mødeopkald",
	"Connecting": "Opretter forbindelse",
	"Dial": "Tast",
	"DialPad": "Telefon",
	"EndAnswer": "Slut + besvar",
	"HoldAnswer": "Vent+Besv",
	"Home": "Hjem:",
	"HomeType": "Hjem",
	"Ignore": "Ignorér",
	"IncomingCall": "Indgående opkald",
	"MissedCalls": "Ubesvarede opkald",
	"Mobile": "Mobil:",
	"MobileType": "Mobil",
	"Name": "Navn",
	"NoCallHistoryData": "Opkaldsliste ikke tilgængelig",
	"Number": "Nummer",
	"NumberorName": "Ønsker du at ringe op efter nummer eller navn?",
	"Other": "Andet:",
	"OtherType": "Andet",
	"Phone": "Telefon",
	"PhoneConnectionLost": "Telefonforbindelse mistet",
	"Private": "Privat",
	"RedialNoDataFirst": "Information om opkaldsdata ikke tilgængelig.",
	"RedialNoDataSecond": "Ønsker du at ringe op igen?",
	"SelectContact": "Vælg kontakt",
	"SelectNumber": "Vælg nummer",
	"Unknown": "Ukendt",
	"VrHelp_DialPad_Help_Digits_Left1": "(Cifrene 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Ring op",
	"VrHelp_DialPad_Help_Digits_Left3": "Slet",
	"VrHelp_DialPad_Help_Digits_Left4": "Ryd",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(Cifrene 0-9, *, #, +)",
	"Work": "Arbejde:",
	"WorkType": "Arbejde",
};

framework.registerAppDictLoaded("phone", "da_DK");