var Localization_phoneAppDict_et_EE = {
	//"stringId" : "localString"
	"ActiveCall": "Aktiivne kõne",
	"ActiveCall1DTMF": "Telefon",
	"ActiveCall2DTMF": "Telefon",
	"ActiveCallDTMF": "Telefon",
	"ActiveCallMergedDTMF": "Telefon",
	"AddCall": "Lisa kõne",
	"AllCalls": "Kõik kõned",
	"Answer": "Vastus",
	"Call": "Kõne",
	"Call1Active": "Kõne 1 aktiivne",
	"Call2Active": "Kõne 2 aktiivne",
	"CallConfirmationTextThird": "Öelge jätkamiseks „Jah”",
	"CallEnd": "Kõne lõppes {callEndTimer}",
	"CallHistory": "Kõnelogi",
	"CallOnHandset": "Helista telefoniga",
	"CannotAddCall": "Kõnet ei saa lisada",
	"CannotPlaceCall": "Kõne ebaõnnestus",
	"ConferenceCall": "Konverentskõne",
	"Connecting": "Ühenduse loomine",
	"Dial": "Vali",
	"DialPad": "Telefon",
	"EndAnswer": "Lõpeta+vasta",
	"HoldAnswer": "Ootele+vasta",
	"Home": "Kodu:",
	"HomeType": "Kodu",
	"Ignore": "Ignoreeri",
	"IncomingCall": "Sisenev kõne",
	"MissedCalls": "Vastamata kõned",
	"Mobile": "Mobiil:",
	"MobileType": "Mobiil",
	"Name": "Nimi",
	"NoCallHistoryData": "Kõnelogi pole saadaval.",
	"Number": "Number",
	"NumberorName": "Kas soovite helistada numbri või nime järgi?",
	"Other": "Muu:",
	"OtherType": "Muu",
	"Phone": "Telefon",
	"PhoneConnectionLost": "Ühendus telefoniga kadus",
	"Private": "Privaatne",
	"RedialNoDataFirst": "Kõnelogi andmed pole kättesaadavad.",
	"RedialNoDataSecond": "Kas soovite uuesti valida?",
	"SelectContact": "Valige kontakt",
	"SelectNumber": "Valige number",
	"Unknown": "Tundmatu",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "Töökoht:",
	"WorkType": "Töökoht",
};

framework.registerAppDictLoaded("phone", "et_EE");