var Localization_phoneAppDict_pt_BR = {
	//"stringId" : "localString"
	"ActiveCall": "Chamada ativa",
	"ActiveCall1DTMF": "Telefone",
	"ActiveCall2DTMF": "Telefone",
	"ActiveCallDTMF": "Telefone",
	"ActiveCallMergedDTMF": "Telefone",
	"AddCall": "Adicionar chamada",
	"AllCalls": "Todas as chamadas",
	"Answer": "Resposta",
	"Call": "Chamada",
	"Call1Active": "Chamada 1 ativa",
	"Call2Active": "Chamada 2 ativa",
	"CallConfirmationTextThird": "Diga \"Sim\" para continuar",
	"CallEnd": "Chamada finalizada {callEndTimer}",
	"CallHistory": "Histórico de chamadas",
	"CallOnHandset": "Chamada no telefone",
	"CannotAddCall": "Não é possível adicionar chamada",
	"CannotPlaceCall": "Chamada incompleta",
	"ConferenceCall": "Chamada em conferência",
	"Connecting": "Conectando",
	"Dial": "Mostrador",
	"DialPad": "Telefone",
	"EndAnswer": "Desl.+Aten",
	"HoldAnswer": "Esp.+Aten ",
	"Home": "Casa:",
	"HomeType": "Casa",
	"Ignore": "Ignorar",
	"IncomingCall": "Chamada recebida",
	"MissedCalls": "Chamadas perdidas",
	"Mobile": "Celular:",
	"MobileType": "Celular",
	"Name": "Nome",
	"NoCallHistoryData": "Histórico de chamadas não disponível",
	"Number": "Número",
	"NumberorName": "Você gostaria de ligar pelo número ou pelo nome?",
	"Other": "Outro:",
	"OtherType": "Outros",
	"Phone": "Telefone",
	"PhoneConnectionLost": "Conexão Bluetooth perdida",
	"Private": "Número bloqueado",
	"RedialNoDataFirst": "Informações do histórico de chamada não disponíveis.",
	"RedialNoDataSecond": "Deseja ligar novamente?",
	"SelectContact": "Selecionar contato",
	"SelectNumber": "Selecione o No.",
	"Unknown": "Número desconhecido",
	"VrHelp_DialPad_Help_Digits_Left1": "(dígitos 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Telefonar",
	"VrHelp_DialPad_Help_Digits_Left3": "Eliminar",
	"VrHelp_DialPad_Help_Digits_Left4": "Limpar",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(dígitos 0-9, *, #, +)",
	"Work": "Trabalho:",
	"WorkType": "Trabalho",
};

framework.registerAppDictLoaded("phone", "pt_BR");