var Localization_phoneAppDict_he_IL = {
	//"stringId" : "localString"
	"ActiveCall": "שיחה פעילה",
	"ActiveCall1DTMF": "טלפון",
	"ActiveCall2DTMF": "טלפון",
	"ActiveCallDTMF": "טלפון",
	"ActiveCallMergedDTMF": "טלפון",
	"AddCall": "הוסף שיחה",
	"AllCalls": "כל השיחות",
	"Answer": "ענה",
	"Call": "שיחה",
	"Call1Active": "שיחה 1 פעילה",
	"Call2Active": "שיחה 2 פעילה",
	"CallConfirmationTextThird": "אמור \"כן\" כדי להמשיך",
	"CallEnd": "השיחה הסתיימה {callEndTimer}",
	"CallHistory": "היסטוריית שיחות",
	"CallOnHandset": "שיחה בטלפון",
	"CannotAddCall": "לא ניתן להוסיף שיחה",
	"CannotPlaceCall": "לא ניתן לחייג שיחה",
	"ConferenceCall": "שיחת ועידה",
	"Connecting": "מקשר",
	"Dial": "חייג",
	"DialPad": "טלפון",
	"EndAnswer": "סיום + ענה",
	"HoldAnswer": "החזק + ענה",
	"Home": "בית",
	"HomeType": "בית",
	"Ignore": "התעלם",
	"IncomingCall": "שיחה נכנסת",
	"MissedCalls": "שיחות שלא נענו",
	"Mobile": "נייד",
	"MobileType": "נייד",
	"Name": "שם",
	"NoCallHistoryData": "מידע היסטוריית שיחות אינו זמין.",
	"Number": "מספר",
	"NumberorName": "האם ברצונך להתקשר לפי מספר או שם?",
	"Other": "אחר",
	"OtherType": "אחר",
	"Phone": "טלפון",
	"PhoneConnectionLost": "חיבור טלפון אבד",
	"Private": "פרטי",
	"RedialNoDataFirst": "מידע היסטוריית שיחות אינו זמין.",
	"RedialNoDataSecond": "האם ברצונך לחייג שוב?",
	"SelectContact": "בחר איש קשר",
	"SelectNumber": "בחר מספר",
	"Unknown": "לא מוכר",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "עבודה",
	"WorkType": "עבודה",
};

framework.registerAppDictLoaded("phone", "he_IL");