var Localization_phoneAppDict_ja_JP = {
	//"stringId" : "localString"
	"ActiveCall": "通話中",
	"ActiveCall1DTMF": "電話",
	"ActiveCall2DTMF": "電話",
	"ActiveCallDTMF": "電話",
	"ActiveCallMergedDTMF": "電話",
	"AddCall": "通話相手を追加",
	"AllCalls": "すべて",
	"Answer": "応答",
	"Call": "発信しますか？",
	"Call1Active": "通話 1",
	"Call2Active": "通話 2",
	"CallConfirmationTextThird": "発信しますか？",
	"CallEnd": "通話終了\n{callEndTimer}",
	"CallHistory": "履歴",
	"CallOnHandset": "携帯電話で通話中",
	"CannotAddCall": "通話相手を\n追加できませんでした。",
	"CannotPlaceCall": "電話を発信\nできませんでした。",
	"ConferenceCall": "三者通話",
	"Connecting": "発信中",
	"Dial": "ダイヤル",
	"DialPad": "ダイヤル",
	"EndAnswer": "終了＋応答",
	"HoldAnswer": "保留＋応答",
	"Home": "自宅 :",
	"HomeType": "自宅 ",
	"Ignore": "拒否",
	"IncomingCall": "着信中",
	"MissedCalls": "不在着信",
	"Mobile": "携帯 : ",
	"MobileType": "携帯 ",
	"Name": "名前",
	"NoCallHistoryData": "着信履歴は利用できません。",
	"Number": "番号",
	"NumberorName": "発信方法を選択してください。",
	"Other": "その他 :",
	"OtherType": "その他 ",
	"Phone": "電話",
	"PhoneConnectionLost": "Bluetooth Phone Connection Lost",
	"Private": "非通知",
	"RedialNoDataFirst": "発信履歴は利用できません。",
	"RedialNoDataSecond": "リダイヤルしますか？",
	"SelectContact": "連絡先を選択してください",
	"SelectNumber": "番号を選択してください",
	"Unknown": "Unknown",
	"VrHelp_DialPad_Help_Digits_Left1": "(0 から 9 までの数字、*、#、+)",
	"VrHelp_DialPad_Help_Digits_Left2": "電話",
	"VrHelp_DialPad_Help_Digits_Left3": "削除",
	"VrHelp_DialPad_Help_Digits_Left4": "クリア",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(0 から 9 までの数字、*、#、+)",
	"Work": "勤務先 :",
	"WorkType": "勤務先 ",
};

framework.registerAppDictLoaded("phone", "ja_JP");