var Localization_phoneAppDict_ms_MY = {
	//"stringId" : "localString"
	"ActiveCall": "Panggilan Aktif",
	"ActiveCall1DTMF": "Telefon",
	"ActiveCall2DTMF": "Telefon",
	"ActiveCallDTMF": "Telefon",
	"ActiveCallMergedDTMF": "Telefon",
	"AddCall": "Tambah Panggilan",
	"AllCalls": "Semua Panggilan",
	"Answer": "Jawapan",
	"Call": "Panggilan",
	"Call1Active": "Panggilan 1 Aktif",
	"Call2Active": "Panggilan 2 Aktif",
	"CallConfirmationTextThird": "Katakan \"Ya\" untuk meneruskan",
	"CallEnd": "Panggilan Tamat {callEndTimer}",
	"CallHistory": "Rekod Panggilan",
	"CallOnHandset": "Hubungi Telefon Bimbit",
	"CannotAddCall": "Tidak boleh menambah panggilan",
	"CannotPlaceCall": "Panggilan tidak dapat dibuat",
	"ConferenceCall": "Panggilan Persidangan",
	"Connecting": "Menyambung",
	"Dial": "Dail",
	"DialPad": "Telefon",
	"EndAnswer": "Tmt + Jawab",
	"HoldAnswer": "Tggu+Jawab",
	"Home": "Rumah:",
	"HomeType": "Rumah",
	"Ignore": "Abaikan",
	"IncomingCall": "Panggilan Masuk",
	"MissedCalls": "Panggilan Tidak Dijawab",
	"Mobile": "Mudah alih:",
	"MobileType": "Mudah Alih",
	"Name": "Nama",
	"NoCallHistoryData": "Maklumat Rekod Panggilan tidak tersedia.",
	"Number": "Nombor",
	"NumberorName": "Adakah anda ingin membuat panggilan menggunakan Nombor atau Nama?",
	"Other": "Lain-lain:",
	"OtherType": "Lain-lain",
	"Phone": "Dail",
	"PhoneConnectionLost": "Sambungan Telefon Terputus",
	"Private": "Peribadi",
	"RedialNoDataFirst": "Maklumat Rekod Panggilan tidak tersedia.",
	"RedialNoDataSecond": "Anda ingin mendail semula?",
	"SelectContact": "Pilih Kenalan",
	"SelectNumber": "Pilih Nombor",
	"Unknown": "Tidak diketahui",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "Kerja:",
	"WorkType": "Kerja",
};

framework.registerAppDictLoaded("phone", "ms_MY");