var Localization_phoneAppDict_sk_SK = {
	//"stringId" : "localString"
	"ActiveCall": "Aktívny hovor",
	"ActiveCall1DTMF": "Telefón",
	"ActiveCall2DTMF": "Telefón",
	"ActiveCallDTMF": "Telefón",
	"ActiveCallMergedDTMF": "Telefón",
	"AddCall": "Pridať volanie",
	"AllCalls": "Všetky hovory",
	"Answer": "Odpovedať",
	"Call": "Hovor",
	"Call1Active": "Hovor 1 aktívny",
	"Call2Active": "Hovor 2 aktívny",
	"CallConfirmationTextThird": "Povedze \"Áno\" a pokračujte",
	"CallEnd": "Hovor skončil {callEndTimer}",
	"CallHistory": "História hovorov",
	"CallOnHandset": "Hovor cez slúchadlá",
	"CannotAddCall": "Volanie nemožno pridať",
	"CannotPlaceCall": "Volanie nebolo možné vykonať",
	"ConferenceCall": "Konferenčný hovor",
	"Connecting": "Pripája sa",
	"Dial": "Vytáčanie",
	"DialPad": "Telefón",
	"EndAnswer": "Koniec + odp.",
	"HoldAnswer": "Držať + odp.",
	"Home": "Domov:",
	"HomeType": "Domov",
	"Ignore": "Ignorovať",
	"IncomingCall": "Prichádzajúci hovor",
	"MissedCalls": "Zmeškané hovory",
	"Mobile": "Mobil:",
	"MobileType": "Mobil",
	"Name": "Názov",
	"NoCallHistoryData": "Informácie o histórii hovorov nie sú k dispozícii.",
	"Number": "Číslo",
	"NumberorName": "Chcete volať podľa čísla alebo podľa mena?",
	"Other": "Iné:",
	"OtherType": "Iné",
	"Phone": "Telefón",
	"PhoneConnectionLost": "Spojenie telefónu bolo prerušené",
	"Private": "Súkromné",
	"RedialNoDataFirst": "Informácie o histórii volaní nie sú k dispozícii.",
	"RedialNoDataSecond": "Chcete vytočiť znovu?",
	"SelectContact": "Vyberte kontakt",
	"SelectNumber": "Vyberte číslo",
	"Unknown": "Neznáme",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "Práca:",
	"WorkType": "Práca",
};

framework.registerAppDictLoaded("phone", "sk_SK");