var Localization_phoneAppDict_hu_HU = {
	//"stringId" : "localString"
	"ActiveCall": "Folyamatban lévő hívás",
	"ActiveCall1DTMF": "Telefon",
	"ActiveCall2DTMF": "Telefon",
	"ActiveCallDTMF": "Telefon",
	"ActiveCallMergedDTMF": "Telefon",
	"AddCall": "Hívás hozzáadása",
	"AllCalls": "Összes hívás",
	"Answer": "Fogad",
	"Call": "Hívás",
	"Call1Active": "1. hívás aktív",
	"Call2Active": "2. hívás aktív",
	"CallConfirmationTextThird": "\"Igen\" beírása a folytatáshoz",
	"CallEnd": "Hívás vége {callEndTimer}",
	"CallHistory": "Hívási előzmények",
	"CallOnHandset": "Hívás a kézibeszélőn",
	"CannotAddCall": "Hívás nem adható hozzá",
	"CannotPlaceCall": "Hívás nem kezdeményezhető",
	"ConferenceCall": "Konferenciahívás",
	"Connecting": "Kapcsolódás",
	"Dial": "Hívás",
	"DialPad": "Telefon",
	"EndAnswer": "Vége + Fog.",
	"HoldAnswer": "Tartás + Fog.",
	"Home": "Otthoni:",
	"HomeType": "Otthoni szám",
	"Ignore": "Mellőz",
	"IncomingCall": "Bejövő hívás",
	"MissedCalls": "Nem fogadott hívások",
	"Mobile": "Mobil:",
	"MobileType": "Mobil szám",
	"Name": "Név",
	"NoCallHistoryData": "Híváselőzmények nem állnak rendelkezésre.",
	"Number": "Szám",
	"NumberorName": "Szám vagy név szerinti hívás?",
	"Other": "Egyéb:",
	"OtherType": "Egyéb",
	"Phone": "Telefon",
	"PhoneConnectionLost": "Telefonkapcsolat megszakadt",
	"Private": "Rejtett szám",
	"RedialNoDataFirst": "Híváselőzmények nem állnak rendelkezésre.",
	"RedialNoDataSecond": "Kíván újratárcsázni?",
	"SelectContact": "Névjegy kiválasztása",
	"SelectNumber": "Szám kijelölése",
	"Unknown": "Ismeretlen",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "Munkahelyi:",
	"WorkType": "Munkahelyi",
};

framework.registerAppDictLoaded("phone", "hu_HU");