var Localization_phoneAppDict_cs_CS = {
	//"stringId" : "localString"
	"ActiveCall": "Aktivní hovor",
	"ActiveCall1DTMF": "Telefon",
	"ActiveCall2DTMF": "Telefon",
	"ActiveCallDTMF": "Telefon",
	"ActiveCallMergedDTMF": "Telefon",
	"AddCall": "Přidat hovor",
	"AllCalls": "Všechny hovory",
	"Answer": "Odpovědět",
	"Call": "Hovor",
	"Call1Active": "Hovor 1 – aktivní",
	"Call2Active": "Hovor 2 – aktivní",
	"CallConfirmationTextThird": "Vyberte \"Ano\" a pokračujte",
	"CallEnd": "Hovor ukončen {callEndTimer}",
	"CallHistory": "Historie volání",
	"CallOnHandset": "Volat telefonem",
	"CannotAddCall": "Nelze přidat hovor",
	"CannotPlaceCall": "Hovor nelze přepojit",
	"ConferenceCall": "Konferenční hovor",
	"Connecting": "Připojování",
	"Dial": "Vytočit",
	"DialPad": "Telefon",
	"EndAnswer": "Konec + odp.",
	"HoldAnswer": "Drž+odp.",
	"Home": "Domů:",
	"HomeType": "Domů",
	"Ignore": "Ignorovat",
	"IncomingCall": "Příchozí hovor",
	"MissedCalls": "Zmeškané hovory",
	"Mobile": "Mobil:",
	"MobileType": "Mobil",
	"Name": "Název",
	"NoCallHistoryData": "Historie hovorů není dostupná",
	"Number": "Číslo",
	"NumberorName": "Chcete volat podle čísla nebo podle jména?",
	"Other": "Jiný:",
	"OtherType": "Jiný",
	"Phone": "Telefon",
	"PhoneConnectionLost": "Telefonické spojení bylo přerušeno.",
	"Private": "Soukromý:",
	"RedialNoDataFirst": "Údaje historie hovorů nejsou k dispozici.",
	"RedialNoDataSecond": "Zkusit znovu?",
	"SelectContact": "Vyberte kontakt",
	"SelectNumber": "Vyberte číslo",
	"Unknown": "Neznámý",
	"VrHelp_DialPad_Help_Digits_Left1": "(digits 0-9, *, #, +)",
	"VrHelp_DialPad_Help_Digits_Left2": "Call",
	"VrHelp_DialPad_Help_Digits_Left3": "Delete",
	"VrHelp_DialPad_Help_Digits_Left4": "Clear",
	"VrHelp_DialPad_Help_NoDigits_Left1": "(digits 0-9, *, #, +)",
	"Work": "Práce:",
	"WorkType": "Práce",
};

framework.registerAppDictLoaded("phone", "cs_CS");