var Localization_schedmaintAppDict_th_TH = {
    //"stringId" : "localString"
    "Maintenance" : "การบำรุงรักษา",
    "tireRotation" : "การสลับยาง",
    "oilChange" : "การเปลี่ยนถ่ายน้ำมัน",
    "Setting" : "การตั้งค่า",
    "Time" : "เวลา",
    "Distance" : "ระยะทาง",
    "Reset" : "รีเซ็ต",
    "scheduledDueIn" : "ครบกำหนดใน:",
    "scheduledMaintenanceDue" : "ครบกำหนดตามกำหนดเวลา!",
    "tireRotationDue" : "ถึงกำหนดสลับยาง !",
    "oilChangeDue" : "ครบกำหนดการเปลี่ยนถ่ายน้ำมัน",
    "resetFail" : "การรีเซ็ตล้มเหลว",
    "retryOff" : "ไม่สามารถปิดการตั้งค่าได้",
    "oilSettingError" : "ข้อผิดพลาดการตั้งค่าน้ำมัน",
    "oilLife" : "อายุการใช้งานของน้ำมัน",
    "Off" : "ปิด",
    "Back" : "ย้อนกลับ",
    "turnOff" : "ปิด",
    "Cancel" : "ยกเลิก",
    "Retry" : "ลองใหม่",
    "OK" : "ตกลง",
    "MILE" : "{value} ไมล์",
    "KM" : "{value} กม.",
    "day" : "{value} วัน",
    "days" : "{value} วัน",
    "month" : "{value} เดือน",
    "months" : "{value} เดือน",
    "settingInterval" : "ระยะเวลาการตั้งค่า",
    "Flexible" : "ยืดหยุ่น",
    "Fixed" : "คงที่",
    "scheduled" : "ตามกำหนด",
    "tryAgain" : "คุณต้องการลองอีกครั้งหรือไม่",
    "confirmOffSchedule" : "แน่ใจหรือไม่ว่าต้องการปิดการบำรุงรักษาตามกำหนดเวลา",
    "confirmOffTire" : "แน่ใจหรือไม่ว่าต้องการปิดการสลับตำแหน่งยาง",
    "confirmOffOil" : "แน่ใจหรือไม่ว่าต้องการปิดการเปลี่ยนน้ำมัน",
    "confirmResetSchedule" : "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการบำรุงรักษาตามกำหนดเวลา",
    "confirmResetTire" : "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการสลับตำแหน่งยาง",
    "confirmResetOil" : "แน่ใจหรือไม่ว่าต้องการรีเซ็ตการเปลี่ยนน้ำมัน",
    "dueInMile" : "{dueInDistance} ไมล์",
    "dueInKm" : "{dueInDistance} กม.",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} กม.",
    "dueUnitOilMile" : "{dueInOil} ไมล์",
    "dueInTimeMonths" : "{dueInTime} เดือน",
    "dueInTimeDays" : "{dueInTime} วัน",
    "dueInTimeDay" : "{dueInTime} วัน",
    "flexibleOilChange" : "การเลือกการตั้งค่าแบบยืดหยุ่นกำหนดให้ต้องใช้น้ำมันเครื่องที่มาสด้าแนะนำ",
    "fixedConfirm" : "แน่ใจหรือไม่ว่าต้องการกำหนดการตั้งค่าการเปลี่ยนน้ำมันเป็นแบบยืดหยุ่น",
    "retryFixed" : "ไม่สามารถเปลี่ยนการตั้งค่าเป็นแบบคงที่ได้",
    "retryFlexible" : "ไม่สามารถเปลี่ยนการตั้งค่าเป็นแบบยืดหยุ่นได้",
};

framework.registerAppDictLoaded("schedmaint", "th_TH");