var Localization_schedmaintAppDict_fr_FR = {
    //"stringId" : "localString"
    "Maintenance" : "Révision",
    "tireRotation" : "Permutation des pneus",
    "oilChange" : "Vidange ",
    "Setting" : "Paramètre",
    "Time" : "Heure",
    "Distance" : "Distance",
    "Reset" : "Réinitialiser",
    "scheduledDueIn" : "Due à:",
    "scheduledMaintenanceDue" : "Révision requise !",
    "tireRotationDue" : "Permutation des pneus nécessaire !",
    "oilChangeDue" : "Vidange nécessaire !",
    "resetFail" : "Échec de réinitialisation",
    "retryOff" : "Ce paramètre ne peut être désactivé",
    "oilSettingError" : "Erreur réglage huile",
    "oilLife" : "Durée d’huile",
    "Off" : "Désact.",
    "Back" : "Retour",
    "turnOff" : "Éteindre",
    "Cancel" : "Annuler",
    "Retry" : "Réessayer",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} jour",
    "days" : "{value} jours",
    "month" : "{value} mois",
    "months" : "{value} mois",
    "settingInterval" : "Intervalle d’un paramètre",
    "Flexible" : "Flexible",
    "Fixed" : "Fixe",
    "scheduled" : "Programmé",
    "tryAgain" : "Voulez-vous réessayer ?",
    "confirmOffSchedule" : "Êtes-vous sûr de vouloir désactiver l’Entretien Programmé ?",
    "confirmOffTire" : "Êtes-vous sûr de vouloir désactiver la Permutation des pneus ?",
    "confirmOffOil" : "Êtes-vous sûr de vouloir désactiver la Vidange ?",
    "confirmResetSchedule" : "Êtes-vous sûr de vouloir réinitialiser l’Entretien Programmé ?",
    "confirmResetTire" : "Êtes-vous sûr de vouloir réinitialiser la Permutation des pneus ?",
    "confirmResetOil" : "Êtes-vous sûr de vouloir réinitialiser la vidange ?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} mois",
    "dueInTimeDays" : "{dueInTime} jours",
    "dueInTimeDay" : "{dueInTime} jour",
    "flexibleOilChange" : "La sélection des paramètres flexibles nécessite l'utilisation d’une huile moteur recommandée par Mazda.",
    "fixedConfirm" : "Êtes-vous sûr de vouloir modifier les paramètres de vidange à Fixe ?",
    "retryFixed" : "Impossible de modifier les paramètres à Fixe",
    "retryFlexible" : "Impossible de modifier les paramètres à Flexible",
};

framework.registerAppDictLoaded("schedmaint", "fr_FR");