var Localization_schedmaintAppDict_fi_FI = {
    //"stringId" : "localString"
    "Maintenance" : "Huolto",
    "tireRotation" : "Renkaiden paikanvaihto",
    "oilChange" : "Öljynvaihto",
    "Setting" : "Asetukset",
    "Time" : "Aika",
    "Distance" : "Etäisyys",
    "Reset" : "Palauta",
    "scheduledDueIn" : "Viim:",
    "scheduledMaintenanceDue" : "Suoritettava heti!",
    "tireRotationDue" : "Suorita renkaiden paikanvaihto!",
    "oilChangeDue" : "Suorita öljynvaihto!",
    "resetFail" : "Nollaus epäonnistui",
    "retryOff" : "Asetusta ei voitu kytkeä pois päältä",
    "oilSettingError" : "Öljyasetusvirhe",
    "oilLife" : "Öljyn ikä",
    "Off" : "Pois",
    "Back" : "Takaisin",
    "turnOff" : "Kytke pois päältä",
    "Cancel" : "Peruuta",
    "Retry" : "Yritä uudelleen",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} päivä",
    "days" : "{value} päivää",
    "month" : "{value} kuukausi",
    "months" : "{value} kuukautta",
    "settingInterval" : "Vaihtovälin määritys",
    "Flexible" : "Joust.",
    "Fixed" : "Kiinteä",
    "scheduled" : "Määräaikaishuolto",
    "tryAgain" : "Haluatko yrittää uudelleen?",
    "confirmOffSchedule" : "Haluatko varmasti poistaa  määräaikaishuollon käytöstä?",
    "confirmOffTire" : "Haluatko varmasti poistaa  renkaiden paikanvaihdon käytöstä?",
    "confirmOffOil" : "Haluatko varmasti poistaa  öljynvaihdon käytöstä?",
    "confirmResetSchedule" : "Haluatko varmasti nollata määräaikaishuollon tiedot?",
    "confirmResetTire" : "Haluatko varmasti nollata renkaiden paikanvaihdon tiedot?",
    "confirmResetOil" : "Haluatko varmasti nollata öljynvaihdon tiedot?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} kk",
    "dueInTimeDays" : "{dueInTime} pv",
    "dueInTimeDay" : "{dueInTime} pv",
    "flexibleOilChange" : "Joustavien asetusten valitseminen edellyttää Mazda suositteleman moottoriöljyn käyttöä.",
    "fixedConfirm" : "Haluatko varmasti vaihtaa Öljynvaihto-asetukseksi Kiinteä?",
    "retryFixed" : "Asetuksen arvoksi ei voitu vaihtaa Kiinteä",
    "retryFlexible" : "Asetuksen arvoksi ei voitu vaihtaa Joustava",
};

framework.registerAppDictLoaded("schedmaint", "fi_FI");