var Localization_schedmaintAppDict_zh_CN = {
    //"stringId" : "localString"
    "Maintenance" : "维护",
    "tireRotation" : "轮胎旋转",
    "oilChange" : "换机油",
    "Setting" : "设置",
    "Time" : "时间",
    "Distance" : "距离",
    "Reset" : "复位",
    "scheduledDueIn" : "到期：",
    "scheduledMaintenanceDue" : "该进行预约的了！",
    "tireRotationDue" : "该进行轮胎旋转了！",
    "oilChangeDue" : "该换机油了！",
    "resetFail" : "复位失败",
    "retryOff" : "无法关闭设置",
    "oilSettingError" : "油设置错误",
    "oilLife" : "油使用寿命",
    "Off" : "关闭",
    "Back" : "返回",
    "turnOff" : "关闭",
    "Cancel" : "取消",
    "Retry" : "重试",
    "OK" : "确定",
    "MILE" : "{value} 英里",
    "KM" : "{value} 公里",
    "day" : "{value} 天",
    "days" : "{value} 天",
    "month" : "{value} 个月",
    "months" : "{value} 个月",
    "settingInterval" : "设置间隔",
    "Flexible" : "灵活",
    "Fixed" : "固定",
    "scheduled" : "已预约",
    "tryAgain" : "您是否希望重试？",
    "confirmOffSchedule" : "您确定要关闭预约维护吗？",
    "confirmOffTire" : "您确定要关闭轮胎旋转吗？",
    "confirmOffOil" : "您确定要关闭换油吗？",
    "confirmResetSchedule" : "您确定要复位预约维护吗？",
    "confirmResetTire" : "您确定要复位轮胎旋转吗？",
    "confirmResetOil" : "您确定要复位换油吗？",
    "dueInMile" : "{dueInDistance} 英里",
    "dueInKm" : "{dueInDistance} 公里",
    "dueUnitFlexible" : "{dueInOil} % ",
    "dueUnitOilKm" : "{dueInOil} 公里",
    "dueUnitOilMile" : "{dueInOil} 英里",
    "dueInTimeMonths" : "{dueInTime} 个月",
    "dueInTimeDays" : "{dueInTime} 天",
    "dueInTimeDay" : "{dueInTime} 天",
    "flexibleOilChange" : "选择灵活设置需要使用 Mazda 推荐的车用机油。",
    "fixedConfirm" : "您确定要将换油更改为固定吗？",
    "retryFixed" : "无法将设置变为固定",
    "retryFlexible" : "无法将设置变为灵活",
};

framework.registerAppDictLoaded("schedmaint", "zh_CN");