var Localization_schedmaintAppDict_pt_PT = {
    //"stringId" : "localString"
    "Maintenance" : "Manutenção",
    "tireRotation" : "Rotação dos Pneus",
    "oilChange" : "Mudança de Óleo",
    "Setting" : "Definição",
    "Time" : "Hora",
    "Distance" : "Distância",
    "Reset" : "Repor",
    "scheduledDueIn" : "Vence em:",
    "scheduledMaintenanceDue" : "Efectuar Manutenção!",
    "tireRotationDue" : "Efectuar a Rotação dos Pneus!",
    "oilChangeDue" : "Efectuar Mudança de Óleo!",
    "resetFail" : "Falha na Reposição",
    "retryOff" : "Não foi possível desactivar a definição",
    "oilSettingError" : "Erro de Definição de Óleo",
    "oilLife" : "Vida Útil do Óleo",
    "Off" : "Deslig.",
    "Back" : "Voltar",
    "turnOff" : "Desligar",
    "Cancel" : "Cancelar",
    "Retry" : "Tentar Novamente",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} dia",
    "days" : "{value} dias",
    "month" : "{value} mês",
    "months" : "{value} meses",
    "settingInterval" : "A Definir Intervalo",
    "Flexible" : "Flexível",
    "Fixed" : "Fixo",
    "scheduled" : "Agendada",
    "tryAgain" : "Pretende tentar novamente?",
    "confirmOffSchedule" : "Tem a certeza de que pretende desactivar a Manutenção Agendada?",
    "confirmOffTire" : "Tem a certeza de que pretende desactivar a Rotação dos Pneus?",
    "confirmOffOil" : "Tem a certeza de que pretende desactivar a Mudança de Óleo?",
    "confirmResetSchedule" : "Tem a certeza de que pretende repor a Manutenção Agendada?",
    "confirmResetTire" : "Tem a certeza de que pretende repor a Rotação dos Pneus?",
    "confirmResetOil" : "Tem a certeza de que pretende repor a Mudança de Óleo?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} meses",
    "dueInTimeDays" : "{dueInTime} dias",
    "dueInTimeDay" : "{dueInTime} dia",
    "flexibleOilChange" : "A escolha de definições Flexível requer a utilização do óleo de motor recomendado pela Mazda.",
    "fixedConfirm" : "Tem a certeza de que pretende definir a opção Mudança de Óleo como Fixo?",
    "retryFixed" : "Não foi possível alterar a definição para Fixo",
    "retryFlexible" : "Não foi possível alterar a definição para Flexível",
};

framework.registerAppDictLoaded("schedmaint", "pt_PT");