var Localization_schedmaintAppDict_lv_LV = {
    //"stringId" : "localString"
    "Maintenance" : "Apkope",
    "tireRotation" : "Riepu pārlikšana",
    "oilChange" : "Eļļas maiņa",
    "Setting" : "Iestatījumi",
    "Time" : "Laiks",
    "Distance" : "Attālums",
    "Reset" : "Atiestatīt",
    "scheduledDueIn" : "Apkope pēc:",
    "scheduledMaintenanceDue" : "Plānotā apkope!",
    "tireRotationDue" : "Jāveic riepu pārlikšana!",
    "oilChangeDue" : "Jāveic eļļas maiņa!",
    "resetFail" : "Atiestate neizdevās",
    "retryOff" : "Iestatījumu nevar izslēgt",
    "oilSettingError" : "Eļļas iestatījumu kļūda",
    "oilLife" : "Eļļas kalpošanas laiks",
    "Off" : "Izslēgts",
    "Back" : "Atpakaļ",
    "turnOff" : "Izslēgt",
    "Cancel" : "Atcelt",
    "Retry" : "Mēģināt vēlreiz",
    "OK" : "Labi",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} diena",
    "days" : "{value} dienas",
    "month" : "{value} mēnesis",
    "months" : "{value} mēneši",
    "settingInterval" : "Iestatīšanas intervāls",
    "Flexible" : "Elastīgs",
    "Fixed" : "Fiksēta",
    "scheduled" : "Plānotā",
    "tryAgain" : "Vai vēlaties mēģināt vēlreiz?",
    "confirmOffSchedule" : "Vai tiešām vēlaties izslēgt plānoto tehnisko apkopi?",
    "confirmOffTire" : "Vai tiešām vēlaties izslēgt riepu pārlikšanu?",
    "confirmOffOil" : "Vai tiešām vēlaties izslēgt eļļas nomaiņu?",
    "confirmResetSchedule" : "Vai tiešām vēlaties atjaunot plānoto tehnisko apkopi?",
    "confirmResetTire" : "Vai tiešām vēlaties atjaunot riepu pārlikšanu?",
    "confirmResetOil" : "Vai tiešām vēlaties atjaunot eļļas nomaiņu?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} mēnešos",
    "dueInTimeDays" : "{dueInTime} dienās",
    "dueInTimeDay" : "{dueInTime} dienā",
    "flexibleOilChange" : "Izvēloties pielāgojamus iestatījumus, jāizmanto Mazda ieteiktā motoreļļa.",
    "fixedConfirm" : "Vai tiešām vēlaties uzstādīt fiksētu eļļas nomaiņu?",
    "retryFixed" : "Iestatījumu nevar pārveidot par fiksētu",
    "retryFlexible" : "Iestatījumu nevar pārveidot par pielāgojamu",
};

framework.registerAppDictLoaded("schedmaint", "lv_LV");