var Localization_schedmaintAppDict_en_UK = {
    //"stringId" : "localString"
    "Maintenance" : "Maintenance",
    "tireRotation" : "Tyre Rotation",
    "oilChange" : "Oil Change",
    "Setting" : "Setting",
    "Time" : "Time",
    "Distance" : "Distance",
    "Reset" : "Reset",
    "scheduledDueIn" : "Due in:",
    "scheduledMaintenanceDue" : "Scheduled Due!",
    "tireRotationDue" : "Tyre Rotation Due!",
    "oilChangeDue" : "Oil Change Due!",
    "resetFail" : "Reset Failed",
    "retryOff" : "Setting could not be turned Off",
    "oilSettingError" : "Oil Setting Error",
    "oilLife" : "Oil Life",
    "Off" : "Off",
    "Back" : "Back",
    "turnOff" : "Turn Off",
    "Cancel" : "Cancel",
    "Retry" : "Retry",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} day",
    "days" : "{value} days",
    "month" : "{value} month",
    "months" : "{value} months",
    "settingInterval" : "Setting Interval",
    "Flexible" : "Flexible",
    "Fixed" : "Fixed",
    "scheduled" : "Scheduled",
    "tryAgain" : "Would you like to try again?",
    "confirmOffSchedule" : "Are you sure you want to turn Off Scheduled Maintenance?",
    "confirmOffTire" : "Are you sure you want to turn Off Tyre Rotation?",
    "confirmOffOil" : "Are you sure you want to turn Off Oil Change?",
    "confirmResetSchedule" : "Are you sure you want to reset Scheduled Maintenance?",
    "confirmResetTire" : "Are you sure you want to reset Tyre Rotation?",
    "confirmResetOil" : "Are you sure you want to reset Oil Change?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} months",
    "dueInTimeDays" : "{dueInTime} days",
    "dueInTimeDay" : "{dueInTime} day",
    "flexibleOilChange" : "Choosing Flexible Settings requires using Mazda recommended Motor Oil.",
    "fixedConfirm" : "Are you sure you want to set Oil Change to Fixed?",
    "retryFixed" : "Setting could not be turned to Fixed",
    "retryFlexible" : "Setting could not be turned to Flexible",
};

framework.registerAppDictLoaded("schedmaint", "en_UK");