var Localization_schedmaintAppDict_lt_LT = {
    //"stringId" : "localString"
    "Maintenance" : "Priežiūra",
    "tireRotation" : "Padangų sukeitimas",
    "oilChange" : "Alyvos keitimas",
    "Setting" : "Nustatymai",
    "Time" : "Laikas",
    "Distance" : "Atst.",
    "Reset" : "Atstatyti",
    "scheduledDueIn" : "Tec.s aptar. po:",
    "scheduledMaintenanceDue" : "Laikas atlikti tech. aptarnavimą!",
    "tireRotationDue" : "Laikas sukeisti padangas!",
    "oilChangeDue" : "Laikas keisti alyvą!",
    "resetFail" : "Nustatymas į pradinę padėtį nepavyko",
    "retryOff" : "Negalima išjungti parametro",
    "oilSettingError" : "Alyvos nustatymo klaida",
    "oilLife" : "Alyvos tarnavimo laikas",
    "Off" : "Išjungta",
    "Back" : "Atgal",
    "turnOff" : "Išjungti",
    "Cancel" : "Atšaukti",
    "Retry" : "Pakartoti",
    "OK" : "TAIP",
    "MILE" : "{value} mi",
    "KM" : "{value} km ",
    "day" : "{value} diena",
    "days" : "{value} dienos",
    "month" : "{value} mėnuo",
    "months" : "{value} mėnesiai",
    "settingInterval" : "Parametro intervalas",
    "Flexible" : "Keič.",
    "Fixed" : "Fiks.",
    "scheduled" : "Suplanuotas",
    "tryAgain" : "Norite bandyti dar kartą?",
    "confirmOffSchedule" : "Ar tikrai norite išjungti planinį techninį aptarnavimą?",
    "confirmOffTire" : "Ar tikrai norite išjungti padangų sukeitimą?",
    "confirmOffOil" : "Ar tikrai norite išjungti alyvos keitimą?",
    "confirmResetSchedule" : "Ar tikrai norite perstatyti planinį techninį aptarnavimą į pradinę padėtį?",
    "confirmResetTire" : "Ar tikrai norite nustatyti į pradinę padėtį padangų sukeitimą?",
    "confirmResetOil" : "Ar tikrai norite perstatyti į pradinę padėtį alyvos keitimą?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} mėnesių",
    "dueInTimeDays" : "{dueInTime} dienų",
    "dueInTimeDay" : "{dueInTime} diena",
    "flexibleOilChange" : "Keičiamus parametrus rinkitės naudodami Mazda rekomenduojamą alyvą.",
    "fixedConfirm" : "Ar tikrai norite nustatyti alyvos keitimo intervalą į fiksuotą?",
    "retryFixed" : "Parametras negali būti pakeistas į fiksuotą",
    "retryFlexible" : "Parsametras negali būti pakeistas į keičiamą",
};

framework.registerAppDictLoaded("schedmaint", "lt_LT");