var Localization_schedmaintAppDict_no_NO = {
    //"stringId" : "localString"
    "Maintenance" : "Vedlikehold",
    "tireRotation" : "Dekkrotering",
    "oilChange" : "Oljeskift",
    "Setting" : "Innstilling",
    "Time" : "Tidspkt.",
    "Distance" : "Avstand",
    "Reset" : "Tilbakestill",
    "scheduledDueIn" : "Innen:",
    "scheduledMaintenanceDue" : "Service påkrevd!",
    "tireRotationDue" : "Dekkrotasjon påkrevd!",
    "oilChangeDue" : "Oljeskift påkrevd!",
    "resetFail" : "Nullstilling mislyktes",
    "retryOff" : "Innstillingen kan ikke slås av",
    "oilSettingError" : "Feil ved oljeinnstilling",
    "oilLife" : "Levetid, olje",
    "Off" : "Av",
    "Back" : "Tilbake",
    "turnOff" : "Slå av",
    "Cancel" : "Avbryt",
    "Retry" : "Prøv på nytt",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} dag",
    "days" : "{value} dager",
    "month" : "{value} måned",
    "months" : "{value} måneder",
    "settingInterval" : "Stille inn intervall",
    "Flexible" : "Fleks.",
    "Fixed" : "Fast",
    "scheduled" : "Foreskrevet",
    "tryAgain" : "Vil du prøve på nytt?",
    "confirmOffSchedule" : "Er du sikker på at du vil slå av foreskrevet vedlikehold?",
    "confirmOffTire" : "Er du sikker på at du vil slå av dekkrotering?",
    "confirmOffOil" : "Er du sikker på at du vil slå av oljeskift?",
    "confirmResetSchedule" : "Er du sikker på at du vil tilbakestille foreskrevet vedlikehold?",
    "confirmResetTire" : "Er du sikker på at du vil tilbakestille dekkrotering?",
    "confirmResetOil" : "Er du sikker på at du vil tilbakestille oljeskift?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} måneder",
    "dueInTimeDays" : "{dueInTime} dager",
    "dueInTimeDay" : "{dueInTime} dag",
    "flexibleOilChange" : "Valg av fleksible innstillinger krever at du bruker motorolje som anbefales av Mazda.",
    "fixedConfirm" : "Er du sikker på at du vil stille inn oljeskift til fast?",
    "retryFixed" : "Innstillingen kan ikke stilles inn til fast",
    "retryFlexible" : "Innstillingen kan ikke stilles inn til fleksibel",
};

framework.registerAppDictLoaded("schedmaint", "no_NO");