var Localization_schedmaintAppDict_hr_HR = {
    //"stringId" : "localString"
    "Maintenance" : "Održavanje",
    "tireRotation" : "Rotacija gume",
    "oilChange" : "Promjena ulja",
    "Setting" : "Postavka",
    "Time" : "Vrijeme",
    "Distance" : "KM:",
    "Reset" : "Poništi ",
    "scheduledDueIn" : "Ističe:",
    "scheduledMaintenanceDue" : "Zakazan termin isteka!",
    "tireRotationDue" : "Očekuje se rotacija gume !",
    "oilChangeDue" : "Obavezna promjena ulja!",
    "resetFail" : "Resetiranje nije uspjelo",
    "retryOff" : "Postavka se nije mogla isključiti",
    "oilSettingError" : "Pogreška postavke ulja",
    "oilLife" : "Trajanje ulja",
    "Off" : "Isklj.",
    "Back" : "Natrag",
    "turnOff" : "Isključi",
    "Cancel" : "Poništi",
    "Retry" : "Pokušaj ponovno",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} dan",
    "days" : "{value} dana",
    "month" : "{value} mjesec",
    "months" : "{value} mjeseci",
    "settingInterval" : "Interval postavljanja",
    "Flexible" : "Fleksib.",
    "Fixed" : "Fiksni",
    "scheduled" : "Zakazani",
    "tryAgain" : "Želite li pok. ponovno?",
    "confirmOffSchedule" : "Jeste li sigurni da želite isklj. zakazano održavanje?",
    "confirmOffTire" : "Jeste li sigurni da želite isklj. rotaciju gume?",
    "confirmOffOil" : "Jeste li sigurni da želite isklj. zamjenu ulja?",
    "confirmResetSchedule" : "Jeste li sigurni da želite reset. zakazano održavanje?",
    "confirmResetTire" : "Jeste li sigurni da želite reset. rotaciju guma?",
    "confirmResetOil" : "Jeste li sigurni da želite reset. promjenu ulja?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} mj.",
    "dueInTimeDays" : "{dueInTime} dana",
    "dueInTimeDay" : "{dueInTime} dan",
    "flexibleOilChange" : "Biranje fleksibilnih postavki zahtijeva korištenje mot. ulja koje preporučuje Mazda",
    "fixedConfirm" : "Jeste li sigurni da promjenu ulja želite postaviti na fiksnu?",
    "retryFixed" : "Postavka se ne može postaviti na fiksnu",
    "retryFlexible" : "Postavka se ne može postaviti na fleksibilnu",
};

framework.registerAppDictLoaded("schedmaint", "hr_HR");