var Localization_schedmaintAppDict_he_IL = {
    //"stringId" : "localString"
    "Maintenance" : "תחזוקה",
    "tireRotation" : "החלפת צמיגים",
    "oilChange" : "החלפת שמן",
    "Setting" : "הגדרות",
    "Time" : "זמן",
    "Distance" : "מרחק",
    "Reset" : "אתחל מחדש (אפס)",
    "scheduledDueIn" : "חל ב:",
    "scheduledMaintenanceDue" : "מתוכנן לחול!",
    "tireRotationDue" : "הגיע זמן להחלפת צמיגים!",
    "oilChangeDue" : "הגיע זמן להחלפת שמן!",
    "resetFail" : "האתחול מחדש נכשל",
    "retryOff" : "לא ניתן לכבות הגדרה זו",
    "oilSettingError" : "שגיאת הגדרת דלק",
    "oilLife" : "אורך חיי דלק",
    "Off" : "כבוי",
    "Back" : "חזור",
    "turnOff" : "כבה",
    "Cancel" : "בטל",
    "Retry" : "נסה שנית",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} ק\"מ",
    "day" : "{value} יום",
    "days" : "{value} ימים",
    "month" : "{value} חודש",
    "months" : "{value} חודשים",
    "settingInterval" : "מגדיר מרווח",
    "Flexible" : "גמיש",
    "Fixed" : "קבוע",
    "scheduled" : "מתוזמן",
    "tryAgain" : "האם תרצה לנסות שנית?",
    "confirmOffSchedule" : "האם אתה בטוח שברצונך לכבות את התחזוקה המתוזמנת?",
    "confirmOffTire" : "האם אתה בטוח שברצונך לכבות את סיבוב הצמיגים?",
    "confirmOffOil" : "האם אתה בטוח שברצונך לכבות החלפת שמן?",
    "confirmResetSchedule" : "האם אתה בטוח שברצונך להגדיר מחדש תחזוקה מתוזמנת?",
    "confirmResetTire" : "האם אתה בטוח שברצונך להגדיר מחדש סיבוב צמיגים?",
    "confirmResetOil" : "האם אתה בטוח שבצרונך להגדיר מחדש החלפת שמן?",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : " ק\"מ {dueInDistance} ",
    "dueUnitFlexible" : "{dueInOil} % בעוד",
    "dueUnitOilKm" : " ק\"מ {dueInOil}",
    "dueUnitOilMile" : " מיילים {dueInOil} ",
    "dueInTimeMonths" : " חודשים {dueInTime}",
    "dueInTimeDays" : " ימים{dueInTime}",
    "dueInTimeDay" : " יום {dueInTime}",
    "flexibleOilChange" : "בחירת הגדרות גמישות מחייבת שימוש בשמן מנוע מומלץ של Mazda.",
    "fixedConfirm" : "האם אתה בטוח שברצונך להגדיר את החלפת השמן כקבועה?",
    "retryFixed" : "לא ניתן לשנות הגדרה זו לקבועה",
    "retryFlexible" : "לא ניתן לשנות הגדרה זו לגמישה",
};

framework.registerAppDictLoaded("schedmaint", "he_IL");