var Localization_schedmaintAppDict_ro_RO = {
    //"stringId" : "localString"
    "Maintenance" : "Întreţinere",
    "tireRotation" : "Permutare pneuri",
    "oilChange" : "Schimb de ulei",
    "Setting" : "Setare",
    "Time" : "Oră",
    "Distance" : "Distanţă",
    "Reset" : "Resetare",
    "scheduledDueIn" : "Timp rămas:",
    "scheduledMaintenanceDue" : "Urmează revizia!",
    "tireRotationDue" : "Urmează permutarea pneurilor!",
    "oilChangeDue" : "Urmează schimbul de ulei!",
    "resetFail" : "Resetare nereuşită",
    "retryOff" : "Setarea nu a putut fi oprită",
    "oilSettingError" : "Eroare setare ulei",
    "oilLife" : "Durabilitate ulei",
    "Off" : "Oprit",
    "Back" : "Înapoi",
    "turnOff" : "Oprire",
    "Cancel" : "Anulare",
    "Retry" : "Reîncercare",
    "OK" : "OK",
    "MILE" : "{value} mi",
    "KM" : "{value} km",
    "day" : "{value} zi",
    "days" : "{value} zile",
    "month" : "{value} lună",
    "months" : "{value} luni",
    "settingInterval" : "Interval setare",
    "Flexible" : "Flexibil",
    "Fixed" : "Fix",
    "scheduled" : "Programat",
    "tryAgain" : "Doriţi să reîncercaţi?",
    "confirmOffSchedule" : "Sunteţi sigur că doriţi să dezactivaţi întreţinerea programată?",
    "confirmOffTire" : "Sunteţi sigur că doriţi să dezactivaţi permutarea pneurilor?",
    "confirmOffOil" : "Sunteţi sigur că doriţi să dezactivaţi schimbul de ulei?",
    "confirmResetSchedule" : "Sunteţi sigur că doriţi să resetaţi întreţinerea programată?",
    "confirmResetTire" : "Sunteţi sigur că doriţi să resetaţi permutarea pneurilor?",
    "confirmResetOil" : "Sunteţi sigur că doriţi să resetaţi schimbul de ulei? ",
    "dueInMile" : "{dueInDistance} mi",
    "dueInKm" : "{dueInDistance} km",
    "dueUnitFlexible" : "{dueInOil} %",
    "dueUnitOilKm" : "{dueInOil} km",
    "dueUnitOilMile" : "{dueInOil} mi",
    "dueInTimeMonths" : "{dueInTime} luni ",
    "dueInTimeDays" : "{dueInTime} zile",
    "dueInTimeDay" : "{dueInTime} zi",
    "flexibleOilChange" : "Alegerea setărilor flexibile presupune folosirea uleiului de motor recomandat de Mazda.",
    "fixedConfirm" : "Sunteţi sigur că doriţi să setaţi schimbul de ulei la fix?",
    "retryFixed" : "Setarea nu a putut fi stabilită la fix.",
    "retryFlexible" : "Setarea nu a putut fi stabilită la Flexibil.",
};

framework.registerAppDictLoaded("schedmaint", "ro_RO");