var Localization_fmradioAppDict_ar_SA = {
	//"stringId" : "localString"
	"Affairs": "قضايا",
	"Alarm": "إنذار",
	"AlarmTest": "اختبار الإنذار",
	"AllMemoryFull": "الذاكرة ممتلئة بالكامل",
	"AllStations": "جميع المحطات",
	"AllTagsTransferred": "تم نقل جميع العلامات",
	"AlternativeFrequency": "موجة بديلة",
	"AutoMemoryList": "قائمة الذاكرة التلقائية",
	"CannotTransferTags": "لا يمكن نقل العلامات",
	"ChangeGenre": "نوع التغيير",
	"Childrens": "برامج أطفال",
	"Classics": "كلاسيكيات",
	"Close": "إغلاق",
	"ConnectIPod": "صل iPod لنقل العلامات",
	"Country": "كانتري",
	"Culture": "ثقافة",
	"Documentary": "برامج وثائقية",
	"Drama": "دراما",
	"Education": "تعليم",
	"ErrorConnection": "خطأ بنقل علامات لـiPod",
	"FMRadio": "راديو FM",
	"FMSettings": "إعدادات FM",
	"Finance": "اقتصاد",
	"Folk": "فولكلور",
	"GenreAffairs": "النوع: قضايا",
	"GenreAlarm": "النوع: إنذار",
	"GenreAlarmTest": "النوع: اختبار الإنذار",
	"GenreAllStations": "النوع: جميع المحطات",
	"GenreChildrens": "النوع: برامج أطفال",
	"GenreClassics": "النوع: كلاسيكيات",
	"GenreCountry": "النوع: كانتري",
	"GenreCulture": "النوع: ثقافة",
	"GenreDocumentary": "النوع: برامج وثائقية",
	"GenreDrama": "النوع: دراما",
	"GenreEducation": "النوع: تعليم",
	"GenreFinance": "النوع: اقتصاد",
	"GenreFolk": "النوع: فولكلور",
	"GenreInfo": "النوع: معلومات",
	"GenreJazz": "النوع: موسيقى الجاز",
	"GenreLeisure": "النوع: ترفيه",
	"GenreLight": "النوع: موسيقى هادئة",
	"GenreList": "قائمة الأنواع",
	"GenreMor": "النوع: موسيقى بنغمة عادية",
	"GenreName": "النوع: {genreName}",
	"GenreNational": "النوع: وطني",
	"GenreNews": "النوع: أخبار",
	"GenreOldies": "النوع: فنون قديمة",
	"GenreOther": "النوع: أخرى",
	"GenrePhoneIn": "النوع: مشاركة عبر الهاتف",
	"GenrePop": "النوع: موسيقى البوب",
	"GenreReligion": "النوع: برامج دينية",
	"GenreRock": "النوع: موسيقى الروك",
	"GenreScience": "النوع: علوم",
	"GenreSeek": "البحث عن النوع",
	"GenreSocial": "النوع: برامج اجتماعية",
	"GenreSport": "النوع: رياضة",
	"GenreTravel": "النوع: سفر",
	"GenreVaried": "النوع: منوعات",
	"GenreWeather": "النوع: طقس",
	"HDRadio": "راديو HD",
	"HDStations": "محطات HD",
	"Info": "معلومات",
	"IpodError": "حدث خطا في جهاز الـiPod",
	"IpodFull": "جهاز الـiPod ممتلئ",
	"Jazz": "موسيقى الجاز",
	"Leisure": "ترفيه",
	"Light": "موسيقى هادئة",
	"MemoryFull": "الذاكرة ممتلئة",
	"Mor": "موسيقى بنغمة عادية",
	"National": "وطني",
	"News": "أخبار",
	"Noresultsfound": "لم يتم العثور على نتائج",
	"Oldies": "فنون قديمة",
	"Other": "أخرى",
	"PartialTransfer": "نقل جزئي",
	"PhoneIn": "مشاركة عبر الهاتف",
	"Pop": "موسيقى البوب",
	"RegionLock": "قفل المنطقة",
	"Religion": "برامج دينية",
	"Remaining": "متبقي {numberOfTags}",
	"Remove": "إزالة",
	"Rock": "موسيقى الروك",
	"Science": "علوم",
	"SignalLost": "تم فقد الإشارة",
	"Social": "برامج اجتماعية",
	"Sport": "رياضة",
	"StationList": "قائمة المحطات",
	"TAOff": "وقف تنقل",
	"TagAlreadySaved": "تم حفظ العلامة بالفعل",
	"TagCaptured": "العلامة المرجعية الملتقطة",
	"TagMemoryFull": "ذاكرة العلامات ممتلئة",
	"TagNotYetProcessed": "لم تتم معالجة العلامة",
	"TagSaved": "تم حفظ العلامة",
	"TagSavedtoIpod": "حفظت العلامة على iPod",
	"TagSavedtoSystem": "حفظت العلامة في النظام",
	"TagTransferredtoiPod": "تم نقل العلامة إلى iPod",
	"TagsCannotBeSaved": "لا يمكن حفظ العلامات",
	"Tooltip_IcnUmpFMSettings": "إعدادات FM",
	"TrafficAlert": "تنبيه التنقل",
	"TrafficAlertOff": "إيقاف تنبيه التنقل",
	"TrafficAlertOn": "تشغيل تنبيه التنقل",
	"Travel": "سفر",
	"UnplugAndReconnect": "افصل وأعد التوصيل",
	"UpdateStationList": "تحديث قائمة المحطات",
	"UpdatingStationList": "تحديث قائمة المحطة",
	"Varied": "منوعات",
	"VrHelp_AutoMemory_Help1_Left1": "(التردد)",
	"VrHelp_AutoMemory_Help1_Left2": "تحديث القائمة",
	"VrHelp_AutoMemory_Help2_Left1": "تحديث القائمة",
	"VrHelp_GenreSeek_Help_Left1": "بحث لأعلى",
	"VrHelp_GenreSeek_Help_Left2": "بحث لأسفل",
	"VrHelp_GenreSeek_Help_Left3": "تغيير النوع",
	"VrHelp_NowPlayingEU_Help_Left1": "ترفيه ",
	"VrHelp_NowPlayingEU_Help_Left2": "قائمة المحطات",
	"VrHelp_NowPlayingEU_Help_Left3": "المفضلة",
	"VrHelp_NowPlayingEU_Help_Left4": "تنبيه التنقل",
	"VrHelp_NowPlayingEU_Help_Left5": "المسح الضوئي ",
	"VrHelp_NowPlayingEU_Help_Right1": "ضبط الراديو",
	"VrHelp_NowPlayingEU_Help_Right2": "بحث عن السابق",
	"VrHelp_NowPlayingEU_Help_Right3": "بحث عن التالي",
	"VrHelp_NowPlayingEU_Help_Right4": "إعدادات FM",
	"VrHelp_NowPlayingEU_Help_Right5": "إعدادات الصوت",
	"VrHelp_NowPlayingNA_Help_Left1": "ترفيه ",
	"VrHelp_NowPlayingNA_Help_Left2": "الذاكرة التلقائية ",
	"VrHelp_NowPlayingNA_Help_Left3": "المفضلة",
	"VrHelp_NowPlayingNA_Help_Left4": "قائمة HD",
	"VrHelp_NowPlayingNA_Help_Left5": "المسح الضوئي ",
	"VrHelp_NowPlayingNA_Help_Right1": "ضبط الراديو",
	"VrHelp_NowPlayingNA_Help_Right2": "علامات iTunes",
	"VrHelp_NowPlayingNA_Help_Right3": "بحث عن السابق",
	"VrHelp_NowPlayingNA_Help_Right4": "بحث عن التالي",
	"VrHelp_NowPlayingNA_Help_Right5": "إعدادات الصوت",
	"VrHelp_NowPlayingOther_Help_Left1": "ترفيه ",
	"VrHelp_NowPlayingOther_Help_Left2": "الذاكرة التلقائية ",
	"VrHelp_NowPlayingOther_Help_Left3": "المفضلة",
	"VrHelp_NowPlayingOther_Help_Left4": "المسح الضوئي ",
	"VrHelp_NowPlayingOther_Help_Left5": "ضبط الراديو",
	"VrHelp_NowPlayingOther_Help_Right1": "بحث عن السابق",
	"VrHelp_NowPlayingOther_Help_Right2": "بحث عن التالي",
	"VrHelp_NowPlayingOther_Help_Right3": "إعدادات الصوت",
	"VrHelp_Settings_Help_Left1": "تشغيل التردد البديل",
	"VrHelp_Settings_Help_Left2": "إيقاف التردد البديل",
	"VrHelp_Settings_Help_Left3": "تشغيل قفل المنطقة",
	"VrHelp_Settings_Help_Left4": "إيقاف قفل المنطقة",
	"VrHelp_Tune_NA_Help_Left1": "(التردد)",
	"VrHelp_Tune_NA_Help_Left2": "توليف لأعلى",
	"VrHelp_Tune_NA_Help_Left3": "توليف لأسفل",
	"VrHelp_Tune_nonNA_Help_Left1": "(التردد)",
	"VrHelp_Tune_nonNA_Help_Left2": "توليف لأعلى",
	"VrHelp_Tune_nonNA_Help_Left3": "توليف لأسفل",
	"Weather": "طقس",
	"favorites_Tooltip": "المفضلات",
	"hdChannels_Tooltip": "قنوات HD",
	"rbds_Adult": "أغاني الكبار",
	"rbds_Class": "كلاسيك روك",
	"rbds_Classical": "كلاسيكي",
	"rbds_College": "كلية",
	"rbds_Country": "كانتري",
	"rbds_Emergency": "تنبيه! تنبيه!",
	"rbds_EmergencyTest": "اختبار الطوارئ",
	"rbds_Foreign": "لغة اجنبية",
	"rbds_Hablar": "تحدث الإسبانية",
	"rbds_HipHop": "الهيب هوب",
	"rbds_Info": "معلومات",
	"rbds_Jazz": "موسيقى الجاز",
	"rbds_Musica": "الموسيقى الإسبانية",
	"rbds_News": "أخبار",
	"rbds_None": "لا يوجد",
	"rbds_Nostalgia": "حنين",
	"rbds_Oldies": "فنون قديمة",
	"rbds_Personality": "شخصية بارزة",
	"rbds_Public": "عام",
	"rbds_ReligousM": "موسيقى دينية",
	"rbds_ReligousT": "حوار ديني",
	"rbds_Rhythym": "ريذم آند بلوز",
	"rbds_Rock": "موسيقى الروك",
	"rbds_Soft": "رقيق",
	"rbds_SoftRB": "سوفت ريذم آند بلوز",
	"rbds_SoftRock": "سوفت روك",
	"rbds_Sports": "رياضة",
	"rbds_Talk": "حوار",
	"rbds_Top40": "أفضل 40",
	"rbds_Weather": "طقس",
	"rbds_genre_Adult": "النوع: أغاني الكبار",
	"rbds_genre_Class": "النوع: كلاسيك روك",
	"rbds_genre_Classical": "النوع: كلاسيكي",
	"rbds_genre_College": "النوع: كلية",
	"rbds_genre_Country": "النوع: كانتري",
	"rbds_genre_Emergency": "النوع: تنبيه! تنبيه!",
	"rbds_genre_EmergencyTest": "النوع: اختبار الطوارئ",
	"rbds_genre_Foreign": "النوع: لغة أجنبية",
	"rbds_genre_Hablar": "النوع: تحدث الإسبانية",
	"rbds_genre_HipHop": "النوع: الهيب هوب",
	"rbds_genre_Info": "النوع: معلومات",
	"rbds_genre_Jazz": "النوع: موسيقى الجاز",
	"rbds_genre_Musica": "النوع: الموسيقى الإسبانية",
	"rbds_genre_News": "النوع: أخبار",
	"rbds_genre_None": "النوع: لا يوجد",
	"rbds_genre_Nostalgia": "النوع: حنين",
	"rbds_genre_Oldies": "النوع: فنون قديمة",
	"rbds_genre_Personality": "لنوع: شخصية بارزة",
	"rbds_genre_Public": "لنوع: عام",
	"rbds_genre_ReligousM": "النوع: موسيقى دينية",
	"rbds_genre_ReligousT": "النوع: حوار ديني",
	"rbds_genre_Rhythym": "النوع: ريذم آند بلوز",
	"rbds_genre_Rock": "النوع: موسيقى الروك",
	"rbds_genre_Soft": "النوع: رقيق",
	"rbds_genre_SoftRB": "النوع: سوفت ريذم آند بلوز",
	"rbds_genre_SoftRock": "النوع: سوفت روك",
	"rbds_genre_Sports": "النوع: رياضة",
	"rbds_genre_Talk": "النوع: حوار",
	"rbds_genre_Top40": "النوع: أفضل 40",
	"rbds_genre_Weather": "النوع: طقس",
};

framework.registerAppDictLoaded("fmradio", "ar_SA");