var Localization_fmradioAppDict_no_NO = {
	//"stringId" : "localString"
	"Affairs": "Aktuelt",
	"Alarm": "Alarm",
	"AlarmTest": "Alarmtest",
	"AllMemoryFull": "Alt minne er fullt",
	"AllStations": "Alle stasjoner",
	"AllTagsTransferred": "Alle taggene er overført",
	"AlternativeFrequency": "Alternativ frekvens",
	"AutoMemoryList": "Autominneliste",
	"CannotTransferTags": "Kan ikke overføre tagger",
	"ChangeGenre": "Endre sjanger",
	"Childrens": "For barn",
	"Classics": "Klassisk",
	"Close": "Lukk",
	"ConnectIPod": "Kobl. til iPod for tag-overf",
	"Country": "Country",
	"Culture": "Kultur",
	"Documentary": "Dokumentar",
	"Drama": "Drama",
	"Education": "Utdanning",
	"ErrorConnection": "F. ved overf. av tag iPod",
	"FMRadio": "FM radio",
	"FMSettings": "FM-innstillinger",
	"Finance": "Finans",
	"Folk": "Folkemusikk",
	"GenreAffairs": "Sjanger: Aktuelt",
	"GenreAlarm": "Sjanger: Alarm",
	"GenreAlarmTest": "Sjanger: Alarmtest",
	"GenreAllStations": "Sjanger: Alle stasjoner",
	"GenreChildrens": "Sjanger: For barn",
	"GenreClassics": "Sjanger: Klassisk",
	"GenreCountry": "Sjanger: Country",
	"GenreCulture": "Sjanger: Kultur",
	"GenreDocumentary": "Sjanger: Dokumentar",
	"GenreDrama": "Sjanger: Drama",
	"GenreEducation": "Sjanger: Utdanning",
	"GenreFinance": "Sjanger: Finans",
	"GenreFolk": "Sjanger: Folkemusikk",
	"GenreInfo": "Sjanger: Informasjon",
	"GenreJazz": "Sjanger: Jazz",
	"GenreLeisure": "Sjanger: Fritid",
	"GenreLight": "Sjanger: Lett",
	"GenreList": "Sjangerliste",
	"GenreMor": "Sjanger: Easy Listening",
	"GenreName": "Sjanger: {genreName}",
	"GenreNational": "Sjanger: Nasjonal",
	"GenreNews": "Sjanger: Nyheter",
	"GenreOldies": "Sjanger: Oldies",
	"GenreOther": "Sjanger: Annet",
	"GenrePhoneIn": "Sjanger: Telefon inn",
	"GenrePop": "Sjanger: Pop",
	"GenreReligion": "Sjanger: Religion",
	"GenreRock": "Sjanger: Rock",
	"GenreScience": "Sjanger: Vitenskap",
	"GenreSeek": "Sjangersøk",
	"GenreSocial": "Sjanger: Sosialt",
	"GenreSport": "Sjanger: Sport",
	"GenreTravel": "Sjanger: Reise",
	"GenreVaried": "Sjanger: Diverse",
	"GenreWeather": "Sjanger: Vær",
	"HDRadio": "HD Radio",
	"HDStations": "HD-stasjoner",
	"Info": "Informasjon ",
	"IpodError": "iPod-feil",
	"IpodFull": "iPod er full",
	"Jazz": "Jazz",
	"Leisure": "Fritid",
	"Light": "Lett",
	"MemoryFull": "Minnet er fullt",
	"Mor": "Easy Listening ",
	"National": "Nasjonal",
	"News": "Nyheter",
	"Noresultsfound": "Fant ingen resultater",
	"Oldies": "Oldies",
	"Other": "Annet",
	"PartialTransfer": "Delvis overføring",
	"PhoneIn": "Telefon inn",
	"Pop": "Pop",
	"RegionLock": "Regionlås",
	"Religion": "Religion",
	"Remaining": "{numberOfTags} gjenstår",
	"Remove": "Fjern",
	"Rock": "Rock",
	"Science": "Vitenskap",
	"SignalLost": "Tapt signal",
	"Social": "Sosialt",
	"Sport": "Sport",
	"StationList": "Stasjonsliste",
	"TAOff": "TA av",
	"TagAlreadySaved": "Taggen er allerede lagret",
	"TagCaptured": "Tagg opptak",
	"TagMemoryFull": "Tagg-minnet er fullt",
	"TagNotYetProcessed": "Tag. er ikke behan. Ennå",
	"TagSaved": "Taggen er lagret",
	"TagSavedtoIpod": "Taggen er lagret på iPod",
	"TagSavedtoSystem": "Taggen er lagret på syst.",
	"TagTransferredtoiPod": "Taggen overført til iPod",
	"TagsCannotBeSaved": "Taggene kan ikke lagres",
	"Tooltip_IcnUmpFMSettings": "FM-innstillinger",
	"TrafficAlert": "Trafikkmelding (TA)",
	"TrafficAlertOff": "Trafikkmelding (TA) av",
	"TrafficAlertOn": "Trafikkmelding (TA) på",
	"Travel": "Fjæringslengde",
	"UnplugAndReconnect": "Koble fra og til på nytt",
	"UpdateStationList": "Oppdater stasjonsliste",
	"UpdatingStationList": "Oppdaterer stasjonsliste",
	"Varied": "Diverse",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Vær",
	"favorites_Tooltip": "Favoritter",
	"hdChannels_Tooltip": "HD-kanaler",
	"rbds_Adult": "Adult hits",
	"rbds_Class": "Klassisk Rock",
	"rbds_Classical": "Klassisk",
	"rbds_College": "Høyskole",
	"rbds_Country": "Country",
	"rbds_Emergency": "Varsle! Varsle!",
	"rbds_EmergencyTest": "Test, nødsituasjon",
	"rbds_Foreign": "Fremmedspråk",
	"rbds_Hablar": "Snakker Spansk",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Informasjon",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Spansk Musikk",
	"rbds_News": "Nyheter",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgi",
	"rbds_Oldies": "Oldies",
	"rbds_Personality": "Personlighet",
	"rbds_Public": "Public",
	"rbds_ReligousM": "Religiøs Musikk",
	"rbds_ReligousT": "Religiøs Diskusjon",
	"rbds_Rhythym": "Rhythm and Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Soft",
	"rbds_SoftRB": "Soft R&B",
	"rbds_SoftRock": "Soft rock",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Diskusjon",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Vær",
	"rbds_genre_Adult": "Sjanger: Adult hits",
	"rbds_genre_Class": "Sjanger: Klassisk Rock",
	"rbds_genre_Classical": "Sjanger: Klassisk",
	"rbds_genre_College": "Sjanger: Høyskole",
	"rbds_genre_Country": "Sjanger: Country",
	"rbds_genre_Emergency": "Sjanger: Varsle! Varsle!",
	"rbds_genre_EmergencyTest": "Sjanger: Test, nødsituasjon",
	"rbds_genre_Foreign": "Sjanger: Fremmedspråk",
	"rbds_genre_Hablar": "Sjanger: Snakker Spansk",
	"rbds_genre_HipHop": "Sjanger: Hip Hop",
	"rbds_genre_Info": "Sjanger: Informasjon",
	"rbds_genre_Jazz": "Sjanger: Jazz",
	"rbds_genre_Musica": "Sjanger: Spansk Musikk",
	"rbds_genre_News": "Sjanger: Nyheter",
	"rbds_genre_None": "Sjanger: --",
	"rbds_genre_Nostalgia": "Sjanger: Nostalgi",
	"rbds_genre_Oldies": "Sjanger: Oldies",
	"rbds_genre_Personality": "Sjanger: Personlighet",
	"rbds_genre_Public": "Sjanger: Public",
	"rbds_genre_ReligousM": "Sjanger: Religiøs Musikk",
	"rbds_genre_ReligousT": "Sjanger: Religiøs Diskusjon",
	"rbds_genre_Rhythym": "Sjanger: Rhythm and Blues",
	"rbds_genre_Rock": "Sjanger: Rock",
	"rbds_genre_Soft": "Sjanger: Soft",
	"rbds_genre_SoftRB": "Sjanger: Soft R&B",
	"rbds_genre_SoftRock": "Sjanger: Soft rock",
	"rbds_genre_Sports": "Sjanger: Sports",
	"rbds_genre_Talk": "Sjanger: Diskusjon",
	"rbds_genre_Top40": "Sjanger: Top 40",
	"rbds_genre_Weather": "Sjanger: Vær",
};

framework.registerAppDictLoaded("fmradio", "no_NO");