var Localization_fmradioAppDict_cs_CS = {
	//"stringId" : "localString"
	"Affairs": "Události",
	"Alarm": "Alarm",
	"AlarmTest": "Zkouška alarmu",
	"AllMemoryFull": "Paměť je plná",
	"AllStations": "Všechny stanice",
	"AllTagsTransferred": "Všechny zálož. přeneseny",
	"AlternativeFrequency": "Náhradní frekvence",
	"AutoMemoryList": "Seznam automatické paměti",
	"CannotTransferTags": "Nelze přenést záložky",
	"ChangeGenre": "Změnit žánr",
	"Childrens": "Dětský",
	"Classics": "Klasika",
	"Close": "Zavřít",
	"ConnectIPod": "Připojit iPod k záložkám",
	"Country": "Venkovský",
	"Culture": "Kultura",
	"Documentary": "Dokumentární",
	"Drama": "Drama",
	"Education": "Vzdělávání",
	"ErrorConnection": "Chyba přen.zálož.do iPodu",
	"FMRadio": "Rádio FM",
	"FMSettings": "Nastavení FM",
	"Finance": "Ekonomika",
	"Folk": "Folk",
	"GenreAffairs": "Žánr: Události",
	"GenreAlarm": "Žánr: Alarm",
	"GenreAlarmTest": "Žánr: Test alarmu",
	"GenreAllStations": "Žánr: Všechny stanice",
	"GenreChildrens": "Žánr: Dětský",
	"GenreClassics": "Žánr: Klasika",
	"GenreCountry": "Žánr: Venkovský",
	"GenreCulture": "Žánr: Kultura",
	"GenreDocumentary": "Žánr: Dokument",
	"GenreDrama": "Žánr: Drama",
	"GenreEducation": "Žánr: Vzdělávání",
	"GenreFinance": "Žánr: Ekonomika",
	"GenreFolk": "Žánr: Folk",
	"GenreInfo": "Žánr: Informace",
	"GenreJazz": "Žánr: Jazz",
	"GenreLeisure": "Žánr: Zábavný",
	"GenreLight": "Žánr: Lehký",
	"GenreList": "Seznam žánrů",
	"GenreMor": "Žánr: Snadné poslouchání",
	"GenreName": "Žánr : {genreName}",
	"GenreNational": "Žánr: Národní",
	"GenreNews": "Žánr: Zprávy",
	"GenreOldies": "Žánr: Oldies",
	"GenreOther": "Žánr: Další",
	"GenrePhoneIn": "Žánr: PhoneIn",
	"GenrePop": "Žánr: Pop",
	"GenreReligion": "Žánr: Náboženský",
	"GenreRock": "Žánr: Rock",
	"GenreScience": "Žánr: Věda",
	"GenreSeek": "Vyhledávání žánru",
	"GenreSocial": "Žánr: Společenský",
	"GenreSport": "Žánr: Sport",
	"GenreTravel": "Žánr: Cestovatelský",
	"GenreVaried": "Žánr: Smíšený",
	"GenreWeather": "Žánr: Počasí",
	"HDRadio": "Rádio HD",
	"HDStations": "Stanice HD",
	"Info": "Informace",
	"IpodError": "Chyba iPodu",
	"IpodFull": "iPod zaplněn",
	"Jazz": "Jazz",
	"Leisure": "Zábavný",
	"Light": "Lehký",
	"MemoryFull": "Paměť zaplněna",
	"Mor": "Snadné poslouchání",
	"National": "Národní",
	"News": "Zprávy",
	"Noresultsfound": "Nebyl nalezen žádný výsledek",
	"Oldies": "Oldies",
	"Other": "Další",
	"PartialTransfer": "Částečný přenos",
	"PhoneIn": "Telefonní kontakt",
	"Pop": "Pop",
	"RegionLock": "Regionální zámek",
	"Religion": "Náboženský",
	"Remaining": "Zůstává {numberOfTags}",
	"Remove": "Odebrat",
	"Rock": "Rock",
	"Science": "Věda",
	"SignalLost": "Ztráta signálu",
	"Social": "Společenský",
	"Sport": "Sport",
	"StationList": "Seznam stanic",
	"TAOff": "TA vyp.",
	"TagAlreadySaved": "Záložka je již uložena.",
	"TagCaptured": "Zaškrtnutí zaznamenáno",
	"TagMemoryFull": "Paměť záložek je plná.",
	"TagNotYetProcessed": "Zálož. zatím nezpracována",
	"TagSaved": "Záložka uložena",
	"TagSavedtoIpod": "Záložka uložena do iPodu",
	"TagSavedtoSystem": "Zálož. uložena do systému",
	"TagTransferredtoiPod": "Zálož. přenesena do iPodu",
	"TagsCannotBeSaved": "Záložky nelze uložit",
	"Tooltip_IcnUmpFMSettings": "Nastavení FM",
	"TrafficAlert": "Dopravní oznámení (TA)",
	"TrafficAlertOff": "Dopravní oznámení (TA) vypn.",
	"TrafficAlertOn": "Dopravní oznámení (TA) zapn.",
	"Travel": "Cestovatelský",
	"UnplugAndReconnect": "Odpojit a znovu zapojit",
	"UpdateStationList": "Aktualizovat seznam stanic",
	"UpdatingStationList": "Aktualizovat seznam stanic",
	"Varied": "Smíšený",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Počasí",
	"favorites_Tooltip": "Oblíbené",
	"hdChannels_Tooltip": "HD Kanály",
	"rbds_Adult": "Dospělí Hits",
	"rbds_Class": "Klasický Rocková",
	"rbds_Classical": "Klasický",
	"rbds_College": "Kolej",
	"rbds_Country": "Venkovský",
	"rbds_Emergency": "Upozornění! Upozornění!",
	"rbds_EmergencyTest": "Nouzové Testy",
	"rbds_Foreign": "Cizí jazyk",
	"rbds_Hablar": "Mluvit španělsky!",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Informace",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Španělská Hudba",
	"rbds_News": "Zprávy",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgie",
	"rbds_Oldies": "Oldies",
	"rbds_Personality": "Osobnost",
	"rbds_Public": "Veřejnost",
	"rbds_ReligousM": "Náboženská Hudba",
	"rbds_ReligousT": "Náboženské Diskuse",
	"rbds_Rhythym": "Rytmus a Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Měkké",
	"rbds_SoftRB": "Měkké R&B",
	"rbds_SoftRock": "Měkké Rocková",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Rozhovory",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Počasí",
	"rbds_genre_Adult": "Žánr: Dospělí Hits",
	"rbds_genre_Class": "Žánr: Klasický Rocková",
	"rbds_genre_Classical": "Žánr: Klasický",
	"rbds_genre_College": "Žánr: Kolej",
	"rbds_genre_Country": "Žánr: Venkovský",
	"rbds_genre_Emergency": "Žánr: Upozornění! Upozornění!",
	"rbds_genre_EmergencyTest": "Žánr: Nouzové Testy",
	"rbds_genre_Foreign": "Žánr: Cizí jazyk",
	"rbds_genre_Hablar": "Žánr: Mluvit španělsky!",
	"rbds_genre_HipHop": "Žánr: Hip Hop",
	"rbds_genre_Info": "Žánr: Informace",
	"rbds_genre_Jazz": "Žánr: Jazz",
	"rbds_genre_Musica": "Žánr: Španělská Hudba",
	"rbds_genre_News": "Žánr: Zprávy",
	"rbds_genre_None": "Žánr: --",
	"rbds_genre_Nostalgia": "Žánr: Nostalgie",
	"rbds_genre_Oldies": "Žánr: Oldies",
	"rbds_genre_Personality": "Žánr: Osobnost",
	"rbds_genre_Public": "Žánr: Veřejnost",
	"rbds_genre_ReligousM": "Žánr: Náboženská Hudba",
	"rbds_genre_ReligousT": "Žánr: Náboženské Diskuse",
	"rbds_genre_Rhythym": "Žánr: Rytmus a Blues",
	"rbds_genre_Rock": "Žánr: Rock",
	"rbds_genre_Soft": "Žánr: Měkké",
	"rbds_genre_SoftRB": "Žánr: Měkké R&B",
	"rbds_genre_SoftRock": "Žánr: Měkké Rocková",
	"rbds_genre_Sports": "Žánr: Sports",
	"rbds_genre_Talk": "Žánr: Rozhovory",
	"rbds_genre_Top40": "Žánr: Top 40",
	"rbds_genre_Weather": "Žánr: Počasí",
};

framework.registerAppDictLoaded("fmradio", "cs_CS");