var Localization_fmradioAppDict_lt_LT = {
	//"stringId" : "localString"
	"Affairs": "Verslas",
	"Alarm": "Pavojaus signalas",
	"AlarmTest": "Pavojaus signalo testas",
	"AllMemoryFull": "Visa atmintis užpildyta",
	"AllStations": "Visos stotys",
	"AllTagsTransferred": "Visos žymės perkeltos",
	"AlternativeFrequency": "Alternatyvus dažnis",
	"AutoMemoryList": "Automatinės atminties sąrašas",
	"CannotTransferTags": "Negalima perduoti žymių",
	"ChangeGenre": "Keisti žanrą",
	"Childrens": "Vaikai",
	"Classics": "Klasika",
	"Close": "Užd.",
	"ConnectIPod": "Prijungti iPod žym. Perd.",
	"Country": "Kantri",
	"Culture": "Kultūra",
	"Documentary": "Dokumentinis",
	"Drama": "Drama",
	"Education": "Švietimas",
	"ErrorConnection": "Klaida perd. žym. į iPod",
	"FMRadio": "FM radijas",
	"FMSettings": "FM nustatymai",
	"Finance": "Finansai",
	"Folk": "Liaudies muzika",
	"GenreAffairs": "Žanras: verslas",
	"GenreAlarm": "Žanras: pavojaus signalas",
	"GenreAlarmTest": "Žanras: pavojaus signalo testas",
	"GenreAllStations": "Žanras: visos stotys",
	"GenreChildrens": "Žanras: vaikai",
	"GenreClassics": "Žanras: klasika",
	"GenreCountry": "Žanras: kantri",
	"GenreCulture": "Žanras: kultūra",
	"GenreDocumentary": "Žanras: dokumentinis",
	"GenreDrama": "Žanras: drama",
	"GenreEducation": "Žanras: švietimas",
	"GenreFinance": "Žanras: finansai",
	"GenreFolk": "Žanras: liaudies muzika",
	"GenreInfo": "Žanras: informacija",
	"GenreJazz": "Žanras: džiazas",
	"GenreLeisure": "Žanras: poilsis",
	"GenreLight": "Žanras: lengvoji muzika",
	"GenreList": "Žanrų sąrašas",
	"GenreMor": "Žanras: lengvoji muzika",
	"GenreName": "Žanras: {genreName}",
	"GenreNational": "Žanras: nacionalinis",
	"GenreNews": "Žanras: naujienos",
	"GenreOldies": "Žanras: senienos",
	"GenreOther": "Žanras: kita",
	"GenrePhoneIn": "Žanras: telefono prijungimas",
	"GenrePop": "Žanras: pop",
	"GenreReligion": "Žanras: religija",
	"GenreRock": "Žanras: rokas",
	"GenreScience": "Žanras: mokslas",
	"GenreSeek": "Žanro paieška",
	"GenreSocial": "Žanras: socialinis",
	"GenreSport": "Žanras: sportas",
	"GenreTravel": "Žanras: kelionės",
	"GenreVaried": "Žanras: įvairūs",
	"GenreWeather": "Žanras: oras",
	"HDRadio": "HD radijas",
	"HDStations": "HD stotys",
	"Info": "Informacija",
	"IpodError": "iPod klaida",
	"IpodFull": "iPod užpildytas",
	"Jazz": "Džiazas",
	"Leisure": "Poilsis",
	"Light": "Lengva",
	"MemoryFull": "Atmintis užpildyta",
	"Mor": "Lengvoji muzika",
	"National": "Nacionalinis",
	"News": "Naujienos",
	"Noresultsfound": "Rezultatų nerasta",
	"Oldies": "Senienos",
	"Other": "Kita",
	"PartialTransfer": "Dalinis perdavimas",
	"PhoneIn": "Iškvietimo signalas",
	"Pop": "Pop",
	"RegionLock": "Regiono užraktas",
	"Religion": "Religija",
	"Remaining": "Liko {numberOfTags}",
	"Remove": "Šalinti",
	"Rock": "Rokas",
	"Science": "Mokslas",
	"SignalLost": "Dingo signalas",
	"Social": "Socialinis",
	"Sport": "Sportas",
	"StationList": "Stočių sąrašas",
	"TAOff": "Eismo įsp. išj.",
	"TagAlreadySaved": "Žymė jau įrašyta",
	"TagCaptured": "Žymė užfiksuota",
	"TagMemoryFull": "Žymių atmintis užpildyta",
	"TagNotYetProcessed": "Žymė dar neapdorota",
	"TagSaved": "Žymė įrašyta",
	"TagSavedtoIpod": "Žymė įrašyta iPod",
	"TagSavedtoSystem": "Žymė įrašyta sistemoje",
	"TagTransferredtoiPod": "Žymė perkelta į iPod",
	"TagsCannotBeSaved": "Įrašyti žymių negalima",
	"Tooltip_IcnUmpFMSettings": "FM nustatymai",
	"TrafficAlert": "Pranešimas apie eismą",
	"TrafficAlertOff": "Pranešimas apie eismą išjungtas",
	"TrafficAlertOn": "Pranešimas apie eismą įjungtas",
	"Travel": "Kelionės",
	"UnplugAndReconnect": "Atjungti ir vėl prijungti",
	"UpdateStationList": "Naujinti stočių sąrašą",
	"UpdatingStationList": "Naujinamas stočių sąrašas",
	"Varied": "Įvairūs",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Oras",
	"favorites_Tooltip": "Mėgstamiausi",
	"hdChannels_Tooltip": "HD kanalai",
	"rbds_Adult": "Suaugusiųjų Hitai",
	"rbds_Class": "Klasikinis Rokas",
	"rbds_Classical": "Klasikinis",
	"rbds_College": "Kolegija",
	"rbds_Country": "Kantri",
	"rbds_Emergency": "įspėti! įspėti!",
	"rbds_EmergencyTest": "Avarinis Testas",
	"rbds_Foreign": "Užsienio Kalba",
	"rbds_Hablar": "Ispanų kalba",
	"rbds_HipHop": "Hip-Hop",
	"rbds_Info": "Informacija",
	"rbds_Jazz": "Džiazas",
	"rbds_Musica": "Ispanų Muzika",
	"rbds_News": "Naujienos",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgija",
	"rbds_Oldies": "Senienos",
	"rbds_Personality": "Asmenybė",
	"rbds_Public": "Visuomenės",
	"rbds_ReligousM": "Religinė Muzika",
	"rbds_ReligousT": "Religiniai pokalbiai",
	"rbds_Rhythym": "Ritmenbliuzo",
	"rbds_Rock": "Rokas",
	"rbds_Soft": "Lengvas",
	"rbds_SoftRB": "Lengvas R&B",
	"rbds_SoftRock": "Lengvas rokas",
	"rbds_Sports": "Sportas",
	"rbds_Talk": "Pokalbiai",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Oras",
	"rbds_genre_Adult": "Žanras: Suaugusiųjų Hitai",
	"rbds_genre_Class": "Žanras: Klasikinis Rokas",
	"rbds_genre_Classical": "Žanras: Klasikinis",
	"rbds_genre_College": "Žanras: Kolegija",
	"rbds_genre_Country": "Žanras: Kantri",
	"rbds_genre_Emergency": "Žanras: įspėti! įspėti!",
	"rbds_genre_EmergencyTest": "Žanras: Avarinis Testas",
	"rbds_genre_Foreign": "Žanras: Užsienio Kalba",
	"rbds_genre_Hablar": "Žanras: Ispanų kalba",
	"rbds_genre_HipHop": "Žanras: Hip-Hop",
	"rbds_genre_Info": "Žanras: Informacija",
	"rbds_genre_Jazz": "Žanras: Džiazas",
	"rbds_genre_Musica": "Žanras: Ispanų Muzika",
	"rbds_genre_News": "Žanras: Naujienos",
	"rbds_genre_None": "Žanras: --",
	"rbds_genre_Nostalgia": "Žanras: Nostalgija",
	"rbds_genre_Oldies": "Žanras: Senienos",
	"rbds_genre_Personality": "Žanras: Asmenybė",
	"rbds_genre_Public": "Žanras: Visuomenės",
	"rbds_genre_ReligousM": "Žanras: Religinė Muzika",
	"rbds_genre_ReligousT": "Žanras: Religiniai pokalbiai",
	"rbds_genre_Rhythym": "Žanras: Ritmenbliuzo",
	"rbds_genre_Rock": "Žanras: Rokas",
	"rbds_genre_Soft": "Žanras: Lengvas",
	"rbds_genre_SoftRB": "Žanras: Lengvas R&B",
	"rbds_genre_SoftRock": "Žanras: Lengvas rokas",
	"rbds_genre_Sports": "Žanras: Sportas",
	"rbds_genre_Talk": "Žanras: Pokalbiai",
	"rbds_genre_Top40": "Žanras: Top 40",
	"rbds_genre_Weather": "Žanras: Oras",
};

framework.registerAppDictLoaded("fmradio", "lt_LT");