var Localization_fmradioAppDict_zh_TW = {
	//"stringId" : "localString"
	"Affairs": "政事",
	"Alarm": "警報",
	"AlarmTest": "警報測試",
	"AllMemoryFull": "所有記憶體已滿",
	"AllStations": "所有電臺",
	"AllTagsTransferred": "已轉移所有標籤",
	"AlternativeFrequency": "替代頻率",
	"AutoMemoryList": "自動記憶列表",
	"CannotTransferTags": "無法轉移標籤",
	"ChangeGenre": "變更類型",
	"Childrens": "兒童",
	"Classics": "古典樂",
	"Close": "關閉",
	"ConnectIPod": "連接 iPod 以轉移標籤",
	"Country": "鄉村",
	"Culture": "文化",
	"Documentary": "紀實",
	"Drama": "戲劇",
	"Education": "教育",
	"ErrorConnection": "向iPod轉移標籤時出錯",
	"FMRadio": "FM",
	"FMSettings": "FM 設置",
	"Finance": "財經",
	"Folk": "民謠",
	"GenreAffairs": "類型： 政事",
	"GenreAlarm": "類型：警報",
	"GenreAlarmTest": "類型：警報測試",
	"GenreAllStations": "類型：所有電臺",
	"GenreChildrens": "類型： 兒童",
	"GenreClassics": "類型： 古典樂",
	"GenreCountry": "類型：鄉村音樂",
	"GenreCulture": "類型： 文化",
	"GenreDocumentary": "類型：紀實",
	"GenreDrama": "類型： 戲劇",
	"GenreEducation": "類型： 教育",
	"GenreFinance": "類型： 財經",
	"GenreFolk": "類型： 民謠",
	"GenreInfo": "類型：資訊",
	"GenreJazz": "類型： 爵士樂",
	"GenreLeisure": "類型： 休閒",
	"GenreLight": "類型： 輕音樂",
	"GenreList": "類型清單",
	"GenreMor": "類型：輕鬆音樂",
	"GenreName": "類型：{genreName}",
	"GenreNational": "類型： 民族音樂",
	"GenreNews": "類型： 新聞",
	"GenreOldies": "類型： 經典老歌",
	"GenreOther": "類型： 其他",
	"GenrePhoneIn": "類型： 烽煙節目",
	"GenrePop": "類型： 流行音樂",
	"GenreReligion": "類型： 宗教",
	"GenreRock": "類型： 搖滾樂",
	"GenreScience": "類型： 科學",
	"GenreSeek": "類型搜索",
	"GenreSocial": "類型：社會",
	"GenreSport": "類型： 體育",
	"GenreTravel": "類型： 旅行",
	"GenreVaried": "類型： 不同的",
	"GenreWeather": "類型： 天氣",
	"HDRadio": "高清無線電",
	"HDStations": "高清電臺",
	"Info": "資訊",
	"IpodError": "iPod錯誤",
	"IpodFull": "iPod已滿",
	"Jazz": "爵士樂",
	"Leisure": "休閒",
	"Light": "輕音樂",
	"MemoryFull": "記憶體已滿",
	"Mor": "輕鬆音樂",
	"National": "民族音樂",
	"News": "新聞",
	"Noresultsfound": "沒有找到結果",
	"Oldies": "經典老歌",
	"Other": "其他",
	"PartialTransfer": "部分轉移",
	"PhoneIn": "電話點播",
	"Pop": "流行樂",
	"RegionLock": "地區鎖",
	"Religion": "宗教",
	"Remaining": "剩餘{numberOfTags}",
	"Remove": "移除",
	"Rock": "搖滾樂",
	"Science": "科學",
	"SignalLost": "失去訊號",
	"Social": "社會",
	"Sport": "體育",
	"StationList": "電台列表",
	"TAOff": "TA關閉",
	"TagAlreadySaved": "標籤已儲存",
	"TagCaptured": "標籤已捕獲",
	"TagMemoryFull": "標籤記憶體已滿",
	"TagNotYetProcessed": "標籤尚未處理",
	"TagSaved": "標籤已儲存",
	"TagSavedtoIpod": "標籤被儲存到iPod",
	"TagSavedtoSystem": "標籤被儲存到系統",
	"TagTransferredtoiPod": "標籤被轉移到iPod",
	"TagsCannotBeSaved": "無法儲存標籤",
	"Tooltip_IcnUmpFMSettings": "FM 設置",
	"TrafficAlert": "交通警告(TA)",
	"TrafficAlertOff": "關閉交通警告(TA)",
	"TrafficAlertOn": "開啟交通警告(TA)",
	"Travel": "旅行",
	"UnplugAndReconnect": "拔掉並重新連接",
	"UpdateStationList": "更新電台列表",
	"UpdatingStationList": "正在更新電台列表",
	"Varied": "不同的",
	"VrHelp_AutoMemory_Help1_Left1": "（頻率）",
	"VrHelp_AutoMemory_Help1_Left2": "更新列表",
	"VrHelp_AutoMemory_Help2_Left1": "更新電台列表",
	"VrHelp_GenreSeek_Help_Left1": "向上搜索",
	"VrHelp_GenreSeek_Help_Left2": "向下搜索",
	"VrHelp_GenreSeek_Help_Left3": "更改流派",
	"VrHelp_NowPlayingEU_Help_Left1": "娛樂",
	"VrHelp_NowPlayingEU_Help_Left2": "電台列表",
	"VrHelp_NowPlayingEU_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingEU_Help_Left4": "交通警告(TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "掃描",
	"VrHelp_NowPlayingEU_Help_Right1": "調台",
	"VrHelp_NowPlayingEU_Help_Right2": "搜索上一個",
	"VrHelp_NowPlayingEU_Help_Right3": "搜索下一個",
	"VrHelp_NowPlayingEU_Help_Right4": "FM設置",
	"VrHelp_NowPlayingEU_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingNA_Help_Left1": "娛樂",
	"VrHelp_NowPlayingNA_Help_Left2": "自動記憶",
	"VrHelp_NowPlayingNA_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingNA_Help_Left4": "HD菜單",
	"VrHelp_NowPlayingNA_Help_Left5": "掃描",
	"VrHelp_NowPlayingNA_Help_Right1": "調台",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes 標記",
	"VrHelp_NowPlayingNA_Help_Right3": "搜索上一個",
	"VrHelp_NowPlayingNA_Help_Right4": "搜索下一個",
	"VrHelp_NowPlayingNA_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingOther_Help_Left1": "娛樂",
	"VrHelp_NowPlayingOther_Help_Left2": "自動記憶",
	"VrHelp_NowPlayingOther_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingOther_Help_Left4": "掃描",
	"VrHelp_NowPlayingOther_Help_Left5": "調台",
	"VrHelp_NowPlayingOther_Help_Right1": "搜索上一個",
	"VrHelp_NowPlayingOther_Help_Right2": "搜索下一個",
	"VrHelp_NowPlayingOther_Help_Right3": "聲音設置",
	"VrHelp_Settings_Help_Left1": "打開替代頻率",
	"VrHelp_Settings_Help_Left2": "關閉替代頻率",
	"VrHelp_Settings_Help_Left3": "打開地區鎖",
	"VrHelp_Settings_Help_Left4": "關閉地區鎖",
	"VrHelp_Tune_NA_Help_Left1": "（頻率）",
	"VrHelp_Tune_NA_Help_Left2": "向上調台",
	"VrHelp_Tune_NA_Help_Left3": "向下調台",
	"VrHelp_Tune_nonNA_Help_Left1": "（頻率）",
	"VrHelp_Tune_nonNA_Help_Left2": "向上調台",
	"VrHelp_Tune_nonNA_Help_Left3": "向下調台",
	"Weather": "天氣",
	"favorites_Tooltip": "收藏夾",
	"hdChannels_Tooltip": "高清頻道",
	"rbds_Adult": "成人流行單曲",
	"rbds_Class": "經典搖滾",
	"rbds_Classical": "古典音樂",
	"rbds_College": "學院",
	"rbds_Country": "鄉村",
	"rbds_Emergency": "警示！警示！",
	"rbds_EmergencyTest": "應急測試",
	"rbds_Foreign": "外語",
	"rbds_Hablar": "談話（西班牙語）",
	"rbds_HipHop": "嘻哈",
	"rbds_Info": "資訊",
	"rbds_Jazz": "爵士樂",
	"rbds_Musica": "音樂（西班牙語）",
	"rbds_News": "新聞",
	"rbds_None": "無",
	"rbds_Nostalgia": "懷舊音樂",
	"rbds_Oldies": "經典老歌",
	"rbds_Personality": "人物",
	"rbds_Public": "大眾",
	"rbds_ReligousM": "宗教音樂",
	"rbds_ReligousT": "宗教談話",
	"rbds_Rhythym": "節奏藍調",
	"rbds_Rock": "搖滾",
	"rbds_Soft": "輕音樂",
	"rbds_SoftRB": "輕柔 R＆B",
	"rbds_SoftRock": "輕柔搖滾",
	"rbds_Sports": "體育",
	"rbds_Talk": "談話",
	"rbds_Top40": "前 40 名榜單",
	"rbds_Weather": "天氣",
	"rbds_genre_Adult": "類型：成人流行單曲",
	"rbds_genre_Class": "類型：經典搖滾",
	"rbds_genre_Classical": "類型：古典音樂",
	"rbds_genre_College": "類型：學院",
	"rbds_genre_Country": "類型：鄉村音樂",
	"rbds_genre_Emergency": "類型：警示！警示！",
	"rbds_genre_EmergencyTest": "類型：應急測試",
	"rbds_genre_Foreign": "類型：外語",
	"rbds_genre_Hablar": "類型：談話（西班牙語）",
	"rbds_genre_HipHop": "類型：嘻哈",
	"rbds_genre_Info": "類型：信息",
	"rbds_genre_Jazz": "類型：爵士樂",
	"rbds_genre_Musica": "類型：音樂（西班牙語）",
	"rbds_genre_News": "類型：新聞",
	"rbds_genre_None": "類型： 無",
	"rbds_genre_Nostalgia": "類型：懷舊音樂",
	"rbds_genre_Oldies": "類型：經典老歌",
	"rbds_genre_Personality": "類型：人物",
	"rbds_genre_Public": "類型：公眾",
	"rbds_genre_ReligousM": "類型：宗教音樂",
	"rbds_genre_ReligousT": "類型：宗教談話",
	"rbds_genre_Rhythym": "類型：節奏藍調",
	"rbds_genre_Rock": "類型：搖滾樂",
	"rbds_genre_Soft": "類型：輕音樂",
	"rbds_genre_SoftRB": "類型：輕柔 R＆B",
	"rbds_genre_SoftRock": "類型：輕柔搖滾",
	"rbds_genre_Sports": "類型：體育",
	"rbds_genre_Talk": "類型：談話",
	"rbds_genre_Top40": "類型：前 40 名榜單",
	"rbds_genre_Weather": "類型：天気",
};

framework.registerAppDictLoaded("fmradio", "zh_TW");