var Localization_fmradioAppDict_pl_PL = {
	//"stringId" : "localString"
	"Affairs": "Wydarzenia",
	"Alarm": "Alarm",
	"AlarmTest": "Test alarmu",
	"AllMemoryFull": "Pamięć pełna",
	"AllStations": "Wszystkie stacje",
	"AllTagsTransferred": "Wszystkie znaczn. przesł.",
	"AlternativeFrequency": "Wł. / wył. trybu AF",
	"AutoMemoryList": "Lista automatycznej pamięci",
	"CannotTransferTags": "Nieprzesł. Znaczników",
	"ChangeGenre": "Zmień gatunek",
	"Childrens": "Dla dzieci",
	"Classics": "Klasyczne",
	"Close": "Zam.",
	"ConnectIPod": "Podł. iPod by przesł. znacz.",
	"Country": "Country",
	"Culture": "Kultura",
	"Documentary": "Dokumentalne",
	"Drama": "Fabuła",
	"Education": "Edukacja",
	"ErrorConnection": "Błąd przesył. do iPoda",
	"FMRadio": "Radio FM",
	"FMSettings": "Ustawienia FM",
	"Finance": "Finanse",
	"Folk": "Folk",
	"GenreAffairs": "Gatunek: wydarzenia",
	"GenreAlarm": "gatunek: alarm",
	"GenreAlarmTest": "Gatunek: test alarmu",
	"GenreAllStations": "Rodzaje muzyki: Wszystkie stacje",
	"GenreChildrens": "Gatunek: dla dzieci",
	"GenreClassics": "Gatunek: klasyczne",
	"GenreCountry": "Gatunek: country",
	"GenreCulture": "Gatunek: kultura",
	"GenreDocumentary": "Gatunek: dokument",
	"GenreDrama": "Gatunek: fabuła",
	"GenreEducation": "Gatunek: edukacja",
	"GenreFinance": "Gatunek: finanse",
	"GenreFolk": "Gatunek: folk",
	"GenreInfo": "Gatunek: Informacje",
	"GenreJazz": "Gatunek: jazz",
	"GenreLeisure": "Gatunek: czas wolny",
	"GenreLight": "Gatunek: lekkie",
	"GenreList": "Lista gatunków",
	"GenreMor": "Gatunek: Lekka muzyka",
	"GenreName": "Gatunek: {genreName}",
	"GenreNational": "Gatunek: muzyka narodowa",
	"GenreNews": "Gatunek: wiadomości",
	"GenreOldies": "Gatunek: stare przeboje",
	"GenreOther": "Gatunek: inne",
	"GenrePhoneIn": "Gatunek: z udziałem słuchaczy",
	"GenrePop": "Gatunek: pop",
	"GenreReligion": "Gatunek: religia",
	"GenreRock": "Gatunek: rock",
	"GenreScience": "Gatunek: nauka",
	"GenreSeek": "Wyszukiwanie gatunku",
	"GenreSocial": "gatunek: społeczne",
	"GenreSport": "Gatunek: sport",
	"GenreTravel": "Gatunek: podróże",
	"GenreVaried": "Gatunek: różne",
	"GenreWeather": "Gatunek: pogoda",
	"HDRadio": "Radio HD",
	"HDStations": "Stacje HD",
	"Info": "Informacje",
	"IpodError": "Błąd tabletu iPod.",
	"IpodFull": "Pamięć tabletu iPod pełna",
	"Jazz": "Jazz",
	"Leisure": "Czas wolny",
	"Light": "Lekkie",
	"MemoryFull": "Pamięć pełna",
	"Mor": "Lekka muzyka",
	"National": "Muzyka narodowa",
	"News": "Wiadomości",
	"Noresultsfound": "Nie znaleziono wyników.",
	"Oldies": "Klasyczne przeboje",
	"Other": "Inne",
	"PartialTransfer": "Częściowo przesłane",
	"PhoneIn": "Nadchodzące połączenie",
	"Pop": "Pop",
	"RegionLock": "Wł. / wył. trybu REG",
	"Religion": "Religia",
	"Remaining": "{numberOfTags} pozostałych",
	"Remove": "Usuń",
	"Rock": "Rock",
	"Science": "Nauka",
	"SignalLost": "Sygnał utracony",
	"Social": "Społeczne",
	"Sport": "Sport",
	"StationList": "Lista stacji",
	"TAOff": "TA wył.",
	"TagAlreadySaved": "Znacznik już zapisany.",
	"TagCaptured": "Znacznik uchwycony",
	"TagMemoryFull": "Pamięć znaczników pełna",
	"TagNotYetProcessed": "Znacznik nieprzetw.",
	"TagSaved": "Znacznik zapisany",
	"TagSavedtoIpod": "Znacznik zapisany w iPod",
	"TagSavedtoSystem": "Znacznik zapisany w syst.",
	"TagTransferredtoiPod": "Znacznik przesł. do iPoda.",
	"TagsCannotBeSaved": "Niezapis. znaczniki.",
	"Tooltip_IcnUmpFMSettings": "Ustawienia FM",
	"TrafficAlert": "Komunikat drogowy",
	"TrafficAlertOff": "Wyłącz komunikat drogowy",
	"TrafficAlertOn": "Włącz komunikat drogowy",
	"Travel": "Podróże",
	"UnplugAndReconnect": "Odłącz i połącz ponownie",
	"UpdateStationList": "Uaktualnij listę stacji",
	"UpdatingStationList": "Aktualizowanie listy stacji",
	"Varied": "Różne",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorite",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorite",
	"VrHelp_NowPlayingNA_Help_Left4": "HD On / Off",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorite",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Pogoda",
	"favorites_Tooltip": "Ulubione",
	"hdChannels_Tooltip": "Kanały HD",
	"rbds_Adult": "Hity dla dorosłych",
	"rbds_Class": "Klasyczny rock",
	"rbds_Classical": "Klasyczna",
	"rbds_College": "Studenckie",
	"rbds_Country": "Country",
	"rbds_Emergency": "Uwaga, uwaga!",
	"rbds_EmergencyTest": "Test bezpieczeństwa",
	"rbds_Foreign": "W języku obcym",
	"rbds_Hablar": "Rozmowy po hiszpańsku",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Informacje",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Hiszpańska muzyka",
	"rbds_News": "Wiadomości",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgiczna",
	"rbds_Oldies": "Klasyczne przeboje",
	"rbds_Personality": "Osobowości",
	"rbds_Public": "Publiczne",
	"rbds_ReligousM": "Muzyka religijna",
	"rbds_ReligousT": "Dyskusje religijne",
	"rbds_Rhythym": "R'n'B",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Soft",
	"rbds_SoftRB": "Soft R'n'B",
	"rbds_SoftRock": "Soft rock",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Dyskusje",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Pogoda",
	"rbds_genre_Adult": "Gatunek: Hity dla dorosłych",
	"rbds_genre_Class": "Gatunek: Klasyczny rock",
	"rbds_genre_Classical": "Gatunek: Klasyczna",
	"rbds_genre_College": "Gatunek: Studenckie",
	"rbds_genre_Country": "Gatunek: Country",
	"rbds_genre_Emergency": "Gatunek: Uwaga, uwaga!",
	"rbds_genre_EmergencyTest": "Gatunek: Test bezpieczeńst.",
	"rbds_genre_Foreign": "Gatunek: W języku obcym",
	"rbds_genre_Hablar": "Gatunek: Rozmowy po hiszp.",
	"rbds_genre_HipHop": "Gatunek: Hip Hop",
	"rbds_genre_Info": "Gatunek: Informacje",
	"rbds_genre_Jazz": "Gatunek: Jazz",
	"rbds_genre_Musica": "Gatunek: Hiszpańska muzyka",
	"rbds_genre_News": "Gatunek: Wiadomości",
	"rbds_genre_None": "Gatunek: --",
	"rbds_genre_Nostalgia": "Gatunek: Nostalgiczna",
	"rbds_genre_Oldies": "Gatunek: Klasyczne przeboje",
	"rbds_genre_Personality": "Gatunek: Osobowości",
	"rbds_genre_Public": "Gatunek: Publiczne",
	"rbds_genre_ReligousM": "Gatunek: Muzyka religijna",
	"rbds_genre_ReligousT": "Gatunek: Dyskusje religijne",
	"rbds_genre_Rhythym": "Gatunek: R'n'B",
	"rbds_genre_Rock": "Gatunek: Rock",
	"rbds_genre_Soft": "Gatunek: Soft",
	"rbds_genre_SoftRB": "Gatunek: Soft R'n'B",
	"rbds_genre_SoftRock": "Gatunek: Soft rock",
	"rbds_genre_Sports": "Gatunek: Sport",
	"rbds_genre_Talk": "Gatunek: Dyskusje",
	"rbds_genre_Top40": "Gatunek: Top 40",
	"rbds_genre_Weather": "Gatunek: Pogoda",
};

framework.registerAppDictLoaded("fmradio", "pl_PL");