var Localization_fmradioAppDict_en_UK = {
	//"stringId" : "localString"
	"Affairs": "Affairs",
	"Alarm": "Alarm",
	"AlarmTest": "Alarm Test",
	"AllMemoryFull": "All Memory Full",
	"AllStations": "All Stations",
	"AllTagsTransferred": "All Tags Transferred",
	"AlternativeFrequency": "Alternative Frequency",
	"AutoMemoryList": "Auto Memory List",
	"CannotTransferTags": "Cannot Transfer Tags",
	"ChangeGenre": "Change Genre",
	"Childrens": "Children",
	"Classics": "Classics",
	"Close": "Close",
	"ConnectIPod": "Connect iPod to Transfer",
	"Country": "Country",
	"Culture": "Culture",
	"Documentary": "Document",
	"Drama": "Drama",
	"Education": "Educate",
	"ErrorConnection": "Error While Transferring",
	"FMRadio": "FM Radio",
	"FMSettings": "FM Settings",
	"Finance": "Finance",
	"Folk": "Folk M",
	"GenreAffairs": "Genre: Affairs",
	"GenreAlarm": "Genre: Alarm",
	"GenreAlarmTest": "Genre: Alarm Test",
	"GenreAllStations": "Genre: All Stations",
	"GenreChildrens": "Genre: Children",
	"GenreClassics": "Genre: Classics",
	"GenreCountry": "Genre: Country",
	"GenreCulture": "Genre: Culture",
	"GenreDocumentary": "Genre: Document",
	"GenreDrama": "Genre: Drama",
	"GenreEducation": "Genre: Educate",
	"GenreFinance": "Genre: Finance",
	"GenreFolk": "Genre: Folk M",
	"GenreInfo": "Genre: Info",
	"GenreJazz": "Genre: Jazz",
	"GenreLeisure": "Genre: Leisure",
	"GenreLight": "Genre: Light M",
	"GenreList": "Genre List",
	"GenreMor": "Genre: Easy M",
	"GenreName": "Genre: {genreName}",
	"GenreNational": "Genre: Nation M",
	"GenreNews": "Genre: News",
	"GenreOldies": "Genre: Oldies",
	"GenreOther": "Genre: Other M",
	"GenrePhoneIn": "Genre: Phone In",
	"GenrePop": "Genre: Pop M",
	"GenreReligion": "Genre: Religion",
	"GenreRock": "Genre: Rock M",
	"GenreScience": "Genre: Science",
	"GenreSeek": "Genre Seek",
	"GenreSocial": "Genre: Social",
	"GenreSport": "Genre: Sport",
	"GenreTravel": "Genre: Travel",
	"GenreVaried": "Genre: Varied",
	"GenreWeather": "Genre: Weather",
	"HDRadio": "HD Radio",
	"HDStations": "HD Stations",
	"Info": "Info",
	"IpodError": "iPod Error",
	"IpodFull": "iPod Full",
	"Jazz": "Jazz",
	"Leisure": "Leisure",
	"Light": "Light M",
	"MemoryFull": "Memory Full",
	"Mor": "Easy M",
	"National": "Nation M",
	"News": "News",
	"Noresultsfound": "No Results Found",
	"Oldies": "Oldies",
	"Other": "Other M",
	"PartialTransfer": "Partial Transfer",
	"PhoneIn": "Phone In",
	"Pop": "Pop M",
	"RegionLock": "Region Lock",
	"Religion": "Religion",
	"Remaining": "{numberOfTags} Remaining",
	"Remove": "Remove",
	"Rock": "Rock M",
	"Science": "Science",
	"SignalLost": "Signal Lost",
	"Social": "Social",
	"Sport": "Sport",
	"StationList": "Station List",
	"TAOff": "TA Off",
	"TagAlreadySaved": "Tag Already Saved",
	"TagCaptured": "Tag Captured",
	"TagMemoryFull": "Tag Memory Full",
	"TagNotYetProcessed": "Tag Not Yet Processed",
	"TagSaved": "Tag Saved",
	"TagSavedtoIpod": "Tag Saved to iPod",
	"TagSavedtoSystem": "Tag Saved to System",
	"TagTransferredtoiPod": "Tag Transferred to iPod",
	"TagsCannotBeSaved": "Tags Cannot be Saved",
	"Tooltip_IcnUmpFMSettings": "FM Settings",
	"TrafficAlert": "Traffic Announcement  (TA)",
	"TrafficAlertOff": "Traffic Announcement  (TA) Off",
	"TrafficAlertOn": "Traffic Announcement  (TA) On",
	"Travel": "Travel",
	"UnplugAndReconnect": "Unplug and Reconnect",
	"UpdateStationList": "Update Station List",
	"UpdatingStationList": "Updating Station List",
	"Varied": "Varied",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favourites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favourites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favourites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Weather",
	"favorites_Tooltip": "Favourites",
	"hdChannels_Tooltip": "HD Channels",
	"rbds_Adult": "Adult Hits",
	"rbds_Class": "Classic Rock",
	"rbds_Classical": "Classical",
	"rbds_College": "College",
	"rbds_Country": "Country",
	"rbds_Emergency": "Alert! Alert!",
	"rbds_EmergencyTest": "Emergency Test",
	"rbds_Foreign": "Foreign Language",
	"rbds_Hablar": "Hablar Español",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Information",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Música Español",
	"rbds_News": "News",
	"rbds_None": "None",
	"rbds_Nostalgia": "Nostalgia",
	"rbds_Oldies": "Oldies",
	"rbds_Personality": "Personality",
	"rbds_Public": "Public",
	"rbds_ReligousM": "Religious Music",
	"rbds_ReligousT": "Religious Talk",
	"rbds_Rhythym": "Rhythm and Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Soft",
	"rbds_SoftRB": "Soft R&B",
	"rbds_SoftRock": "Soft Rock",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Talk",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Weather",
	"rbds_genre_Adult": "Genre: Adult Hits",
	"rbds_genre_Class": "Genre: Classic Rock",
	"rbds_genre_Classical": "Genre: Classical",
	"rbds_genre_College": "Genre: Música Español",
	"rbds_genre_Country": "Genre: Country",
	"rbds_genre_Emergency": "Genre: Alert! Alert!",
	"rbds_genre_EmergencyTest": "Genre: Emergency Test",
	"rbds_genre_Foreign": "Genre: Foreign Language",
	"rbds_genre_Hablar": "Genre: Hablar Español",
	"rbds_genre_HipHop": "Genre: Hip Hop",
	"rbds_genre_Info": "Genre: Information",
	"rbds_genre_Jazz": "Genre: Jazz",
	"rbds_genre_Musica": "Genre: Música Español",
	"rbds_genre_News": "Genre: News",
	"rbds_genre_None": "Genre: None",
	"rbds_genre_Nostalgia": "Genre: Nostalgia",
	"rbds_genre_Oldies": "Genre: Oldies",
	"rbds_genre_Personality": "Genre: Personality",
	"rbds_genre_Public": "Genre: Public",
	"rbds_genre_ReligousM": "Genre: Religious Music",
	"rbds_genre_ReligousT": "Genre: Religious Talk",
	"rbds_genre_Rhythym": "Genre: Rhythm and Blues",
	"rbds_genre_Rock": "Genre: Rock",
	"rbds_genre_Soft": "Genre: Soft",
	"rbds_genre_SoftRB": "Genre: Soft R&B",
	"rbds_genre_SoftRock": "Genre: Soft Rock",
	"rbds_genre_Sports": "Genre: Sports",
	"rbds_genre_Talk": "Genre: Talk",
	"rbds_genre_Top40": "Genre: Top 40",
	"rbds_genre_Weather": "Genre: Weather",
};

framework.registerAppDictLoaded("fmradio", "en_UK");