var Localization_fmradioAppDict_hr_HR = {
	//"stringId" : "localString"
	"Affairs": "Poslovi",
	"Alarm": "Alarm",
	"AlarmTest": "Test alarma",
	"AllMemoryFull": "Memorija je puna",
	"AllStations": "Sve stanice",
	"AllTagsTransferred": "Sve oznake prenesene",
	"AlternativeFrequency": "Alternativna frekvencija",
	"AutoMemoryList": "Popis automatske memorije",
	"CannotTransferTags": "Oznake nemoguće prenijeti",
	"ChangeGenre": "Promijeni žanr",
	"Childrens": "Djeca",
	"Classics": "Klasika",
	"Close": "Zatv.",
	"ConnectIPod": "Poveži iPod na ozn. prijen.",
	"Country": "Država",
	"Culture": "Kultura",
	"Documentary": "Dokumentarni",
	"Drama": "Drama",
	"Education": "Obrazovanje",
	"ErrorConnection": "Pogr. pri prij. ozn. na iPod",
	"FMRadio": "FM radio",
	"FMSettings": "FM postavke",
	"Finance": "Financije",
	"Folk": "Narodna glazba",
	"GenreAffairs": "Žanr: poslovi",
	"GenreAlarm": "Žanr: alarm",
	"GenreAlarmTest": "Žanr: test alarma",
	"GenreAllStations": "Žanr: sve postaje",
	"GenreChildrens": "Žanr: djeca",
	"GenreClassics": "Žanr: klasika",
	"GenreCountry": "Žanr: country",
	"GenreCulture": "Žanr: kultura",
	"GenreDocumentary": "Žanr: dokumentarni",
	"GenreDrama": "Žanr: drama",
	"GenreEducation": "Žanr: obrazovanje",
	"GenreFinance": "Žanr: financije",
	"GenreFolk": "Žanr: narodna glazba",
	"GenreInfo": "Žanr: Informacije",
	"GenreJazz": "Žanr: jazz",
	"GenreLeisure": "Žanr: slobodno vrijeme",
	"GenreLight": "Žanr: lagano",
	"GenreList": "Popis žanrova",
	"GenreMor": "Žanr: Ugodno slušanje",
	"GenreName": "Žanr: {genreName}",
	"GenreNational": "Žanr: nacionalno",
	"GenreNews": "Žanr: vijesti",
	"GenreOldies": "Žanr: stari hitovi",
	"GenreOther": "Žanr: ostalo",
	"GenrePhoneIn": "Žanr: ulaz telefona",
	"GenrePop": "Žanr: pop",
	"GenreReligion": "Žanr: religijski",
	"GenreRock": "Žanr: rock",
	"GenreScience": "Žanr: znanost",
	"GenreSeek": "Traženje žanra",
	"GenreSocial": "Žanr: društveni",
	"GenreSport": "Žanr: sport",
	"GenreTravel": "Žanr: putovanja",
	"GenreVaried": "Žanr: raznoliko",
	"GenreWeather": "Žanr: vrijeme",
	"HDRadio": "HD radio",
	"HDStations": "HD stanice",
	"Info": "Informacije",
	"IpodError": "Pogreška iPoda",
	"IpodFull": "iPod pun",
	"Jazz": "Jazz",
	"Leisure": "Slobodno vrijeme",
	"Light": "Lagano",
	"MemoryFull": "Puna memorija",
	"Mor": "Ugodno slušanje",
	"National": "Nacionalno",
	"News": "Vijesti",
	"Noresultsfound": "Nisu pronađeni rezultati",
	"Oldies": "Stari hitovi",
	"Other": "Drugi",
	"PartialTransfer": "Djelimični prijenos",
	"PhoneIn": "Nazovite",
	"Pop": "Pop",
	"RegionLock": "Regionalna blokada",
	"Religion": "Religijski",
	"Remaining": "Preostalo {numberOfTags}",
	"Remove": "Ukloni",
	"Rock": "Rock",
	"Science": "Znanost",
	"SignalLost": "Signal izgubljen",
	"Social": "Društveni",
	"Sport": "Sport",
	"StationList": "Popis postaja",
	"TAOff": "TA isključen",
	"TagAlreadySaved": " Oznaka je već spremljena ",
	"TagCaptured": "Oznaka snimlj.",
	"TagMemoryFull": "Memorija oznakaa puna",
	"TagNotYetProcessed": "Oznaka još nije obrađena",
	"TagSaved": "Oznaka spremljena",
	"TagSavedtoIpod": "Oznaka spremljena u iPod",
	"TagSavedtoSystem": "Oznaka spremljena u sust.",
	"TagTransferredtoiPod": "Oznaka prenesena u iPod",
	"TagsCannotBeSaved": "Ozn. nije moguće spremiti",
	"Tooltip_IcnUmpFMSettings": "FM postavke",
	"TrafficAlert": "Prometna objava (TA)",
	"TrafficAlertOff": "Prometna objava (TA) isklj",
	"TrafficAlertOn": "Prometna objava (TA) uklj",
	"Travel": "Putovanje",
	"UnplugAndReconnect": "Isključi i ponovno poveži",
	"UpdateStationList": "Ažuriraj popis postaja ",
	"UpdatingStationList": "Ažuriranje popisa postaja ",
	"Varied": "Raznoliko",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Vrijeme",
	"favorites_Tooltip": "Favoriti",
	"hdChannels_Tooltip": "HD kanali",
	"rbds_Adult": "Odrasle Posjeta",
	"rbds_Class": "Klasični Rock",
	"rbds_Classical": "Klasika",
	"rbds_College": "Koledž",
	"rbds_Country": "Država",
	"rbds_Emergency": "Uzbuna! Uzbuna!",
	"rbds_EmergencyTest": "Hitna Test",
	"rbds_Foreign": "Strani Jezik",
	"rbds_Hablar": "Govoreći Španjolski",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Informacije",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Španjolski Glazba",
	"rbds_News": "Vijesti",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgija",
	"rbds_Oldies": "Stari hitovi",
	"rbds_Personality": "Ličnost",
	"rbds_Public": "Javni",
	"rbds_ReligousM": "Vjerska Glazba",
	"rbds_ReligousT": "Vjerski Razgovor",
	"rbds_Rhythym": "Ritam i Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Mekan",
	"rbds_SoftRB": "Mekan R&B",
	"rbds_SoftRock": "Soft Rock",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Govoriti",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Vrijeme",
	"rbds_genre_Adult": "Žanr: Odrasle Posjeta",
	"rbds_genre_Class": "Žanr: Klasični Rock",
	"rbds_genre_Classical": "Žanr: Klasika",
	"rbds_genre_College": "Žanr: Koledž",
	"rbds_genre_Country": "Žanr: Država",
	"rbds_genre_Emergency": "Žanr: Uzbuna! Uzbuna!",
	"rbds_genre_EmergencyTest": "Žanr: Hitna Test",
	"rbds_genre_Foreign": "Žanr: Strani Jezik",
	"rbds_genre_Hablar": "Žanr: Govoreći Španjolski",
	"rbds_genre_HipHop": "Žanr: Hip Hop",
	"rbds_genre_Info": "Žanr: Informacije",
	"rbds_genre_Jazz": "Žanr: Country",
	"rbds_genre_Musica": "Žanr: Španjolski Glazba",
	"rbds_genre_News": "Žanr: Vijesti",
	"rbds_genre_None": "Žanr: --",
	"rbds_genre_Nostalgia": "Žanr: Nostalgija",
	"rbds_genre_Oldies": "Žanr: Stari hitovi",
	"rbds_genre_Personality": "Žanr: Ličnost",
	"rbds_genre_Public": "Žanr: Javni",
	"rbds_genre_ReligousM": "Žanr: Vjerska Glazba",
	"rbds_genre_ReligousT": "Žanr: Vjerski Razgovor",
	"rbds_genre_Rhythym": "Žanr: Ritam i Blues",
	"rbds_genre_Rock": "Žanr: Rock",
	"rbds_genre_Soft": "Žanr: Mekan",
	"rbds_genre_SoftRB": "Žanr: Mekan R&B",
	"rbds_genre_SoftRock": "Žanr: Soft Rock",
	"rbds_genre_Sports": "Žanr: Sports",
	"rbds_genre_Talk": "Žanr: Govoriti",
	"rbds_genre_Top40": "Žanr: Top 40",
	"rbds_genre_Weather": "Žanr: Vrijeme",
};

framework.registerAppDictLoaded("fmradio", "hr_HR");