var Localization_fmradioAppDict_bg_BG = {
	//"stringId" : "localString"
	"Affairs": "Актуално",
	"Alarm": "Аларма",
	"AlarmTest": "Тест на алармата",
	"AllMemoryFull": "Цялата памет е пълна",
	"AllStations": "Всички станции",
	"AllTagsTransferred": "Вс. таг. са прехв.",
	"AlternativeFrequency": "Алтернативна честота",
	"AutoMemoryList": "Списък с авт. запаметени",
	"CannotTransferTags": "Таг-те не се прехв.",
	"ChangeGenre": "Промяна на жанра",
	"Childrens": "Детски",
	"Classics": "Класика",
	"Close": "Затв.",
	"ConnectIPod": "Свър. iPod за прехв. таг.",
	"Country": "Страна",
	"Culture": "Култура",
	"Documentary": "Документален",
	"Drama": "Драма",
	"Education": "Образование",
	"ErrorConnection": "Грешка прехв. таг. в iPod",
	"FMRadio": "Радио FM",
	"FMSettings": "Настройки за FM",
	"Finance": "Финанси",
	"Folk": "Фолк",
	"GenreAffairs": "Жанр: актуално",
	"GenreAlarm": "Жанр: аларма",
	"GenreAlarmTest": "Жанр: тест на алармата",
	"GenreAllStations": "Жанр: всички станции",
	"GenreChildrens": "Жанр: детски",
	"GenreClassics": "Жанр: класика",
	"GenreCountry": "Жанр: страна",
	"GenreCulture": "Жанр: култура",
	"GenreDocumentary": "Жанр: документален",
	"GenreDrama": "Жанр: драма",
	"GenreEducation": "Жанр: образование",
	"GenreFinance": "Жанр: финанси",
	"GenreFolk": "Жанр: фолк",
	"GenreInfo": "Жанр: информация",
	"GenreJazz": "Жанр: джаз",
	"GenreLeisure": "Жанр: отдих",
	"GenreLight": "Жанр: лек",
	"GenreList": "Списък с жанрове",
	"GenreMor": "Жанр: лека музика",
	"GenreName": "Жанр: {genreName}",
	"GenreNational": "Жанр: национални",
	"GenreNews": "Жанр: новини",
	"GenreOldies": "Жанр: ретро",
	"GenreOther": "Жанр: други",
	"GenrePhoneIn": "Жанр: обаждания на слушатели",
	"GenrePop": "Жанр: поп",
	"GenreReligion": "Жанр: религия",
	"GenreRock": "Жанр: рок",
	"GenreScience": "Жанр: наука",
	"GenreSeek": "Търсене на жанр",
	"GenreSocial": "Жанр: социални",
	"GenreSport": "Жанр: спорт",
	"GenreTravel": "Жанр: туризъм",
	"GenreVaried": "Жанр: разни",
	"GenreWeather": "Жанр: времето",
	"HDRadio": "Радио HD",
	"HDStations": "Станции HD",
	"Info": "Информация ",
	"IpodError": "Грешка в iPod",
	"IpodFull": "iPod е пълен",
	"Jazz": "Джаз",
	"Leisure": "Отдих",
	"Light": "Светло",
	"MemoryFull": "Паметта е пълна",
	"Mor": "Лека музика ",
	"National": "Национални",
	"News": "Новини",
	"Noresultsfound": "Няма намерени резултати",
	"Oldies": "Ретро",
	"Other": "Други",
	"PartialTransfer": "Частичен трансфер",
	"PhoneIn": "Обаждания на слушатели",
	"Pop": "Поп",
	"RegionLock": "Заключване по регион",
	"Religion": "Религия",
	"Remaining": "Остават {numberOfTags}",
	"Remove": "Изтриване",
	"Rock": "Рок",
	"Science": "Наука",
	"SignalLost": "Сигналът е изгубен",
	"Social": "Социални",
	"Sport": "Спорт",
	"StationList": "Списък със станции",
	"TAOff": "Изкл. пр. дв.",
	"TagAlreadySaved": "Тагът е вече записан",
	"TagCaptured": "Тагът е снет",
	"TagMemoryFull": "Пълна памет за тагове",
	"TagNotYetProcessed": "Тагът не е обработен",
	"TagSaved": "Тагът е записан",
	"TagSavedtoIpod": "Тагът е записан в iPod",
	"TagSavedtoSystem": "Тагът е записан в сист.",
	"TagTransferredtoiPod": "Тагът прехв. в iPod",
	"TagsCannotBeSaved": "Таг-те не се записв.",
	"Tooltip_IcnUmpFMSettings": "Настройки за FM",
	"TrafficAlert": "Предупр. движение",
	"TrafficAlertOff": "Изключено предупреждение за движението",
	"TrafficAlertOn": "Включено предупреждение за движението",
	"Travel": "Туризъм",
	"UnplugAndReconnect": "Изв. и свър. пак",
	"UpdateStationList": "Акт. спис. станции",
	"UpdatingStationList": "Актуал. спис. станции",
	"Varied": "Разни",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Времето",
	"favorites_Tooltip": "Предпочитани",
	"hdChannels_Tooltip": "Канали HD",
	"rbds_Adult": "Смесени хитове",
	"rbds_Class": "Класически рок",
	"rbds_Classical": "Класическа музика",
	"rbds_College": "Kолеж",
	"rbds_Country": "Страна",
	"rbds_Emergency": "Предупреждение! Предупреждение!",
	"rbds_EmergencyTest": "Авариeн тест",
	"rbds_Foreign": "Чужд език",
	"rbds_Hablar": "Говорейки испански",
	"rbds_HipHop": "Хип хоп",
	"rbds_Info": "Информация",
	"rbds_Jazz": "Джаз",
	"rbds_Musica": "Испански музика",
	"rbds_News": "Новини",
	"rbds_None": "--",
	"rbds_Nostalgia": "Носталгия",
	"rbds_Oldies": "Ретро",
	"rbds_Personality": "Личност",
	"rbds_Public": "Обществено",
	"rbds_ReligousM": "Религиозна музика",
	"rbds_ReligousT": "Религиозни разговори",
	"rbds_Rhythym": "Ритъм и блус",
	"rbds_Rock": "Рок",
	"rbds_Soft": "Софт",
	"rbds_SoftRB": "Софт ритъм и блус",
	"rbds_SoftRock": "Софт рок",
	"rbds_Sports": "Спорт",
	"rbds_Talk": "Ток",
	"rbds_Top40": "Топ 40",
	"rbds_Weather": "Времето",
	"rbds_genre_Adult": "Жанр: Смесени хитове",
	"rbds_genre_Class": "Жанр: Класически рок",
	"rbds_genre_Classical": "Жанр: Класическа музика",
	"rbds_genre_College": "Жанр: Kолеж",
	"rbds_genre_Country": "Жанр: Страна",
	"rbds_genre_Emergency": "Жанр: Предупр.! Предупр.!",
	"rbds_genre_EmergencyTest": "Жанр: Авариeн тест",
	"rbds_genre_Foreign": "Жанр: Чужд език",
	"rbds_genre_Hablar": "Жанр: Говорейки испански",
	"rbds_genre_HipHop": "Жанр: Хип хоп",
	"rbds_genre_Info": "Жанр: Информация",
	"rbds_genre_Jazz": "Жанр: Джаз",
	"rbds_genre_Musica": "Жанр: Испански музика",
	"rbds_genre_News": "Жанр: Новини",
	"rbds_genre_None": "Жанр: --",
	"rbds_genre_Nostalgia": "Жанр: Носталгия",
	"rbds_genre_Oldies": "Жанр: Ретро",
	"rbds_genre_Personality": "Жанр: Личност",
	"rbds_genre_Public": "Жанр: Обществено",
	"rbds_genre_ReligousM": "Жанр: Религиозна музика",
	"rbds_genre_ReligousT": "Жанр: Религиозни разговори",
	"rbds_genre_Rhythym": "Жанр: Ритъм и блус",
	"rbds_genre_Rock": "Жанр: Рок",
	"rbds_genre_Soft": "Жанр: Софт",
	"rbds_genre_SoftRB": "Жанр: Софт ритъм и блус",
	"rbds_genre_SoftRock": "Жанр: Софт рок",
	"rbds_genre_Sports": "Жанр: Спорт",
	"rbds_genre_Talk": "Жанр: Ток",
	"rbds_genre_Top40": "Жанр: Топ 40",
	"rbds_genre_Weather": "Жанр: Времето",
};

framework.registerAppDictLoaded("fmradio", "bg_BG");