var Localization_fmradioAppDict_cn_HK = {
	//"stringId" : "localString"
	"Affairs": "財經",
	"Alarm": "鬧鐘",
	"AlarmTest": "鬧鐘測試",
	"AllMemoryFull": "全部記憶體已滿",
	"AllStations": "所有電台",
	"AllTagsTransferred": "所有標籤均已傳輸",
	"AlternativeFrequency": "備用頻率",
	"AutoMemoryList": "自動存儲清單",
	"CannotTransferTags": "無法傳輸標籤",
	"ChangeGenre": "更改類別",
	"Childrens": "兒童",
	"Classics": "古典",
	"Close": "關閉",
	"ConnectIPod": "連線 iPod 進行傳輸",
	"Country": "鄉村",
	"Culture": "文化",
	"Documentary": "文件",
	"Drama": "戲劇",
	"Education": "教育",
	"ErrorConnection": "傳輸錯誤",
	"FMRadio": "FM 收音機",
	"FMSettings": "FM 設定",
	"Finance": "金融",
	"Folk": "民謠 M",
	"GenreAffairs": "類別： 財經",
	"GenreAlarm": "類別： 鬧鐘",
	"GenreAlarmTest": "類別： 鬧鐘測試",
	"GenreAllStations": "類別： 所有電台",
	"GenreChildrens": "類別： 兒童",
	"GenreClassics": "類別： 古典",
	"GenreCountry": "類別： 鄉村",
	"GenreCulture": "類別： 文化",
	"GenreDocumentary": "類別： 文件",
	"GenreDrama": "類別： 戲劇",
	"GenreEducation": "類別： 教育",
	"GenreFinance": "類別： 金融",
	"GenreFolk": "類別： 民謠 M",
	"GenreInfo": "類別： 資訊",
	"GenreJazz": "類別： 爵士",
	"GenreLeisure": "類別： 休閒",
	"GenreLight": "類別： 輕鬆 M",
	"GenreList": "類別選取",
	"GenreMor": "類別： 舒緩 M",
	"GenreName": "類別： {genreName}",
	"GenreNational": "類別： 國度 M",
	"GenreNews": "類別： 新聞",
	"GenreOldies": "類別： 經典老歌",
	"GenreOther": "類別： 其他 M",
	"GenrePhoneIn": "類別： 電話",
	"GenrePop": "類別： 流行 M",
	"GenreReligion": "類別： 宗教",
	"GenreRock": "類別： 搖滾 M",
	"GenreScience": "類別： 科學",
	"GenreSeek": "類別搜尋",
	"GenreSocial": "類別： 社會",
	"GenreSport": "類別： 體育",
	"GenreTravel": "類別： 旅遊",
	"GenreVaried": "類別： 綜合",
	"GenreWeather": "類別： 天氣",
	"HDRadio": "HD Radio",
	"HDStations": "HD 電臺",
	"Info": "資訊",
	"IpodError": "iPod 錯誤",
	"IpodFull": "iPod 已滿",
	"Jazz": "爵士",
	"Leisure": "休閒",
	"Light": "輕鬆 M",
	"MemoryFull": "記憶體已滿",
	"Mor": "舒緩 M",
	"National": "國度 M",
	"News": "新聞",
	"Noresultsfound": "未發現結果",
	"Oldies": "經典老歌",
	"Other": "其他 M",
	"PartialTransfer": "部分傳輸",
	"PhoneIn": "電話",
	"Pop": "流行 M",
	"RegionLock": "區域鎖",
	"Religion": "宗教",
	"Remaining": "{numberOfTags} 剩餘",
	"Remove": "移除",
	"Rock": "搖滾 M",
	"Science": "科學",
	"SignalLost": "訊號丟失",
	"Social": "社會",
	"Sport": "體育",
	"StationList": "電台清單",
	"TAOff": "TA 關閉",
	"TagAlreadySaved": "標籤已存儲",
	"TagCaptured": "捕捉到標籤",
	"TagMemoryFull": "全部記憶體已滿",
	"TagNotYetProcessed": "標籤尚未處理",
	"TagSaved": "標籤已存儲",
	"TagSavedtoIpod": "標籤已存儲至 iPod",
	"TagSavedtoSystem": "標籤已存儲至系統",
	"TagTransferredtoiPod": "標籤已傳輸至 iPod",
	"TagsCannotBeSaved": "無法存儲標籤",
	"Tooltip_IcnUmpFMSettings": "FM 設定",
	"TrafficAlert": "交通警示(TA)",
	"TrafficAlertOff": "關閉交通警示 (TA)",
	"TrafficAlertOn": "啟動交通警示 (TA)",
	"Travel": "旅遊",
	"UnplugAndReconnect": "拔出並重新連線",
	"UpdateStationList": "更新電台清單",
	"UpdatingStationList": "正在更新電台清單",
	"Varied": "綜合",
	"VrHelp_AutoMemory_Help1_Left1": "(頻率)",
	"VrHelp_AutoMemory_Help1_Left2": "更新列表",
	"VrHelp_AutoMemory_Help2_Left1": "更新電台列表",
	"VrHelp_GenreSeek_Help_Left1": "向上搜索",
	"VrHelp_GenreSeek_Help_Left2": "向下搜索",
	"VrHelp_GenreSeek_Help_Left3": "更改流派",
	"VrHelp_NowPlayingEU_Help_Left1": "娛樂",
	"VrHelp_NowPlayingEU_Help_Left2": "電台列表",
	"VrHelp_NowPlayingEU_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingEU_Help_Left4": "交通警告(TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "掃描",
	"VrHelp_NowPlayingEU_Help_Right1": "調台",
	"VrHelp_NowPlayingEU_Help_Right2": "搜索上一個",
	"VrHelp_NowPlayingEU_Help_Right3": "搜索下一個",
	"VrHelp_NowPlayingEU_Help_Right4": "FM設置",
	"VrHelp_NowPlayingEU_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingNA_Help_Left1": "娛樂",
	"VrHelp_NowPlayingNA_Help_Left2": "自動記憶",
	"VrHelp_NowPlayingNA_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingNA_Help_Left4": "HD菜單",
	"VrHelp_NowPlayingNA_Help_Left5": "掃描",
	"VrHelp_NowPlayingNA_Help_Right1": "調台",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes 標記",
	"VrHelp_NowPlayingNA_Help_Right3": "搜索上一個",
	"VrHelp_NowPlayingNA_Help_Right4": "搜索下一個",
	"VrHelp_NowPlayingNA_Help_Right5": "聲音設置",
	"VrHelp_NowPlayingOther_Help_Left1": "娛樂",
	"VrHelp_NowPlayingOther_Help_Left2": "自動記憶",
	"VrHelp_NowPlayingOther_Help_Left3": "收藏夾",
	"VrHelp_NowPlayingOther_Help_Left4": "掃描",
	"VrHelp_NowPlayingOther_Help_Left5": "調台",
	"VrHelp_NowPlayingOther_Help_Right1": "搜索上一個",
	"VrHelp_NowPlayingOther_Help_Right2": "搜索下一個",
	"VrHelp_NowPlayingOther_Help_Right3": "聲音設置",
	"VrHelp_Settings_Help_Left1": "打開替代頻率",
	"VrHelp_Settings_Help_Left2": "關閉替代頻率",
	"VrHelp_Settings_Help_Left3": "打開地區鎖",
	"VrHelp_Settings_Help_Left4": "關閉地區鎖",
	"VrHelp_Tune_NA_Help_Left1": "(頻率)",
	"VrHelp_Tune_NA_Help_Left2": "向上調台",
	"VrHelp_Tune_NA_Help_Left3": "向下調台",
	"VrHelp_Tune_nonNA_Help_Left1": "(頻率)",
	"VrHelp_Tune_nonNA_Help_Left2": "向上調台",
	"VrHelp_Tune_nonNA_Help_Left3": "向下調台",
	"Weather": "天氣",
	"favorites_Tooltip": "我的最愛",
	"hdChannels_Tooltip": "HD 功能表",
	"rbds_Adult": "成人名曲",
	"rbds_Class": "古典搖滾",
	"rbds_Classical": "古典",
	"rbds_College": "大學",
	"rbds_Country": "鄉村",
	"rbds_Emergency": "警示！ 警示！",
	"rbds_EmergencyTest": "緊急測試",
	"rbds_Foreign": "外語",
	"rbds_Hablar": "Hablar Español",
	"rbds_HipHop": "嘻哈",
	"rbds_Info": "資訊",
	"rbds_Jazz": "爵士",
	"rbds_Musica": "Música Español",
	"rbds_News": "新聞",
	"rbds_None": "無",
	"rbds_Nostalgia": "經典老歌",
	"rbds_Oldies": "經典老歌",
	"rbds_Personality": "性格",
	"rbds_Public": "公眾",
	"rbds_ReligousM": "宗教音樂",
	"rbds_ReligousT": "宗教談話",
	"rbds_Rhythym": "節奏與藍調",
	"rbds_Rock": "搖滾",
	"rbds_Soft": "輕音樂",
	"rbds_SoftRB": "輕說唱",
	"rbds_SoftRock": "輕搖滾",
	"rbds_Sports": "體育",
	"rbds_Talk": "交談",
	"rbds_Top40": "排行榜前 40 首",
	"rbds_Weather": "天氣",
	"rbds_genre_Adult": "類別： 成人名曲",
	"rbds_genre_Class": "類別： 古典搖滾",
	"rbds_genre_Classical": "類別： 古典",
	"rbds_genre_College": "類別： 大學",
	"rbds_genre_Country": "類別： 鄉村",
	"rbds_genre_Emergency": "類別： 警示！ 警示！",
	"rbds_genre_EmergencyTest": "類別： 緊急測試",
	"rbds_genre_Foreign": "類別： 外語",
	"rbds_genre_Hablar": "類別： Hablar Español",
	"rbds_genre_HipHop": "類別： 嘻哈",
	"rbds_genre_Info": "類別： 資訊",
	"rbds_genre_Jazz": "類別： 爵士",
	"rbds_genre_Musica": "類別： Música Español",
	"rbds_genre_News": "類別： 新聞",
	"rbds_genre_None": "類別： 無",
	"rbds_genre_Nostalgia": "類別： 經典老歌",
	"rbds_genre_Oldies": "類別： 經典老歌",
	"rbds_genre_Personality": "類別： 性格",
	"rbds_genre_Public": "類別： 公眾",
	"rbds_genre_ReligousM": "類別： 宗教音樂",
	"rbds_genre_ReligousT": "類別： 宗教談話",
	"rbds_genre_Rhythym": "類別： 節奏與藍調",
	"rbds_genre_Rock": "類別： 搖滾",
	"rbds_genre_Soft": "類別： 輕音樂",
	"rbds_genre_SoftRB": "類別： 輕說唱",
	"rbds_genre_SoftRock": "類別： 輕搖滾",
	"rbds_genre_Sports": "類別： 體育",
	"rbds_genre_Talk": "類別： 交談",
	"rbds_genre_Top40": "類別： 排行榜前 40 首",
	"rbds_genre_Weather": "類別： 天氣",
};

framework.registerAppDictLoaded("fmradio", "cn_HK");