var Localization_fmradioAppDict_et_EE = {
	//"stringId" : "localString"
	"Affairs": "Juhtumid",
	"Alarm": "Alarm",
	"AlarmTest": "Alarmi test",
	"AllMemoryFull": "Kogu mälu on täis",
	"AllStations": "Kõik jaamad",
	"AllTagsTransferred": "Kõik sildid edastatud",
	"AlternativeFrequency": "Teine sagedus",
	"AutoMemoryList": "Automaatse mälu loend",
	"CannotTransferTags": "Silte ei saa edastada",
	"ChangeGenre": "Muuda žanrit",
	"Childrens": "Lastele",
	"Classics": "Klassika",
	"Close": "Sulge",
	"ConnectIPod": "Üh. iPod siltide edastam.",
	"Country": "Riik",
	"Culture": "Kultuur",
	"Documentary": "Dokumentaal",
	"Drama": "Draama",
	"Education": "Haridus",
	"ErrorConnection": "Viga siltide edast. iPodi",
	"FMRadio": "FM raadio",
	"FMSettings": "FM-sätted",
	"Finance": "Rahandus",
	"Folk": "Folk",
	"GenreAffairs": "Žanr:  Juhtumid",
	"GenreAlarm": "Žanr:  Alarm",
	"GenreAlarmTest": "Žanr:  Alarmi test",
	"GenreAllStations": "Žanr:  Kõik jaamad",
	"GenreChildrens": "Žanr:  Lastele",
	"GenreClassics": "Žanr:  Klassika",
	"GenreCountry": "Žanr:  Kantri",
	"GenreCulture": "Žanr:  Kultuur",
	"GenreDocumentary": "Žanr:  Dokumentaal",
	"GenreDrama": "Žanr:  Draama",
	"GenreEducation": "Žanr:  Haridus",
	"GenreFinance": "Žanr:  Rahandus",
	"GenreFolk": "Žanr:  Folk",
	"GenreInfo": "Žanr: Teave",
	"GenreJazz": "Žanr:  Jazz",
	"GenreLeisure": "Žanr:  Vaba aeg",
	"GenreLight": "Žanr:  Kerge",
	"GenreList": "Žanrite loend",
	"GenreMor": "Žanr: Ajaviitemuusika",
	"GenreName": "Žanr: {genreName}",
	"GenreNational": "Žanr:  Riiklik",
	"GenreNews": "Žanr:  Uudised",
	"GenreOldies": "Žanr:  Vanad",
	"GenreOther": "Žanr:  Muu",
	"GenrePhoneIn": "Žanr:  Helistamine",
	"GenrePop": "Žanr:  Popp",
	"GenreReligion": "Žanr:  Religioon",
	"GenreRock": "Žanr:  Rock",
	"GenreScience": "Žanr:  Teadus",
	"GenreSeek": "Žanri otsing",
	"GenreSocial": "Žanr:  Sotsiaalne",
	"GenreSport": "Žanr:  Sport",
	"GenreTravel": "Žanr:  Reisimine",
	"GenreVaried": "Žanr:  Varia",
	"GenreWeather": "Žanr:  Ilm",
	"HDRadio": "HD Radio",
	"HDStations": "HD-jaamad",
	"Info": "Teave",
	"IpodError": "iPodi viga",
	"IpodFull": "iPod täis",
	"Jazz": "Jazz",
	"Leisure": "Vaba aeg",
	"Light": "Kerge",
	"MemoryFull": "Mälu täis",
	"Mor": "Ajaviitemuusika",
	"National": "Riiklik",
	"News": "Uudised",
	"Noresultsfound": "Tulemusi ei leitud",
	"Oldies": "Vanad",
	"Other": "Muu",
	"PartialTransfer": "Sõidu monitor",
	"PhoneIn": "Telefonisisend",
	"Pop": "Popp",
	"RegionLock": "Regiooni lukustus",
	"Religion": "Religioon",
	"Remaining": "{numberOfTags} jäänud",
	"Remove": "Eemalda",
	"Rock": "Rock",
	"Science": "Teadus",
	"SignalLost": "Signaal kadus",
	"Social": "Sotsiaalne",
	"Sport": "Sport",
	"StationList": "Jaamade loend",
	"TAOff": "TA väljas",
	"TagAlreadySaved": "Silt on juba salvestatud",
	"TagCaptured": "Silt jäädvustatud",
	"TagMemoryFull": "Sildi mälu täis",
	"TagNotYetProcessed": "Silti pole veel töödeldud",
	"TagSaved": "Silt on salvestatud",
	"TagSavedtoIpod": "Silt on iPodi salvestatud",
	"TagSavedtoSystem": "Silt on süsteemi salvest.",
	"TagTransferredtoiPod": "Silt on iPodi edastatud",
	"TagsCannotBeSaved": "Silte ei saa salvestada",
	"Tooltip_IcnUmpFMSettings": "FM-sätted",
	"TrafficAlert": "Liiklusteade (TA)  ",
	"TrafficAlertOff": "Liiklusteade (TA) väljas",
	"TrafficAlertOn": "Liiklusteade (TA) sees",
	"Travel": "Reisimine",
	"UnplugAndReconnect": "Lahutage ja ühend. uuesti",
	"UpdateStationList": "Värskenda jaamade loendit",
	"UpdatingStationList": "Jaamade loendi värskendamine",
	"Varied": "Varia",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Ilm",
	"favorites_Tooltip": "Lemmikud",
	"hdChannels_Tooltip": "HD-kanalid",
	"rbds_Adult": "Täiskasvanud Tulemus",
	"rbds_Class": "Klassika Rock",
	"rbds_Classical": "Klassika",
	"rbds_College": "Kolledž",
	"rbds_Country": "Riik",
	"rbds_Emergency": "Häire! Häire!",
	"rbds_EmergencyTest": "Avarii Test",
	"rbds_Foreign": "Võõrkeele",
	"rbds_Hablar": "Rääkimine Hispaania",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Informatsioon",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Hispaania Muusika",
	"rbds_News": "Uudised",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgia",
	"rbds_Oldies": "Vanad",
	"rbds_Personality": "Isikupära",
	"rbds_Public": "Avalik",
	"rbds_ReligousM": "Religioossed Muusika",
	"rbds_ReligousT": "Religioossed Rääkima",
	"rbds_Rhythym": "Rütm ja Sina",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Pehme",
	"rbds_SoftRB": "Pehme R&B",
	"rbds_SoftRock": "Pehme Rock",
	"rbds_Sports": "Sports",
	"rbds_Talk": "Rääkima",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Ilm",
	"rbds_genre_Adult": "Žanr: Täiskasvanud Tulemus",
	"rbds_genre_Class": "Žanr: Klassika Rock",
	"rbds_genre_Classical": "Žanr: Klassika",
	"rbds_genre_College": "Žanr: Kolledž",
	"rbds_genre_Country": "Žanr: Riik",
	"rbds_genre_Emergency": "Žanr: Häire! Häire!",
	"rbds_genre_EmergencyTest": "Žanr: Avarii Test",
	"rbds_genre_Foreign": "Žanr: Võõrkeele",
	"rbds_genre_Hablar": "Žanr: Rääkimine Hispaania",
	"rbds_genre_HipHop": "Žanr: Hip Hop",
	"rbds_genre_Info": "Žanr: Informatsioon",
	"rbds_genre_Jazz": "Žanr: Jazz",
	"rbds_genre_Musica": "Žanr: Hispaania Muusika",
	"rbds_genre_News": "Žanr: Uudised",
	"rbds_genre_None": "Žanr: --",
	"rbds_genre_Nostalgia": "Žanr: Nostalgia",
	"rbds_genre_Oldies": "Žanr: Vanad",
	"rbds_genre_Personality": "Žanr: Isikupära",
	"rbds_genre_Public": "Žanr: Avalik",
	"rbds_genre_ReligousM": "Žanr: Religioossed Muusika",
	"rbds_genre_ReligousT": "Žanr: Religioossed Rääkima",
	"rbds_genre_Rhythym": "Žanr: Rütm ja Sina",
	"rbds_genre_Rock": "Žanr: Rock",
	"rbds_genre_Soft": "Žanr: Pehme",
	"rbds_genre_SoftRB": "Žanr: Pehme R&B",
	"rbds_genre_SoftRock": "Žanr: Pehme Rock",
	"rbds_genre_Sports": "Žanr: Sports",
	"rbds_genre_Talk": "Žanr: Rääkima",
	"rbds_genre_Top40": "Žanr: Top 40",
	"rbds_genre_Weather": "Žanr: Ilm",
};

framework.registerAppDictLoaded("fmradio", "et_EE");