var Localization_fmradioAppDict_ms_MY = {
	//"stringId" : "localString"
	"Affairs": "Hal-ehwal",
	"Alarm": "Penggera",
	"AlarmTest": "Ujian Penggera",
	"AllMemoryFull": "Semua Memori Penuh",
	"AllStations": "Semua Stesen",
	"AllTagsTransferred": "Semua Teg Dipindahkan",
	"AlternativeFrequency": "Frekuensi Alternatif",
	"AutoMemoryList": "Senarai Memori Auto",
	"CannotTransferTags": "Tdk Blh Pindah Tag",
	"ChangeGenre": "Tukar Genre",
	"Childrens": "Kanak-kanak",
	"Classics": "Klasik",
	"Close": "Tutup",
	"ConnectIPod": "Samb. iPod utk Pindah Tag",
	"Country": "Negara",
	"Culture": "Budaya",
	"Documentary": "Dokumentari",
	"Drama": "Drama",
	"Education": "Pendidikan",
	"ErrorConnection": "Ralat Pindah Tag ke iPod",
	"FMRadio": "Radio FM",
	"FMSettings": "Tetapan FM",
	"Finance": "Kewangan",
	"Folk": "Rakyat",
	"GenreAffairs": "Genre: Hal-ehwal",
	"GenreAlarm": "Genre: Penggera",
	"GenreAlarmTest": "Genre: Ujian Penggera",
	"GenreAllStations": "Genre: Semua Stesen",
	"GenreChildrens": "Genre: Kanak-kanak",
	"GenreClassics": "Genre: Klasik",
	"GenreCountry": "Genre: Kedesaan",
	"GenreCulture": "Genre: Budaya",
	"GenreDocumentary": "Genre: Dokumentari",
	"GenreDrama": "Genre: Drama",
	"GenreEducation": "Genre: Pendidikan",
	"GenreFinance": "Genre: Kewangan",
	"GenreFolk": "Genre: Rakyat",
	"GenreInfo": "Genre: Maklumat",
	"GenreJazz": "Genre: Jaz",
	"GenreLeisure": "Genre: Santai",
	"GenreLight": "Genre: Ringan",
	"GenreList": "Senarai Genre",
	"GenreMor": "Genre: Sedap Didengar",
	"GenreName": "Genre: {genreName}",
	"GenreNational": "Genre: Kebangsaan",
	"GenreNews": "Genre: Berita",
	"GenreOldies": "Genre: Lama",
	"GenreOther": "Genre: Lain-lain",
	"GenrePhoneIn": "Genre: Panggil Masuk",
	"GenrePop": "Genre: Pop",
	"GenreReligion": "Genre: Agama",
	"GenreRock": "Genre: Rock",
	"GenreScience": "Genre: Sains",
	"GenreSeek": "Carian Genre",
	"GenreSocial": "Genre: Sosial",
	"GenreSport": "Genre: Sukan",
	"GenreTravel": "Genre: Kembara",
	"GenreVaried": "Genre: Pelbagai",
	"GenreWeather": "Genre: Cuaca",
	"HDRadio": "Radio HD",
	"HDStations": "Stesen HD",
	"Info": "Maklumat",
	"IpodError": "Ralat iPod",
	"IpodFull": "iPod Penuh",
	"Jazz": "Jaz",
	"Leisure": "Santai",
	"Light": "Ringan",
	"MemoryFull": "Memori Penuh",
	"Mor": "Sedap Didengar",
	"National": "Kebangsaan",
	"News": "Berita",
	"Noresultsfound": "Tiada hasil ditemui",
	"Oldies": "Lama",
	"Other": "Lain-lain",
	"PartialTransfer": "Pindahan Separa",
	"PhoneIn": "Panggil Masuk",
	"Pop": "Pop",
	"RegionLock": "Kunci Kawasan",
	"Religion": "Agama",
	"Remaining": "{numberOfTags} Berbaki",
	"Remove": "Buang",
	"Rock": "Rock",
	"Science": "Sains",
	"SignalLost": "Isyarat Terputus",
	"Social": "Sosial",
	"Sport": "Sukan",
	"StationList": "Senarai Stesen",
	"TAOff": "TA Dimatikan",
	"TagAlreadySaved": "Teg Telah Disimpan",
	"TagCaptured": "Teg Dirakamkan",
	"TagMemoryFull": "Memori Teg Penuh",
	"TagNotYetProcessed": "Teg Belum Diproses Lagi",
	"TagSaved": "Teg Disimpan",
	"TagSavedtoIpod": "Teg Disimpan pada iPod",
	"TagSavedtoSystem": "Teg Disimpan pada Sistem",
	"TagTransferredtoiPod": "Teg Dipindahkan ke iPod",
	"TagsCannotBeSaved": "Teg Tidak Dapat Disimpan",
	"Tooltip_IcnUmpFMSettings": "Tetapan FM",
	"TrafficAlert": "Makluman Lalu Lintas (TA)",
	"TrafficAlertOff": "Makluman Lalu Lintas  (TA) Dimatikan",
	"TrafficAlertOn": "Makluman Lalu Lintas  (TA) Dihidupkan",
	"Travel": "Kembara",
	"UnplugAndReconnect": "Tanggal & Samb. Semula",
	"UpdateStationList": "Kemaskini Senarai Stesen",
	"UpdatingStationList": "Mengemas Kini Senarai Stesen",
	"Varied": "Pelbagai",
	"VrHelp_AutoMemory_Help1_Left1": "(frequency)",
	"VrHelp_AutoMemory_Help1_Left2": "Update List",
	"VrHelp_AutoMemory_Help2_Left1": "Update List",
	"VrHelp_GenreSeek_Help_Left1": "Seek Up",
	"VrHelp_GenreSeek_Help_Left2": "Seek Down",
	"VrHelp_GenreSeek_Help_Left3": "Change Genre",
	"VrHelp_NowPlayingEU_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingEU_Help_Left2": "Station List",
	"VrHelp_NowPlayingEU_Help_Left3": "Favorites",
	"VrHelp_NowPlayingEU_Help_Left4": "Traffic Announcement  (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Scan",
	"VrHelp_NowPlayingEU_Help_Right1": "Tune",
	"VrHelp_NowPlayingEU_Help_Right2": "Seek Previous",
	"VrHelp_NowPlayingEU_Help_Right3": "Seek Next",
	"VrHelp_NowPlayingEU_Help_Right4": "FM Settings",
	"VrHelp_NowPlayingEU_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingNA_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingNA_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingNA_Help_Left3": "Favorites",
	"VrHelp_NowPlayingNA_Help_Left4": "HD Menu",
	"VrHelp_NowPlayingNA_Help_Left5": "Scan",
	"VrHelp_NowPlayingNA_Help_Right1": "Tune",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes Tagging",
	"VrHelp_NowPlayingNA_Help_Right3": "Seek Previous",
	"VrHelp_NowPlayingNA_Help_Right4": "Seek Next",
	"VrHelp_NowPlayingNA_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingOther_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingOther_Help_Left2": "Auto Memory",
	"VrHelp_NowPlayingOther_Help_Left3": "Favorites",
	"VrHelp_NowPlayingOther_Help_Left4": "Scan",
	"VrHelp_NowPlayingOther_Help_Left5": "Tune",
	"VrHelp_NowPlayingOther_Help_Right1": "Seek Previous",
	"VrHelp_NowPlayingOther_Help_Right2": "Seek Next",
	"VrHelp_NowPlayingOther_Help_Right3": "Sound Settings",
	"VrHelp_Settings_Help_Left1": "Alternative Frequency On",
	"VrHelp_Settings_Help_Left2": "Alternative Frequency Off",
	"VrHelp_Settings_Help_Left3": "Region Lock On",
	"VrHelp_Settings_Help_Left4": "Region Lock Off",
	"VrHelp_Tune_NA_Help_Left1": "(frequency)",
	"VrHelp_Tune_NA_Help_Left2": "Tune Up",
	"VrHelp_Tune_NA_Help_Left3": "Tune Down",
	"VrHelp_Tune_nonNA_Help_Left1": "(frequency)",
	"VrHelp_Tune_nonNA_Help_Left2": "Tune Up",
	"VrHelp_Tune_nonNA_Help_Left3": "Tune Down",
	"Weather": "Cuaca",
	"favorites_Tooltip": "Kegemaran",
	"hdChannels_Tooltip": "Saluran HD",
	"rbds_Adult": "Hit Dewasa",
	"rbds_Class": "Rock Klasik",
	"rbds_Classical": "Klasikal",
	"rbds_College": "Kolej",
	"rbds_Country": "Negara",
	"rbds_Emergency": "Amaran! Amaran!",
	"rbds_EmergencyTest": "Ujian Kecemasan",
	"rbds_Foreign": "Bahasa Asing",
	"rbds_Hablar": "Bercakap Bahasa Sepanyol",
	"rbds_HipHop": "Hip Hop",
	"rbds_Info": "Maklumat",
	"rbds_Jazz": "Jaz",
	"rbds_Musica": "Muzik Sepanyol",
	"rbds_News": "Berita",
	"rbds_None": "Tiada",
	"rbds_Nostalgia": "Nostalgia",
	"rbds_Oldies": "Lama",
	"rbds_Personality": "Personaliti",
	"rbds_Public": "Awam",
	"rbds_ReligousM": "Muzik Keagamaan",
	"rbds_ReligousT": "Perbincangan Keagamaan",
	"rbds_Rhythym": "Rhythm and Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Lembut",
	"rbds_SoftRB": "R&B Lembut",
	"rbds_SoftRock": "Rock Lembut",
	"rbds_Sports": "Sukan",
	"rbds_Talk": "Perbincangan",
	"rbds_Top40": "Top 40",
	"rbds_Weather": "Cuaca",
	"rbds_genre_Adult": "Genre: Hit Dewasa",
	"rbds_genre_Class": "Genre: Rock Klasik",
	"rbds_genre_Classical": "Genre: Klasikal",
	"rbds_genre_College": "Genre: Kolej",
	"rbds_genre_Country": "Genre: Country",
	"rbds_genre_Emergency": "Genre: Amaran! Amaran!",
	"rbds_genre_EmergencyTest": "Genre: Ujian Kecemasan",
	"rbds_genre_Foreign": "Genre: Bahasa Asing",
	"rbds_genre_Hablar": "Genre: Bahasa Sepanyol",
	"rbds_genre_HipHop": "Genre: Hip Hop",
	"rbds_genre_Info": "Genre: Maklumat",
	"rbds_genre_Jazz": "Genre: Jaz",
	"rbds_genre_Musica": "Genre: Muzik Sepanyol",
	"rbds_genre_News": "Genre: Berita",
	"rbds_genre_None": "Genre: Tiada",
	"rbds_genre_Nostalgia": "Genre: Nostalgia",
	"rbds_genre_Oldies": "Genre: Lagu Lama",
	"rbds_genre_Personality": "Genre: Personaliti",
	"rbds_genre_Public": "Genre: Awam",
	"rbds_genre_ReligousM": "Genre: Muzik Keagamaan",
	"rbds_genre_ReligousT": "Genre: Perbincangan Keagamaan",
	"rbds_genre_Rhythym": "Genre: Rhythm and Blues",
	"rbds_genre_Rock": "Genre: Rock",
	"rbds_genre_Soft": "Genre: Lembut",
	"rbds_genre_SoftRB": "Genre: R&B Lembut",
	"rbds_genre_SoftRock": "Genre: Rock Lembut",
	"rbds_genre_Sports": "Genre: Sukan",
	"rbds_genre_Talk": "Genre: Cakap",
	"rbds_genre_Top40": "Genre: Carta 40",
	"rbds_genre_Weather": "Genre: Cuaca",
};

framework.registerAppDictLoaded("fmradio", "ms_MY");