var Localization_fmradioAppDict_sv_SE = {
	//"stringId" : "localString"
	"Affairs": "Affärer",
	"Alarm": "Larm",
	"AlarmTest": "Larmtest",
	"AllMemoryFull": "Hela minnet fullt",
	"AllStations": "Alla stationer",
	"AllTagsTransferred": "Alla taggar överförda",
	"AlternativeFrequency": "Alternativ frekvens",
	"AutoMemoryList": "Autominneslista",
	"CannotTransferTags": "Kan inte överföra taggar",
	"ChangeGenre": "Ändra kategori",
	"Childrens": "Barn",
	"Classics": "Klassiskt",
	"Close": "Stäng",
	"ConnectIPod": "Anslut iPod, överför tagg",
	"Country": "Country",
	"Culture": "Kultur",
	"Documentary": "Dokumentär",
	"Drama": "Drama",
	"Education": "Utbildning",
	"ErrorConnection": "Fel då taggar överförs till",
	"FMRadio": "FM radio",
	"FMSettings": "FM-inställningar",
	"Finance": "Ekonomi",
	"Folk": "Folkmusik",
	"GenreAffairs": "Kategori: Affärer",
	"GenreAlarm": "Kategori: Larm",
	"GenreAlarmTest": "Kategori: Larmtest",
	"GenreAllStations": "Kategori: Alla stationer",
	"GenreChildrens": "Kategori: Barn",
	"GenreClassics": "Kategori: Klassiskt",
	"GenreCountry": "Kategori: Country",
	"GenreCulture": "Kategori: Kultur",
	"GenreDocumentary": "Kategori: Dokumentär",
	"GenreDrama": "Kategori: Drama",
	"GenreEducation": "Kategori: Utbildning",
	"GenreFinance": "Kategori: Ekonomi",
	"GenreFolk": "Kategori: Folkmusik",
	"GenreInfo": "Kategori: Information",
	"GenreJazz": "Kategori: Jazz",
	"GenreLeisure": "Kategori: Fritid",
	"GenreLight": "Kategori: Lätt",
	"GenreList": "Kategorilista",
	"GenreMor": "Kategori: Lättlyssnat",
	"GenreName": "Kategori: {genreName}",
	"GenreNational": "Kategori: Nationellt",
	"GenreNews": "Kategori: Nyheter",
	"GenreOldies": "Kategori: Äldre",
	"GenreOther": "Kategori: Annat",
	"GenrePhoneIn": "Kategori: Telefon in",
	"GenrePop": "Kategori: Pop",
	"GenreReligion": "Kategori: Religion",
	"GenreRock": "Kategori: Rock",
	"GenreScience": "Kategori: Vetenskap",
	"GenreSeek": "Sök i kategori",
	"GenreSocial": "Kategori: Social",
	"GenreSport": "Kategori: Sport",
	"GenreTravel": "Kategori: Resa",
	"GenreVaried": "Kategori: Varierat",
	"GenreWeather": "Kategori: Väder",
	"HDRadio": "HD-radio",
	"HDStations": "HD-stationer",
	"Info": "Information",
	"IpodError": "Fel på iPod",
	"IpodFull": "iPod full",
	"Jazz": "Jazz",
	"Leisure": "Fritid",
	"Light": "Lätt",
	"MemoryFull": "Minnet fullt",
	"Mor": "Lättlyssnat",
	"National": "Nationellt",
	"News": "Nyheter",
	"Noresultsfound": "Hittade inga resultat",
	"Oldies": "Äldre",
	"Other": "Annat",
	"PartialTransfer": "Partiell överföring",
	"PhoneIn": "Ring in",
	"Pop": "Pop",
	"RegionLock": "Regionslås",
	"Religion": "Religion",
	"Remaining": "{numberOfTags} kvar",
	"Remove": "Ta bort",
	"Rock": "Rock",
	"Science": "Vetenskap",
	"SignalLost": "Signalen har förlorats",
	"Social": "Social",
	"Sport": "Sport",
	"StationList": "Stationslista",
	"TAOff": "TA av",
	"TagAlreadySaved": "Taggen redan sparad",
	"TagCaptured": "Tagg tagen",
	"TagMemoryFull": "Taggminnet fullt",
	"TagNotYetProcessed": "Tagg har inte bearbetats",
	"TagSaved": "Tagg har sparats",
	"TagSavedtoIpod": "Tagg har sparats till iPod",
	"TagSavedtoSystem": "Tagg sparad till system",
	"TagTransferredtoiPod": "Tagg överförd till iPod",
	"TagsCannotBeSaved": "Taggar kan inte sparas",
	"Tooltip_IcnUmpFMSettings": "FM-inställningar",
	"TrafficAlert": "Trafikvarning (TA)",
	"TrafficAlertOff": "Trafikvarning (TA) av",
	"TrafficAlertOn": "Trafikvarning (TA) på",
	"Travel": "Resa",
	"UnplugAndReconnect": "Koppla från och återanslut",
	"UpdateStationList": "Uppdatera stationslista",
	"UpdatingStationList": "Uppdaterar stationslista",
	"Varied": "Blandat",
	"VrHelp_AutoMemory_Help1_Left1": "(frekvens)",
	"VrHelp_AutoMemory_Help1_Left2": "Uppdatera lista",
	"VrHelp_AutoMemory_Help2_Left1": "Uppdatera lista",
	"VrHelp_GenreSeek_Help_Left1": "Sök uppåt",
	"VrHelp_GenreSeek_Help_Left2": "Sök nedåt",
	"VrHelp_GenreSeek_Help_Left3": "Ändra kategori",
	"VrHelp_NowPlayingEU_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingEU_Help_Left2": "Stationslista",
	"VrHelp_NowPlayingEU_Help_Left3": "Favoriter",
	"VrHelp_NowPlayingEU_Help_Left4": "Trafikvarning (TA)",
	"VrHelp_NowPlayingEU_Help_Left5": "Sök",
	"VrHelp_NowPlayingEU_Help_Right1": "Ställ in",
	"VrHelp_NowPlayingEU_Help_Right2": "Sök föregående",
	"VrHelp_NowPlayingEU_Help_Right3": "Sök nästa",
	"VrHelp_NowPlayingEU_Help_Right4": "FM-inställningar",
	"VrHelp_NowPlayingEU_Help_Right5": "Ljudinställningar",
	"VrHelp_NowPlayingNA_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingNA_Help_Left2": "Automatiskt minne",
	"VrHelp_NowPlayingNA_Help_Left3": "Favoriter",
	"VrHelp_NowPlayingNA_Help_Left4": " HD-meny",
	"VrHelp_NowPlayingNA_Help_Left5": "Sök",
	"VrHelp_NowPlayingNA_Help_Right1": "Ställ in",
	"VrHelp_NowPlayingNA_Help_Right2": "iTunes-taggning",
	"VrHelp_NowPlayingNA_Help_Right3": "Sök föregående",
	"VrHelp_NowPlayingNA_Help_Right4": "Sök nästa",
	"VrHelp_NowPlayingNA_Help_Right5": "Ljudinställningar",
	"VrHelp_NowPlayingOther_Help_Left1": "Underhållning",
	"VrHelp_NowPlayingOther_Help_Left2": "Automatiskt minne",
	"VrHelp_NowPlayingOther_Help_Left3": "Favoriter",
	"VrHelp_NowPlayingOther_Help_Left4": "Sök",
	"VrHelp_NowPlayingOther_Help_Left5": "Ställ in",
	"VrHelp_NowPlayingOther_Help_Right1": "Sök föregående",
	"VrHelp_NowPlayingOther_Help_Right2": "Sök nästa",
	"VrHelp_NowPlayingOther_Help_Right3": "Ljudinställningar",
	"VrHelp_Settings_Help_Left1": "Alternativ frekvens på",
	"VrHelp_Settings_Help_Left2": "Alternativ frekvens av",
	"VrHelp_Settings_Help_Left3": "Regionlås på",
	"VrHelp_Settings_Help_Left4": "Regionlås av",
	"VrHelp_Tune_NA_Help_Left1": "(frekvens)",
	"VrHelp_Tune_NA_Help_Left2": "Ställ in uppåt",
	"VrHelp_Tune_NA_Help_Left3": "Ställ in nedåt",
	"VrHelp_Tune_nonNA_Help_Left1": "(frekvens)",
	"VrHelp_Tune_nonNA_Help_Left2": "Ställ in uppåt",
	"VrHelp_Tune_nonNA_Help_Left3": "Ställ in nedåt",
	"Weather": "Väder",
	"favorites_Tooltip": "Favoriter",
	"hdChannels_Tooltip": "HD stanice",
	"rbds_Adult": "Vuxenhits",
	"rbds_Class": "Klassisk rock",
	"rbds_Classical": "Klassiskt",
	"rbds_College": "College",
	"rbds_Country": "Country",
	"rbds_Emergency": "SOS! SOS!",
	"rbds_EmergencyTest": "Nödanropstest",
	"rbds_Foreign": "Främmande språk",
	"rbds_Hablar": "Spanska",
	"rbds_HipHop": "Hip hop",
	"rbds_Info": "Information",
	"rbds_Jazz": "Jazz",
	"rbds_Musica": "Spansk musik",
	"rbds_News": "Nyheter",
	"rbds_None": "--",
	"rbds_Nostalgia": "Nostalgi",
	"rbds_Oldies": "Äldre",
	"rbds_Personality": "Personlighet",
	"rbds_Public": "Allmänt",
	"rbds_ReligousM": "Religiös musik",
	"rbds_ReligousT": "Religiöst prat",
	"rbds_Rhythym": "Rhytm'n Blues",
	"rbds_Rock": "Rock",
	"rbds_Soft": "Soft",
	"rbds_SoftRB": "Soft R&B",
	"rbds_SoftRock": "Mjukrock",
	"rbds_Sports": "Sport",
	"rbds_Talk": "Prata",
	"rbds_Top40": "Topp 40",
	"rbds_Weather": "Väder",
	"rbds_genre_Adult": "Kategori: Vuxenhits",
	"rbds_genre_Class": "Kategori: Klassisk rock",
	"rbds_genre_Classical": "Kategori: Klassiskt",
	"rbds_genre_College": "Kategori: College",
	"rbds_genre_Country": "Kategori: Country",
	"rbds_genre_Emergency": "Kategori: SOS! SOS!",
	"rbds_genre_EmergencyTest": "Kategori: Nödanropstest",
	"rbds_genre_Foreign": "Kategori: Främmande språk",
	"rbds_genre_Hablar": "Kategori: Spanska",
	"rbds_genre_HipHop": "Kategori: Hip hop",
	"rbds_genre_Info": "Kategori: Info",
	"rbds_genre_Jazz": "Kategori: Jazz",
	"rbds_genre_Musica": "Kategori: Spansk musik",
	"rbds_genre_News": "Kategori: Nyheter",
	"rbds_genre_None": "Kategori: --",
	"rbds_genre_Nostalgia": "Kategori: Nostalgi",
	"rbds_genre_Oldies": "Kategori: Oldies",
	"rbds_genre_Personality": "Kategori: Personlighet",
	"rbds_genre_Public": "Kategori: Allmänt",
	"rbds_genre_ReligousM": "Kategori: Religiös musik",
	"rbds_genre_ReligousT": "Kategori: Religiöst prat",
	"rbds_genre_Rhythym": "Kategori: Rhytm'n Blues",
	"rbds_genre_Rock": "Kategori: Rock",
	"rbds_genre_Soft": "Kategori: Soft",
	"rbds_genre_SoftRB": "Kategori: Soft R&B",
	"rbds_genre_SoftRock": "Kategori: Mjukrock",
	"rbds_genre_Sports": "Kategori: Sports",
	"rbds_genre_Talk": "Kategori: Prata",
	"rbds_genre_Top40": "Kategori: Topp 40",
	"rbds_genre_Weather": "Kategori: Väder",
};

framework.registerAppDictLoaded("fmradio", "sv_SE");