var Localization_emailAppDict_fi_FI = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Järjestelmä ei tue liitetiedostoja",
	"AutoDownload": "Email ladattu",
	"Back": "Takaisin",
	"Bcc": "Piilokopio: {Bcc}",
	"Cc": "Kopio: {Cc}",
	"ContinueEmail": "Jatka Email",
	"Delete": "Poista",
	"DeleteFail": "Poistaminen ei onnistunut",
	"DeleteFailDesc": "Viestin poistaminen ei onnistunut",
	"Discard": "Hylkää",
	"DiscardConfirm": "Haluatko hylätä nykyisen viestin?",
	"DownloadFail": "Lataaminen ei onnistunut",
	"DownloadFailDesc": "Puhelimen tietojen noutaminen ei onnistunut",
	"DownloadedEmailMessages": "Päivitä Saapuneet-kansio",
	"Email": "Email",
	"EmailDeleteConfirm": "Tämä Email poistetaan mobiililaitteesta, ja toimintoa ei voi perua. Haluatko varmasti poistaa sen?",
	"EmailNotSent": "Email ei lähetetty",
	"EmailSent": "Email lähetetty",
	"From": "Lähettäjä: {From}",
	"Inbox": "Saapuneet",
	"InboxSelector": "Valitse tilin saapuneet-kansio",
	"InstanceDisconnectDesc": "Tiliin yhdistäminen epäonnistui",
	"ListDownloadFail": "Luettelon lataaminen ei onnistunut",
	"Message": "Viesti: {Msg}",
	"MessagePreset": "Valmis viesti",
	"NEW-AllAccounts": "Kaikki tilit",
	"NotificationNotSupported": "Järjestelmä ei tue ilmoitusta",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Kaikki Saapuneet",
	"Reply": "Vastaa",
	"Retry": "Yritä uudelleen",
	"Return": "Palaa",
	"SelectContact": "Valitse yhteystieto",
	"SelectMessage": "Valitse viesti",
	"Send": "Lähetä",
	"SendFail": "Lähettäminen ei onnistunut",
	"SendFailDesc": "Viestin puhelimeen lähettäminen ei onnistunut",
	"Sending": "Email lähetetään",
	"SpeedRestriction": "Viestiä ei näytetä turvallisuussyistä.",
	"Subject": "Aihe: {Sub}",
	"TTSReadFail": "Viestin lukeminen ei onnistunut",
	"TextMessages": "SMS",
	"To": "Vastaanottaja: {To}",
	"UnfinishedEmailMessage": "Keskeneräinen viesti edellyttää toimenpiteitäsi.",
	"Updating": "Päivitetään",
	"VUIConfirmSend": "Haluatko jatkaa tämän Email lähettämistä?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Viestintä",
	"VrHelp_EmailMessageDetail_Help_Left2": "Saapuneet",
	"VrHelp_EmailMessageDetail_Help_Left3": "Toista / Tauko",
	"VrHelp_EmailMessageDetail_Help_Left4": "Edellinen",
	"VrHelp_EmailMessageDetail_Help_Left5": "Seuraava",
	"VrHelp_EmailMessageDetail_Help_Right1": "Vastaa ",
	"VrHelp_EmailMessageDetail_Help_Right2": "Vastaa kaikille",
	"VrHelp_EmailMessageDetail_Help_Right3": "Puhelu",
	"VrHelp_EmailMessageDetail_Help_Right4": "Poista",
	"VrHelp_EmailReply_Help_Left1": "Lisää viesti",
	"VrHelp_EmailReply_Help_Left2": "Lähetä",
	"home": "Koti:",
	"mobile": "Matkapuhelin:",
	"other": "Muu:",
	"work": "Työ:",
};

framework.registerAppDictLoaded("email", "fi_FI");