var Localization_emailAppDict_nl_NL = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Bijlage niet ondersteund",
	"AutoDownload": "Gedownloade Emails",
	"Back": "Terug",
	"Bcc": "Bcc: {Bcc}",
	"Cc": "Cc: {Cc}",
	"ContinueEmail": "Meer Email",
	"Delete": "Verwijderen",
	"DeleteFail": "Kan niet verwijderen",
	"DeleteFailDesc": "Kan bericht niet verwijderen",
	"Discard": "Weggooien",
	"DiscardConfirm": "Wilt u het huidige bericht verwijderen?",
	"DownloadFail": "Kan niet downloaden",
	"DownloadFailDesc": "Kan geen telefonische informatie opvragen",
	"DownloadedEmailMessages": "Inbox Bijwerken",
	"Email": "Email",
	"EmailDeleteConfirm": "Deze Email zal definitief van het mobiele apparaat worden verwijderd. Weet u zeker dat u deze wilt verwijderen?",
	"EmailNotSent": "Email is niet verzonden",
	"EmailSent": "Email verzonden",
	"From": "Van: {From}",
	"Inbox": "Inbox",
	"InboxSelector": "Account inbox selecteren",
	"InstanceDisconnectDesc": "Geen verbinding met het account",
	"ListDownloadFail": "Kan lijst niet downloaden",
	"Message": "Bericht: {Msg}",
	"MessagePreset": "Voorinstelling bericht",
	"NEW-AllAccounts": "Alle accounts",
	"NotificationNotSupported": "Melding niet ondersteund",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Alle Inboxes",
	"Reply": "Beantwoorden",
	"Retry": "Opnieuw proberen",
	"Return": "Terug",
	"SelectContact": "Selecteer contactpersoon",
	"SelectMessage": "Selecteer bericht",
	"Send": "Verzenden",
	"SendFail": "Kan niet verzenden",
	"SendFailDesc": "Kan geen bericht verzenden naar telefoon",
	"Sending": "Email wordt verzonden",
	"SpeedRestriction": "Voor uw veiligheid wordt het bericht niet weergegeven",
	"Subject": "Onderwerp: {Sub}",
	"TTSReadFail": "Kan bericht niet lezen",
	"TextMessages": "SMS",
	"To": "Aan: {To}",
	"UnfinishedEmailMessage": "Een onvoltooid bericht vereist uw aandacht.",
	"Updating": "Updaten",
	"VUIConfirmSend": "Wilt u doorgaan met het verzenden van deze Email?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communicatie",
	"VrHelp_EmailMessageDetail_Help_Left2": " Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": " Afspelen / Pauze",
	"VrHelp_EmailMessageDetail_Help_Left4": "Vorige",
	"VrHelp_EmailMessageDetail_Help_Left5": " Volgende",
	"VrHelp_EmailMessageDetail_Help_Right1": "Beantwoorden",
	"VrHelp_EmailMessageDetail_Help_Right2": "Allen beantwoorden",
	"VrHelp_EmailMessageDetail_Help_Right3": "Bellen ",
	"VrHelp_EmailMessageDetail_Help_Right4": "Verwijderen",
	"VrHelp_EmailReply_Help_Left1": "Bericht Toevoegen",
	"VrHelp_EmailReply_Help_Left2": "Verzenden",
	"home": "Thuis:",
	"mobile": "Mobiel:",
	"other": "Andere:",
	"work": "Werk:",
};

framework.registerAppDictLoaded("email", "nl_NL");