var Localization_emailAppDict_zh_CN = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "不支持附件",
	"AutoDownload": "已下载电子邮件",
	"Back": "返回",
	"Bcc": "密送：{Bcc}",
	"Cc": "抄送：{Cc}",
	"ContinueEmail": "继续电子邮件",
	"Delete": "删除",
	"DeleteFail": "无法删除",
	"DeleteFailDesc": "无法删除消息",
	"Discard": "放弃",
	"DiscardConfirm": "是否要放弃当前消息？",
	"DownloadFail": "无法下载",
	"DownloadFailDesc": "无法从电话获得信息",
	"DownloadedEmailMessages": "更新收件箱",
	"Email": "电子邮件",
	"EmailDeleteConfirm": "该电子邮件将从移动设备中删除，并且无法撤销。确定要删除吗？",
	"EmailNotSent": "未发送电子邮件",
	"EmailSent": "已发送电子邮件",
	"From": "发件人：{From}",
	"Inbox": "收件箱",
	"InboxSelector": "选择帐户收件箱",
	"InstanceDisconnectDesc": "无法连接到帐户",
	"ListDownloadFail": "无法下载列表",
	"Message": "消息： {Msg}",
	"MessagePreset": "消息预设",
	"NEW-AllAccounts": "所有帐户",
	"NotificationNotSupported": "不支持通知",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "所有收件箱",
	"Reply": "回复",
	"Retry": "重试",
	"Return": "返回",
	"SelectContact": "选择联系人",
	"SelectMessage": "选择消息",
	"Send": "发送",
	"SendFail": "无法发送",
	"SendFailDesc": "无法将消息发送到电话",
	"Sending": "正在发送电子邮件",
	"SpeedRestriction": "为了您的安全，不显示此消息",
	"Subject": "主题：{Sub}",
	"TTSReadFail": "无法阅读消息",
	"TextMessages": "文本消息",
	"To": "收件人： {To}",
	"UnfinishedEmailMessage": "请注意有一条未完成的消息。",
	"Updating": "正在更新",
	"VUIConfirmSend": "是否要继续发送此电子邮件？",
	"VrHelp_EmailMessageDetail_Help_Left1": "通讯",
	"VrHelp_EmailMessageDetail_Help_Left2": "收件箱",
	"VrHelp_EmailMessageDetail_Help_Left3": "播放 / 暂停",
	"VrHelp_EmailMessageDetail_Help_Left4": "上一个",
	"VrHelp_EmailMessageDetail_Help_Left5": "下一个",
	"VrHelp_EmailMessageDetail_Help_Right1": "回复",
	"VrHelp_EmailMessageDetail_Help_Right2": "全部回复",
	"VrHelp_EmailMessageDetail_Help_Right3": "呼叫",
	"VrHelp_EmailMessageDetail_Help_Right4": "删除",
	"VrHelp_EmailReply_Help_Left1": "添加消息",
	"VrHelp_EmailReply_Help_Left2": "发送",
	"home": "住宅电话:",
	"mobile": "手机:",
	"other": "其它电话:",
	"work": "工作电话:",
};

framework.registerAppDictLoaded("email", "zh_CN");