var Localization_emailAppDict_he_IL = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "אין תמיכה בקובץ המצורף",
	"AutoDownload": "פריטי דואר אלקטרוני הורדו",
	"Back": "חזרה",
	"Bcc": "עותק נסתר: {Bcc}",
	"Cc": "עותק : {Cc}",
	"ContinueEmail": "המשך אימייל",
	"Delete": "מחק",
	"DeleteFail": "לא ניתן למחוק",
	"DeleteFailDesc": "לא ניתן למחוק את ההודעה",
	"Discard": "בטל",
	"DiscardConfirm": "האם ברצונך לבטל את ההודעה הנוכחית?",
	"DownloadFail": "לא ניתן להוריד",
	"DownloadFailDesc": "לא ניתן לקבל מידע מהטלפון",
	"DownloadedEmailMessages": "עדכן דואר נכנס",
	"Email": "אימייל",
	"EmailDeleteConfirm": "פריט דואר האלקטרוני זה יוסר מהמכשיר הנייד באופן בלתי הפיך. האם אתה בטוח שברצונך למחוק אותו?",
	"EmailNotSent": "Email לא נשלח",
	"EmailSent": "דואר אלקטרוני נשלח",
	"From": "מאת: {From}",
	"Inbox": "דואר נכנס",
	"InboxSelector": "בחר תיבת דואר נכנס של החשבון",
	"InstanceDisconnectDesc": "לא ניתן להתחבר לחשבון",
	"ListDownloadFail": "לא ניתן להוריד את הרשימה",
	"Message": "הודעה: {Msg}",
	"MessagePreset": "הודעה מוכנה מראש",
	"NEW-AllAccounts": "כל החשבונות",
	"NotificationNotSupported": "אין תמיכה בהתראה",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "כל תיבות דואר נכנס",
	"Reply": "ענה",
	"Retry": "נסה שוב",
	"Return": "חזור",
	"SelectContact": "בחר איש קשר",
	"SelectMessage": "בחר הודעה",
	"Send": "שלח",
	"SendFail": "לא ניתן לשלוח",
	"SendFailDesc": "לא ניתן לשלוח הודעה לטלפון",
	"Sending": "שולח דואר אלקטרוני",
	"SpeedRestriction": "ההודעה אינה מוצגת מטעמי בטיחות",
	"Subject": "נושא: {Sub}",
	"TTSReadFail": "לא ניתן לקרוא את ההודעה",
	"TextMessages": "הודעות טקסט",
	"To": "אל: {To}",
	"UnfinishedEmailMessage": "הודעה בלתי גמורה דורשת את תשומת לבך.",
	"Updating": "מעדכן",
	"VUIConfirmSend": "האם ברצונך להמשיך לשלוח את הדואר האלקטרוני הזה?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Previous",
	"VrHelp_EmailMessageDetail_Help_Left5": "Next",
	"VrHelp_EmailMessageDetail_Help_Right1": "Reply",
	"VrHelp_EmailMessageDetail_Help_Right2": "Reply All",
	"VrHelp_EmailMessageDetail_Help_Right3": "Call",
	"VrHelp_EmailMessageDetail_Help_Right4": "Delete",
	"VrHelp_EmailReply_Help_Left1": "Add Message",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "בית",
	"mobile": "נייד",
	"other": "אחר",
	"work": "עבודה",
};

framework.registerAppDictLoaded("email", "he_IL");