var Localization_emailAppDict_hu_HU = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Melléklet nem támogatott",
	"AutoDownload": "Letöltött Email üzenetek",
	"Back": "Vissza",
	"Bcc": "Titkos másolat: {Bcc}",
	"Cc": "Másolatot kap: {Cc}",
	"ContinueEmail": "Email folytatása",
	"Delete": "Törlés",
	"DeleteFail": "Nem lehet törölni",
	"DeleteFailDesc": "Nem lehet az üzenetet törölni",
	"Discard": "Elvetés",
	"DiscardConfirm": "Elveti az aktuális üzenetet?",
	"DownloadFail": "Nem lehet letölteni",
	"DownloadFailDesc": "Nem szerezhető be adat a telefonról",
	"DownloadedEmailMessages": "Bejövő üzenetek frissítése",
	"Email": "Email",
	"EmailDeleteConfirm": "Ezt az Email üzenetet a rendszer visszavonhatatlanul törli a mobil eszközről. Biztosan törli?",
	"EmailNotSent": "Nem került elküldésre az Email.",
	"EmailSent": "Email elküldve",
	"From": "Feladó: {From}",
	"Inbox": "Beérkezett üzen.",
	"InboxSelector": "Beérkezett üzenet kijelölése",
	"InstanceDisconnectDesc": "Nem lehet a fiókhoz kapcsolódni.",
	"ListDownloadFail": "Nem lehet a listát letölteni",
	"Message": "Üzenet: {Msg}",
	"MessagePreset": "Üzenet beállítása",
	"NEW-AllAccounts": "Összes felhasználó",
	"NotificationNotSupported": "Értesítés nem támogatott",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Összes bejövő",
	"Reply": "Válasz",
	"Retry": "Újrapróbálkozás",
	"Return": "Visszatérés",
	"SelectContact": "Névjegy kiválasztása",
	"SelectMessage": "Üzenet kijelölése",
	"Send": "Küldés",
	"SendFail": "Nem lehet elküldeni",
	"SendFailDesc": "Nem küldhető üzenet a telefonra",
	"Sending": "Email küldése",
	"SpeedRestriction": "Az üzenetet a rendszer az Ön biztonsága érdekében nem jeleníti meg",
	"Subject": "Tárgy: {Sub}",
	"TTSReadFail": "Nem lehet az üzenetet olvasni",
	"TextMessages": "SMS",
	"To": "Címzett: {To}",
	"UnfinishedEmailMessage": "Egy befejezetlen üzenet figyelmet igényel.",
	"Updating": "Frissítés",
	"VUIConfirmSend": "Folytatja az Email elküldését?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Previous",
	"VrHelp_EmailMessageDetail_Help_Left5": "Next",
	"VrHelp_EmailMessageDetail_Help_Right1": "Reply",
	"VrHelp_EmailMessageDetail_Help_Right2": "Reply All",
	"VrHelp_EmailMessageDetail_Help_Right3": "Call",
	"VrHelp_EmailMessageDetail_Help_Right4": "Delete",
	"VrHelp_EmailReply_Help_Left1": "Add Message",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "Otthoni:",
	"mobile": "Mobil:",
	"other": "Egyéb:",
	"work": "Munkahelyi:",
};

framework.registerAppDictLoaded("email", "hu_HU");