var Localization_emailAppDict_fr_CN = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Pièce jointe non acceptée",
	"AutoDownload": "Emails téléchargés",
	"Back": "Retour",
	"Bcc": "Copie cachée à : {Bcc}",
	"Cc": "Copie à : {Cc}",
	"ContinueEmail": "Continuer l’Email",
	"Delete": "Supprimer",
	"DeleteFail": "Impossible de supprimer",
	"DeleteFailDesc": "Impossible de supprimer le message",
	"Discard": "Ne pas enregistrer",
	"DiscardConfirm": "Voulez-vous supprimer le message en cours ?",
	"DownloadFail": "Impossible de télécharger",
	"DownloadFailDesc": "Impossible d'obtenir des données du téléphone",
	"DownloadedEmailMessages": "Màj de boîte de réception",
	"Email": "Email",
	"EmailDeleteConfirm": "Cet Email sera supprimé du dispositif mobile. Cette opération ne peut être annulée. Etes-vous sûr de vouloir supprimer ?",
	"EmailNotSent": "L’Email n'a pas été envoyé",
	"EmailSent": "Email envoyé",
	"From": "De : {From}",
	"Inbox": "Boîte de réception",
	"InboxSelector": "Sélectionner boîte de réception",
	"InstanceDisconnectDesc": "Connexion au compte impossible",
	"ListDownloadFail": "Impossible de télécharger la liste",
	"Message": "Message : {Msg}",
	"MessagePreset": "Prédéfinition du message ",
	"NEW-AllAccounts": "Tous les comptes",
	"NotificationNotSupported": "Notification non acceptée",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Toutes boîtes",
	"Reply": "Répondre",
	"Retry": "Réessayer",
	"Return": "Retour",
	"SelectContact": "Sélectionner un contact",
	"SelectMessage": "Sélectionner un message",
	"Send": "Envoyer",
	"SendFail": "Impossible d’envoyer",
	"SendFailDesc": "Impossible d'envoyer un message au téléphone",
	"Sending": "En cours d’envoi d’un Email",
	"SpeedRestriction": "Pour votre sécurité, le message n’est pas affiché",
	"Subject": "Sujet : {Sub}",
	"TTSReadFail": "Impossible de lire le message",
	"TextMessages": "SMS",
	"To": "A : {To}",
	"UnfinishedEmailMessage": "Un message inachevé nécessite votre attention.",
	"Updating": "mise à jour en cours",
	"VUIConfirmSend": "Voulez-vous poursuivre l’envoi de cet Email ?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Boîte de réception",
	"VrHelp_EmailMessageDetail_Help_Left3": "Lire/Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Précédent",
	"VrHelp_EmailMessageDetail_Help_Left5": "Suivant",
	"VrHelp_EmailMessageDetail_Help_Right1": "Répondre",
	"VrHelp_EmailMessageDetail_Help_Right2": "Répondre à tous",
	"VrHelp_EmailMessageDetail_Help_Right3": "Appeler",
	"VrHelp_EmailMessageDetail_Help_Right4": "Supprimer",
	"VrHelp_EmailReply_Help_Left1": "Ajouter un message",
	"VrHelp_EmailReply_Help_Left2": "Envoyer",
	"home": "Maison:",
	"mobile": "Mobile:",
	"other": "Autre:",
	"work": "Travail:",
};

framework.registerAppDictLoaded("email", "fr_CN");