var Localization_emailAppDict_da_DK = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Vedhæftninger ikke understøttet",
	"AutoDownload": "Downloadede Email",
	"Back": "Tilbage",
	"Bcc": "Bcc: {Bcc}",
	"Cc": "Cc: {Cc}",
	"ContinueEmail": "Fortsæt Email",
	"Delete": "Slet",
	"DeleteFail": "Kunne ikke slette",
	"DeleteFailDesc": "Kunne ikke slette beskeden",
	"Discard": "Kassér",
	"DiscardConfirm": "Ønsker du at kassere denne besked?",
	"DownloadFail": "Kunne ikke hente",
	"DownloadFailDesc": "Kunne ikke få information fra telefon",
	"DownloadedEmailMessages": "Opdatér indbakke",
	"Email": "Email",
	"EmailDeleteConfirm": "Denne Email vil blive slettet på mobilenheden og kan ikke gendannes. Er du sikker på, at du ønsker at slette?",
	"EmailNotSent": "Email blev ikke sendt",
	"EmailSent": "Email sendt",
	"From": "Fra: {From}",
	"Inbox": "Indbakke",
	"InboxSelector": "Vælg kontoindbakke",
	"InstanceDisconnectDesc": "Kunne ikke oprette forbindelse til kontoen",
	"ListDownloadFail": "Kunne ikke hente liste",
	"Message": "Besked: {Msg}",
	"MessagePreset": "Forvalgt besked",
	"NEW-AllAccounts": "Alle konti",
	"NotificationNotSupported": "Notifikation understøttes ikke",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Alle indbakker",
	"Reply": "Besvar",
	"Retry": "Forsøg igen",
	"Return": "Tilbage",
	"SelectContact": "Vælg kontakt",
	"SelectMessage": "Vælg besked",
	"Send": "Send",
	"SendFail": "Kunne ikke sende",
	"SendFailDesc": "Kunne ikke sende besked til telefonen",
	"Sending": "Sender Email",
	"SpeedRestriction": "Af hensyn til din sikkerhed, vises beskeden ikke",
	"Subject": "Emne: {Sub}",
	"TTSReadFail": "Kunne ikke læse beskeden",
	"TextMessages": "SMS",
	"To": "Til {To}",
	"UnfinishedEmailMessage": "En uafsluttet besked kræver din opmærksomhed.",
	"Updating": "Opdaterer",
	"VUIConfirmSend": "Ønsker du at fortsætte med at sende denne Email?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Kommunikation",
	"VrHelp_EmailMessageDetail_Help_Left2": "Indbakke",
	"VrHelp_EmailMessageDetail_Help_Left3": "Afspil / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Forrige",
	"VrHelp_EmailMessageDetail_Help_Left5": "Næste",
	"VrHelp_EmailMessageDetail_Help_Right1": "Besvar",
	"VrHelp_EmailMessageDetail_Help_Right2": "Besvar alle",
	"VrHelp_EmailMessageDetail_Help_Right3": "Opkald",
	"VrHelp_EmailMessageDetail_Help_Right4": "Slet ",
	"VrHelp_EmailReply_Help_Left1": "Tilføj besked",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "Hjem:",
	"mobile": "Mobil:",
	"other": "Andet:",
	"work": "Arbejde:",
};

framework.registerAppDictLoaded("email", "da_DK");