var Localization_emailAppDict_sr_RS = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Prilog nije podržan",
	"AutoDownload": "Email su preuzete",
	"Back": "Nazad",
	"Bcc": "Bcc: {Bcc}",
	"Cc": "Cc: {Cc}",
	"ContinueEmail": "Nastavi Email",
	"Delete": "Izbriši",
	"DeleteFail": "Nije moguće izbrisati",
	"DeleteFailDesc": "Nije moguće izbrisati poruku",
	"Discard": "Odbaci",
	"DiscardConfirm": "Da li želite da odbacite trenutnu poruku?",
	"DownloadFail": "Preuzimanje nije moguće",
	"DownloadFailDesc": "Nije moguće dobiti informaciju od telefona",
	"DownloadedEmailMessages": "Ažuriraj prijemno sanduče",
	"Email": "Email",
	"EmailDeleteConfirm": "Ova Email će biti izbrisana sa mobilnog uređaja i ne može se povratiti. Da li ste sigurni da želite da je izbrišete?",
	"EmailNotSent": "Email nije poslat",
	"EmailSent": "Email je poslata",
	"From": "Od: {From}",
	"Inbox": "Prijemno sanduče",
	"InboxSelector": "Izaberite prijemno sanduče",
	"InstanceDisconnectDesc": "Nije moguće povezati se na nalog",
	"ListDownloadFail": "Preuzimanje liste nije moguće",
	"Message": "Poruka: {Msg}",
	"MessagePreset": "Unapred podešena poruka",
	"NEW-AllAccounts": "Svi nalozi",
	"NotificationNotSupported": "Obaveštenje nije podržano",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Svi prijemni sandučići",
	"Reply": "Odgovori",
	"Retry": "Pokušaj ponovo",
	"Return": "Vrati",
	"SelectContact": "Izaberite kontakt",
	"SelectMessage": "Odaberite poruku",
	"Send": "Pošalji",
	"SendFail": "Slanje nije moguće",
	"SendFailDesc": "Nije moguće poslati poruku na telefon",
	"Sending": "Slanje Email",
	"SpeedRestriction": "Poruka nije prikazana zbog vaše bezbednosti",
	"Subject": "Predmet: {Sub}",
	"TTSReadFail": "Nije moguće pročitati poruku",
	"TextMessages": "SMS",
	"To": "Za: {To}",
	"UnfinishedEmailMessage": "Nedovršena poruka zahteva vašu pažnju.",
	"Updating": "Ažuriranje",
	"VUIConfirmSend": "Želite li da nastavite slanje ove Email?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Previous",
	"VrHelp_EmailMessageDetail_Help_Left5": "Next",
	"VrHelp_EmailMessageDetail_Help_Right1": "Reply",
	"VrHelp_EmailMessageDetail_Help_Right2": "Reply All",
	"VrHelp_EmailMessageDetail_Help_Right3": "Call",
	"VrHelp_EmailMessageDetail_Help_Right4": "Delete",
	"VrHelp_EmailReply_Help_Left1": "Add Message",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "Kuća:",
	"mobile": "Mobilni:",
	"other": "Ostalo:",
	"work": "Posao:",
};

framework.registerAppDictLoaded("email", "sr_RS");