var Localization_emailAppDict_en_US = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Attachment Not Supported",
	"AutoDownload": "Emails Downloaded",
	"Back": "Back",
	"Bcc": "Bcc: {Bcc}",
	"Cc": "Cc: {Cc}",
	"ContinueEmail": "Continue Email",
	"Delete": "Delete",
	"DeleteFail": "Unable to Delete",
	"DeleteFailDesc": "Unable to Delete Message",
	"Discard": "Discard",
	"DiscardConfirm": "Would you like to discard this message?",
	"DownloadFail": "Unable to Download",
	"DownloadFailDesc": "Unable to Get Information from Phone",
	"DownloadedEmailMessages": "Update Inbox",
	"Email": "Email",
	"EmailDeleteConfirm": "This email will be deleted from the system and your mobile device. It cannot be undone. Are you sure you want to delete?",
	"EmailNotSent": "Unable to Send Email",
	"EmailSent": "Email Sent",
	"From": "From: {From}",
	"Inbox": "Inbox",
	"InboxSelector": "Select Inbox",
	"InstanceDisconnectDesc": "Unable to Connect to Account",
	"ListDownloadFail": "Unable to Download List",
	"Message": "Message: {Msg}",
	"MessagePreset": "Preset Messages",
	"NEW-AllAccounts": "All Accounts",
	"NotificationNotSupported": "Notification Not Supported",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "All Inboxes",
	"Reply": "Reply",
	"Retry": "Retry",
	"Return": "Return",
	"SelectContact": "Select Contact with Line Number",
	"SelectMessage": "Select Message with Line Number",
	"Send": "Send",
	"SendFail": "Unable to Send",
	"SendFailDesc": "Unable to Send Message to Phone",
	"Sending": "Sending Email",
	"SpeedRestriction": "For your safety the message cannot be displayed.",
	"Subject": "Subject: {Sub}",
	"TTSReadFail": "Unable to Read Message",
	"TextMessages": "Text Messages",
	"To": "To: {To}",
	"UnfinishedEmailMessage": "Unfinished message. If you want to edit a new message, the previous message will be deleted. Would you like to discard the previous message?",
	"Updating": "Updating",
	"VUIConfirmSend": "Do you want to continue sending this email?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Previous",
	"VrHelp_EmailMessageDetail_Help_Left5": "Next",
	"VrHelp_EmailMessageDetail_Help_Right1": "Reply",
	"VrHelp_EmailMessageDetail_Help_Right2": "Reply All",
	"VrHelp_EmailMessageDetail_Help_Right3": "Call",
	"VrHelp_EmailMessageDetail_Help_Right4": "Delete",
	"VrHelp_EmailReply_Help_Left1": "Add Message",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "Home:",
	"mobile": "Mobile:",
	"other": "Other:",
	"work": "Work:",
};

framework.registerAppDictLoaded("email", "en_US");