var Localization_emailAppDict_lt_LT = {
	//"stringId" : "localString"
	"AttachmentsNotSupported": "Nepalaikomas priedas",
	"AutoDownload": "Emaili atsisiųsti",
	"Back": "Atgal",
	"Bcc": "Taip pat:  {Bcc} ",
	"Cc": "Kopija:  {Cc}",
	"ContinueEmail": "Tęskite Email formavimą",
	"Delete": "Naikinti",
	"DeleteFail": "Nepavyko panaikinti",
	"DeleteFailDesc": "Nepavyko panaikinti žinutės",
	"Discard": "Atmesti",
	"DiscardConfirm": "Ar norite atmesti dabartinę žinutę?",
	"DownloadFail": "Nepavyko atsiųsti",
	"DownloadFailDesc": "Nepavyko gauti informacijos iš telefono",
	"DownloadedEmailMessages": "Naujinama pašto dėžė",
	"Email": "Email",
	"EmailDeleteConfirm": "Šis Email bus panaikintas iš mobiliojo įrenginio, anuliuoti šio veiksmo negalima. Ar tikrai norite panaikinti?",
	"EmailNotSent": "Email nebuvo išsiųstas",
	"EmailSent": "Email išsiųstas",
	"From": "Nuo: {From}",
	"Inbox": "Gautų laiškų",
	"InboxSelector": "Pasirinkite abonemento aplanką",
	"InstanceDisconnectDesc": "Negalima prisijungti porie abonemento",
	"ListDownloadFail": "Nepavyko atsiųsti sąrašo",
	"Message": "Žinutė: {Msg}",
	"MessagePreset": "Žinutės šablonas",
	"NEW-AllAccounts": "Visos paskyros",
	"NotificationNotSupported": "Pranešimas nepalaikomas",
	"NowViewing": "{AccountSelected}",
	"NowViewingAllInboxes": "Visi gautieji apl.",
	"Reply": "Atsakyti",
	"Retry": "Bandyti dar kartą",
	"Return": "Grįžti",
	"SelectContact": "Pasirinkite kontaktą",
	"SelectMessage": "Pasirinkite žinutę",
	"Send": "Siųsti",
	"SendFail": "Nepavyko išsiųsti",
	"SendFailDesc": "Nepavyko išsiųsti žinutės į telefoną",
	"Sending": "Siunčiamas Email",
	"SpeedRestriction": "Saugos sumetimais žinutė nerodoma",
	"Subject": "Pavadinimas: {Sub}",
	"TTSReadFail": "Nepavyko perskaityti žinutės",
	"TextMessages": "SMS",
	"To": "Kam: {To}",
	"UnfinishedEmailMessage": "Žinutė nebaigta, patikrinkite.",
	"Updating": "Naujinama",
	"VUIConfirmSend": "Ar norite toliau siųsti šį Email?",
	"VrHelp_EmailMessageDetail_Help_Left1": "Communication",
	"VrHelp_EmailMessageDetail_Help_Left2": "Inbox",
	"VrHelp_EmailMessageDetail_Help_Left3": "Play / Pause",
	"VrHelp_EmailMessageDetail_Help_Left4": "Previous",
	"VrHelp_EmailMessageDetail_Help_Left5": "Next",
	"VrHelp_EmailMessageDetail_Help_Right1": "Reply",
	"VrHelp_EmailMessageDetail_Help_Right2": "Reply All",
	"VrHelp_EmailMessageDetail_Help_Right3": "Call",
	"VrHelp_EmailMessageDetail_Help_Right4": "Delete",
	"VrHelp_EmailReply_Help_Left1": "Add Message",
	"VrHelp_EmailReply_Help_Left2": "Send",
	"home": "Namų:",
	"mobile": "Mobilus:",
	"other": "Kiti:",
	"work": "Darbo:",
};

framework.registerAppDictLoaded("email", "lt_LT");