var Localization_vdtAppDict_fi_FI = {
	//"stringId" : "localString"
	"BackButton": "Takaisin",
	"CancelButton": "Peruuta",
	"ClearAllData": "Tyhjennä kaikki tiedot",
	"ClearAllDataFailure": "Kaikkien tietojen poisto epäonnistui",
	"ClearAllDataSuccessful": "Poista kaikki tiedot ok",
	"ClearButton": "Tyhjennä",
	"ClearDataFailure": "Tietoja ei voitu poistaa",
	"ClearDataRetryDialogText": "Kaikkien tietojen tyhjentäminen epäonnistui. Haluatko yrittää uudelleen?",
	"ClearDataSuccess": "Tietojen tyhjentäminen onnistui",
	"ClearingAllData": "Kaikkia tietoja tyhjennetään",
	"ClearingAllDataConfirm": "Tyhjennetäänkö kaikki tiedot?",
	"ConfirmClearAllDataDialogText": "Haluatko varmasti tyhjentää kaikki tiedot?",
	"ConfirmCleariDMDataDialogText": "Haluatko poistaa valitun ajolokin?",
	"ConfirmTurnONDriveChart": "Haluatko varmasti laittaa ajokaavio-asetuksen päälle? ",
	"ConfirmTurnONMyDoctor": "Haluatko varmasti laittaa MyDoctor-asetuksen päälle?",
	"ConfirmTurnONPhoneDataTransfer": "Halutko varmasti käynnistää puhelimen tiedonsiirtoasetuksen?",
	"CopyData": "Kopioi tiedot",
	"CopyDataFailure": "Tietoja ei kopioitu",
	"CopyDataFailureUSBFull": "USB-muisti on täynnä",
	"CopyDataFailureUSBRemoved": "Liitä USB-asema",
	"CopyDataSuccess": "Tietojen kopioiminen USB:lle onnistui",
	"CopyDataSuccessful": "Tiedostojen kopiointi ok",
	"CopyDataUsbFailure": "Tietojen kopiointi USB:lle epäonnistui",
	"CopyingDataToUSB": "Kopioidaan tietoja USB:lle",
	"CopyingDialogText1": "Kopioi USB:lle. Älä irrota asemaa/sammuta autoa.",
	"CopyingDialogText2": "{noOfFilesCopied}/{totalFiles} tiedostoa siirretty.",
	"CouldNotClearAllData": "Kaikkia tietoja ei voitu tyhjentää",
	"DeleteButton": "Poista",
	"DeleteDriveChart": "Poistetaanko nämä ajolokin tiedot?",
	"DeleteDriveChartRetry": "Ajolokin tietoja ei voitu poistaa.  Haluatko yrittää uudelleen?",
	"DriveChartClearSuccess": "Ajotietojen poisto ok",
	"DriveChartData": "Kuljettajakaavion tiedot",
	"DriveChartDataDeleted": "Ajoloki poistettu",
	"DriveChartDataTransfer": "Kuljettajan kaaviotietojen siirto",
	"DriveChartDeleteFailure": "Ajotietojen poisto epäonnistui",
	"DriveChartDeleteSuccess": "Ajotietojen poisto onnistui",
	"DriveChartDeleted": "Ajoloki poistettu",
	"DriveChartDetails": "Kuljettajakaavion tiedot",
	"DriveChartWasNotDeleted": "Ajotietoja ei voitu poistaa",
	"DriveLog": "Ajoloki {logNumber}",
	"DriveRecord": "Ajorekisteri",
	"DriverLog": "Kuskiloki",
	"EditPIN": "Muokkaa PIN-koodia",
	"EnterCurrentPIN": "Anna nykyinen PIN",
	"EnterNewPIN": "Anna uusi 4-numeroinen PIN",
	"EnterYourPIN": "Syötä PIN-koodisi",
	"InsertUSBDialogText": "Tietojen kopiointi USB-laitteelle epäonnistui. Liitä USB-asema ja yritä uudestaan.",
	"InsertUSBTitle": "Tietoja ei voitu kopioida. Liitä USB ja yritä uudelleen.",
	"InsufficientUSBMemory": "Riittämätön USB-muisti",
	"MemoryFullTitle": "Tietoja ei voitu kopioida USB:lle. USB-muisti täynnä.",
	"MyDoctorData": "My Doctor -tiedot  ",
	"MyDoctorDataTransfer": "MyDoctor-tietojen siirto",
	"NoFilesCopy": "Ei kopioitavia tiedostoja",
	"PINChangedToDefault": "Käyttäjän PIN muutettu oletusarvoon",
	"PINNotAccepted": "PIN väärin, syötä toinen PIN.",
	"PhoneDataTransfer": "Puhelintietojen siirto",
	"ProtectionErrorDialogText": "Vain yksi suojattu tieto yhtä kuljettajatunnusta kohti. Poista tiedosto tai ota suojaus pois käytöstä.",
	"RetryButton": "Yritä uudelleen",
	"SelectCopyData": "Kopioi tiedot USB-laitteelle",
	"SendDataRetryDialogText": "Tietojen kopiointi USB-laitteelle epäonnistui. Haluatko yrittää uudelleen?",
	"StartRecording": "Ajolokin tallennus alkaa",
	"StopRecording": "Ajolokin tallennus loppuu",
	"TransferData": "Siirtotiedot",
	"TransferringDataToUSB": "Siirretään tietoja USB:lle",
	"TurnONButton": "Päälle",
	"USBDriveRemoved": "USB-asema irrotettu. Yhdistä USB-asema uudelleen.",
	"USBMemoryFullDialogText": "Tietojen kopiointi USB-laitteelle epäonnistui. USB-muisti on täynnä. Haluatko yrittää uudelleen?",
	"USBTransferTitle": "USB-tietojen kopiointi",
	"UpdatedPIN": "PIN on päivitetty",
	"VDT": "ATS",
	"VTT": "ATS",
	"WrongPIN": "PIN väärin. Yritä uudelleen.",
	"writingToFile": "Kirjoitetaan…",
};

framework.registerAppDictLoaded("vdt", "fi_FI");