var Localization_vdtAppDict_it_IT = {
	//"stringId" : "localString"
	"BackButton": "Indietro",
	"CancelButton": "Annulla",
	"ClearAllData": "Elimina tutti i dati",
	"ClearAllDataFailure": "Cancella tutti gli errori dei dati",
	"ClearAllDataSuccessful": "Cancell. dati riuscita",
	"ClearButton": "Annulla",
	"ClearDataFailure": "Imposs. cancellare dati",
	"ClearDataRetryDialogText": "Impossibile eliminare tutti i dati. Riprovare?",
	"ClearDataSuccess": "Eliminazione dati riuscita.",
	"ClearingAllData": "Cancellando tutti i dati ",
	"ClearingAllDataConfirm": "Cancella tutti i dati? ",
	"ConfirmClearAllDataDialogText": "Eliminare tutti i dati?",
	"ConfirmCleariDMDataDialogText": "Eliminare il reg. di guida selezionato?",
	"ConfirmTurnONDriveChart": "Attivare l'impost. statistiche di guida?",
	"ConfirmTurnONMyDoctor": "Attivare l'impost. MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "ATTIVARE l’impostazione di trasferimento dei dati del telefono?",
	"CopyData": "Copia dati",
	"CopyDataFailure": "Dati non copiati",
	"CopyDataFailureUSBFull": "Memoria USB piena.",
	"CopyDataFailureUSBRemoved": "Inserisci dispositivo USB",
	"CopyDataSuccess": "Copia dati su USB riuscita",
	"CopyDataSuccessful": "Copia dati riuscita",
	"CopyDataUsbFailure": "Copia dei dati su USB non riusc.",
	"CopyingDataToUSB": "Copia dei dati su USB",
	"CopyingDialogText1": "Copia dati su USB. Non rimuovere unità o spegnere la macchina.",
	"CopyingDialogText2": "{noOfFilesCopied} dei {totalFiles} file trasferiti.",
	"CouldNotClearAllData": "Non poteva Cancella tutti i dati ",
	"DeleteButton": "Elimina",
	"DeleteDriveChart": "Eliminare questi dati del reg. di guida?",
	"DeleteDriveChartRetry": "Non è stato possibile eliminare i dati del reg. di guida.  Riprovare?",
	"DriveChartClearSuccess": "Cancellaz. dati di guida riuscita",
	"DriveChartData": "Guidare dati del grafico ",
	"DriveChartDataDeleted": "Registro di guida eliminato",
	"DriveChartDataTransfer": "Trasferimento dati guida",
	"DriveChartDeleteFailure": "Canc. dati statist. di guida non riuscita",
	"DriveChartDeleteSuccess": "Canc. dati statist. di guida riuscita",
	"DriveChartDeleted": "Reg. di guida eliminato",
	"DriveChartDetails": " Dettagli Grafico Guida",
	"DriveChartWasNotDeleted": "Imposs. cancellare dati guida",
	"DriveLog": "Reg. di guida  {logNumber}",
	"DriveRecord": "Archivio di guida",
	"DriverLog": "Registro del pilota",
	"EditPIN": "Modifica PIN ",
	"EnterCurrentPIN": "Inserire PIN corrente.",
	"EnterNewPIN": "Inserire nuovo PIN di 4 cifre.",
	"EnterYourPIN": "Inserisci il tuo PIN ",
	"InsertUSBDialogText": "Impossibile copiare i dati su USB. Inserire un dispositivo USB e riprovare.",
	"InsertUSBTitle": "Imposs. copiare dati. Reinserire unità USB e riprovare.",
	"InsufficientUSBMemory": "Memoria USB insufficiente ",
	"MemoryFullTitle": "Imposs. copiare dati su USB. Memoria USB piena.",
	"MyDoctorData": "MyDoctor dati ",
	"MyDoctorDataTransfer": "Trasf. dati Mydoctor",
	"NoFilesCopy": "Nessun file da copiare",
	"PINChangedToDefault": "PIN tornato al valore predef.",
	"PINNotAccepted": "PIN non accettato, digitare un PIN diverso.",
	"PhoneDataTransfer": "Trasf. dati telefono",
	"ProtectionErrorDialogText": "È consentito un solo file protetto per l'ID Conducente. Eliminare un file o disattivare la protezione.",
	"RetryButton": "Riprova",
	"SelectCopyData": "Copia i dati su USB",
	"SendDataRetryDialogText": "Impossibile copiare tutti i dati su USB. Riprovare?",
	"StartRecording": "Inizio registrazione  ",
	"StopRecording": "Fine registrazione  ",
	"TransferData": "Il trasferimento dei dati ",
	"TransferringDataToUSB": "Trasferimento dati USB ",
	"TurnONButton": "Accendi",
	"USBDriveRemoved": "Drive USB Rimosso. Ricollegare unità USB ",
	"USBMemoryFullDialogText": "Impossibile copiare i dati su USB. Memoria USB piena. Riprovare?",
	"USBTransferTitle": "Copia dati USB",
	"UpdatedPIN": "PIN è stato aggiornato ",
	"VDT": "TTV",
	"VTT": "TTV",
	"WrongPIN": "PIN errato. Riprovare",
	"writingToFile": "Scrivendo dati ",
};

framework.registerAppDictLoaded("vdt", "it_IT");