var Localization_vdtAppDict_en_US = {
	//"stringId" : "localString"
	"BackButton": "Back",
	"CancelButton": "Cancel",
	"ClearAllData": "Clear All Data",
	"ClearAllDataFailure": "Clear All Data Failure",
	"ClearAllDataSuccessful": "Clear All Data Okay",
	"ClearButton": "Clear",
	"ClearDataFailure": "Could Not Clear Data",
	"ClearDataRetryDialogText": "Could not Clear All Data. Would you like to try again?",
	"ClearDataSuccess": "Successful Data Clear",
	"ClearingAllData": "Clearning All Data",
	"ClearingAllDataConfirm": "Clear All Data?",
	"ConfirmClearAllDataDialogText": "Are you sure you would you like to Clear All Data?",
	"ConfirmCleariDMDataDialogText": "Would you like to delete the selected Drive Log?",
	"ConfirmTurnONMyDoctor": "Are you sure you want to turn ON MyDoctor setting?",
	"ConfirmTurnONPhoneDataTransfer": "Are you sure you want to turn ON Phone Data Transfer setting?",
	"ConfirmTurnONPhoneDriveChart": "Are you sure you want to turn ON Phone Drive Chart setting?",
	"CopyData": "Copy Data",
	"CopyDataFailure": "Data Not Copied",
	"CopyDataFailureUSBFull": "USB Memory Full",
	"CopyDataFailureUSBRemoved": "Insert USB Drive",
	"CopyDataSuccess": "Copy Data to USB Success",
	"CopyDataSuccessful": "Copy Data Okay",
	"CopyDataUsbFailure": "Copy Data to USB Failure",
	"CopyingDataToUSB": "Copying Data to USB",
	"CopyingDialogText1": "Copying Data to USB Do not Remove Drive or Turn Off Car.",
	"CopyingDialogText2": "{noOfFilesCopied} of {totalFiles} files transferred.",
	"CouldNotClearAllData": "Could Not Clear All Data ",
	"DeleteButton": "Delete",
	"DeleteDriveChart": "Delete this Drive Log Data?",
	"DeleteDriveChartRetry": "Could not delete Drive Log Data.  Would you like to try again?",
	"DriveChartClearSuccess": "Drive Data Clear Okay",
	"DriveChartData": "Drive Chart Data",
	"DriveChartDataDeleted": "Drive Log Deleted",
	"DriveChartDataTransfer": "Driver Chart Data transfer",
	"DriveChartDeleteFailure": "Drive Chart Data could not be Cleared",
	"DriveChartDeleteSuccess": "Successful Drive Log Data Clear",
	"DriveChartDeleted": "Drive Log Deleted",
	"DriveChartDetails": "Drive Chart Details",
	"DriveChartWasNotDeleted": "Could Not Clear Drive Data",
	"DriveLog": "Drive Log {logNumber}",
	"DriveRecord": "Drive Record",
	"DriverLog": "Driver Log",
	"EditPIN": "Edit PIN",
	"EnterCurrentPIN": "Enter the Current PIN",
	"EnterNewPIN": "Enter New 4-Digit PIN",
	"EnterYourPIN": "Enter Your PIN",
	"InsertUSBDialogText": "Could not Copy Data to USB. Insert USB Drive and try again.",
	"InsertUSBTitle": "Could not Copy Data. Insert USB Drive and try again.",
	"InsufficientUSBMemory": "Insufficient USB Memory",
	"MemoryFullTitle": "Could not Copy Data to USB. USB Memory Full.",
	"MyDoctorData": "My Doctor Data  ",
	"MyDoctorDataTransfer": "MyDoctor Data Transfer",
	"NoFilesCopy": "No Files to Copy",
	"PINChangedToDefault": "User PIN changed to Default",
	"PINNotAccepted": "PIN not accepted, Please enter a different PIN.",
	"PhoneDataTransfer": "Phone Data Transfer",
	"ProtectionErrorDialogText": "Only 1 protected file per Driver ID is allowed. Delete a file or turn Off protection.",
	"RetryButton": "Retry",
	"SelectCopyData": "Copy Data to USB",
	"SendDataRetryDialogText": "Could not Copy Data to USB. Would you like to try again?",
	"StartRecording": "Start Recording Drive Log",
	"StopRecording": "Stop Recording Drive Log",
	"TransferData": "Transfer Data",
	"TransferringDataToUSB": "Transferring Data to USB",
	"TurnONButton": "Turn ON",
	"USBDriveRemoved": "USB Drive Removed. Reconnect USB Drive",
	"USBMemoryFullDialogText": "Could not Copy Data to USB. USB Memory Full. Would you like to try again?",
	"USBTransferTitle": "USB Data Copy",
	"UpdatedPIN": "PIN has been Updated ",
	"VDT": "VTT",
	"VTT": "VTT",
	"WrongPIN": "Wrong PIN.  Please try again.",
	"writingToFile": "Writing…",
};

framework.registerAppDictLoaded("vdt", "en_US");