var Localization_vdtAppDict_es_ES = {
	//"stringId" : "localString"
	"BackButton": "Atrás",
	"CancelButton": "Cancelar",
	"ClearAllData": "Borrar todos los datos",
	"ClearAllDataFailure": "Error al despejar todos los datos",
	"ClearAllDataSuccessful": "Despejar todos los datos aceptados",
	"ClearButton": "Borrar",
	"ClearDataFailure": "No se pueden despejar los datos",
	"ClearDataRetryDialogText": "No se pueden borrar todos los datos. ¿Desea probar otra vez?",
	"ClearDataSuccess": "Limpieza de datos realizada con éxito",
	"ClearingAllData": "Borrando todos los datos",
	"ClearingAllDataConfirm": "¿Borrar todos los datos?",
	"ConfirmClearAllDataDialogText": "¿Está seguro de que quiere eliminar todos los datos?",
	"ConfirmCleariDMDataDialogText": "¿Desea eliminar el Archivo de Conducción seleccionado?",
	"ConfirmTurnONDriveChart": "¿Seguro que desea activar la configuración del mapa de conducción?",
	"ConfirmTurnONMyDoctor": "¿Seguro que desea activar la configuración de MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "¿Está seguro de que quiere activar la configuración de transferencia de datos del teléfono?",
	"CopyData": "Copiar datos",
	"CopyDataFailure": "No se han copiado los datos",
	"CopyDataFailureUSBFull": "Memoria USB Llena",
	"CopyDataFailureUSBRemoved": "Insertar USB",
	"CopyDataSuccess": "Copia de datos a USB correcta",
	"CopyDataSuccessful": "Copia de datos aceptada",
	"CopyDataUsbFailure": "Error al copiar datos a USB ",
	"CopyingDataToUSB": "Copia de datos a USB",
	"CopyingDialogText1": "Copia de datos a USB. No lo extraiga ni apague coche.",
	"CopyingDialogText2": "{noOfFilesCopied} de {totalFiles}archivos transferidos.",
	"CouldNotClearAllData": "No se han podido borrar los datos",
	"DeleteButton": "Eliminar",
	"DeleteDriveChart": "¿Quiere eliminar los datos del Archivo de conducción?",
	"DeleteDriveChartRetry": "No se han podido eliminar los datos del Archivo de conducción  ¿Le gustaría intentarlo de nuevo?",
	"DriveChartClearSuccess": "Despeje de datos de la unidad correcto",
	"DriveChartData": "Datos del gráfico de conducción",
	"DriveChartDataDeleted": "Archivo de conducción eliminado",
	"DriveChartDataTransfer": "Transf. datos conducción",
	"DriveChartDeleteFailure": "Eliminación de datos de mapa de unidad incorrecta",
	"DriveChartDeleteSuccess": "Eliminación de datos de mapa de unidad correcta",
	"DriveChartDeleted": "Archivo de conducción eliminado",
	"DriveChartDetails": "Detalles del gráfico de conducción",
	"DriveChartWasNotDeleted": "No se pueden despejar datos de unidad",
	"DriveLog": "Archivo de conducción {logNumber}",
	"DriveRecord": "Regist. de cond.",
	"DriverLog": "Archivo del Conductor",
	"EditPIN": "Editar PIN",
	"EnterCurrentPIN": "Introducir PIN actual",
	"EnterNewPIN": "Introducir PIN nuevo de 4 dígitos",
	"EnterYourPIN": "Introduzca su PIN",
	"InsertUSBDialogText": "No se pueden copiar los datos al USB. Insertar USB y probar otra vez.",
	"InsertUSBTitle": "No se pueden copiar datos. Inserte una unidad USB y vuelva a intentarlo.",
	"InsufficientUSBMemory": "Memoria USB insuficiente",
	"MemoryFullTitle": "No se pueden copiar datos a USB. Memoria USB llena.",
	"MyDoctorData": "Datos de My Doctor  ",
	"MyDoctorDataTransfer": "Transferencia de datos MyDoctor",
	"NoFilesCopy": "No hay archivos para copiar",
	"PINChangedToDefault": "PIN de usuario cambiado a predeterminado",
	"PINNotAccepted": "PIN no válido. Introduzca un nuevo PIN.",
	"PhoneDataTransfer": "Transferencia de datos del tel.",
	"ProtectionErrorDialogText": "Solo se permite 1 archivo protegido por ID de conductor. Elimine un archivo o quite la protección.",
	"RetryButton": "Reintentar",
	"SelectCopyData": "Copiar datos a USB",
	"SendDataRetryDialogText": "No se pueden copiar los datos al USB. ¿Desea probar otra vez?",
	"StartRecording": "Iniciar Archivo Grabc. Cond.",
	"StopRecording": "Detener Archivo Grabc.Cond.",
	"TransferData": "Transferir datos",
	"TransferringDataToUSB": "Transfiriendo datos a USB",
	"TurnONButton": "Activar",
	"USBDriveRemoved": "Unidad USB desconectada. Vuelva a conectar la unidad USB. ",
	"USBMemoryFullDialogText": "No se pueden copiar los datos al USB. La memoria está llena. ¿Desea probar otra vez?",
	"USBTransferTitle": "Copia de datos a USB",
	"UpdatedPIN": "El PIN se ha actualizado",
	"VDT": "Transf. de información",
	"VTT": "Transf. de información",
	"WrongPIN": "PIN incorrecto. Vuelva a intentarlo.",
	"writingToFile": "Escribiendo...",
};

framework.registerAppDictLoaded("vdt", "es_ES");