var Localization_vdtAppDict_es_MX = {
	//"stringId" : "localString"
	"BackButton": "Atrás",
	"CancelButton": "Cancelar",
	"ClearAllData": "Borrar todos los datos",
	"ClearAllDataFailure": "Falló el borrado de todos los datos",
	"ClearAllDataSuccessful": "Se borraron todos los datos correct.",
	"ClearButton": "Borrar",
	"ClearDataFailure": "No se pudieron borrar los datos",
	"ClearDataRetryDialogText": "No se pueden borrar todos los datos. ¿Desea probar otra vez?",
	"ClearDataSuccess": "Limpieza de datos realizada con éxito",
	"ClearingAllData": "Borrando todos los datos",
	"ClearingAllDataConfirm": "¿Borrar todos los datos?",
	"ConfirmClearAllDataDialogText": "¿Está seguro de que quiere eliminar todos los datos?",
	"ConfirmCleariDMDataDialogText": "¿Desea eliminar el Archivo de Conducción seleccionado?",
	"ConfirmTurnONDriveChart": "¿Está seguro de que desea activar la configuración del gráfico de conducción?",
	"ConfirmTurnONMyDoctor": "¿Está seguro de que desea activar la configuración de MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "¿Está seguro de que quiere ENCENDER la configuración de la transferencia de información del teléfono?",
	"CopyData": "Copiar datos",
	"CopyDataFailure": "No se copiaron los datos",
	"CopyDataFailureUSBFull": "Memoria USB Llena",
	"CopyDataFailureUSBRemoved": "Insertar USB",
	"CopyDataSuccess": "Se copiaron los datos al USB correctamente",
	"CopyDataSuccessful": "Copia de datos correcta",
	"CopyDataUsbFailure": "Falló la copia de datos a USB",
	"CopyingDataToUSB": "Copia de datos a USB",
	"CopyingDialogText1": "La copia de datos a USB no elimina la unidad ni apaga el automóvil.",
	"CopyingDialogText2": "{noOfFilesCopied} de {totalFiles}archivos transferidos.",
	"CouldNotClearAllData": "No fue posible borrar los datos ",
	"DeleteButton": "Eliminar",
	"DeleteDriveChart": "¿Eliminar este Archivo de Conducción?",
	"DeleteDriveChartRetry": "No se pudo eliminar la información del Archivo de Conducción.  ¿Desea intentarlo de nuevo?",
	"DriveChartClearSuccess": "Se borraron los datos de la unidad correctamente",
	"DriveChartData": "Datos del gráfico de conducción",
	"DriveChartDataDeleted": "Se registro de conducción eliminados",
	"DriveChartDataTransfer": "Transf. de datos de conducción",
	"DriveChartDeleteFailure": "Error al eliminar los datos de Drive Chart",
	"DriveChartDeleteSuccess": "Se eliminaron los datos de Drive Chart correctamente",
	"DriveChartDeleted": "Se Archivo de Conducción eliminados",
	"DriveChartDetails": "Detalles del gráfico de conducción",
	"DriveChartWasNotDeleted": "No se pudieron borrar datos de unidad",
	"DriveLog": "Archivo de Conducción {logNumber}",
	"DriveRecord": "Regist. de cond.",
	"DriverLog": "Archivo del cond.",
	"EditPIN": "Editar PIN",
	"EnterCurrentPIN": "Introduzca el PIN actual",
	"EnterNewPIN": "Introduzca un nuevo PIN de 4 dígitos",
	"EnterYourPIN": "Introduzca su PIN",
	"InsertUSBDialogText": "No se pueden copiar los datos al USB. Insertar USB y probar otra vez.",
	"InsertUSBTitle": "No se pudieron copiar los datos. Inserte la unidad USB y vuelva a intentarlo.",
	"InsufficientUSBMemory": "Memoria USB insuficiente",
	"MemoryFullTitle": "No se pudieron copiar los datos a USB. Memoria de USB llena.",
	"MyDoctorData": "Datos de My Doctor  ",
	"MyDoctorDataTransfer": "Transf. de datos de MyDoctor",
	"NoFilesCopy": "No hay archivos para copiar",
	"PINChangedToDefault": "El PIN del usuario cambió al predeterminado",
	"PINNotAccepted": "PIN no aceptado. Ingrese un PIN diferente.",
	"PhoneDataTransfer": "Transferencia de datos del tel.",
	"ProtectionErrorDialogText": "Solo se permite 1 archivo protegido por ID de conductor. Elimine un archivo o quite la protección.",
	"RetryButton": "Reintentar",
	"SelectCopyData": "Copiar datos a USB",
	"SendDataRetryDialogText": "No se pueden copiar los datos al USB. ¿Desea probar otra vez?",
	"StartRecording": "Iniciar Archivo Grabc. Cond.",
	"StopRecording": "Detener Archivo.Grabc.Cond.",
	"TransferData": "Transferir datos",
	"TransferringDataToUSB": "Transfiriendo datos a USB",
	"TurnONButton": "Encender",
	"USBDriveRemoved": "Unidad USB desconectada. Vuelva a conectar la unidad USB. ",
	"USBMemoryFullDialogText": "No se pueden copiar los datos al USB. La memoria está llena. ¿Desea probar otra vez?",
	"USBTransferTitle": "Copia de datos de USB",
	"UpdatedPIN": "El PIN se ha actualizado",
	"VDT": "Transf. de información",
	"VTT": "Transf. de información",
	"WrongPIN": "PIN incorrecto. Intente de nuevo.",
	"writingToFile": "Escribiendo...\n",
};

framework.registerAppDictLoaded("vdt", "es_MX");