var Localization_vdtAppDict_mn_TW = {
	//"stringId" : "localString"
	"BackButton": "回上頁",
	"CancelButton": "取消",
	"ClearAllData": "清除所有資料",
	"ClearAllDataFailure": "清除所有資料失敗",
	"ClearAllDataSuccessful": "成功清除所有資料",
	"ClearButton": "清除",
	"ClearDataFailure": "無法清除資料",
	"ClearDataRetryDialogText": "無法清除所有資料。 要重試嗎?",
	"ClearDataSuccess": "已順利清除資料",
	"ClearingAllData": "正在清除所有資料",
	"ClearingAllDataConfirm": "清除所有資料?",
	"ConfirmClearAllDataDialogText": "您確定要清除所有資料嗎?",
	"ConfirmCleariDMDataDialogText": "要刪除選定磁碟機記錄嗎?",
	"ConfirmTurnONDriveChart": "您確定要開啟駕駛圖表設定？",
	"ConfirmTurnONMyDoctor": "您確定要開啟我的修理設定？",
	"ConfirmTurnONPhoneDataTransfer": "您確定要開啟手機資料傳輸設定？",
	"CopyData": "複製資料",
	"CopyDataFailure": "資料未複製",
	"CopyDataFailureUSBFull": "USB 記憶體已滿",
	"CopyDataFailureUSBRemoved": "請插入 USB 磁碟機",
	"CopyDataSuccess": "複製資料到 USB 成功",
	"CopyDataSuccessful": "成功複製資料",
	"CopyDataUsbFailure": "複製資料到 USB 失敗",
	"CopyingDataToUSB": "正在將資料複製到 USB",
	"CopyingDialogText1": "正在將資料複製到USB。請勿刪除駕駛或關掉車輛。",
	"CopyingDialogText2": "已傳送 {noOfFilesCopied} 個檔案，共 {totalFiles} 個檔案。",
	"CouldNotClearAllData": "無法清除所有資料",
	"DeleteButton": "刪除",
	"DeleteDriveChart": "刪除此駕駛圖表資料?",
	"DeleteDriveChartRetry": "無法清除所有駕駛圖表資料。  要重試嗎?",
	"DriveChartClearSuccess": "同意駕駛資料清除",
	"DriveChartData": "駕駛圖表資料",
	"DriveChartDataDeleted": "已刪除駕駛圖表資料",
	"DriveChartDataTransfer": "駕駛圖表資料傳輸",
	"DriveChartDeleteFailure": "駕駛圖表資料刪除失敗",
	"DriveChartDeleteSuccess": "駕駛圖表資料刪除成功",
	"DriveChartDeleted": "已移除駕駛圖表",
	"DriveChartDetails": "駕駛圖表詳細資料",
	"DriveChartWasNotDeleted": "駕駛圖表未被移除",
	"DriveLog": "駕駛記錄 {logNumber}",
	"DriveRecord": "駕駛記錄",
	"DriverLog": "駕駛記錄",
	"EditPIN": "編輯密碼",
	"EnterCurrentPIN": "請輸入舊密碼",
	"EnterNewPIN": "請輸入新密碼",
	"EnterYourPIN": "請輸入您的 PIN",
	"InsertUSBDialogText": "無法將資料複製到 USB。 請插入 USB 磁碟機並重試。",
	"InsertUSBTitle": "無法複製資料。 插入 USB 磁碟，然後再試一次。",
	"InsufficientUSBMemory": "USB 記憶體不足",
	"MemoryFullTitle": "無法複製資料到 USB。 USB 記憶體已滿。",
	"MyDoctorData": "我的修理資料",
	"MyDoctorDataTransfer": "我的修理資料傳輸－電話",
	"NoFilesCopy": "沒有檔案可複製",
	"PINChangedToDefault": "使用者 PIN 已變更成預設值",
	"PINNotAccepted": "不接受 PIN，請輸入其他 PIN。",
	"PhoneDataTransfer": "手機資料傳輸",
	"ProtectionErrorDialogText": "每個駕駛員 ID 只容許具有 1 個保護檔案。 刪除檔案或關閉保護。",
	"RetryButton": "重試",
	"SelectCopyData": "將資料複製到 USB",
	"SendDataRetryDialogText": "無法將資料複製到 USB。 要重試嗎?",
	"StartRecording": "開始記錄駕駛記錄",
	"StopRecording": "停止記錄駕駛記錄",
	"TransferData": "傳輸資料",
	"TransferringDataToUSB": "正在傳輸資料至 USB",
	"TurnONButton": "開啟",
	"USBDriveRemoved": "USB 磁碟機已移除。重新連接 USB 磁碟機。",
	"USBMemoryFullDialogText": "無法將資料複製到 USB。 USB 記憶體已滿。 要重試嗎?",
	"USBTransferTitle": "USB 資料複製",
	"UpdatedPIN": "已更新 PIN",
	"VDT": "車子遙感傳輸",
	"VTT": "車子遙感傳輸",
	"WrongPIN": "密碼錯誤。請重試。",
	"writingToFile": "正在寫入檔案。",
};

framework.registerAppDictLoaded("vdt", "mn_TW");