var Localization_vdtAppDict_zh_CN = {
	//"stringId" : "localString"
	"BackButton": "返回",
	"CancelButton": "取消",
	"ClearAllData": "清除所有数据",
	"ClearAllDataFailure": "清除所有数据失败",
	"ClearAllDataSuccessful": "已成功清除所有数据",
	"ClearButton": "清除",
	"ClearDataFailure": "无法清除数据",
	"ClearDataRetryDialogText": "无法清除所有数据。您是否希望重试？",
	"ClearDataSuccess": "数据清除成功",
	"ClearingAllData": "清除所有数据",
	"ClearingAllDataConfirm": "清除所有数据？",
	"ConfirmClearAllDataDialogText": "您确定要清除所有数据吗？",
	"ConfirmCleariDMDataDialogText": "是否要删除所选驾驶日志？",
	"ConfirmTurnONDriveChart": "您确定要打开“驾驶图”设置吗？",
	"ConfirmTurnONMyDoctor": "您确定要打开“MyDoctor”设置吗？",
	"ConfirmTurnONPhoneDataTransfer": "您确定要开启“电话数据传输”设置?",
	"CopyData": "复制数据",
	"CopyDataFailure": "未复制数据",
	"CopyDataFailureUSBFull": "USB 存储器已满",
	"CopyDataFailureUSBRemoved": "插入 USB 驱动器",
	"CopyDataSuccess": "成功将数据复制到 USB",
	"CopyDataSuccessful": "已成功复制数据",
	"CopyDataUsbFailure": "将数据复制到 USB 失败",
	"CopyingDataToUSB": "正将数据复制到 USB",
	"CopyingDialogText1": "将数据复制到 USB 设备不要卸下驱动器或关闭汽车。",
	"CopyingDialogText2": "传输了 {noOfFilesCopied} 个（共 {totalFiles} 个）文件。",
	"CouldNotClearAllData": "无法清除所有数据 ",
	"DeleteButton": "删除",
	"DeleteDriveChart": "删除此驾驶日志数据?",
	"DeleteDriveChartRetry": "无法删除驾驶日志数据。  您想再试一次?",
	"DriveChartClearSuccess": "已成功清除驾驶数据",
	"DriveChartData": "驾驶图数据",
	"DriveChartDataDeleted": "已删除驾驶日志",
	"DriveChartDataTransfer": "驾驶图数据传输",
	"DriveChartDeleteFailure": "删除驾驶图数据失败",
	"DriveChartDeleteSuccess": "已成功删除驾驶图数据",
	"DriveChartDeleted": "已删除驾驶日志",
	"DriveChartDetails": "驾驶图详情",
	"DriveChartWasNotDeleted": "未删除驾驶图",
	"DriveLog": "驾驶记录{logNumber}",
	"DriveRecord": "驾驶记录",
	"DriverLog": "驾驶员日志",
	"EditPIN": "编辑 PIN",
	"EnterCurrentPIN": "输入当前 PIN",
	"EnterNewPIN": "输入新的 4 位数 PIN",
	"EnterYourPIN": "输入您的 PIN",
	"InsertUSBDialogText": "无法将数据复制到 USB。插入 USB 驱动器，然后重试。",
	"InsertUSBTitle": "无法复制数据。 插入 USB 驱动器，然后重试。",
	"InsufficientUSBMemory": "USB 存储器不足",
	"MemoryFullTitle": "无法将数据复制到 USB。 USB 存储器已满。",
	"MyDoctorData": "我的医生数据  ",
	"MyDoctorDataTransfer": "MyDoctor 数据传输",
	"NoFilesCopy": "没有供复制的文件",
	"PINChangedToDefault": "用户 PIN 已更改为默认设置",
	"PINNotAccepted": "不接受 PIN，请输入不同的 PIN。",
	"PhoneDataTransfer": "电话数据传输",
	"ProtectionErrorDialogText": "每张驾驶证仅允许 1 个受保护文件。删除一个文件或关闭保护。",
	"RetryButton": "重试",
	"SelectCopyData": "将数据复制到 USB",
	"SendDataRetryDialogText": "无法将数据复制到 USB。您是否希望重试？",
	"StartRecording": "开始记录驾驶日志",
	"StopRecording": "停止记录驾驶日志",
	"TransferData": "传输数据",
	"TransferringDataToUSB": "将数据传输到 USB 设备",
	"TurnONButton": "打开",
	"USBDriveRemoved": "USB 驱动器已卸下。 重新连接 USB 驱动器。 ",
	"USBMemoryFullDialogText": "无法将数据复制到 USB。USB 存储器已满。您是否希望重试？",
	"USBTransferTitle": "USB 数据复制",
	"UpdatedPIN": "PIN 已更新",
	"VDT": "车辆遥测传输 ",
	"VTT": "车辆遥测传输 (VTT)",
	"WrongPIN": "错误 PIN。  请重试。",
	"writingToFile": "正在写入…",
};

framework.registerAppDictLoaded("vdt", "zh_CN");