var Localization_vdtAppDict_he_IL = {
	//"stringId" : "localString"
	"BackButton": "חזור",
	"CancelButton": "בטל",
	"ClearAllData": "נקה את כל הנתונים",
	"ClearAllDataFailure": "ניקיון כל הנתונים נכשל",
	"ClearAllDataSuccessful": "נקה את כל הנתונים אישור",
	"ClearButton": "נקה",
	"ClearDataFailure": "לא ניתן לנקות נתונים",
	"ClearDataRetryDialogText": "לא ניתן למחוק נתונים. האם תרצה לנסות שנית?",
	"ClearDataSuccess": "הנתונים נוקו בהצלחה",
	"ClearingAllData": "ניקוי כל הנתונים",
	"ClearingAllDataConfirm": "נקה את כל הנתונים?",
	"ConfirmClearAllDataDialogText": "האם אתה בטוח שברצונך למחוק את כל הנתונים?",
	"ConfirmCleariDMDataDialogText": "האם תרצה למחוק את יומן הנהיגה הנבחר?",
	"ConfirmTurnONDriveChart": "האם אתה בטוח שברצונך להפעיל הגדרות תרשים נהיגה?",
	"ConfirmTurnONMyDoctor": "האם אתה בטוח שברצונך להפעיל הגדרות MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "האם אתה בטוח שברצונך להפעיל את הגדרות העברת נתוני הטלפון?",
	"CopyData": "העתק נתונים",
	"CopyDataFailure": "הנתונים לא הועתקו",
	"CopyDataFailureUSBFull": "זכרון USB מלא",
	"CopyDataFailureUSBRemoved": "הכנס כונן USB",
	"CopyDataSuccess": "העתקת נתונים ל-USB הצליחה",
	"CopyDataSuccessful": "העתק נתונים אישור",
	"CopyDataUsbFailure": "העתקת נתונים ל-USB נכשלה",
	"CopyingDataToUSB": "מעתיק נתונים ל-USB",
	"CopyingDialogText1": "מעתיק נתונים ל-USB אל תוציא את הכונן ואל תכבה את המנוע.",
	"CopyingDialogText2": "{noOfFilesCopied} מתוך {totalFiles} קבצים הועברו.",
	"CouldNotClearAllData": "לא היתה אפשרות לנקות את כל הנתונים ",
	"DeleteButton": "מחק",
	"DeleteDriveChart": "למחוק נתוני יומן נסיעה אלה?",
	"DeleteDriveChartRetry": "לא ניתן למחוק את הנתונים ביומן הנסיעה.  האם ברצונך לנסות שוב?",
	"DriveChartClearSuccess": "נקה נתוני כונן אישור",
	"DriveChartData": "נתוני תרשים נהיגה",
	"DriveChartDataDeleted": "יומן הנסיעה נמחק",
	"DriveChartDataTransfer": "העברת נתוני תרשים נהיגה",
	"DriveChartDeleteFailure": "מחיקת נתוני תרשים הנהיגה נכשלה",
	"DriveChartDeleteSuccess": "מחיקת נתוני תרשים הנהיגה הצליחה",
	"DriveChartDeleted": "יומן הנסיעה נמחק",
	"DriveChartDetails": "פרטי תרשים נהיגה",
	"DriveChartWasNotDeleted": "לא ניתן לנקות את נתוני הכונן",
	"DriveLog": "יומן נהיגה {logNumber}",
	"DriveRecord": "רשומת נסיעה",
	"DriverLog": "יומן נהג",
	"EditPIN": "ערוך PIN",
	"EnterCurrentPIN": "הזן את ה-PIN הנוכחי",
	"EnterNewPIN": "הזן PIN חדש בן 4 ספרות",
	"EnterYourPIN": "הזן את ה-PIN שלך",
	"InsertUSBDialogText": "לא ניתן להעתיק נתונים ל-USB. הכנס כונן USB ונסה שנית.",
	"InsertUSBTitle": "לא ניתן להעתיק נתונים ל-USB. הכנס כונן USB ונסה שנית.",
	"InsufficientUSBMemory": "אין די זיכרון מסוג USB ",
	"MemoryFullTitle": "לא ניתן להעתיק נתונים ל-USB. זיכרון ה-USB מלא.",
	"MyDoctorData": "נתוני My Doctor",
	"MyDoctorDataTransfer": "העברת נתוני MyDoctor",
	"NoFilesCopy": "אין קבצים להעתקה",
	"PINChangedToDefault": "PIN המשתמש השתנה לברירת המחדל",
	"PINNotAccepted": "PIN לא התקבל, אנא הזן PIN אחר",
	"PhoneDataTransfer": "העברת נתוני טלפון",
	"ProtectionErrorDialogText": "רק קובץ מוגן 1 מותר עבור כל נהג. מחק קובץ או הסר הגנה.",
	"RetryButton": "נסה שנית",
	"SelectCopyData": "העתק נתונים ל-USB",
	"SendDataRetryDialogText": "לא ניתן להעתיק נתונים ל-USB. האם תרצה לנסות שנית?",
	"StartRecording": "הפעל הקלטת יומן נהיגה",
	"StopRecording": "הפסק הקלטת יומן נהיגה",
	"TransferData": " העברת נתונים",
	"TransferringDataToUSB": "מעביר נתונים ל-USB",
	"TurnONButton": "הפעל",
	"USBDriveRemoved": "כונן USB הוסר. חבר מחדש את כונן USB",
	"USBMemoryFullDialogText": "לא ניתן להעתיק נתונים ל-USB. זכרון ה-USB מלא. האם תרצה לנסות שנית?",
	"USBTransferTitle": "העתקת נתוני USB",
	"UpdatedPIN": "PIN עודכן ",
	"VDT": "הנר\"ב",
	"VTT": "הנר\"ב",
	"WrongPIN": "PIN שגוי. נסה שנית.",
	"writingToFile": "כותב…",
};

framework.registerAppDictLoaded("vdt", "he_IL");