var Localization_vdtAppDict_nl_NL = {
	//"stringId" : "localString"
	"BackButton": "Terug",
	"CancelButton": "Annuleren",
	"ClearAllData": "Alle data wissen",
	"ClearAllDataFailure": "Alle datafouten verwijderen",
	"ClearAllDataSuccessful": "Alle data verwijderd",
	"ClearButton": "Wissen",
	"ClearDataFailure": "Verwijderen gegevens mislukt",
	"ClearDataRetryDialogText": "Wissen alle data mislukt. Wilt u het opnieuw proberen?",
	"ClearDataSuccess": "Data gewist",
	"ClearingAllData": "Alle data worden gewist.",
	"ClearingAllDataConfirm": "Alle data wissen?",
	"ConfirmClearAllDataDialogText": "Weet u zeker dat u alle data wilt wissen?",
	"ConfirmCleariDMDataDialogText": "Wilt u de geselecteerde Rittenlogboek verwijderen?",
	"ConfirmTurnONDriveChart": "Weet u zeker dat u de instelling Drive Chart wilt inschakelen?",
	"ConfirmTurnONMyDoctor": "Weet u zeker dat u de instelling MyDoctor wilt inschakelen?",
	"ConfirmTurnONPhoneDataTransfer": "Bent u zeker dat u de telefoongegevensoverdracht wil inschakelen?",
	"CopyData": "Data kopiëren",
	"CopyDataFailure": "Gegevens niet gekopieerd",
	"CopyDataFailureUSBFull": "USB-geheugen vol",
	"CopyDataFailureUSBRemoved": "Plaats USB-stick",
	"CopyDataSuccess": "Gegevens gekopieerd naar USB",
	"CopyDataSuccessful": "Data gekopieerd",
	"CopyDataUsbFailure": "Data kopiëren naar USB mislukt",
	"CopyingDataToUSB": "Data kopiëren naar USB",
	"CopyingDialogText1": "Gegevens kopiëren naar USB, USB-stick niet verwijderen en auto niet uitzetten.",
	"CopyingDialogText2": "{noOfFilesCopied} of {totalFiles} bestanden overgezet.",
	"CouldNotClearAllData": "Kon niet alle data wissen",
	"DeleteButton": "Verwijderen",
	"DeleteDriveChart": "Wil u deze Rittenlogboek gegevens verwijderen?",
	"DeleteDriveChartRetry": "De gegevens van het Rittenlogboek konden niet worden verwijderd.  Wil u het opnieuw proberen?",
	"DriveChartClearSuccess": "Schijfdata verwijderd",
	"DriveChartData": "Drive Chart data",
	"DriveChartDataDeleted": "Rittenlogboek verwijderd",
	"DriveChartDataTransfer": "Drive Chart data overzetten",
	"DriveChartDeleteFailure": "Verwijderen gegevens Drive Chart mislukt",
	"DriveChartDeleteSuccess": "Data Drive Chart verwijderd",
	"DriveChartDeleted": "Rittenlogboek verwijderd",
	"DriveChartDetails": "Drive Chart gegevens",
	"DriveChartWasNotDeleted": "Data konden niet worden verwijderd",
	"DriveLog": "Rittenlogboek {logNumber}",
	"DriveRecord": "Rijbestand",
	"DriverLog": "Bestuurderslogboek",
	"EditPIN": "Bewerken PIN",
	"EnterCurrentPIN": "Voer huidige PIN in",
	"EnterNewPIN": "Voer nieuwe PIN van vier tekens in",
	"EnterYourPIN": "Voer uw PIN in",
	"InsertUSBDialogText": "Data kopiëren naar USB mislukt. Plaats USB-stick en probeer het opnieuw.",
	"InsertUSBTitle": "Data kopiëren mislukt. Voer USB-stick in en probeer opnieuw.",
	"InsufficientUSBMemory": "Onvoldoende USB-geheugen",
	"MemoryFullTitle": "Data kopiëren naar USB mislukt. USB-geheugen vol.",
	"MyDoctorData": "My Doctor data  ",
	"MyDoctorDataTransfer": "Dataoverdracht MyDoctor",
	"NoFilesCopy": "Er zijn geen bestanden om te kopiëren",
	"PINChangedToDefault": "PIN gebruiker gewijzigd in standaard",
	"PINNotAccepted": "De pincode is onjuist. Voer een andere pincode in.",
	"PhoneDataTransfer": "Overdracht telefoondata",
	"ProtectionErrorDialogText": "Slechts 1 beveiligd bestand per bestuurders-ID toegestaan. Verwijder een bestand of schakel beveiliging uit.",
	"RetryButton": "Opnieuw proberen",
	"SelectCopyData": "Data kopiëren naar USB ",
	"SendDataRetryDialogText": "Data kopiëren naar USB mislukt. Wilt u het opnieuw proberen?",
	"StartRecording": "Start opname ",
	"StopRecording": "Stop opname  ",
	"TransferData": "Overzetten Data",
	"TransferringDataToUSB": "Data overzetten naar USB",
	"TurnONButton": "Inschakelen",
	"USBDriveRemoved": "USB-stick verwijderd. Verbind USB-stick opnieuw.",
	"USBMemoryFullDialogText": "Data kopiëren naar USB mislukt. USB-geheugen vol. Wilt u het opnieuw proberen?",
	"USBTransferTitle": "USB Gegevens kopiëren",
	"UpdatedPIN": "PIN is bijgewerkt",
	"VDT": "OVT",
	"VTT": "OVT",
	"WrongPIN": "Verkeerde PIN. Probeer het nog eens.",
	"writingToFile": "Schrijven…",
};

framework.registerAppDictLoaded("vdt", "nl_NL");