var Localization_vdtAppDict_hr_HR = {
	//"stringId" : "localString"
	"BackButton": "Natrag",
	"CancelButton": "Otkaži",
	"ClearAllData": "Obriši sve pod.",
	"ClearAllDataFailure": "Neuspješno brisanje svih podataka",
	"ClearAllDataSuccessful": "Uspješno brisanje svih podataka",
	"ClearButton": "Obriši",
	"ClearDataFailure": "Brisanje podataka nije moguće",
	"ClearDataRetryDialogText": "Sve pod. nije moguće obrisati. Želite li pok. ponovno?",
	"ClearDataSuccess": "Uspješno brisanje pod.",
	"ClearingAllData": "Brisanje svih podataka",
	"ClearingAllDataConfirm": "Briši sve podatke?",
	"ConfirmClearAllDataDialogText": "Jeste li sigurni da želite obrisati sve podatke?",
	"ConfirmCleariDMDataDialogText": "Želite li izbrisati odabrani zapis o vožnji?",
	"ConfirmTurnONDriveChart": "Želite li zaista uključiti postavke tablice s pod. o vožnjama?",
	"ConfirmTurnONMyDoctor": "Želite li zaista uključiti postavke za MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "Jeste li sigurnu da želite UKLJUČITI postavku prijenosa podataka telefona?",
	"CopyData": "Kopiranje podataka",
	"CopyDataFailure": "Podaci nisu kopirani",
	"CopyDataFailureUSBFull": "USB memorija je puna",
	"CopyDataFailureUSBRemoved": "Umetni USB pog.",
	"CopyDataSuccess": "Uspješno kopiranje podataka na USB",
	"CopyDataSuccessful": "Uspješno kopiranje podataka",
	"CopyDataUsbFailure": "Neuspješno kopiranje podataka na USB",
	"CopyingDataToUSB": "Kopiranje podataka na USB",
	"CopyingDialogText1": "Kop. podat. na USB Ne vaditi pogon niti gasiti vozilo.",
	"CopyingDialogText2": "Preneseno je {noOfFilesCopied} od {totalFiles} datoteka.",
	"CouldNotClearAllData": "Svi podaci nisu izbrisani",
	"DeleteButton": "Izbriši",
	"DeleteDriveChart": "Izbriši podatke zapisa vožnje?",
	"DeleteDriveChartRetry": "Nije moguće izbrisati podatke zapisa vožnje.  Želite li pokušati ponovno?",
	"DriveChartClearSuccess": "Uspješno brisanje podataka o vožnjama",
	"DriveChartData": "Tablica s podacima o vožnjama",
	"DriveChartDataDeleted": "Izbrisan je zapis vožnje",
	"DriveChartDataTransfer": "Prij. tablice s pod. o vožnjama",
	"DriveChartDeleteFailure": "Neuspješno brisanje podataka tablice s pod. o vožnjama",
	"DriveChartDeleteSuccess": "Uspješno brisanje podataka tablice s pod. o vožnjama",
	"DriveChartDeleted": "Izbrisan je zapis vožnje",
	"DriveChartDetails": "Poj. iz tablice s pod. o vožnjama",
	"DriveChartWasNotDeleted": "Brisanje podat. o vožnji nije moguće",
	"DriveLog": "Zapis vožnje {logNumber}",
	"DriveRecord": "Evidencija vožnje",
	"DriverLog": "Zapis vozača",
	"EditPIN": "Promijeni PIN",
	"EnterCurrentPIN": "Unesite trenutni PIN",
	"EnterNewPIN": "Unesite novi 4-znamenkasti PIN",
	"EnterYourPIN": "Unesite vaš PIN",
	"InsertUSBDialogText": "Kopiranje pod. na USB nije moguće. Umet. USB pogon i pok. ponovno.",
	"InsertUSBTitle": "Kopiranje podataka nije moguće. Umetnite USB pogon i pokušajte ponovno.",
	"InsufficientUSBMemory": "Nedovoljna memorija na USB pogonu",
	"MemoryFullTitle": "Kopiranje podataka na USB nije moguće. USB memorija je puna. ",
	"MyDoctorData": "Podaci aplikacije My Doctor",
	"MyDoctorDataTransfer": "Prijenos podataka za MyDoctor",
	"NoFilesCopy": "Nema dostupnih datoteka za kopiranje.",
	"PINChangedToDefault": "PIN korisnika promijenjen u zadano",
	"PINNotAccepted": "PIN nije prihvaćen, unesite drugi PIN.",
	"PhoneDataTransfer": "Prijenos podataka telefona",
	"ProtectionErrorDialogText": "ID vozača dozvoljava samo jednu zaštićenu datoteku. Obrišite datoteku ili isključite zaštitu.",
	"RetryButton": "Pokušaj ponovno",
	"SelectCopyData": "Kop. pod. na USB",
	"SendDataRetryDialogText": "Kopiranje pod. na USB nije moguće. Želite li pok. ponovno?",
	"StartRecording": "Počni snimanje zapisa o vožnji",
	"StopRecording": "Zaustavi snimanje zapisa o vožnji",
	"TransferData": "Prijenos podataka",
	"TransferringDataToUSB": "Prijenos podataka na USB",
	"TurnONButton": "Uključi",
	"USBDriveRemoved": "USB pogon je uklonjen. Ponovno spojite USB pogon.",
	"USBMemoryFullDialogText": "Kopiranje pod. na USB nije moguće. USB memorija je puna. Želite li pok. ponovno?",
	"USBTransferTitle": "Kopiranje podataka s USB-a",
	"UpdatedPIN": "PIN je ažuriran ",
	"VDT": "PTV",
	"VTT": "PTV",
	"WrongPIN": "Pogrešan PIN. Pokušajte ponovno.",
	"writingToFile": "Zapisivanje …",
};

framework.registerAppDictLoaded("vdt", "hr_HR");