var Localization_vdtAppDict_el_GR = {
	//"stringId" : "localString"
	"BackButton": "Πίσω",
	"CancelButton": "Ακύρωση",
	"ClearAllData": "Εκκαθάριση των δεδομένων",
	"ClearAllDataFailure": "Απαλοιφή όλων των αποτυχιών δεδομένων",
	"ClearAllDataSuccessful": "Απαλοιφή όλων των δεδομένων ΟΚ",
	"ClearButton": "Εκκαθάριση",
	"ClearDataFailure": "Δεν ήταν δυνατός ο καθαρισμός των δεδομένων",
	"ClearDataRetryDialogText": "Δεν ήταν δυνατή η εκκαθάριση όλων των δεδομένων. Θέλετε να προσπαθήσετε ξανά;",
	"ClearDataSuccess": "Επιτυχής εκκαθάριση δεδομένων",
	"ClearingAllData": "Απαλοιφή όλων των δεδομένων",
	"ClearingAllDataConfirm": "Να γίνει απαλοιφή όλων των δεδομένων;",
	"ConfirmClearAllDataDialogText": "Θέλετε σίγουρα να εκκαθαρίσετε όλα τα δεδομένα;",
	"ConfirmCleariDMDataDialogText": "Θέλετε να διαγράψετε το επιλεγμένο αρχείο οδήγησης;",
	"ConfirmTurnONDriveChart": "Θέλετε σίγουρα να ενεργοποιήσετε τη ρύθμιση διάγραμμα οδήγησης;",
	"ConfirmTurnONMyDoctor": "Θέλετε σίγουρα να ενεργοποιήσετε τη ρύθμιση MyDoctor;",
	"ConfirmTurnONPhoneDataTransfer": "Είστε βέβαιοι ότι θέλετε να ενεργοποιήσετε τη ρύθμιση μεταφοράς δεδομένων τηλεφώνου;",
	"CopyData": "Αντιγραφή δεδομένων",
	"CopyDataFailure": "Δεν έγινε αντιγραφή δεδομένων",
	"CopyDataFailureUSBFull": "Πλήρης μνήμη USB",
	"CopyDataFailureUSBRemoved": "Εισαγωγή μονάδας USB",
	"CopyDataSuccess": "Επιτυχής αντιγραφή δεδομένων σε USB",
	"CopyDataSuccessful": "Αντιγραφή δεδομένων ΟΚ",
	"CopyDataUsbFailure": "Η αντιγραφή δεδομένων σε USB απέτυχε",
	"CopyingDataToUSB": "Αντιγραφή δεδομένων σε USB",
	"CopyingDialogText1": "Αντιγραφή δεδομένων σε USB Μην αφαιρείτε τον οδηγό, μη σβήνετε τον κινητήρα.",
	"CopyingDialogText2": "Μεταφέρθηκαν {noOfFilesCopied} από {totalFiles} αρχεία.",
	"CouldNotClearAllData": "Δεν ήταν δυνατή η απαλοιφή όλων των δεδομένων",
	"DeleteButton": "Διαγραφή",
	"DeleteDriveChart": "Διαγραφή των δεδομένων αυτού του αρχείου καταγραφής οδήγησης;",
	"DeleteDriveChartRetry": "Αδύνατη η διαγραφή των δεδομένων του αρχείου καταγραφής οδήγησης.  Θέλετε να προσπαθήσετε ξανά;",
	"DriveChartClearSuccess": "Απαλοιφή δεδομένων οδήγησης ΟΚ",
	"DriveChartData": "Δεδομένα διαγράμματος οδήγησης",
	"DriveChartDataDeleted": "Το αρχείο καταγραφής οδήγησης διαγράφηκε",
	"DriveChartDataTransfer": "Μεταφορά δεδομένων διαγράμματος οδήγησης ",
	"DriveChartDeleteFailure": "Η διαγραφή δεδομένων διαγράμματος οδήγησης απέτυχε",
	"DriveChartDeleteSuccess": "Η διαγραφή δεδομένων διαγράμματος οδήγησης πέτυχε",
	"DriveChartDeleted": "Το αρχείο καταγραφής οδήγησης διαγράφηκε",
	"DriveChartDetails": "Λεπτομέρειες διαγράμματος οδήγησης",
	"DriveChartWasNotDeleted": "Δεν έγινε απαλοιφή δεδομένων οδηήγησης",
	"DriveLog": "Μονάδα καταγραφής {logNumber}",
	"DriveRecord": "Εγγραφή οδήγησης",
	"DriverLog": "Αρχείο καταγραφής οδηγού",
	"EditPIN": "Επεξεργασία PIN",
	"EnterCurrentPIN": "Καταχώρηση ισχύοντος PIN",
	"EnterNewPIN": "Καταχώρηση νέου 4ψήφιου PIN",
	"EnterYourPIN": "Καταχώρηση του PIN σας",
	"InsertUSBDialogText": "Δεν ήταν δυνατή η αντιγραφή δεδομένων σε USB. Εισαγάγετε τη μονάδα USB και προσπαθήστε ξανά.",
	"InsertUSBTitle": "Δεν ήταν δυνατή η αντιγραφή δεδομένων στο USB. Εισάγετε το USB και ξαναδοκιμάστε.",
	"InsufficientUSBMemory": "Ανεπαρκής μνήμη USB",
	"MemoryFullTitle": "Δεν ήταν δυνατή η αντιγραφή δεδομένων στο USB. Η μνήμη του USB είναι πλήρης.",
	"MyDoctorData": "Δεδομένα My Doctor",
	"MyDoctorDataTransfer": "Μεταφορά δεδομένων MyDoctor",
	"NoFilesCopy": "Δεν υπάρχουν αρχεία για αντιγραφή",
	"PINChangedToDefault": "Το PIN χρήστη άλλαξε στο προεπιλεγμένο",
	"PINNotAccepted": "Μη αποδεκτός PIN. Πληκτρολογήστε διαφορετικό PIN.",
	"PhoneDataTransfer": "Μεταφορά δεδομένων τηλεφώνου",
	"ProtectionErrorDialogText": "Επιτρέπεται μόνο 1 προστατευμένο αρχείο ανά ορισμένο οδηγό. Διαγράψτε ένα αρχείο ή απενεργοποιήστε την προστασία.",
	"RetryButton": "Νέα προσπάθεια",
	"SelectCopyData": "Αντιγραφή δεδομένων σε USB",
	"SendDataRetryDialogText": "Δεν ήταν δυνατή η αντιγραφή δεδομένων σε USB. Θέλετε να προσπαθήσετε ξανά;",
	"StartRecording": "Έναρξη εγγραφή  ",
	"StopRecording": "Διακοπή εγγραφή  ",
	"TransferData": "Μεταφορά δεδομένων",
	"TransferringDataToUSB": "Γίνεται μεταφορά δεδομένων στο USB",
	"TurnONButton": "Ενεργοποίηση",
	"USBDriveRemoved": "Ο δίσκος USB αφαιρέθηκε. Επανασυνδέστε το δίσκο USB. ",
	"USBMemoryFullDialogText": "Δεν ήταν δυνατή η αντιγραφή δεδομένων σε USB. Η μνήμη του USB είναι πλήρης. Θέλετε να προσπαθήσετε ξανά;",
	"USBTransferTitle": "Αντιγραφή δεδομένων σε USB",
	"UpdatedPIN": "Το PIN ενημερώθηκε ",
	"VDT": "Μεταφορά δεδομένων ",
	"VTT": "Μεταφορά δεδομένων ",
	"WrongPIN": "Λάθος ΡΙΝ. Δοκιμάστε ξανά.",
	"writingToFile": "Γίνεται καταγραφή…",
};

framework.registerAppDictLoaded("vdt", "el_GR");