var Localization_vdtAppDict_sk_SK = {
	//"stringId" : "localString"
	"BackButton": "Dozadu",
	"CancelButton": "Vymazať",
	"ClearAllData": "Vymazať všetky dáta",
	"ClearAllDataFailure": "Chyba vymazania všetkých dát",
	"ClearAllDataSuccessful": "Všetky dáta úspešne vymazané",
	"ClearButton": "Zmazať",
	"ClearDataFailure": "Dáta sa nepodarilo vymazať",
	"ClearDataRetryDialogText": "Nedali sa vymazať všetky dáta. Chcete skúsiť znova?",
	"ClearDataSuccess": "Úspešne vymazané dáta",
	"ClearingAllData": "Zmazanie všetkých údajov",
	"ClearingAllDataConfirm": "Zmazať všetky údaje?",
	"ConfirmClearAllDataDialogText": "Naozaj chcete vymazať všetky dáta?",
	"ConfirmCleariDMDataDialogText": "Chcete zmazať vybraný záznam jazdy?",
	"ConfirmTurnONDriveChart": "Naozaj chcete ZAPNÚŤ diagram jazdy?",
	"ConfirmTurnONMyDoctor": "Naozaj chcete ZAPNÚŤ aplikáciu MyDoctor?",
	"ConfirmTurnONPhoneDataTransfer": "Naozaj chcete ZAPNÚŤ nastavenie prenosu údajov telefónu?",
	"CopyData": "Kopírovať dáta",
	"CopyDataFailure": "Dáta neskopírované",
	"CopyDataFailureUSBFull": "USB memória plná",
	"CopyDataFailureUSBRemoved": "Vložiť USB",
	"CopyDataSuccess": "Dáta úspešne skopírované na USB",
	"CopyDataSuccessful": "Dáta úspešne skopírované",
	"CopyDataUsbFailure": "Chyba kopírovania dát na zariadenie USB",
	"CopyingDataToUSB": "Dáta sa kopírujú na zariadenie USB",
	"CopyingDialogText1": "Dáta sa kopírujú na USB. Nevyb. USB a nevyp. auto.",
	"CopyingDialogText2": "{noOfFilesCopied} z {totalFiles} súborov boli presunuté.",
	"CouldNotClearAllData": "Nebolo možné zmazať všetky údaje",
	"DeleteButton": "Zmazať",
	"DeleteDriveChart": "Chcete odstrániť tieto údaje denníka jázd?",
	"DeleteDriveChartRetry": "Údaje denníka jázd sa nepodarilo odstrániť.  Chcete to skúsiť znova?",
	"DriveChartClearSuccess": "Vymazanie jazdných dát úspešné",
	"DriveChartData": "Údaje diagramu jazdy",
	"DriveChartDataDeleted": "Denník jázd odstránený",
	"DriveChartDataTransfer": "Prenos údajov diagramu jazdy",
	"DriveChartDeleteFailure": "Chyba vymazania dát diagramu jazdy",
	"DriveChartDeleteSuccess": "Dáta diagramu jazdy úspešne vymazané",
	"DriveChartDeleted": "Denník jázd odstránený",
	"DriveChartDetails": "Podrobnosti diagramu jazdy",
	"DriveChartWasNotDeleted": "Jazdné dáta sa nepodarilo vymazať",
	"DriveLog": "Záznam jázd {logNumber}",
	"DriveRecord": "Záznam jázd",
	"DriverLog": "Denník vodiča",
	"EditPIN": "Úprava kódu PIN",
	"EnterCurrentPIN": "Zadajte aktuálny kód PIN",
	"EnterNewPIN": "Zadajte nový 4-miestny kód PIN",
	"EnterYourPIN": "Zadajte svoj kód PIN",
	"InsertUSBDialogText": "Nedajú sa kopírovať dáta na USB. Vsuňte USB znova.",
	"InsertUSBTitle": "Dáta sa nepodarilo skopírovať. Vložte jednotku USB a skúste to znova.",
	"InsufficientUSBMemory": "Nepostačujúca USB pamäť",
	"MemoryFullTitle": "Dáta sa nepodarilo skopírovať na zariadenie USB. Pamäť zariadenia USB je plná.",
	"MyDoctorData": "Údaje aplikácie My Doctor",
	"MyDoctorDataTransfer": "Prenos dát aplikácie MyDoctor",
	"NoFilesCopy": "Žiadne súbory na kopírovanie",
	"PINChangedToDefault": "Kód PIN používateľa zmenený na predvolený",
	"PINNotAccepted": "PIN kód nebol akceptovaný. Zadajte iný PIN kód.",
	"PhoneDataTransfer": "Prenos dát do telefónu",
	"ProtectionErrorDialogText": "Je povolený iba 1 chránený súbor pre Vodiča ID. Odstráňte súboru alebo vypnite ochranu.",
	"RetryButton": "Skúsiť znova",
	"SelectCopyData": "Kopírovať dáta na USB",
	"SendDataRetryDialogText": "Nedá sa kopírovať dáta na USB. Chcete skúsiť?",
	"StartRecording": "Štart nahrávania jazdy",
	"StopRecording": "Štop nahrávania jazdy",
	"TransferData": "Prenos údajov",
	"TransferringDataToUSB": "Prenos údajov do USB",
	"TurnONButton": "ZAPNÚŤ",
	"USBDriveRemoved": "USB jednotka bola odpojená. Znova pripojte USB jednotku.",
	"USBMemoryFullDialogText": "Nedajú sa kopírovať dáta na USB. USB memória plná. Chcete skúsiť znová?",
	"USBTransferTitle": "Kopírovanie dát na USB",
	"UpdatedPIN": "Kód PIN bol aktualizovaný",
	"VDT": "PTÚV",
	"VTT": "PTÚV",
	"WrongPIN": "Nesprávny kód PIN. Skúste to znova.",
	"writingToFile": "Zapisovanie…",
};

framework.registerAppDictLoaded("vdt", "sk_SK");