var Localization_vdtAppDict_ja_JP = {
	//"stringId" : "localString"
	"BackButton": "戻る",
	"CancelButton": "キャンセル",
	"ClearAllData": "ドライブログを削除",
	"ClearAllDataFailure": "すべてのデータをクリアできません",
	"ClearAllDataSuccessful": "すべてのデータをクリアします",
	"ClearButton": "削除",
	"ClearDataFailure": "データをクリアできませんでした",
	"ClearDataRetryDialogText": "削除できませんでした。\nリトライしますか？",
	"ClearDataSuccess": "ドライブログを削除しました",
	"ClearingAllData": "すべてのデータをクリア中",
	"ClearingAllDataConfirm": "すべてのデータをクリアしますか？",
	"ConfirmClearAllDataDialogText": "ドライブログをすべて削除しますか？",
	"ConfirmCleariDMDataDialogText": "選択したドライブログを削除しますか？",
	"ConfirmTurnONDriveChart": "車両状態の送信を許可しますか？",
	"ConfirmTurnONMyDoctor": "診断の設定をオンにしますか？",
	"ConfirmTurnONPhoneDataTransfer": "車両状態の送信を許可しますか？",
	"CopyData": "データを転送",
	"CopyDataFailure": "データがコピーできませんでした",
	"CopyDataFailureUSBFull": "USBメモリが一杯です",
	"CopyDataFailureUSBRemoved": "USBメモリを挿入してください",
	"CopyDataSuccess": "データがUSBメモリへ転送されました",
	"CopyDataSuccessful": "データを転送します",
	"CopyDataUsbFailure": "データをUSBメモリに転送できません",
	"CopyingDataToUSB": "データをUSBメモリへ転送中",
	"CopyingDialogText1": "データをUSBにコピーしています。ドライブを取り出したりエンジンを切ったりしないでください。",
	"CopyingDialogText2": "ドライブログ転送中 {noOfFilesCopied} / {totalFiles}",
	"CouldNotClearAllData": "一部のデータをクリアできませんでした",
	"DeleteButton": "削除",
	"DeleteDriveChart": "このドライブログを削除しますか？",
	"DeleteDriveChartRetry": "ドライブログを削除できませんでした。リトライしますか？",
	"DriveChartClearSuccess": "ドライブのデータをクリアします",
	"DriveChartData": "ドライブチャートデータ",
	"DriveChartDataDeleted": "ドライブログを削除しました",
	"DriveChartDataTransfer": "ドライブチャートデータ転送",
	"DriveChartDeleteFailure": " ",
	"DriveChartDeleteSuccess": "ドライブログ削除成功",
	"DriveChartDeleted": "ドライブログを削除しました",
	"DriveChartDetails": "ドライブチャート詳細",
	"DriveChartWasNotDeleted": "ドライブのデータをクリアできません",
	"DriveLog": "ドライブログ  {logNumber}",
	"DriveRecord": "ドライブレコード",
	"DriverLog": "ドライバーログ",
	"EditPIN": "PINコードを編集",
	"EnterCurrentPIN": "現在のPINを入力してください",
	"EnterNewPIN": "新しいPINを4桁で入力してください",
	"EnterYourPIN": "PIN を入力してください",
	"InsertUSBDialogText": "転送できませんでした。\nUSBメモリを挿入してから\nリトライしてください。",
	"InsertUSBTitle": "転送できませんでした。USBメモリを挿入してからリトライしてください。",
	"InsufficientUSBMemory": "USB メモリが不足しています",
	"MemoryFullTitle": "転送できませんでした。USBメモリが一杯です。",
	"MyDoctorData": "診断データ",
	"MyDoctorDataTransfer": "診断データを転送",
	"NoFilesCopy": "コピーするファイルがありません",
	"PINChangedToDefault": "ユーザーPINがリセットされました",
	"PINNotAccepted": "PIN（暗証番号）が認証できません。違うPINを入力してください。",
	"PhoneDataTransfer": "車両状態の送信",
	"ProtectionErrorDialogText": "保護できるドライブログは１つのみです。他のログの保護をOFFしてください。",
	"RetryButton": "リトライ",
	"SelectCopyData": "ドライブログをUSBメモリへ転送",
	"SendDataRetryDialogText": "転送できませんでした。\nリトライしますか？",
	"StartRecording": "記録開始",
	"StopRecording": "記録終了",
	"TransferData": "データの転送",
	"TransferringDataToUSB": "データを USB に転送中",
	"TurnONButton": "許可する",
	"USBDriveRemoved": "USB ドライブが削除されました。USB ドライブを再接続します。",
	"USBMemoryFullDialogText": "転送できませんでした。\nUSBメモリが一杯です。\nリトライしますか？",
	"USBTransferTitle": "USBデータを転送",
	"UpdatedPIN": "PIN が更新されました",
	"VDT": "車両状態の送信",
	"VTT": "車両状態の送信",
	"WrongPIN": "PINコードが間違っています。再度入力してください。",
	"writingToFile": "書き込み中…",
};

framework.registerAppDictLoaded("vdt", "ja_JP");