var Localization_fmradioAppDict_de_DE = {
    //"stringId" : "localString"
    "UpdateStationList" : "Senderliste aktualisieren",
    "AutoMemoryList" : "Automatische Speicherliste",
    "StationList" : "Senderliste",
    "FMSettings" : "FM Einstellungen",
    "HDRadio" : "HD Radio",
    "TrafficAlert" : "Verkehrsmeldung",
    "RegionLock" : "Regionale Sperre",
    "GenreList" : "Genreliste",
    "HDStations" : "HD Sender",
    "AllStations" : "Alle Sender",
    "News" : "Neuigkeiten",
    "Affairs" : "Aktuelles Geschehen",
    "Info" : "Information ",
    "Sport" : "Sport",
    "Education" : "Ausbildung",
    "Drama" : "Schauspiel",
    "Culture" : "Kultur",
    "Science" : "Wissenschaft",
    "Varied" : "Verschiedenes",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Unterhaltung ",
    "Light" : "Leicht",
    "Classics" : "Klassisch",
    "Other" : "Andere",
    "Weather" : "Wetter",
    "Finance" : "Finanzen",
    "Childrens" : "Kinder",
    "Religion" : "Religion",
    "Social" : "Soziales",
    "PhoneIn" : "Anrufsendung",
    "Travel" : "Reise",
    "Leisure" : "Freizeit",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "National",
    "Oldies" : "Oldies",
    "Folk" : "Folk",
    "Documentary" : "Dokumentation",
    "AlarmTest" : "Alarm Test",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Genre: Alle Sender",
    "GenreNews" : "Genre: Neuigkeiten",
    "GenreAffairs" : "Genre: Aktuelles Geschehen",
    "GenreInfo" : "Genre: Information",
    "GenreSport" : "Genre: Sport",
    "GenreEducation" : "Genre: Ausbildung",
    "GenreDrama" : "Genre: Schauspiel",
    "GenreCulture" : "Genre: Kultur",
    "GenreScience" : "Genre: Wissenschaft",
    "GenreVaried" : "Genre: Verschiedenes",
    "GenrePop" : "Genre: Pop",
    "GenreRock" : "Genre: Rock",
    "GenreMor" : "Genre: Unterhaltung",
    "GenreLight" : "Genre: Leicht",
    "GenreClassics" : "Genre: Klassisch",
    "GenreOther" : "Genre: Andere",
    "GenreWeather" : "Genre: Wetter",
    "GenreFinance" : "Genre: Finanzen",
    "GenreChildrens" : "Genre: Kinder",
    "GenreReligion" : "Genre: Religion",
    "GenrePhoneIn" : "Genre: Phone-In",
    "GenreTravel" : "Genre: Reise",
    "GenreLeisure" : "Genre: Freizeit",
    "GenreJazz" : "Genre: Jazz",
    "GenreCountry" : "Genre: Country",
    "GenreNational" : "Genre: National",
    "GenreOldies" : "Genre: Oldies",
    "GenreFolk" : "Genre: Folk",
    "GenreDocumentary" : "Genre: Dokumentation",
    "GenreAlarmTest" : "Genre: Alarm Test",
    "GenreAlarm" : "Genre: Alarm",
    "GenreSocial" : "Genre: Soziales",
    "ErrorConnection" : "Tag-Übertra.-Fehler z. iPod",
    "CannotTransferTags" : "Kann Tags nicht übertr.",
    "TagSaved" : "Tag gespeichert",
    "TagSavedtoIpod" : "Tag auf iPod gespeichert",
    "TagSavedtoSystem" : "Tag auf System gespeich.",
    "MemoryFull" : "Speicher voll",
    "AllMemoryFull" : "Gesamter Speicher voll",
    "TagMemoryFull" : "Tag-Speicher voll",
    "TagAlreadySaved" : "Tag bereits gespeichert",
    "IpodFull" : "iPod voll",
    "TagTransferredtoiPod" : "Tag auf iPod übertragen",
    "UnplugAndReconnect" : "Trennen u. wiederverbind.",
    "TagNotYetProcessed" : "Tag noch nicht bearbeitet",
    "Remaining" : "{numberOfTags} übrig",
    "IpodError" : "iPod Fehler",
    "ConnectIPod" : "iPod anschl. f. Tagübertr.",
    "TagsCannotBeSaved" : "Tags nicht speicherbar",
    "AllTagsTransferred" : "Alle Tags übertragen",
    "FMRadio" : "FM-Radio",
    "Noresultsfound" : "Keine Resultate gefunden",
    "UpdatingStationList" : "Senderliste aktualisieren",
    "GenreSeek" : "Genre-Suche",
    "ChangeGenre" : "Genre ändern",
    "TAOff" : "TA aus",
    "Remove" : "Entfernen",
    "SignalLost" : "Signal verloren",
    "AlternativeFrequency" : "Alternative Frequenz",
    "Close" : "Schlie.",
    "VrHelp_NowPlayingNA_Help_Left1" : "Unterhaltung",
    "VrHelp_NowPlayingNA_Help_Left2" : "Senderliste",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD ein/aus",
    "VrHelp_NowPlayingNA_Help_Left5" : "Abstimmen",
    "VrHelp_NowPlayingNA_Help_Right1" : "Einstellen",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes-Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Suche vorherigen",
    "VrHelp_NowPlayingNA_Help_Right4" : "Suche nächsten",
    "VrHelp_NowPlayingNA_Help_Right5" : "Automatischer Speicher",
    "VrHelp_NowPlayingEU_Help_Left1" : "Unterhaltung",
    "VrHelp_NowPlayingEU_Help_Left2" : "Senderliste",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingEU_Help_Left4" : "Abstimmen",
    "VrHelp_NowPlayingEU_Help_Left5" : "Einstellen",
    "VrHelp_NowPlayingEU_Help_Right1" : "Verkehrsmeldung",
    "VrHelp_NowPlayingEU_Help_Right2" : "Suche vorherigen",
    "VrHelp_NowPlayingEU_Help_Right3" : "Suche nächsten",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM-Einstellungen",
    "VrHelp_NowPlayingEU_Help_Right5" : "Toneinstellungen",
    "VrHelp_NowPlayingOther_Help_Left1" : "Unterhaltung",
    "VrHelp_NowPlayingOther_Help_Left2" : "Automatischer Speicher",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingOther_Help_Left4" : "Abstimmen",
    "VrHelp_NowPlayingOther_Help_Left5" : "Einstellen",
    "VrHelp_NowPlayingOther_Help_Right1" : "Suche vorherigen",
    "VrHelp_NowPlayingOther_Help_Right2" : "Suche nächsten",
    "VrHelp_NowPlayingOther_Help_Right3" : "Toneinstellungen",
    "VrHelp_AutoMemory_Help1_Left1" : "(Frequenz)",
    "VrHelp_AutoMemory_Help1_Left2" : "Liste aktualisieren",
    "VrHelp_AutoMemory_Help2_Left1" : "Liste aktualisieren",
    "VrHelp_Tune_NA_Help_Left1" : "(Frequenz)",
    "VrHelp_Tune_NA_Help_Left2" : "Einstellen nach oben",
    "VrHelp_Tune_NA_Help_Left3" : "Einstellen nach unten",
    "VrHelp_Tune_nonNA_Help_Left1" : "(Frequenz)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Einstellen nach oben",
    "VrHelp_Tune_nonNA_Help_Left3" : "Einstellen nach unten",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequenz aus",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequenz aus",
    "VrHelp_Settings_Help_Left3" : "Regionale Sicherung einschalten",
    "VrHelp_Settings_Help_Left4" : "Regionale Sicherung ausschalten",
    "VrHelp_GenreSeek_Help_Left1" : "Suche nach oben",
    "VrHelp_GenreSeek_Help_Left2" : "Suche nach unten",
    "VrHelp_GenreSeek_Help_Left3" : "Genre ändern",
    "TrafficAlertOn" : "Verkehrsmeldung an",
    "TrafficAlertOff" : "Verkehrsmeldung aus",
    "TagCaptured" : "Ermitteltes Tag",
    "GenreName" : "Genre : {genreName}",
    "favorites_Tooltip" : "Favoriten",
    "hdChannels_Tooltip" : "HD-Kanäle",
    "rbds_Weather" : "Wetter",
    "rbds_Talk" : "Talk",
    "rbds_Class" : "Rock-Klassiker",
    "rbds_Adult" : "Hits f. Erw.",
    "rbds_SoftRock" : "Soft-Rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Leichte Musik",
    "rbds_Nostalgia" : "Nostalgie",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Klassik",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rhythm & Blues",
    "rbds_SoftRB" : "Leichter R&B",
    "rbds_Foreign" : "Fremdsprachen",
    "rbds_ReligousM" : "Kirchenmusik",
    "rbds_ReligousT" : "Kirchentalk",
    "rbds_News" : "Neuigkeiten",
    "rbds_Personality" : "Personality",
    "rbds_Info" : "Information",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Öffentl.",
    "rbds_College" : "Uni",
    "rbds_Hablar" : "Span. Talk",
    "rbds_Musica" : "Span. Musik",
    "rbds_HipHop" : "Hip-Hop",
    "rbds_EmergencyTest" : "Notfalltest",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Warnung! Warnung!",
    "rbds_genre_Weather" : "Genre: Wetter",
    "rbds_genre_Talk" : "Genre: Talk",
    "rbds_genre_Class" : "Genre: Rock-Klassiker",
    "rbds_genre_Adult" : "Genre: Hits f. Erw.",
    "rbds_genre_SoftRock" : "Genre: Soft-Rock",
    "rbds_genre_Top40" : "Genre: Top 40",
    "rbds_genre_Soft" : "Genre: Leichte Musik",
    "rbds_genre_Nostalgia" : "Genre: Nostalgie",
    "rbds_genre_Jazz" : "Genre: Jazz",
    "rbds_genre_Country" : "Genre: Country",
    "rbds_genre_Classical" : "Genre: Klassik",
    "rbds_genre_Oldies" : "Genre: Oldies",
    "rbds_genre_Rhythym" : "Genre: Rhythm & Blues",
    "rbds_genre_SoftRB" : "Genre: Leichter R&B",
    "rbds_genre_Foreign" : "Genre: Fremdsprachen",
    "rbds_genre_ReligousM" : "Genre: Kirchenmusik",
    "rbds_genre_ReligousT" : "Genre: Kirchentalk",
    "rbds_genre_News" : "Genre: Nachrichten",
    "rbds_genre_Personality" : "Genre: Personality",
    "rbds_genre_Info" : "Genre: Information",
    "rbds_genre_Sports" : "Genre: Sport",
    "rbds_genre_Public" : "Genre: Öffentl.",
    "rbds_genre_College" : "Genre: Uni",
    "rbds_genre_Hablar" : "Genre: Span. Talk",
    "rbds_genre_Musica" : "Genre: Span. Musik",
    "rbds_genre_HipHop" : "Genre: Hip-Hop",
    "rbds_genre_EmergencyTest" : "Genre: Notfalltest",
    "rbds_genre_Rock" : "Genre: Rock",
    "rbds_genre_Emergency" : "Genre: Warnung! Warnung!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Genre: --",
};

framework.registerAppDictLoaded("fmradio", "de_DE");