var Localization_fmradioAppDict_en_US = {
    //"stringId" : "localString"
    "UpdateStationList" : "Update Station List",
    "AutoMemoryList" : "Auto Memory List",
    "StationList" : "Station List",
    "FMSettings" : "FM Settings",
    "HDRadio" : "HD Radio",
    "TrafficAlert" : "Traffic Alert",
    "RegionLock" : "Region Lock",
    "GenreList" : "Genre Selection",
    "HDStations" : "HD Stations",
    "AllStations" : "All Stations",
    "News" : "News",
    "Affairs" : "Affairs",
    "Info" : "Info",
    "Sport" : "Sport",
    "Education" : "Educate",
    "Drama" : "Drama",
    "Culture" : "Culture",
    "Science" : "Science",
    "Varied" : "Varied",
    "Pop" : "Pop M",
    "Rock" : "Rock M",
    "Mor" : "Easy M",
    "Light" : "Light M",
    "Classics" : "Classics",
    "Other" : "Other M",
    "Weather" : "Weather",
    "Finance" : "Finance",
    "Childrens" : "Children",
    "Religion" : "Religion",
    "Social" : "Social",
    "PhoneIn" : "Phone In",
    "Travel" : "Travel",
    "Leisure" : "Leisure",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "Nation M",
    "Oldies" : "Oldies",
    "Folk" : "Folk M",
    "Documentary" : "Document",
    "AlarmTest" : "Alarm Test",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Genre: All Stations",
    "GenreNews" : "Genre: News",
    "GenreAffairs" : "Genre: Affairs",
    "GenreInfo" : "Genre: Info",
    "GenreSport" : "Genre: Sport",
    "GenreEducation" : "Genre: Educate",
    "GenreDrama" : "Genre: Drama",
    "GenreCulture" : "Genre: Culture",
    "GenreScience" : "Genre: Science",
    "GenreVaried" : "Genre: Varied",
    "GenrePop" : "Genre: Pop M",
    "GenreRock" : "Genre: Rock M",
    "GenreMor" : "Genre: Easy M",
    "GenreLight" : "Genre: Light M",
    "GenreClassics" : "Genre: Classics",
    "GenreOther" : "Genre: Other M",
    "GenreWeather" : "Genre: Weather",
    "GenreFinance" : "Genre: Finance",
    "GenreChildrens" : "Genre: Children",
    "GenreReligion" : "Genre: Religion",
    "GenrePhoneIn" : "Genre: Phone In",
    "GenreTravel" : "Genre: Travel",
    "GenreLeisure" : "Genre: Leisure",
    "GenreJazz" : "Genre: Jazz",
    "GenreCountry" : "Genre: Country",
    "GenreNational" : "Genre: Nation M",
    "GenreOldies" : "Genre: Oldies",
    "GenreFolk" : "Genre: Folk M",
    "GenreDocumentary" : "Genre: Document",
    "GenreAlarmTest" : "Genre: Alarm Test",
    "GenreAlarm" : "Genre: Alarm",
    "GenreSocial" : "Genre: Social",
    "ErrorConnection" : "Error While Transferring",
    "CannotTransferTags" : "Cannot Transfer Tags",
    "TagSaved" : "Tag Saved",
    "TagSavedtoIpod" : "Tag Saved to iPod",
    "TagSavedtoSystem" : "Tag Saved to System",
    "MemoryFull" : "Memory Full",
    "AllMemoryFull" : "All Memory Full",
    "TagMemoryFull" : "Tag Memory Full",
    "TagAlreadySaved" : "Tag Already Saved",
    "IpodFull" : "iPod Full",
    "TagTransferredtoiPod" : "Tag Transferred to iPod",
    "UnplugAndReconnect" : "Unplug and Reconnect",
    "TagNotYetProcessed" : "Tag Not Yet Processed",
    "Remaining" : "{numberOfTags} Remaining",
    "IpodError" : "iPod Error",
    "ConnectIPod" : "Connect iPod to Transfer",
    "TagsCannotBeSaved" : "Tags Cannot be Saved",
    "AllTagsTransferred" : "All Tags Transferred",
    "FMRadio" : "FM Radio",
    "Noresultsfound" : "No Result Found",
    "UpdatingStationList" : "Updating Station List",
    "GenreSeek" : "Genre Seek",
    "ChangeGenre" : "Change Genre",
    "TAOff" : "TA Off",
    "Remove" : "Remove",
    "SignalLost" : "Signal Lost",
    "AlternativeFrequency" : "Alternative Frequency",
    "Close" : "Close",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorites",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On/Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorites",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorites",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Traffic Alert On",
    "TrafficAlertOff" : "Traffic Alert Off",
    "TagCaptured" : "Tag Captured",
    "GenreName" : "Genre: {genreName}",
    "favorites_Tooltip" : "Favorites",
    "hdChannels_Tooltip" : "HD Menu",
    "rbds_Weather" : "Weather",
    "rbds_Talk" : "Talk",
    "rbds_Class" : "Classic Rock",
    "rbds_Adult" : "Adult Hits",
    "rbds_SoftRock" : "Soft Rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Soft",
    "rbds_Nostalgia" : "Nostalgia",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Classical",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rhythm and Blues",
    "rbds_SoftRB" : "Soft R&B",
    "rbds_Foreign" : "Foreign Language",
    "rbds_ReligousM" : "Religious Music",
    "rbds_ReligousT" : "Religious Talk",
    "rbds_News" : "News",
    "rbds_Personality" : "Personality",
    "rbds_Info" : "Information",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Public",
    "rbds_College" : "College",
    "rbds_Hablar" : "Hablar Español",
    "rbds_Musica" : "Música Español",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Emergency Test",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Alert! Alert!",
    "rbds_genre_Weather" : "Genre: Weather",
    "rbds_genre_Talk" : "Genre: Talk",
    "rbds_genre_Class" : "Genre: Classic Rock",
    "rbds_genre_Adult" : "Genre: Adult Hits",
    "rbds_genre_SoftRock" : "Genre: Soft Rock",
    "rbds_genre_Top40" : "Genre: Top 40",
    "rbds_genre_Soft" : "Genre: Soft",
    "rbds_genre_Nostalgia" : "Genre: Nostalgia",
    "rbds_genre_Jazz" : "Genre: Jazz",
    "rbds_genre_Country" : "Genre: Country",
    "rbds_genre_Classical" : "Genre: Classical",
    "rbds_genre_Oldies" : "Genre: Oldies",
    "rbds_genre_Rhythym" : "Genre: Rhythm and Blues",
    "rbds_genre_SoftRB" : "Genre: Soft R&B",
    "rbds_genre_Foreign" : "Genre: Foreign Language",
    "rbds_genre_ReligousM" : "Genre: Religious Music",
    "rbds_genre_ReligousT" : "Genre: Religious Talk",
    "rbds_genre_News" : "Genre: News",
    "rbds_genre_Personality" : "Genre: Personality",
    "rbds_genre_Info" : "Genre: Information",
    "rbds_genre_Sports" : "Genre: Sports",
    "rbds_genre_Public" : "Genre: Public",
    "rbds_genre_College" : "Genre: College",
    "rbds_genre_Hablar" : "Genre: Hablar Español",
    "rbds_genre_Musica" : "Genre: Música Español",
    "rbds_genre_HipHop" : "Genre: Hip Hop",
    "rbds_genre_EmergencyTest" : "Genre: Emergency Test",
    "rbds_genre_Rock" : "Genre: Rock",
    "rbds_genre_Emergency" : "Genre: Alert! Alert!",
    "rbds_None" : "None",
    "rbds_genre_None" : "Genre: None",
};

framework.registerAppDictLoaded("fmradio", "en_US");