var Localization_fmradioAppDict_no_NO = {
    //"stringId" : "localString"
    "UpdateStationList" : "Oppdater stasjonsliste",
    "AutoMemoryList" : "Autominneliste",
    "StationList" : "Stasjonsliste",
    "FMSettings" : "FM-innstillinger",
    "HDRadio" : "HD-radio",
    "TrafficAlert" : "Trafikkvarsel",
    "RegionLock" : "Regionlås",
    "GenreList" : "Sjangerliste",
    "HDStations" : "HD-stasjoner",
    "AllStations" : "Alle stasjoner",
    "News" : "Nyheter",
    "Affairs" : "Aktuelt",
    "Info" : "Informasjon ",
    "Sport" : "Sport",
    "Education" : "Utdanning",
    "Drama" : "Drama",
    "Culture" : "Kultur",
    "Science" : "Vitenskap",
    "Varied" : "Diverse",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Easy Listening ",
    "Light" : "Lett",
    "Classics" : "Klassisk",
    "Other" : "Annet",
    "Weather" : "Vær",
    "Finance" : "Finans",
    "Childrens" : "For barn",
    "Religion" : "Religion",
    "Social" : "Sosialt",
    "PhoneIn" : "Telefon inn",
    "Travel" : "Fjæringslengde",
    "Leisure" : "Fritid",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "Nasjonal",
    "Oldies" : "Oldies",
    "Folk" : "Folkemusikk",
    "Documentary" : "Dokumentar",
    "AlarmTest" : "Alarmtest",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Sjanger: Alle stasjoner",
    "GenreNews" : "Sjanger: Nyheter",
    "GenreAffairs" : "Sjanger: Aktuelt",
    "GenreInfo" : "Sjanger: Informasjon",
    "GenreSport" : "Sjanger: Sport",
    "GenreEducation" : "Sjanger: Utdanning",
    "GenreDrama" : "Sjanger: Drama",
    "GenreCulture" : "Sjanger: Kultur",
    "GenreScience" : "Sjanger: Vitenskap",
    "GenreVaried" : "Sjanger: Diverse",
    "GenrePop" : "Sjanger: Pop",
    "GenreRock" : "Sjanger: Rock",
    "GenreMor" : "Sjanger: Easy Listening",
    "GenreLight" : "Sjanger: Lett",
    "GenreClassics" : "Sjanger: Klassisk",
    "GenreOther" : "Sjanger: Annet",
    "GenreWeather" : "Sjanger: Vær",
    "GenreFinance" : "Sjanger: Finans",
    "GenreChildrens" : "Sjanger: For barn",
    "GenreReligion" : "Sjanger: Religion",
    "GenrePhoneIn" : "Sjanger: Telefon inn",
    "GenreTravel" : "Sjanger: Reise",
    "GenreLeisure" : "Sjanger: Fritid",
    "GenreJazz" : "Sjanger: Jazz",
    "GenreCountry" : "Sjanger: Country",
    "GenreNational" : "Sjanger: Nasjonal",
    "GenreOldies" : "Sjanger: Oldies",
    "GenreFolk" : "Sjanger: Folkemusikk",
    "GenreDocumentary" : "Sjanger: Dokumentar",
    "GenreAlarmTest" : "Sjanger: Alarmtest",
    "GenreAlarm" : "Sjanger: Alarm",
    "GenreSocial" : "Sjanger: Sosialt",
    "ErrorConnection" : "F. ved overf. av tag iPod",
    "CannotTransferTags" : "Kan ikke overføre tagger",
    "TagSaved" : "Taggen er lagret",
    "TagSavedtoIpod" : "Taggen er lagret på iPod",
    "TagSavedtoSystem" : "Taggen er lagret på syst.",
    "MemoryFull" : "Minnet er fullt",
    "AllMemoryFull" : "Alt minne er fullt",
    "TagMemoryFull" : "Tagg-minnet er fullt",
    "TagAlreadySaved" : "Taggen er allerede lagret",
    "IpodFull" : "iPod er full",
    "TagTransferredtoiPod" : "Taggen overført til iPod",
    "UnplugAndReconnect" : "Koble fra og til på nytt",
    "TagNotYetProcessed" : "Tag. er ikke behan. Ennå",
    "Remaining" : "{numberOfTags} gjenstår",
    "IpodError" : "iPod-feil",
    "ConnectIPod" : "Kobl. til iPod for tag-overf",
    "TagsCannotBeSaved" : "Taggene kan ikke lagres",
    "AllTagsTransferred" : "Alle taggene er overført",
    "FMRadio" : "FM-radio",
    "Noresultsfound" : "Fant ingen resultater",
    "UpdatingStationList" : "Oppdaterer stasjonsliste",
    "GenreSeek" : "Sjangersøk",
    "ChangeGenre" : "Endre sjanger",
    "TAOff" : "TA av",
    "Remove" : "Fjern",
    "SignalLost" : "Tapt signal",
    "AlternativeFrequency" : "Alternativ frekvens",
    "Close" : "Lukk",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On / Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Trafikkvarsel på",
    "TrafficAlertOff" : "Trafikkvarsel av",
    "TagCaptured" : "Tagg opptak",
    "GenreName" : "Sjanger: {genreName}",
    "favorites_Tooltip" : "Favoritter",
    "hdChannels_Tooltip" : "HD-kanaler",
    "rbds_Weather" : "Vær",
    "rbds_Talk" : "Diskusjon",
    "rbds_Class" : "Klassisk Rock",
    "rbds_Adult" : "Adult hits",
    "rbds_SoftRock" : "Soft rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Soft",
    "rbds_Nostalgia" : "Nostalgi",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Klassisk",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rhythm and Blues",
    "rbds_SoftRB" : "Soft R&B",
    "rbds_Foreign" : "Fremmedspråk",
    "rbds_ReligousM" : "Religiøs Musikk",
    "rbds_ReligousT" : "Religiøs Diskusjon",
    "rbds_News" : "Nyheter",
    "rbds_Personality" : "Personlighet",
    "rbds_Info" : "Informasjon",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Public",
    "rbds_College" : "Høyskole",
    "rbds_Hablar" : "Snakker Spansk",
    "rbds_Musica" : "Spansk Musikk",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Test, nødsituasjon",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Varsle! Varsle!",
    "rbds_genre_Weather" : "Sjanger: Vær",
    "rbds_genre_Talk" : "Sjanger: Diskusjon",
    "rbds_genre_Class" : "Sjanger: Klassisk Rock",
    "rbds_genre_Adult" : "Sjanger: Adult hits",
    "rbds_genre_SoftRock" : "Sjanger: Soft rock",
    "rbds_genre_Top40" : "Sjanger: Top 40",
    "rbds_genre_Soft" : "Sjanger: Soft",
    "rbds_genre_Nostalgia" : "Sjanger: Nostalgi",
    "rbds_genre_Jazz" : "Sjanger: Jazz",
    "rbds_genre_Country" : "Sjanger: Country",
    "rbds_genre_Classical" : "Sjanger: Klassisk",
    "rbds_genre_Oldies" : "Sjanger: Oldies",
    "rbds_genre_Rhythym" : "Sjanger: Rhythm and Blues",
    "rbds_genre_SoftRB" : "Sjanger: Soft R&B",
    "rbds_genre_Foreign" : "Sjanger: Fremmedspråk",
    "rbds_genre_ReligousM" : "Sjanger: Religiøs Musikk",
    "rbds_genre_ReligousT" : "Sjanger: Religiøs Diskusjon",
    "rbds_genre_News" : "Sjanger: Nyheter",
    "rbds_genre_Personality" : "Sjanger: Personlighet",
    "rbds_genre_Info" : "Sjanger: Informasjon",
    "rbds_genre_Sports" : "Sjanger: Sports",
    "rbds_genre_Public" : "Sjanger: Public",
    "rbds_genre_College" : "Sjanger: Høyskole",
    "rbds_genre_Hablar" : "Sjanger: Snakker Spansk",
    "rbds_genre_Musica" : "Sjanger: Spansk Musikk",
    "rbds_genre_HipHop" : "Sjanger: Hip Hop",
    "rbds_genre_EmergencyTest" : "Sjanger: Test, nødsituasjon",
    "rbds_genre_Rock" : "Sjanger: Rock",
    "rbds_genre_Emergency" : "Sjanger: Varsle! Varsle!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Sjanger: --",
};

framework.registerAppDictLoaded("fmradio", "no_NO");