var Localization_fmradioAppDict_ar_SA = {
    //"stringId" : "localString"
    "UpdateStationList" : "تحديث قائمة المحطة",
    "AutoMemoryList" : "قائمة الذاكرة التلقائية",
    "StationList" : "قائمة المحطة",
    "FMSettings" : "إعدادات FM",
    "HDRadio" : "راديو HD",
    "TrafficAlert" : "تنبيه المرور",
    "RegionLock" : "قفل المنطقة",
    "GenreList" : "قائمة الأنواع",
    "HDStations" : "محطات HD",
    "AllStations" : "جميع المحطات",
    "News" : "أخبار",
    "Affairs" : "قضايا",
    "Info" : "معلومات",
    "Sport" : "رياضة",
    "Education" : "تعليم",
    "Drama" : "دراما",
    "Culture" : "ثقافة",
    "Science" : "علوم",
    "Varied" : "منوعات",
    "Pop" : "موسيقى البوب",
    "Rock" : "موسيقى الروك",
    "Mor" : "موسيقى بنغمة عادية",
    "Light" : "موسيقى هادئة",
    "Classics" : "كلاسيكيات",
    "Other" : "أخرى",
    "Weather" : "طقس",
    "Finance" : "اقتصاد",
    "Childrens" : "برامج أطفال",
    "Religion" : "دين",
    "Social" : "اجتماعي",
    "PhoneIn" : "اتصال على الهواء",
    "Travel" : "سفر",
    "Leisure" : "ترفيه",
    "Jazz" : "موسيقى الجاز",
    "Country" : "كانتري",
    "National" : "وطني",
    "Oldies" : "فنون قديمة",
    "Folk" : "فولكلور",
    "Documentary" : "برامج وثائقية",
    "AlarmTest" : "اختبار الإنذار",
    "Alarm" : "إنذار",
    "GenreAllStations" : "النوع: جميع المحطات",
    "GenreNews" : "النوع: أخبار",
    "GenreAffairs" : "النوع: قضايا",
    "GenreInfo" : "النوع: معلومات",
    "GenreSport" : "النوع: رياضة",
    "GenreEducation" : "النوع: تعليم",
    "GenreDrama" : "النوع: دراما",
    "GenreCulture" : "النوع: ثقافة",
    "GenreScience" : "النوع: علوم",
    "GenreVaried" : "النوع: منوعات",
    "GenrePop" : "النوع: موسيقى البوب",
    "GenreRock" : "النوع: موسيقى الروك",
    "GenreMor" : "النوع: موسيقى بنغمة عادية",
    "GenreLight" : "النوع: موسيقى هادئة",
    "GenreClassics" : "النوع: كلاسيكيات",
    "GenreOther" : "النوع: أخرى",
    "GenreWeather" : "النوع: طقس",
    "GenreFinance" : "النوع: اقتصاد",
    "GenreChildrens" : "النوع: برامج أطفال",
    "GenreReligion" : "النوع: دين",
    "GenrePhoneIn" : "النوع: مشاركة عبر الهاتف",
    "GenreTravel" : "النوع: سفر",
    "GenreLeisure" : "النوع: ترفيه",
    "GenreJazz" : "النوع: موسيقى الجاز",
    "GenreCountry" : "النوع: كانتري",
    "GenreNational" : "النوع: وطني",
    "GenreOldies" : "النوع: فنون قديمة",
    "GenreFolk" : "النوع: فولكلور",
    "GenreDocumentary" : "النوع: برامج وثائقية",
    "GenreAlarmTest" : "النوع: اختبار الإنذار",
    "GenreAlarm" : "النوع: إنذار",
    "GenreSocial" : "النوع: إجتماعي",
    "ErrorConnection" : "خطأ نقل العلامات لـ iPod",
    "CannotTransferTags" : "لا يمكن نقل العلامات",
    "TagSaved" : "تم حفظ العلامة",
    "TagSavedtoIpod" : "حفظت العلامة على iPod",
    "TagSavedtoSystem" : "حفظت العلامة في النظام",
    "MemoryFull" : "الذاكرة ممتلئة",
    "AllMemoryFull" : "الذاكرة ممتلئة بالكامل",
    "TagMemoryFull" : "ذاكرة العلامات ممتلئة",
    "TagAlreadySaved" : "تم حفظ العلامة بالفعل",
    "IpodFull" : "جهاز الـiPod ممتلئ",
    "TagTransferredtoiPod" : "تم نقل العلامة إلى iPod",
    "UnplugAndReconnect" : "افصل وأعد التوصيل",
    "TagNotYetProcessed" : "لم تتم معالجة العلامة",
    "Remaining" : "متبقي {numberOfTags}",
    "IpodError" : "حدث خطا في جهاز الـiPod",
    "ConnectIPod" : "صل iPod لنقل العلامات",
    "TagsCannotBeSaved" : "لا يمكن حفظ العلامات",
    "AllTagsTransferred" : "تم نقل جميع العلامات",
    "FMRadio" : "راديو FM",
    "Noresultsfound" : "لم يتم العثور على نتائج",
    "UpdatingStationList" : "تحديث قائمة المحطة",
    "GenreSeek" : "البحث عن النوع",
    "ChangeGenre" : "نوع التغيير",
    "TAOff" : "توقف المر...",
    "Remove" : "إزالة",
    "SignalLost" : "تم فقد الإشارة",
    "AlternativeFrequency" : "التردد البديل",
    "Close" : "إغلاق",
    "VrHelp_NowPlayingNA_Help_Left1" : " الترفيه",
    "VrHelp_NowPlayingNA_Help_Left2" : "قائمة المحطة",
    "VrHelp_NowPlayingNA_Help_Left3" : "المفضل",
    "VrHelp_NowPlayingNA_Help_Left4" : "تشغيل/إيقاف HD",
    "VrHelp_NowPlayingNA_Help_Left5" : "مسح ضوئي",
    "VrHelp_NowPlayingNA_Help_Right1" : "توليف",
    "VrHelp_NowPlayingNA_Help_Right2" : "علامة iTunes",
    "VrHelp_NowPlayingNA_Help_Right3" : "بحث عن السابق",
    "VrHelp_NowPlayingNA_Help_Right4" : "بحث عن التالي",
    "VrHelp_NowPlayingNA_Help_Right5" : "الذاكرة التلقائية",
    "VrHelp_NowPlayingEU_Help_Left1" : " الترفيه",
    "VrHelp_NowPlayingEU_Help_Left2" : "قائمة المحطة",
    "VrHelp_NowPlayingEU_Help_Left3" : "المفضل",
    "VrHelp_NowPlayingEU_Help_Left4" : "مسح ضوئي",
    "VrHelp_NowPlayingEU_Help_Left5" : "توليف",
    "VrHelp_NowPlayingEU_Help_Right1" : "تنبيه المرور",
    "VrHelp_NowPlayingEU_Help_Right2" : "بحث عن السابق",
    "VrHelp_NowPlayingEU_Help_Right3" : "بحث عن التالي",
    "VrHelp_NowPlayingEU_Help_Right4" : "إعدادات FM",
    "VrHelp_NowPlayingEU_Help_Right5" : "إعدادات الصوت",
    "VrHelp_NowPlayingOther_Help_Left1" : " الترفيه",
    "VrHelp_NowPlayingOther_Help_Left2" : "الذاكرة التلقائية",
    "VrHelp_NowPlayingOther_Help_Left3" : "المفضل",
    "VrHelp_NowPlayingOther_Help_Left4" : "مسح ضوئي",
    "VrHelp_NowPlayingOther_Help_Left5" : "توليف",
    "VrHelp_NowPlayingOther_Help_Right1" : "بحث عن السابق",
    "VrHelp_NowPlayingOther_Help_Right2" : "بحث عن التالي",
    "VrHelp_NowPlayingOther_Help_Right3" : "إعدادات الصوت",
    "VrHelp_AutoMemory_Help1_Left1" : "(التردد)",
    "VrHelp_AutoMemory_Help1_Left2" : "تحديث القائمة",
    "VrHelp_AutoMemory_Help2_Left1" : "تحديث القائمة",
    "VrHelp_Tune_NA_Help_Left1" : "(التردد)",
    "VrHelp_Tune_NA_Help_Left2" : "توليف لأعلى",
    "VrHelp_Tune_NA_Help_Left3" : "توليف لأسفل",
    "VrHelp_Tune_nonNA_Help_Left1" : "(التردد)",
    "VrHelp_Tune_nonNA_Help_Left2" : "توليف لأعلى",
    "VrHelp_Tune_nonNA_Help_Left3" : "توليف لأسفل",
    "VrHelp_Settings_Help_Left1" : "تشغيل التردد البديل",
    "VrHelp_Settings_Help_Left2" : "إيقاف التردد البديل",
    "VrHelp_Settings_Help_Left3" : "تشغيل قفل المنطقة",
    "VrHelp_Settings_Help_Left4" : "إيقاف قفل المنطقة",
    "VrHelp_GenreSeek_Help_Left1" : "بحث لأعلى",
    "VrHelp_GenreSeek_Help_Left2" : "بحث لأسفل",
    "VrHelp_GenreSeek_Help_Left3" : "تغيير النوع",
    "TrafficAlertOn" : "تشغيل تنبيه المرور",
    "TrafficAlertOff" : "إيقاف تنبيه المرور",
    "TagCaptured" : "العلامة المرجعية الملتقطة",
    "GenreName" : "النوع: {genreName}",
    "favorites_Tooltip" : "المفضلات",
    "hdChannels_Tooltip" : "قنوات HD",
    "rbds_Weather" : "طقس",
    "rbds_Talk" : "حديث",
    "rbds_Class" : "كلاسيك روك",
    "rbds_Adult" : "أغاني الكبار",
    "rbds_SoftRock" : "سوفت روك",
    "rbds_Top40" : "أفضل 40",
    "rbds_Soft" : "ناعم",
    "rbds_Nostalgia" : "حنين",
    "rbds_Jazz" : "موسيقى الجاز",
    "rbds_Country" : "كانتري",
    "rbds_Classical" : "كلاسيكي",
    "rbds_Oldies" : "فنون قديمة",
    "rbds_Rhythym" : "ريذم آند بلوز",
    "rbds_SoftRB" : "سوفت ريذم آند بلوز",
    "rbds_Foreign" : "لغة اجنبية",
    "rbds_ReligousM" : "موسيقى دينية",
    "rbds_ReligousT" : "حديث ديني",
    "rbds_News" : "أخبار",
    "rbds_Personality" : "شخصية بارزة",
    "rbds_Info" : "معلومات",
    "rbds_Sports" : "رياضة",
    "rbds_Public" : "عام",
    "rbds_College" : "كلية",
    "rbds_Hablar" : "تحدث الإسبانية",
    "rbds_Musica" : "الموسيقى الإسبانية",
    "rbds_HipHop" : "الهيب هوب",
    "rbds_EmergencyTest" : "اختبار الطوارئ",
    "rbds_Rock" : "موسيقى الروك",
    "rbds_Emergency" : "تنبيه! تنبيه!",
    "rbds_genre_Weather" : "النوع: طقس",
    "rbds_genre_Talk" : "النوع: حديث",
    "rbds_genre_Class" : "النوع: كلاسيك روك",
    "rbds_genre_Adult" : "النوع: أغاني الكبار",
    "rbds_genre_SoftRock" : "النوع: سوفت روك",
    "rbds_genre_Top40" : "النوع: أفضل 40",
    "rbds_genre_Soft" : "النوع: رقيق",
    "rbds_genre_Nostalgia" : "النوع: حنين",
    "rbds_genre_Jazz" : "النوع: موسيقى الجاز",
    "rbds_genre_Country" : "النوع: كانتري",
    "rbds_genre_Classical" : "النوع: كلاسيكي",
    "rbds_genre_Oldies" : "النوع: فنون قديمة",
    "rbds_genre_Rhythym" : "النوع: ريذم آند بلوز",
    "rbds_genre_SoftRB" : "النوع: سوفت ريذم آند بلوز",
    "rbds_genre_Foreign" : "النوع: لغة أجنبية",
    "rbds_genre_ReligousM" : "النوع: موسيقى دينية",
    "rbds_genre_ReligousT" : "النوع: حديث ديني",
    "rbds_genre_News" : "النوع: أخبار",
    "rbds_genre_Personality" : "لنوع: شخصية بارزة",
    "rbds_genre_Info" : "النوع: معلومات",
    "rbds_genre_Sports" : "النوع: رياضة",
    "rbds_genre_Public" : "لنوع: عام",
    "rbds_genre_College" : "النوع: كلية",
    "rbds_genre_Hablar" : "النوع: تحدث الإسبانية",
    "rbds_genre_Musica" : "النوع: الموسيقى الإسبانية",
    "rbds_genre_HipHop" : "النوع: الهيب هوب",
    "rbds_genre_EmergencyTest" : "النوع: اختبار الطوارئ",
    "rbds_genre_Rock" : "النوع: موسيقى الروك",
    "rbds_genre_Emergency" : "النوع: تنبيه! تنبيه!",
    "rbds_None" : "لا يوجد",
    "rbds_genre_None" : "النوع: لا يوجد",
};

framework.registerAppDictLoaded("fmradio", "ar_SA");