var Localization_fmradioAppDict_tr_TR = {
    //"stringId" : "localString"
    "UpdateStationList" : "İstasyon Listesini Güncelle",
    "AutoMemoryList" : "Otomatik Hafıza Listesi",
    "StationList" : "İstasyon Listesi",
    "FMSettings" : "FM Ayarları",
    "HDRadio" : "HD Radyo",
    "TrafficAlert" : "Trafik Uyarısı",
    "RegionLock" : "Bölge Kilidi",
    "GenreList" : "Tür Listesi",
    "HDStations" : "HD İstasyonlar",
    "AllStations" : "Tüm İstasyonlar",
    "News" : "Haberler",
    "Affairs" : "İlişkiler",
    "Info" : "Bilgilendirici",
    "Sport" : "Spor",
    "Education" : "Eğitim",
    "Drama" : "Drama",
    "Culture" : "Kültür",
    "Science" : "Bilim",
    "Varied" : "Muhtelif",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Dinlendirici",
    "Light" : "Hafif",
    "Classics" : "Klasik",
    "Other" : "Diğer",
    "Weather" : "Hava Durumu",
    "Finance" : "Finans",
    "Childrens" : "Çocuklar",
    "Religion" : "Dini",
    "Social" : "Sosyal",
    "PhoneIn" : "Telefon Girişi",
    "Travel" : "Seyahat",
    "Leisure" : "Hobi",
    "Jazz" : "Caz",
    "Country" : "Ülke",
    "National" : "Ulusal",
    "Oldies" : "Eskiler",
    "Folk" : "Halk Müziği",
    "Documentary" : "Belgesel",
    "AlarmTest" : "Alarm Testi",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Tür: Tüm İstasyonlar",
    "GenreNews" : "Tür: Haberler",
    "GenreAffairs" : "Tür: İlişkiler",
    "GenreInfo" : "Tür: Bilgilendirici",
    "GenreSport" : "Tür: Spor",
    "GenreEducation" : "Tür: Eğitim",
    "GenreDrama" : "Tür: Drama",
    "GenreCulture" : "Tür: Kültür",
    "GenreScience" : "Tür: Bilim",
    "GenreVaried" : "Tür: Muhtelif",
    "GenrePop" : "Tür: Pop",
    "GenreRock" : "Tür: Rock",
    "GenreMor" : "Tür: Dinlendirici",
    "GenreLight" : "Tür: Hafif",
    "GenreClassics" : "Tür: Klasik",
    "GenreOther" : "Tür: Diğer",
    "GenreWeather" : "Tür: Hava Durumu",
    "GenreFinance" : "Tür: Finans",
    "GenreChildrens" : "Tür: Çocuklar",
    "GenreReligion" : "Tür: Dini",
    "GenrePhoneIn" : "Tür: Telefon Girişi",
    "GenreTravel" : "Tür: Seyahat",
    "GenreLeisure" : "Tür: Hobi",
    "GenreJazz" : "Tür: Caz",
    "GenreCountry" : "Tür: Ülke",
    "GenreNational" : "Tür: Ulusal",
    "GenreOldies" : "Tür: Eskiler",
    "GenreFolk" : "Tür: Halk Müziği",
    "GenreDocumentary" : "Tür: Belgesel",
    "GenreAlarmTest" : "Tür: Alarm Testi",
    "GenreAlarm" : "Tür: Alarm",
    "GenreSocial" : "Tür: Sosyal",
    "ErrorConnection" : "iPod'a Etiket Aktar Hata",
    "CannotTransferTags" : "Etiketler Aktarılamıyor",
    "TagSaved" : "Etiket Kaydedildi",
    "TagSavedtoIpod" : "Etiket iPod'a Kaydedildi",
    "TagSavedtoSystem" : "Etiket Sisteme Kaydedildi",
    "MemoryFull" : "Hafıza Dolu",
    "AllMemoryFull" : "Tüm Hafıza Dolu",
    "TagMemoryFull" : "Etiket Hafızası Dolu",
    "TagAlreadySaved" : "Etiket Zaten Kayıtlı",
    "IpodFull" : "iPod Dolu",
    "TagTransferredtoiPod" : "Etiket iPod'a Aktarıldı",
    "UnplugAndReconnect" : "Çıkar ve Yeniden Bağla",
    "TagNotYetProcessed" : "Etiket Henüz İşlenmedi",
    "Remaining" : "Kalan: {numberOfTags}",
    "IpodError" : "iPod Hatası",
    "ConnectIPod" : "Etiketler, iPod'u Bağla",
    "TagsCannotBeSaved" : "Etiketler Kaydedilemiyor",
    "AllTagsTransferred" : "Tüm Etiketler Aktarıldı",
    "FMRadio" : "FM Radyo",
    "Noresultsfound" : "Sonuç bulunamadı",
    "UpdatingStationList" : "İstasyon Listesi Güncelleniyor",
    "GenreSeek" : "Tür Ara",
    "ChangeGenre" : "Türü Değiştir",
    "TAOff" : "TA Kapalı",
    "Remove" : "Kaldır",
    "SignalLost" : "Sinyal Kesildi",
    "AlternativeFrequency" : "Alternatif Frekans",
    "Close" : "Kapat",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On / Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Trafik Uyarısı Açık",
    "TrafficAlertOff" : "Trafik Uyarısı Kapalı",
    "TagCaptured" : "Etiket Alındı",
    "GenreName" : "Tür: {genreName}",
    "favorites_Tooltip" : "Omiljeni",
    "hdChannels_Tooltip" : "HD stanice",
    "rbds_Weather" : "Hava Durumu",
    "rbds_Talk" : "Konuşmak",
    "rbds_Class" : "Klasik Rock",
    "rbds_Adult" : "Yetişkin Sayısı",
    "rbds_SoftRock" : "Yumuşak Rock",
    "rbds_Top40" : "üst 40",
    "rbds_Soft" : "Yumuşak",
    "rbds_Nostalgia" : "Nostalji",
    "rbds_Jazz" : "Caz",
    "rbds_Country" : "Ülke",
    "rbds_Classical" : "Klasik",
    "rbds_Oldies" : "Eskiler",
    "rbds_Rhythym" : "Ritim ve Blues",
    "rbds_SoftRB" : "Yumuşakp R&B",
    "rbds_Foreign" : "Yabancı Dil",
    "rbds_ReligousM" : "Dini Müzik",
    "rbds_ReligousT" : "Dini Konuşma",
    "rbds_News" : "Haberler",
    "rbds_Personality" : "Kişilik",
    "rbds_Info" : "Bilgi",
    "rbds_Sports" : "Spor",
    "rbds_Public" : "Kamu",
    "rbds_College" : "Üniversite",
    "rbds_Hablar" : "İspanyolca Konuşan",
    "rbds_Musica" : "İspanyol Müzik",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Acil Testi",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Uyarı! Uyarı!",
    "rbds_genre_Weather" : "Tür: Hava Durumu",
    "rbds_genre_Talk" : "Tür: Konuşmak",
    "rbds_genre_Class" : "Tür: Klasik Rock",
    "rbds_genre_Adult" : "Tür: Yetişkin Sayısı",
    "rbds_genre_SoftRock" : "Tür: Yumuşak Rock",
    "rbds_genre_Top40" : "Tür: üst 40",
    "rbds_genre_Soft" : "Tür: Yumuşak",
    "rbds_genre_Nostalgia" : "Tür: Nostalji",
    "rbds_genre_Jazz" : "Tür: Caz",
    "rbds_genre_Country" : "Tür: Ülke",
    "rbds_genre_Classical" : "Tür: Klasik",
    "rbds_genre_Oldies" : "Tür: Eskiler",
    "rbds_genre_Rhythym" : "Tür: Ritim ve Blues",
    "rbds_genre_SoftRB" : "Tür: Yumuşakp R&B",
    "rbds_genre_Foreign" : "Tür: Yabancı Dil",
    "rbds_genre_ReligousM" : "Tür: Dini Müzik",
    "rbds_genre_ReligousT" : "Tür: Dini Konuşma",
    "rbds_genre_News" : "Tür: Haberler",
    "rbds_genre_Personality" : "Tür: Kişilik",
    "rbds_genre_Info" : "Tür: Bilgi",
    "rbds_genre_Sports" : "Tür: Spor",
    "rbds_genre_Public" : "Tür: Kamu",
    "rbds_genre_College" : "Tür: Üniversite",
    "rbds_genre_Hablar" : "Tür: İspanyolca Konuşan",
    "rbds_genre_Musica" : "Tür: İspanyol Müzik",
    "rbds_genre_HipHop" : "Tür: Hip Hop",
    "rbds_genre_EmergencyTest" : "Tür: Acil Testi",
    "rbds_genre_Rock" : "Tür: Rock",
    "rbds_genre_Emergency" : "Tür: Uyarı! Uyarı!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Tür: --",
};

framework.registerAppDictLoaded("fmradio", "tr_TR");