var Localization_fmradioAppDict_fr_FR = {
    //"stringId" : "localString"
    "UpdateStationList" : "Mettre à jour la liste des stations",
    "AutoMemoryList" : "Liste de la Mémoire Automatique",
    "StationList" : "Liste des stations",
    "FMSettings" : "Réglages FM",
    "HDRadio" : "Radio HD",
    "TrafficAlert" : "Alerte trafic",
    "RegionLock" : "Verrouillage de la région",
    "GenreList" : "Liste de genre",
    "HDStations" : "Stations HD",
    "AllStations" : "Toutes les stations",
    "News" : "Actualités",
    "Affairs" : "Affaires",
    "Info" : "Information",
    "Sport" : "Sport",
    "Education" : "Education",
    "Drama" : "Fiction",
    "Culture" : "Culture",
    "Science" : "Sciences",
    "Varied" : "Varié",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Musique de détente ",
    "Light" : "Musique Légère",
    "Classics" : "Classiques",
    "Other" : "Autre",
    "Weather" : "Météo",
    "Finance" : "Finance",
    "Childrens" : "Enfants",
    "Religion" : "Religion",
    "Social" : "Social",
    "PhoneIn" : "Émission à ligne ouverte",
    "Travel" : "Voyage",
    "Leisure" : "Loisirs",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "National",
    "Oldies" : "Vieux classiques",
    "Folk" : "Folk",
    "Documentary" : "Documentaire",
    "AlarmTest" : "Alarm Test",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Genre:  toutes les stations",
    "GenreNews" : "Genre:  Informations",
    "GenreAffairs" : "Genre:  Affaires",
    "GenreInfo" : "Genre : Information",
    "GenreSport" : "Genre:  Sport",
    "GenreEducation" : "Genre:  Education",
    "GenreDrama" : "Genre:  Fiction",
    "GenreCulture" : "Genre:  Culture",
    "GenreScience" : "Genre:  Sciences",
    "GenreVaried" : "Genre:  Varié",
    "GenrePop" : "Genre:  Pop",
    "GenreRock" : "Genre:  Rock",
    "GenreMor" : "Genre : Musique de détente",
    "GenreLight" : "Genre:  Musique Légère",
    "GenreClassics" : "Genre:  Classiques",
    "GenreOther" : "Genre:  Autre",
    "GenreWeather" : "Genre:  Météo",
    "GenreFinance" : "Genre:  Finance",
    "GenreChildrens" : "Genre:  Enfants",
    "GenreReligion" : "Genre:  Religion",
    "GenrePhoneIn" : "Genre:  Emission à ligne ouverte",
    "GenreTravel" : "Genre:  Voyage",
    "GenreLeisure" : "Genre:  Loisirs",
    "GenreJazz" : "Genre:  Jazz",
    "GenreCountry" : "Genre:  Country",
    "GenreNational" : "Genre:  National",
    "GenreOldies" : "Genre:  Vieux classiques",
    "GenreFolk" : "Genre:  Folk",
    "GenreDocumentary" : "Genre:  Documentaire",
    "GenreAlarmTest" : "Genre:  Test d’alarme",
    "GenreAlarm" : "Genre:  Alarme",
    "GenreSocial" : "Genre:  Sociale",
    "ErrorConnection" : "Err transf balise vers iPod",
    "CannotTransferTags" : "Transf balises impossible",
    "TagSaved" : "Balise enregistrée",
    "TagSavedtoIpod" : "Balise enregistrée sur l’iPod",
    "TagSavedtoSystem" : "Balise enregistrée sur syst",
    "MemoryFull" : "Mémoire pleine",
    "AllMemoryFull" : "Toutes mémoires pleines",
    "TagMemoryFull" : "Mémoires balises pleines",
    "TagAlreadySaved" : "Balise déjà enregistrée",
    "IpodFull" : "Mémoire iPod pleine",
    "TagTransferredtoiPod" : "Balise transférée sur l’iPod",
    "UnplugAndReconnect" : "Débrancher et reconnecter",
    "TagNotYetProcessed" : "Balise non encore traitée",
    "Remaining" : "{numberOfTags} restants",
    "IpodError" : "Erreur de l’iPod",
    "ConnectIPod" : "Conct iPod pr transf balis",
    "TagsCannotBeSaved" : "Balises non enregistrables",
    "AllTagsTransferred" : "Toutes balises transférées",
    "FMRadio" : "Radio FM",
    "Noresultsfound" : "Aucun résultat trouvé",
    "UpdatingStationList" : "Mise à jour de liste des stations",
    "GenreSeek" : "Recherche de Genre",
    "ChangeGenre" : "Modifier genre",
    "TAOff" : "Info circ off",
    "Remove" : "Supprimer",
    "SignalLost" : "Signal perdu",
    "AlternativeFrequency" : "Autre fréquence",
    "Close" : "Ferm",
    "VrHelp_NowPlayingNA_Help_Left1" : "Divertissements",
    "VrHelp_NowPlayingNA_Help_Left2" : "Liste des stations",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favori",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD activé/désactivé",
    "VrHelp_NowPlayingNA_Help_Left5" : "Balayage",
    "VrHelp_NowPlayingNA_Help_Right1" : "Régler",
    "VrHelp_NowPlayingNA_Help_Right2" : "Balisage iTunes",
    "VrHelp_NowPlayingNA_Help_Right3" : "Rechercher précédent",
    "VrHelp_NowPlayingNA_Help_Right4" : "Rechercher suivant",
    "VrHelp_NowPlayingNA_Help_Right5" : "Mémoire automatique",
    "VrHelp_NowPlayingEU_Help_Left1" : "Divertissements",
    "VrHelp_NowPlayingEU_Help_Left2" : "Liste des stations",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favori",
    "VrHelp_NowPlayingEU_Help_Left4" : "Balayage",
    "VrHelp_NowPlayingEU_Help_Left5" : "Régler",
    "VrHelp_NowPlayingEU_Help_Right1" : "Avertissement de circulation",
    "VrHelp_NowPlayingEU_Help_Right2" : "Rechercher précédent",
    "VrHelp_NowPlayingEU_Help_Right3" : "Rechercher suivant",
    "VrHelp_NowPlayingEU_Help_Right4" : "Paramètres FM",
    "VrHelp_NowPlayingEU_Help_Right5" : "Paramètres audio",
    "VrHelp_NowPlayingOther_Help_Left1" : "Divertissements",
    "VrHelp_NowPlayingOther_Help_Left2" : "Mémoire automatique",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favori",
    "VrHelp_NowPlayingOther_Help_Left4" : "Balayage",
    "VrHelp_NowPlayingOther_Help_Left5" : "Régler",
    "VrHelp_NowPlayingOther_Help_Right1" : "Rechercher précédent",
    "VrHelp_NowPlayingOther_Help_Right2" : "Rechercher suivant",
    "VrHelp_NowPlayingOther_Help_Right3" : "Paramètres audio",
    "VrHelp_AutoMemory_Help1_Left1" : "(fréquence)",
    "VrHelp_AutoMemory_Help1_Left2" : "Mettre liste à jour",
    "VrHelp_AutoMemory_Help2_Left1" : "Mettre liste à jour",
    "VrHelp_Tune_NA_Help_Left1" : "(fréquence)",
    "VrHelp_Tune_NA_Help_Left2" : "Régler sur la radio précédente",
    "VrHelp_Tune_NA_Help_Left3" : "Régler sur la radio suivante",
    "VrHelp_Tune_nonNA_Help_Left1" : "(fréquence)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Régler sur la radio précédente",
    "VrHelp_Tune_nonNA_Help_Left3" : "Régler sur la radio suivante",
    "VrHelp_Settings_Help_Left1" : "Autre fréquence activé",
    "VrHelp_Settings_Help_Left2" : "Autre fréquence désactivé",
    "VrHelp_Settings_Help_Left3" : "Verrouillage régional activé",
    "VrHelp_Settings_Help_Left4" : "Verrouillage régional désactivé",
    "VrHelp_GenreSeek_Help_Left1" : "Recherche radio précédente",
    "VrHelp_GenreSeek_Help_Left2" : "Recherche radio suivante",
    "VrHelp_GenreSeek_Help_Left3" : "Modifier genre",
    "TrafficAlertOn" : "Avertissement de circulation activé",
    "TrafficAlertOff" : "Avertissement de circulation désactivé",
    "TagCaptured" : "Balise enregistrée",
    "GenreName" : "Genre:  {genreName}",
    "favorites_Tooltip" : "Favoris",
    "hdChannels_Tooltip" : "Canaux HD",
    "rbds_Weather" : "Météo",
    "rbds_Talk" : "Parler",
    "rbds_Class" : "Rock Classique",
    "rbds_Adult" : "Hits Adultes",
    "rbds_SoftRock" : "Soft Rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Musique douce",
    "rbds_Nostalgia" : "Nostalgie",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Classique",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rythme et Blues",
    "rbds_SoftRB" : "R&B Doux",
    "rbds_Foreign" : "Langue Étrangère",
    "rbds_ReligousM" : "Musique Religieuse",
    "rbds_ReligousT" : "Discussion Religieuse",
    "rbds_News" : "Actualités",
    "rbds_Personality" : "Personnalité",
    "rbds_Info" : "Information",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Publique",
    "rbds_College" : "Collège",
    "rbds_Hablar" : "Hablar Español",
    "rbds_Musica" : "Música Español",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Test d'Urgence",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Alerte! Alerte!",
    "rbds_genre_Weather" : "Genre: Météo",
    "rbds_genre_Talk" : "Genre: Parler",
    "rbds_genre_Class" : "Genre: Rock Classique",
    "rbds_genre_Adult" : "Genre: Hits Adultes",
    "rbds_genre_SoftRock" : "Genre: Soft Rock",
    "rbds_genre_Top40" : "Genre: Top 40",
    "rbds_genre_Soft" : "Genre: Doux",
    "rbds_genre_Nostalgia" : "Genre: Nostalgie",
    "rbds_genre_Jazz" : "Genre: Jazz",
    "rbds_genre_Country" : "Genre: Country",
    "rbds_genre_Classical" : "Genre: Classique",
    "rbds_genre_Oldies" : "Genre: Oldies",
    "rbds_genre_Rhythym" : "Genre: Rythme and Blues",
    "rbds_genre_SoftRB" : "Genre: R&B doux",
    "rbds_genre_Foreign" : "Genre: Langue Étrangère",
    "rbds_genre_ReligousM" : "Genre: Musique Religieuse",
    "rbds_genre_ReligousT" : "Genre: Discussion religieuse",
    "rbds_genre_News" : "Genre: Actualités",
    "rbds_genre_Personality" : "Genre: Personnalité",
    "rbds_genre_Info" : "Genre: Information",
    "rbds_genre_Sports" : "Genre: Sports",
    "rbds_genre_Public" : "Genre: Publique",
    "rbds_genre_College" : "Genre: Collège",
    "rbds_genre_Hablar" : "Genre: Hablar Español",
    "rbds_genre_Musica" : "Genre: Música Español",
    "rbds_genre_HipHop" : "Genre: Hip Hop",
    "rbds_genre_EmergencyTest" : "Genre: Test d'Urgence",
    "rbds_genre_Rock" : "Genre: Rock",
    "rbds_genre_Emergency" : "Genre: Alerte! Alerte!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Genre: --",
};

framework.registerAppDictLoaded("fmradio", "fr_FR");