var Localization_fmradioAppDict_da_DK = {
    //"stringId" : "localString"
    "UpdateStationList" : "Opdatér stationsliste",
    "AutoMemoryList" : "Liste med automatisk hukommelse",
    "StationList" : "Stationsliste",
    "FMSettings" : "FM-indstillinger",
    "HDRadio" : "HD-radio",
    "TrafficAlert" : "Trafikvarsel",
    "RegionLock" : "Regionslås",
    "GenreList" : "Genreliste",
    "HDStations" : "HD-stationer",
    "AllStations" : "Alle stationer",
    "News" : "Nyheder",
    "Affairs" : "Politik",
    "Info" : "Information",
    "Sport" : "Sport",
    "Education" : "Uddannelse",
    "Drama" : "Dramatik",
    "Culture" : "Kultur",
    "Science" : "Videnskab",
    "Varied" : "Blandet",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Easy Listening ",
    "Light" : "Let",
    "Classics" : "Klassikere",
    "Other" : "Andet",
    "Weather" : "Vejr",
    "Finance" : "Finans",
    "Childrens" : "For børn",
    "Religion" : "Religion",
    "Social" : "Social",
    "PhoneIn" : "Ring ind",
    "Travel" : "Rejser",
    "Leisure" : "Fritid",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "National",
    "Oldies" : "Oldies",
    "Folk" : "Folkemusik",
    "Documentary" : "Dokumentar",
    "AlarmTest" : "Alarmtest",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Genre: alle stationer",
    "GenreNews" : "Genre: Nyheder",
    "GenreAffairs" : "Genre: Politik",
    "GenreInfo" : "Genre: Information",
    "GenreSport" : "Genre: Sport",
    "GenreEducation" : "Genre: Undervisning",
    "GenreDrama" : "Genre: Drama",
    "GenreCulture" : "Genre: Kultur",
    "GenreScience" : "Genre: Videnskab",
    "GenreVaried" : "Genre: Diverse",
    "GenrePop" : "Genre: Pop",
    "GenreRock" : "Genre: Rock",
    "GenreMor" : "Genre: Easy Listening",
    "GenreLight" : "Genre: Let",
    "GenreClassics" : "Genre: Klassisk",
    "GenreOther" : "Genre: Andet",
    "GenreWeather" : "Genre: Vejret",
    "GenreFinance" : "Genre: Finans",
    "GenreChildrens" : "Genre: For børn",
    "GenreReligion" : "Genre: Religion",
    "GenrePhoneIn" : "Genre: Ring ind",
    "GenreTravel" : "Genre: Rejser",
    "GenreLeisure" : "Genre: Fritid",
    "GenreJazz" : "Genre: Jazz",
    "GenreCountry" : "Genre: Countrymusik",
    "GenreNational" : "Genre: National",
    "GenreOldies" : "Genre: Oldies",
    "GenreFolk" : "Genre: Folkemusik",
    "GenreDocumentary" : "Genre: Dokumentar",
    "GenreAlarmTest" : "Genre: Alarmtest",
    "GenreAlarm" : "Genre: Alarm",
    "GenreSocial" : "Genre: Social",
    "ErrorConnection" : "Fejl: tag-overfør. til iPod",
    "CannotTransferTags" : "Kan ikke overføre tags",
    "TagSaved" : "Tag gemt",
    "TagSavedtoIpod" : "Tag gemt på iPod",
    "TagSavedtoSystem" : "Tag gemt på Systemet",
    "MemoryFull" : "Hukommelsen er fuld",
    "AllMemoryFull" : "Hele hukommelsen er fuld",
    "TagMemoryFull" : "Tag-hukommelsen er fuld",
    "TagAlreadySaved" : "Tag allerede gemt",
    "IpodFull" : " iPod fuld",
    "TagTransferredtoiPod" : "Tag overført til iPod",
    "UnplugAndReconnect" : "Tag stik ud og genforbind",
    "TagNotYetProcessed" : "Tag endnu ikke bearbejdet",
    "Remaining" : "{numberOfTags} tilbage",
    "IpodError" : "Fejl i iPod",
    "ConnectIPod" : "Tilslut iPod for tagoverfør",
    "TagsCannotBeSaved" : "Tags kan ikke gemmes",
    "AllTagsTransferred" : "Alle tags er overført",
    "FMRadio" : "FM-radio",
    "Noresultsfound" : "Der blev ikke fundet resultater",
    "UpdatingStationList" : "Opdaterer stationsliste",
    "GenreSeek" : "Genre søgning",
    "ChangeGenre" : "Ændre genre",
    "TAOff" : "Trafikvar. Fra",
    "Remove" : "Fjern ",
    "SignalLost" : "Signal mistet",
    "AlternativeFrequency" : "Alternativ frekvens",
    "Close" : "Luk",
    "VrHelp_NowPlayingNA_Help_Left1" : "Underholdning",
    "VrHelp_NowPlayingNA_Help_Left2" : "Stationsliste",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On/Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Indstil",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Søg forrige",
    "VrHelp_NowPlayingNA_Help_Right4" : "Søg næste",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Hukommelse",
    "VrHelp_NowPlayingEU_Help_Left1" : "Underholdning",
    "VrHelp_NowPlayingEU_Help_Left2" : "Stationsliste",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Indstil",
    "VrHelp_NowPlayingEU_Help_Right1" : "Trafikmelding",
    "VrHelp_NowPlayingEU_Help_Right2" : "Søg forrige",
    "VrHelp_NowPlayingEU_Help_Right3" : "Søg næste",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM-indstillinger",
    "VrHelp_NowPlayingEU_Help_Right5" : "Lydindstillinger",
    "VrHelp_NowPlayingOther_Help_Left1" : "Underholdning",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto hukommelse",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorit",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Indstil",
    "VrHelp_NowPlayingOther_Help_Right1" : "Søg forrige",
    "VrHelp_NowPlayingOther_Help_Right2" : "Søg næste",
    "VrHelp_NowPlayingOther_Help_Right3" : "Lydindstillinger",
    "VrHelp_AutoMemory_Help1_Left1" : "(frekvens)",
    "VrHelp_AutoMemory_Help1_Left2" : "Opdatér liste",
    "VrHelp_AutoMemory_Help2_Left1" : "Opdatér liste",
    "VrHelp_Tune_NA_Help_Left1" : "(frekvens)",
    "VrHelp_Tune_NA_Help_Left2" : "Frekvens op",
    "VrHelp_Tune_NA_Help_Left3" : "Frekvens ned",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frekvens)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Frekvens op",
    "VrHelp_Tune_nonNA_Help_Left3" : "Frekvens ned",
    "VrHelp_Settings_Help_Left1" : "Alternativ frekvens til",
    "VrHelp_Settings_Help_Left2" : "Alternativ frekvens fra",
    "VrHelp_Settings_Help_Left3" : "Regional til",
    "VrHelp_Settings_Help_Left4" : "Regional fra",
    "VrHelp_GenreSeek_Help_Left1" : "Søg op",
    "VrHelp_GenreSeek_Help_Left2" : "Søg ned",
    "VrHelp_GenreSeek_Help_Left3" : "Skift genre",
    "TrafficAlertOn" : "Trafikmelding til",
    "TrafficAlertOff" : "Trafikmelding fra",
    "TagCaptured" : "Tag fundet",
    "GenreName" : "Genre: {genreName}",
    "favorites_Tooltip" : "Favoritter",
    "hdChannels_Tooltip" : "HD-kanaler",
    "rbds_Weather" : "Vejr",
    "rbds_Talk" : "Tale",
    "rbds_Class" : "Classic Rock",
    "rbds_Adult" : "Voksen Hits",
    "rbds_SoftRock" : "Soft Rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Soft",
    "rbds_Nostalgia" : "Nostalgi",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Klassisk",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rhythm og Blues",
    "rbds_SoftRB" : "Soft R&B",
    "rbds_Foreign" : "Udenlandske Sprog",
    "rbds_ReligousM" : "Religiøs Musik",
    "rbds_ReligousT" : "Religiøs",
    "rbds_News" : "Nyheder",
    "rbds_Personality" : "Personlighed",
    "rbds_Info" : "Information",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Public",
    "rbds_College" : "College",
    "rbds_Hablar" : "Spansk",
    "rbds_Musica" : "Spansk Musik",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Emergency Test",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Advarsel! Advarsel!",
    "rbds_genre_Weather" : "Genre: Vejr",
    "rbds_genre_Talk" : "Genre: Tal",
    "rbds_genre_Class" : "Genre: Klassisk rock",
    "rbds_genre_Adult" : "Genre: Voksen",
    "rbds_genre_SoftRock" : "Genre: Blød rock",
    "rbds_genre_Top40" : "Genre: Top 40",
    "rbds_genre_Soft" : "Genre: Rolig",
    "rbds_genre_Nostalgia" : "Genre: Nostalgi",
    "rbds_genre_Jazz" : "Genre: Jazz",
    "rbds_genre_Country" : "Genre: Country",
    "rbds_genre_Classical" : "Genre: Klassisk",
    "rbds_genre_Oldies" : "Genre: Oldies",
    "rbds_genre_Rhythym" : "Genre: Rytme og Blues",
    "rbds_genre_SoftRB" : "Genre: Soft R&B",
    "rbds_genre_Foreign" : "Genre: Udenlandske sprog",
    "rbds_genre_ReligousM" : "Genre: Religiøs musik",
    "rbds_genre_ReligousT" : "Genre: Religiøs snak",
    "rbds_genre_News" : "Genre: Nyheder",
    "rbds_genre_Personality" : "Genre: Personlighed",
    "rbds_genre_Info" : "Genre: Information",
    "rbds_genre_Sports" : "Genre: Sport",
    "rbds_genre_Public" : "Genre: Offentlig",
    "rbds_genre_College" : "Genre: College",
    "rbds_genre_Hablar" : "Genre: Spansk tale",
    "rbds_genre_Musica" : "Genre: Spansk Musik",
    "rbds_genre_HipHop" : "Genre: Hip Hop",
    "rbds_genre_EmergencyTest" : "Genre: Nødtest",
    "rbds_genre_Rock" : "Genre: Rock",
    "rbds_genre_Emergency" : "Genre: Advarsel! Advarsel!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Genre: --",
};

framework.registerAppDictLoaded("fmradio", "da_DK");