var Localization_fmradioAppDict_it_IT = {
    //"stringId" : "localString"
    "UpdateStationList" : "Aggiorna elenco stazioni",
    "AutoMemoryList" : "Elenco memoria automatica",
    "StationList" : "Elenco stazioni",
    "FMSettings" : "Impostazioni FM",
    "HDRadio" : "Radio HD",
    "TrafficAlert" : "Allerta traffico",
    "RegionLock" : "Blocco territoriale",
    "GenreList" : "Elenco generi",
    "HDStations" : "Stazioni HD",
    "AllStations" : "Tutte le stazioni",
    "News" : "Notizie",
    "Affairs" : "Affari",
    "Info" : "Informazioni",
    "Sport" : "Sport",
    "Education" : "Istruzione",
    "Drama" : "Teatro",
    "Culture" : "Cultura",
    "Science" : "Scienza",
    "Varied" : "Vari",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Di facile ascolto",
    "Light" : "Leggera",
    "Classics" : "Classica",
    "Other" : "Altro",
    "Weather" : "Clima",
    "Finance" : "Finanza",
    "Childrens" : "Bambini",
    "Religion" : "Religione",
    "Social" : "Sociale",
    "PhoneIn" : "Con telefonate",
    "Travel" : "Viaggi",
    "Leisure" : "Tempo libero",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "Nazionale",
    "Oldies" : "Classici",
    "Folk" : "Folk",
    "Documentary" : "Documentari",
    "AlarmTest" : "Allarme Test",
    "Alarm" : "Allarme",
    "GenreAllStations" : "Genere: tutte le stazioni",
    "GenreNews" : "Genere: Notizie",
    "GenreAffairs" : "Genere: Affari",
    "GenreInfo" : "Genere: Informazioni",
    "GenreSport" : "Genere: Sport",
    "GenreEducation" : "Genere: Istruzione",
    "GenreDrama" : "Genere: Teatro",
    "GenreCulture" : "Genere: Cultura",
    "GenreScience" : "Genere: Scienza",
    "GenreVaried" : "Genere: Vari",
    "GenrePop" : "Genere: Pop",
    "GenreRock" : "Genere: Rock",
    "GenreMor" : "Genere: di facile ascolto",
    "GenreLight" : "Genere: Leggera",
    "GenreClassics" : "Genere: Classica",
    "GenreOther" : "Genere: Altro",
    "GenreWeather" : "Genere: Clima",
    "GenreFinance" : "Genere: Finanza",
    "GenreChildrens" : "Genere: Bambini",
    "GenreReligion" : "Genere: Religione",
    "GenrePhoneIn" : "Genere: Programma con telefonate",
    "GenreTravel" : "Genere: Viaggi",
    "GenreLeisure" : "Genere: Tempo libero",
    "GenreJazz" : "Genere: Jazz",
    "GenreCountry" : "Genere: Country",
    "GenreNational" : "Genere: Nazionale",
    "GenreOldies" : "Genere: Classici",
    "GenreFolk" : "Genere: Folk",
    "GenreDocumentary" : "Genere: Documentari",
    "GenreAlarmTest" : "Genere: Test allarme",
    "GenreAlarm" : "Genere: Allarme",
    "GenreSocial" : "Genere: Sociale",
    "ErrorConnection" : "Errore invio Tag su iPod.",
    "CannotTransferTags" : "Impossibile trasferire tag.",
    "TagSaved" : "Tag salvata.",
    "TagSavedtoIpod" : "Tag salvata su iPod.",
    "TagSavedtoSystem" : "Tag salvata su sistema.",
    "MemoryFull" : "Memoria piena.",
    "AllMemoryFull" : "Memoria piena.",
    "TagMemoryFull" : "Memoria tag piena.",
    "TagAlreadySaved" : "Tag già salvata.",
    "IpodFull" : "iPod pieno.",
    "TagTransferredtoiPod" : "Tag trasferita su iPod.",
    "UnplugAndReconnect" : "Sconnetti e riconnetti",
    "TagNotYetProcessed" : "Tag non processata.",
    "Remaining" : "{numberOfTags} Rimanenti",
    "IpodError" : "Errore iPod ",
    "ConnectIPod" : "Conn iPod per trasfer tag",
    "TagsCannotBeSaved" : "Impossibile salvare le tag.",
    "AllTagsTransferred" : "Tutte le tag trasferite.",
    "FMRadio" : "Radio FM",
    "Noresultsfound" : "Nessun risultato trovato.",
    "UpdatingStationList" : "Aggiornamento elenco stazioni",
    "GenreSeek" : "Ricerca genere",
    "ChangeGenre" : "Cambia genere",
    "TAOff" : "TA spento",
    "Remove" : "Elimina",
    "SignalLost" : "Segnale perso",
    "AlternativeFrequency" : "Frequenza alternativa",
    "Close" : "Chiudi",
    "VrHelp_NowPlayingNA_Help_Left1" : "Intrattenimento",
    "VrHelp_NowPlayingNA_Help_Left2" : "Elenco stazioni",
    "VrHelp_NowPlayingNA_Help_Left3" : "Preferita",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD acceso / spento",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scansione",
    "VrHelp_NowPlayingNA_Help_Right1" : "Sintonizza",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Cerca precedente",
    "VrHelp_NowPlayingNA_Help_Right4" : "Cerca successivo",
    "VrHelp_NowPlayingNA_Help_Right5" : "Memoria automatica",
    "VrHelp_NowPlayingEU_Help_Left1" : "Intrattenimento",
    "VrHelp_NowPlayingEU_Help_Left2" : "Elenco stazioni",
    "VrHelp_NowPlayingEU_Help_Left3" : "Preferito",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scansione",
    "VrHelp_NowPlayingEU_Help_Left5" : "Sintonizza",
    "VrHelp_NowPlayingEU_Help_Right1" : "Allerta traffico",
    "VrHelp_NowPlayingEU_Help_Right2" : "Cerca precedente",
    "VrHelp_NowPlayingEU_Help_Right3" : "Cerca successivo",
    "VrHelp_NowPlayingEU_Help_Right4" : "Impostazioni FM",
    "VrHelp_NowPlayingEU_Help_Right5" : "Impostazioni audio",
    "VrHelp_NowPlayingOther_Help_Left1" : "Intrattenimento",
    "VrHelp_NowPlayingOther_Help_Left2" : "Memoria automatica",
    "VrHelp_NowPlayingOther_Help_Left3" : "Preferito",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scansione",
    "VrHelp_NowPlayingOther_Help_Left5" : "Sintonizza",
    "VrHelp_NowPlayingOther_Help_Right1" : "Cerca precedente",
    "VrHelp_NowPlayingOther_Help_Right2" : "Cerca successivo",
    "VrHelp_NowPlayingOther_Help_Right3" : "Impostazioni audio",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequenza)",
    "VrHelp_AutoMemory_Help1_Left2" : "Aggiorna elenco",
    "VrHelp_AutoMemory_Help2_Left1" : "Aggiorna elenco",
    "VrHelp_Tune_NA_Help_Left1" : "(frequenza)",
    "VrHelp_Tune_NA_Help_Left2" : "Sintonizza indietro",
    "VrHelp_Tune_NA_Help_Left3" : "Sintonizza avanti",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequenza)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Sintonizza indietro",
    "VrHelp_Tune_nonNA_Help_Left3" : "Sintonizza avanti",
    "VrHelp_Settings_Help_Left1" : "Frequenza alternativa accesa",
    "VrHelp_Settings_Help_Left2" : "Frequenza alternativa spenta",
    "VrHelp_Settings_Help_Left3" : "Blocco territoriale acceso",
    "VrHelp_Settings_Help_Left4" : "Blocco territoriale spento",
    "VrHelp_GenreSeek_Help_Left1" : "Cerca indietro",
    "VrHelp_GenreSeek_Help_Left2" : "Cerca avanti",
    "VrHelp_GenreSeek_Help_Left3" : "Cambia genere",
    "TrafficAlertOn" : "Allerta traffico accesa",
    "TrafficAlertOff" : "Allerta traffico spenta",
    "TagCaptured" : "Tag catturata",
    "GenreName" : "Genere: {genreName}",
    "favorites_Tooltip" : "Preferiti",
    "hdChannels_Tooltip" : "Canali HD",
    "rbds_Weather" : "Clima",
    "rbds_Talk" : "Conversazioni",
    "rbds_Class" : "Rock classico",
    "rbds_Adult" : "Vecchie hit",
    "rbds_SoftRock" : "Rock leggero",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Soft",
    "rbds_Nostalgia" : "Nostalgica",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Classica",
    "rbds_Oldies" : "Classici",
    "rbds_Rhythym" : "Rhythm and Blues",
    "rbds_SoftRB" : "Rhythm and Blues soft",
    "rbds_Foreign" : "In lingua straniera",
    "rbds_ReligousM" : "Musica religiosa",
    "rbds_ReligousT" : "Discorsi Religiosi",
    "rbds_News" : "Notizie",
    "rbds_Personality" : "Personalità",
    "rbds_Info" : "Informazioni",
    "rbds_Sports" : "Sport",
    "rbds_Public" : "Pubblico",
    "rbds_College" : "Università",
    "rbds_Hablar" : "In Spagnolo",
    "rbds_Musica" : "Musica Spagnola",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Test di Emergenza",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Alert! Alert!",
    "rbds_genre_Weather" : "Genere: Clima",
    "rbds_genre_Talk" : "Genere: Conversazioni",
    "rbds_genre_Class" : "Genere: Rock classico",
    "rbds_genre_Adult" : "Genere: Vecchie hit",
    "rbds_genre_SoftRock" : "Genere: Rock leggero",
    "rbds_genre_Top40" : "Genere: Top 40",
    "rbds_genre_Soft" : "Genere: Soft",
    "rbds_genre_Nostalgia" : "Genere: Nostalgica",
    "rbds_genre_Jazz" : "Genere: Jazz",
    "rbds_genre_Country" : "Genere: Country",
    "rbds_genre_Classical" : "Genere: Classica",
    "rbds_genre_Oldies" : "Genere: Classici",
    "rbds_genre_Rhythym" : "Genere: Rhythm and Blues",
    "rbds_genre_SoftRB" : "Genere: Rhythm and Blues soft",
    "rbds_genre_Foreign" : "Genere: In lingua straniera",
    "rbds_genre_ReligousM" : "Genere: Musica religiosa",
    "rbds_genre_ReligousT" : "Genere: Discorsi Religiosi",
    "rbds_genre_News" : "Genere: Notizie",
    "rbds_genre_Personality" : "Genere: Personalità",
    "rbds_genre_Info" : "Genere: Informazioni",
    "rbds_genre_Sports" : "Genere: Sport",
    "rbds_genre_Public" : "Genere: Pubblico",
    "rbds_genre_College" : "Genere: Università",
    "rbds_genre_Hablar" : "Genere: In Spagnolo",
    "rbds_genre_Musica" : "Genere: Musica Spagnola",
    "rbds_genre_HipHop" : "Genere: Hip Hop",
    "rbds_genre_EmergencyTest" : "Genere: Test di Emergenza",
    "rbds_genre_Rock" : "Genere: Rock",
    "rbds_genre_Emergency" : "Genere: Alert! Alert!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Genere: --",
};

framework.registerAppDictLoaded("fmradio", "it_IT");