var Localization_fmradioAppDict_hu_HU = {
    //"stringId" : "localString"
    "UpdateStationList" : "Rádióadók listájának frissítése",
    "AutoMemoryList" : "Automemória-lista",
    "StationList" : "Rádióadások listája",
    "FMSettings" : "FM beállítások",
    "HDRadio" : "HD rádió",
    "TrafficAlert" : "Útinform",
    "RegionLock" : "Régiózár",
    "GenreList" : "Műfajlista",
    "HDStations" : "HD rádióadók",
    "AllStations" : "Az összes állomás",
    "News" : "Hírek",
    "Affairs" : "Hírháttér",
    "Info" : "Tájékoztatás",
    "Sport" : "Sport",
    "Education" : "Nevelés",
    "Drama" : "Dráma",
    "Culture" : "Kultúra",
    "Science" : "Tudomány",
    "Varied" : "Vegyes",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Fülbemászó zene",
    "Light" : "Könnyűzene",
    "Classics" : "Klasszikus",
    "Other" : "Egyéb",
    "Weather" : "Időjárás",
    "Finance" : "Gazdaság",
    "Childrens" : "Gyerekek",
    "Religion" : "Vallás",
    "Social" : "Közösségi",
    "PhoneIn" : "Betelefonálás",
    "Travel" : "Utazás",
    "Leisure" : "Szabadidő",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "Országos",
    "Oldies" : "Örökzöldek",
    "Folk" : "Népzene",
    "Documentary" : "Dokumentum",
    "AlarmTest" : "Riasztóteszt",
    "Alarm" : "Riasztó",
    "GenreAllStations" : "Műfaj: Az összes állomás",
    "GenreNews" : "Műfaj: Hírek",
    "GenreAffairs" : "Műfaj: Hírháttér",
    "GenreInfo" : "Műfaj: Tájékoztatás",
    "GenreSport" : "Műfaj: Sport",
    "GenreEducation" : "Műfaj: Nevelés",
    "GenreDrama" : "Műfaj: Dráma",
    "GenreCulture" : "Műfaj: Kultúra",
    "GenreScience" : "Műfaj: Tudomány",
    "GenreVaried" : "Műfaj: Vegyes",
    "GenrePop" : "Műfaj: Pop",
    "GenreRock" : "Műfaj: Rock",
    "GenreMor" : "Műfaj: Fülbemászó zene",
    "GenreLight" : "Műfaj: Könnyűzene",
    "GenreClassics" : "Műfaj: Klasszikus",
    "GenreOther" : "Műfaj: Egyéb",
    "GenreWeather" : "Műfaj: Időjárás",
    "GenreFinance" : "Műfaj: Gazdaság",
    "GenreChildrens" : "Műfaj: Gyerekek",
    "GenreReligion" : "Műfaj: Vallás",
    "GenrePhoneIn" : "Műfaj: Betelefonálás",
    "GenreTravel" : "Műfaj: Utazás",
    "GenreLeisure" : "Műfaj: Szabadidő",
    "GenreJazz" : "Műfaj: Jazz",
    "GenreCountry" : "Műfaj: Country",
    "GenreNational" : "Műfaj: Országos",
    "GenreOldies" : "Műfaj: Örökzöldek",
    "GenreFolk" : "Műfaj: Népzene",
    "GenreDocumentary" : "Műfaj: Ismeretterjesztő",
    "GenreAlarmTest" : "Műfaj: Próbariadó",
    "GenreAlarm" : "Műfaj: Riasztás",
    "GenreSocial" : "Műfaj: Közösségi hírek",
    "ErrorConnection" : "Hiba címk.iPodra adásakor",
    "CannotTransferTags" : "Címkék nem adhatók át",
    "TagSaved" : "Címke mentve",
    "TagSavedtoIpod" : "Címke iPod-ra mentve",
    "TagSavedtoSystem" : "Címke rendszerre mentve",
    "MemoryFull" : "Betelt a memória",
    "AllMemoryFull" : "Minden memória betelt",
    "TagMemoryFull" : "Címkememória betelt",
    "TagAlreadySaved" : "Címke már mentve",
    "IpodFull" : "iPod megtelt",
    "TagTransferredtoiPod" : "Címke iPod-ra átadva",
    "UnplugAndReconnect" : "Kihúzás és újracsatl.",
    "TagNotYetProcessed" : "Még feldolgozatlan címke",
    "Remaining" : "{numberOfTags} fennmar.",
    "IpodError" : "iPod-hiba",
    "ConnectIPod" : "iPod-csatl címkeátadáshoz",
    "TagsCannotBeSaved" : "Nem menthető címkék",
    "AllTagsTransferred" : "Minden címke átadva",
    "FMRadio" : "FM-rádió",
    "Noresultsfound" : "Nincs találat",
    "UpdatingStationList" : "Állomáslista frissítése",
    "GenreSeek" : "Műfajkeresés",
    "ChangeGenre" : "Műfaj módosítása",
    "TAOff" : "Forg fi kikap.",
    "Remove" : "Eltávolítás",
    "SignalLost" : "Megszakadt a jel",
    "AlternativeFrequency" : "Alternatív frekvencia",
    "Close" : "Bezár",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On / Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Útinform be",
    "TrafficAlertOff" : "Útinform ki",
    "TagCaptured" : "Címke rögzítve",
    "GenreName" : "Műfaj: {genreName}",
    "favorites_Tooltip" : "Kedvencek",
    "hdChannels_Tooltip" : "HD-csatornák",
    "rbds_Weather" : "Időjárás",
    "rbds_Talk" : "Beszélgetős",
    "rbds_Class" : "Klasszikus rock",
    "rbds_Adult" : "Felnőtt slágerek",
    "rbds_SoftRock" : "Lágy rock",
    "rbds_Top40" : "Legjobb 40",
    "rbds_Soft" : "Lágy",
    "rbds_Nostalgia" : "Nosztalgia",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Klasszikus",
    "rbds_Oldies" : "Örökzöldek",
    "rbds_Rhythym" : "Ritmus és blúz",
    "rbds_SoftRB" : "Lágy R&B",
    "rbds_Foreign" : "Idegen nyelv",
    "rbds_ReligousM" : "Vallási zene",
    "rbds_ReligousT" : "Vallási tárgyú ",
    "rbds_News" : "Hírek",
    "rbds_Personality" : "Személyiség",
    "rbds_Info" : "Tájékoztatás",
    "rbds_Sports" : "Sport",
    "rbds_Public" : "Nyilvános",
    "rbds_College" : "Főiskola",
    "rbds_Hablar" : "Spanyol nyelvű",
    "rbds_Musica" : "Spanyol zene",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Vészhelyzetpróba",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Figyelmeztetés! Figyelmeztetés!",
    "rbds_genre_Weather" : "Műfaj: Időjárás",
    "rbds_genre_Talk" : "Műfaj: Beszélgetős",
    "rbds_genre_Class" : "Műfaj: Klasszikus rock",
    "rbds_genre_Adult" : "Műfaj: Felnőtt slágerek",
    "rbds_genre_SoftRock" : "Műfaj: Lágy rock",
    "rbds_genre_Top40" : "Műfaj: Legjobb 40",
    "rbds_genre_Soft" : "Műfaj: Lágy",
    "rbds_genre_Nostalgia" : "Műfaj: Nosztalgia",
    "rbds_genre_Jazz" : "Műfaj: Jazz",
    "rbds_genre_Country" : "Műfaj: Country",
    "rbds_genre_Classical" : "Műfaj: Klasszikus",
    "rbds_genre_Oldies" : "Műfaj: Örökzöldek",
    "rbds_genre_Rhythym" : "Műfaj: Ritmus és blúz",
    "rbds_genre_SoftRB" : "Műfaj: Lágy R&B",
    "rbds_genre_Foreign" : "Műfaj: Idegen nyelv",
    "rbds_genre_ReligousM" : "Műfaj: Vallási zene",
    "rbds_genre_ReligousT" : "Műfaj: Vallási tárgyú ",
    "rbds_genre_News" : "Műfaj: Hírek",
    "rbds_genre_Personality" : "Műfaj: Személyiség",
    "rbds_genre_Info" : "Műfaj: Tájékoztatás",
    "rbds_genre_Sports" : "Műfaj: Sport",
    "rbds_genre_Public" : "Műfaj: Nyilvános",
    "rbds_genre_College" : "Műfaj: Főiskola",
    "rbds_genre_Hablar" : "Műfaj: Spanyol nyelvű",
    "rbds_genre_Musica" : "Műfaj: Spanyol zene",
    "rbds_genre_HipHop" : "Műfaj: Hip Hop",
    "rbds_genre_EmergencyTest" : "Műfaj: Vészhelyzetpróba",
    "rbds_genre_Rock" : "Műfaj: Rock",
    "rbds_genre_Emergency" : "Műfaj: Figyelmeztetés!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Műfaj: --",
};

framework.registerAppDictLoaded("fmradio", "hu_HU");