var Localization_fmradioAppDict_sk_SK = {
    //"stringId" : "localString"
    "UpdateStationList" : "Aktualizovať zoznam staníc",
    "AutoMemoryList" : "Zoznam automatickej pamäte",
    "StationList" : "Zoznam staníc",
    "FMSettings" : "Nastavenia FM",
    "HDRadio" : "HD rádio",
    "TrafficAlert" : "Dopravné upozornenie",
    "RegionLock" : "Zámok regiónu",
    "GenreList" : "Zoznam žánrov",
    "HDStations" : "HD stanice",
    "AllStations" : "Všetky stanice",
    "News" : "Novinky",
    "Affairs" : "Udalosti",
    "Info" : "Informácie",
    "Sport" : "Šport",
    "Education" : "Vzdelávanie",
    "Drama" : "Dráma",
    "Culture" : "Kultúra",
    "Science" : "Veda",
    "Varied" : "Rôzne",
    "Pop" : "Pop",
    "Rock" : "Rock",
    "Mor" : "Ľahké počúvanie",
    "Light" : "Light",
    "Classics" : "Klasika",
    "Other" : "Iné",
    "Weather" : "Počasie",
    "Finance" : "Financie",
    "Childrens" : "Deti",
    "Religion" : "Náboženstvo",
    "Social" : "Spoločenské",
    "PhoneIn" : "Phone In",
    "Travel" : "Cestovanie",
    "Leisure" : "Voľný čas",
    "Jazz" : "Jazz",
    "Country" : "Country",
    "National" : "Národné",
    "Oldies" : "Oldies",
    "Folk" : "Folk",
    "Documentary" : "Dokumentárne",
    "AlarmTest" : "Test alarmu",
    "Alarm" : "Alarm",
    "GenreAllStations" : "Žáner: Všetky stanice",
    "GenreNews" : "Žáner: Novinky",
    "GenreAffairs" : "Žáner: Udalosti",
    "GenreInfo" : "Žáner: Informácie",
    "GenreSport" : "Žáner: Šport",
    "GenreEducation" : "Žáner: Vzdelávanie",
    "GenreDrama" : "Žáner: Dráma",
    "GenreCulture" : "Žáner: Kultúra",
    "GenreScience" : "Žáner: Veda",
    "GenreVaried" : "Žáner: Rôzne",
    "GenrePop" : "Žáner: Pop",
    "GenreRock" : "Žáner: Rock",
    "GenreMor" : "Žáner: Ľahké počúvanie",
    "GenreLight" : "Žáner: Ľahké",
    "GenreClassics" : "Žáner: Klasika",
    "GenreOther" : "Žáner: Iné",
    "GenreWeather" : "Žáner: Počasie",
    "GenreFinance" : "Žáner: Financie",
    "GenreChildrens" : "Žáner: Deti",
    "GenreReligion" : "Žáner: Náboženstvo",
    "GenrePhoneIn" : "Žáner: PhoneIn",
    "GenreTravel" : "Žáner: Cestovanie",
    "GenreLeisure" : "Žáner: Voľný čas",
    "GenreJazz" : "Žáner: Jazz",
    "GenreCountry" : "Žáner: Country",
    "GenreNational" : "Žáner: Národné",
    "GenreOldies" : "Žáner: Oldies",
    "GenreFolk" : "Žáner: Folk",
    "GenreDocumentary" : "Žáner: Dokumentárne",
    "GenreAlarmTest" : "Žáner: Test alarmu",
    "GenreAlarm" : "Žáner: Alarm",
    "GenreSocial" : "Žáner: Spoločnosť",
    "ErrorConnection" : "Tag prenesený do iPodu",
    "CannotTransferTags" : "Značky nemožno preniesť",
    "TagSaved" : "Značka uložená",
    "TagSavedtoIpod" : "Značka uložená do iPodu",
    "TagSavedtoSystem" : "Značka uložená do sys.",
    "MemoryFull" : "Pamäť plná",
    "AllMemoryFull" : "Celá pamäť plná",
    "TagMemoryFull" : "Pamäť značiek plná",
    "TagAlreadySaved" : "Značka už uložená",
    "IpodFull" : "iPod je plný",
    "TagTransferredtoiPod" : "Tag prenesený do iPodu",
    "UnplugAndReconnect" : "Odpojiť a znovu pripojiť",
    "TagNotYetProcessed" : "Znač. nie je spracovaná",
    "Remaining" : "Zostáva {numberOfTags}",
    "IpodError" : "Chyba iPod-u",
    "ConnectIPod" : "Na prenos zn. prip. iPod",
    "TagsCannotBeSaved" : "Značky nemožno uložiť",
    "AllTagsTransferred" : "Všetky značky prenesené",
    "FMRadio" : "FM rádio",
    "Noresultsfound" : "Nenašli sa žiadne výsledky",
    "UpdatingStationList" : "Aktualizácia zoznamu staníc",
    "GenreSeek" : "Vyhľadávanie žánru",
    "ChangeGenre" : "Zmeniť žáner",
    "TAOff" : "TA vyp.",
    "Remove" : "Odstrániť",
    "SignalLost" : "Signál sa stratil",
    "AlternativeFrequency" : "Alternatívna frekvencia",
    "Close" : "Zat.",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On / Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Premávka zap.",
    "TrafficAlertOff" : "Premávka vyp.",
    "TagCaptured" : "Značka zachytená",
    "GenreName" : "Žáner: {genreName}",
    "favorites_Tooltip" : "Obľúbené",
    "hdChannels_Tooltip" : "HD kanály",
    "rbds_Weather" : "Počasie",
    "rbds_Talk" : "Rozhovory",
    "rbds_Class" : "Klasický Rock",
    "rbds_Adult" : "Dospelých Hity",
    "rbds_SoftRock" : "Mäkký Rock",
    "rbds_Top40" : "Top 40",
    "rbds_Soft" : "Mäkký",
    "rbds_Nostalgia" : "Nostalgie",
    "rbds_Jazz" : "Jazz",
    "rbds_Country" : "Country",
    "rbds_Classical" : "Klasický",
    "rbds_Oldies" : "Oldies",
    "rbds_Rhythym" : "Rytmus a Blues",
    "rbds_SoftRB" : "Mäkký R&B",
    "rbds_Foreign" : "Cudzí Jazyk",
    "rbds_ReligousM" : "Náboženská Hudba",
    "rbds_ReligousT" : "Náboženské rozhovory",
    "rbds_News" : "Novinky",
    "rbds_Personality" : "Osobnosť",
    "rbds_Info" : "Informácie",
    "rbds_Sports" : "Sports",
    "rbds_Public" : "Verejnosť",
    "rbds_College" : "Koľaj",
    "rbds_Hablar" : "Hovoriť španielsky",
    "rbds_Musica" : "Španielska hudba",
    "rbds_HipHop" : "Hip Hop",
    "rbds_EmergencyTest" : "Núdzové Testy",
    "rbds_Rock" : "Rock",
    "rbds_Emergency" : "Upozornenie! Upozornenie!",
    "rbds_genre_Weather" : "Žáner: Počasie",
    "rbds_genre_Talk" : "Žáner: Počasie",
    "rbds_genre_Class" : "Žáner: Rozhovory",
    "rbds_genre_Adult" : "Žáner: Klasický Rock",
    "rbds_genre_SoftRock" : "Žáner: Dospelých Hity",
    "rbds_genre_Top40" : "Žáner: Mäkký Rock",
    "rbds_genre_Soft" : "Žáner: Top 40",
    "rbds_genre_Nostalgia" : "Žáner: Mäkký",
    "rbds_genre_Jazz" : "Žáner: Nostalgie",
    "rbds_genre_Country" : "Žáner: Jazz",
    "rbds_genre_Classical" : "Žáner: Country",
    "rbds_genre_Oldies" : "Žáner: Klasický",
    "rbds_genre_Rhythym" : "Žáner: Oldies",
    "rbds_genre_SoftRB" : "Žáner: Rytmus a Blues",
    "rbds_genre_Foreign" : "Žáner: Mäkký R&B",
    "rbds_genre_ReligousM" : "Žáner: Cudzí Jazyk",
    "rbds_genre_ReligousT" : "Žáner: Náboženská Hudba",
    "rbds_genre_News" : "Žáner: Náboženské rozhovory",
    "rbds_genre_Personality" : "Žáner: Novinky",
    "rbds_genre_Info" : "Žáner: Osobnosť",
    "rbds_genre_Sports" : "Žáner: Informácie",
    "rbds_genre_Public" : "Žáner: Sports",
    "rbds_genre_College" : "Žáner: Verejnosť",
    "rbds_genre_Hablar" : "Žáner: Koľaj",
    "rbds_genre_Musica" : "Žáner: Hovoriť španielsky",
    "rbds_genre_HipHop" : "Žáner: Španielska hudba",
    "rbds_genre_EmergencyTest" : "Žáner: Hip Hop",
    "rbds_genre_Rock" : "Žáner: Núdzové Testy",
    "rbds_genre_Emergency" : "Žáner: Rock",
    "rbds_None" : "--",
    "rbds_genre_None" : "Žáner: --",
};

framework.registerAppDictLoaded("fmradio", "sk_SK");