var Localization_fmradioAppDict_ru_RU = {
    //"stringId" : "localString"
    "UpdateStationList" : "Обновить список станций",
    "AutoMemoryList" : "Список автозапоминания",
    "StationList" : "Список станций",
    "FMSettings" : "Настройки FM",
    "HDRadio" : "Радио HD",
    "TrafficAlert" : "Уведомление о траффике",
    "RegionLock" : "Привязка к региону",
    "GenreList" : "Список жанров",
    "HDStations" : "Станции HD",
    "AllStations" : "Все станции",
    "News" : "Новости",
    "Affairs" : "Отношения",
    "Info" : "Информация",
    "Sport" : "Спорт",
    "Education" : "Образование",
    "Drama" : "Драма",
    "Culture" : "Культура",
    "Science" : "Наука",
    "Varied" : "Разное",
    "Pop" : "Поп",
    "Rock" : "Рок",
    "Mor" : "Легкая музыка",
    "Light" : "Легкая",
    "Classics" : "Классика",
    "Other" : "Прочее",
    "Weather" : "Погода",
    "Finance" : "Финансы",
    "Childrens" : "Дети",
    "Religion" : "Религия",
    "Social" : "Социальный",
    "PhoneIn" : "Сигнал вызова",
    "Travel" : "Путешествия",
    "Leisure" : "Досуг",
    "Jazz" : "Джаз",
    "Country" : "Кантри",
    "National" : "Национальная музыка",
    "Oldies" : "Ретро",
    "Folk" : "Фолк",
    "Documentary" : "Документальные фильмы",
    "AlarmTest" : "Тест аварийного сигнала",
    "Alarm" : "Аварийный сигнал",
    "GenreAllStations" : "Жанр: все станции",
    "GenreNews" : "Жанр: новости",
    "GenreAffairs" : "Жанр: отношения",
    "GenreInfo" : "Жанр: Информация",
    "GenreSport" : "Жанр: спорт",
    "GenreEducation" : "Жанр: образование",
    "GenreDrama" : "Жанр: драма",
    "GenreCulture" : "Жанр: культура",
    "GenreScience" : "Жанр: наука",
    "GenreVaried" : "Жанр: разное",
    "GenrePop" : "Жанр: поп",
    "GenreRock" : "Жанр: рок",
    "GenreMor" : "Жанр: Легкая музыка",
    "GenreLight" : "Жанр: легкая",
    "GenreClassics" : "Жанр: классика",
    "GenreOther" : "Жанр: прочее",
    "GenreWeather" : "Жанр: погода",
    "GenreFinance" : "Жанр: финансы",
    "GenreChildrens" : "Жанр: дети",
    "GenreReligion" : "Жанр: религия",
    "GenrePhoneIn" : "Жанр: прямая линия",
    "GenreTravel" : "Жанр: путешествия",
    "GenreLeisure" : "Жанр: досуг",
    "GenreJazz" : "Жанр: джаз",
    "GenreCountry" : "Жанр: кантри",
    "GenreNational" : "Жанр: национальная музыка",
    "GenreOldies" : "Жанр: ретро",
    "GenreFolk" : "Жанр: фолк",
    "GenreDocumentary" : "Жанр: Документальный",
    "GenreAlarmTest" : "Жанр: Проверка будильника",
    "GenreAlarm" : "Жанр: Будильник",
    "GenreSocial" : "Жанр: Общественный",
    "ErrorConnection" : "ошиб при прч. тэг в iPod",
    "CannotTransferTags" : "Невозм передать тэги",
    "TagSaved" : "Тэг сохранен",
    "TagSavedtoIpod" : "Тэг сохранен на iPod",
    "TagSavedtoSystem" : "Тэг сохранен в системе",
    "MemoryFull" : "Память переполнена",
    "AllMemoryFull" : "Память переполнена",
    "TagMemoryFull" : "тэг-память переполнена",
    "TagAlreadySaved" : "Тэг уже сохранен",
    "IpodFull" : "Ошибка iPod",
    "TagTransferredtoiPod" : "Тэг передан на iPod",
    "UnplugAndReconnect" : "Откл и подкл снова",
    "TagNotYetProcessed" : "Тэг еще не обработан",
    "Remaining" : "Осталось {numberOfTags}",
    "IpodError" : "Выкрик",
    "ConnectIPod" : "подкл iPod, перед тэг",
    "TagsCannotBeSaved" : "Невозможно сохр. тэги",
    "AllTagsTransferred" : "Все тэги переданы",
    "FMRadio" : "FM радио",
    "Noresultsfound" : "Результаты не найдены",
    "UpdatingStationList" : "Обновление списка станций",
    "GenreSeek" : "Поиск по жанру",
    "ChangeGenre" : "Сменить жанр",
    "TAOff" : "TA Выкл.",
    "Remove" : "Удалить",
    "SignalLost" : "Сигнал потерян",
    "AlternativeFrequency" : "Другая частота",
    "Close" : "Закр.",
    "VrHelp_NowPlayingNA_Help_Left1" : "Развлечение",
    "VrHelp_NowPlayingNA_Help_Left2" : "Список станций",
    "VrHelp_NowPlayingNA_Help_Left3" : "Избранное",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD Вкл. / Выкл.",
    "VrHelp_NowPlayingNA_Help_Left5" : "Сканировать",
    "VrHelp_NowPlayingNA_Help_Right1" : "Громкость",
    "VrHelp_NowPlayingNA_Help_Right2" : "Тэгирование iTunes",
    "VrHelp_NowPlayingNA_Help_Right3" : "Искать предыдущий",
    "VrHelp_NowPlayingNA_Help_Right4" : "Искать следующий",
    "VrHelp_NowPlayingNA_Help_Right5" : "Авто-память",
    "VrHelp_NowPlayingEU_Help_Left1" : "Развлечение",
    "VrHelp_NowPlayingEU_Help_Left2" : "Список станций",
    "VrHelp_NowPlayingEU_Help_Left3" : "Избранное",
    "VrHelp_NowPlayingEU_Help_Left4" : "Сканировать",
    "VrHelp_NowPlayingEU_Help_Left5" : "Громкость",
    "VrHelp_NowPlayingEU_Help_Right1" : "Сигнал траффика",
    "VrHelp_NowPlayingEU_Help_Right2" : "Искать предыдущий",
    "VrHelp_NowPlayingEU_Help_Right3" : "Искать следующий",
    "VrHelp_NowPlayingEU_Help_Right4" : "Настройки FM",
    "VrHelp_NowPlayingEU_Help_Right5" : "Настройки звука",
    "VrHelp_NowPlayingOther_Help_Left1" : "Развлечение",
    "VrHelp_NowPlayingOther_Help_Left2" : "Авто-память",
    "VrHelp_NowPlayingOther_Help_Left3" : "Избранное",
    "VrHelp_NowPlayingOther_Help_Left4" : "Сканировать",
    "VrHelp_NowPlayingOther_Help_Left5" : "Громкость",
    "VrHelp_NowPlayingOther_Help_Right1" : "Искать предыдущий",
    "VrHelp_NowPlayingOther_Help_Right2" : "Искать следующий",
    "VrHelp_NowPlayingOther_Help_Right3" : "Настройки звука",
    "VrHelp_AutoMemory_Help1_Left1" : "(частота)",
    "VrHelp_AutoMemory_Help1_Left2" : "Обновить список",
    "VrHelp_AutoMemory_Help2_Left1" : "Обновить список",
    "VrHelp_Tune_NA_Help_Left1" : "(частота)",
    "VrHelp_Tune_NA_Help_Left2" : "Громкость выше",
    "VrHelp_Tune_NA_Help_Left3" : "Громкость ниже",
    "VrHelp_Tune_nonNA_Help_Left1" : "(частота)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Громкость выше",
    "VrHelp_Tune_nonNA_Help_Left3" : "Громкость ниже",
    "VrHelp_Settings_Help_Left1" : "Альтернативная частота Вкл.",
    "VrHelp_Settings_Help_Left2" : "Альтернативная частота Выкл.",
    "VrHelp_Settings_Help_Left3" : "Блокировка региона Вкл.",
    "VrHelp_Settings_Help_Left4" : "Блокировка региона Выкл.",
    "VrHelp_GenreSeek_Help_Left1" : "Поиск вверх",
    "VrHelp_GenreSeek_Help_Left2" : "Поиск вниз",
    "VrHelp_GenreSeek_Help_Left3" : "Изменить жанр",
    "TrafficAlertOn" : "Предупр-ния о возм. столкн-иях вкл.",
    "TrafficAlertOff" : "Предупр-ния о возм. cтолкн-иях выкл.",
    "TagCaptured" : "Тэг получен",
    "GenreName" : "Жанр: {genreName}",
    "favorites_Tooltip" : "Избранное",
    "hdChannels_Tooltip" : "HD каналы",
    "rbds_Weather" : "Погода",
    "rbds_Talk" : "Ток",
    "rbds_Class" : "Kлассический Рок",
    "rbds_Adult" : "Хиты для взрослых",
    "rbds_SoftRock" : "Легкий рок",
    "rbds_Top40" : "Топ 40",
    "rbds_Soft" : "Легкий",
    "rbds_Nostalgia" : "Hостальгия",
    "rbds_Jazz" : "Джаз",
    "rbds_Country" : "Кантри",
    "rbds_Classical" : "Kлассический",
    "rbds_Oldies" : "Ретро",
    "rbds_Rhythym" : "Ритм-энд-блюз",
    "rbds_SoftRB" : "легкий R&B",
    "rbds_Foreign" : "Иностранный язык",
    "rbds_ReligousM" : "Религиозная музыка",
    "rbds_ReligousT" : "Религиозные Беседы",
    "rbds_News" : "Новости",
    "rbds_Personality" : "личность",
    "rbds_Info" : "информация",
    "rbds_Sports" : "Спорт",
    "rbds_Public" : "общественность",
    "rbds_College" : "колледж",
    "rbds_Hablar" : "говорить по-испански",
    "rbds_Musica" : "испанская музыка",
    "rbds_HipHop" : "Хип-хоп",
    "rbds_EmergencyTest" : "Аварийные испытания",
    "rbds_Rock" : "Рок",
    "rbds_Emergency" : "Тревога! Тревога!",
    "rbds_genre_Weather" : "Жанр: Погода",
    "rbds_genre_Talk" : "Жанр: Ток",
    "rbds_genre_Class" : "Жанр: Kлассический Рок",
    "rbds_genre_Adult" : "Жанр: Хиты для взрослых",
    "rbds_genre_SoftRock" : "Жанр: Легкий рок",
    "rbds_genre_Top40" : "Жанр: Топ 40",
    "rbds_genre_Soft" : "Жанр: Легкий",
    "rbds_genre_Nostalgia" : "Жанр: Hостальгия",
    "rbds_genre_Jazz" : "Жанр: Джаз",
    "rbds_genre_Country" : "Жанр: Кантри",
    "rbds_genre_Classical" : "Жанр: Kлассический",
    "rbds_genre_Oldies" : "Жанр: Ретро",
    "rbds_genre_Rhythym" : "Жанр: Ритм-энд-блюз",
    "rbds_genre_SoftRB" : "Жанр: легкий R&B",
    "rbds_genre_Foreign" : "Жанр: Иностранный язык",
    "rbds_genre_ReligousM" : "Жанр: Религиозная музыка",
    "rbds_genre_ReligousT" : "Жанр: Религиозные Беседы",
    "rbds_genre_News" : "Жанр: Новости",
    "rbds_genre_Personality" : "Жанр: личность",
    "rbds_genre_Info" : "Жанр: информация",
    "rbds_genre_Sports" : "Жанр: Спорт",
    "rbds_genre_Public" : "Жанр: общественность",
    "rbds_genre_College" : "Жанр: колледж",
    "rbds_genre_Hablar" : "Жанр: говорить по-испански",
    "rbds_genre_Musica" : "Жанр: испанская музыка",
    "rbds_genre_HipHop" : "Жанр: Хип-хоп",
    "rbds_genre_EmergencyTest" : "Жанр: Аварийные испытания",
    "rbds_genre_Rock" : "Жанр: Рок",
    "rbds_genre_Emergency" : "Жанр: Тревога! Тревога!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Жанр: --",
};

framework.registerAppDictLoaded("fmradio", "ru_RU");