var Localization_fmradioAppDict_bg_BG = {
    //"stringId" : "localString"
    "UpdateStationList" : "Акт. спис. станции",
    "AutoMemoryList" : "Списък с авт. запаметени",
    "StationList" : "Списък със станции",
    "FMSettings" : "Настройки за FM",
    "HDRadio" : "Радио HD",
    "TrafficAlert" : "Предупр. движение",
    "RegionLock" : "Заключване по регион",
    "GenreList" : "Списък с жанрове",
    "HDStations" : "Станции HD",
    "AllStations" : "Всички станции",
    "News" : "Новини",
    "Affairs" : "Актуално",
    "Info" : "Информация ",
    "Sport" : "Спорт",
    "Education" : "Образование",
    "Drama" : "Драма",
    "Culture" : "Култура",
    "Science" : "Наука",
    "Varied" : "Разни",
    "Pop" : "Поп",
    "Rock" : "Рок",
    "Mor" : "Лека музика ",
    "Light" : "Светло",
    "Classics" : "Класика",
    "Other" : "Други",
    "Weather" : "Времето",
    "Finance" : "Финанси",
    "Childrens" : "Детски",
    "Religion" : "Религия",
    "Social" : "Социални",
    "PhoneIn" : "Обаждания на слушатели",
    "Travel" : "Туризъм",
    "Leisure" : "Отдих",
    "Jazz" : "Джаз",
    "Country" : "Страна",
    "National" : "Национални",
    "Oldies" : "Ретро",
    "Folk" : "Фолк",
    "Documentary" : "Документален",
    "AlarmTest" : "Тест на алармата",
    "Alarm" : "Аларма",
    "GenreAllStations" : "Жанр: всички станции",
    "GenreNews" : "Жанр: новини",
    "GenreAffairs" : "Жанр: актуално",
    "GenreInfo" : "Жанр: информация",
    "GenreSport" : "Жанр: спорт",
    "GenreEducation" : "Жанр: образование",
    "GenreDrama" : "Жанр: драма",
    "GenreCulture" : "Жанр: култура",
    "GenreScience" : "Жанр: наука",
    "GenreVaried" : "Жанр: разни",
    "GenrePop" : "Жанр: поп",
    "GenreRock" : "Жанр: рок",
    "GenreMor" : "Жанр: лека музика",
    "GenreLight" : "Жанр: лек",
    "GenreClassics" : "Жанр: класика",
    "GenreOther" : "Жанр: други",
    "GenreWeather" : "Жанр: времето",
    "GenreFinance" : "Жанр: финанси",
    "GenreChildrens" : "Жанр: детски",
    "GenreReligion" : "Жанр: религия",
    "GenrePhoneIn" : "Жанр: обаждания на слушатели",
    "GenreTravel" : "Жанр: туризъм",
    "GenreLeisure" : "Жанр: отдих",
    "GenreJazz" : "Жанр: джаз",
    "GenreCountry" : "Жанр: страна",
    "GenreNational" : "Жанр: национални",
    "GenreOldies" : "Жанр: ретро",
    "GenreFolk" : "Жанр: фолк",
    "GenreDocumentary" : "Жанр: документален",
    "GenreAlarmTest" : "Жанр: тест на алармата",
    "GenreAlarm" : "Жанр: аларма",
    "GenreSocial" : "Жанр: социални",
    "ErrorConnection" : "Грешка прехв. таг. в iPod",
    "CannotTransferTags" : "Таг-те не се прехв.",
    "TagSaved" : "Тагът е записан",
    "TagSavedtoIpod" : "Тагът е записан в iPod",
    "TagSavedtoSystem" : "Тагът е записан в сист.",
    "MemoryFull" : "Паметта е пълна",
    "AllMemoryFull" : "Цялата памет е пълна",
    "TagMemoryFull" : "Пълна памет за тагове",
    "TagAlreadySaved" : "Тагът е вече записан",
    "IpodFull" : "iPod е пълен",
    "TagTransferredtoiPod" : "Тагът прехв. в iPod",
    "UnplugAndReconnect" : "Изв. и свър. пак",
    "TagNotYetProcessed" : "Тагът не е обработен",
    "Remaining" : "Остават {numberOfTags}",
    "IpodError" : "Грешка в iPod",
    "ConnectIPod" : "Свър. iPod за прехв. таг.",
    "TagsCannotBeSaved" : "Таг-те не се записв.",
    "AllTagsTransferred" : "Вс. таг. са прехв.",
    "FMRadio" : "Радио FM",
    "Noresultsfound" : "Няма намерени резултати",
    "UpdatingStationList" : "Актуал. спис. станции",
    "GenreSeek" : "Търсене на жанр",
    "ChangeGenre" : "Промяна на жанра",
    "TAOff" : "Изкл. пр. дв.",
    "Remove" : "Изтриване",
    "SignalLost" : "Сигналът е изгубен",
    "AlternativeFrequency" : "Алтернативна честота",
    "Close" : "Затв.",
    "VrHelp_NowPlayingNA_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingNA_Help_Left2" : "Station List",
    "VrHelp_NowPlayingNA_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingNA_Help_Left4" : "HD On / Off",
    "VrHelp_NowPlayingNA_Help_Left5" : "Scan",
    "VrHelp_NowPlayingNA_Help_Right1" : "Tune",
    "VrHelp_NowPlayingNA_Help_Right2" : "iTunes Tagging",
    "VrHelp_NowPlayingNA_Help_Right3" : "Seek Previous",
    "VrHelp_NowPlayingNA_Help_Right4" : "Seek Next",
    "VrHelp_NowPlayingNA_Help_Right5" : "Auto Memory",
    "VrHelp_NowPlayingEU_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingEU_Help_Left2" : "Station List",
    "VrHelp_NowPlayingEU_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingEU_Help_Left4" : "Scan",
    "VrHelp_NowPlayingEU_Help_Left5" : "Tune",
    "VrHelp_NowPlayingEU_Help_Right1" : "Traffic Alert",
    "VrHelp_NowPlayingEU_Help_Right2" : "Seek Previous",
    "VrHelp_NowPlayingEU_Help_Right3" : "Seek Next",
    "VrHelp_NowPlayingEU_Help_Right4" : "FM Settings",
    "VrHelp_NowPlayingEU_Help_Right5" : "Sound Settings",
    "VrHelp_NowPlayingOther_Help_Left1" : "Entertainment",
    "VrHelp_NowPlayingOther_Help_Left2" : "Auto Memory",
    "VrHelp_NowPlayingOther_Help_Left3" : "Favorite",
    "VrHelp_NowPlayingOther_Help_Left4" : "Scan",
    "VrHelp_NowPlayingOther_Help_Left5" : "Tune",
    "VrHelp_NowPlayingOther_Help_Right1" : "Seek Previous",
    "VrHelp_NowPlayingOther_Help_Right2" : "Seek Next",
    "VrHelp_NowPlayingOther_Help_Right3" : "Sound Settings",
    "VrHelp_AutoMemory_Help1_Left1" : "(frequency)",
    "VrHelp_AutoMemory_Help1_Left2" : "Update List",
    "VrHelp_AutoMemory_Help2_Left1" : "Update List",
    "VrHelp_Tune_NA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_NA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_NA_Help_Left3" : "Tune Down",
    "VrHelp_Tune_nonNA_Help_Left1" : "(frequency)",
    "VrHelp_Tune_nonNA_Help_Left2" : "Tune Up",
    "VrHelp_Tune_nonNA_Help_Left3" : "Tune Down",
    "VrHelp_Settings_Help_Left1" : "Alternative Frequency On",
    "VrHelp_Settings_Help_Left2" : "Alternative Frequency Off",
    "VrHelp_Settings_Help_Left3" : "Region Lock On",
    "VrHelp_Settings_Help_Left4" : "Region Lock Off",
    "VrHelp_GenreSeek_Help_Left1" : "Seek Up",
    "VrHelp_GenreSeek_Help_Left2" : "Seek Down",
    "VrHelp_GenreSeek_Help_Left3" : "Change Genre",
    "TrafficAlertOn" : "Включено предупреждение за движението",
    "TrafficAlertOff" : "Изключено предупреждение за движението",
    "TagCaptured" : "Тагът е снет",
    "GenreName" : "Жанр: {genreName}",
    "favorites_Tooltip" : "Предпочитани",
    "hdChannels_Tooltip" : "Канали HD",
    "rbds_Weather" : "Времето",
    "rbds_Talk" : "Ток",
    "rbds_Class" : "Класически рок",
    "rbds_Adult" : "Смесени хитове",
    "rbds_SoftRock" : "Софт рок",
    "rbds_Top40" : "Топ 40",
    "rbds_Soft" : "Софт",
    "rbds_Nostalgia" : "Носталгия",
    "rbds_Jazz" : "Джаз",
    "rbds_Country" : "Страна",
    "rbds_Classical" : "Класическа музика",
    "rbds_Oldies" : "Ретро",
    "rbds_Rhythym" : "Ритъм и блус",
    "rbds_SoftRB" : "Софт ритъм и блус",
    "rbds_Foreign" : "Чужд език",
    "rbds_ReligousM" : "Религиозна музика",
    "rbds_ReligousT" : "Религиозни разговори",
    "rbds_News" : "Новини",
    "rbds_Personality" : "Личност",
    "rbds_Info" : "Информация",
    "rbds_Sports" : "Спорт",
    "rbds_Public" : "Обществено",
    "rbds_College" : "Kолеж",
    "rbds_Hablar" : "Говорейки испански",
    "rbds_Musica" : "Испански музика",
    "rbds_HipHop" : "Хип хоп",
    "rbds_EmergencyTest" : "Авариeн тест",
    "rbds_Rock" : "Рок",
    "rbds_Emergency" : "Предупреждение! Предупреждение!",
    "rbds_genre_Weather" : "Жанр: Времето",
    "rbds_genre_Talk" : "Жанр: Ток",
    "rbds_genre_Class" : "Жанр: Класически рок",
    "rbds_genre_Adult" : "Жанр: Смесени хитове",
    "rbds_genre_SoftRock" : "Жанр: Софт рок",
    "rbds_genre_Top40" : "Жанр: Топ 40",
    "rbds_genre_Soft" : "Жанр: Софт",
    "rbds_genre_Nostalgia" : "Жанр: Носталгия",
    "rbds_genre_Jazz" : "Жанр: Джаз",
    "rbds_genre_Country" : "Жанр: Страна",
    "rbds_genre_Classical" : "Жанр: Класическа музика",
    "rbds_genre_Oldies" : "Жанр: Ретро",
    "rbds_genre_Rhythym" : "Жанр: Ритъм и блус",
    "rbds_genre_SoftRB" : "Жанр: Софт ритъм и блус",
    "rbds_genre_Foreign" : "Жанр: Чужд език",
    "rbds_genre_ReligousM" : "Жанр: Религиозна музика",
    "rbds_genre_ReligousT" : "Жанр: Религиозни разговори",
    "rbds_genre_News" : "Жанр: Новини",
    "rbds_genre_Personality" : "Жанр: Личност",
    "rbds_genre_Info" : "Жанр: Информация",
    "rbds_genre_Sports" : "Жанр: Спорт",
    "rbds_genre_Public" : "Жанр: Обществено",
    "rbds_genre_College" : "Жанр: Kолеж",
    "rbds_genre_Hablar" : "Жанр: Говорейки испански",
    "rbds_genre_Musica" : "Жанр: Испански музика",
    "rbds_genre_HipHop" : "Жанр: Хип хоп",
    "rbds_genre_EmergencyTest" : "Жанр: Авариeн тест",
    "rbds_genre_Rock" : "Жанр: Рок",
    "rbds_genre_Emergency" : "Жанр: Предупр.! Предупр.!",
    "rbds_None" : "--",
    "rbds_genre_None" : "Жанр: --",
};

framework.registerAppDictLoaded("fmradio", "bg_BG");