var Localization_systemAppDict_zh_TW = {
	//"stringId" : "localString"
	"ActiveCallItem": "正在通話",
	"AhaMaintError": "aha 維護錯誤",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "應用程式",
	"AudioSourceNotAvailableBTAudio": "Bluetooth音頻不可用",
	"AudioSourceNotAvailableCD": "CD已取出",
	"AudioSourceNotAvailableDVD": "DVD已取出",
	"AudioSourceNotAvailableTV": "電視不可用",
	"AudioSourceNotAvailableUSB": "USB裝置已變更",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "通話記錄",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "頻道停止廣播",
	"ChannelUnauth": "頻道未授權",
	"CheckAntenna": "檢查天線",
	"CheckTuner": "檢查調諧器",
	"Communication": "通訊",
	"Connect": "連接",
	"Contacts": "聯繫人",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "致電",
	"DisclaimerText": "注意力分散可能導致事故。請勿在駕駛時操作。始終專心駕駛並遵守交通法規。參閱所有者手冊。",
	"DisconnectThenReconnect": "啟動Siri時出現錯誤。斷開然後重新連接 Apple Device",
	"DriveRecord": "駕駛記錄",
	"DriverIDItem": "駕駛員識別",
	"EcoenergyApp": "燃油經濟性 [監視器]",
	"EcoenergyAppHEV": "駕駛顯示器",
	"Email": "電子郵件",
	"Entertainment": "娛樂",
	"ErrorWhileStartingSiri": "啟動Siri時出現錯誤。",
	"FailedNotificationRetrieval": "無法擷取通知清單。",
	"FavoritesItem": "收藏夾",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™交通圖",
	"InitiateSiri": "長按講話按鈕以便啟動Siri會話",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "導航",
	"NoConnectionNotifyText": "現在是否要連接電話？",
	"NoConnectionNotifyTitle": "未連接電話",
	"NoDeviceText": "現在是否要連接裝置？",
	"NoDeviceTitle": "未連接裝置",
	"Notifications": "通知",
	"NotifyIgnore": "略過",
	"NotifyIncomingMsg": "呼入訊息來自：",
	"NotifyOff": "通知關閉",
	"NotifyRead": "閱讀",
	"NotifyReadNow": "是否要現在閱讀它？",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "正在重新連接aha收音機的BT音頻",
	"ReconnectBTAudio": "正在重新連接BT音頻，以繼續播放",
	"ReconnectCD": "正在驗證 CD，以便繼續播放",
	"ReconnectDVD": "正在驗證 DVD，以便繼續播放",
	"ReconnectEntMenuButton": "娛樂選單",
	"ReconnectFailedBTAudio": "無法重新連接Bluetooth音頻",
	"ReconnectFailedCD": "CD已取出。無法繼續播放。",
	"ReconnectFailedDVD": "DVD已取出。無法繼續播放。",
	"ReconnectFailedTV": "電視不可用。無法繼續播放。",
	"ReconnectFailedUSB": "USB裝置已變更。無法繼續播放。",
	"ReconnectPandora": "正在重新連接Pandora的Bluetooth音頻",
	"ReconnectStitcher": "正在重新連接Stitcher的Bluetooth音頻",
	"ReconnectTV": "檢驗電視以便繼續播放",
	"ReconnectUSB": "正在重新連接 USB 裝置，以繼續播放",
	"RetryLabel": "重試",
	"SchedMaintenanceApp": "維護",
	"ScreenReplication": "屏幕複製",
	"SdarsRadio": "XM",
	"Settings": "設置",
	"SettingsCommunication": "設置",
	"Siri": "Siri",
	"SiriDisabled": "Siri is Disabled on Apple Device.",
	"Sms": "短信",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "溫度警告",
	"TempWarningText": "顯示幕太熱。在冷卻前，螢幕效能可能降低。",
	"TextDownloaded": "已下載文字",
	"TextSent": "已傳送文字",
	"TrafficAlertsItem": "交通資訊",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "車輛資料傳輸",
	"VehicleTelemetryTransfer": "車子遙感傳輸",
	"VideoSignalLost": "視訊訊號遺失",
	"VoiceNotSupported": "不支持語音。",
	"VoiceRecognition": "語音識別",
	"VrHelp_HomeScreen_Help_Left1": "娛樂",
	"VrHelp_HomeScreen_Help_Left2": "通訊",
	"VrHelp_HomeScreen_Help_Left3": "導航",
	"VrHelp_HomeScreen_Help_Left4": "設置",
	"VrHelp_HomeScreen_Help_Left5": "應用程序",
	"VrHelp_HomeScreen_Help_Right1": "收藏夾",
	"WarnGuidanceApp": "警告指導",
	"WarningTitle": "警告！",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "我同意",
};

framework.registerAppDictLoaded("system", "zh_TW");