var Localization_systemAppDict_bg_BG = {
	//"stringId" : "localString"
	"ActiveCallItem": "Активно повикване",
	"AhaMaintError": "Грешка в поддръжката на aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Приложения",
	"AudioSourceNotAvailableBTAudio": "Bluetooth аудио не е достъпно",
	"AudioSourceNotAvailableCD": "CD е изваден",
	"AudioSourceNotAvailableDVD": "DVD е изваден",
	"AudioSourceNotAvailableTV": "TV не е налично",
	"AudioSourceNotAvailableUSB": "USB устройството е променено",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Повиквания",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Каналът не предава",
	"ChannelUnauth": "Каналът не е разрешен",
	"CheckAntenna": "Проверете антената",
	"CheckTuner": "Проверете тунера",
	"Communication": "Комуникация",
	"Connect": "Свързване",
	"Contacts": "Контакти",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Набиране на телефон",
	"DisclaimerText": "Разсейването води до злополуки. Не работете, докато шофирате. Съсредоточавайте се върху шофирането и спазвайте правилника. Вижте Ръководството.",
	"DisconnectThenReconnect": "Грешка при стартиране на Siri. Прекъснете и свържете Apple Device.",
	"DriveRecord": "Запис за шофиране",
	"DriverIDItem": "Избор на водача",
	"EcoenergyApp": "Pазхода на гориво",
	"EcoenergyAppHEV": "Следене на курса",
	"Email": "Email",
	"Entertainment": "Развлечения",
	"ErrorWhileStartingSiri": "Грешка при стартиране на Siri.",
	"FailedNotificationRetrieval": "Списъкът с известия не може да се изтегли",
	"FavoritesItem": "Предпочитани",
	"FmRadio": "FM",
	"HDTrafficItem": "Радио HD™ – карта на движението",
	"InitiateSiri": "Натиснете и задръжте бутона за говор, за да стартирате Siri сесията",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Навигация",
	"NoConnectionNotifyText": "Искате ли да свържете телефон сега?",
	"NoConnectionNotifyTitle": "Няма свързан телефон",
	"NoDeviceText": "Искате ли да свържете устройство сега?",
	"NoDeviceTitle": "Няма свързано устройство",
	"Notifications": "Известия",
	"NotifyIgnore": "Игнориране",
	"NotifyIncomingMsg": "Входящо съобщение от:",
	"NotifyOff": "Без извест.",
	"NotifyRead": "Четене",
	"NotifyReadNow": "Искате ли да го прочетете сега?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Свързване на Bluetooth за радио aha",
	"ReconnectBTAudio": "Свързване на Bluetooth за продължа.",
	"ReconnectCD": "Проверка на CD за продължаване",
	"ReconnectDVD": "Проверка на DVD за продължаване",
	"ReconnectEntMenuButton": "Меню „Развлечения“",
	"ReconnectFailedBTAudio": "Звуково устройство с Bluetooth не може да се свърже повторно",
	"ReconnectFailedCD": "CD е изваден. Възпроизвеждането не може да продължи.",
	"ReconnectFailedDVD": "DVD е изваден. Възпроизвеждането не може да продължи.",
	"ReconnectFailedTV": "TV не е налично. Не можете да възобновите възпроизвеждането.",
	"ReconnectFailedUSB": "USB устройството е променено. Възпроизвеждането не може да продължи.",
	"ReconnectPandora": "Свързване на Bluetooth за Pandora",
	"ReconnectStitcher": "Свързване на Bluetooth за Stitcher",
	"ReconnectTV": "Проверка на TV, за да възобновите възпроизвеждането",
	"ReconnectUSB": "Свързване на USB за продължаване",
	"RetryLabel": "Повторен опит",
	"SchedMaintenanceApp": "Поддръжка",
	"ScreenReplication": "Копие на екрана",
	"SdarsRadio": "XM",
	"Settings": "Настройки",
	"SettingsCommunication": "Настройки",
	"Siri": "Siri",
	"SiriDisabled": "Siri is Disabled on Apple Device.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Предупреждение температура",
	"TempWarningText": "Дисплеят е много горещ. Работата на екрана може да бъде влошена, докато не изстине.",
	"TextDownloaded": "Текстът е изтеглен",
	"TextSent": "SMS е изпратен",
	"TrafficAlertsItem": "Информация за движението",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 – {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 – {deviceName}",
	"VehicleDataTransferItem": "Предаване на данни в автом.",
	"VehicleTelemetryTransfer": "TTA",
	"VideoSignalLost": "Изгубен видеосигнал",
	"VoiceNotSupported": "Voice not supported. ",
	"VoiceRecognition": "Разпознаване на глас",
	"VrHelp_HomeScreen_Help_Left1": "Entertainment",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Settings",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favorites",
	"WarnGuidanceApp": "Предупр. указ.",
	"WarningTitle": "ПРЕДУПРЕЖДЕНИЕ!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Съгласен съм",
};

framework.registerAppDictLoaded("system", "bg_BG");