var Localization_systemAppDict_it_IT = {
	//"stringId" : "localString"
	"ActiveCallItem": "Chiamata attiva",
	"AhaMaintError": "Errore manutenzione aha.",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Applicazioni",
	"AudioSourceNotAvailableBTAudio": "Audio Bluetooth non disponibile.",
	"AudioSourceNotAvailableCD": "Il CD è stato estratto. ",
	"AudioSourceNotAvailableDVD": "Il DVD è stato estratto. ",
	"AudioSourceNotAvailableTV": "TV Non Disponibile",
	"AudioSourceNotAvailableUSB": "Il dispositivo USB è cambiato",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Registro chiamate",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Canale chiuso",
	"ChannelUnauth": "Canale non autorizzato",
	"CheckAntenna": "Controlla antenna",
	"CheckTuner": "Controlla Tuner ",
	"Communication": "Comunicazione",
	"Connect": "Connetti",
	"Contacts": "Contatti",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Telefono con tastiera",
	"DisclaimerText": "La distrazione può causare incidenti. Non fare niente mentre si guida. Rimanere concentrati sulla guida e rispettare le norme stradali. Leggere il manuale di istruzioni.",
	"DisconnectThenReconnect": "Disconnettere quindi riconnettere Apple Device",
	"DriveRecord": "Archivio di guida",
	"DriverIDItem": "Selezione conducente",
	"EcoenergyApp": "Consumo carburante",
	"EcoenergyAppHEV": "Monitor di guida",
	"Email": "Email",
	"Entertainment": "Intrattenimento",
	"ErrorWhileStartingSiri": "Errore durante l'avvio di Siri.",
	"FailedNotificationRetrieval": "Impossibile recuperare l'elenco notifiche.",
	"FavoritesItem": "Preferiti",
	"FmRadio": "FM",
	"HDTrafficItem": "Informazioni sul traffico Radio HD",
	"InitiateSiri": "Premere a lungo il pulsante conversazione per avviare la sessione di Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigazione",
	"NoConnectionNotifyText": "Connettere un telefono ora?",
	"NoConnectionNotifyTitle": "Nessun telefono connesso.",
	"NoDeviceText": "Connettere il dispositivo ora?",
	"NoDeviceTitle": "Nessun dispositivo connesso.",
	"Notifications": "Notifiche",
	"NotifyIgnore": "Ignora",
	"NotifyIncomingMsg": "Messaggio in arrivo da:",
	"NotifyOff": "Notifiche off",
	"NotifyRead": "Leggi",
	"NotifyReadNow": "Leggere ora?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Riconnes audio Bluetooth per Radio aha",
	"ReconnectBTAudio": "Riconnes audio Bluetooth per riprod",
	"ReconnectCD": "Verifica Cd per ripristino riproduzione",
	"ReconnectDVD": "Verifica DVD per ripristino riproduzione",
	"ReconnectEntMenuButton": "Menu intrattenimento",
	"ReconnectFailedBTAudio": "Impossibile connettere di nuovo l'audio Bluetooth.",
	"ReconnectFailedCD": "Il cd è stato estratto. Impossibile ripristinare la riproduzione.",
	"ReconnectFailedDVD": "Il DVD è stato estratto. Impossibile ripristinare la riproduzione.",
	"ReconnectFailedTV": "TV Non Disponibile. Non in grado di riprendere la riproduzione.",
	"ReconnectFailedUSB": "Il dispositivo USB è cambiato. Impossibile ripristinare la riproduzione.",
	"ReconnectPandora": "Riconnes audio Bluetooth per Pandora",
	"ReconnectStitcher": "Riconnes audio Bluetooth per Stitcher",
	"ReconnectTV": "Verifica TV per riprendere la riproduzione",
	"ReconnectUSB": "Riconnes dispositivo USB per riproduzione",
	"RetryLabel": "Riprova",
	"SchedMaintenanceApp": "Manutenzione",
	"ScreenReplication": "Replica schermata",
	"SdarsRadio": "XM",
	"Settings": "Impostazioni",
	"SettingsCommunication": "Impostazioni",
	"Siri": "Siri",
	"SiriDisabled": "Siri è disabilitato sul disp. Apple.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Avviso temperatura",
	"TempWarningText": "Surriscaldamento display. La prestazione dello schermo potrebbe diminuire fin quando non si raffredda.",
	"TextDownloaded": "SMS scaricato",
	"TextSent": "SMS inviato",
	"TrafficAlertsItem": "Informazioni sul traffico",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Trasferimento dati veicolo",
	"VehicleTelemetryTransfer": "Trasferimento telemetria del veicolo",
	"VideoSignalLost": "Segnale video perso",
	"VoiceNotSupported": "Voce non supportata.",
	"VoiceRecognition": "Riconoscimento vocale",
	"VrHelp_HomeScreen_Help_Left1": "Intrattenimento",
	"VrHelp_HomeScreen_Help_Left2": "Comunicazione",
	"VrHelp_HomeScreen_Help_Left3": "Navigazione",
	"VrHelp_HomeScreen_Help_Left4": "Impostazioni",
	"VrHelp_HomeScreen_Help_Left5": "Applicazioni",
	"VrHelp_HomeScreen_Help_Right1": "Preferiti",
	"WarnGuidanceApp": "Avvisi di guida",
	"WarningTitle": "ATTENZIONE!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Accetto",
};

framework.registerAppDictLoaded("system", "it_IT");