var Localization_systemAppDict_de_DE = {
	//"stringId" : "localString"
	"ActiveCallItem": "Aktiver Anruf",
	"AhaMaintError": "aha-Wartungsfehler",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Anwendungen",
	"AudioSourceNotAvailableBTAudio": "Bluetooth-Audio nicht verfügbar",
	"AudioSourceNotAvailableCD": "CD wurde entfernt",
	"AudioSourceNotAvailableDVD": "DVD wurde entfernt",
	"AudioSourceNotAvailableTV": "TV nicht verfügbar",
	"AudioSourceNotAvailableUSB": "USB-Gerät wurde gewechselt. ",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Anrufhistorie",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Sender sendet nicht",
	"ChannelUnauth": "Unerlaubter Sender",
	"CheckAntenna": "Antenne überprüfen",
	"CheckTuner": "Tuner überprüfen",
	"Communication": "Kommunikation",
	"Connect": "Verbinden",
	"Contacts": "Kontakte",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Wählen",
	"DisclaimerText": "Ablenkung kann Unfälle verursachen. Nicht während der Fahrt benutzen. Immer auf das Fahren konzentrieren und die Verkehrsregeln beachten. Siehe Bedienungsanleitung.",
	"DisconnectThenReconnect": "Fehler während Siri Start. Apple Device trennen und erneut verbinden.",
	"DriveRecord": "Fahreintrag",
	"DriverIDItem": "Auswahl Fahrer",
	"EcoenergyApp": "Verbrauchsanzeige",
	"EcoenergyAppHEV": "Fahranzeige",
	"Email": "Email",
	"Entertainment": "Unterhaltung",
	"ErrorWhileStartingSiri": "Fehler während Siri Start.",
	"FailedNotificationRetrieval": "Meldungsliste kann nicht geladen werden",
	"FavoritesItem": "Favoriten",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ Verkehrskarte",
	"InitiateSiri": "Sprechtaste länger drücken, um  die Siri Sitzung zu starten",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigation",
	"NoConnectionNotifyText": "Möchten Sie jetzt ein Telefon verbinden?",
	"NoConnectionNotifyTitle": "Kein Telefon angeschlossen",
	"NoDeviceText": "Möchten Sie jetzt ein Gerät verbinden?",
	"NoDeviceTitle": "Kein Gerät verbunden",
	"Notifications": "Benachrichtigungen",
	"NotifyIgnore": "Ignorieren",
	"NotifyIncomingMsg": "Eingehende Nachricht von:",
	"NotifyOff": "Benachr. aus",
	"NotifyRead": "Lesen",
	"NotifyReadNow": "Möchten Sie es nun lesen?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Ern. Bluetooth Audioverb. für aha Radio",
	"ReconnectBTAudio": "Ern. Bluetooth Audioverb. z. WdgForts. ",
	"ReconnectCD": "Überprüfe CD, um Wiedergabe fortzus.",
	"ReconnectDVD": "Überprüfe DVD, um Wiedergabe fortzus.",
	"ReconnectEntMenuButton": "Unterhaltungsmenü",
	"ReconnectFailedBTAudio": "Kann Bluetooth-Audio Verbindung nicht wiederherstellen",
	"ReconnectFailedCD": "CD wurde entfernt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectFailedDVD": "DVD wurde entfernt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectFailedTV": "TV nicht verfügbar. Wiedergabe kann nicht fortgesetzt werden.",
	"ReconnectFailedUSB": "USB-Gerät wurde gewechselt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectPandora": "Ern. Bluetooth Audioverb. für Pandora",
	"ReconnectStitcher": "Ern. Bluetooth Audioverb. für Stitcher",
	"ReconnectTV": "Prüfe TV zum Fortsetzen der Wiedergabe",
	"ReconnectUSB": "Ern. USB-Geräteverb. für Wiedergabe",
	"RetryLabel": "Erneut versuchen",
	"SchedMaintenanceApp": "Wartung",
	"ScreenReplication": "Überprüfe Wiederholung",
	"SdarsRadio": "XM",
	"Settings": "Einstellungen",
	"SettingsCommunication": "Einstellungen",
	"Siri": "Siri",
	"SiriDisabled": "Siri ist deaktiviert auf Apple Device",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Temperaturwarnung",
	"TempWarningText": "Anzeige ist zu heiss. Bildschirmdarstellung kann verringert sein, bis er abkühlt",
	"TextDownloaded": "SMS heruntergeladen",
	"TextSent": "SMS gesendet",
	"TrafficAlertsItem": "Verkehrsinformation",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Fahrzeugdaten-Übermittlung",
	"VehicleTelemetryTransfer": "Fahrzeugtelemetrie-Übertragung",
	"VideoSignalLost": "Videosignal verloren",
	"VoiceNotSupported": "Stimme nicht unterstützt",
	"VoiceRecognition": "Spracherkennung",
	"VrHelp_HomeScreen_Help_Left1": "Unterhaltung",
	"VrHelp_HomeScreen_Help_Left2": "Kommunikation",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Einstellungen",
	"VrHelp_HomeScreen_Help_Left5": "Anwendungen",
	"VrHelp_HomeScreen_Help_Right1": "Favoriten",
	"WarnGuidanceApp": "Warnmeldungen",
	"WarningTitle": "Achtung!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Ich stimme zu",
};

framework.registerAppDictLoaded("system", "de_DE");