var Localization_systemAppDict_ms_MY = {
	//"stringId" : "localString"
	"ActiveCallItem": "Panggilan Aktif",
	"AhaMaintError": "Ralat Penyelenggaraan aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Aplikasi",
	"AudioSourceNotAvailableBTAudio": "Audio Bluetooth Tidak Tersedia",
	"AudioSourceNotAvailableCD": "CD telah dikeluarkan",
	"AudioSourceNotAvailableDVD": "DVD telah dikeluarkan",
	"AudioSourceNotAvailableTV": "TV tidak tersedia.",
	"AudioSourceNotAvailableUSB": "Peranti USB telah berubah",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName} ",
	"CallHistory": "Rekod Panggilan",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Saluran Tidak Bersiaran",
	"ChannelUnauth": "Saluran Tidak Dibenarkan",
	"CheckAntenna": "Periksa Antena",
	"CheckTuner": "Periksa Penala",
	"Communication": "Komunikasi",
	"Connect": "Sambung",
	"Contacts": "Kenalan",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Dail",
	"DisclaimerText": "Gangguan boleh mengakibatkan kemalangan. Jangan kendalikan semasa memandu. Sentiasa berikan tumpuan kepada pemanduan dan patuhi peraturan lalu lintas. Lihat Panduan Pemilik.",
	"DisconnectThenReconnect": "Ralat Bermula Siri. Putuskan smbgn kemudian smbg semula Apple Device.",
	"DriveRecord": "Rekod Pemanduan",
	"DriverIDItem": "Pilihan Pemandu",
	"EcoenergyApp": "Ekonomi bahan api",
	"EcoenergyAppHEV": "Monitor Memandu",
	"Email": "E-mel",
	"Entertainment": "Hiburan",
	"ErrorWhileStartingSiri": "Ralat ketika memulakan Siri.",
	"FailedNotificationRetrieval": "Tidak dapat mengambil semula Senarai Pemberitahuan",
	"FavoritesItem": "Kegemaran",
	"FmRadio": "FM",
	"HDTrafficItem": "Peta Trafik HD Radio™",
	"InitiateSiri": "Tekan lama Butang Cakap untuk memulakan sesi Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigasi",
	"NoConnectionNotifyText": "Adakah anda ingin menyambungkan telefon sekarang?",
	"NoConnectionNotifyTitle": "Tiada Telefon Disambungkan",
	"NoDeviceText": "Adakah anda ingin menyambungkan peranti sekarang?",
	"NoDeviceTitle": "Tiada Peranti Disambungkan",
	"Notifications": "Pemberitahuan",
	"NotifyIgnore": "Abaikan",
	"NotifyIncomingMsg": "Mesej Masuk daripada:",
	"NotifyOff": "Mencetuskan",
	"NotifyRead": "Baca",
	"NotifyReadNow": "Adakah anda mahu membaca skrg?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Sambung semula audio BT utk aha Radio",
	"ReconnectBTAudio": "Samb sem. audio BT utk terus bermain",
	"ReconnectCD": "Sahkan CD utk main semula",
	"ReconnectDVD": "Sahkan DVD utk main semula",
	"ReconnectEntMenuButton": "Menu Hiburan",
	"ReconnectFailedBTAudio": "Audio Bluetooth gagal disambung.",
	"ReconnectFailedCD": "CD telah dikeluarkan. Tidak dapat menyambung semula rakaman.",
	"ReconnectFailedDVD": "DVD telah dikeluarkan. Tidak dapat menyambung semula rakaman.",
	"ReconnectFailedTV": "TV tidak tersedia. Tidak dapat main semula.",
	"ReconnectFailedUSB": "Peranti USB telah berubah. Tidak dapat menyambung semula rakaman.",
	"ReconnectPandora": "Sambung semula audio BT utk Pandora",
	"ReconnectStitcher": "Sambung semula audio BT utk Stitcher",
	"ReconnectTV": "Mengesahkan TV untuk menyambung main semula.",
	"ReconnectUSB": "Peranti USB disambungkan",
	"RetryLabel": "Cuba Semula",
	"SchedMaintenanceApp": "Penyelenggaraan",
	"ScreenReplication": "Replikasi Skrin",
	"SdarsRadio": "XM",
	"Settings": "Tetapan",
	"SettingsCommunication": "Tetapan",
	"Siri": "Siri",
	"SiriDisabled": "Siri is Disabled on Apple Device.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Amaran Suhu",
	"TempWarningText": "Paparan terlalu panas. Prestasi skrin mungkin turun sehingga skrin sejuk.",
	"TextDownloaded": "SMS Dimuat Turun",
	"TextSent": "SMS Dihantar",
	"TrafficAlertsItem": "Maklumat Lalu Lintas",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Pindah Maklumat",
	"VehicleTelemetryTransfer": "Pindah Maklumat",
	"VideoSignalLost": "Isyarat Video Tiada",
	"VoiceNotSupported": "Suara tidak disokong.",
	"VoiceRecognition": "Pengecaman Suara",
	"VrHelp_HomeScreen_Help_Left1": "Entertainment",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Settings",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favorites",
	"WarnGuidanceApp": "Panduan Amaran",
	"WarningTitle": "AMARAN!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Saya Setuju",
};

framework.registerAppDictLoaded("system", "ms_MY");