var Localization_systemAppDict_ro_RO = {
	//"stringId" : "localString"
	"ActiveCallItem": "Apel activ",
	"AhaMaintError": "Eroare întreţinere aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Aplicaţii",
	"AudioSourceNotAvailableBTAudio": "Audio Bluetooth indisponibil",
	"AudioSourceNotAvailableCD": "S-a scos CD-ul",
	"AudioSourceNotAvailableDVD": "S-a scos DVD-ul",
	"AudioSourceNotAvailableTV": "TN indisponibil",
	"AudioSourceNotAvailableUSB": "Dispozitivul USB s-a modificat",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Istoric apeluri",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Canal dezactivat",
	"ChannelUnauth": "Canal neautorizat",
	"CheckAntenna": "Verificare antenă",
	"CheckTuner": "Verificare tuner",
	"Communication": "Comunicare",
	"Connect": "Conectare",
	"Contacts": "Contacte",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Apelare telefon",
	"DisclaimerText": "Neatenţia poate provoca accidente. Nu folosiţi în timpul condusului. Concentraţi-vă mereu la volan şi respectaţi regulile de circulaţie. Consultaţi manualul de utilizare.",
	"DisconnectThenReconnect": "Eroare pornire Siri. Deconectaţi şi reconectaţi Apple Device",
	"DriveRecord": "Înregist. privind cond.",
	"DriverIDItem": "Identificare şofer",
	"EcoenergyApp": "Economie Combustibil",
	"EcoenergyAppHEV": "Monitor conducere",
	"Email": "Email",
	"Entertainment": "Divertisment",
	"ErrorWhileStartingSiri": "Eroare pornire Siri.",
	"FailedNotificationRetrieval": "Listă notificare nedescărcată",
	"FavoritesItem": "Favorite",
	"FmRadio": "FM",
	"HDTrafficItem": "Hartă rutier HD Radio™",
	"InitiateSiri": "Ţineţi apăsat pe butonul Vorbire pentru a porni sesiunea Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigaţie",
	"NoConnectionNotifyText": "Doriţi să conectaţi un telefon acum?",
	"NoConnectionNotifyTitle": "Nu este conectat niciun telefon",
	"NoDeviceText": "Doriţi să conectaţi un dispozitiv acum?",
	"NoDeviceTitle": "Niciun dispozitiv conectat",
	"Notifications": "Notificări",
	"NotifyIgnore": "Ignorare",
	"NotifyIncomingMsg": "Mesaj primit de la:",
	"NotifyOff": "Notif. Oprită",
	"NotifyRead": "Citire",
	"NotifyReadNow": "Doriţi să îl citiţi acum?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Reconect. Bluetooth audio pt. aha Radio",
	"ReconnectBTAudio": "Reconect. Bluetooth audio pt. rel. redare",
	"ReconnectCD": "Verificare CD pt. reluarea redării",
	"ReconnectDVD": "Verificare DVD pt. reluarea redării",
	"ReconnectEntMenuButton": "Meniu divertisment",
	"ReconnectFailedBTAudio": "Nu s-a putut reconecta audio prin Bluetooth",
	"ReconnectFailedCD": "S-a scos CD-ul. Nu se poate relua redarea.",
	"ReconnectFailedDVD": "S-a scos DVD-ul. Nu se poate relua redarea.",
	"ReconnectFailedTV": "TN indisponibil. Nu se poate relua redarea",
	"ReconnectFailedUSB": "Dispozitivul USB s-a modificat. Nu se poate relua redarea.",
	"ReconnectPandora": "Reconect. Bluetooth audio pt. Pandora",
	"ReconnectStitcher": "Reconect. Bluetooth audio pt. Stitcher",
	"ReconnectTV": "Verificaţi TV pentru a relua redarea",
	"ReconnectUSB": "Reconectare USB pentru reluarea redării",
	"RetryLabel": "Reîncercare",
	"SchedMaintenanceApp": "Întreţinere",
	"ScreenReplication": "Replicare Ecran",
	"SdarsRadio": "XM",
	"Settings": "Setări",
	"SettingsCommunication": "Setări",
	"Siri": "Siri",
	"SiriDisabled": "Siri este dezactivat pe dispozitivul Apple.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Avertisment temperatură",
	"TempWarningText": "Afişaj supraîncălzit. Performanţa ecranului poate fi redusă până când se răceşte.",
	"TextDownloaded": "SMS descărcat",
	"TextSent": "SMS trimis",
	"TrafficAlertsItem": "Informaţii trafic",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Transfer de date vehicul",
	"VehicleTelemetryTransfer": "TDTV",
	"VideoSignalLost": "Semnal video pierdut",
	"VoiceNotSupported": "Voce neacceptată",
	"VoiceRecognition": "Recunoaşterea vocii",
	"VrHelp_HomeScreen_Help_Left1": "Entertainment",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Settings",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favorites",
	"WarnGuidanceApp": "Avertisment ghidare",
	"WarningTitle": "ATENŢIE!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Sunt de acord",
};

framework.registerAppDictLoaded("system", "ro_RO");