var Localization_systemAppDict_mn_TW = {
	//"stringId" : "localString"
	"ActiveCallItem": "主動呼叫",
	"AhaMaintError": "aha 維修錯誤",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "應用程式",
	"AudioSourceNotAvailableBTAudio": "藍牙音訊無法使用",
	"AudioSourceNotAvailableCD": "CD已退片",
	"AudioSourceNotAvailableDVD": "DVD已退片",
	"AudioSourceNotAvailableTV": "TV 無法使用",
	"AudioSourceNotAvailableUSB": "已變更 USB 裝置",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "藍牙",
	"BluetoothWithDevice": "藍牙 - {deviceName}",
	"CallHistory": "通話歷史記錄",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "頻道已停播",
	"ChannelUnauth": "頻道未獲授權",
	"CheckAntenna": "請檢查天線",
	"CheckTuner": "請檢查調諧器",
	"Communication": "通訊",
	"Connect": "連接",
	"Contacts": "通訊錄",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "撥打電話",
	"DisclaimerText": "注意力分散可能導致事故。駕駛時請勿進行操作。請務必專心駕駛並遵守交通規則。 請參閱《車主手冊》。",
	"DisconnectThenReconnect": "開啟 Siri 時發生錯誤。 已中斷連接並重新連接 Apple Device。",
	"DriveRecord": "駕駛記錄",
	"DriverIDItem": "選擇駕駛人",
	"EcoenergyApp": "油耗顯示",
	"EcoenergyAppHEV": "駕駛狀況",
	"Email": "電子郵件",
	"Entertainment": "娛樂",
	"ErrorWhileStartingSiri": "開啟 Siri 時發生錯誤",
	"FailedNotificationRetrieval": "無法擷取通知清單",
	"FavoritesItem": "我的最愛",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ 路況顯示",
	"InitiateSiri": "長按通話按鍵以開啟 Siri 工作階段",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "導航",
	"NoConnectionNotifyText": "要現在連接電話嗎?",
	"NoConnectionNotifyTitle": "未連接電話",
	"NoDeviceText": "要現在連接裝置嗎?",
	"NoDeviceTitle": "未連接裝置",
	"Notifications": "通知",
	"NotifyIgnore": "忽略",
	"NotifyIncomingMsg": "來自      的訊息",
	"NotifyOff": "關閉通知",
	"NotifyRead": "讀取",
	"NotifyReadNow": "要現在閱讀嗎?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "正在連接藍牙音訊以用於 aha 廣播",
	"ReconnectBTAudio": "正在重新連接藍牙音訊以恢復",
	"ReconnectCD": "正在驗證 CD 以恢復播放",
	"ReconnectDVD": "正在驗證 DVD 以恢復播放",
	"ReconnectEntMenuButton": "娛樂清単",
	"ReconnectFailedBTAudio": "無法重新連接藍牙音訊",
	"ReconnectFailedCD": "CD已退片，無法繼續播放",
	"ReconnectFailedDVD": "DVD已退片，無法繼續播放",
	"ReconnectFailedTV": "TV 無法使用。 無法繼續播放。",
	"ReconnectFailedUSB": "已變更 USB 裝置。 無法繼續播放。",
	"ReconnectPandora": "正在連接藍牙音訊以用於 Pandora",
	"ReconnectStitcher": "正在連接藍牙音訊以用於 Stitcher",
	"ReconnectTV": "正在驗證 TV 以恢復播放",
	"ReconnectUSB": "正在重新連接 USB 裝置以恢復",
	"RetryLabel": "重試",
	"SchedMaintenanceApp": "維修保養",
	"ScreenReplication": "畫面複製",
	"SdarsRadio": "XM",
	"Settings": "設定",
	"SettingsCommunication": "設定",
	"Siri": "Siri",
	"SiriDisabled": "無法在 Apple Device 使用 Siri。",
	"Sms": "簡訊",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "溫度提示",
	"TempWarningText": "螢幕過熱\n若不關閉冷卻，螢幕顯示效能可能下降",
	"TextDownloaded": "已下載簡訊",
	"TextSent": "簡訊已傳送",
	"TrafficAlertsItem": "即時路況",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "車輛資訊傳輸",
	"VehicleTelemetryTransfer": "車子遙感傳輸",
	"VideoSignalLost": "視訊信號中斷",
	"VoiceNotSupported": "系統不支援此語音",
	"VoiceRecognition": "語音辨識",
	"VrHelp_HomeScreen_Help_Left1": "娛樂",
	"VrHelp_HomeScreen_Help_Left2": "通訊",
	"VrHelp_HomeScreen_Help_Left3": "導航",
	"VrHelp_HomeScreen_Help_Left4": "設置",
	"VrHelp_HomeScreen_Help_Left5": "應用程序",
	"VrHelp_HomeScreen_Help_Right1": "收藏夾",
	"WarnGuidanceApp": "警告提示",
	"WarningTitle": "警告!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "我同意",
};

framework.registerAppDictLoaded("system", "mn_TW");