var Localization_systemAppDict_en_US = {
	//"stringId" : "localString"
	"ActiveCallItem": "Active Call",
	"AhaMaintError": "aha Maintenance Error",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Applications",
	"AudioSourceNotAvailableBTAudio": "Bluetooth Audio Not Available",
	"AudioSourceNotAvailableCD": "CD was Removed",
	"AudioSourceNotAvailableDVD": "DVD Removed",
	"AudioSourceNotAvailableTV": "TV Not Available",
	"AudioSourceNotAvailableUSB": "USB Device Changed",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Call History",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Channel Off Air",
	"ChannelUnauth": "Channel Unauthorized",
	"CheckAntenna": "Check  Antenna",
	"CheckTuner": "Check Tuner",
	"Communication": "Communication",
	"Connect": "Connect",
	"Contacts": "Contacts",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Dial Phone",
	"DisclaimerText": "Distraction may cause accidents. Do not operate while driving. Always concentrate on driving and obey Traffic Regulations. See Owner's Manual.",
	"DisconnectThenReconnect": "Error While Starting Siri. Disconnect then Reconnect Apple Device.",
	"DriveRecord": "Drive Record",
	"DriverIDItem": "Driver Selection",
	"EcoenergyApp": "Fuel Economy Monitor",
	"EcoenergyAppHEV": "Drive Monitor",
	"Email": "Email",
	"Entertainment": "Entertainment",
	"ErrorWhileStartingSiri": "Error While Starting Siri",
	"FailedNotificationRetrieval": "Unable to Retrieve Notification List",
	"FavoritesItem": "Favorites",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ Traffic Map",
	"InitiateSiri": "Long press the Talk Button to start Siri session",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigation",
	"NoConnectionNotifyText": "Would you like to connect a phone using Bluetooth?",
	"NoConnectionNotifyTitle": "No Bluetooth Phone Connected",
	"NoDeviceText": "Would you like to connect a Device now?",
	"NoDeviceTitle": "No Device Connected",
	"Notifications": "Notifications",
	"NotifyIgnore": "Ignore",
	"NotifyIncomingMsg": "Incoming Message from:",
	"NotifyOff": "Notify Off",
	"NotifyRead": "Read",
	"NotifyReadNow": "Would you like to read it now?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Reconnecting BT Audio for aha Radio",
	"ReconnectBTAudio": "Reconnecting BT Audio to resume",
	"ReconnectCD": "Verifying CD to Resume Playback",
	"ReconnectCarPlay": "Resuming Apple Carplay.",
	"ReconnectDVD": "Verifying DVD to Resume Playback",
	"ReconnectEntMenuButton": "Audio Sources",
	"ReconnectFailedBTAudio": "Unable to Reconnect Bluetooth Audio",
	"ReconnectFailedCD": "CD was removed. Unable to resume playback.",
	"ReconnectFailedCarPlay": "Unable to Reconnect Apple CarPlay",
	"ReconnectFailedDVD": "DVD was removed. Unable to resume playback.",
	"ReconnectFailedTV": "TV Not Available. Unable to resume playback.",
	"ReconnectFailedUSB": "USB device has changed. Unable to resume playback.",
	"ReconnectPandora": "Reconnecting BT Audio for Pandora",
	"ReconnectStitcher": "Reconnecting BT Audio for Stitcher",
	"ReconnectTV": "Verifying TV to resume playback",
	"ReconnectUSB": "Reconnecting USB device to resume",
	"RetryLabel": "Retry",
	"SchedMaintenanceApp": "Maintenance",
	"ScreenReplication": "Screen Replication",
	"SdarsRadio": "XM",
	"Settings": "Settings",
	"SettingsCommunication": "Settings",
	"Siri": "Siri",
	"SiriDisabled": "Siri is Disabled on Apple Device.",
	"Sms": "Text Messages",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Temperature Warning",
	"TempWarningText": "Display is too Hot. Screen performance may be decreased until it cools.",
	"TextDownloaded": "Text Downloaded",
	"TextSent": "Text Sent",
	"TrafficAlertsItem": "Traffic Information",
	"USB": "USB",
	"USB1AndroidAuto": "USB 1 - Android Auto",
	"USB1CarPlay": "USB 1 - Apple CarPlay",
	"USB2AndroidAuto": "USB 2 - Android Auto",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Vehicle Telemetry Transfer ",
	"VehicleStatusMonitor": "Vehicle Status Monitor",
	"VehicleTelemetryTransfer": "Vehicle Telemetry Transfer",
	"VideoSignalLost": "Video Signal Lost",
	"VoiceNotSupported": "Voice not supported. ",
	"VoiceRecognition": "Voice Recognition",
	"VrHelp_HomeScreen_Help_Left1": "Entertainment",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Settings",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favorites",
	"WarnGuidanceApp": "Warning Guidance",
	"WarningTitle": "WARNING!",
	"XMAudio": "XM Audio",
	"XMData": "XM Services",
	"agree": "I Agree",
};

framework.registerAppDictLoaded("system", "en_US");