var Localization_systemAppDict_pl_PL = {
	//"stringId" : "localString"
	"ActiveCallItem": "Połączenie aktywne",
	"AhaMaintError": "Błąd konserwacji aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Aplikacje",
	"AudioSourceNotAvailableBTAudio": "Niedostępne Bluetooth Audio ",
	"AudioSourceNotAvailableCD": "Dysk CD został wyjęty.",
	"AudioSourceNotAvailableDVD": "Dysk DVD został wyjęty.",
	"AudioSourceNotAvailableTV": "Opcja TV niedostępna",
	"AudioSourceNotAvailableUSB": "Zawartość  USB została zmieniona.",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth — {deviceName}",
	"CallHistory": "Historia połączeń",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Kanał nie nadaje",
	"ChannelUnauth": "Kanał nieautoryzowany",
	"CheckAntenna": "Sprawdź antenę",
	"CheckTuner": "Sprawdź tuner",
	"Communication": "Komunikacja",
	"Connect": "Połącz",
	"Contacts": "Kontakty",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Wybierz numer",
	"DisclaimerText": "Rozproszenie uwagi może być przyczyną wypadku. Nie korzystaj z ekranu podczas jazdy. Skup się na prowadzeniu pojazdu i przestrzegaj przepisów ruchu drogowego. Zobacz instr. obsługi.",
	"DisconnectThenReconnect": "Błąd uruchamiania Siri. Odłącz i podłącz ponownie urządzenie Apple.",
	"DriveRecord": "Rejestr jazdy",
	"DriverIDItem": "Identyfikacja kierowcy",
	"EcoenergyApp": "Monitor Paliwa",
	"EcoenergyAppHEV": "Moduł kontroli jazdy",
	"Email": "Email",
	"Entertainment": "Rozrywka",
	"ErrorWhileStartingSiri": "Błąd podczas uruchamiania Siri.",
	"FailedNotificationRetrieval": "Nie można odzyskać listy powiadomień",
	"FavoritesItem": "Ulubione",
	"FmRadio": "FM",
	"HDTrafficItem": "Radio HD — mapa natężenia ruchu",
	"InitiateSiri": "Przytrzymaj przycisk rozmowy, aby rozpocząć sesję Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Nawigacja",
	"NoConnectionNotifyText": "Czy połączyć telefon teraz?",
	"NoConnectionNotifyTitle": "Niepodłączony telefon",
	"NoDeviceText": "Czy połączyć urządzenie teraz?",
	"NoDeviceTitle": "Brak połączonego urządzenia.",
	"Notifications": "Powiadomienia",
	"NotifyIgnore": "Ignoruj",
	"NotifyIncomingMsg": "Przychodząca wiadomość od:",
	"NotifyOff": "Wył. Powiad.",
	"NotifyRead": "Odczyt",
	"NotifyReadNow": "Czy odczytać teraz?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Pon. łącz. z BluetoothAudio - aha Radio",
	"ReconnectBTAudio": "Pon. łącz. z BluetoothAudio - wzn.odtw.",
	"ReconnectCD": "Weryf. dysku CD do wznow. odtw.",
	"ReconnectDVD": "Weryf. dysku DVD do wznow. odtw.  ",
	"ReconnectEntMenuButton": "Menu rozrywki",
	"ReconnectFailedBTAudio": "Nie można ponownie podłączyć Bluetooth Audio",
	"ReconnectFailedCD": "Dysk CD został wyjęty. Nie można wznowić odtwarzania.",
	"ReconnectFailedDVD": "Dysk DVD został wyjęty. Nie można wznowić odtwarzania.",
	"ReconnectFailedTV": "Opcja TV niedostępna. Nie można wznowić odtwarzania.",
	"ReconnectFailedUSB": "Zawartość urządzenia USB została zmieniona. Nie można wznowić odtwarzania.",
	"ReconnectPandora": "Pon. łącz. z BluetoothAudio - Pandora",
	"ReconnectStitcher": "Pon. łącz. z BluetoothAudio- Stitcher",
	"ReconnectTV": "Trwa sprawdzanie opcji TV, aby wnowić odtwarzanie",
	"ReconnectUSB": "Pon. podłącz.USB - wznow. odtw.",
	"RetryLabel": "Ponów",
	"SchedMaintenanceApp": "Obsługa okresowa",
	"ScreenReplication": "Powtarzanie",
	"SdarsRadio": "XM",
	"Settings": "Ustawienia",
	"SettingsCommunication": "Ustawienia",
	"Siri": "Siri",
	"SiriDisabled": "Funkcja Siri jest wyłączona na urządzeniu Apple.",
	"Sms": "Wiadomość SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Ostrzeżenie o wys. temperaturze",
	"TempWarningText": "Zbyt wysoka temp. wyświetlacza. Ekran może nie działać prawidłowo do czasu schłodzenia.",
	"TextDownloaded": "SMS wysłana",
	"TextSent": "SMS wysłana",
	"TrafficAlertsItem": "Informacje o natężeniu ruchu",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 — {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 — {deviceName}",
	"VehicleDataTransferItem": "Przesyłanie danych pojazdu",
	"VehicleTelemetryTransfer": "TDTP",
	"VideoSignalLost": "Sygnał video utracony",
	"VoiceNotSupported": "Głos nie jest obsługiwana.",
	"VoiceRecognition": "Rozpoznawanie głosu",
	"VrHelp_HomeScreen_Help_Left1": "Entertainment",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Settings",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favorites",
	"WarnGuidanceApp": "Wskazówka ostrzegawcza",
	"WarningTitle": "OSTRZEŻENIE!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Zgadzam się",
};

framework.registerAppDictLoaded("system", "pl_PL");