var Localization_systemAppDict_ar_SA = {
	//"stringId" : "localString"
	"ActiveCallItem": "مكالمة نشطة",
	"AhaMaintError": "خطأ في صيانة aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "التطبيقات",
	"AudioSourceNotAvailableBTAudio": "صوت Bluetooth غير متاح",
	"AudioSourceNotAvailableCD": "تمت إزالة CD",
	"AudioSourceNotAvailableDVD": "تمت إزالة DVD",
	"AudioSourceNotAvailableTV": "التلفاز غير متاح",
	"AudioSourceNotAvailableUSB": "تم تغيير منفذ USB",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "سجل المكالمة",
	"Carplay": "Carplay",
	"CdPlayer": "CD",
	"ChannelOffAir": "القناة غير مذاعة",
	"ChannelUnauth": "القناة غير معتمدة",
	"CheckAntenna": "تفقد الهوائي",
	"CheckTuner": "تفقد الموالف",
	"Communication": "الاتصالات",
	"Connect": "اتصال",
	"Contacts": "جهات الاتصال",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "هاتف الاتصال",
	"DisclaimerText": "قد يتسبب تشتت الانتباه في وقوع حوادث. تجنب التشغيل أثناء القيادة. احرص دائمًا على التركيز واتباع لوائح المرور. انظر كتيب المالك.",
	"DisconnectThenReconnect": "افصل Apple Device ثم أعد توصيله",
	"DriveRecord": "سجلّ القيادة",
	"DriverIDItem": "تحديد السائق",
	"EcoenergyApp": "إقتصاد وقود",
	"EcoenergyAppHEV": "شاشة القيادة",
	"Email": "بريد إلكتروني",
	"Entertainment": " الترفيه",
	"ErrorWhileStartingSiri": "حدث خطأ أثناء بدء Siri.",
	"FailedNotificationRetrieval": "تعذر استرجاع قائمة الإخطارات",
	"FavoritesItem": "المفضلات",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ خريطة التنقل في",
	"InitiateSiri": "اضغط بشكلٍ مطول على زر التحدث لبدء جلسة عمل Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "التنقل",
	"NoConnectionNotifyText": "هل ترغب في توصيل هاتف الآن؟",
	"NoConnectionNotifyTitle": "لا يوجد هاتف متصل",
	"NoDeviceText": "هل ترغب في توصيل جهاز الآن؟",
	"NoDeviceTitle": "لا يوجد جهاز متصل",
	"Notifications": "الإخطارات",
	"NotifyIgnore": "تجاهل",
	"NotifyIncomingMsg": "رسالة واردة من:",
	"NotifyOff": "إبطال الإخطار",
	"NotifyRead": "قراءة",
	"NotifyReadNow": "هل ترغب في قرائتها الآن؟",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "إعادة اتصال Bluetooth لراديو aha",
	"ReconnectBTAudio": "إعادة اتصال BT لاستئناف التشغيل",
	"ReconnectCD": "يتحقق من CD لاستئناف التشغيل",
	"ReconnectDVD": "يتحقق من DVD لاستئناف التشغيل",
	"ReconnectEntMenuButton": "قائمة الترفيه",
	"ReconnectFailedBTAudio": "لم يتمكن من إعادة الاتصال بصوت Bluetooth.",
	"ReconnectFailedCD": "تمت إزالة CD. تعذر استئناف التشغيل.",
	"ReconnectFailedDVD": "تمت إزالة DVD. تعذر استئناف التشغيل.",
	"ReconnectFailedTV": "التلفاز غير متاح. لا يمكن متابعة التشغيل.",
	"ReconnectFailedUSB": "تم تغيير منفذ USB. لم يتمكن من استئناف التشغيل.",
	"ReconnectPandora": "إعادة اتصال صوت Bluetooth لـPandora",
	"ReconnectStitcher": "إعادة اتصال صوت Bluetooth لـStitcher",
	"ReconnectTV": "جاري التحقق من التلفاز لمتابعة التشغيل",
	"ReconnectUSB": "إعادة اتصال USB لاستئناف التشغيل",
	"RetryLabel": "أعد المحاولة",
	"SchedMaintenanceApp": "الصيانة",
	"ScreenReplication": "تكرار الشاشة",
	"SdarsRadio": "XM",
	"Settings": "الإعدادات",
	"SettingsCommunication": "الإعدادات",
	"Siri": "Siri",
	"SiriDisabled": "تم تعطيل Siri في جهاز Apple.",
	"Sms": "رسائل قصيرة",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "تحذير درجة الحرارة",
	"TempWarningText": "جهاز العرض ساخن للغاية. قد ينراجع أداء الشاشة حتى تبرد.",
	"TextDownloaded": "تم تنزيل النص",
	"TextSent": "تم إرسال النص",
	"TrafficAlertsItem": "المعلومات المتعلقة بالتنقل",
	"USB": "USB",
	"UsbAudioA": " USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": " USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "نقل معلومات",
	"VehicleTelemetryTransfer": "نقل المعلومات",
	"VideoSignalLost": "تم فقد إشارة الفيديو",
	"VoiceNotSupported": "الصوت غير مدعوم. ",
	"VoiceRecognition": "تمييز الصوت",
	"VrHelp_HomeScreen_Help_Left1": " الترفيه",
	"VrHelp_HomeScreen_Help_Left2": "الاتصالات",
	"VrHelp_HomeScreen_Help_Left3": "التنقل",
	"VrHelp_HomeScreen_Help_Left4": "الإعدادات",
	"VrHelp_HomeScreen_Help_Left5": "التطبيقات",
	"VrHelp_HomeScreen_Help_Right1": "المفضلات",
	"WarnGuidanceApp": "التوجيه التحذيري",
	"WarningTitle": "تحذير!",
	"XMAudio": "NA ONLY",
	"XMData": "XM Data",
	"agree": "أوافق",
};

framework.registerAppDictLoaded("system", "ar_SA");