var Localization_systemAppDict_fr_FR = {
	//"stringId" : "localString"
	"ActiveCallItem": "Appel actif",
	"AhaMaintError": "Erreur de maintenance d’aha",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Applications",
	"AudioSourceNotAvailableBTAudio": "Bluetooth audio non disponible.",
	"AudioSourceNotAvailableCD": "Le CD a été retiré",
	"AudioSourceNotAvailableDVD": "Le DVD a été retiré",
	"AudioSourceNotAvailableTV": "TV non disponible",
	"AudioSourceNotAvailableUSB": "Le dispositif USB a été modifié",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Historique des appels",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Le canal a cessé d’émettre",
	"ChannelUnauth": "Canal non autorisé",
	"CheckAntenna": "Vérifier l’antenne",
	"CheckTuner": "Vérifier le tuner",
	"Communication": "Communication",
	"Connect": "Connecter  ",
	"Contacts": "Contacts",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Clavier du téléphone",
	"DisclaimerText": "Le manque de concentration peut causer accidents. Ne pas utiliser pendant la conduite. Toujours se concentrer sur la conduite et respecter le code de la route. Consulter le guide d'utilisation",
	"DisconnectThenReconnect": "Erreur au démarrage de Siri. Décon. puis reconnectez l'appareil Apple.",
	"DriveRecord": "Enregist. de la cond.",
	"DriverIDItem": "Identification du conducteur",
	"EcoenergyApp": "Consommation",
	"EcoenergyAppHEV": "Assistant de conduite",
	"Email": "Email",
	"Entertainment": "Divertissements",
	"ErrorWhileStartingSiri": "Erreur au démarrage de Siri.",
	"FailedNotificationRetrieval": "Impossible de récupérer la liste de notifications",
	"FavoritesItem": "Favoris",
	"FmRadio": "FM",
	"HDTrafficItem": "Carte de circulation de HD Radio™",
	"InitiateSiri": "Appuyez longuement sur le bouton Talk pour démarrer la session Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigation",
	"NoConnectionNotifyText": "Voulez-vous connecter un téléphone maintenant ?",
	"NoConnectionNotifyTitle": "Aucun téléphone connecté",
	"NoDeviceText": "Voulez-vous connecter un dispositif maintenant ?",
	"NoDeviceTitle": "Aucun dispositif connecté",
	"Notifications": "Notifications",
	"NotifyIgnore": "Ignorer",
	"NotifyIncomingMsg": "Message entrant de :",
	"NotifyOff": "Notif OFF",
	"NotifyRead": "Lire",
	"NotifyReadNow": "Voulez-vous le lire maintenant ?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Reconnexion Bluetooth audio pour aha",
	"ReconnectBTAudio": "Reconnex Bluetooth audio pr repris lect",
	"ReconnectCD": "Vérification du CD pour reprise lecture",
	"ReconnectDVD": "Vérification DVD pour reprise lecture",
	"ReconnectEntMenuButton": "Menu des divertissements",
	"ReconnectFailedBTAudio": "Impossible de reconnecter l’audio Bluetooth",
	"ReconnectFailedCD": "Le CD a été retiré. Impossible de reprendre la lecture.",
	"ReconnectFailedDVD": "Le DVD a été retiré. Impossible de reprendre la lecture.",
	"ReconnectFailedTV": "TV non disponible. Impossible de reprendre la lecture.",
	"ReconnectFailedUSB": "Le dispositif USB a été modifié. Impossible de reprendre la lecture.",
	"ReconnectPandora": "Reconnexion Bluetooth audio pr Pandora",
	"ReconnectStitcher": "Reconnexion Bluetooth audio pr Stitcher",
	"ReconnectTV": "Vérification de la TV pour reprendre la lecture",
	"ReconnectUSB": "Reconnex° dispositif USB pr reprise lect",
	"RetryLabel": "Réessayer",
	"SchedMaintenanceApp": "Entretien",
	"ScreenReplication": "Screen Replication",
	"SdarsRadio": "XM",
	"Settings": "Paramètres",
	"SettingsCommunication": "Paramètres",
	"Siri": "Siri",
	"SiriDisabled": "Siri est désactivé sur l'appareil Apple.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Avertissement de température",
	"TempWarningText": "LA température de l’affichage est trop élevée. Les performances de l'écran peuvent être réduites jusqu'à son refroidissement.",
	"TextDownloaded": "SMS téléchargé",
	"TextSent": "SMS envoyé",
	"TrafficAlertsItem": "Info sur la circulation",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Transfert données du véhicule",
	"VehicleTelemetryTransfer": "Transfert Données",
	"VideoSignalLost": "Signal vidéo perdu",
	"VoiceNotSupported": "Voix pas pris en charge",
	"VoiceRecognition": "Reconnaissance vocale",
	"VrHelp_HomeScreen_Help_Left1": "Divertissements",
	"VrHelp_HomeScreen_Help_Left2": "Communication",
	"VrHelp_HomeScreen_Help_Left3": "Navigation",
	"VrHelp_HomeScreen_Help_Left4": "Paramètres",
	"VrHelp_HomeScreen_Help_Left5": "Applications",
	"VrHelp_HomeScreen_Help_Right1": "Favoris",
	"WarnGuidanceApp": "Avertissements",
	"WarningTitle": "ATTENTION !",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Je suis d'accord",
};

framework.registerAppDictLoaded("system", "fr_FR");