var Localization_systemAppDict_fi_FI = {
	//"stringId" : "localString"
	"ActiveCallItem": "Käynnissä oleva puhelu",
	"AhaMaintError": "aha ylläpitovirhe",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Sovellukset",
	"AudioSourceNotAvailableBTAudio": "BT-audioon ei ole käytettävissä",
	"AudioSourceNotAvailableCD": "CD otettiin pois asemasta",
	"AudioSourceNotAvailableDVD": "DVD otettiin pois asemasta",
	"AudioSourceNotAvailableTV": "TV ei saatavilla",
	"AudioSourceNotAvailableUSB": "USB-laite on vaihtunut",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Puheluhistoria",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Kanavalla ei ole lähetystä",
	"ChannelUnauth": "Kanavaan ei ole oikeuksia",
	"CheckAntenna": "Tarkista antenni",
	"CheckTuner": "Tarkista viritin",
	"Communication": "Viestintä",
	"Connect": "Yhdistä",
	"Contacts": "Yhteystiedot",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Soita puhelimeen",
	"DisclaimerText": "Häiriötekijät voivat aiheuttaa onnettomuuksia. Älä käytä laitetta ajon aikana. Keskity aina liikenteeseen ja noudata liikennesäätöjä. Katso omistajan käsikirja.",
	"DisconnectThenReconnect": "Katkaise yhteys ja yhdistä Apple-laite uudelleen",
	"DriveRecord": "Ajorekisteri",
	"DriverIDItem": "Kuljettajan tunnistus",
	"EcoenergyApp": "Kulutuksen valvonta",
	"EcoenergyAppHEV": "Ajomonitori",
	"Email": "Email",
	"Entertainment": "Viihde",
	"ErrorWhileStartingSiri": "Siri -sovelluksen käynnistyksessä tapahtui virhe.",
	"FailedNotificationRetrieval": "Ilmoitusluettelon noutaminen ei onnistu",
	"FavoritesItem": "Suosikit",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ -liikennekartta",
	"InitiateSiri": "Paina Puhe-nappulaa pohjassa ja aloita Siri-sovelluksen käyttö.",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigointi",
	"NoConnectionNotifyText": "Haluatko liittää puhelimen nyt?",
	"NoConnectionNotifyTitle": "Ei kytkettyä puhelinta",
	"NoDeviceText": "Haluatko liittää laitteen nyt?",
	"NoDeviceTitle": "Ei kytkettyä laitetta",
	"Notifications": "Ilmoitukset",
	"NotifyIgnore": "Ohita",
	"NotifyIncomingMsg": "Saapuva viesti lähettäjältä:",
	"NotifyOff": "Ilmoitus pois",
	"NotifyRead": "Lue",
	"NotifyReadNow": "Haluatko lukea sen nyt?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Yhdistää BT-audioon aha-radiota varten",
	"ReconnectBTAudio": "Yhdistää BT-audioon toistoa varten",
	"ReconnectCD": "Tarkistaa CD-levyä toistamista varten",
	"ReconnectDVD": "Tarkistaa DVD-levyä toistamista varten",
	"ReconnectEntMenuButton": "Viihdevalikko",
	"ReconnectFailedBTAudio": "Bluetooth-äänilaitteen yhteyden uudelleenmuodostaminen ei onnistunut",
	"ReconnectFailedCD": "CD otettiin pois asemasta. Toistoa ei voi jatkaa.",
	"ReconnectFailedDVD": "DVD otettiin pois asemasta. Toistoa ei voi jatkaa.",
	"ReconnectFailedTV": "TV ei saatavilla. Toiston jatkaminen ei onnistunut.",
	"ReconnectFailedUSB": "USB-laite on vaihtunut. Toistoa ei voi jatkaa.",
	"ReconnectPandora": "Yhdistää BT-audioon Pandoraa varten",
	"ReconnectStitcher": "Yhdistää BT-audioon Stitcheriä varten",
	"ReconnectTV": "TV:tä vahvistetaan toiston jatkamiseksi",
	"ReconnectUSB": "Yhdistää USB-laitteeseen toistoa varten",
	"RetryLabel": "Yritä uudelleen",
	"SchedMaintenanceApp": "Huolto",
	"ScreenReplication": "Näytönreplikaatio",
	"SdarsRadio": "XM",
	"Settings": "Asetukset",
	"SettingsCommunication": "Asetukset",
	"Siri": "Siri",
	"SiriDisabled": "Siri ei ole käytössä Applen laitteilla.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Lämpötilavaroitus",
	"TempWarningText": "Näyttö on ylikuumentunut. Näyttö voi toimia hitaasti, kunnes se ehtii jäähtyä.",
	"TextDownloaded": "SMS ladattu",
	"TextSent": "SMS lähetetty",
	"TrafficAlertsItem": "Liikennetiedot",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Auton tiedonsiirto",
	"VehicleTelemetryTransfer": "Ajoneuvon telemetrian siirto",
	"VideoSignalLost": "Kuvasignaali katkesi",
	"VoiceNotSupported": "Ääntä ei tueta",
	"VoiceRecognition": "Äänentunnistus",
	"VrHelp_HomeScreen_Help_Left1": "Viihde",
	"VrHelp_HomeScreen_Help_Left2": "Viestintä",
	"VrHelp_HomeScreen_Help_Left3": "Navigointi",
	"VrHelp_HomeScreen_Help_Left4": "Asetukset",
	"VrHelp_HomeScreen_Help_Left5": "Sovellukset",
	"VrHelp_HomeScreen_Help_Right1": "Suosikit",
	"WarnGuidanceApp": "Varoitukset",
	"WarningTitle": "VAROITUS!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Hyväksyn",
};

framework.registerAppDictLoaded("system", "fi_FI");