var Localization_systemAppDict_es_ES = {
	//"stringId" : "localString"
	"ActiveCallItem": "Llamada Activa",
	"AhaMaintError": "Error de mantenimiento aha",
	"AhaRadio": "aha ",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Aplicaciones ",
	"AudioSourceNotAvailableBTAudio": "Audio de Bluetooth No Disponible",
	"AudioSourceNotAvailableCD": "CD ha sido eliminado",
	"AudioSourceNotAvailableDVD": "DVD ha sido eliminado",
	"AudioSourceNotAvailableTV": "No hay TV disponible",
	"AudioSourceNotAvailableUSB": "El dispositivo USB ha cambiado",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Historial de Llamadas",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Canal fuera del área",
	"ChannelUnauth": "Canal no autorizado",
	"CheckAntenna": "Revisar antena",
	"CheckTuner": "Revisar sintonizador",
	"Communication": "Comunicación",
	"Connect": "Conectar ",
	"Contacts": "Contactos ",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Marcar Teléfono",
	"DisclaimerText": "Las distracciones pueden causar accidentes. No maneje sus dispositivos mientras conduzca. Concéntrese en conducir y cumpla las reglas de tráfico. Vea manual de usuario.",
	"DisconnectThenReconnect": "Error al iniciar Siri. Desconecte y vuelva a conectar el dispositivo Apple.",
	"DriveRecord": "Registro de cond.",
	"DriverIDItem": "Selección Conductor",
	"EcoenergyApp": "Ahorro de Combustible",
	"EcoenergyAppHEV": "Monitor conducción",
	"Email": "Email ",
	"Entertainment": "Entretenimiento",
	"ErrorWhileStartingSiri": "Error al iniciar Siri.",
	"FailedNotificationRetrieval": "No se puede recuperar la Lista de Notificaciones",
	"FavoritesItem": "Favoritos ",
	"FmRadio": "FM",
	"HDTrafficItem": "Mapa de Tráfico HD Radio™",
	"InitiateSiri": "Presione de forma prolongada el botón Hablar para iniciar una sesión de Siri",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navegación",
	"NoConnectionNotifyText": "¿Desea conectar un teléfono ahora?",
	"NoConnectionNotifyTitle": "No hay Teléfono Conectado",
	"NoDeviceText": "¿Desea conectar un dispositivo ahora?",
	"NoDeviceTitle": "No hay ningún Dispositivo Conectado",
	"Notifications": "Notificaciones ",
	"NotifyIgnore": "Ignorar ",
	"NotifyIncomingMsg": "Mensaje Entrante de:",
	"NotifyOff": "Notif. Off",
	"NotifyRead": "Lectura ",
	"NotifyReadNow": "¿Desea leerlo ahora?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Reconect.audio Bluetooth Radio aha",
	"ReconnectBTAudio": "Recn.audio Bluetooth reanudar reprod.",
	"ReconnectCD": "Verificando CD reanudar reproduc.",
	"ReconnectDVD": "Verificando DVD reanudar reproduc.",
	"ReconnectEntMenuButton": "Menú entretenimiento",
	"ReconnectFailedBTAudio": "No se puede Volver a Conectar el Audio de Bluetooth.",
	"ReconnectFailedCD": "CD ha sido eliminado. No se puede reanudar la reproducción.",
	"ReconnectFailedDVD": "DVD ha sido eliminado. No se puede reanudar la reproducción.",
	"ReconnectFailedTV": "No hay TV disponible. No se puede resumir la reproducción.",
	"ReconnectFailedUSB": "El dispositivo USB ha cambiado No se puede reanudar la reproducción.",
	"ReconnectPandora": "Reconect.audio Bluetooth Pandora",
	"ReconnectStitcher": "Reconect.audio Bluetooth Stitcher",
	"ReconnectTV": "Verificando la TV para continuar la reproducción",
	"ReconnectUSB": "Reconect.USB reanudar reproducc.",
	"RetryLabel": "Reintentar",
	"SchedMaintenanceApp": "Mantenimiento",
	"ScreenReplication": "Reproducción de la pantalla",
	"SdarsRadio": "XM",
	"Settings": "Configuraciones",
	"SettingsCommunication": "Configuraciones",
	"Siri": "Siri",
	"SiriDisabled": "Siri desactivado en dispositivo Apple.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Advertencia de Temperatura",
	"TempWarningText": "La pantalla está muy caliente.  El rendimiento de la pantalla puede disminuir hasta que enfríe. ",
	"TextDownloaded": "SMS descargado",
	"TextSent": "SMS enviado",
	"TrafficAlertsItem": "Información de Tráfico",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Transf Datos de Vehículo",
	"VehicleTelemetryTransfer": "Transf. de información",
	"VideoSignalLost": "Señal de vídeo perdida",
	"VoiceNotSupported": "Voz no es compatible.",
	"VoiceRecognition": "Reconocimiento de voz",
	"VrHelp_HomeScreen_Help_Left1": "Entretenimiento",
	"VrHelp_HomeScreen_Help_Left2": "Comunicación",
	"VrHelp_HomeScreen_Help_Left3": "Navegación",
	"VrHelp_HomeScreen_Help_Left4": "Configuraciones",
	"VrHelp_HomeScreen_Help_Left5": "Aplicaciones",
	"VrHelp_HomeScreen_Help_Right1": "Favoritos",
	"WarnGuidanceApp": "Guía de advertencia",
	"WarningTitle": "¡ADVERTENCIA!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Estoy de Acuerdo",
};

framework.registerAppDictLoaded("system", "es_ES");