var Localization_systemAppDict_da_DK = {
	//"stringId" : "localString"
	"ActiveCallItem": "Aktivt opkald",
	"AhaMaintError": "aha fejl i vedligeholdelse",
	"AhaRadio": "aha",
	"AmRadio": "AM",
	"AndroidAuto": "Android Auto",
	"Applications": "Applikationer",
	"AudioSourceNotAvailableBTAudio": "Bluetooth-audio ikke disponibel",
	"AudioSourceNotAvailableCD": "CD'en blev fjernet",
	"AudioSourceNotAvailableDVD": "DVD'en blev fjernet",
	"AudioSourceNotAvailableTV": "Tv ikke tilgængelig",
	"AudioSourceNotAvailableUSB": "USB-enhed er skiftet",
	"AuxIn": "AUX",
	"BT": "BT",
	"Bluetooth": "Bluetooth",
	"BluetoothWithDevice": "Bluetooth - {deviceName}",
	"CallHistory": "Opkaldshistorik",
	"Carplay": "CarPlay",
	"CdPlayer": "CD",
	"ChannelOffAir": "Kanal ikke tilgængelig",
	"ChannelUnauth": "Kanal ikke godkendt",
	"CheckAntenna": "Kontrollér antennen",
	"CheckTuner": "Kontrollér radio",
	"Communication": "Kommunikation",
	"Connect": "Tilslut",
	"Contacts": "Kontakter",
	"DVDItem": "DVD",
	"DabRadio": "DAB",
	"DialPhone": "Opkald",
	"DisclaimerText": "Forstyrrelser kan forårsage ulykker. Betjen ikke under kørsel. Koncentrér dig altid om kørslen og overhold færdselsreglerne. Se instruktionsbogen.",
	"DisconnectThenReconnect": "Fejl under start af Siri. Frakobl, og tilkobl så Apple Device.",
	"DriveRecord": "Kørebog",
	"DriverIDItem": "Identifikation af fører ",
	"EcoenergyApp": "Økonomi",
	"EcoenergyAppHEV": "Køreskærm",
	"Email": "Email",
	"Entertainment": "Underholdning",
	"ErrorWhileStartingSiri": "Fejl under start af Siri.",
	"FailedNotificationRetrieval": "Kunne ikke hente notifikationsliste",
	"FavoritesItem": "Favoritter ",
	"FmRadio": "FM",
	"HDTrafficItem": "HD Radio™ Traffic Map",
	"InitiateSiri": "Tryk og hold knappen nede for at starte en Siri-session",
	"IntelligentDriveMasterItem": "i-DM",
	"NavigationTitle": "Navigering",
	"NoConnectionNotifyText": "Ønsker du at tilslutte telefonen nu?",
	"NoConnectionNotifyTitle": "Ingen telefon tilsluttet",
	"NoDeviceText": "Ønsker du at tilslutte en enhed nu?",
	"NoDeviceTitle": "Der er ikke tilsluttet nogen enhed",
	"Notifications": "Meddelelser",
	"NotifyIgnore": "Ignorér",
	"NotifyIncomingMsg": "Indgående besked fra:",
	"NotifyOff": "Medl. Fra",
	"NotifyRead": "Læs",
	"NotifyReadNow": "Ønsker du at læse den nu?",
	"Pandora": "Pandora",
	"ReconnectAhaRadio": "Genforbinder Bluetooth audio",
	"ReconnectBTAudio": "Genforbinder Bluetooth audio",
	"ReconnectCD": "Verificerer CD for at genoptage afspiln.",
	"ReconnectDVD": "Verificerer DVD for at genoptage afsp.",
	"ReconnectEntMenuButton": "Underholdningsmenu",
	"ReconnectFailedBTAudio": "Kunne ikke genforbinde til Bluetooth-audio.",
	"ReconnectFailedCD": "CD'en blev fjernet. Kunne ikke genoptage afspilning.",
	"ReconnectFailedDVD": "DVD blev fjernet. Kan ikke genoptage afspilningen.",
	"ReconnectFailedTV": "Tv ikke tilgængelig. Kan ikke genoptage afspilningen.",
	"ReconnectFailedUSB": "USB-enhed er skiftet. Kunne ikke genoptage afspilning.",
	"ReconnectPandora": "Genforbinder Bluetooth audio",
	"ReconnectStitcher": "Genforbinder Bluetooth audio",
	"ReconnectTV": "Verificerer tv for at genoptage afspilningen",
	"ReconnectUSB": "Genforbinder USB-enhed",
	"RetryLabel": "Prøv igen",
	"SchedMaintenanceApp": "Vedligeholdelse",
	"ScreenReplication": "Skærmkopiering",
	"SdarsRadio": "XM",
	"Settings": "Indstillinger",
	"SettingsCommunication": "Indstillinger",
	"Siri": "Siri",
	"SiriDisabled": "Siri is Disabled on Apple Device.",
	"Sms": "SMS",
	"StitcherItem": "Stitcher",
	"TVItem": "TV",
	"TempWarning": "Temperaturadvarsel",
	"TempWarningText": "Displayet er for varmt. Skærmens ydelse kan være nedsat, indtil den køler af.",
	"TextDownloaded": "SMS hentet",
	"TextSent": "SMS sendt",
	"TrafficAlertsItem": "Trafikinformation",
	"USB": "USB",
	"UsbAudioA": "USB 1",
	"UsbAudioAWithDevice": "USB 1 - {deviceName}",
	"UsbAudioB": "USB 2",
	"UsbAudioBWithDevice": "USB 2 - {deviceName}",
	"VehicleDataTransferItem": "Overførsel af køretøjsdata",
	"VehicleTelemetryTransfer": "OKT",
	"VideoSignalLost": "Videosignalet mistet",
	"VoiceNotSupported": "Voice understøttes ikke",
	"VoiceRecognition": "Stemmegenkendelse",
	"VrHelp_HomeScreen_Help_Left1": "Underholdning",
	"VrHelp_HomeScreen_Help_Left2": "Kommunikation",
	"VrHelp_HomeScreen_Help_Left3": "Navigering",
	"VrHelp_HomeScreen_Help_Left4": "Indstillinger",
	"VrHelp_HomeScreen_Help_Left5": "Applikationer",
	"VrHelp_HomeScreen_Help_Right1": "Foretrukne",
	"WarnGuidanceApp": "Advarselsvejledning",
	"WarningTitle": "ADVARSEL!",
	"XMAudio": "XM Audio",
	"XMData": "XM Data",
	"agree": "Jeg Accepterer",
};

framework.registerAppDictLoaded("system", "da_DK");