var Localization_emnaviAppDict_th_TH = {
	//"stringId" : "localString"
	"AddressNotFound": "ไม่พบที่อยู่",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "เข็มทิศ",
	"E": "{value} ต.อ.",
	"Elevation": "ค่าระดับความสูง",
	"FT": "{value}{spacing}ฟ.",
	"Latitude": "ละติจูด",
	"Loading": "กำลังโหลดระบบนำทาง",
	"Longitude": "ลองจิจูด",
	"M": "{value}{spacing}ม.",
	"N": "{value} น.",
	"NAVAddressSearch": "ระบบนำทาง",
	"NAVAvoidances": "ระบบนำทาง",
	"NAVCitySearch": "ระบบนำทาง",
	"NAVCoordinate": "ระบบนำทาง",
	"NAVDragMode": "ระบบนำทาง",
	"NAVGasPrice": "ระบบนำทาง",
	"NAVHistory": "ระบบนำทาง",
	"NAVItemList": "ระบบนำทาง",
	"NAVMap": "ระบบนำทาง",
	"NAVMecca": "ระบบนำทาง",
	"NAVModifyPoint": "ระบบนำทาง",
	"NAVNavigationInfo": "ระบบนำทาง",
	"NAVNewDestination": "ระบบนำทาง",
	"NAVPOI": "ระบบนำทาง",
	"NAVPhoneZipSearch": "ระบบนำทาง",
	"NAVPointOnMap": "ระบบนำทาง",
	"NAVQuickSearch": "ระบบนำทาง",
	"NAVResults": "ระบบนำทาง",
	"NAVRoute": "ระบบนำทาง",
	"NAVSettings": "ระบบนำทาง",
	"NAVSimulation": "ระบบนำทาง",
	"NAVSortingOptions": "ระบบนำทาง",
	"NAVTraffic": "ระบบนำทาง",
	"NAVTurnByTurn": "ระบบนำทาง",
	"NAVVoicePrompts": "ระบบนำทาง",
	"NAVWeather": "ระบบนำทาง",
	"NoNavigation": "Mazda ของคุณไม่มีระบบนำทาง อย่างไรก็ตาม สามารถจัดหาระบบนำทางมาเป็นส่วนเสริมของแท้ของ Mazda (Genuine Mazda Accessory) ได้จากตัวแทนจำหน่าย Mazda ของคุณ",
	"S": "{value} ต",
	"SDCardInvalid": "การ์ด SD ไม่ถูกต้อง",
	"SDCradInserted": "ใส่การ์ด SD",
	"SDCradRemoved": "ถอดการ์ด SD ออก",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} ต.ต.",
	"Y": "{value}{spacing}หลา",
	"YourLocation": "ตำแหน่งของคุณ",
	"emnavi": "ระบบนำทาง",
	"km": "{value}{spacing}กม.",
	"mi": "{value}{spacing}ไมล์",
};

framework.registerAppDictLoaded("emnavi", "th_TH");