var Localization_emnaviAppDict_ro_RO = {
	//"stringId" : "localString"
	"AddressNotFound": "Adresă negăsită",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Cuprins",
	"E": "{value} E",
	"Elevation": "Altitudine",
	"FT": "{value}{spacing}ft",
	"Latitude": "Latitudine",
	"Loading": "Încărcare navigaţie",
	"Longitude": "Longitudine",
	"M": "{value}{spacing}m",
	"N": "{value} N",
	"NAVAddressSearch": "Navigaţie",
	"NAVAvoidances": "Navigaţie",
	"NAVCitySearch": "Navigaţie",
	"NAVCoordinate": "Navigaţie",
	"NAVDragMode": "Navigaţie",
	"NAVGasPrice": "Navigaţie",
	"NAVHistory": "Navigaţie",
	"NAVItemList": "Navigaţie",
	"NAVMap": "Navigaţie",
	"NAVMecca": "Navigaţie",
	"NAVModifyPoint": "Navigaţie",
	"NAVNavigationInfo": "Navigaţie",
	"NAVNewDestination": "Navigaţie",
	"NAVPOI": "Navigaţie",
	"NAVPhoneZipSearch": "Navigaţie",
	"NAVPointOnMap": "Navigaţie",
	"NAVQuickSearch": "Navigaţie",
	"NAVResults": "Navigaţie",
	"NAVRoute": "Navigaţie",
	"NAVSettings": "Navigaţie",
	"NAVSimulation": "Navigaţie",
	"NAVSortingOptions": "Navigaţie",
	"NAVTraffic": "Navigaţie",
	"NAVTurnByTurn": "Navigaţie",
	"NAVVoicePrompts": "Navigaţie",
	"NAVWeather": "Navigaţie",
	"NoNavigation": "Vehiculul dvs. Mazda nu este dotat cu sistem de navigaţie. Un sistem de navigaţie integrat este disponibil la dealerul Mazda ca Accesoriu original Mazda.",
	"S": "{value} S",
	"SDCardInvalid": "Card SD nevalid",
	"SDCradInserted": "Card SD introdus",
	"SDCradRemoved": "Card SD scos",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} V",
	"Y": "{value}{spacing}yd",
	"YourLocation": "Locaţia dvoastră",
	"emnavi": "Navigaţie",
	"km": "{value}{spacing}km",
	"mi": "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "ro_RO");