var Localization_emnaviAppDict_zh_CN = {
	//"stringId" : "localString"
	"AddressNotFound": "未找到地址",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "指南针",
	"E": "{value} 东",
	"Elevation": "海拔",
	"FT": "{value}{spacing}英尺",
	"Latitude": "纬度",
	"Loading": "正在加载导航",
	"Longitude": "经度",
	"M": "{value}{spacing}米",
	"N": "{value} 北",
	"NAVAddressSearch": "导航",
	"NAVAvoidances": "导航",
	"NAVCitySearch": "导航",
	"NAVCoordinate": "导航",
	"NAVDragMode": "导航",
	"NAVGasPrice": "导航",
	"NAVHistory": "导航",
	"NAVItemList": "导航",
	"NAVMap": "导航",
	"NAVMecca": "导航",
	"NAVModifyPoint": "导航",
	"NAVNavigationInfo": "导航",
	"NAVNewDestination": "导航",
	"NAVPOI": "导航",
	"NAVPhoneZipSearch": "导航",
	"NAVPointOnMap": "导航",
	"NAVQuickSearch": "导航",
	"NAVResults": "导航",
	"NAVRoute": "导航",
	"NAVSettings": "导航",
	"NAVSimulation": "导航",
	"NAVSortingOptions": "导航",
	"NAVTraffic": "导航",
	"NAVTurnByTurn": "导航",
	"NAVVoicePrompts": "导航",
	"NAVWeather": "导航",
	"NoNavigation": "您的Mazda未配备导航系统。但通过您的Mazda经销商可获得作为真品Mazda附件提供的集成导航系统。",
	"S": "{value} 南",
	"SDCardInvalid": "SD卡无效",
	"SDCradInserted": "SD卡已插入",
	"SDCradRemoved": "SD卡已取出",
	"VrHelp_Cockpit_Help2_Left1": "新目的地",
	"VrHelp_Cockpit_Help2_Left2": "将我带到家",
	"VrHelp_Cockpit_Help2_Left3": "导航到地址",
	"VrHelp_Cockpit_Help2_Left4": "导航到最近目的地",
	"VrHelp_Cockpit_Help2_Left5": "清除路线",
	"VrHelp_Cockpit_Help2_Right1": "我在哪儿",
	"VrHelp_Cockpit_Help2_Right2": "路线概览",
	"VrHelp_Cockpit_Help2_Right3": "重复指令",
	"VrHelp_Cockpit_Help2_Right4": "将当前位置添加到收藏夹",
	"VrHelp_Cockpit_Help2_Right5": "添加路标（类别）",
	"W": "{value} 西",
	"Y": "{value}{spacing}码",
	"YourLocation": "您的位置",
	"emnavi": "导航",
	"km": "{value}{spacing}公里",
	"mi": "{value}{spacing}英里",
};

framework.registerAppDictLoaded("emnavi", "zh_CN");