var Localization_emnaviAppDict_fi_FI = {
	//"stringId" : "localString"
	"AddressNotFound": "Osoitetta ei löydy",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Kompassi",
	"E": "{value} E",
	"Elevation": "Korkeus",
	"FT": "{value}{spacing}jalkaa",
	"Latitude": "Leveysaste",
	"Loading": "Ladataan navigointia",
	"Longitude": "Pituusaste",
	"M": "{value}{spacing}m",
	"N": "{value} N",
	"NAVAddressSearch": "Navigointi",
	"NAVAvoidances": "Navigointi",
	"NAVCitySearch": "Navigointi",
	"NAVCoordinate": "Navigointi",
	"NAVDragMode": "Navigointi",
	"NAVGasPrice": "Navigointi",
	"NAVHistory": "Navigointi",
	"NAVItemList": "Navigointi",
	"NAVMap": "Navigointi",
	"NAVMecca": "Navigointi",
	"NAVModifyPoint": "Navigointi",
	"NAVNavigationInfo": "Navigointi",
	"NAVNewDestination": "Navigointi",
	"NAVPOI": "Navigointi",
	"NAVPhoneZipSearch": "Navigointi",
	"NAVPointOnMap": "Navigointi",
	"NAVQuickSearch": "Navigointi",
	"NAVResults": "Navigointi",
	"NAVRoute": "Navigointi",
	"NAVSettings": "Navigointi",
	"NAVSimulation": "Navigointi",
	"NAVSortingOptions": "Navigointi",
	"NAVTraffic": "Navigointi",
	"NAVTurnByTurn": "Navigointi",
	"NAVVoicePrompts": "Navigointi",
	"NAVWeather": "Navigointi",
	"NoNavigation": "Mazda-autossasi ei ole navigointijärjestelmää. Voit hankkia alkuperäisenä Mazda-lisävarusteena saatavan integroidun navigointijärjestelmän Mazda-jälleenmyyjältäsi.",
	"S": "{value} S",
	"SDCardInvalid": "Virheellinen SD-kortti",
	"SDCradInserted": "SD-kortti laitettu asemaan",
	"SDCradRemoved": "SD-kortti otettiin pois asemasta",
	"VrHelp_Cockpit_Help2_Left1": "Uusi määränpää",
	"VrHelp_Cockpit_Help2_Left2": "Vie minut kotiin",
	"VrHelp_Cockpit_Help2_Left3": "Navigoi osoitteeseen",
	"VrHelp_Cockpit_Help2_Left4": "Navigoi äskettäin käytettyyn määränpäähän",
	"VrHelp_Cockpit_Help2_Left5": "Tyhjennä reitti",
	"VrHelp_Cockpit_Help2_Right1": "Missä minä olen",
	"VrHelp_Cockpit_Help2_Right2": "Reitin yhteenveto",
	"VrHelp_Cockpit_Help2_Right3": "Toista ohjeet",
	"VrHelp_Cockpit_Help2_Right4": "Lisää nykyinen sijainti suosikkeihin ",
	"VrHelp_Cockpit_Help2_Right5": "Lisää välietappi (luokka)",
	"W": "{value} W",
	"Y": "{value}{spacing}jaardia",
	"YourLocation": "Oma sijaintisi",
	"emnavi": "Navigointi",
	"km": "{value}{spacing}km",
	"mi": "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "fi_FI");