var Localization_emnaviAppDict_sk_SK = {
	//"stringId" : "localString"
	"AddressNotFound": "Adresa sa nenašla",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Kompas",
	"E": "{value} V",
	"Elevation": "n/výška",
	"FT": "{value}{spacing}stopy",
	"Latitude": "Zem. šírka",
	"Loading": "Načítava sa navigácia",
	"Longitude": "Zemep. dĺžka",
	"M": "{value}{spacing}m",
	"N": "{value} S",
	"NAVAddressSearch": "Navigácia",
	"NAVAvoidances": "Navigácia",
	"NAVCitySearch": "Navigácia",
	"NAVCoordinate": "Navigácia",
	"NAVDragMode": "Navigácia",
	"NAVGasPrice": "Navigácia",
	"NAVHistory": "Navigácia",
	"NAVItemList": "Navigácia",
	"NAVMap": "Navigácia",
	"NAVMecca": "Navigácia",
	"NAVModifyPoint": "Navigácia",
	"NAVNavigationInfo": "Navigácia",
	"NAVNewDestination": "Navigácia",
	"NAVPOI": "Navigácia",
	"NAVPhoneZipSearch": "Navigácia",
	"NAVPointOnMap": "Navigácia",
	"NAVQuickSearch": "Navigácia",
	"NAVResults": "Navigácia",
	"NAVRoute": "Navigácia",
	"NAVSettings": "Navigácia",
	"NAVSimulation": "Navigácia",
	"NAVSortingOptions": "Navigácia",
	"NAVTraffic": "Navigácia",
	"NAVTurnByTurn": "Navigácia",
	"NAVVoicePrompts": "Navigácia",
	"NAVWeather": "Navigácia",
	"NoNavigation": "Vaša Mazda nie je vybavená navigačným systémom. Avšak, integrovaný navigačný systém si možno zadovážiť od svojho predajcu Mazda ako originálne príslušenstvo značky Mazda.",
	"S": "{value} J",
	"SDCardInvalid": "Neplatná SD karta",
	"SDCradInserted": "SD karta zasunutá",
	"SDCradRemoved": "SD karta vybratá",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} Z",
	"Y": "{value}{spacing}yardov",
	"YourLocation": "Vaša poloha",
	"emnavi": "Navigácia",
	"km": "{value}{spacing}km",
	"mi": "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "sk_SK");