var Localization_emnaviAppDict_pt_BR = {
	//"stringId" : "localString"
	"AddressNotFound": "Endereço não encontrado",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Bússola",
	"E": "{value} L",
	"Elevation": "Elevação",
	"FT": "{value}{spacing} pés",
	"Latitude": "Latitude",
	"Loading": "Carregando navegação",
	"Longitude": "Longitude",
	"M": "{value}{spacing}m",
	"N": "{value} N",
	"NAVAddressSearch": "Navegação",
	"NAVAvoidances": "Navegação",
	"NAVCitySearch": "Navegação",
	"NAVCoordinate": "Navegação",
	"NAVDragMode": "Navegação",
	"NAVGasPrice": "Navegação",
	"NAVHistory": "Navegação",
	"NAVItemList": "Navegação",
	"NAVMap": "Navegação",
	"NAVMecca": "Navegação",
	"NAVModifyPoint": "Navegação",
	"NAVNavigationInfo": "Navegação",
	"NAVNewDestination": "Navegação",
	"NAVPOI": "Navegação",
	"NAVPhoneZipSearch": "Navegação",
	"NAVPointOnMap": "Navegação",
	"NAVQuickSearch": "Navegação",
	"NAVResults": "Navegação",
	"NAVRoute": "Navegação",
	"NAVSettings": "Navegação",
	"NAVSimulation": "Navegação",
	"NAVSortingOptions": "Navegação",
	"NAVTraffic": "Navegação",
	"NAVTurnByTurn": "Navegação",
	"NAVVoicePrompts": "Navegação",
	"NAVWeather": "Navegação",
	"NoNavigation": "Veículo não equipado com sist. navegação. Um sistema de navegação integrado está disponível em sua concessionária Mazda como Acessório Original da Mazda.",
	"S": "{value} S",
	"SDCardInvalid": "Cartão SD inválido",
	"SDCradInserted": "Cartão SD inserido",
	"SDCradRemoved": "Cartão SD removido",
	"VrHelp_Cockpit_Help2_Left1": "Novo destino",
	"VrHelp_Cockpit_Help2_Left2": "Ir para casa",
	"VrHelp_Cockpit_Help2_Left3": "Navegar para um endereço",
	"VrHelp_Cockpit_Help2_Left4": "Navegar para destino recente",
	"VrHelp_Cockpit_Help2_Left5": "Limpar percurso",
	"VrHelp_Cockpit_Help2_Right1": "Onde estou",
	"VrHelp_Cockpit_Help2_Right2": "Resumo do percurso",
	"VrHelp_Cockpit_Help2_Right3": "Repetir instrução",
	"VrHelp_Cockpit_Help2_Right4": "Adicionar localização actual aos favoritos",
	"VrHelp_Cockpit_Help2_Right5": "Adicionar ponto de referência (categoria)",
	"W": "{value} O",
	"Y": "{value}{spacing} jardas",
	"YourLocation": "Seu local",
	"emnavi": "Navegação",
	"km": "{value}{spacing}km",
	"mi": "{value}{spacing} milhas",
};

framework.registerAppDictLoaded("emnavi", "pt_BR");