var Localization_emnaviAppDict_bg_BG = {
	//"stringId" : "localString"
	"AddressNotFound": "Адресът не е намерен",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Компас",
	"E": "{value} И",
	"Elevation": "Височина",
	"FT": "{value}{spacing}фута",
	"Latitude": "Ширина",
	"Loading": "Зареждане на навигация",
	"Longitude": "Дължина",
	"M": "{value}{spacing}м",
	"N": "{value} С",
	"NAVAddressSearch": "Навигация",
	"NAVAvoidances": "Навигация",
	"NAVCitySearch": "Навигация",
	"NAVCoordinate": "Навигация",
	"NAVDragMode": "Навигация",
	"NAVGasPrice": "Навигация",
	"NAVHistory": "Навигация",
	"NAVItemList": "Навигация",
	"NAVMap": "Навигация",
	"NAVMecca": "Навигация",
	"NAVModifyPoint": "Навигация",
	"NAVNavigationInfo": "Навигация",
	"NAVNewDestination": "Навигация",
	"NAVPOI": "Навигация",
	"NAVPhoneZipSearch": "Навигация",
	"NAVPointOnMap": "Навигация",
	"NAVQuickSearch": "Навигация",
	"NAVResults": "Навигация",
	"NAVRoute": "Навигация",
	"NAVSettings": "Навигация",
	"NAVSimulation": "Навигация",
	"NAVSortingOptions": "Навигация",
	"NAVTraffic": "Навигация",
	"NAVTurnByTurn": "Навигация",
	"NAVVoicePrompts": "Навигация",
	"NAVWeather": "Навигация",
	"NoNavigation": "Вашият автомобил Mazda няма навигационна система. Вземете интегр. навиг. с-ма от дилър на Mazda.",
	"S": "{value} Ю",
	"SDCardInvalid": "Невалидна SD карта",
	"SDCradInserted": "SD картата е поставена",
	"SDCradRemoved": "SD картата е извадена",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} З",
	"Y": "{value}{spacing}ярда",
	"YourLocation": "Вашето местопл.",
	"emnavi": "Навигация",
	"km": "{value}{spacing}км",
	"mi": "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "bg_BG");