var Localization_emnaviAppDict_he_IL = {
	//"stringId" : "localString"
	"AddressNotFound": "כתובת לא נמצאה",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "מצפן",
	"E": "{value} מזרח",
	"Elevation": "רום",
	"FT": "{value}{spacing}רגל",
	"Latitude": "קו רוחב",
	"Loading": "טוען ניווט",
	"Longitude": "קו אורך",
	"M": "{value}{spacing}מטר",
	"N": "{value} צפון",
	"NAVAddressSearch": "ניווט",
	"NAVAvoidances": "ניווט",
	"NAVCitySearch": "ניווט",
	"NAVCoordinate": "ניווט",
	"NAVDragMode": "ניווט",
	"NAVGasPrice": "ניווט",
	"NAVHistory": "ניווט",
	"NAVItemList": "ניווט",
	"NAVMap": "ניווט",
	"NAVMecca": "ניווט",
	"NAVModifyPoint": "ניווט",
	"NAVNavigationInfo": "ניווט",
	"NAVNewDestination": "ניווט",
	"NAVPOI": "ניווט",
	"NAVPhoneZipSearch": "ניווט",
	"NAVPointOnMap": "ניווט",
	"NAVQuickSearch": "ניווט",
	"NAVResults": "ניווט",
	"NAVRoute": "ניווט",
	"NAVSettings": "ניווט",
	"NAVSimulation": "ניווט",
	"NAVSortingOptions": "ניווט",
	"NAVTraffic": "ניווט",
	"NAVTurnByTurn": "ניווט",
	"NAVVoicePrompts": "ניווט",
	"NAVWeather": "ניווט",
	"NoNavigation": "Mazda שלך לא מצויידת במערכת ניווט. למרות זאת, מערכת ניווט משולבת זמינה דרך סוכן Mazda שלך כאביזר Mazda מקורי.",
	"S": "{value} דרום",
	"SDCardInvalid": "כרטיס SD אינו תקף",
	"SDCradInserted": "הוכנס כרטיס SD",
	"SDCradRemoved": "הוסר כרטיס SD",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} מערב",
	"Y": "{value}{spacing}יארד",
	"YourLocation": "מיקומך",
	"emnavi": "ניווט",
	"km": "{value}{spacing}ק\"מ",
	"mi": "{value}{spacing}מייל",
};

framework.registerAppDictLoaded("emnavi", "he_IL");