var Localization_emnaviAppDict_cs_CS = {
	//"stringId" : "localString"
	"AddressNotFound": "Adresa nenalezena",
	"AtSpeedCautionText": "JAPAN ONLY",
	"Compass": "Kompas",
	"E": "{value} V",
	"Elevation": "Nadmoř. Výška",
	"FT": "{value}{spacing}ft",
	"Latitude": "Zem. šířka",
	"Loading": "Nahrávání navigace",
	"Longitude": "Zeměp. délka",
	"M": "{value}{spacing}m",
	"N": "{value} S",
	"NAVAddressSearch": "Navigace",
	"NAVAvoidances": "Navigace",
	"NAVCitySearch": "Navigace",
	"NAVCoordinate": "Navigace",
	"NAVDragMode": "Navigace",
	"NAVGasPrice": "Navigace",
	"NAVHistory": "Navigace",
	"NAVItemList": "Navigace",
	"NAVMap": "Navigace",
	"NAVMecca": "Navigace",
	"NAVModifyPoint": "Navigace",
	"NAVNavigationInfo": "Navigace",
	"NAVNewDestination": "Navigace",
	"NAVPOI": "Navigace",
	"NAVPhoneZipSearch": "Navigace",
	"NAVPointOnMap": "Navigace",
	"NAVQuickSearch": "Navigace",
	"NAVResults": "Navigace",
	"NAVRoute": "Navigace",
	"NAVSettings": "Navigace",
	"NAVSimulation": "Navigace",
	"NAVSortingOptions": "Navigace",
	"NAVTraffic": "Navigace",
	"NAVTurnByTurn": "Navigace",
	"NAVVoicePrompts": "Navigace",
	"NAVWeather": "Navigace",
	"NoNavigation": "Tato Mazda není vybaveno navigaci. Navigační systém lze dokoupit u kteréhokoli  dealera Mazda jako dodatečné příslušenství.",
	"S": "{value} J",
	"SDCardInvalid": "Chybná karta SD",
	"SDCradInserted": "Karta SD vložena",
	"SDCradRemoved": "Karta SD odebrána",
	"VrHelp_Cockpit_Help2_Left1": "New Destination",
	"VrHelp_Cockpit_Help2_Left2": "Take Me Home",
	"VrHelp_Cockpit_Help2_Left3": "Navigate to an Address",
	"VrHelp_Cockpit_Help2_Left4": "Navigate to Recent Destination",
	"VrHelp_Cockpit_Help2_Left5": "Clear Route",
	"VrHelp_Cockpit_Help2_Right1": "Where Am I",
	"VrHelp_Cockpit_Help2_Right2": "Route Summary",
	"VrHelp_Cockpit_Help2_Right3": "Repeat Instruction",
	"VrHelp_Cockpit_Help2_Right4": "Add Current Location to Favorites",
	"VrHelp_Cockpit_Help2_Right5": "Add Waypoint (category)",
	"W": "{value} Z",
	"Y": "{value}{spacing}yd",
	"YourLocation": "Vaše poloha",
	"emnavi": "Navigace",
	"km": "{value}{spacing}km",
	"mi": "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "cs_CS");