var Localization_satradioAppDict_pt_PT = {
	//"stringId" : "localString"
	"AllChannels": "Todos os Canais",
	"Category": "Categoria: {cachedSelectedGenre}",
	"CategoryAllChannels": "Categoria: Todos os Canais",
	"CategoryList": "Lista de Categorias",
	"ChannelList": "Lista de Canais",
	"ChannelsUnlockedForSession": "Canais Desbloqueados para a Sessão",
	"CheckXMAntenna": "Verificar Antena XM",
	"CheckXMTuner": "Verificar Sintonizador XM",
	"EditPINCode": "Editar Código PIN",
	"EnterFactoryPINToReset": "PIN de Fábr. p/ Repor",
	"EnterNewPIN": "Introd. Novo PIN",
	"EnterPIN": "Introduzir PIN",
	"InitializePINCode": "Inicializar Código PIN",
	"IsThisCorrect": "Está correcto?",
	"LoadingXM": "A Carregar XM",
	"LockCurrentChannel": "Bloquear Canal Actual",
	"NoXMSignal": "Nenhum Sinal XM",
	"PINSet": "Definição do PIN",
	"ParentalLock": "Limitação de Acesso",
	"PleaseTryAgain": "Tente Novamente",
	"RadioID": "ID da Rádio: {radioId}",
	"ResetPINCode": "Repor Código PIN",
	"SelectLockButton": "Selecc. o Botão Bloquear para desbl. os can. sessão",
	"SessionLock": "Bloqueio da Sessão",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Lista de Canais",
	"VrHelp_NowPlaying_Help_Left3": "Canal (número)",
	"VrHelp_NowPlaying_Help_Left4": "Favoritos",
	"VrHelp_NowPlaying_Help_Left5": "Limite de Acesso",
	"VrHelp_NowPlaying_Help_Right1": "Procurar",
	"VrHelp_NowPlaying_Help_Right2": "Anterior",
	"VrHelp_NowPlaying_Help_Right3": "Reproduzir (nome do canal)",
	"VrHelp_NowPlaying_Help_Right4": "Seguinte",
	"VrHelp_NowPlaying_Help_Right5": "Definições de Som",
	"VrHelp_ParentalLock_Help_1_Left1": "Bloquear Canal Actual",
	"VrHelp_ParentalLock_Help_1_Left2": "Desbloquear Canal Actual",
	"VrHelp_ParentalLock_Help_1_Left3": "Bloqueio da sessão activado",
	"VrHelp_ParentalLock_Help_1_Left4": "Bloqueio da sessão desactivado",
	"VrHelp_ParentalLock_Help_1_Left5": "Inicializar Código PIN",
	"VrHelp_ParentalLock_Help_1_Right1": "Repor Código PIN",
	"VrHelp_ParentalLock_Help_2_Left1": "Bloquear Canal Actual",
	"VrHelp_ParentalLock_Help_2_Left2": "Desbloquear Canal Actual",
	"VrHelp_ParentalLock_Help_2_Left3": "Bloqueio da sessão activado",
	"VrHelp_ParentalLock_Help_2_Left4": "Bloqueio da sessão desactivado",
	"VrHelp_ParentalLock_Help_2_Left5": "Editar Código PIN",
	"VrHelp_ParentalLock_Help_2_Right1": "Repor Código PIN",
	"VrHelp_PinEntryNew_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Limpar",
	"VrHelp_PinEntryReset_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Limpar",
	"VrHelp_PinEntryUnlock_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Limpar",
	"VrHelp_PinEntryUnlock_Help_Left4": "Inicializar Código PIN",
	"WrongPIN": "PIN Incorrecto",
	"XM": "XM",
	"XMChannelNotAuthorized": "Canal XM Não Autorizado",
	"XMChannelNotAvailable": "Canal XM Não Disponível",
	"XMChannelOffAir": "Canal XM Fora de Emissão",
};

framework.registerAppDictLoaded("satradio", "pt_PT");