var Localization_satradioAppDict_th_TH = {
	//"stringId" : "localString"
	"AllChannels": "ช่องทั้งหมด",
	"Category": "หมวดหมู่ : {cachedSelectedGenre}",
	"CategoryAllChannels": "หมวดหมู่ : ช่องทั้งหมด",
	"CategoryList": "รายการหมวดหมู่",
	"ChannelList": "รายการช่อง",
	"ChannelsUnlockedForSession": "ปลดล็อกช่องสำหรับเซสชันแล้ว",
	"CheckXMAntenna": "ตรวจสอบเสาอากาศ XM ",
	"CheckXMTuner": "ตรวจสอบตัวปรับสัญญาณ XM",
	"EditPINCode": "แก้ไขรหัส PIN",
	"EnterFactoryPINToReset": "ป้อน PIN งานเพื่อรีเซ็ต",
	"EnterNewPIN": "ป้อนรหัส PIN ใหม่",
	"EnterPIN": "ป้อนรหัส PIN",
	"InitializePINCode": "เริ่มการทำงานของรหัส PIN",
	"IsThisCorrect": "ถูกต้องหรือไม่",
	"LoadingXM": "การโหลด XM",
	"LockCurrentChannel": "ล็อกช่องปัจจุบัน",
	"NoXMSignal": "ไม่มีสัญญาณ XM ",
	"PINSet": "ตั้งค่า PIN",
	"ParentalLock": "การล็อกโดยผู้ปกครอง",
	"PleaseTryAgain": "โปรดลองใหม่อีกครั้ง",
	"RadioID": "ID วิทยุ : {radioId}",
	"ResetPINCode": "รีเซ็ตรหัส PIN",
	"SelectLockButton": "เลือกปุ่มล็อกเพื่อปลดล็อกช่องสำหรับเซสชัน",
	"SessionLock": "ล็อกเซสชัน",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Channel List",
	"VrHelp_NowPlaying_Help_Left3": "Channel (number)",
	"VrHelp_NowPlaying_Help_Left4": "Favorites",
	"VrHelp_NowPlaying_Help_Left5": "Parental Lock",
	"VrHelp_NowPlaying_Help_Right1": "Scan",
	"VrHelp_NowPlaying_Help_Right2": "Previous",
	"VrHelp_NowPlaying_Help_Right3": "Play (channel name)",
	"VrHelp_NowPlaying_Help_Right4": "Next",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_ParentalLock_Help_1_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_1_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialize PIN Code",
	"VrHelp_ParentalLock_Help_1_Right1": "Reset PIN Code",
	"VrHelp_ParentalLock_Help_2_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_2_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_2_Left5": "Edit PIN Code",
	"VrHelp_ParentalLock_Help_2_Right1": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialize PIN Code",
	"WrongPIN": "PIN ไม่ถูกต้อง",
	"XM": "XM",
	"XMChannelNotAuthorized": "ไม่อนุญาตให้ใช้ช่องสัญญาณ XM",
	"XMChannelNotAvailable": "ช่องสัญญาณ XM ไม่พร้อมใช้งาน",
	"XMChannelOffAir": "ช่องสัญญาณ XM ไม่ออกอากาศ",
};

framework.registerAppDictLoaded("satradio", "th_TH");