var Localization_satradioAppDict_pt_BR = {
	//"stringId" : "localString"
	"AllChannels": "Todos os canais",
	"Category": "Categoria: {cachedSelectedGenre}",
	"CategoryAllChannels": "Categoria: Todos os canais",
	"CategoryList": "Lista de categorias",
	"ChannelList": "Lista de canais",
	"ChannelsUnlockedForSession": "Canais desbloqueados para sessão",
	"CheckXMAntenna": "Verifique a antena XM",
	"CheckXMTuner": "Verifique o sintonizador XM",
	"EditPINCode": "Editar senha",
	"EnterFactoryPINToReset": "Digitar senha de fáb.",
	"EnterNewPIN": "Digite a nova senha",
	"EnterPIN": "Digite a senha",
	"InitializePINCode": "Inicializar senha",
	"IsThisCorrect": "Isto está correto?",
	"LoadingXM": "Carregando XM",
	"LockCurrentChannel": "Bloquear canal atual",
	"NoXMSignal": "Sem sinal XM",
	"PINSet": "Senha definida",
	"ParentalLock": "Bloqueio dos pais",
	"PleaseTryAgain": "Tente novam.",
	"RadioID": "ID da Rádio: {radioId}",
	"ResetPINCode": "Redefinir senha",
	"SelectLockButton": "Selecione o botão bloquear para desbloquear canais",
	"SessionLock": "Bloqueio de sessão",
	"VrHelp_NowPlaying_Help_Left1": "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2": "Lista de canais",
	"VrHelp_NowPlaying_Help_Left3": "Canal (número)",
	"VrHelp_NowPlaying_Help_Left4": "Favoritos",
	"VrHelp_NowPlaying_Help_Left5": "Limite de acesso",
	"VrHelp_NowPlaying_Help_Right1": "Procurar",
	"VrHelp_NowPlaying_Help_Right2": "Anterior",
	"VrHelp_NowPlaying_Help_Right3": "Reproduzir (nome do canal)",
	"VrHelp_NowPlaying_Help_Right4": "Seguinte",
	"VrHelp_NowPlaying_Help_Right5": "Definições de som",
	"VrHelp_ParentalLock_Help_1_Left1": "Bloquear canal atual",
	"VrHelp_ParentalLock_Help_1_Left2": "Desbloquear canal atual",
	"VrHelp_ParentalLock_Help_1_Left3": "Bloqueio de sessão ativado",
	"VrHelp_ParentalLock_Help_1_Left4": "Bloqueio de sessão desativado",
	"VrHelp_ParentalLock_Help_1_Left5": "Inicializar código PIN",
	"VrHelp_ParentalLock_Help_1_Right1": "Repor código PIN",
	"VrHelp_ParentalLock_Help_2_Left1": "Bloquear canal atual",
	"VrHelp_ParentalLock_Help_2_Left2": "Desbloquear canal atual",
	"VrHelp_ParentalLock_Help_2_Left3": "Bloqueio de sessão ativado",
	"VrHelp_ParentalLock_Help_2_Left4": "Bloqueio de sessão desativado",
	"VrHelp_ParentalLock_Help_2_Left5": "Editar código PIN",
	"VrHelp_ParentalLock_Help_2_Right1": "Repor código PIN",
	"VrHelp_PinEntryNew_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Limpar",
	"VrHelp_PinEntryReset_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Limpar",
	"VrHelp_PinEntryUnlock_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Limpar",
	"VrHelp_PinEntryUnlock_Help_Left4": "Inicializar código PIN",
	"WrongPIN": "Senha incorreta",
	"XM": "XM",
	"XMChannelNotAuthorized": "Canal XM não autorizado",
	"XMChannelNotAvailable": "Canal XM não disponível",
	"XMChannelOffAir": "Canal XM fora do ar",
};

framework.registerAppDictLoaded("satradio", "pt_BR");