var Localization_satradioAppDict_nl_NL = {
	//"stringId" : "localString"
	"AllChannels": "Alle kanalen",
	"Category": "Categorie: {cachedSelectedGenre}",
	"CategoryAllChannels": "Categorie: Alle kanalen",
	"CategoryList": "Categorielijst",
	"ChannelList": "Lijst met kanalen",
	"ChannelsUnlockedForSession": "Kanalen vrijgegeven voor sessie",
	"CheckXMAntenna": "Check XM-antenne",
	"CheckXMTuner": "Check XM-tuner",
	"EditPINCode": "Pincode bewerken",
	"EnterFactoryPINToReset": "PIN inv.voor reset",
	"EnterNewPIN": "Voor nieuwe PIN in",
	"EnterPIN": "Pincode invoeren",
	"InitializePINCode": "Pincode initialiseren",
	"IsThisCorrect": "Is dit juist?",
	"LoadingXM": "XM laden",
	"LockCurrentChannel": "Huidig kanaal sluiten",
	"NoXMSignal": "Geen XM-signaal",
	"PINSet": "PIN ingesteld",
	"ParentalLock": "Kinderslot",
	"PleaseTryAgain": "Probeer het opnieuw",
	"RadioID": "radio ID: {radioId}",
	"ResetPINCode": "Reset PIN",
	"SelectLockButton": "Select. “Lock” om de kan. voor de sessie te ontgren.",
	"SessionLock": "Sessie-lock",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Lijst met zenders",
	"VrHelp_NowPlaying_Help_Left3": "Kanaal(nummer)",
	"VrHelp_NowPlaying_Help_Left4": "Favorieten",
	"VrHelp_NowPlaying_Help_Left5": "Volgende",
	"VrHelp_NowPlaying_Help_Right1": "Scannen",
	"VrHelp_NowPlaying_Help_Right2": "Vorige",
	"VrHelp_NowPlaying_Help_Right3": " Afspelen (kanaalnaam)",
	"VrHelp_NowPlaying_Help_Right4": "Volgende",
	"VrHelp_NowPlaying_Help_Right5": "Geluidsinstellingen",
	"VrHelp_ParentalLock_Help_1_Left1": "Huidige Zender Vergrendelen",
	"VrHelp_ParentalLock_Help_1_Left2": "Huidige Zender Ontgrendelen",
	"VrHelp_ParentalLock_Help_1_Left3": "Sessievergrendeling aan",
	"VrHelp_ParentalLock_Help_1_Left4": "Sessievergrendeling uit",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialiseren van de PIN-Code",
	"VrHelp_ParentalLock_Help_1_Right1": "PIN-Code Opnieuw Instellen",
	"VrHelp_ParentalLock_Help_2_Left1": "Huidige Zender Vergrendelen",
	"VrHelp_ParentalLock_Help_2_Left2": "Huidige Zender Ontgrendelen",
	"VrHelp_ParentalLock_Help_2_Left3": "Sessievergrendeling aan",
	"VrHelp_ParentalLock_Help_2_Left4": "Sessievergrendeling uit",
	"VrHelp_ParentalLock_Help_2_Left5": "PIN-Code Bewerken",
	"VrHelp_ParentalLock_Help_2_Right1": "PIN-Code Opnieuw Instellen",
	"VrHelp_PinEntryNew_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Duidelijk",
	"VrHelp_PinEntryReset_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Duidelijk",
	"VrHelp_PinEntryUnlock_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Duidelijk",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialiseren van de PIN-Code",
	"WrongPIN": "Onjuiste PIN",
	"XM": "XM",
	"XMChannelNotAuthorized": "XM-kanaal niet geautoriseerd",
	"XMChannelNotAvailable": "XM-kanaal niet beschikbaar",
	"XMChannelOffAir": "XM-kanaal uit de lucht",
};

framework.registerAppDictLoaded("satradio", "nl_NL");