var Localization_satradioAppDict_mn_TW = {
	//"stringId" : "localString"
	"AllChannels": "所有頻道",
	"Category": "類別 :  {cachedSelectedGenre}",
	"CategoryAllChannels": "類別 :  所有頻道",
	"CategoryList": "類別清單",
	"ChannelList": "頻道清單",
	"ChannelsUnlockedForSession": "已針對工作階段解除頻道鎖定",
	"CheckXMAntenna": "請檢查 XM 天線",
	"CheckXMTuner": "請檢查 XM 調諧器",
	"EditPINCode": "編輯密碼",
	"EnterFactoryPINToReset": "請輸入原廠密碼",
	"EnterNewPIN": "請輸入新密碼",
	"EnterPIN": "請輸入密碼",
	"InitializePINCode": "初始化 PIN 碼",
	"IsThisCorrect": "這正確嗎?",
	"LoadingXM": "正在載入 XM",
	"LockCurrentChannel": "鎖定目前頻道",
	"NoXMSignal": "無 XM 信號",
	"PINSet": "密碼已設定",
	"ParentalLock": "分級鎖",
	"PleaseTryAgain": "請重試",
	"RadioID": "廣播電台 ID :  {radioId}",
	"ResetPINCode": "重設密碼",
	"SelectLockButton": "請選取下面的鎖定按鍵以解除頻道鎖定。",
	"SessionLock": "工作階段鎖",
	"VrHelp_NowPlaying_Help_Left1": "變更來源",
	"VrHelp_NowPlaying_Help_Left2": "我的最愛",
	"VrHelp_NowPlaying_Help_Left3": "頻道清單",
	"VrHelp_NowPlaying_Help_Left4": "掃描",
	"VrHelp_NowPlaying_Help_Left5": "下一曲",
	"VrHelp_NowPlaying_Help_Right1": "上一個",
	"VrHelp_NowPlaying_Help_Right2": "家長鎖定",
	"VrHelp_NowPlaying_Help_Right3": "聲音設定",
	"VrHelp_NowPlaying_Help_Right4": "頻道（編號）",
	"VrHelp_NowPlaying_Help_Right5": "播放（頻道名稱）",
	"VrHelp_ParentalLock_Help_1_Left1": "鎖定目前頻道",
	"VrHelp_ParentalLock_Help_1_Left2": "解鎖目前頻道",
	"VrHelp_ParentalLock_Help_1_Left3": "打開會話鎖",
	"VrHelp_ParentalLock_Help_1_Left4": "關閉會話鎖",
	"VrHelp_ParentalLock_Help_1_Left5": "起始設定 PIN 碼",
	"VrHelp_ParentalLock_Help_1_Right1": "重置PIN碼",
	"VrHelp_ParentalLock_Help_2_Left1": "鎖定目前頻道",
	"VrHelp_ParentalLock_Help_2_Left2": "解鎖目前頻道",
	"VrHelp_ParentalLock_Help_2_Left3": "打開會話鎖",
	"VrHelp_ParentalLock_Help_2_Left4": "關閉會話鎖",
	"VrHelp_ParentalLock_Help_2_Left5": "編輯 PIN 碼",
	"VrHelp_ParentalLock_Help_2_Right1": "重置PIN碼",
	"VrHelp_PinEntryNew_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryNew_Help_Left2": "確定",
	"VrHelp_PinEntryNew_Help_Left3": "清除",
	"VrHelp_PinEntryReset_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryReset_Help_Left2": "確定",
	"VrHelp_PinEntryReset_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryUnlock_Help_Left2": "確定",
	"VrHelp_PinEntryUnlock_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left4": "起始設定 PIN 碼",
	"WrongPIN": "密碼錯誤",
	"XM": "XM",
	"XMChannelNotAuthorized": "XM 頻道未獲授權",
	"XMChannelNotAvailable": "XM 頻道無法使用",
	"XMChannelOffAir": "XM 頻道已停播",
};

framework.registerAppDictLoaded("satradio", "mn_TW");