var Localization_satradioAppDict_id_ID = {
	//"stringId" : "localString"
	"AllChannels": "Semua Saluran",
	"Category": "Kategori : {cachedSelectedGenre}",
	"CategoryAllChannels": "Kategori : Semua Saluran",
	"CategoryList": "Daftar Kategori",
	"ChannelList": "Daftar Saluran",
	"ChannelsUnlockedForSession": "Saluran Terbuka Untuk Sesi",
	"CheckXMAntenna": "Periksa Antena XM",
	"CheckXMTuner": "Periksa Penala XM",
	"EditPINCode": "Edit Kode PIN",
	"EnterFactoryPINToReset": "PIN Pabrik u/ Reset",
	"EnterNewPIN": "Tulis PIN Baru",
	"EnterPIN": "Masukkan PIN",
	"InitializePINCode": "Tetapkan Kode PIN",
	"IsThisCorrect": "Apakah ini benar?",
	"LoadingXM": "Memuat XM",
	"LockCurrentChannel": "Kunci Saluran ini",
	"NoXMSignal": "Tidak Ada Sinyal XM",
	"PINSet": "PIN Disetel",
	"ParentalLock": "Kunci oleh Orang Tua",
	"PleaseTryAgain": "Silakan Coba Lagi",
	"RadioID": "ID Radio : {radioId}",
	"ResetPINCode": "Setelan Ulang Kode PIN",
	"SelectLockButton": "Pilih Tombol Kunci untuk membuka kunci saluran sesi",
	"SessionLock": "Penguncian Sesi",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Channel List",
	"VrHelp_NowPlaying_Help_Left3": "Channel (number)",
	"VrHelp_NowPlaying_Help_Left4": "Favorites",
	"VrHelp_NowPlaying_Help_Left5": "Parental Lock",
	"VrHelp_NowPlaying_Help_Right1": "Scan",
	"VrHelp_NowPlaying_Help_Right2": "Previous",
	"VrHelp_NowPlaying_Help_Right3": "Play (channel name)",
	"VrHelp_NowPlaying_Help_Right4": "Next",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_ParentalLock_Help_1_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_1_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialize PIN Code",
	"VrHelp_ParentalLock_Help_1_Right1": "Reset PIN Code",
	"VrHelp_ParentalLock_Help_2_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_2_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_2_Left5": "Edit PIN Code",
	"VrHelp_ParentalLock_Help_2_Right1": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialize PIN Code",
	"WrongPIN": "PIN Salah",
	"XM": "XM",
	"XMChannelNotAuthorized": "Saluran XM Tidak Sah",
	"XMChannelNotAvailable": "Saluran XM Tidak Tersedia",
	"XMChannelOffAir": "Saluran XM Tidak Mengudara",
};

framework.registerAppDictLoaded("satradio", "id_ID");