var Localization_satradioAppDict_sk_SK = {
	//"stringId" : "localString"
	"AllChannels": "Všetky kanály",
	"Category": "Kategória: {cachedSelectedGenre}",
	"CategoryAllChannels": "Kategória: Všetky kanály",
	"CategoryList": "Zoznam kategórií",
	"ChannelList": "Zoznam kanálov",
	"ChannelsUnlockedForSession": "Kanály odblokované pre reláciu",
	"CheckXMAntenna": "Skontrolujte XM anténu",
	"CheckXMTuner": "Skontrolujte XM tuner",
	"EditPINCode": "Upraviť PIN kód",
	"EnterFactoryPINToReset": "Resetovanie - PIN",
	"EnterNewPIN": "Zadať nový PIN",
	"EnterPIN": "Zadať PIN",
	"InitializePINCode": "Inicializovať PIN kód",
	"IsThisCorrect": "Je to správne?",
	"LoadingXM": "Zavádzanie XM",
	"LockCurrentChannel": "Zamknúť aktu. kanál",
	"NoXMSignal": "Žiaden XM signál",
	"PINSet": "Nastavenie PIN",
	"ParentalLock": "Rodičovský zámok",
	"PleaseTryAgain": "Skúste znovu",
	"RadioID": "ID rádia: {radioId}",
	"ResetPINCode": "Resetovať PIN kód",
	"SelectLockButton": "Vyberte tlačidlo zámku a odom. kanále pre reláciu",
	"SessionLock": "Zámok relácie",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Channel List",
	"VrHelp_NowPlaying_Help_Left3": "Channel (number)",
	"VrHelp_NowPlaying_Help_Left4": "Favorites",
	"VrHelp_NowPlaying_Help_Left5": "Parental Lock",
	"VrHelp_NowPlaying_Help_Right1": "Scan",
	"VrHelp_NowPlaying_Help_Right2": "Previous",
	"VrHelp_NowPlaying_Help_Right3": "Play (channel name)",
	"VrHelp_NowPlaying_Help_Right4": "Next",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_ParentalLock_Help_1_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_1_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialize PIN Code",
	"VrHelp_ParentalLock_Help_1_Right1": "Reset PIN Code",
	"VrHelp_ParentalLock_Help_2_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_2_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_2_Left5": "Edit PIN Code",
	"VrHelp_ParentalLock_Help_2_Right1": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialize PIN Code",
	"WrongPIN": "Nesprávny PIN kód",
	"XM": "XM",
	"XMChannelNotAuthorized": "XM kanál nie je autorizovaný",
	"XMChannelNotAvailable": "XM kanál nie je k dispozícii",
	"XMChannelOffAir": "XM kanál nevysiela",
};

framework.registerAppDictLoaded("satradio", "sk_SK");