var Localization_satradioAppDict_cn_HK = {
	//"stringId" : "localString"
	"AllChannels": "全部頻道",
	"Category": "分類： {cachedSelectedGenre}",
	"CategoryAllChannels": "分類： 全部頻道",
	"CategoryList": "分類清單",
	"ChannelList": "頻道清單",
	"ChannelsUnlockedForSession": "工作階段頻道已解鎖",
	"CheckXMAntenna": "檢查 XM 天線",
	"CheckXMTuner": "檢查 XM 調諧器",
	"EditPINCode": "編輯 PIN 碼",
	"EnterFactoryPINToReset": "輸入出廠 PIN 碼",
	"EnterNewPIN": "輸入新的 PIN 碼",
	"EnterPIN": "輸入 PIN 碼",
	"InitializePINCode": "初始化 PIN 碼",
	"IsThisCorrect": "這是否正確？",
	"LoadingXM": "XM 載入中",
	"LockCurrentChannel": "鎖定當前頻道",
	"NoXMSignal": "無 XM 訊號",
	"PINSet": "PIN 碼設定",
	"ParentalLock": "家長鎖碼",
	"PleaseTryAgain": "請重試",
	"RadioID": "無線電 ID： {radioId}",
	"ResetPINCode": "重設 PIN 碼",
	"SelectLockButton": "選取下方的鎖定按鈕，對頻道進行解鎖。",
	"SessionLock": "工作階段鎖定",
	"VrHelp_NowPlaying_Help_Left1": "變更來源",
	"VrHelp_NowPlaying_Help_Left2": "我的最愛",
	"VrHelp_NowPlaying_Help_Left3": "頻道清單",
	"VrHelp_NowPlaying_Help_Left4": "掃描",
	"VrHelp_NowPlaying_Help_Left5": "下一曲",
	"VrHelp_NowPlaying_Help_Right1": "上一個",
	"VrHelp_NowPlaying_Help_Right2": "家長鎖定",
	"VrHelp_NowPlaying_Help_Right3": "聲音設定",
	"VrHelp_NowPlaying_Help_Right4": "頻道（編號）",
	"VrHelp_NowPlaying_Help_Right5": "播放（頻道名稱）",
	"VrHelp_ParentalLock_Help_1_Left1": "鎖定目前頻道",
	"VrHelp_ParentalLock_Help_1_Left2": "解鎖目前頻道",
	"VrHelp_ParentalLock_Help_1_Left3": "打開會話鎖",
	"VrHelp_ParentalLock_Help_1_Left4": "關閉會話鎖",
	"VrHelp_ParentalLock_Help_1_Left5": "起始設定 PIN 碼",
	"VrHelp_ParentalLock_Help_1_Right1": "重置PIN碼",
	"VrHelp_ParentalLock_Help_2_Left1": "鎖定目前頻道",
	"VrHelp_ParentalLock_Help_2_Left2": "解鎖目前頻道",
	"VrHelp_ParentalLock_Help_2_Left3": "打開會話鎖",
	"VrHelp_ParentalLock_Help_2_Left4": "關閉會話鎖",
	"VrHelp_ParentalLock_Help_2_Left5": "編輯 PIN 碼",
	"VrHelp_ParentalLock_Help_2_Right1": "重置PIN碼",
	"VrHelp_PinEntryNew_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryNew_Help_Left2": "確定",
	"VrHelp_PinEntryNew_Help_Left3": "清除",
	"VrHelp_PinEntryReset_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryReset_Help_Left2": "確定",
	"VrHelp_PinEntryReset_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryUnlock_Help_Left2": "確定",
	"VrHelp_PinEntryUnlock_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left4": "起始設定 PIN 碼",
	"WrongPIN": "PIN 碼錯誤",
	"XM": "XM",
	"XMChannelNotAuthorized": "XM 頻道未授權",
	"XMChannelNotAvailable": "XM 頻道不可用",
	"XMChannelOffAir": "XM 頻道消失",
};

framework.registerAppDictLoaded("satradio", "cn_HK");