var Localization_satradioAppDict_he_IL = {
	//"stringId" : "localString"
	"AllChannels": "כל הערוצים",
	"Category": "קטגוריה:  {cachedSelectedGenre}",
	"CategoryAllChannels": "קטגוריה : כל הערוצים",
	"CategoryList": "רשימת קטגוריות",
	"ChannelList": "רשימת ערוצים",
	"ChannelsUnlockedForSession": "נעילת ערוצים שוחררו לסבב",
	"CheckXMAntenna": "בדוק אנטנת XM",
	"CheckXMTuner": "בדוק XM Tuner",
	"EditPINCode": "ערוך קוד PIN",
	"EnterFactoryPINToReset": "הזן PIN יצרן כדי לאפס",
	"EnterNewPIN": "הזן PIN חדש",
	"EnterPIN": "הזן PIN",
	"InitializePINCode": "אתחל קוד PIN",
	"IsThisCorrect": "האם הוא נכון?",
	"LoadingXM": "טוען XM",
	"LockCurrentChannel": "נעל ערוץ נוכחי",
	"NoXMSignal": "אין אות XM",
	"PINSet": "קבע PIN",
	"ParentalLock": "בקרת הורים",
	"PleaseTryAgain": "נסה שוב",
	"RadioID": "מספר זיהוי רדיו: {radioId}",
	"ResetPINCode": "אתחל קוד PIN",
	"SelectLockButton": "בחר לחצן נעילה כדי לשחרר את הערוצים לסבב",
	"SessionLock": "נעילת סבב",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Channel List",
	"VrHelp_NowPlaying_Help_Left3": "Channel (number)",
	"VrHelp_NowPlaying_Help_Left4": "Favorites",
	"VrHelp_NowPlaying_Help_Left5": "Parental Lock",
	"VrHelp_NowPlaying_Help_Right1": "Scan",
	"VrHelp_NowPlaying_Help_Right2": "Previous",
	"VrHelp_NowPlaying_Help_Right3": "Play (channel name)",
	"VrHelp_NowPlaying_Help_Right4": "Next",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_ParentalLock_Help_1_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_1_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialize PIN Code",
	"VrHelp_ParentalLock_Help_1_Right1": "Reset PIN Code",
	"VrHelp_ParentalLock_Help_2_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_2_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_2_Left5": "Edit PIN Code",
	"VrHelp_ParentalLock_Help_2_Right1": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialize PIN Code",
	"WrongPIN": "PIN שגוי",
	"XM": "XM",
	"XMChannelNotAuthorized": "ערוץ XM אינו מורשה",
	"XMChannelNotAvailable": "ערוץ XM אינו זמין",
	"XMChannelOffAir": "ערוץ XM אינו מחובר",
};

framework.registerAppDictLoaded("satradio", "he_IL");