var Localization_satradioAppDict_et_EE = {
	//"stringId" : "localString"
	"AllChannels": "Kõik kanalid",
	"Category": "Kategooria: {cachedSelectedGenre}",
	"CategoryAllChannels": "Kategooria: Kõik kanalid",
	"CategoryList": "Kategooriate loend",
	"ChannelList": "Kanalite loend",
	"ChannelsUnlockedForSession": "Kanalid on seansi ajaks lukust avatud",
	"CheckXMAntenna": "Kontrollige XM-antenni",
	"CheckXMTuner": "Kontrollige XM-tuunerit",
	"EditPINCode": "Muuda PIN-koodi",
	"EnterFactoryPINToReset": "Sisest. vaike PIN",
	"EnterNewPIN": "Sisestage uus PIN",
	"EnterPIN": "Sisestage PIN",
	"InitializePINCode": "Lähtesta PIN-kood",
	"IsThisCorrect": "Kas see on õige?",
	"LoadingXM": "XM-i laadimine",
	"LockCurrentChannel": "Luk. praegune kanal",
	"NoXMSignal": "XM-signaal puudub",
	"PINSet": "PIN-koodi seadistamine",
	"ParentalLock": "Lapselukk",
	"PleaseTryAgain": "Palun proovige uuesti.",
	"RadioID": "Raadio ID:  {radioId}",
	"ResetPINCode": "Lähtesta PIN-kood",
	"SelectLockButton": "Valige lukust.seansiks kanal. lukust vabastamiseks",
	"SessionLock": "Seansi lukustus",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Channel List",
	"VrHelp_NowPlaying_Help_Left3": "Channel (number)",
	"VrHelp_NowPlaying_Help_Left4": "Favorites",
	"VrHelp_NowPlaying_Help_Left5": "Parental Lock",
	"VrHelp_NowPlaying_Help_Right1": "Scan",
	"VrHelp_NowPlaying_Help_Right2": "Previous",
	"VrHelp_NowPlaying_Help_Right3": "Play (channel name)",
	"VrHelp_NowPlaying_Help_Right4": "Next",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_ParentalLock_Help_1_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_1_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_1_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_1_Left5": "Initialize PIN Code",
	"VrHelp_ParentalLock_Help_1_Right1": "Reset PIN Code",
	"VrHelp_ParentalLock_Help_2_Left1": "Lock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left2": "Unlock Current Channel",
	"VrHelp_ParentalLock_Help_2_Left3": "Session Lock On",
	"VrHelp_ParentalLock_Help_2_Left4": "Session Lock Off",
	"VrHelp_ParentalLock_Help_2_Left5": "Edit PIN Code",
	"VrHelp_ParentalLock_Help_2_Right1": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left4": "Initialize PIN Code",
	"WrongPIN": "Vale PIN-kood",
	"XM": "XM",
	"XMChannelNotAuthorized": "XM-kanal pole autoriseeritud",
	"XMChannelNotAvailable": "XM-kanal kättesaadav",
	"XMChannelOffAir": "XM-kanalit pole eetris",
};

framework.registerAppDictLoaded("satradio", "et_EE");