var Localization_dvdAppDict_el_GR = {
	//"stringId" : "localString"
	"Adjust": "Ρύθμιση",
	"AspectRatio": "Αναλογίες εικόνας",
	"AudioSettings": "Ρυθμίσεις ήχου",
	"Brightness": "Φωτεινό",
	"Chapter": "Κεφάλαιο",
	"ChooseMaxAllowRating": "Επιλέξτε μέγιστη επιτρεπτή τιμή",
	"Close": "Απόκρυψη κουμπιών",
	"Color": "Χρώμα",
	"Contrast": "Αντίθεση",
	"DVD": "DVD",
	"DVDMechanical": "Μηχανικό σφάλμα συσκ. αναπ. DVD",
	"DVDRegionViolation": "Παραβίαση περιοχής DVD",
	"DiscError": "Σφάλμα δίσκου",
	"DiscErrorNotification": "Συνέβη σφάλμα δίσκου",
	"DiscInserted": "Εισήχθη δίσκος",
	"DiscNotPlayable": "Ο δίσκος δεν μπορεί να αναπαραχθεί.",
	"EditPinCode": "Επεξεργασία κωδικού Pin",
	"EjectingDisc": "Εξαγωγή DVD",
	"EnterFactoryPIN": "Εργοστ. PIN ",
	"EnterNewPin": "Καταχ. νέου PIN",
	"EnterPIN": "Καταχώρηση PIN",
	"InitializePINCode": "Αρχικοποίηση κωδικού PIN",
	"IsThisCorrect": "Είναι σωστό αυτό;",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Φόρτωση",
	"LostVideoSignal": "Απώλεια σήμ. βίντεο",
	"MechanicalError": "Μηχανικό σφάλμα DVD",
	"NoDiscInserted": "Δεν έχει εισαχθεί δίσκος",
	"NoVideoSignalAvailable": "Μη διαθέσιμο σήμα βίντεο",
	"None": "--",
	"PG13": "Επιθυμητή γονική συναίνεση",
	"PINSet": "Ρύθμιση ΡΙΝ",
	"Panscan": "4:3 Pan-scan",
	"ParentalLock": "Γονικό κλείδωμα",
	"ParentalLockRating": "Κατηγορία γονικού κλειδώματος",
	"R15": "Απαραίττ. γονική συναίνεση",
	"R18": "Ακατάλληλο για ανηλίκους",
	"Reset": "Επαναφ.",
	"ResetPinCode": "Επαναφορά κωδικού PIN",
	"SelectController": "Επιλογή",
	"SelectRootMenuTooltip": "Βασικό Μενού",
	"Settings": "Ρυθμίσεις",
	"Tint": "Τόνος",
	"Track": "Κομμάτι {trackNumber}",
	"VideoNotDisplayed": "Για λόγους ασφαλείας δεν γίνεται αναπαρ. βίντεο κατά την οδήγηση",
	"VrHelp_DVDGraphic_Help_Left1": "Entertainment",
	"VrHelp_DVDGraphic_Help_Left2": "Previous",
	"VrHelp_DVDGraphic_Help_Left3": "Play / Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Next",
	"VrHelp_DVDGraphic_Help_Left5": "DVD Settings",
	"VrHelp_DVDSettings_Help_Left1": "Sound Settings",
	"VrHelp_DVDSettings_Help_Left2": "Aspect Ratio",
	"VrHelp_ParentalLockRating_Help_Left1": "None",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "Parental Lock Rating",
	"VrHelp_ParentalLock_Help1_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help1_Left3": "Reset PIN Code",
	"VrHelp_ParentalLock_Help2_Left1": "Parental Lock On/Off",
	"VrHelp_ParentalLock_Help2_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help2_Left3": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_TitleGraphic_Help_Left1": "Change Source",
	"VrHelp_TitleGraphic_Help_Left2": "Previous",
	"VrHelp_TitleGraphic_Help_Left3": "Play",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Next",
	"VrHelp_TitleGraphic_Help_Right1": "Rewind",
	"VrHelp_TitleGraphic_Help_Right2": "Fast Forward",
	"VrHelp_TitleScreen_Help_Left1": "Change Source",
	"VrHelp_TitleScreen_Help_Left2": "Previous",
	"VrHelp_TitleScreen_Help_Left3": "Play",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Next",
	"VrHelp_TitleScreen_Help_Right1": "Rewind",
	"VrHelp_TitleScreen_Help_Right2": "Fast Forward",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entertainment",
	"VrHelp_VideoNowPlaying_Help_Left2": "Root Menu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Previous",
	"VrHelp_VideoNowPlaying_Help_Left4": "Play / Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Next",
	"VrHelp_VideoNowPlaying_Help_Right1": "Camera Angle",
	"VrHelp_VideoNowPlaying_Help_Right2": "Subtitles",
	"VrHelp_VideoNowPlaying_Help_Right3": "Parental Lock",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD Settings",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video Settings",
	"Widescreen": "16:9 Widescreen",
	"WrongPIN": "Λάθος ΡΙΝ",
	"displayAdjustments": "Ρυθμίσεις εμφάνισης",
};

framework.registerAppDictLoaded("dvd", "el_GR");