var Localization_dvdAppDict_da_DK = {
	//"stringId" : "localString"
	"Adjust": "Tilpas",
	"AspectRatio": "Billedformat",
	"AudioSettings": "Lydindstillinger",
	"Brightness": "Lysstyrke",
	"Chapter": "Kapitel",
	"ChooseMaxAllowRating": "Vælg den maks. tilladte ",
	"Close": "Skjul",
	"Color": "Farve",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "Dvd-afspiller mekanisk fejl",
	"DVDRegionViolation": "DVD regionslåst",
	"DiscError": "Diskfejl",
	"DiscErrorNotification": "Der opstod en diskfejl",
	"DiscInserted": "Disk indsat",
	"DiscNotPlayable": "Disken kan ikke afspilles.",
	"EditPinCode": "Redigér pinkode",
	"EjectingDisc": "Skubber DVD ud",
	"EnterFactoryPIN": "Nul. fabriks-PIN",
	"EnterNewPin": "Indtast ny PIN",
	"EnterPIN": "Indtast PIN-kode",
	"InitializePINCode": "Initialisér PIN-kode",
	"IsThisCorrect": "Er dette korrekt?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Indlæser",
	"LostVideoSignal": "Tabt videosignal",
	"MechanicalError": "Mekanisk fejl i DVD",
	"NoDiscInserted": "Der er ikke isat nogen disk",
	"NoVideoSignalAvailable": "Intet videosignal til rådighed",
	"None": "--",
	"PG13": "PG12",
	"PINSet": "PIN gemt",
	"Panscan": "4:3 Panscanning",
	"ParentalLock": "Børnesikring",
	"ParentalLockRating": "Børnesikringsklasse",
	"R15": "R15",
	"R18": "R18",
	"Reset": "Nulstil",
	"ResetPinCode": "Nulstil pinkode",
	"SelectController": "Vælg",
	"SelectRootMenuTooltip": "Hovedmenu",
	"Settings": "Indstillinger",
	"Tint": "Farvetone",
	"Track": "Track {trackNumber}",
	"VideoNotDisplayed": "Af sikkerhedsmæssige årsager bliver videoen ikke vist under kørsel.",
	"VrHelp_DVDGraphic_Help_Left1": "Underholdning",
	"VrHelp_DVDGraphic_Help_Left2": "Forrige",
	"VrHelp_DVDGraphic_Help_Left3": "Afspil/Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Næste",
	"VrHelp_DVDGraphic_Help_Left5": "dvd-Indstillinger ",
	"VrHelp_DVDSettings_Help_Left1": "Lydindstillinger",
	"VrHelp_DVDSettings_Help_Left2": "Billedformat",
	"VrHelp_ParentalLockRating_Help_Left1": "Ingen",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15 +",
	"VrHelp_ParentalLock_Help1_Left1": "Forældrelås, bedømmelse",
	"VrHelp_ParentalLock_Help1_Left2": "Redigér PIN-kode",
	"VrHelp_ParentalLock_Help1_Left3": "Nulstil PIN-kode",
	"VrHelp_ParentalLock_Help2_Left1": "Forældrelås On/Off",
	"VrHelp_ParentalLock_Help2_Left2": "Redigér PIN-kode",
	"VrHelp_ParentalLock_Help2_Left3": "Nulstil PIN-kode",
	"VrHelp_PinEntryNew_Help_Left1": "(Cifrene 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Ryd",
	"VrHelp_PinEntryReset_Help_Left1": "(Cifrene 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Ryd",
	"VrHelp_PinEntryUnlock_Help_Left1": "(Cifrene 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Ryd",
	"VrHelp_TitleGraphic_Help_Left1": "Skift kilde",
	"VrHelp_TitleGraphic_Help_Left2": "Forrige",
	"VrHelp_TitleGraphic_Help_Left3": "Afspil",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Næste",
	"VrHelp_TitleGraphic_Help_Right1": "Spol tilbage",
	"VrHelp_TitleGraphic_Help_Right2": "Hurtigt frem",
	"VrHelp_TitleScreen_Help_Left1": "Skift kilde",
	"VrHelp_TitleScreen_Help_Left2": "Forrige",
	"VrHelp_TitleScreen_Help_Left3": "Afspil",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Næste",
	"VrHelp_TitleScreen_Help_Right1": "Spol tilbage",
	"VrHelp_TitleScreen_Help_Right2": "Hurtigt frem",
	"VrHelp_VideoNowPlaying_Help_Left1": "Underholdning",
	"VrHelp_VideoNowPlaying_Help_Left2": "Hovedmenu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Forrige",
	"VrHelp_VideoNowPlaying_Help_Left4": "Afspil/Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Næste",
	"VrHelp_VideoNowPlaying_Help_Right1": "Kameravinke",
	"VrHelp_VideoNowPlaying_Help_Right2": "Undertekster",
	"VrHelp_VideoNowPlaying_Help_Right3": "Forældrelås",
	"VrHelp_VideoNowPlaying_Help_Right4": "dvd-Indstillinger ",
	"VrHelp_VideoNowPlaying_Help_Right5": "videoIndstillinger",
	"Widescreen": "16:9 Widescreen",
	"WrongPIN": "Forkert PIN",
	"displayAdjustments": "Vis justeringer",
};

framework.registerAppDictLoaded("dvd", "da_DK");