var Localization_dvdAppDict_sv_SE = {
	//"stringId" : "localString"
	"Adjust": "Justera",
	"AspectRatio": "Bildformat",
	"AudioSettings": "Ljudinställningar",
	"Brightness": "Ljusstyrka",
	"Chapter": "Kapitel",
	"ChooseMaxAllowRating": "Välj max klassning",
	"Close": "Dölj knappar",
	"Color": "Färg",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "Mekaniskt fel på DVD-spelaren",
	"DVDRegionViolation": "Regionöverträdelse för DVD",
	"DiscError": "Fel på skivan",
	"DiscErrorNotification": "Det blev fel på skivan",
	"DiscInserted": "Skiva inmatad",
	"DiscNotPlayable": "Skivan kan inte spelas.",
	"EditPinCode": "Redigera PIN-kod",
	"EjectingDisc": "Matar ut DVD",
	"EnterFactoryPIN": "Fabriks-PIN, återst",
	"EnterNewPin": "Ange ny PIN",
	"EnterPIN": "Ange PIN",
	"InitializePINCode": "Initiera PIN-kod",
	"IsThisCorrect": "Är detta rätt?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Läser in",
	"LostVideoSignal": "Bruten videosignal",
	"MechanicalError": "Mekaniskt fel på DVD",
	"NoDiscInserted": "Ingen skiva inmatad",
	"NoVideoSignalAvailable": "Det finns ingen videosignal",
	"None": "--",
	"PG13": "PG12",
	"PINSet": "PIN-kod inställd",
	"Panscan": "4:3 Panscan",
	"ParentalLock": "Föräldralås",
	"ParentalLockRating": "Föräldralåsklassning",
	"R15": "Ungdom",
	"R18": "Vuxen",
	"Reset": "Återställ",
	"ResetPinCode": "Återställ PIN-kod",
	"SelectController": "Välj",
	"SelectRootMenuTooltip": "Osnovni meni",
	"Settings": "Inställningar",
	"Tint": "Mättnad",
	"Track": "Spår {trackNumber}",
	"VideoNotDisplayed": "Av säkerhetsskäl kommer videon inte visas under körning.",
	"VrHelp_DVDGraphic_Help_Left1": "Underhållning",
	"VrHelp_DVDGraphic_Help_Left2": "Föregående",
	"VrHelp_DVDGraphic_Help_Left3": "Spela upp / Paus",
	"VrHelp_DVDGraphic_Help_Left4": "Nästa",
	"VrHelp_DVDGraphic_Help_Left5": "DVD inställningar",
	"VrHelp_DVDSettings_Help_Left1": "Ljudinställningar",
	"VrHelp_DVDSettings_Help_Left2": "Bildformat",
	"VrHelp_ParentalLockRating_Help_Left1": "Ingen",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "Ungdom och äldre",
	"VrHelp_ParentalLock_Help1_Left1": "Föräldralåsklassning",
	"VrHelp_ParentalLock_Help1_Left2": "Redigera PIN-kod",
	"VrHelp_ParentalLock_Help1_Left3": "Återställ PIN-kod",
	"VrHelp_ParentalLock_Help2_Left1": "Föräldralås på/av",
	"VrHelp_ParentalLock_Help2_Left2": "Redigera PIN-kod",
	"VrHelp_ParentalLock_Help2_Left3": "Återställ PIN-kod",
	"VrHelp_PinEntryNew_Help_Left1": "(siffrorna 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Rensa",
	"VrHelp_PinEntryReset_Help_Left1": "(siffrorna 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Rensa",
	"VrHelp_PinEntryUnlock_Help_Left1": "(siffrorna 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Rensa",
	"VrHelp_TitleGraphic_Help_Left1": "Ändra källa",
	"VrHelp_TitleGraphic_Help_Left2": "Föregående",
	"VrHelp_TitleGraphic_Help_Left3": "Spela upp",
	"VrHelp_TitleGraphic_Help_Left4": "Paus",
	"VrHelp_TitleGraphic_Help_Left5": "Nästa",
	"VrHelp_TitleGraphic_Help_Right1": "Snabbt bakåt",
	"VrHelp_TitleGraphic_Help_Right2": "Snabbt framåt",
	"VrHelp_TitleScreen_Help_Left1": "Ändra källa",
	"VrHelp_TitleScreen_Help_Left2": "Föregående",
	"VrHelp_TitleScreen_Help_Left3": "Spela upp",
	"VrHelp_TitleScreen_Help_Left4": "Paus",
	"VrHelp_TitleScreen_Help_Left5": "Nästa",
	"VrHelp_TitleScreen_Help_Right1": "Snabbt bakåt",
	"VrHelp_TitleScreen_Help_Right2": "Snabbt framåt",
	"VrHelp_VideoNowPlaying_Help_Left1": "Underhållning",
	"VrHelp_VideoNowPlaying_Help_Left2": "Rotmeny",
	"VrHelp_VideoNowPlaying_Help_Left3": "Föregående",
	"VrHelp_VideoNowPlaying_Help_Left4": "Spela upp / Paus",
	"VrHelp_VideoNowPlaying_Help_Left5": "Nästa",
	"VrHelp_VideoNowPlaying_Help_Right1": "Kameravinkel",
	"VrHelp_VideoNowPlaying_Help_Right2": "Undertext",
	"VrHelp_VideoNowPlaying_Help_Right3": "Föräldralås",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD inställningar",
	"VrHelp_VideoNowPlaying_Help_Right5": " video inställningar",
	"Widescreen": "16:9 Widescreen",
	"WrongPIN": "Fel PIN-kod",
	"displayAdjustments": "Podešavanja ekrana",
};

framework.registerAppDictLoaded("dvd", "sv_SE");