var Localization_dvdAppDict_sk_SK = {
	//"stringId" : "localString"
	"Adjust": "Prispôs.",
	"AspectRatio": "Pomer strán",
	"AudioSettings": "Nastavenia zvuku",
	"Brightness": "Jas",
	"Chapter": "Kapitola",
	"ChooseMaxAllowRating": "Vybrať max. možné hodnotenie",
	"Close": "Skryť tlačidlá",
	"Color": "Farba",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "Mechanická chyba prehrávača DVD",
	"DVDRegionViolation": "Porušenie regiónu DVD",
	"DiscError": "Chyba disku",
	"DiscErrorNotification": "Došlo k chybe disku",
	"DiscInserted": "Disk vložený",
	"DiscNotPlayable": "Tento disk nie je možné prehrať.",
	"EditPinCode": "Upraviť PIN kód",
	"EjectingDisc": "Vysúva sa DVD",
	"EnterFactoryPIN": "Resetovanie -  PIN",
	"EnterNewPin": "Zadajte nový PIN",
	"EnterPIN": "Zadať PIN",
	"InitializePINCode": "Inicializovať PIN kód",
	"IsThisCorrect": "Je to správne?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Načítava sa",
	"LostVideoSignal": "Video signál sa stratil",
	"MechanicalError": "Mechanická chyba DVD",
	"NoDiscInserted": "Nie je vložený žiaden disk",
	"NoVideoSignalAvailable": "Nie je k dispozícii žiadny video signál",
	"None": "--",
	"PG13": "PG12",
	"PINSet": "Nastavenie PIN",
	"Panscan": "4:3 Pan-scan",
	"ParentalLock": "Rodičovský zámok",
	"ParentalLockRating": "Hodnotenie rodičovského zámku",
	"R15": "R15",
	"R18": "R18",
	"Reset": "Resetovať",
	"ResetPinCode": "Obnoviť PIN kód",
	"SelectController": "Vybrať",
	"SelectRootMenuTooltip": "Hlavná ponuka",
	"Settings": "Nastavenia",
	"Tint": "Zafarb.",
	"Track": "Položka {trackNumber}",
	"VideoNotDisplayed": "Z bezpečnostných dôvodov sa video nedá zobraziť počas jazdy.",
	"VrHelp_DVDGraphic_Help_Left1": "Entertainment",
	"VrHelp_DVDGraphic_Help_Left2": "Previous",
	"VrHelp_DVDGraphic_Help_Left3": "Play / Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Next",
	"VrHelp_DVDGraphic_Help_Left5": "DVD Settings",
	"VrHelp_DVDSettings_Help_Left1": "Sound Settings",
	"VrHelp_DVDSettings_Help_Left2": "Aspect Ratio",
	"VrHelp_ParentalLockRating_Help_Left1": "None",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "Parental Lock Rating",
	"VrHelp_ParentalLock_Help1_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help1_Left3": "Reset PIN Code",
	"VrHelp_ParentalLock_Help2_Left1": "Parental Lock On/Off",
	"VrHelp_ParentalLock_Help2_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help2_Left3": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_TitleGraphic_Help_Left1": "Change Source",
	"VrHelp_TitleGraphic_Help_Left2": "Previous",
	"VrHelp_TitleGraphic_Help_Left3": "Play",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Next",
	"VrHelp_TitleGraphic_Help_Right1": "Rewind",
	"VrHelp_TitleGraphic_Help_Right2": "Fast Forward",
	"VrHelp_TitleScreen_Help_Left1": "Change Source",
	"VrHelp_TitleScreen_Help_Left2": "Previous",
	"VrHelp_TitleScreen_Help_Left3": "Play",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Next",
	"VrHelp_TitleScreen_Help_Right1": "Rewind",
	"VrHelp_TitleScreen_Help_Right2": "Fast Forward",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entertainment",
	"VrHelp_VideoNowPlaying_Help_Left2": "Root Menu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Previous",
	"VrHelp_VideoNowPlaying_Help_Left4": "Play / Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Next",
	"VrHelp_VideoNowPlaying_Help_Right1": "Camera Angle",
	"VrHelp_VideoNowPlaying_Help_Right2": "Subtitles",
	"VrHelp_VideoNowPlaying_Help_Right3": "Parental Lock",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD Settings",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video Settings",
	"Widescreen": "16:9 Širokouhlé",
	"WrongPIN": "Nesprávny PIN",
	"displayAdjustments": "Nastavenie displeja",
};

framework.registerAppDictLoaded("dvd", "sk_SK");