var Localization_dvdAppDict_nl_NL = {
	//"stringId" : "localString"
	"Adjust": "Aanpas.",
	"AspectRatio": "Beeldverhouding",
	"AudioSettings": "Audio-instellingen",
	"Brightness": "Helderheid",
	"Chapter": "Hoofdstuk",
	"ChooseMaxAllowRating": "Kies max toegestane categorie",
	"Close": "Knoppen verbergen",
	"Color": "Kleur",
	"Contrast": "Contrast",
	"DVD": "DVD",
	"DVDMechanical": "Mechanische fout DVD-speler",
	"DVDRegionViolation": "DVD regio-overtreding",
	"DiscError": "Disc fout",
	"DiscErrorNotification": "Er heeft zich een schijffout voorgedaan",
	"DiscInserted": "Disc geplaatst",
	"DiscNotPlayable": "De disc is niet afspeelbaar.",
	"EditPinCode": "Pincode bewerken",
	"EjectingDisc": "Eject DVD",
	"EnterFactoryPIN": "PIN inv. voor res",
	"EnterNewPin": "Vr. nwe PIN in",
	"EnterPIN": "Voer PIN in",
	"InitializePINCode": "Pincode initialiseren",
	"IsThisCorrect": "Is dit juist?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Bezig met laden",
	"LostVideoSignal": "Videosignaal Verloren",
	"MechanicalError": "DVD mechanische fout",
	"NoDiscInserted": "Geen disc ingevoerd",
	"NoVideoSignalAvailable": "Geen Videosignaal Beschikbaar",
	"None": "--",
	"PG13": "12J",
	"PINSet": "PIN ingesteld",
	"Panscan": "Beeldverhouding 4:3",
	"ParentalLock": "Kinderslot",
	"ParentalLockRating": "Niveau kinderslot",
	"R15": "15J",
	"R18": "18J",
	"Reset": "Reset",
	"ResetPinCode": "Pincode resetten",
	"SelectController": "Selecteer",
	"SelectRootMenuTooltip": "Rootmenu",
	"Settings": "Instellingen",
	"Tint": "Tint",
	"Track": "Track {trackNumber}",
	"VideoNotDisplayed": "Om veiligheidsredenen wordt de video tijdens het rijden niet getoond.",
	"VrHelp_DVDGraphic_Help_Left1": "Entertainment",
	"VrHelp_DVDGraphic_Help_Left2": "Vorige",
	"VrHelp_DVDGraphic_Help_Left3": " Afspelen / Pauze",
	"VrHelp_DVDGraphic_Help_Left4": "Volgende",
	"VrHelp_DVDGraphic_Help_Left5": "DVD-instellingen",
	"VrHelp_DVDSettings_Help_Left1": "Geluidsinstelling gen",
	"VrHelp_DVDSettings_Help_Left2": "Beeldverhouding",
	"VrHelp_ParentalLockRating_Help_Left1": "Geen",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15 +",
	"VrHelp_ParentalLock_Help1_Left1": "Kinderslot Rating",
	"VrHelp_ParentalLock_Help1_Left2": "PIN-Code bewerken",
	"VrHelp_ParentalLock_Help1_Left3": "PIN-Code Opnieuw Instellen",
	"VrHelp_ParentalLock_Help2_Left1": "Kinderslot Aan / Uit",
	"VrHelp_ParentalLock_Help2_Left2": "PIN-Code bewerken",
	"VrHelp_ParentalLock_Help2_Left3": "PIN-Code Opnieuw Instellen",
	"VrHelp_PinEntryNew_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Duidelijk",
	"VrHelp_PinEntryReset_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Duidelijk",
	"VrHelp_PinEntryUnlock_Help_Left1": "(cijfers 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Duidelijk",
	"VrHelp_TitleGraphic_Help_Left1": "Bron wijzigen",
	"VrHelp_TitleGraphic_Help_Left2": "Vorige",
	"VrHelp_TitleGraphic_Help_Left3": "Spelen",
	"VrHelp_TitleGraphic_Help_Left4": "Pauze",
	"VrHelp_TitleGraphic_Help_Left5": "Volgende",
	"VrHelp_TitleGraphic_Help_Right1": "Terugspoelen",
	"VrHelp_TitleGraphic_Help_Right2": "Snel Doorspoelen",
	"VrHelp_TitleScreen_Help_Left1": "Bron wijzigen",
	"VrHelp_TitleScreen_Help_Left2": "Vorige",
	"VrHelp_TitleScreen_Help_Left3": "Spelen",
	"VrHelp_TitleScreen_Help_Left4": "Pauze",
	"VrHelp_TitleScreen_Help_Left5": "Volgende",
	"VrHelp_TitleScreen_Help_Right1": "Terugspoelen",
	"VrHelp_TitleScreen_Help_Right2": "Snel Doorspoelen",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entertainment",
	"VrHelp_VideoNowPlaying_Help_Left2": " Rootmenu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Vorige ",
	"VrHelp_VideoNowPlaying_Help_Left4": " Afspelen / Pauze",
	"VrHelp_VideoNowPlaying_Help_Left5": "Volgende",
	"VrHelp_VideoNowPlaying_Help_Right1": "Camerahoek",
	"VrHelp_VideoNowPlaying_Help_Right2": " Ondertitels",
	"VrHelp_VideoNowPlaying_Help_Right3": "Kinderslot",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD-instellingen",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video-instellingen",
	"Widescreen": "16:9 Breedbeeld",
	"WrongPIN": "Onjuiste PIN",
	"displayAdjustments": "Instellingen display",
};

framework.registerAppDictLoaded("dvd", "nl_NL");