var Localization_dvdAppDict_zh_CN = {
	//"stringId" : "localString"
	"Adjust": "调整",
	"AspectRatio": "高宽比",
	"AudioSettings": "音频设置",
	"Brightness": "亮度",
	"Chapter": "章节",
	"ChooseMaxAllowRating": "选择最大允许等级",
	"Close": "隐藏按钮",
	"Color": "颜色",
	"Contrast": "对比度",
	"DVD": "DVD",
	"DVDMechanical": "DVD 播放器机械故障",
	"DVDRegionViolation": "DVD地区违规",
	"DiscError": "磁盘错误",
	"DiscErrorNotification": "出现磁盘错误",
	"DiscInserted": "磁盘已插入",
	"DiscNotPlayable": "此磁盘不可播放。",
	"EditPinCode": "编辑验证密码",
	"EjectingDisc": "正在弹出DVD",
	"EnterFactoryPIN": "输入工厂PIN重设",
	"EnterNewPin": "输入新 PIN",
	"EnterPIN": "输入 PIN 代码",
	"InitializePINCode": "PIN 码初始化",
	"IsThisCorrect": "是否正确？",
	"Letterbox": "4:3 外框",
	"Loading": "正在加载",
	"LostVideoSignal": "丢失视频信号",
	"MechanicalError": "DVD机械故障",
	"NoDiscInserted": "未插入磁盘",
	"NoVideoSignalAvailable": "未获得视频信号",
	"None": "无",
	"PG13": "PG12",
	"PINSet": "PIN 设置",
	"Panscan": "4:3 全景",
	"ParentalLock": "家长锁",
	"ParentalLockRating": "家长所等级",
	"R15": "15 岁及以上",
	"R18": "18 岁及以上",
	"Reset": "重新设置",
	"ResetPinCode": "重设验证密码",
	"SelectController": "选择",
	"SelectRootMenuTooltip": "根菜单",
	"Settings": "设置",
	"Tint": "色调",
	"Track": "曲 {trackNumber}",
	"VideoNotDisplayed": "出于安全原因，驾驶时不显示视频。",
	"VrHelp_DVDGraphic_Help_Left1": "更改来源",
	"VrHelp_DVDGraphic_Help_Left2": "上一个",
	"VrHelp_DVDGraphic_Help_Left3": "播放 / 暂停",
	"VrHelp_DVDGraphic_Help_Left4": "下一个",
	"VrHelp_DVDGraphic_Help_Left5": "设置",
	"VrHelp_DVDSettings_Help_Left1": "声音设置",
	"VrHelp_DVDSettings_Help_Left2": "长宽比",
	"VrHelp_ParentalLockRating_Help_Left1": "无",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "家长锁评级",
	"VrHelp_ParentalLock_Help1_Left2": "编辑 PIN 码",
	"VrHelp_ParentalLock_Help1_Left3": "重置PIN码",
	"VrHelp_ParentalLock_Help2_Left1": "打开 / 关闭家长锁",
	"VrHelp_ParentalLock_Help2_Left2": "编辑 PIN 码",
	"VrHelp_ParentalLock_Help2_Left3": "重置PIN码",
	"VrHelp_PinEntryNew_Help_Left1": "（数字 0-9）",
	"VrHelp_PinEntryNew_Help_Left2": "确定",
	"VrHelp_PinEntryNew_Help_Left3": "清除",
	"VrHelp_PinEntryReset_Help_Left1": "（数字 0-9）",
	"VrHelp_PinEntryReset_Help_Left2": "确定",
	"VrHelp_PinEntryReset_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left1": "（数字 0-9）",
	"VrHelp_PinEntryUnlock_Help_Left2": "确定",
	"VrHelp_PinEntryUnlock_Help_Left3": "清除",
	"VrHelp_TitleGraphic_Help_Left1": "更改来源",
	"VrHelp_TitleGraphic_Help_Left2": "上一个",
	"VrHelp_TitleGraphic_Help_Left3": "播放",
	"VrHelp_TitleGraphic_Help_Left4": "暂停",
	"VrHelp_TitleGraphic_Help_Left5": "下一个",
	"VrHelp_TitleGraphic_Help_Right1": "倒带",
	"VrHelp_TitleGraphic_Help_Right2": "快进",
	"VrHelp_TitleScreen_Help_Left1": "更改来源",
	"VrHelp_TitleScreen_Help_Left2": "上一个",
	"VrHelp_TitleScreen_Help_Left3": "播放",
	"VrHelp_TitleScreen_Help_Left4": "暂停",
	"VrHelp_TitleScreen_Help_Left5": "下一个",
	"VrHelp_TitleScreen_Help_Right1": "倒带",
	"VrHelp_TitleScreen_Help_Right2": "快进",
	"VrHelp_VideoNowPlaying_Help_Left1": "更改来源",
	"VrHelp_VideoNowPlaying_Help_Left2": "DVD 菜单",
	"VrHelp_VideoNowPlaying_Help_Left3": "上一个",
	"VrHelp_VideoNowPlaying_Help_Left4": "播放 / 暂停",
	"VrHelp_VideoNowPlaying_Help_Left5": "下一个",
	"VrHelp_VideoNowPlaying_Help_Right1": "摄像头角度",
	"VrHelp_VideoNowPlaying_Help_Right2": "副标题",
	"VrHelp_VideoNowPlaying_Help_Right3": "家长锁",
	"VrHelp_VideoNowPlaying_Help_Right4": "设置",
	"VrHelp_VideoNowPlaying_Help_Right5": "显示调整",
	"Widescreen": "16:9 宽屏幕",
	"WrongPIN": "错误的 PIN",
	"displayAdjustments": "显示调整",
};

framework.registerAppDictLoaded("dvd", "zh_CN");