var Localization_dvdAppDict_es_ES = {
	//"stringId" : "localString"
	"Adjust": "Ajuste",
	"AspectRatio": "Relación de aspecto",
	"AudioSettings": "Ajustes de audio",
	"Brightness": "Brillo ",
	"Chapter": "Capítulo",
	"ChooseMaxAllowRating": "Elija clasificación máxima permitida",
	"Close": "Ocultar",
	"Color": "Color",
	"Contrast": "Contraste ",
	"DVD": "DVD",
	"DVDMechanical": "Error mecánico del reproductor de DVD",
	"DVDRegionViolation": "Violación de región de DVD",
	"DiscError": "Error de disco",
	"DiscErrorNotification": "Ha ocurrido un error de disco",
	"DiscInserted": "Disco Insertado",
	"DiscNotPlayable": "El disco no es reproducible.",
	"EditPinCode": "Editar código Pin",
	"EjectingDisc": "Expulsando DVD",
	"EnterFactoryPIN": "Ing Pin fábrica ",
	"EnterNewPin": "Ingrese Nuevo PIN",
	"EnterPIN": "Introducir PIN",
	"InitializePINCode": "Inicializar código PIN",
	"IsThisCorrect": "¿Es esto correcto?",
	"Letterbox": "Letterbox 4:3",
	"Loading": "Cargando",
	"LostVideoSignal": "Señal Video Perdida",
	"MechanicalError": "Error mecánico de DVD",
	"NoDiscInserted": "No Hay Disco Insertado",
	"NoVideoSignalAvailable": "No hay señal de video disponible",
	"None": "--",
	"PG13": "PG 12",
	"PINSet": "PIN establecido",
	"Panscan": "Pan-scan 4:3",
	"ParentalLock": "Bloqueo parental ",
	"ParentalLockRating": "Clasificación de bloqueo parental",
	"R15": "R15",
	"R18": "R18",
	"Reset": "Reiniciar ",
	"ResetPinCode": "Restablecer código pin",
	"SelectController": "Seleccionar",
	"SelectRootMenuTooltip": "Menú raíz",
	"Settings": "Configuraciones",
	"Tint": "Tono",
	"Track": "Pista {trackNumber}",
	"VideoNotDisplayed": "Por razones de seguridad, no aparecerá el vídeo mientras conduce.",
	"VrHelp_DVDGraphic_Help_Left1": "Entretenimiento",
	"VrHelp_DVDGraphic_Help_Left2": "Anterior",
	"VrHelp_DVDGraphic_Help_Left3": "Reproducir/Pausa",
	"VrHelp_DVDGraphic_Help_Left4": "Siguiente",
	"VrHelp_DVDGraphic_Help_Left5": "Ajustes de DVD",
	"VrHelp_DVDSettings_Help_Left1": "Ajustes de Sonido",
	"VrHelp_DVDSettings_Help_Left2": "Relación de aspecto",
	"VrHelp_ParentalLockRating_Help_Left1": "Ninguno",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "Clasificación de Control Paterno",
	"VrHelp_ParentalLock_Help1_Left2": "Editar Código PIN",
	"VrHelp_ParentalLock_Help1_Left3": "Restablecer Código PIN",
	"VrHelp_ParentalLock_Help2_Left1": "Control Paterno Activado/ Desactivado",
	"VrHelp_ParentalLock_Help2_Left2": "Editar Código PIN",
	"VrHelp_ParentalLock_Help2_Left3": "Restablecer Código PIN",
	"VrHelp_PinEntryNew_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "ACEPTAR",
	"VrHelp_PinEntryNew_Help_Left3": "Borrar",
	"VrHelp_PinEntryReset_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "ACEPTAR",
	"VrHelp_PinEntryReset_Help_Left3": "Borrar",
	"VrHelp_PinEntryUnlock_Help_Left1": "(dígitos 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "ACEPTAR",
	"VrHelp_PinEntryUnlock_Help_Left3": "Borrar",
	"VrHelp_TitleGraphic_Help_Left1": "Cambiar Fuente",
	"VrHelp_TitleGraphic_Help_Left2": "Anterior",
	"VrHelp_TitleGraphic_Help_Left3": "Reproducir",
	"VrHelp_TitleGraphic_Help_Left4": "Pausa",
	"VrHelp_TitleGraphic_Help_Left5": "Siguiente",
	"VrHelp_TitleGraphic_Help_Right1": "Rebobinar",
	"VrHelp_TitleGraphic_Help_Right2": "Avance Rápido",
	"VrHelp_TitleScreen_Help_Left1": "Cambiar Fuente",
	"VrHelp_TitleScreen_Help_Left2": "Anterior",
	"VrHelp_TitleScreen_Help_Left3": "Reproducir",
	"VrHelp_TitleScreen_Help_Left4": "Pausa",
	"VrHelp_TitleScreen_Help_Left5": "Siguiente",
	"VrHelp_TitleScreen_Help_Right1": "Rebobinar",
	"VrHelp_TitleScreen_Help_Right2": "Avance Rápido",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entretenimiento",
	"VrHelp_VideoNowPlaying_Help_Left2": "Menú raíz",
	"VrHelp_VideoNowPlaying_Help_Left3": "Anterior",
	"VrHelp_VideoNowPlaying_Help_Left4": "Reproducir/Pausa",
	"VrHelp_VideoNowPlaying_Help_Left5": "Siguiente",
	"VrHelp_VideoNowPlaying_Help_Right1": "Ángulo de Cámara",
	"VrHelp_VideoNowPlaying_Help_Right2": "Subtítulos",
	"VrHelp_VideoNowPlaying_Help_Right3": "Control Paterno",
	"VrHelp_VideoNowPlaying_Help_Right4": "Ajustes de DVD",
	"VrHelp_VideoNowPlaying_Help_Right5": "Ajustes de vídeo",
	"Widescreen": "Widescreen 16:9",
	"WrongPIN": "PIN incorrecto",
	"displayAdjustments": "Ajustes de pantalla",
};

framework.registerAppDictLoaded("dvd", "es_ES");