var Localization_dvdAppDict_de_DE = {
	//"stringId" : "localString"
	"Adjust": "Anpassen",
	"AspectRatio": "Bildseitenverhältnis",
	"AudioSettings": "Audioeinstellungen",
	"Brightness": "Helligkeit",
	"Chapter": "Kapitel",
	"ChooseMaxAllowRating": "Max zuläss. Freigabest. wählen",
	"Close": "Schließen",
	"Color": "Farbe",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "DVD: Mechanischer Fehler",
	"DVDRegionViolation": "DVD Bereichsverletzung",
	"DiscError": "Datenträgerfehler",
	"DiscErrorNotification": "Datenträgerfehler aufgetreten",
	"DiscInserted": "Datenträger eingelegt",
	"DiscNotPlayable": "Die Disc ist nicht abspielbar.",
	"EditPinCode": "Pin-Code bearbeiten",
	"EjectingDisc": "DVD wird ausgeworfen",
	"EnterFactoryPIN": "Res.WerkPIN eing.",
	"EnterNewPin": "Neue PIN eingeben",
	"EnterPIN": "PIN eingeben",
	"InitializePINCode": "PIN-Code initialisieren",
	"IsThisCorrect": "Ist das richtig?",
	"Letterbox": "4:3 Posteingang",
	"Loading": "Wird geladen",
	"LostVideoSignal": "Verlust d. Videosignals",
	"MechanicalError": "DVD mechanischer Fehler",
	"NoDiscInserted": "Kein Datenträger eingelegt",
	"NoVideoSignalAvailable": "Kein Videosignal verfügbar",
	"None": "--",
	"PG13": "Freigabe ab 12",
	"PINSet": "PIN-Einstellung",
	"Panscan": "4:3 Pan-scan",
	"ParentalLock": "Kindersicherung",
	"ParentalLockRating": "Sicherheitsstufe Kindersicherung",
	"R15": "Freigabe ab 15",
	"R18": "Freigabe ab 18",
	"Reset": "Zurückset.",
	"ResetPinCode": "Pin-Code zurücksetzen",
	"SelectController": "Auswählen",
	"SelectRootMenuTooltip": "Stamm-Menü",
	"Settings": "Einstellungen",
	"Tint": "Tönung",
	"Track": "Titel {trackNumber}",
	"VideoNotDisplayed": "Aus Sicherheitsgründen werden Videos nicht während der Fahrt wiedergegeben",
	"VrHelp_DVDGraphic_Help_Left1": "Unterhaltung",
	"VrHelp_DVDGraphic_Help_Left2": "Vorheriger",
	"VrHelp_DVDGraphic_Help_Left3": "Wiedergabe/Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Nächster",
	"VrHelp_DVDGraphic_Help_Left5": "DVD-Einstellungen",
	"VrHelp_DVDSettings_Help_Left1": "Toneinstellungen",
	"VrHelp_DVDSettings_Help_Left2": "Seitenverhältnis",
	"VrHelp_ParentalLockRating_Help_Left1": "Kein",
	"VrHelp_ParentalLockRating_Help_Left2": "Freigabe ohne Altersbeschränkung",
	"VrHelp_ParentalLockRating_Help_Left3": "Freigabe ab 12",
	"VrHelp_ParentalLockRating_Help_Left4": "Freigabe ab 15",
	"VrHelp_ParentalLock_Help1_Left1": "Einstufung der Kindersicherung",
	"VrHelp_ParentalLock_Help1_Left2": "PIN-Code bearbeiten",
	"VrHelp_ParentalLock_Help1_Left3": "PIN-Code zurücksetzen",
	"VrHelp_ParentalLock_Help2_Left1": "Kindersicherung ein-/ausschalten",
	"VrHelp_ParentalLock_Help2_Left2": "PIN-Code bearbeiten",
	"VrHelp_ParentalLock_Help2_Left3": "PIN-Code zurücksetzen",
	"VrHelp_PinEntryNew_Help_Left1": "(Ziffern 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Löschen",
	"VrHelp_PinEntryReset_Help_Left1": "(Ziffern 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Löschen",
	"VrHelp_PinEntryUnlock_Help_Left1": "(Ziffern 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Löschen",
	"VrHelp_TitleGraphic_Help_Left1": "Quelle ändern",
	"VrHelp_TitleGraphic_Help_Left2": "Vorheriger",
	"VrHelp_TitleGraphic_Help_Left3": "Wiedergabe",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Nächster",
	"VrHelp_TitleGraphic_Help_Right1": "Rücklauf",
	"VrHelp_TitleGraphic_Help_Right2": "Vorlauf",
	"VrHelp_TitleScreen_Help_Left1": "Quelle ändern",
	"VrHelp_TitleScreen_Help_Left2": "Vorheriger",
	"VrHelp_TitleScreen_Help_Left3": "Wiedergabe",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Nächster",
	"VrHelp_TitleScreen_Help_Right1": "Rücklauf",
	"VrHelp_TitleScreen_Help_Right2": "Vorlauf",
	"VrHelp_VideoNowPlaying_Help_Left1": "Unterhaltung",
	"VrHelp_VideoNowPlaying_Help_Left2": "Stammmenü",
	"VrHelp_VideoNowPlaying_Help_Left3": "Vorheriger",
	"VrHelp_VideoNowPlaying_Help_Left4": "Wiedergabe/Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Nächster",
	"VrHelp_VideoNowPlaying_Help_Right1": "Kamerawinkel",
	"VrHelp_VideoNowPlaying_Help_Right2": "Untertitel",
	"VrHelp_VideoNowPlaying_Help_Right3": "Kindersicherung",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD-Einstellungen",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video-Einstellungen",
	"Widescreen": "16:9 Breitbildformat",
	"WrongPIN": "PIN falsch",
	"displayAdjustments": "Anzeige Anpassung",
};

framework.registerAppDictLoaded("dvd", "de_DE");