var Localization_dvdAppDict_mn_TW = {
	//"stringId" : "localString"
	"Adjust": "調整",
	"AspectRatio": "外觀比例",
	"AudioSettings": "音訊設定",
	"Brightness": "亮度",
	"Chapter": "章",
	"ChooseMaxAllowRating": "選擇可容許的評等上限",
	"Close": "隱藏按鍵",
	"Color": "鮮豔度",
	"Contrast": "對比度",
	"DVD": "DVD",
	"DVDMechanical": "DVD 播放器機械異常",
	"DVDRegionViolation": "DVD區域限制",
	"DiscError": "光碟錯誤",
	"DiscErrorNotification": "光碟發生錯誤",
	"DiscInserted": "已插入光碟",
	"DiscNotPlayable": "光碟不可播放。",
	"EditPinCode": "編輯密碼",
	"EjectingDisc": "正在退出 DVD",
	"EnterFactoryPIN": "請輸入原廠密碼",
	"EnterNewPin": "請輸入新密碼",
	"EnterPIN": "請輸入密碼",
	"InitializePINCode": "回復預設密碼",
	"IsThisCorrect": "這正確嗎?",
	"Letterbox": "4:3 上下黑邊",
	"Loading": "載入中",
	"LostVideoSignal": "視訊信號已中斷",
	"MechanicalError": "DVD 機械異常",
	"NoDiscInserted": "未插入光碟",
	"NoVideoSignalAvailable": "無可讀取的視訊信號",
	"None": "無",
	"PG13": "PG12",
	"PINSet": "密碼已設定",
	"Panscan": "4:3 全螢幕",
	"ParentalLock": "分級鎖",
	"ParentalLockRating": "分級鎖評等",
	"R15": "R15",
	"R18": "R18",
	"Reset": "初始設定",
	"ResetPinCode": "重設密碼",
	"SelectController": "選取",
	"SelectRootMenuTooltip": "根目録",
	"Settings": "設定",
	"Tint": "濃淡",
	"Track": "曲目 {trackNumber}",
	"VideoNotDisplayed": "為了安全起見，行駛時此影片將不顯示播放。",
	"VrHelp_DVDGraphic_Help_Left1": "更改來源",
	"VrHelp_DVDGraphic_Help_Left2": "上一個",
	"VrHelp_DVDGraphic_Help_Left3": "播放 / 暫停",
	"VrHelp_DVDGraphic_Help_Left4": "下一個",
	"VrHelp_DVDGraphic_Help_Left5": "設置",
	"VrHelp_DVDSettings_Help_Left1": "聲音設置",
	"VrHelp_DVDSettings_Help_Left2": "長寬比",
	"VrHelp_ParentalLockRating_Help_Left1": "無",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "家長鎖評級",
	"VrHelp_ParentalLock_Help1_Left2": "編輯 PIN 碼",
	"VrHelp_ParentalLock_Help1_Left3": "重置PIN碼",
	"VrHelp_ParentalLock_Help2_Left1": "打開 / 關閉家長鎖",
	"VrHelp_ParentalLock_Help2_Left2": "編輯 PIN 碼",
	"VrHelp_ParentalLock_Help2_Left3": "重置PIN碼",
	"VrHelp_PinEntryNew_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryNew_Help_Left2": "確定",
	"VrHelp_PinEntryNew_Help_Left3": "清除",
	"VrHelp_PinEntryReset_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryReset_Help_Left2": "確定",
	"VrHelp_PinEntryReset_Help_Left3": "清除",
	"VrHelp_PinEntryUnlock_Help_Left1": "（數字 0-9）",
	"VrHelp_PinEntryUnlock_Help_Left2": "確定",
	"VrHelp_PinEntryUnlock_Help_Left3": "清除",
	"VrHelp_TitleGraphic_Help_Left1": "更改來源",
	"VrHelp_TitleGraphic_Help_Left2": "上一個",
	"VrHelp_TitleGraphic_Help_Left3": "播放",
	"VrHelp_TitleGraphic_Help_Left4": "暫停",
	"VrHelp_TitleGraphic_Help_Left5": "下一個",
	"VrHelp_TitleGraphic_Help_Right1": "倒帶",
	"VrHelp_TitleGraphic_Help_Right2": "快進",
	"VrHelp_TitleScreen_Help_Left1": "更改來源",
	"VrHelp_TitleScreen_Help_Left2": "上一個",
	"VrHelp_TitleScreen_Help_Left3": "播放",
	"VrHelp_TitleScreen_Help_Left4": "暫停",
	"VrHelp_TitleScreen_Help_Left5": "下一個",
	"VrHelp_TitleScreen_Help_Right1": "倒帶",
	"VrHelp_TitleScreen_Help_Right2": "快進",
	"VrHelp_VideoNowPlaying_Help_Left1": "更改來源",
	"VrHelp_VideoNowPlaying_Help_Left2": "DVD 菜單",
	"VrHelp_VideoNowPlaying_Help_Left3": "上一個",
	"VrHelp_VideoNowPlaying_Help_Left4": "播放 / 暫停",
	"VrHelp_VideoNowPlaying_Help_Left5": "下一個",
	"VrHelp_VideoNowPlaying_Help_Right1": "攝像頭角度",
	"VrHelp_VideoNowPlaying_Help_Right2": "副標題",
	"VrHelp_VideoNowPlaying_Help_Right3": "家長鎖",
	"VrHelp_VideoNowPlaying_Help_Right4": "設置",
	"VrHelp_VideoNowPlaying_Help_Right5": "顯示調整",
	"Widescreen": "16:9 寬螢幕",
	"WrongPIN": "密碼錯誤",
	"displayAdjustments": "顯示調整",
};

framework.registerAppDictLoaded("dvd", "mn_TW");