var Localization_dvdAppDict_no_NO = {
	//"stringId" : "localString"
	"Adjust": "Justere",
	"AspectRatio": "Høyde-/breddeforhold",
	"AudioSettings": "Lydinnstillinger",
	"Brightness": "Lysstyrke",
	"Chapter": "Kapittel",
	"ChooseMaxAllowRating": "Velg maks. tillatte rangering",
	"Close": "Skjul knapper",
	"Color": "Fargetone",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "Mekanisk feil, DVD-spiller",
	"DVDRegionViolation": "Regionsfeil, DVD",
	"DiscError": "Diskfeil",
	"DiscErrorNotification": "Det oppstod en diskfeil",
	"DiscInserted": "Plate satt inn",
	"DiscNotPlayable": "Platen kan ikke spilles av.",
	"EditPinCode": "Rediger PIN-kode",
	"EjectingDisc": "Løser ut DVD",
	"EnterFactoryPIN": "Angi fab.-PIN, n.st.",
	"EnterNewPin": "Angi ny PIN",
	"EnterPIN": "Legg inn PIN",
	"InitializePINCode": "Initialiser PIN-kode",
	"IsThisCorrect": "Er dette korrekt?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Laster",
	"LostVideoSignal": "Tapt videosignal",
	"MechanicalError": "Mekanisk feil, DVD",
	"NoDiscInserted": "Ingen plate satt inn",
	"NoVideoSignalAvailable": "Ingen videosignaler er tilgjengelige.",
	"None": "--",
	"PG13": "PG12",
	"PINSet": "Stille inn PIN",
	"Panscan": "4:3 Pan-scan",
	"ParentalLock": "Barnelås",
	"ParentalLockRating": "Rangering, barnelås",
	"R15": "R15",
	"R18": "R18",
	"Reset": "Farge",
	"ResetPinCode": "Tilbakestill PIN-kode",
	"SelectController": "Velg",
	"SelectRootMenuTooltip": "Hovedmeny",
	"Settings": "Innstillinger",
	"Tint": "Farge",
	"Track": "Spor {trackNumber}",
	"VideoNotDisplayed": "Av sikkerhetsgrunner blir video ikke vist under kjøring.",
	"VrHelp_DVDGraphic_Help_Left1": "Entertainment",
	"VrHelp_DVDGraphic_Help_Left2": "Previous",
	"VrHelp_DVDGraphic_Help_Left3": "Play / Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Next",
	"VrHelp_DVDGraphic_Help_Left5": "DVD Settings",
	"VrHelp_DVDSettings_Help_Left1": "Sound Settings",
	"VrHelp_DVDSettings_Help_Left2": "Aspect Ratio",
	"VrHelp_ParentalLockRating_Help_Left1": "None",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "Parental Lock Rating",
	"VrHelp_ParentalLock_Help1_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help1_Left3": "Reset PIN Code",
	"VrHelp_ParentalLock_Help2_Left1": "Parental Lock On/Off",
	"VrHelp_ParentalLock_Help2_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help2_Left3": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_TitleGraphic_Help_Left1": "Change Source",
	"VrHelp_TitleGraphic_Help_Left2": "Previous",
	"VrHelp_TitleGraphic_Help_Left3": "Play",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Next",
	"VrHelp_TitleGraphic_Help_Right1": "Rewind",
	"VrHelp_TitleGraphic_Help_Right2": "Fast Forward",
	"VrHelp_TitleScreen_Help_Left1": "Change Source",
	"VrHelp_TitleScreen_Help_Left2": "Previous",
	"VrHelp_TitleScreen_Help_Left3": "Play",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Next",
	"VrHelp_TitleScreen_Help_Right1": "Rewind",
	"VrHelp_TitleScreen_Help_Right2": "Fast Forward",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entertainment",
	"VrHelp_VideoNowPlaying_Help_Left2": "Root Menu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Previous",
	"VrHelp_VideoNowPlaying_Help_Left4": "Play / Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Next",
	"VrHelp_VideoNowPlaying_Help_Right1": "Camera Angle",
	"VrHelp_VideoNowPlaying_Help_Right2": "Subtitles",
	"VrHelp_VideoNowPlaying_Help_Right3": "Parental Lock",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD Settings",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video Settings",
	"Widescreen": "16:9 bredformat",
	"WrongPIN": "Feil PIN",
	"displayAdjustments": "Vis justeringer",
};

framework.registerAppDictLoaded("dvd", "no_NO");