var Localization_dvdAppDict_sr_RS = {
	//"stringId" : "localString"
	"Adjust": "Podesi",
	"AspectRatio": "Odnos širina/visina",
	"AudioSettings": "Audio postavke",
	"Brightness": "Osvetlj.",
	"Chapter": "Poglavlje",
	"ChooseMaxAllowRating": "Odaberite maks. dozvoljenu ocenu",
	"Close": "Sakri dugmiće",
	"Color": "Boja",
	"Contrast": "Kontrast",
	"DVD": "DVD",
	"DVDMechanical": "Mehanička greška u DVD plejeru",
	"DVDRegionViolation": "Narušavanje DVD regiona",
	"DiscError": "Greška na disku",
	"DiscErrorNotification": "Došlo je do greške na disku",
	"DiscInserted": "Disk je ubačen",
	"DiscNotPlayable": " Disk ne može da se reprodukuje.",
	"EditPinCode": "Uredi PIN kod",
	"EjectingDisc": "Izbacivanje diska",
	"EnterFactoryPIN": "Fabr. PIN za res.",
	"EnterNewPin": "Unesite novi PIN",
	"EnterPIN": "Unesite PIN",
	"InitializePINCode": "Inicijalizuj PIN kod",
	"IsThisCorrect": "Da li je ovo tačno?",
	"Letterbox": "4:3 Letterbox",
	"Loading": "Učitavanje",
	"LostVideoSignal": "Video signal izgubljen",
	"MechanicalError": "Mehanička greška na DVD-u",
	"NoDiscInserted": "Nije ubačen nijedan disk",
	"NoVideoSignalAvailable": "Nije dostupan video signal",
	"None": "--",
	"PG13": "PG12",
	"PINSet": "PIN je postavljen",
	"Panscan": "4:3 Pan-scan",
	"ParentalLock": "Roditeljska blokada",
	"ParentalLockRating": "Ocena roditeljske blokade",
	"R15": "R15",
	"R18": "R18",
	"Reset": "Resetuj",
	"ResetPinCode": "Resetuj PIN kod",
	"SelectController": "Odaberi",
	"SelectRootMenuTooltip": "Osnovni meni",
	"Settings": "Postavke",
	"Tint": "Boja",
	"Track": "Pesma {trackNumber}",
	"VideoNotDisplayed": "Iz sigurnosnih razloga, Video neće biti prikazan tokom vožnje.",
	"VrHelp_DVDGraphic_Help_Left1": "Entertainment",
	"VrHelp_DVDGraphic_Help_Left2": "Previous",
	"VrHelp_DVDGraphic_Help_Left3": "Play / Pause",
	"VrHelp_DVDGraphic_Help_Left4": "Next",
	"VrHelp_DVDGraphic_Help_Left5": "DVD Settings",
	"VrHelp_DVDSettings_Help_Left1": "Sound Settings",
	"VrHelp_DVDSettings_Help_Left2": "Aspect Ratio",
	"VrHelp_ParentalLockRating_Help_Left1": "None",
	"VrHelp_ParentalLockRating_Help_Left2": "G",
	"VrHelp_ParentalLockRating_Help_Left3": "PG 12",
	"VrHelp_ParentalLockRating_Help_Left4": "R15+",
	"VrHelp_ParentalLock_Help1_Left1": "Parental Lock Rating",
	"VrHelp_ParentalLock_Help1_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help1_Left3": "Reset PIN Code",
	"VrHelp_ParentalLock_Help2_Left1": "Parental Lock On/Off",
	"VrHelp_ParentalLock_Help2_Left2": "Edit PIN Code",
	"VrHelp_ParentalLock_Help2_Left3": "Reset PIN Code",
	"VrHelp_PinEntryNew_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryNew_Help_Left2": "OK",
	"VrHelp_PinEntryNew_Help_Left3": "Clear",
	"VrHelp_PinEntryReset_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryReset_Help_Left2": "OK",
	"VrHelp_PinEntryReset_Help_Left3": "Clear",
	"VrHelp_PinEntryUnlock_Help_Left1": "(digits 0-9)",
	"VrHelp_PinEntryUnlock_Help_Left2": "OK",
	"VrHelp_PinEntryUnlock_Help_Left3": "Clear",
	"VrHelp_TitleGraphic_Help_Left1": "Change Source",
	"VrHelp_TitleGraphic_Help_Left2": "Previous",
	"VrHelp_TitleGraphic_Help_Left3": "Play",
	"VrHelp_TitleGraphic_Help_Left4": "Pause",
	"VrHelp_TitleGraphic_Help_Left5": "Next",
	"VrHelp_TitleGraphic_Help_Right1": "Rewind",
	"VrHelp_TitleGraphic_Help_Right2": "Fast Forward",
	"VrHelp_TitleScreen_Help_Left1": "Change Source",
	"VrHelp_TitleScreen_Help_Left2": "Previous",
	"VrHelp_TitleScreen_Help_Left3": "Play",
	"VrHelp_TitleScreen_Help_Left4": "Pause",
	"VrHelp_TitleScreen_Help_Left5": "Next",
	"VrHelp_TitleScreen_Help_Right1": "Rewind",
	"VrHelp_TitleScreen_Help_Right2": "Fast Forward",
	"VrHelp_VideoNowPlaying_Help_Left1": "Entertainment",
	"VrHelp_VideoNowPlaying_Help_Left2": "Root Menu",
	"VrHelp_VideoNowPlaying_Help_Left3": "Previous",
	"VrHelp_VideoNowPlaying_Help_Left4": "Play / Pause",
	"VrHelp_VideoNowPlaying_Help_Left5": "Next",
	"VrHelp_VideoNowPlaying_Help_Right1": "Camera Angle",
	"VrHelp_VideoNowPlaying_Help_Right2": "Subtitles",
	"VrHelp_VideoNowPlaying_Help_Right3": "Parental Lock",
	"VrHelp_VideoNowPlaying_Help_Right4": "DVD Settings",
	"VrHelp_VideoNowPlaying_Help_Right5": "Video Settings",
	"Widescreen": "Široki ekran 16:9",
	"WrongPIN": "Pogrešan PIN",
	"displayAdjustments": "Podešavanja ekrana",
};

framework.registerAppDictLoaded("dvd", "sr_RS");