var Localization_commonAppDict_ms_MY = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Menu Aplikasi",
	"Auto": "Auto",
	"Back": "Kembali",
	"BrightnessTab": "Kecerahan",
	"Cancel": "Batal",
	"ColorTab": "Warna",
	"Connect": "Sambung",
	"Contacts": "Kenalan",
	"ContrastTab": "Kontras",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Peranti",
	"DisplayTab": "Paparan",
	"Download": "Muat trn",
	"FullMonthNameApr": "April",
	"FullMonthNameAug": "Ogos",
	"FullMonthNameDec": "Disember",
	"FullMonthNameFeb": "Februari",
	"FullMonthNameJan": "Januari",
	"FullMonthNameJul": "Julai",
	"FullMonthNameJun": "Jun",
	"FullMonthNameMar": "Mac",
	"FullMonthNameMay": "Mei",
	"FullMonthNameNov": "November",
	"FullMonthNameOct": "Oktober",
	"FullMonthNameSep": "September",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Menukar bahasa. Sila tunggu",
	"Loading": "Memuatkan",
	"MemoryFull": "Memori Penuh",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr",
	"MonthNameAug": "Ogo",
	"MonthNameDec": "Dis",
	"MonthNameFeb": "Feb",
	"MonthNameJan": "Jan",
	"MonthNameJul": "Jul",
	"MonthNameJun": "Jun",
	"MonthNameMar": "Mac",
	"MonthNameMay": "Mei",
	"MonthNameNov": "Nov",
	"MonthNameOct": "Okt",
	"MonthNameSep": "Sep",
	"No": "Tidak",
	"Off": "Matikan",
	"Ok": "OK",
	"On": "Aktif",
	"Quit": "Berhenti",
	"Remove": "Alih Keluar",
	"ResetTab": "Reset",
	"Retry": "Cuba Lagi",
	"SbnVoiceNotSupported": "Suara Tidak Disokong",
	"SbnVoiceRecognition": "Pengecaman Suara",
	"SbnWaitForTone": "Tunggu Nada",
	"Setup": "Persediaan",
	"Siri": "Siri",
	"SoundTab": "Bunyi",
	"SpacebarText": "space",
	"SystemTab": "Sistem",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Warna",
	"TooltipFavorites": "Kegemaran",
	"Tooltip_IcnUmpAddCall": "Tambah Panggilan",
	"Tooltip_IcnUmpAddContact": "Tambah Kenalan",
	"Tooltip_IcnUmpAddSong": "Tambah Lagu",
	"Tooltip_IcnUmpAmPm": "Tukar AM/PM",
	"Tooltip_IcnUmpApps": "Aplikasi",
	"Tooltip_IcnUmpAutoMem": "Memori Auto",
	"Tooltip_IcnUmpBack": "Kembali",
	"Tooltip_IcnUmpBack15s": "Undur 15 Saat",
	"Tooltip_IcnUmpBack30s": "Undur 30 Saat",
	"Tooltip_IcnUmpBargeIn": "Cakap Sekarang",
	"Tooltip_IcnUmpBookmark": "Penanda halaman",
	"Tooltip_IcnUmpBookmark_Sel": "Penanda Halaman",
	"Tooltip_IcnUmpBookmark_Unsel": "Penanda Halaman",
	"Tooltip_IcnUmpCall": "Panggilan",
	"Tooltip_IcnUmpCamAngle": "Sudut Kamera",
	"Tooltip_IcnUmpCloseUmp": "Sembunyikan Butang",
	"Tooltip_IcnUmpCommMenu": "Komunikasi",
	"Tooltip_IcnUmpConnectionManager": "Pengurus Sambungan",
	"Tooltip_IcnUmpCurrentList": "Senarai Stesen",
	"Tooltip_IcnUmpDelete": "Padam",
	"Tooltip_IcnUmpDialpad": "Pad dail",
	"Tooltip_IcnUmpEject": "Keluarkan",
	"Tooltip_IcnUmpEntMenu": "Hiburan",
	"Tooltip_IcnUmpEqualizer": "Aturan Bunyi",
	"Tooltip_IcnUmpFavorite_Favorite": "Padamkan daripada Kegemaran",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Tambah pada Kegemaran",
	"Tooltip_IcnUmpFolder_Up": "Menu Atas",
	"Tooltip_IcnUmpFwd15s": "Ke hadapan 15 Saat",
	"Tooltip_IcnUmpFwd30s": "Ke Hadapan 30 Saat",
	"Tooltip_IcnUmpGenre": "Genre",
	"Tooltip_IcnUmpHD_Sel": "HD Dimatikan",
	"Tooltip_IcnUmpHD_Unsel": "HD Dihidupkan",
	"Tooltip_IcnUmpHangup": "Tamatkan Panggilan",
	"Tooltip_IcnUmpItunesTag_Tagged": "Padamkan Teg untuk iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Teg",
	"Tooltip_IcnUmpLock_Locked": "Buka",
	"Tooltip_IcnUmpLock_Unlocked": "Kunci",
	"Tooltip_IcnUmpMap": "Peta",
	"Tooltip_IcnUmpMergecall": "Gabungkan Panggilan",
	"Tooltip_IcnUmpMic": "Hebahan",
	"Tooltip_IcnUmpMinus": "Kurangkan",
	"Tooltip_IcnUmpMore": "Lebih Seperti Ini",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Bisu",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Nyah Bisu",
	"Tooltip_IcnUmpNextAudio": "Seterusnya",
	"Tooltip_IcnUmpNowPlaying": "Sedang Dimainkan",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Pindahkan ke Telefon Bimbit",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Pindahkan Ke Kenderaan",
	"Tooltip_IcnUmpPlayOrPause": "Main/Jeda",
	"Tooltip_IcnUmpPlayPause_Pause": "Jeda",
	"Tooltip_IcnUmpPlayPause_Play": "Main",
	"Tooltip_IcnUmpPlayPause_Stop": "Berhenti",
	"Tooltip_IcnUmpPlus": "Tambah",
	"Tooltip_IcnUmpPreviousAudio": "Sebelumnya",
	"Tooltip_IcnUmpRepeat_List": "Ulang",
	"Tooltip_IcnUmpRepeat_None": "Ulang",
	"Tooltip_IcnUmpRepeat_Song": "Ulang",
	"Tooltip_IcnUmpReply": "Balas",
	"Tooltip_IcnUmpReplyToAll": "Balas Semua",
	"Tooltip_IcnUmpReset": "Tetapkan Semula",
	"Tooltip_IcnUmpScan_Sel": "Hentikan Imbasan",
	"Tooltip_IcnUmpScan_Unsel": "Imbas",
	"Tooltip_IcnUmpSettings": "Tetapan",
	"Tooltip_IcnUmpShuffle_Folder": "Rawak",
	"Tooltip_IcnUmpShuffle_Off": "Rawak",
	"Tooltip_IcnUmpShuffle_On": "Rawak",
	"Tooltip_IcnUmpStation_Create": "Cipta Stesen",
	"Tooltip_IcnUmpSubtitles": "Sari Kata",
	"Tooltip_IcnUmpSwapCalls_01": "Tukar Panggilan",
	"Tooltip_IcnUmpSwapCalls_02": "Tukar Panggilan",
	"Tooltip_IcnUmpSwitchView": "Tukar Paparan",
	"Tooltip_IcnUmpSwitchView_1": "Tukar Paparan",
	"Tooltip_IcnUmpSwitchView_2": "Tukar Paparan",
	"Tooltip_IcnUmpSwitchView_3": "Tukar Paparan",
	"Tooltip_IcnUmpThumbsDown_Sel": "Tidak Suka",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Tidak Suka",
	"Tooltip_IcnUmpThumbsUp_Sel": "Tanda Suka",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Tanda Suka",
	"Tooltip_IcnUmpTopList": "Folder Punca",
	"Tooltip_IcnUmpTrafficAlert": "Makluman Trafik (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Makluman Lalu Lintas  (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Makluman Lalu Lintas  (TA)",
	"Tooltip_IcnUmpTune": "Frekuensi Radio",
	"Tooltip_IcnUmpVideoSet": "Tetapan Video",
	"VehicleTab": "Kereta",
	"VolumeTab": "Lantang",
	"VuiHelpDefaultTitle": "Arahan Tersedia Termasuk:",
	"Yes": "Ya",
	"delete": "Padamkan",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Redam Dimatikan",
	"muteOn": "Redam Dihidupkan",
	"shortRepnHours": "j",
	"shortRepnMins": "m",
	"shortRepnSecs": "s",
	"tempUnitsCelsius": "C",
	"tempUnitsFahrenheit": "F",
	"volUnitsGallons": "gelen",
	"volUnitsLiters": "liter",
};

framework.registerAppDictLoaded("common", "ms_MY");