var Localization_commonAppDict_lv_LV = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Lietojumprogrammas izvēlne",
	"Auto": "Auto",
	"Back": "Atpakaļ",
	"BrightnessTab": "Spilgt.",
	"Cancel": "Atcelt",
	"ColorTab": "Krāsa",
	"Connect": "Savienot",
	"Contacts": "Kontakti",
	"ContrastTab": "Kontr.",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Ierīces",
	"DisplayTab": "Displejs",
	"Download": "Lejupiel.",
	"FullMonthNameApr": "Aprīlis",
	"FullMonthNameAug": "Augusts",
	"FullMonthNameDec": "Decembris",
	"FullMonthNameFeb": "Februāris",
	"FullMonthNameJan": "Janvāris",
	"FullMonthNameJul": "Jūlijs",
	"FullMonthNameJun": "Jūnijs",
	"FullMonthNameMar": "Marts",
	"FullMonthNameMay": "Maijs",
	"FullMonthNameNov": "Novembris",
	"FullMonthNameOct": "Oktobris",
	"FullMonthNameSep": "Septembris",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Maina valodu. Lūdzu, uzgaidiet.",
	"Loading": "Ielādē",
	"MemoryFull": "Atmiņa ir pilna",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr.",
	"MonthNameAug": "Aug.",
	"MonthNameDec": "Dec.",
	"MonthNameFeb": "Feb.",
	"MonthNameJan": "Jan.",
	"MonthNameJul": "Jūl.",
	"MonthNameJun": "Jūn.",
	"MonthNameMar": "Mar.",
	"MonthNameMay": "Maijs",
	"MonthNameNov": "Nov.",
	"MonthNameOct": "Okt.",
	"MonthNameSep": "Sep.",
	"No": "Nē",
	"Off": "Izslēgt",
	"Ok": "Labi",
	"On": "Ieslēgt",
	"Quit": "Iziet",
	"Remove": "Noņemt",
	"ResetTab": "Atiestatīt",
	"Retry": "Atkārtot",
	"SbnVoiceNotSupported": "Balss netiek atbalstīta",
	"SbnVoiceRecognition": "Balss atpazīšana",
	"SbnWaitForTone": "Gaidīt signālu",
	"Setup": "Iestatīšana",
	"Siri": "Siri",
	"SoundTab": "Skaņa",
	"SpacebarText": "atstarpe",
	"SystemTab": "Sistēma",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Tonis",
	"TooltipFavorites": "Izlase",
	"Tooltip_IcnUmpAddCall": "Pievienot zvanu",
	"Tooltip_IcnUmpAddContact": "Pievienot kontaktu",
	"Tooltip_IcnUmpAddSong": "Pievienot dziesmu",
	"Tooltip_IcnUmpAmPm": "Pārslēgt AM/PM",
	"Tooltip_IcnUmpApps": "Lietojumprogrammas",
	"Tooltip_IcnUmpAutoMem": "Automātiskā atmiņa",
	"Tooltip_IcnUmpBack": "Atpakaļ",
	"Tooltip_IcnUmpBack15s": "15 sekundes atpakaļ",
	"Tooltip_IcnUmpBack30s": "30 sekundes atpakaļ",
	"Tooltip_IcnUmpBargeIn": "Runājiet tagad",
	"Tooltip_IcnUmpBookmark": "Grāmatzīme",
	"Tooltip_IcnUmpBookmark_Sel": "Grāmatzīme",
	"Tooltip_IcnUmpBookmark_Unsel": "Grāmatzīme",
	"Tooltip_IcnUmpCall": "Zvanīt",
	"Tooltip_IcnUmpCamAngle": "Kameras leņķis",
	"Tooltip_IcnUmpCloseUmp": "Aizv.",
	"Tooltip_IcnUmpCommMenu": "Saziņa",
	"Tooltip_IcnUmpConnectionManager": "Savienojumu pārvaldnieks",
	"Tooltip_IcnUmpCurrentList": "Staciju saraksts",
	"Tooltip_IcnUmpDelete": "Dzēst",
	"Tooltip_IcnUmpDialpad": "Tastatūra",
	"Tooltip_IcnUmpEject": "Izstumt",
	"Tooltip_IcnUmpEntMenu": "Izklaide",
	"Tooltip_IcnUmpEqualizer": "Skaņas iestatījumi",
	"Tooltip_IcnUmpFavorite_Favorite": "Noņemt no izlases",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Pievienot izlasei",
	"Tooltip_IcnUmpFolder_Up": "Izvēlne augšup",
	"Tooltip_IcnUmpFwd15s": "15 sekundes uz priekšu",
	"Tooltip_IcnUmpFwd30s": "30 sekundes uz priekšu",
	"Tooltip_IcnUmpGenre": "Žanrs",
	"Tooltip_IcnUmpHD_Sel": "HD izslēgta",
	"Tooltip_IcnUmpHD_Unsel": "HD ieslēgta",
	"Tooltip_IcnUmpHangup": "Nolikt klausuli",
	"Tooltip_IcnUmpItunesTag_Tagged": "Noņemt atzīmi no iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Atzīme",
	"Tooltip_IcnUmpLock_Locked": "Atbloķēt",
	"Tooltip_IcnUmpLock_Unlocked": "Bloķēt",
	"Tooltip_IcnUmpMap": "Karte",
	"Tooltip_IcnUmpMergecall": "Apvienot zvanus",
	"Tooltip_IcnUmpMic": "Runāt",
	"Tooltip_IcnUmpMinus": "Samazināt",
	"Tooltip_IcnUmpMore": "Vairāk kā šis",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Izslēgt skaņu",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Ieslēgt skaņu",
	"Tooltip_IcnUmpNextAudio": "Nākamais",
	"Tooltip_IcnUmpNowPlaying": "Tagad atskaņo",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Pāradresēt uz tālruni",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Pāradresēt uz transportlīdzekli",
	"Tooltip_IcnUmpPlayOrPause": "Atskaņot/Pauze",
	"Tooltip_IcnUmpPlayPause_Pause": "Pauze",
	"Tooltip_IcnUmpPlayPause_Play": "Atskaņot",
	"Tooltip_IcnUmpPlayPause_Stop": "Apturēt",
	"Tooltip_IcnUmpPlus": "Palielināt",
	"Tooltip_IcnUmpPreviousAudio": "Iepriekšējais",
	"Tooltip_IcnUmpRepeat_List": "Atkārtot",
	"Tooltip_IcnUmpRepeat_None": "Atkārtot",
	"Tooltip_IcnUmpRepeat_Song": "Atkārtot",
	"Tooltip_IcnUmpReply": "Atbildēt",
	"Tooltip_IcnUmpReplyToAll": "Atbildēt visiem",
	"Tooltip_IcnUmpReset": "Atiestatīt",
	"Tooltip_IcnUmpScan_Sel": "Apturēt meklēšanu",
	"Tooltip_IcnUmpScan_Unsel": "Meklēt",
	"Tooltip_IcnUmpSettings": "Iestatījumi",
	"Tooltip_IcnUmpShuffle_Folder": "Jauktā secībā",
	"Tooltip_IcnUmpShuffle_Off": "Jauktā secībā",
	"Tooltip_IcnUmpShuffle_On": "Jauktā secībā",
	"Tooltip_IcnUmpStation_Create": "Izveidojiet staciju",
	"Tooltip_IcnUmpSubtitles": "Subtitri",
	"Tooltip_IcnUmpSwapCalls_01": "Apmainīt zvanus",
	"Tooltip_IcnUmpSwapCalls_02": "Apmainīt zvanus",
	"Tooltip_IcnUmpSwitchView": "Pārslēgt skatu",
	"Tooltip_IcnUmpSwitchView_1": "Pārslēgt skatu",
	"Tooltip_IcnUmpSwitchView_2": "Pārslēgt skatu",
	"Tooltip_IcnUmpSwitchView_3": "Pārslēgt skatu",
	"Tooltip_IcnUmpThumbsDown_Sel": "Īkšķis uz leju",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Īkšķis uz leju",
	"Tooltip_IcnUmpThumbsUp_Sel": "Īkšķis uz augšu",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Īkšķis uz augšu",
	"Tooltip_IcnUmpTopList": "Saknes mape",
	"Tooltip_IcnUmpTrafficAlert": "Satiksmes paziņojums (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Satiksmes paziņojums (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Satiksmes paziņojums (TA)",
	"Tooltip_IcnUmpTune": "Regulēt",
	"Tooltip_IcnUmpVideoSet": "Video iestatījumi",
	"VehicleTab": "Transp.",
	"VolumeTab": "Skaļums",
	"VuiHelpDefaultTitle": "Pieejamo komandu saraksts:",
	"Yes": "Jā",
	"delete": "Dzēst",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Skaņa ieslēgta",
	"muteOn": "Skaņa izslēgta",
	"shortRepnHours": "h",
	"shortRepnMins": "m",
	"shortRepnSecs": "s",
	"tempUnitsCelsius": "C",
	"tempUnitsFahrenheit": "F",
	"volUnitsGallons": "galoni",
	"volUnitsLiters": "litri",
};

framework.registerAppDictLoaded("common", "lv_LV");