var Localization_commonAppDict_hu_HU = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Menu alkalmazások",
	"Auto": "Auto",
	"Back": "Vissza",
	"BrightnessTab": "Fényerő",
	"Cancel": "Mégse",
	"ColorTab": "Szín",
	"Connect": "Csatl.",
	"Contacts": "Kapcsolatok",
	"ContrastTab": "Kontraszt",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Eszközök",
	"DisplayTab": "Képer.",
	"Download": "Letöltés",
	"FullMonthNameApr": "Április",
	"FullMonthNameAug": "Augusztus",
	"FullMonthNameDec": "December",
	"FullMonthNameFeb": "Február",
	"FullMonthNameJan": "Január",
	"FullMonthNameJul": "Július",
	"FullMonthNameJun": "Június",
	"FullMonthNameMar": "Március",
	"FullMonthNameMay": "Május",
	"FullMonthNameNov": "November",
	"FullMonthNameOct": "Október",
	"FullMonthNameSep": "Szeptember",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Nyelvváltoztatás. Várjon.",
	"Loading": "Betöltés",
	"MemoryFull": "Memória megtelt.",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Ápr.",
	"MonthNameAug": "Aug.",
	"MonthNameDec": "Dec.",
	"MonthNameFeb": "Feb.",
	"MonthNameJan": "Jan.",
	"MonthNameJul": "Júl.",
	"MonthNameJun": "Jún.",
	"MonthNameMar": "Márc.",
	"MonthNameMay": "Máj.",
	"MonthNameNov": "Nov.",
	"MonthNameOct": "Okt.",
	"MonthNameSep": "Szept.",
	"No": "Nem",
	"Off": "Ki",
	"Ok": "OK",
	"On": "Be",
	"Quit": "Kilépés",
	"Remove": "Eltávolítás",
	"ResetTab": "Visszaáll.",
	"Retry": "Újraprób.",
	"SbnVoiceNotSupported": "Nem támogatott a hangfelismerés.",
	"SbnVoiceRecognition": "Hangfelismerés",
	"SbnWaitForTone": "Várjon a hangjelzésre.",
	"Setup": "Beállítás",
	"Siri": "Siri",
	"SoundTab": "Hang",
	"SpacebarText": "szóköz",
	"SystemTab": "Rendszer",
	"TimeLabelAm": "de.",
	"TimeLabelPm": "du.",
	"TintTab": "Tónus",
	"TooltipFavorites": "Kedvencek",
	"Tooltip_IcnUmpAddCall": "Hívás hozzáadása",
	"Tooltip_IcnUmpAddContact": "Névjegy hozzáadása",
	"Tooltip_IcnUmpAddSong": "Dal hozzáadása",
	"Tooltip_IcnUmpAmPm": "De./du. átváltás",
	"Tooltip_IcnUmpApps": "Alkalmazások",
	"Tooltip_IcnUmpAutoMem": "Automatikus memória",
	"Tooltip_IcnUmpBack": "Vissza",
	"Tooltip_IcnUmpBack15s": "Vissza 15 másodperccel",
	"Tooltip_IcnUmpBack30s": "Vissza 30 másodperccel",
	"Tooltip_IcnUmpBargeIn": "Most beszéljen",
	"Tooltip_IcnUmpBookmark": "Könyvjelző",
	"Tooltip_IcnUmpBookmark_Sel": "Könyvjelző",
	"Tooltip_IcnUmpBookmark_Unsel": "Könyvjelző",
	"Tooltip_IcnUmpCall": "Hívás",
	"Tooltip_IcnUmpCamAngle": "Kameraszög",
	"Tooltip_IcnUmpCloseUmp": "Gombok elrejtése",
	"Tooltip_IcnUmpCommMenu": "Kommunikáció",
	"Tooltip_IcnUmpConnectionManager": "Csatlakozáskezelő",
	"Tooltip_IcnUmpCurrentList": "Állomáslista",
	"Tooltip_IcnUmpDelete": "Törlés",
	"Tooltip_IcnUmpDialpad": "Tárcsázás",
	"Tooltip_IcnUmpEject": "Kiadás",
	"Tooltip_IcnUmpEntMenu": "Szórakozás",
	"Tooltip_IcnUmpEqualizer": "Hangbeállítások",
	"Tooltip_IcnUmpFavorite_Favorite": "Eltávolítás a kedvencek közül",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Hozzáadás a kedvencekhez",
	"Tooltip_IcnUmpFolder_Up": "Menü fel",
	"Tooltip_IcnUmpFwd15s": "Előre 15 másodperccel",
	"Tooltip_IcnUmpFwd30s": "Előre 30 másodperccel",
	"Tooltip_IcnUmpGenre": "Műfaj",
	"Tooltip_IcnUmpHD_Sel": "HD ki",
	"Tooltip_IcnUmpHD_Unsel": "HD be",
	"Tooltip_IcnUmpHangup": "Vonal bontása",
	"Tooltip_IcnUmpItunesTag_Tagged": "iTunes-címke eltávolítása",
	"Tooltip_IcnUmpItunesTag_Untagged": "Címke",
	"Tooltip_IcnUmpLock_Locked": "Feloldás",
	"Tooltip_IcnUmpLock_Unlocked": "Zár",
	"Tooltip_IcnUmpMap": "Térkép",
	"Tooltip_IcnUmpMergecall": "Hívások összevonása",
	"Tooltip_IcnUmpMic": "Hangüzenet",
	"Tooltip_IcnUmpMinus": "Csökkentés",
	"Tooltip_IcnUmpMore": "További hasonlók",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Némítás",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Némítás megszüntetése",
	"Tooltip_IcnUmpNextAudio": "Következő",
	"Tooltip_IcnUmpNowPlaying": "Most játszott",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Mobilkészüléknek átadás",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Járműnek átadás",
	"Tooltip_IcnUmpPlayOrPause": "Lejátszás/megállítás",
	"Tooltip_IcnUmpPlayPause_Pause": "Szünet",
	"Tooltip_IcnUmpPlayPause_Play": "Lejátszás",
	"Tooltip_IcnUmpPlayPause_Stop": "Leállítás",
	"Tooltip_IcnUmpPlus": "Növelés",
	"Tooltip_IcnUmpPreviousAudio": "Előző",
	"Tooltip_IcnUmpRepeat_List": "Ismétlés",
	"Tooltip_IcnUmpRepeat_None": "Ismétlés",
	"Tooltip_IcnUmpRepeat_Song": "Ismétlés",
	"Tooltip_IcnUmpReply": "Válasz",
	"Tooltip_IcnUmpReplyToAll": "Válasz mindenkinek",
	"Tooltip_IcnUmpReset": "Visszaállítás",
	"Tooltip_IcnUmpScan_Sel": "Állomáskeresés leállítása",
	"Tooltip_IcnUmpScan_Unsel": "Állomáskeresés",
	"Tooltip_IcnUmpSettings": "Beállítások",
	"Tooltip_IcnUmpShuffle_Folder": "Keverés",
	"Tooltip_IcnUmpShuffle_Off": "Keverés",
	"Tooltip_IcnUmpShuffle_On": "Keverés",
	"Tooltip_IcnUmpStation_Create": "Állomás létrehozása",
	"Tooltip_IcnUmpSubtitles": "Felirat",
	"Tooltip_IcnUmpSwapCalls_01": "Hívásváltás",
	"Tooltip_IcnUmpSwapCalls_02": "Hívásváltás",
	"Tooltip_IcnUmpSwitchView": "Nézetváltás",
	"Tooltip_IcnUmpSwitchView_1": "Nézetváltás",
	"Tooltip_IcnUmpSwitchView_2": "Nézetváltás",
	"Tooltip_IcnUmpSwitchView_3": "Nézetváltás",
	"Tooltip_IcnUmpThumbsDown_Sel": "Nem tetszik",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Nem tetszik",
	"Tooltip_IcnUmpThumbsUp_Sel": "Tetszik",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Tetszik",
	"Tooltip_IcnUmpTopList": "Gyökérmappa",
	"Tooltip_IcnUmpTrafficAlert": "Útinform (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Útinform (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Útinform (TA)",
	"Tooltip_IcnUmpTune": "Finomhangolás",
	"Tooltip_IcnUmpVideoSet": "Videobeállítások",
	"VehicleTab": "Jármű",
	"VolumeTab": "Hangerő",
	"VuiHelpDefaultTitle": "Kiadható parancsok:",
	"Yes": "Igen",
	"delete": "Törlés",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Elnémítás KI",
	"muteOn": "Elnémítás BE",
	"shortRepnHours": "ó",
	"shortRepnMins": "p",
	"shortRepnSecs": "mp",
	"tempUnitsCelsius": "C",
	"tempUnitsFahrenheit": "F",
	"volUnitsGallons": "gallon",
	"volUnitsLiters": "liter",
};

framework.registerAppDictLoaded("common", "hu_HU");