var Localization_commonAppDict_ro_RO = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Meniu aplicaţii",
	"Auto": "Auto",
	"Back": "Înapoi",
	"BrightnessTab": "Luminozit.",
	"Cancel": "Anulare",
	"ColorTab": "Culoare",
	"Connect": "Conectare",
	"Contacts": "Contacte",
	"ContrastTab": "Contrast",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Dispoziti.",
	"DisplayTab": "Afişaj",
	"Download": "Descarcă",
	"FullMonthNameApr": "Aprilie",
	"FullMonthNameAug": "August",
	"FullMonthNameDec": "Decembrie",
	"FullMonthNameFeb": "Februarie",
	"FullMonthNameJan": "Ianuarie",
	"FullMonthNameJul": "Iulie",
	"FullMonthNameJun": "Iunie",
	"FullMonthNameMar": "Martie",
	"FullMonthNameMay": "Mai",
	"FullMonthNameNov": "Noiembrie",
	"FullMonthNameOct": "Octombrie",
	"FullMonthNameSep": "Septembrie",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Schimbare limbă. Aşteptaţi",
	"Loading": "Se încarcă",
	"MemoryFull": "Memorie plină",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr",
	"MonthNameAug": "Aug",
	"MonthNameDec": "Dec",
	"MonthNameFeb": "Feb",
	"MonthNameJan": "Ian",
	"MonthNameJul": "Iul",
	"MonthNameJun": "Iun",
	"MonthNameMar": "Mar",
	"MonthNameMay": "Mai",
	"MonthNameNov": "Nov",
	"MonthNameOct": "Oct",
	"MonthNameSep": "Sep",
	"No": "Nu",
	"Off": "Oprit",
	"Ok": "OK",
	"On": "Pornit",
	"Quit": "Renunţare",
	"Remove": "Eliminare",
	"ResetTab": "Resetare",
	"Retry": "Reîncerc.",
	"SbnVoiceNotSupported": "Voce nedisponibilă",
	"SbnVoiceRecognition": "Recunoaşterea vocii",
	"SbnWaitForTone": "Aşteptare ton",
	"Setup": "Configurare",
	"Siri": "Siri",
	"SoundTab": "Sunet",
	"SpacebarText": "spaţiu",
	"SystemTab": "Sistem",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Nuanţă",
	"TooltipFavorites": "Favorite",
	"Tooltip_IcnUmpAddCall": "Adăugare apel",
	"Tooltip_IcnUmpAddContact": "Adăugare contact",
	"Tooltip_IcnUmpAddSong": "Adăugare melodie",
	"Tooltip_IcnUmpAmPm": "Comutare AM/PM",
	"Tooltip_IcnUmpApps": "Aplicaţii",
	"Tooltip_IcnUmpAutoMem": "Memorie automată",
	"Tooltip_IcnUmpBack": "Înapoi",
	"Tooltip_IcnUmpBack15s": "Înapoi 15 secunde",
	"Tooltip_IcnUmpBack30s": "Înapoi 30 secunde",
	"Tooltip_IcnUmpBargeIn": "Vorbiţi acum",
	"Tooltip_IcnUmpBookmark": "Marcaj",
	"Tooltip_IcnUmpBookmark_Sel": "Marcaj",
	"Tooltip_IcnUmpBookmark_Unsel": "Marcaj",
	"Tooltip_IcnUmpCall": "Apel",
	"Tooltip_IcnUmpCamAngle": "Unghi cameră",
	"Tooltip_IcnUmpCloseUmp": "Ascundere butoane",
	"Tooltip_IcnUmpCommMenu": "Comunicare",
	"Tooltip_IcnUmpConnectionManager": "Manager conexiuni",
	"Tooltip_IcnUmpCurrentList": "Listă de posturi",
	"Tooltip_IcnUmpDelete": "Ştergere",
	"Tooltip_IcnUmpDialpad": "Tastatură telefonică",
	"Tooltip_IcnUmpEject": "Ejectare",
	"Tooltip_IcnUmpEntMenu": "Divertisment",
	"Tooltip_IcnUmpEqualizer": "Setări sunet",
	"Tooltip_IcnUmpFavorite_Favorite": "Elimină din Favorite",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Adăugare la Favorite",
	"Tooltip_IcnUmpFolder_Up": "Meniu anterior",
	"Tooltip_IcnUmpFwd15s": "Înainte 15 secunde",
	"Tooltip_IcnUmpFwd30s": "Înainte 30 de secunde",
	"Tooltip_IcnUmpGenre": "Gen",
	"Tooltip_IcnUmpHD_Sel": "HD oprit",
	"Tooltip_IcnUmpHD_Unsel": "HD pornit",
	"Tooltip_IcnUmpHangup": "Închidere",
	"Tooltip_IcnUmpItunesTag_Tagged": "Elimină eticheta pentru iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Marcare",
	"Tooltip_IcnUmpLock_Locked": "Deblocare",
	"Tooltip_IcnUmpLock_Unlocked": "Blocare",
	"Tooltip_IcnUmpMap": "Hartă",
	"Tooltip_IcnUmpMergecall": "Fuzionare apeluri",
	"Tooltip_IcnUmpMic": "Strigăt",
	"Tooltip_IcnUmpMinus": "Reducere",
	"Tooltip_IcnUmpMore": "Mai multe similare",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Dezactivare sunet",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Anulare surdină",
	"Tooltip_IcnUmpNextAudio": "Următoarea",
	"Tooltip_IcnUmpNowPlaying": "Redat acum",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Transfer unitate",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Transfer vehicul",
	"Tooltip_IcnUmpPlayOrPause": "Redare/Suspendare",
	"Tooltip_IcnUmpPlayPause_Pause": "Pauză",
	"Tooltip_IcnUmpPlayPause_Play": "Redare",
	"Tooltip_IcnUmpPlayPause_Stop": "Oprire",
	"Tooltip_IcnUmpPlus": "Creştere",
	"Tooltip_IcnUmpPreviousAudio": "Precedenta",
	"Tooltip_IcnUmpRepeat_List": "Repetare",
	"Tooltip_IcnUmpRepeat_None": "Repetare",
	"Tooltip_IcnUmpRepeat_Song": "Repetare",
	"Tooltip_IcnUmpReply": "Răspuns",
	"Tooltip_IcnUmpReplyToAll": "Răspunde la toţi",
	"Tooltip_IcnUmpReset": "Resetare",
	"Tooltip_IcnUmpScan_Sel": "Oprire scanare",
	"Tooltip_IcnUmpScan_Unsel": "Scanare",
	"Tooltip_IcnUmpSettings": "Setări",
	"Tooltip_IcnUmpShuffle_Folder": "Amestecare",
	"Tooltip_IcnUmpShuffle_Off": "Amestecare",
	"Tooltip_IcnUmpShuffle_On": "Amestecare",
	"Tooltip_IcnUmpStation_Create": "Creaţi post",
	"Tooltip_IcnUmpSubtitles": "Subtitluri",
	"Tooltip_IcnUmpSwapCalls_01": "Permutare apeluri",
	"Tooltip_IcnUmpSwapCalls_02": "Permutare apeluri",
	"Tooltip_IcnUmpSwitchView": "Comutare vizualizare",
	"Tooltip_IcnUmpSwitchView_1": "Comutare vizualizare",
	"Tooltip_IcnUmpSwitchView_2": "Comutare vizualizare",
	"Tooltip_IcnUmpSwitchView_3": "Comutare vizualizare",
	"Tooltip_IcnUmpThumbsDown_Sel": "Dezaprobare",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Dezaprobare",
	"Tooltip_IcnUmpThumbsUp_Sel": "Aprobare",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Aprobare",
	"Tooltip_IcnUmpTopList": "Folder rădăcină",
	"Tooltip_IcnUmpTrafficAlert": "Informaţii trafic",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Informaţii trafic",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Informaţii trafic",
	"Tooltip_IcnUmpTune": "Acord",
	"Tooltip_IcnUmpVideoSet": "Setări video",
	"VehicleTab": "Vehicul",
	"VolumeTab": "Volum",
	"VuiHelpDefaultTitle": "Comenzile disponibile include:",
	"Yes": "Da",
	"delete": "Eliminare",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Mut oprit",
	"muteOn": "Mut pornit",
	"shortRepnHours": "h",
	"shortRepnMins": "min",
	"shortRepnSecs": "s",
	"tempUnitsCelsius": "C",
	"tempUnitsFahrenheit": "F",
	"volUnitsGallons": "galoane",
	"volUnitsLiters": "litri",
};

framework.registerAppDictLoaded("common", "ro_RO");