var Localization_commonAppDict_de_DE = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Anwendungsmenü",
	"Auto": "Auto",
	"Back": "Zurück",
	"BrightnessTab": "Helligkeit",
	"Cancel": "Abbrechen",
	"ColorTab": "Farbe",
	"Connect": "Verbinden",
	"Contacts": "Kontakte",
	"ContrastTab": "Kontrast",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Geräte",
	"DisplayTab": "Anzeige",
	"Download": "Herunterl.",
	"FullMonthNameApr": "April",
	"FullMonthNameAug": "August",
	"FullMonthNameDec": "Dezember",
	"FullMonthNameFeb": "Februar",
	"FullMonthNameJan": "Januar",
	"FullMonthNameJul": "Juli",
	"FullMonthNameJun": "Juni",
	"FullMonthNameMar": "März",
	"FullMonthNameMay": "Mai",
	"FullMonthNameNov": "November",
	"FullMonthNameOct": "Oktober",
	"FullMonthNameSep": "September",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Ändere Sprache. Bitte warten",
	"Loading": "Wird geladen",
	"MemoryFull": "Speicher voll",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr.",
	"MonthNameAug": "Aug.",
	"MonthNameDec": "Dez.",
	"MonthNameFeb": "Feb.",
	"MonthNameJan": "Jan.",
	"MonthNameJul": "Jul.",
	"MonthNameJun": "Jun.",
	"MonthNameMar": "Mar.",
	"MonthNameMay": "Mai",
	"MonthNameNov": "Nov.",
	"MonthNameOct": "Okt.",
	"MonthNameSep": "Sep.",
	"No": "Nein",
	"Off": "Aus",
	"Ok": "OK",
	"On": "Ein",
	"Quit": "Beenden",
	"Remove": "Entfernen",
	"ResetTab": "Zurückset.",
	"Retry": "Erneut versuchen",
	"SbnVoiceNotSupported": "Sprache nicht unterstützt",
	"SbnVoiceRecognition": "Spracherkennung",
	"SbnWaitForTone": "Auf Signalton warten",
	"Setup": "Einrichtung",
	"Siri": "Siri",
	"SoundTab": "Ton",
	"SpacebarText": "leertaste",
	"SystemTab": "System",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Färbung",
	"TooltipFavorites": "Favoriten",
	"Tooltip_IcnUmpAddCall": "Anruf hinzufügen",
	"Tooltip_IcnUmpAddContact": "Kontakt hinzufügen",
	"Tooltip_IcnUmpAddSong": "Lied hinzufügen",
	"Tooltip_IcnUmpAmPm": "AM/PM umschalten",
	"Tooltip_IcnUmpApps": "Anwendungen",
	"Tooltip_IcnUmpAutoMem": "Automatischer Speicher",
	"Tooltip_IcnUmpBack": "Zurück",
	"Tooltip_IcnUmpBack15s": "15 Sekunden zurück",
	"Tooltip_IcnUmpBack30s": "30 Sekunden zurück",
	"Tooltip_IcnUmpBargeIn": "Sprechen Sie jetzt",
	"Tooltip_IcnUmpBookmark": "Lesezeichen",
	"Tooltip_IcnUmpBookmark_Sel": "Lesezeichen",
	"Tooltip_IcnUmpBookmark_Unsel": "Lesezeichen",
	"Tooltip_IcnUmpCall": "Anrufen",
	"Tooltip_IcnUmpCamAngle": "Kamerawinkel",
	"Tooltip_IcnUmpCloseUmp": "Ausblenden",
	"Tooltip_IcnUmpCommMenu": "Kommunikation",
	"Tooltip_IcnUmpConnectionManager": "Verbindungsmanager",
	"Tooltip_IcnUmpCurrentList": "Senderliste",
	"Tooltip_IcnUmpDelete": "Löschen",
	"Tooltip_IcnUmpDialpad": "Wähltastatur",
	"Tooltip_IcnUmpEject": "Auswerfen",
	"Tooltip_IcnUmpEntMenu": "Unterhaltung",
	"Tooltip_IcnUmpEqualizer": "Toneinstellungen",
	"Tooltip_IcnUmpFavorite_Favorite": "Aus Favoriten entfernen",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Zu Favoriten hinzufügen",
	"Tooltip_IcnUmpFolder_Up": "Menü nach oben",
	"Tooltip_IcnUmpFwd15s": "15 Sekunden vor",
	"Tooltip_IcnUmpFwd30s": "30 Sek. vor",
	"Tooltip_IcnUmpGenre": "Genre",
	"Tooltip_IcnUmpHD_Sel": "HD aus",
	"Tooltip_IcnUmpHD_Unsel": "HD an",
	"Tooltip_IcnUmpHangup": "Auflegen",
	"Tooltip_IcnUmpItunesTag_Tagged": "Tag für iTunes entfernen",
	"Tooltip_IcnUmpItunesTag_Untagged": "Taggen",
	"Tooltip_IcnUmpLock_Locked": "Entriegeln",
	"Tooltip_IcnUmpLock_Unlocked": "Verriegeln",
	"Tooltip_IcnUmpMap": "Karte",
	"Tooltip_IcnUmpMergecall": "Anrufe verbinden",
	"Tooltip_IcnUmpMic": "Rufen",
	"Tooltip_IcnUmpMinus": "Weniger",
	"Tooltip_IcnUmpMore": "Ähnliche Musik",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Stumm schalten",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Stumm schalten aufheben",
	"Tooltip_IcnUmpNextAudio": "Nächster",
	"Tooltip_IcnUmpNowPlaying": "Wiedergabe",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Übertragen an Telefon",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Übertragen an Fahrzeug",
	"Tooltip_IcnUmpPlayOrPause": "Wiedergabe/Pause",
	"Tooltip_IcnUmpPlayPause_Pause": "Pause",
	"Tooltip_IcnUmpPlayPause_Play": "Wiedergabe",
	"Tooltip_IcnUmpPlayPause_Stop": "Stopp",
	"Tooltip_IcnUmpPlus": "Mehr",
	"Tooltip_IcnUmpPreviousAudio": "Vorheriger",
	"Tooltip_IcnUmpRepeat_List": "Wiederholen",
	"Tooltip_IcnUmpRepeat_None": "Wiederholen",
	"Tooltip_IcnUmpRepeat_Song": "Wiederholen",
	"Tooltip_IcnUmpReply": "Antworten",
	"Tooltip_IcnUmpReplyToAll": "Allen antworten",
	"Tooltip_IcnUmpReset": "Zurücksetzen",
	"Tooltip_IcnUmpScan_Sel": "Suche unterbrechen",
	"Tooltip_IcnUmpScan_Unsel": "Suchen",
	"Tooltip_IcnUmpSettings": "Einstellungen",
	"Tooltip_IcnUmpShuffle_Folder": "Mischen",
	"Tooltip_IcnUmpShuffle_Off": "Mischen",
	"Tooltip_IcnUmpShuffle_On": "Mischen",
	"Tooltip_IcnUmpStation_Create": "Sender erstellen",
	"Tooltip_IcnUmpSubtitles": "Untertitel",
	"Tooltip_IcnUmpSwapCalls_01": "Makeln",
	"Tooltip_IcnUmpSwapCalls_02": "Makeln",
	"Tooltip_IcnUmpSwitchView": "Ansicht wechseln",
	"Tooltip_IcnUmpSwitchView_1": "Ansicht wechseln",
	"Tooltip_IcnUmpSwitchView_2": "Ansicht wechseln",
	"Tooltip_IcnUmpSwitchView_3": "Ansicht wechseln",
	"Tooltip_IcnUmpThumbsDown_Sel": "Ablehnen",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Ablehnen",
	"Tooltip_IcnUmpThumbsUp_Sel": "Akzeptieren",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Akzeptieren",
	"Tooltip_IcnUmpTopList": "Stammordner",
	"Tooltip_IcnUmpTrafficAlert": "Verkehrsmeldung (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Verkehrsmeldung (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Verkehrsmeldung (TA)",
	"Tooltip_IcnUmpTune": "Einstellen",
	"Tooltip_IcnUmpVideoSet": "Video-Einstellungen",
	"VehicleTab": "Fahrzeug",
	"VolumeTab": "Lautst.",
	"VuiHelpDefaultTitle": "Verfügbare Befehle sind:",
	"Yes": "Ja",
	"delete": "Löschen",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Stumm aus",
	"muteOn": "Stumm an",
	"shortRepnHours": "Std.",
	"shortRepnMins": "Min.",
	"shortRepnSecs": "Sek.",
	"tempUnitsCelsius": "°C",
	"tempUnitsFahrenheit": "°F",
	"volUnitsGallons": "Gallonen",
	"volUnitsLiters": "Liter",
};

framework.registerAppDictLoaded("common", "de_DE");