var Localization_commonAppDict_sk_SK = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Ponuka aplikácie",
	"Auto": "Auto",
	"Back": "Späť",
	"BrightnessTab": "Jas",
	"Cancel": "Zrušiť",
	"ColorTab": "Farba",
	"Connect": "Pripojiť",
	"Contacts": "Kontakty",
	"ContrastTab": "Kontrast",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Zariade.",
	"DisplayTab": "Displej",
	"Download": "Prevziať",
	"FullMonthNameApr": "Apríl",
	"FullMonthNameAug": "August",
	"FullMonthNameDec": "December",
	"FullMonthNameFeb": "Február",
	"FullMonthNameJan": "Január",
	"FullMonthNameJul": "Júl",
	"FullMonthNameJun": "Jún",
	"FullMonthNameMar": "Marec",
	"FullMonthNameMay": "Máj",
	"FullMonthNameNov": "November",
	"FullMonthNameOct": "Október",
	"FullMonthNameSep": "September",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Zmena jazyka. Čakajte",
	"Loading": "Nahráva sa",
	"MemoryFull": "Plná pamäť",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr",
	"MonthNameAug": "Aug",
	"MonthNameDec": "Dec",
	"MonthNameFeb": "Feb",
	"MonthNameJan": "Jan",
	"MonthNameJul": "Júl",
	"MonthNameJun": "Jún",
	"MonthNameMar": "Mar",
	"MonthNameMay": "Máj",
	"MonthNameNov": "Nov",
	"MonthNameOct": "Okt",
	"MonthNameSep": "Sep",
	"No": "Nie",
	"Off": "Vypnuté",
	"Ok": "OK",
	"On": "Zap.",
	"Quit": "Ukončiť",
	"Remove": "Odstrániť",
	"ResetTab": "Reset",
	"Retry": "Opakovať",
	"SbnVoiceNotSupported": "Hlas nepodporovaný",
	"SbnVoiceRecognition": "Rozpoznanie hlasom",
	"SbnWaitForTone": "Čakajte na tón",
	"Setup": "Nastavenie",
	"Siri": "Siri",
	"SoundTab": "Zvuk",
	"SpacebarText": "medzera",
	"SystemTab": "Systém",
	"TimeLabelAm": "dop.",
	"TimeLabelPm": "odp.",
	"TintTab": "Odtieň",
	"TooltipFavorites": "Obľúbené",
	"Tooltip_IcnUmpAddCall": "Pridať volanie",
	"Tooltip_IcnUmpAddContact": "Pridať kontakt",
	"Tooltip_IcnUmpAddSong": "Pridať pieseň",
	"Tooltip_IcnUmpAmPm": "Prepínanie predpoludnie/popoludnie",
	"Tooltip_IcnUmpApps": "Aplikácie",
	"Tooltip_IcnUmpAutoMem": "Automatická pamäť",
	"Tooltip_IcnUmpBack": "Späť",
	"Tooltip_IcnUmpBack15s": "Späť 15 sekúnd",
	"Tooltip_IcnUmpBack30s": "Späť 30 sekúnd",
	"Tooltip_IcnUmpBargeIn": "Rozprávajte",
	"Tooltip_IcnUmpBookmark": "Záložka",
	"Tooltip_IcnUmpBookmark_Sel": "Záložka",
	"Tooltip_IcnUmpBookmark_Unsel": "Záložka",
	"Tooltip_IcnUmpCall": "Volanie",
	"Tooltip_IcnUmpCamAngle": "Uhol kamery",
	"Tooltip_IcnUmpCloseUmp": "Skryť tlačidlá",
	"Tooltip_IcnUmpCommMenu": "Komunikácia",
	"Tooltip_IcnUmpConnectionManager": "Správca pripojenia",
	"Tooltip_IcnUmpCurrentList": "Zoznam staníc",
	"Tooltip_IcnUmpDelete": "Vymazať",
	"Tooltip_IcnUmpDialpad": "Číselná klávesnica",
	"Tooltip_IcnUmpEject": "Vysunúť",
	"Tooltip_IcnUmpEntMenu": "Zábava",
	"Tooltip_IcnUmpEqualizer": "Nastavenia zvuku",
	"Tooltip_IcnUmpFavorite_Favorite": "Odstrániť z obľúbených",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Pridať do obľúbených",
	"Tooltip_IcnUmpFolder_Up": "Návrat hore",
	"Tooltip_IcnUmpFwd15s": "Dopredu 15 sekúnd",
	"Tooltip_IcnUmpFwd30s": "Dopredu o 30 sekúnd",
	"Tooltip_IcnUmpGenre": "Žáner",
	"Tooltip_IcnUmpHD_Sel": "HD vyp.",
	"Tooltip_IcnUmpHD_Unsel": "HD zap.",
	"Tooltip_IcnUmpHangup": "Zavesiť",
	"Tooltip_IcnUmpItunesTag_Tagged": "Odstrániť značku pre aplikáciu iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Označiť",
	"Tooltip_IcnUmpLock_Locked": "Odomknúť",
	"Tooltip_IcnUmpLock_Unlocked": "Zamknúť",
	"Tooltip_IcnUmpMap": "Mapa",
	"Tooltip_IcnUmpMergecall": "Zlúčiť volania",
	"Tooltip_IcnUmpMic": "Hlasové volanie",
	"Tooltip_IcnUmpMinus": "Znížiť",
	"Tooltip_IcnUmpMore": "Ďalšie podobné",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Stlmiť hlasitosť",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Zrušiť stlmenie hlasitosti",
	"Tooltip_IcnUmpNextAudio": "Ďalej",
	"Tooltip_IcnUmpNowPlaying": "Práve hrá",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Prenos cez telefón",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Prenos v aute",
	"Tooltip_IcnUmpPlayOrPause": "Play/Pauza",
	"Tooltip_IcnUmpPlayPause_Pause": "Pozastaviť",
	"Tooltip_IcnUmpPlayPause_Play": "Prehrať",
	"Tooltip_IcnUmpPlayPause_Stop": "Stop",
	"Tooltip_IcnUmpPlus": "Zvýšiť",
	"Tooltip_IcnUmpPreviousAudio": "Predchádzajúce",
	"Tooltip_IcnUmpRepeat_List": "Opakovať",
	"Tooltip_IcnUmpRepeat_None": "Opakovať",
	"Tooltip_IcnUmpRepeat_Song": "Opakovať",
	"Tooltip_IcnUmpReply": "Odpovedať",
	"Tooltip_IcnUmpReplyToAll": "Odpovedať všetkým",
	"Tooltip_IcnUmpReset": "Reset",
	"Tooltip_IcnUmpScan_Sel": "Zastaviť skenovanie",
	"Tooltip_IcnUmpScan_Unsel": "Skenovať",
	"Tooltip_IcnUmpSettings": "Nastavenia",
	"Tooltip_IcnUmpShuffle_Folder": "Náhodný výber",
	"Tooltip_IcnUmpShuffle_Off": "Náhodný výber",
	"Tooltip_IcnUmpShuffle_On": "Náhodný výber",
	"Tooltip_IcnUmpStation_Create": "Vytvoriť stanicu",
	"Tooltip_IcnUmpSubtitles": "Titulky",
	"Tooltip_IcnUmpSwapCalls_01": "Vymeniť volania",
	"Tooltip_IcnUmpSwapCalls_02": "Vymeniť volania",
	"Tooltip_IcnUmpSwitchView": "Prepnúť zobrazenie",
	"Tooltip_IcnUmpSwitchView_1": "Prepnúť zobrazenie",
	"Tooltip_IcnUmpSwitchView_2": "Prepnúť zobrazenie",
	"Tooltip_IcnUmpSwitchView_3": "Prepnúť zobrazenie",
	"Tooltip_IcnUmpThumbsDown_Sel": "Nepáči sa",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Nepáči sa",
	"Tooltip_IcnUmpThumbsUp_Sel": "Páči sa",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Páči sa",
	"Tooltip_IcnUmpTopList": "Hlavný priečinok",
	"Tooltip_IcnUmpTrafficAlert": "Premávka (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Premávka (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Premávka (TA)",
	"Tooltip_IcnUmpTune": "Ladenie",
	"Tooltip_IcnUmpVideoSet": "Nastavenia videa",
	"VehicleTab": "Vozidlo",
	"VolumeTab": "Hlasitosť",
	"VuiHelpDefaultTitle": "Dostupné príkazy zahŕňajú:",
	"Yes": "Áno",
	"delete": "Vymazať",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Zosilniť",
	"muteOn": "Stlmiť",
	"shortRepnHours": "h",
	"shortRepnMins": "min",
	"shortRepnSecs": "s",
	"tempUnitsCelsius": "°C",
	"tempUnitsFahrenheit": "°F",
	"volUnitsGallons": "galóny",
	"volUnitsLiters": "litre",
};

framework.registerAppDictLoaded("common", "sk_SK");