var Localization_commonAppDict_es_ES = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Menú aplicaciones",
	"Auto": "Auto",
	"Back": "Volver",
	"BrightnessTab": "Brillo ",
	"Cancel": "Cancelar",
	"ColorTab": "Color",
	"Connect": "Conectar",
	"Contacts": "Contactos",
	"ContrastTab": "Contraste ",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Aparatos",
	"DisplayTab": "Pantalla ",
	"Download": "Descargar",
	"FullMonthNameApr": "Abril ",
	"FullMonthNameAug": "Agosto ",
	"FullMonthNameDec": "Diciembre ",
	"FullMonthNameFeb": "Febrero ",
	"FullMonthNameJan": "Enero ",
	"FullMonthNameJul": "Julio ",
	"FullMonthNameJun": "Junio ",
	"FullMonthNameMar": "Marzo ",
	"FullMonthNameMay": "Mayo",
	"FullMonthNameNov": "Noviembre ",
	"FullMonthNameOct": "Octubre ",
	"FullMonthNameSep": "Septiembre ",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Cambiando idioma. Por favor espere",
	"Loading": "Cargando",
	"MemoryFull": "Memoria llena",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Abr ",
	"MonthNameAug": "Ago",
	"MonthNameDec": "Dic",
	"MonthNameFeb": "Feb ",
	"MonthNameJan": "Ene",
	"MonthNameJul": "Jul",
	"MonthNameJun": "Jun",
	"MonthNameMar": "Mar ",
	"MonthNameMay": "May",
	"MonthNameNov": "Nov",
	"MonthNameOct": "Oct",
	"MonthNameSep": "Sept",
	"No": "No",
	"Off": "Off",
	"Ok": "OK",
	"On": "Activ",
	"Quit": "Salir",
	"Remove": "Eliminar",
	"ResetTab": "Reiniciar",
	"Retry": "Reintent",
	"SbnVoiceNotSupported": "Voz no soportada",
	"SbnVoiceRecognition": "Reconocimiento de voz",
	"SbnWaitForTone": "Esperar al tono",
	"Setup": "Configuración",
	"Siri": "Siri",
	"SoundTab": "Sonido ",
	"SpacebarText": "espacio",
	"SystemTab": "Sistema ",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Matiz",
	"TooltipFavorites": "Favoritos",
	"Tooltip_IcnUmpAddCall": "Añadir Llamada",
	"Tooltip_IcnUmpAddContact": "Añadir Contacto",
	"Tooltip_IcnUmpAddSong": "Añadir Canción",
	"Tooltip_IcnUmpAmPm": "Cambiar AM/PM",
	"Tooltip_IcnUmpApps": "Aplicaciones ",
	"Tooltip_IcnUmpAutoMem": "Memoria Automática",
	"Tooltip_IcnUmpBack": "Atrás  ",
	"Tooltip_IcnUmpBack15s": "Retroceder 15 Segundos",
	"Tooltip_IcnUmpBack30s": "Retroceder 30 Segundos",
	"Tooltip_IcnUmpBargeIn": "Hable Ahora",
	"Tooltip_IcnUmpBookmark": "Favoritos",
	"Tooltip_IcnUmpBookmark_Sel": "Favoritos",
	"Tooltip_IcnUmpBookmark_Unsel": "Favoritos",
	"Tooltip_IcnUmpCall": "Llamar ",
	"Tooltip_IcnUmpCamAngle": "Ángulo de cámara",
	"Tooltip_IcnUmpCloseUmp": "Ocultar",
	"Tooltip_IcnUmpCommMenu": "Comunicación",
	"Tooltip_IcnUmpConnectionManager": "Gestor de Conexión",
	"Tooltip_IcnUmpCurrentList": "Lista de Emisoras",
	"Tooltip_IcnUmpDelete": "Eliminar",
	"Tooltip_IcnUmpDialpad": "Teclado de marcación",
	"Tooltip_IcnUmpEject": "Expulsar ",
	"Tooltip_IcnUmpEntMenu": "Entretenimiento",
	"Tooltip_IcnUmpEqualizer": "Configuración de Sonido",
	"Tooltip_IcnUmpFavorite_Favorite": "Eliminar de Favoritos",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Añadir a Favoritos",
	"Tooltip_IcnUmpFolder_Up": "Menú Arriba",
	"Tooltip_IcnUmpFwd15s": "Adelantar 15 Segundos",
	"Tooltip_IcnUmpFwd30s": "Avanzar 30 Segundos",
	"Tooltip_IcnUmpGenre": "Género",
	"Tooltip_IcnUmpHD_Sel": "HD apagado",
	"Tooltip_IcnUmpHD_Unsel": "HD encendido",
	"Tooltip_IcnUmpHangup": "Colgar ",
	"Tooltip_IcnUmpItunesTag_Tagged": "Eliminar Etiqueta para iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Marcar",
	"Tooltip_IcnUmpLock_Locked": "Desbloquear ",
	"Tooltip_IcnUmpLock_Unlocked": "Bloqueo",
	"Tooltip_IcnUmpMap": "Mapa",
	"Tooltip_IcnUmpMergecall": "Fusionar Llamadas",
	"Tooltip_IcnUmpMic": "Gritar ",
	"Tooltip_IcnUmpMinus": "Disminuir ",
	"Tooltip_IcnUmpMore": "Más de Este Tipo",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Silencio",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Desactivar Silencio",
	"Tooltip_IcnUmpNextAudio": "Siguiente ",
	"Tooltip_IcnUmpNowPlaying": "Reproduciendo Ahora",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Transferir a Teléfono",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Transferir a Vehículo",
	"Tooltip_IcnUmpPlayOrPause": "Reproducir/Pausa",
	"Tooltip_IcnUmpPlayPause_Pause": "Pausa",
	"Tooltip_IcnUmpPlayPause_Play": "Reproducir ",
	"Tooltip_IcnUmpPlayPause_Stop": "Detener",
	"Tooltip_IcnUmpPlus": "Aumentar ",
	"Tooltip_IcnUmpPreviousAudio": "Anterior",
	"Tooltip_IcnUmpRepeat_List": "Repetir",
	"Tooltip_IcnUmpRepeat_None": "Repetir",
	"Tooltip_IcnUmpRepeat_Song": "Repetir",
	"Tooltip_IcnUmpReply": "Responder",
	"Tooltip_IcnUmpReplyToAll": "Responder Todos",
	"Tooltip_IcnUmpReset": "Reiniciar",
	"Tooltip_IcnUmpScan_Sel": "Detener Exploración",
	"Tooltip_IcnUmpScan_Unsel": "Explorar",
	"Tooltip_IcnUmpSettings": "Configuraciones",
	"Tooltip_IcnUmpShuffle_Folder": "Aleatorio",
	"Tooltip_IcnUmpShuffle_Off": "Aleatorio",
	"Tooltip_IcnUmpShuffle_On": "Aleatorio",
	"Tooltip_IcnUmpStation_Create": "Crear emisora",
	"Tooltip_IcnUmpSubtitles": "Subtítulos",
	"Tooltip_IcnUmpSwapCalls_01": "Intercambiar Llamadas",
	"Tooltip_IcnUmpSwapCalls_02": "Intercambiar Llamadas",
	"Tooltip_IcnUmpSwitchView": "Cambiar Vista",
	"Tooltip_IcnUmpSwitchView_1": "Cambiar Vista",
	"Tooltip_IcnUmpSwitchView_2": "Cambiar Vista",
	"Tooltip_IcnUmpSwitchView_3": "Cambiar Vista",
	"Tooltip_IcnUmpThumbsDown_Sel": "No me gusta",
	"Tooltip_IcnUmpThumbsDown_UnSel": "No me gusta",
	"Tooltip_IcnUmpThumbsUp_Sel": "Me gusta",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Me gusta",
	"Tooltip_IcnUmpTopList": "Carpeta principal",
	"Tooltip_IcnUmpTrafficAlert": "Anuncio de tráfico (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Anuncio de tráfico (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Anuncio de tráfico (TA)",
	"Tooltip_IcnUmpTune": "Sintonizar ",
	"Tooltip_IcnUmpVideoSet": "Ajustes de vídeo",
	"VehicleTab": "Vehículo ",
	"VolumeTab": "Volumen ",
	"VuiHelpDefaultTitle": "Comandos disponibles incluidos",
	"Yes": "Sí",
	"delete": "Eliminar",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Silencio OFF",
	"muteOn": "Silencio ON",
	"shortRepnHours": "H",
	"shortRepnMins": "M",
	"shortRepnSecs": "S",
	"tempUnitsCelsius": "°C",
	"tempUnitsFahrenheit": "°F",
	"volUnitsGallons": "Galones ",
	"volUnitsLiters": "Litros ",
};

framework.registerAppDictLoaded("common", "es_ES");