var Localization_commonAppDict_sr_RS = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Meni Aplikacija",
	"Auto": "Auto",
	"Back": "Nazad",
	"BrightnessTab": "Osvetlj.",
	"Cancel": "Otkaži",
	"ColorTab": "Boja",
	"Connect": "Poveži",
	"Contacts": "Kontakti",
	"ContrastTab": "Kontrast",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Uređaji",
	"DisplayTab": "Ekran",
	"Download": "Preuz.",
	"FullMonthNameApr": "April",
	"FullMonthNameAug": "Avgust",
	"FullMonthNameDec": "Decembar",
	"FullMonthNameFeb": "Februar",
	"FullMonthNameJan": "Januar",
	"FullMonthNameJul": "Jul",
	"FullMonthNameJun": "Jun",
	"FullMonthNameMar": "Mart",
	"FullMonthNameMay": "Maj",
	"FullMonthNameNov": "Novembar",
	"FullMonthNameOct": "Oktobar",
	"FullMonthNameSep": "Septembar",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "Promena jezika. Molim sačekajte",
	"Loading": "Učitavanje",
	"MemoryFull": "Memorija je puna",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Apr.",
	"MonthNameAug": "Avg.",
	"MonthNameDec": "Dec.",
	"MonthNameFeb": "Feb.",
	"MonthNameJan": "Jan.",
	"MonthNameJul": "Jul",
	"MonthNameJun": "Jun",
	"MonthNameMar": "Mar.",
	"MonthNameMay": "Maj",
	"MonthNameNov": "Nov.",
	"MonthNameOct": "Okt.",
	"MonthNameSep": "Sep.",
	"No": "Ne",
	"Off": "Isključ.",
	"Ok": "U redu",
	"On": "Uklj.",
	"Quit": "Zatvori",
	"Remove": "Ukloni",
	"ResetTab": "Resetuj",
	"Retry": "Retry",
	"SbnVoiceNotSupported": "Prepoznavanje glasa nije podržano",
	"SbnVoiceRecognition": "Prepoznavanje glasa uključeno",
	"SbnWaitForTone": "Sačekajte zvučni signal",
	"Setup": "Podešavanje",
	"Siri": "Siri",
	"SoundTab": "Zvuk",
	"SpacebarText": "razmak",
	"SystemTab": "Sistem",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Boja",
	"TooltipFavorites": "Omiljeni",
	"Tooltip_IcnUmpAddCall": "Dodaj poziv",
	"Tooltip_IcnUmpAddContact": "Dodaj kontakt",
	"Tooltip_IcnUmpAddSong": "Dodaj pesmu",
	"Tooltip_IcnUmpAmPm": "Promena AM/PM",
	"Tooltip_IcnUmpApps": "Aplikacije",
	"Tooltip_IcnUmpAutoMem": "Automatska memorija",
	"Tooltip_IcnUmpBack": "Nazad",
	"Tooltip_IcnUmpBack15s": "15 sekundi unazad",
	"Tooltip_IcnUmpBack30s": "30 sekundi unazad",
	"Tooltip_IcnUmpBargeIn": "Razgovaraj sada",
	"Tooltip_IcnUmpBookmark": "Obeleživač",
	"Tooltip_IcnUmpBookmark_Sel": "Obeleži",
	"Tooltip_IcnUmpBookmark_Unsel": "Obeleži",
	"Tooltip_IcnUmpCall": "Poziv",
	"Tooltip_IcnUmpCamAngle": "Ugao kamere",
	"Tooltip_IcnUmpCloseUmp": "Sakri dugmiće",
	"Tooltip_IcnUmpCommMenu": "Komunikacija",
	"Tooltip_IcnUmpConnectionManager": "Upravljač povezivanja",
	"Tooltip_IcnUmpCurrentList": "Lista stanica",
	"Tooltip_IcnUmpDelete": "Izbriši",
	"Tooltip_IcnUmpDialpad": "Tastatura za biranje",
	"Tooltip_IcnUmpEject": "Izbaci",
	"Tooltip_IcnUmpEntMenu": "Zabava",
	"Tooltip_IcnUmpEqualizer": "Postavke zvuka",
	"Tooltip_IcnUmpFavorite_Favorite": "Ukloni iz omiljenih",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Dodaj u omiljene",
	"Tooltip_IcnUmpFolder_Up": "Meni - gore",
	"Tooltip_IcnUmpFwd15s": "Napred 15 sekundi",
	"Tooltip_IcnUmpFwd30s": "Napred 30 sekundi",
	"Tooltip_IcnUmpGenre": "Žanr",
	"Tooltip_IcnUmpHD_Sel": "HD opcija isključena",
	"Tooltip_IcnUmpHD_Unsel": "HD opcija uključena",
	"Tooltip_IcnUmpHangup": "Prekini vezu",
	"Tooltip_IcnUmpItunesTag_Tagged": "Ukloni oznaku za iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Označi",
	"Tooltip_IcnUmpLock_Locked": "Otključaj",
	"Tooltip_IcnUmpLock_Unlocked": "Zaključaj",
	"Tooltip_IcnUmpMap": "Mapa",
	"Tooltip_IcnUmpMergecall": "Pripoji pozive",
	"Tooltip_IcnUmpMic": "Uzvik",
	"Tooltip_IcnUmpMinus": "Smanji",
	"Tooltip_IcnUmpMore": "Više ovakvih",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Bez tona",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Pojačaj",
	"Tooltip_IcnUmpNextAudio": "Sledeće",
	"Tooltip_IcnUmpNowPlaying": "Sada se reprodukuje",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Prenos poziva na slušalice",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Prenos poziva na handsfree način rada",
	"Tooltip_IcnUmpPlayOrPause": "Reprodukcija/Pauza",
	"Tooltip_IcnUmpPlayPause_Pause": "Pauza",
	"Tooltip_IcnUmpPlayPause_Play": "Reprodukcija",
	"Tooltip_IcnUmpPlayPause_Stop": "Zaustavi",
	"Tooltip_IcnUmpPlus": "Povećaj",
	"Tooltip_IcnUmpPreviousAudio": "Prethodno",
	"Tooltip_IcnUmpRepeat_List": "Ponovi",
	"Tooltip_IcnUmpRepeat_None": "Ponovi",
	"Tooltip_IcnUmpRepeat_Song": "Ponovi",
	"Tooltip_IcnUmpReply": "Odgovori",
	"Tooltip_IcnUmpReplyToAll": "Odgovori svima",
	"Tooltip_IcnUmpReset": "Resetuj",
	"Tooltip_IcnUmpScan_Sel": "Zaustavi ",
	"Tooltip_IcnUmpScan_Unsel": "Skeniraj",
	"Tooltip_IcnUmpSettings": "Postavke",
	"Tooltip_IcnUmpShuffle_Folder": "Slučajni redosled",
	"Tooltip_IcnUmpShuffle_Off": "Slučajni redosled",
	"Tooltip_IcnUmpShuffle_On": "Slučajni redosled",
	"Tooltip_IcnUmpStation_Create": "Kreiraj stanicu",
	"Tooltip_IcnUmpSubtitles": "Titlovi",
	"Tooltip_IcnUmpSwapCalls_01": "Zameni pozive",
	"Tooltip_IcnUmpSwapCalls_02": "Zameni pozive",
	"Tooltip_IcnUmpSwitchView": "Prebaci na prikaz",
	"Tooltip_IcnUmpSwitchView_1": "Promeni prikaz",
	"Tooltip_IcnUmpSwitchView_2": "Promeni prikaz",
	"Tooltip_IcnUmpSwitchView_3": "Promeni prikaz",
	"Tooltip_IcnUmpThumbsDown_Sel": "Palac nadole",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Palac nadole",
	"Tooltip_IcnUmpThumbsUp_Sel": "Palac nagore",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Palac nagore",
	"Tooltip_IcnUmpTopList": "Osnovna fascikla",
	"Tooltip_IcnUmpTrafficAlert": "Obaveštenja o stanju saobraćaja",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Obaveštenja o stanju saobraćaja",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Obaveštenja o stanju saobraćaja",
	"Tooltip_IcnUmpTune": "Podesi",
	"Tooltip_IcnUmpVideoSet": "Video postavke",
	"VehicleTab": "Vozilo",
	"VolumeTab": "Jač. zv.",
	"VuiHelpDefaultTitle": "Obuhvata dostupne komande:",
	"Yes": "Da",
	"delete": "Brisanje",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Uključen zvuk",
	"muteOn": "Isključen zvuk",
	"shortRepnHours": "h",
	"shortRepnMins": "m",
	"shortRepnSecs": "s",
	"tempUnitsCelsius": "C",
	"tempUnitsFahrenheit": "F",
	"volUnitsGallons": "galona",
	"volUnitsLiters": "litara",
};

framework.registerAppDictLoaded("common", "sr_RS");