var Localization_commonAppDict_fr_FR = {
	//"stringId" : "localString"
	"AppleCarPlay": "Apple CarPlay",
	"ApplicationsMenu": "Menu Applications",
	"Auto": "Auto",
	"Back": "Retour",
	"BrightnessTab": "Luminosité",
	"Cancel": "Annuler",
	"ColorTab": "Couleur",
	"Connect": "Connecter",
	"Contacts": "Contacts ",
	"ContrastTab": "Contraste",
	"DateFormat": "{day} {month}",
	"DevicesTab": "Dispositif",
	"DisplayTab": "Afficha.",
	"Download": "Téléchgr",
	"FullMonthNameApr": "Avril",
	"FullMonthNameAug": "Août",
	"FullMonthNameDec": "Décembre ",
	"FullMonthNameFeb": "Février ",
	"FullMonthNameJan": "Janvier ",
	"FullMonthNameJul": "Juillet ",
	"FullMonthNameJun": "Juin ",
	"FullMonthNameMar": "Mars ",
	"FullMonthNameMay": "Mai ",
	"FullMonthNameNov": "Novembre",
	"FullMonthNameOct": "Octobre ",
	"FullMonthNameSep": "Septembre ",
	"HUDTab": "AD-Disp",
	"LanguageChangeNotice": "lang. en cours de mod. Veuillez patienter",
	"Loading": "En cours de chargement",
	"MemoryFull": "Mémoire pleine",
	"MirrorLink": "MirrorLink",
	"MonthNameApr": "Avr",
	"MonthNameAug": "Aou",
	"MonthNameDec": "Déc",
	"MonthNameFeb": "Fév",
	"MonthNameJan": "Jan",
	"MonthNameJul": "Juil",
	"MonthNameJun": "Juin",
	"MonthNameMar": "Mar",
	"MonthNameMay": "Mai ",
	"MonthNameNov": "Nov",
	"MonthNameOct": "Oct",
	"MonthNameSep": "Sep",
	"No": "Non",
	"Off": "Désact.",
	"Ok": "OK",
	"On": "Activé ",
	"Quit": "Quitter",
	"Remove": "Supprimer",
	"ResetTab": "Réinit",
	"Retry": "Réessay",
	"SbnVoiceNotSupported": "Commande vocale non acceptée",
	"SbnVoiceRecognition": "Reconnaissance vocale",
	"SbnWaitForTone": "Attendre le bip",
	"Setup": "Configuration ",
	"Siri": "Siri",
	"SoundTab": "Audio",
	"SpacebarText": "espace",
	"SystemTab": "Système",
	"TimeLabelAm": "AM",
	"TimeLabelPm": "PM",
	"TintTab": "Teinte",
	"TooltipFavorites": "Favoris",
	"Tooltip_IcnUmpAddCall": "Ajouter un appel",
	"Tooltip_IcnUmpAddContact": "Ajouter un contact",
	"Tooltip_IcnUmpAddSong": "Ajouter un morceau",
	"Tooltip_IcnUmpAmPm": "Activer/désactiver AM/PM",
	"Tooltip_IcnUmpApps": "Applications",
	"Tooltip_IcnUmpAutoMem": "Mémoire Automatique",
	"Tooltip_IcnUmpBack": "Retour",
	"Tooltip_IcnUmpBack15s": "Retour de 15 secondes",
	"Tooltip_IcnUmpBack30s": "Retour de 30 secondes",
	"Tooltip_IcnUmpBargeIn": "Parlez maintenant",
	"Tooltip_IcnUmpBookmark": "Marquer",
	"Tooltip_IcnUmpBookmark_Sel": "Marquer",
	"Tooltip_IcnUmpBookmark_Unsel": "Marquer",
	"Tooltip_IcnUmpCall": "Appeler",
	"Tooltip_IcnUmpCamAngle": "Angle de caméra",
	"Tooltip_IcnUmpCloseUmp": "Masquer les touches",
	"Tooltip_IcnUmpCommMenu": "Communication",
	"Tooltip_IcnUmpConnectionManager": "Gestionnaire de connexion",
	"Tooltip_IcnUmpCurrentList": "Liste des stations",
	"Tooltip_IcnUmpDelete": "Supprimer",
	"Tooltip_IcnUmpDialpad": "Clavier",
	"Tooltip_IcnUmpEject": "Éjecter",
	"Tooltip_IcnUmpEntMenu": "Divertissements",
	"Tooltip_IcnUmpEqualizer": "Paramètres audio",
	"Tooltip_IcnUmpFavorite_Favorite": "Supprimer des Favoris",
	"Tooltip_IcnUmpFavorite_Unfavorite": "Ajouter aux favoris",
	"Tooltip_IcnUmpFolder_Up": "Menu précédent",
	"Tooltip_IcnUmpFwd15s": "Avance de 15 secondes",
	"Tooltip_IcnUmpFwd30s": "Avance de 30 secondes",
	"Tooltip_IcnUmpGenre": "Genre",
	"Tooltip_IcnUmpHD_Sel": "HD désactivée",
	"Tooltip_IcnUmpHD_Unsel": "HD activée",
	"Tooltip_IcnUmpHangup": "Raccrocher",
	"Tooltip_IcnUmpItunesTag_Tagged": "Supprimer la balise pour iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged": "Balise",
	"Tooltip_IcnUmpLock_Locked": "Déverrouiller",
	"Tooltip_IcnUmpLock_Unlocked": "Verrouiller",
	"Tooltip_IcnUmpMap": "Carte ",
	"Tooltip_IcnUmpMergecall": "Fusionner les appels",
	"Tooltip_IcnUmpMic": "Shout",
	"Tooltip_IcnUmpMinus": "Diminuer",
	"Tooltip_IcnUmpMore": "Autres musiques similaires",
	"Tooltip_IcnUmpMuteUnmute_Mute": "Silencieux",
	"Tooltip_IcnUmpMuteUnmute_Unmute": "Désactiver le mode silencieux",
	"Tooltip_IcnUmpNextAudio": "Suivant",
	"Tooltip_IcnUmpNowPlaying": "En cours de lecture",
	"Tooltip_IcnUmpPhoneRoute_Handset": "Transférer vers le combiné",
	"Tooltip_IcnUmpPhoneRoute_Vehicle": "Transférer vers le véhicule",
	"Tooltip_IcnUmpPlayOrPause": "Lire/Pause",
	"Tooltip_IcnUmpPlayPause_Pause": "Pause",
	"Tooltip_IcnUmpPlayPause_Play": "Lire",
	"Tooltip_IcnUmpPlayPause_Stop": "Stop",
	"Tooltip_IcnUmpPlus": "Augmenter",
	"Tooltip_IcnUmpPreviousAudio": "Précédent",
	"Tooltip_IcnUmpRepeat_List": "Lecture en boucle",
	"Tooltip_IcnUmpRepeat_None": "Lecture en boucle",
	"Tooltip_IcnUmpRepeat_Song": "Lecture en boucle",
	"Tooltip_IcnUmpReply": "Répondre",
	"Tooltip_IcnUmpReplyToAll": "Répondre à tous",
	"Tooltip_IcnUmpReset": "Réinitialiser",
	"Tooltip_IcnUmpScan_Sel": "Arrêt recherche",
	"Tooltip_IcnUmpScan_Unsel": "Recherche",
	"Tooltip_IcnUmpSettings": "Paramètres",
	"Tooltip_IcnUmpShuffle_Folder": "Lecture aléatoire",
	"Tooltip_IcnUmpShuffle_Off": "Lecture aléatoire",
	"Tooltip_IcnUmpShuffle_On": "Lecture aléatoire",
	"Tooltip_IcnUmpStation_Create": "Créer une station",
	"Tooltip_IcnUmpSubtitles": "Sous-titres",
	"Tooltip_IcnUmpSwapCalls_01": "Basculer les appels",
	"Tooltip_IcnUmpSwapCalls_02": "Basculer les appels",
	"Tooltip_IcnUmpSwitchView": "Modifier l’affichage",
	"Tooltip_IcnUmpSwitchView_1": "Modifier l’affichage",
	"Tooltip_IcnUmpSwitchView_2": "Modifier l’affichage",
	"Tooltip_IcnUmpSwitchView_3": "Modifier l’affichage",
	"Tooltip_IcnUmpThumbsDown_Sel": "Défavorable",
	"Tooltip_IcnUmpThumbsDown_UnSel": "Défavorable",
	"Tooltip_IcnUmpThumbsUp_Sel": "Favorable",
	"Tooltip_IcnUmpThumbsUp_UnSel": "Favorable",
	"Tooltip_IcnUmpTopList": "Répertoire racine",
	"Tooltip_IcnUmpTrafficAlert": "Avertissement de circulation",
	"Tooltip_IcnUmpTrafficAlert_Sel": "Avertissement de circulation",
	"Tooltip_IcnUmpTrafficAlert_Unsel": "Avertissement de circulation",
	"Tooltip_IcnUmpTune": "Régler",
	"Tooltip_IcnUmpVideoSet": "Paramètres vidéo",
	"VehicleTab": "Véhicule",
	"VolumeTab": "Volume",
	"VuiHelpDefaultTitle": "Les commandes possibles sont:",
	"Yes": "Oui",
	"delete": "Supprimer",
	"distanceUnitsKms": "km",
	"distanceUnitsMiles": "mi",
	"muteOff": "Sourdine désactivée",
	"muteOn": "Sourdine activée",
	"shortRepnHours": "h",
	"shortRepnMins": "min",
	"shortRepnSecs": "sec",
	"tempUnitsCelsius": "°C",
	"tempUnitsFahrenheit": "°F",
	"volUnitsGallons": "gallons",
	"volUnitsLiters": "litres",
};

framework.registerAppDictLoaded("common", "fr_FR");