var Localization_sysupdateAppDict_ar_SA = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "بحث عن باقات تحديث قاعدة بيانات الموسيقى على وحدة USB خاصتك؟",
    "SystemUpdate" : "تحديث النظام",
    "Search" : "بحث",
    "SearchingForMusicUpdates" : "بحث عن التحديثات",
    "AvailablePackages" : "باقات تحديث الموسيقى المتاحة",
    "CurrentVersion" : "تحديث الموسيقى (الحالي)",
    "GracenoteVersion" : "تحديث الموسيقى",
    "SearchFailed" : "لم ينجح البحث",
    "USER_TERMINATED" : "قام المستخدم بإلغاء عملية التحديث.",
    "DEVICE_ERROR" : "تم فصل USB",
    "NOT_FOUND" : "تم فقد باقة التحديث المطلوبة.",
    "AUTH_FAILED" : "فشل التحقق من صحة شهادة الباقة.",
    "INCOMPATIBLE_VERSION" : "باقة التحديث غير متوافقة مع الإصدار الحالي للوحة.",
    "SEARCH_FAILED" : "فشل تنفيذ عملية البحث.",
    "UPDATE_FAILED" : "فشل تنفيذ عملية التحديث.",
    "NOT_SUPPORTED" : "العملية غير مسموح بها بسبب الوحدة أو الوظيفة المفقودة",
    "UNKNOWN" : "السبب غير معروف",
    "BUSY" : "العملية مطلوبة في حالة غير ملائمة.",
    "INVALID" : "يوجد خطأ في محتوى باقة التحديث أو أنه غير كافٍ.",
    "Retry" : "أعد المحاولة",
    "NoNewMusicPackages" : "لا تتوافر باقات تحديث جديدة للموسيقى.",
    "NeedFailSafeImageUpdate" : "من الضروري تحديث صورة fail-safe، للاستمرار، يرجى الاتصال بأقرب موزع",
    "CurrentDatabase" : "الإصدار الحالي من قاعدة بيانات الموسيقى هو {CurrentVersion}.",
    "InstallDatabase" : "هل ترغب في تثبيت تحديث الموسيقى {InstallVersion}؟",
    "SystemNA" : "النظام غير متاح بالكامل.",
    "SystemRestart" : "إعادة تشغيل النظام دخلت حيز التنفيذ.",
    "Install" : "تثبيت",
    "InstallMusic" : "تثبيت تحديث الموسيقى {MusicVersion}",
    "VehicleRestart" : "لا تعيد تشغيل المركبة ذاك الوقت.",
    "MusicInstallSuccess" : "نجح تثبيت موسيقى الإصدار {MusicVersion}.",
    "FunctionNA" : "فشل تحديث قاعدة بيانات الموسيقى.",
    "USBcatalog" : "فهرسة USB لن تكون متوافرة.",
    "searchAgain" : "يرجى البحث مرة أخرى.",
    "RebootReflash" : "جارٍ الإعداد للتحديث",
    "ValidationFailed" : "فشل التحقق من الصحة",
    "SearchSoftwareUpdates" : "بحث عن باقات تحديث النظام على وحدة USB خاصتك؟",
    "SearchingForSoftwareUpdates" : "بحث عن تحديثات النظام",
    "AvailableSoftwarePackages" : "باقات تحديث البرامج المتاحة",
    "CurrentOSVersion" : "تحديث البرنامج (الحالي)",
    "SoftwareVersion" : "تحديث البرنامج",
    "ReinstallationPackage" : "باقة إعادة التثبيت",
    "NoNewSoftwarePackages" : "لا تتوافر باقات تحديث جديدة.",
    "FailSafeImageUpdateNotify" : "من الضروري تحديث صورة fail-safe، يرجى القيام بتحديث صورة fail-safe.",
    "Continue" : "متابعة",
    "CurrentSoftwareVersion" : "النظام الحالي {CurrentOsVersion} قيد التشغيل.",
    "ConfirmFailSafeUpdateInstall" : "هل تود تثبيت تحديث صورة fail-safe {FailsafeImageVersion}؟",
    "InstallingFailsafeSystem" : "جارٍ تثبيت تحديث نظام Fail-Safe",
    "DonotRestart" : "لا تعيد تشغيل المركبة ذاك الوقت.",
    "InstallSuccessful" : "نجح التثبيت",
    "NoReboot" : "لا توجد ضرورة لإعادة التشغيل",
    "InstallUnsuccessful" : "لم ينجح التثبيت",
    "UpdatesNA" : "تحديثات النظام لن تكون متوافرة.",
    "OSVersion" : "إصدار نظام التشغيل هو {CurrentOsVersion}",
    "MusicDBVersion" : "إصدار قاعدة بيانات الموسيقى هو {CurrentVersion}",
    "FailSafeImage" : "باقة Fail Safe",
    "InstallingSysUpdates" : "جارٍ تثبيت تحديثات نظام {OsVersion}",
    "SysInstallSuccess" : "تم تثبيت برنامج إصدار {OsVersion} بنجاح.",
    "RestartVehicle" : "يرجى إعادة تشغيل المركبة لتنفيذ التغييرات.",
    "InstallNotSuccessful" : "لم ينجح التثبيت {errorType}",
    "InsertUSBDialogText" : "أدخل USB مع باقة إعادة التثبيت.",
    "AutoRetry" : "بعدها سيعيد النظام تلقائيًا محاولة التحديث.",
    "ValidatingUpdate" : "جارٍ التحقق من باقة تحديث النظام {OsVersion}",
    "FailsafeAvailable" : "صورة fail-safe الموجودة متاحة.",
    "SystemFailure" : "فشل النظام",
    "SigCheckFailed" : "فشل تفقد توقيع الباقة",
    "UpdateToSoftwareVersion" : "هل ترغب في تثبيت نظام تشغيل تحديث البرامج {InstallOsVersion}؟",
    "NotAvailable" : "إصدار قاعدة بيانات الموسيقى غير متاح",
};

framework.registerAppDictLoaded("sysupdate", "ar_SA");