var Localization_sysupdateAppDict_tr_TR = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "USB aygıtınızda Müzik Veritabanı güncelleme paketlerini arayın?",
    "SystemUpdate" : "Sistem Güncellemesi",
    "Search" : "Ara",
    "SearchingForMusicUpdates" : "Güncellemeler Aranıyor",
    "AvailablePackages" : "Mevcut Müzik Güncelleme Paketleri",
    "CurrentVersion" : "Müzik Güncellemesi (Güncel)",
    "GracenoteVersion" : "Müzik Güncellemesi",
    "SearchFailed" : "Arama Başarısız",
    "USER_TERMINATED" : "Güncelleme işlemi kullanıcı tarafından iptal edildi.",
    "DEVICE_ERROR" : "USB Bağlantısı Kesildi",
    "NOT_FOUND" : "Talep edilen güncelleme paketi mevcut değil.",
    "AUTH_FAILED" : "Paket sertifikası doğrulanamadı.",
    "INCOMPATIBLE_VERSION" : "Güncelleme paketi, mevcut kart sürümüyle uyumlu değil.",
    "SEARCH_FAILED" : "Arama işlemi uygulanamadı.",
    "UPDATE_FAILED" : "Güncelleme işlemi uygulanamadı.",
    "NOT_SUPPORTED" : "Eksik modül veya işlev nedeniyle işleme izin verilmedi.",
    "UNKNOWN" : "Nedeni bilinmiyor",
    "BUSY" : "İşlem uygun olmayan bir durumda talep edildi.",
    "INVALID" : "Güncelleme paketi içeriği yanlış veya yeterli değil.",
    "Retry" : "Yeniden Dene",
    "NoNewMusicPackages" : "Yeni müzik güncelleme paketi bulunmuyor.",
    "NeedFailSafeImageUpdate" : "Devam edilebilmesi için hataya karşı korumalı görüntü güncellemesi gerekiyor, lütfen size en yakın satıcıya danışın.",
    "CurrentDatabase" : "Mevcut Müzik Veritabanı sürümü: {CurrentVersion}.",
    "InstallDatabase" : "{InstallVersion} Müzik Güncellemesini yüklemek ister misiniz?",
    "SystemNA" : "Sistem tam kullanılabilir değil.",
    "SystemRestart" : "Sistem Yeniden Başlatılacak.",
    "Install" : "Yükle",
    "InstallMusic" : "{MusicVersion} Müzik Güncel. Kuruluyor",
    "VehicleRestart" : "Aracı şu anda yeniden çalıştırmayın.",
    "MusicInstallSuccess" : "{MusicVersion} sürümü müzik kurulumu başarısız.",
    "FunctionNA" : "Müzik veritabanı güncelleme başarısız.",
    "USBcatalog" : "USB kataloglama mevcut değil.",
    "searchAgain" : "Lütfen tekrar Arayın.",
    "RebootReflash" : "Güncellemeye Hazırlanılıyor",
    "ValidationFailed" : "Doğrulama Başarısız",
    "SearchSoftwareUpdates" : "USB aygıtınızda Sistem Güncelleme paketlerini arayın?",
    "SearchingForSoftwareUpdates" : "Sistem Güncellemeleri Aranıyor",
    "AvailableSoftwarePackages" : "Mevcut Yazılım Güncelleme Paketleri",
    "CurrentOSVersion" : "Yazılım Güncellemesi (Güncel)",
    "SoftwareVersion" : "Yazılım Güncellemesi",
    "ReinstallationPackage" : "Yeniden Kurulum Paketi",
    "NoNewSoftwarePackages" : "Yeni güncelleme paketi bulunmuyor.",
    "FailSafeImageUpdateNotify" : "Hataya karşı korumalı görüntü güncellemesi gerekiyor, lütfen hataya karşı korumalı görüntü güncellemesi gerçekleştirin.",
    "Continue" : "Devam",
    "CurrentSoftwareVersion" : "Mevcut sistem {CurrentOsVersion} çalışıyor.",
    "ConfirmFailSafeUpdateInstall" : "{FailsafeImageVersion} hataya karşı korumalı görüntü güncellemesini yüklemek ister misiniz?",
    "InstallingFailsafeSystem" : "Hata Korumalı sistem güncellemesi",
    "DonotRestart" : "Aracı şu anda yeniden çalıştırmayın.",
    "InstallSuccessful" : "Yükleme Başarılı",
    "NoReboot" : "Yeniden Başlatılmasına Gerek Yoktur",
    "InstallUnsuccessful" : "Yükleme Başarısız",
    "UpdatesNA" : "Sistem Güncellemeleri mevcut değil.",
    "OSVersion" : "İşletim Sistemi Sürümü: {CurrentOsVersion}",
    "MusicDBVersion" : "Müzik Veritabanı Sürümü: {CurrentVersion}",
    "FailSafeImage" : "Hataya Karşı Korumalı Paket",
    "InstallingSysUpdates" : "{OsVersion} Sistem Güncellemeleri Kuruluyor",
    "SysInstallSuccess" : "{OsVersion} Sürüm Yazılım Kurulumu başarılı.",
    "RestartVehicle" : "Değişikliklerin geçerli olabilmesi için lütfen aracı yeniden çalıştırın.",
    "InstallNotSuccessful" : "{errorType} kurulumu başarısız",
    "InsertUSBDialogText" : "USB'yi yeniden kurulum paketiyle takın.",
    "AutoRetry" : "Sistem otomatik olarak güncellemeyi yeniden dener.",
    "ValidatingUpdate" : "{OsVersion} sistem güncelleme paketi doğrulanıyor",
    "FailsafeAvailable" : "Mevcut hata güvenlikli görüntü bulunuyor.",
    "SystemFailure" : "Pad sistema",
    "SigCheckFailed" : "Neuspela kontrola paketa potpisa",
    "UpdateToSoftwareVersion" : "Software Update OS {InstallOsVersion} yüklemek ister misiniz?",
    "NotAvailable" : "Müzik Veritabanı Sürümü Mevcut Değil",
};

framework.registerAppDictLoaded("sysupdate", "tr_TR");