var Localization_sysupdateAppDict_no_NO = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Søke etter oppdateringspakker for musikkdatabase på USB-enheten?",
    "SystemUpdate" : "Systemoppdatering",
    "Search" : "Søk",
    "SearchingForMusicUpdates" : "Søker etter oppdateringer",
    "AvailablePackages" : "Tilgjengelige oppdat. for musikk",
    "CurrentVersion" : "Musikkoppdatering (nå)",
    "GracenoteVersion" : "Musikkoppdatering",
    "SearchFailed" : "Søket mislyktes",
    "USER_TERMINATED" : "Oppdateringen ble avbrutt av brukeren.",
    "DEVICE_ERROR" : "USB frakoblet",
    "NOT_FOUND" : "Den forespurte oppdateringspakken mangler.",
    "AUTH_FAILED" : "Validering av pakkesertifikatet mislyktes.",
    "INCOMPATIBLE_VERSION" : "Oppdateringspakken er ikke komplett med gjeldende kortversjon.",
    "SEARCH_FAILED" : "Søket mislyktes.",
    "UPDATE_FAILED" : "Oppdateringen mislyktes.",
    "NOT_SUPPORTED" : "Handlingen er ikke tillatt på grunn av manglende modul eller funksjon.",
    "UNKNOWN" : "Ukjent årsak",
    "BUSY" : "Handlingen er forespurt i feil tilstand.",
    "INVALID" : "Innholdet i oppdateringspakken er feil eller ikke tilstrekkelig.",
    "Retry" : "Prøv på nytt",
    "NoNewMusicPackages" : "Ingen nye musikkoppdateringspakker er tilgjengelige.",
    "NeedFailSafeImageUpdate" : "Trenger oppdatering av feilsikkert duplikat, kontakt nærmeste forhandler.",
    "CurrentDatabase" : "Musikkdatabasens versjon er {CurrentVersion}.",
    "InstallDatabase" : "Vil du installere musikkoppdateringen {InstallVersion}?",
    "SystemNA" : "Systemet er ikke helt tilgjengelig.",
    "SystemRestart" : "Systemomstart vil starte.",
    "Install" : "Installer",
    "InstallMusic" : "Inst. musikkoppdateringer {MusicVersion}",
    "VehicleRestart" : "Motor må ikke startes på nytt nå.",
    "MusicInstallSuccess" : "Installasjon av musikk, versjon {MusicVersion}, var vellykket.",
    "FunctionNA" : "Oppdater. av musikkdatabase mislyktes.",
    "USBcatalog" : "USB-katalogisering vil ikke være tilgjengelig.",
    "searchAgain" : "Søk på nytt.",
    "RebootReflash" : "Forbereder oppdatering",
    "ValidationFailed" : "Validering mislyktes",
    "SearchSoftwareUpdates" : "Søke etter systemoppdateringspakker på USB-enheten?",
    "SearchingForSoftwareUpdates" : "Søker etter systemoppdateringer",
    "AvailableSoftwarePackages" : "Tilgjengelige oppdat. for progr.",
    "CurrentOSVersion" : "Programvareoppdater.(nå)",
    "SoftwareVersion" : "Programvareoppdatering",
    "ReinstallationPackage" : "Re-installeringspakke",
    "NoNewSoftwarePackages" : "Ingen nye oppdateringspakker er tilgjengelige.",
    "FailSafeImageUpdateNotify" : "Trenger oppdatering av feilsikkert duplikat, utfør alle duplikatoppdateringene for feilsikker.",
    "Continue" : "Fortsett",
    "CurrentSoftwareVersion" : "Gjeldende system {CurrentOsVersion} kjører.",
    "ConfirmFailSafeUpdateInstall" : "Vil du installere oppdateringen til feilsikker-bildet {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Installerer Fail-safe oppdateringer",
    "DonotRestart" : "Bilen må ikke startes nå.",
    "InstallSuccessful" : "Installasjon vellykket",
    "NoReboot" : "Ingen omstart er nødvendig",
    "InstallUnsuccessful" : "Installasjonen mislyktes",
    "UpdatesNA" : "Systemoppdat. vil ikke være tilgjengelig.",
    "OSVersion" : "OS-versjonen er {CurrentOsVersion}",
    "MusicDBVersion" : "Versjon for musikkdatabase er {CurrentVersion}",
    "FailSafeImage" : "Fail-safe pakke",
    "InstallingSysUpdates" : "Installerer systemoppdateringer {OsVersion}",
    "SysInstallSuccess" : "Installasjon av {OsVersion} programvaren var vellykket.",
    "RestartVehicle" : "Start kjøretøyet på nytt for å aktivere endringene.",
    "InstallNotSuccessful" : "Installasjonen mislyktes {errorType}",
    "InsertUSBDialogText" : "sett inn USB med ominstallasjonspakken.",
    "AutoRetry" : "Systemet vil deretter prøve oppdateringen på nytt automatisk.",
    "ValidatingUpdate" : "Validerer systemoppdateringspakke {OsVersion}",
    "FailsafeAvailable" : "Eksisterende Fail-safe bilde er tilgjengelig.",
    "SystemFailure" : "Systemfeil",
    "SigCheckFailed" : "Kontroll av pakkesignaturen mislyktes",
    "UpdateToSoftwareVersion" : "Vil du installere Programvareoppdatering OS {InstallOsVersion}?",
    "NotAvailable" : "Versjon for musikkdatabase er ikke tilgjengelig",
};

framework.registerAppDictLoaded("sysupdate", "no_NO");