var Localization_sysupdateAppDict_el_GR = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Αναζήτηση για πακέτα ενημέρωσης για βάση δεδομένων μουσικής στη USB συσκευή σας;",
    "SystemUpdate" : "Ενημ. συστ.",
    "Search" : "Αναζήτηση",
    "SearchingForMusicUpdates" : "Αναζήτηση ενημερώσεων",
    "AvailablePackages" : "Διαθ. πακέτα αναβ. μουσικής",
    "CurrentVersion" : "Ενημ. μουσικής (τρέχον)",
    "GracenoteVersion" : "Ενημέρωση μουσικής",
    "SearchFailed" : "Η αναζήτηση ήταν ανεπιτυχής",
    "USER_TERMINATED" : "Η λειτουργία ενημέρωσης ακυρώθηκε από το χρήστη.",
    "DEVICE_ERROR" : "Το USB αποσυνδέθηκε",
    "NOT_FOUND" : "Δεν υπάρχει το ζητούμενο πακέτο ενημέρωσης.",
    "AUTH_FAILED" : "Απέτυχε η επικύρωση του πιστοποιητικού πακέτου.",
    "INCOMPATIBLE_VERSION" : "Το πακέτο ενημ. δεν είναι συμβατό με την τρέχουσα έκδοση πίνακα.",
    "SEARCH_FAILED" : "Απέτυχε η εκτέλεση της λειτουργίας αναζήτησης.",
    "UPDATE_FAILED" : "Απέτυχε η εκτέλεση της λειτουργίας ενημέρωσης.",
    "NOT_SUPPORTED" : "Η λειτουργία δεν επιτρέπεται λόγω μη υπάρχουσας μονάδας ή λειτουργίας.",
    "UNKNOWN" : "Άγνωστη αιτία",
    "BUSY" : "Η λειτουργία ζητήθηκε σε ακατάλληλη κατάσταση.",
    "INVALID" : "Το περιεχόμενο του πακέτου ενημ. είναι εσφαλμένο ή ανεπαρκές.",
    "Retry" : "Δοκιμάστε ξανά",
    "NoNewMusicPackages" : "Δεν υπάρχουν διαθέσιμα νέα πακέτα ενημέρωσης μουσικής.",
    "NeedFailSafeImageUpdate" : "Απαιτείται ενημέρωση εικόνας προστασίας από αστοχία για να συνεχίσετε, επικοινωνήστε με την πλησιέστερη αντιπροσωπεία.",
    "CurrentDatabase" : "Η τρέχουσα έκδοση μουσικής βάσης δεδομένων είναι {CurrentVersion}.",
    "InstallDatabase" : "Θέλετε να εγκαταστήσετε ενημέρωση μουσικής {InstallVersion};",
    "SystemNA" : "Σύστημα μη πλήρως διαθέσιμο.",
    "SystemRestart" : "Η επανεκκίνηση θα εφαρμοστεί.",
    "Install" : "Εγκατάσταση",
    "InstallMusic" : "Εγκατ. Ενημερ. μουσ {MusicVersion}",
    "VehicleRestart" : "Μην επανεκκινείτε τώρα το όχημα. ",
    "MusicInstallSuccess" : "Εγκατάσταση έκδοσης {MusicVersion} μουσικής ήταν επιτυχής.",
    "FunctionNA" : "Μη επιτυχής ενημέρωση δεδομένων ",
    "USBcatalog" : "Ο κατάλογος USB δεν θα είναι διαθέσιμος",
    "searchAgain" : "Επαναλάβετε την αναζήτηση.",
    "RebootReflash" : "Προετοιμασία για ενημέρωση",
    "ValidationFailed" : "Αποτυχία επικύρωσης",
    "SearchSoftwareUpdates" : "Αναζήτηση για πακέτα ενημέρωση συστήματος στη USB συσκευή σας;",
    "SearchingForSoftwareUpdates" : "Αναζήτηση ενημερ. συστήματος",
    "AvailableSoftwarePackages" : "Διαθ. πακέτα αναβ. λογισμικού",
    "CurrentOSVersion" : "Ενημ. λογισμικού (τρέχον)",
    "SoftwareVersion" : "Ενημέρωση λογισμικού",
    "ReinstallationPackage" : "Πακέτο επανεγκατάστασης",
    "NoNewSoftwarePackages" : "Δεν υπάρχουν διαθέσιμα νέα πακέτα ενημέρωσης.",
    "FailSafeImageUpdateNotify" : "Απαιτείται ενημέρωση εικόνας προστασίας από αστοχία, εκτελέστε ενημέρωση εικόνας προστασίας από αστοχία.",
    "Continue" : "Συνέχεια",
    "CurrentSoftwareVersion" : "Εκτελείται το τρέχον σύστημα {CurrentOsVersion}.",
    "ConfirmFailSafeUpdateInstall" : "Θέλετε να εγκαταστήσετε ενημέρωση εικόνας προστασίας από αστοχία {FailsafeImageVersion};",
    "InstallingFailsafeSystem" : "Εγκατάσταση ενημέρωσης συστήματος προστασίας από αστοχία",
    "DonotRestart" : "Μην επανεκκινείτε τώρα το όχημα.",
    "InstallSuccessful" : "Επιτυχής εγκατάσταση",
    "NoReboot" : "Δεν απαιτείται επανεκκίνηση",
    "InstallUnsuccessful" : "Εγκατάσταση απέτυχε",
    "UpdatesNA" : "Δεν είναι διαθέσιμες οι ενημερώσεις.",
    "OSVersion" : "Η έκδοση λειτουργικού συστήματος είναι {CurrentOsVersion}",
    "MusicDBVersion" : "Η έκδοση της βάσης δεδομένων μουσικής είναι {CurrentVersion}",
    "FailSafeImage" : "Πακ. προστ. από αστοχίες",
    "InstallingSysUpdates" : "Εγκατάσταση ενημερώσεων συστήματος {OsVersion}",
    "SysInstallSuccess" : "Επιτυχής εγκατάσταση λογισμικού {OsVersion}.",
    "RestartVehicle" : "Επανεκκινήστε το όχημα για να εφαρμοστούν οι αλλαγές.",
    "InstallNotSuccessful" : "Μη επιτυχής εγκατάσταση {errorType}",
    "InsertUSBDialogText" : "Εισαγάγετε το USB με το πακέτο επανεγκατάστασης.",
    "AutoRetry" : "Το σύστημα θα προσπαθήσει ξανά αυτόματα να κάνει ενημέρωση.",
    "ValidatingUpdate" : "Επικύρωση πακέτου ενημέρωσης συστήματος {OsVersion}",
    "FailsafeAvailable" : "Διατίθεται υπάρχον σύστημα εικόνας προστασίας από αστοχία.",
    "SystemFailure" : "Αποτυχία συστήματος",
    "SigCheckFailed" : "Απέτυχε ο έλεγχος της υπογραφής πακέτου",
    "UpdateToSoftwareVersion" : "Θέλετε να εγκαταστήσετε το OS {InstallOsVersion} ενημέρωσης;",
    "NotAvailable" : "Η έκδοση μουσικής βάσης δεδομένων δεν είναι διαθέσιμη",
};

framework.registerAppDictLoaded("sysupdate", "el_GR");