var Localization_sysupdateAppDict_pl_PL = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Czy wyszukać pakiety aktualizacji bazy danych muzyki na urządzeniu USB?",
    "SystemUpdate" : "Aktual. Systemu",
    "Search" : "Szukaj",
    "SearchingForMusicUpdates" : "Wyszukiwanie aktualizacji",
    "AvailablePackages" : "Pakiety aktual. muzyki",
    "CurrentVersion" : "Aktual. muzyki (bieżąca)",
    "GracenoteVersion" : "Aktualizacja b.d. muzyki",
    "SearchFailed" : "Wyszukiwanie bez wyników",
    "USER_TERMINATED" : "Użytkownik anulował aktualizację.",
    "DEVICE_ERROR" : "USB rozłączone",
    "NOT_FOUND" : "Brak potrzebnego pakietu aktualizacji",
    "AUTH_FAILED" : "Nieudane uwierzytelnienie świadectwa pakietu",
    "INCOMPATIBLE_VERSION" : "Pakiet aktualizacji jest niezgodny z aktualną wersją płyty.",
    "SEARCH_FAILED" : "Nie dokonano wyszukiwania",
    "UPDATE_FAILED" : "Nie dokonano aktualizacji",
    "NOT_SUPPORTED" : "Niedozwolone działanie z powodu braku modułu lub funkcjonalności",
    "UNKNOWN" : "Nieznana przyczyna",
    "BUSY" : "Działanie jest wymagane w nieodpowiednim stanie",
    "INVALID" : "Zawartość pakietu aktualizacyjnego jest błędna lub niewystarczająca.",
    "Retry" : "Ponów",
    "NoNewMusicPackages" : "Brak dostępnych nowych pakietów aktualizacji b.d. muzyki.",
    "NeedFailSafeImageUpdate" : "Dalej potrzebna aktualizacja obrazu odpornego na uszkodzenia. Skontaktuj się z najbliższym dealerem.",
    "CurrentDatabase" : "Bieżąca wersja bazy danych muzyki: {CurrentVersion}.",
    "InstallDatabase" : "Czy zainstalować aktualizację bazy danych muzyki {InstallVersion}?",
    "SystemNA" : "System jest dostępny tylko częściowo.",
    "SystemRestart" : "System zostanie uruchomiony ponownie.",
    "Install" : "Zainstaluj",
    "InstallMusic" : "Instal. aktualiz. muz. {MusicVersion}",
    "VehicleRestart" : "Nie uruchamiaj teraz pojazdu",
    "MusicInstallSuccess" : "Instalacja wersji bazy danych muzyki {MusicVersion} została zakończona pomyślnie.",
    "FunctionNA" : "Akt. bazy danych muz. nie powiodła się.",
    "USBcatalog" : "Katalogowanie urządzenia USB nie będzie dostępne.",
    "searchAgain" : "Wyszukaj ponownie.",
    "RebootReflash" : "Przygotowywanie do aktualizacji",
    "ValidationFailed" : "Weryfikacja nie powiodła się.",
    "SearchSoftwareUpdates" : "Czy wyszukać pakiety aktualizacji systemu na urządzeniu USB?",
    "SearchingForSoftwareUpdates" : "Wyszukiwanie aktualizacji systemowych",
    "AvailableSoftwarePackages" : "Dost. pakiety akt. oprogramowania",
    "CurrentOSVersion" : "Aktualiz. oprogram. (bież.)",
    "SoftwareVersion" : "Aktualizacja oprogramow.",
    "ReinstallationPackage" : "Pakiet ponownej instalacji",
    "NoNewSoftwarePackages" : "Brak dostępnych nowych pakietów aktualizacji.",
    "FailSafeImageUpdateNotify" : "Wymagany jest obraz pakietu awaryjnego. Przeprowadź aktualizację pakietu awaryjnego.",
    "Continue" : "Kontynuuj",
    "CurrentSoftwareVersion" : "Używana wersja oprogramowania {CurrentOsVersion}.",
    "ConfirmFailSafeUpdateInstall" : "Czy zainstalować aktualizację pakietu awaryjnego {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Instalowanie aktualizacji systemu awaryjnego",
    "DonotRestart" : "Nie uruchamiaj teraz pojazdu.",
    "InstallSuccessful" : "Powodzenie instalacji",
    "NoReboot" : "Niewymagane ponowne uruchomienie",
    "InstallUnsuccessful" : "Niepowodzenie instalacji",
    "UpdatesNA" : "Aktualiz. systemowe nie będą dostępne.",
    "OSVersion" : "Wersja systemu operacyjnego: {CurrentOsVersion}",
    "MusicDBVersion" : "Wersja bazy danych muzyki: {CurrentVersion}",
    "FailSafeImage" : "Pakiet awaryjny",
    "InstallingSysUpdates" : "Instalowanie aktualizacji systemowych {OsVersion}",
    "SysInstallSuccess" : "Udana instalacja oprogramowania w wersji {OsVersion}.",
    "RestartVehicle" : "Zrestartuj pojazd, aby wprowadzić zmiany.",
    "InstallNotSuccessful" : "Nieudana instalacja {errorType}",
    "InsertUSBDialogText" : "Włóż pamięć USB z pakietem preinstalacyjnym.",
    "AutoRetry" : "System automatycznie ponowi próbę aktualizacji.",
    "ValidatingUpdate" : "Sprawdzanie poprawności pakietu aktualizacji systemowych {OsVersion}",
    "FailsafeAvailable" : "Istniejący obraz pakietu awaryjnego jest dostępny.",
    "SystemFailure" : "Usterka systemowa",
    "SigCheckFailed" : "Nieudane sprawdzanie sygnatury pakietu",
    "UpdateToSoftwareVersion" : "Czy chcesz zainstalować aktualizację oprogramowania OS {InstallOsVersion}?",
    "NotAvailable" : "Niedostępna wersja bazy danych muzycznych",
};

framework.registerAppDictLoaded("sysupdate", "pl_PL");