var Localization_sysupdateAppDict_en_AU = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Search for update packages for Music Database on your USB device?",
    "SystemUpdate" : "System Update",
    "Search" : "Search",
    "SearchingForMusicUpdates" : "Searching for Updates",
    "AvailablePackages" : "Available Music Update Packages",
    "CurrentVersion" : "Music Update (Current)",
    "GracenoteVersion" : "Music Update",
    "SearchFailed" : "Search was Unsuccessful",
    "USER_TERMINATED" : "The update operation is cancelled by user.",
    "DEVICE_ERROR" : "USB Disconnected",
    "NOT_FOUND" : "The requested update package is missing.",
    "AUTH_FAILED" : "Failed to validate package certificate.",
    "INCOMPATIBLE_VERSION" : "The update package is incompatible with current board version.",
    "SEARCH_FAILED" : "Failed to execute the search operation.",
    "UPDATE_FAILED" : "Failed to execute the update operation.",
    "NOT_SUPPORTED" : "Operation not allowed because of missing module or functionality.",
    "UNKNOWN" : "Reason Unknown",
    "BUSY" : "The operation is requested in an inappropriate state.",
    "INVALID" : "The content of the update package is wrong or not sufficient.",
    "Retry" : "Retry",
    "NoNewMusicPackages" : "No New Music Update Packages Available",
    "NeedFailSafeImageUpdate" : "Need fail-safe image update to continue. Please contact the nearest dealer.",
    "CurrentDatabase" : "The Current Music Database version is {CurrentVersion}.",
    "InstallDatabase" : "Would you like to install Music Update {InstallVersion}?",
    "SystemNA" : "System is not fully available.",
    "SystemRestart" : "System Restart will take effect.",
    "Install" : "Install",
    "InstallMusic" : "Installing Music Updates {MusicVersion}",
    "VehicleRestart" : "Do not restart vehicle at this time.",
    "MusicInstallSuccess" : "Version {MusicVersion} Music install was successful.",
    "FunctionNA" : "Music Database Update Unsuccessful",
    "USBcatalog" : "USB cataloging will not be available.",
    "searchAgain" : "Please Search Again",
    "RebootReflash" : "Preparing to Update",
    "ValidationFailed" : "Validation Failed",
    "SearchSoftwareUpdates" : "Search for System Update packages on your USB device?",
    "SearchingForSoftwareUpdates" : "Searching for System Updates",
    "AvailableSoftwarePackages" : "Avail Software Update Packages",
    "CurrentOSVersion" : "Software Update (Current)",
    "SoftwareVersion" : "Software Update",
    "ReinstallationPackage" : "Reinstallation Package",
    "NoNewSoftwarePackages" : "No New Update Packages Available",
    "FailSafeImageUpdateNotify" : "Need fail-safe image update. Please perform the fail-safe image update.",
    "Continue" : "Continue",
    "CurrentSoftwareVersion" : "The current system {CurrentOsVersion} is running.",
    "ConfirmFailSafeUpdateInstall" : "Would you like to install fail-safe image update {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Installing Fail-Safe System Update",
    "DonotRestart" : "Do not restart vehicle at this time.",
    "InstallSuccessful" : "Install Successful",
    "NoReboot" : "No Reboot Is Required",
    "InstallUnsuccessful" : "Install Unsuccessful",
    "UpdatesNA" : "System Updates will not be available.",
    "OSVersion" : "OS Version is {CurrentOsVersion}",
    "MusicDBVersion" : "Music Database Version is {CurrentVersion}",
    "FailSafeImage" : "Fail-Safe Package",
    "InstallingSysUpdates" : "Installing System Updates {OsVersion}",
    "SysInstallSuccess" : "Version {OsVersion} Software Install was successful.",
    "RestartVehicle" : "Please restart the vehicle for changes to take effect.",
    "InstallNotSuccessful" : "Install not succesful {errorType}",
    "InsertUSBDialogText" : "Insert USB with re-install package.",
    "AutoRetry" : "The system will then automatically retry the update.",
    "ValidatingUpdate" : "Validating System Update Package {OsVersion}",
    "FailsafeAvailable" : "Existing fail-safe image is avilable.",
    "SystemFailure" : "System Failure",
    "SigCheckFailed" : "Package Signature Check Failed",
    "UpdateToSoftwareVersion" : "Would you like to install Software Update OS {InstallOsVersion}?",
    "NotAvailable" : "Music Database Version Not Available",
};

framework.registerAppDictLoaded("sysupdate", "en_AU");