var Localization_sysupdateAppDict_it_IT = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Ricercare pacchetti aggiornamenti per database musica sul proprio dispositivo USB?",
    "SystemUpdate" : "Aggior sistema",
    "Search" : "Ricerca",
    "SearchingForMusicUpdates" : "Ricerca di aggiornamenti",
    "AvailablePackages" : "Pacchetti aggiorn musica disponibili",
    "CurrentVersion" : "Aggiorn musica (attuale)",
    "GracenoteVersion" : "Aggiornamento musica",
    "SearchFailed" : "Nessun risultato trovato.",
    "USER_TERMINATED" : "L'operazione di aggiornamento è stata annullata dall'utente.",
    "DEVICE_ERROR" : "USB disconnesso",
    "NOT_FOUND" : "Il pacchetto di aggiornamenti richiesto non è presente.",
    "AUTH_FAILED" : "Impossibile convalidare il certificato del pacchetto.",
    "INCOMPATIBLE_VERSION" : "Il pacchetto degli aggiornamenti non è compatibile con la versione attuale.",
    "SEARCH_FAILED" : "Impossibile effettuare l'operazione di ricerca.",
    "UPDATE_FAILED" : "Impossibile effettuare l'operazione di aggiornamento.",
    "NOT_SUPPORTED" : "Operazione non consentita per modulo o funzionalità assente.",
    "UNKNOWN" : "Motivo sconosciuto.",
    "BUSY" : "L'operazione è stata richiesta in uno stato inappropriato.",
    "INVALID" : "Il contenuto del pacchetto aggiornamenti è incorretto o insufficiente.",
    "Retry" : "Riprova",
    "NoNewMusicPackages" : "Nessun pacchetto aggiornamento musica nuova disponibile.",
    "NeedFailSafeImageUpdate" : "È necessario l'aggiornamento dell'immagine file-safe. Contattare il concessionario più vicino.",
    "CurrentDatabase" : "La versione attuale del DB Musica è {CurrentVersion}.",
    "InstallDatabase" : "Installare aggiornamento musica {InstallVersion}?",
    "SystemNA" : "Il sistema non è completamente disp.",
    "SystemRestart" : "Si verificherà un riavvio del sistema.",
    "Install" : "Installa",
    "InstallMusic" : "Inst. aggiornamenti mus. {MusicVersion}",
    "VehicleRestart" : "Non riavviare il veicolo questa volta.",
    "MusicInstallSuccess" : "Installazione versione musica {MusicVersion} riuscita.",
    "FunctionNA" : "Aggiorn. database musica non riuscito.",
    "USBcatalog" : "La catalogazione USB non sarà disponibile.",
    "searchAgain" : "Ricerca di nuovo",
    "RebootReflash" : "Preparazione all'aggiornamento",
    "ValidationFailed" : "Convalida non riuscita.",
    "SearchSoftwareUpdates" : "Ricercare pacchetti aggiornamenti sistema sul proprio dispositivo USB?",
    "SearchingForSoftwareUpdates" : "Ricerca di aggiornamenti sistema",
    "AvailableSoftwarePackages" : "Aggiornamenti software disponibili",
    "CurrentOSVersion" : "Aggiorn software (attuale)",
    "SoftwareVersion" : "Aggiornamento software",
    "ReinstallationPackage" : "Pacchetto reinstallazione",
    "NoNewSoftwarePackages" : "Nessun pachetto aggiornamento nuovo disponibile.",
    "FailSafeImageUpdateNotify" : "È necessario caricare un'immagine fail-safe, si prega di effettuare l'aggiornamento dell'immagine fail-safe.",
    "Continue" : "Continua",
    "CurrentSoftwareVersion" : "Il sistema attuale {CurrentOsVersion} è in funzione.",
    "ConfirmFailSafeUpdateInstall" : "Installare aggiornamento immagine fail-safe {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Installazione aggiornamento Fail-System",
    "DonotRestart" : "Non riavviare il veicolo questa volta.",
    "InstallSuccessful" : "Installazione riuscita!",
    "NoReboot" : "Riavvio non necessario",
    "InstallUnsuccessful" : "Installazione non riuscita.",
    "UpdatesNA" : "Gli aggiorn. di sistema non saranno disp.",
    "OSVersion" : "La versione OS è {CurrentOsVersion}",
    "MusicDBVersion" : "La versione attuale del database musica è {CurrentVersion}",
    "FailSafeImage" : "Pacchetto failsafe",
    "InstallingSysUpdates" : "Installazione aggiornamenti sistema {OsVersion}",
    "SysInstallSuccess" : "Installazione version software {OsVersion}  riuscita.",
    "RestartVehicle" : "Riavviare il veicolo affinché le modifiche vengano attuate.",
    "InstallNotSuccessful" : "Installazione non riuscita {errorType}.",
    "InsertUSBDialogText" : "Inserire USB con pacchetto di re-installazione.",
    "AutoRetry" : "Il sistema riproverà automaticamente l'aggiornamento.",
    "ValidatingUpdate" : "Convalida pacchetto aggiornamento sistema {OsVersion}",
    "FailsafeAvailable" : "È disponibile un'immagine fail-safe già esistente.",
    "SystemFailure" : "Blocco del sistema.",
    "SigCheckFailed" : "Controllo firma pacchetto non riuscito.",
    "UpdateToSoftwareVersion" : "Installare l'aggiornamento software OS {InstallOsVersion}?",
    "NotAvailable" : "Versione database musica\nnon disponibile.",
};

framework.registerAppDictLoaded("sysupdate", "it_IT");