var Localization_sysupdateAppDict_hr_HR = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Tražiti pakete ažuriranja za bazu podataka glazbe na vašem USB uređaju?",
    "SystemUpdate" : "Ažur. sustava",
    "Search" : "Traži",
    "SearchingForMusicUpdates" : "Traženje ažuriranja",
    "AvailablePackages" : "Dostupni paketi ažuriranja glazbe",
    "CurrentVersion" : "Ažuriranje glazbe (trenutno)",
    "GracenoteVersion" : "Ažuriranje glazbe",
    "SearchFailed" : "Pretraživanje nije uspjelo",
    "USER_TERMINATED" : "Postupak ažuriranja otkazao je korisnik.",
    "DEVICE_ERROR" : "USB odvojen",
    "NOT_FOUND" : "Nedostaje traženi paket ažuriranja.",
    "AUTH_FAILED" : "Potvrđivanje certifikata paketa nije uspjelo.",
    "INCOMPATIBLE_VERSION" : "Paket ažuriranja nije kompatibilan s trenutačnom verzijom kartice.",
    "SEARCH_FAILED" : "Izvršavanje postupka pretraživanja nije uspjelo.",
    "UPDATE_FAILED" : "Izvršavanje postupka ažuriranja nije uspjelo.",
    "NOT_SUPPORTED" : "Postupak nije dopušten zbog nepostojanja modula ili funkcije.",
    "UNKNOWN" : "Nepoznat uzrok",
    "BUSY" : "Postupak je zatražen u neodgovarajućem stanju.",
    "INVALID" : "Sadržaj paketa ažuriranja je pogrešan ili nedovoljan.",
    "Retry" : "Pokušaj ponovno",
    "NoNewMusicPackages" : "Nema dostupnih paketa ažuriranja glazbe.",
    "NeedFailSafeImageUpdate" : "Za nastavak je potrebno ažuriranje fail-safe slike. Obratite se najbližem prodavaču.",
    "CurrentDatabase" : "Trenutačna inačica BP glazbe je {CurrentVersion}.",
    "InstallDatabase" : "Žalite li instalirati ažuriranje glazbe {InstallVersion}?",
    "SystemNA" : "Sustav nije u potpunosti dostupan.",
    "SystemRestart" : "Na snagu će stupiti pon. Pokret. sust.",
    "Install" : "Instaliraj",
    "InstallMusic" : "Instal. ažuriranja glazbe {MusicVersion}",
    "VehicleRestart" : "Sada nemojte ponovno pokretati vozilo.",
    "MusicInstallSuccess" : "Uspješno instaliranje inačice {MusicVersion} glazbe.",
    "FunctionNA" : "Neusp. ažuriranje baze podataka glazbe.",
    "USBcatalog" : "Katalogiziranje USB-a nije dostupno.",
    "searchAgain" : "Ponovno provedite pretraživanje.",
    "RebootReflash" : "Priprema za ažuriranje",
    "ValidationFailed" : "Potvrđivanje nije uspjelo",
    "SearchSoftwareUpdates" : "Tražiti pakete ažuriranja sustava na vašem USB uređaju?",
    "SearchingForSoftwareUpdates" : "Traženje ažuriranja sustava",
    "AvailableSoftwarePackages" : "Dostupni paketi ažuriranja softvera",
    "CurrentOSVersion" : "Ažuriranje softv. (trenutno)",
    "SoftwareVersion" : "Ažuriranje softvera",
    "ReinstallationPackage" : "Paket za ponovno instalaciju",
    "NoNewSoftwarePackages" : "Nema novih dostupnih paketa ažuriranja.",
    "FailSafeImageUpdateNotify" : "Potrebno je ažuriranje fail-safe slike; provedite ažuriranje fail-safe slike.",
    "Continue" : "Nastavi",
    "CurrentSoftwareVersion" : "Trenutni sustav {CurrentOsVersion} se izvodi.",
    "ConfirmFailSafeUpdateInstall" : "Želite li instalirati ažuriranje fail-safe slike {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Instal. ažur. sust. zaštite od kvara",
    "DonotRestart" : "Sada nemojte ponovno pokretati vozilo.",
    "InstallSuccessful" : "Uspješno instaliranje",
    "NoReboot" : "Nije potrebno ponovno podizanje",
    "InstallUnsuccessful" : "Neuspješno instaliranje",
    "UpdatesNA" : "Ažuriranja sustava neće biti dostupna.",
    "OSVersion" : "Inačica OS-a je {CurrentOsVersion}",
    "MusicDBVersion" : "Inačica baze podataka glazbe je {CurrentVersion}",
    "FailSafeImage" : "Fail Safe paket",
    "InstallingSysUpdates" : "Instaliranje ažuriranja sustava {OsVersion}",
    "SysInstallSuccess" : "Instal. verzije softvera {OsVersion} je uspješno.",
    "RestartVehicle" : "Ponovo pokrenite vozilo kako bi promjene stupile na snagu.",
    "InstallNotSuccessful" : "Instaliranje nije uspješno {errorType}",
    "InsertUSBDialogText" : "umetnite USB s paketom za pon. inst.",
    "AutoRetry" : "Sustav će potom autom. pon. pokušati ažuriranje.",
    "ValidatingUpdate" : "Prov. valj. paketa ažur. sustava {OsVersion}",
    "FailsafeAvailable" : "Postojeća slika zaštite od kvara je dostupna.",
    "SystemFailure" : "Kvar sustava",
    "SigCheckFailed" : "Neuspjeh provjere potpisa paketa",
    "UpdateToSoftwareVersion" : "Želite li instalirati\nažuriranje softvera\nOS {InstallOsVersion}?",
    "NotAvailable" : "Verzija baze podataka glazbe nije dostupna",
};

framework.registerAppDictLoaded("sysupdate", "hr_HR");