var Localization_sysupdateAppDict_hu_HU = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Kíván zenei adatbázishoz való frissítőcsomagot keresni az adott USB-eszközön?",
    "SystemUpdate" : "Rendszerfrissítés",
    "Search" : "Keresés",
    "SearchingForMusicUpdates" : "Frissítések keresése",
    "AvailablePackages" : "Rend. álló zenei frissítőcsomagok",
    "CurrentVersion" : "Zenei frissítés (aktuális)",
    "GracenoteVersion" : "Zenei frissítés",
    "SearchFailed" : "Sikertelen keresés",
    "USER_TERMINATED" : "Frissítés felhasználó által megszakítva.",
    "DEVICE_ERROR" : "USB lecsatlakozva",
    "NOT_FOUND" : "A kért frissítőcsomag hiányzik",
    "AUTH_FAILED" : "Csomagtanúsítvány hitelesítése sikertelen.",
    "INCOMPATIBLE_VERSION" : "Aktuális panelverzióval nem kompatibilis frissítőcsomag.",
    "SEARCH_FAILED" : "Keresési művelet végrehajtása sikertelen.",
    "UPDATE_FAILED" : "Frissítési művelet végrehajtása sikertelen.",
    "NOT_SUPPORTED" : "Hiányzó funkciós modul miatt nem lehetséges a művelet.",
    "UNKNOWN" : "Ismeretlen ok",
    "BUSY" : "Alkalmatlan állapotban kért művelet.",
    "INVALID" : "Hibás vagy hiányos tartalmú frissítőcsomag.",
    "Retry" : "Újrapróbálkozás",
    "NoNewMusicPackages" : "Nem áll rendelkezésre új zenei frissítési csomag.",
    "NeedFailSafeImageUpdate" : "Hibamentes képfrissítés szükséges a folytatáshoz; forduljon a helyi márkakereskedőhöz.",
    "CurrentDatabase" : "Az aktuális zenei adatbázis verziószáma: {CurrentVersion}",
    "InstallDatabase" : "Telepíti a(z) {InstallVersion} verziójú zenei frissítést?",
    "SystemNA" : "Nem teljes a rendszer rendelk. állása.",
    "SystemRestart" : "Rendszer-újraindítás következik.",
    "Install" : "Telepítés",
    "InstallMusic" : "Zenei frissítések tel. {MusicVersion}",
    "VehicleRestart" : "Most ne indítsa újra a járművet.",
    "MusicInstallSuccess" : "A(z) {MusicVersion} verziójú zenei telepítés sikeres volt.",
    "FunctionNA" : "Zenei adatbázis sikertelen frissítése.",
    "USBcatalog" : "USB-katalogizálásra nem lesz lehetőség.",
    "searchAgain" : "Végezzen új keresést.",
    "RebootReflash" : "Felkészülés frissítésre",
    "ValidationFailed" : "Sikertelen hitelesítés",
    "SearchSoftwareUpdates" : "Kíván rendszerfrissítő csomagot keresni az adott USB-eszközön?",
    "SearchingForSoftwareUpdates" : "Rendszerfrissítések keresése",
    "AvailableSoftwarePackages" : "Rend.álló szoftverfriss.csomagok",
    "CurrentOSVersion" : "Szoftverfrissítés (aktuális)",
    "SoftwareVersion" : "Szoftverfrissítés",
    "ReinstallationPackage" : "Újratelepítő csomag",
    "NoNewSoftwarePackages" : "Nem áll rendelkezésre új frissítési csomag.",
    "FailSafeImageUpdateNotify" : "A folytatáshoz frissíteni kell a biztonsági képet - szíveskedjék a biztonsági képet frissíteni.",
    "Continue" : "Folytatás",
    "CurrentSoftwareVersion" : "Jelenleg {CurrentOsVersion} verziójú operációs rendszer fut.",
    "ConfirmFailSafeUpdateInstall" : "Telepíti a(z) {FailsafeImageVersion} verziójú biztonsági képet?",
    "InstallingFailsafeSystem" : "Biztonsági rendszerfrissítések telepítése",
    "DonotRestart" : "Most ne indítsa újra a járművet.",
    "InstallSuccessful" : "Sikeres telepítés",
    "NoReboot" : "Rendszer újrabetöltése nem szükséges",
    "InstallUnsuccessful" : "Sikertelen telepítés",
    "UpdatesNA" : "Nem álnak rendszerfrissítések rendelk.",
    "OSVersion" : "Operációs rendszer verziószáma: {CurrentOsVersion}",
    "MusicDBVersion" : "Zenei adatbázis verziószáma {CurrentVersion}",
    "FailSafeImage" : "Biztonsági csomag",
    "InstallingSysUpdates" : "Rendszerfrissítések telepítése {OsVersion}",
    "SysInstallSuccess" : "{OsVersion}verzió szoftvertelepítése sikerült.",
    "RestartVehicle" : "Indítsa újra a járművet a változtatások érvényesítésére.",
    "InstallNotSuccessful" : "Nem sikerült a telepítés {errorType}.",
    "InsertUSBDialogText" : "Dugja be az újratelepítő csomagot tartalmazó USB-eszközt.",
    "AutoRetry" : "Automatikusan újrapróbálja a rendszer a frissítést.",
    "ValidatingUpdate" : "Rendszerfrissítő csomag frissítésének ellenőrzése {OsVersion}",
    "FailsafeAvailable" : "Hibamentes kép áll rendelkezésre.",
    "SystemFailure" : "Rendszerhiba",
    "SigCheckFailed" : "Csomag aláírásának ellenőrzése nem sikerült.",
    "UpdateToSoftwareVersion" : "Akarja telepíteni {InstallOsVersion} operációs rendszer szoftver frissítést?",
    "NotAvailable" : "Zenei adabázis verzió nem áll rendelkezésre.",
};

framework.registerAppDictLoaded("sysupdate", "hu_HU");