var Localization_sysupdateAppDict_ru_RU = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Выполнить поиск пакетов обновлений музыкальной базы данных на вашем USB-устройстве?",
    "SystemUpdate" : "Сис. обнвл.",
    "Search" : "Поиск",
    "SearchingForMusicUpdates" : "Выполняется поиск обновлений",
    "AvailablePackages" : "Доступ. обновления музыки",
    "CurrentVersion" : "Обновление музыки (тек.)",
    "GracenoteVersion" : "обновление музыки",
    "SearchFailed" : "Поиск был неудачным",
    "USER_TERMINATED" : "Операция обновления отменена пользователем.",
    "DEVICE_ERROR" : "Разъем USB отсоединен",
    "NOT_FOUND" : "Обновление запрошенного пакета отсутствует.",
    "AUTH_FAILED" : "Валидация сертификата пакета не выполнена.",
    "INCOMPATIBLE_VERSION" : "Пакет обновления насовместим с текущей версией.",
    "SEARCH_FAILED" : "Операция поиска не выполнена.",
    "UPDATE_FAILED" : "Операция обновления не выполнена.",
    "NOT_SUPPORTED" : "Операция не разрешена т.к. отсут-т модуль или функциональность.",
    "UNKNOWN" : "Причина неизвестна",
    "BUSY" : "Операция запрошена в несоответствующем состоянии.",
    "INVALID" : "Содержание пакета обновления неверное или несоответствующее.",
    "Retry" : "Повторная попытка",
    "NoNewMusicPackages" : "Новые пакеты обновления музыки отсутствуют.",
    "NeedFailSafeImageUpdate" : "Необх. обновление безотказ. изображения для продолжения, свяжитесь с дилером.",
    "CurrentDatabase" : "Текущая версия музыкальной БД {CurrentVersion}.",
    "InstallDatabase" : "Хотите установить музык. обновления {InstallVersion}?",
    "SystemNA" : "Система частично недоступна.",
    "SystemRestart" : "Необходима перезагрузка системы.",
    "Install" : "Установка",
    "InstallMusic" : "Устан-вка муз. Обновл. {MusicVersion}",
    "VehicleRestart" : "Просьба не выключать машину.",
    "MusicInstallSuccess" : "Установка версии музыки {MusicVersion} выполнена успешно.",
    "FunctionNA" : "Сбой обновления базы данных муз.",
    "USBcatalog" : "Каталогизирование USB будет недоступно.",
    "searchAgain" : "Выполните поиск еще раз.",
    "RebootReflash" : "Подготовка к обновлению",
    "ValidationFailed" : "Сбой проверки",
    "SearchSoftwareUpdates" : "Выполнить поиск пакетов обновления системы на вашем USB-устройстве?",
    "SearchingForSoftwareUpdates" : "Выполняется поиск сист. обновлений",
    "AvailableSoftwarePackages" : "Доступ. пакеты обновления ПО",
    "CurrentOSVersion" : "Обновление ПО (текущее)",
    "SoftwareVersion" : "Обновление ПО",
    "ReinstallationPackage" : "Переустановка пакета",
    "NoNewSoftwarePackages" : "Новые пакеты обновления отсутствуют.",
    "FailSafeImageUpdateNotify" : "Необходимо обновление образа системы безопасности.  Выполните обновление образа системы безопасности.",
    "Continue" : "Продолжить",
    "CurrentSoftwareVersion" : "Текущая система {CurrentOsVersion} включена",
    "ConfirmFailSafeUpdateInstall" : "Хотите установить обновление образа системы безопасности {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Установка обновления сист. Безоп-сти",
    "DonotRestart" : "Просьба не выключать машину.",
    "InstallSuccessful" : "Установка выполнена успешно",
    "NoReboot" : "Перезагрузка не требуется",
    "InstallUnsuccessful" : "Сбой установки",
    "UpdatesNA" : "Систем. обновления будут недоступ.",
    "OSVersion" : "Версия ОС {CurrentOsVersion}",
    "MusicDBVersion" : "Версия базы данных музыки {CurrentVersion}",
    "FailSafeImage" : "Пкт обнвл. сис. бзп.",
    "InstallingSysUpdates" : "Установка системных обновлений {OsVersion}",
    "SysInstallSuccess" : "Программное обеспечение версии {OsVersion} успешно установлено.",
    "RestartVehicle" : "Чтобы изменения вступили в силу перезапустите автомобиль.",
    "InstallNotSuccessful" : "Сбой установки {errorType}",
    "InsertUSBDialogText" : "вставьте USB-носитель с пакетом для переустановки.",
    "AutoRetry" : "Система попытается автоматически выполнить обновление.",
    "ValidatingUpdate" : "Проверка пакета системных обновлений {OsVersion}",
    "FailsafeAvailable" : "Доступен образ системы безопасности.",
    "SystemFailure" : "Сбой системы",
    "SigCheckFailed" : "Сбой проверки сигнатуры пакета",
    "UpdateToSoftwareVersion" : "Хотели бы вы установ. программного OS {InstallOsVersion}?",
    "NotAvailable" : "Версия музыкальной базы данных не доступна",
};

framework.registerAppDictLoaded("sysupdate", "ru_RU");