var Localization_sysupdateAppDict_zh_TW = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "在您的USB裝置上搜尋音樂資料庫的更新包？",
    "SystemUpdate" : "系統更新",
    "Search" : "搜尋",
    "SearchingForMusicUpdates" : "正在搜尋更新",
    "AvailablePackages" : "可用音樂更新包",
    "CurrentVersion" : "音樂更新（目前）",
    "GracenoteVersion" : "音樂更新",
    "SearchFailed" : "搜尋失敗",
    "USER_TERMINATED" : "更新操作被使用者取消。",
    "DEVICE_ERROR" : "已斷開USB的連接",
    "NOT_FOUND" : "所需的更新包遺失。",
    "AUTH_FAILED" : "包證書驗證失敗。",
    "INCOMPATIBLE_VERSION" : "更新包和目前版本不相容。",
    "SEARCH_FAILED" : "無法執行搜尋操作。",
    "UPDATE_FAILED" : "無法執行更新操作。",
    "NOT_SUPPORTED" : "因遺失模組或功能，不允許執行。",
    "UNKNOWN" : "原因未知",
    "BUSY" : "在不適當的狀態下請求了此操作。",
    "INVALID" : "更新包內容錯誤或不完整。",
    "Retry" : "重試",
    "NoNewMusicPackages" : "未獲得新的音樂更新包。",
    "NeedFailSafeImageUpdate" : "需要故障保護映射更新才能繼續，請聯絡最近的經銷商。",
    "CurrentDatabase" : "目前音樂資料庫版本為{CurrentVersion}。",
    "InstallDatabase" : "是否要安裝音樂更新{InstallVersion}？",
    "SystemNA" : "系統部分可用",
    "SystemRestart" : "系統重啟後生效。",
    "Install" : "安裝",
    "InstallMusic" : "正在安裝音樂更新 {MusicVersion}",
    "VehicleRestart" : "請勿在此時重啟車輛。",
    "MusicInstallSuccess" : "版本{MusicVersion}音樂安裝成功",
    "FunctionNA" : "音樂資料庫更新失敗。",
    "USBcatalog" : "將不提供USB目錄。",
    "searchAgain" : "請再次搜尋。",
    "RebootReflash" : "正在準備更新",
    "ValidationFailed" : "驗證失敗",
    "SearchSoftwareUpdates" : "在您的USB裝置上搜尋系統更新包？",
    "SearchingForSoftwareUpdates" : "正在搜尋系統更新",
    "AvailableSoftwarePackages" : "可用軟體更新包",
    "CurrentOSVersion" : "軟體更新（目前）",
    "SoftwareVersion" : "軟體更新",
    "ReinstallationPackage" : "重新安裝包",
    "NoNewSoftwarePackages" : "未獲得新的更新包。",
    "FailSafeImageUpdateNotify" : "需要故障保護映射更新，請執行故障保護映射更新。",
    "Continue" : "繼續",
    "CurrentSoftwareVersion" : "目前系統 {CurrentOsVersion} 正在執行。",
    "ConfirmFailSafeUpdateInstall" : "是否要安裝故障保護映射更新{FailsafeImageVersion}？",
    "InstallingFailsafeSystem" : "正在安裝故障保護系統更新",
    "DonotRestart" : "請勿在此時重啟車輛。",
    "InstallSuccessful" : "安裝成功",
    "NoReboot" : "無需重啟",
    "InstallUnsuccessful" : "安裝失敗",
    "UpdatesNA" : "將不提供系統更新。",
    "OSVersion" : "操作系統版本為{CurrentOsVersion}",
    "MusicDBVersion" : "音樂資料庫版本為{CurrentVersion}",
    "FailSafeImage" : "故障保護包",
    "InstallingSysUpdates" : "正在安裝系統更新 {OsVersion}",
    "SysInstallSuccess" : "版本 {OsVersion} 軟體安裝成功。",
    "RestartVehicle" : "請重新起動車輛，以便使變更生效。",
    "InstallNotSuccessful" : "未成功安裝 {errorType}",
    "InsertUSBDialogText" : "插入包含重裝包的 USB。",
    "AutoRetry" : "然後系統將自動重試此更新。",
    "ValidatingUpdate" : "正在驗證系統更新包 {OsVersion}",
    "FailsafeAvailable" : "現有故障保護映射不可用。",
    "SystemFailure" : "系統故障",
    "SigCheckFailed" : "包簽名檢查失敗",
    "UpdateToSoftwareVersion" : "想要安裝軟體更新 OS {InstallOsVersion}？",
    "NotAvailable" : "音樂資料庫版本不可用",
};

framework.registerAppDictLoaded("sysupdate", "zh_TW");