var Localization_sysupdateAppDict_fi_FI = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Etsitäänkö musiikkitietokannan päivityspaketteja USB-laitteesta?",
    "SystemUpdate" : "Järjestelmäpäiv.",
    "Search" : "Etsi",
    "SearchingForMusicUpdates" : "Etsitään päivityksiä",
    "AvailablePackages" : "Saatavilla olevat musiikkipäiv.",
    "CurrentVersion" : "Musiikkipäivitys (nykyinen)",
    "GracenoteVersion" : "Musiikkipäivitys",
    "SearchFailed" : "Etsintä epäonnistui",
    "USER_TERMINATED" : "Käyttäjä peruutti päivitystoiminnon.",
    "DEVICE_ERROR" : "USB-laite irrotettu",
    "NOT_FOUND" : "Pyydetty päivityspaketti puuttuu.",
    "AUTH_FAILED" : "Paketin sertifikaatin vahventaminen epäonnistui.",
    "INCOMPATIBLE_VERSION" : "Päivityspaketti ei ole yhteensopiva nykyisen version kanssa.",
    "SEARCH_FAILED" : "Hakutoimintoa ei voitu suorittaa.",
    "UPDATE_FAILED" : "Päivitystoimintoa ei voitu suorittaa.",
    "NOT_SUPPORTED" : "Toiminto ei ole sallittu, koska moduuli tai toiminto puuttuu.",
    "UNKNOWN" : "Tuntematon syy",
    "BUSY" : "Pyydetty toiminto on väärässä tilassa.",
    "INVALID" : "Päivityspaketin sisältö on virheellinen tai puutteellinen.",
    "Retry" : "Yritä uudelleen",
    "NoNewMusicPackages" : "Uusia musiikkipäivityspaketteja ei ole saatavilla.",
    "NeedFailSafeImageUpdate" : "Jatkaminen edellyttää vikasietotilan levykuvan päivitystä. Ota yhteyttä lähimpään jälleenmyyjään.",
    "CurrentDatabase" : "Musiikkitietokannan tämänhetkinen versio on {CurrentVersion}.",
    "InstallDatabase" : "Haluatko asentaa musiikkipäivityksen {InstallVersion}?",
    "SystemNA" : "Järjest. kaikki toim. eivät ole käytettäv.",
    "SystemRestart" : "Järjestelmä käynnistetään nyt uudelleen.",
    "Install" : "Asenna",
    "InstallMusic" : "Asentaa musiikkipäivityksiä {MusicVersion}",
    "VehicleRestart" : "Älä käynnistä autoa uudelleen nyt.",
    "MusicInstallSuccess" : "Versio {MusicVersion} musiikin asentaminen onnistui.",
    "FunctionNA" : "Musiikkitietokannan päivitys epäonnistui.",
    "USBcatalog" : "USB-laitteen luettelotoiminto ei ole käytettävissä.",
    "searchAgain" : "Suorita haku uudelleen.",
    "RebootReflash" : "Valmistellaan päivittämistä",
    "ValidationFailed" : "Varmistus epäonnistui",
    "SearchSoftwareUpdates" : "Etsitäänkö järjestelmäpäivityspaketteja USB-laitteesta?",
    "SearchingForSoftwareUpdates" : "Etsitään järjestelmäpäivityksiä",
    "AvailableSoftwarePackages" : "Saatavilla olevat ohj.päivitykset",
    "CurrentOSVersion" : "Ohjelmistopäiv. (nykyinen)",
    "SoftwareVersion" : "Ohjelmistopäivitys",
    "ReinstallationPackage" : "Uudelleenasennuspaketti",
    "NoNewSoftwarePackages" : "Uusia päivityspaketteja ei ole saatavilla.",
    "FailSafeImageUpdateNotify" : "Tarvitaan vikasietotilan levykuvan päivitys. Suorita vikasietotilan levykuvan päivitys.",
    "Continue" : "Jatka",
    "CurrentSoftwareVersion" : "Tämänhetkinen järjestelmä {CurrentOsVersion} on käynnissä.",
    "ConfirmFailSafeUpdateInstall" : "Haluatko asentaa vikasietotilan levykuvan päivityksen {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "Asennetaan vikasietotilan järj.päivitystä",
    "DonotRestart" : "Älä käynnistä autoa uudelleen nyt.",
    "InstallSuccessful" : "Asennus onnistui",
    "NoReboot" : "Ei vaadi uudelleenkäynnistystä",
    "InstallUnsuccessful" : "Asennus epäonnistui",
    "UpdatesNA" : "Järjest.äivitykset eivät ole saatavilla.",
    "OSVersion" : "Käyttöjärjestelmän versio on {CurrentOsVersion}",
    "MusicDBVersion" : "Musiikkitietokannan versio on {CurrentVersion}",
    "FailSafeImage" : "Vikasietotilan paketti",
    "InstallingSysUpdates" : "Järjestelmäpäivityksiä asennetaan {OsVersion}",
    "SysInstallSuccess" : "Version {OsVersion} ohjelmiston asentaminen onnistui.",
    "RestartVehicle" : "Käynnistä auto, jotta muutokset tulevat voimaan.",
    "InstallNotSuccessful" : "Asennus epäonnistui {errorType}",
    "InsertUSBDialogText" : "liitä USB-laite, jossa on uudelleenasennustiedosto.",
    "AutoRetry" : "Järjestelmä yrittää sen jälkeen päivitystä automaattisesti uudelleen.",
    "ValidatingUpdate" : "Vahvistetaan järjestelmäpäivityspakettia {OsVersion}",
    "FailsafeAvailable" : "Olemassa oleva vikasietotilan levykuva on saatavilla.",
    "SystemFailure" : "Järjestelmähäiriö",
    "SigCheckFailed" : "Paketin allekirjoituksen tarkistaminen epäonnistui",
    "UpdateToSoftwareVersion" : "Haluatko asentaa ohjelmistopäivityksen käyttöjärjestelmän {InstallOsVersion}?",
    "NotAvailable" : "Musiikkitietokannan versio ei ole saatavilla",
};

framework.registerAppDictLoaded("sysupdate", "fi_FI");