var Localization_sysupdateAppDict_he_IL = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "האם לחפש את חבילות עדכון של בסיס נתונים  מוזיקלי בהתקן USB  שלך?",
    "SystemUpdate" : "עדכון המערכת",
    "Search" : "חפש",
    "SearchingForMusicUpdates" : "מחפש עדכונים",
    "AvailablePackages" : "ישנן חבילות עדכוני מוזיקה",
    "CurrentVersion" : "עדכון מוזיקה (נוכחי)",
    "GracenoteVersion" : "עדכון מוזיקה",
    "SearchFailed" : "חיפוש בלתי מוצלח",
    "USER_TERMINATED" : "פעולת עדכון בוטלה ע\"י משתמש.",
    "DEVICE_ERROR" : "USB נותק",
    "NOT_FOUND" : "חבילת עדכון רצויה חסרה.",
    "AUTH_FAILED" : "נכשל ניסיון לאמת את תעודת החבילה.",
    "INCOMPATIBLE_VERSION" : "חבילת עדכון לא תואמת לגירסת  נוהל עכשוית.",
    "SEARCH_FAILED" : "ביצוע פעולת חיפוש נכשל.",
    "UPDATE_FAILED" : "ביצוע פעולת עדכון נכשל.",
    "NOT_SUPPORTED" : "פעולה אסורה בגלל מודול או תפקוד חסר",
    "UNKNOWN" : "סיבה לא ידועה",
    "BUSY" : "הפעולה נדרשת במצב לא מתאים.",
    "INVALID" : "תוכן חבילת העדכון לא נכון או לא מספיק.",
    "Retry" : "נסה שנית",
    "NoNewMusicPackages" : "אין חבילות של עדכון מוזיקה זמינות.",
    "NeedFailSafeImageUpdate" : "זקוק לעדכון דימוי אל-כשל  על מנת להמשיך, אנא צור קשר עם הסוכן הקרוב ביותר.",
    "CurrentDatabase" : "גירסת הDB מוזיקה העכשוית היא {CurrentVersion}.",
    "InstallDatabase" : "האם ברצונך להתקין את עדכון המוזיקה {InstallVersion}?",
    "SystemNA" : "מערכת אינה זמינה בשלמותה.",
    "SystemRestart" : "חידוש המערכת ייכנס לתוקף.",
    "Install" : "התקן",
    "InstallMusic" : "מתקין עדכוני מוזיקה {MusicVersion}",
    "VehicleRestart" : "על תפעיל את הרכב שוב כעת.",
    "MusicInstallSuccess" : "גירסה {MusicVersion} התקנת מוזיקה הצליחה.",
    "FunctionNA" : "עדכון נתונים של מוזיקה לא הצליח.",
    "USBcatalog" : "קיטלוג USB לא יהיה זמין.",
    "searchAgain" : "נא לחפש שוב.",
    "RebootReflash" : "מתכונן לעדכון",
    "ValidationFailed" : "אימות נכשל",
    "SearchSoftwareUpdates" : "האם לחפש את חבילות עדכון המערכת בהתקן USB  שלך?",
    "SearchingForSoftwareUpdates" : "מחפש עדכוני מערכת",
    "AvailableSoftwarePackages" : "ישנן חבילות עדכוני תוכנות ",
    "CurrentOSVersion" : "עדכון התוכנה (נוכחי)",
    "SoftwareVersion" : "עדכון התוכנה",
    "ReinstallationPackage" : "חבילת התקנה מחדש",
    "NoNewSoftwarePackages" : "אין חבילות עדכון חדשות זמינות.",
    "FailSafeImageUpdateNotify" : "זקוק לעדכון של דימוי אל-כשל , בצע עדכון של דימוי אל-כשל",
    "Continue" : "המשך",
    "CurrentSoftwareVersion" : "מערכת ההפעלה {CurrentOsVersion} פועלת.",
    "ConfirmFailSafeUpdateInstall" : "האם ברצונך להתקין את עדכון דימוי אל-כשל  {FailsafeImageVersion}?",
    "InstallingFailsafeSystem" : "מתקין עדכון אל-כשל",
    "DonotRestart" : "על תפעיל את הרכב שוב כעת.",
    "InstallSuccessful" : "התקנה מוצלחת",
    "NoReboot" : "לא נדרש אתחול מחדש",
    "InstallUnsuccessful" : "התקנה לא מוצלחת",
    "UpdatesNA" : "עדכוני מערכת לא יהיו זמינים",
    "OSVersion" : "גרסת מערכת הפעלה היא {CurrentOsVersion}",
    "MusicDBVersion" : "גירסת בסיס נתונים של מוזיקה היא {CurrentVersion}",
    "FailSafeImage" : "חבילת אל-כשל",
    "InstallingSysUpdates" : "מתקין עדכוני מערכת {OsVersion}",
    "SysInstallSuccess" : "התקנת גרסת התוכנה {OsVersion} הצליחה",
    "RestartVehicle" : "נא להפעיל מחדש את הרכב, כדי שהשינויים ייכנסו לתוקף.",
    "InstallNotSuccessful" : "ההתקנה לא הצליחה {errorType}",
    "InsertUSBDialogText" : "הכנס USB עם חבילת התקנה מחדש.",
    "AutoRetry" : "לאחר מכן המערכת תנסה להתעדכן מחדש אוטומטית.",
    "ValidatingUpdate" : "מאמת חבילת עדכון מערכת {OsVersion}",
    "FailsafeAvailable" : "תמונת אל-כשל של דיסק זמינה",
    "SystemFailure" : "כשל מערכת",
    "SigCheckFailed" : "בדיקת חתימת החבילה נכשלה",
    "UpdateToSoftwareVersion" : "האם ברצונך להתקין את עדכון תוכנת מערכת ההפעלה {InstallOsVersion}?",
    "NotAvailable" : "מוסיקה גרסת מסד הנתונים לא זמינה",
};

framework.registerAppDictLoaded("sysupdate", "he_IL");