var Localization_sysupdateAppDict_zh_CN = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "在您的USB设备上搜索音乐数据库的更新包？",
    "SystemUpdate" : "系统更新",
    "Search" : "搜索",
    "SearchingForMusicUpdates" : "正在搜索更新",
    "AvailablePackages" : "可用音乐更新包",
    "CurrentVersion" : "音乐更新（当前）",
    "GracenoteVersion" : "音乐更新",
    "SearchFailed" : "搜索失败",
    "USER_TERMINATED" : "更新操作被用户取消。",
    "DEVICE_ERROR" : "已断开USB的连接",
    "NOT_FOUND" : "所需的更新包丢失。",
    "AUTH_FAILED" : "包证书验证失败。",
    "INCOMPATIBLE_VERSION" : "更新包和当前版本不兼容。",
    "SEARCH_FAILED" : "无法执行搜索操作。",
    "UPDATE_FAILED" : "无法执行更新操作。",
    "NOT_SUPPORTED" : "因丢失模块或功能，不允许运行。",
    "UNKNOWN" : "原因未知",
    "BUSY" : "在不适当的状态下请求了此操作。",
    "INVALID" : "更新包内容错误或不完整。",
    "Retry" : "重试",
    "NoNewMusicPackages" : "未获得新的音乐更新包。",
    "NeedFailSafeImageUpdate" : "需要故障保护映像更新才能继续，请联系最近的经销商。",
    "CurrentDatabase" : "当前音乐数据库版本为{CurrentVersion}。",
    "InstallDatabase" : "是否要安装音乐更新{InstallVersion}？",
    "SystemNA" : "系统部分可用。",
    "SystemRestart" : "系统重启后生效。",
    "Install" : "安装",
    "InstallMusic" : "正在安装音乐更新 {MusicVersion}",
    "VehicleRestart" : "请勿在此时重启车辆。",
    "MusicInstallSuccess" : "版本{MusicVersion}音乐安装成功",
    "FunctionNA" : "音乐数据库更新失败。",
    "USBcatalog" : "将不提供USB目录。",
    "searchAgain" : "请重新搜索",
    "RebootReflash" : "正在准备更新",
    "ValidationFailed" : "验证失败",
    "SearchSoftwareUpdates" : "在您的USB设备上搜索系统更新包？",
    "SearchingForSoftwareUpdates" : "正在搜索系统更新",
    "AvailableSoftwarePackages" : "可用软件更新包",
    "CurrentOSVersion" : "软件更新（当前）",
    "SoftwareVersion" : "软件更新",
    "ReinstallationPackage" : "重新安装包",
    "NoNewSoftwarePackages" : "未获得新的更新包。",
    "FailSafeImageUpdateNotify" : "需要故障保护映像更新，请执行故障保护映像更新。",
    "Continue" : "继续",
    "CurrentSoftwareVersion" : "当前系统 {CurrentOsVersion} 正在运行。",
    "ConfirmFailSafeUpdateInstall" : "是否要安装故障保护映像更新{FailsafeImageVersion}？",
    "InstallingFailsafeSystem" : "正在安装故障保护系统更新",
    "DonotRestart" : "请勿在此时重启车辆。",
    "InstallSuccessful" : "安装成功",
    "NoReboot" : "无需重启",
    "InstallUnsuccessful" : "安装失败",
    "UpdatesNA" : "将不提供系统更新。",
    "OSVersion" : "操作系统版本为{CurrentOsVersion}",
    "MusicDBVersion" : "音乐数据库版本为{CurrentVersion}",
    "FailSafeImage" : "故障保护包",
    "InstallingSysUpdates" : "正在安装系统更新 {OsVersion}",
    "SysInstallSuccess" : "版本 {OsVersion} 软件安装成功。",
    "RestartVehicle" : "请重新起动车辆，以便使更改生效。",
    "InstallNotSuccessful" : "未成功安装 {errorType}",
    "InsertUSBDialogText" : "插入包含重装包的 USB。",
    "AutoRetry" : "然后系统将自动重试此更新。",
    "ValidatingUpdate" : "正在验证系统更新包 {OsVersion}",
    "FailsafeAvailable" : "现有故障保护映像不可用。",
    "SystemFailure" : "系统故障",
    "SigCheckFailed" : "包签名检查失败",
    "UpdateToSoftwareVersion" : "想要安装软件更新 OS {InstallOsVersion}？",
    "NotAvailable" : "音乐数据库版本不可用",
};

framework.registerAppDictLoaded("sysupdate", "zh_CN");