var Localization_sysupdateAppDict_de_DE = {
    //"stringId" : "localString"
    "SearchMusicDBUpdate" : "Suche nach Update-Paketen für Musik. Datenbank auf Ihrem USB-Gerät?",
    "SystemUpdate" : "Systemaktualisierung",
    "Search" : "Suchen",
    "SearchingForMusicUpdates" : "Es wird nach Updates gesucht",
    "AvailablePackages" : "Verfügbare Musik-Update-Pakete",
    "CurrentVersion" : "Musik-Update (aktuell)",
    "GracenoteVersion" : "Musik aktualisieren",
    "SearchFailed" : "Suche war nicht erfolgreich",
    "USER_TERMINATED" : "Der Update-Vorgang wurde vom Benutzer abgebrochen.",
    "DEVICE_ERROR" : "USB getrennt",
    "NOT_FOUND" : "Das angeforderte Update-Paket fehlt.",
    "AUTH_FAILED" : "Das Paketzertifikat konnte nicht überprüft werden",
    "INCOMPATIBLE_VERSION" : "Das Update-Paket ist nicht kompatibel mit der aktuellen Board-Version",
    "SEARCH_FAILED" : "Der Suchvorgang konnte nicht durchgeführt werden.",
    "UPDATE_FAILED" : "Der Update-Vorgang konnte nicht durchgeführt werden.",
    "NOT_SUPPORTED" : "Betrieb aufgrund fehlendem Modul oder Funktionalität nicht erlaubt.",
    "UNKNOWN" : "Grund: unbekannt.",
    "BUSY" : "Der Vorgang wird in einem ungeeigneten Zustand angefordert.",
    "INVALID" : "Der Inhalt des Update-Pakets ist falsch oder reicht nicht aus.",
    "Retry" : "Wiederholen",
    "NoNewMusicPackages" : "Kein neues Musikpaket zur Aktualisierung verfügbar.",
    "NeedFailSafeImageUpdate" : "Ausfallsichere Bildaktualisierung erforderlich, um fortzufahren. Bitte kontaktieren Sie einen Fachhändler.",
    "CurrentDatabase" : "Die aktuelle Musik-DB-Version ist {CurrentVersion}.",
    "InstallDatabase" : "Möchten Sie die Musikaktualisierung {InstallVersion} installieren?",
    "SystemNA" : "System ist nicht vollständig verfügbar.",
    "SystemRestart" : "Das System wird neu gestartet.",
    "Install" : "Installieren",
    "InstallMusic" : "Installiere Musik-Updates {MusicVersion}",
    "VehicleRestart" : "Das Fahrzeug jetzt nicht erneut starten.",
    "MusicInstallSuccess" : "Version {MusicVersion} zur Musik-Installation war erfolgreich.",
    "FunctionNA" : "Musik-Datenbankupdate fehlgeschlagen.",
    "USBcatalog" : "Die USB-Katalogisierung ist nicht verfügbar.",
    "searchAgain" : "Bitte versuchen Sie es erneut.",
    "RebootReflash" : "Update wird vorbereitet",
    "ValidationFailed" : "Validierung fehlgeschlagen",
    "SearchSoftwareUpdates" : "Suche nach dem System Update-Paket auf Ihrem USB-Gerät?",
    "SearchingForSoftwareUpdates" : "Es wird nach System-Updates gesucht",
    "AvailableSoftwarePackages" : "Verfügb. Software Update-Pakete",
    "CurrentOSVersion" : "Software-Update (aktuell)",
    "SoftwareVersion" : "Software-Update",
    "ReinstallationPackage" : "Neu-Installierungspaket",
    "NoNewSoftwarePackages" : "Keine neuen Update-Pakete verfügbar.",
    "FailSafeImageUpdateNotify" : "Benötigt ausfallsicheres Bildaufnahme-Update, bitte führen Sie das Update f. d. ausfallsichere Bildaufnahme durch.",
    "Continue" : "Fortfahren",
    "CurrentSoftwareVersion" : "Das aktuelle System {CurrentOsVersion} wird ausgeführt.",
    "ConfirmFailSafeUpdateInstall" : "Möchten Sie die ausfallsichere Bildaktualisierung {FailsafeImageVersion} installieren?",
    "InstallingFailsafeSystem" : "Fail-Safe-Systemupdate wird installiert",
    "DonotRestart" : "Das Fahrzeug jetzt nicht erneut starten.",
    "InstallSuccessful" : "Installation erfolgreich",
    "NoReboot" : "Kein Neustart erforderlich",
    "InstallUnsuccessful" : "Installation nicht erfolgreich",
    "UpdatesNA" : "Systemupdates nicht Verfügung stehen.",
    "OSVersion" : "Betriebssystemversion ist {CurrentOsVersion}",
    "MusicDBVersion" : "Musikdatenbankversion ist {CurrentVersion}",
    "FailSafeImage" : "Ausfallsicheres Paket",
    "InstallingSysUpdates" : "System-Updates {OsVersion} werden installiert",
    "SysInstallSuccess" : "Installation der Software-Version {OsVersion} war erfolgreich.",
    "RestartVehicle" : "Bitte starten Sie das Fahrzeug erneut, damit die Änderungen wirksam werden.",
    "InstallNotSuccessful" : "Installation nicht erfolgreich {errorType}",
    "InsertUSBDialogText" : "Verbinden Sie USB mit Neuinstallationspaket.",
    "AutoRetry" : "Das System wiederholt dann automatisch den Update-Versuch.",
    "ValidatingUpdate" : "Überprüfe System-Updatepaket {OsVersion}",
    "FailsafeAvailable" : "Ein existierendes Ausfall-Image ist verfügbar.",
    "SystemFailure" : "Systemausfall",
    "SigCheckFailed" : "Prüfung der Paketsignatur gescheitert",
    "UpdateToSoftwareVersion" : "Möchten Sie Software Update OS installieren {InstallOsVersion}?",
    "NotAvailable" : "Musikdatenbankversion nicht verfügbar",
};

framework.registerAppDictLoaded("sysupdate", "de_DE");