var Localization_vdtAppDict_da_DK = {
    //"stringId" : "localString"
    "VDT" : "VDT",
    "StartRecording" : "Start optagelse af kørselslog",
    "StopRecording" : "Stop optagelse af kørselslog",
    "DeleteButton" : "Slet",
    "BackButton" : "Tilbage",
    "ClearButton" : "Ryd",
    "RetryButton" : "Forsøg igen",
    "CancelButton" : "Annullér",
    "USBTransferTitle" : "USB-dataoverførsel",
    "ClearAllData" : "Ryd alle data",
    "SelectCopyData" : "Kopiér data til USB",
    "ConfirmClearAllDataDialogText" : "Er du sikker på, at du vil slette alle data?",
    "ClearDataRetryDialogText" : "Kunne ikke slette alle data. Vil du forsøge igen?",
    "SendDataRetryDialogText" : "Kunne ikke kopiere til USB. Vil du forsøge igen?",
    "ConfirmCleariDMDataDialogText" : "Vil du slette den valgte kørselslog?",
    "USBMemoryFullDialogText" : "Kunne ikke kopiere data til USB. USB-hukommelse fuld. Vil du forsøge igen?",
    "InsertUSBDialogText" : "Kunne ikke kopiere data til USB. Isæt USB-drev og forsøg igen.",
    "ClearDataSuccess" : "Dataene er nu slettet.",
    "ClearDataFailure" : "Dataene kunne ikke slettes.",
    "CopyDataSuccess" : "Kopiering af data til USB er nu udført.",
    "CopyDataFailure" : "Dataene kunne ikke kopieres.",
    "CopyDataFailureUSBFull" : "USB-hukommelse fuld.",
    "CopyDataFailureUSBRemoved" : "Isæt USB-drev",
    "ProtectionErrorDialogText" : "Kun 1 beskyttet fil pr. fører-id er tilladt. Slet en fil eller slå beskyttelse fra.",
    "CopyingDialogText1" : "Kopierer data til USB. Fjern ikke USB-stik eller sluk for bilen.",
    "CopyingDialogText2" : "{noOfFilesCopied} af {totalFiles} filer overført.",
};

framework.registerAppDictLoaded("vdt", "da_DK");