var Localization_vdtAppDict_sr_RS = {
    //"stringId" : "localString"
    "VDT" : "VDT",
    "StartRecording" : "Čuvaj info. o vožnji",
    "StopRecording" : "Prekini čuv.info. o vožnji",
    "DeleteButton" : "Izbriši",
    "BackButton" : "Nazad",
    "ClearButton" : "Poništi",
    "RetryButton" : "Pokušaj ponovo",
    "CancelButton" : "Otkaži",
    "USBTransferTitle" : "Prenos podataka sa USB uređaja",
    "ClearAllData" : "Obriši sve podatke",
    "SelectCopyData" : "Kopiraj podatke na USB",
    "ConfirmClearAllDataDialogText" : "Da li ste sigurni da želite da izbrišete sve podatke?",
    "ClearDataRetryDialogText" : "Nije moguće izbrisati sve podatke. Želite li da pokušate ponovo?",
    "SendDataRetryDialogText" : "Nije moguće kopirati podatke na USB uređaj. Želite li da pokušate ponovo?",
    "ConfirmCleariDMDataDialogText" : "Da li želite da izbrišete odabrane informacije o vožnji?",
    "USBMemoryFullDialogText" : "Nije moguće kopirati podatke na USB. Memorija je puna. Želite li da pokušate ponovo?",
    "InsertUSBDialogText" : "Nije moguće kopirati podatke na USB. Privežite USB i pokušajte ponovo.",
    "ClearDataSuccess" : "Podaci su uspešno obrisani",
    "ClearDataFailure" : "Podatke nije moguće obrisati",
    "CopyDataSuccess" : "Podaci su uspešno kopirani na USB",
    "CopyDataFailure" : "Nije moguće kopirati podatke",
    "CopyDataFailureUSBFull" : "USB memorija je puna",
    "CopyDataFailureUSBRemoved" : "Povežite USB uređaj",
    "ProtectionErrorDialogText" : "Dozvoljen je samo 1 zaštićen fajl za ID vozača. Obrišite fajl ili isključite zaštitu.",
    "CopyingDialogText1" : "Kopiranje podataka na USB flesh memoriju. Nemojte uklanjati USSB i nemojte gasiti auto.",
    "CopyingDialogText2" : "Prebačeno je {noOfFilesCopied} od {totalFiles} fajlova. ",
};

framework.registerAppDictLoaded("vdt", "sr_RS");