var Localization_vdtAppDict_hr_HR = {
    //"stringId" : "localString"
    "VDT" : "VDT",
    "StartRecording" : "Počni snimanje zapisa o vožnji",
    "StopRecording" : "Zaustavi snimanje zapisa o vožnji",
    "DeleteButton" : "Izbriši",
    "BackButton" : "Natrag",
    "ClearButton" : "Obriši",
    "RetryButton" : "Pon. pok.",
    "CancelButton" : "Otkaži",
    "USBTransferTitle" : "Prijenos USB pod.",
    "ClearAllData" : "Obriši sve pod.",
    "SelectCopyData" : "Kop. pod. na USB",
    "ConfirmClearAllDataDialogText" : "Jeste li sigurni da želite obrisati sve podatke?",
    "ClearDataRetryDialogText" : "Sve pod. nije moguće obrisati. Želite li pok. ponovno?",
    "SendDataRetryDialogText" : "Kopiranje pod. na USB nije moguće. Želite li pok. ponovno?",
    "ConfirmCleariDMDataDialogText" : "Želite li izbrisati odabrani zapis o vožnji?",
    "USBMemoryFullDialogText" : "Kopiranje pod. na USB nije moguće. USB memorija je puna. Želite li pok. ponovno?",
    "InsertUSBDialogText" : "Kopiranje pod. na USB nije moguće. Umet. USB pogon i pok. ponovno.",
    "ClearDataSuccess" : "Uspješno brisanje pod.",
    "ClearDataFailure" : "Pod. se ne mogu obristati",
    "CopyDataSuccess" : "Kop. pod. na USB uspješno",
    "CopyDataFailure" : "Pod. se ne mogu kopirati",
    "CopyDataFailureUSBFull" : "USB memorija je puna",
    "CopyDataFailureUSBRemoved" : "Umetni USB pog.",
    "ProtectionErrorDialogText" : "ID vozača dozvoljava samo jednu zaštićenu datoteku. Obrišite datoteku ili isključite zaštitu.",
    "CopyingDialogText1" : "Kopiranje podataka na USB. Ne uklanjajte USB uređaj ili isključite vozilo.",
    "CopyingDialogText2" : "Preneseno je {noOfFilesCopied} od {totalFiles} datoteka.",
};

framework.registerAppDictLoaded("vdt", "hr_HR");