var Localization_vdtAppDict_lv_LV = {
    //"stringId" : "localString"
    "VDT" : "VDT",
    "StartRecording" : "Sākt braukšanas žurnāla ierakstīšanu",
    "StopRecording" : "Pārtraukt braukš.žurn. ierakstu",
    "DeleteButton" : "Dzēst",
    "BackButton" : "Atpakaļ",
    "ClearButton" : "Notīrīt",
    "RetryButton" : "Atkārtot",
    "CancelButton" : "Atcelt",
    "USBTransferTitle" : "USB datu pārsūtīšana",
    "ClearAllData" : "Notīrīt visus datus",
    "SelectCopyData" : "Kopēt datus USB",
    "ConfirmClearAllDataDialogText" : "Vai esat pārliecināts, ka vēlaties dzēst visus datus?",
    "ClearDataRetryDialogText" : "Nevar notīrīt visus datus. Vai vēlaties mēģināt vēlreiz?",
    "SendDataRetryDialogText" : "Nevar kopēt datus USB. Vai vēlaties mēģināt vēlreiz?",
    "ConfirmCleariDMDataDialogText" : "Vai vēlaties dzēst atlasīto braukšanas žurnālu?",
    "USBMemoryFullDialogText" : "Nevar kopēt datus USB. USB atmiņa ir pilna. Vai vēlaties mēģināt vēlreiz?",
    "InsertUSBDialogText" : "Nevar kopēt datus USB. Ievietojiet USB dzini un mēģiniet vēlreiz.",
    "ClearDataSuccess" : "Veiksmīga datu notīrīšana",
    "ClearDataFailure" : "Datus nevar notīrīt",
    "CopyDataSuccess" : "Datu kopēšanas USB veiksmīga",
    "CopyDataFailure" : "Datus nevar kopēt",
    "CopyDataFailureUSBFull" : "USB Atmiņa pilna",
    "CopyDataFailureUSBRemoved" : "Ievietot USB dzini",
    "ProtectionErrorDialogText" : "Atļauts tikai 1 aizsargāts fails uz vienu draivera ID. Izdzēst failu vai izslēgt aizsardzību.",
    "CopyingDialogText1" : "Notiek datu kopēšana USB atmiņā. Neizņemiet USB atmiņu vai neizslēdziet automašīnu.",
    "CopyingDialogText2" : "Pārsūtīti {noOfFilesCopied} faili no {totalFiles}.",
};

framework.registerAppDictLoaded("vdt", "lv_LV");